Repository PrestaShop/PrestaShop, pull requests merged in 2018-11, with the labels that each got.

#11239 Do not install Addons modules for Test BDD creation
  tests/PrestaShopBundle/Utils/DatabaseCreator.php
Labels: 1.7.5.x, Improvement

#11035 Optimize legacy links in dev mode
  app/config/config_test.yml
  classes/Link.php
  composer.json
  src/PrestaShopBundle/Resources/config/services/bundle/event_listener.yml
  src/PrestaShopBundle/Resources/config/services/bundle/routing.yml
  src/PrestaShopBundle/Routing/Converter/AbstractLegacyRouteProvider.php
  src/PrestaShopBundle/Routing/Converter/CacheKeyGeneratorInterface.php
  src/PrestaShopBundle/Routing/Converter/CacheProvider.php
  src/PrestaShopBundle/Routing/Converter/Exception/ArgumentException.php
  src/PrestaShopBundle/Routing/Converter/Exception/RouteNotFoundException.php
  src/PrestaShopBundle/Routing/Converter/Exception/RoutingException.php
  src/PrestaShopBundle/Routing/Converter/LegacyRoute.php
  src/PrestaShopBundle/Routing/Converter/LegacyRouteProviderInterface.php
  src/PrestaShopBundle/Routing/Converter/LegacyUrlConverter.php
  src/PrestaShopBundle/Routing/Converter/RouterProvider.php
  src/PrestaShopBundle/Routing/Converter/RoutingCacheKeyGenerator.php
  src/PrestaShopBundle/Routing/LegacyUrlConverter.php
  tests/Integration/PrestaShopBundle/Routing/Converter/LegacyUrlConverterTest.php
  tests/PrestaShopBundle/Routing/Converter/CacheProviderTest.php
  tests/PrestaShopBundle/Routing/Converter/LegacyRouteTest.php
  tests/PrestaShopBundle/Routing/Converter/LegacyUrlConverterTest.php
  tests/PrestaShopBundle/Routing/Converter/RouterProviderTest.php
  tests/PrestaShopBundle/Routing/Converter/RoutingCacheKeyGeneratorTest.php
  tests/check_phpunit.sh
  tests/phpunit-routing.xml
  tests/phpunit.xml
Labels: 1.7.5.x, Improvement, QA ✔️

#10446 Increase max size of reference, meta_title, meta_description email, password, firstname, lastname and company.
  app/Resources/translations/default/ShopNotificationsError.xlf
  classes/CMS.php
  classes/CMSCategory.php
  classes/Category.php
  classes/Combination.php
  classes/Contact.php
  classes/Customer.php
  classes/CustomerThread.php
  classes/Employee.php
  classes/Mail.php
  classes/Manufacturer.php
  classes/Product.php
  classes/ProductSupplier.php
  classes/Referrer.php
  classes/Store.php
  classes/Supplier.php
  classes/form/CustomerForm.php
  classes/stock/Warehouse.php
  controllers/admin/AdminAddressesController.php
  controllers/admin/AdminCategoriesController.php
  controllers/admin/AdminCmsController.php
  controllers/admin/AdminContactsController.php
  controllers/admin/AdminCustomersController.php
  controllers/admin/AdminEmployeesController.php
  controllers/admin/AdminGroupsController.php
  controllers/admin/AdminManufacturersController.php
  install-dev/data/db_structure.sql
  install-dev/upgrade/sql/1.7.5.0.sql
Labels: 1.7.5.x, Bug, Improvement, QA ✔️

#11237 Improved survival tests
  tests/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
Labels: Improvement, develop

#11249 Fix declaration of method arguments
  classes/Cart.php
Labels: Improvement, develop

#11058 Add Hindi, Mexican & Bosnian languages
  app/Resources/all_languages.json
  app/Resources/legacy-to-standard-locales.json
  install-dev/langs/bs/data/cms.xml
  install-dev/langs/bs/data/index.php
  install-dev/langs/bs/flag.jpg
  install-dev/langs/bs/img/bs-default-category.jpg
  install-dev/langs/bs/img/bs-default-home.jpg
  install-dev/langs/bs/img/bs-default-large.jpg
  install-dev/langs/bs/img/bs-default-large_scene.jpg
  install-dev/langs/bs/img/bs-default-medium.jpg
  install-dev/langs/bs/img/bs-default-small.jpg
  install-dev/langs/bs/img/bs-default-thickbox.jpg
  install-dev/langs/bs/img/bs-default-thumb_scene.jpg
  install-dev/langs/bs/img/bs.jpg
  install-dev/langs/bs/img/index.php
  install-dev/langs/bs/index.php
  install-dev/langs/bs/language.xml
  install-dev/langs/hi/data/cms.xml
  install-dev/langs/hi/data/index.php
  install-dev/langs/hi/flag.jpg
  install-dev/langs/hi/img/hi-default-category.jpg
  install-dev/langs/hi/img/hi-default-home.jpg
  install-dev/langs/hi/img/hi-default-large.jpg
  install-dev/langs/hi/img/hi-default-large_scene.jpg
  install-dev/langs/hi/img/hi-default-medium.jpg
  install-dev/langs/hi/img/hi-default-small.jpg
  install-dev/langs/hi/img/hi-default-thickbox.jpg
  install-dev/langs/hi/img/hi-default-thumb_scene.jpg
  install-dev/langs/hi/img/hi.jpg
  install-dev/langs/hi/img/index.php
  install-dev/langs/hi/index.php
  install-dev/langs/hi/language.xml
  install-dev/langs/mx/data/cms.xml
  install-dev/langs/mx/data/index.php
  install-dev/langs/mx/flag.jpg
  install-dev/langs/mx/img/index.php
  install-dev/langs/mx/img/mx-default-category.jpg
  install-dev/langs/mx/img/mx-default-home.jpg
  install-dev/langs/mx/img/mx-default-large.jpg
  install-dev/langs/mx/img/mx-default-large_scene.jpg
  install-dev/langs/mx/img/mx-default-medium.jpg
  install-dev/langs/mx/img/mx-default-small.jpg
  install-dev/langs/mx/img/mx-default-thickbox.jpg
  install-dev/langs/mx/img/mx-default-thumb_scene.jpg
  install-dev/langs/mx/img/mx.jpg
  install-dev/langs/mx/index.php
  install-dev/langs/mx/language.xml
Labels: 1.7.5.x, Improvement, QA ✔️

#11179 Fix sorting issue in the webservice page
  controllers/admin/AdminWebserviceController.php
Labels: Bug, QA ✔️, develop

#11215 Fix 11211: Removing inline-style of color in test-data
  install-dev/fixtures/fashion/langs/bn/data/product.xml
  install-dev/fixtures/fashion/langs/br/data/product.xml
  install-dev/fixtures/fashion/langs/de/data/product.xml
  install-dev/fixtures/fashion/langs/en/data/category.xml
  install-dev/fixtures/fashion/langs/en/data/product.xml
  install-dev/fixtures/fashion/langs/es/data/product.xml
  install-dev/fixtures/fashion/langs/fa/data/category.xml
  install-dev/fixtures/fashion/langs/fa/data/product.xml
  install-dev/fixtures/fashion/langs/fr/data/category.xml
  install-dev/fixtures/fashion/langs/fr/data/product.xml
  install-dev/fixtures/fashion/langs/id/data/product.xml
  install-dev/fixtures/fashion/langs/it/data/product.xml
  install-dev/fixtures/fashion/langs/nl/data/product.xml
  install-dev/fixtures/fashion/langs/pl/data/product.xml
  install-dev/fixtures/fashion/langs/qc/data/product.xml
  install-dev/fixtures/fashion/langs/ro/data/product.xml
  install-dev/fixtures/fashion/langs/ru/data/product.xml
  install-dev/fixtures/fashion/langs/tw/data/product.xml
  install-dev/fixtures/fashion/langs/vn/data/product.xml
  install-dev/fixtures/fashion/langs/zh/data/product.xml
Labels: Improvement, QA ✔️, develop

#11133 Removed inline-style of color in demo product desciption of "Hummingbi…
  install-dev/fixtures/fashion/langs/bn/data/product.xml
Labels: Improvement, develop

#11070 Feature/module manager categories
  app/Resources/translations/default/AdminModulesFeature.xlf
  app/config/addons/categories.yml
  app/config/config.yml
  src/Core/Addon/Module/ModuleManagerBuilder.php
  src/PrestaShopBundle/DependencyInjection/AddOnsConfiguration.php
  src/PrestaShopBundle/DependencyInjection/PrestaShopExtension.php
  src/PrestaShopBundle/Resources/config/services/adapter/data_provider.yml
  src/PrestaShopBundle/Service/DataProvider/Admin/CategoriesProvider.php
Labels: 1.7.5.x, Improvement, QA ✔️

#9316 Fix Cart::autoAddToCart using undefined customer when called from BO
  classes/CartRule.php
Labels: 1.7.5.x, Bug, QA ✔️

#9132 extra field hook added on customer address form
  classes/form/CustomerAddressFormatter.php
Labels: Feature, QA ✔️, develop

#11246 Fix 10962: Replace deprecated library PhpExcel by PhpSpreadsheet
  composer.json
  composer.lock
  controllers/admin/AdminImportController.php
  src/Adapter/Converter/ExcelToCsvFileConverter.php
Labels: Improvement, QA ✔️, develop

#10904 [BO] Fix date filtering in AdminSpecificPriceRuleController
  controllers/admin/AdminSpecificPriceRuleController.php
Labels: Bug, Needs port on StarterTheme, QA ✔️, develop

#11285 Fix filemanager security breaches
  admin-dev/filemanager/ajax_calls.php
  admin-dev/filemanager/config/config.php
  admin-dev/filemanager/execute.php
  admin-dev/filemanager/include/utils.php
  admin-dev/filemanager/upload.php
  composer.json
  composer.lock
  config/autoload.php
  install-dev/install_version.php
Labels: 1.7.4.x, Bug

#11286 Fix filemanager security breaches
  admin-dev/filemanager/ajax_calls.php
  admin-dev/filemanager/config/config.php
  admin-dev/filemanager/execute.php
  admin-dev/filemanager/include/utils.php
  admin-dev/filemanager/upload.php
  install-dev/install_version.php
Labels: 1.6.1.x, Bug

#11228 Avoid warning in WebServiceRequest
  classes/webservice/WebserviceRequest.php
Labels: 1.7.4.x, Bug

#11266 $this->fetch() can return content in BO context
  classes/Smarty/SmartyResourceModule.php
Labels: Improvement, QA ✔️, develop

#11214 Handles bad address usecase for Carrier Tax Rate
  classes/Carrier.php
Labels: Bug, QA ✔️, develop

#11287 Fix filemanager security breaches
  admin-dev/filemanager/ajax_calls.php
  admin-dev/filemanager/config/config.php
  admin-dev/filemanager/execute.php
  admin-dev/filemanager/include/utils.php
  admin-dev/filemanager/upload.php
  composer.json
Labels: 1.7.5.x, Bug

#11306 Fix linter jobs of Travis
  classes/form/CustomerAddressFormatter.php
Labels: Bug, develop

#11300 Fix error on tab unregistration when handled by the module
  src/Adapter/Module/Tab/ModuleTabUnregister.php
Labels: 1.7.5.x, Bug, QA ✔️

#11184 Advanced localization
  tests/E2E/test/campaigns/common_scenarios/localization.js
  tests/E2E/test/campaigns/full/11_international/1_localization/1_localization/4_advanced.js
  tests/E2E/test/selectors/BO/international/localization.js
Labels: Feature, QA ✔️, TE, develop

#10197 Added a schema generator
  tools/build/Library/ReleaseCreator.php
  tools/foreignkeyGenerator/README.md
  tools/foreignkeyGenerator/changes.php
  tools/foreignkeyGenerator/foreign.php
  tools/foreignkeyGenerator/relations.php
Labels: Feature, develop

#11095 Introduces grid design update regarding grid wheel icon position and dropdown toggle icon modification
  admin-dev/themes/new-theme/js/components/grid/extension/export-to-sql-manager-extension.js
  admin-dev/themes/new-theme/js/components/grid/extension/reload-list-extension.js
  admin-dev/themes/new-theme/js/components/grid/grid.js
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/catalog_product.bundle.js
  admin-dev/themes/new-theme/public/categories.bundle.js
  admin-dev/themes/new-theme/public/contacts.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/employee.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/imports_data.bundle.js
  admin-dev/themes/new-theme/public/improve_design_positions.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/meta.bundle.js
  admin-dev/themes/new-theme/public/module.bundle.js
  admin-dev/themes/new-theme/public/module_card.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/translation_settings.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
  admin-dev/themes/new-theme/scss/components/_button_groups.scss
  admin-dev/themes/new-theme/scss/components/_cards.scss
  admin-dev/themes/new-theme/scss/theme.scss
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/action.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/grid.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/grid_panel.html.twig
Labels: Improvement, QA ✔️, develop, migration

#11312 Prevent short description limit to be set at 0
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/ProductPreferencesFormDataProvider.php
Labels: 1.7.5.x, Bug, QA ✔️

#11337 Show more logs in admin
  src/PrestaShopBundle/Entity/Repository/LogRepository.php
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/employee_name_with_avatar.html.twig
Labels: 1.7.5.x, Bug, QA ✔️, waiting for wording

#11160 Form handling improvements in import page step 1 and 2
  src/Adapter/Import/DataMatchSaver.php
  src/Core/Import/Configuration/ImportConfig.php
  src/Core/Import/Configuration/ImportConfigFactory.php
  src/Core/Import/Configuration/ImportConfigFactoryInterface.php
  src/Core/Import/Configuration/ImportConfigInterface.php
  src/Core/Import/Configuration/ImportDataMatchConfiguration.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ImportController.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Import/ImportDataConfigurationFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Import/ImportFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Import/ImportFormDataProviderInterface.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Import/ImportFormHandler.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Import/ImportFormHandlerInterface.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/import.yml
  src/PrestaShopBundle/Resources/config/services/adapter/data_configuration.yml
  src/PrestaShopBundle/Resources/config/services/adapter/import.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_builder.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_handler.yml
  src/PrestaShopBundle/Resources/config/services/core/import.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/ImportPage/Blocks/import_data_configuration.html.twig
Labels: Improvement, develop, migration

#11311 Be able to disable Help Link on Back Office pages
  admin-dev/themes/new-theme/template/page_header_toolbar.tpl
  controllers/admin/AdminLegacyLayoutController.php
Labels: 1.7.5.x, Bug, QA ✔️

#11384 Add an rtlfix file to correctly hide the right side bar in rtl languages
  admin-dev/themes/new-theme/public/theme.rtlfix
Labels: 1.7.5.x, Bug, QA ✔️

#11385 Fix missing dot in wording
  app/Resources/translations/default/AdminNotificationsError.xlf
  app/Resources/translations/default/messages.xlf
  src/PrestaShopBundle/Controller/Admin/Improve/Shipping/PreferencesController.php
Labels: 1.7.5.x, Bug, Wording ✔️

#11357 Improve install warning message for beta builds
  tools/build/Library/InstallUnpacker/classes/Download.php
  tools/build/Library/InstallUnpacker/classes/InstallManager.php
  tools/build/Library/InstallUnpacker/index_template.php
Labels: 1.7.5.x, Improvement, QA ✔️

#11394 Fix crashing for bulk actions
  admin-dev/themes/new-theme/js/pages/email/index.js
  admin-dev/themes/new-theme/js/pages/webservice/index.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
  src/Core/Grid/Definition/Factory/AbstractGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/BackupDefinitionFactory.php
  src/Core/Grid/Definition/Factory/EmailLogsDefinitionFactory.php
  src/Core/Grid/Definition/Factory/LogGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/MetaGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/RequestSqlGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/WebserviceKeyDefinitionFactory.php
  src/Core/Grid/Presenter/GridPresenter.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmailController.php
  tests/Unit/Core/Grid/Definition/Factory/AbstractGridDefinitionFactoryTest.php
Labels: 1.7.5.x, Bug, QA ✔️

#11407 Module manager sorting
  admin-dev/themes/new-theme/js/pages/module/controller.js
  admin-dev/themes/new-theme/public/module.bundle.js
Labels: 1.7.5.x, Bug, QA ✔️

#11309 Add LegacyContext::getLegacyAdminLink
  classes/Link.php
  src/Adapter/LegacyContext.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ImportController.php
Labels: 1.7.5.x, Bug, QA ✔️

#11410 Changing primary domain name no longer reindexes simplified URLs
  src/Adapter/Meta/ShopUrlDataConfiguration.php
  src/PrestaShopBundle/Resources/config/services/adapter/data_configuration.yml
Labels: 1.7.5.x, Bug, QA ✔️

#11376 Some strings need to be escaped
  install-dev/theme/views/process.php
  src/Adapter/Meta/ShopUrlDataConfiguration.php
Labels: 1.7.5.x, Bug, QA ✔️

#11421 Display configure button only if module is configurable
  src/PrestaShopBundle/Resources/views/Admin/Improve/Payment/PaymentMethods/Blocks/payment_modules_list.html.twig
Labels: 1.7.5.x, Bug, QA ✔️

#11280 Add some fixes to the script
  tests/E2E/test/campaigns/common_scenarios/file.js
  tests/E2E/test/campaigns/common_scenarios/shop_parameters.js
  tests/E2E/test/campaigns/full/10_module/8_read_more_module.js
  tests/E2E/test/campaigns/high/08_stocks/1_group_of_product_quantity.js
  tests/E2E/test/campaigns/high/12_shop_parameters/3_onboarding.js
  tests/E2E/test/clients/onboarding.js
  tests/E2E/test/selectors/BO/menu.js
Labels: 1.7.5.x, QA ✔️, Refactoring, TE

#11419 Noto Sans fonts updated to version 2.001 hinted
  themes/classic/assets/css/154da4697acc779b55af0a67f1241e4e.ttf
  themes/classic/assets/css/199038f07312bfc6f0aabd3ed6a2b64d.woff2
  themes/classic/assets/css/19c1b868764c0e4d15a45d3f61250488.woff2
  themes/classic/assets/css/2fd9c16b805724d590c0cff96da070a4.ttf
  themes/classic/assets/css/332f555bb44cdc394d6c799df0c03389.woff
  themes/classic/assets/css/3d34be670a7f15086e512282b97ae35e.svg
  themes/classic/assets/css/3d4a907b1b7a232654324a3dd7ae4aa3.eot
  themes/classic/assets/css/3f81521029cc8a9a703419c4a74704a0.woff
  themes/classic/assets/css/4f6ff3639c1e5728b905b650c1a06e75.ttf
  themes/classic/assets/css/5dc400bcedda37b13f35cb44623193cf.svg
  themes/classic/assets/css/5ea9fdf2293930126fa9c544968009ae.svg
  themes/classic/assets/css/7a3ebca0cba2e2c6090e84e1d77e0f94.woff2
  themes/classic/assets/css/80e74ff9406650e53bbec1e292c2c094.svg
  themes/classic/assets/css/846c191efd3d0aacde5a916cf2ebf1a4.woff
  themes/classic/assets/css/a165a42685795361b25593effb32fdb1.ttf
  themes/classic/assets/css/a68cfe9d548950edf5df102269877edd.woff2
  themes/classic/assets/css/a77ade19de3d3762dfbf1fe553b293cc.eot
  themes/classic/assets/css/b467416c449eb823029e16347b2ea510.eot
  themes/classic/assets/css/c2183257e7a697769df4200c547551f1.woff
  themes/classic/assets/css/eeb9224f85430652fd070e4e64129aa4.eot
Labels: Bug, QA ✔️, develop, waiting for UX

#11397 add total_shipping_tax_excl , incl in email data
  classes/PaymentModule.php
Labels: Bug, QA ✔️, develop

#11424 Improvement needs on hover of "Ok" button of source code modal on product page
  js/tiny_mce/skins/prestashop/skin.min.css
Labels: Bug, QA ✔️, develop

#11235 Prevent unnecessary Order objects from being created in Admin Orders
  controllers/admin/AdminOrdersController.php
Labels: Improvement, QA ✔️, develop

#11043 CO: Update ambiguous code style
  controllers/front/CategoryController.php
Labels: 1.6.1.x, Refactoring

#11447 Escape everything!
  admin-dev/themes/default/template/controllers/cart_rules/form.tpl
  admin-dev/themes/default/template/controllers/dashboard/helpers/view/view.tpl
  admin-dev/themes/default/template/controllers/shop/helpers/list/list_content.tpl
  admin-dev/themes/default/template/controllers/tabs/helpers/list/list_content.tpl
  admin-dev/themes/default/template/controllers/tax_rules/helpers/list/list_content.tpl
  admin-dev/themes/default/template/helpers/form/form.tpl
  admin-dev/themes/default/template/helpers/list/list_content.tpl
  admin-dev/themes/default/template/layout.tpl
Labels: 1.7.5.x, Bug, QA ✔️

#11236 Add some fixes to the scripts
  tests/E2E/test/campaigns/common_scenarios/customer.js
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/common_scenarios/shop_parameters.js
  tests/E2E/test/campaigns/full/02_product/10_check_product_page_buttons.js
  tests/E2E/test/campaigns/full/02_product/11_options_in_catalog_page.js
  tests/E2E/test/campaigns/full/10_module/5_check_addons_catalog_page.js
  tests/E2E/test/campaigns/high/11_international/translation.js
  tests/E2E/test/campaigns/high/12_shop_parameters/2_open_all_menu_links.js
  tests/E2E/test/campaigns/install_upgrade/02_autoupgrade.js
  tests/E2E/test/clients/product/create_combinations.js
  tests/E2E/test/common.webdriverio.js
  tests/E2E/test/selectors/BO/add_product_page.js
  tests/E2E/test/selectors/BO/installation.js
  tests/E2E/test/selectors/BO/module_page.js
  tests/E2E/test/selectors/BO/onboarding.js
Labels: 1.7.4.x, Refactoring, TE

#11448 Remove useless trad files in install for persian
  classes/Country.php
  install-dev/langs/fa/data/carrier.xml
  install-dev/langs/fa/data/category.xml
  install-dev/langs/fa/data/cms_category.xml
  install-dev/langs/fa/data/configuration.xml
  install-dev/langs/fa/data/contact.xml
  install-dev/langs/fa/data/country.xml
  install-dev/langs/fa/data/gender.xml
  install-dev/langs/fa/data/group.xml
  install-dev/langs/fa/data/meta.xml
  install-dev/langs/fa/data/order_return_state.xml
  install-dev/langs/fa/data/order_state.xml
  install-dev/langs/fa/data/profile.xml
  install-dev/langs/fa/data/quick_access.xml
  install-dev/langs/fa/data/risk.xml
  install-dev/langs/fa/data/stock_mvt_reason.xml
  install-dev/langs/fa/data/supplier_order_state.xml
  install-dev/langs/fa/data/supply_order_state.xml
  install-dev/langs/fa/data/tab.xml
  src/PrestaShopBundle/Install/Install.php
Labels: 1.7.5.x, Bug, QA ✔️

#11463 fix admin translation redirect
  src/Adapter/Translations/TranslationRouteFinder.php
Labels: 1.7.5.x, Bug, QA ✔️

#11279 Allow product ordering on explicit request
  src/Adapter/Product/ListParametersUpdater.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/views/Admin/Helpers/range_inputs.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Blocks/filters.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Lists/list.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Lists/products_table.html.twig
Labels: 1.7.5.x, Bug, QA ✔️

#11256 Fixes error reported in #9687, regarding carrier list in the modal to ...
  controllers/admin/AdminOrdersController.php
Labels: Bug, QA ✔️, develop

#11204 [*] CO : Fixed incorrect comparison when out of stock
  src/Adapter/Presenter/Product/ProductLazyArray.php
Labels: Bug, QA ✔️, develop

#11362 Dont expose Powered-By: Prestashop
  classes/controller/FrontController.php
Labels: Improvement, develop

#11469 Fix SQL update when last_connection_date is null
  classes/Employee.php
Labels: Bug, QA ✔️, develop

#11457 Refactoring filemanager/execute.php
  admin-dev/filemanager/execute.php
  admin-dev/filemanager/upload.php
Labels: 1.7.5.x, QA ✔️, Refactoring

#11478 Changes the redirection url after store update
  controllers/admin/AdminShopUrlController.php
Labels: 1.7.5.x, Bug, QA ✔️

#9312 Check order details (selenium tests)
  tests/E2E/test/campaigns/selenium/order_detail.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/selectors/FO/order_page.js
Labels: Feature, QA ✔️, TE, develop

#10964 Mine dev presta shop branch
  themes/_core/js/product.js
  themes/classic/_dev/package-lock.json
  themes/classic/assets/css/theme.css
  themes/core.js
  themes/core.js.map
  themes/package-lock.json
Labels: 1.7.5.x, Bug, QA ✔️

#11486 Fix layout
  admin-dev/themes/new-theme/css/right-sidebar.css
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/layout/_header_toolbar.scss
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
Labels: 1.7.5.x, Bug, QA ✔️

#11455 Removing unnecessary spaces on header of the checkout page
  themes/classic/_dev/css/components/checkout.scss
  themes/classic/assets/css/154da4697acc779b55af0a67f1241e4e.ttf
  themes/classic/assets/css/199038f07312bfc6f0aabd3ed6a2b64d.woff2
  themes/classic/assets/css/19c1b868764c0e4d15a45d3f61250488.woff2
  themes/classic/assets/css/2fd9c16b805724d590c0cff96da070a4.ttf
  themes/classic/assets/css/332f555bb44cdc394d6c799df0c03389.woff
  themes/classic/assets/css/3d34be670a7f15086e512282b97ae35e.svg
  themes/classic/assets/css/3d4a907b1b7a232654324a3dd7ae4aa3.eot
  themes/classic/assets/css/3f81521029cc8a9a703419c4a74704a0.woff
  themes/classic/assets/css/4f6ff3639c1e5728b905b650c1a06e75.ttf
  themes/classic/assets/css/5dc400bcedda37b13f35cb44623193cf.svg
  themes/classic/assets/css/5ea9fdf2293930126fa9c544968009ae.svg
  themes/classic/assets/css/7a3ebca0cba2e2c6090e84e1d77e0f94.woff2
  themes/classic/assets/css/80e74ff9406650e53bbec1e292c2c094.svg
  themes/classic/assets/css/846c191efd3d0aacde5a916cf2ebf1a4.woff
  themes/classic/assets/css/a165a42685795361b25593effb32fdb1.ttf
  themes/classic/assets/css/a68cfe9d548950edf5df102269877edd.woff2
  themes/classic/assets/css/a77ade19de3d3762dfbf1fe553b293cc.eot
  themes/classic/assets/css/b467416c449eb823029e16347b2ea510.eot
  themes/classic/assets/css/c2183257e7a697769df4200c547551f1.woff
  themes/classic/assets/css/custom_rtl.css
  themes/classic/assets/css/eeb9224f85430652fd070e4e64129aa4.eot
  themes/classic/assets/css/error_rtl.css
  themes/classic/assets/css/theme.css
  themes/classic/assets/css/theme_rtl.css
Labels: Improvement, QA ✔️, UX ✔️, develop

#11475 impossible to change position of products
  admin-dev/themes/default/js/bundle/product/catalog.js
  classes/Product.php
  install-dev/fixtures/fashion/data/category_product.xml
  src/Adapter/Product/AdminProductDataUpdater.php
  src/Adapter/Product/ListParametersUpdater.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Forms/form_products.html.twig
Labels: 1.7.5.x, Bug, QA ✔️

#11510 Polyfill php73
  classes/webservice/WebserviceOutputJSON.php
  classes/webservice/WebserviceRequest.php
  composer.json
  composer.lock
  controllers/admin/AdminSearchController.php
Labels: Improvement, develop

#11508 Escape javascript and html strings
  admin-dev/themes/default/template/header.tpl
  admin-dev/themes/default/template/helpers/form/form.tpl
  admin-dev/themes/default/template/helpers/list/list_header.tpl
Labels: 1.7.5.x, Bug, QA ✔️

#10974 [WIP] Implement form handlers for SqlManager form
  admin-dev/themes/new-theme/js/pages/sql-manager/index.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  src/Core/Form/IdentifiableObject/Builder/FormBuilder.php
  src/Core/Form/IdentifiableObject/Builder/FormBuilderFactory.php
  src/Core/Form/IdentifiableObject/Builder/FormBuilderFactoryInterface.php
  src/Core/Form/IdentifiableObject/Builder/FormBuilderInterface.php
  src/Core/Form/IdentifiableObject/DataHandler/FormDataHandlerInterface.php
  src/Core/Form/IdentifiableObject/DataHandler/SqlRequestFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/FormDataProviderInterface.php
  src/Core/Form/IdentifiableObject/DataProvider/SqlRequestFormDataProvider.php
  src/Core/Form/IdentifiableObject/Handler/FormHandler.php
  src/Core/Form/IdentifiableObject/Handler/FormHandlerFactory.php
  src/Core/Form/IdentifiableObject/Handler/FormHandlerFactoryInterface.php
  src/Core/Form/IdentifiableObject/Handler/FormHandlerInterface.php
  src/Core/Form/IdentifiableObject/Handler/FormHandlerResult.php
  src/Core/Form/IdentifiableObject/Handler/FormHandlerResultInterface.php
  src/Core/Grid/Definition/Factory/RequestSqlGridDefinitionFactory.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SqlManagerController.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/RequestSql/SqlRequestType.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/_advanced_parameters.yml
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/sql_request.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form.yml
  src/PrestaShopBundle/Resources/config/services/core/form/choice_provider.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_handler.yml
  src/PrestaShopBundle/Resources/config/services/core/grid.yml
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/grid_actions.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/RequestSql/Blocks/db_tables_panel.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/RequestSql/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/RequestSql/Blocks/settings_panel.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/RequestSql/create.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/RequestSql/edit.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/RequestSql/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/RequestSql/index.html.twig
  src/PrestaShopBundle/Resources/views/Admin/macros.html.twig
Labels: Feature, develop, migration

#10465 Fixed bug on inc/dec product quantity in cart with vouchers discounts
  classes/Cart.php
Labels: QA ✔️, bug fix, develop

#11282 Convert customization price to current currency
  classes/Product.php
Labels: Bug, QA ✔️, develop

#10859 Fixed keywords disappear from search index
  classes/Product.php
Labels: 1.6.1.x, Bug, QA ✔️

#11192 Correctly call hook for product update in Product class
  classes/Product.php
Labels: Bug, QA ✔️, develop

#11313 only call ntree regeneration at this end of a WS call and optimize regenerateEntireNtree
  classes/Category.php
  classes/webservice/WebserviceRequest.php
Labels: Improvement, QA ✔️, Webservice, develop

#10981 Change BO product list price source for multistore
  src/Adapter/Product/AdminProductDataProvider.php
Labels: Bug, QA ✔️, develop

#9042 Fix controller override
  controllers/admin/AdminAccessController.php
  controllers/admin/AdminCategoriesController.php
  controllers/admin/AdminLegacyLayoutController.php
  controllers/admin/AdminModulesController.php
  controllers/admin/AdminStoresController.php
  controllers/admin/AdminThemesController.php
  controllers/front/AddressController.php
  controllers/front/CartController.php
  controllers/front/GuestTrackingController.php
  controllers/front/OrderConfirmationController.php
  controllers/front/listing/ManufacturerController.php
  controllers/front/listing/SearchController.php
  controllers/front/listing/SupplierController.php
Labels: Bug, QA ✔️, develop

#11103 fix discount display without tax
  classes/Cart.php
  classes/Product.php
  src/Adapter/Presenter/Cart/CartPresenter.php
  src/Adapter/Presenter/Product/ProductLazyArray.php
Labels: Bug, QA ✔️, develop

#11533 Disable oProxyCommand when imap.enable_insecure_rsh does not exists
  classes/Validate.php
  controllers/admin/AdminCustomerThreadsController.php
Labels: 1.7.5.x, Improvement, QA ✔️

#11549 Unable to build tests container
  tests/E2E/.docker/Dockerfile
  tests/E2E/.docker/prestashop/docker_run.sh
Labels: Bug, develop

#9366 Don't display the system step if mandatory requirements are OK
  install-dev/classes/controllerHttp.php
Labels: Bug, QA ✔️, develop

#11531 Fix all miswritten getAdminLink calls in templates
  admin-dev/themes/default/template/controllers/carriers/helpers/list/list_content.tpl
  admin-dev/themes/default/template/controllers/carts/helpers/view/view.tpl
  admin-dev/themes/default/template/controllers/customer_threads/helpers/view/modal.tpl
  admin-dev/themes/default/template/controllers/customer_threads/helpers/view/view.tpl
  admin-dev/themes/default/template/controllers/manufacturers/helpers/view/view.tpl
  admin-dev/themes/default/template/controllers/modules/page_header_toolbar-legacy.tpl
  admin-dev/themes/default/template/controllers/orders/_documents.tpl
  admin-dev/themes/default/template/controllers/orders/_print_pdf_icon.tpl
  admin-dev/themes/default/template/controllers/orders/_shipping.tpl
  admin-dev/themes/default/template/controllers/orders/form.tpl
  admin-dev/themes/default/template/controllers/orders/helpers/view/view.tpl
  admin-dev/themes/default/template/controllers/outstanding/_print_pdf_icon.tpl
  admin-dev/themes/default/template/controllers/shop/helpers/list/list_content.tpl
  admin-dev/themes/default/template/controllers/slip/_print_pdf_icon.tpl
  admin-dev/themes/default/template/controllers/themes/helpers/options/options.tpl
  admin-dev/themes/default/template/header.tpl
  admin-dev/themes/default/template/helpers/list/list_header.tpl
  admin-dev/themes/new-theme/template/components/layout/employee_dropdown.tpl
  classes/controller/AdminController.php
  classes/module/Module.php
  controllers/admin/AdminAddressesController.php
  controllers/admin/AdminAttributesGroupsController.php
  controllers/admin/AdminCarriersController.php
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/positions.html.twig
Labels: 1.7.5.x, Bug, QA ✔️

#11525 Introduce modern unit tests for new test structure
  .travis.yml
  composer.json
  tests-legacy/README.md
  tests/README.md
  tests/Unit/Core/Webservice/ServerRequirementsCheckerTest.php
  tests/Unit/README.md
  tests/Unit/bootstrap.php
  tests/Unit/phpunit.xml
  tests/check_unit.sh
Labels: Refactoring, develop

#11563 Fix typo for "Environment" comment
  docs/server_config/nginx.conf.dist
Labels: Bug, develop, typo fix

#11526 Fix wrong protocol in the File Manager Dialog
  admin-dev/filemanager/dialog.php
Labels: Bug, QA ✔️, develop

#11565 Allow tests high and fix conflicts in file
  tests/E2E/.docker/run-tests.sh
  tests/E2E/test/campaigns/high/02_product/03_create_product_with_combination.js
Labels: Improvement, develop

#11566 Build all the assets using a single command
  admin-dev/themes/default/package.json
  tools/assets/build.sh
Labels: Improvement, develop
