Repository PrestaShop/PrestaShop, pull requests merged in 2018-06, with the labels that each got.

#9151 Fix undefined method trans() when loggin on the marketplace from the module page
  src/PrestaShopBundle/Controller/Admin/AddonsController.php
Labels: 1.7.4.x, QA-approved

#9149 Error with quota fields
  src/Adapter/Upload/UploadQuotaConfiguration.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Administration/UploadQuotaType.php
Labels: 1.7.4.x, QA-approved, bug fix

#9157 State filter in catalog page doesn't work
  src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Lists/products_table.html.twig
Labels: 1.7.4.x, QA-approved, bug fix

#9156 Fix missing security event listeners registration
  src/PrestaShopBundle/Resources/config/services/bundle/event_listener.yml
Labels: develop

#9133 Regression with DatePicker and checkboxes on stock page (catalogue > stock)
  admin-dev/themes/default/js/bundle/product/product-combinations.js
  admin-dev/themes/new-theme/js/app/pages/logs/index.js
  admin-dev/themes/new-theme/js/app/pages/stock/components/header/filters.vue
  admin-dev/themes/new-theme/js/app/utils/datepicker.js
  admin-dev/themes/new-theme/js/app/widgets/ps-checkbox.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-datepicker.vue
  admin-dev/themes/new-theme/js/theme.js
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
Labels: 1.7.4.x, QA-approved, bug fix

#9105 Check if key exists before checking the value
  classes/Cart.php
Labels: QA-approved, To be cherry-picked, bug fix, develop

#9147 Navigate between pages in catalog page
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/full/02_product/15_navigate_between_catalog_pages.js
  tests/E2E/test/campaigns/high/02_product/7_check_all_products.js
  tests/E2E/test/clients/product/product.js
  tests/E2E/test/selectors/BO/add_product_page.js
Labels: E2E, QA-approved, develop

#9127 Buttons in product page
  tests/E2E/test/campaigns/common_scenarios/shop_parameters.js
  tests/E2E/test/campaigns/full/02_product/10_check_product_page_buttons.js
  tests/E2E/test/selectors/BO/add_product_page.js
Labels: E2E, QA-approved, develop

#8956 Add customization ID to cart ajax response and updateCart event data
  controllers/front/CartController.php
  themes/_core/js/cart.js
Labels: QA-approved, develop, improvement

#8914 Clean Header BO design for merchant
  admin-dev/themes/default/img/trophy.png
  admin-dev/themes/default/public/theme.css
  admin-dev/themes/default/sass/modules/_mixins.sass
  admin-dev/themes/default/sass/modules/_variables.sass
  admin-dev/themes/default/sass/partials/_content.sass
  admin-dev/themes/default/sass/partials/_header.sass
  admin-dev/themes/default/sass/partials/_multistore.sass
  admin-dev/themes/default/sass/partials/_nav.sass
  admin-dev/themes/default/sass/partials/_toolbar.sass
  admin-dev/themes/default/sass/vendor/bootstrap-sass/_navbar.scss
  admin-dev/themes/default/template/header.tpl
  admin-dev/themes/default/template/helpers/shops_list/list.tpl
  admin-dev/themes/default/template/search_form.tpl
  admin-dev/themes/new-theme/js/nav_bar.js
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/scss/components/_notifications.scss
  admin-dev/themes/new-theme/scss/components/layout/_header_toolbar.scss
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
  admin-dev/themes/new-theme/scss/components/layout/_nav_bar.scss
  admin-dev/themes/new-theme/scss/config/_settings.scss
  admin-dev/themes/new-theme/scss/mixins/_breakpoints.scss
  admin-dev/themes/new-theme/scss/mixins/_notification_container.scss
  admin-dev/themes/new-theme/scss/mixins/_notification_counter.scss
  admin-dev/themes/new-theme/scss/theme.scss
  admin-dev/themes/new-theme/template/components/layout/employee_dropdown.tpl
  admin-dev/themes/new-theme/template/components/layout/notifications_center.tpl
  admin-dev/themes/new-theme/template/components/layout/shop_list.tpl
  admin-dev/themes/new-theme/template/layout.tpl
  tests/E2E/test/selectors/BO/shopParameters/shop_parameters.js
Labels: 1.7.4.x, QA-approved, improvement

#9160 Fix 500 while getting order total
  classes/Cart.php
Labels: 1.7.4.x, QA-approved, bug fix

#9126 Control if customer is the owner of the selected order in contact form
  controllers/front/ContactController.php
Labels: 1.6.1.x, QA-approved, bug fix

#9167 Update native module versions
  composer.json
  composer.lock
Labels: 1.7.4.x

#9128 index.php file for controllers/front/listing/
  controllers/front/listing/index.php
Labels: develop, improvement

#9170 Fix smarty condition count
  admin-dev/themes/default/template/controllers/cart_rules/conditions.tpl
Labels: QA-approved, develop

#9154 Migrate Theme Catalog Page of Design Section
  admin-dev/themes/default/template/controllers/themes_catalog/content.tpl
  classes/Link.php
  controllers/admin/AdminThemesCatalogController.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeCatalogController.php
  src/PrestaShopBundle/Resources/config/routing/admin/routing_theme.yml
  src/PrestaShopBundle/Resources/config/routing/routing_admin.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/ThemesCatalogPage/addons_store.html.twig
  tests/PrestaShopBundle/Controller/ControllerTest.php
Labels: QA-approved, develop, feature

#9169 fix product attachment list
  admin-dev/themes/default/template/controllers/attachments/helpers/list/list_action_delete.tpl
Labels: 1.7.4.x, QA-approved, bug fix

#9177 Update scripts on 1.7.4.x
  tests/E2E/test/campaigns/common_scenarios/feature.js
  tests/E2E/test/campaigns/common_scenarios/module.js
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/common_scenarios/stock.js
  tests/E2E/test/campaigns/common_scenarios/taxes.js
  tests/E2E/test/campaigns/full/02_product/10_check_product_page_buttons.js
  tests/E2E/test/campaigns/full/02_product/11_options_in_catalog_page.js
  tests/E2E/test/campaigns/full/02_product/12_check_tinymce_field_in_BO.js
  tests/E2E/test/campaigns/full/02_product/13_delete_product.js
  tests/E2E/test/campaigns/full/02_product/14_check_pagination_of_product_in_FO.js
  tests/E2E/test/campaigns/full/10_module/5_check_addons_catalog_page.js
  tests/E2E/test/campaigns/full/10_module/7_discover_module.js
  tests/E2E/test/campaigns/full/14_discount/2_check_catalog_rule_price.js
  tests/E2E/test/campaigns/full/14_discount/3_check_discount_in_FO.js
  tests/E2E/test/campaigns/full/14_discount/5_check_discount_table_in_FO.js
  tests/E2E/test/campaigns/full/15_design/1_theme_and_logo/1_check_addons_theme.js
  tests/E2E/test/campaigns/high/01_orders/2_create_order_in_FO.js
  tests/E2E/test/campaigns/high/02_product/1_create_standard_product.js
  tests/E2E/test/campaigns/high/02_product/2_create_pack_of_product.js
  tests/E2E/test/campaigns/high/02_product/3_create_product_with_combination.js
  tests/E2E/test/campaigns/high/02_product/4_create_virtual_product.js
  tests/E2E/test/campaigns/high/02_product/8_sort_product.js
  tests/E2E/test/campaigns/high/02_product/9_check_shopping_cart.js
  tests/E2E/test/campaigns/high/08_stocks/1_group_of_product_quantity.js
  tests/E2E/test/campaigns/high/08_stocks/2_single_product_quantity.js
  tests/E2E/test/campaigns/high/08_stocks/3_check_order_movement.js
  tests/E2E/test/campaigns/high/10_module/1_Zip_module.js
  tests/E2E/test/campaigns/high/10_module/2_cross_selling_module.js
  tests/E2E/test/campaigns/high/10_module/3_search_module.js
  tests/E2E/test/campaigns/high/10_module/4_sort_module.js
  tests/E2E/test/campaigns/high/12_shop_parameters/2_open_all_menu_links.js
  tests/E2E/test/campaigns/install_upgrade/03_rollback.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/discount.js
  tests/E2E/test/clients/onboarding.js
  tests/E2E/test/clients/product/product.js
  tests/E2E/test/clients/stocks.js
  tests/E2E/test/selectors/BO/add_product_page.js
  tests/E2E/test/selectors/BO/catalogpage/Manufacturers/brands.js
  tests/E2E/test/selectors/BO/catalogpage/feature_submenu.js
  tests/E2E/test/selectors/BO/catalogpage/index.js
  tests/E2E/test/selectors/BO/catalogpage/stocksubmenu/movements.js
  tests/E2E/test/selectors/BO/catalogpage/stocksubmenu/stock.js
  tests/E2E/test/selectors/BO/design/index.js
  tests/E2E/test/selectors/BO/design/theme_and_logo.js
  tests/E2E/test/selectors/BO/design/theme_catalog.js
  tests/E2E/test/selectors/BO/international/translations.js
  tests/E2E/test/selectors/BO/menu.js
  tests/E2E/test/selectors/BO/module_page.js
  tests/E2E/test/selectors/BO/pages_form.js
  tests/E2E/test/selectors/BO/shopParameters/shop_parameters.js
Labels: 1.7.4.x, E2E

#9175 Missing requirement message
  src/Adapter/Requirement/CheckRequirements.php
Labels: 1.7.4.x, QA-approved, bug fix

#9181 Use CustomerPreferencesFormHandler to handle specific tabs toggling for B2B mode
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/CustomerPreferences/CustomerPreferencesFormHandler.php
  src/PrestaShopBundle/Resources/config/services/form/form_handler.yml
Labels: 1.7.4.x, QA-approved, bug fix

#9173 Registered all namespaces in ModuleTemplateLoader class
  src/PrestaShopBundle/Resources/config/services/services.yml
  src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Lists/list.html.twig
  src/PrestaShopBundle/Twig/Locator/ModuleTemplateLoader.php
  tests/PrestaShopBundle/Twig/Fixtures/module1/views/PrestaShop/Admin/Product/test.html.twig
  tests/PrestaShopBundle/Twig/Fixtures/module2/views/PrestaShop/test.html.twig
  tests/PrestaShopBundle/Twig/Fixtures/module3/views/PrestaShop/Admin/Product/ProductPage/Lists/list.html.twig
  tests/PrestaShopBundle/Twig/Fixtures/module3/views/PrestaShop/Admin/Product/test.html.twig
  tests/PrestaShopBundle/Twig/Locator/ModuleTemplateLoaderTest.php
Labels: 1.7.4.x, QA-approved, bug fix

#9183 restore missing translation keys
  classes/lang/KeysReference/AttributeGroupLang.php
  classes/lang/KeysReference/AttributeLang.php
  classes/lang/KeysReference/CarrierLang.php
  classes/lang/KeysReference/CategoryLang.php
  classes/lang/KeysReference/CmsCategoryLang.php
  classes/lang/KeysReference/ConfigurationLang.php
  classes/lang/KeysReference/ContactLang.php
  classes/lang/KeysReference/FeatureLang.php
  classes/lang/KeysReference/FeatureValueLang.php
  classes/lang/KeysReference/GenderLang.php
  classes/lang/KeysReference/GroupLang.php
  classes/lang/KeysReference/MetaLang.php
  classes/lang/KeysReference/OrderMessageLang.php
  classes/lang/KeysReference/OrderReturnStateLang.php
  classes/lang/KeysReference/OrderStateLang.php
  classes/lang/KeysReference/ProfileLang.php
  classes/lang/KeysReference/QuickAccessLang.php
  classes/lang/KeysReference/README.md
  classes/lang/KeysReference/RiskLang.php
  classes/lang/KeysReference/StockMvtReasonLang.php
  classes/lang/KeysReference/SupplyOrderStateLang.php
  classes/lang/KeysReference/TabLang.php
  classes/lang/KeysReference/ThemeLang.php
Labels: 1.7.4.x

#8724 PHP 7.2 compat - Fix fatal error
  controllers/admin/AdminLoginController.php
  controllers/admin/AdminNotFoundController.php
  controllers/admin/AdminPatternsController.php
Labels: 1.6.1.x, bug fix

#9189 Hide disabled level 3 tabs in the BO
  admin-dev/themes/default/template/page_header_toolbar.tpl
  admin-dev/themes/new-theme/template/page_header_toolbar.tpl
Labels: 1.7.4.x, QA-approved

#9188 Fix wrong test in left join condition
  classes/ProductAssembler.php
Labels: QA-approved

#9190 Fixed DataConfigurationInterface PHPDoc
  src/Core/Configuration/DataConfigurationInterface.php
Labels: bug fix, develop

#9150 Add dockerfile for single container run of E2E
  tests/E2E/Dockerfile
  tests/E2E/README.md
  tests/E2E/docker-compose.yml
  tests/E2E/docker-files/npm-warmup.sh
  tests/E2E/docker-files/run-tests.sh
  tests/E2E/docker_prestashop/Dockerfile
  tests/E2E/docker_prestashop/wait-for-it.sh
Labels: develop, feature

#9066 Refactor Dispatcher::useDefaultController()
  classes/Dispatcher.php
  classes/Employee.php
Labels: develop, improvement

#9197 Fix duplicate wording
  app/Resources/translations/default/AdminNotificationsError.xlf
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/ProductPreferencesController.php
Labels: 1.7.4.x

#9196 Fix wrong translation domain
  app/Resources/translations/default/AdminGlobalError.xlf
  app/Resources/translations/default/AdminNotificationsError.xlf
  src/PrestaShopBundle/Controller/Admin/ProductController.php
Labels: 1.7.4.x

#9198 Add use statement for AppKernel
  src/Adapter/Shop/ShopInformation.php
Labels: bug fix, develop

#9141 Use https no http employee class
  classes/Employee.php
Labels: 1.6.1.x, QA-approved, improvement

#9200 Fix duplicate wording
  admin-dev/themes/default/template/controllers/import/helpers/form/form.tpl
  app/Resources/translations/default/AdminAdvparametersHelp.xlf
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Blocks/import_panel.html.twig
Labels: 1.7.4.x

#9097 Fix phone fieldtype
  classes/form/CustomerAddressFormatter.php
Labels: QA-approved, develop, improvement

#9192 Migrate Payment methods page
  classes/Link.php
  controllers/admin/AdminPaymentController.php
  src/Adapter/Module/Presenter/PaymentModulesPresenter.php
  src/Adapter/Module/TabModuleListProvider.php
  src/Adapter/Shop/Context.php
  src/Core/Addon/Module/ModuleRepository.php
  src/Core/Module/DataProvider/TabModuleListProviderInterface.php
  src/PrestaShopBundle/Controller/Admin/Improve/Payment/PaymentMethodsController.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/_improve.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/payment/payment_methods.yml
  src/PrestaShopBundle/Resources/config/routing/routing_admin.yml
  src/PrestaShopBundle/Resources/config/services/adapter/module.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/Payment/PaymentMethods/Blocks/payment_modules_list.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Payment/PaymentMethods/payment_methods.html.twig
Labels: QA-approved, develop, feature

#9131 Add export shopping carts scenario
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/campaigns/full/01_orders/6_export_shopping_carts.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/order.js
  tests/E2E/test/selectors/BO/order.js
Labels: E2E, develop, waiting for rebase

#9195 Fixed mixed up display in some cases at partial refunds
  admin-dev/themes/default/template/controllers/orders/_product_line.tpl
Labels: QA-approved, bug fix, develop

#9204 Remove leftover routing files
  src/PrestaShopBundle/Resources/config/routing/admin/routing_order.yml
  src/PrestaShopBundle/Resources/config/routing/routing_admin.yml
Labels: develop, improvement

#9202 Preserve position in category when adding a new Product using Web services
  classes/Product.php
Labels: QA-approved, bug fix, develop

#9194 Handle 1.7 method in update function 'add_new_tab'
  install-dev/upgrade/php/add_new_tab.php
  install-dev/upgrade/php/ps_1740_update_module_tabs.php
Labels: 1.7.4.x, QA-approved

#9210 BO: Duplicate array keys
  controllers/admin/AdminCurrenciesController.php
Labels: develop

#9209 CO: Callable calls in loops, repetitive calls.
  src/PrestaShopBundle/Form/Admin/Product/ProductPrice.php
Labels: develop, improvement

#9212 Fix position of PrestaShop logo when in RTL
  admin-dev/themes/default/public/theme.rtlfix
  admin-dev/themes/new-theme/public/theme.rtlfix
Labels: 1.7.4.x, QA-approved

#9205 Improve form choice providers
  src/Core/Form/ChoiceProvider/CountryByIdChoiceProvider.php
  src/Core/Form/ChoiceProvider/CurrencyByIdChoiceProvider.php
  src/Core/Form/ChoiceProvider/LanguageByIdChoiceProvider.php
  src/Core/Form/ChoiceProvider/LocalizationPackByIsoCodeChoiceProvider.php
  src/Core/Form/ChoiceProvider/TimezoneByNameChoiceProvider.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Localization/LanguageChoiceProvider.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form.yml
Labels: QA-approved, develop, improvement

#9199 Introduced Survival tests for new modern pages
  classes/Tools.php
  src/Adapter/Currency/CurrencyDataProvider.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/OrderPreferences/GeneralType.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/OrderPreferences/GiftOptionsType.php
  src/PrestaShopBundle/Resources/config/services/adapter/data_provider.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/configuration.yml
  src/PrestaShopBundle/Resources/config/services/core/import.yml
  tests/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
  tests/Integration/PrestaShopBundle/Test/WebTestCase.php
Labels: develop, improvement

#9153 Be able to declare modern controllers in modules
  app/config/config.yml
  app/config/routing.yml
  src/PrestaShopBundle/Resources/config/services.yml
  src/PrestaShopBundle/Resources/config/services/adapter_services.yml
  src/PrestaShopBundle/Resources/config/services/bundle/routing.yml
  src/PrestaShopBundle/Resources/config/services/bundle_services.yml
  src/PrestaShopBundle/Resources/config/services/core_services.yml
  src/PrestaShopBundle/Routing/YamlModuleLoader.php
  tests/Integration/classes/module/ModuleOverrideInstallUninstallTest.php
  tests/PrestaShopBundle/Routing/YamlRoutesInModuleTest.php
  tests/resources/module/demo/README.md
  tests/resources/module/demo/composer.json
  tests/resources/module/demo/config.xml
  tests/resources/module/demo/config/routes.yml
  tests/resources/module/demo/demo.php
  tests/resources/module/demo/logo.gif
  tests/resources/module/demo/src/Controller/Admin/DemoController.php
  tests/resources/module/demo/templates/admin/demo.html.twig
  tests/resources/module/demo/vendor/autoload.php
  tests/resources/module/demo/vendor/composer/ClassLoader.php
  tests/resources/module/demo/vendor/composer/LICENSE
  tests/resources/module/demo/vendor/composer/autoload_classmap.php
  tests/resources/module/demo/vendor/composer/autoload_namespaces.php
  tests/resources/module/demo/vendor/composer/autoload_psr4.php
  tests/resources/module/demo/vendor/composer/autoload_real.php
  tests/resources/module/demo/vendor/composer/autoload_static.php
  tests/resources/module/demo/vendor/composer/installed.json
Labels: QA-approved, develop, feature

#8820 Check price on order page
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/selectors/FO/order_page.js
Labels: E2E, QA-approved, develop

#9214 Fix products pagination without URL rewriting
  classes/controller/FrontController.php
Labels: QA-approved, bug fix, develop

#8827 create, edit, delete and delete with bulk actions address
  tests/E2E/test/campaigns/common_scenarios/addresses.js
  tests/E2E/test/campaigns/common_scenarios/stock.js
  tests/E2E/test/campaigns/full/09_customer/addresses/create_edit_delete_address.js
  tests/E2E/test/campaigns/high/09_customer/2_create_address.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/customer.js
  tests/E2E/test/selectors/BO/customers/addresses.js
  tests/E2E/test/selectors/BO/customers/index.js
  tests/E2E/test/selectors/FO/access_page.js
Labels: E2E, QA-approved, develop

#9215 Adapted module URLs for new routing
  admin-dev/themes/default/js/bundle/module/module.js
  src/PrestaShopBundle/Resources/views/Admin/Module/catalog.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/common.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/manage.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/notifications.html.twig
Labels: QA-approved, bug fix, develop

#9218 Improve cookie encryption
  classes/Blowfish.php
  classes/Cookie.php
  classes/Rijndael.php
  controllers/admin/AdminPerformanceController.php
Labels: 1.6.1.x, QA-approved

#9207 CO: array_push calls behaving as $array[] works faster than invoking functions in PHP
  classes/ConfigurationTest.php
  classes/Media.php
  controllers/admin/AdminImportController.php
  controllers/admin/AdminModulesPositionsController.php
  controllers/admin/AdminTranslationsController.php
  controllers/front/CartController.php
  src/PrestaShopBundle/Service/TranslationService.php
  tools/htmlpurifier/HTMLPurifier.standalone.php
Labels: QA-approved, develop, improvement

#9222 Improve cookie encryption
  classes/PhpEncryptionLegacyEngine.php
Labels: 1.7.3.x, QA-approved

#9223 SSL field is only available is accessed using HTTPS protocol
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/General/PreferencesType.php
  src/PrestaShopBundle/Resources/config/services/form/form_type.yml
Labels: 1.7.4.x, bug fix

#9224 Fix undefined property key on Rijndael
  classes/Rijndael.php
Labels: 1.6.1.x, QA-approved

#9219 Update product-prices.tpl
  themes/classic/templates/catalog/_partials/product-prices.tpl
Labels: Needs port on StarterTheme, QA-approved, bug fix, develop

#9227 Add alt tag for images categories
  themes/classic/templates/catalog/listing/category.tpl
Labels: 1.7.4.x, Needs port on StarterTheme, QA-approved

#9216 Make deprecation warnings opt-in
  classes/Tools.php
Labels: 1.7.4.x, QA-approved, bug fix

#8887 Create, edit, delete, view, sort, filter a file
  tests/E2E/test/campaigns/common_scenarios/file.js
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/full/16_file/1_create_edit_delete_file_in_BO.js
  tests/E2E/test/campaigns/full/16_file/2_check_file_in_FO.js
  tests/E2E/test/campaigns/full/16_file/3_sort_filter_file_in_BO.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/file.js
  tests/E2E/test/datas/prestashop_developer_guide.pdf
  tests/E2E/test/selectors/BO/add_product_page.js
  tests/E2E/test/selectors/BO/catalogpage/files.js
  tests/E2E/test/selectors/BO/catalogpage/index.js
  tests/E2E/test/selectors/FO/product_page.js
Labels: E2E, develop

#9138 [FO] Fix notice on brands page
  classes/Manufacturer.php
Labels: 1.7.4.x, QA-approved, bug fix

#9172 Fix auto-remove carrier-specific voucher when changing carrier
  admin-dev/themes/default/template/controllers/cart_rules/conditions.tpl
  classes/Cart.php
  tests/Unit/Core/Cart/AbstractCartTest.php
  tests/Unit/Core/Cart/Calculation/Carrier/AbstractCarrierTest.php
  tests/Unit/Core/Cart/Calculation/Carrier/CarrierTest.php
  tests/Unit/Core/Cart/Calculation/Carrier/CartRulesCarrierSpecificTest.php
  tests/Unit/Core/Cart/Calculation/Carrier/RuleWhenChangingCarrierTest.php
Labels: 1.7.4.x, QA-approved, bug fix

#9203 Fixed bug with friendly URLs and Media Servers
  classes/Tools.php
Labels: QA-approved, bug fix, develop

#9093 Add view shopping carts scenario
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/campaigns/full/01_orders/5_shopping_carts_view.js
  tests/E2E/test/campaigns/high/01_orders/1_create_order_in_BO.js
  tests/E2E/test/campaigns/high/08_stocks/3_check_order_movement.js
  tests/E2E/test/campaigns/regular/04_create_order_in_FO.js
  tests/E2E/test/selectors/BO/order.js
  tests/E2E/test/selectors/FO/add_account_page.js
  tests/E2E/test/selectors/FO/order_page.js
  tests/E2E/test/selectors/FO/product_page.js
Labels: E2E, QA-approved, develop

#8977 Delete shopping carts
  tests/E2E/test/campaigns/full/01_orders/5_delete_shopping_carts.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/selectors/BO/catalogpage/index.js
  tests/E2E/test/selectors/BO/order.js
  tests/E2E/test/selectors/FO/product_page.js
Labels: E2E, QA-approved, develop

#9226 Fixed access to Front Office container from modules
  classes/module/Module.php
Labels: 1.7.4.x, bug fix

#9148 Adding review page check
  tests/E2E/test/campaigns/common_scenarios/pages.js
  tests/E2E/test/campaigns/full/15_design/2_pages/1_category.js
  tests/E2E/test/campaigns/full/15_design/2_pages/2_page.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/selectors/BO/design/pages.js
  tests/E2E/test/selectors/FO/access_page.js
Labels: QA-approved, develop, improvement

#9208 CO: glob and scandir without sorting are faster
  admin-dev/filemanager/dialog.php
  admin-dev/filemanager/include/utils.php
  admin-dev/init.php
  classes/Dispatcher.php
  classes/Image.php
  classes/Language.php
  classes/Media.php
  classes/PrestaShopAutoload.php
  classes/Tools.php
  classes/module/Module.php
  classes/webservice/WebserviceSpecificManagementImages.php
  controllers/admin/AdminCategoriesController.php
  controllers/admin/AdminImagesController.php
  controllers/admin/AdminImportController.php
  controllers/admin/AdminInvoicesController.php
  controllers/admin/AdminModulesController.php
  controllers/admin/AdminStatusesController.php
  controllers/admin/AdminThemesController.php
  controllers/admin/AdminTranslationsController.php
  install-dev/controllers/console/process.php
  install-dev/controllers/http/process.php
  install-dev/fixtures/fashion/img/c/resize.php
  install-dev/fixtures/fashion/img/p/resize.php
  install-dev/init.php
  install-dev/upgrade/php/create_multistore.php
  install-dev/upgrade/php/deactivate_custom_modules.php
  install-dev/upgrade/php/move_translations_module_file.php
  install-dev/upgrade/php/p15014_copy_missing_images_tab_from_installer.php
  install-dev/upgrade/php/p15015_blockadvertising_extension.php
  install-dev/upgrade/php/p15018_change_image_types.php
  install-dev/upgrade/php/p1606module_exceptions.php
  install-dev/upgrade/php/updatetabicon_from_11version.php
  src/Core/Addon/Theme/ThemeRepository.php
  src/Core/Cldr/Update.php
  src/PrestaShopBundle/Command/UpdateEUTaxruleGroupsCommand.php
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Install/Upgrade.php
  src/PrestaShopBundle/Install/XmlLoader.php
Labels: QA-approved, develop, improvement

#9233 Updated dependencies
  admin-dev/index.php
  composer.json
  composer.lock
  config/smartyadmin.config.inc.php
  config/smartyfront.config.inc.php
  var/SymfonyRequirements.php
Labels: 1.7.4.x, bug fix, waiting for QA feedback

#9201 Refactor Version class and client code and add unit tests
  src/Core/Foundation/Exception/InvalidVersionException.php
  src/Core/Foundation/Version.php
  src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php
  src/PrestaShopBundle/Controller/Admin/Improve/AddonsStoreController.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeCatalogController.php
  src/PrestaShopBundle/Resources/config/services/bundle/data_collector.yml
  src/PrestaShopBundle/Resources/config/services/bundle/services.yml
  src/PrestaShopBundle/Resources/config/services/core/foundation.yml
  tests/Unit/Core/Foundation/VersionTest.php
Labels: QA-approved, bug fix, develop
