Repository PrestaShop/PrestaShop, pull requests merged in 2018-08, with the labels that each got.

#9320 Phpdocs2
  src/Adapter/AddressFactory.php
  src/Adapter/ClassLang.php
  src/Adapter/CombinationDataProvider.php
  src/Adapter/Configuration.php
  src/Adapter/CoreException.php
  src/Adapter/Database.php
  src/Adapter/EntityMapper.php
  src/Adapter/EntityMetaDataRetriever.php
  src/Adapter/HookManager.php
  src/Adapter/ImageManager.php
  src/Adapter/LegacyLogger.php
  src/Adapter/NewProducts/NewProductsProductSearchProvider.php
  src/Adapter/Order/GeneralConfiguration.php
  src/Adapter/Order/GiftOptionsConfiguration.php
  src/Adapter/Order/Invoice.php
  src/Adapter/Preferences/PreferencesConfiguration.php
  src/Adapter/Presenter/Cart/CartPresenter.php
  src/Adapter/Presenter/Order/OrderReturnLazyArray.php
  src/Adapter/Presenter/Order/OrderReturnPresenter.php
  src/Adapter/Presenter/Order/OrderSubtotalLazyArray.php
  src/Adapter/Presenter/Product/ProductLazyArray.php
  src/Adapter/Presenter/Product/ProductListingLazyArray.php
  src/Adapter/Presenter/Product/ProductListingPresenter.php
  src/Adapter/Presenter/Product/ProductPresenter.php
  src/Adapter/PricesDrop/PricesDropProductSearchProvider.php
  src/Adapter/Product/AdminProductDataProvider.php
  src/Adapter/Product/AdminProductDataUpdater.php
  src/Adapter/Product/AdminProductWrapper.php
  src/Adapter/Product/PackItemsManager.php
  src/Adapter/Product/PriceCalculator.php
  src/Adapter/Product/PriceFormatter.php
  src/Adapter/Product/ProductColorsRetriever.php
  src/Adapter/Requirement/CheckMissingOrUpdatedFiles.php
  src/Adapter/Search/SearchProductSearchProvider.php
  src/Adapter/Security/Admin.php
  src/Adapter/Supplier/SupplierProductSearchProvider.php
  src/Adapter/Tools.php
  src/Adapter/Validate.php
  src/Core/Order/InvoiceInterface.php
Labels: Improvement, develop

#9259 Make PrestaShop fully compatible with Twig 2+
  .travis.yml
  src/Adapter/Presenter/Module/ModulePresenter.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SystemInformationController.php
  src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Blocks/import_panel.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Blocks/import_sample_files.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/LogsPage/logs.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/administration.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/performance.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/customer_preferences_general.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_general.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_page.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_pagination.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_stock.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/OrderPreferences/Blocks/order_preferences_general.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/OrderPreferences/Blocks/order_preferences_gift_options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/maintenance.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/preferences.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Geolocation/Blocks/geolocation_by_ip_address.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Localization/Blocks/advanced_configuration.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Localization/Blocks/configuration.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Localization/Blocks/local_units.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Lists/products_table.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_shipping.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Delivery/slip.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Invoices/Blocks/generate_by_date.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Invoices/Blocks/generate_by_status.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Invoices/Blocks/invoice_options.html.twig
  src/PrestaShopBundle/Twig/AdminExtension.php
  tests/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
Labels: Bug, QA ✔️, develop

#9398 Use HotModuleReplacementPlugin only in dev mode
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/webpack.config.js
Labels: Bug, QA ✔️, develop

#9389 Fixed path to updated files in System Information page
  src/Adapter/Requirement/CheckMissingOrUpdatedFiles.php
Labels: Bug, QA ✔️, develop

#9390 Combination issue while trying to change size on a product page
  classes/Product.php
  controllers/front/CartController.php
  controllers/front/ProductController.php
Labels: Bug, QA ✔️, develop

#9404 Add gsitemap
  composer.json
  composer.lock
  src/PrestaShopBundle/Install/Install.php
Labels: Improvement, QA ✔️, develop

#9244 Fixed Apache Optimization
  src/Adapter/Cache/CombineCompressCacheConfiguration.php
Labels: Bug, QA ✔️, develop

#9399 Fix ajax in 500 in product page
  admin-dev/themes/new-theme/js/product-page/combination.js
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
Labels: Bug, QA ✔️, develop

#9410 Improve grid search and reset buttons
  admin-dev/themes/new-theme/js/components/grid/extension/filters-reset-extension.js
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  src/Core/Grid/Definition/Factory/EmailLogsDefinitionFactory.php
  src/Core/Grid/Definition/Factory/LogGridDefinitionFactory.php
  src/PrestaShopBundle/Form/Admin/Type/SearchAndResetType.php
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
Labels: Improvement, QA ✔️, develop

#9409 Symfony requirements file now compatible with PHP 7.2
  var/SymfonyRequirements.php
Labels: Bug, QA ✔️, develop

#9417 FO: override CustomerAddressForm->submit method more easily
  classes/form/CustomerAddressForm.php
Labels: Improvement, develop

#8690 Improved performance of Product List page
  classes/Access.php
  classes/controller/AdminController.php
  classes/controller/Controller.php
  classes/controller/FrontController.php
  src/Adapter/ContainerBuilder.php
  src/Adapter/Product/AdminProductDataProvider.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/bundle/security.yml
  src/PrestaShopBundle/Resources/config/services/core/cache.yml
  src/PrestaShopBundle/Security/Admin/EmployeeProvider.php
Labels: Improvement, QA ✔️, develop

#9411 Indian Localization improved
  localization/in.xml
Labels: Improvement, QA ✔️, develop

#9424 Issues templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Improvement, develop

#9429 Add formatted field file_size_formatted in attachments
  src/Adapter/Presenter/Product/ProductLazyArray.php
Labels: Bug, QA ✔️, develop

#9446 fix welcome page variable injection by adding missing %
  install-dev/theme/views/welcome.php
Labels: Bug, QA ✔️, develop

#9445 Change out of stock condition with greater or equals
  src/Adapter/Presenter/Product/ProductLazyArray.php
Labels: Bug, QA ✔️, develop

#9433 Add customizations field in product whitelist
  src/Core/Filter/FrontEndObject/ProductFilter.php
Labels: Bug, QA ✔️, develop

#9439 Fix Error 500 from API request with PHP 7.2
  classes/webservice/WebserviceRequest.php
Labels: Bug, develop

#9436 Remove unused taxes
  localization/dk.xml
Labels: Bug, QA ✔️, develop

#9432 Make it unnecessary to append a '_' to the controller name when using the AdminSecurity annotation
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AdministrationController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmailController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ImportController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/LogsController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/PerformanceController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SystemInformationController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/CustomerPreferencesController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/GeolocationController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/LocalizationController.php
  src/PrestaShopBundle/Controller/Admin/Improve/Payment/PaymentPreferencesController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/DeliveryController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/InvoicesController.php
  src/PrestaShopBundle/Controller/Admin/TranslationsController.php
  src/PrestaShopBundle/Security/Voter/PageVoter.php
Labels: Improvement, QA ✔️, develop

#9400 Allow docker to run e2e tests
  install-dev/classes/controllerConsole.php
  tests/E2E/.docker/Dockerfile
  tests/E2E/.docker/prepare-prestashop.sh
  tests/E2E/.docker/prestashop/Dockerfile
  tests/E2E/.docker/prestashop/docker_run.sh
  tests/E2E/.docker/prestashop/wait-for-it.sh
  tests/E2E/.docker/run-tests.sh
  tests/E2E/DOCKER.md
  tests/E2E/Dockerfile
  tests/E2E/README.md
  tests/E2E/docker-compose.yml
  tests/E2E/docker-files/npm-warmup.sh
  tests/E2E/docker-files/run-tests.sh
  tests/E2E/package-lock.json
  tests/E2E/package.json
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/common.webdriverio.js
  tests/E2E/test/globals.webdriverio.js
Labels: Improvement, develop

#9441 Fix 403 error when accessing localhost using IPv6 (Maxmind Database exists)
  classes/controller/FrontController.php
Labels: Bug, QA ✔️, develop

#9426 add comment line to Address.php
  classes/Address.php
Labels: Improvement, develop

#9291 Small FrameworkBundleAdminController clean up
  src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php
Labels: Improvement, develop

#7612 Added new actionFrontControllerSetVariables hook
  classes/controller/FrontController.php
Labels: Improvement, QA ✔️, develop

#9457 Enable Logs page
  admin-dev/themes/default/template/controllers/logs/employee_field.tpl
  admin-dev/themes/default/template/controllers/logs/helpers/index.php
  admin-dev/themes/default/template/controllers/logs/helpers/list/index.php
  admin-dev/themes/default/template/controllers/logs/helpers/list/list_header.tpl
  admin-dev/themes/default/template/controllers/logs/index.php
  classes/Link.php
  controllers/admin/AdminLogsController.php
  src/Adapter/Hosting/HostingInformation.php
  src/Core/Grid/Definition/Factory/LogGridDefinitionFactory.php
  src/Core/Search/Filters.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/LogsController.php
  src/PrestaShopBundle/Controller/ArgumentResolver/SearchParametersResolver.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Logs/FilterLogsByAttributeType.php
  src/PrestaShopBundle/Resources/config/services/core/grid.yml
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/grid_actions.html.twig
  tests/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
  tests/Integration/PrestaShopBundle/Test/WebTestCase.php
  tests/PrestaShopBundle/Controller/ControllerTest.php
Labels: Feature, QA ✔️, develop

#9428 Added a new hook to custom SwiftMessage before sending mail
  classes/Mail.php
Labels: Improvement, QA ✔️, develop

#9455 Removed all translations errors from localization page
  src/PrestaShopBundle/Form/Admin/Improve/International/Localization/ImportLocalizationPackType.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Localization/LocalizationConfigurationType.php
Labels: Bug, QA ✔️, develop

#9461 Update Readme
  CONTRIBUTING.md
  README.md
Labels: Improvement, develop

#8710 Improved Product catalogAction
  src/Adapter/Product/FilterCategoriesRequestPurifier.php
  src/Adapter/Product/FilterParametersUpdater.php
  src/Core/Product/ProductCsvExporter.php
  src/Core/Product/ProductExporterInterface.php
  src/PrestaShopBundle/Component/CsvResponse.php
  src/PrestaShopBundle/Controller/Admin/CombinationController.php
  src/PrestaShopBundle/Controller/Admin/CommonController.php
  src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Form/Admin/Product/ProductCategories.php
  src/PrestaShopBundle/Model/Product/AdminModelAdapter.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products/products.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/services.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/bundle/services.yml
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Panels/essentials.html.twig
  tests/PrestaShopBundle/Model/Product/AdminModelAdapterTest.php
Labels: Improvement, QA ✔️, develop

#9462 Fix wrong rules in robots.txt
  classes/Tools.php
  controllers/admin/AdminMetaController.php
  robots.txt
Labels: Bug, QA ✔️, develop

#9430 Update modern forms layout
  admin-dev/themes/default/js/bundle/admin_parameters/performancePageUI.js
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Email/Blocks/email_configuration.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Email/Blocks/smtp_configuration.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Email/Blocks/test_email_sending.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Email/email.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/administration.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/memcache_servers.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/performance.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/customer_preferences_general.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_general.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_page.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_pagination.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_stock.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/OrderPreferences/Blocks/order_preferences_general.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/OrderPreferences/Blocks/order_preferences_gift_options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/OrderPreferences/order_preferences.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/customer_preferences.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/maintenance.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/product_preferences.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Geolocation/Blocks/geolocation_by_ip_address.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Geolocation/Blocks/geolocation_ip_address_whitelist.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Geolocation/Blocks/geolocation_options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Geolocation/geolocation.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Localization/Blocks/advanced_configuration.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Localization/Blocks/configuration.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Localization/Blocks/import_localization_pack_block.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Localization/Blocks/local_units.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Localization/localization.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Shipping/Preferences/Blocks/shipping_preferences_carrier_options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Shipping/Preferences/Blocks/shipping_preferences_handling.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Shipping/Preferences/preferences.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Delivery/slip.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Invoices/Blocks/generate_by_date.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Invoices/Blocks/generate_by_status.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Invoices/Blocks/invoice_options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Invoices/invoices.html.twig
Labels: Improvement, QA ✔️, develop

#9467 Build core theme using Webpack 4 and jQuery 2.2.4
  themes/core.js
  themes/core.js.map
  themes/package-lock.json
  themes/package.json
  themes/webpack.config.js
Labels: Improvement, QA ✔️, develop

#9469 Do not display product Specific References if empty
  themes/classic/templates/catalog/_partials/product-details.tpl
Labels: QA ✔️, bug fix, develop

#9407 Display NOK PrestaShop requirements
  src/Adapter/Requirement/CheckRequirements.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/system_information.html.twig
Labels: Bug, QA ✔️, develop

#9450 Modify Link::getAdminLink in MultipleShop mode
  classes/Link.php
Labels: Bug, QA ✔️, develop

#9414 Add arabic language in installer
  install-dev/langs/ar/data/cms.xml
  install-dev/langs/ar/data/index.php
  install-dev/langs/ar/flag.jpg
  install-dev/langs/ar/img/ar-default-category.jpg
  install-dev/langs/ar/img/ar-default-home.jpg
  install-dev/langs/ar/img/ar-default-large.jpg
  install-dev/langs/ar/img/ar-default-large_scene.jpg
  install-dev/langs/ar/img/ar-default-medium.jpg
  install-dev/langs/ar/img/ar-default-small.jpg
  install-dev/langs/ar/img/ar-default-thickbox.jpg
  install-dev/langs/ar/img/ar-default-thumb_scene.jpg
  install-dev/langs/ar/img/ar.jpg
  install-dev/langs/ar/img/index.php
  install-dev/langs/ar/index.php
  install-dev/langs/ar/language.xml
Labels: Improvement, QA ✔️, develop

#9464 Fix geolocation whitelist
  install-dev/data/xml/configuration.xml
Labels: Bug, develop

#10042 With undefined function call (Fixed #10041)
  src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php
Labels: QA ✔️

#9466 fix combination generation
  admin-dev/themes/new-theme/js/product-page/combination.js
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  src/PrestaShopBundle/Controller/Admin/SupplierController.php
Labels: Bug, QA ✔️

#10089 Wrong bash conditions in check_file_syntax file
  tests/check_file_syntax.sh
Labels: Bug, develop

#9463 Change the default redirection behaviour to product category
  admin-dev/themes/default/js/bundle/product/form.js
  classes/Product.php
  controllers/front/ProductController.php
  install-dev/fixtures/fashion/data/product.xml
  src/Core/Product/ProductInterface.php
  src/PrestaShopBundle/Form/Admin/Product/ProductSeo.php
  src/PrestaShopBundle/Model/Product/AdminModelAdapter.php
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/typeahead.html.twig
Labels: Improvement, QA ✔️, develop

#9474 CO: files can not be accessed
  translations/.htaccess
Labels: Bug, QA ✔️, develop

#10104 Add Latvian language in the installer
  install-dev/langs/lv/data/cms.xml
  install-dev/langs/lv/data/index.php
  install-dev/langs/lv/flag.jpg
  install-dev/langs/lv/img/index.php
  install-dev/langs/lv/img/lv-default-category.jpg
  install-dev/langs/lv/img/lv-default-home.jpg
  install-dev/langs/lv/img/lv-default-large.jpg
  install-dev/langs/lv/img/lv-default-large_scene.jpg
  install-dev/langs/lv/img/lv-default-medium.jpg
  install-dev/langs/lv/img/lv-default-small.jpg
  install-dev/langs/lv/img/lv-default-thickbox.jpg
  install-dev/langs/lv/img/lv-default-thumb_scene.jpg
  install-dev/langs/lv/img/lv.jpg
  install-dev/langs/lv/index.php
  install-dev/langs/lv/language.xml
Labels: Improvement, QA ✔️, develop

#10110 Replace Forge with GitHub issues in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improvement, develop

#10126 Reduce Travis jobs
  .travis.yml
Labels: Improvement, develop

#10129 Fix phpunit.xml indentation
  phpunit.xml
Labels: Improvement, develop

#10106 Add Galician language in the installer
  install-dev/langs/gl/data/cms.xml
  install-dev/langs/gl/data/index.php
  install-dev/langs/gl/flag.jpg
  install-dev/langs/gl/img/gl-default-category.jpg
  install-dev/langs/gl/img/gl-default-home.jpg
  install-dev/langs/gl/img/gl-default-large.jpg
  install-dev/langs/gl/img/gl-default-large_scene.jpg
  install-dev/langs/gl/img/gl-default-medium.jpg
  install-dev/langs/gl/img/gl-default-small.jpg
  install-dev/langs/gl/img/gl-default-thickbox.jpg
  install-dev/langs/gl/img/gl-default-thumb_scene.jpg
  install-dev/langs/gl/img/gl.jpg
  install-dev/langs/gl/img/index.php
  install-dev/langs/gl/index.php
  install-dev/langs/gl/language.xml
Labels: Improvement, QA ✔️, develop

#9451 Replace PrestaTrust property with setter
  src/Adapter/Module/PrestaTrust/ModuleEventSubscriber.php
  src/PrestaShopBundle/Resources/config/services/adapter/prestatrust.yml
Labels: Improvement, QA ✔️, develop

#10139 Remove legacy AdminBackup controller
  controllers/admin/AdminBackupController.php
Labels: Bug, develop

#9305 Introduce ToggleColumn for Grid component
  admin-dev/themes/new-theme/js/app/utils/column-toggling.js
  admin-dev/themes/new-theme/js/components/grid/extension/column-toggling-extension.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/_grid.scss
  admin-dev/themes/new-theme/scss/theme.scss
  src/Core/Grid/Column/Type/Common/ToggleColumn.php
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/toggle.html.twig
Labels: Feature, develop

#10038 Fixed mismatch of PHPDocs + unit tests
  src/Adapter/Admin/LegacyBlockHelperSubscriber.php
  src/Adapter/Hook/HookDispatcher.php
  src/Adapter/LegacyHookSubscriber.php
  src/Core/Hook/HookDispatcher.php
  src/Core/Hook/RenderedHook.php
  src/Core/Hook/RenderedHookInterface.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_handler.yml
  src/PrestaShopBundle/Service/Hook/RenderingHookEvent.php
  src/PrestaShopBundle/Twig/HookExtension.php
  tests/PrestaShopBundle/Service/Hook/HookDispatcherTest.php
  tests/Unit/Core/Hook/HookDispatcherTest.php
  tests/Unit/Core/Hook/RenderedHookTest.php
Labels: Bug, develop

#10155 fix trusted modules cache creation
  classes/module/Module.php
  tests/Integration/Core/Module/ModuleCacheTest.php
Labels: Bug, develop

#10165 Add form handler for Translations settings forms
  src/Adapter/Translations/TranslationRouteFinder.php
  src/PrestaShopBundle/Controller/Admin/TranslationsController.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Translations/TranslationsSettingsFormHandler.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_handler.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Translations/Blocks/add_update_language.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Translations/Blocks/copy_language.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Translations/Blocks/export_language.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Translations/Blocks/modify_translations.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Translations/translations_settings.html.twig
Labels: Bug, develop

#10170 Small ux optimizations
  admin-dev/themes/new-theme/js/product-page/category-tree.js
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/catalog_product.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/improve_design_positions.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/module_card.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/translation_settings.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/scss/components/_category_tree.scss
  admin-dev/themes/new-theme/scss/pages/_product_page.scss
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Blocks/footer.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_categories.html.twig
Labels: Improvement, QA ✔️, develop, waiting for wording

#9396 Update version to 1.7.5.0
  app/AppKernel.php
  install-dev/install_version.php
Labels: Improvement, develop, waiting for QA

#10117 Fix bug shipping number is empty in {followup}
  classes/order/OrderCarrier.php
Labels: Bug, QA ✔️, develop

#10201 Errors when saving memcached configuration
  admin-dev/themes/default/js/bundle/admin_parameters/performancePage.js
  src/Adapter/Cache/MemcacheServerManager.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/MemcacheServerController.php
Labels: Bug, QA ✔️, develop

#10169 Images aren't displayed in combinations
  admin-dev/themes/default/package-lock.json
  admin-dev/themes/new-theme/js/product-page/combination.js
  admin-dev/themes/new-theme/js/product-page/product-header.js
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/catalog_product.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/improve_design_positions.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/module_card.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/translation_settings.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/scss/pages/_product_page.scss
  admin-dev/themes/new-theme/template/components/layout/search_form.tpl
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Blocks/tabs.html.twig
Labels: Bug, QA ✔️, develop

#10151 Replaced Forge URL with GitHub issues
  admin-dev/themes/default/template/controllers/dashboard/helpers/view/view.tpl
  admin-dev/themes/default/template/footer.tpl
  themes/classic/CONTRIBUTING.md
Labels: Improvement, Needs port on StarterTheme, QA ✔️, develop

#9458 Change brand and supplier default rule for SEO purposes
  classes/Dispatcher.php
  install-dev/upgrade/php/add_supplier_manufacturer_routes.php
  install-dev/upgrade/sql/1.7.5.0.sql
  src/PrestaShopBundle/Install/Upgrade.php
Labels: Improvement, QA ✔️, develop

#9385 Add eslint based on Airbnb
  .eslintignore
  .eslintrc.js
  .eslintrc.json
  js/.eslintrc.js
  package-lock.json
  package.json
Labels: Improvement, develop

#10218 Fix falsy value returned by upgrade script
  install-dev/upgrade/php/ps1700_stores.php
Labels: Bug, QA ✔️, develop

#10200 Bring back Addons Catalog controller
  classes/Link.php
  install-dev/data/xml/tab.xml
  install-dev/langs/en/data/tab.xml
  install-dev/langs/fa/data/tab.xml
  install-dev/upgrade/php/ps_1750_update_module_tabs.php
  install-dev/upgrade/sql/1.7.5.0.sql
  src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php
  src/PrestaShopBundle/Controller/Admin/Improve/Modules/AddonsStoreController.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/modules/_modules.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/Module/addons_store.html.twig
Labels: Bug, QA ✔️, develop

#10207 Voucher button is too long in Cart
  themes/classic/_dev/css/components/cart.scss
  themes/classic/assets/css/theme.css
  themes/classic/assets/js/theme.js
Labels: Improvement, Needs port on StarterTheme, QA ✔️, develop

#8744 CO: prefer Hook::coreRenderWidget
  config/smartyfront.config.inc.php
Labels: Improvement, QA ✔️, develop

#10230 Add magic methods on LazyArray classes for object-like use
  src/Adapter/Presenter/AbstractLazyArray.php
Labels: Bug, QA ✔️, develop

#9456 Modify product canonical url and title value
  controllers/front/ProductController.php
  src/Adapter/Presenter/Product/ProductLazyArray.php
Labels: Improvement, QA ✔️, develop

#10232 Generate front core assets
  themes/core.js
  themes/core.js.map
Labels: Bug, QA ✔️, develop

#9343 Fix function comment of Module class
  classes/module/Module.php
Labels: Bug, develop
