Repository PrestaShop/PrestaShop, pull requests merged in 2018-03, with the labels that each got.

#8746 Make file copy on ModuleSelfConfiguration mockable
  src/Adapter/Module/Configuration/ModuleSelfConfigurator.php
  src/PrestaShopBundle/Resources/config/admin/services.yml
  tests/Unit/Adapter/Module/Configuration/ModuleSelfConfiguratorTest.php
Labels: 1.7.x, QA-approved

#8234 Fixed bug on save specific price priority for specific product
  controllers/admin/AdminProductsController.php
Labels: QA-approved, Type: Bug Fix

#8277 CustomerAddressFormatter states were queried without the status (active) check causing disabling states in BO useless
  classes/State.php
  classes/form/CustomerAddressFormatter.php
Labels: QA-approved

#8462 Fix empty module return on actionEmailSendBefore breaks all email send
  classes/Mail.php
Labels: QA-approved

#8476 Fix customer search in new order form
  admin-dev/themes/default/template/controllers/orders/form.tpl
Labels: QA-approved

#8522 Fixed specific price percentage rounding on front product page
  src/Core/Product/ProductPresenter.php
Labels: 1.7.x, QA-approved

#8525 "No tax" price option is now well saved in admin product page
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Model/Product/AdminModelAdapter.php
Labels: 1.7.x, QA-approved

#8618 Fix type warning in order detail
  admin-dev/themes/default/template/controllers/orders/_customized_data.tpl
  admin-dev/themes/default/template/controllers/orders/_new_product.tpl
  admin-dev/themes/default/template/controllers/orders/_product_line.tpl
Labels: 1.7.x, QA-approved

#8648 Fix modal backdrop not removed when uninstalling a module
  admin-dev/themes/default/js/bundle/module/module_card.js
Labels: QA-approved

#8669 Make sure all adresses are reset on cart
  classes/Context.php
Labels: QA-approved

#8696 Fix translation issue during language install
  classes/Context.php
  classes/Language.php
  classes/lang/AttributeGroupLang.php
  classes/lang/AttributeLang.php
  classes/lang/CarrierLang.php
  classes/lang/CategoryLang.php
  classes/lang/CmsCategoryLang.php
  classes/lang/ConfigurationLang.php
  classes/lang/ContactLang.php
  classes/lang/DataLang.php
  classes/lang/FeatureLang.php
  classes/lang/FeatureValueLang.php
  classes/lang/GenderLang.php
  classes/lang/GroupLang.php
  classes/lang/MetaLang.php
  classes/lang/OrderMessageLang.php
  classes/lang/OrderReturnStateLang.php
  classes/lang/OrderStateLang.php
  classes/lang/ProfileLang.php
  classes/lang/QuickAccessLang.php
  classes/lang/RiskLang.php
  classes/lang/StockMvtReasonLang.php
  classes/lang/SupplyOrderStateLang.php
  classes/lang/TabLang.php
  classes/lang/ThemeLang.php
Labels: QA-approved

#8714 Update loaded details from database on module action
  src/Adapter/Module/Module.php
  src/Core/Addon/Module/ModuleManager.php
  tests/Unit/Core/Addon/Module/ModuleManagerTest.php
Labels: QA-approved

#8725 Replace Google+ link on BO footer by Youtube link
  admin-dev/themes/default/css/admin-theme.css
  admin-dev/themes/default/css/admin-theme_rtl.css
  admin-dev/themes/default/css/font.css
  admin-dev/themes/default/css/schemes/admin-theme-blue.css
  admin-dev/themes/default/css/schemes/admin-theme-contrast.css
  admin-dev/themes/default/css/schemes/admin-theme-flex.css
  admin-dev/themes/default/css/schemes/admin-theme-fruit.css
  admin-dev/themes/default/css/schemes/admin-theme-prune.css
  admin-dev/themes/default/css/schemes_rtl/admin-theme-blue_rtl.css
  admin-dev/themes/default/css/schemes_rtl/admin-theme-contrast_rtl.css
  admin-dev/themes/default/css/schemes_rtl/admin-theme-flex_rtl.css
  admin-dev/themes/default/css/schemes_rtl/admin-theme-fruit_rtl.css
  admin-dev/themes/default/css/schemes_rtl/admin-theme-prune_rtl.css
  admin-dev/themes/default/sass/partials/_footer.sass
  admin-dev/themes/default/template/footer.tpl
Labels: QA-approved

#8815 Re-enable functional tests
  .travis.yml
  tests/E2E/test/campaigns/high/02_product/product.js
  tests/E2E/test/campaigns/high/10_module/module.js
  tests/E2E/test/campaigns/install_upgrade/02_autoupgrade.js
  tests/E2E/test/campaigns/regular/04_create_order_in_FO.js
  tests/E2E/test/selectors/BO/add_product_page.js
  tests/E2E/test/selectors/BO/module_page.js
  travis-scripts/run-functional-tests
Labels: E2E

#8689 Fix translator in prod mode
  install-dev/missing_requirement.php
  src/PrestaShopBundle/DependencyInjection/Compiler/OverrideTranslatorServiceCompilerPass.php
  src/PrestaShopBundle/PrestaShopBundle.php
Labels: waiting for QA feedback

#8806 Sample products in FA
  install-dev/fixtures/fashion/langs/fa/data/product.xml
Labels: 1.7.x, Translations

#8515 Upgrade Symfony to 3.4 LTS
  .gitignore
  app/AppKernel.php
  app/config/config_test.yml
  app/config/services.yml
  classes/Tools.php
  composer.json
  composer.lock
  install-dev/init.php
  src/Adapter/Cache/CacheClearer.php
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Resources/config/adapter/services.yml
  src/PrestaShopBundle/Resources/config/admin/services-form.yml
  src/PrestaShopBundle/Resources/config/admin/services.yml
  src/PrestaShopBundle/Resources/config/services.yml
  src/PrestaShopBundle/Service/Command/AbstractCommand.php
  tests/Integration/PrestaShopBundle/Controller/Api/StockManagementControllerTest.php
  tests/Integration/PrestaShopBundle/Test/WebTestCase.php
  tests/Integration/classes/CartGetOrderTotalTest.php
  tests/PrestaShopBundle/Utils/DatabaseCreator.php
  tests/TestCase/IntegrationTestCase.php
  tests/old-controllers.xml
  tests/phpunit-admin.xml
  tests/phpunit.xml
  tests/sf-tests.xml
Labels: 1.7.x, QA-approved

#8823 Fixed broken search after #8741
  controllers/front/listing/SearchController.php
Labels: 1.7.x, QA-approved

#8543 Layout broken by cache clear
  classes/controller/AdminController.php
  controllers/admin/AdminThemesController.php
  src/Core/Addon/Theme/ThemeManager.php
  src/Core/Addon/Theme/ThemeRepository.php
  src/PrestaShopBundle/Cache/CacheWarmer.php
Labels: 1.7.x, QA-approved

#8780 Improve BO speed by removing menu images
  classes/controller/AdminController.php
Labels: PM-approved, Performance improvements, QA-approved

#8846 Fix menu width and submenu hover on header
  themes/classic/_dev/css/components/mainmenu.scss
  themes/classic/_dev/css/theme.scss
  themes/classic/_dev/js/components/top-menu.js
  themes/classic/assets/css/theme.css
  themes/classic/assets/js/theme.js
  themes/classic/modules/ps_mainmenu/ps_mainmenu.tpl
Labels: 1.7.x, QA-approved

#8631 Request module zip for upgrade ONLY when the version available is higher
  src/Adapter/Module/Module.php
  src/Core/Addon/Module/ModuleManager.php
Labels: QA-approved

#7775 Resolve incompatibility between canonical redirections, attributes and product route not only containing rewrite
  controllers/front/ProductController.php
Labels: QA-approved, Type: Bug Fix

#8498 Fixed bug on reorder with free gift in the cart
  classes/Cart.php
Labels: 1.7.x, QA-approved

#8845 Fix search bar on header when it moves from hook and improve header structure #2
  themes/classic/_dev/css/components/mainmenu.scss
  themes/classic/_dev/css/components/search-widget.scss
  themes/classic/_dev/css/theme.scss
  themes/classic/assets/css/theme.css
  themes/classic/assets/js/theme.js
  themes/classic/modules/ps_searchbar/ps_searchbar.tpl
  themes/classic/templates/_partials/header.tpl
Labels: 1.7.x, QA-approved

#8847 Override advertising module on classic template to fix image width
  themes/classic/_dev/css/components/categories.scss
  themes/classic/assets/css/theme.css
  themes/classic/modules/ps_advertising/index.php
  themes/classic/modules/ps_advertising/ps_advertising.tpl
Labels: 1.7.x, QA-approved, report on StarterTheme

#8500 Make sure shop list in header is scrollable with lot of items
  admin-dev/themes/default/css/admin-theme.css
  admin-dev/themes/default/css/admin-theme_rtl.css
  admin-dev/themes/default/css/schemes/admin-theme-blue.css
  admin-dev/themes/default/css/schemes/admin-theme-contrast.css
  admin-dev/themes/default/css/schemes/admin-theme-flex.css
  admin-dev/themes/default/css/schemes/admin-theme-fruit.css
  admin-dev/themes/default/css/schemes/admin-theme-prune.css
  admin-dev/themes/default/css/schemes_rtl/admin-theme-blue_rtl.css
  admin-dev/themes/default/css/schemes_rtl/admin-theme-contrast_rtl.css
  admin-dev/themes/default/css/schemes_rtl/admin-theme-flex_rtl.css
  admin-dev/themes/default/css/schemes_rtl/admin-theme-fruit_rtl.css
  admin-dev/themes/default/css/schemes_rtl/admin-theme-prune_rtl.css
  admin-dev/themes/default/sass/partials/_header.sass
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
Labels: 1.7.x, QA-approved

#8584 Update toCamelCase
  classes/Tools.php
  tests/Unit/classes/ToolsCoreTest.php
Labels: 1.7.x

#8664 Change employee icon
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
  admin-dev/themes/new-theme/template/components/layout/employee_dropdown.tpl
Labels: waiting for QA feedback

#8856 Fixed undefined variables when an url is called in ajax
  controllers/front/OrderDetailController.php
  controllers/front/listing/BestSalesController.php
  controllers/front/listing/CategoryController.php
  controllers/front/listing/ManufacturerController.php
  controllers/front/listing/NewProductsController.php
  controllers/front/listing/PricesDropController.php
  controllers/front/listing/SearchController.php
  controllers/front/listing/SupplierController.php
Labels: 1.7.x, QA-approved

#8803 Stop full object exposure on the front end
  classes/controller/Controller.php
  classes/controller/FrontController.php
  classes/controller/ProductListingFrontController.php
  config/services/front/services_prod.yml
  controllers/front/CartController.php
  install-dev/data/xml/hook.xml
  src/Core/Filter/CollectionFilter.php
  src/Core/Filter/FilterException.php
  src/Core/Filter/FilterInterface.php
  src/Core/Filter/FrontEndObject/CartFilter.php
  src/Core/Filter/FrontEndObject/ConfigurationFilter.php
  src/Core/Filter/FrontEndObject/CustomerFilter.php
  src/Core/Filter/FrontEndObject/EmbeddedAttributesFilter.php
  src/Core/Filter/FrontEndObject/MainFilter.php
  src/Core/Filter/FrontEndObject/ProductFilter.php
  src/Core/Filter/FrontEndObject/SearchResultProductFilter.php
  src/Core/Filter/FrontEndObject/ShopFilter.php
  src/Core/Filter/HashMapWhitelistFilter.php
  tests/Unit/Core/Filter/CollectionFilterTest.php
  tests/Unit/Core/Filter/HashMapWhitelistFilterTest.php
Labels: 1.7.x, QA-approved

#8860 Make the dezipper great again
  tools/build/Library/InstallUnpacker/compile.php
  tools/build/Library/InstallUnpacker/index_template.php
Labels: QA-approved

#8711 Default AJAX Relevance search sort order is wrong
  controllers/front/listing/SearchController.php
  src/Core/Product/Search/SortOrderFactory.php
Labels: QA-approved

#8607 Fix pack quantity issue
  classes/Cart.php
  classes/CartRule.php
  classes/Pack.php
  classes/Product.php
  classes/order/OrderDetail.php
  classes/stock/StockAvailable.php
  classes/stock/StockManager.php
  controllers/admin/AdminOrdersController.php
  controllers/admin/AdminProductsController.php
  controllers/front/CartController.php
  controllers/front/ProductController.php
  src/Core/Product/ProductPresenter.php
  src/Core/Stock/StockManager.php
  src/PrestaShopBundle/Form/Admin/Product/ProductQuantity.php
  tests/Unit/ContextMocker.php
  tests/Unit/Core/Cart/AbstractCartTest.php
  tests/Unit/Core/Cart/Adding/Product/AddPackTest.php
  tests/resources/ModulesOverrideInstallUninstallTest/AdminProductsController.php
  tests/resources/module/pscsx32412/override/controllers/admin/AdminProductsController.php
Labels: 1.7.x, QA-approved

#8779 Little css override for modal title
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/scss/theme.scss
Labels: QA-approved

#8873 Fix contactform module issues
  mails/en/contact_form.html
  mails/en/contact_form.txt
  src/PrestaShopBundle/Install/Install.php
  themes/classic/modules/contactform/views/templates/widget/contactform.tpl
Labels: 1.7.x, QA-approved

#8766 Show unit price within a tax in order confirmation e-mail
  classes/PaymentModule.php
Labels: 1.7.x, QA-approved

#8849 Add User club and UserVoice on BO link footer
  admin-dev/themes/default/template/footer.tpl
Labels: 1.7.x, QA-approved

#8685 Fixed link_rewrite argument for getImageLink().
  classes/order/OrderCarrier.php
Labels: 1.7.x, QA-approved

#8871 Improved rendering of combinations in Product page
  admin-dev/themes/new-theme/js/product-page/combination.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  app/config/config.yml
  src/Adapter/CombinationDataProvider.php
  src/PrestaShopBundle/Controller/Admin/CombinationController.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combination.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combination_collection.html.twig
Labels: QA-approved, waiting for wording

#8743 CO: Fix the links sent in the mails (multilingualism)
  classes/Mail.php
Labels: QA-approved

#8789 Do not call search::indexation at each entity creation
  install-dev/classes/controllerHttp.php
  install-dev/controllers/http/process.php
  src/PrestaShopBundle/Install/Install.php
Labels: 1.7.x, Performance improvements, QA-approved, Type: Improvement

#8754 Fix non-filtered meta by filterHtmlContent hook
  classes/Meta.php
Labels: 1.7.x, QA-approved, Type: Bug Fix

#8529 Fix bug alignment sidebar menuCollapse Admin theme
  admin-dev/themes/default/css/admin-theme.css
  admin-dev/themes/default/js/admin-theme.js
Labels: 1.7.x, QA-approved

#8514 Added GroupBy option for actionAdminProductsListingFieldsModifier hook
  src/Adapter/Admin/AbstractAdminQueryBuilder.php
  src/Adapter/Product/AdminProductDataProvider.php
Labels: 1.7.x, QA-approved

#8270 Allow modifying IdentityController to save personal information without password
  classes/form/CustomerForm.php
  classes/form/CustomerPersister.php
  controllers/front/IdentityController.php
Labels: QA-approved

#8790 Optimize reserved product quantity update
  install-dev/data/db_structure.sql
  install-dev/upgrade/sql/1.7.3.0.sql
  install-dev/upgrade/sql/1.7.4.0.sql
  src/Adapter/StockManager.php
Labels: 1.7.x, QA-approved

#8469 add a few optimisations to speed up the display of the order history …
  classes/Cart.php
  classes/order/Order.php
  classes/tax/TaxConfiguration.php
  controllers/front/HistoryController.php
  src/Adapter/Order/OrderPresenter.php
Labels: 1.7.x, Code reviewed, QA-approved, Type: Improvement

#8886 properly set the test database by taking into account the environment with console commands
  app/config/config_test.yml
  app/config/set_parameters.php
  tests/PrestaShopBundle/Utils/DatabaseCreator.php
  tests/sf-tests.xml
Labels: 1.7.x

#8788 speed up test_dir with a lot of files present in a directory
  classes/ConfigurationTest.php
  classes/Tools.php
Labels: 1.7.x, Performance improvements, Type: Improvement

#8819 Fix sort product script
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/high/02_product/3_create_product_with_combination.js
  tests/E2E/test/campaigns/high/02_product/8_sort_product.js
  tests/E2E/test/campaigns/high/02_product/9_check_shopping_cart.js
  tests/E2E/test/campaigns/high/06_catalogbulkaction/catalogbulkaction.js
  tests/E2E/test/clients/product/product.js
Labels: E2E

#8705 Introduce switch type in forms
  admin-dev/bootstrap.php
  admin-dev/index.php
  admin-dev/themes/default/js/bundle/admin_parameters/performancePageUI.js
  classes/Combination.php
  classes/Feature.php
  classes/Group.php
  classes/container/LegacyCompilerPass.php
  src/Adapter/Admin/NotificationsConfiguration.php
  src/Adapter/Cache/CombineCompressCacheConfiguration.php
  src/Adapter/Configuration.php
  src/Adapter/Debug/DebugModeConfiguration.php
  src/Adapter/GeneralConfiguration.php
  src/Adapter/Shop/MaintenanceConfiguration.php
  src/Adapter/Smarty/SmartyCacheConfiguration.php
  src/Core/Addon/Theme/ThemeManagerBuilder.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Administration/GeneralType.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Administration/NotificationsType.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/CachingType.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/CombineCompressCacheType.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/DebugModeType.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/OptionalFeaturesType.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/SmartyType.php
  src/PrestaShopBundle/Form/Admin/ShopParameters/General/MaintenanceType.php
  src/PrestaShopBundle/Form/Admin/Type/SwitchType.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/maintenance.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_3_horizontal_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_3_layout.html.twig
  tests/Integration/PrestaShopBundle/Test/WebTestCase.php
  tests/bootstrap-controllers.php
  tests/bootstrap-sf.php
Labels: QA-approved

#8891 Fix dezipper redirect
  tools/build/Library/InstallUnpacker/index_template.php
Labels: QA-approved

#8875 Check the addons catalog page
  tests/E2E/test/campaigns/full/10_module/5_check_addons_catalog_page.js
  tests/E2E/test/selectors/BO/addons_catalog_page.js
Labels: 1.7.x, E2E

#8879 Test Buttons (Preview, Duplicate, Online, Go to catalog, Add a new product, Delete) in add product page
  tests/E2E/test/campaigns/full/02_product/10_check_product_page_buttons.js
  tests/E2E/test/selectors/BO/add_product_page.js
  tests/E2E/test/selectors/BO/module_page.js
  tests/E2E/test/selectors/FO/product_page.js
Labels: 1.7.x, E2E

#8854 Check the change of the default combination from the edition page
  tests/E2E/test/campaigns/high/02_product/3_create_product_with_combination.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/selectors/BO/add_product_page.js
Labels: E2E

#8874 Check notifications
  tests/E2E/test/campaigns/common_scenarios/module.js
  tests/E2E/test/campaigns/full/10_module/6_check_notifications.js
  tests/E2E/test/selectors/BO/module_page.js
Labels: 1.7.x, E2E

#8878 Check the appearance of tinymce field on the product page
  tests/E2E/test/campaigns/common_scenarios/employee.js
  tests/E2E/test/campaigns/common_scenarios/international.js
  tests/E2E/test/campaigns/full/02_product/10_check_tinymce_field_in_BO.js
  tests/E2E/test/selectors/BO/add_product_page.js
  tests/E2E/test/selectors/BO/employee_page.js
  tests/E2E/test/selectors/BO/international/index.js
  tests/E2E/test/selectors/BO/international/localization.js
Labels: E2E

#8876 Disable Symfony tokenization in routing
  classes/Link.php
  classes/controller/AdminController.php
  src/Core/Feature/TokenInUrls.php
  src/PrestaShopBundle/EventListener/TokenizedUrlsListener.php
  src/PrestaShopBundle/Service/Routing/Router.php
Labels: 1.7.x, Code reviewed, QA-approved

#8863 Fixed misuse of magic routing
  src/PrestaShopBundle/Controller/Admin/StockController.php
  src/PrestaShopBundle/Controller/Admin/TranslationsController.php
Labels: 1.7.x

#8853 Make override of object models easy
  classes/ObjectModel.php
  src/Adapter/EntityMapper.php
Labels: 1.7.x, QA-approved

#8864 Removed almost all deprecations on Product page
  app/AppKernel.php
  app/config/config_prod.yml
  app/config/security.yml
  src/PrestaShopBundle/DependencyInjection/Compiler/RouterPass.php
  src/PrestaShopBundle/Form/Admin/Category/SimpleCategory.php
  src/PrestaShopBundle/Form/Admin/Feature/ProductFeature.php
  src/PrestaShopBundle/Form/Admin/Product/ProductCombination.php
  src/PrestaShopBundle/Form/Admin/Product/ProductCustomField.php
  src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php
  src/PrestaShopBundle/Form/Admin/Product/ProductOptions.php
  src/PrestaShopBundle/Form/Admin/Product/ProductPrice.php
  src/PrestaShopBundle/Form/Admin/Product/ProductQuantity.php
  src/PrestaShopBundle/Form/Admin/Product/ProductSeo.php
  src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php
  src/PrestaShopBundle/Form/Admin/Product/ProductSpecificPrice.php
  src/PrestaShopBundle/Form/Admin/Product/ProductSupplierCombination.php
  src/PrestaShopBundle/Form/Admin/Product/ProductVirtual.php
  src/PrestaShopBundle/Form/Admin/Type/ChoiceCategoriesTreeType.php
  src/PrestaShopBundle/Resources/config/services/alias.yml
Labels: 1.7.x, QA-approved

#8866 FO: Fixed breadcrumb links in ProductController
  controllers/front/ProductController.php
Labels: 1.7.x, QA-approved

#8884 QUERY_STRING is not set on all environments
  classes/controller/FrontController.php
Labels: 1.7.x, Code reviewed, To be cherry-picked

#8812 Delete product
  tests/E2E/test/campaigns/full/02_product/10_delete_product.js
  tests/E2E/test/campaigns/high/06_catalogbulkaction/catalogbulkaction.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/selectors/BO/catalogpage/index.js
Labels: 1.7.x, E2E

#8805 Reset module Welcome if the RESUME button does not exist
  tests/E2E/test/campaigns/common_scenarios/module.js
  tests/E2E/test/campaigns/common_scenarios/shop_parameters.js
  tests/E2E/test/campaigns/high/10_module/1_Zip_module.js
  tests/E2E/test/campaigns/high/12_shop_parameters/3_onboarding.js
  tests/E2E/test/clients/module.js
  tests/E2E/test/clients/onboarding.js
  tests/E2E/test/selectors/BO/module_page.js
Labels: 1.7.x, E2E

#8899 Optimize stock queries
  src/PrestaShopBundle/Api/QueryParamsCollection.php
  src/PrestaShopBundle/Entity/Repository/StockManagementRepository.php
  src/PrestaShopBundle/Entity/Repository/StockMovementRepository.php
  src/PrestaShopBundle/Entity/Repository/StockRepository.php
  tests/Unit/PrestaShopBundle/Api/QueryParamsCollectionTest.php
Labels: 1.7.x, Code reviewed, Performance improvements, QA-approved, Type: Improvement

#8890 Fix display of image form in product page
  src/PrestaShopBundle/Controller/Admin/ProductImageController.php
Labels: Code reviewed, QA-approved

#8859 Passing language ID for Store object instance
  classes/Store.php
Labels: 1.7.x, Code reviewed, QA-approved

#8813 Check the product discount in the Front Office
  tests/E2E/test/campaigns/common_scenarios/discount.js
  tests/E2E/test/campaigns/common_scenarios/taxes.js
  tests/E2E/test/campaigns/full/11_international/3_taxes/1_create_edit_delete_tax_rule_in_BO.js
  tests/E2E/test/campaigns/full/14_discount/1_create_edit_delete_cart_rule_in_BO.js
  tests/E2E/test/campaigns/full/14_discount/2_check_catalog_rule_price.js
  tests/E2E/test/campaigns/full/14_discount/3_check_discount_in_FO.js
  tests/E2E/test/campaigns/full/14_discount/4_check_vouchers_in_FO.js
  tests/E2E/test/campaigns/full/14_discount/5_check_discount_table_in_FO.js
  tests/E2E/test/selectors/BO/add_product_page.js
  tests/E2E/test/selectors/BO/international/index.js
  tests/E2E/test/selectors/BO/international/taxes.js
  tests/E2E/test/selectors/BO/shopParameters/customer_settings.js
  tests/E2E/test/selectors/BO/shopParameters/index.js
  tests/E2E/test/selectors/FO/product_page.js
Labels: 1.7.x, E2E

#8826 create, edit, delete and delete with bulk actions customer
  tests/E2E/test/campaigns/common_scenarios/customer.js
  tests/E2E/test/campaigns/full/09_customer/customer_settings/create_edit_delete_customer.js
  tests/E2E/test/campaigns/high/09_customer/1_create_customer.js
  tests/E2E/test/campaigns/high/09_customer/3_create_customer_in_FO.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/customer.js
  tests/E2E/test/helpers.js
  tests/E2E/test/selectors/BO/customers/customer.js
Labels: 1.7.x, E2E

#8900 CMS Page and category
  tests/E2E/test/campaigns/common_scenarios/pages.js
  tests/E2E/test/campaigns/full/15_design/pages/1_category.js
  tests/E2E/test/campaigns/full/15_design/pages/2_page.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/design.js
  tests/E2E/test/globals.webdriverio.js
  tests/E2E/test/selectors/BO/design/index.js
  tests/E2E/test/selectors/BO/design/pages.js
  tests/E2E/test/selectors/BO/index.js
  tests/E2E/test/selectors/FO/access_page.js
Labels: E2E
