Repository PrestaShop/PrestaShop, pull requests merged in 2018-09, with the labels that each got.

#10233 HookDispatcher dispatchMultiple doesn't exists anymore
  src/Adapter/Hook/HookDispatcher.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
Labels: Bug, QA ✔️, develop

#10227 CO: Fixed error with inheritance
  classes/CartRule.php
Labels: Bug, QA ✔️, develop

#10249 Use PHP_BINARY while using createTestDb
  tests/PrestaShopBundle/Utils/DatabaseCreator.php
Labels: Improvement, develop

#10242 BO: Fix wrong translations
  install-dev/langs/fa/data/tab.xml
Labels: Bug, QA ✔️, develop

#10219 Minor grid improvements
  src/Core/Backup/Listing/BackupGridDataProvider.php
  src/Core/Grid/Definition/Factory/AbstractGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/GridDefinitionFactoryInterface.php
  src/Core/Grid/Definition/GridDefinition.php
  src/Core/Grid/Definition/GridDefinitionInterface.php
  src/Core/Grid/Filter/GridFilterFormFactory.php
  src/Core/Grid/Filter/GridFilterFormFactoryInterface.php
  src/Core/Grid/Grid.php
  src/Core/Grid/GridFactory.php
  src/Core/Grid/GridInterface.php
  src/Core/Grid/Presenter/GridPresenter.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/BackupController.php
  src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php
  src/PrestaShopBundle/Resources/config/services/core/backup.yml
  src/PrestaShopBundle/Resources/config/services/core/grid.yml
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/table.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/grid.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/grid_panel.html.twig
  tests/Unit/Core/Grid/Definition/Factory/AbstractGridDefinitionFactoryTest.php
  tests/Unit/Core/Grid/Presenter/GridPresenterTest.php
Labels: Improvement, develop

#10241 Add Tactician command/query bus
  app/AppKernel.php
  composer.json
  composer.lock
  src/Core/CommandBus/CommandBusInterface.php
  src/Core/CommandBus/TacticianCommandBusAdapter.php
  src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php
  src/PrestaShopBundle/Resources/config/services/core/command_bus.yml
Labels: Feature, develop

#10254 Fix getTotalWeight Notice
  classes/Cart.php
Labels: Bug, QA ✔️, develop

#9362 [FO] Add breadcrumb to the contact page
  controllers/front/ContactController.php
Labels: Improvement, PM ✔️, QA ✔️, develop

#9471 Build Back Office default theme using Webpack 4
  admin-dev/themes/default/package-lock.json
  admin-dev/themes/default/package.json
  admin-dev/themes/default/public/bundle.js
  admin-dev/themes/default/public/theme.css
  admin-dev/themes/default/webpack.config.js
Labels: Improvement, QA ✔️, develop

#10276 Run PHP CS Fixer
  classes/Cart.php
  classes/CartRule.php
  classes/Mail.php
  classes/Product.php
  classes/db/Db.php
  classes/stock/SupplyOrderDetail.php
  controllers/front/ContactController.php
  src/Adapter/Currency/CurrencyDataProvider.php
  src/Adapter/Product/PriceCalculator.php
  src/PrestaShopBundle/Security/Annotation/AdminSecurity.php
Labels: Bug, develop

#9356 CO: Add new variable in product.php, to sort features in front
  classes/Product.php
Labels: Improvement, QA ✔️, develop

#10260 Fix help sidebar not working in the Stock page
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/catalog_product.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/improve_design_positions.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/module_card.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/translation_settings.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
  admin-dev/themes/new-theme/scss/components/layout/_header_toolbar.scss
  src/PrestaShopBundle/Controller/Admin/StockController.php
Labels: Bug, QA ✔️, develop, waiting for rebase

#10287 Fixed pre-commit hook script
  .github/contrib/install.php
  .github/contrib/pre-commit
Labels: Bug, develop

#10281 Fixed minor issues on Logs Grid page
  admin-dev/themes/new-theme/js/app/pages/logs/index.js
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/catalog_product.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/improve_design_positions.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/module_card.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/translation_settings.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
  src/Core/Grid/Definition/Factory/LogGridDefinitionFactory.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Logs/LogsByEmailType.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/logs.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/LogsPage/Blocks/severity_levels.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/LogsPage/logs.html.twig
Labels: Bug, QA ✔️, develop, waiting for author

#9475 Make title different from meta title on CMS for SEO purpose
  classes/CMS.php
  classes/Meta.php
  controllers/admin/AdminCmsController.php
  install-dev/data/db_structure.sql
  install-dev/upgrade/sql/1.7.5.0.sql
Labels: Bug, QA ✔️, develop, waiting for author

#10302 Images aren't displayed in combinations with new products
  admin-dev/themes/new-theme/js/product-page/combination.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/theme.css
Labels: Bug, QA ✔️, develop

#10326 Manage getAdminBaseLink in LegacyContext::getAdminLink
  src/Adapter/LegacyContext.php
Labels: Bug, QA ✔️, develop

#10322 Wrong variable name
  src/PrestaShopBundle/Controller/Admin/ProductController.php
Labels: Bug, QA ✔️, develop

#9444 Add search engine result preview on product page
  admin-dev/themes/new-theme/js/app/utils/serp/index.js
  admin-dev/themes/new-theme/js/app/utils/serp/serp.vue
  admin-dev/themes/new-theme/js/product-page/index.js
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/catalog_product.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/improve_design_positions.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/module_card.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/translation_settings.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
  src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php
  src/PrestaShopBundle/Form/Admin/Product/ProductSeo.php
  src/PrestaShopBundle/Form/Admin/Type/FormattedTextareaType.php
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_seo.html.twig
Labels: Feature, QA ✔️, develop

#9453 Allow import entity to be preselected
  src/Core/Import/Entity.php
  src/Core/Import/Exception/ExceptionInterface.php
  src/Core/Import/Exception/NotSupportedImportTypeException.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ImportController.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Import/ImportType.php
Labels: Bug, QA ✔️, develop

#10202 Fix 'edit specific price' modal behavior bugs and display
  admin-dev/themes/new-theme/js/pages/catalog/product/index.js
  admin-dev/themes/new-theme/js/pages/catalog/product/specific-price-form-handler.js
  admin-dev/themes/new-theme/public/catalog_product.bundle.js
  src/Adapter/Product/AdminProductWrapper.php
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_edit_specific_price_modal.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_specific_price.html.twig
Labels: Bug, QA ✔️, develop

#10279 Check minimal quantity
  controllers/front/CartController.php
Labels: Bug, QA ✔️, develop, waiting for wording

#9324 Fixed the Show SQL query action
  src/Core/Grid/Data/Factory/DoctrineGridDataFactory.php
  src/Core/Grid/Exception/UnsupportedParameterException.php
  src/Core/Grid/Query/DoctrineQueryParser.php
  src/Core/Grid/Query/QueryParserInterface.php
  src/PrestaShopBundle/Resources/config/services/core/grid.yml
  tests/Unit/Core/Grid/Data/Factory/DoctrineGridDataFactoryTest.php
  tests/Unit/Core/Grid/Query/DoctrineQueryParserTest.php
Labels: Bug, QA ✔️, develop

#10135 [BOOM-6197] PDF documents unformatted
  admin-dev/themes/default/public/theme.css
  admin-dev/themes/default/sass/partials/_print.sass
Labels: Bug, QA ✔️, develop

#10361 Only load Vue Serp component if available
  admin-dev/themes/new-theme/js/app/utils/serp/index.js
  admin-dev/themes/new-theme/js/product-page/index.js
  admin-dev/themes/new-theme/public/main.bundle.js
Labels: Bug, QA ✔️, develop

#10352 Fix htaccess to support Apache 2.4 webservers
  var/.htaccess
Labels: Bug, QA ✔️, develop

#10347 FO: Fix htaccess to support Apache 2.4 webservers
  translations/cldr/.htaccess
Labels: Bug, QA ✔️, develop

#10337 Remove hard-coded-version in assets URL
  app/config/config.yml
Labels: Bug, QA ✔️, develop

#9292 Update pull-request template with additional PR types
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improvement, develop

#9340 Update rel="noopener noreferrer"
  install-dev/theme/views/header.php
Labels: Bug, QA ✔️, develop

#10265 Move Logs page JS to appropriate location
  admin-dev/themes/new-theme/js/pages/logs/index.js
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/catalog_product.bundle.js
  admin-dev/themes/new-theme/public/categories.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/improve_design_positions.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/module_card.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/translation_settings.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
  admin-dev/themes/new-theme/webpack.config.js
Labels: Improvement, QA ✔️, develop

#10363 Fix undefined method in query parser
  src/Core/Grid/Query/DoctrineQueryParser.php
  tests/Unit/Core/Grid/Query/DoctrineQueryParserTest.php
Labels: Bug, develop

#10358 Update list and settings layout
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Email/Blocks/email_configuration.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Email/Blocks/smtp_configuration.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Email/Blocks/test_email_sending.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/LogsPage/logs.html.twig
Labels: Improvement, QA ✔️, develop

#10350 Fix empty row when social title is empty
  classes/form/CustomerFormatter.php
Labels: Bug, QA ✔️, develop

#10267 FO | Product List: pack flag visual problem
  themes/classic/_dev/js/components/product-miniature.js
  themes/classic/assets/css/theme.css
  themes/classic/assets/js/theme.js
Labels: Bug, QA ✔️, develop

#10375 Fix category tree in BO Products Catalog page
  admin-dev/themes/default/js/bundle/category-tree.js
  admin-dev/themes/default/js/bundle/product/catalog.js
  src/PrestaShopBundle/Form/Admin/Product/ProductCategories.php
  src/PrestaShopBundle/Form/Admin/Type/ChoiceCategoriesTreeType.php
  src/PrestaShopBundle/Resources/views/Admin/Product/Themes/categories_theme.html.twig
Labels: Bug, QA ✔️, develop

#8825 Check displaying the cover image if no image is selected for declination
  tests/E2E/test/campaigns/full/01_orders/7_shopping_carts_view.js
  tests/E2E/test/campaigns/full/02_product/11_check_cover_picture_in_product_with_combinations.js
  tests/E2E/test/campaigns/full/02_product/16_options_in_catalog_page.js
  tests/E2E/test/campaigns/high/02_product/3_create_product_with_combination.js
  tests/E2E/test/clients/product/create_combinations.js
  tests/E2E/test/clients/product/product.js
  tests/E2E/test/datas/greentshirt.jpg
  tests/E2E/test/datas/redtshirt.jpg
  tests/E2E/test/selectors/BO/add_product_page.js
Labels: Improvement, QA ✔️, TE, develop

#8824 check add to cart button inability when the quantities of the product in the cart is not available
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/campaigns/full/01_orders/4_check_adding_product_to_cart_with_unavailable_quantities.js
  tests/E2E/test/campaigns/full/01_orders/5_create_order_without_account.js
  tests/E2E/test/campaigns/full/01_orders/6_delete_shopping_carts.js
  tests/E2E/test/campaigns/full/01_orders/7_export_shopping_carts.js
  tests/E2E/test/campaigns/full/01_orders/8_shopping_carts_view.js
  tests/E2E/test/selectors/FO/order_page.js
  tests/E2E/test/selectors/FO/product_page.js
Labels: Improvement, QA ✔️, TE, develop

#10291 Fix the display of textarea in the category page
  admin-dev/themes/default/template/helpers/form/form.tpl
Labels: Bug, QA ✔️, develop

#10295 Display the company name in outstanding orders
  controllers/admin/AdminOutstandingController.php
Labels: Bug, QA ✔️, develop

#10311 Small improvements for Webservice list
  admin-dev/themes/new-theme/js/app/utils/column-toggling.js
  admin-dev/themes/new-theme/js/components/grid/extension/column-toggling-extension.js
  admin-dev/themes/new-theme/js/pages/webservice/index.js
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/catalog_product.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/improve_design_positions.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/module_card.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/translation_settings.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
  src/Adapter/Webservice/WebserviceKeyEraser.php
  src/Adapter/Webservice/WebserviceKeyStatusModifier.php
  src/Core/Grid/Definition/Factory/WebserviceKeyDefinitionFactory.php
  src/Core/Grid/Query/WebserviceKeyQueryBuilder.php
  src/Core/Search/Filters/WebserviceKeyFilters.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceController.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/webservice.yml
  src/PrestaShopBundle/Resources/config/services/adapter/data_configuration.yml
  src/PrestaShopBundle/Resources/config/services/adapter/webservice.yml
  src/PrestaShopBundle/Resources/config/services/core/grid.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/WebservicePage/webservice.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/WebservicePage/webservice_settings.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/WebservicePage/webservice_settings.twig
Labels: Improvement, QA ✔️, develop

#9124 Check the created customer in the front office and delete customer with both mode
  tests/E2E/test/campaigns/common_scenarios/address.js
  tests/E2E/test/campaigns/common_scenarios/customer.js
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/campaigns/full/09_customer/1_create_customer.js
  tests/E2E/test/campaigns/full/09_customer/2_create_address.js
  tests/E2E/test/campaigns/full/09_customer/addresses/1_create_edit_delete_address.js
  tests/E2E/test/campaigns/full/09_customer/customer_settings/1_create_edit_delete_customer.js
  tests/E2E/test/campaigns/full/09_customer/customer_settings/2_create_customer_in_FO.js
  tests/E2E/test/campaigns/full/09_customer/customer_settings/create_edit_delete_customer.js
  tests/E2E/test/campaigns/full/15_design/2_pages/2_page.js
  tests/E2E/test/campaigns/high/09_customer/2_create_address.js
  tests/E2E/test/campaigns/high/09_customer/3_create_customer_in_FO.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/helpers.js
  tests/E2E/test/selectors/BO/customers/customer.js
  tests/E2E/test/selectors/FO/access_page.js
  tests/E2E/test/selectors/FO/add_account_page.js
Labels: Improvement, QA ✔️, TE, develop

#8941 Click on read more
  tests/E2E/test/campaigns/common_scenarios/module.js
  tests/E2E/test/campaigns/full/10_module/8_read_more_module.js
  tests/E2E/test/selectors/BO/menu.js
  tests/E2E/test/selectors/BO/module_page.js
Labels: Feature, QA ✔️, TE, develop

#9274 Adding check all the product status
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/high/06_catalogbulkaction/catalogbulkaction.js
  tests/E2E/test/clients/catalogbulkaction.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/product/product.js
  tests/E2E/test/selectors/BO/catalogpage/index.js
Labels: Improvement, QA ✔️, develop

#9275 Create, edit and delete Linkwidget
  tests/E2E/test/campaigns/common_scenarios/linkwidget.js
  tests/E2E/test/campaigns/full/15_design/3_link_widget/01_linkWidget.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/common.webdriverio.js
  tests/E2E/test/selectors/BO/design/link_widget.js
  tests/E2E/test/selectors/FO/access_page.js
  tests/E2E/test/selectors/FO/order_page.js
  tests/E2E/test/selectors/FO/product_page.js
Labels: Feature, QA ✔️, develop

#10419 Change Javascript indent to 2 spaces, per AirBnb rules
  .eslintrc.js
Labels: Bug, develop

#10410 fix fixtures inconsistencies
  install-dev/fixtures/fashion/data/cart_product.xml
  install-dev/fixtures/fashion/data/feature_product.xml
  install-dev/fixtures/fashion/data/feature_value.xml
  install-dev/fixtures/fashion/data/order_detail.xml
  install-dev/fixtures/fashion/data/product.xml
  install-dev/fixtures/fashion/langs/en/data/feature_value.xml
  install-dev/fixtures/fashion/langs/fa/data/feature_value.xml
  install-dev/fixtures/fashion/langs/fr/data/feature.xml
  install-dev/fixtures/fashion/langs/fr/data/feature_value.xml
Labels: Bug, develop, waiting for QA

#10416 Improve perceived form horizontal alignment
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/_form.scss
Labels: Improvement, QA ✔️, develop

#10426 Handle boolean returns from RequestSql validation
  src/Adapter/SqlManager/SqlQueryValidator.php
Labels: Improvement, QA ✔️, develop

#9328 Create a Standard, Pack, Combination and Virtual product and check it in the Front Office
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/full/02_product/15_navigate_between_catalog_pages.js
  tests/E2E/test/campaigns/high/02_product/10_display_each_kind_of_product.js
  tests/E2E/test/campaigns/high/06_catalogbulkaction/catalogbulkaction.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/product/product.js
  tests/E2E/test/datas/combination.jpg
  tests/E2E/test/datas/music.jpg
  tests/E2E/test/datas/pack.jpeg
  tests/E2E/test/datas/standard.jpg
  tests/E2E/test/selectors/BO/menu.js
  tests/E2E/test/selectors/FO/product_page.js
Labels: Feature, QA ✔️, develop

#9108 Contact
  tests/E2E/test/campaigns/common_scenarios/contact.js
  tests/E2E/test/campaigns/full/12_shop_parameters/5_contact/1_create_edit_delete_contact_in_BO.js
  tests/E2E/test/campaigns/high/02_product/6_pack_stock.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/selectors/BO/customerService/customer_service.js
  tests/E2E/test/selectors/BO/customerService/index.js
  tests/E2E/test/selectors/BO/module_page.js
  tests/E2E/test/selectors/BO/shopParameters/shop_parameters.js
  tests/E2E/test/selectors/FO/contact_us_page.js
Labels: Feature, QA ✔️, TE, develop

#9111 Languages
  tests/E2E/test/campaigns/common_scenarios/attribute.js
  tests/E2E/test/campaigns/common_scenarios/feature.js
  tests/E2E/test/campaigns/common_scenarios/localization.js
  tests/E2E/test/campaigns/full/02_product/13_delete_product.js
  tests/E2E/test/campaigns/full/11_international/1_localization/1_create_edit_delete_language_in_BO.js
  tests/E2E/test/campaigns/full/14_discount/2_check_catalog_rule_price.js
  tests/E2E/test/campaigns/full/14_discount/3_check_discount_in_FO.js
  tests/E2E/test/campaigns/full/14_discount/4_check_vouchers_in_FO.js
  tests/E2E/test/campaigns/full/14_discount/5_check_discount_table_in_FO.js
  tests/E2E/test/campaigns/high/02_product/1_create_standard_product.js
  tests/E2E/test/campaigns/high/02_product/2_create_pack_of_product.js
  tests/E2E/test/campaigns/high/02_product/3_create_product_with_combination.js
  tests/E2E/test/campaigns/high/02_product/4_create_virtual_product.js
  tests/E2E/test/campaigns/high/02_product/9_check_shopping_cart.js
  tests/E2E/test/campaigns/regular/03_create_product.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/datas/language_farsi_flag.png
  tests/E2E/test/datas/language_spanish_flag.png
  tests/E2E/test/datas/language_suisse_flag.jpg
  tests/E2E/test/datas/no_image_available.png
  tests/E2E/test/selectors/BO/design/theme_and_logo.js
  tests/E2E/test/selectors/BO/international/index.js
  tests/E2E/test/selectors/BO/international/localization.js
  tests/E2E/test/selectors/BO/menu.js
  tests/E2E/test/selectors/FO/home_page.js
  tests/E2E/test/selectors/FO/index.js
  tests/E2E/test/selectors/FO/order_page.js
  tests/E2E/test/selectors/FO/product_page.js
Labels: Feature, QA ✔️, TE, develop

#9418 Check that all product are diplayed in the front Office
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/common_scenarios/stock.js
  tests/E2E/test/campaigns/high/02_product/01_create_standard_product.js
  tests/E2E/test/campaigns/high/02_product/02_create_pack_of_product.js
  tests/E2E/test/campaigns/high/02_product/03_create_product_with_combination.js
  tests/E2E/test/campaigns/high/02_product/04_create_virtual_product.js
  tests/E2E/test/campaigns/high/02_product/05_check_default_product_sort.js
  tests/E2E/test/campaigns/high/02_product/06_pack_stock.js
  tests/E2E/test/campaigns/high/02_product/07_check_all_products.js
  tests/E2E/test/campaigns/high/02_product/08_sort_product.js
  tests/E2E/test/campaigns/high/02_product/09_check_shopping_cart.js
  tests/E2E/test/campaigns/high/02_product/10_display_all_product.js
  tests/E2E/test/clients/product/product.js
  tests/E2E/test/selectors/BO/add_product_page.js
  tests/E2E/test/selectors/FO/access_page.js
Labels: Feature, QA ✔️, develop, waiting for rebase

#10427 Get link of the first ACTIVE tab in nav
  classes/controller/AdminController.php
Labels: Bug, QA ✔️, develop

#10438 Fix for Issue #10433 : Update lastName and firstName max size
  classes/Address.php
Labels: Bug, QA ✔️, develop

#9419 Adding Increase and Decrease quantity of products using the arrow …
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/common_scenarios/stock.js
  tests/E2E/test/campaigns/full/01_orders/7_shopping_carts_view.js
  tests/E2E/test/campaigns/high/02_product/11_display_each_kind_of_product.js
  tests/E2E/test/campaigns/high/08_stocks/1_group_of_product_quantity.js
  tests/E2E/test/campaigns/high/08_stocks/2_single_product_quantity.js
  tests/E2E/test/campaigns/high/08_stocks/3_check_order_movement.js
  tests/E2E/test/campaigns/high/08_stocks/4_update_product_quantity.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/stocks.js
  tests/E2E/test/selectors/BO/catalogpage/stocksubmenu/movements.js
  tests/E2E/test/selectors/BO/catalogpage/stocksubmenu/stock.js
  tests/E2E/test/selectors/BO/menu.js
Labels: Improvement, QA ✔️, develop

#10428 Fixes issue #10417 incorrect argument order
  classes/Manufacturer.php
Labels: Bug, QA ✔️, develop

#9107 Edit demo product and check info
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/full/02_product/14_edit_check_demo_product_in_BO.js
  tests/E2E/test/campaigns/high/02_product/01_create_standard_product.js
  tests/E2E/test/campaigns/high/02_product/02_create_pack_of_product.js
  tests/E2E/test/campaigns/high/02_product/03_create_product_with_combination.js
  tests/E2E/test/campaigns/high/02_product/04_create_virtual_product.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/product/check_product.js
  tests/E2E/test/clients/product/product.js
  tests/E2E/test/selectors/BO/add_product_page.js
  tests/E2E/test/selectors/BO/catalogpage/index.js
Labels: Feature, QA ✔️, TE, develop, waiting for rebase

#9423 Create Order with account
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/campaigns/full/01_orders/6_delete_shopping_carts.js
  tests/E2E/test/campaigns/high/01_orders/2_create_order_in_FO.js
  tests/E2E/test/campaigns/high/01_orders/4_create_order_with_account.js
  tests/E2E/test/campaigns/install_upgrade/02_autoupgrade.js
  tests/E2E/test/campaigns/install_upgrade/03_rollback.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/selectors/FO/index.js
  tests/E2E/test/selectors/FO/order_page.js
  tests/E2E/test/selectors/FO/product_page.js
Labels: Feature, develop

#10422 Add stock location through ps_stock_available table
  admin-dev/themes/default/public/theme.css
  admin-dev/themes/default/sass/controllers/_products.sass
  admin-dev/themes/default/template/controllers/orders/_customized_data.tpl
  admin-dev/themes/default/template/controllers/orders/_product_line.tpl
  admin-dev/themes/default/template/controllers/orders/helpers/view/view.tpl
  classes/Product.php
  classes/order/Order.php
  classes/stock/StockAvailable.php
  controllers/admin/AdminOrdersController.php
  install-dev/data/db_structure.sql
  install-dev/upgrade/sql/1.7.5.0.sql
  src/Adapter/CombinationDataProvider.php
  src/Adapter/Product/AdminProductWrapper.php
  src/Adapter/Product/ProductDataProvider.php
  src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Form/Admin/Product/ProductCombination.php
  src/PrestaShopBundle/Form/Admin/Product/ProductQuantity.php
  src/PrestaShopBundle/Model/Product/AdminModelAdapter.php
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combination.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Panels/combinations.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/product.html.twig
Labels: Bug, Feature, QA ✔️, develop

#10229 Mobile Menu: improve UX/UI of the mobile menu
  themes/classic/_dev/css/components/mainmenu.scss
  themes/classic/_dev/css/theme.scss
  themes/classic/_dev/js/components/top-menu.js
  themes/classic/assets/css/theme.css
  themes/classic/assets/js/theme.js
Labels: Improvement, QA ✔️, develop

#8237 Fixed bug in AdminGroupsController when adding ModulesRestrictions to group in multishop configuration
  classes/Group.php
  classes/module/Module.php
  controllers/admin/AdminGroupsController.php
  controllers/admin/AdminOrdersController.php
Labels: Bug, QA ✔️, develop

#10485 Minor migrated Webservice improvements
  src/Core/Webservice/ServerRequirementsChecker.php
  src/Core/Webservice/ServerRequirementsCheckerInterface.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceController.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Webservice/WebserviceConfigurationType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_handler.yml
  src/PrestaShopBundle/Resources/config/services/core/configuration.yml
  src/PrestaShopBundle/Resources/config/services/core/webservice.yml
  tests/Unit/Core/Webservice/ServerRequirementsCheckerTest.php
  tests/Unit/Core/Webservice/WebserviceCanBeEnabledConfigurationCheckerTest.php
Labels: Improvement, QA ✔️, develop, migration

#10571 Fix broken service definition
  src/PrestaShopBundle/Resources/config/services/core/form.yml
Labels: Bug, QA ✔️, develop, migration

#9119 Create attribute
  tests/E2E/test/campaigns/common_scenarios/attribute.js
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/full/04_attribute/1_create_edit_delete_attribute_value.js
  tests/E2E/test/campaigns/full/04_attribute/2_create_attribute.js
  tests/E2E/test/campaigns/high/01_orders/1_create_order_in_BO.js
  tests/E2E/test/campaigns/high/04_attribute/1_create_edit_delete_attribute_value.js
  tests/E2E/test/campaigns/high/08_stocks/3_check_order_movement.js
  tests/E2E/test/clients/attribute_and_feature.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/datas/t_shirt_gris.jpg
  tests/E2E/test/selectors/BO/add_product_page.js
  tests/E2E/test/selectors/BO/catalogpage/attribute_submenu.js
  tests/E2E/test/selectors/FO/product_page.js
  tests/E2E/test/selectors/FO/search_product_page.js
Labels: Improvement, QA ✔️, TE, develop

#10572 Update Full tests
  tests/E2E/test/campaigns/common_scenarios/category.js
  tests/E2E/test/campaigns/common_scenarios/file.js
  tests/E2E/test/campaigns/common_scenarios/localization.js
  tests/E2E/test/campaigns/common_scenarios/module.js
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/full/01_orders/4_check_adding_product_to_cart_with_unavailable_quantities.js
  tests/E2E/test/campaigns/full/01_orders/7_export_shopping_carts.js
  tests/E2E/test/campaigns/full/02_product/01_create_standard_product.js
  tests/E2E/test/campaigns/full/09_customer/customer_settings/2_create_customer_in_FO.js
  tests/E2E/test/campaigns/full/10_module/5_check_addons_catalog_page.js
  tests/E2E/test/campaigns/full/10_module/6_check_notifications.js
  tests/E2E/test/campaigns/full/10_module/7_discover_module.js
  tests/E2E/test/campaigns/full/10_module/8_read_more_module.js
  tests/E2E/test/campaigns/high/10_module/3_search_module.js
  tests/E2E/test/campaigns/high/10_module/4_sort_module.js
  tests/E2E/test/campaigns/high/12_shop_parameters/2_open_all_menu_links.js
  tests/E2E/test/campaigns/high/13_employee/1_employee.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/helpers.js
  tests/E2E/test/selectors/BO/catalogpage/Manufacturers/brands.js
  tests/E2E/test/selectors/BO/catalogpage/category_submenu.js
  tests/E2E/test/selectors/BO/international/index.js
  tests/E2E/test/selectors/BO/international/translations.js
  tests/E2E/test/selectors/BO/menu.js
  tests/E2E/test/selectors/BO/module_page.js
  tests/E2E/test/selectors/BO/pages_form.js
  tests/E2E/test/selectors/BO/shopParameters/shop_parameters.js
  tests/E2E/test/selectors/FO/add_account_page.js
Labels: Refactoring, TE, develop

#10569 Update Grid definition Ids
  install-dev/data/xml/hook.xml
  src/Core/Grid/Definition/Factory/BackupDefinitionFactory.php
  src/Core/Grid/Definition/Factory/EmailLogsDefinitionFactory.php
  src/Core/Grid/Definition/Factory/LogGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/MetaGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/RequestSqlGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/WebserviceKeyDefinitionFactory.php
  tests/Integration/PrestaShopBundle/Controller/Api/Improve/Design/PositionsControllerTest.php
Labels: Improvement, develop, migration

#10382 Bug when advanced stock management is enabled in Product Shipping page
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_shipping.html.twig
Labels: 1.7.5.x, Bug, develop

#10448 Fatal error while adding tags
  classes/Tag.php
Labels: Bug, develop

#10601 Use attr('data-') instead of data
  admin-dev/themes/new-theme/js/pages/module/controller.js
  admin-dev/themes/new-theme/public/module.bundle.js
Labels: 1.7.5.x, Bug, QA ✔️

#10662 Update native modules
  composer.lock
Labels: 1.7.5.x, Improvement

#8786 Replace serialize with json_encode
  admin-dev/functions.php
  classes/Cart.php
  classes/controller/AdminController.php
  classes/helper/HelperList.php
  install-dev/fixtures/fashion/data/cart.xml
Labels: 1.6.1.x, Bug, QA ✔️

#8763 Catch all Swift exceptions in Mail::Send()
  classes/Mail.php
Labels: 1.6.1.x, Bug, QA ✔️

#8758 Adding "¤" and "|" to isName()
  classes/Validate.php
Labels: 1.6.1.x, Bug, QA ✔️

#8658 Removed duplicate expressions
  themes/default-bootstrap/order-opc-new-account.tpl
Labels: 1.6.1.x, Improvement, QA ✔️

#8274 Disallow the negative discounts in orders
  controllers/admin/AdminOrdersController.php
Labels: QA ✔️

#8321 Fix Module configure permission
  controllers/admin/AdminModulesController.php
Labels: 1.6.1.x, QA ✔️

#8828 Stop sending a copy of the contact message to the "author" (avoid spam)
  controllers/front/ContactController.php
Labels: 1.6.1.x, Critical, QA ✔️

#10656 Fix grid ids in migrated JS
  admin-dev/themes/new-theme/js/pages/email/index.js
  admin-dev/themes/new-theme/js/pages/sql-manager/index.js
  admin-dev/themes/new-theme/js/pages/webservice/index.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
  src/Core/Grid/Presenter/GridPresenter.php
Labels: 1.7.5.x, Bug, QA ✔️, migration

#9341 Identity (Selenium tests)
  tests/E2E/package.json
  tests/E2E/prepare-shop.php
  tests/E2E/test/campaigns/common_scenarios/customer.js
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/campaigns/selenium/identity.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/customer.js
  tests/E2E/test/selectors/FO/access_page.js
  tests/E2E/test/selectors/FO/add_account_page.js
  tests/E2E/test/selectors/FO/order_page.js
  tests/E2E/test/selectors/FO/product_page.js
Labels: Feature, QA ✔️, TE, develop

#10716 Fix unit tests if Addons API doesn't give us modules
  classes/module/Module.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/PositionsController.php
  src/PrestaShopBundle/Controller/Api/Improve/Design/PositionsController.php
  tests/Integration/PrestaShopBundle/Controller/Admin/Improve/Design/PositionsControllerTest.php
  tests/Integration/PrestaShopBundle/Controller/Api/Improve/Design/PositionsControllerTest.php
  tests/resources/modules/bankwire/bankwire.php
Labels: 1.7.5.x, Bug

#10643 FO: Fix password validation message
  themes/classic/templates/_partials/form-fields.tpl
Labels: Bug, Needs port on StarterTheme, QA ✔️, develop

#10705 Move position column template
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/position.html.twig
Labels: 1.7.5.x, Bug, QA ✔️, migration

#10681 Fix module catalog js & css issues
  admin-dev/themes/new-theme/js/pages/module/controller.js
  admin-dev/themes/new-theme/public/module.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/_modulescards.scss
  admin-dev/themes/new-theme/scss/pages/_modules.scss
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/card_grid.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/card_grid_addons.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/card_list.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/grid.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/grid_manage_installed.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/sorting.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/alerts.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/catalog-refresh.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/common.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/manage.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/updates.html.twig
  tests/E2E/test/selectors/BO/module_page.js
  tests/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
Labels: 1.7.5.x, Bug, QA ✔️

#10594 Bring back functional tests
  .travis.yml
  tests/E2E/test/selectors/FO/index.js
  themes/classic/modules/ps_languageselector/ps_languageselector.tpl
Labels: Bug, develop

#10724 Clean php-cs-fixer files
  tests/phpcs/legacy.xml
  tests/phpcs/prestashop.xml
Labels: Improvement, develop

#10680 Hide arguments in debug trace page
  classes/exception/PrestaShopException.php
Labels: 1.6.1.x, Bug, QA ✔️

#5378 Add a fallback to curl when file_get_content() return an empty response
  cache/cacert.pem
  classes/Tools.php
  config/defines.inc.php
Labels: 1.6.1.x, Bug, Code ✔️, Improvement, QA ✔️

#10725 hide delete button on ordered cart
  controllers/admin/AdminCartsController.php
Labels: 1.7.5.x, Improvement, QA ✔️

#10736 Use new routes for quick access
  install-dev/data/xml/quick_access.xml
Labels: 1.7.5.x, Bug, QA ✔️

#10726 Module manager improvement (search, categories, configure button)
  admin-dev/themes/new-theme/js/pages/module/controller.js
  admin-dev/themes/new-theme/public/module.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/pages/_modules.scss
  src/Adapter/Module/AdminModuleDataProvider.php
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/dropdown_categories.html.twig
  src/PrestaShopBundle/Service/DataProvider/Admin/CategoriesProvider.php
Labels: 1.7.5.x, Bug, QA ✔️

#10462 Fix wrong display of the brand page
  admin-dev/themes/default/template/helpers/form/form.tpl
Labels: 1.7.5.x, Bug, Code ✔️, QA ✔️

#10728 FilterParametersUpdater manages filters in a better way
  src/Adapter/Product/AdminProductDataProvider.php
  src/Adapter/Product/FilterParametersUpdater.php
  src/Core/Exception/ProductException.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
Labels: 1.7.5.x, Bug, QA ✔️
