Repository PrestaShop/PrestaShop, pull requests merged in 2018-07, with the labels that each got.

#9241 Fix Version service namepsace usage
  src/Core/Localization/Pack/Factory/LocalizationPackFactoryInterface.php
  src/Core/Localization/Pack/Loader/RemoteLocalizationPackLoader.php
Labels: develop

#9245 Can't create or edit a category
  admin-dev/themes/default/template/helpers/uploader/ajax.tpl
  admin-dev/themes/default/template/helpers/uploader/simple.tpl
Labels: 1.7.4.x, QA-approved, bug fix

#9243 Fix show sql action in logs page
  admin-dev/themes/new-theme/js/components/grid.js
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  src/Core/Grid/Definition/Factory/LogGridDefinitionFactory.php
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Actions/Grid/delete_all_logs.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Actions/Grid/export_to_sql_manager.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Actions/Grid/simple.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/grid_actions.html.twig
Labels: QA-approved, bug fix, develop

#9254 Merge 1.7.4.x in develop
  CONTRIBUTORS.md
  admin-dev/themes/default/template/helpers/uploader/ajax.tpl
  admin-dev/themes/default/template/helpers/uploader/simple.tpl
  classes/module/Module.php
  composer.lock
  docs/CHANGELOG.txt
  docs/readme_de.txt
  docs/readme_en.txt
  docs/readme_es.txt
  docs/readme_fr.txt
  docs/readme_it.txt
  src/PrestaShopBundle/Resources/config/services/bundle/cache.yml
  var/SymfonyRequirements.php
Labels: develop, improvement

#9094 Migrate Improve > Shipping > Preferences controller
  classes/Link.php
  controllers/admin/AdminShippingController.php
  src/Adapter/Carrier/CarrierDataProvider.php
  src/Adapter/Carrier/CarrierOptionsConfiguration.php
  src/Adapter/Carrier/HandlingConfiguration.php
  src/PrestaShopBundle/Controller/Admin/Improve/Shipping/PreferencesController.php
  src/PrestaShopBundle/Form/Admin/Improve/Shipping/Preferences/CarrierOptionsType.php
  src/PrestaShopBundle/Form/Admin/Improve/Shipping/Preferences/HandlingType.php
  src/PrestaShopBundle/Form/Admin/Improve/Shipping/Preferences/PreferencesFormDataProvider.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/_improve.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/shipping/preferences.yml
  src/PrestaShopBundle/Resources/config/services/adapter/data_configuration.yml
  src/PrestaShopBundle/Resources/config/services/adapter/data_provider.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_handler.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/Shipping/Preferences/Blocks/shipping_preferences_carrier_options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Shipping/Preferences/Blocks/shipping_preferences_handling.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Shipping/Preferences/preferences.html.twig
  tests/PrestaShopBundle/Controller/ControllerTest.php
Labels: QA-approved, develop, new feature

#9235 Corrects a bug when importing store contacts
  controllers/admin/AdminImportController.php
Labels: QA-approved, bug fix, develop

#9234 Fix override handling when PS_DISABLE_OVERRIDES is used
  classes/PrestaShopAutoload.php
  classes/Tools.php
  tests/Unit/Classes/PrestaShopAutoloadTest.php
Labels: QA-approved, bug fix, develop

#9257 problem overriding getRobotsContent in Tools.php
  classes/Tools.php
Labels: 1.7.4.x, QA-approved, bug fix

#9252 add combinations in cart summary
  themes/classic/templates/checkout/_partials/cart-summary-product-line.tpl
Labels: 1.7.4.x, Needs port on StarterTheme, QA-approved, bug fix

#9256 Improve resolving of column options
  src/Core/Grid/Column/AbstractColumn.php
  src/Core/Grid/Column/ColumnInterface.php
  src/Core/Grid/Column/Type/Common/ActionColumn.php
  src/Core/Grid/Column/Type/Common/BulkActionColumn.php
  src/Core/Grid/Column/Type/Common/DateTimeColumn.php
  src/Core/Grid/Column/Type/Status/SeverityLevelColumn.php
  src/Core/Grid/Presenter/GridPresenter.php
Labels: develop, improvement

#9268 Added .htaccess to var folder
  var/.htaccess
Labels: 1.7.4.x, Bug

#9101 Fix have cart rule today
  classes/CartRule.php
  install-dev/data/db_structure.sql
  install-dev/upgrade/sql/1.7.4.1.sql
  tests/Unit/Core/Cart/AbstractCartTest.php
  tests/Unit/Core/Cart/Adding/CartRule/AddRuleTest.php
Labels: 1.7.4.x, Bug, QA ✔️

#9237 Fixed bug with friendly URLs and Media Servers
  classes/Tools.php
Labels: 1.7.4.x, Bug

#9261 Update Controller name for link generation to modules catalog
  classes/controller/AdminController.php
Labels: 1.7.4.x, Bug, QA ✔️, waiting for QA

#9270 Apache 2.4 configuration
  admin-dev/backups/.htaccess
  admin-dev/export/.htaccess
  admin-dev/import/.htaccess
  app/.htaccess
  bin/.htaccess
  cache/.htaccess
  classes/.htaccess
  config/.htaccess
  config/xml/.htaccess
  controllers/.htaccess
  docs/.htaccess
  docs/csv_import/.htaccess
  download/.htaccess
  img/.htaccess
  localization/.htaccess
  mails/.htaccess
  modules/.htaccess
  override/.htaccess
  pdf/.htaccess
  src/.htaccess
  themes/.htaccess
  themes/classic/_dev/.htaccess
  themes/classic/config/.htaccess
  tools/htmlpurifier/.htaccess
  tools/parser_sql/.htaccess
  tools/profiling/.htaccess
  translations/.htaccess
  vendor/.htaccess
Labels: 1.7.4.x, Bug, Needs port on StarterTheme, QA ✔️

#9220 Ability to use widget block from specific hook
  config/smartyfront.config.inc.php
Labels: 1.7.4.x, Bug, QA ✔️

#9242 Introducing reusable way to display KPIs blocks in Back Office modern pages
  admin-dev/themes/new-theme/scss/components/layout/_kpi.scss
  js/admin.js
  src/Adapter/Configuration/KpiConfiguration.php
  src/Adapter/Kpi/EnabledLanguagesKpi.php
  src/Adapter/Kpi/MainCountryKpi.php
  src/Adapter/Kpi/TranslationsKpi.php
  src/Core/Kpi/KpiInterface.php
  src/Core/Kpi/RenderableKpi.php
  src/Core/Kpi/Row/KpiRow.php
  src/Core/Kpi/Row/KpiRowFactory.php
  src/Core/Kpi/Row/KpiRowFactoryInterface.php
  src/Core/Kpi/Row/KpiRowInterface.php
  src/Core/Kpi/Row/KpiRowPresenter.php
  src/Core/Kpi/Row/KpiRowPresenterInterface.php
  src/PrestaShopBundle/Controller/Admin/CommonController.php
  src/PrestaShopBundle/Controller/Admin/TranslationsController.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/translations.yml
  src/PrestaShopBundle/Resources/config/services/adapter/kpi.yml
  src/PrestaShopBundle/Resources/config/services/adapter/services.yml
  src/PrestaShopBundle/Resources/config/services/core/kpi.yml
  src/PrestaShopBundle/Resources/views/Admin/Common/Kpi/kpi_row.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Translations/translations_settings.html.twig
Labels: Improvement, QA ✔️, develop

#9258 Limit subquery results in upgrade sql 1.7.0.0
  install-dev/upgrade/sql/1.7.0.0.sql
Labels: 1.7.4.x, Bug, QA ✔️

#9255 Fix rendering of theme catalog page
  src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeCatalogController.php
Labels: Bug, QA ✔️, develop

#9265 Can't upload an image in the product page
  classes/Hook.php
Labels: Bug, QA ✔️, develop

#9284 Add tests for grid
  tests/Unit/Core/Grid/DataProvider/DoctrineGridDataProviderTest.php
  tests/Unit/Core/Grid/Definition/Factory/AbstractGridDefinitionFactoryTest.php
  tests/Unit/Core/Grid/Presenter/GridPresenterTest.php
Labels: Improvement, develop

#9283 Update column naming
  src/Core/Grid/Column/Type/Common/BulkActionColumn.php
  src/Core/Grid/Column/Type/Common/DateTimeColumn.php
  src/Core/Grid/Column/Type/DataColumn.php
  src/Core/Grid/Column/Type/Employee/EmployeeNameWithAvatarColumn.php
  src/Core/Grid/Column/Type/Status/SeverityLevelColumn.php
  src/Core/Grid/Definition/Factory/LogGridDefinitionFactory.php
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/bulk_action.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/data.html.twig
Labels: Improvement, develop

#9282 Cleanup ModuleTemplateLoader
  src/PrestaShopBundle/Twig/Locator/ModuleTemplateLoader.php
  tests/PrestaShopBundle/Twig/Locator/ModuleTemplateLoaderTest.php
Labels: Bug, develop

#9290 Fix grid tests after column names update
  tests/Unit/Core/Grid/Definition/Factory/AbstractGridDefinitionFactoryTest.php
  tests/Unit/Core/Grid/Presenter/GridPresenterTest.php
Labels: Bug, develop

#9293 Rename routing file catalog.yml to _catalog.yml to follow routing structure
  src/PrestaShopBundle/Resources/config/routing/admin/sell/_sell.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/_catalog.yml
Labels: Improvement, develop

#9298 Fix/remove mbo from tests
  tests/Integration/classes/module/ModuleGetOverrideTest.php
Labels: 1.7.4.x, Bug

#9297 Fix display when a module uses $this->bootstrap = false;
  admin-dev/themes/default/public/theme.css
  admin-dev/themes/default/sass/partials/_backward.sass
Labels: 1.7.4.x, Bug, QA ✔️

#9295 Fix free shipping display on cart
  src/Core/Cart/CartRuleCalculator.php
Labels: 1.7.4.x, Bug, QA ✔️

#9300 Fix grid sorting by
  src/PrestaShopBundle/Controller/ArgumentResolver/SearchParametersResolver.php
Labels: BO, Bug, QA ✔️, develop

#9288 Fix Cart::isVirtualCart() method when cart is empty
  classes/Cart.php
Labels: 1.7.4.x, Bug, QA ✔️

#9271 Catch more exceptions during install & display the error intead of a JS error
  install-dev/controllers/http/process.php
  install-dev/theme/js/process.js
  src/PrestaShopBundle/Install/Install.php
Labels: 1.7.4.x, Bug, QA ✔️

#9299 Fix error while duplicating a product when catalog specific price rules are stored
  classes/SpecificPrice.php
Labels: 1.7.4.x, Bug, QA ✔️

#9315 Fix not visible category display
  controllers/front/listing/CategoryController.php
Labels: 1.7.4.x, Bug, QA ✔️

#9311 Apply shop context in configuration
  src/Adapter/Configuration.php
Labels: BO, Improvement, QA ✔️, develop

#9264 Update cart.js
  themes/_core/js/cart.js
Labels: Improvement, QA ✔️, develop

#9302 Reduce the number of ajax calls if the fixtures are not too larges and if there's enough memory available
  install-dev/controllers/http/process.php
Labels: 1.7.4.x, Improvement, QA ✔️

#9286 Grid/reset action
  admin-dev/themes/new-theme/js/app/utils/reset_search.js
  admin-dev/themes/new-theme/js/components/grid.js
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  src/Core/Grid/Definition/Factory/LogGridDefinitionFactory.php
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
Labels: Bug, QA ✔️, develop

#9306 Add a link to the addons' favicon generator
  controllers/admin/AdminThemesController.php
Labels: Improvement, QA ✔️, develop

#9267 Unable to copy theme translations
  controllers/admin/AdminTranslationsController.php
Labels: Bug, QA ✔️, develop

#9250 Implement addBefore() & addAfter() methods of ColumnCollection
  src/Core/Grid/Column/ColumnCollection.php
  tests/Unit/Core/Grid/Column/ColumnCollectionTest.php
Labels: Improvement, develop, waiting for author

#9319 Phpdocs
  src/Adapter/Addons/AddonsDataProvider.php
  src/Adapter/Admin/AbstractAdminQueryBuilder.php
  src/Adapter/Admin/PagePreference.php
  src/Adapter/Admin/UrlGenerator.php
  src/Adapter/Assets/AssetUrlGeneratorTrait.php
  src/Adapter/Attribute/AdminAttributeGeneratorControllerWrapper.php
  src/Adapter/BestSales/BestSalesProductSearchProvider.php
  src/Adapter/Cart/CartPresenter.php
  src/Adapter/Category/CategoryDataProvider.php
  src/Adapter/Category/CategoryProductSearchProvider.php
  src/Adapter/Hook/HookInformationProvider.php
  src/Adapter/Image/ImageRetriever.php
  src/Adapter/Manufacturer/ManufacturerProductSearchProvider.php
  src/Adapter/Media/MediaServerConfiguration.php
  src/Adapter/Module/AdminModuleDataProvider.php
  src/Adapter/Module/Configuration/ModuleComplexConfigurationInterface.php
  src/Adapter/Module/Configuration/ModuleSelfConfigurator.php
  src/Adapter/Module/Module.php
  src/Adapter/Module/ModuleDataProvider.php
  src/Adapter/Module/ModuleDataUpdater.php
  src/Adapter/Module/ModulePresenter.php
  src/Adapter/Module/ModuleZip.php
  src/Adapter/Module/ModuleZipManager.php
  src/Adapter/Module/PrestaTrust/PrestaTrustChecker.php
  src/Adapter/Module/Tab/ModuleTabManagementSubscriber.php
  src/Adapter/Module/Tab/ModuleTabRegister.php
  src/Adapter/Module/Tab/ModuleTabUnregister.php
  src/Core/Addon/Module/ModuleInterface.php
Labels: Improvement, develop

#9339 CO: fix bug extra space: htaccess directive order
  admin-dev/backups/.htaccess
  admin-dev/export/.htaccess
  admin-dev/import/.htaccess
  app/.htaccess
  bin/.htaccess
  cache/.htaccess
  classes/.htaccess
  config/.htaccess
  config/xml/.htaccess
  controllers/.htaccess
  docs/.htaccess
  docs/csv_import/.htaccess
  download/.htaccess
  img/.htaccess
  localization/.htaccess
  mails/.htaccess
  modules/.htaccess
  override/.htaccess
  pdf/.htaccess
  src/.htaccess
  themes/.htaccess
  themes/classic/_dev/.htaccess
  themes/classic/config/.htaccess
  tools/htmlpurifier/.htaccess
  tools/parser_sql/.htaccess
  tools/profiling/.htaccess
  translations/.htaccess
  vendor/.htaccess
Labels: 1.7.4.x, Bug, Needs port on StarterTheme

#9327 Fixed Product form when stock management is disabled
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/product.html.twig
Labels: 1.7.4.x, Bug, QA ✔️

#9231 Fixed missing call of ObjectModel hooks in CMSCategory::delete()
  classes/CMSCategory.php
Labels: Bug, QA ✔️, develop

#9145 Bug correction when changing shipped state
  classes/order/OrderHistory.php
Labels: Bug, QA ✔️, develop

#9326 Module translations aren't working when using Smarty Extend into TPL
  classes/Smarty/SmartyCustom.php
  classes/Translate.php
  config/smartyfront.config.inc.php
Labels: 1.7.4.x, Bug, QA ✔️

#9330 It is impossible to create a SQL query "SELECT" - SQL Manager page
  classes/Tools.php
  composer.json
  composer.lock
Labels: 1.7.4.x, Bug, QA ✔️

#9335 Url does not update when changing product attributes
  themes/_core/js/facets.js
  themes/_core/js/product.js
  themes/core.js
  themes/core.js.map
Labels: 1.7.4.x, Bug, QA ✔️

#9345 Can't install prestashop in dev mode with open_basedir
  app/AppKernel.php
Labels: 1.7.4.x, Bug, QA ✔️

#9348 Fixed a misnamed variable
  classes/Product.php
Labels: 1.7.4.x, Bug, QA ✔️

#9344 [CO] add function to display information message
  classes/module/Module.php
Labels: Feature, QA ✔️, develop

#9354 Set correct Employee Css after update
  install-dev/upgrade/sql/1.7.4.1.sql
  install-dev/upgrade/sql/1.7.4.2.sql
Labels: 1.7.4.x, Bug, QA ✔️

#9253 Remove modules catalog controller
  classes/Link.php
  install-dev/data/xml/tab.xml
  install-dev/langs/en/data/tab.xml
  install-dev/langs/fa/data/tab.xml
  install-dev/upgrade/sql/1.7.5.0.sql
  src/PrestaShopBundle/Controller/Admin/Improve/AddonsStoreController.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/modules/modules.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/Module/addons_store.html.twig
Labels: QA ✔️, develop

#9333 Small fixes for Sell -> Orders -> Invoices page
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/translations.bundle.js
  src/Core/Proxy/CachedFileFinderProxy.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/InvoicesController.php
  src/PrestaShopBundle/Entity/Repository/OrderInvoiceRepository.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/Invoices/InvoicesByDateDataProvider.php
  src/PrestaShopBundle/Resources/config/services/core/file.yml
  src/PrestaShopBundle/Resources/config/services/core/form.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Invoices/Blocks/generate_by_date.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Invoices/Blocks/generate_by_status.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Invoices/Blocks/invoice_options.html.twig
Labels: Bug, QA ✔️, develop

#9359 Allow configuration to save html data
  src/Adapter/Configuration.php
  src/Adapter/Shop/MaintenanceConfiguration.php
  src/Core/Form/FormHandler.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/MaintenanceController.php
  tests/Unit/Adapter/Module/Configuration/ModuleSelfConfiguratorTest.php
Labels: 1.7.4.x, Bug, QA ✔️

#9355 Allow to install PrestaShop without allow_url_fopen enabled
  classes/Language.php
Labels: 1.7.4.x, Bug, QA ✔️

#9358 AdminSearchController.php : Parameter must be an array or an object that implements Countable
  controllers/admin/AdminSearchController.php
Labels: 1.7.4.x, Bug, QA ✔️

#9112 Delete a category using the three options and script refactoring
  tests/E2E/test/campaigns/common_scenarios/category.js
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/full/02_product/10_check_product_page_buttons.js
  tests/E2E/test/campaigns/full/02_product/11_options_in_catalog_page.js
  tests/E2E/test/campaigns/full/03_category/1_create_category.js
  tests/E2E/test/campaigns/full/03_category/1_create_edit_delete_category.js
  tests/E2E/test/campaigns/full/03_category/2_delete_category_with_three_mode.js
  tests/E2E/test/campaigns/full/03_category/2_update_category.js
  tests/E2E/test/campaigns/full/03_category/3_delete_category.js
  tests/E2E/test/campaigns/full/15_design/1_theme_catalog/1_check_addons_theme.js
  tests/E2E/test/campaigns/high/02_product/9_check_shopping_cart.js
  tests/E2E/test/campaigns/high/03_category/1_create_category.js
  tests/E2E/test/campaigns/high/03_category/1_create_edit_delete_category.js
  tests/E2E/test/campaigns/high/03_category/2_update_category.js
  tests/E2E/test/campaigns/high/03_category/3_delete_category.js
  tests/E2E/test/campaigns/high/11_international/translation.js
  tests/E2E/test/clients/category.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/datas/category_miniature_menu.jpeg
  tests/E2E/test/selectors/BO/add_product_page.js
  tests/E2E/test/selectors/BO/catalogpage/category_submenu.js
  tests/E2E/test/selectors/BO/module_page.js
  tests/E2E/test/selectors/FO/access_page.js
  tests/E2E/test/selectors/FO/category_page.js
Labels: TE, develop, waiting for QA

#9357 Core.js typeerror after updatecart
  themes/_core/js/product.js
  themes/core.js
  themes/core.js.map
Labels: 1.7.4.x, Bug, QA ✔️

#9361 IN: Set allow_url_fopen optional in the system step
  classes/ConfigurationTest.php
  install-dev/controllers/http/system.php
Labels: 1.7.4.x, Improvement, QA ✔️

#9365 Wrong generated template path when using getCurrentSubTemplate with a full path name.
  classes/module/Module.php
Labels: 1.7.4.x, Bug, QA ✔️

#9364 Fix JS error after add to cart
  themes/classic/_dev/js/components/block-cart.js
Labels: 1.7.4.x, Bug, Needs port on StarterTheme, QA ✔️

#9353 Correctly handle hyphens in search index
  classes/Search.php
  tests/Unit/Core/Business/Product/Search/SearchTest.php
Labels: Bug, Needs port on StarterTheme, QA ✔️, develop

#9276 Fix product quantity in order return details table
  themes/classic/templates/customer/order-return.tpl
Labels: Bug, Needs port on StarterTheme, QA ✔️, develop

#9371 ntree regeneration should be done also if the entity arg is empty during install
  src/PrestaShopBundle/Install/Install.php
Labels: 1.7.4.x, Bug, QA ✔️

#9374 fix multishop price calculation
  src/Core/Cart/CartRow.php
Labels: 1.7.4.x, Bug, QA ✔️

#9321 Add some fixes to the script and update scenario of onbording
  tests/E2E/test/campaigns/common_scenarios/shop_parameters.js
  tests/E2E/test/campaigns/high/08_stocks/1_group_of_product_quantity.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/selectors/BO/add_product_page.js
  tests/E2E/test/selectors/BO/catalogpage/Manufacturers/brands.js
  tests/E2E/test/selectors/BO/menu.js
Labels: 1.7.4.x, TE

#9384 Update README.md
  README.md
Labels: Improvement, QA ✔️, develop

#9318 Make documentation link on the dashboard point to the 1.7 docs instead of 1.6
  admin-dev/themes/default/template/controllers/dashboard/helpers/view/view.tpl
Labels: Bug, QA ✔️, develop

#9373 Prevent users from doubleclick on Payment button from #9351
  themes/_core/js/checkout-payment.js
  themes/core.js
  themes/core.js.map
Labels: 1.7.4.x, Bug, QA ✔️, develop

#9381 Fix label "Use this address for invoice too'"
  themes/classic/templates/checkout/_partials/address-form.tpl
Labels: Bug, Needs port on StarterTheme, QA ✔️, develop

#9372 Update OrderFollowController.php
  controllers/front/OrderFollowController.php
Labels: Bug, QA ✔️, develop

#9369 Combinations not working when token is disabled
  admin-dev/themes/new-theme/js/product-page/combination.js
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combination.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combinations.html.twig
Labels: Bug, QA ✔️, develop

#9368 [FO] Detect if there is already GET param in URL
  themes/_core/js/product.js
  themes/core.js
  themes/core.js.map
Labels: Bug, QA ✔️, develop

#9301 Improve E2E tests
  .travis.yml
  tests/E2E/README.md
  tests/E2E/package.json
  tests/E2E/test/campaigns/common_scenarios/common_installation.js
  tests/E2E/test/campaigns/full/02_product/12_check_tinymce_field_in_BO.js
  tests/E2E/test/campaigns/full/09_customer/addresses/create_edit_delete_address.js
  tests/E2E/test/campaigns/full/09_customer/customer_settings/create_edit_delete_customer.js
  tests/E2E/test/campaigns/high/09_customer/1_create_customer.js
  tests/E2E/test/campaigns/high/10_module/3_search_module.js
  tests/E2E/test/common.webdriverio.js
  tests/E2E/test/globals.webdriverio.js
  tests/E2E/test/selectors/BO/menu.js
Labels: Improvement, QA ✔️, develop

#9394 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improvement, develop
