Repository PrestaShop/PrestaShop, pull requests merged in 2018-04, with the labels that each got.

#8903 Add some fixes to the script
  tests/E2E/README.md
  tests/E2E/test/campaigns/common_scenarios/common_installation.js
  tests/E2E/test/campaigns/high/01_orders/1_create_order_in_BO.js
  tests/E2E/test/campaigns/high/04_attribute/1_create_attribute.js
  tests/E2E/test/campaigns/high/04_attribute/2_update_attribute.js
  tests/E2E/test/campaigns/high/04_attribute/3_delete_attribute_value.js
  tests/E2E/test/campaigns/high/04_attribute/4_delete_attribute.js
  tests/E2E/test/campaigns/install_upgrade/01_install.js
  tests/E2E/test/campaigns/install_upgrade/02_autoupgrade.js
  tests/E2E/test/campaigns/install_upgrade/03_rollback.js
  tests/E2E/test/clients/attribute_and_feature.js
  tests/E2E/test/clients/category.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/product/product.js
  tests/E2E/test/common.webdriverio.js
  tests/E2E/test/selectors/BO/catalogpage/attribute_submenu.js
  tests/E2E/test/selectors/FO/search_product_page.js
Labels: E2E

#8901 Check addons theme
  tests/E2E/test/campaigns/full/15_design/1_theme_and_logo/1_check_addons_theme.js
  tests/E2E/test/campaigns/full/15_design/2_pages/1_category.js
  tests/E2E/test/campaigns/full/15_design/2_pages/2_page.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/selectors/BO/design/index.js
  tests/E2E/test/selectors/BO/design/theme_and_logo.js
Labels: E2E

#8894 Delete feature with bulk actions
  tests/E2E/test/campaigns/common_scenarios/feature.js
  tests/E2E/test/campaigns/full/05_feature/1_create_edit_delete_feature.js
  tests/E2E/test/campaigns/full/05_feature/1_create_feature.js
  tests/E2E/test/campaigns/full/05_feature/2_update_feature.js
  tests/E2E/test/campaigns/full/05_feature/3_delete_feature.js
  tests/E2E/test/campaigns/high/05_feature/1_create_edit_delete_feature.js
  tests/E2E/test/campaigns/high/05_feature/1_create_feature.js
  tests/E2E/test/campaigns/high/05_feature/2_update_feature.js
  tests/E2E/test/campaigns/high/05_feature/3_delete_feature.js
  tests/E2E/test/selectors/BO/catalogpage/feature_submenu.js
  tests/E2E/test/selectors/FO/search_product_page.js
Labels: E2E

#8870 Options in catalog page
  tests/E2E/test/campaigns/full/02_product/11_options_in_catalog_page.js
  tests/E2E/test/selectors/BO/add_product_page.js
Labels: 1.7.x, E2E

#8911 Create order by a guest
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/campaigns/full/01_orders/4_create_order_without_account.js
  tests/E2E/test/campaigns/high/01_orders/1_create_order_in_BO.js
  tests/E2E/test/campaigns/high/01_orders/2_create_order_in_FO.js
  tests/E2E/test/datas/customer_and_address_data.js
  tests/E2E/test/selectors/BO/order.js
  tests/E2E/test/selectors/FO/product_page.js
Labels: E2E

#8898 Check generated combinations table
  tests/E2E/test/campaigns/high/02_product/3_create_product_with_combination.js
  tests/E2E/test/selectors/BO/add_product_page.js
Labels: E2E

#8869 Click on discover button
  tests/E2E/test/campaigns/full/10_module/7_discover_module.js
  tests/E2E/test/selectors/BO/module_page.js
Labels: 1.7.x, E2E

#8881 Check the pagination of product in the Front Office
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/full/02_product/11_check_pagination_of_product_in_FO.js
  tests/E2E/test/campaigns/high/02_product/7_check_all_products.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/product/product.js
  tests/E2E/test/selectors/BO/shopParameters/product_settings.js
  tests/E2E/test/selectors/BO/shopParameters/shop_parameters.js
  tests/E2E/test/selectors/FO/product_page.js
Labels: E2E

#8913 Fix issue with pack in fixtures (installer)
  install-dev/fixtures/fashion/data/pack.xml
  install-dev/fixtures/fashion/data/product.xml
  src/PrestaShopBundle/Install/XmlLoader.php
Labels: 1.7.x, QA-approved, Type: Bug Fix

#8921 Fixed CDN management in Performance page
  src/Adapter/Media/MediaServerConfiguration.php
Labels: QA-approved

#8924 Refactored Back Office controllers
  src/PrestaShopBundle/Controller/Admin/AddonsController.php
  src/PrestaShopBundle/Controller/Admin/AttachementProductController.php
  src/PrestaShopBundle/Controller/Admin/AttributeController.php
  src/PrestaShopBundle/Controller/Admin/CategoryController.php
  src/PrestaShopBundle/Controller/Admin/CombinationController.php
  src/PrestaShopBundle/Controller/Admin/CommonController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/PerformanceController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SystemInformationController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/MaintenanceController.php
  src/PrestaShopBundle/Controller/Admin/FeatureController.php
  src/PrestaShopBundle/Controller/Admin/Improve/AddonsStoreController.php
  src/PrestaShopBundle/Controller/Admin/ModuleController.php
  src/PrestaShopBundle/Controller/Admin/ProductImageController.php
  src/PrestaShopBundle/Controller/Admin/SpecificPriceController.php
  src/PrestaShopBundle/Controller/Admin/SupplierController.php
  src/PrestaShopBundle/Controller/Admin/VirtualProductController.php
  src/PrestaShopBundle/Controller/Admin/WarehouseController.php
Labels: 1.7.x, Type: Improvement

#8922 Fixed access to Front Office container from modules
  classes/module/Module.php
Labels: 1.7.x, Code reviewed, QA-approved

#8925 Stop generating RTL css file for the default theme using SASS
  admin-dev/themes/default/css/admin-theme_rtl.css
  admin-dev/themes/default/css/admin-theme_rtl.css.map
  admin-dev/themes/default/sass/admin-theme_rtl.sass
Labels: QA-approved

#8931 Out of stock message display only if customer can order the product
  themes/classic/templates/catalog/_partials/product-prices.tpl
Labels: 1.7.x, QA-approved

#8814 Module tab new subtree
  src/Adapter/Module/Tab/ModuleTabRegister.php
  src/Adapter/Module/Tab/ModuleTabUnregister.php
  src/PrestaShopBundle/Entity/Repository/TabRepository.php
Labels: 1.7.x, Code reviewed, QA-approved, Type: Improvement

#8920 Migrate Shop Parameters -> Customer Settings
  classes/Link.php
  controllers/admin/AdminCustomerPreferencesController.php
  src/Adapter/Customer/CustomerConfiguration.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/CustomerPreferencesController.php
  src/PrestaShopBundle/Form/Admin/ShopParameters/CustomerPreferences/CustomerPreferencesDataProvider.php
  src/PrestaShopBundle/Form/Admin/ShopParameters/CustomerPreferences/CustomerPreferencesFormHandler.php
  src/PrestaShopBundle/Form/Admin/ShopParameters/CustomerPreferences/GeneralType.php
  src/PrestaShopBundle/Resources/config/routing/admin/routing_shop_parameters.yml
  src/PrestaShopBundle/Resources/config/services.yml
  src/PrestaShopBundle/Resources/config/services/adapters.yml
  src/PrestaShopBundle/Resources/config/services/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/config/services/form/form_handler.yml
  src/PrestaShopBundle/Resources/config/services/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/form_services.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/customer_preferences_general.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/customer_preferences.html.twig
  tests/PrestaShopBundle/Controller/ControllerTest.php
Labels: 1.7.x, Code reviewed, QA-approved, Type: Feature

#8679 Catch Throwable errors on CLI install and check Theme instance in context
  install-dev/classes/controllerConsole.php
  install-dev/controllers/console/process.php
  install-dev/index_cli.php
  src/PrestaShopBundle/Install/AbstractInstall.php
  src/PrestaShopBundle/Install/Database.php
  src/PrestaShopBundle/Install/Install.php
Labels: 1.7.x, Code reviewed, QA-approved, Type: Bug Fix

#8944 Hide Logs page
  classes/Link.php
Labels: 1.7.x, Type: Bug Fix

#8843 Minor install improvements
  classes/Language.php
  install-dev/index.php
  install-dev/index_cli.php
  install-dev/init.php
  install-dev/install_version.php
  install-dev/missing_requirement.php
Labels: 1.7.x, QA-approved, Type: Improvement

#8909 Allow autoloading in modules for services use in BO
  app/AppKernel.php
Labels: 1.7.x, QA-approved, Type: Improvement

#8834 Adds missing Persian translations for data and samples
  install-dev/fixtures/fashion/langs/fa/data/attribute.xml
  install-dev/fixtures/fashion/langs/fa/data/attribute_group.xml
  install-dev/fixtures/fashion/langs/fa/data/attributegroup.xml
  install-dev/fixtures/fashion/langs/fa/data/carrier.xml
  install-dev/fixtures/fashion/langs/fa/data/category.xml
  install-dev/fixtures/fashion/langs/fa/data/customization_field.xml
  install-dev/fixtures/fashion/langs/fa/data/feature.xml
  install-dev/fixtures/fashion/langs/fa/data/feature_value.xml
  install-dev/fixtures/fashion/langs/fa/data/featurevalue.xml
  install-dev/fixtures/fashion/langs/fa/data/image.xml
  install-dev/fixtures/fashion/langs/fa/data/manufacturer.xml
  install-dev/fixtures/fashion/langs/fa/data/order_message.xml
  install-dev/fixtures/fashion/langs/fa/data/ordermessage.xml
  install-dev/fixtures/fashion/langs/fa/data/profile.xml
  install-dev/fixtures/fashion/langs/fa/data/scene.xml
  install-dev/fixtures/fashion/langs/fa/data/store.xml
  install-dev/fixtures/fashion/langs/fa/data/supplier.xml
  install-dev/fixtures/fashion/langs/fa/data/tag.xml
  install-dev/langs/fa/data/carrier.xml
  install-dev/langs/fa/data/category.xml
  install-dev/langs/fa/data/cms_category.xml
  install-dev/langs/fa/data/configuration.xml
  install-dev/langs/fa/data/contact.xml
  install-dev/langs/fa/data/country.xml
  install-dev/langs/fa/data/gender.xml
  install-dev/langs/fa/data/group.xml
  install-dev/langs/fa/data/meta.xml
  install-dev/langs/fa/data/order_return_state.xml
  install-dev/langs/fa/data/order_state.xml
  install-dev/langs/fa/data/profile.xml
  install-dev/langs/fa/data/quick_access.xml
  install-dev/langs/fa/data/risk.xml
  install-dev/langs/fa/data/stock_mvt_reason.xml
  install-dev/langs/fa/data/supplier_order_state.xml
  install-dev/langs/fa/data/supply_order_state.xml
  install-dev/langs/fa/data/tab.xml
Labels: 1.7.x, QA-approved, Type: Improvement

#8896 Optimize breadcrumb computation performances
  classes/Category.php
  controllers/admin/AdminImportController.php
  src/Adapter/Category/CategoryDataProvider.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Install/XmlLoader.php
Labels: 1.7.x, Code reviewed, Performance improvements, QA-approved, Type: Improvement

#8020 Fix not handled new tab ID during migration
  install-dev/upgrade/sql/1.7.0.0.sql
Labels: QA-approved, Type: Bug Fix

#8836 Replace Open Sans font with Vazir font for Farsi (BO default theme)
  admin-dev/themes/default/css/admin-theme.rtlfix
Labels: 1.7.x, QA-approved, Type: Improvement

#8837 Replace Open Sans font with Vazir font for Farsi (BO new theme)
  admin-dev/themes/new-theme/public/theme.rtlfix
Labels: 1.7.x, QA-approved, Type: Improvement

#8637 Update back-office menu style
  admin-dev/themes/default/config.rb
  admin-dev/themes/default/css/admin-theme.css
  admin-dev/themes/default/css/schemes/admin-theme-blue.css
  admin-dev/themes/default/css/schemes/admin-theme-contrast.css
  admin-dev/themes/default/css/schemes/admin-theme-flex.css
  admin-dev/themes/default/css/schemes/admin-theme-fruit.css
  admin-dev/themes/default/css/schemes/admin-theme-prune.css
  admin-dev/themes/default/js/admin-theme.js
  admin-dev/themes/default/sass/modules/_mixins.sass
  admin-dev/themes/default/sass/modules/_variables.sass
  admin-dev/themes/default/sass/partials/_content.sass
  admin-dev/themes/default/sass/partials/_header.sass
  admin-dev/themes/default/sass/partials/_nav.sass
  admin-dev/themes/default/sass/partials/_print.sass
  admin-dev/themes/default/sass/partials/_rtl.sass
  admin-dev/themes/default/template/header.tpl
  admin-dev/themes/default/template/layout.tpl
  admin-dev/themes/default/template/nav.tpl
  admin-dev/themes/new-theme/js/nav_bar.js
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/scss/components/layout/_content_div.scss
  admin-dev/themes/new-theme/scss/components/layout/_header_toolbar.scss
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
  admin-dev/themes/new-theme/scss/components/layout/_nav_bar.scss
  admin-dev/themes/new-theme/template/components/layout/employee_dropdown.tpl
  admin-dev/themes/new-theme/template/components/layout/nav_bar.tpl
  admin-dev/themes/new-theme/template/components/layout/non-responsive.tpl
  admin-dev/themes/new-theme/template/layout.tpl
  classes/controller/AdminController.php
Labels: 1.7.x, QA-approved, Type: Improvement

#8948 Fixed update of combinations
  src/Adapter/CombinationDataProvider.php
  src/PrestaShopBundle/Controller/Admin/CombinationController.php
Labels: 1.7.x, QA-approved, Type: Bug Fix

#8940 Check product availability in order step
  .travis.yml
  controllers/front/OrderController.php
  themes/classic/_dev/js/cart.js
  themes/classic/assets/js/theme.js
  themes/classic/templates/checkout/_partials/cart-detailed-actions.tpl
Labels: 1.7.x, QA-approved, Type: Bug Fix, report on StarterTheme

#8950 Fix regular tests
  tests/E2E/test/campaigns/common_scenarios/module.js
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/selectors/BO/access_page.js
  tests/E2E/test/selectors/BO/module_page.js
Labels: 1.7.x, E2E

#8946 Fix button show password height on Safari
  themes/classic/_dev/css/partials/_commons.scss
  themes/classic/assets/css/theme.css
Labels: 1.7.x, QA-approved, Type: Bug Fix

#8942 Tell if a currency is installed, get a list of installed currencies
  classes/Currency.php
Labels: 1.7.x, Type: Feature

#8882 Migrate import page
  admin-dev/themes/new-theme/js/pages/import/FormFieldToggle.js
  admin-dev/themes/new-theme/js/pages/import/ImportPage.js
  admin-dev/themes/new-theme/js/pages/import/index.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/sql-manager-helper.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/webpack.config.js
  classes/Link.php
  controllers/admin/AdminImportController.php
  src/Core/Configuration/IniConfiguration.php
  src/Core/Import/File/FileFinder.php
  src/Core/Import/File/FileRemoval.php
  src/Core/Import/File/FileUploader.php
  src/Core/Import/ImportDirectory.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ImportController.php
  src/PrestaShopBundle/Exception/FileUploadException.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Import/ImportFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Import/ImportFormHandler.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Import/ImportType.php
  src/PrestaShopBundle/Form/Admin/Type/TranslatorAwareType.php
  src/PrestaShopBundle/Resources/config/routing/admin/routing_advanced_parameters.yml
  src/PrestaShopBundle/Resources/config/services.yml
  src/PrestaShopBundle/Resources/config/services/core/configuration.yml
  src/PrestaShopBundle/Resources/config/services/core/import.yml
  src/PrestaShopBundle/Resources/config/services/core_services.yml
  src/PrestaShopBundle/Resources/config/services/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/config/services/form/form_handler.yml
  src/PrestaShopBundle/Resources/config/services/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Blocks/import_available_fields.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Blocks/import_file_history.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Blocks/import_panel.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Blocks/import_sample_files.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/import.html.twig
  src/PrestaShopBundle/Resources/views/Admin/layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/macros.html.twig
Labels: 1.7.x, QA-approved, Type: Feature

#7944 Suggestion - Call getPackageShippingCost of modules even if carrier is free
  classes/Cart.php
Labels: QA-approved

#8951 fix error display on cart quantity edition
  classes/Cart.php
  classes/Product.php
  controllers/front/CartController.php
  themes/classic/_dev/js/cart.js
  themes/classic/assets/js/theme.js
Labels: 1.7.x, QA-approved, Type: Bug Fix

#8965 Fix theme install with prestatrust modules
  src/Core/Addon/Theme/ThemeManager.php
Labels: 1.7.x, QA-approved, Type: Bug Fix

#8960 Fixed undefined class constant
  src/Core/Stock/StockManager.php
Labels: QA-approved

#8962 Properly handle set of the PK value in the EntityMapper
  src/Adapter/EntityMapper.php
Labels: Type: Bug Fix, develop

#8959 Able to pass hook as a parameter
  config/smartyfront.config.inc.php
Labels: Type: Improvement, develop

#8895 Allow override of every modern template
  src/PrestaShopBundle/Controller/Admin/AdvancedParameters/AdministrationController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/PerformanceController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SystemInformationController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/MaintenanceController.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
Labels: 1.7.x, QA-approved, Type: Bug Fix

#8831 Better handling of invalid modules from Addons API
  src/Adapter/Module/AdminModuleDataProvider.php
  src/Adapter/Module/Module.php
  src/Core/Addon/AddonsCollection.php
  src/Core/Addon/Module/ModuleManager.php
  src/PrestaShopBundle/Controller/Admin/CommonController.php
  src/PrestaShopBundle/Controller/Admin/ModuleController.php
Labels: 1.7.x, QA-approved, Type: Bug Fix

#8973 Fixed undefined class constant
  src/Core/Stock/StockManager.php
Labels: 1.7.3.x

#8246 Make PS compatible with PHP 7.2
  .travis.yml
  classes/Cart.php
  classes/Currency.php
  classes/ObjectModel.php
  classes/Tools.php
  classes/controller/AdminController.php
  classes/helper/HelperList.php
  classes/module/Module.php
  controllers/admin/AdminAttachmentsController.php
  controllers/admin/AdminAttributeGeneratorController.php
  controllers/admin/AdminCarrierWizardController.php
  controllers/admin/AdminCartRulesController.php
  controllers/admin/AdminCartsController.php
  controllers/admin/AdminCategoriesController.php
  controllers/admin/AdminCmsContentController.php
  controllers/admin/AdminCountriesController.php
  controllers/admin/AdminEmailsController.php
  controllers/admin/AdminEmployeesController.php
  controllers/admin/AdminGroupsController.php
  controllers/admin/AdminImportController.php
  controllers/admin/AdminLegacyLayoutController.php
  controllers/admin/AdminLoginController.php
  controllers/admin/AdminManufacturersController.php
  controllers/admin/AdminMetaController.php
  controllers/admin/AdminModulesController.php
  controllers/admin/AdminNotFoundController.php
  controllers/admin/AdminOrdersController.php
  controllers/admin/AdminPatternsController.php
  controllers/admin/AdminPaymentController.php
  controllers/admin/AdminPaymentPreferencesController.php
  controllers/admin/AdminReferrersController.php
  controllers/admin/AdminSearchController.php
  controllers/admin/AdminSuppliersController.php
  controllers/admin/AdminThemesController.php
  src/PrestaShopBundle/Api/QueryParamsCollection.php
  tests/Unit/Adapter/Module/Configuration/ModuleSelfConfiguratorTest.php
  tests/Unit/ContextMocker.php
  tools/profiling/Controller.php
Labels: QA-approved, Type: Feature

#8945 Return default values when api is unavailable
  src/PrestaShopBundle/Service/DataProvider/Marketplace/ApiClient.php
Labels: 1.7.x, QA-approved, Type: Bug Fix

#8975 Fix broken "you must first create a new language" link in BO Translations
  admin-dev/themes/default/template/controllers/translations/helpers/view/main.tpl
Labels: 1.7.3.x, QA-approved, Type: Bug Fix

#8916 Add tips in the back office to improve user experience
  admin-dev/themes/default/template/controllers/categories/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/images/content.tpl
  controllers/admin/AdminCategoriesController.php
  controllers/admin/AdminThemesController.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_general.html.twig
Labels: 1.7.x, QA-approved, Type: Improvement

#8970 Improved readability
  classes/controller/Controller.php
Labels: Code reviewed, develop

#8976 Set cache driver in container instead of env var CACHE_DRIVER
  app/AppKernel.php
  app/config/config_prod.yml
  app/config/set_parameters.php
Labels: QA-approved, Type: Bug Fix, develop

#8983 Parallelize builds
  .travis.yml
Labels: Type: Improvement, develop

#8954 Allowed robots access to assets requierd to be mobile-friendly
  classes/Tools.php
Labels: Code reviewed, QA-approved, Type: Bug Fix, develop

#8980 Remove deprecated message for DataCollectorInterface
  src/PrestaShopBundle/DataCollector/HookDataCollector.php
Labels: Type: Improvement, develop, waiting for rebase

#8752 Check product availability before validating orders
  classes/Cart.php
  classes/Pack.php
  classes/Product.php
  classes/checkout/CheckoutPaymentStep.php
  controllers/front/CartController.php
  tests/Unit/Core/Cart/AbstractCartTest.php
  tests/Unit/Core/Cart/Adding/Product/AddPackTest.php
Labels: 1.7.x, QA-approved, Type: Bug Fix

#8981 Set explicit version of MySQL in docker-compose.yml
  README.md
  docker-compose.yml
Labels: Code reviewed, QA-approved, Type: Bug Fix, develop

#8947 Hooks for recommended modules & themes
  admin-dev/themes/default/template/controllers/themes/helpers/options/options.tpl
  admin-dev/themes/default/template/footer.tpl
  admin-dev/themes/default/template/page_header_toolbar.tpl
  admin-dev/themes/new-theme/template/layout.tpl
  classes/controller/AdminController.php
  controllers/admin/AdminPaymentController.php
  controllers/admin/AdminThemesController.php
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.4.0.sql
Labels: Code reviewed, QA-approved, Type: Improvement, develop

#8833 Hide empty list if all variations are out of stock
  themes/classic/templates/catalog/_partials/product-variants.tpl
Labels: 1.7.x, Code reviewed, Needs port on StarterTheme, QA-approved, Type: Improvement

#8927 Remove default theme schemes (no longer used)
  admin-dev/themes/default/css/schemes/admin-theme-blue.css
  admin-dev/themes/default/css/schemes/admin-theme-blue.css.map
  admin-dev/themes/default/css/schemes/admin-theme-contrast.css
  admin-dev/themes/default/css/schemes/admin-theme-contrast.css.map
  admin-dev/themes/default/css/schemes/admin-theme-flex.css
  admin-dev/themes/default/css/schemes/admin-theme-flex.css.map
  admin-dev/themes/default/css/schemes/admin-theme-fruit.css
  admin-dev/themes/default/css/schemes/admin-theme-fruit.css.map
  admin-dev/themes/default/css/schemes/admin-theme-prune.css
  admin-dev/themes/default/css/schemes/admin-theme-prune.css.map
  admin-dev/themes/default/css/schemes/index.php
  admin-dev/themes/default/css/schemes_rtl/admin-theme-blue_rtl.css
  admin-dev/themes/default/css/schemes_rtl/admin-theme-blue_rtl.css.map
  admin-dev/themes/default/css/schemes_rtl/admin-theme-contrast_rtl.css
  admin-dev/themes/default/css/schemes_rtl/admin-theme-contrast_rtl.css.map
  admin-dev/themes/default/css/schemes_rtl/admin-theme-flex_rtl.css
  admin-dev/themes/default/css/schemes_rtl/admin-theme-flex_rtl.css.map
  admin-dev/themes/default/css/schemes_rtl/admin-theme-fruit_rtl.css
  admin-dev/themes/default/css/schemes_rtl/admin-theme-fruit_rtl.css.map
  admin-dev/themes/default/css/schemes_rtl/admin-theme-prune_rtl.css
  admin-dev/themes/default/css/schemes_rtl/admin-theme-prune_rtl.css.map
  admin-dev/themes/default/css/schemes_rtl/index.php
  admin-dev/themes/default/sass/schemes/admin-theme-blue.sass
  admin-dev/themes/default/sass/schemes/admin-theme-contrast.sass
  admin-dev/themes/default/sass/schemes/admin-theme-flex.sass
  admin-dev/themes/default/sass/schemes/admin-theme-fruit.sass
  admin-dev/themes/default/sass/schemes/admin-theme-prune.sass
  admin-dev/themes/default/sass/schemes/index.php
  admin-dev/themes/default/sass/schemes_rtl/admin-theme-blue_rtl.sass
  admin-dev/themes/default/sass/schemes_rtl/admin-theme-contrast_rtl.sass
  admin-dev/themes/default/sass/schemes_rtl/admin-theme-flex_rtl.sass
  admin-dev/themes/default/sass/schemes_rtl/admin-theme-fruit_rtl.sass
  admin-dev/themes/default/sass/schemes_rtl/admin-theme-prune_rtl.sass
  admin-dev/themes/default/sass/schemes_rtl/index.php
  controllers/admin/AdminEmployeesController.php
Labels: 1.7.x, QA-approved, Type: Improvement

#8830 Fix uninitialized $moreStepLabels in AdminImportController
  controllers/admin/AdminImportController.php
Labels: 1.7.x, Type: Bug Fix

#8979 Move administration page to proper location
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AdministrationController.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Administration/FormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Administration/GeneralType.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Administration/NotificationsType.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Administration/UploadQuotaType.php
  src/PrestaShopBundle/Resources/config/routing/admin/routing_advanced_parameters.yml
  src/PrestaShopBundle/Resources/config/services/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/config/services/form/form_handler.yml
  src/PrestaShopBundle/Resources/config/services/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/administration.html.twig
Labels: QA-approved, Type: Improvement, develop

#9008 Use getBoolean() instead of get() when configuration is bool in Product Settings page
  src/Adapter/Product/GeneralConfiguration.php
  src/Adapter/Product/PageConfiguration.php
  src/Adapter/Product/StockConfiguration.php
Labels: develop

#9005 Fix cannot order oos product even if it's allowed
  classes/Cart.php
Labels: 1.7.3.x, QA-approved
