Repository PrestaShop/PrestaShop, pull requests merged in 2019-03, with the labels that each got.

#12756 CO: Fix bug when create class override Address
  classes/CustomerAddress.php
Labels: Bug, develop

#12346 Add Category form builder & handler
  controllers/admin/AdminLegacyLayoutController.php
  src/Core/Form/IdentifiableObject/DataHandler/AbstractCategoryFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/CategoryFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/RootCategoryFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/CategoryFormDataProvider.php
  src/Core/Grid/Definition/Factory/CategoryGridDefinitionFactory.php
  src/Core/Grid/Filter/CategoryFilterFormFactory.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Form/Admin/Catalog/Category/AbstractCategoryType.php
  src/PrestaShopBundle/Form/Admin/Catalog/Category/CategoryType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/categories.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_handler.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/breadcrumb.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/delete_block.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/delete_categories_modal.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/listing_panel_footer.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/add.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/add_root.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/edit.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/edit_root.html.twig
Labels: Improvement, Wording ✔️, develop, migration

#12761 BO: Remove timeout from product image upload
  admin-dev/themes/default/js/bundle/product/form.js
Labels: Improvement, develop, waiting for QA

#12723 Patch to Issue #12500
  src/Adapter/Product/AdminProductWrapper.php
Labels: Bug, QA ✔️, develop

#12711 BO the shipping cost becomes free if more than a half ordered
  classes/order/Order.php
Labels: Bug, QA ✔️, develop

#12758 Added a Theme Enabler command
  src/PrestaShopBundle/Command/ThemeEnablerCommand.php
Labels: Feature, QA ✔️, develop

#12753 Allow ipv6 to be used in htaccess redirects
  classes/Tools.php
Labels: Improvement, QA ✔️, develop

#12766 Remove duplicated CLDR service
  src/PrestaShopBundle/Resources/config/services/core/currency.yml
  src/PrestaShopBundle/Resources/config/services/core/form/choice_provider.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_data_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/localization.yml
  src/PrestaShopBundle/Resources/config/services/core/localization/cldr.yml
Labels: QA ✔️, Refactoring, develop

#12666 [IN] #12626 - Delivery slips fails when upgrading to 1.7.5
  install-dev/upgrade/sql/1.7.0.0.sql
Labels: Bug, QA ✔️, develop

#12793 Allow Travis phpHigh build to fail as it is an informative check, not…
  .travis.yml
Labels: Improvement, develop

#11783 Migrate customers searching via ajax
  admin-dev/themes/default/template/controllers/orders/form.tpl
  controllers/admin/AdminOrdersController.php
  src/Adapter/Customer/QueryHandler/SearchCustomersHandler.php
  src/Core/Domain/Customer/Query/SearchCustomers.php
  src/Core/Domain/Customer/QueryHandler/SearchCustomersHandlerInterface.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
  src/PrestaShopBundle/Form/Admin/Product/ProductSpecificPrice.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer/customers.yml
  src/PrestaShopBundle/Resources/config/services/adapter/customer.yml
Labels: Bug, QA ✔️, Refactoring, develop, migration

#12505 Improve error handling in migrated controllers
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ProfilesController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/ContactsController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/profiles.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Profiles/index.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Contact/Contacts/index.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop, migration

#12717 Adds re-usable rewrite link copier service
  admin-dev/themes/new-theme/js/components/text-to-link-rewrite-copier.js
  admin-dev/themes/new-theme/js/pages/categories/index.js
  admin-dev/themes/new-theme/js/pages/categories/name-to-link-rewrite-copier.js
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
Labels: Improvement, QA ✔️, develop

#12787 adds legacy links to all meta page routes
  src/PrestaShopBundle/Resources/config/routing/admin/configure/shop_parameters/meta.yml
  tests-legacy/Integration/PrestaShopBundle/Routing/Converter/LegacyUrlConverterTest.php
Labels: Bug, develop, migration

#12751 Fix saving shop association in migrated add/edit forms
  src/Adapter/Domain/AbstractObjectModelHandler.php
  src/Adapter/Form/ChoiceProvider/ShopTreeChoiceProvider.php
  src/Adapter/Language/CommandHandler/AbstractLanguageHandler.php
  src/Adapter/Language/CommandHandler/AddLanguageHandler.php
  src/Adapter/Language/CommandHandler/EditLanguageHandler.php
Labels: Bug, QA ✔️, develop

#12804 Use string value for CSRF token in DeliveryControllerTest
  tests-legacy/Integration/PrestaShopBundle/Controller/Admin/Sell/Order/DeliveryControllerTest.php
Labels: Improvement, develop

#12784 Add module main class parse error to log message
  src/Adapter/Module/ModuleDataProvider.php
Labels: Improvement, QA ✔️, develop

#12610 Taxes Options configuration form migration
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/js/pages/tax/display-in-cart-option-handler.js
  admin-dev/themes/new-theme/js/pages/tax/index.js
  src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php
  src/Adapter/Tax/Ecotax/ProductEcotaxResetter.php
  src/Core/Form/ChoiceProvider/TaxAddressTypeChoiceProvider.php
  src/Core/Tax/Ecotax/ProductEcotaxResetterInterface.php
  src/Core/Tax/TaxOptionsConfiguration.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/TaxController.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Tax/TaxOptionsFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Tax/TaxOptionsType.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/_international.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/tax.yml
  src/PrestaShopBundle/Resources/config/services/adapter/data_configuration.yml
  src/PrestaShopBundle/Resources/config/services/adapter/tax.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_handler.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/choice_provider.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Tax/Blocks/tax_options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Tax/index.html.twig
Labels: QA ✔️, Refactoring, Wording ✔️, develop, migration

#12808 Deprecate Cart::addExtraCarriers()
  classes/Cart.php
Labels: Improvement, develop

#12810 Install ps_faviconnotificationbo automatically
  src/PrestaShopBundle/Install/Install.php
Labels: Improvement, QA ✔️, develop

#12803 Fallback on language code when locale is empty
  classes/Tools.php
  classes/controller/Controller.php
Labels: Bug, QA ✔️, develop

#12730 Error 500 in product catalog when short description is too long
  src/Adapter/Product/AdminProductDataUpdater.php
Labels: Bug, QA ✔️, develop

#12748 Remove obsolete P3P policy
  classes/controller/FrontController.php
Labels: Improvement, QA ✔️, develop

#12749 9 duplicates removed from array in getProductAttributeWhitelist(). It…
  src/Adapter/Presenter/Product/ProductLazyArray.php
Labels: Improvement, QA ✔️, develop

#12251 Improve version
  src/Adapter/Requirement/CheckMissingOrUpdatedFiles.php
  src/Core/Foundation/Version.php
  tests-legacy/Unit/Core/Foundation/VersionTest.php
  tests/Unit/Core/Foundation/VersionTest.php
Labels: Improvement, QA ✔️, develop

#12836 Fixes http 500 when trying to get the images of a product with no images
  classes/webservice/WebserviceSpecificManagementImages.php
Labels: Bug, QA ✔️, develop

#12841 Add deprecation notice for hook actionAjaxDieBefore
  classes/Hook.php
Labels: Bug, QA ✔️, develop

#12838 Update ProductSpecificPrice.php
  src/PrestaShopBundle/Form/Admin/Product/ProductSpecificPrice.php
Labels: Improvement, QA ✔️, develop

#12817 Robots should not index search content
  controllers/front/listing/SearchController.php
Labels: Bug, QA ✔️, develop

#12864 Legalcompliance not included
  composer.json
  composer.lock
Labels: Feature, QA ✔️, develop

#12794 Add missing columns in products_import.csv
  docs/csv_import/products_import.csv
Labels: Bug, QA ✔️, develop

#12699 Refacto addons store controller and handle addons failure
  src/PrestaShopBundle/Controller/Admin/Improve/Modules/AddonsStoreController.php
Labels: Improvement, QA ✔️, Wording ✔️, develop

#12902 [Backport from develop] Allow Travis phpHigh build to fail as it is an informative check
  .travis.yml
Labels: Improvement

#12788 Remove html escaping of errors
  admin-dev/themes/default/template/layout.tpl
Labels: Bug, QA ✔️, develop

#10253 Add modal-dialog-centered class to classic theme
  themes/classic/_dev/css/partials/_commons.scss
  themes/classic/assets/css/theme.css
  themes/classic/templates/catalog/_partials/quickview.tpl
Labels: Improvement, QA ✔️, develop

#12644 Add margin between buttons on Traffic & SEO page
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/_showcase-card.scss
Labels: Improvement, QA ✔️, develop

#12874 Fix Symfony console crash because of DocumentationLinkProvider service definition
  classes/Language.php
  config/services/common.yml
  config/services/front/services_prod.yml
  src/Adapter/Configuration.php
  src/PrestaShopBundle/Resources/config/services/adapter/common.yml
  src/PrestaShopBundle/Resources/config/services/adapter/data_provider.yml
  src/PrestaShopBundle/Resources/config/services/adapter/services.yml
  src/PrestaShopBundle/Resources/config/services/core/util/helper_card.yml
Labels: Bug, QA ✔️, develop

#12912 Fix Traffic and SEO route paths
  src/PrestaShopBundle/Resources/config/routing/admin/configure/shop_parameters/meta.yml
  tests-legacy/Integration/PrestaShopBundle/Routing/Converter/LegacyUrlConverterTest.php
Labels: QA ✔️, Refactoring, develop

#11943 Improve performance by avoiding parsing YAML files during ModuleManagerBuilder init
  src/Core/Addon/Module/ModuleManagerBuilder.php
  src/Core/Util/File/YamlParser.php
  tests/Unit/Core/Util/YamlParserTest.php
Labels: Improvement, Performance, QA ✔️, develop

#12945 Build assets
  admin-dev/themes/new-theme/public/categories.bundle.js
  admin-dev/themes/new-theme/public/contacts.bundle.js
  admin-dev/themes/new-theme/public/currency.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/language.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/meta.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/product_page.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
Labels: Improvement, develop

#12897 Enable lite display for new theme
  admin-dev/themes/new-theme/template/layout.tpl
  controllers/admin/AdminLegacyLayoutController.php
Labels: Bug, QA ✔️, develop

#12940 Do not look for translations if no locale
  classes/Context.php
Labels: Bug, QA ✔️, develop

#12946 Fix issue in AdminCarrierWizardController::processRanges()
  controllers/admin/AdminCarrierWizardController.php
Labels: Bug, QA ✔️, develop

#12960 DoctrineBuilderExtension uses YamlParser for its config
  src/Adapter/Container/DoctrineBuilderExtension.php
  src/Adapter/ContainerBuilder.php
Labels: Bug, develop

#12959 Handle Tools curl timeout to ease debugging
  classes/Tools.php
Labels: Improvement, develop

#12956 Customization - improve phpdoc and constants usage
  classes/Cart.php
  classes/Customization.php
  controllers/admin/AdminProductsController.php
  controllers/front/ProductController.php
  src/Adapter/Product/AdminProductWrapper.php
Labels: Improvement, QA ✔️, develop

#11962 Do not stripslashes value from _GET & _POST
  classes/Employee.php
  classes/Tools.php
  tests-legacy/Unit/Classes/ToolsCoreTest.php
Labels: Bug, QA ✔️, develop

#12965 Fix wrong cart calculation when using cart rule with virtual products
  classes/Cart.php
  src/Core/Cart/Calculator.php
  tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/amount_mono_virtual.feature
Labels: Bug, QA ✔️, develop

#12782 Fixes for migrated Categories add/edit actions
  admin-dev/themes/new-theme/js/components/form/text-with-length-counter.js
  admin-dev/themes/new-theme/js/pages/categories/index.js
  admin-dev/themes/new-theme/scss/components/_grid.scss
  classes/Category.php
  src/Adapter/Category/CommandHandler/AbstractCategoryHandler.php
  src/Adapter/Category/CommandHandler/AddCategoryHandler.php
  src/Adapter/Category/CommandHandler/AddRootCategoryHandler.php
  src/Adapter/Category/CommandHandler/BulkDeleteCategoriesHandler.php
  src/Adapter/Category/CommandHandler/BulkUpdateCategoriesStatusHandler.php
  src/Adapter/Category/CommandHandler/DeleteCategoryHandler.php
  src/Adapter/Category/CommandHandler/EditCategoryHandler.php
  src/Adapter/Category/CommandHandler/EditRootCategoryHandler.php
  src/Adapter/Category/CommandHandler/ToggleCategoryStatusHandler.php
  src/Adapter/Form/ChoiceProvider/CategoryTreeChoiceProvider.php
  src/Core/Domain/Category/Command/AbstractCategoryCommand.php
  src/Core/Domain/Category/Command/AddCategoryCommand.php
  src/Core/Domain/Category/Command/AddRootCategoryCommand.php
  src/Core/Domain/Category/Command/BulkDisableCategoriesCommand.php
  src/Core/Domain/Category/Command/BulkEnableCategoriesCommand.php
  src/Core/Domain/Category/Command/BulkUpdateCategoriesStatusCommand.php
  src/Core/Domain/Category/Command/DisableCategoriesCommand.php
  src/Core/Domain/Category/Command/EditCategoryCommand.php
  src/Core/Domain/Category/Command/EditRootCategoryCommand.php
  src/Core/Domain/Category/Command/EnableCategoriesCommand.php
  src/Core/Domain/Category/CommandHandler/BulkUpdateCategoriesStatusHandlerInterface.php
  src/Core/Domain/Category/Exception/CategoryConstraintException.php
  src/Core/Domain/Category/ValueObject/CategoryStatus.php
  src/Core/Domain/Group/Exception/InvalidGroupIdException.php
  src/Core/Domain/Group/QueryHandler/GetDefaultGroupsHandlerInterface.php
  src/Core/Domain/Group/QueryResult/DefaultGroup.php
  src/Core/Domain/Group/QueryResult/DefaultGroups.php
  src/Core/Domain/Group/ValueObject/GroupId.php
  src/Core/Form/IdentifiableObject/DataHandler/AbstractCategoryFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/CategoryFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/RootCategoryFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/CategoryFormDataProvider.php
  src/Core/Grid/Definition/Factory/CategoryGridDefinitionFactory.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Form/Admin/Catalog/Category/AbstractCategoryType.php
  src/PrestaShopBundle/Form/Admin/Catalog/Category/CategoryType.php
  src/PrestaShopBundle/Form/Admin/Type/Material/MaterialChoiceTreeType.php
  src/PrestaShopBundle/Form/Admin/Type/TextWithLengthCounterType.php
  src/PrestaShopBundle/Resources/config/services/adapter/category.yml
  src/PrestaShopBundle/Resources/config/services/adapter/form.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/breadcrumb.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/index.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_horizontal_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/material.html.twig
Labels: Improvement, QA ✔️, develop, migration

#12705 Update OrderHistory to manage {followup} & {shipping_number} vars in all email templates, not only in in_transit template
  classes/order/OrderHistory.php
Labels: Bug, QA ✔️, develop

#12971 Enable customers page
  admin-dev/themes/default/template/controllers/addresses/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/customers/helpers/index.php
  admin-dev/themes/default/template/controllers/customers/helpers/list/index.php
  admin-dev/themes/default/template/controllers/customers/helpers/list/list_header.tpl
  admin-dev/themes/default/template/controllers/customers/helpers/required_fields.tpl
  admin-dev/themes/default/template/controllers/customers/helpers/view/index.php
  admin-dev/themes/default/template/controllers/customers/helpers/view/view.tpl
  admin-dev/themes/default/template/controllers/customers/index.php
  admin-dev/themes/default/template/controllers/orders/form.tpl
  admin-dev/themes/default/template/controllers/orders/helpers/view/view.tpl
  controllers/admin/AdminAddressesController.php
  controllers/admin/AdminCustomersController.php
  controllers/admin/AdminGroupsController.php
  controllers/admin/AdminReturnController.php
  controllers/admin/AdminSearchController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer/customers.yml
  tests-legacy/PrestaShopBundle/Controller/ControllerTest.php
Labels: Improvement, QA ✔️, develop, migration

#13035 Merge 1.7.5.x in develop
  composer.json
  composer.lock
  docs/CHANGELOG.txt
  src/Core/Grid/Definition/Factory/AbstractGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/CategoryGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/CmsPageCategoryDefinitionFactory.php
  src/Core/Grid/Definition/Factory/ContactGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/CustomerGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/EmailLogsDefinitionFactory.php
  src/Core/Grid/Definition/Factory/EmployeeGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/LogGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/ProfilesGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/RequestSqlGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/WebserviceKeyDefinitionFactory.php
  src/Core/Grid/Filter/GridFilterFormFactory.php
  src/Core/Grid/GridFactory.php
  src/Core/Hook/HookDispatcherAwareTrait.php
  src/PrestaShopBundle/Resources/config/services/core/grid.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_data_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_filter_form_factory.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/TrafficSeo/Meta/index.html.twig
  tests-legacy/Unit/Core/Grid/Definition/Factory/AbstractGridDefinitionFactoryTest.php
Labels: Improvement, develop

#12964 Wrong specific price refresh on product page with combinations
  themes/_core/js/product.js
  themes/core.js
  themes/core.js.map
Labels: Bug, Needs port on StarterTheme, QA ✔️, develop

#12967 Foward $locale to Translate::getModuleTranslation()
  classes/module/Module.php
Labels: Bug, QA ✔️, develop

#13009 Change product canonical url to parent, no more redirection
  .travis.yml
  controllers/front/ProductController.php
  tests/E2E/README.md
  tests/check_e2e.sh
  themes/classic/templates/catalog/_partials/miniatures/product.tpl
Labels: Improvement, QA ✔️, develop

#12329 API and Products: Add missing combination IDs in the pack content
  classes/Product.php
Labels: Improvement, QA ✔️, develop

#13052 Remove usage of TRAVIS_BUILD_DIR
  travis-scripts/base64-screenshots
  travis-scripts/run-functional-tests
  travis-scripts/run-selenium-tests
  travis-scripts/test-startertheme
Labels: Improvement, develop

#13049 Fix BO scaling in mobile
  admin-dev/themes/default/template/header.tpl
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/_showcase-card.scss
  admin-dev/themes/new-theme/scss/components/layout/_content_div.scss
  admin-dev/themes/new-theme/scss/config/_settings.scss
  admin-dev/themes/new-theme/scss/mixins/_breakpoints.scss
  admin-dev/themes/new-theme/scss/theme.scss
  admin-dev/themes/new-theme/template/header.tpl
  controllers/admin/AdminLegacyLayoutController.php
Labels: Bug, QA ✔️, develop

#12523 Solved problem with texture upload when attribute has hex color
  admin-dev/themes/default/template/controllers/attributes/helpers/form/form.tpl
  controllers/admin/AdminAttributesGroupsController.php
  themes/classic/templates/catalog/_partials/product-variants.tpl
Labels: Bug, Needs port on StarterTheme, QA ✔️, Wording ✔️, develop

#13057 Fixes search action configuration for grids
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/employee.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/design/cms_pages.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/categories.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer/customers.yml
Labels: Bug, develop, migration, waiting for author

#13066 Fix npm install not working anymore on new-theme
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/public/catalog_product.bundle.js
  admin-dev/themes/new-theme/public/categories.bundle.js
  admin-dev/themes/new-theme/public/cms_page.bundle.js
  admin-dev/themes/new-theme/public/contacts.bundle.js
  admin-dev/themes/new-theme/public/currency.bundle.js
  admin-dev/themes/new-theme/public/customer.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/employee.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/improve_design_positions.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/language.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/manufacturer.bundle.js
  admin-dev/themes/new-theme/public/manufacturer_address.bundle.js
  admin-dev/themes/new-theme/public/meta.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/translations.bundle.js
Labels: Bug, QA ✔️, develop, waiting for wording

#13067 Fix manufacturers ns typo's and wrong typecasts in commands
  src/Adapter/Manufacturer/CommandHandler/BulkDeleteManufacturerHandler.php
  src/Adapter/Manufacturer/CommandHandler/BulkToggleManufacturerStatusHandler.php
  src/Adapter/Manufacturer/CommandHandler/DeleteManufacturerHandler.php
  src/Adapter/Manufacturer/CommandHandler/ToggleManufacturerStatusHandler.php
  src/Core/Domain/Manufacturer/Command/AddManufacturerCommand.php
  src/Core/Domain/Manufacturer/CommandHandler/BulkDeleteManufacturerHandlerInterface.php
  src/Core/Domain/Manufacturer/CommandHandler/BulkToggleManufacturerStatusHandlerInterface.php
  src/Core/Domain/Manufacturer/CommandHandler/DeleteManufacturerHandlerInterface.php
  src/Core/Domain/Manufacturer/CommandHandler/ToggleManufacturerStatusHandlerInterface.php
  src/Core/Domain/Manufacturer/QueryHandler/GetManufacturerForEditingHandlerInterface.php
  src/Core/Domain/Manufacturer/QueryResult/EditableManufacturer.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/manufacturer.yml
Labels: QA ✔️, Refactoring, develop, migration

#13008 Adds phpdoc on range objectmodel
  classes/range/RangePrice.php
  classes/range/RangeWeight.php
Labels: Improvement, develop

#13063 Module Manager: Use categoryParentEnglishName instead category name
  src/PrestaShopBundle/Service/DataProvider/Admin/CategoriesProvider.php
Labels: Bug, QA ✔️, develop

#12892 limit carrier image size on checkout page
  img/s/2.jpg
  themes/classic/_dev/css/components/checkout.scss
  themes/classic/assets/css/theme.css
Labels: Bug, QA ✔️, develop

#12391 12040 broken authentication
  classes/Customer.php
  classes/form/CustomerPersister.php
Labels: Bug, QA ✔️, develop

#12850 [BO] 11692 "Module Manager" tab should be the first tab in Modules Tab
  install-dev/data/xml/tab.xml
  install-dev/upgrade/sql/1.7.6.0.sql
Labels: Improvement, QA ✔️, develop

#13078 Revert "Delivery slips fails when upgrading to 1.7.5"
  install-dev/upgrade/sql/1.7.0.0.sql
Labels: Bug, develop

#13043 Fix to handle fancybox customer creation in Add an Order page
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/modal_create_success.html.twig
Labels: Bug, QA ✔️, develop, migration

#13054 Escape all import output data
  controllers/admin/AdminImportController.php
Labels: Bug, QA ✔️, develop

#13081 Empty filter should not be shown
  themes/classic/templates/catalog/_partials/facets.tpl
  themes/classic/templates/catalog/listing/product-list.tpl
Labels: Bug, Needs port on StarterTheme, QA ✔️, develop

#13014 Final Migration of Categories page
  admin-dev/themes/default/template/controllers/categories/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/categories/helpers/form/index.php
  admin-dev/themes/default/template/controllers/categories/helpers/index.php
  admin-dev/themes/default/template/controllers/categories/helpers/list/index.php
  admin-dev/themes/default/template/controllers/categories/helpers/list/list_header.tpl
  admin-dev/themes/new-theme/js/components/grid/extension/column/catalog/category-position-extension.js
  controllers/admin/AdminCategoriesController.php
  src/Adapter/Category/CommandHandler/AbstractCategoryHandler.php
  src/Adapter/Category/CommandHandler/AddCategoryHandler.php
  src/Adapter/Category/CommandHandler/AddRootCategoryHandler.php
  src/Adapter/Category/CommandHandler/EditCategoryHandler.php
  src/Adapter/Category/CommandHandler/EditRootCategoryHandler.php
  src/Adapter/Category/CommandHandler/UpdateCategoryPositionHandler.php
  src/Adapter/Grid/Search/Factory/SearchCriteriaWithCategoryParentIdFilterFactory.php
  src/Core/Domain/Category/Command/UpdateCategoryPositionCommand.php
  src/Core/Domain/Category/CommandHandler/UpdateCategoryPositionHandlerInterface.php
  src/Core/Form/IdentifiableObject/DataHandler/CategoryFormDataHandler.php
  src/Core/Grid/Definition/Factory/CategoryGridDefinitionFactory.php
  src/PrestaShopBundle/Controller/Admin/CategoryController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Form/Admin/Catalog/Category/CategoryType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/categories.yml
  src/PrestaShopBundle/Resources/config/services/adapter/category.yml
  src/PrestaShopBundle/Resources/config/services/adapter/form.yml
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/category_position.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/create.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/create_root.html.twig
Labels: QA ✔️, Refactoring, develop, migration, waiting for wording

#13079 Fix visual glitches in new theme
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/catalog_product.bundle.js
  admin-dev/themes/new-theme/public/categories.bundle.js
  admin-dev/themes/new-theme/public/cms_page.bundle.js
  admin-dev/themes/new-theme/public/contacts.bundle.js
  admin-dev/themes/new-theme/public/currency.bundle.js
  admin-dev/themes/new-theme/public/customer.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/employee.bundle.js
  admin-dev/themes/new-theme/public/form_popover_error.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/improve_design_positions.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/language.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/manufacturer.bundle.js
  admin-dev/themes/new-theme/public/manufacturer_address.bundle.js
  admin-dev/themes/new-theme/public/meta.bundle.js
  admin-dev/themes/new-theme/public/module.bundle.js
  admin-dev/themes/new-theme/public/module_card.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_page.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/profiles.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/supplier.bundle.js
  admin-dev/themes/new-theme/public/tax.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/themes.bundle.js
  admin-dev/themes/new-theme/public/translation_settings.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/table.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/grid.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Language/index.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Stock/overview.html.twig
Labels: Bug, QA ✔️, develop

#13076 Migrate Add/Edit Profiles page
  admin-dev/themes/new-theme/js/pages/profiles/ProfilesPage.js
  controllers/admin/AdminLegacyLayoutController.php
  controllers/admin/AdminProfilesController.php
  src/Adapter/Profile/CommandHandler/AddProfileHandler.php
  src/Adapter/Profile/CommandHandler/EditProfileHandler.php
  src/Adapter/Profile/QueryHandler/GetProfileForEditingHandler.php
  src/Core/Domain/Profile/Command/AddProfileCommand.php
  src/Core/Domain/Profile/Command/EditProfileCommand.php
  src/Core/Domain/Profile/CommandHandler/AddProfileHandlerInterface.php
  src/Core/Domain/Profile/CommandHandler/EditProfileHandlerInterface.php
  src/Core/Domain/Profile/Query/GetProfileForEditing.php
  src/Core/Domain/Profile/QueryHandler/GetProfileForEditingHandlerInterface.php
  src/Core/Domain/Profile/QueryResult/EditableProfile.php
  src/Core/Form/IdentifiableObject/DataHandler/ProfileFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/ProfileFormDataProvider.php
  src/Core/Grid/Definition/Factory/ProfileGridDefinitionFactory.php
  src/Core/Search/Filters/ProfileFilters.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ProfileController.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Profile/ProfileType.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/profiles.yml
  src/PrestaShopBundle/Resources/config/services/adapter/profile.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_handler.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_factory.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Profiles/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Profiles/create.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Profiles/edit.html.twig
  tests-legacy/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
  tests-legacy/Integration/PrestaShopBundle/Routing/Converter/LegacyUrlConverterTest.php
  tests-legacy/PrestaShopBundle/Controller/ControllerTest.php
Labels: QA ✔️, Refactoring, Wording ✔️, develop, migration

#13012 Update Twig to v1.38
  composer.json
Labels: Improvement, develop

#13095 Update dashboard links
  admin-dev/themes/default/template/controllers/dashboard/helpers/view/view.tpl
  controllers/admin/AdminDashboardController.php
Labels: Improvement, QA ✔️, develop

#13094 Fix product demo link_rewrite
  install-dev/fixtures/fashion/langs/bn/data/product.xml
  install-dev/fixtures/fashion/langs/br/data/product.xml
  install-dev/fixtures/fashion/langs/de/data/product.xml
  install-dev/fixtures/fashion/langs/en/data/product.xml
  install-dev/fixtures/fashion/langs/es/data/product.xml
  install-dev/fixtures/fashion/langs/fa/data/product.xml
  install-dev/fixtures/fashion/langs/fr/data/product.xml
  install-dev/fixtures/fashion/langs/id/data/product.xml
  install-dev/fixtures/fashion/langs/it/data/product.xml
  install-dev/fixtures/fashion/langs/nl/data/product.xml
  install-dev/fixtures/fashion/langs/pl/data/product.xml
  install-dev/fixtures/fashion/langs/qc/data/product.xml
  install-dev/fixtures/fashion/langs/ro/data/product.xml
  install-dev/fixtures/fashion/langs/ru/data/product.xml
  install-dev/fixtures/fashion/langs/tw/data/product.xml
  install-dev/fixtures/fashion/langs/vn/data/product.xml
  install-dev/fixtures/fashion/langs/zh/data/product.xml
Labels: Bug, QA ✔️, develop

#13104 Fix bad variable in Customers Add/Edit template
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/form.html.twig
Labels: Bug, QA ✔️, develop, migration

#12550 Improve the way VAT is managed for price calculation
  classes/Product.php
Labels: Bug, QA ✔️, develop

#12893 Fix bug on contact for mail too long
  themes/classic/_dev/css/components/contact.scss
  themes/classic/assets/css/theme.css
Labels: Bug, QA ✔️, develop

#12914 Reduce number of SQL requests to get the employee authorizations
  classes/Profile.php
  tests-legacy/Unit/Classes/ProfileCoreTest.php
Labels: Improvement, QA ✔️, develop

#11975 Space after semicolon
  admin-dev/filemanager/config/config.php
  admin-dev/filemanager/include/php_image_magician.php
  install-dev/theme/views/system.php
  tests-legacy/resources/ModulesOverrideInstallUninstallTest/AdminProductsController.php
  tests-legacy/resources/module/pscsx32412/override/controllers/admin/AdminProductsController.php
  tests-legacy/resources/modules/gamification/gamification.php
Labels: Improvement, develop

#11977 Function declaration
  tests-legacy/PrestaShopBundle/Routing/Converter/LegacyUrlConverterTest.php
  tests-legacy/PrestaShopBundle/Routing/Converter/RouterProviderTest.php
  tests-legacy/resources/modules/bankwire/bankwire.php
Labels: Improvement, develop

#11970 Unary operator spaces
  admin-dev/filemanager/include/php_image_magician.php
  tests-legacy/resources/modules/gamification/controllers/admin/AdminGamificationController.php
  tools/parser_sql/processors/DropProcessor.php
Labels: Improvement

#11730 Use of static instead of ClassName
  classes/PaymentModule.php
  classes/PrestaShopAutoload.php
  controllers/admin/AdminTranslationsController.php
  install-dev/classes/datas.php
  install-dev/classes/session.php
  install-dev/upgrade/classes/ToolsInstall.php
  src/Core/Cart/AmountImmutable.php
  src/Core/Localization/CLDR/LocaleData.php
  src/Core/Localization/CLDR/NumberSymbolsData.php
  src/Core/Localization/Currency/CurrencyCollection.php
  src/Core/Product/Search/SortOrder.php
  src/PrestaShopBundle/Install/DatabaseDump.php
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Install/Simplexml.php
  src/PrestaShopBundle/Routing/Converter/LegacyRoute.php
  src/PrestaShopBundle/Security/Admin/Employee.php
  src/PrestaShopBundle/Service/DataProvider/Admin/CategoriesProvider.php
  tests-legacy/TestCase/File.php
  tests-legacy/Unit/Core/Stock/Core_Stock_StockManagerTest.php
  tests-legacy/resources/ModulesOverrideInstallUninstallTest/AdminProductsController.php
  tests-legacy/resources/module/pscsx32412/override/controllers/admin/AdminProductsController.php
  tests-legacy/resources/modules/cronjobs/cronjobs.php
  tools/build/Library/InstallUnpacker/classes/VersionNumber.php
  tools/parser_sql/builders/WhereExpressionBuilder.php
  tools/parser_sql/utils/PHPSQLParserConstants.php
  tools/profiling/Tools.php
Labels: Improvement, develop

#13113 Fix typo on static
  tests-legacy/Unit/Core/Stock/Core_Stock_StockManagerTest.php
Labels: Bug, develop
