Repository PrestaShop/PrestaShop, pull requests merged in 2019-01, with the labels that each got.

#11985 PHP unit test case static method calls
  tests-legacy/Integration/Core/Module/ModuleCacheTest.php
  tests-legacy/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
  tests-legacy/Integration/PrestaShopBundle/Test/LightWebTestCase.php
  tests-legacy/Integration/classes/module/ModuleGetOverrideTest.php
  tests-legacy/PrestaShopBundle/Routing/YamlRoutesInModuleTest.php
  tests-legacy/PrestaShopBundle/Twig/Locator/ModuleTemplateLoaderTest.php
  tests-legacy/Unit/Core/Search/ControllerActionTest.php
Labels: Improvement, develop

#11922 Fix searching issue in the Credit Slips page
  controllers/admin/AdminSlipController.php
Labels: Bug, QA ✔️, develop

#11754 Fix wrong discount details on order page / on invoice
  classes/Cart.php
  classes/PaymentModule.php
  src/Core/Cart/Calculator.php
  src/Core/Cart/CartRuleCalculator.php
  tests-legacy/Unit/ContextMocker.php
  tests-legacy/Unit/Core/Cart/CartToOrder/CartToOrderTest.php
  tests-legacy/Unit/Core/Cart/CartToOrder/PaymentModuleFake.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#11936 Description has a max length and can not exceeded
  src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php
  src/PrestaShopBundle/Form/Admin/Type/FormattedTextareaType.php
Labels: Bug, QA ✔️, develop

#11932 Can't sort tax included for now
  src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Lists/products_table.html.twig
Labels: Bug, QA ✔️, Wording ✔️, develop

#11898 Fix travis script for running tests and fix broken tests
  .travis.yml
  classes/module/Module.php
  src/Adapter/Module/ModuleDataProvider.php
  src/Core/Addon/Module/ModuleManager.php
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
  tests-legacy/Integration/Adapter/AdapterDatabaseTest.php
  tests-legacy/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
  tests-legacy/Integration/PrestaShopBundle/Controller/Api/Improve/Design/PositionsControllerTest.php
  tests-legacy/Integration/ProductURLsTest.php
  tests-legacy/Integration/classes/module/ModuleOverrideInstallUninstallTest.php
  tests-legacy/Unit/Core/Addon/Module/ModuleManagerTest.php
  tests-legacy/Unit/Core/Localization/ReaderTest.php
  tests-legacy/Unit/PrestaShopBundle/Api/QueryParamsCollectionTest.php
  tests-legacy/resources/ModulesOverrideInstallUninstallTest/AdminProductsController.php
  tests-legacy/resources/ModulesOverrideInstallUninstallTest/Cart.php
Labels: Bug, develop

#12013 Isolate legacy tests into suites to fix develop branch
  composer.json
  tests-legacy/phpunit.xml
Labels: Bug, develop

#10294 Fix minimum order amount for secondary currency
  src/Adapter/Presenter/Cart/CartPresenter.php
Labels: Bug, QA ✔️, develop

#11726 Force dni fields required if associated Country needs it
  classes/Address.php
  classes/form/CustomerAddressFormatter.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#12015 fix typo in example nginx config file
  docs/server_config/nginx.conf.dist
Labels: Bug, develop

#12007 Delivery slip test
  tests/E2E/test/campaigns/common_scenarios/attribute.js
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/full/01_orders/07_export_shopping_carts.js
  tests/E2E/test/campaigns/full/01_orders/09_delivery_slips_pdf_and_options.js
  tests/E2E/test/campaigns/full/01_orders/10_credit_slip.js
  tests/E2E/test/campaigns/full/01_orders/11_credit_slips_options.js
  tests/E2E/test/campaigns/full/01_orders/12_generate_pdf_by_date.js
  tests/E2E/test/campaigns/full/01_orders/13_generate_pdf_by_status.js
  tests/E2E/test/campaigns/full/01_orders/14_credit_slip_PDF.js
  tests/E2E/test/campaigns/high/01_orders/1_create_order_in_BO.js
  tests/E2E/test/campaigns/high/02_product/11_display_each_kind_of_product.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/order.js
  tests/E2E/test/selectors/BO/Merchandise_returns.js
  tests/E2E/test/selectors/BO/menu.js
  tests/E2E/test/selectors/BO/order.js
Labels: Feature, develop

#12001 Filters in catalog page
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/full/02_product/08_filters_in_catalog_page.js
  tests/E2E/test/campaigns/full/02_product/08_sort_product.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/product/product.js
  tests/E2E/test/selectors/BO/add_product_page.js
Labels: Feature, TE, develop

#10774 Migration of "International > Localization > Currencies" page listing
  admin-dev/themes/new-theme/js/pages/currency/index.js
  admin-dev/themes/new-theme/scss/pages/_currency.scss
  admin-dev/themes/new-theme/scss/theme.scss
  admin-dev/themes/new-theme/webpack.config.js
  src/Adapter/Currency/CommandHandler/DeleteCurrencyHandler.php
  src/Adapter/Currency/CommandHandler/ToggleCurrencyStatusHandler.php
  src/Core/Currency/CurrencyGridDataFactory.php
  src/Core/Domain/Currency/Command/DeleteCurrencyCommand.php
  src/Core/Domain/Currency/Command/ToggleCurrencyStatusCommand.php
  src/Core/Domain/Currency/CommandHandler/DeleteCurrencyHandlerInterface.php
  src/Core/Domain/Currency/CommandHandler/ToggleCurrencyStatusHandlerInterface.php
  src/Core/Domain/Currency/Exception/CannotDeleteCurrencyException.php
  src/Core/Domain/Currency/Exception/CannotDeleteDefaultCurrencyException.php
  src/Core/Domain/Currency/Exception/CannotDisableDefaultCurrencyException.php
  src/Core/Domain/Currency/Exception/CannotToggleCurrencyException.php
  src/Core/Domain/Currency/Exception/CurrencyException.php
  src/Core/Domain/Currency/Exception/CurrencyNotFoundException.php
  src/Core/Domain/Currency/ValueObject/CurrencyId.php
  src/Core/Grid/Definition/Factory/CurrencyGridDefinitionFactory.php
  src/Core/Grid/Query/CurrencyQueryBuilder.php
  src/Core/Search/Filters/CurrencyFilters.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/_international.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/currencies.yml
  src/PrestaShopBundle/Resources/config/services/adapter/currency.yml
  src/PrestaShopBundle/Resources/config/services/core/cldr.yml
  src/PrestaShopBundle/Resources/config/services/core/currency.yml
  src/PrestaShopBundle/Resources/config/services/core/grid.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_data_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_factory.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Currency/index.html.twig
Labels: Feature, QA ✔️, UX ✔️, develop, migration, waiting for author, waiting for wording

#10477 Added an Error Data Listener
  tests-legacy/phpunit-admin.xml
  tests-legacy/phpunit.xml
  tests-legacy/sf-tests.xml
  tests/TestCase/ErrorsDataListener.php
  tests/TestCase/PhpErrorsCounter.php
Labels: Bug, QA ✔️, develop

#12010 Make filtering of LazyArrays return a new instance
  src/Adapter/Presenter/AbstractLazyArray.php
  src/Core/Filter/HashMapWhitelistFilter.php
  tests-legacy/Unit/Core/Filter/HashMapWhitelistFilterTest.php
  tests-legacy/Unit/Core/Filter/_Artifacts/TestLazyArray.php
Labels: Bug, QA ✔️, develop

#10297 Fix image dimensions in Product Card view
  themes/classic/_dev/css/components/featuredproducts.scss
  themes/classic/_dev/package-lock.json
  themes/classic/assets/css/theme.css
  themes/classic/templates/catalog/_partials/miniatures/product.tpl
Labels: Bug, Needs port on StarterTheme, QA ✔️, develop

#12030 Filters by category in catalog page
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/full/02_product/16_filter_by_categories_in_catalog_page.js
  tests/E2E/test/clients/category.js
  tests/E2E/test/clients/product/product.js
  tests/E2E/test/selectors/BO/add_product_page.js
  tests/E2E/test/selectors/BO/catalogpage/category_submenu.js
Labels: Feature, TE, develop

#12045 Update autoupgrade test
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/campaigns/full/01_orders/11_credit_slips_options.js
  tests/E2E/test/campaigns/install_upgrade/02_autoupgrade.js
  tests/E2E/test/clients/common_client.js
Labels: Refactoring, TE, develop

#12049 Change position, unhook and transplant a module
  tests/E2E/test/campaigns/common_scenarios/positions.js
  tests/E2E/test/campaigns/full/15_design/4_positions/1_change_position_unhook_transplant_module.js
  tests/E2E/test/clients/design.js
  tests/E2E/test/selectors/BO/design/positions.js
Labels: Feature, TE, develop

#11854 Add customer_message table name into SQL request
  controllers/admin/AdminCustomerThreadsController.php
Labels: Bug, QA ✔️, develop

#11995 Fix undefined INTL_IDNA_VARIANT_UTS46 if intl ICU < 4.6
  classes/Mail.php
Labels: 1.7.5.x, Bug, QA ✔️

#12054 Migrate legacy unit test for Hashing
  tests/Unit/Core/Crypto/HashingTest.php
Labels: Refactoring, develop

#12023 When downloading a virtual good, check if the order was made by the current user.
  controllers/front/GetFileController.php
Labels: Bug, QA ✔️, develop

#12031 Make pre-commit execute linter only if php files have been staged
  .github/contrib/pre-commit
Labels: Improvement, develop

#12052 SERP : Avoid mutating a prop directly + fix url encode
  admin-dev/themes/new-theme/js/app/utils/serp/serp.vue
  admin-dev/themes/new-theme/public/customer.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
Labels: Bug, QA ✔️, develop

#12079 fix static cache reset on ObjectModel
  classes/Address.php
  classes/Attribute.php
  classes/Currency.php
  classes/Customer.php
  classes/ObjectModel.php
  composer.json
  tests-legacy/Unit/ContextMocker.php
  tests-legacy/Unit/Core/Cart/CartToOrder/CartToOrderTest.php
  tests-legacy/phpunit.xml
Labels: Bug, develop

#12086 Location: zone and country
  tests/E2E/test/campaigns/common_scenarios/customer.js
  tests/E2E/test/campaigns/common_scenarios/location.js
  tests/E2E/test/campaigns/full/11_international/2_locations/1_create_edit_delete_bulk_action_zone.js
  tests/E2E/test/campaigns/full/11_international/2_locations/2_create_edit_activate_restrictions_country.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/customer.js
  tests/E2E/test/clients/international.js
  tests/E2E/test/common.webdriverio.js
  tests/E2E/test/selectors/BO/international/location.js
  tests/E2E/test/selectors/FO/add_account_page.js
  tests/E2E/test/selectors/FO/order_page.js
  tests/E2E/test/selectors/FO/product_page.js
Labels: Feature, TE, develop

#12014 Unify algorithm for calculating average tax rate for products in a cart
  classes/Cart.php
Labels: Bug, QA ✔️, develop

#12091 Geo-location: By IP address
  tests/E2E/test/campaigns/full/11_international/1_localization/4_geolocation/1_geolocation_ip_address.js
  tests/E2E/test/clients/international.js
  tests/E2E/test/selectors/BO/international/localization.js
Labels: Feature, TE, develop

#11877 introduces moved search and reset type button to the right
  admin-dev/themes/new-theme/scss/components/_grid.scss
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Header/Content/action.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
Labels: Improvement, QA ✔️, UX ✔️, develop, migration

#12067 Add some fixes to the campaign full
  tests/E2E/test/campaigns/boom/3098.js
  tests/E2E/test/campaigns/boom/3580.js
  tests/E2E/test/campaigns/boom/4847.js
  tests/E2E/test/campaigns/broken_tests/05_feature/2_create_feature.js
  tests/E2E/test/campaigns/common_scenarios/localization.js
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/common_scenarios/shop_parameters.js
  tests/E2E/test/campaigns/full/01_orders/12_generate_pdf_by_date.js
  tests/E2E/test/campaigns/full/01_orders/13_generate_pdf_by_status.js
  tests/E2E/test/campaigns/full/02_product/08_filters_in_catalog_page.js
  tests/E2E/test/campaigns/full/02_product/10_check_product_page_buttons.js
  tests/E2E/test/campaigns/full/03_category/1_create_edit_delete_category.js
  tests/E2E/test/campaigns/full/04_attribute/2_create_attribute.js
  tests/E2E/test/campaigns/full/06_catalogbulkaction/catalogbulkaction.js
  tests/E2E/test/campaigns/full/10_module/1_Zip_module.js
  tests/E2E/test/campaigns/full/10_module/3_search_module.js
  tests/E2E/test/campaigns/full/10_module/4_sort_module.js
  tests/E2E/test/campaigns/full/10_module/5_check_addons_catalog_page.js
  tests/E2E/test/campaigns/full/10_module/7_discover_module.js
  tests/E2E/test/campaigns/full/11_international/1_localization/1_localization/3_local_units.js
  tests/E2E/test/campaigns/full/11_international/2_locations/2_create_edit_activate_restrictions_country.js
  tests/E2E/test/campaigns/full/12_shop_parameters/2_open_all_menu_links.js
  tests/E2E/test/campaigns/full/12_shop_parameters/3_onboarding.js
  tests/E2E/test/campaigns/full/14_discount/2_check_discount_in_FO.js
  tests/E2E/test/campaigns/full/15_design/1_theme_catalog/1_check_addons_theme.js
  tests/E2E/test/campaigns/high/02_product/01_create_standard_product.js
  tests/E2E/test/campaigns/high/02_product/02_create_pack_of_product.js
  tests/E2E/test/campaigns/high/02_product/03_create_product_with_combination.js
  tests/E2E/test/campaigns/high/02_product/04_create_virtual_product.js
  tests/E2E/test/campaigns/high/02_product/10_display_all_product.js
  tests/E2E/test/campaigns/high/02_product/11_display_each_kind_of_product.js
  tests/E2E/test/campaigns/high/03_category/1_create_edit_delete_category.js
  tests/E2E/test/campaigns/high/06_catalogbulkaction/catalogbulkaction.js
  tests/E2E/test/campaigns/high/10_module/1_Zip_module.js
  tests/E2E/test/campaigns/high/10_module/2_cross_selling_module.js
  tests/E2E/test/campaigns/high/10_module/3_search_module.js
  tests/E2E/test/campaigns/high/10_module/4_sort_module.js
  tests/E2E/test/campaigns/high/11_international/translation.js
  tests/E2E/test/campaigns/high/12_shop_parameters/1_enable_and_disable_shop.js
  tests/E2E/test/campaigns/high/12_shop_parameters/2_open_all_menu_links.js
  tests/E2E/test/campaigns/high/12_shop_parameters/3_onboarding.js
  tests/E2E/test/campaigns/install_upgrade/02_autoupgrade.js
  tests/E2E/test/campaigns/install_upgrade/03_rollback.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/selectors/BO/advancedParameters/index.js
  tests/E2E/test/selectors/BO/advancedParameters/performance.js
  tests/E2E/test/selectors/BO/index.js
  tests/E2E/test/selectors/BO/pages_form.js
Labels: Refactoring, TE, develop

#12104 Update delete shopping cart test
  tests/E2E/test/campaigns/full/01_orders/06_delete_shopping_carts.js
  tests/E2E/test/campaigns/full/11_international/1_localization/4_geolocation/1_geolocation_ip_address.js
  tests/E2E/test/campaigns/full/11_international/2_locations/1_create_edit_delete_bulk_action_zone.js
  tests/E2E/test/campaigns/full/11_international/2_locations/2_create_edit_activate_restrictions_country.js
  tests/E2E/test/selectors/BO/order.js
Labels: Refactoring, TE, develop

#12112 Update bulk actions in catalog page test
  tests/E2E/test/campaigns/full/06_catalogbulkaction/catalogbulkaction.js
  tests/E2E/test/clients/catalogbulkaction.js
  tests/E2E/test/selectors/FO/search_product_page.js
Labels: Refactoring, TE, develop

#11693 BO: FIX PrestaShop#9853 Search feature value and pagination
  controllers/admin/AdminFeaturesController.php
Labels: Bug, QA ✔️, develop

#12115 Update create manufacturers test
  tests/E2E/test/campaigns/common_scenarios/manufacturers.js
  tests/E2E/test/campaigns/full/07_manufacturer/1_create_manufacturers.js
  tests/E2E/test/campaigns/full/07_manufacturer/create_manufacturers.js
  tests/E2E/test/clients/manufacturers.js
  tests/E2E/test/selectors/BO/add_product_page.js
  tests/E2E/test/selectors/FO/site_map_page.js
Labels: Refactoring, TE, develop

#12089 Implement AbstractTypedCollection with tests
  src/Core/Data/AbstractTypedCollection.php
  src/Core/Exception/TypeException.php
  tests/Unit/Core/Data/AbstractTypedCollectionTest.php
Labels: 1.7.6.x, Bug, Feature

#12125 Fix bad GridFactory service definition
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_factory.yml
Labels: Bug, develop

#12139 Fix some Symfony service definitions
  src/PrestaShopBundle/Resources/config/services/adapter/feature.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
Labels: Bug, QA ✔️, develop

#12150 Allow specific versions of libs to be ignored
  composer.json
Labels: Improvement, develop

#12141 Change php requirements in INSTALL.txt
  INSTALL.txt
Labels: Bug, develop

#12155 Fixtures does not generate thumbnails
  install-dev/controllers/console/process.php
  install-dev/controllers/http/process.php
  src/PrestaShopBundle/Install/Install.php
Labels: Bug, QA ✔️, develop

#11920 Add advice when lint fails + Display all files in error in Travis lint job
  tests-legacy/check_file_syntax.sh
Labels: Improvement, develop

#10341 Fix main page slider display on all devices
  themes/classic/_dev/css/components/imageslider.scss
  themes/classic/assets/css/theme.css
Labels: Bug, QA ✔️, develop

#12166 Update php-cs-fixer to a recent version to be compatible with PHP7.3
  classes/Address.php
  classes/AddressFormat.php
  classes/Attachment.php
  classes/AttributeGroup.php
  classes/CMS.php
  classes/Carrier.php
  classes/Cart.php
  classes/Category.php
  classes/Combination.php
  classes/ConnectionsSource.php
  classes/Country.php
  classes/Currency.php
  classes/Customer.php
  classes/CustomerMessage.php
  classes/Customization.php
  classes/Employee.php
  classes/Hook.php
  classes/Language.php
  classes/Manufacturer.php
  classes/Media.php
  classes/Meta.php
  classes/Referrer.php
  classes/State.php
  classes/Store.php
  classes/Supplier.php
  classes/Tab.php
  classes/Tag.php
  classes/Translate.php
  classes/TranslatedConfiguration.php
  classes/db/Db.php
  classes/pdf/HTMLTemplateSupplyOrderForm.php
  classes/webservice/WebserviceOutputBuilder.php
  composer.lock
  controllers/admin/AdminProductsController.php
  controllers/front/ProductController.php
  src/Adapter/Carrier/CarrierDataProvider.php
  src/Adapter/Customer/CustomerDataProvider.php
  src/Adapter/File/HtaccessFileGenerator.php
  src/Adapter/Language/LanguageDataProvider.php
  src/Adapter/Module/ModuleZip.php
  src/Adapter/Module/ModuleZipManager.php
  src/Adapter/Presenter/Product/ProductLazyArray.php
  src/Adapter/Presenter/Product/ProductListingLazyArray.php
  src/Adapter/Product/AdminProductWrapper.php
  src/Core/Addon/Module/ModuleManagerBuilder.php
  src/Core/Cldr/Localize.php
  src/Core/Grid/Search/SearchCriteria.php
  src/PrestaShopBundle/Component/CsvResponse.php
  src/PrestaShopBundle/Controller/Admin/SpecificPriceController.php
  src/PrestaShopBundle/EventListener/ModuleActivatedListener.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Import/ImportFormDataProvider.php
  src/PrestaShopBundle/Routing/Converter/LegacyUrlConverter.php
Labels: Bug, develop

#11534 Move scroll forcing from core to classic
  themes/_core/js/facets.js
  themes/classic/_dev/js/listing.js
  themes/classic/assets/js/theme.js
  themes/core.js
  themes/core.js.map
Labels: Improvement, QA ✔️, UX ✔️, develop

#12181 Update onboarding test
  tests/E2E/test/campaigns/common_scenarios/module.js
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/common_scenarios/shop_parameters.js
  tests/E2E/test/campaigns/full/01_orders/09_delivery_slips_pdf_and_options.js
  tests/E2E/test/campaigns/full/01_orders/11_credit_slips_options.js
  tests/E2E/test/campaigns/full/02_product/17_display_all_product.js
  tests/E2E/test/campaigns/full/02_product/18_display_each_kind_of_product.js
  tests/E2E/test/campaigns/full/12_shop_parameters/3_onboarding.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/product/product.js
  tests/E2E/test/selectors/BO/menu.js
  tests/E2E/test/selectors/BO/onboarding.js
  tests/E2E/test/selectors/BO/pages_form.js
Labels: Refactoring, TE, develop

#12188 Add test link id
  tests/E2E/test/campaigns/broken_tests/01_orders/08_shopping_carts_view.js
  tests/E2E/test/campaigns/broken_tests/03_category/2_delete_category_with_three_mode.js
  tests/E2E/test/campaigns/broken_tests/05_feature/2_create_feature.js
  tests/E2E/test/campaigns/broken_tests/10_module/8_read_more_module.js
  tests/E2E/test/campaigns/broken_tests/11_international/1_localization/1_create_edit_delete_language_in_BO.js
  tests/E2E/test/campaigns/broken_tests/11_international/1_localization/1_localization/2_configuration.js
  tests/E2E/test/campaigns/broken_tests/12_shop_parameters/5_contact/1_create_edit_delete_contact_in_BO.js
  tests/E2E/test/campaigns/broken_tests/15_design/2_pages/1_category.js
  tests/E2E/test/campaigns/broken_tests/15_design/2_pages/2_page.js
  tests/E2E/test/campaigns/broken_tests/15_design/3_link_widget/01_linkWidget.js
  tests/E2E/test/campaigns/broken_tests/16_file/3_sort_filter_file_in_BO.js
  tests/E2E/test/campaigns/full/01_orders/04_check_adding_product_to_cart_with_unavailable_quantities.js
  tests/E2E/test/campaigns/full/01_orders/06_delete_shopping_carts.js
  tests/E2E/test/campaigns/full/01_orders/07_export_shopping_carts.js
  tests/E2E/test/campaigns/full/01_orders/09_delivery_slips_pdf_and_options.js
  tests/E2E/test/campaigns/full/01_orders/10_check_credit_slip.js
  tests/E2E/test/campaigns/full/01_orders/11_credit_slips_options.js
  tests/E2E/test/campaigns/full/01_orders/12_generate_pdf_by_date.js
  tests/E2E/test/campaigns/full/01_orders/13_generate_pdf_by_status.js
  tests/E2E/test/campaigns/full/01_orders/14_credit_slip_PDF.js
  tests/E2E/test/campaigns/full/02_product/08_filters_in_catalog_page.js
  tests/E2E/test/campaigns/full/02_product/10_buttons_in_footer_product_page.js
  tests/E2E/test/campaigns/full/02_product/12_edit_check_demo_product_in_BO.js
  tests/E2E/test/campaigns/full/02_product/13_navigate_between_catalog_pages.js
  tests/E2E/test/campaigns/full/02_product/14_options_in_catalog_page.js
  tests/E2E/test/campaigns/full/02_product/15_buttons_in_header_product_page.js
  tests/E2E/test/campaigns/full/02_product/16_filter_by_categories_in_catalog_page.js
  tests/E2E/test/campaigns/full/03_category/1_create_edit_delete_category.js
  tests/E2E/test/campaigns/full/04_attribute/1_create_edit_delete_attribute_value.js
  tests/E2E/test/campaigns/full/04_attribute/2_create_attribute.js
  tests/E2E/test/campaigns/full/05_feature/1_create_edit_delete_feature.js
  tests/E2E/test/campaigns/full/07_manufacturer/2_create_brand_address.js
  tests/E2E/test/campaigns/full/09_customer/addresses/1_create_edit_delete_address.js
  tests/E2E/test/campaigns/full/09_customer/customer_settings/1_create_edit_delete_customer.js
  tests/E2E/test/campaigns/full/10_module/1_Zip_module.js
  tests/E2E/test/campaigns/full/10_module/3_search_module.js
  tests/E2E/test/campaigns/full/10_module/4_sort_module.js
  tests/E2E/test/campaigns/full/10_module/5_check_addons_catalog_page.js
  tests/E2E/test/campaigns/full/10_module/6_check_notifications.js
  tests/E2E/test/campaigns/full/10_module/7_discover_module.js
  tests/E2E/test/campaigns/full/11_international/1_localization/1_localization/1_import_localization.js
  tests/E2E/test/campaigns/full/11_international/1_localization/1_localization/3_local_units.js
  tests/E2E/test/campaigns/full/11_international/1_localization/1_localization/4_advanced.js
  tests/E2E/test/campaigns/full/11_international/1_localization/3_currency/1_create_edit_delete_live_exchange_rate_currency.js
  tests/E2E/test/campaigns/full/12_shop_parameters/2_open_all_menu_links.js
  tests/E2E/test/campaigns/full/14_discount/1_create_edit_delete_cart_rule_in_BO.js
  tests/E2E/test/campaigns/full/15_design/1_theme_catalog/1_check_addons_theme.js
  tests/E2E/test/campaigns/full/15_design/4_positions/1_change_position_unhook_transplant_module.js
  tests/E2E/test/campaigns/full/16_file/1_create_edit_delete_file_in_BO.js
  tests/E2E/test/campaigns/full/16_file/2_check_file_in_FO.js
  tests/E2E/test/campaigns/high/01_orders/1_create_order_in_BO.js
  tests/E2E/test/campaigns/high/12_shop_parameters/2_open_all_menu_links.js
Labels: Improvement, TE, develop

#12183 Restore survival test for Import page
  tests-legacy/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
Labels: Improvement, develop

#12190 Update check the addons catalog page test
  tests/E2E/test/campaigns/full/10_module/5_check_addons_catalog_page.js
Labels: Refactoring, TE, develop

#12206 Installation test
  tests/E2E/test/campaigns/broken_tests/installation/installation.js
  tests/E2E/test/campaigns/common_scenarios/common_installation.js
  tests/E2E/test/clients/employee.js
  tests/E2E/test/clients/installation.js
  tests/E2E/test/globals.webdriverio.js
  tests/E2E/test/selectors/BO/employee_page.js
  tests/E2E/test/selectors/BO/installation.js
  tests/E2E/test/selectors/BO/international/localization.js
  tests/E2E/test/selectors/FO/access_page.js
Labels: Refactoring, TE, develop

#12210 Update nightly tests
  .travis.yml
  tests/E2E/.docker/prestashop/Dockerfile
  tests/E2E/.docker/run-tests.sh
  tests/E2E/scripts/run-nightly-tests.sh
Labels: Bug, develop

#12217 Update search module test
  tests/E2E/test/campaigns/common_scenarios/module.js
  tests/E2E/test/campaigns/full/10_module/3_search_module.js
  tests/E2E/test/campaigns/full/12_shop_parameters/3_onboarding.js
Labels: Refactoring, TE, develop

#12196 Fix RTL glitches
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/theme.rtlfix
  admin-dev/themes/new-theme/public/theme_rtl.css
Labels: 1.7.5.x, Bug, QA ✔️

#12211 Add breadcrumb to the search results page
  controllers/front/listing/SearchController.php
Labels: Improvement, QA ✔️, develop

#12225 Add a json check when running report combine
  tests/E2E/scripts/combine-reports.py
  tests/E2E/scripts/run-nightly-tests.sh
Labels: Bug, develop

#12106 Robots.txt with multilang/multishop
  classes/Tools.php
  controllers/admin/AdminShopUrlController.php
Labels: 1.7.5.x, Bug, QA ✔️

#12222 Add notice for docker-compose
  README.md
Labels: Improvement, develop

#12077 Refacto ThemeCatalogController to use annotations
  src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeCatalogController.php
Labels: Improvement, QA ✔️, develop

#12016 Update module & service link in upgrade
  install-dev/upgrade/php/ps_1751_update_module_sf_tab.php
  install-dev/upgrade/sql/1.7.5.1.sql
Labels: 1.7.5.x, Bug, QA ✔️

#12219 Update click on discover test
  tests/E2E/test/campaigns/common_scenarios/module.js
  tests/E2E/test/campaigns/full/10_module/7_discover_module.js
  tests/E2E/test/selectors/BO/module_page.js
Labels: Refactoring, TE, develop

#12245 Update check notifications test
  tests/E2E/test/campaigns/common_scenarios/module.js
  tests/E2E/test/campaigns/full/10_module/6_check_notifications.js
  tests/E2E/test/selectors/BO/module_page.js
Labels: Refactoring, TE, develop

#12099 Refactor MaintenanceController to use annotations
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/MaintenanceController.php
Labels: Improvement, QA ✔️, develop

#12140 Default carrier name was displayed as 0
  classes/order/Order.php
Labels: Bug, QA ✔️, develop

#12097 Refacto PaymentMethodsController to use annotations
  src/PrestaShopBundle/Controller/Admin/Improve/Payment/PaymentMethodsController.php
Labels: Improvement, QA ✔️, develop

#12098 Refactor Shipping/ referencesController to use annotations
  src/PrestaShopBundle/Controller/Admin/Improve/Shipping/PreferencesController.php
Labels: Improvement, QA ✔️, develop

#12074 Refacto PreferencesController to use annotations
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/PreferencesController.php
Labels: Improvement, QA ✔️, develop

#12096 Fix access rights to Administration page
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AdministrationController.php
Labels: Bug, QA ✔️, develop

#12256 Wrong duration time while combine nightly tests reports
  tests/E2E/scripts/combine-reports.py
  tests/E2E/scripts/run-nightly-tests.sh
Labels: Improvement, develop

#12247 Bump version to 1.7.6.0
  app/AppKernel.php
  install-dev/install_version.php
Labels: Improvement, QA ✔️, develop

#12017 Weak token implementation
  controllers/front/PasswordController.php
Labels: Improvement, QA ✔️, Wording ✔️, develop

#12232 Add unit tests for Core/Kpi
  tests/Unit/Core/Kpi/KpiRowFactoryTest.php
  tests/Unit/Core/Kpi/KpiRowPresenterTest.php
  tests/Unit/Core/Kpi/KpiRowTest.php
Labels: Improvement, develop

#12240 Adds missing argument in MetaController which caused page crash
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/MetaController.php
Labels: Bug, QA ✔️, develop

#12243 Update gitignore
  .gitignore
Labels: Bug, QA ✔️, develop

#12236 SERP: Textarea from tinymce requires jquery to return the text value
  admin-dev/themes/new-theme/js/app/utils/serp/index.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/theme.css
Labels: 1.7.5.x, Bug, QA ✔️

#12249 Migrate legacy test TermsAndConditionsTest and refactor related class
  classes/checkout/ConditionsToApproveFinder.php
  src/Core/Checkout/TermsAndConditions.php
  tests/Unit/Core/Checkout/TermsAndConditionsTest.php
Labels: QA ✔️, Refactoring, develop

#12272 add checkFile step after downloading a file
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/campaigns/full/01_orders/04_check_adding_product_to_cart_with_unavailable_quantities.js
  tests/E2E/test/campaigns/full/01_orders/07_export_shopping_carts.js
  tests/E2E/test/campaigns/full/01_orders/09_delivery_slips_pdf_and_options.js
  tests/E2E/test/campaigns/full/01_orders/10_check_credit_slip.js
  tests/E2E/test/campaigns/full/01_orders/11_credit_slips_options.js
  tests/E2E/test/campaigns/full/01_orders/12_generate_pdf_by_date.js
  tests/E2E/test/campaigns/full/01_orders/13_generate_pdf_by_status.js
  tests/E2E/test/campaigns/full/01_orders/14_credit_slip_PDF.js
  tests/E2E/test/campaigns/full/16_file/01_create_view_edit_delete_bulk_action_file.js
  tests/E2E/test/campaigns/high/01_orders/1_create_order_in_BO.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/order.js
Labels: Refactoring, TE, develop

#12227 Fix ps_viewedproduct in classic theme
  themes/classic/modules/ps_viewedproduct/views/templates/hook/index.php
  themes/classic/modules/ps_viewedproduct/views/templates/hook/ps_viewedproduct.tpl
  themes/classic/modules/ps_viewedproduct/views/templates/index.php
Labels: Bug, QA ✔️, develop

#12266 Migrate ImageTagSourceParserTest in tests folder
  tests/Unit/Core/Image/Parser/ImageTagSourceParserTest.php
Labels: Refactoring, develop

#12281 Update zip module test
  tests/E2E/test/campaigns/common_scenarios/module.js
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/common_scenarios/shop_parameters.js
  tests/E2E/test/campaigns/full/01_orders/07_export_shopping_carts.js
  tests/E2E/test/campaigns/full/01_orders/09_delivery_slips_pdf_and_options.js
  tests/E2E/test/campaigns/full/01_orders/11_credit_slips_options.js
  tests/E2E/test/campaigns/full/01_orders/12_generate_pdf_by_date.js
  tests/E2E/test/campaigns/full/01_orders/13_generate_pdf_by_status.js
  tests/E2E/test/campaigns/full/01_orders/14_credit_slip_PDF.js
  tests/E2E/test/campaigns/full/02_product/17_display_all_product.js
  tests/E2E/test/campaigns/full/02_product/18_display_each_kind_of_product.js
  tests/E2E/test/campaigns/full/10_module/1_Zip_module.js
  tests/E2E/test/campaigns/full/12_shop_parameters/2_open_all_menu_links.js
  tests/E2E/test/campaigns/high/01_orders/1_create_order_in_BO.js
  tests/E2E/test/clients/product/product.js
  tests/E2E/test/datas/abandoned-cart-pro.zip
  tests/E2E/test/selectors/BO/module_page.js
Labels: Refactoring, TE, develop

#12289 Update sort module test
  tests/E2E/test/campaigns/common_scenarios/module.js
  tests/E2E/test/campaigns/full/10_module/4_sort_module.js
  tests/E2E/test/clients/module.js
  tests/E2E/test/selectors/BO/menu.js
  tests/E2E/test/selectors/BO/module_page.js
Labels: Refactoring, TE, develop

#11961 Some update to Domain namespace
  src/Adapter/Category/QueryHandler/GetCategoryForEditingHandler.php
  src/Adapter/Customer/QueryHandler/GetCustomerForViewingHandler.php
  src/Adapter/Group/QueryHandler/GetDefaultGroupsHandler.php
  src/Adapter/Meta/QueryHandler/GetPagesForLayoutCustomizationHandler.php
  src/Core/Domain/Category/Command/BulkDeleteCategoriesCommand.php
  src/Core/Domain/Category/Command/DeleteCategoryCommand.php
  src/Core/Domain/Category/Command/DeleteCategoryCoverImageCommand.php
  src/Core/Domain/Category/Command/DeleteCategoryMenuThumbnailImageCommand.php
  src/Core/Domain/Category/Command/DisableCategoriesCommand.php
  src/Core/Domain/Category/Command/EditCategoryCommand.php
  src/Core/Domain/Category/Command/EditRootCategoryCommand.php
  src/Core/Domain/Category/Command/EnableCategoriesCommand.php
  src/Core/Domain/Category/Command/ToggleCategoryStatusCommand.php
  src/Core/Domain/Category/Command/UpdateCategoriesStatusCommand.php
  src/Core/Domain/Category/Query/GetCategoryForEditing.php
  src/Core/Domain/Category/QueryHandler/GetCategoryForEditingHandlerInterface.php
  src/Core/Domain/Category/QueryResult/EditableCategory.php
  src/Core/Domain/Customer/Command/EditCustomerCommand.php
  src/Core/Domain/Customer/Command/SavePrivateNoteForCustomerCommand.php
  src/Core/Domain/Customer/Command/TransformGuestToCustomerCommand.php
  src/Core/Domain/Customer/Query/GetCustomerForEditing.php
  src/Core/Domain/Customer/Query/GetCustomerForViewing.php
  src/Core/Domain/Customer/QueryHandler/GetCustomerForViewingHandlerInterface.php
  src/Core/Domain/Customer/QueryResult/Viewable/AddressInformation.php
  src/Core/Domain/Customer/QueryResult/Viewable/BoughtProductInformation.php
  src/Core/Domain/Customer/QueryResult/Viewable/CartInformation.php
  src/Core/Domain/Customer/QueryResult/Viewable/DiscountInformation.php
  src/Core/Domain/Customer/QueryResult/Viewable/GeneralInformation.php
  src/Core/Domain/Customer/QueryResult/Viewable/GroupInformation.php
  src/Core/Domain/Customer/QueryResult/Viewable/LastConnectionInformation.php
  src/Core/Domain/Customer/QueryResult/Viewable/MessageInformation.php
  src/Core/Domain/Customer/QueryResult/Viewable/OrderInformation.php
  src/Core/Domain/Customer/QueryResult/Viewable/OrdersInformation.php
  src/Core/Domain/Customer/QueryResult/Viewable/PersonalInformation.php
  src/Core/Domain/Customer/QueryResult/Viewable/ProductsInformation.php
  src/Core/Domain/Customer/QueryResult/Viewable/ReferrerInformation.php
  src/Core/Domain/Customer/QueryResult/Viewable/SentEmailInformation.php
  src/Core/Domain/Customer/QueryResult/Viewable/Subscriptions.php
  src/Core/Domain/Customer/QueryResult/Viewable/ViewedProductInformation.php
  src/Core/Domain/Customer/QueryResult/ViewableCustomer.php
  src/Core/Domain/Group/QueryHandler/GetDefaultGroupsHandlerInterface.php
  src/Core/Domain/Group/QueryResult/DefaultGroup.php
  src/Core/Domain/Group/QueryResult/DefaultGroups.php
  src/Core/Domain/Meta/Query/GetPagesForLayoutCustomization.php
  src/Core/Domain/Meta/QueryResult/LayoutCustomizationPage.php
  src/Core/Form/IdentifiableObject/DataProvider/CustomerFormDataProvider.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
  src/PrestaShopBundle/Form/Admin/Improve/Design/Theme/PageLayoutCustomizationFormFactory.php
  src/PrestaShopBundle/Form/Admin/Improve/Design/Theme/PageLayoutCustomizationFormFactoryInterface.php
Labels: Bug, Improvement, develop, migration

#12298 Improve logging for nightly tests
  .travis.yml
  tests/E2E/scripts/combine-reports.py
  tests/E2E/scripts/run-nightly-tests.sh
Labels: Improvement, develop

#12277 Avoid usage of enter key in search hook input
  admin-dev/themes/new-theme/js/pages/improve/design_positions/positions-list-handler.js
  admin-dev/themes/new-theme/public/improve_design_positions.bundle.js
  admin-dev/themes/new-theme/public/theme.css
Labels: 1.7.5.x, Bug, QA ✔️

#11859 Replace tabs with spaces in htaccess
  img/.htaccess
  install-dev/sandbox/.htaccess
  js/.htaccess
  upload/.htaccess
Labels: Improvement, develop

#12292 Allow arabic numbers in link rewrite
  classes/Dispatcher.php
  classes/Validate.php
Labels: 1.7.5.x, Bug, QA ✔️

#12324 Separate nightly tests and reports
  .travis.yml
  tests/E2E/scripts/run-nightly-reports.sh
  tests/E2E/scripts/run-nightly-tests.sh
Labels: Improvement, develop

#11968 Switch case space
  tests-legacy/resources/ModulesOverrideInstallUninstallTest/AdminProductsController.php
  tests-legacy/resources/module/pscsx32412/override/controllers/admin/AdminProductsController.php
Labels: Improvement

#12315 Create order as a guest test and update readme file
  tests/E2E/README.md
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/common_scenarios/stock.js
  tests/E2E/test/campaigns/full/01_orders/05_create_order_without_account.js
  tests/E2E/test/campaigns/high/02_product/03_create_product_with_combination.js
  tests/E2E/test/clients/stocks.js
  tests/E2E/test/datas/customer_and_address_data.js
  tests/E2E/test/selectors/BO/add_product_page.js
  tests/E2E/test/selectors/BO/catalogpage/stocksubmenu/movements.js
  tests/E2E/test/selectors/BO/customers/addresses.js
  tests/E2E/test/selectors/BO/customers/customer.js
  tests/E2E/test/selectors/BO/order.js
  tests/E2E/test/selectors/FO/access_page.js
  tests/E2E/test/selectors/FO/order_page.js
  tests/E2E/test/selectors/FO/search_product_page.js
Labels: Refactoring, TE, develop

#11442 Fixed the problem with the type of a return value in Module::onInstall()
  src/Adapter/Module/Module.php
  src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php
Labels: Bug, QA ✔️, Wording ✔️

#11175 Update AdminProductsController.php
  controllers/admin/AdminProductsController.php
Labels: Bug, QA ✔️, develop

#12317 Create order in BO test
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/full/01_orders/01_create_order_in_BO.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/selectors/BO/catalogpage/discount_submenu.js
  tests/E2E/test/selectors/BO/order.js
  tests/E2E/test/selectors/FO/home_page.js
Labels: Refactoring, TE, develop

#8993 Fix HTML formated configuration not saved
  classes/controller/AdminController.php
Labels: Bug, QA ✔️, develop

#12343 Print invoice order
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/full/01_orders/14_print_the_invoice_order.js
  tests/E2E/test/campaigns/full/01_orders/15_credit_slip_PDF.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/order.js
  tests/E2E/test/selectors/BO/add_product_page.js
  tests/E2E/test/selectors/BO/international/taxes.js
  tests/E2E/test/selectors/BO/order.js
  tests/E2E/test/selectors/FO/order_page.js
Labels: Refactoring, TE, develop

#12201 Fixes sql exception when creating a product_option without values
  classes/AttributeGroup.php
Labels: Bug, QA ✔️, develop

#12351 Update create order in FO test
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/campaigns/common_scenarios/stock.js
  tests/E2E/test/campaigns/full/01_orders/02_create_order_in_FO.js
  tests/E2E/test/campaigns/full/01_orders/05_create_order_without_account.js
  tests/E2E/test/campaigns/full/01_orders/09_delivery_slips_pdf_and_options.js
  tests/E2E/test/campaigns/high/01_orders/2_create_order_in_FO.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/stocks.js
  tests/E2E/test/selectors/BO/customers/customer.js
  tests/E2E/test/selectors/BO/employee_page.js
  tests/E2E/test/selectors/BO/order.js
  tests/E2E/test/selectors/FO/order_page.js
Labels: Refactoring, develop

#12316 Access rules for SystemInformationController and MemcacheServer
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/MemcacheServerController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SystemInformationController.php
Labels: Improvement, QA ✔️, develop

#12355 Print the delivery slip
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/campaigns/full/01_orders/15_print_delivery_slip.js
  tests/E2E/test/campaigns/full/01_orders/16_credit_slip_PDF.js
  tests/E2E/test/selectors/BO/order.js
Labels: Refactoring, TE, develop

#12362 Go to next and previous page test
  tests/E2E/test/campaigns/boom/4847.js
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/full/02_product/07_check_all_products.js
  tests/E2E/test/campaigns/full/02_product/07_next_and_previous_page.js
  tests/E2E/test/campaigns/full/02_product/09_check_shopping_cart.js
  tests/E2E/test/campaigns/high/02_product/07_check_all_products.js
  tests/E2E/test/campaigns/high/02_product/07_sort_product.js
  tests/E2E/test/campaigns/high/02_product/08_check_shopping_cart.js
  tests/E2E/test/selectors/BO/shopParameters/shop_parameters.js
  tests/E2E/test/selectors/FO/access_page.js
  tests/E2E/test/selectors/FO/product_page.js
Labels: Refactoring, develop

#12304 Add unit tests for Core IdentifiableObject classes
  tests/Unit/Core/Form/IdentifiableObject/Builder/FormBuilderFactoryTest.php
  tests/Unit/Core/Form/IdentifiableObject/Builder/FormBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/Handler/FormHandlerTest.php
Labels: Improvement, develop

#12327 Add SEO options especially for product attributes in title, the front…
  controllers/front/ProductController.php
  src/Adapter/Meta/SEOOptionsDataConfiguration.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/TrafficSeo/Meta/MetaSettingsFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/TrafficSeo/Meta/SEOOptionsType.php
  src/PrestaShopBundle/Resources/config/services/adapter/data_configuration.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_handler.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/TrafficSeo/Meta/Blocks/seo_options_configuration.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/TrafficSeo/Meta/index.html.twig
  themes/_core/js/product.js
  themes/core.js
  themes/core.js.map
Labels: 1.7.5.x, Improvement, QA ✔️, Wording ✔️

#12369 Fix deprecation notices reported by Composer
  composer.json
Labels: Improvement, develop, waiting for QA

#12378 Improve report files generation
  tests/E2E/scripts/combine-reports.py
Labels: Improvement, develop

#12361 Refacto SearchParameters and SearchParametersResolver for pagination
  src/Core/Search/SearchParameters.php
  src/Core/Search/SearchParametersInterface.php
  src/PrestaShopBundle/Controller/ArgumentResolver/SearchParametersResolver.php
  tests/Unit/Core/Search/SearchParametersTest.php
  tests/Unit/PrestaShopBundle/Controller/ArgumentResolver/SearchParametersResolverTest.php
Labels: 1.7.5.x, Bug, QA ✔️

#12344 Fix translation on account creation email error
  classes/form/CustomerForm.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#12341 Use show_price to display price in schema.org tags
  themes/classic/templates/catalog/product.tpl
Labels: Bug, QA ✔️, develop

#12208 Add filter on the modules folder to avoid caching all files by Twig
  src/PrestaShopBundle/Cache/ModuleTemplateCacheWarmer.php
  src/PrestaShopBundle/DependencyInjection/Compiler/OverrideTwigServiceCompilerPass.php
  src/PrestaShopBundle/PrestaShopBundle.php
  src/PrestaShopBundle/Twig/Locator/ModuleTemplateIterator.php
  tests/Unit/PrestaShopBundle/Cache/ModuleTemplateCacheWarmerTest.php
  tests/Unit/PrestaShopBundle/Twig/Fixtures/modules/dummy.md
  tests/Unit/PrestaShopBundle/Twig/Fixtures/modules/template.html.twig
  tests/Unit/PrestaShopBundle/Twig/Locator/ModuleTemplateIteratorTest.php
Labels: Improvement, QA ✔️, develop

#12354 Fix cancel button on Safari browser
  admin-dev/themes/default/template/helpers/form/form.tpl
Labels: 1.7.5.x, Bug, QA ✔️
