Repository PrestaShop/PrestaShop, pull requests merged in 2019-02, with the labels that each got.

#12395 Change stock alert z index to be on top of header
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/pages/_stock_page.scss
Labels: 1.7.5.x, Bug, QA ✔️

#12406 Revert "Fix translation on account creation email error"
  classes/form/CustomerForm.php
Labels: Bug, QA ✔️, develop

#12367 Move PositionColumn in its original folder
  src/Core/Grid/Column/Type/Common/PositionColumn.php
Labels: Bug, QA ✔️, develop

#12370 RTL fixes: profile, select and notification dropdown, popover tooltips, stock quantity arrows
  admin-dev/themes/default/public/theme.rtlfix
  admin-dev/themes/new-theme/public/theme.rtlfix
Labels: 1.7.5.x, Bug, QA ✔️

#12372 Fix provider warehouse routes
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products/suppliers.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products/warehouses.yml
Labels: 1.7.5.x, Bug, QA ✔️

#12284 Include script handler to manage installation of modules
  .travis.yml
  composer.json
  composer.lock
  tests-legacy/check_file_syntax.sh
  travis-scripts/.composer-auth.json
Labels: Feature, QA ✔️, develop

#12402 Fix first attribute generation when not choosing first attribute
  src/PrestaShopBundle/Controller/Admin/AttributeController.php
Labels: 1.7.5.x, Bug, QA ✔️

#12431 TE: update product quantity test
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/campaigns/common_scenarios/stock.js
  tests/E2E/test/campaigns/full/01_orders/05_create_order_without_account.js
  tests/E2E/test/campaigns/full/01_orders/09_delivery_slips_pdf_and_options.js
  tests/E2E/test/campaigns/full/01_orders/11_credit_slips_options.js
  tests/E2E/test/campaigns/full/01_orders/14_print_the_invoice_order.js
  tests/E2E/test/campaigns/full/08_stocks/4_update_product_quantity.js
  tests/E2E/test/campaigns/high/08_stocks/2_single_product_quantity.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/stocks.js
  tests/E2E/test/selectors/BO/catalogpage/stocksubmenu/movements.js
  tests/E2E/test/selectors/BO/catalogpage/stocksubmenu/stock.js
Labels: Refactoring, TE, develop

#12400 Remove a harmless duplicate array entry in PositionsController
  src/PrestaShopBundle/Controller/Admin/Improve/Design/PositionsController.php
Labels: Refactoring

#12397 Fix use of array_merge in HookFinder->addExpectedInstanceClasses
  src/PrestaShopBundle/Service/Hook/HookFinder.php
  tests/Unit/PrestaShopBundle/Service/Hook/HookFinderTest.php
Labels: Bug, QA ✔️, develop

#12398 Fix unused variables where straightforward to do so
  src/Adapter/Image/ImageRetriever.php
  src/Adapter/LegacyContext.php
Labels: Refactoring, develop, refactor

#12389 Fixed grid hook calls
  src/Core/Grid/Data/Factory/DoctrineGridDataFactory.php
  src/Core/Grid/Filter/GridFilterFormFactory.php
  src/Core/Grid/GridFactory.php
  src/PrestaShopBundle/Resources/config/services/core/grid.yml
Labels: 1.7.5.x, Bug, Major, QA ✔️

#12234 Force refresh of tinymce editors in product page step 1
  admin-dev/themes/default/js/bundle/product/form.js
Labels: 1.7.5.x, Bug, QA ✔️

#12399 Actually use arguments passed to CountryDataProvider->getCountries()
  src/Adapter/Country/CountryDataProvider.php
Labels: Bug, develop

#12446 Enable new Languages page
  admin-dev/themes/default/template/controllers/languages/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/languages/helpers/form/index.php
  admin-dev/themes/default/template/controllers/languages/helpers/index.php
  admin-dev/themes/default/template/controllers/languages/index.php
  controllers/admin/AdminLanguagesController.php
  src/Core/Domain/Language/ValueObject/TagIETF.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/language.yml
  tests-legacy/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
  tests-legacy/PrestaShopBundle/Controller/ControllerTest.php
  tests/Unit/Core/Domain/Language/ValueObject/IsoCodeTest.php
  tests/Unit/Core/Domain/Language/ValueObject/TagIETFTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/LanguageFormDataProviderTest.php
Labels: QA ✔️, Refactoring, develop

#12447 Remove legacy Webservice controller
  admin-dev/themes/default/template/controllers/webservice/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/webservice/helpers/form/index.php
  admin-dev/themes/default/template/controllers/webservice/helpers/index.php
  admin-dev/themes/default/template/controllers/webservice/index.php
  controllers/admin/AdminWebserviceController.php
Labels: Refactoring, develop

#11470 Improve birthdate validation
  classes/Validate.php
  classes/form/CustomerForm.php
  tests-legacy/Unit/Classes/ValidateCoreTest.php
Labels: QA ✔️, Refactoring, develop

#12479 Avoid module sorting function warnings when module data is invalid
  controllers/admin/AdminAccessController.php
Labels: Bug, QA ✔️, develop

#12480 Add a descriptif comment for the broken test "shopping_carts_view"
  tests/E2E/test/campaigns/broken_tests/01_orders/08_shopping_carts_view.js
Labels: Improvement, TE, develop

#12481 Add a descriptif comment for the broken test "create_product_with_combination"
  tests/E2E/test/campaigns/broken_tests/02_product/03_create_product_with_combination.js
Labels: Improvement, TE, develop

#12485 Add a descriptif comment for the broken test "create_feature"
  tests/E2E/test/campaigns/broken_tests/05_feature/2_create_feature.js
Labels: Improvement, TE, develop

#12486 Add a descriptif comment for the broken test "read_more_module"
  tests/E2E/test/campaigns/broken_tests/10_module/8_read_more_module.js
Labels: Improvement, TE, develop

#12482 Add a descriptif comment for the broken test "Delete category"
  tests/E2E/test/campaigns/broken_tests/03_category/2_delete_category_with_three_mode.js
Labels: Improvement, TE, develop

#12487 Add a descriptif comment for the broken test "configuration"
  tests/E2E/test/campaigns/broken_tests/11_international/1_localization/1_localization/2_configuration.js
Labels: Improvement, TE, develop

#12491 TE: add a descriptif comment for the broken test "category"
  tests/E2E/test/campaigns/broken_tests/15_design/2_pages/1_category.js
Labels: Improvement, TE, develop

#12492 Add a descriptif comment for the broken test "page"
  tests/E2E/test/campaigns/broken_tests/15_design/2_pages/2_page.js
Labels: Improvement, TE, develop

#12493 Add a descriptif comment for the broken test "linkWidget"
  tests/E2E/test/campaigns/broken_tests/15_design/3_link_widget/01_linkWidget.js
Labels: Improvement, TE, develop

#12494 Add a descriptif comment for the broken test "sort filter file"
  tests/E2E/test/campaigns/broken_tests/16_file/3_sort_filter_file_in_BO.js
Labels: Improvement, TE, develop

#12496 Add a descriptif comment for the broken test "autoupgrade"
  tests/E2E/test/campaigns/broken_tests/install_upgrade/02_autoupgrade.js
Labels: Improvement, develop

#12124 Remove unwanted umask
  admin-dev/ajax-tab.php
  admin-dev/ajax.php
  admin-dev/ajax_products_list.php
  admin-dev/backup.php
  admin-dev/bootstrap.php
  admin-dev/cron_currency_rates.php
  admin-dev/displayImage.php
  admin-dev/drawer.php
  admin-dev/functions.php
  admin-dev/get-file-admin.php
  admin-dev/grider.php
  admin-dev/index.php
  admin-dev/pdf.php
  admin-dev/searchcron.php
  bin/console
  classes/Language.php
  classes/Media.php
  classes/PrestaShopAutoload.php
  classes/Tools.php
  classes/module/Module.php
  controllers/admin/AdminCartsController.php
  controllers/admin/AdminTranslationsController.php
  controllers/front/ProductController.php
  install-dev/upgrade/upgrade.php
  src/Adapter/Cache/CombineCompressCacheConfiguration.php
  src/Core/Addon/Theme/ThemeManager.php
  src/Core/Addon/Theme/ThemeRepository.php
  src/Core/Cldr/Repository.php
  src/Core/Cldr/Update.php
  src/Core/Foundation/Filesystem/FileSystem.php
  src/Core/Localization/RTL/StylesheetGenerator.php
  src/PrestaShopBundle/Install/XmlLoader.php
  src/PrestaShopBundle/Service/Command/AbstractCommand.php
  tests-legacy/bootstrap-controllers.php
  tests-legacy/bootstrap-sf.php
Labels: Bug, QA ✔️, develop

#12507 Add hookDispatcher in GridFactory constructor, HookDispatcherAwareTrait has a safer getter
  src/Core/Grid/Definition/Factory/AbstractGridDefinitionFactory.php
  src/Core/Grid/Filter/GridFilterFormFactory.php
  src/Core/Grid/GridFactory.php
  src/Core/Hook/HookDispatcherAwareTrait.php
  src/PrestaShopBundle/Resources/config/services/core/grid.yml
  tests/Unit/Core/Grid/Definition/Factory/AbstractGridDefinitionFactoryTest.php
Labels: 1.7.5.x, Bug, QA ✔️, migration

#12543 Update vulnerable dependencies
  composer.json
  composer.lock
Labels: 1.7.5.x, Bug

#12532 Updated Core using new version of Composer script handler
  .github/release/create_release.sh
  .travis.yml
  composer.json
  composer.lock
  tests/E2E/.docker/prestashop/docker_run.sh
Labels: Improvement, QA ✔️, develop

#12484 Fix missing tag for CustomerType
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
Labels: Bug, QA ✔️, develop

#12473 Order Creation: fix out of stock status
  classes/PaymentModule.php
Labels: Bug, QA ✔️, develop

#12471 Use AdminSecurity annotation for ajax call for Sql Manager
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SqlManagerController.php
Labels: Bug, QA ✔️, develop

#11764 CO : Undefined variable
  classes/Cart.php
Labels: Bug, QA ✔️, develop

#12152 Fixed (by temporary hacking) #12151 'Timezone standard is ignored'
  install-dev/init.php
Labels: Bug, QA ✔️, develop

#12403 Attribute min not allowed on element input at this point, change type…
  themes/classic/templates/catalog/_partials/product-add-to-cart.tpl
  themes/classic/templates/checkout/_partials/cart-detailed-product-line.tpl
Labels: Bug, QA ✔️, develop

#12574 Fix PositionsControllerTest for good
  .travis.yml
  classes/exception/PrestaShopException.php
  composer.json
  install-dev/classes/controllerConsole.php
  tests-legacy/Integration/PrestaShopBundle/Controller/Api/Improve/Design/PositionsControllerTest.php
  tests-legacy/resources/modules/ps_banner/config.xml
  tests-legacy/resources/modules/ps_banner/index.php
  tests-legacy/resources/modules/ps_banner/logo.png
  tests-legacy/resources/modules/ps_banner/ps_banner.php
  travis-scripts/install-prestashop
Labels: Bug, develop

#12598 Restore composer file
  composer.json
  composer.lock
Labels: Improvement, develop

#12597 Bug when switching language
  classes/Tools.php
Labels: Bug, QA ✔️, develop

#12563 Fixes error in admin panel when visiting a category that's not under Index
  controllers/admin/AdminCategoriesController.php
Labels: Bug, QA ✔️, develop

#12559 Fix translations removing from db when Language is deleted
  classes/Language.php
Labels: Bug, QA ✔️, develop

#12465 Fixed duplicated id
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_supplier_choice.html.twig
Labels: Bug, QA ✔️, develop

#12678 Create virtual product
  tests/E2E/test/campaigns/boom/3580.js
  tests/E2E/test/campaigns/common_scenarios/currency.js
  tests/E2E/test/campaigns/common_scenarios/localization.js
  tests/E2E/test/campaigns/common_scenarios/module.js
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/common_scenarios/suppliers.js
  tests/E2E/test/campaigns/full/01_orders/01_create_order_in_BO.js
  tests/E2E/test/campaigns/full/02_product/04_create_virtual_product.js
  tests/E2E/test/campaigns/full/02_product/15_buttons_in_header_product_page.js
  tests/E2E/test/campaigns/full/11_international/1_localization/1_localization/1_import_localization.js
  tests/E2E/test/campaigns/full/11_international/1_localization/3_currency/1_create_edit_delete_live_exchange_rate_currency.js
  tests/E2E/test/campaigns/high/02_product/04_create_virtual_product.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/currency.js
  tests/E2E/test/clients/international.js
  tests/E2E/test/clients/product/product.js
  tests/E2E/test/common.webdriverio.js
  tests/E2E/test/datas/product-data.js
  tests/E2E/test/selectors/BO/add_product_page.js
  tests/E2E/test/selectors/BO/catalogpage/Manufacturers/suppliers.js
  tests/E2E/test/selectors/BO/catalogpage/category_submenu.js
  tests/E2E/test/selectors/BO/international/localization.js
  tests/E2E/test/selectors/BO/order.js
  tests/E2E/test/selectors/FO/access_page.js
  tests/E2E/test/selectors/FO/add_account_page.js
  tests/E2E/test/selectors/FO/home_page.js
  tests/E2E/test/selectors/FO/order_page.js
  tests/E2E/test/selectors/FO/product_page.js
Labels: Refactoring, TE, develop

#12622 Refactor AddonsStoreController to use annotations and some improvements
  src/PrestaShopBundle/Controller/Admin/Improve/Modules/AddonsStoreController.php
Labels: Improvement, QA ✔️, develop

#12668 Fix help sidebar when adding/editing language
  src/PrestaShopBundle/Controller/Admin/Improve/International/LanguageController.php
Labels: Bug, QA ✔️, develop, migration

#12713 Enable usage of roles for Module Updates and Module Alerts pages and manage access
  install-dev/data/xml/access.xml
  install-dev/data/xml/authorization_role.xml
  src/PrestaShopBundle/Controller/Admin/Improve/Modules/AlertsController.php
  src/PrestaShopBundle/Controller/Admin/Improve/Modules/UpdatesController.php
Labels: Improvement, QA ✔️, develop

#12696 fix missing coma in sql upgrade file
  install-dev/upgrade/sql/1.7.6.0.sql
Labels: Critical, QA ✔️, Type: Critical Bug Fix, develop

#12733 Changed the regex to force space and hyphen in postcode validation
  classes/Country.php
Labels: Bug, QA ✔️, develop

#12716 Prevent including jQuery in the new theme
  controllers/admin/AdminLegacyLayoutController.php
Labels: Bug, QA ✔️, develop

#12709 Refactor MetaController to secure search usage
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/MetaController.php
Labels: Bug, QA ✔️, develop

#12679 Add some fixes to the campaign full
  tests/E2E/test/campaigns/broken_tests/12_shop_parameters/2_open_all_menu_links.js
  tests/E2E/test/campaigns/broken_tests/12_shop_parameters/3_onboarding.js
  tests/E2E/test/campaigns/broken_tests/installation/installation.js
  tests/E2E/test/campaigns/common_scenarios/address.js
  tests/E2E/test/campaigns/common_scenarios/attribute.js
  tests/E2E/test/campaigns/common_scenarios/localization.js
  tests/E2E/test/campaigns/common_scenarios/manufacturers.js
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/common_scenarios/shop_parameters.js
  tests/E2E/test/campaigns/common_scenarios/stock.js
  tests/E2E/test/campaigns/full/01_orders/05_create_order_without_account.js
  tests/E2E/test/campaigns/full/01_orders/12_generate_pdf_by_date.js
  tests/E2E/test/campaigns/full/01_orders/14_print_the_invoice_order.js
  tests/E2E/test/campaigns/full/01_orders/15_print_delivery_slip.js
  tests/E2E/test/campaigns/full/02_product/15_buttons_in_header_product_page.js
  tests/E2E/test/campaigns/full/04_attribute/2_create_attribute.js
  tests/E2E/test/campaigns/full/07_manufacturer/1_create_manufacturers.js
  tests/E2E/test/campaigns/full/07_manufacturer/2_create_brand_address.js
  tests/E2E/test/campaigns/full/08_stocks/4_update_product_quantity.js
  tests/E2E/test/campaigns/full/11_international/1_localization/1_import_localization.js
  tests/E2E/test/campaigns/full/11_international/1_localization/2_local_units.js
  tests/E2E/test/campaigns/full/11_international/1_localization/3_advanced.js
  tests/E2E/test/campaigns/full/11_international/1_localization/4_create_edit_delete_live_exchange_rate_currency.js
  tests/E2E/test/campaigns/full/11_international/1_localization/5_geolocation_ip_address.js
  tests/E2E/test/campaigns/full/12_shop_parameters/2_patch_open_all_menu_links.js
  tests/E2E/test/campaigns/full/12_shop_parameters/3_patch_onboarding.js
  tests/E2E/test/campaigns/full/15_design/1_theme_catalog/1_check_addons_theme.js
  tests/E2E/test/selectors/BO/catalogpage/Manufacturers/brands_address.js
  tests/E2E/test/selectors/BO/catalogpage/stocksubmenu/movements.js
  tests/E2E/test/selectors/BO/international/localization.js
  tests/E2E/test/selectors/BO/menu.js
  tests/E2E/test/selectors/BO/onboarding.js
  tests/E2E/test/selectors/BO/pages_form.js
Labels: Refactoring, TE, develop

#12488 Add a descriptif comment for the broken test "create_edit_delete_language"
  tests/E2E/test/campaigns/broken_tests/11_international/1_localization/1_create_edit_delete_language_in_BO.js
Labels: Improvement, TE, develop

#12490 TE: add a descriptif comment for the broken test "create_edit_delete_contact"
  tests/E2E/test/campaigns/broken_tests/12_shop_parameters/5_contact/1_create_edit_delete_contact_in_BO.js
Labels: Improvement, TE, develop

#12495 Add a descriptif comment for the broken test "installation language <> country "
  tests/E2E/test/campaigns/broken_tests/installation/installation.js
Labels: Improvement, TE, develop

#12739 Revert to Webpack 2
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/.webpack/dev.js
  admin-dev/themes/new-theme/.webpack/prod.js
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
  admin-dev/themes/new-theme/postcss.config.js
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/catalog_product.bundle.js
  admin-dev/themes/new-theme/public/categories.bundle.js
  admin-dev/themes/new-theme/public/cms_page.bundle.js
  admin-dev/themes/new-theme/public/contacts.bundle.js
  admin-dev/themes/new-theme/public/currency.bundle.js
  admin-dev/themes/new-theme/public/customer.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/employee.bundle.js
  admin-dev/themes/new-theme/public/form_popover_error.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/improve_design_positions.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/language.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/meta.bundle.js
  admin-dev/themes/new-theme/public/module.bundle.js
  admin-dev/themes/new-theme/public/module_card.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_page.bundle.js
  admin-dev/themes/new-theme/public/product_page.css
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/profiles.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/stock.css
  admin-dev/themes/new-theme/public/supplier.bundle.js
  admin-dev/themes/new-theme/public/theme.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/themes.bundle.js
  admin-dev/themes/new-theme/public/translation_settings.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/public/translations.css
  admin-dev/themes/new-theme/public/webservice.bundle.js
  admin-dev/themes/new-theme/webpack.config.js
Labels: Bug, QA ✔️, develop

#12747 Fix PhpDoc for AttributeGroupCore::getAttributes()
  classes/AttributeGroup.php
Labels: Refactoring, develop
