Repository PrestaShop/PrestaShop, pull requests merged in 2019-12, with the labels that each got.

#16552 Add generic ButtonBulkAction and javascript to handle open in tabs
  admin-dev/themes/new-theme/js/components/grid/extension/bulk-open-tabs-extension.js
  admin-dev/themes/new-theme/js/pages/order/index.js
  admin-dev/themes/new-theme/public/order.bundle.js
  src/Core/Grid/Action/Bulk/Type/ButtonBulkAction.php
  src/Core/Grid/Definition/Factory/OrderGridDefinitionFactory.php
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Actions/Bulk/button.html.twig
Labels: Improvement, QA ✔️, develop, waiting for wording

#16524 Switching select of ps_brandlist to a bootstrap dropdown
  themes/classic/modules/ps_brandlist/views/templates/_partials/brand_form.tpl
Labels: FO, Improvement, QA ✔️, develop

#16612 Functional tests - Adding test update Quantity on catalog-stocks page
  tests/puppeteer/campaigns/data/demo/products.js
  tests/puppeteer/campaigns/functional/BO/catalog/stocks/01_simpleFilterStocks.js
  tests/puppeteer/campaigns/functional/BO/catalog/stocks/02_updateQuantity.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/catalog/stocks/index.js
Labels: Refactoring, TE, develop

#16566 Functional Tests - Add BO tests for generate invoice by date
  tests/puppeteer/.eslintrc.js
  tests/puppeteer/README.md
  tests/puppeteer/campaigns/data/demo/invoices.js
  tests/puppeteer/campaigns/data/demo/orders.js
  tests/puppeteer/campaigns/functional/BO/orders/invoices/01_generateInvoiceByDate.js
  tests/puppeteer/campaigns/utils/files.js
  tests/puppeteer/campaigns/utils/globals.js
  tests/puppeteer/campaigns/utils/helpers.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/orders/invoices/index.js
  tests/puppeteer/pages/commonPage.js
Labels: Refactoring, TE, develop

#16644 Tests - Fix logout used in Employee tests
  tests/puppeteer/pages/BO/BObasePage.js
Labels: Refactoring, TE, develop

#16647 Tests - Using pptruser to run tests with download
  tests/puppeteer/.docker/Dockerfile
  tests/puppeteer/campaigns/utils/globals.js
Labels: Refactoring, TE, develop

#16635 Fix discount calculation if two gift-cartrules exist for the same product.
  src/Core/Cart/CartRuleCalculator.php
Labels: Bug, QA ✔️, develop

#16527 Check memory_limit during installation
  classes/ConfigurationTest.php
  install-dev/controllers/http/process.php
  install-dev/controllers/http/system.php
  install-dev/theme/views/welcome.php
Labels: Improvement, QA ✔️, Wording ✔️, develop

#16655 Functional Tests - Add BO tests for generate invoice by status
  tests/puppeteer/campaigns/data/demo/invoices.js
  tests/puppeteer/campaigns/functional/BO/orders/invoices/02_generateInvoiceByStatus.js
  tests/puppeteer/pages/BO/orders/invoices/index.js
Labels: Refactoring, TE, develop

#16662 Fix PHP docblocks
  classes/FeatureValue.php
  classes/Image.php
Labels: Improvement, develop

#16666 Tests - Running tests with user root
  tests/puppeteer/.docker/Dockerfile
  tests/puppeteer/campaigns/utils/globals.js
Labels: Refactoring, TE, develop

#16570 Provides several UX improvements for order pages and allows to change order addresses
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js
  admin-dev/themes/new-theme/js/pages/order/view.js
  admin-dev/themes/new-theme/scss/components/_button.scss
  admin-dev/themes/new-theme/scss/components/_grid.scss
  src/Adapter/Customer/CustomerDataProvider.php
  src/Core/Domain/Order/Command/ChangeOrderDeliveryAddressCommand.php
  src/Core/Domain/Order/Command/ChangeOrderInvoiceAddressCommand.php
  src/Core/Form/ChoiceProvider/CustomerAddressesChoiceProvider.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/ChangeOrderAddressType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/choice_provider.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/update_customer_address_modal.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/details.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig
Labels: Improvement, Must-have, QA ✔️, Wording ✔️, develop

#16674 Functional Tests - Add BO tests for invoice options Enable/Disable
  tests/puppeteer/campaigns/functional/BO/orders/invoices/03_invoiceOptions/01_enableDisableInvoices.js
  tests/puppeteer/pages/BO/orders/invoices/index.js
  tests/puppeteer/pages/BO/orders/view.js
Labels: Refactoring, TE, develop

#16681 Tests - Fix errors in functional tests
  tests/puppeteer/campaigns/functional/BO/customers/customers/02_CRUDCustomerInBO.js
  tests/puppeteer/campaigns/functional/BO/customers/customers/03_customersBulkActionsInBO.js
  tests/puppeteer/campaigns/functional/BO/international/taxes/03_taxesBulkActionsInBO.js
  tests/puppeteer/pages/BO/catalog/stocks/index.js
Labels: Refactoring, TE, develop

#16074 Move the customer search by id to the first place
  controllers/admin/AdminAddressesController.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#16528 Changing links block style in carrier process
  themes/classic/_dev/css/components/checkout.scss
  themes/classic/assets/css/theme.css
Labels: Bug, FO, QA ✔️, develop

#16648 Fix customer statuses not being able to toggle when optin field is required
  classes/ObjectModel.php
  src/Adapter/Customer/CommandHandler/EditCustomerHandler.php
  src/Core/Domain/Customer/ValueObject/RequiredField.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
Labels: 1.7.6.x, QA ✔️

#16679 Functional Tests - Fix describe message for generate invoice by date/status
  tests/puppeteer/campaigns/functional/BO/orders/invoices/01_generateInvoiceByDate.js
  tests/puppeteer/campaigns/functional/BO/orders/invoices/02_generateInvoiceByStatus.js
Labels: Refactoring, TE, develop

#16659 Tests Update README.md and DOCKER.md
  tests/puppeteer/DOCKER.md
  tests/puppeteer/README.md
Labels: Refactoring, TE, develop

#16690 Add Khmer language
  app/Resources/all_languages.json
  app/Resources/legacy-to-standard-locales.json
Labels: Improvement, QA ✔️, develop

#16705 Functional tests - Add test 'Bulk Edit Quantity in stocks'
  tests/puppeteer/campaigns/data/demo/products.js
  tests/puppeteer/campaigns/functional/BO/catalog/stocks/03_bulkEditQuantity.js
  tests/puppeteer/pages/BO/catalog/stocks/index.js
Labels: Refactoring, TE, develop

#16699 Functional Tests - add test create official currency
  tests/puppeteer/campaigns/data/demo/currencies.js
  tests/puppeteer/campaigns/functional/BO/international/localization/currencies/01_CreateOfficialCurrency.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/international/currencies/add.js
  tests/puppeteer/pages/BO/international/currencies/index.js
  tests/puppeteer/pages/BO/international/localization/index.js
  tests/puppeteer/pages/FO/FObasePage.js
Labels: Refactoring, TE, develop

#16708 Tests - Fix eslint errors on linkchecker
  tests/puppeteer/tools/linkchecker.js
  tests/puppeteer/tools/urls.js
Labels: Refactoring, TE, develop

#16638 Fix logic and display of customer's cart rules
  classes/CartRule.php
Labels: Bug, QA ✔️, develop

#16721 Functional tests - Fix echange rate on test currency
  tests/puppeteer/campaigns/functional/BO/international/localization/currencies/01_CreateOfficialCurrency.js
  tests/puppeteer/pages/BO/international/currencies/index.js
Labels: Refactoring, TE, develop

#16727 Functional tests - Fix test CRUD profile
  tests/puppeteer/campaigns/data/faker/profile.js
  tests/puppeteer/campaigns/functional/BO/advancedParameters/team/04_CRUDProfile.js
Labels: Refactoring, TE, develop

#16733 Fix new connection detection
  classes/Connection.php
Labels: Bug, develop

#16731 Tests - Disable dev mode while testing with docker
  tests/puppeteer/.docker/prestashop/docker_run.sh
Labels: Refactoring, TE, develop

#16440 Added indexes for product reference and supplier_reference
  install-dev/upgrade/sql/1.7.7.0.sql
Labels: Improvement, QA ✔️, develop

#16750 Sanity tests - Can't install prestashop with same db in prod mode
  .travis.yml
  tests/puppeteer/campaigns/utils/globals.js
  tests/puppeteer/pages/Install/install.js
Labels: Refactoring, TE, develop

#16759 Functional Tests - Enable/Disable product image in the invoice
  tests/puppeteer/campaigns/functional/BO/orders/invoices/03_invoiceOptions/03_enableDisableProductImage.js
  tests/puppeteer/campaigns/utils/files.js
  tests/puppeteer/package.json
  tests/puppeteer/pages/BO/orders/invoices/index.js
  tests/puppeteer/pages/BO/orders/view.js
  tests/puppeteer/pages/FO/checkout.js
Labels: Refactoring, TE, develop

#16764 Tests - Fix sanity on nightly
  tests/puppeteer/pages/BO/catalog/products/add.js
  tests/puppeteer/pages/BO/catalog/products/index.js
  tests/puppeteer/pages/commonPage.js
Labels: Refactoring, TE, develop

#16761 Functional test - CRUD order message
  tests/puppeteer/campaigns/data/faker/orderMessage.js
  tests/puppeteer/campaigns/functional/BO/customerService/orderMessages/01_CRUDOrderMessage.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/customerService/orderMessages/add.js
  tests/puppeteer/pages/BO/customerService/orderMessages/index.js
Labels: Refactoring, TE, develop

#16748 Functional tests - Fix expect on test currencies
  tests/puppeteer/campaigns/functional/BO/international/localization/currencies/01_CreateOfficialCurrency.js
Labels: Refactoring, TE, develop

#16766 Functional test - Fix global variable call in the test
  tests/puppeteer/campaigns/functional/BO/orders/invoices/01_generateInvoiceByDate.js
  tests/puppeteer/campaigns/functional/BO/orders/invoices/02_generateInvoiceByStatus.js
  tests/puppeteer/campaigns/functional/BO/orders/invoices/03_invoiceOptions/03_enableDisableProductImage.js
  tests/puppeteer/campaigns/utils/files.js
Labels: Refactoring, TE, develop

#16747 Functional Tests - Enable/Disable tax breakdown
  tests/puppeteer/campaigns/data/demo/taxRule.js
  tests/puppeteer/campaigns/data/faker/product.js
  tests/puppeteer/campaigns/data/faker/taxRule.js
  tests/puppeteer/campaigns/data/faker/taxRuleGroup.js
  tests/puppeteer/campaigns/functional/BO/orders/invoices/03_invoiceOptions/02_enableDisableTaxBreakdown.js
  tests/puppeteer/campaigns/utils/files.js
  tests/puppeteer/pages/BO/catalog/products/add.js
  tests/puppeteer/pages/BO/international/taxes/index.js
  tests/puppeteer/pages/BO/international/taxes/taxRules/add.js
  tests/puppeteer/pages/BO/international/taxes/taxRules/index.js
  tests/puppeteer/pages/BO/orders/invoices/index.js
  tests/puppeteer/pages/BO/orders/view.js
Labels: Refactoring, TE, develop

#15942 Docker compose could not stats files
  .docker/Dockerfile
  .docker/docker_run_git.sh
  .docker/wait-for-it.sh
  .gitignore
  docker-compose.yml
Labels: Bug, Developer Feature, develop

#16784 Tests - Fix checkout FO
  tests/puppeteer/pages/FO/cart.js
Labels: Refactoring, TE, develop

#16771 Functionnal tests - Add test "Filter and bulk delete order messages"
  tests/puppeteer/campaigns/functional/BO/customerService/orderMessages/02_filterAndBulkDeleteOrderMessages.js
  tests/puppeteer/pages/BO/customerService/orderMessages/index.js
Labels: Refactoring, TE, develop

#16789 Security policy
  .github/SECURITY.md
Labels: Improvement, develop

#16658 Use tab attribute as fallback when a module does not have category
  src/Core/Addon/Module/ModuleManagerBuilder.php
  src/PrestaShopBundle/Resources/config/services/adapter/data_provider.yml
  src/PrestaShopBundle/Service/DataProvider/Admin/CategoriesProvider.php
  tests/Unit/PrestaShopBundle/Service/DataProvider/Admin/CategoriesProviderTest.php
  tests/Unit/PrestaShopBundle/Service/DataProvider/Admin/fixtures/categories.yml
Labels: Improvement, QA ✔️, develop

#16144 Migrate hooks for new Order view page
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js
  admin-dev/themes/new-theme/js/pages/order/view.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  install-dev/data/xml/hook.xml
  install-dev/data/xml/hook_alias.xml
  install-dev/upgrade/sql/1.7.7.0.sql
  src/PrestaShopBundle/Controller/Admin/Sell/Order/ActionsBarButton.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/ActionsBarButtonInterface.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/ActionsBarButtonsCollection.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/details.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/extra_order_button_actions.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/order_actions.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig
Labels: Improvement, Must-have, QA ✔️, Wording ✔️, develop, migration

#16307 Cast employeeId to int in the bulk update employee command
  src/Core/Domain/Employee/Command/BulkDeleteEmployeeCommand.php
  src/Core/Domain/Employee/Command/BulkUpdateEmployeeStatusCommand.php
Labels: Bug, QA ✔️, develop

#16815 Unhide new migrated Catalog > Files Symfony page
  admin-dev/themes/default/template/controllers/attachments/helpers/list/list_action_delete.tpl
  admin-dev/themes/default/template/controllers/attachments/index.php
  composer.json
  controllers/admin/AdminAttachmentsController.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/webservice.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/attachment.yml
  tests-legacy/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
  tests-legacy/Integration/PrestaShopBundle/Test/LightWebTestCase.php
  tests-legacy/PrestaShopBundle/Controller/ControllerTest.php
  tests-legacy/check_phpunit.sh
  tests/Integration/PrestaShopBundle/Routing/Converter/LegacyUrlConverterTest.php
Labels: Feature, QA ✔️, develop, migration

#16791 Functional Tests - Test some options in the invoice file
  tests/puppeteer/campaigns/data/faker/invoice.js
  tests/puppeteer/campaigns/functional/BO/orders/invoices/03_invoiceOptions/06_otherOptions.js
  tests/puppeteer/pages/BO/orders/invoices/index.js
Labels: Refactoring, TE, develop

#16801 Functional tests - add test create and delete link widget
  tests/puppeteer/campaigns/data/demo/linkWidgets.js
  tests/puppeteer/campaigns/functional/BO/design/linkWidget/01_CreateAndCheckFooterLinkWidget.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/design/linkWidgets/add.js
  tests/puppeteer/pages/BO/design/linkWidgets/index.js
  tests/puppeteer/pages/FO/FObasePage.js
Labels: Refactoring, TE, develop

#16834 Switch zone for BA, LI, and UA
  install-dev/data/xml/country.xml
Labels: Improvement, QA ✔️, develop

#16775 Functional Tests - Enable/Disable current year in the invoice file name
  tests/puppeteer/campaigns/functional/BO/orders/invoices/03_invoiceOptions/05_enableDisableCurrentYear.js
  tests/puppeteer/pages/BO/orders/invoices/index.js
Labels: Refactoring, TE, develop

#16756 Functional tests - Add test Create unofficial currency
  tests/puppeteer/campaigns/data/demo/currencies.js
  tests/puppeteer/campaigns/functional/BO/international/localization/currencies/02_CreateUnofficialCurrency.js
  tests/puppeteer/pages/BO/international/currencies/add.js
Labels: Refactoring, TE, develop

#16821 Add empty states for Catalog > Files and Orders > Credit slips pages
  admin-dev/themes/new-theme/img/empty_state/attachment.png
  admin-dev/themes/new-theme/img/empty_state/credit_slip.png
  src/PrestaShopBundle/Resources/config/services/core/util/helper_card.yml
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/EmptyState/attachment.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/EmptyState/credit_slip.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop, migration

#16848 Functional tests - add test Create DB Backup
  tests/puppeteer/campaigns/functional/BO/advancedParameters/database/dbBackup/01_CreateAndDeleteDbBackup.js
  tests/puppeteer/campaigns/utils/helpers.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/advancedParameters/database/dbBackup/index.js
  tests/puppeteer/pages/BO/advancedParameters/database/sqlManager/index.js
  tests/puppeteer/pages/BO/design/linkWidgets/index.js
  tests/puppeteer/pages/FO/FObasePage.js
Labels: Refactoring, TE, develop

#16861 Functional test : Activate Employees bulk actions test
  tests/puppeteer/campaigns/functional/BO/advancedParameters/team/03_employeesBulkActions.js
Labels: Refactoring, TE, develop

#16467 Migrate partial refund
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js
  admin-dev/themes/new-theme/js/pages/order/view.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/pages/_orders.scss
  classes/order/OrderSlip.php
  src/Adapter/Order/CommandHandler/IssuePartialRefundHandler.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Core/Domain/Order/Command/IssuePartialRefundCommand.php
  src/Core/Domain/Order/Exception/EmptyRefundAmountException.php
  src/Core/Domain/Order/Exception/EmptyRefundQuantityException.php
  src/Core/Domain/Order/QueryResult/OrderProductForViewing.php
  src/Core/Form/IdentifiableObject/DataHandler/PartialRefundFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/PartialRefundFormDataProvider.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/PartialRefundType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
  src/PrestaShopBundle/Resources/config/services/adapter/order.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_handler.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/order_actions.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig
Labels: Bug, Must-have, QA ✔️, Wording ✔️, develop, migration

#16772 Functional Tests - Test prefix in the invoice file name
  tests/puppeteer/campaigns/data/faker/invoice.js
  tests/puppeteer/campaigns/functional/BO/orders/invoices/03_invoiceOptions/04_invoicePrefix.js
  tests/puppeteer/pages/BO/orders/invoices/index.js
Labels: Refactoring, TE, develop

#16757 Covers multiple CommandHandlers and QueryHandlers by behat tests
  src/Core/Domain/MailTemplate/Command/GenerateThemeMailTemplatesCommand.php
  src/Core/Form/ChoiceProvider/TabChoiceProvider.php
  tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/AbstractDomainFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/DebugModeFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/EmployeeFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/ShowcaseCardFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/ThemeMailTemplatesFeatureContext.php
  tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Misc/debug_mode.feature
  tests/Integration/Behaviour/Features/Scenario/Misc/showcase_card.feature
  tests/Integration/Behaviour/Features/Scenario/Misc/theme_mail_templates.feature
  tests/Integration/Behaviour/behat.yml
Labels: Improvement, develop, migration

#16875 Functional Tests - Delete Category from monitoring page
  tests/puppeteer/campaigns/functional/BO/catalog/monitoring/01_deleteEmptyCategory.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/catalog/categories/index.js
  tests/puppeteer/pages/BO/catalog/monitoring/index.js
Labels: Refactoring, TE, develop

#16831 Functional Tests - Create, check and filter credit slips
  tests/puppeteer/campaigns/functional/BO/orders/creditSlips/01_createFilterCreditSlips.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/orders/creditSlips/index.js
  tests/puppeteer/pages/BO/orders/view.js
  tests/puppeteer/pages/FO/cart.js
Labels: Refactoring, TE, develop

#16881 Functional tests - Fix tests 'CRUD customer' and 'CRUD Category'
  tests/puppeteer/campaigns/functional/BO/catalog/categories/02_CRUDCategoryInBO.js
  tests/puppeteer/campaigns/functional/BO/customers/customers/02_CRUDCustomerInBO.js
  tests/puppeteer/pages/BO/catalog/categories/index.js
  tests/puppeteer/pages/BO/customers/index.js
Labels: Refactoring, TE, develop

#16882 Functional Tests - Generate credit slip by date
  tests/puppeteer/campaigns/functional/BO/orders/creditSlips/02_generateCreditSlipsByDate.js
  tests/puppeteer/pages/BO/orders/creditSlips/index.js
Labels: Refactoring, TE, develop

#16884 Functional Tests - Test credit slip options
  tests/puppeteer/campaigns/functional/BO/orders/creditSlips/01_createFilterCreditSlips.js
  tests/puppeteer/campaigns/functional/BO/orders/creditSlips/02_generateCreditSlipsByDate.js
  tests/puppeteer/campaigns/functional/BO/orders/creditSlips/03_creditSlipOptions.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/orders/creditSlips/index.js
  tests/puppeteer/pages/BO/orders/view.js
Labels: Refactoring, TE, develop

#16897 Tests - Fix tests : invoices options
  tests/puppeteer/pages/BO/orders/view.js
Labels: Refactoring, TE, develop

#16900 Functional tests - Disable tests profile including creation
  tests/puppeteer/campaigns/functional/BO/advancedParameters/team/04_CRUDProfile.js
  tests/puppeteer/campaigns/functional/BO/advancedParameters/team/06_profileBulkActions.js
Labels: Refactoring, develop

#14428 Succeed a search even with spelling errors
  classes/Search.php
  controllers/admin/AdminSearchConfController.php
  install-dev/data/xml/configuration.xml
Labels: Improvement, Must-have, QA ✔️, Wording ✔️, develop

#16908 Functional Test - Add new test CRUD files
  tests/puppeteer/campaigns/data/faker/file.js
  tests/puppeteer/campaigns/functional/BO/catalog/files/01_CRUDFile.js
  tests/puppeteer/campaigns/utils/files.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/catalog/files/add.js
  tests/puppeteer/pages/BO/catalog/files/index.js
Labels: Refactoring, TE, develop

#16888 Fix customer comment template
  mails/themes/modern/core/order_customer_comment.html.twig
Labels: 1.7.6.x, Bug, QA ✔️

#16893 Fix yml config parse typo
  config/bootstrap.php
Labels: 1.7.6.x, Bug

#16868 Show "No picture" image instead of broken one
  themes/classic/templates/checkout/_partials/cart-detailed-product-line.tpl
Labels: Bug, QA ✔️, develop

#16729 Cost price & unit price are erased when saving with a supplier
  controllers/admin/AdminProductsController.php
Labels: 1.7.6.x, Bug, QA ✔️

#16857 Changing brand page style
  themes/classic/_dev/css/components/brands.scss
  themes/classic/_dev/css/theme.scss
  themes/classic/assets/css/theme.css
Labels: Improvement, QA ✔️, develop

#16746 Attributes bo_css & bo_theme can be empty
  classes/controller/AdminController.php
Labels: 1.7.6.x, Bug, QA ✔️

#16909 Functional tests - Add filter contacts tests
  tests/puppeteer/campaigns/data/demo/contacts.js
  tests/puppeteer/campaigns/functional/BO/shopParameters/contact/01_filterContacts.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/shopParameters/contact/index.js
Labels: Refactoring, TE, develop

#16886 Functional Tests - Generate delivery slip by date
  tests/puppeteer/campaigns/functional/BO/orders/deliverySlips/01_generateDeliverySlipByDate.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/orders/deliverySlips/index.js
Labels: Refactoring, TE, develop

#16931 Functional tests - add test filter stocks by status
  tests/puppeteer/campaigns/functional/BO/catalog/stocks/04_filterStocksByStatus.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/catalog/stocks/index.js
Labels: Refactoring, TE, develop

#16914 Functional Test - Add new test : filter SEO pages grid
  tests/puppeteer/campaigns/data/demo/seoPages.js
  tests/puppeteer/campaigns/functional/BO/shopParameters/trafficAndSeo/seoAndUrls/01_filterSeoPages.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/index.js
Labels: Refactoring, TE, develop

#16915 Fix multiple submit
  themes/_core/js/checkout.js
  themes/core.js
  themes/core.js.map
Labels: Bug, QA ✔️, develop

#16807 Travis: update config for dpl v2
  .travis.yml
Labels: Improvement, develop

#16959 Functional tests - Add new test : CRUD Seo Page
  tests/puppeteer/campaigns/data/demo/seoPages.js
  tests/puppeteer/campaigns/data/faker/seoPage.js
  tests/puppeteer/campaigns/functional/BO/shopParameters/trafficAndSeo/seoAndUrls/02_CRUDSeoPage.js
  tests/puppeteer/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/add.js
  tests/puppeteer/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/index.js
Labels: Refactoring, TE, develop

#16923 Functional tests - Bulk delete backups
  tests/puppeteer/campaigns/functional/BO/advancedParameters/database/dbBackup/02_bulkDeleteDbBackups.js
  tests/puppeteer/pages/BO/advancedParameters/database/dbBackup/index.js
Labels: Refactoring, TE, develop

#16905 Functional Tests - Add monitoring products test
  tests/puppeteer/campaigns/functional/BO/catalog/monitoring/01_deleteEmptyCategory.js
  tests/puppeteer/campaigns/functional/BO/catalog/monitoring/02_monitoringProducts.js
Labels: Refactoring, TE, develop

#16922 Functional tests - Add Bulk actions for file tests
  tests/puppeteer/campaigns/functional/BO/catalog/files/02_fileBulkActions.js
  tests/puppeteer/pages/BO/catalog/files/index.js
Labels: Refactoring, TE, develop

#16960 Functional Tests - Add prefix verification for delivery slip file
  tests/puppeteer/campaigns/data/faker/deliverySlipOptions.js
  tests/puppeteer/campaigns/functional/BO/orders/deliverySlips/02_deliverySlipOptions/01_deliverySlipPrefix.js
  tests/puppeteer/pages/BO/orders/deliverySlips/index.js
Labels: Refactoring, TE, develop
