Repository PrestaShop/PrestaShop, pull requests merged in 2019-04, with the labels that each got.

#13106 Checkout proceeds automatically go to latest step
  classes/checkout/AbstractCheckoutStep.php
  classes/checkout/CheckoutAddressesStep.php
  classes/checkout/CheckoutDeliveryStep.php
  classes/checkout/CheckoutPersonalInformationStep.php
  classes/checkout/CheckoutProcess.php
  controllers/front/CartController.php
Labels: Bug, QA ✔️, develop

#13122 Fix notice when iso code does not exist in array
  controllers/admin/AdminDashboardController.php
Labels: Bug, QA ✔️, develop

#13088 Ensure translations are always saved with the selected theme in back office
  src/PrestaShopBundle/Controller/Api/TranslationController.php
Labels: Bug, QA ✔️, develop

#13033 Filter registered hooks in module possible hooks list
  admin-dev/themes/default/template/controllers/modules_positions/form.tpl
  classes/module/Module.php
  js/admin/modules-position.js
Labels: Improvement, QA ✔️, develop

#13127 Do not run tests with the StarterTheme anymore
  tests/check_e2e.sh
  travis-scripts/test-startertheme
Labels: Improvement, develop

#12707 New design for employee profile [Back-Office]
  admin-dev/themes/default/public/theme.css
  admin-dev/themes/default/sass/partials/_header.sass
  admin-dev/themes/default/template/header.tpl
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
  admin-dev/themes/new-theme/scss/config/_settings.scss
  admin-dev/themes/new-theme/template/components/layout/employee_dropdown.tpl
Labels: Improvement, QA ✔️, Wording ✔️, develop

#13115 fix strpos args order
  tools/build/Library/InstallUnpacker/classes/Download.php
Labels: Bug, develop

#13105 Validate theme zip file and show error messages
  src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php
  src/PrestaShopBundle/Form/Admin/Improve/Design/Theme/ImportThemeType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Theme/import.html.twig
Labels: Bug, QA ✔️, Wording ✔️, develop, migration

#13135 Add variable to tell if prices are tax included or not
  classes/controller/FrontController.php
  src/Core/Filter/FrontEndObject/ConfigurationFilter.php
Labels: Improvement, QA ✔️, develop

#13123 Display shop path in Information page
  src/Adapter/Shop/ShopInformation.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/system_information.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop

#12974 Cms page category listing position update
  src/Adapter/CMS/PageCategory/CommandHandler/DeleteCmsPageCategoryHandler.php
  src/Core/Grid/Definition/Factory/CmsPageCategoryDefinitionFactory.php
  src/Core/Grid/Presenter/GridPresenter.php
  src/Core/Grid/Query/CmsPageCategoryQueryBuilder.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/CmsPageController.php
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
Labels: Feature, QA ✔️, develop, migration, waiting for UX

#13093 Add missing label and delete legacy tax controller as it was migrated
  controllers/admin/AdminTaxesController.php
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Tax/Blocks/tax_options.html.twig
  tests-legacy/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
  tests-legacy/PrestaShopBundle/Controller/ControllerTest.php
Labels: Bug, QA ✔️, Refactoring, Wording ✔️, develop, migration

#13103 Introduce new hooks displayProductActions & displayPersonalInformationTop
  themes/classic/templates/catalog/_partials/product-add-to-cart.tpl
  themes/classic/templates/checkout/_partials/steps/personal-information.tpl
Labels: Feature, QA ✔️, develop

#13150 Add a missing space that could trigger an SQL error
  classes/Category.php
Labels: Bug, QA ✔️, develop

#13146 Fixes missing fields validation in Language command handlers
  src/Adapter/Language/CommandHandler/AddLanguageHandler.php
  src/Adapter/Language/CommandHandler/EditLanguageHandler.php
  src/Core/ConstraintValidator/TypedRegexConstraintValidator.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Language/LanguageType.php
Labels: Bug, QA ✔️, develop

#13145 fixes bug with incorrect errors display within the forms.
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/macros.html.twig
Labels: Bug, QA ✔️, develop

#13157 Fix Add/Edit brand icon
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Manufacturer/Blocks/form.html.twig
Labels: Bug, QA ✔️, develop, migration

#12931 Make footer on product page spreads itself when the menu is hidden
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/pages/_product_page.scss
Labels: Bug, QA ✔️, develop

#13159 Remove 'Constraint' suffix from TypedRegex constraint and validator
  src/Core/ConstraintValidator/Constraints/TypedRegex.php
  src/Core/ConstraintValidator/TypedRegexValidator.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Profile/ProfileType.php
  src/PrestaShopBundle/Form/Admin/Improve/Design/Pages/CmsPageType.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Language/LanguageType.php
  src/PrestaShopBundle/Form/Admin/Sell/Address/ManufacturerAddressType.php
  src/PrestaShopBundle/Form/Admin/Sell/Manufacturer/ManufacturerType.php
Labels: QA ✔️, Refactoring, develop

#13167 Move lint checks in GitHub action
  .github/main.workflow
  .travis.yml
  tests-legacy/check_file_syntax.sh
Labels: Feature, develop

#12872 Fix label "Web only"
  themes/classic/_dev/css/components/featuredproducts.scss
  themes/classic/_dev/css/components/products.scss
  themes/classic/_dev/js/components/product-miniature.js
  themes/classic/_dev/js/components/product-select.js
  themes/classic/assets/css/theme.css
  themes/classic/assets/js/theme.js
Labels: Bug, QA ✔️, develop

#13141 Performance : avoid useless attributes queries
  classes/Product.php
Labels: Improvement, QA ✔️, develop

#13161 Remove icons from Customers form
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/form.html.twig
Labels: Bug, QA ✔️, develop, migration

#13177 Fix notice undefined index: icon on Design -> Positions
  admin-dev/themes/new-theme/template/page_header_toolbar.tpl
Labels: Bug, QA ✔️, develop

#13176 Allow to use date as parameter for nightly builds
  tests/E2E/scripts/run-nightly-reports.sh
  tests/E2E/scripts/run-nightly-tests.sh
Labels: Improvement, develop

#13125 Add CMS page listing position update functionality
  admin-dev/themes/new-theme/js/pages/cms-page/index.js
  src/Core/Grid/Definition/Factory/CmsPageDefinitionFactory.php
  src/Core/Grid/Query/CmsPageQueryBuilder.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/CmsPageController.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/design/cms_pages.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_position_definition_factory.yml
Labels: Improvement, QA ✔️, develop, migration

#13158 Sets error bubbling inside the translatable type
  src/PrestaShopBundle/Form/Admin/Catalog/Category/AbstractCategoryType.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Profile/ProfileType.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/Contact/ContactType.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/TrafficSeo/Meta/MetaType.php
  src/PrestaShopBundle/Form/Admin/Improve/Design/Pages/CmsPageCategoryType.php
  src/PrestaShopBundle/Form/Admin/Improve/Design/Pages/CmsPageType.php
  src/PrestaShopBundle/Form/Admin/Type/TranslatableType.php
Labels: Improvement, QA ✔️, develop, migration

#13108 Fix missing lang entries in Configuration
  install-dev/upgrade/sql/1.7.6.0.sql
Labels: Bug, QA ✔️, develop

#13199 Fix Profiles form twig template compatibility with twig v2
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Profiles/Blocks/form.html.twig
Labels: Bug, develop, migration

#13171 Outdated assets
  admin-dev/themes/default/package-lock.json
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/catalog_product.bundle.js
  admin-dev/themes/new-theme/public/categories.bundle.js
  admin-dev/themes/new-theme/public/cms_page.bundle.js
  admin-dev/themes/new-theme/public/cms_page_form.bundle.js
  admin-dev/themes/new-theme/public/contacts.bundle.js
  admin-dev/themes/new-theme/public/currency.bundle.js
  admin-dev/themes/new-theme/public/customer.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/employee.bundle.js
  admin-dev/themes/new-theme/public/employee_form.bundle.js
  admin-dev/themes/new-theme/public/form_popover_error.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/improve_design_positions.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/language.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/manufacturer.bundle.js
  admin-dev/themes/new-theme/public/manufacturer_address_form.bundle.js
  admin-dev/themes/new-theme/public/meta.bundle.js
  admin-dev/themes/new-theme/public/module.bundle.js
  admin-dev/themes/new-theme/public/module_card.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_page.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/profiles.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/supplier.bundle.js
  admin-dev/themes/new-theme/public/tax.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/themes.bundle.js
  admin-dev/themes/new-theme/public/translation_settings.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
  themes/classic/_dev/package-lock.json
  themes/classic/assets/css/theme.css
  themes/package-lock.json
  tools/assets/build.sh
Labels: Bug, develop

#12999 Remove calls to old CLDR
  classes/Currency.php
  classes/Language.php
  classes/LocalizationPack.php
  classes/Tools.php
  classes/controller/AdminController.php
  classes/controller/Controller.php
  composer.json
  composer.lock
  controllers/admin/AdminTranslationsController.php
  install-dev/controllers/console/process.php
  install-dev/controllers/http/process.php
  install-dev/index_cli.php
  install-dev/init.php
  src/Adapter/CombinationDataProvider.php
  src/Adapter/Currency/CurrencyDataProvider.php
  src/Adapter/Language/Pack/LanguagePackImporter.php
  src/Core/Cldr/Composer/Hook.php
  src/Core/Cldr/Localize.php
  src/Core/Cldr/Repository.php
  src/Core/Cldr/Update.php
  src/Core/Currency/CurrencyDataProviderInterface.php
  src/Core/Currency/CurrencyGridDataFactory.php
  src/Core/Form/ChoiceProvider/CurrencyNameByIsoCodeChoiceProvider.php
  src/Core/Grid/Data/Factory/CustomerGridDataFactoryDecorator.php
  src/Core/Grid/Query/CurrencyQueryBuilder.php
  src/Core/Localization/CLDR/Currency.php
  src/Core/Localization/CLDR/Locale.php
  src/Core/Localization/CLDR/LocaleInterface.php
  src/Core/Localization/Currency.php
  src/Core/Localization/Currency/DataLayer/CurrencyDatabase.php
  src/Core/Localization/Currency/DataLayer/CurrencyInstalled.php
  src/Core/Localization/Locale/Repository.php
  src/Core/Localization/Number/Formatter.php
  src/Core/Localization/Specification/Factory.php
  src/Core/Localization/Specification/Number.php
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Install/Upgrade.php
  src/PrestaShopBundle/Model/Product/AdminModelAdapter.php
  src/PrestaShopBundle/Resources/config/services/adapter/data_provider.yml
  src/PrestaShopBundle/Resources/config/services/core/cldr.yml
  src/PrestaShopBundle/Resources/config/services/core/currency.yml
  src/PrestaShopBundle/Resources/config/services/core/form/choice_provider.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_data_factory.yml
  tests-legacy/Integration/Core/Localization/LocaleUsageTest.php
  tests-legacy/Integration/PrestaShopBundle/Controller/Api/Improve/Design/PositionsControllerTest.php
  tests-legacy/Integration/PrestaShopBundle/Localization/LocaleCurrencyFormatE2ETest.php
  tests-legacy/PrestaShopBundle/Model/Product/AdminModelAdapterTest.php
  tests-legacy/PrestaShopBundle/Utils/DatabaseCreator.php
  tests-legacy/Unit/Controller/FrontController/ProductControllerTest.php
  tests-legacy/Unit/Core/Cldr/RepositoryTest.php
  tests-legacy/Unit/Core/Localization/DataLayer/CurrencyDatabaseTest.php
  tests/TestCase/SymfonyIntegrationTestCase.php
Labels: Improvement, QA ✔️, develop

#12941 Remove unnecessary return on update
  src/Core/Form/IdentifiableObject/DataHandler/FormDataHandlerInterface.php
Labels: Improvement, develop, migration

#13209 Properly set error headers
  classes/CMSCategory.php
  classes/Configuration.php
  classes/Language.php
  classes/Meta.php
  classes/PaymentModule.php
  classes/PrestaShopBackup.php
  classes/Tools.php
  classes/log/FileLogger.php
  classes/module/Module.php
  classes/order/OrderHistory.php
  controllers/front/AddressesController.php
Labels: Bug, QA ✔️, develop

#13216 Enable help bar on suppliers page
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/SupplierController.php
Labels: Bug, QA ✔️, develop, migration

#13208 Broken page when request a duplicate _legacy_link
  phpunit.xml
  src/PrestaShopBundle/Routing/Converter/AbstractLegacyRouteProvider.php
  tests-legacy/PrestaShopBundle/Routing/Converter/CacheProviderTest.php
  tests-legacy/PrestaShopBundle/Routing/Converter/RouterProviderTest.php
Labels: Bug, QA ✔️, develop

#13164 Manufacturer page fixes
  src/Core/Grid/Data/Factory/ManufacturerAddressGridDataFactory.php
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_data_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_factory.yml
Labels: QA ✔️, Refactoring, develop, migration

#13047 New design for prices and taxes
  classes/controller/FrontController.php
  src/Adapter/Presenter/Cart/CartPresenter.php
  src/Adapter/Presenter/Order/OrderLazyArray.php
  themes/classic/_dev/css/components/cart.scss
  themes/classic/_dev/css/components/checkout.scss
  themes/classic/_dev/css/components/products.scss
  themes/classic/_dev/css/partials/_variables.scss
  themes/classic/_dev/js/checkout.js
  themes/classic/_dev/package-lock.json
  themes/classic/_dev/package.json
  themes/classic/assets/css/theme.css
  themes/classic/assets/js/theme.js
  themes/classic/modules/ps_shoppingcart/modal.tpl
  themes/classic/templates/checkout/_partials/cart-detailed-totals.tpl
  themes/classic/templates/checkout/_partials/cart-summary-totals.tpl
  themes/classic/templates/checkout/_partials/cart-summary.tpl
  themes/classic/templates/checkout/_partials/cart-voucher.tpl
  themes/classic/templates/checkout/_partials/order-confirmation-table.tpl
Labels: Improvement, QA ✔️, develop

#13218 Breadcrumb in search results page brings to 404 page
  controllers/front/listing/SearchController.php
Labels: Bug, QA ✔️, develop

#13222 Do not try to install a language we don't support
  classes/Language.php
  classes/LocalizationPack.php
Labels: Bug, QA ✔️, develop

#13239 Update js folder license headers
  js/admin/import.js
Labels: Improvement, develop

#13238 Update themes folders license headers
  admin-dev/themes/default/template/controllers/import/helpers/view/view.tpl
  admin-dev/themes/default/template/controllers/import/modal_import_progress.tpl
  admin-dev/themes/default/template/controllers/zones/index.php
  admin-dev/themes/new-theme/js/components/form/form-popover-error.js
  admin-dev/themes/new-theme/js/components/generatable-input.js
  admin-dev/themes/new-theme/js/components/grid/extension/action/bulk/customer/delete-customers-bulk-action-extension.js
  admin-dev/themes/new-theme/js/components/grid/extension/action/row/customer/delete-customer-row-action-extension.js
  admin-dev/themes/new-theme/js/components/taggable-field.js
  admin-dev/themes/new-theme/js/pages/currency/ExchangeRatesUpdateScheduler.js
  admin-dev/themes/new-theme/js/pages/meta/meta-page-name-option-handler.js
  admin-dev/themes/new-theme/js/pages/profiles/ProfilesPage.js
  admin-dev/themes/new-theme/js/pages/profiles/index.js
  admin-dev/themes/new-theme/js/pages/supplier/index.js
  admin-dev/themes/new-theme/js/pages/themes/index.js
  admin-dev/themes/new-theme/js/pages/themes/reset-theme-layouts-handler.js
  admin-dev/themes/new-theme/js/pages/webservice/permissions-row-selector.js
  install-dev/upgrade/php/ps_1751_update_module_sf_tab.php
  themes/classic/templates/catalog/_partials/facets.tpl
  themes/classic/templates/catalog/listing/product-list.tpl
Labels: Improvement, develop

#13242 Add missing hook description for additionalCustomerAddressFields
  install-dev/data/xml/hook.xml
Labels: Bug, develop

#13201 fix old bug PSCSX-8515 (group for not logged in user)
  classes/Category.php
  classes/Manufacturer.php
  classes/Product.php
  classes/ProductSale.php
  classes/Search.php
  classes/Supplier.php
  classes/Tag.php
Labels: Bug, QA ✔️, develop

#13246 Add missing hook description
  install-dev/data/xml/hook.xml
Labels: 1.7.6.x, Bug

#13232 [CO] Wrong calculation, free Gift
  src/Core/Cart/CartRuleCalculator.php
Labels: Bug, QA ✔️, develop

#13119 Allow hookAdditionalCustomerFormFields and --AddressFormFields to modify fields positions
  classes/form/CustomerAddressFormatter.php
  classes/form/CustomerFormatter.php
Labels: Improvement, QA ✔️, develop

#13264 Fixes deleted generatable_text_widget from template
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
Labels: 1.7.6.x, Bug, QA ✔️, migration

#13200 Add SecurityAnnotation linter
  src/PrestaShopBundle/Command/SecurityAnnotationLinterCommand.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/translations.yml
  src/PrestaShopBundle/Resources/config/services/bundle/routing.yml
  src/PrestaShopBundle/Routing/Linter/AdminRouteProvider.php
  src/PrestaShopBundle/Routing/Linter/LinterException.php
  src/PrestaShopBundle/Routing/Linter/RouteLinterInterface.php
  src/PrestaShopBundle/Routing/Linter/SecurityAnnotationLinter.php
  tests/Integration/PrestaShopBundle/Routing/Linter/SecurityAnnotationLinterTest.php
  tests/Resources/Controller/TestController.php
Labels: Feature, develop, migration

#13251 Removes unnecessary return on update everywhere
  src/Adapter/Address/CommandHandler/EditManufacturerAddressHandler.php
  src/Adapter/CMS/Page/CommandHandler/EditCmsPageHandler.php
  src/Adapter/CMS/PageCategory/CommandHandler/EditCmsPageCategoryHandler.php
  src/Adapter/Category/CommandHandler/EditCategoryHandler.php
  src/Adapter/Contact/CommandHandler/EditContactHandler.php
  src/Adapter/Currency/CommandHandler/EditCurrencyHandler.php
  src/Adapter/Customer/CommandHandler/EditCustomerHandler.php
  src/Adapter/Language/CommandHandler/EditLanguageHandler.php
  src/Adapter/Manufacturer/CommandHandler/EditManufacturerHandler.php
  src/Adapter/Meta/CommandHandler/EditMetaHandler.php
  src/Adapter/Presenter/Order/OrderLazyArray.php
  src/Adapter/Profile/Employee/CommandHandler/EditEmployeeHandler.php
  src/Adapter/Tax/CommandHandler/EditTaxHandler.php
  src/Core/Domain/Address/CommandHandler/EditManufacturerAddressHandlerInterface.php
  src/Core/Domain/CmsPage/CommandHandler/EditCmsPageHandlerInterface.php
  src/Core/Domain/CmsPageCategory/CommandHandler/EditCmsPageCategoryHandlerInterface.php
  src/Core/Domain/Contact/CommandHandler/EditContactHandlerInterface.php
  src/Core/Domain/Currency/CommandHandler/EditCurrencyHandlerInterface.php
  src/Core/Domain/Employee/CommandHandler/EditEmployeeHandlerInterface.php
  src/Core/Domain/Language/CommandHandler/EditLanguageHandlerInterface.php
  src/Core/Domain/Manufacturer/CommandHandler/EditManufacturerHandlerInterface.php
  src/Core/Form/IdentifiableObject/DataHandler/CategoryFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/CmsPageCategoryFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/CmsPageFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/ContactFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/CurrencyFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/CustomerFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/EmployeeFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/LanguageFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/ManufacturerAddressFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/ManufacturerFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/MetaFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/RootCategoryFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/SqlRequestFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/TaxFormDataHandler.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ProfileController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SqlManagerController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/ContactsController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/MetaController.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/CmsPageController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/LanguageController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/TaxController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
Labels: 1.7.6.x, QA ✔️, Refactoring, migration

#13256 Fixes to Customer subdomain & controller
  src/Core/Domain/Customer/Command/BulkDeleteCustomerCommand.php
  src/Core/Domain/Customer/Command/DeleteCustomerCommand.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
Labels: 1.7.6.x, Bug, QA ✔️, Wording ✔️, migration

#13273 Fix domain errors
  src/Core/Domain/Category/Exception/CategoryConstraintException.php
  src/Core/Domain/CmsPage/QueryHandler/GetCmsPageForEditingHandlerInterface.php
Labels: 1.7.6.x, Bug

#13349 Make all grids responsive
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/table.html.twig
Labels: 1.7.6.x, Bug, QA ✔️

#13356 Adds unit tests for FormHandlerFactory
  tests/Unit/Core/Form/IdentifiableObject/Handler/FormHandlerFactoryTest.php
Labels: 1.7.6.x, Improvement

#13359 Merge 1.7.6.x to develop - 11/04/2019
  src/Adapter/Address/CommandHandler/EditManufacturerAddressHandler.php
  src/Adapter/CMS/Page/CommandHandler/EditCmsPageHandler.php
  src/Adapter/CMS/PageCategory/CommandHandler/EditCmsPageCategoryHandler.php
  src/Adapter/Category/CommandHandler/EditCategoryHandler.php
  src/Adapter/Contact/CommandHandler/EditContactHandler.php
  src/Adapter/Currency/CommandHandler/EditCurrencyHandler.php
  src/Adapter/Customer/CommandHandler/EditCustomerHandler.php
  src/Adapter/Language/CommandHandler/EditLanguageHandler.php
  src/Adapter/Manufacturer/CommandHandler/EditManufacturerHandler.php
  src/Adapter/Meta/CommandHandler/EditMetaHandler.php
  src/Adapter/Presenter/Order/OrderLazyArray.php
  src/Adapter/Profile/Employee/CommandHandler/EditEmployeeHandler.php
  src/Adapter/Tax/CommandHandler/EditTaxHandler.php
  src/Core/Domain/Address/CommandHandler/EditManufacturerAddressHandlerInterface.php
  src/Core/Domain/Category/Exception/CategoryConstraintException.php
  src/Core/Domain/CmsPage/CommandHandler/EditCmsPageHandlerInterface.php
  src/Core/Domain/CmsPage/QueryHandler/GetCmsPageForEditingHandlerInterface.php
  src/Core/Domain/CmsPageCategory/CommandHandler/EditCmsPageCategoryHandlerInterface.php
  src/Core/Domain/Contact/CommandHandler/EditContactHandlerInterface.php
  src/Core/Domain/Currency/CommandHandler/EditCurrencyHandlerInterface.php
  src/Core/Domain/Customer/Command/BulkDeleteCustomerCommand.php
  src/Core/Domain/Customer/Command/DeleteCustomerCommand.php
  src/Core/Domain/Employee/CommandHandler/EditEmployeeHandlerInterface.php
  src/Core/Domain/Language/CommandHandler/EditLanguageHandlerInterface.php
  src/Core/Domain/Manufacturer/CommandHandler/EditManufacturerHandlerInterface.php
  src/Core/Form/IdentifiableObject/DataHandler/CategoryFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/CmsPageCategoryFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/CmsPageFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/ContactFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/CurrencyFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/CustomerFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/EmployeeFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/LanguageFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/ManufacturerAddressFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/ManufacturerFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/MetaFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/RootCategoryFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/SqlRequestFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/TaxFormDataHandler.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ProfileController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SqlManagerController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/ContactsController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/MetaController.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/CmsPageController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/LanguageController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/TaxController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/table.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
Labels: Bug, develop

#13363 Fix syntax error in tpl
  admin-dev/themes/default/template/controllers/return/helpers/form/form.tpl
Labels: 1.7.6.x, Bug, QA ✔️

#13375 Merge 1.7.6.x to develop - 12/04/2019
  admin-dev/themes/default/template/controllers/return/helpers/form/form.tpl
  tests/Unit/Core/Form/IdentifiableObject/Handler/FormHandlerFactoryTest.php
Labels: Bug, develop

#13223 Fix SQL syntax error in upgrade file to PS 1.7.6
  install-dev/upgrade/php/ps_1760_replace_index_of_admin_filter.php
  install-dev/upgrade/php/sql_indexes.php
  install-dev/upgrade/sql/1.7.6.0.sql
Labels: 1.7.6.x, Bug, QA ✔️

#13351 Mail generator fixes
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.6.0.sql
  src/Core/Domain/MailTemplate/CommandHandler/GenerateThemeMailTemplatesCommandHandler.php
  src/Core/MailTemplate/Layout/LayoutVariablesBuilder.php
  src/Core/MailTemplate/Layout/LayoutVariablesBuilderInterface.php
  src/PrestaShopBundle/Resources/config/services/core/mail_template.yml
  tests/Unit/Core/MailTemplate/LayoutVariablesBuilderTest.php
Labels: 1.7.6.x, Bug, QA ✔️

#13261 Fix lang on currency install
  classes/Currency.php
  classes/LocalizationPack.php
  install-dev/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php
  src/Adapter/Currency/CommandHandler/AddCurrencyHandler.php
  src/PrestaShopBundle/Resources/config/services/adapter/currency.yml
Labels: 1.7.6.x, Bug, QA ✔️

#13367 Remove deactivated currencies from new CLDR
  src/Core/Form/ChoiceProvider/CurrencyNameByIsoCodeChoiceProvider.php
  src/Core/Localization/CLDR/CurrencyData.php
  src/Core/Localization/CLDR/Reader.php
Labels: 1.7.6.x, Bug, QA ✔️

#13353 Fixes default Customer group overriding
  classes/Customer.php
  src/Adapter/Customer/CommandHandler/EditCustomerHandler.php
  src/Adapter/Customer/QueryHandler/GetCustomerForEditingHandler.php
Labels: 1.7.6.x, Bug, QA ✔️

#13409 Do not call removed cldr lib
  controllers/admin/AdminSpecificPriceRuleController.php
Labels: 1.7.6.x, Bug, QA ✔️

#13402 Add new hooks of 1.7.6.0 in fixtures
  install-dev/data/xml/hook.xml
Labels: 1.7.6.x, Improvement

#13429 Build outdated assets for 1.7.6.x
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/catalog_product.bundle.js
  admin-dev/themes/new-theme/public/categories.bundle.js
  admin-dev/themes/new-theme/public/cms_page.bundle.js
  admin-dev/themes/new-theme/public/cms_page_form.bundle.js
  admin-dev/themes/new-theme/public/contacts.bundle.js
  admin-dev/themes/new-theme/public/currency.bundle.js
  admin-dev/themes/new-theme/public/customer.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/employee.bundle.js
  admin-dev/themes/new-theme/public/employee_form.bundle.js
  admin-dev/themes/new-theme/public/form_popover_error.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/improve_design_positions.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/language.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/manufacturer.bundle.js
  admin-dev/themes/new-theme/public/manufacturer_address_form.bundle.js
  admin-dev/themes/new-theme/public/meta.bundle.js
  admin-dev/themes/new-theme/public/module.bundle.js
  admin-dev/themes/new-theme/public/module_card.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_page.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/profiles.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/supplier.bundle.js
  admin-dev/themes/new-theme/public/tax.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/themes.bundle.js
  admin-dev/themes/new-theme/public/translation_settings.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
Labels: 1.7.6.x, Bug

#13404 missing showcase card in cms page implementation
  admin-dev/themes/new-theme/js/pages/cms-page/index.js
  admin-dev/themes/new-theme/scss/img/helper-card/content-background@3x.png
  admin-dev/themes/new-theme/scss/img/helper-card/content@3x.png
  admin-dev/themes/new-theme/scss/pages/_cms_page.scss
  admin-dev/themes/new-theme/scss/theme.scss
  src/Core/Domain/ShowcaseCard/ConfigurationMap.php
  src/Core/Domain/ShowcaseCard/ValueObject/ShowcaseCard.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/CmsPageController.php
  src/PrestaShopBundle/Resources/config/services/core/util/helper_card.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Cms/Blocks/showcase_card.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Cms/index.html.twig
Labels: 1.7.6.x, Improvement, QA ✔️, Wording ✔️, migration

#13425 Border inside tabs when counter is empty
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/layout/_header_toolbar.scss
Labels: Bug, QA ✔️, develop

#13434 Remove material icons on SQL manager page
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/RequestSql/Blocks/form.html.twig
Labels: 1.7.6.x, Bug, QA ✔️

#13431 Fix parameters list in product lookup
  src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php
Labels: 1.7.6.x, Bug, QA ✔️

#13464 Apply CS Fixer on 1.7.6.x
  .github/main.workflow
  tests/Unit/Core/ConstraintValidator/TypedRegexValidatorTest.php
Labels: 1.7.6.x, Bug

#13435 Fixes option for MaterialMultipleChoiceTableType
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
Labels: 1.7.6.x, Bug, QA ✔️

#13461 Merge 1.7.6.x in develop
  .github/main.workflow
  src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer/customers.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/RequestSql/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
  src/PrestaShopBundle/Routing/Converter/AbstractLegacyRouteProvider.php
  src/PrestaShopBundle/Routing/Converter/Exception/AlreadyConvertedException.php
  src/PrestaShopBundle/Routing/Converter/LegacyUrlConverter.php
  tests/Integration/PrestaShopBundle/Routing/Converter/LegacyUrlConverterTest.php
  tests/TestCase/SymfonyIntegrationTestCase.php
  tests/Unit/Core/ConstraintValidator/TypedRegexValidatorTest.php
  tests/Unit/PrestaShopBundle/Routing/Converter/CacheProviderTest.php
  tests/Unit/PrestaShopBundle/Routing/Converter/LegacyRouteTest.php
  tests/Unit/PrestaShopBundle/Routing/Converter/LegacyUrlConverterTest.php
  tests/Unit/PrestaShopBundle/Routing/Converter/RouterProviderTest.php
  tests/Unit/PrestaShopBundle/Routing/Converter/RoutingCacheKeyGeneratorTest.php
Labels: Refactoring, develop

#13466 Brand and address export actions
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
Labels: 1.7.6.x, QA ✔️, Refactoring, Wording ✔️

#13470 Removes GetDefaultGroupHandler adapter
  src/Adapter/Group/QueryHandler/GetDefaultGroupsHandler.php
  src/PrestaShopBundle/Resources/config/services/adapter/group.yml
Labels: 1.7.6.x, Bug

#13003 free shipping behat tests
  classes/Cart.php
  tests/Integration/Behaviour/Features/Context/CarrierFeatureContext.php
  tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/Carrier/carrier.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/Carrier/cart_rule_carrier_specific.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/Carrier/change_carrier_cart_rule.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/amount_mono_virtual.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/carrier.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/CartToOrder/cart_to_order.feature
Labels: 1.7.6.x, Bug, QA ✔️, develop

#13486 Fix coding style on develop
  src/PrestaShopBundle/Command/SecurityAnnotationLinterCommand.php
Labels: Improvement, develop

#13482 Merge 1.7.6.x to develop - 18/04/2019
  classes/Cart.php
  src/Adapter/Group/QueryHandler/GetDefaultGroupsHandler.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
  src/PrestaShopBundle/Resources/config/services/adapter/group.yml
  tests/Integration/Behaviour/Features/Context/CarrierFeatureContext.php
  tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/Carrier/carrier.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/Carrier/cart_rule_carrier_specific.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/Carrier/change_carrier_cart_rule.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/amount_mono_virtual.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/carrier.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/CartToOrder/cart_to_order.feature
Labels: Bug, develop

#13528 Fix calendar overflow
  admin-dev/themes/new-theme/public/categories.bundle.js
  admin-dev/themes/new-theme/public/cms_page.bundle.js
  admin-dev/themes/new-theme/public/cms_page_form.bundle.js
  admin-dev/themes/new-theme/public/customer.bundle.js
  admin-dev/themes/new-theme/public/employee.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/manufacturer.bundle.js
  admin-dev/themes/new-theme/public/meta.bundle.js
  admin-dev/themes/new-theme/public/product_page.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/scss/components/_grid.scss
Labels: 1.7.6.x, Bug, QA ✔️, migration

#13542 Merge 1.7.6.x to develop - 23/04/2019
  admin-dev/themes/new-theme/js/components/form/text-with-recommended-length-counter.js
  admin-dev/themes/new-theme/js/pages/categories/index.js
  admin-dev/themes/new-theme/public/categories.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/_grid.scss
  src/Core/Domain/Category/SeoSettings.php
  src/PrestaShopBundle/Form/Admin/Catalog/Category/AbstractCategoryType.php
  src/PrestaShopBundle/Form/Admin/Type/TextWithRecommendedLengthType.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
Labels: Bug, develop

#13508 Enable ChoiceTree javascript in manufacturers form
  admin-dev/themes/new-theme/js/pages/manufacturer/index.js
  admin-dev/themes/new-theme/public/manufacturer.bundle.js
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Manufacturer/Address/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Manufacturer/Address/create.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Manufacturer/Address/edit.html.twig
Labels: 1.7.6.x, Bug, QA ✔️

#13540 Update upgrade scripts to PS 1.7.6.0
  install-dev/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php
  install-dev/upgrade/php/ps_1760_replace_index_of_admin_filter.php
  install-dev/upgrade/sql/1.7.6.0.sql
Labels: 1.7.6.x, Bug, QA ✔️

#13535 Fix responsive showcase cards
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/_showcase-card.scss
Labels: 1.7.6.x, Bug, QA ✔️, migration

#13525 fix currency display on not existing language
  classes/Currency.php
  src/Adapter/Currency/CurrencyDataProvider.php
Labels: 1.7.6.x, Bug, QA ✔️

#13484 Fixes Categories grid filtering by position
  src/Core/Grid/Query/CategoryQueryBuilder.php
Labels: 1.7.6.x, Bug, QA ✔️, migration

#13549 Forbid URLs to be inserted into Name fields
  classes/Validate.php
  tests/Unit/Classes/ValidateCoreTest.php
Labels: 1.7.5.x, Bug, QA ✔️

#13557 Merge 1.7.6.x to develop - 25/04/2019
  admin-dev/themes/new-theme/js/pages/manufacturer/index.js
  admin-dev/themes/new-theme/public/manufacturer.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/_showcase-card.scss
  classes/Currency.php
  install-dev/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php
  install-dev/upgrade/php/ps_1760_replace_index_of_admin_filter.php
  install-dev/upgrade/sql/1.7.6.0.sql
  src/Adapter/Currency/CurrencyDataProvider.php
  src/Core/Grid/Query/CategoryQueryBuilder.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Manufacturer/Address/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Manufacturer/Address/create.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Manufacturer/Address/edit.html.twig
Labels: Bug, develop

#13411 Hide tax label in front when tax display is disabled in the shop
  themes/classic/templates/catalog/_partials/product-prices.tpl
Labels: 1.7.6.x, Bug, QA ✔️

#13536 Fixes e2e broken selectors
  tests/E2E/test/campaigns/common_scenarios/customer.js
  tests/E2E/test/selectors/BO/customers/customer.js
  tests/E2E/test/selectors/BO/customers/index.js
Labels: 1.7.6.x, Refactoring, TE

#13560 Remove duplicate method call
  src/Core/Translation/Locale/Converter.php
Labels: 1.7.6.x, Bug

#13547 Deprecate Language::installEmailsLanguagePack
  classes/Language.php
  src/Core/Domain/MailTemplate/CommandHandler/GenerateThemeMailTemplatesCommandHandler.php
Labels: 1.7.6.x, Bug, QA ✔️

#13552 Fix tests International/localization and international/taxes
  tests/E2E/test/campaigns/common_scenarios/currency.js
  tests/E2E/test/campaigns/full/11_international/1_localization/4_create_edit_delete_live_exchange_rate_currency.js
  tests/E2E/test/selectors/BO/international/localization.js
  tests/E2E/test/selectors/BO/international/taxes.js
  tests/E2E/test/selectors/BO/menu.js
Labels: 1.7.6.x, Refactoring, TE

#13534 Fix tests manufacturer
  tests/E2E/test/campaigns/common_scenarios/manufacturers.js
  tests/E2E/test/campaigns/full/07_manufacturer/1_create_manufacturers.js
  tests/E2E/test/selectors/BO/catalogpage/Manufacturers/brands.js
  tests/E2E/test/selectors/BO/catalogpage/Manufacturers/brands_address.js
  tests/E2E/test/selectors/BO/catalogpage/index.js
  tests/E2E/test/selectors/FO/site_map_page.js
Labels: 1.7.6.x, Refactoring, TE

#13503 FIx test Create Attribute Suite Full
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/clients/common_client.js
Labels: 1.7.6.x, E2E Tests, Refactoring, TE

#13559 Forbid URLs to be inserted into Name fields
  classes/Validate.php
  tests/Unit/classes/ValidateCoreTest.php
Labels: 1.6.1.x, Bug, QA ✔️

#13561 fix for tests 1 and 2 of the shop_parameters test suite
  tests/E2E/test/campaigns/high/12_shop_parameters/1_enable_and_disable_shop.js
  tests/E2E/test/selectors/BO/pages_form.js
Labels: 1.7.6.x, Refactoring, TE

#13567 Improve name validation
  classes/Validate.php
  tests/Unit/Classes/ValidateCoreTest.php
Labels: 1.7.5.x, Bug, QA ✔️

#13454 Fix on product redirect in SEO tabs
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/pages/_product_page.scss
Labels: Bug, QA ✔️, develop

#13574 Improve name validation
  classes/Validate.php
  tests/Unit/classes/ValidateCoreTest.php
Labels: 1.6.1.x, Bug, QA ✔️

#13550 Add missing check in Manufacturer image uploader
  src/Adapter/Image/Uploader/ManufacturerImageUploader.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Manufacturer/index.html.twig
Labels: 1.7.6.x, Bug, QA ✔️

#13568 Fix tests 10_module Suite Full
  tests/E2E/test/campaigns/common_scenarios/module.js
  tests/E2E/test/campaigns/full/10_module/5_check_addons_catalog_page.js
  tests/E2E/test/selectors/BO/addons_catalog_page.js
  tests/E2E/test/selectors/BO/module_page.js
Labels: 1.7.6.x, Refactoring, TE

#13572 Add FiltersSubmitButtonEnablerExtension to profiles page
  admin-dev/themes/new-theme/js/pages/profiles/ProfilesPage.js
  admin-dev/themes/new-theme/public/profiles.bundle.js
Labels: Bug, QA ✔️, develop

#13581 fix test feature update
  tests/E2E/test/campaigns/common_scenarios/feature.js
  tests/E2E/test/selectors/BO/catalogpage/feature_submenu.js
Labels: 1.7.6.x, Refactoring, TE

#13580 Fixed dispatched hook on the Grid presenter
  src/Core/Grid/Presenter/GridPresenter.php
Labels: Bug

#13595 Merge 1.7.6.x to develop - 29/04/2019
  classes/Language.php
  src/Adapter/Image/Uploader/ManufacturerImageUploader.php
  src/Core/Domain/MailTemplate/CommandHandler/GenerateThemeMailTemplatesCommandHandler.php
  src/Core/Translation/Locale/Converter.php
  src/Core/Util/Url/BackUrlProvider.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
  src/PrestaShopBundle/EventListener/BackUrlRedirectResponseListener.php
  src/PrestaShopBundle/Resources/config/services/bundle/event_listener.yml
  src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
  src/PrestaShopBundle/Resources/config/services/core/util.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Manufacturer/index.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/form.html.twig
  src/PrestaShopBundle/Twig/Extension/PathWithBackUrlExtension.php
  tests/E2E/test/campaigns/common_scenarios/currency.js
  tests/E2E/test/campaigns/common_scenarios/customer.js
  tests/E2E/test/campaigns/common_scenarios/feature.js
  tests/E2E/test/campaigns/common_scenarios/manufacturers.js
  tests/E2E/test/campaigns/common_scenarios/module.js
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/full/07_manufacturer/1_create_manufacturers.js
  tests/E2E/test/campaigns/full/10_module/5_check_addons_catalog_page.js
  tests/E2E/test/campaigns/full/11_international/1_localization/4_create_edit_delete_live_exchange_rate_currency.js
  tests/E2E/test/campaigns/high/12_shop_parameters/1_enable_and_disable_shop.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/selectors/BO/addons_catalog_page.js
  tests/E2E/test/selectors/BO/catalogpage/Manufacturers/brands.js
  tests/E2E/test/selectors/BO/catalogpage/Manufacturers/brands_address.js
  tests/E2E/test/selectors/BO/catalogpage/feature_submenu.js
  tests/E2E/test/selectors/BO/catalogpage/index.js
  tests/E2E/test/selectors/BO/customers/customer.js
  tests/E2E/test/selectors/BO/customers/index.js
  tests/E2E/test/selectors/BO/international/localization.js
  tests/E2E/test/selectors/BO/international/taxes.js
  tests/E2E/test/selectors/BO/menu.js
  tests/E2E/test/selectors/BO/module_page.js
  tests/E2E/test/selectors/BO/pages_form.js
  tests/E2E/test/selectors/FO/site_map_page.js
  tests/Unit/Core/Util/Url/BackUrlProviderTest.php
  tests/Unit/PrestaShopBundle/EventListener/BackUrlRedirectResponseListenerTest.php
  tests/Unit/PrestaShopBundle/Twig/Extension/PathWithBackUrlExtensionTest.php
  themes/classic/templates/catalog/_partials/product-prices.tpl
Labels: Bug, develop

#13563 Do not get data from null currency
  classes/Currency.php
Labels: 1.7.6.x, Bug, QA ✔️

#13588 Fixing some tests orders
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/campaigns/full/01_orders/12_generate_pdf_by_date.js
  tests/E2E/test/campaigns/full/01_orders/13_generate_pdf_by_status.js
  tests/E2E/test/campaigns/full/01_orders/14_print_the_invoice_order.js
  tests/E2E/test/campaigns/full/01_orders/15_print_delivery_slip.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/selectors/BO/international/taxes.js
Labels: 1.7.6.x, Refactoring, TE

#13597 Fix test 09_delivery_slips_pdf_and_options
  tests/E2E/test/campaigns/common_scenarios/order.js
Labels: 1.7.6.x, Refactoring, TE

#13502 Fix test Category suite full
  tests/E2E/test/campaigns/common_scenarios/category.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/selectors/BO/catalogpage/category_submenu.js
Labels: 1.7.6.x, E2E Tests, TE

#13609 Fixed dispatched hook on the Grid presenter
  src/Core/Grid/Presenter/GridPresenter.php
Labels: 1.7.6.x, Bug, Cherry-picked ✔️

#13603 Add id for orders view page to ease E2E testing
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/orders.html.twig
Labels: 1.7.6.x, Improvement, QA ✔️

#13599 Forbid URLS to be added in customer names
  classes/Customer.php
  classes/Validate.php
  classes/ValidateConstraintTranslator.php
  js/validate.js
  tests/Unit/Classes/ValidateCoreTest.php
Labels: 1.7.5.x, Bug, QA ✔️

#13602 Fix for test 2 of the orders test suite
  tests/E2E/test/campaigns/full/01_orders/01_create_order_in_BO.js
  tests/E2E/test/campaigns/full/01_orders/02_create_order_in_FO.js
  tests/E2E/test/selectors/BO/customers/customer.js
  tests/E2E/test/selectors/BO/order.js
Labels: 1.7.6.x, Refactoring, TE

#13606 Fix phpdoc on Module class
  classes/module/Module.php
Labels: Improvement, develop

#13607 Forbid URLs to be inserted into Name fields
  classes/Customer.php
  classes/Validate.php
  js/validate.js
  tests/Unit/classes/ValidateCoreTest.php
  themes/default-bootstrap/authentication.tpl
  themes/default-bootstrap/identity.tpl
Labels: 1.6.1.x, Bug, QA ✔️

#13583 Fix selector in E2E tests for addons catalog page and another one in the autoupgrage test
  tests/E2E/test/campaigns/install_upgrade/02_autoupgrade.js
  tests/E2E/test/selectors/BO/addons_catalog_page.js
Labels: 1.7.5.x, Refactoring, TE

#13440 Change checkout behaviour (needs to be validated after meeting)
  themes/_core/js/checkout.js
  themes/classic/_dev/js/checkout.js
  themes/classic/assets/js/theme.js
  themes/classic/templates/checkout/_partials/steps/personal-information.tpl
  themes/core.js
  themes/core.js.map
  themes/package-lock.json
Labels: 1.7.6.x, Bug, QA ✔️

#13578 Automatically add dni field in Address format for countries which need it
  classes/AddressFormat.php
  controllers/admin/AdminCountriesController.php
Labels: 1.7.6.x, Bug, QA ✔️

#13616 fix method to change quantity
  tests/E2E/test/campaigns/common_scenarios/order.js
Labels: 1.7.6.x, Refactoring, TE

#13471 Set null values when trying to retrieve the non-existing default shop
  classes/Language.php
  classes/shop/ShopUrl.php
Labels: 1.7.6.x, Bug, QA ✔️

#13571 Enable grid search button by default
  admin-dev/themes/new-theme/js/components/grid/extension/filters-submit-button-enabler-extension.js
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/categories.bundle.js
  admin-dev/themes/new-theme/public/cms_page.bundle.js
  admin-dev/themes/new-theme/public/currency.bundle.js
  admin-dev/themes/new-theme/public/customer.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/employee.bundle.js
  admin-dev/themes/new-theme/public/language.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/manufacturer.bundle.js
  admin-dev/themes/new-theme/public/meta.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/supplier.bundle.js
  admin-dev/themes/new-theme/public/tax.bundle.js
  src/PrestaShopBundle/Form/Admin/Type/SearchAndResetType.php
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
Labels: Bug, QA ✔️, UX ✔️, develop, migration

#13545 Fix test Employee Suite Full
  tests/E2E/test/campaigns/high/13_employee/1_employee.js
  tests/E2E/test/selectors/BO/access_page.js
  tests/E2E/test/selectors/BO/employee_page.js
Labels: 1.7.6.x, Refactoring, TE
