Repository PrestaShop/PrestaShop, pull requests merged in 2019-05, with the labels that each got.

#13615 Fix test Product suite full
  tests/E2E/test/campaigns/broken_tests/12_shop_parameters/3_onboarding.js
  tests/E2E/test/campaigns/common_scenarios/module.js
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/common_scenarios/shop_parameters.js
  tests/E2E/test/campaigns/full/01_orders/05_create_order_without_account.js
  tests/E2E/test/campaigns/full/02_product/04_create_virtual_product.js
  tests/E2E/test/campaigns/full/02_product/07_next_and_previous_page.js
  tests/E2E/test/campaigns/full/02_product/08_filters_in_catalog_page.js
  tests/E2E/test/campaigns/full/02_product/16_filter_by_categories_in_catalog_page.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/clients/product/product.js
  tests/E2E/test/selectors/BO/add_product_page.js
  tests/E2E/test/selectors/BO/catalogpage/category_submenu.js
Labels: 1.7.6.x, Refactoring, TE

#13612 Fix test 05 create order without account
  tests/E2E/test/campaigns/full/01_orders/05_create_order_without_account.js
  tests/E2E/test/selectors/BO/customers/customer.js
  tests/E2E/test/selectors/BO/employee_page.js
  tests/E2E/test/selectors/FO/order_page.js
Labels: 1.7.6.x, Bug, Refactoring, TE

#13372 Add missing security annotations
  src/PrestaShopBundle/Controller/Admin/CommonController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ImportController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ImportDataConfigurationController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ProfileController.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/LanguageController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/SupplierController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
  src/PrestaShopBundle/Controller/Admin/StockController.php
  src/PrestaShopBundle/Controller/Api/ApiController.php
  src/PrestaShopBundle/Controller/Api/StockController.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/employee.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/translations.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/stocks.yml
  src/PrestaShopBundle/Resources/config/routing/api/stocks.yml
Labels: 1.7.6.x, Bug, QA ✔️, migration

#13407 Fix labels display computing
  src/Adapter/Presenter/Product/ProductLazyArray.php
  tests-legacy/Unit/Core/Business/Product/ProductPresenterTest.php
  themes/classic/_dev/css/components/featuredproducts.scss
  themes/classic/_dev/css/components/products.scss
  themes/classic/_dev/js/components/product-miniature.js
  themes/classic/_dev/js/components/product-select.js
  themes/classic/_dev/package-lock.json
  themes/classic/assets/css/theme.css
  themes/classic/assets/js/theme.js
Labels: 1.7.6.x, Bug, QA ✔️

#13605 Add missing translation domains
  src/Core/Import/EntityField/Provider/AddressFieldsProvider.php
  src/Core/Import/EntityField/Provider/CategoryFieldsProvider.php
  src/Core/Import/EntityField/Provider/CombinationFieldsProvider.php
  src/Core/Import/EntityField/Provider/CustomerFieldsProvider.php
  src/Core/Import/EntityField/Provider/ProductFieldsProvider.php
  src/Core/Import/EntityField/Provider/StoreContactFieldsProvider.php
  src/Core/Import/EntityField/Provider/SupplierFieldsProvider.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/RequestSql/Blocks/form.html.twig
Labels: 1.7.6.x, Bug, Wording ✔️

#13604 Forbid URLS to be added in customer names
  classes/Customer.php
  classes/Validate.php
  classes/ValidateConstraintTranslator.php
  js/validate.js
  tests-legacy/Unit/Classes/ValidateCoreTest.php
Labels: 1.7.6.x, Bug, QA ✔️

#13635 Fix product link should not include attribute parameter equals to zero
  src/Adapter/Presenter/Product/ProductLazyArray.php
Labels: 1.7.6.x, Bug, QA ✔️

#13659 Adding close welcome module in tests Attribute
  tests/E2E/test/campaigns/full/04_attribute/2_create_attribute.js
Labels: 1.7.6.x, Refactoring, TE

#13651 Adding close welcome module in tests product
  tests/E2E/test/campaigns/full/02_product/07_next_and_previous_page.js
  tests/E2E/test/campaigns/full/02_product/08_filters_in_catalog_page.js
  tests/E2E/test/campaigns/full/02_product/10_buttons_in_footer_product_page.js
  tests/E2E/test/campaigns/full/02_product/11_delete_product.js
  tests/E2E/test/campaigns/full/02_product/12_edit_check_demo_product_in_BO.js
  tests/E2E/test/campaigns/full/02_product/13_navigate_between_catalog_pages.js
  tests/E2E/test/campaigns/full/02_product/14_options_in_catalog_page.js
  tests/E2E/test/campaigns/full/02_product/15_buttons_in_header_product_page.js
  tests/E2E/test/campaigns/full/02_product/16_filter_by_categories_in_catalog_page.js
  tests/E2E/test/campaigns/full/02_product/17_display_all_product.js
  tests/E2E/test/campaigns/high/02_product/02_create_pack_of_product.js
  tests/E2E/test/campaigns/high/02_product/05_check_default_product_sort.js
  tests/E2E/test/campaigns/high/02_product/06_pack_stock.js
  tests/E2E/test/campaigns/high/02_product/08_check_shopping_cart.js
Labels: 1.7.6.x, Refactoring, TE

#13617 Fix not null voucher with free shipping producing php error
  classes/Cart.php
  src/Core/Cart/Calculator.php
  src/Core/Cart/CartRuleCalculator.php
  tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/free_shipping.feature
Labels: 1.7.6.x, Bug, QA ✔️

#13623 Fix categories deleting in bulk action
  admin-dev/themes/new-theme/js/components/grid/extension/action/bulk/category/delete-categories-bulk-action-extension.js
  admin-dev/themes/new-theme/public/categories.bundle.js
Labels: 1.7.6.x, Bug, QA ✔️, migration

#13684 Wrong discount subtotal when customergroup is set to use ex taxes
  classes/Cart.php
  src/Adapter/Presenter/Cart/CartPresenter.php
Labels: 1.7.6.x, Bug, QA ✔️

#13643 Fixes incorrect hook names for identifiable object forms.
  src/Core/Form/IdentifiableObject/Builder/FormBuilder.php
  src/Core/Form/IdentifiableObject/Handler/FormHandler.php
Labels: 1.7.6.x, Bug

#13661 fix for test 4 of the order test suite after canonical url fix
  tests/E2E/test/campaigns/full/01_orders/04_check_adding_product_to_cart_with_unavailable_quantities.js
Labels: 1.7.6.x, Refactoring, TE

#13637 Add handling of the welcome modal and document the blocking issue for the last step
  tests/E2E/test/campaigns/full/01_orders/04_check_adding_product_to_cart_with_unavailable_quantities.js
Labels: 1.7.6.x, Refactoring, TE

#13664 Remove id_attribute parameter from product link when it is equal to 0
  classes/Link.php
  controllers/front/ProductController.php
Labels: 1.7.6.x, Bug, QA ✔️

#13700 fix for test 3 of the test suite 12
  tests/E2E/test/selectors/BO/onboarding.js
Labels: 1.7.6.x, Refactoring, TE

#13696 Add welcome module for tests discount
  tests/E2E/test/campaigns/full/14_discount/2_check_discount_in_FO.js
  tests/E2E/test/campaigns/full/14_discount/3_check_vouchers_in_FO.js
  tests/E2E/test/selectors/FO/search_product_page.js
Labels: 1.7.6.x, Refactoring, TE

#13693 fix test 01 of the order test suite
  tests/E2E/test/campaigns/full/01_orders/01_create_order_in_BO.js
  tests/E2E/test/selectors/BO/order.js
Labels: 1.7.6.x, Refactoring, TE

#13676 Add close welcome modal for tests Manufacturer
  tests/E2E/test/campaigns/full/07_manufacturer/2_create_brand_address.js
Labels: 1.7.6.x, Refactoring, TE

#13667 Fix test Feature 1 create edit delete feature
  tests/E2E/test/clients/product/product.js
  tests/E2E/test/selectors/BO/add_product_page.js
Labels: 1.7.6.x, Refactoring, TE

#13657 Fix the check of the success message when saving and deleting a currency
  tests/E2E/test/campaigns/full/02_product/04_create_virtual_product.js
Labels: 1.7.6.x, Refactoring

#13656 Fix for tests in order test suite
  tests/E2E/test/campaigns/full/01_orders/06_delete_shopping_carts.js
  tests/E2E/test/campaigns/full/01_orders/07_export_shopping_carts.js
  tests/E2E/test/campaigns/full/01_orders/09_delivery_slips_pdf_and_options.js
  tests/E2E/test/campaigns/full/01_orders/10_check_credit_slip.js
  tests/E2E/test/campaigns/full/01_orders/11_credit_slips_options.js
  tests/E2E/test/campaigns/full/01_orders/12_generate_pdf_by_date.js
  tests/E2E/test/campaigns/full/01_orders/13_generate_pdf_by_status.js
  tests/E2E/test/campaigns/full/01_orders/14_print_the_invoice_order.js
  tests/E2E/test/campaigns/full/01_orders/15_print_delivery_slip.js
  tests/E2E/test/campaigns/full/01_orders/16_credit_slip_PDF.js
Labels: 1.7.6.x, Refactoring, TE

#13630 Fix Onboarding close method
  tests/E2E/test/campaigns/common_scenarios/welcome.js
  tests/E2E/test/campaigns/full/01_orders/05_create_order_without_account.js
  tests/E2E/test/selectors/BO/onboarding.js
Labels: 1.7.6.x, Refactoring, TE

#13680 Fix tests customer
  tests/E2E/test/campaigns/common_scenarios/customer.js
  tests/E2E/test/campaigns/full/09_customer/customer_settings/1_create_edit_delete_customer.js
Labels: 1.7.6.x, Refactoring, TE

#13683 Add close welcome module for tests 10_modules
  tests/E2E/test/campaigns/full/10_module/3_search_module.js
  tests/E2E/test/campaigns/full/10_module/4_sort_module.js
  tests/E2E/test/campaigns/full/10_module/5_check_addons_catalog_page.js
  tests/E2E/test/campaigns/full/10_module/6_check_notifications.js
  tests/E2E/test/campaigns/full/10_module/7_discover_module.js
Labels: 1.7.6.x, Refactoring, TE, waiting for author

#13686 Add close welcome module for tests 11_international
  tests/E2E/test/campaigns/common_scenarios/positions.js
  tests/E2E/test/campaigns/full/11_international/1_localization/1_import_localization.js
  tests/E2E/test/campaigns/full/11_international/1_localization/2_local_units.js
  tests/E2E/test/campaigns/full/11_international/1_localization/3_advanced.js
  tests/E2E/test/campaigns/full/11_international/1_localization/4_create_edit_delete_live_exchange_rate_currency.js
  tests/E2E/test/campaigns/full/11_international/2_locations/2_create_edit_activate_restrictions_country.js
Labels: 1.7.6.x, Refactoring, TE, waiting for author

#13735 Update native modules
  composer.json
  composer.lock
Labels: 1.7.6.x, Improvement

#13018 Only run deploy if the triggered commit is recent
  .travis.yml
Labels: Improvement, develop

#13198 Create SF command to return routes with missing _legacy_link
  src/PrestaShopBundle/Command/LegacyLinkLinterCommand.php
  src/PrestaShopBundle/Resources/config/services/bundle/routing.yml
  src/PrestaShopBundle/Routing/Linter/LegacyLinkLinter.php
Labels: Improvement, develop, migration

#13739 Fix after merge of PR tinymce
  tests/E2E/test/campaigns/common_scenarios/category.js
  tests/E2E/test/campaigns/common_scenarios/manufacturers.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/selectors/BO/catalogpage/Manufacturers/brands.js
  tests/E2E/test/selectors/BO/catalogpage/category_submenu.js
Labels: 1.7.6.x, Refactoring, TE

#13704 Fix exclude discounted products on CartRule
  src/Core/Cart/CartRuleCalculator.php
  tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/cheapest_product.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/exclude_discounted_product.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/Product/specific_price.feature
Labels: Bug, QA ✔️, develop

#13687 Update OrderReturn.php
  classes/order/OrderReturn.php
Labels: 1.7.5.x, Bug, QA ✔️

#13738 Escape strings in installation assistant plus remove unwanted javascript
  install-dev/controllers/http/configure.php
  install-dev/theme/views/configure.php
Labels: 1.7.6.x, Bug, QA ✔️

#13711 Compare strictly value of hook name when getting modules registered on it
  classes/Hook.php
Labels: Bug, QA ✔️, develop

#13768 Merge beta release into 1.7.6.x
  CONTRIBUTORS.md
  classes/Validate.php
  docs/CHANGELOG.txt
  src/Core/Grid/Presenter/GridPresenter.php
  tests/E2E/test/campaigns/install_upgrade/02_autoupgrade.js
Labels: 1.7.6.x, release

#13766 Merge 1.7.5.2 into 1.7.6.x
  CONTRIBUTORS.md
  classes/Validate.php
  docs/CHANGELOG.txt
  src/Core/Grid/Presenter/GridPresenter.php
  tests/E2E/test/campaigns/install_upgrade/02_autoupgrade.js
Labels: 1.7.6.x, Bug

#13765 Fix sql manager bulk actions
  admin-dev/themes/new-theme/js/pages/sql-manager/index.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SqlManagerController.php
Labels: 1.7.6.x, Bug, QA ✔️

#13763 Fix help sidebar display in Customers page
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
Labels: 1.7.6.x, Bug, QA ✔️

#13593 Automated hooks discovery and updating hooks list in xml and sql files
  src/Core/Hook/Generator/HookDescriptionGenerator.php
  src/Core/Hook/Generator/HookDescriptionGeneratorInterface.php
  src/Core/Hook/HookDescription.php
  src/Core/Hook/Provider/GridDefinitionHookByServiceIdsProvider.php
  src/Core/Hook/Provider/HookByFormTypeProviderInterface.php
  src/Core/Hook/Provider/HookByServiceIdsProviderInterface.php
  src/Core/Hook/Provider/IdentifiableObjectHookByFormTypeProvider.php
  src/Core/Util/String/StringModifier.php
  src/Core/Util/String/StringModifierInterface.php
  src/Core/Util/String/StringValidator.php
  src/Core/Util/String/StringValidatorInterface.php
  src/PrestaShopBundle/Command/AppendConfigurationFileHooksListCommand.php
  src/PrestaShopBundle/Command/AppendHooksListForSqlUpgradeFileCommand.php
  src/PrestaShopBundle/DependencyInjection/Compiler/GridDefinitionServiceIdsCollectorPass.php
  src/PrestaShopBundle/DependencyInjection/Compiler/IdentifiableObjectFormTypesCollectorPass.php
  src/PrestaShopBundle/DependencyInjection/Compiler/OptionsFormHookNameCollectorPass.php
  src/PrestaShopBundle/PrestaShopBundle.php
  src/PrestaShopBundle/Resources/config/services/core/hook.yml
  src/PrestaShopBundle/Resources/config/services/core/util/string.yml
  tests/Unit/Core/Hook/Generator/HookDescriptionGeneratorTest.php
  tests/Unit/Core/Util/String/StringModifierTest.php
  tests/Unit/Core/Util/String/StringValidatorTest.php
Labels: Feature, develop, migration

#13722 Filter themes without override in email generation form
  src/Core/Form/ChoiceProvider/ThemeByNameWithEmailsChoiceProvider.php
  src/PrestaShopBundle/Form/Admin/Improve/Design/MailTheme/GenerateMailsType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/choice_provider.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/MailTheme/Blocks/generate_mails_form.html.twig
Labels: 1.7.6.x, Improvement, QA ✔️, Wording ✔️

#13776 Improve tests orders and category
  tests/E2E/test/campaigns/common_scenarios/category.js
  tests/E2E/test/campaigns/full/01_orders/01_create_order_in_BO.js
  tests/E2E/test/campaigns/full/01_orders/05_create_order_without_account.js
Labels: 1.7.6.x, Refactoring, TE

#13780 fix displayed discount on tax excluded cart display
  src/Adapter/Presenter/Cart/CartPresenter.php
Labels: 1.7.6.x, Bug, QA ✔️

#13772 Correct usage of fixtures on behat tests for taxes
  tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Context/TaxFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/Taxes/tax.feature
Labels: Refactoring, develop

#13764 Fixes customer view url in notifications bar
  classes/Notification.php
  js/admin/notifications.js
Labels: Bug, QA ✔️

#13777 Incorrect translation arguments passed in cms page form
  src/PrestaShopBundle/Form/Admin/Improve/Design/Pages/CmsPageType.php
  tests-legacy/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
  tests-legacy/Integration/PrestaShopBundle/Test/LightWebTestCase.php
Labels: 1.7.6.x, Critical, QA ✔️, Type: Critical Bug Fix, migration

#13779 Allow to overwrite theme mails if they have modules OR mail templates
  src/Core/Form/ChoiceProvider/ThemeByNameWithEmailsChoiceProvider.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php
Labels: 1.7.6.x, Improvement, QA ✔️

#13798 Change input type for imap password
  controllers/admin/AdminCustomerThreadsController.php
Labels: Bug, QA ✔️, develop

#13808 Update Symfony to latest patch version to fix ICU version problem
  composer.json
  composer.lock
Labels: 1.7.6.x, Bug

#13778 Add new hooks for Symfony migrated pages in XML install file and SQL upgrade
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.6.0.sql
Labels: 1.7.6.x, Improvement

#12891 Fix bug on block social in footer
  themes/classic/_dev/css/components/footer.scss
  themes/classic/assets/css/theme.css
Labels: 1.7.6.x, Bug, QA ✔️, develop

#13726 Moving tests High to full or to broken tests
  tests/E2E/test/campaigns/broken_tests/02_product/03_create_product_with_combination.js
  tests/E2E/test/campaigns/full/01_orders/03_create_account_from_checkout_FO.js
  tests/E2E/test/campaigns/full/02_product/01_create_standard_product.js
  tests/E2E/test/campaigns/full/02_product/02_create_pack_of_product.js
  tests/E2E/test/campaigns/full/02_product/05_check_default_product_sort.js
  tests/E2E/test/campaigns/full/02_product/06_pack_stock.js
  tests/E2E/test/campaigns/full/02_product/09_check_shopping_cart.js
  tests/E2E/test/campaigns/full/04_attribute/1_create_edit_delete_attribute_value.js
  tests/E2E/test/campaigns/full/05_feature/1_create_edit_delete_feature.js
  tests/E2E/test/campaigns/full/08_stocks/1_group_of_product_quantity.js
  tests/E2E/test/campaigns/full/08_stocks/2_single_product_quantity.js
  tests/E2E/test/campaigns/full/08_stocks/3_check_order_movement.js
  tests/E2E/test/campaigns/full/09_customer/customer_settings/2_create_customer_in_FO.js
  tests/E2E/test/campaigns/full/10_module/2_cross_selling_module.js
  tests/E2E/test/campaigns/full/11_international/translation.js
  tests/E2E/test/campaigns/full/12_shop_parameters/1_enable_and_disable_shop.js
  tests/E2E/test/campaigns/full/13_employee/1_employee.js
  tests/E2E/test/campaigns/high/01_orders/3_create_account_from_checkout_FO.js
  tests/E2E/test/campaigns/high/02_product/01_create_standard_product.js
  tests/E2E/test/campaigns/high/02_product/02_create_pack_of_product.js
  tests/E2E/test/campaigns/high/02_product/03_create_product_with_combination.js
  tests/E2E/test/campaigns/high/02_product/05_check_default_product_sort.js
  tests/E2E/test/campaigns/high/02_product/06_pack_stock.js
  tests/E2E/test/campaigns/high/02_product/08_check_shopping_cart.js
  tests/E2E/test/campaigns/high/04_attribute/1_create_edit_delete_attribute_value.js
  tests/E2E/test/campaigns/high/05_feature/1_create_edit_delete_feature.js
  tests/E2E/test/campaigns/high/08_stocks/1_group_of_product_quantity.js
  tests/E2E/test/campaigns/high/08_stocks/2_single_product_quantity.js
  tests/E2E/test/campaigns/high/08_stocks/3_check_order_movement.js
  tests/E2E/test/campaigns/high/09_customer/3_create_customer_in_FO.js
  tests/E2E/test/campaigns/high/10_module/2_cross_selling_module.js
  tests/E2E/test/campaigns/high/11_international/translation.js
  tests/E2E/test/campaigns/high/12_shop_parameters/1_enable_and_disable_shop.js
  tests/E2E/test/campaigns/high/13_employee/1_employee.js
  tests/E2E/test/campaigns/regular/05_create_account.js
Labels: 1.7.6.x, Refactoring, TE

#13818 Remove redundant condition in cart.php
  classes/Cart.php
Labels: Improvement, develop

#13824 Update tests and package-lock
  tests/E2E/package-lock.json
  tests/E2E/scripts/run-nightly-tests.sh
Labels: Bug, develop

#13811 Download in headless mode in tests
  tests/E2E/package.json
  tests/E2E/test/campaigns/common_scenarios/order.js
  tests/E2E/test/campaigns/full/01_orders/09_delivery_slips_pdf_and_options.js
  tests/E2E/test/campaigns/full/01_orders/11_credit_slips_options.js
  tests/E2E/test/campaigns/full/01_orders/14_print_the_invoice_order.js
  tests/E2E/test/campaigns/full/01_orders/15_print_delivery_slip.js
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/common.webdriverio.js
Labels: 1.7.6.x, Refactoring, TE

#13827 Revert "Only run deploy if the triggered commit is recent"
  .travis.yml
Labels: develop

#13736 Replace all calls to $this->l() in controllers
  classes/controller/AdminController.php
  controllers/admin/AdminCmsController.php
  controllers/admin/AdminCountriesController.php
  controllers/admin/AdminImportController.php
  controllers/admin/AdminModulesController.php
  controllers/admin/AdminTabsController.php
Labels: QA ✔️, Refactoring, develop

#13831 Force report name
  tests/E2E/scripts/run-nightly-reports.sh
Labels: 1.7.6.x, Bug

#13165 Fix multilanguage fields configuration
  src/Adapter/Configuration.php
  src/Adapter/LegacyContext.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/StockType.php
  src/PrestaShopBundle/Form/Admin/Type/TranslatableType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  tests-legacy/Integration/PrestaShopBundle/Test/LightWebTestCase.php
Labels: 1.7.6.x, Bug, QA ✔️, migration

#13803 Make the movement of the Grid columns really easy
  src/Core/Grid/Column/ColumnCollection.php
  tests-legacy/Unit/Core/Grid/Column/ColumnCollectionTest.php
Labels: Improvement, develop

#13821 Fix manufacturers, taxes lists id filtering
  src/Core/Grid/Query/ManufacturerAddressQueryBuilder.php
  src/Core/Grid/Query/ManufacturerQueryBuilder.php
  src/Core/Grid/Query/TaxQueryBuilder.php
Labels: 1.7.6.x, Bug, QA ✔️

#13862 Improve E2E report
  tests/E2E/scripts/run-nightly-reports.sh
  tests/E2E/scripts/run-nightly-tests.sh
Labels: Improvement, TE

#13864 Apply develop fix on 1.7.6.x branch
  tests/E2E/scripts/run-nightly-reports.sh
  tests/E2E/scripts/run-nightly-tests.sh
Labels: Improvement, TE

#13690 Theme and logo page design fixes
  admin-dev/themes/new-theme/scss/pages/_themes_logo.scss
  admin-dev/themes/new-theme/scss/pages/partials/_theme_logo_configuration.scss
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Theme/Blocks/layouts_configuration.html.twig
Labels: 1.7.6.x, Bug, QA ✔️, migration

#13797 Adds missing legacy links for currency controller
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/currencies.yml
  tests/Integration/PrestaShopBundle/Routing/Converter/LegacyUrlConverterTest.php
Labels: 1.7.6.x, Bug

#13852 Delete legacy AdminRequestSqlController
  admin-dev/themes/default/template/controllers/request_sql/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/request_sql/helpers/view/view.tpl
  admin-dev/themes/default/template/controllers/request_sql/list_action_export.tpl
  controllers/admin/AdminRequestSqlController.php
Labels: 1.7.6.x, Refactoring, migration

#13850 Deletes AdminModulesPositions legacy controller
  admin-dev/themes/default/template/controllers/modules_positions/form.tpl
  admin-dev/themes/default/template/controllers/modules_positions/index.php
  admin-dev/themes/default/template/controllers/modules_positions/list_modules.tpl
  controllers/admin/AdminModulesPositionsController.php
Labels: 1.7.6.x, Refactoring, migration

#13849 Deletes legacy AdminCms controllers
  admin-dev/themes/default/template/controllers/cms/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/cms/helpers/form/index.php
  admin-dev/themes/default/template/controllers/cms/helpers/index.php
  admin-dev/themes/default/template/controllers/cms/index.php
  admin-dev/themes/default/template/controllers/cms_categories/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/cms_categories/helpers/form/index.php
  admin-dev/themes/default/template/controllers/cms_categories/helpers/index.php
  admin-dev/themes/default/template/controllers/cms_categories/index.php
  admin-dev/themes/default/template/controllers/cms_content/content.tpl
  admin-dev/themes/default/template/controllers/cms_content/index.php
  controllers/admin/AdminCmsCategoriesController.php
  controllers/admin/AdminCmsContentController.php
  controllers/admin/AdminCmsController.php
Labels: 1.7.6.x, Refactoring, migration

#13847 Delete legacy AdminManufacturer controller
  admin-dev/themes/default/template/controllers/manufacturers/helpers/index.php
  admin-dev/themes/default/template/controllers/manufacturers/helpers/view/index.php
  admin-dev/themes/default/template/controllers/manufacturers/helpers/view/view.tpl
  admin-dev/themes/default/template/controllers/manufacturers/index.php
  controllers/admin/AdminManufacturersController.php
  tests-legacy/PrestaShopBundle/Controller/ControllerTest.php
Labels: 1.7.6.x, Refactoring, migration

#13804 Fix #9763 smarty compilation ID multi shop / multi theme
  classes/controller/FrontController.php
  classes/module/Module.php
Labels: Bug, QA ✔️, develop

#13857 Missing legacy links fix for employess controller
  src/Core/Grid/Definition/Factory/EmployeeGridDefinitionFactory.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/employee.yml
  tests/Integration/PrestaShopBundle/Routing/Converter/LegacyUrlConverterTest.php
Labels: 1.7.6.x, Bug, Wording ✔️, migration

#13866 fix cart rule calculation for free gift
  src/Core/Cart/CartRuleCalculator.php
  tests/Integration/Behaviour/Features/Scenario/Cart/CartToOrder/cart_to_order.feature
Labels: 1.7.6.x, Bug, QA ✔️

#13885 Force array cache for doctrine
  src/Adapter/ContainerBuilder.php
Labels: 1.7.6.x, Bug, QA ✔️

#13886 Add missing migrated routes to survival-test
  tests-legacy/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
  tests-legacy/Integration/PrestaShopBundle/Test/LightWebTestCase.php
Labels: 1.7.6.x, Refactoring, migration

#13813 Fixes toggling Category status in Monitoring page
  admin-dev/themes/default/template/helpers/list/list_action_enable.tpl
  admin-dev/themes/default/template/helpers/list/list_header.tpl
  controllers/admin/AdminTrackingController.php
Labels: 1.7.6.x, Bug, QA ✔️, migration

#13826 Enable global kernel for legacy compatibility for Behat tests
  tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php
Labels: Bug, develop

#13910 Removes AdminPreferencesController
  controllers/admin/AdminPreferencesController.php
  controllers/admin/AdminStatsTabController.php
Labels: 1.7.6.x, Refactoring, migration

#13932 Merge 1.7.6.x to develop - 23/05/2019
  admin-dev/themes/default/template/controllers/cms/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/cms/helpers/form/index.php
  admin-dev/themes/default/template/controllers/cms/helpers/index.php
  admin-dev/themes/default/template/controllers/cms/index.php
  admin-dev/themes/default/template/controllers/cms_categories/helpers/form/index.php
  admin-dev/themes/default/template/controllers/cms_categories/helpers/index.php
  admin-dev/themes/default/template/controllers/cms_categories/index.php
  admin-dev/themes/default/template/controllers/cms_content/content.tpl
  admin-dev/themes/default/template/controllers/cms_content/index.php
  admin-dev/themes/default/template/controllers/manufacturers/helpers/index.php
  admin-dev/themes/default/template/controllers/manufacturers/helpers/view/index.php
  admin-dev/themes/default/template/controllers/manufacturers/helpers/view/view.tpl
  admin-dev/themes/default/template/controllers/manufacturers/index.php
  admin-dev/themes/default/template/controllers/modules_positions/form.tpl
  admin-dev/themes/default/template/controllers/modules_positions/index.php
  admin-dev/themes/default/template/controllers/modules_positions/list_modules.tpl
  admin-dev/themes/default/template/controllers/request_sql/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/request_sql/helpers/view/view.tpl
  admin-dev/themes/default/template/controllers/request_sql/list_action_export.tpl
  admin-dev/themes/default/template/helpers/list/list_action_enable.tpl
  admin-dev/themes/default/template/helpers/list/list_header.tpl
  admin-dev/themes/new-theme/scss/pages/_themes_logo.scss
  admin-dev/themes/new-theme/scss/pages/partials/_theme_logo_configuration.scss
  controllers/admin/AdminCmsCategoriesController.php
  controllers/admin/AdminCmsContentController.php
  controllers/admin/AdminCmsController.php
  controllers/admin/AdminManufacturersController.php
  controllers/admin/AdminModulesPositionsController.php
  controllers/admin/AdminRequestSqlController.php
  controllers/admin/AdminTrackingController.php
  src/Adapter/ContainerBuilder.php
  src/Adapter/Customer/CommandHandler/AbstractCustomerHandler.php
  src/Adapter/Customer/CommandHandler/AddCustomerHandler.php
  src/Adapter/Customer/CommandHandler/EditCustomerHandler.php
  src/Core/Domain/Customer/Command/SetRequiredFieldsForCustomerCommand.php
  src/Core/Domain/Customer/Exception/MissingCustomerRequiredFieldsException.php
  src/Core/Domain/Customer/ValueObject/RequiredField.php
  src/Core/Grid/Definition/Factory/EmployeeGridDefinitionFactory.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/employee.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/currencies.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Theme/Blocks/layouts_configuration.html.twig
  tests-legacy/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
  tests-legacy/Integration/PrestaShopBundle/Test/LightWebTestCase.php
  tests-legacy/PrestaShopBundle/Controller/ControllerTest.php
  tests/Integration/Behaviour/Features/Scenario/Cart/CartToOrder/cart_to_order.feature
  tests/Integration/PrestaShopBundle/Routing/Converter/LegacyUrlConverterTest.php
Labels: Bug, develop

#13900 Fixing Download behavior in tests with docker
  tests/E2E/.docker/run-tests.sh
  tests/E2E/docker-compose.yml
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/common.webdriverio.js
Labels: 1.7.6.x, Refactoring, TE

#13840 Fix resetting sort and items per page on list filters reset action
  src/PrestaShopBundle/Controller/Admin/CommonController.php
  src/PrestaShopBundle/Entity/Repository/AdminFilterRepository.php
Labels: 1.7.6.x, Bug, PM ✔️, QA ✔️, migration

#13967 Merge 1.7.6.x to develop - 24/05/2019
  controllers/admin/AdminPreferencesController.php
  controllers/admin/AdminStatsTabController.php
  src/PrestaShopBundle/Controller/Admin/CommonController.php
  src/PrestaShopBundle/Entity/Repository/AdminFilterRepository.php
  tests/E2E/.docker/run-tests.sh
  tests/E2E/docker-compose.yml
  tests/E2E/test/clients/common_client.js
  tests/E2E/test/common.webdriverio.js
Labels: Bug, develop

#13961 Giving write access to selenium-chrome container to download file in selenium-downloads volume
  tests/E2E/docker-compose.yml
Labels: 1.7.6.x, Refactoring, TE

#13956 Restore legacy controller and template files deleted late in beta
  admin-dev/themes/default/template/controllers/cms/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/cms/helpers/form/index.php
  admin-dev/themes/default/template/controllers/cms/helpers/index.php
  admin-dev/themes/default/template/controllers/cms/index.php
  admin-dev/themes/default/template/controllers/cms_categories/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/cms_categories/helpers/form/index.php
  admin-dev/themes/default/template/controllers/cms_categories/helpers/index.php
  admin-dev/themes/default/template/controllers/cms_categories/index.php
  admin-dev/themes/default/template/controllers/cms_content/content.tpl
  admin-dev/themes/default/template/controllers/cms_content/index.php
  admin-dev/themes/default/template/controllers/manufacturers/helpers/index.php
  admin-dev/themes/default/template/controllers/manufacturers/helpers/view/index.php
  admin-dev/themes/default/template/controllers/manufacturers/helpers/view/view.tpl
  admin-dev/themes/default/template/controllers/manufacturers/index.php
  admin-dev/themes/default/template/controllers/modules_positions/form.tpl
  admin-dev/themes/default/template/controllers/modules_positions/index.php
  admin-dev/themes/default/template/controllers/modules_positions/list_modules.tpl
  admin-dev/themes/default/template/controllers/request_sql/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/request_sql/helpers/view/view.tpl
  admin-dev/themes/default/template/controllers/request_sql/list_action_export.tpl
  controllers/admin/AdminCmsCategoriesController.php
  controllers/admin/AdminCmsContentController.php
  controllers/admin/AdminCmsController.php
  controllers/admin/AdminManufacturersController.php
  controllers/admin/AdminModulesPositionsController.php
  controllers/admin/AdminPreferencesController.php
  controllers/admin/AdminRequestSqlController.php
  controllers/admin/AdminStatsTabController.php
  tests-legacy/PrestaShopBundle/Controller/ControllerTest.php
Labels: 1.7.6.x, Bug, QA ✔️, migration

#13820 Fixes form_rest placing
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/LogsPage/index.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Webservice/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Webservice/webservice_settings.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/customer_preferences_general.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_general.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_page.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_pagination.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_stock.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/OrderPreferences/Blocks/order_preferences_general.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/OrderPreferences/Blocks/order_preferences_gift_options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/TrafficSeo/Meta/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Theme/customize_page_layouts.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Theme/import.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Currency/Blocks/form.html.twig
Labels: 1.7.6.x, Bug, migration

#13916 Fixes saving private note about customer from order page
  admin-dev/themes/default/template/controllers/orders/helpers/view/view.tpl
  js/admin.js
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
Labels: 1.7.6.x, Bug, QA ✔️, Wording ✔️, migration

#13774 Includes missing theme & logo page validation handling for logo and icon images
  src/Adapter/Shop/CommandHandler/UploadLogosHandler.php
  src/Core/Domain/Exception/FileUploadException.php
  src/Core/Domain/Shop/Command/UploadLogosCommand.php
  src/Core/Domain/Shop/DTO/ShopLogoSettings.php
  src/Core/Domain/Shop/Exception/NotSupportedLogoImageExtensionException.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php
  src/PrestaShopBundle/Form/Admin/Improve/Design/Theme/ShopLogosType.php
Labels: 1.7.6.x, Bug, QA ✔️, Wording ✔️, migration

#13713 Fix product tests
  tests/E2E/test/campaigns/common_scenarios/product.js
  tests/E2E/test/campaigns/full/02_product/04_create_virtual_product.js
  tests/E2E/test/campaigns/full/02_product/10_buttons_in_footer_product_page.js
  tests/E2E/test/campaigns/full/02_product/17_display_all_product.js
Labels: 1.7.6.x, Refactoring, TE

#13905 Step clickable and not - Checkout page
  themes/classic/_dev/css/components/checkout.scss
  themes/classic/assets/css/theme.css
Labels: 1.7.6.x, Bug, QA ✔️

#14011 Update outdated CSS assets
  admin-dev/themes/new-theme/public/theme.css
Labels: 1.7.6.x, Improvement

#14007 Fix currency precision from CLDR at install
  src/Adapter/Currency/CommandHandler/AddCurrencyHandler.php
  src/PrestaShopBundle/Resources/config/services/adapter/currency.yml
Labels: 1.7.6.x, Bug, QA ✔️

#14010 Update some license headers that were outdated
  classes/Currency.php
  install-dev/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php
  mails/themes/index.php
  src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php
  src/Core/Domain/Exception/FileUploadException.php
  src/Core/Domain/Shop/DTO/ShopLogoSettings.php
  src/Core/Domain/Shop/Exception/NotSupportedLogoImageExtensionException.php
  src/Core/Form/ChoiceProvider/ThemeByNameWithEmailsChoiceProvider.php
  src/Core/Util/Url/BackUrlProvider.php
  src/PrestaShopBundle/EventListener/BackUrlRedirectResponseListener.php
  src/PrestaShopBundle/Routing/Converter/Exception/AlreadyConvertedException.php
  src/PrestaShopBundle/Translation/DomainNormalizer.php
  src/PrestaShopBundle/Translation/Exception/InvalidLegacyTranslationKeyException.php
  src/PrestaShopBundle/Translation/Loader/LegacyFileReader.php
  src/PrestaShopBundle/Translation/Loader/LegacyTranslationKey.php
  src/PrestaShopBundle/Twig/Extension/PathWithBackUrlExtension.php
Labels: 1.7.6.x, Improvement

#14026 Adds missing pages to survival test
  tests-legacy/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
Labels: 1.7.6.x, Improvement, migration

#13875 Adds consistent form elements rendering using form_rest
  src/PrestaShopBundle/Form/Admin/Extension/HelpTextExtension.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_extension.yml
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/form_div_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/macros.html.twig
Labels: 1.7.6.x, Bug, QA ✔️, migration
