Repository PrestaShop/PrestaShop, pull requests merged in 2019-11, with the labels that each got.

#16033 Introduces kpi design update for orders listing page - also includes layout changes for all kpi's in migrated pages
  admin-dev/themes/new-theme/scss/components/layout/_kpi.scss
  admin-dev/themes/new-theme/template/helpers/kpi/kpi.tpl
  src/Adapter/Kpi/AbandonedCartKpi.php
  src/Adapter/Kpi/AverageOrderValueKpi.php
  src/Adapter/Kpi/ConversionRateKpi.php
  src/Adapter/Kpi/NetProfitPerVisitKpi.php
  src/PrestaShopBundle/Resources/views/Admin/Common/Kpi/kpi_row.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/index.html.twig
Labels: Improvement, QA ✔️, develop, migration

#16237 Set Demo mode only if undefined
  config/defines.inc.php
Labels: Improvement, develop

#16241 Improve install doc
  INSTALL.txt
Labels: Improvement, develop

#16258 Remove unnecessary require_once config.inc
  src/PrestaShopBundle/Command/GenerateMailTemplatesCommand.php
  src/PrestaShopBundle/Command/ModuleCommand.php
  src/PrestaShopBundle/Command/ThemeEnablerCommand.php
Labels: 1.7.6.x, Bug, QA ✔️

#16063 Improve wording on order confirmation email
  classes/PaymentModule.php
  mails/themes/modern/core/order_conf.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop

#16069 Change wording in FO when there is specific price by quantity
  classes/controller/FrontController.php
  themes/classic/templates/catalog/_partials/product-discounts.tpl
Labels: Improvement, QA ✔️, Wording ✔️, develop

#16244 Update Costa Rican, Peruvian and Brazilian tax rates
  localization/br.xml
  localization/cr.xml
  localization/pe.xml
Labels: Bug, Improvement, QA ✔️, develop

#16278 Use https links to doc instead of http
  src/PrestaShopBundle/Resources/config/services/core/util/helper_card.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Blocks/import_panel.html.twig
Labels: Improvement, develop

#16274 Fix contact us email display
  themes/classic/_dev/css/components/contact.scss
  themes/classic/assets/css/theme.css
Labels: 1.7.6.x, Bug, QA ✔️

#16265 Fix category checkbox redirect (Backport #16159)
  admin-dev/themes/new-theme/js/components/grid/extension/link-row-action-extension.js
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/category.bundle.js
  admin-dev/themes/new-theme/public/cms_page.bundle.js
  admin-dev/themes/new-theme/public/contacts.bundle.js
  admin-dev/themes/new-theme/public/currency.bundle.js
  admin-dev/themes/new-theme/public/customer.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/employee.bundle.js
  admin-dev/themes/new-theme/public/language.bundle.js
  admin-dev/themes/new-theme/public/manufacturer.bundle.js
  admin-dev/themes/new-theme/public/meta.bundle.js
  admin-dev/themes/new-theme/public/profiles.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/supplier.bundle.js
  admin-dev/themes/new-theme/public/tax.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
Labels: 1.7.6.x, Bug, QA ✔️

#16266 Fix ajax exception when search for a product in order creation page
  admin-dev/themes/default/template/controllers/orders/form.tpl
Labels: Bug, QA ✔️, develop

#16271 Remove useless checkbox in product options tab for attached files
  admin-dev/themes/default/js/bundle/product/form.js
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
Labels: Bug, QA ✔️, develop

#16209 Use local fonts in BO default theme
  admin-dev/themes/default/js/theme.js
  admin-dev/themes/default/package-lock.json
  admin-dev/themes/default/package.json
  admin-dev/themes/default/public/08952b029e4decbc8ef9fb553cae8cea.woff2
  admin-dev/themes/default/public/1c0b4eb93fcf561eec03297a24922d6c.ttf
  admin-dev/themes/default/public/24aab533f87e7b434be5fa5b1684975c.svg
  admin-dev/themes/default/public/2a9a30e14574c9ec24add2901a80b81c.svg
  admin-dev/themes/default/public/2ca61b76e22053571dd8611e5aac4900.png
  admin-dev/themes/default/public/3326e4d74d3924ee1c882c29f5b571c0.woff2
  admin-dev/themes/default/public/3343e54368719e3786f78a1b22839455.woff2
  admin-dev/themes/default/public/33f225b8f5f7d6b34a0926f58f96c1e9.ttf
  admin-dev/themes/default/public/383eba0e55ed778006d76428812d343c.woff2
  admin-dev/themes/default/public/49e3f006018662f60f1db2aec0b2cca9.png
  admin-dev/themes/default/public/51eedfb43f888d1b221e20467e8188fa.gif
  admin-dev/themes/default/public/525074686dfb8aa36b1b92e29de467ac.woff
  admin-dev/themes/default/public/55835483c304eaa8477fea2c36abba17.woff2
  admin-dev/themes/default/public/5a100916f94b0babde0c92aaa8fb80d6.ttf
  admin-dev/themes/default/public/5aaceea2d60ddb477c6aafc825eece3d.woff2
  admin-dev/themes/default/public/5be71612af754cc566ec30ef200d8a65.woff
  admin-dev/themes/default/public/7b9776076d5fceef4993b55c9383dedd.gif
  admin-dev/themes/default/public/7be88e73fea7b64568a450d7c01346b0.woff
  admin-dev/themes/default/public/892667349c5cff6fcf7e40439596b97c.woff
  admin-dev/themes/default/public/8a486134dd38f7185b6dda1e09ad091e.png
  admin-dev/themes/default/public/8b55a822e72b8fd5e2ee069236f2d797.png
  admin-dev/themes/default/public/9b30f13428e1b4a659aeeab4ac1fff35.ttf
  admin-dev/themes/default/public/9f2144213fad53d4e0fdb26ecf93865f.woff
  admin-dev/themes/default/public/a33a878f3861ca67e9bc423c58b2a357.svg
  admin-dev/themes/default/public/ac327c4db6284ef64ebe872b6308f5da.woff
  admin-dev/themes/default/public/b46ff9f5c8bcba1ea3b4b320e22be5c7.svg
  admin-dev/themes/default/public/bf4dde0147bb02556500d922e2efc90b.svg
  admin-dev/themes/default/public/bundle.js
  admin-dev/themes/default/public/c36b5ac7c2dddf6f525c8d161412ef41.ttf
  admin-dev/themes/default/public/cd7296352d159532b66c07d98efb1126.ttf
  admin-dev/themes/default/public/eb24af6668c633feab6bf8f989296e73.woff2
  admin-dev/themes/default/public/ec55f263e2b86bc0f28fff46b873d6df.woff
  admin-dev/themes/default/public/fedf49d31f55f4beaf2c891f3875554f.svg
  admin-dev/themes/default/public/theme.css
  admin-dev/themes/default/sass/admin-theme.sass
  admin-dev/themes/default/sass/modules/_variables.sass
  admin-dev/themes/default/webpack.config.js
  docs/licences/fonts/open-sans.txt
  docs/licences/fonts/ubuntu-condensed.txt
Labels: BO, Bug, QA ✔️, develop

#16285 Fix ajax spinner not disappearing after Ajax is done
  js/admin.js
Labels: Bug, QA ✔️, develop

#16225 Fix prices display in new order page
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
Labels: Bug, QA ✔️, develop, migration

#16235 Correct vouchers reductions display values in cart summary
  src/Adapter/Presenter/Cart/CartPresenter.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#16065 Migrates Shipping block of new Order View page
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js
  admin-dev/themes/new-theme/js/pages/order/order-shipping-manager.js
  admin-dev/themes/new-theme/js/pages/order/view.js
  src/Adapter/Form/ChoiceProvider/CarrierForOrderChoiceProvider.php
  src/Adapter/Order/CommandHandler/UpdateOrderShippingDetailsHandler.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Core/Domain/Order/Command/UpdateOrderShippingDetailsCommand.php
  src/Core/Domain/Order/Exception/TransistEmailSendingException.php
  src/Core/Domain/Order/QueryResult/OrderForViewing.php
  src/Core/Domain/Order/QueryResult/OrderShippingForViewing.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/UpdateOrderShippingType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
  src/PrestaShopBundle/Resources/config/services/adapter/form.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/update_shipping_modal.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/details.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/shipping.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig
Labels: High, Improvement, QA ✔️, Wording ✔️, develop, migration

#16180 Use Media Server for assets (CSS, JS, Images)
  classes/Tools.php
  classes/assets/AbstractAssetManager.php
  classes/assets/CccReducer.php
  classes/controller/FrontController.php
  themes/classic/templates/_partials/head.tpl
  themes/classic/templates/_partials/header.tpl
  themes/classic/templates/checkout/_partials/header.tpl
  themes/classic/templates/errors/maintenance.tpl
  themes/classic/templates/errors/restricted-country.tpl
Labels: FO, High, Improvement, QA ✔️, develop

#16281 Update wording and add a link in product options tab
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Panels/options.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop

#16292 Add missing languages to localization packs
  localization/cn.xml
  localization/fr.xml
  localization/in.xml
  localization/no.xml
  localization/ph.xml
  localization/rs.xml
  localization/sg.xml
Labels: Improvement, QA ✔️, develop

#16079 Update Azerbaijani tax rates
  localization/az.xml
Labels: Improvement, QA ✔️, develop

#16291 Update tax rates for several countries
  localization/ar.xml
  localization/at.xml
  localization/be.xml
  localization/bg.xml
  localization/by.xml
  localization/cn.xml
  localization/cy.xml
  localization/cz.xml
  localization/de.xml
  localization/dk.xml
  localization/ee.xml
  localization/es.xml
  localization/fi.xml
  localization/fr.xml
  localization/gb.xml
  localization/gr.xml
  localization/hr.xml
  localization/hu.xml
  localization/ie.xml
  localization/it.xml
  localization/lt.xml
  localization/lu.xml
  localization/lv.xml
  localization/mt.xml
  localization/nl.xml
  localization/pa.xml
  localization/ph.xml
  localization/pl.xml
  localization/pt.xml
  localization/ro.xml
  localization/se.xml
  localization/si.xml
  localization/sk.xml
  localization/tn.xml
  src/PrestaShopBundle/Command/UpdateEUTaxruleGroupsCommand.php
Labels: Improvement, QA ✔️, develop

#16084 Migrates Merchandise returns for Orders view
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/details.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/merchandise_returns.html.twig
Labels: High, Improvement, QA ✔️, Wording ✔️, develop, migration

#16305 Fix SQL upgrade for 1.7.7.0 (missing FROM)
  install-dev/upgrade/sql/1.7.7.0.sql
Labels: Bug, develop

#16099 Makes checkout js code easier to understand
  themes/_core/js/checkout-steps.js
  themes/_core/js/checkout.js
  themes/core.js
  themes/core.js.map
Labels: High, QA ✔️, Refactoring, develop

#16309 Tests - Separate BO pages
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/01_filterAndQuickEditBrands.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/02_filterBrandAddresses.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/03_CRUDBrandAndAddress.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/04_BulkActionsBrands.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/05_BulkActionsBrandAddresses.js
  tests/puppeteer/campaigns/functional/BO/catalog/categories/01_filterAndQuickEditCategories.js
  tests/puppeteer/campaigns/functional/BO/catalog/categories/02_CRUDCategoryInBO.js
  tests/puppeteer/campaigns/functional/BO/catalog/categories/03_categoriesBulkAction.js
  tests/puppeteer/campaigns/functional/BO/customers/customers/02_CRUDCustomerInBO.js
  tests/puppeteer/campaigns/functional/BO/customers/customers/03_customersBulkActionsInBO.js
  tests/puppeteer/campaigns/functional/BO/international/taxes/01_filterAndQuickEditTaxes.js
  tests/puppeteer/campaigns/functional/BO/international/taxes/02_CRUDTaxesInBO.js
  tests/puppeteer/campaigns/functional/BO/international/taxes/03_taxesBulkActionsInBO.js
  tests/puppeteer/campaigns/functional/BO/international/taxes/04_taxOptionsForm.js
  tests/puppeteer/campaigns/sanity/02_productsBO/01_filterProducts.js
  tests/puppeteer/campaigns/sanity/02_productsBO/02_CRUDStandardProductInBO.js
  tests/puppeteer/campaigns/sanity/02_productsBO/03_CRUDStandardProductWithCombinationsInBO.js
  tests/puppeteer/campaigns/sanity/02_productsBO/04_deleteProduct.js
  tests/puppeteer/campaigns/sanity/02_productsBO/05_deleteProductsWithBulkActions.js
  tests/puppeteer/campaigns/sanity/03_ordersBO/02_editOrder.js
  tests/puppeteer/campaigns/upgrade/upgradeShop.js
  tests/puppeteer/pages/BO/catalog/brands/add.js
  tests/puppeteer/pages/BO/catalog/brands/addresses/add.js
  tests/puppeteer/pages/BO/catalog/brands/index.js
  tests/puppeteer/pages/BO/catalog/brands/view.js
  tests/puppeteer/pages/BO/catalog/categories/add.js
  tests/puppeteer/pages/BO/catalog/categories/index.js
  tests/puppeteer/pages/BO/catalog/products/add.js
  tests/puppeteer/pages/BO/catalog/products/index.js
  tests/puppeteer/pages/BO/customers/add.js
  tests/puppeteer/pages/BO/customers/index.js
  tests/puppeteer/pages/BO/customers/view.js
  tests/puppeteer/pages/BO/dashboard/index.js
  tests/puppeteer/pages/BO/international/taxes/add.js
  tests/puppeteer/pages/BO/international/taxes/index.js
  tests/puppeteer/pages/BO/login/index.js
  tests/puppeteer/pages/BO/modules/autoUpgrade/index.js
  tests/puppeteer/pages/BO/modules/moduleCatalog/index.js
  tests/puppeteer/pages/BO/modules/moduleManager/index.js
  tests/puppeteer/pages/BO/orders/index.js
  tests/puppeteer/pages/BO/orders/view.js
  tests/puppeteer/pages/BO/shopParameters/general/index.js
  tests/puppeteer/pages/BO/shopParameters/general/maintenance/index.js
Labels: Refactoring, TE, develop

#16297 Functional tests - Using the correct element in loop for brands tests
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/01_filterAndQuickEditBrands.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/04_BulkActionsBrands.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/05_BulkActionsBrandAddresses.js
Labels: Refactoring, TE, develop

#16176 Increase maximum hook length to 191 characters
  classes/Hook.php
  install-dev/data/db_structure.sql
  install-dev/upgrade/sql/1.7.7.0.sql
Labels: Improvement, QA ✔️, develop

#16159 Fix category checkbox redirect
  admin-dev/themes/new-theme/js/components/grid/extension/link-row-action-extension.js
  admin-dev/themes/new-theme/public/attachment.bundle.js
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/category.bundle.js
  admin-dev/themes/new-theme/public/cms_page.bundle.js
  admin-dev/themes/new-theme/public/contacts.bundle.js
  admin-dev/themes/new-theme/public/currency.bundle.js
  admin-dev/themes/new-theme/public/customer.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/employee.bundle.js
  admin-dev/themes/new-theme/public/language.bundle.js
  admin-dev/themes/new-theme/public/manufacturer.bundle.js
  admin-dev/themes/new-theme/public/meta.bundle.js
  admin-dev/themes/new-theme/public/monitoring.bundle.js
  admin-dev/themes/new-theme/public/order.bundle.js
  admin-dev/themes/new-theme/public/order_message.bundle.js
  admin-dev/themes/new-theme/public/profiles.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/supplier.bundle.js
  admin-dev/themes/new-theme/public/tax.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
Labels: Bug, QA ✔️, develop

#16078 Update Argentinian conversion and tax rates
  localization/ar.xml
Labels: Improvement, QA ✔️, develop

#16296 Functional Tests - Add BO tests for Supplier
  tests/puppeteer/.eslintrc.js
  tests/puppeteer/campaigns/data/faker/supplier.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/suppliers/01_CRUDSupplier.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/suppliers/02_filterQuickEditAndBulkActionsSupplier.js
  tests/puppeteer/pages/BO/catalog/suppliers/add.js
  tests/puppeteer/pages/BO/catalog/suppliers/index.js
  tests/puppeteer/pages/BO/catalog/suppliers/view.js
Labels: Refactoring, TE, develop

#16312 Incorrect display value in Price Tab of admin product controller
  src/PrestaShopBundle/Form/Admin/Product/ProductPrice.php
Labels: Bug, QA ✔️, develop

#16147 Add CSS sizes for images in custom text block
  themes/classic/_dev/css/components/custom-text.scss
  themes/classic/assets/css/theme.css
Labels: Bug, QA ✔️, develop

#16304 change wording of lifetime of BO cookies help label
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/administration.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop

#16319 Use customer group price display preference for display order in BO
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Order/QueryHandler/GetOrderPreviewHandler.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/preview.html.twig
Labels: Bug, High, QA ✔️, Wording ✔️, develop

#15915 Migration of International > Taxes > Tax rules page
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/js/pages/tax-rules-group/index.js
  admin-dev/themes/new-theme/public/tax_rules_group.bundle.js
  src/Adapter/TaxRulesGroup/AbstractTaxRulesGroupHandler.php
  src/Adapter/TaxRulesGroup/CommandHandler/BulkDeleteTaxRulesGroupHandler.php
  src/Adapter/TaxRulesGroup/CommandHandler/BulkSetTaxRulesGroupStatusHandler.php
  src/Adapter/TaxRulesGroup/CommandHandler/DeleteTaxRulesGroupHandler.php
  src/Adapter/TaxRulesGroup/CommandHandler/SetTaxRulesGroupStatusHandler.php
  src/Adapter/TaxRulesGroup/QueryHandler/GetTaxRulesGroupForEditingHandler.php
  src/Core/Domain/TaxRulesGroup/Command/BulkDeleteTaxRulesGroupCommand.php
  src/Core/Domain/TaxRulesGroup/Command/BulkSetTaxRulesGroupStatusCommand.php
  src/Core/Domain/TaxRulesGroup/Command/DeleteTaxRulesGroupCommand.php
  src/Core/Domain/TaxRulesGroup/Command/SetTaxRulesGroupStatusCommand.php
  src/Core/Domain/TaxRulesGroup/CommandHandler/BulkDeleteTaxRulesGroupHandlerInterface.php
  src/Core/Domain/TaxRulesGroup/CommandHandler/BulkToggleTaxRulesGroupStatusHandlerInterface.php
  src/Core/Domain/TaxRulesGroup/CommandHandler/DeleteTaxRulesGroupHandlerInterface.php
  src/Core/Domain/TaxRulesGroup/CommandHandler/ToggleTaxRulesGroupStatusHandlerInterface.php
  src/Core/Domain/TaxRulesGroup/Exception/CannotBulkDeleteTaxRulesGroupException.php
  src/Core/Domain/TaxRulesGroup/Exception/CannotBulkUpdateTaxRulesGroupException.php
  src/Core/Domain/TaxRulesGroup/Exception/CannotDeleteTaxRulesGroupException.php
  src/Core/Domain/TaxRulesGroup/Exception/CannotUpdateTaxRulesGroupException.php
  src/Core/Domain/TaxRulesGroup/Exception/TaxRulesGroupConstraintException.php
  src/Core/Domain/TaxRulesGroup/Exception/TaxRulesGroupException.php
  src/Core/Domain/TaxRulesGroup/Exception/TaxRulesGroupNotFoundException.php
  src/Core/Domain/TaxRulesGroup/Query/GetTaxRulesGroupForEditing.php
  src/Core/Domain/TaxRulesGroup/QueryHandler/GetTaxRulesGroupForEditingHandlerInterface.php
  src/Core/Domain/TaxRulesGroup/QueryResult/EditableTaxRulesGroup.php
  src/Core/Domain/TaxRulesGroup/ValueObject/TaxRulesGroupId.php
  src/Core/Grid/Definition/Factory/TaxRulesGroupGridDefinitionFactory.php
  src/Core/Grid/Query/TaxRulesGroupQueryBuilder.php
  src/Core/Search/Filters/TaxRulesGroupFilters.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/TaxRulesGroupController.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/_international.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/tax_rules_groups.yml
  src/PrestaShopBundle/Resources/config/services/adapter/tax_rules_group.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_data_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_factory.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/TaxRulesGroup/index.html.twig
Labels: QA ✔️, Refactoring, Wording ✔️, develop, migration, waiting for wording

#16332 Tests - using same demo elements
  tests/puppeteer/campaigns/data/demo/countries.js
  tests/puppeteer/campaigns/data/demo/groupAccess.js
  tests/puppeteer/campaigns/data/faker/brandAddress.js
  tests/puppeteer/campaigns/data/faker/category.js
  tests/puppeteer/campaigns/data/faker/customer.js
  tests/puppeteer/campaigns/data/faker/supplier.js
Labels: Refactoring, TE, develop

#16360 Twig\HookExtension: Bugfix ob level in renderHooksArray
  src/PrestaShopBundle/Twig/HookExtension.php
Labels: Bug, Technical Task, develop

#16335 update id_order_state at the right place
  classes/PaymentModule.php
Labels: 1.7.6.x, Bug, QA ✔️

#16365 Viewed products - the date is showing product id - not a date
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/viewed_products.html.twig
Labels: 1.7.6.x, Bug, QA ✔️

#16331 Add "total_shipping_tax_excl" and "total_shipping_tax_incl" in email data
  src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php
Labels: Improvement, QA ✔️, develop

#16371 Tests - Delete replaces and use new methods instead in Supplier tests
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/suppliers/02_filterQuickEditAndBulkActionsSupplier.js
  tests/puppeteer/pages/BO/catalog/suppliers/index.js
Labels: Refactoring, TE, develop

#16373 Tests - Using employees demo file for installation
  tests/puppeteer/README.md
  tests/puppeteer/campaigns/data/demo/employees.js
  tests/puppeteer/campaigns/utils/globals.js
  tests/puppeteer/pages/Install/install.js
Labels: Refactoring, TE, develop

#16375 Emails are not case sensitive
  src/Core/Domain/Customer/ValueObject/Email.php
  src/Core/Domain/ValueObject/Email.php
Labels: Bug, QA ✔️, develop

#15627 Added states to India
  install-dev/data/xml/country.xml
  install-dev/data/xml/state.xml
Labels: Improvement, QA ✔️, Wording ✔️, develop

#16387 Tests - Delete replaces in tests categories
  tests/puppeteer/campaigns/functional/BO/catalog/categories/01_filterAndQuickEditCategories.js
  tests/puppeteer/campaigns/functional/BO/catalog/categories/02_CRUDCategoryInBO.js
  tests/puppeteer/campaigns/functional/BO/catalog/categories/03_categoriesBulkAction.js
  tests/puppeteer/pages/BO/catalog/categories/index.js
  tests/puppeteer/pages/FO/siteMap.js
Labels: Refactoring, TE, develop

#16330 Tests - Delete replaces in tests and use new methods instead
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/01_filterAndQuickEditBrands.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/02_filterBrandAddresses.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/03_CRUDBrandAndAddress.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/04_BulkActionsBrands.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/05_BulkActionsBrandAddresses.js
  tests/puppeteer/pages/BO/catalog/brands/index.js
  tests/puppeteer/pages/BO/catalog/brands/view.js
Labels: Refactoring, TE, develop

#16394 Fix typo in condition
  classes/controller/AdminController.php
Labels: Bug, Technical Task, develop

#16395 Tests - Delete replaces in tests Customers
  tests/puppeteer/campaigns/functional/BO/customers/customers/01_filterAndQuickEditCustomers.js
  tests/puppeteer/campaigns/functional/BO/customers/customers/02_CRUDCustomerInBO.js
  tests/puppeteer/campaigns/functional/BO/customers/customers/03_customersBulkActionsInBO.js
  tests/puppeteer/pages/BO/customers/index.js
  tests/puppeteer/pages/BO/customers/view.js
Labels: Refactoring, TE, develop

#16317 Only trigger deploy on cron task, and tests on push / pull requests
  .travis.yml
Labels: Improvement, develop

#16399 Tests - Delete replaces in tests Taxes
  tests/puppeteer/campaigns/functional/BO/international/taxes/01_filterAndQuickEditTaxes.js
  tests/puppeteer/campaigns/functional/BO/international/taxes/02_CRUDTaxesInBO.js
  tests/puppeteer/campaigns/functional/BO/international/taxes/03_taxesBulkActionsInBO.js
  tests/puppeteer/pages/BO/international/taxes/index.js
Labels: Refactoring, TE, develop

#15902 Use the correct environment depending on what you are doing (dev, test, and prod)
  admin-dev/index.php
  app/AppCache.php
  app/AppKernel.php
  app/config/config_test.yml
  app/config/set_parameters.php
  classes/PrestaShopAutoload.php
  classes/Tools.php
  composer.json
  config/bootstrap.php
  config/defines.inc.php
  install-dev/controllers/console/process.php
  install-dev/controllers/http/welcome.php
  install-dev/init.php
  install-dev/upgrade/upgrade.php
  src/Adapter/Environment.php
  src/PrestaShopBundle/Command/UpdateSchemaCommand.php
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Service/Command/AbstractCommand.php
  src/PrestaShopBundle/Service/Database/Upgrade.php
  tests-legacy/PrestaShopBundle/Controller/ControllerTest.php
  tests-legacy/PrestaShopBundle/Utils/DatabaseCreator.php
  travis-scripts/install-prestashop
Labels: Improvement, QA ✔️, develop

#16392 Fixed the change the quantity of a free product in an order in the BO
  js/admin/orders.js
Labels: Bug, QA ✔️, develop

#16405 Tests - Replace duplicated steps with foreach in suppliers tests
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/suppliers/02_filterQuickEditAndBulkActionsSupplier.js
Labels: Refactoring, TE, develop

#16403 Tests - Replace duplicated steps with foreach for brands tests
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/01_filterAndQuickEditBrands.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/02_filterBrandAddresses.js
Labels: Refactoring, TE, develop

#16213 Make id order available
  classes/PaymentModule.php
  src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php
Labels: Bug, QA ✔️, develop

#15229 Migration of Sell > Customers > Addresses page
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/js/pages/address/index.js
  admin-dev/themes/new-theme/public/address.bundle.js
  src/Adapter/Address/CommandHandler/BulkDeleteAddressHandler.php
  src/Adapter/Address/CommandHandler/SetRequiredFieldsForAddressHandler.php
  src/Adapter/Address/QueryHandler/GetRequiredFieldsForAddressHandler.php
  src/Core/Domain/Address/Command/SetRequiredFieldsForAddressCommand.php
  src/Core/Domain/Address/CommandHandler/SetRequiredFieldsForAddressHandlerInterface.php
  src/Core/Domain/Address/Exception/BulkDeleteAddressException.php
  src/Core/Domain/Address/Exception/CannotSetRequiredFieldsForAddressException.php
  src/Core/Domain/Address/Exception/InvalidAddressRequiredFieldsException.php
  src/Core/Domain/Address/Query/GetRequiredFieldsForAddress.php
  src/Core/Domain/Address/QueryHandler/GetRequiredFieldsForAddressHandlerInterface.php
  src/Core/Domain/Address/ValueObject/RequiredFields.php
  src/Core/Form/ChoiceProvider/AddressRequiredFieldsChoiceProvider.php
  src/Core/Grid/Definition/Factory/AddressGridDefinitionFactory.php
  src/Core/Grid/Query/AddressQueryBuilder.php
  src/Core/Search/Filters/AddressFilters.php
  src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php
  src/PrestaShopBundle/Form/Admin/Sell/Address/RequiredFieldsAddressType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer/_customer.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer/addresses.yml
  src/PrestaShopBundle/Resources/config/services/adapter/address.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/choice_provider.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_data_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_factory.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Address/Blocks/required_fields.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Address/index.html.twig
Labels: QA ✔️, Refactoring, Wording ✔️, develop, migration

#16414 Tests - Replace duplicated steps with foreach in taxes tests
  tests/puppeteer/campaigns/functional/BO/international/taxes/01_filterAndQuickEditTaxes.js
  tests/puppeteer/campaigns/functional/BO/international/taxes/03_taxesBulkActionsInBO.js
Labels: Refactoring, TE, develop

#16407 Tests - Replace duplicated steps with foreach in categories tests
  tests/puppeteer/campaigns/functional/BO/catalog/categories/01_filterAndQuickEditCategories.js
  tests/puppeteer/campaigns/functional/BO/catalog/categories/03_categoriesBulkAction.js
  tests/puppeteer/pages/BO/catalog/categories/index.js
Labels: Refactoring, TE, develop

#16408 Tests - Replace duplicated steps with foreach in customers tests
  tests/puppeteer/campaigns/functional/BO/customers/customers/01_filterAndQuickEditCustomers.js
  tests/puppeteer/campaigns/functional/BO/customers/customers/03_customersBulkActionsInBO.js
Labels: Refactoring, TE, develop

#16310 Add ps_dataprivacy, productcomments and ps_crossselling as native modules
  composer.json
  composer.lock
  src/PrestaShopBundle/Install/Install.php
Labels: Improvement, QA ✔️, develop

#14288 Migrate Customer Service view
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/js/pages/customer-thread/customer-thread-view-page-map.js
  admin-dev/themes/new-theme/js/pages/customer-thread/view.js
  admin-dev/themes/new-theme/public/customer_thread_view.bundle.js
  admin-dev/themes/new-theme/scss/components/_font.scss
  admin-dev/themes/new-theme/scss/components/_timeline.scss
  admin-dev/themes/new-theme/scss/pages/_customer_thread.scss
  admin-dev/themes/new-theme/scss/theme.scss
  src/Adapter/CustomerService/CommandHandler/ForwardCustomerThreadHandler.php
  src/Adapter/CustomerService/CommandHandler/ReplyToCustomerThreadHandler.php
  src/Adapter/CustomerService/QueryHandler/GetCustomerThreadForViewingHandler.php
  src/Adapter/Form/ChoiceProvider/EmployeeNameByIdChoiceProvider.php
  src/Adapter/Profile/Employee/AbstractEmployeeHandler.php
  src/Adapter/Profile/Employee/QueryHandler/GetEmployeeEmailByIdHandler.php
  src/Adapter/Twig/LocaleExtension.php
  src/Core/Domain/CustomerService/Command/ForwardCustomerThreadCommand.php
  src/Core/Domain/CustomerService/Command/ReplyToCustomerThreadCommand.php
  src/Core/Domain/CustomerService/Command/UpdateCustomerThreadStatusCommand.php
  src/Core/Domain/CustomerService/CommandHandler/ForwardCustomerThreadHandlerInterface.php
  src/Core/Domain/CustomerService/CommandHandler/ReplyToCustomerThreadHandlerInterface.php
  src/Core/Domain/CustomerService/CommandHandler/UpdateCustomerThreadStatusHandler.php
  src/Core/Domain/CustomerService/CommandHandler/UpdateCustomerThreadStatusHandlerInterface.php
  src/Core/Domain/CustomerService/Exception/CustomerServiceException.php
  src/Core/Domain/CustomerService/Exception/CustomerThreadNotFoundException.php
  src/Core/Domain/CustomerService/Query/GetCustomerServiceSignature.php
  src/Core/Domain/CustomerService/Query/GetCustomerThreadForViewing.php
  src/Core/Domain/CustomerService/QueryHandler/GetCustomerServiceSignatureHandler.php
  src/Core/Domain/CustomerService/QueryHandler/GetCustomerServiceSignatureHandlerInterface.php
  src/Core/Domain/CustomerService/QueryHandler/GetCustomerThreadForViewingHandlerInterface.php
  src/Core/Domain/CustomerService/QueryResult/CustomerInformation.php
  src/Core/Domain/CustomerService/QueryResult/CustomerThreadMessage.php
  src/Core/Domain/CustomerService/QueryResult/CustomerThreadTimeline.php
  src/Core/Domain/CustomerService/QueryResult/CustomerThreadTimelineItem.php
  src/Core/Domain/CustomerService/QueryResult/CustomerThreadView.php
  src/Core/Domain/CustomerService/ValueObject/CustomerThreadId.php
  src/Core/Domain/CustomerService/ValueObject/CustomerThreadMessageType.php
  src/Core/Domain/CustomerService/ValueObject/CustomerThreadStatus.php
  src/Core/Domain/Employee/Query/GetEmployeeEmailById.php
  src/Core/Domain/Employee/QueryHandler/GetEmployeeEmailByIdHandlerInterface.php
  src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/CustomerThreadController.php
  src/PrestaShopBundle/Form/Admin/CustomerService/CustomerThread/ForwardCustomerThreadType.php
  src/PrestaShopBundle/Form/Admin/Sell/CustomerService/ReplyToCustomerThreadType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer_service/_customer_service.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer_service/customer_threads.yml
  src/PrestaShopBundle/Resources/config/services/adapter/customer_service.yml
  src/PrestaShopBundle/Resources/config/services/adapter/employee.yml
  src/PrestaShopBundle/Resources/config/services/adapter/form.yml
  src/PrestaShopBundle/Resources/config/services/adapter/twig.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/domain/customer_service.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/CustomerService/CustomerThread/Block/customer_information.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/CustomerService/CustomerThread/Block/forward_thread_modal.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/CustomerService/CustomerThread/Block/thread_actions.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/CustomerService/CustomerThread/Block/thread_messages.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/CustomerService/CustomerThread/Block/timeline.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/CustomerService/CustomerThread/Block/your_answer.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/CustomerService/CustomerThread/view.html.twig
  tests/Unit/Core/Domain/CustomerService/ValueObject/CustomerThreadStatusTest.php
Labels: QA ✔️, Refactoring, Wording ✔️, develop, migration

#16316 ImageManager::validateUpload : MimeType can't be check for SVG files
  classes/ImageManager.php
Labels: Improvement, QA ✔️, develop

#16423 Use default attribute when no one are passed in front page
  controllers/front/ProductController.php
Labels: 1.7.6.x, Bug, QA ✔️

#16416 Added albanian & korean to the installer
  install-dev/langs/ko/data/index.php
  install-dev/langs/ko/flag.jpg
  install-dev/langs/ko/img/index.php
  install-dev/langs/ko/img/ko-default-category.jpg
  install-dev/langs/ko/img/ko-default-home.jpg
  install-dev/langs/ko/img/ko-default-large.jpg
  install-dev/langs/ko/img/ko-default-large_scene.jpg
  install-dev/langs/ko/img/ko-default-medium.jpg
  install-dev/langs/ko/img/ko-default-small.jpg
  install-dev/langs/ko/img/ko-default-thickbox.jpg
  install-dev/langs/ko/img/ko-default-thumb_scene.jpg
  install-dev/langs/ko/img/ko.jpg
  install-dev/langs/ko/index.php
  install-dev/langs/ko/language.xml
  install-dev/langs/sq/data/index.php
  install-dev/langs/sq/flag.jpg
  install-dev/langs/sq/img/index.php
  install-dev/langs/sq/img/sq-default-category.jpg
  install-dev/langs/sq/img/sq-default-home.jpg
  install-dev/langs/sq/img/sq-default-large.jpg
  install-dev/langs/sq/img/sq-default-large_scene.jpg
  install-dev/langs/sq/img/sq-default-medium.jpg
  install-dev/langs/sq/img/sq-default-small.jpg
  install-dev/langs/sq/img/sq-default-thickbox.jpg
  install-dev/langs/sq/img/sq-default-thumb_scene.jpg
  install-dev/langs/sq/img/sq.jpg
  install-dev/langs/sq/index.php
  install-dev/langs/sq/language.xml
Labels: Improvement, QA ✔️, Wording ✔️, develop

#16404 Improved cache for staticPrice with product with combinations
  classes/Product.php
Labels: Improvement, QA ✔️, develop

#16450 Tests - Replace duplicated steps with foreach in brands tests
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/01_filterAndQuickEditBrands.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/04_BulkActionsBrands.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/05_BulkActionsBrandAddresses.js
Labels: Refactoring, TE, develop

#16448 Running Sanity and functional tests faster
  tests/puppeteer/campaigns/functional/BO/customers/customers/01_filterAndQuickEditCustomers.js
  tests/puppeteer/campaigns/utils/globals.js
  tests/puppeteer/pages/BO/catalog/products/add.js
  tests/puppeteer/pages/FO/home.js
  tests/puppeteer/pages/commonPage.js
Labels: Refactoring, TE, develop

#16454 Add comments about DataLang
  classes/Language.php
  classes/lang/DataLang.php
Labels: Improvement, develop

#14894 Move to utf8mb4 for emoji support
  .travis.yml
  app/config/config.yml
  classes/PrestaShopBackup.php
  classes/db/DbMySQLi.php
  classes/db/DbPDO.php
  install-dev/data/db_structure.sql
  install-dev/init.php
  install-dev/upgrade/sql/1.7.7.0.sql
  src/Adapter/Module/Configuration/ModuleSelfConfigurator.php
  src/PrestaShopBundle/Install/Install.php
Labels: Improvement, QA ✔️, develop

#16376 Functional Tests - Add BO tests for Filter And Quick Edit products
  tests/puppeteer/campaigns/data/demo/products.js
  tests/puppeteer/campaigns/functional/BO/catalog/products/01_filterAndQuickEditProducts.js
  tests/puppeteer/pages/BO/catalog/products/index.js
Labels: Refactoring, TE, develop

#16456 Functional tests - add simple filter tests for stocks
  tests/puppeteer/campaigns/functional/BO/catalog/stocks/01_simpleFilterStocks.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/catalog/stocks/index.js
Labels: Refactoring, TE, develop

#15707 Improve query performance in order status update due very slow StockManager.php queries
  src/Adapter/StockManager.php
Labels: Improvement, QA ✔️, develop

#16429 Upgrade Smarty to v3.1.34
  composer.lock
Labels: Improvement, QA ✔️, develop

#16289 Functional Tests - Add BO tests for Team>employees and profiles
  tests/puppeteer/campaigns/commonTests/loginBO.js
  tests/puppeteer/campaigns/data/demo/employees.js
  tests/puppeteer/campaigns/data/demo/languages.js
  tests/puppeteer/campaigns/data/demo/pages.js
  tests/puppeteer/campaigns/data/demo/profiles.js
  tests/puppeteer/campaigns/data/faker/employee.js
  tests/puppeteer/campaigns/data/faker/profile.js
  tests/puppeteer/campaigns/functional/BO/advancedParameters/team/01_filterAndQuickEditEmployees.js
  tests/puppeteer/campaigns/functional/BO/advancedParameters/team/02_CRUDEmployee.js
  tests/puppeteer/campaigns/functional/BO/advancedParameters/team/03_employeesBulkActions.js
  tests/puppeteer/campaigns/functional/BO/advancedParameters/team/04_CRUDProfile.js
  tests/puppeteer/campaigns/functional/BO/advancedParameters/team/05_filterProfiles.js
  tests/puppeteer/campaigns/functional/BO/advancedParameters/team/06_profileBulkActions.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/advancedParameters/team/add.js
  tests/puppeteer/pages/BO/advancedParameters/team/index.js
  tests/puppeteer/pages/BO/advancedParameters/team/profiles/add.js
  tests/puppeteer/pages/BO/advancedParameters/team/profiles/index.js
Labels: TE, develop, waiting for review

#16127 Functional Tests - Add BO tests for Design>Pages
  tests/puppeteer/campaigns/data/demo/CMSpage.js
  tests/puppeteer/campaigns/data/faker/CMScategory.js
  tests/puppeteer/campaigns/data/faker/CMSpage.js
  tests/puppeteer/campaigns/functional/BO/design/pages/01_filterAndQuickEditPages.js
  tests/puppeteer/campaigns/functional/BO/design/pages/02_CRUDPageCategory.js
  tests/puppeteer/campaigns/functional/BO/design/pages/03_categoriesBulkActions.js
  tests/puppeteer/campaigns/functional/BO/design/pages/04_filterAndQuickEditCategories.js
  tests/puppeteer/campaigns/functional/BO/design/pages/05_pagesBulkActions.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/design/pages/add.js
  tests/puppeteer/pages/BO/design/pages/index.js
  tests/puppeteer/pages/BO/design/pages/pageCategory/add.js
  tests/puppeteer/pages/FO/cart.js
  tests/puppeteer/pages/FO/cms.js
  tests/puppeteer/pages/FO/siteMap.js
Labels: TE, develop, waiting for review

#16469 Functional tests - fix Employees tests
  tests/puppeteer/pages/BO/advancedParameters/team/add.js
Labels: Refactoring, TE, develop

#16087 Fix no carriers in checkout bad cart rules
  classes/Cart.php
  src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php
  src/Core/Domain/Cart/Command/UpdateCartAddressesCommand.php
  tests/Integration/Behaviour/Features/Context/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Context/CountryFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Delivery/delivery_options.feature
  tests/Integration/Behaviour/Features/Scenario/Order/add_order_from_bo.feature
  tests/Integration/Behaviour/behat.yml
Labels: Bug, Must-have, PM ✔️, QA ✔️, develop

#16052 Fix Very strict selector div.delivery-option
  themes/_core/js/checkout-delivery.js
  themes/core.js
  themes/core.js.map
Labels: Improvement, QA ✔️, develop

#16461 Display display_name instead of name in theme card and adds author.url
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Theme/Blocks/Partials/theme_card.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Theme/index.html.twig
Labels: Bug, QA ✔️, develop

#16468 Fix issue where html tags from ps_emailsubscription module would be escaped and not interpreted as HTML
  themes/classic/modules/ps_emailsubscription/views/templates/hook/ps_emailsubscription.tpl
Labels: Bug, FO, QA ✔️, bugfix, develop

#15958 New design on module positions page
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/pages/_modules.scss
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/positions.html.twig
Labels: BO, Improvement, QA ✔️, UX ✔️, Wording ✔️, develop

#16480 Tests - Using foreach for sanity tests orders
  tests/puppeteer/campaigns/sanity/03_ordersBO/01_filterOrders.js
  tests/puppeteer/pages/BO/orders/index.js
Labels: Refactoring, TE, develop

#16479 Tests - Using foreach for sanity tests products
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/05_BulkActionsBrandAddresses.js
  tests/puppeteer/campaigns/sanity/02_productsBO/01_filterProducts.js
  tests/puppeteer/campaigns/sanity/02_productsBO/05_deleteProductsWithBulkActions.js
Labels: Refactoring, TE, develop

#16340 Fix Bullets of bulleted lists are removed by default
  themes/classic/_dev/css/components/custom-text.scss
  themes/classic/assets/css/theme.css
Labels: Bug, Improvement, QA ✔️, UX ✔️, develop

#16492 Tests - Skip all scenarios Employees bulk actions
  tests/puppeteer/campaigns/functional/BO/advancedParameters/team/03_employeesBulkActions.js
Labels: Refactoring, TE, develop

#16489 Remove unofficial languages from language packs
  localization/az.xml
  localization/cn.xml
  localization/dz.xml
  localization/es.xml
  localization/fr.xml
  localization/il.xml
  localization/ma.xml
  localization/md.xml
  localization/rs.xml
  localization/tn.xml
Labels: Improvement, QA ✔️, develop

#16267 Finish migration "Catalog > Monitoring" page
  admin-dev/themes/new-theme/js/pages/monitoring/index.js
  admin-dev/themes/new-theme/public/helper-card/monitoring@3x.png
  admin-dev/themes/new-theme/public/monitoring.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/_showcase-card.scss
  admin-dev/themes/new-theme/static/helper-card/monitoring@3x.png
  src/Adapter/Product/CommandHandler/UpdateProductStatusCommandHandler.php
  src/Adapter/Product/QueryHandler/GetProductIsEnabledHandler.php
  src/Core/Domain/Product/Command/UpdateProductStatusCommand.php
  src/Core/Domain/Product/CommandHandler/UpdateProductStatusCommandHandlerInterface.php
  src/Core/Domain/Product/Exception/CannotUpdateProductException.php
  src/Core/Domain/Product/Query/GetProductIsEnabled.php
  src/Core/Domain/Product/QueryHandler/GetProductIsEnabledHandlerInterface.php
  src/Core/Domain/ShowcaseCard/ConfigurationMap.php
  src/Core/Domain/ShowcaseCard/ValueObject/ShowcaseCard.php
  src/Core/Grid/Definition/Factory/Monitoring/AbstractProductGridDefinitionFactory.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/MonitoringController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/core/util/helper_card.yml
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Actions/Row/link.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Monitoring/Blocks/showcase_card.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Monitoring/index.html.twig
Labels: High, QA ✔️, Refactoring, Wording ✔️, develop, migration

#16250 Product alignment is wrong in product lists for smaller devices
  themes/classic/_dev/css/components/featuredproducts.scss
  themes/classic/assets/css/theme.css
Labels: Bug, QA ✔️, develop

#16478 Fix shipping method design in payment tunnel
  themes/classic/_dev/css/components/checkout.scss
  themes/classic/assets/css/theme.css
  themes/classic/templates/checkout/_partials/steps/shipping.tpl
Labels: Bug, FO, QA ✔️, bugfix, develop

#16465 Fix autoupgrade
  install-dev/upgrade/php/ps_1770_preset_tab_enabled.php
  install-dev/upgrade/sql/1.7.7.0.sql
  src/PrestaShopBundle/Install/Upgrade.php
  tools/build/Library/ReleaseCreator.php
Labels: Bug, QA ✔️, develop

#16410 Make sure to get correct lang fields for shop
  classes/CMS.php
Labels: Bug, QA ✔️, develop

#16457 Enable TinyMCE on add/edit supplier page BO
  admin-dev/themes/new-theme/js/pages/supplier/supplier-form.js
  src/PrestaShopBundle/Form/Admin/Sell/Supplier/SupplierType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Suppliers/add.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Suppliers/edit.html.twig
Labels: Bug, QA ✔️, develop, migration

#16503 Hiding pack products prices when pack's show price is disabled
  themes/classic/templates/catalog/_partials/miniatures/pack-product.tpl
  themes/classic/templates/catalog/product.tpl
Labels: Bug, QA ✔️, develop

#16013 Mobile Homepage slider
  themes/classic/_dev/css/components/imageslider.scss
  themes/classic/_dev/js/theme.js
  themes/classic/_dev/package-lock.json
  themes/classic/_dev/package.json
  themes/classic/assets/css/theme.css
  themes/classic/assets/js/theme.js
  themes/classic/modules/ps_imageslider/views/templates/hook/slider.tpl
Labels: FO, Improvement, QA ✔️, UX ✔️, develop

#16506 Set minimum PHP version to 7.1.3 (and not 7.1)
  classes/ConfigurationTest.php
  install-dev/controllers/http/system.php
  install-dev/install_version.php
  tools/build/Library/InstallUnpacker/index_template.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#16459 Fix behavior of Module::isRegisteredInHook()
  classes/module/Module.php
Labels: Bug, CO, QA ✔️, develop

#16496 Tests - Fix test CRUD Page Category in functional campaign
  tests/puppeteer/pages/BO/design/pages/index.js
Labels: Refactoring, TE, develop

#16500 Incorrect email subject and template variable {shop_name}
  classes/Mail.php
Labels: 1.7.6.x, Bug, QA ✔️

#16530 Use country id while creating the Supplier form
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/SupplierController.php
Labels: Bug, QA ✔️, develop

#16532 Remove useless debug controller actions
  src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php
Labels: Improvement, develop

#16535 Fixing a JS bug where TinyMCE was not loaded on safari in page content textarea
  admin-dev/themes/new-theme/js/pages/cms-page/form/index.js
  admin-dev/themes/new-theme/public/cms_page_form.bundle.js
Labels: Bug, QA ✔️, develop

#16533 Test- Update functional test Supplier
  tests/puppeteer/pages/BO/catalog/suppliers/add.js
Labels: Refactoring, TE, develop

#16541 Repair pagination on product page listing
  src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Forms/form_products.html.twig
Labels: Bug, QA ✔️, develop

#16542 Specific prices are not displayed in the BO
  src/Adapter/Product/AdminProductWrapper.php
Labels: Bug, QA ✔️, develop

#16504 Displaying 3 products on the same line on home with 2 columns layout
  themes/classic/_dev/css/components/featuredproducts.scss
  themes/classic/assets/css/theme.css
  themes/classic/modules/ps_featuredproducts/views/templates/hook/ps_featuredproducts.tpl
Labels: Bug, QA ✔️, develop

#16473 Adding the Code of Conduct
  CODE_OF_CONDUCT.md
Labels: Bug, Improvement, develop

#16548 Use CMSCategory instead of CMS object model
  src/Adapter/CMS/Page/CommandHandler/AbstractCmsPageHandler.php
Labels: Bug, QA ✔️, develop

#16550 Fix var not displayed in emails when mail address is in uppercase
  classes/Mail.php
Labels: Bug, QA ✔️, develop

#16564 Tests - Fixing tests 04_filterAndQuickEditCategories (functional campaign)
  tests/puppeteer/pages/BO/design/pages/index.js
Labels: Refactoring, TE, develop

#16531 Fix round remaining value of reduction amount
  classes/PaymentModule.php
Labels: Bug, QA ✔️, develop

#16526 Changing suppliers select into bootstrap dropdown
  themes/classic/_dev/css/components/categories.scss
  themes/classic/assets/css/theme.css
  themes/classic/modules/ps_supplierlist/views/templates/_partials/supplier_form.tpl
Labels: FO, Improvement, QA ✔️, develop

#16591 Release 1.7.6.2
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: 1.7.6.x, Improvement

#16596 Merge 1.7.6.x in develop
  CONTRIBUTORS.md
  classes/Mail.php
  docs/CHANGELOG.txt
Labels: Bug, develop

#16522 Prevent getter from changing class state
  classes/Context.php
Labels: 1.7.6.x, Bug, QA ✔️

#16571 Fix total tax in order confirmation
  classes/PaymentModule.php
Labels: Bug, QA ✔️, develop

#16104 Update order status colors
  install-dev/data/xml/order_state.xml
  install-dev/upgrade/php/ps_1770_update_order_status_colors.php
  install-dev/upgrade/sql/1.7.7.0.sql
  src/Core/Domain/Order/Status/OrderStatusColor.php
Labels: Improvement, QA ✔️, develop

#16621 Remove legacy unused Order Slip files
  admin-dev/themes/default/template/controllers/slip/_print_pdf_icon.tpl
  admin-dev/themes/default/template/controllers/slip/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/slip/helpers/form/index.php
  admin-dev/themes/default/template/controllers/slip/helpers/index.php
  admin-dev/themes/default/template/controllers/slip/index.php
  controllers/admin/AdminSlipController.php
Labels: Refactoring, develop

#16588 Unhide monitoring sf page
  admin-dev/themes/default/template/controllers/tracking/helpers/index.php
  admin-dev/themes/default/template/controllers/tracking/helpers/list/index.php
  admin-dev/themes/default/template/controllers/tracking/helpers/list/list_header.tpl
  admin-dev/themes/default/template/controllers/tracking/index.php
  controllers/admin/AdminTrackingController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/monitoring.yml
Labels: QA ✔️, Refactoring, develop, migration

#16318 Make migrated order page's grid rows clickable
  admin-dev/themes/new-theme/js/components/grid/extension/link-row-action-extension.js
  admin-dev/themes/new-theme/public/address.bundle.js
  admin-dev/themes/new-theme/public/attachment.bundle.js
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/category.bundle.js
  admin-dev/themes/new-theme/public/cms_page.bundle.js
  admin-dev/themes/new-theme/public/contacts.bundle.js
  admin-dev/themes/new-theme/public/currency.bundle.js
  admin-dev/themes/new-theme/public/customer.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/employee.bundle.js
  admin-dev/themes/new-theme/public/language.bundle.js
  admin-dev/themes/new-theme/public/manufacturer.bundle.js
  admin-dev/themes/new-theme/public/meta.bundle.js
  admin-dev/themes/new-theme/public/monitoring.bundle.js
  admin-dev/themes/new-theme/public/order.bundle.js
  admin-dev/themes/new-theme/public/order_message.bundle.js
  admin-dev/themes/new-theme/public/profiles.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/supplier.bundle.js
  admin-dev/themes/new-theme/public/tax.bundle.js
  admin-dev/themes/new-theme/public/tax_rules_group.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
  src/Core/Grid/Column/AbstractColumn.php
  src/Core/Grid/Column/Type/BooleanColumn.php
  src/Core/Grid/Column/Type/Common/BadgeColumn.php
  src/Core/Grid/Column/Type/Common/DateTimeColumn.php
  src/Core/Grid/Column/Type/Common/IdentifierColumn.php
  src/Core/Grid/Column/Type/Common/ImageColumn.php
  src/Core/Grid/Column/Type/Common/LinkColumn.php
  src/Core/Grid/Column/Type/Common/PositionColumn.php
  src/Core/Grid/Column/Type/DataColumn.php
  src/Core/Grid/Definition/Factory/CategoryGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/OrderGridDefinitionFactory.php
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/table.html.twig
Labels: Fix, Improvement, Must-have, QA ✔️, develop, migration

#16560 Fix header for migrated Orders pages
  admin-dev/themes/new-theme/template/controllers/orders/page_header_toolbar.tpl
  controllers/admin/AdminLegacyLayoutController.php
  src/Adapter/LegacyContext.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/header.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig
  src/PrestaShopBundle/Resources/views/Admin/layout.html.twig
  src/PrestaShopBundle/Twig/LayoutExtension.php
Labels: Bug, Must-have, QA ✔️, develop, migration

#16383 Currency are customizable and prices are shown accordingly
  .php_cs.dist
  classes/Currency.php
  install-dev/data/db_structure.sql
  install-dev/upgrade/sql/1.7.7.0.sql
  src/Adapter/Currency/CommandHandler/AbstractCurrencyHandler.php
  src/Adapter/Currency/CommandHandler/AddOfficialCurrencyHandler.php
  src/Adapter/Currency/CommandHandler/AddUnofficialCurrencyHandler.php
  src/Adapter/Currency/CommandHandler/EditOfficialCurrencyHandler.php
  src/Adapter/Currency/CommandHandler/EditUnofficialCurrencyHandler.php
  src/Adapter/Currency/CurrencyDataProvider.php
  src/Adapter/Currency/QueryHandler/GetReferenceCurrencyHandler.php
  src/Core/Domain/Currency/Command/AddCurrencyCommand.php
  src/Core/Domain/Currency/Command/EditCurrencyCommand.php
  src/Core/Domain/Currency/QueryResult/ReferenceCurrency.php
  src/Core/Localization/CLDR/CurrencyData.php
  src/Core/Localization/Currency.php
  src/Core/Localization/Currency/CurrencyData.php
  src/Core/Localization/Currency/DataLayer/CurrencyDatabase.php
  src/Core/Localization/Currency/DataLayer/CurrencyReference.php
  src/Core/Localization/Currency/PatternTransformer.php
  src/Core/Localization/Currency/Repository.php
  src/Core/Localization/Specification/Factory.php
  src/Core/Localization/Specification/Number.php
  src/Core/Localization/Specification/NumberInterface.php
  tests-legacy/Unit/Core/Localization/DataLayer/CurrencyDatabaseTest.php
  tests/Integration/Behaviour/Features/Context/CLDRFeatureContext.php
  tests/Integration/Behaviour/Features/Context/CurrencyFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CurrencyFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/CLDR/cldr.feature
  tests/Integration/Behaviour/Features/Scenario/Currency/currency_data.feature
  tests/Integration/Behaviour/Features/Scenario/Currency/currency_management.feature
  tests/Integration/Behaviour/Features/Scenario/Currency/currency_reference.feature
  tests/Integration/Behaviour/behat.yml
  tests/Unit/Core/Localization/Currency/PatternTransformerTest.php
Labels: Improvement, QA ✔️, develop

#16586 Do not escape translations when using the legacy translator from the new one
  classes/Translate.php
  src/Adapter/Localization/LegacyTranslator.php
  src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php
Labels: Bug, CO, QA ✔️, develop

#16510 Avoiding dropdowns from module page to be under header element
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/dropdown_bulk.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/dropdown_categories.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/dropdown_status.html.twig
Labels: Bug, QA ✔️, develop
