Repository PrestaShop/PrestaShop, pull requests merged in 2019-10, with the labels that each got.

#15765 $id_hook is int, not bool
  classes/module/Module.php
Labels: Improvement, develop

#15766 Prepares Twig templates for Add Order page
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/js/pages/order/create-order-map.js
  admin-dev/themes/new-theme/js/pages/order/create-order-page.js
  admin-dev/themes/new-theme/js/pages/order/create.js
  admin-dev/themes/new-theme/js/pages/order/customer-searcher-component.js
  admin-dev/themes/new-theme/js/pages/order/shipping-renderer.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/addresses.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/customer.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/shipping.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/summary.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/vouchers.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/create.html.twig
Labels: Refactoring, develop

#14767 Behat tests for Seo & Urls page commands - some code improvements
  src/Adapter/Meta/CommandHandler/AddMetaHandler.php
  src/Adapter/Meta/CommandHandler/EditMetaHandler.php
  src/Adapter/Meta/MetaDataProvider.php
  src/Core/ConstraintValidator/IsUrlRewriteValidator.php
  src/PrestaShopBundle/Resources/config/services/adapter/meta.yml
  src/PrestaShopBundle/Resources/config/services/core/constraint_validator.yml
  tests/Integration/Behaviour/Features/Context/Domain/AbstractDomainFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/MetaFeatureContext.php
  tests/Integration/Behaviour/Features/Context/LanguageFeatureContext.php
  tests/Integration/Behaviour/Features/Context/MetaFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Meta/meta_management.feature
  tests/Integration/Behaviour/behat.yml
  tests/Unit/Core/ConstraintValidator/IsUrlRewriteValidatorTest.php
Labels: Improvement, develop, migration

#15772 Tests - Fix global Vars in linkchecker
  tests/puppeteer/campaigns/linkchecker.js
Labels: Refactoring, TE, develop

#14665 Allow to display/hide manufacturers and suppliers independently
  admin-dev/themes/default/template/content.tpl
  controllers/front/SitemapController.php
  controllers/front/listing/ManufacturerController.php
  install-dev/data/xml/configuration.xml
  install-dev/upgrade/sql/1.7.7.0.sql
  src/Adapter/Preferences/PreferencesConfiguration.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/SupplierController.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/General/PreferencesType.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/preferences.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Manufacturer/index.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Suppliers/index.html.twig
  src/PrestaShopBundle/Resources/views/Admin/macros.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop

#15616 Refuse empty customer first and last names
  classes/Validate.php
  src/Core/ConstraintValidator/CustomerNameValidator.php
  tests/Unit/Core/ConstraintValidator/CustomerNameValidatorTest.php
Labels: Bug, QA ✔️, develop

#12855 Add Manufacturer Part Number in product codes
  admin-dev/themes/default/template/controllers/suppliers/helpers/view/view.tpl
  classes/Cart.php
  classes/Combination.php
  classes/Product.php
  classes/Search.php
  classes/Validate.php
  classes/order/OrderDetail.php
  classes/stock/Stock.php
  classes/stock/StockMvtWS.php
  classes/stock/SupplyOrderDetail.php
  controllers/admin/AdminImportController.php
  controllers/admin/AdminProductsController.php
  controllers/admin/AdminSuppliersController.php
  install-dev/data/db_structure.sql
  install-dev/upgrade/sql/1.7.7.0.sql
  js/admin/products.js
  src/Adapter/CombinationDataProvider.php
  src/Adapter/Manufacturer/QueryHandler/GetManufacturerForViewingHandler.php
  src/Adapter/Presenter/Product/ProductLazyArray.php
  src/Adapter/Product/AdminProductWrapper.php
  src/Core/Import/EntityField/Provider/CombinationFieldsProvider.php
  src/Core/Import/EntityField/Provider/ProductFieldsProvider.php
  src/PrestaShopBundle/Form/Admin/Product/ProductCombination.php
  src/PrestaShopBundle/Form/Admin/Product/ProductOptions.php
  src/PrestaShopBundle/Model/Product/AdminModelAdapter.php
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combination.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Panels/options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Manufacturer/Blocks/View/products.html.twig
  tests-legacy/PrestaShopBundle/Model/Product/AdminModelAdapterTest.php
  tests/E2E/test/datas/product-data.js
Labels: Feature, Improvement, PM ✔️, QA ✔️, Wording ✔️, develop

#15761 Fix order view page wordings
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/add_order_discount_modal.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/details.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/documents.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/messages.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/payments.html.twig
Labels: Improvement, Wording ✔️, develop

#15790 Tests - Remove chai from Page Objects
  tests/puppeteer/campaigns/sanity/01_installShop/01_installShop.js
  tests/puppeteer/campaigns/sanity/02_productsBO/02_CRUDStandardProductInBO.js
  tests/puppeteer/campaigns/sanity/02_productsBO/03_CRUDStandardProductWithCombinationsInBO.js
  tests/puppeteer/campaigns/sanity/03_ordersBO/01_filterOrders.js
  tests/puppeteer/campaigns/sanity/03_ordersBO/02_editOrder.js
  tests/puppeteer/campaigns/sanity/04_catalogFO/02_checkProduct.js
  tests/puppeteer/campaigns/sanity/05_cartFO/01_editCheckCart.js
  tests/puppeteer/campaigns/sanity/06_checkoutFO/01_orderProduct.js
  tests/puppeteer/campaigns/upgrade/upgradeShop.js
  tests/puppeteer/pages/BO/modulesPages/autoUpgrade.js
  tests/puppeteer/pages/BO/order.js
  tests/puppeteer/pages/BO/products.js
  tests/puppeteer/pages/FO/cart.js
  tests/puppeteer/pages/FO/product.js
  tests/puppeteer/pages/Install/install.js
  tests/puppeteer/pages/commonPage.js
Labels: Refactoring, TE, develop

#15130 Simplify rendering of forms
  src/PrestaShopBundle/Controller/Admin/Improve/Design/CmsPageController.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/OrderPreferences/GeneralType.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/OrderPreferences/GiftOptionsType.php
  src/PrestaShopBundle/Form/Admin/Improve/Design/Pages/CmsPageType.php
  src/PrestaShopBundle/Form/Admin/Type/CustomContentType.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/OrderPreferences/Blocks/order_preferences_general.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/OrderPreferences/Blocks/order_preferences_gift_options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Cms/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Cms/Blocks/seo_preview.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_horizontal_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/form_div_layout.html.twig
  tests-legacy/Integration/PrestaShopBundle/Test/LightWebTestCase.php
Labels: Improvement, QA ✔️, develop, migration

#15750 Update jQuery to 3.4.1 in Core theme and Classic theme
  themes/_core/js/theme.js
  themes/classic/_dev/package-lock.json
  themes/classic/_dev/package.json
  themes/core.js
  themes/core.js.map
  themes/package-lock.json
  themes/package.json
Labels: Improvement, QA ✔️, develop

#15111 Fix wording domains
  admin-dev/themes/default/template/header.tpl
  admin-dev/themes/default/template/layout-ajax.tpl
  admin-dev/themes/default/template/layout.tpl
  admin-dev/themes/new-theme/template/components/layout/error_messages.tpl
  admin-dev/themes/new-theme/template/components/layout/non-responsive.tpl
  admin-dev/themes/new-theme/template/components/layout/quick_access.tpl
  admin-dev/themes/new-theme/template/components/layout/search_form.tpl
  admin-dev/themes/new-theme/template/components/layout/shop_list.tpl
  admin-dev/themes/new-theme/template/components/layout/warning_messages.tpl
  admin-dev/themes/new-theme/template/error.tpl
  admin-dev/themes/new-theme/template/header.tpl
  admin-dev/themes/new-theme/template/helpers/shops_list/list.tpl
  admin-dev/themes/new-theme/template/layout.tpl
  admin-dev/themes/new-theme/template/modal.tpl
  admin-dev/themes/new-theme/template/page_header_toolbar.tpl
Labels: Bug, QA ✔️, Wording ✔️, develop

#13517 Show free shipping indication only if appropriate
  src/Adapter/Presenter/Cart/CartPresenter.php
  themes/classic/modules/ps_shoppingcart/modal.tpl
  themes/classic/templates/checkout/_partials/cart-detailed-totals.tpl
  themes/classic/templates/checkout/_partials/cart-summary-subtotals.tpl
Labels: Improvement, PM ✔️, QA ✔️, Wording ✔️, develop

#15811 Tests - Fix Login Test
  tests/puppeteer/pages/BO/login.js
Labels: Refactoring, TE, develop

#15297 FO: Fix attribute change update on quickview displayProductAdditionalInfo hook
  themes/classic/templates/catalog/_partials/quickview.tpl
Labels: Bug, FO, QA ✔️, develop

#15549 Fix calculation price in group reductions when in tax excluded mode
  classes/product/SpecificPriceFormatter.php
  controllers/front/ProductController.php
  tests-legacy/Unit/Classes/Product/SpecificPriceFormatterTest.php
  tests-legacy/Unit/Controller/FrontController/ProductControllerTest.php
Labels: Bug, QA ✔️, develop

#15755 CLDR Specification\Number should be immutable
  src/Core/Localization/Locale/Repository.php
  src/Core/Localization/Specification/Factory.php
  src/Core/Localization/Specification/Number.php
  tests-legacy/Unit/Core/Localization/Specification/FactoryTest.php
  tests-legacy/Unit/Core/Localization/Specification/NumberTest.php
Labels: Improvement, develop

#15731 Webservices shouldn't display warning when running with fpm or Nginx
  src/Core/Webservice/ServerRequirementsChecker.php
  tests/Unit/Core/Webservice/ServerRequirementsCheckerTest.php
Labels: 1.7.6.x, Bug, QA ✔️

#15840 do not apply htmlentities before insterting message in db
  classes/checkout/CheckoutSession.php
Labels: Bug, QA ✔️, develop

#15848 Fix E2E dockerfile as npm is not anymore in the nodejs package
  tests/E2E/.docker/Dockerfile
Labels: Bug, develop

#15868 Update puppeteer Tests description on package.json
  tests/puppeteer/package.json
Labels: Refactoring, TE, develop

#15856 Must use min-with instead max-widght for the Profile button
  .gitignore
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
Labels: 1.7.6.x, Bug, QA ✔️

#15855 Allow anonymous mode for AdminController
  classes/controller/AdminController.php
  controllers/admin/AdminSearchController.php
Labels: 1.7.6.x, Bug, QA ✔️

#15799 Fix The Association of payment methods with delivery module
  classes/PaymentModule.php
Labels: Bug, QA ✔️, develop

#14970 Migration of Order message page
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/js/pages/order_message/form.js
  admin-dev/themes/new-theme/js/pages/order_message/index.js
  admin-dev/themes/new-theme/public/order_message.bundle.js
  admin-dev/themes/new-theme/public/order_message_form.bundle.js
  controllers/admin/AdminOrderMessageController.php
  src/Adapter/OrderMessage/AbstractOrderMessageHandler.php
  src/Adapter/OrderMessage/CommandHandler/AddOrderMessageHandler.php
  src/Adapter/OrderMessage/CommandHandler/BulkDeleteOrderMessageHandler.php
  src/Adapter/OrderMessage/CommandHandler/DeleteOrderMessageHandler.php
  src/Adapter/OrderMessage/CommandHandler/EditOrderMessageHandler.php
  src/Adapter/OrderMessage/QueryHandler/GetOrderMessageForEditingHandler.php
  src/Core/Domain/OrderMessage/Command/AddOrderMessageCommand.php
  src/Core/Domain/OrderMessage/Command/BulkDeleteOrderMessageCommand.php
  src/Core/Domain/OrderMessage/Command/DeleteOrderMessageCommand.php
  src/Core/Domain/OrderMessage/Command/EditOrderMessageCommand.php
  src/Core/Domain/OrderMessage/CommandHandler/AddOrderMessageHandlerInterface.php
  src/Core/Domain/OrderMessage/CommandHandler/BulkDeleteOrderMessageHandlerInterface.php
  src/Core/Domain/OrderMessage/CommandHandler/DeleteOrderMessageHandlerInterface.php
  src/Core/Domain/OrderMessage/CommandHandler/EditOrderMessageHandlerInterface.php
  src/Core/Domain/OrderMessage/Exception/OrderMessageConstraintException.php
  src/Core/Domain/OrderMessage/Exception/OrderMessageException.php
  src/Core/Domain/OrderMessage/Exception/OrderMessageNotFoundException.php
  src/Core/Domain/OrderMessage/OrderMessageConstraint.php
  src/Core/Domain/OrderMessage/Query/GetOrderMessageForEditing.php
  src/Core/Domain/OrderMessage/QueryHandler/GetOrderMessageForEditingHandlerInterface.php
  src/Core/Domain/OrderMessage/QueryResult/EditableOrderMessage.php
  src/Core/Domain/OrderMessage/ValueObject/OrderMessageId.php
  src/Core/Form/IdentifiableObject/DataHandler/OrderMessageFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/OrderMessageFormDataProvider.php
  src/Core/Grid/Definition/Factory/OrderMessageGridDefinitionFactory.php
  src/Core/Grid/Query/OrderMessageQueryBuilder.php
  src/Core/Search/Filters/OrderMessageFilters.php
  src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/OrderMessageController.php
  src/PrestaShopBundle/Form/Admin/Sell/CustomerService/OrderMessageType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/_sell.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer_service/_customer_service.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer_service/order_message.yml
  src/PrestaShopBundle/Resources/config/services/adapter/order_message.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_handler.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_data_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_factory.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/CustomerService/OrderMessage/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/CustomerService/OrderMessage/create.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/CustomerService/OrderMessage/edit.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/CustomerService/OrderMessage/index.html.twig
  tests-legacy/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
  tests-legacy/PrestaShopBundle/Controller/ControllerTest.php
  tests/Integration/Behaviour/Features/Context/Domain/AbstractDomainFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderMessageContext.php
  tests/Integration/Behaviour/Features/Context/OrderMessageContext.php
  tests/Integration/Behaviour/Features/Scenario/OrderMessage/order_message_management.feature
  tests/Integration/Behaviour/behat.yml
Labels: QA ✔️, Refactoring, Wording ✔️, develop, migration

#15706 Wrong combinaison reference in customer account order history
  themes/classic/templates/customer/_partials/order-detail-no-return.tpl
  themes/classic/templates/customer/_partials/order-detail-return.tpl
Labels: Bug, QA ✔️, develop

#15880 Fix wrong data mapping in export
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
Labels: 1.7.6.x, Bug, QA ✔️

#15851 Fixed missing translation for tax label
  classes/checkout/CheckoutDeliveryStep.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#14864 Files list migration
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/js/pages/attachment/index.js
  admin-dev/themes/new-theme/public/attachment.bundle.js
  src/Adapter/Attachment/AbstractAttachmentHandler.php
  src/Adapter/Attachment/CommandHandler/BulkDeleteAttachmentsHandler.php
  src/Adapter/Attachment/CommandHandler/DeleteAttachmentHandler.php
  src/Adapter/Attachment/QueryHandler/GetAttachmentHandler.php
  src/Core/Domain/Attachment/Command/BulkDeleteAttachmentsCommand.php
  src/Core/Domain/Attachment/Command/DeleteAttachmentCommand.php
  src/Core/Domain/Attachment/CommandHandler/BulkDeleteAttachmentsHandlerInterface.php
  src/Core/Domain/Attachment/CommandHandler/DeleteAttachmentHandlerInterface.php
  src/Core/Domain/Attachment/Exception/AttachmentConstraintException.php
  src/Core/Domain/Attachment/Exception/AttachmentException.php
  src/Core/Domain/Attachment/Exception/AttachmentNotFoundException.php
  src/Core/Domain/Attachment/Exception/BulkDeleteAttachmentsException.php
  src/Core/Domain/Attachment/Exception/DeleteAttachmentException.php
  src/Core/Domain/Attachment/Query/GetAttachment.php
  src/Core/Domain/Attachment/QueryHandler/GetAttachmentHandlerInterface.php
  src/Core/Domain/Attachment/QueryResult/Attachment.php
  src/Core/Domain/Attachment/ValueObject/AttachmentId.php
  src/Core/Grid/Action/Row/Type/SubmitRowAction.php
  src/Core/Grid/Data/Factory/AttachmentGridDataFactoryDecorator.php
  src/Core/Grid/Definition/Factory/AttachmentGridDefinitionFactory.php
  src/Core/Grid/Query/AttachmentQueryBuilder.php
  src/Core/Search/Filters/AttachmentFilters.php
  src/Core/Util/File/FileSizeConverter.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/AttachmentController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/_sell.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/attachment.yml
  src/PrestaShopBundle/Resources/config/services/adapter/attachment.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_data_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/util/file_size.yml
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Actions/Row/submit.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Attachment/index.html.twig
  tests/Unit/Core/Util/File/FileSizeConverterTest.php
Labels: QA ✔️, Refactoring, Wording ✔️, develop, migration

#15895 Add management of an env var to disable debug toolbar in travis tests
  .travis.yml
  app/config/config_dev.yml
  app/config/config_test.yml
  app/config/parameters.yml.dist
  app/config/set_parameters.php
  tests-legacy/parameters.yml.travis
Labels: 1.7.6.x, Bug

#15621 Revert "Fix lang table multi-store data issue"
  classes/ObjectModel.php
  install-dev/upgrade/sql/1.7.6.2.sql
  src/Adapter/Category/QueryHandler/GetCategoryForEditingHandler.php
Labels: 1.7.6.x, Bug, QA ✔️

#15691 Cart rules mustn't be auto added automatically in some cases
  classes/Cart.php
  tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Context/CategoryFeatureContext.php
  tests/Integration/Behaviour/Features/Context/CustomerFeatureContext.php
  tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/amount_multiple.feature
  tests/Integration/Behaviour/behat.yml
Labels: 1.7.6.x, Bug, QA ✔️

#15847 Npm is not anymore in the nodejs package
  tests/E2E/.docker/Dockerfile
Labels: 1.7.6.x, Bug

#15501 Updated blockReassurance in composer.json
  composer.json
  composer.lock
Labels: FO, Improvement, QA ✔️, develop

#15912 Fix missing currency in behat test
  composer.json
  tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/Currency/currency.feature
  tests/Integration/Behaviour/Features/Scenario/Order/add_order_from_bo.feature
Labels: Bug, develop

#15917 Define use_debug_toolbar even if it's not set in parameters.php
  app/config/set_parameters.php
Labels: 1.7.6.x, Bug

#15859 Add clickable row option for grid actions
  admin-dev/themes/new-theme/js/components/grid/extension/link-row-action-extension.js
  admin-dev/themes/new-theme/js/pages/cms-page/index.js
  admin-dev/themes/new-theme/js/pages/currency/index.js
  admin-dev/themes/new-theme/js/pages/employee/index.js
  admin-dev/themes/new-theme/js/pages/manufacturer/index.js
  admin-dev/themes/new-theme/js/pages/supplier/index.js
  admin-dev/themes/new-theme/js/pages/tax/index.js
  admin-dev/themes/new-theme/js/pages/webservice/index.js
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/category.bundle.js
  admin-dev/themes/new-theme/public/cms_page.bundle.js
  admin-dev/themes/new-theme/public/contacts.bundle.js
  admin-dev/themes/new-theme/public/currency.bundle.js
  admin-dev/themes/new-theme/public/customer.bundle.js
  admin-dev/themes/new-theme/public/employee.bundle.js
  admin-dev/themes/new-theme/public/language.bundle.js
  admin-dev/themes/new-theme/public/manufacturer.bundle.js
  admin-dev/themes/new-theme/public/meta.bundle.js
  admin-dev/themes/new-theme/public/profiles.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/supplier.bundle.js
  admin-dev/themes/new-theme/public/tax.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
  src/Core/Grid/Action/Row/Type/LinkRowAction.php
  src/Core/Grid/Definition/Factory/BackupDefinitionFactory.php
  src/Core/Grid/Definition/Factory/CategoryGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/CmsPageCategoryDefinitionFactory.php
  src/Core/Grid/Definition/Factory/CmsPageDefinitionFactory.php
  src/Core/Grid/Definition/Factory/ContactGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/CurrencyGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/CustomerGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/EmployeeGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/LanguageGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/ManufacturerAddressGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/ManufacturerGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/MetaGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/ProfileGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/RequestSqlGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/SupplierGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/TaxGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/WebserviceKeyDefinitionFactory.php
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Actions/Row/link.html.twig
Labels: 1.7.6.x, Bug, Improvement, QA ✔️

#15888 Update jquery in installation pages
  install-dev/theme/views/header.php
Labels: Improvement, QA ✔️, develop

#15916 Set emailsubscription input required
  themes/classic/modules/ps_emailsubscription/views/templates/hook/ps_emailsubscription.tpl
Labels: Improvement, QA ✔️, develop

#15623 Do not allow to put item in cart if available quantity is 0
  classes/Pack.php
  classes/Product.php
  controllers/front/CartController.php
Labels: Bug, QA ✔️, develop

#15930 Fix on product-flags class for product cards
  themes/classic/_dev/css/components/products.scss
  themes/classic/assets/css/theme.css
  themes/classic/assets/js/theme.js
Labels: 1.7.6.x, Bug, QA ✔️

#15428 Add check for required fields in BO > Country > Address format
  admin-dev/themes/default/template/controllers/countries/helpers/form/form.tpl
  classes/AddressFormat.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#15903 Hides bad vouchers that should not be displayed to customers
  controllers/front/DiscountController.php
  src/Adapter/Presenter/Cart/CartPresenter.php
Labels: Bug, QA ✔️, develop

#15886 Improve pop up information on Category deletion
  src/Core/Form/ChoiceProvider/CategoryDeleteModeChoiceProvider.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/delete_categories_modal.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop

#15643 Allow CLDR to display deleted/inactive currencies
  app/config/set_parameters.php
  classes/Currency.php
  install-dev/upgrade/php/ps_1761_update_currencies.php
  src/Adapter/Currency/CommandHandler/AddCurrencyHandler.php
  src/Adapter/Currency/CommandHandler/EditCurrencyHandler.php
  src/Adapter/Currency/CurrencyDataProvider.php
  src/Core/Currency/CurrencyDataProviderInterface.php
  src/Core/Localization/Currency/CurrencyDataSource.php
  src/Core/Localization/Currency/DataLayer/CurrencyDatabase.php
  src/Core/Localization/Currency/DataLayer/CurrencyInstalled.php
  src/Core/Localization/Currency/DataSourceInterface.php
  src/Core/Localization/Currency/Repository.php
  src/Core/Localization/Currency/RepositoryInterface.php
  src/Core/Localization/Locale/Repository.php
  tests-legacy/Unit/Core/Localization/DataLayer/CurrencyDatabaseTest.php
  tests/Integration/Behaviour/Features/Context/CLDRFeatureContext.php
  tests/Integration/Behaviour/Features/Context/CurrencyFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/AbstractDomainFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CurrencyFeatureContext.php
  tests/Integration/Behaviour/Features/Context/LanguageFeatureContext.php
  tests/Integration/Behaviour/Features/Context/SharedStorage.php
  tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/CLDR/cldr.feature
  tests/Integration/Behaviour/Features/Scenario/Currency/currency_management.feature
  tests/Integration/Behaviour/behat.yml
Labels: 1.7.6.x, BC break, Bug, QA ✔️

#15757 Fix monitoring grids id configuration
  src/Core/Grid/Data/Factory/EmptyCategoryGridDataFactory.php
  src/Core/Grid/Definition/Factory/Monitoring/EmptyCategoryGridDefinitionFactory.php
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_data_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_factory.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Monitoring/index.html.twig
Labels: Bug, QA ✔️, develop, migration

#15969 Update Mexican tax rates
  localization/mx.xml
Labels: Improvement, develop

#15968 Update Swedish tax rates
  localization/se.xml
Labels: Improvement, develop

#15798 Remove a field from the employee creation form
  classes/Employee.php
  install-dev/data/db_structure.sql
  install-dev/upgrade/sql/1.7.7.0.sql
  src/Adapter/Profile/Employee/CommandHandler/AddEmployeeHandler.php
  src/Adapter/Profile/Employee/CommandHandler/EditEmployeeHandler.php
  src/Adapter/Profile/Employee/QueryHandler/GetEmployeeForEditingHandler.php
  src/Core/Domain/Employee/Command/AddEmployeeCommand.php
  src/Core/Domain/Employee/Command/EditEmployeeCommand.php
  src/Core/Domain/Employee/QueryResult/EditableEmployee.php
  src/Core/Form/IdentifiableObject/DataHandler/EmployeeFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/EmployeeFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Employee/EmployeeType.php
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Employee/Blocks/form.html.twig
Labels: Improvement, QA ✔️, develop

#15967 Use midnight for birthdate verification
  classes/Validate.php
  tests-legacy/Unit/Classes/ValidateCoreTest.php
Labels: Bug, develop

#15963 Add rel="nofollow" to prestashop website link
  themes/classic/templates/_partials/footer.tpl
Labels: 1.7.6.x, Bug, QA ✔️

#15905 Tests - Add module alias
  tests/puppeteer/campaigns/functional/BO/customers/customers/01_filterAndQuickEditCustomers.js
  tests/puppeteer/campaigns/functional/BO/customers/customers/02_CRUDCustomerInBO.js
  tests/puppeteer/campaigns/functional/BO/customers/customers/03_customersBulkActionsInBO.js
  tests/puppeteer/campaigns/sanity/01_installShop/01_installShop.js
  tests/puppeteer/campaigns/sanity/02_productsBO/01_filterProducts.js
  tests/puppeteer/campaigns/sanity/02_productsBO/02_CRUDStandardProductInBO.js
  tests/puppeteer/campaigns/sanity/02_productsBO/03_CRUDStandardProductWithCombinationsInBO.js
  tests/puppeteer/campaigns/sanity/02_productsBO/04_deleteProduct.js
  tests/puppeteer/campaigns/sanity/02_productsBO/05_deleteProductsWithBulkActions.js
  tests/puppeteer/campaigns/sanity/03_ordersBO/01_filterOrders.js
  tests/puppeteer/campaigns/sanity/03_ordersBO/02_editOrder.js
  tests/puppeteer/campaigns/sanity/04_catalogFO/01_filterProducts.js
  tests/puppeteer/campaigns/sanity/04_catalogFO/02_checkProduct.js
  tests/puppeteer/campaigns/sanity/05_cartFO/01_editCheckCart.js
  tests/puppeteer/campaigns/sanity/06_checkoutFO/01_orderProduct.js
  tests/puppeteer/campaigns/upgrade/upgradeShop.js
  tests/puppeteer/package-lock.json
  tests/puppeteer/package.json
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/addCustomer.js
  tests/puppeteer/pages/BO/addProduct.js
  tests/puppeteer/pages/BO/customers.js
  tests/puppeteer/pages/BO/dashboard.js
  tests/puppeteer/pages/BO/login.js
  tests/puppeteer/pages/BO/moduleCatalog.js
  tests/puppeteer/pages/BO/moduleManager.js
  tests/puppeteer/pages/BO/modulesPages/autoUpgrade.js
  tests/puppeteer/pages/BO/order.js
  tests/puppeteer/pages/BO/products.js
  tests/puppeteer/pages/BO/shopParamsGeneral.js
  tests/puppeteer/pages/BO/shopParamsMaintenance.js
  tests/puppeteer/pages/BO/viewCustomer.js
  tests/puppeteer/pages/FO/FObasePage.js
  tests/puppeteer/pages/FO/cart.js
  tests/puppeteer/pages/FO/checkout.js
  tests/puppeteer/pages/FO/home.js
  tests/puppeteer/pages/FO/login.js
  tests/puppeteer/pages/FO/orderConfirmation.js
  tests/puppeteer/pages/FO/product.js
  tests/puppeteer/pages/Install/install.js
Labels: Refactoring, TE, develop

#15900 Replace usages of jQuery.live usages and add polyfill
  admin-dev/themes/default/template/controllers/addresses/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/carriers/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/orders/form.tpl
  admin-dev/themes/default/template/controllers/specific_price_rule/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/tags/helpers/form/form.tpl
  admin-dev/themes/default/template/helpers/form/assoshop.tpl
  classes/controller/AdminController.php
  js/admin/addons.js
  js/jquery/jquery.live-polyfill-1.0.3.min.js
  themes/_core/js/theme.js
  themes/classic/_dev/package-lock.json
  themes/classic/_dev/package.json
  themes/core.js
  themes/core.js.map
  themes/package-lock.json
  themes/package.json
Labels: Bug, QA ✔️, develop

#15908 Introduces list dropdown - uses it in order list page
  admin-dev/themes/new-theme/js/components/grid/extension/choice-extension.js
  admin-dev/themes/new-theme/js/pages/order/index.js
  admin-dev/themes/new-theme/scss/components/_grid.scss
  src/Core/Grid/Column/Type/Common/ChoiceColumn.php
  src/Core/Grid/Definition/Factory/OrderGridDefinitionFactory.php
  src/Core/Grid/Query/OrderQueryBuilder.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/choice.html.twig
Labels: Feature, QA ✔️, Wording ✔️, develop, migration

#15909 Fix for product images in multishop BO
  classes/Image.php
  src/Adapter/Product/ProductDataProvider.php
Labels: Bug, Multistore, QA ✔️, develop

#15984 [Test] - Improve quick view product
  tests/puppeteer/pages/FO/home.js
Labels: Refactoring, TE, develop

#15974 Fix condition check count languages in getAlternativeLangsUrl
  classes/controller/FrontController.php
Labels: Bug, QA ✔️, develop

#15955 Migrates Customer block of Order view page
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js
  admin-dev/themes/new-theme/js/pages/order/view.js
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Core/Domain/Order/QueryResult/OrderCustomerForViewing.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig
Labels: QA ✔️, Refactoring, develop, migration

#15805 Fix Cannot use object of type ParameterBag as array
  src/Adapter/Security/Admin.php
Labels: Bug, develop

#15926 Fix error SQL in getRecurseCategory method
  classes/CMSCategory.php
Labels: Bug, QA ✔️, develop

#16014 Fix html being displayed in download virtual product text mail
  classes/order/OrderHistory.php
  mails/_partials/download_product_virtual_products.tpl
  mails/_partials/download_product_virtual_products.txt
  mails/themes/classic/core/download_product.html.twig
  mails/themes/modern/core/download_product.html.twig
  src/Adapter/MailTemplate/MailPartialTemplateRenderer.php
Labels: Bug, develop

#13636 Adding zones for: Austria, Switzerland, Denkmark, Netherlands, Thaila…
  localization/at.xml
  localization/ch.xml
  localization/dk.xml
  localization/nl.xml
  localization/th.xml
Labels: Improvement, QA ✔️, Wording ✔️, develop

#16026 Remove final keyword from Lang entity
  src/PrestaShopBundle/Entity/Lang.php
Labels: 1.7.6.x, Bug

#16030 Update Travis CI status image
  README.md
Labels: Bug, develop

#16020 Update Turkish currency sign
  localization/tr.xml
Labels: Improvement, QA ✔️, develop

#16041 remove google plus from login footer google plus is dead
  admin-dev/themes/default/template/controllers/login/content.tpl
Labels: Improvement, PM ✔️, QA ✔️, develop

#16036 Add redirect routes on security annotation of Category pages
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
Labels: 1.7.6.x, Bug, QA ✔️

#16051 Merge of bug fixes from 1.7.6.x branch to develop
  src/PrestaShopBundle/Entity/Lang.php
  themes/classic/templates/_partials/footer.tpl
  themes/classic/templates/catalog/_partials/miniatures/product.tpl
Labels: Bug, develop

#16055 Update Greek tax rates
  localization/gr.xml
Labels: Improvement, QA ✔️, develop

#15448 Replaced Tools::displayPrice deprecated in favor of Locale::formatPrice()
  admin-dev/themes/default/template/controllers/orders/_customized_data.tpl
  admin-dev/themes/default/template/controllers/orders/_product_line.tpl
  admin-dev/themes/default/template/controllers/orders/helpers/view/view.tpl
  classes/Cart.php
  classes/Currency.php
  classes/Notification.php
  classes/PaymentModule.php
  classes/Product.php
  classes/Referrer.php
  classes/Tools.php
  classes/order/OrderHistory.php
  controllers/admin/AdminCartRulesController.php
  controllers/admin/AdminCartsController.php
  controllers/admin/AdminCustomerThreadsController.php
  controllers/admin/AdminOrdersController.php
  controllers/admin/AdminOutstandingController.php
  controllers/admin/AdminStatsController.php
  controllers/admin/AdminSuppliersController.php
  controllers/front/DiscountController.php
  src/Adapter/Cart/QueryHandler/GetCartForViewingHandler.php
  src/Adapter/Cart/QueryHandler/GetCartInformationHandler.php
  src/Adapter/CombinationDataProvider.php
  src/Adapter/Customer/QueryHandler/GetCustomerCartsHandler.php
  src/Adapter/Customer/QueryHandler/GetCustomerForViewingHandler.php
  src/Adapter/Customer/QueryHandler/GetCustomerOrdersHandler.php
  src/Adapter/Kpi/ShoppingCartTotalKpi.php
  src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php
  src/Adapter/Order/CommandHandler/IssuePartialRefundHandler.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Presenter/Order/OrderDetailLazyArray.php
  src/Adapter/Product/AdminProductWrapper.php
  src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php
  src/Core/Localization/Locale.php
  src/PrestaShopBundle/Resources/config/services/adapter/cart.yml
  src/PrestaShopBundle/Resources/config/services/adapter/customer.yml
  src/PrestaShopBundle/Resources/config/services/adapter/data_provider.yml
  src/PrestaShopBundle/Resources/config/services/adapter/kpi.yml
  src/PrestaShopBundle/Resources/config/services/adapter/mail_template.yml
  src/PrestaShopBundle/Resources/config/services/adapter/order.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/supplier.yml
  src/PrestaShopBundle/Resources/config/services/core/cldr.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_data_factory.yml
Labels: Refactoring, develop

#16005 Tests - Adding env file for docker
  tests/puppeteer/.docker/prestashop/.env
  tests/puppeteer/.docker/prestashop/Dockerfile
  tests/puppeteer/.docker/prestashop/Dockerfile-from-git
  tests/puppeteer/docker-compose.nightly.yml
  tests/puppeteer/docker-compose.ps-git.yml
Labels: QA ✔️, Refactoring, TE, develop

#16060 Minor improvements for Orders list
  src/Core/Grid/Definition/Factory/OrderGridDefinitionFactory.php
  src/Core/Grid/Query/OrderQueryBuilder.php
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/order_price.html.twig
Labels: Improvement, QA ✔️, develop, migration

#15511 Make sure the key used for translation is case sensitive.
  src/PrestaShopBundle/Entity/Translation.php
Labels: Bug, QA ✔️, develop

#16018 Sanity Tests - Refacto of all tests
  tests/puppeteer/campaigns/data/FO/cart.js
  tests/puppeteer/campaigns/data/demo/orders.js
  tests/puppeteer/campaigns/sanity/01_installShop/01_installShop.js
  tests/puppeteer/campaigns/sanity/02_productsBO/01_filterProducts.js
  tests/puppeteer/campaigns/sanity/02_productsBO/02_CRUDStandardProductInBO.js
  tests/puppeteer/campaigns/sanity/02_productsBO/03_CRUDStandardProductWithCombinationsInBO.js
  tests/puppeteer/campaigns/sanity/02_productsBO/04_deleteProduct.js
  tests/puppeteer/campaigns/sanity/02_productsBO/05_deleteProductsWithBulkActions.js
  tests/puppeteer/campaigns/sanity/03_ordersBO/01_filterOrders.js
  tests/puppeteer/campaigns/sanity/03_ordersBO/02_editOrder.js
  tests/puppeteer/campaigns/sanity/04_catalogFO/01_filterProducts.js
  tests/puppeteer/campaigns/sanity/04_catalogFO/02_checkProduct.js
  tests/puppeteer/campaigns/sanity/05_cartFO/01_editCheckCart.js
  tests/puppeteer/campaigns/sanity/06_checkoutFO/01_orderProduct.js
  tests/puppeteer/pages/BO/order.js
  tests/puppeteer/pages/BO/orders.js
  tests/puppeteer/pages/FO/cart.js
  tests/puppeteer/pages/FO/home.js
  tests/puppeteer/pages/Install/install.js
Labels: Refactoring, TE, develop

#15980 Linkchecker update
  tests/puppeteer/.gitignore
  tests/puppeteer/README.md
  tests/puppeteer/campaigns/linkchecker.js
  tests/puppeteer/package.json
  tests/puppeteer/tools/linkchecker.js
  tests/puppeteer/tools/urls.js
Labels: Refactoring, TE, develop

#16071 Fixed "Call to a member function formatPrice() on null"
  classes/Cart.php
  classes/Product.php
Labels: Bug, QA ✔️, develop

#15987 Check if customized product image exists before trying to delete it
  classes/Cart.php
Labels: Bug, QA ✔️, develop

#15988 Functional Tests - Add tests for categories
  tests/puppeteer/campaigns/data/demo/categories.js
  tests/puppeteer/campaigns/data/faker/category.js
  tests/puppeteer/campaigns/functional/BO/catalog/categories/01_filterAndQuickEditCategories.js
  tests/puppeteer/campaigns/functional/BO/catalog/categories/02_CRUDCategoryInBO.js
  tests/puppeteer/campaigns/functional/BO/catalog/categories/03_categoriesBulkAction.js
  tests/puppeteer/package.json
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/addCategory.js
  tests/puppeteer/pages/BO/categories.js
  tests/puppeteer/pages/FO/FObasePage.js
  tests/puppeteer/pages/FO/siteMap.js
  tests/puppeteer/pages/commonPage.js
Labels: Refactoring, TE, develop

#16090 Implement new Order View header
  admin-dev/themes/new-theme/scss/components/_font.scss
  admin-dev/themes/new-theme/scss/theme.scss
  admin-dev/themes/new-theme/template/controllers/orders/page_header_toolbar.tpl
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Core/Domain/Order/QueryResult/OrderForViewing.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/header.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop, migration

#16085 Fixed "Attempted to call an undefined method named 'formatPrice' of class 'PrestaShop\PrestaShop\Core\Localization\CLDR\Locale'"
  src/Adapter/Presenter/Order/OrderDetailLazyArray.php
Labels: Bug, QA ✔️, develop

#16111 Checked that ShippingCostTax values are not null before being formatted
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
Labels: Bug, QA ✔️, develop

#16047 Handle multistore customers sharing in customers listing at group level
  src/Adapter/Shop/Context.php
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
Labels: 1.7.6.x, Bug, QA ✔️

#16114 Add missing placeholder in the Private Note textarea
  src/PrestaShopBundle/Form/Admin/Sell/Customer/PrivateNoteType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
Labels: Bug, QA ✔️, Wording ✔️, develop

#16126 Change checkout button wording
  themes/classic/templates/checkout/_partials/steps/payment.tpl
Labels: Improvement, QA ✔️, develop

#16022 Migrate order action and status block
  admin-dev/themes/new-theme/scss/components/_button.scss
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Core/Domain/Order/QueryResult/OrderCarrierForViewing.php
  src/Core/Domain/Order/QueryResult/OrderDocumentsForViewing.php
  src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/history.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/order_actions.html.twig
  src/PrestaShopBundle/Twig/Extension/LocalizationExtension.php
Labels: QA ✔️, Refactoring, develop, migration

#16072 Remove require config.inc.php on all command and fix a notice
  src/PrestaShopBundle/Command/AppendConfigurationFileHooksListCommand.php
  src/PrestaShopBundle/Command/AppendHooksListForSqlUpgradeFileCommand.php
  src/PrestaShopBundle/Command/GenerateMailTemplatesCommand.php
  src/PrestaShopBundle/Command/ModuleCommand.php
  src/PrestaShopBundle/Command/ThemeEnablerCommand.php
Labels: Bug, QA ✔️, develop

#15906 Fixes issue Undefined index _route
  src/PrestaShopBundle/Controller/Admin/CommonController.php
Labels: Bug, QA ✔️, develop

#16045 Swap select value submision fix in admin forms
  js/admin.js
Labels: Bug, QA ✔️, develop

#16123 Delete supplier's address only if no other shops use it
  src/Adapter/Supplier/CommandHandler/AbstractDeleteSupplierHandler.php
Labels: Bug, QA ✔️, develop

#16156 Tests - Update name of catalog Menu link in BO
  tests/puppeteer/campaigns/functional/BO/catalog/categories/01_filterAndQuickEditCategories.js
  tests/puppeteer/campaigns/functional/BO/catalog/categories/02_CRUDCategoryInBO.js
  tests/puppeteer/campaigns/functional/BO/catalog/categories/03_categoriesBulkAction.js
  tests/puppeteer/campaigns/sanity/02_productsBO/01_filterProducts.js
  tests/puppeteer/campaigns/sanity/02_productsBO/02_CRUDStandardProductInBO.js
  tests/puppeteer/campaigns/sanity/02_productsBO/03_CRUDStandardProductWithCombinationsInBO.js
  tests/puppeteer/campaigns/sanity/02_productsBO/04_deleteProduct.js
  tests/puppeteer/campaigns/sanity/02_productsBO/05_deleteProductsWithBulkActions.js
  tests/puppeteer/pages/BO/BObasePage.js
Labels: Refactoring, develop

#16097 Improvement on product image generation for high definition images.
  controllers/admin/AdminImagesController.php
Labels: Improvement, QA ✔️, develop

#16000 Update Indian tax rates
  localization/in.xml
Labels: Bug, Improvement, QA ✔️, Wording ✔️, develop

#16049 Fix number of DL & expiration date being displayed in the download virtual product mail
  classes/order/OrderHistory.php
  mails/_partials/download_product_virtual_products.tpl
  mails/_partials/download_product_virtual_products.txt
  src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php
  src/PrestaShopBundle/Resources/config/services/adapter/mail_template.yml
Labels: Bug, QA ✔️, Wording ✔️, develop

#16125 Functional Tests - Add BO tests for Brands
  tests/puppeteer/.eslintrc.js
  tests/puppeteer/campaigns/data/demo/brands.js
  tests/puppeteer/campaigns/data/faker/brand.js
  tests/puppeteer/campaigns/data/faker/brandAddress.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/01_filterAndQuickEditBrands.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/02_filterBrandAddresses.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/03_CRUDBrandAndAddress.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/04_BulkActionsBrands.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/05_BulkActionsBrandAddresses.js
  tests/puppeteer/campaigns/utils/files.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/addBrand.js
  tests/puppeteer/pages/BO/addBrandAddress.js
  tests/puppeteer/pages/BO/brands.js
  tests/puppeteer/pages/BO/viewBrand.js
  tests/puppeteer/pages/commonPage.js
Labels: Refactoring, TE, develop

#16160 Update Swiss tax rates
  localization/ch.xml
Labels: Improvement, QA ✔️, develop

#16172 Remove constraint on siret in CustomerType
  src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php
Labels: 1.7.6.x, Bug, QA ✔️

#16158 Fix filter not being taken into account in grid export
  src/Core/Grid/Definition/Factory/CategoryGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/CustomerGridDefinitionFactory.php
  src/Core/Search/Filters/CategoryFilters.php
  src/Core/Search/Filters/CustomerFilters.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/categories.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer/customers.yml
Labels: 1.7.6.x, Bug, QA ✔️

#16161 Update Colombian tax rates
  localization/co.xml
Labels: Improvement, QA ✔️, develop

#16187 Update Israeli tax rates
  localization/il.xml
Labels: Improvement, QA ✔️, develop

#16185 Update Guyanan tax rates
  localization/gy.xml
Labels: Improvement, QA ✔️, develop

#16186 Update Indonesian tax rates
  localization/id.xml
Labels: Improvement, QA ✔️, develop

#16183 Update Fijian tax rates
  localization/fj.xml
Labels: Improvement, QA ✔️, develop

#16182 Update Egyptian tax rates
  localization/eg.xml
Labels: Improvement, QA ✔️, develop

#16188 Update Iranian tax rates
  localization/ir.xml
Labels: Improvement, QA ✔️, develop

#16194 Tests - Refactoring puppeteer tests
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/01_filterAndQuickEditBrands.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/02_filterBrandAddresses.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/03_CRUDBrandAndAddress.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/04_BulkActionsBrands.js
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/05_BulkActionsBrandAddresses.js
  tests/puppeteer/campaigns/functional/BO/catalog/categories/01_filterAndQuickEditCategories.js
  tests/puppeteer/campaigns/functional/BO/catalog/categories/02_CRUDCategoryInBO.js
  tests/puppeteer/campaigns/functional/BO/catalog/categories/03_categoriesBulkAction.js
  tests/puppeteer/campaigns/functional/BO/customers/customers/01_filterAndQuickEditCustomers.js
  tests/puppeteer/campaigns/functional/BO/customers/customers/02_CRUDCustomerInBO.js
  tests/puppeteer/campaigns/functional/BO/customers/customers/03_customersBulkActionsInBO.js
  tests/puppeteer/campaigns/functional/BO/international/taxes/01_filterAndQuickEditTaxes.js
  tests/puppeteer/campaigns/functional/BO/international/taxes/02_CRUDTaxesInBO.js
  tests/puppeteer/campaigns/functional/BO/international/taxes/03_taxesBulkActionsInBO.js
  tests/puppeteer/campaigns/sanity/01_installShop/01_installShop.js
  tests/puppeteer/campaigns/sanity/02_productsBO/01_filterProducts.js
  tests/puppeteer/campaigns/sanity/02_productsBO/02_CRUDStandardProductInBO.js
  tests/puppeteer/campaigns/sanity/02_productsBO/03_CRUDStandardProductWithCombinationsInBO.js
  tests/puppeteer/campaigns/sanity/02_productsBO/04_deleteProduct.js
  tests/puppeteer/campaigns/sanity/02_productsBO/05_deleteProductsWithBulkActions.js
  tests/puppeteer/campaigns/sanity/03_ordersBO/01_filterOrders.js
  tests/puppeteer/campaigns/sanity/03_ordersBO/02_editOrder.js
  tests/puppeteer/campaigns/sanity/04_catalogFO/01_filterProducts.js
  tests/puppeteer/campaigns/sanity/04_catalogFO/02_checkProduct.js
  tests/puppeteer/campaigns/sanity/05_cartFO/01_editCheckCart.js
  tests/puppeteer/campaigns/sanity/06_checkoutFO/01_orderProduct.js
  tests/puppeteer/pages/BO/addCategory.js
  tests/puppeteer/pages/BO/addCustomer.js
  tests/puppeteer/pages/BO/addTax.js
  tests/puppeteer/pages/BO/brands.js
  tests/puppeteer/pages/BO/categories.js
  tests/puppeteer/pages/BO/customers.js
  tests/puppeteer/pages/BO/login.js
  tests/puppeteer/pages/BO/orders.js
  tests/puppeteer/pages/BO/products.js
  tests/puppeteer/pages/BO/taxes.js
Labels: Refactoring, TE, develop

#16193 Update Norwegian tax rates
  localization/no.xml
Labels: Improvement, QA ✔️, develop

#16189 Update Japanese tax rates
  localization/jp.xml
Labels: Improvement, QA ✔️, develop

#16216 Tests - Add functional tests command to package.json
  tests/puppeteer/campaigns/functional/BO/catalog/brandsAndSuppliers/brands/03_CRUDBrandAndAddress.js
  tests/puppeteer/package.json
  tests/puppeteer/pages/BO/addBrandAddress.js
Labels: Refactoring, TE, develop

#16175 Fix label not in place on BO products page in Filter by categories
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/_category_tree.scss
Labels: Bug, QA ✔️, develop

#12379 Fix of the carrier choice in payment preferences, product editor and cart rules
  controllers/admin/AdminCartRulesController.php
  src/Core/Form/ChoiceProvider/CarrierByReferenceChoiceProvider.php
  src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php
Labels: Bug, PM ✔️, QA ✔️, develop

#15965 Implements CQRS on Notifications
  src/Adapter/Notification/CommandHandler/UpdateEmployeeNotificationLastElementHandler.php
  src/Adapter/Notification/QueryHandler/GetNotificationLastElementsHandler.php
  src/Core/Domain/Notification/Command/UpdateEmployeeNotificationLastElementCommand.php
  src/Core/Domain/Notification/CommandHandler/UpdateEmployeeNotificationLastElementCommandHandlerInterface.php
  src/Core/Domain/Notification/Exception/NotificationException.php
  src/Core/Domain/Notification/Query/GetNotificationLastElements.php
  src/Core/Domain/Notification/QueryHandler/GetNotificationLastElementsHandlerInterface.php
  src/Core/Domain/Notification/QueryResult/NotificationResult.php
  src/Core/Domain/Notification/QueryResult/NotificationsResult.php
  src/Core/Domain/Notification/QueryResult/NotificationsResults.php
  src/Core/Domain/Notification/ValueObject/Type.php
  src/PrestaShopBundle/Controller/Admin/CommonController.php
  src/PrestaShopBundle/Resources/config/services/adapter/notification.yml
Labels: QA ✔️, Refactoring, develop

#16222 Fix error when deleting order cart rule
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Core/Domain/Order/QueryResult/OrderDiscountForViewing.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
Labels: Bug, QA ✔️, develop, migration

#16218 Add and update tax rates
  localization/nz.xml
  localization/rs.xml
  localization/ru.xml
  localization/sa.xml
  localization/tz.xml
  localization/ua.xml
  localization/ve.xml
  localization/vn.xml
  localization/za.xml
Labels: Improvement, QA ✔️, develop

#16230 Add tax information for ecotax field
  src/PrestaShopBundle/Form/Admin/Product/ProductCombination.php
Labels: Improvement, QA ✔️, Wording ✔️, develop

#16224 Add tax information in combination table
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combinations.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop

#16173 Add Ivory Coast as a supported country
  localization/ci.xml
Labels: Feature, QA ✔️, Wording ✔️, develop

#16075 Some fixes to Orders page
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Order/QueryHandler/GetOrderPreviewHandler.php
  src/Core/Domain/Order/QueryResult/OrderProductForViewing.php
  src/Core/Grid/Definition/Factory/OrderGridDefinitionFactory.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/preview.html.twig
Labels: Bug, QA ✔️, Wording ✔️, develop, migration

#16088 Disable Customer group selection checkbox when single customer is set…
  admin-dev/themes/default/template/controllers/cart_rules/form.js
Labels: Improvement, QA ✔️, develop
