Repository PrestaShop/PrestaShop, pull requests merged in 2020-02, with the labels that each got.

#17241 Do not allow negative amount in order payment block
  classes/order/OrderPayment.php
  src/Core/Domain/Order/Exception/NegativePaymentAmountException.php
  src/Core/Domain/Order/Payment/Command/AddPaymentCommand.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/OrderPaymentType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  tests/Integration/Behaviour/Features/Context/Domain/OrderPaymentFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️

#17445 Fix wrong address edit link
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig
Labels: 1.7.7.x, Bug, QA ✔️

#17421 Delete free shipping voucher after creating an order on BO
  src/Adapter/Cart/CommandHandler/SetFreeShippingToCartHandler.php
  src/Core/Domain/CartRule/Exception/CannotDeleteCartRuleException.php
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️, migration

#17366 Added missing admin security annotations
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
Labels: 1.7.7.x, Bug, QA ✔️, migration

#17465 Fix create order customization/combinations
  admin-dev/themes/new-theme/js/pages/order/create/product-manager.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/addresses.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, waiting for wording

#17395 Can't explore a category when all subcats are disabled
  src/Adapter/Grid/Action/Row/AccessibilityChecker/CategoryForViewAccessibilityChecker.php
Labels: 1.7.6.x, Bug, QA ✔️

#17440 Functional tests - Add new test bulk actions languages
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/languages/03_bulkActionsLanguages.js
  tests/puppeteer/pages/BO/international/languages/index.js
Labels: 1.7.7.x, Refactoring, TE

#17483 Merge 1.7.7.x into develop - 03/02/2020
  admin-dev/themes/default/template/controllers/request_sql/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/request_sql/helpers/view/view.tpl
  classes/order/OrderPayment.php
  src/Adapter/Cart/CommandHandler/SetFreeShippingToCartHandler.php
  src/Core/Domain/CartRule/Exception/CannotDeleteCartRuleException.php
  src/Core/Domain/Order/Exception/NegativePaymentAmountException.php
  src/Core/Domain/Order/Payment/Command/AddPaymentCommand.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/OrderPaymentType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig
  tests/Integration/Behaviour/Features/Context/Domain/OrderPaymentFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
Labels: Improvement, develop

#17495 Functional tests - Add test for monitoring product without description
  tests/puppeteer/campaigns/data/faker/product.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/03_monitoring/02_monitoringProducts.js
Labels: 1.7.7.x, Refactoring, TE

#17073 Email subject doesn't support html entities
  classes/Mail.php
Labels: Bug, QA ✔️, develop

#17499 Functional tests - Add new test Filter modules by categories
  tests/puppeteer/campaigns/functional/BO/07_modules/01_moduleManager/02_filterModulesByCategories.js
  tests/puppeteer/pages/BO/modules/moduleManager/index.js
Labels: 1.7.7.x, Refactoring, TE

#17518 Functional test - Add data file for module categories
  tests/puppeteer/campaigns/data/demo/moduleCategories.js
  tests/puppeteer/campaigns/functional/BO/07_modules/01_moduleManager/02_filterModulesByCategories.js
Labels: 1.7.7.x, Refactoring, TE

#17531 Remove irrelevant Todo in order messages
  admin-dev/themes/new-theme/js/pages/order/message/order-view-page-messages-handler.js
Labels: 1.7.7.x, Bug

#17532 Fix PHP CS Fixer configuration: disable single_line_throw and backport #17328
  .github/workflows/main.yml
  .github/workflows/php.yml
  .php_cs.dist
  .prettyci.composer.json
  composer.json
Labels: 1.7.7.x, Improvement

#17515 Increase timeout to download translation packages from 5 to 20 seconds
  classes/Language.php
Labels: Improvement, develop

#17388 Functional tests - Product settings test new days number
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_newDaysNumber.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
  tests/puppeteer/pages/FO/home.js
Labels: 1.7.7.x, Refactoring, TE

#17510 Fix phpdoc of class Link
  classes/Link.php
Labels: Improvement, develop

#15773 CO : Performance optimisation
  classes/ProductAssembler.php
Labels: Improvement, develop

#17456 Introduces checkbox in list filter row
  admin-dev/themes/new-theme/js/components/grid/extension/filters-submit-button-enabler-extension.js
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/Table/filters_row.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/bulk_actions_select_all.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/grid.html.twig
Labels: 1.7.7.x, Improvement, QA ✔️, migration

#17478 Cherry picked the changes from develop related to Refactor UI kit form #16964 and applied to 1.7.7.x
  admin-dev/themes/default/js/bundle/admin_parameters/performancePageUI.js
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/PerformanceController.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/CachingType.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/CombineCompressCacheType.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/DebugModeType.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/MediaServersType.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/MemcacheServerType.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/OptionalFeaturesType.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/SmartyType.php
  src/PrestaShopBundle/Form/Admin/Extension/RowAttributesExtension.php
  src/PrestaShopBundle/Form/Admin/Type/TranslatorAwareType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_extension.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/memcache_servers.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/performance.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: 1.7.7.x, Improvement, QA ✔️, migration

#17448 Fix create order info missing
  admin-dev/themes/new-theme/js/pages/order/create/create-order-map.js
  admin-dev/themes/new-theme/js/pages/order/create/customer-renderer.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/customer.html.twig
Labels: 1.7.7.x, Bug, QA ✔️

#17133 Correct history on product page
  themes/_core/js/product.js
  themes/core.js
Labels: Bug, QA ✔️, develop

#17537 Increase timeout to download translation packages from 5 to 20 seconds
  classes/Language.php
Labels: 1.7.7.x, Improvement

#17020 Sending rating event on product refresh to avoid empty rating stars
  themes/_core/js/product.js
Labels: Bug, QA ✔️, develop

#17014 Correct history problem on listing page
  themes/classic/_dev/js/listing.js
Labels: Bug, QA ✔️, develop

#17547 Fix grids, when search finds no result we still display filters and reset button
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/Table/filters_row.html.twig
Labels: 1.7.7.x, Bug, QA ✔️

#17559 Functional tests - Fix select all grid selector
  tests/puppeteer/pages/BO/advancedParameters/database/dbBackup/index.js
  tests/puppeteer/pages/BO/advancedParameters/team/index.js
  tests/puppeteer/pages/BO/advancedParameters/team/profiles/index.js
  tests/puppeteer/pages/BO/catalog/brands/index.js
  tests/puppeteer/pages/BO/catalog/categories/index.js
  tests/puppeteer/pages/BO/catalog/files/index.js
  tests/puppeteer/pages/BO/catalog/suppliers/index.js
  tests/puppeteer/pages/BO/customerService/orderMessages/index.js
  tests/puppeteer/pages/BO/customers/addresses/index.js
  tests/puppeteer/pages/BO/customers/index.js
  tests/puppeteer/pages/BO/design/pages/index.js
  tests/puppeteer/pages/BO/international/languages/index.js
  tests/puppeteer/pages/BO/international/taxes/index.js
  tests/puppeteer/pages/BO/shopParameters/contact/index.js
Labels: 1.7.7.x, Refactoring, TE

#17533 Only compute assets for Travis for tests which need it
  .travis.yml
Labels: Improvement, develop

#17243 Permit submit form button to be outside of a form with a form attribute
  themes/_core/js/cart.js
Labels: Improvement, QA ✔️, develop

#17477 Register new 1.7.8 hooks into XML and SQL files
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.8.0.sql
Labels: Feature, develop

#17589 Update Configuration::get phpdoc
  classes/Configuration.php
Labels: Improvement, develop

#17583 Migration 1.7.7.x Register all new hooks
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.7.0.sql
  src/Core/Hook/Provider/GridDefinitionHookByServiceIdsProvider.php
  src/Core/Hook/Provider/IdentifiableObjectHookByFormTypeProvider.php
Labels: 1.7.7.x, Improvement

#17556 Improve Travis config file to avoid green builds if File Syntax fails
  .travis.yml
  tests/check_file_syntax.sh
Labels: Bug, develop

#17555 Functional tests - Product settings max size short description
  tests/puppeteer/campaigns/data/faker/product.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/03_maxSizeShortDescription.js
  tests/puppeteer/pages/BO/catalog/products/add.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
Labels: 1.7.7.x, Refactoring, TE

#16287 Don't duplicate currencies in DB when creating a formerly deleted one
  src/Adapter/Currency/CommandHandler/AbstractCurrencyHandler.php
  src/Adapter/Currency/CommandHandler/AddOfficialCurrencyHandler.php
  src/Adapter/Currency/CommandHandler/AddUnofficialCurrencyHandler.php
  src/Adapter/Currency/CommandHandler/EditOfficialCurrencyHandler.php
  src/Adapter/Currency/CommandHandler/EditUnofficialCurrencyHandler.php
  src/Adapter/Currency/CurrencyDataProvider.php
  src/Core/Domain/Currency/Command/AddCurrencyCommand.php
  src/Core/Domain/Currency/Command/AddOfficialCurrencyCommand.php
  src/Core/Domain/Currency/Command/AddUnofficialCurrencyCommand.php
  src/Core/Domain/Currency/CommandHandler/AddCurrencyHandlerInterface.php
  src/Core/Form/IdentifiableObject/DataHandler/CurrencyFormDataHandler.php
  src/PrestaShopBundle/Resources/config/services/adapter/currency.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
  tests/Integration/Behaviour/Features/Context/CurrencyFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CurrencyFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Currency/currency_management.feature
Labels: Improvement, QA ✔️, develop

#17566 Functional tests - CRUD web service key
  tests/puppeteer/campaigns/data/faker/webservice.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/09_webservice/01_CRUDWebservice.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/advancedParameters/webservice/add.js
  tests/puppeteer/pages/BO/advancedParameters/webservice/index.js
Labels: 1.7.7.x, Refactoring, TE

#16543 Fixing menu animation to be opened properly
  admin-dev/themes/default/js/admin-theme.js
  admin-dev/themes/default/js/bundle/components/navbar-transition-handler.js
  admin-dev/themes/default/js/bundle/utils/animations.js
  admin-dev/themes/default/js/modernizr-loads.js
  admin-dev/themes/default/sass/partials/_nav.sass
  admin-dev/themes/default/template/nav.tpl
  admin-dev/themes/new-theme/js/app/utils/animations.js
  admin-dev/themes/new-theme/js/components/navbar-transition-handler.js
  admin-dev/themes/new-theme/js/nav_bar.js
  admin-dev/themes/new-theme/scss/components/layout/_nav_bar.scss
  admin-dev/themes/new-theme/template/components/layout/nav_bar.tpl
Labels: BO, Bug, Front-end, QA ✔️, develop

#17433 Do not escape translations when using the legacy translator from the new one
  classes/Translate.php
  src/Adapter/Localization/LegacyTranslator.php
  src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php
Labels: 1.7.6.x, Bug, QA ✔️

#17612 Fixed Empty Option in Smarty Form in Advanced Parameters > Performance
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/SmartyType.php
Labels: 1.7.7.x, Bug, QA ✔️

#17634 Fix some comments in `CartRuleCalculator` class
  src/Core/Cart/CartRuleCalculator.php
Labels: develop, no

#17616 Remove useless assets
  admin-dev/themes/default/package.json
  themes/classic/assets/css/theme.css
  themes/classic/assets/js/theme.js
  themes/core.js
  themes/package.json
Labels: Bug, develop

#17643 CS fix
  tests/Integration/Behaviour/Features/Context/Domain/OrderRefundFeatureContext.php
Labels: 1.7.7.x, Bug

#17642 Fix SQL request for order detail
  install-dev/upgrade/sql/1.7.7.0.sql
Labels: 1.7.7.x, Bug

#17569 On virtual product, the delivery time shouldn't display
  themes/classic/templates/catalog/_partials/product-prices.tpl
Labels: Bug, QA ✔️, develop

#17088 Allow override of Product::cleanPositions() function
  classes/Product.php
Labels: Bug, develop

#17522 FIX - Disabled products are visible with wrong token or no token at all
  controllers/front/ProductController.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#17652 Functional tests - Fix monitoring test
  tests/puppeteer/campaigns/functional/BO/03_catalog/03_monitoring/02_monitoringProducts.js
Labels: 1.7.7.x, Refactoring, TE

#17459 Adjust zindex header to avoid it behind over the menu on mobile
  admin-dev/themes/new-theme/scss/components/layout/_header_toolbar.scss
Labels: Bug, QA ✔️, develop

#17649 Fix wrong address edit link in order detail
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, migration

#17608 Email subject doesn't support html entities
  classes/Mail.php
Labels: 1.7.6.x, Bug, QA ✔️

#17678 Functional tests - Add context to orders tests
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/01_generateInvoiceByDate.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/02_generateInvoiceByStatus.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/01_enableDisableInvoices.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/02_enableDisableTaxBreakdown.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/03_enableDisableProductImage.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/04_invoicePrefix.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/05_enableDisableCurrentYear.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/06_otherOptions.js
  tests/puppeteer/campaigns/functional/BO/02_orders/03_creditSlips/01_createFilterCreditSlips.js
  tests/puppeteer/campaigns/functional/BO/02_orders/03_creditSlips/02_generateCreditSlipsByDate.js
  tests/puppeteer/campaigns/functional/BO/02_orders/03_creditSlips/03_creditSlipOptions.js
  tests/puppeteer/campaigns/functional/BO/02_orders/04_deliverySlips/01_generateDeliverySlipByDate.js
  tests/puppeteer/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/01_deliverySlipPrefix.js
  tests/puppeteer/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/02_deliverySlipNumber.js
  tests/puppeteer/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/03_enableDisableProductImage.js
Labels: 1.7.7.x, Refactoring, TE

#17674 Functional tests - Add context to catalog tests
  tests/puppeteer/campaigns/functional/BO/03_catalog/01_products/01_filterAndQuickEditProducts.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/01_filterAndQuickEditCategories.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/02_CRUDCategoryInBO.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/03_categoriesBulkAction.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/03_monitoring/01_deleteEmptyCategory.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/03_monitoring/02_monitoringProducts.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/01_filterAndQuickEditBrands.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/02_filterBrandAddresses.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/03_CRUDBrandAndAddress.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/04_BulkActionsBrands.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/05_BulkActionsBrandAddresses.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/suppliers/01_CRUDSupplier.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/suppliers/02_filterQuickEditAndBulkActionsSupplier.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/06_files/01_CRUDFile.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/06_files/02_fileBulkActions.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/01_simpleFilterStocks.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/02_updateQuantity.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/03_bulkEditQuantity.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/04_filterStocksByStatus.js
Labels: 1.7.7.x, Refactoring, TE

#17582 Functional tests - Add context to customers, addresses and customer service tests
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/01_filterAndQuickEditCustomers.js
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/02_CRUDCustomerInBO.js
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/03_customersBulkActionsInBO.js
  tests/puppeteer/campaigns/functional/BO/04_customers/02_addresses/01_filterAddresses.js
  tests/puppeteer/campaigns/functional/BO/04_customers/02_addresses/02_CRUDAddressInBO.js
  tests/puppeteer/campaigns/functional/BO/04_customers/02_addresses/03_addressesBulkActions.js
  tests/puppeteer/campaigns/functional/BO/05_customerService/02_orderMessages/01_CRUDOrderMessage.js
  tests/puppeteer/campaigns/functional/BO/05_customerService/02_orderMessages/02_filterAndBulkDeleteOrderMessages.js
Labels: 1.7.7.x, Refactoring, TE

#17567 Functional tests - Add context to international tests
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/currencies/01_CreateOfficialCurrency.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/currencies/02_CreateUnofficialCurrency.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/languages/01_filterLanguages.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/languages/02_CRUDLanguage.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/languages/03_bulkActionsLanguages.js
  tests/puppeteer/campaigns/functional/BO/11_international/03_taxes/01_filterAndQuickEditTaxes.js
  tests/puppeteer/campaigns/functional/BO/11_international/03_taxes/02_CRUDTaxesInBO.js
  tests/puppeteer/campaigns/functional/BO/11_international/03_taxes/03_taxesBulkActionsInBO.js
  tests/puppeteer/campaigns/functional/BO/11_international/03_taxes/04_taxOptionsForm.js
Labels: 1.7.7.x, Refactoring, TE

#17543 Functional tests - Add context for shop params tests
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/01_general/maintenance/01_enableDisableShop.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_enableDisableCatalogMode.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/05_contact/01_filterContacts.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/05_contact/02_CRUDContact.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/05_contact/03_contactBulkActions.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/seoAndUrls/01_filterSeoPages.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/seoAndUrls/02_CRUDSeoPage.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/seoAndUrls/03_enableDisableFriendlyURL.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/seoAndUrls/04_enableDisableAccentedURL.js
Labels: 1.7.7.x, Refactoring, TE

#17534 Functional tests - Add context for advanced params tests
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/employees/01_filterAndQuickEditEmployees.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/employees/02_CRUDEmployee.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/employees/03_employeesBulkActions.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/profiles/01_filterProfiles.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/profiles/02_CRUDProfile.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/profiles/03_profileBulkActions.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/07_database/dbBackup/01_CreateAndDeleteDbBackup.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/07_database/dbBackup/02_bulkDeleteDbBackups.js
Labels: 1.7.7.x, Refactoring, TE

#17530 Functional tests - Add context to functional tests (Modules And Design)
  tests/puppeteer/campaigns/functional/BO/07_modules/01_moduleManager/01_filterModulesByStatus.js
  tests/puppeteer/campaigns/functional/BO/07_modules/01_moduleManager/02_filterModulesByCategories.js
  tests/puppeteer/campaigns/functional/BO/08_design/03_emailThemes/01_previewEmailThemes.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/01_filterAndQuickEditPages.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/02_CRUDPageCategory.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/03_categoriesBulkActions.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/04_filterAndQuickEditCategories.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/05_pagesBulkActions.js
  tests/puppeteer/campaigns/functional/BO/08_design/07_linkWidget/01_CreateAndCheckFooterLinkWidget.js
Labels: 1.7.7.x, Refactoring, TE

#17677 Reintroduce hook displayAdditionalCustomerAddressFields
  install-dev/data/xml/hook.xml
  themes/classic/templates/customer/_partials/block-address.tpl
Labels: 1.7.7.x, Bug

#17664 Disallow birth year in two digits
  classes/Validate.php
  tests-legacy/Unit/Classes/ValidateCoreTest.php
Labels: Bug, QA ✔️, develop

#17641 Fixed Exception for not defined variables when editing a product quantity in an order
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
Labels: 1.7.7.x, Bug, QA ✔️, migration

#17693 Functional tests - Add test 'Sort languages'
  tests/puppeteer/.eslintrc.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/languages/04_sortLanguages.js
  tests/puppeteer/pages/BO/international/languages/index.js
  tests/puppeteer/pages/commonPage.js
Labels: 1.7.7.x, Refactoring, TE

#17633 Cart object is undefined after refreshing the cart
  themes/_core/js/cart.js
  themes/classic/_dev/js/cart.js
Labels: Bug, QA ✔️, develop

#17640 Functional tests - Customer settings enable/disable re-display cart at login
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/01_enableDisableRedisplayCartAtLogin.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/shopParameters/customerSettings/index.js
  tests/puppeteer/pages/FO/FObasePage.js
  tests/puppeteer/pages/FO/home.js
Labels: 1.7.7.x, Refactoring, TE

#17605 Functional tests - Product settings enable/disable default activation status
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/06_enableDisableDefaultActivationStatus.js
  tests/puppeteer/pages/BO/catalog/products/add.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
  tests/puppeteer/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/index.js
Labels: 1.7.7.x, Refactoring, TE

#17708 Functional tests - Fix validation message selector name
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/international/taxes/taxRules/add.js
  tests/puppeteer/pages/BO/orders/view.js
  tests/puppeteer/pages/BO/shopParameters/customerSettings/index.js
  tests/puppeteer/pages/BO/shopParameters/general/maintenance/index.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
Labels: 1.7.7.x, Refactoring, TE

#17697 Functional tests - Add test 'Sort Taxes'
  tests/puppeteer/campaigns/functional/BO/11_international/03_taxes/05_sortTaxes.js
  tests/puppeteer/pages/BO/international/taxes/index.js
Labels: 1.7.7.x, Refactoring, TE

#17660 Migration of order view page printing functionality and layout changes - part 4
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js
  admin-dev/themes/new-theme/js/pages/order/view.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/_button.scss
  admin-dev/themes/new-theme/scss/components/_grid.scss
  admin-dev/themes/new-theme/scss/pages/_orders.scss
  admin-dev/themes/new-theme/scss/pages/_orders_view.scss
  admin-dev/themes/new-theme/scss/theme.scss
  admin-dev/themes/new-theme/template/components/layout/nav_bar.tpl
  admin-dev/themes/new-theme/template/layout.tpl
  admin-dev/themes/new-theme/template/page_header_toolbar.tpl
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/details.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/details_card.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/documents.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/history.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/messages.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/order_actions.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/payments.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/print_order_statistics.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/print_title.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/shipping.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig
  src/PrestaShopBundle/Resources/views/Admin/layout.html.twig
Labels: 1.7.7.x, Feature, QA ✔️

#17714 Functional tests - Fix Sort tests
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/languages/04_sortLanguages.js
  tests/puppeteer/campaigns/functional/BO/11_international/03_taxes/05_sortTaxes.js
Labels: 1.7.7.x, Refactoring, TE

#17715 Fix print css
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/pages/_orders_view.scss
Labels: 1.7.7.x, Refactoring

#17607 Add displayBanner hook
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.8.0.sql
Labels: Bug, QA ✔️, develop

#17730 Merge 1.7.6.x into 1.7.7.x - 19/02/2020
  classes/Mail.php
  src/Adapter/Grid/Action/Row/AccessibilityChecker/CategoryForViewAccessibilityChecker.php
Labels: Improvement, develop

#17710 Functional tests - Add movement check after update stocks quantity
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/02_updateQuantity.js
  tests/puppeteer/pages/BO/catalog/stocks/index.js
  tests/puppeteer/pages/BO/catalog/stocks/movements/index.js
Labels: 1.7.7.x, Refactoring, TE

#17720 Functional tests - Add test 'Sort products'
  tests/puppeteer/campaigns/functional/BO/03_catalog/01_products/01_filterAndQuickEditProducts.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/01_products/02_sortProducts.js
  tests/puppeteer/pages/BO/catalog/products/index.js
Labels: 1.7.7.x, Refactoring, TE

#17724 Functional tests - Add test 'Sort brands and addresses'
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/06_sortBrandsAndAddresses.js
  tests/puppeteer/pages/BO/catalog/brands/index.js
Labels: 1.7.7.x, Refactoring, TE

#17722 Functional tests - Product settings Enable/Disable display available quantities
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/01_enableDisableCatalogMode.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/02_newDaysNumber.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/03_maxSizeShortDescription.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/05_enableDisableForceUpdateFriendlyURL.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/06_enableDisableDefaultActivationStatus.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/01_enableDisableDisplayAvailableQuantities.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
  tests/puppeteer/pages/FO/product.js
Labels: 1.7.7.x, Refactoring, TE

#17731 Fix license headers
  src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php
  src/Core/Domain/Order/Command/CancelOrderProductCommand.php
  src/Core/Domain/Order/CommandHandler/CancelOrderProductHandlerInterface.php
  src/Core/Domain/Order/Exception/InvalidCancelProductException.php
  src/Core/Form/IdentifiableObject/DataHandler/CancellationFormDataHandler.php
  src/PrestaShopBundle/Form/Admin/Extension/RowAttributesExtension.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/details_card.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/print_order_statistics.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/print_title.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: 1.7.7.x, Improvement

#17220 Fix multiple bugs in order view page
  admin-dev/themes/new-theme/js/pages/order/view/order-product-edit.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js
  admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Core/Domain/Order/QueryResult/OrderProductForViewing.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/AddOrderCartRuleType.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/add_order_discount_modal.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️, migration

#17735 Functional tests - Adding wait for navigation in goToHomePage function
  tests/puppeteer/pages/FO/FObasePage.js
Labels: 1.7.7.x, Refactoring, TE

#16818 Force Configuration::updateValue to return a bool
  classes/Configuration.php
Labels: BC break, Bug fix, develop

#17757 Fix cancel product type translation domain
  src/PrestaShopBundle/Form/Admin/Sell/Order/CancelProductType.php
Labels: 1.7.7.x, Bug, Wording ✔️, waiting for wording

#17305 Adds optional DNI field and missing post_code handling in supplier form
  src/Adapter/Supplier/CommandHandler/AddSupplierHandler.php
  src/Adapter/Supplier/CommandHandler/EditSupplierHandler.php
  src/Adapter/Supplier/QueryHandler/GetSupplierForEditingHandler.php
  src/Core/Domain/Supplier/Command/AddSupplierCommand.php
  src/Core/Domain/Supplier/Command/EditSupplierCommand.php
  src/Core/Domain/Supplier/Query/GetSupplierForEditing.php
  src/Core/Domain/Supplier/QueryResult/EditableSupplier.php
  src/Core/Form/IdentifiableObject/DataHandler/SupplierFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/SupplierFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Sell/Supplier/SupplierType.php
Labels: 1.7.7.x, Bug, PM ✔️, QA ✔️, migration

#17700 Wrong address update when changing the shipping adresse of an order
  admin-dev/themes/new-theme/js/pages/order/view.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
Labels: 1.7.7.x, Bug, QA ✔️, migration

#17733 Unwanted spaces in 1.7.7.0.sql file
  install-dev/upgrade/sql/1.7.7.0.sql
Labels: 1.7.7.x, Bug, QA ✔️

#17116 Unnecessary localhost string when using getRemoteAddr
  classes/controller/FrontController.php
Labels: Bug, develop

#17577 Prevent email enumeration
  src/Core/Crypto/Hashing.php
Labels: 1.7.7.x, Improvement, QA ✔️

#17568 Order price font size
  admin-dev/themes/default/template/helpers/list/list_content.tpl
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/_grid.scss
  classes/Tools.php
  install-dev/data/xml/order_state.xml
  src/Core/Domain/Order/Status/OrderStatusColor.php
  src/Core/Util/ColorBrightnessCalculator.php
Labels: 1.7.7.x, Improvement, QA ✔️, migration

#17497 Increase bo cookie lifetime from 15 to 60 minutes
  classes/controller/AdminController.php
Labels: Bug, QA ✔️, develop

#17645 Backport #16927
  localization/ba.xml
  localization/bd.xml
  localization/cm.xml
  localization/mg.xml
  localization/sn.xml
Labels: 1.7.7.x, Feature, QA ✔️

#17528 Fix all 1.7.7.x controllers and routes to comply with conventions
  src/Core/Grid/Definition/Factory/AttachmentGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/CreditSlipGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/Monitoring/AbstractProductGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/Monitoring/DisabledProductGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/Monitoring/EmptyCategoryGridDefinitionFactory.php
  src/PrestaShopBundle/Command/NamingConventionLinterCommand.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/AttachmentController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/MonitoringController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/attachment.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/monitoring.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/credit_slips.yml
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/EmptyState/attachment.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Attachment/Blocks/form.html.twig
  src/PrestaShopBundle/Routing/Linter/Exception/NamingConventionException.php
  src/PrestaShopBundle/Routing/Linter/NamingConventionLinter.php
  tests-legacy/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
  tests/Integration/PrestaShopBundle/Routing/Converter/LegacyUrlConverterTest.php
Labels: 1.7.7.x, QA ✔️, Refactoring, Wording ✔️, migration

#17702 Order Page: Keep email failure from blocking product cancellation (and some refactor)
  src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php
  src/Adapter/Order/Refund/OrderProductRemover.php
  src/Core/Domain/Order/Exception/DeleteCustomizedProductFromOrderException.php
  src/Core/Domain/Order/Exception/DeleteProductFromOrderException.php
  src/PrestaShopBundle/Resources/config/services/adapter/order.yml
Labels: 1.7.7.x, Improvement, QA ✔️, migration

#17741 Functional tests - Add test 'Sort contacts'
  tests/puppeteer/campaigns/functional/BO/03_catalog/01_products/02_sortProducts.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/06_sortBrandsAndAddresses.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/languages/04_sortLanguages.js
  tests/puppeteer/campaigns/functional/BO/11_international/03_taxes/05_sortTaxes.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/05_contact/04_sortContacts.js
  tests/puppeteer/pages/BO/shopParameters/contact/index.js
Labels: 1.7.7.x, Refactoring, TE

#17756 Functional tests - Add test 'Sort customers'
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/04_sortCustomers.js
  tests/puppeteer/pages/BO/customers/index.js
Labels: 1.7.7.x, Refactoring, TE

#17638 Prevent email enumeration
  src/Core/Crypto/Hashing.php
Labels: 1.7.6.x, Improvement, QA ✔️

#16616 Fix round remaining value of reduction amount (backport #16531)
  classes/PaymentModule.php
Labels: 1.7.6.x, Bug, QA ✔️

#17613 Files translations.css and product_page.css do not exist
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/product.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Translations/overview.html.twig
Labels: 1.7.6.x, Bug, QA ✔️

#17738 Simplify mathematical operation in StockAvailable::setQuantity()
  classes/stock/StockAvailable.php
Labels: Refactoring, develop

#17763 Update catalog for 1.7.7.0
  app/Resources/translations/default/AdminActions.xlf
  app/Resources/translations/default/AdminAdvparametersFeature.xlf
  app/Resources/translations/default/AdminAdvparametersHelp.xlf
  app/Resources/translations/default/AdminAdvparametersNotification.xlf
  app/Resources/translations/default/AdminCatalogFeature.xlf
  app/Resources/translations/default/AdminCatalogHelp.xlf
  app/Resources/translations/default/AdminCatalogNotification.xlf
  app/Resources/translations/default/AdminDesignFeature.xlf
  app/Resources/translations/default/AdminDesignHelp.xlf
  app/Resources/translations/default/AdminDesignNotification.xlf
  app/Resources/translations/default/AdminGlobal.xlf
  app/Resources/translations/default/AdminInternationalFeature.xlf
  app/Resources/translations/default/AdminInternationalHelp.xlf
  app/Resources/translations/default/AdminInternationalNotification.xlf
  app/Resources/translations/default/AdminLoginNotification.xlf
  app/Resources/translations/default/AdminModulesFeature.xlf
  app/Resources/translations/default/AdminModulesNotification.xlf
  app/Resources/translations/default/AdminNavigationHeader.xlf
  app/Resources/translations/default/AdminNavigationMenu.xlf
  app/Resources/translations/default/AdminNavigationNotification.xlf
  app/Resources/translations/default/AdminNavigationSearch.xlf
  app/Resources/translations/default/AdminNotificationsError.xlf
  app/Resources/translations/default/AdminNotificationsSuccess.xlf
  app/Resources/translations/default/AdminNotificationsWarning.xlf
  app/Resources/translations/default/AdminOrderscustomersFeature.xlf
  app/Resources/translations/default/AdminOrderscustomersHelp.xlf
  app/Resources/translations/default/AdminOrderscustomersNotification.xlf
  app/Resources/translations/default/AdminPaymentNotification.xlf
  app/Resources/translations/default/AdminShippingFeature.xlf
  app/Resources/translations/default/AdminShopparametersFeature.xlf
  app/Resources/translations/default/AdminShopparametersHelp.xlf
  app/Resources/translations/default/AdminShopparametersNotification.xlf
  app/Resources/translations/default/EmailsBody.xlf
  app/Resources/translations/default/EmailsSubject.xlf
  app/Resources/translations/default/Install.xlf
  app/Resources/translations/default/ModulesBlockreassuranceAdmin.xlf
  app/Resources/translations/default/ModulesBlockreassuranceShop.xlf
  app/Resources/translations/default/ModulesContactinfoAdmin.xlf
  app/Resources/translations/default/ModulesCrosssellingAdmin.xlf
  app/Resources/translations/default/ModulesCrosssellingShop.xlf
  app/Resources/translations/default/ModulesDashactivityAdmin.xlf
  app/Resources/translations/default/ModulesDataprivacyAdmin.xlf
  app/Resources/translations/default/ModulesDataprivacyShop.xlf
  app/Resources/translations/default/ModulesEmailsubscriptionAdmin.xlf
  app/Resources/translations/default/ModulesEmailsubscriptionShop.xlf
  app/Resources/translations/default/ModulesFacetedsearchAdmin.xlf
  app/Resources/translations/default/ModulesFacetedsearchShop.xlf
  app/Resources/translations/default/ModulesMailalertsAdmin.xlf
  app/Resources/translations/default/ModulesShoppingcartAdmin.xlf
  app/Resources/translations/default/ShopFormsErrors.xlf
  app/Resources/translations/default/ShopFormsHelp.xlf
  app/Resources/translations/default/ShopFormsLabels.xlf
  app/Resources/translations/default/ShopNotificationsError.xlf
  app/Resources/translations/default/ShopNotificationsWarning.xlf
  app/Resources/translations/default/ShopThemeActions.xlf
  app/Resources/translations/default/ShopThemeCatalog.xlf
  app/Resources/translations/default/ShopThemeCheckout.xlf
  app/Resources/translations/default/ShopThemeCustomeraccount.xlf
  app/Resources/translations/default/ShopThemeGlobal.xlf
  app/Resources/translations/default/messages.xlf
Labels: 1.7.7.x, Feature, Wording ✔️

#17796 Fix new wording without domain
  admin-dev/themes/default/template/controllers/suppliers/helpers/view/view.tpl
Labels: 1.7.7.x, Bug, Wording ✔️

#17762 Functional tests - Add test 'Import localization pack'
  tests/puppeteer/campaigns/data/demo/currencies.js
  tests/puppeteer/campaigns/data/demo/languages.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/01_importLocalizationPack.js
  tests/puppeteer/pages/BO/international/localization/index.js
  tests/puppeteer/pages/commonPage.js
Labels: 1.7.7.x, Refactoring, TE

#17775 Functional tests - Customer settings enable/disable send email after registration
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/02_enableDisableSendEmailAfterRegistration.js
  tests/puppeteer/package-lock.json
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/advancedParameters/email/index.js
  tests/puppeteer/pages/BO/shopParameters/customerSettings/index.js
  tests/puppeteer/pages/FO/login.js
Labels: 1.7.7.x, Refactoring, TE

#17772 Functional tests - Add test 'Sort Addresses'
  tests/puppeteer/campaigns/functional/BO/04_customers/02_addresses/04_sortAddresses.js
  tests/puppeteer/pages/BO/customers/addresses/index.js
Labels: 1.7.7.x, Refactoring, TE

#17824 Functional tests - Fix sending emails in nightly
  tests/puppeteer/.docker/prestashop/Dockerfile
Labels: 1.7.7.x, Refactoring, TE

#17779 Functional tests - Add new tests 'Sort categories' and 'Change category position'
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/04_changeCategoryPosition.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/05_sortCategories.js
  tests/puppeteer/pages/BO/catalog/categories/index.js
  tests/puppeteer/pages/commonPage.js
Labels: 1.7.7.x, Refactoring, TE

#17746 Restore GA for PHP CS Fixer
  .github/workflows/php.yml
Labels: 1.7.7.x, Bug

#17828 Functional tests - Shop Parameters> General enable/disable display suppliers
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/01_general/general/08_enableDisableSuppliers.js
  tests/puppeteer/pages/BO/catalog/suppliers/index.js
  tests/puppeteer/pages/BO/shopParameters/general/index.js
  tests/puppeteer/pages/FO/FObasePage.js
  tests/puppeteer/pages/FO/siteMap.js
Labels: 1.7.7.x, Refactoring, TE

#17754 Functional tests - Product settings display remaining quantity in product page
  tests/puppeteer/campaigns/data/faker/product.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/02_displayRemainingQuantities.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
  tests/puppeteer/pages/FO/home.js
  tests/puppeteer/pages/FO/product.js
  tests/puppeteer/pages/FO/searchResults.js
Labels: 1.7.7.x, Refactoring, TE

#17829 Functional tests - Shop Parameters> General enable/disable display brands
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/01_general/general/09_enableDisableBrands.js
  tests/puppeteer/pages/BO/catalog/brands/index.js
  tests/puppeteer/pages/BO/shopParameters/general/index.js
  tests/puppeteer/pages/FO/siteMap.js
Labels: 1.7.7.x, Refactoring, TE

#17795 Functional tests - Payment>Preferences Configure currency restriction
  tests/puppeteer/campaigns/functional/BO/10_payment/02_preferences/01_currencyRestrictions.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/payment/preferences/index.js
  tests/puppeteer/pages/FO/checkout.js
Labels: 1.7.7.x, Refactoring, TE

#17841 Improve PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improvement, develop

#17836 Funtional tests - Fix employee faker
  tests/puppeteer/campaigns/data/faker/employee.js
Labels: 1.7.7.x, Refactoring, TE

#17872 Functional tests - Invoices > Other options - delete check legal free text from scenario
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/06_otherOptions.js
  tests/puppeteer/pages/BO/orders/invoices/index.js
Labels: 1.7.7.x, Refactoring, TE

#17785 Fix X-Forwarded-For not supported properly
  classes/Tools.php
Labels: Bug, develop

#17711 Fix a bug on safari where SEO preview on create page was not updated
  admin-dev/themes/new-theme/js/pages/cms-page/form/index.js
  admin-dev/themes/new-theme/public/cms_page_form.bundle.js
Labels: 1.7.6.x, Bug, QA ✔️

#17840 Improve issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Improvement, develop

#17699 Functional Tests - Product settings choose quantity discounts based on
  tests/puppeteer/campaigns/data/faker/product.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/04_quantityDiscountsBasedOn.js
  tests/puppeteer/pages/BO/catalog/products/add.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
  tests/puppeteer/pages/FO/FObasePage.js
  tests/puppeteer/pages/FO/cart.js
  tests/puppeteer/pages/FO/product.js
Labels: 1.7.7.x, Refactoring, TE

#17884 Use constant for reduction type in CatalogPriceRuleGridDataFactory
  src/Core/Grid/Data/Factory/CatalogPriceRuleGridDataFactory.php
Labels: 1.7.7.x, Bug, migration

#17846 Fix exception thrown when editing a customer with a bad email address
  src/Core/Domain/Customer/ValueObject/Email.php
  src/Core/Domain/ValueObject/Email.php
Labels: 1.7.6.x, Bug, QA ✔️
