Repository PrestaShop/PrestaShop, pull requests merged in 2020-11, with the labels that each got.

#21699 Remove useless comments
  controllers/admin/AdminDashboardController.php
Labels: Improvement, develop

#21456 Fixed sort for column ID Order in Shopping Carts Grid
  classes/controller/AdminController.php
  controllers/admin/AdminCartsController.php
Labels: Bug, QA ✔️, develop

#21691 Fix typo in Customer class
  classes/Customer.php
  classes/Employee.php
Labels: Documentation, Improvement, develop

#21709 Add test 'Update default country'
  tests/UI/campaigns/functional/BO/11_international/01_localization/04_defaultCurrency.js
  tests/UI/campaigns/functional/BO/11_international/01_localization/05_defaultCountry.js
  tests/UI/pages/BO/customers/addresses/add.js
  tests/UI/pages/BO/international/localization/index.js
Labels: Refactoring, TE, develop

#21669 Add test 'View raw html and text' in email themes page
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/MailTheme/Blocks/list_mail_theme_layouts.html.twig
  tests/UI/campaigns/functional/BO/08_design/03_emailThemes/03_viewRawHtmlAndText.js
  tests/UI/pages/BO/design/emailThemes/preview.js
Labels: QA ✔️, Refactoring, TE, develop

#21528 Add test 'CRUD order return status'
  tests/UI/campaigns/data/faker/orderReturnStatus.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/01_CRUDOrderStatus.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/02_filterSortAndPaginationOrderStatus.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/03_CRUDOrderReturnStatus.js
  tests/UI/pages/BO/shopParameters/orderSettings/statuses/index.js
  tests/UI/pages/BO/shopParameters/orderSettings/statuses/returnStatus/add.js
Labels: QA ✔️, Refactoring, TE, develop

#21666 Recompute price tax excluded only when the price is different from catalog
  src/Adapter/Order/AbstractOrderHandler.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_french_tax.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_odd_tax.feature
Labels: 1.7.7.x, Bug, QA ✔️

#21636 Add test 'CRUD tag'
  tests/UI/campaigns/data/faker/tag.js
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/02_tags/01_CRUDTag.js
  tests/UI/package-lock.json
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/shopParameters/search/index.js
  tests/UI/pages/BO/shopParameters/search/tags/add.js
  tests/UI/pages/BO/shopParameters/search/tags/index.js
Labels: QA ✔️, Refactoring, TE, develop

#21726 Fix nightly (03-11-2020) 'Sort shopping cart table by order ID'
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/02_sortAndPagination.js
Labels: Refactoring, TE, develop

#21728 Changelog v1.7.7.0
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: 1.7.7.x, Feature, WIP

#21674 Set jquery colorpicker option only if it is needed and loaded
  admin-dev/themes/default/template/helpers/options/options.tpl
  classes/helper/HelperOptions.php
Labels: Bug, QA ✔️, develop

#21557 Fix product pagination when adding a product in an empty order
  admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js
  admin-dev/themes/new-theme/public/currency_form.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
Labels: 1.7.7.x, Bug, QA ✔️

#21321 Introduce ProductCategoryUpdater and use it in handlers. Remove AbstractProductCategoryHandler
  src/Adapter/Product/AbstractProductCategoriesAssociationHandler.php
  src/Adapter/Product/CommandHandler/RemoveAllAssociatedProductCategoriesHandler.php
  src/Adapter/Product/CommandHandler/SetAssociatedProductCategoriesHandler.php
  src/Adapter/Product/Update/ProductCategoryUpdater.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
Labels: Refactoring, develop, migration

#21153 Removed mention tax in invoice when Tax is disabled
  classes/pdf/HTMLTemplateInvoice.php
  pdf/invoice.product-tab.tpl
  pdf/invoice.tax-tab.tpl
  pdf/invoice.total-tab.tpl
Labels: Improvement, QA ✔️, develop

#21526 Improved Error message in New Order Page when adding a minimal product
  src/Adapter/Cart/CommandHandler/UpdateProductQuantityInCartHandler.php
  src/Core/Domain/Cart/Exception/MinimalQuantityException.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php
  tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Adding/Product/add_standard_product.feature
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️

#20675 Always pass an instance to the actionCartSave hook
  classes/Cart.php
Labels: Bug, QA ✔️, develop

#21651 Change product unit price color to brand primary
  themes/classic/_dev/css/components/products.scss
Labels: Improvement, QA ✔️, develop

#21673 Fix checkbox going over label on multishop add shop
  admin-dev/themes/default/sass/partials/_commons.sass
  admin-dev/themes/default/template/controllers/shop/helpers/form/form.tpl
Labels: Bug, QA ✔️, develop

#18179 Fixed Sort by price in FO with specific price
  classes/Category.php
  classes/Manufacturer.php
  classes/Product.php
  classes/Search.php
  classes/Supplier.php
Labels: Bug, QA ✔️, develop

#21583 Payment > Preferences - Update message in all shops or in a group context
  src/PrestaShopBundle/Resources/views/Admin/Improve/Payment/Preferences/payment_preferences.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop

#21738 Add test 'Sort and pagination webservice keys'
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/04_sortAndPagination.js
  tests/UI/pages/BO/advancedParameters/webservice/index.js
Labels: QA ✔️, Refactoring, TE, develop

#21735 Add test 'Filter sort and pagination SQL queries'
  tests/UI/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/04_filterSortAndPagination.js
  tests/UI/pages/BO/advancedParameters/database/sqlManager/index.js
Labels: QA ✔️, Refactoring, TE, develop

#21660 Add test 'Update default carrier'
  src/PrestaShopBundle/Resources/views/Admin/Improve/Shipping/Preferences/Blocks/shipping_preferences_carrier_options.html.twig
  tests/UI/campaigns/data/demo/carriers.js
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/02_filterSortAndPagination.js
  tests/UI/campaigns/functional/BO/09_shipping/02_preferences/02_carrierOptions/01_defaultCarrier.js
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/shipping/preferences/index.js
  tests/UI/pages/FO/checkout/index.js
Labels: QA ✔️, Refactoring, TE, develop

#21635 Delete generating images inside the pages
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/02_CRUDCategoryInBO.js
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/03_categoriesBulkAction.js
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/05_paginationAndSortCategories.js
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/08_editHomeCategory.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/01_deleteEmptyCategory.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/04_sortListOfEmptyCategories.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/03_CRUDBrandAndAddress.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/04_BulkActionsBrands.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/06_paginationAndSortBrandsAndAddresses.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/suppliers/01_CRUDSupplier.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/suppliers/02_filterQuickEditAndBulkActionsSupplier.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/suppliers/04_paginationAndSortSuppliers.js
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/01_CRUDCarrier.js
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/02_filterSortAndPagination.js
  tests/UI/campaigns/functional/BO/11_international/01_localization/languages/02_CRUDLanguage.js
  tests/UI/campaigns/functional/BO/11_international/01_localization/languages/03_bulkActionsLanguages.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/01_CRUDOrderStatus.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/02_filterSortAndPaginationOrderStatus.js
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/03_titles/02_CRUDTitles.js
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/03_titles/03_bulkDeleteTitles.js
  tests/UI/campaigns/utils/files.js
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/catalog/brands/add.js
  tests/UI/pages/BO/catalog/categories/add.js
  tests/UI/pages/BO/catalog/suppliers/add.js
  tests/UI/pages/BO/international/languages/add.js
  tests/UI/pages/BO/shipping/carriers/add.js
  tests/UI/pages/BO/shopParameters/customerSettings/titles/add.js
  tests/UI/pages/BO/shopParameters/orderSettings/statuses/add.js
  tests/UI/pages/commonPage.js
Labels: QA ✔️, Refactoring, TE, develop

#21590 Fix selectors for design tests
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Cms/Blocks/listing_panel_footer.html.twig
  tests/UI/pages/BO/design/linkWidgets/index.js
  tests/UI/pages/BO/design/pages/add.js
  tests/UI/pages/BO/design/pages/index.js
  tests/UI/pages/BO/design/pages/pageCategory/add.js
Labels: QA ✔️, Refactoring, TE, develop

#21471 Add EventEmitter to prestashop global js object
  admin-dev/themes/new-theme/js/app/utils/init-components.js
Labels: Improvement, QA ✔️, develop

#21617 Show gift package and message on every details tabs of order view
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/details.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/shipping.html.twig
Labels: Bug, QA ✔️, Wording ✔️, develop

#21620 Fix categorytree not showing on mobile when mobile is enabled
  themes/classic/modules/ps_categorytree/views/templates/hook/ps_categorytree.tpl
Labels: BC break, Bug, QA ✔️, develop

#21643 Fix td alignment of merchandise return filters
  admin-dev/themes/default/sass/controllers/_order.sass
Labels: Bug, QA ✔️, develop

#21013 Fix message on Module Manager when post_max_size limitation is reached
  src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php
Labels: Bug, QA ✔️, develop

#21755 Trim string generated for tax rule group to avoid filter fail
  tests/UI/campaigns/data/faker/taxRuleGroup.js
Labels: Refactoring, TE, develop

#21758 Replace I Need Help issue template by external link
  .github/ISSUE_TEMPLATE/3_support_question.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: Improvement, develop

#21765 Generating images inside carrier test and fix checking number of sql queries after filter
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/03_quickEditAndBulkActions.js
  tests/UI/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/04_filterSortAndPagination.js
Labels: Refactoring, TE, develop

#21769 Fix GH issue chooser
  .github/ISSUE_TEMPLATE/config.yml
Labels: Bug, Improvement, develop

#21141 Changed the naming for attributes in product list
  classes/Cart.php
  classes/order/OrderDetail.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#21062 Make locale errors from translatable type work with locale
  src/PrestaShopBundle/Form/Admin/Type/TranslatableType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
  src/PrestaShopBundle/Resources/views/Admin/macros.html.twig
Labels: BC break, QA ✔️, Refactoring, develop, migration

#21733 Add test 'Create simple order in BO'
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/summary.html.twig
  tests/UI/campaigns/data/demo/carriers.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/03_createSimpleOrderInBO.js
  tests/UI/pages/BO/orders/add.js
  tests/UI/pages/BO/orders/view.js
  tests/UI/pages/FO/cart/index.js
  tests/UI/pages/commonPage.js
Labels: QA ✔️, Refactoring, TE, develop

#21756 Add test 'Filter sort and pagination tags'
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/02_tags/02_filterSortAndPagination.js
  tests/UI/pages/BO/shopParameters/search/tags/index.js
Labels: QA ✔️, Refactoring, TE, develop

#21746 Add test 'Enable/Disable' webservice keys by bulk actions
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/04_sortPaginationAndBulkActions.js
  tests/UI/pages/BO/advancedParameters/webservice/index.js
Labels: Refactoring, TE, develop

#21776 Made sure getErrorsByLocale doesn't return empty
  src/PrestaShopBundle/Form/Admin/Type/TranslatableType.php
Labels: Refactoring, develop

#21273 Wrong url in credit-slip e-mail
  classes/Mail.php
  mails/themes/modern/core/credit_slip.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop

#21777 remove composer.lock from the .gitignore file
  .gitignore
Labels: Improvement, develop

#21625 Don't trim arrays in AdminStoresController::postProcess : they delete it
  controllers/admin/AdminStoresController.php
Labels: Bug, QA ✔️, develop

#20606 Fix invoice address selection at checkout
  classes/checkout/CheckoutAddressesStep.php
  classes/controller/FrontController.php
  controllers/front/OrderController.php
Labels: BC break, Bug, Key feature, QA ✔️, develop

#21612 Add selected combinations value inside product page
  themes/classic/templates/catalog/_partials/product-variants.tpl
Labels: Improvement, QA ✔️, Wording ✔️, develop

#21244 Simplified carrier preferences
  controllers/admin/AdminLegacyLayoutController.php
  src/PrestaShopBundle/Controller/Admin/Improve/Shipping/PreferencesController.php
  src/PrestaShopBundle/Form/Admin/Improve/Shipping/Preferences/CarrierOptionsType.php
  src/PrestaShopBundle/Form/Admin/Improve/Shipping/Preferences/HandlingType.php
  src/PrestaShopBundle/Form/Admin/Improve/Shipping/Preferences/PreferencesHandlingFormDataProvider.php
  src/PrestaShopBundle/Resources/views/Admin/Improve/Shipping/Preferences/Blocks/shipping_preferences_carrier_options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Shipping/Preferences/Blocks/shipping_preferences_handling.html.twig
Labels: QA ✔️, Refactoring, develop, migration

#21672 Made switch type not required
  src/PrestaShopBundle/Form/Admin/Type/SwitchType.php
Labels: QA ✔️, Refactoring, develop, migration

#21375 Add override list to admin Information page
  src/Adapter/Shop/ShopInformation.php
  src/Adapter/System/SystemInformation.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/system_information.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop

#21789 Add filter and reset steps to cart rules tests
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/02_filterQuickEditAndBulkActionsCartRules.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/03_sortAndPaginationCartRule.js
  tests/UI/pages/BO/catalog/discounts/index.js
Labels: Refactoring, TE, develop

#21611 Add swipe on product images on mobile
  themes/classic/_dev/css/components/products.scss
  themes/classic/_dev/js/product.js
  themes/classic/_dev/js/selectors.js
Labels: Improvement, QA ✔️, develop

#21796 Improve attachment tests to check multiple languages
  tests/Integration/Behaviour/Features/Scenario/Attachment/attachment_management.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_attachments.feature
  tests/Integration/Behaviour/behat.yml
Labels: Refactoring, develop

#17253 UIKit improvements to prepare new version
  admin-dev/themes/new-theme/js/pages/module/controller.js
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
  admin-dev/themes/new-theme/scss/components/_grid.scss
  admin-dev/themes/new-theme/scss/components/_ps_dropdown.scss
  admin-dev/themes/new-theme/scss/pages/_modules.scss
  admin-dev/themes/new-theme/scss/pages/product/product_page.scss
  admin-dev/themes/new-theme/scss/pages/product/products_catalog.scss
  admin-dev/themes/new-theme/scss/theme.scss
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/action.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Common/HelpBox/helpbox.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/MailTheme/Blocks/list_mail_theme_layouts.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/dropdown_bulk.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/dropdown_categories.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/dropdown_categories_catalog.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/dropdown_status.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Forms/form_edit_dropdown.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Lists/list.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Panels/options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Manufacturer/Blocks/View/products.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop

#21814 FO: fix wrong redirection after address edition in checkout process
  classes/checkout/CheckoutAddressesStep.php
Labels: Bug, QA ✔️, develop

#21616 Do not use the cache when checking if data exists in the database (Part 1)
  classes/Address.php
  classes/Alias.php
  classes/CartRule.php
  classes/Category.php
  classes/Customer.php
  classes/Employee.php
  classes/ImageType.php
  classes/Manufacturer.php
  classes/Product.php
  classes/Store.php
  classes/Supplier.php
  classes/shop/ShopGroup.php
  classes/stock/Warehouse.php
Labels: Refactoring, develop

#21578 Added a new hook call "displayProductPriceBlock" with type "custom_price"
  themes/classic/templates/catalog/_partials/miniatures/product.tpl
  themes/classic/templates/catalog/_partials/product-prices.tpl
Labels: Feature, Hook, QA ✔️, develop

#21854 Fix tests after new UI kit version merged
  tests/UI/campaigns/functional/BO/03_catalog/01_products/01_filterAndQuickEditProducts.js
  tests/UI/campaigns/functional/BO/11_international/01_localization/02_defaultLanguage.js
  tests/UI/pages/BO/advancedParameters/email/index.js
  tests/UI/pages/BO/advancedParameters/team/add.js
  tests/UI/pages/BO/advancedParameters/webservice/add.js
  tests/UI/pages/BO/catalog/brands/add.js
  tests/UI/pages/BO/catalog/categories/add.js
  tests/UI/pages/BO/catalog/categories/index.js
  tests/UI/pages/BO/catalog/products/index.js
  tests/UI/pages/BO/catalog/suppliers/add.js
  tests/UI/pages/BO/customers/add.js
  tests/UI/pages/BO/design/pages/add.js
  tests/UI/pages/BO/design/pages/pageCategory/add.js
  tests/UI/pages/BO/international/currencies/add.js
  tests/UI/pages/BO/international/languages/add.js
  tests/UI/pages/BO/international/localization/index.js
  tests/UI/pages/BO/international/taxes/add.js
  tests/UI/pages/BO/international/taxes/index.js
  tests/UI/pages/BO/modules/moduleManager/index.js
  tests/UI/pages/BO/orders/add.js
  tests/UI/pages/BO/orders/deliverySlips/index.js
  tests/UI/pages/BO/orders/invoices/index.js
  tests/UI/pages/BO/shopParameters/contact/add.js
  tests/UI/pages/BO/shopParameters/customerSettings/index.js
  tests/UI/pages/BO/shopParameters/general/index.js
  tests/UI/pages/BO/shopParameters/general/maintenance/index.js
  tests/UI/pages/BO/shopParameters/orderSettings/index.js
  tests/UI/pages/BO/shopParameters/productSettings/index.js
  tests/UI/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/index.js
Labels: Refactoring, TE, develop

#21555 Fixed increment button when adding a product out of stock and with allow order
  admin-dev/themes/new-theme/js/pages/order/create/product-manager.js
  admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js
Labels: 1.7.7.x, Bug, QA ✔️

#21861 Add behat tests for UpdateProductStatusCommand [product page migration]
  tests/Integration/Behaviour/Features/Context/Domain/Product/CommonProductFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateStatusFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/add_product.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_attachments.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_status.feature
  tests/Integration/Behaviour/behat.yml
Labels: Refactoring, develop, migration

#21684 Fix customer addresses edit/delete redirection
  src/Core/Grid/Definition/Factory/CustomerAddressGridDefinitionFactory.php
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig
Labels: Bug, QA ✔️, develop

#21613 Fix webservice accessory xlink href
  classes/Product.php
Labels: Bug, QA ✔️, develop

#21830 Correctly generate cart error messages
  src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php
Labels: 1.7.7.x, Bug, QA ✔️

#21783 Get page title respecting dedicated meta title and combination information
  controllers/front/ProductController.php
Labels: Bug, QA ✔️, develop

#21883 Fixing phpstan errors after cart rules
  src/Core/Domain/CartRule/Command/ToggleCartRuleStatusCommand.php
  src/Core/Domain/CartRule/QueryResult/EditableCartRule.php
  src/Core/Domain/CartRule/QueryResult/EditableCartRuleMinimum.php
  src/Core/Domain/CartRule/QueryResult/EditableCartRuleReduction.php
  src/Core/Grid/Definition/Factory/CartRuleGridDefinitionFactory.php
  src/Core/Grid/Query/CartRuleQueryBuilder.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CartRuleController.php
Labels: Bug, develop

#21856 Adjust birthday inputs on create customer page
  admin-dev/themes/new-theme/scss/pages/_customer.scss
  admin-dev/themes/new-theme/scss/theme.scss
Labels: Bug, QA ✔️, develop

#21412 Add a new test "import file"
  tests/UI/campaigns/data/demo/customer.js
  tests/UI/campaigns/data/demo/sampleFiles.js
  tests/UI/campaigns/functional/BO/14_advancedParameters/05_import/02_importFile.js
  tests/UI/campaigns/utils/files.js
  tests/UI/pages/BO/advancedParameters/import/index.js
Labels: Refactoring, TE, develop

#21874 Fix TCPD::Output() method name call
  classes/pdf/PDFGenerator.php
Labels: Improvement, develop

#21289 Refactor admin notifications.js
  admin-dev/themes/default/template/header.tpl
  js/admin/notifications.js
Labels: QA ✔️, Refactoring, develop

#21853 Add missing use in CancelOrderProductHandler
  src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php
Labels: 1.7.7.x, Bug, migration

#21858 Add test 'Quick edit tax rules'
  tests/UI/campaigns/functional/BO/11_international/03_taxes/taxRules/03_quickEditAndBulkActions.js
  tests/UI/pages/BO/international/taxes/taxRules/index.js
Labels: Refactoring, TE, develop

#21690 Handle '+' sign in url when using 'back' parameter to redirect
  classes/controller/AdminController.php
  controllers/admin/AdminCartRulesController.php
  controllers/front/AuthController.php
  src/Core/Util/Url/BackUrlProvider.php
  src/PrestaShopBundle/EventListener/BackUrlRedirectResponseListener.php
Labels: Bug, QA ✔️, develop

#21816 Remove useless logic Product customization images in Order Page and handle exotic chars in name
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig
Labels: 1.7.7.x, Bug, QA ✔️

#21896 Fix dependency which is targeting the v1.3.0 instead of the 1.3 branch
  composer.json
  composer.lock
Labels: Bug, develop

#21822 Remove inline style from default datas
  install-dev/fixtures/fashion/langs/bn/data/product.xml
  install-dev/fixtures/fashion/langs/br/data/product.xml
  install-dev/fixtures/fashion/langs/de/data/product.xml
  install-dev/fixtures/fashion/langs/en/data/category.xml
  install-dev/fixtures/fashion/langs/en/data/manufacturer.xml
  install-dev/fixtures/fashion/langs/en/data/product.xml
  install-dev/fixtures/fashion/langs/es/data/product.xml
  install-dev/fixtures/fashion/langs/fa/data/category.xml
  install-dev/fixtures/fashion/langs/fa/data/manufacturer.xml
  install-dev/fixtures/fashion/langs/fa/data/product.xml
  install-dev/fixtures/fashion/langs/fr/data/category.xml
  install-dev/fixtures/fashion/langs/fr/data/manufacturer.xml
  install-dev/fixtures/fashion/langs/fr/data/product.xml
  install-dev/fixtures/fashion/langs/id/data/product.xml
  install-dev/fixtures/fashion/langs/it/data/product.xml
  install-dev/fixtures/fashion/langs/nl/data/product.xml
  install-dev/fixtures/fashion/langs/pl/data/product.xml
  install-dev/fixtures/fashion/langs/qc/data/product.xml
  install-dev/fixtures/fashion/langs/ro/data/product.xml
  install-dev/fixtures/fashion/langs/ru/data/product.xml
  install-dev/fixtures/fashion/langs/tw/data/product.xml
  install-dev/fixtures/fashion/langs/vn/data/product.xml
  install-dev/fixtures/fashion/langs/zh/data/product.xml
Labels: Improvement, QA ✔️, develop

#21576 No alert displayed when changing the status with bulk action in legacy controllers
  classes/controller/AdminController.php
  controllers/admin/AdminCarriersController.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#21732 Fixed `displayPackPrice` not defined to true due to a type comparision
  controllers/front/ProductController.php
Labels: Bug, QA ✔️, develop

#20565 Filter variations by qty at FO
  controllers/front/ProductController.php
Labels: Bug, QA ✔️, develop

#21907 Update README.md for UI tests
  tests/UI/README.md
  tests/UI/campaigns/data/demo/carriers.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/02_catalogPriceRules/02_filterSortAndPagination.js
  tests/UI/campaigns/utils/globals.js
  tests/UI/pages/install/index.js
Labels: Refactoring, TE, develop

#21928 Release 1.7.6.9
  .travis.yml
  app/AppKernel.php
  docs/CHANGELOG.txt
  install-dev/install_version.php
Labels: 1.7.6.x, Improvement

#21849 Fix alert of compromised page and center window
  admin-dev/themes/new-theme/scss/pages/_compromised.scss
  admin-dev/themes/new-theme/scss/theme.scss
  src/PrestaShopBundle/Resources/views/Admin/Security/compromised.html.twig
Labels: Bug, QA ✔️, UX ✔️, develop

#21892 Fix badges on customer page
  admin-dev/themes/new-theme/scss/pages/_customer.scss
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/personal_information.html.twig
Labels: Bug, QA ✔️, develop

#21443 Made it so order preferences uses the same form theme as all others simplified forms
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/OrderPreferences/Blocks/order_preferences_general.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/OrderPreferences/Blocks/order_preferences_gift_options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: QA ✔️, Refactoring, develop, migration

#20080 Add eslint to themes and classic folders
  .github/workflows/js-fo.yml
  themes/.eslintignore
  themes/.eslintrc.js
  themes/_core/js/address.js
  themes/_core/js/cart.js
  themes/_core/js/checkout-address.js
  themes/_core/js/checkout-delivery.js
  themes/_core/js/checkout-payment.js
  themes/_core/js/checkout-steps.js
  themes/_core/js/common.js
  themes/_core/js/facets.js
  themes/_core/js/listing.js
  themes/_core/js/migrate-mute.js
  themes/_core/js/product.js
  themes/_core/js/selectors.js
  themes/_core/js/theme.js
  themes/classic/_dev/.eslintignore
  themes/classic/_dev/.eslintrc.js
  themes/classic/_dev/js/cart.js
  themes/classic/_dev/js/checkout.js
  themes/classic/_dev/js/components/block-cart.js
  themes/classic/_dev/js/components/drop-down.js
  themes/classic/_dev/js/components/form.js
  themes/classic/_dev/js/components/product-miniature.js
  themes/classic/_dev/js/components/product-select.js
  themes/classic/_dev/js/components/top-menu.js
  themes/classic/_dev/js/customer.js
  themes/classic/_dev/js/listing.js
  themes/classic/_dev/js/product.js
  themes/classic/_dev/js/responsive.js
  themes/classic/_dev/js/theme.js
  themes/classic/_dev/package-lock.json
  themes/classic/_dev/package.json
  themes/classic/_dev/postcss.config.js
  themes/package-lock.json
  themes/package.json
  themes/webpack.config.js
Labels: Improvement, QA ✔️, develop

#21818 Improve feature wording in Product Settings page
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_page.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop

#21940 Merge 177x into develop 16/11/2020
  CONTRIBUTORS.md
  admin-dev/themes/new-theme/js/pages/order/create/product-manager.js
  admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js
  admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js
  app/Resources/translations/default/AdminNotificationsError.xlf
  app/Resources/translations/default/AdminOrderscustomersFeature.xlf
  app/Resources/translations/default/AdminOrderscustomersNotification.xlf
  app/Resources/translations/default/ModulesBlockreassuranceAdmin.xlf
  app/Resources/translations/default/ModulesCheckpaymentAdmin.xlf
  app/Resources/translations/default/ModulesCheckpaymentShop.xlf
  app/Resources/translations/default/ModulesDashtrendsAdmin.xlf
  app/Resources/translations/default/ModulesWelcomeAdmin.xlf
  docs/CHANGELOG.txt
  src/Adapter/Cart/CommandHandler/UpdateProductQuantityInCartHandler.php
  src/Adapter/Order/AbstractOrderHandler.php
  src/Core/Domain/Cart/Exception/MinimalQuantityException.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
  tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Adding/Product/add_standard_product.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_french_tax.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_odd_tax.feature
Labels: Improvement, develop

#21931 Remove special case of Product::toggleStatus
  classes/Product.php
Labels: Bug, QA ✔️, develop

#21425 Add autocomplete attributes on FO login form
  classes/form/CustomerLoginFormatter.php
  classes/form/FormField.php
  themes/classic/templates/_partials/form-fields.tpl
Labels: Bug, Improvement, QA ✔️, develop

#21956 Merge 1769 into 177x
  controllers/front/OrderController.php
  docs/CHANGELOG.txt
Labels: 1.7.7.x, Improvement

#21679 Simplify customer form
  admin-dev/themes/new-theme/scss/theme.scss
  src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php
  src/PrestaShopBundle/Form/Admin/Sell/Customer/TransferGuestAccountType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/Index/required_fields.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/personal_information.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/delete_modal.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: BC break, QA ✔️, Refactoring, Wording ✔️, develop, migration

#21957 Update latest native modules
  composer.lock
Labels: 1.7.7.x, Improvement

#21908 Strip_tags() error when having an array in the URL
  classes/controller/FrontController.php
Labels: Bug, QA ✔️, develop

#21725 Avoid global markup duplicate in checkout.tpl
  themes/classic/templates/checkout/_partials/footer.tpl
  themes/classic/templates/checkout/_partials/header.tpl
  themes/classic/templates/checkout/checkout.tpl
Labels: Improvement, QA ✔️, develop

#21934 Fix PHPDoc Tools::displayPrice()
  classes/Tools.php
Labels: Documentation, Improvement, develop

#21958 Block blank issues
  .github/ISSUE_TEMPLATE/config.yml
Labels: Improvement, develop

#21869 Add test 'CRUD search'
  tests/UI/campaigns/data/faker/search.js
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/01_search/01_CRUDSearch.js
  tests/UI/pages/BO/shopParameters/search/add.js
  tests/UI/pages/BO/shopParameters/search/index.js
Labels: QA ✔️, Refactoring, TE, develop

#21954 Add test "Pagination DB backup"
  tests/UI/campaigns/functional/BO/14_advancedParameters/07_database/dbBackup/02_paginationAndBulkDelete.js
  tests/UI/pages/BO/advancedParameters/database/dbBackup/index.js
Labels: Refactoring, TE, develop

#21955 Remove transformation traits from behats and implement contexts instead
  tests/Integration/Behaviour/Features/Context/Configuration/CommonConfigurationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateAttachmentFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateOptionsFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePackFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePricesFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateProductSuppliersFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateSeoFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateShippingFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateStatusFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateTagsFeatureContext.php
  tests/Integration/Behaviour/Features/Transform/CurrencyTransformContext.php
  tests/Integration/Behaviour/Features/Transform/SharedStorageTransformContext.php
  tests/Integration/Behaviour/Features/Transform/StringToArrayTransformContext.php
  tests/Integration/Behaviour/Features/Transform/StringToBoolTransformContext.php
  tests/Integration/Behaviour/behat.yml
Labels: Refactoring, develop, migration

#21953 Fix "column count doesn't match value count" error during upgrade
  install-dev/upgrade/sql/1.7.7.0.sql
Labels: 1.7.7.x, Bug, QA ✔️

#21779 Add test 'Filter sort and pagination order return status'
  tests/UI/campaigns/data/demo/orderReturnStatuses.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/returnStatuses/01_CRUDOrderReturnStatus.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/returnStatuses/02_filterSortAndPagination.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/statuses/01_CRUDOrderStatus.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/statuses/02_filterSortAndPagination.js
Labels: QA ✔️, Refactoring, TE, develop

#21959 Fix step identifier checker command name
  .github/workflows/ui-tests-code-checks.yml
  tests/UI/package.json
Labels: QA ✔️, Refactoring, TE, develop

#21973 Add test "CRUD multistore"
  tests/UI/campaigns/data/faker/shopGroup.js
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/01_CRUDShopGroups.js
  tests/UI/pages/BO/advancedParameters/multistore/add.js
  tests/UI/pages/BO/advancedParameters/multistore/index.js
Labels: Refactoring, TE, develop

#21960 Fix legacy form selectors
  admin-dev/themes/new-theme/js/pages/improve/design_positions/positions-list-handler.js
  admin-dev/themes/new-theme/js/pages/order-preferences/terms-and-conditions-option-handler.js
  admin-dev/themes/new-theme/js/pages/product-preferences/stock-management-option-handler.js
Labels: Bug, QA ✔️, develop

#21721 Handle Shop context override in order editing
  classes/order/Order.php
  classes/order/OrderDetail.php
  src/Adapter/Cart/CommandHandler/AddCartRuleToCartHandler.php
  src/Adapter/Cart/CommandHandler/UpdateCartCarrierHandler.php
  src/Adapter/Cart/CommandHandler/UpdateProductQuantityInCartHandler.php
  src/Adapter/Cart/QueryHandler/GetCartInformationHandler.php
  src/Adapter/ContextStateManager.php
  src/Adapter/Order/AbstractOrderHandler.php
  src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php
  src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php
  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
  src/Adapter/Order/CommandHandler/DeleteCartRuleFromOrderHandler.php
  src/Adapter/Order/CommandHandler/DeleteProductFromOrderHandler.php
  src/Adapter/Order/CommandHandler/DuplicateOrderCartHandler.php
  src/Adapter/Order/OrderAmountUpdater.php
  src/Adapter/Order/OrderProductQuantityUpdater.php
  src/Adapter/Product/QueryHandler/SearchProductsHandler.php
  tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_multi_shop.feature
  tests/Integration/Behaviour/bootstrap.php
  tests/Unit/Adapter/ContextStateManagerTest.php
Labels: 1.7.7.x, Bug, QA ✔️, migration

#21628 Stream downloaded file for HTTP/2
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SqlManagerController.php
Labels: Bug, QA ✔️, develop

#21984 Improve Link::getProductLink : Avoid short variable names
  classes/Link.php
Labels: Improvement, develop

#22001 Fix some typos in admin filemanager
  admin-dev/filemanager/config/config.php
  admin-dev/filemanager/dialog.php
Labels: Improvement, develop

#19776 Allow developers to use their own tinymce config
  js/admin/tinymce.inc.js
Labels: Improvement, QA ✔️, develop

#21855 Add missing SQL row for actionFrontControllerSetVariables hook
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.8.0.sql
Labels: Improvement, QA ✔️, develop

#21975 Correctly substring fields before update, remove duplicates and add missing sql queries
  install-dev/upgrade/sql/1.7.7.0.sql
Labels: 1.7.7.x, Bug, QA ✔️

#21994 Remove or cancel all products
  src/Adapter/Order/OrderAmountUpdater.php
  src/Adapter/Order/Refund/OrderProductRemover.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_cancel_product.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
Labels: 1.7.7.x, Bug, QA ✔️

#21947 Adjust modal position when wrong used with a form
  admin-dev/themes/new-theme/scss/components/_form.scss
Labels: Bug, QA ✔️, develop

#21985 Remove wrong div endblock on order page view after the 177 merge
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
Labels: Bug, QA ✔️, develop

#20809 Update to check Language association to the current store
  config/config.inc.php
Labels: Bug, QA ✔️, develop

#21981 Make sure favicon, stores_icon and logo are correctly settled for themes
  classes/controller/FrontController.php
  themes/classic/templates/_partials/head.tpl
  themes/classic/templates/_partials/header.tpl
  themes/classic/templates/checkout/_partials/header.tpl
  themes/classic/templates/errors/maintenance.tpl
  themes/classic/templates/errors/restricted-country.tpl
Labels: 1.7.7.x, Bug, QA ✔️

#21094 Fixed array parameter processing in Link::getCategoryObject method
  classes/Link.php
Labels: Bug, QA ✔️, develop

#21886 Fix radius on some custom components
  admin-dev/themes/new-theme/scss/config/_settings.scss
  admin-dev/themes/new-theme/scss/pages/orders/_orders_view.scss
  admin-dev/themes/new-theme/scss/pages/stock/stock_page.scss
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/history.html.twig
Labels: Bug, QA ✔️, develop

#21986 Add test "Disable multi store on CRUD shop group test"
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/01_CRUDShopGroups.js
Labels: QA ✔️, Refactoring, TE, develop

#21946 Add test "Sort and pagination emails table"
  tests/UI/campaigns/functional/BO/14_advancedParameters/04_email/03_sortAndPagination.js
  tests/UI/pages/BO/advancedParameters/email/index.js
Labels: QA ✔️, Refactoring, TE, develop

#22018 Order zero ratio for order detail tax
  classes/order/OrderDetail.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
Labels: 1.7.7.x, Bug, QA ✔️

#22054 Add test 'Erase all' emails
  tests/UI/campaigns/functional/BO/14_advancedParameters/04_email/03_sortAndPagination.js
  tests/UI/pages/BO/advancedParameters/email/index.js
Labels: QA ✔️, Refactoring, TE, develop

#22055 Delete spaces in the end of title name in faker for UI tests
  tests/UI/campaigns/data/faker/title.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#22013 Handle parallel updates from CartRules when updating a product in Order
  admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js
  admin-dev/themes/new-theme/public/currency_form.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  classes/Cart.php
  src/Adapter/Cart/Comparator/CartProductUpdate.php
  src/Adapter/Cart/Comparator/CartProductsComparator.php
  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
  src/Adapter/Order/OrderProductQuantityUpdater.php
  src/Adapter/Order/Refund/OrderProductRemover.php
  src/Core/Cart/CartRow.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature
  tests/Unit/Adapter/Cart/Comparator/CartProductsComparatorTest.php
Labels: 1.7.7.x, Bug, QA ✔️

#22063 Last translation updates
  app/Resources/translations/default/AdminAdvparametersNotification.xlf
  app/Resources/translations/default/AdminCatalogNotification.xlf
  app/Resources/translations/default/AdminDesignNotification.xlf
  app/Resources/translations/default/AdminNotificationsError.xlf
  app/Resources/translations/default/AdminNotificationsSuccess.xlf
  app/Resources/translations/default/AdminOrderscustomersFeature.xlf
  app/Resources/translations/default/AdminOrderscustomersNotification.xlf
  app/Resources/translations/default/EmailsSubject.xlf
  app/Resources/translations/default/ModulesProductcommentsAdmin.xlf
  app/Resources/translations/default/ModulesProductcommentsShop.xlf
  app/Resources/translations/default/ModulesStatsvisitsAdmin.xlf
  app/Resources/translations/default/ShopNotificationsError.xlf
  app/Resources/translations/default/ShopNotificationsWarning.xlf
  app/Resources/translations/default/ShopThemeCatalog.xlf
  app/Resources/translations/default/ShopThemeGlobal.xlf
Labels: 1.7.7.x, Improvement

#21345 Refactor UpdateProductSeoHandler to use ProductRepository
  src/Adapter/Category/Repository/CategoryRepository.php
  src/Adapter/Product/CommandHandler/UpdateProductSeoHandler.php
  src/Adapter/Product/Update/ProductSeoPropertiesFiller.php
  src/Adapter/Product/Validate/ProductValidator.php
  src/Core/Domain/Product/ValueObject/RedirectOption.php
  src/Core/Domain/Product/ValueObject/RedirectType.php
  src/PrestaShopBundle/Resources/config/services/adapter/category.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  tests/Integration/Behaviour/Features/Scenario/Product/update_seo.feature
  tests/Unit/Core/Domain/Product/ValueObject/RedirectOptionTest.php
  tests/Unit/Core/Domain/Product/ValueObject/RedirectTargetTest.php
  tests/Unit/Core/Domain/Product/ValueObject/RedirectTypeTest.php
Labels: Refactoring, develop, migration

#22090 Remove redundant customization field commands
  src/Core/Domain/Product/Customization/Command/AddCustomizationFieldCommand.php
  src/Core/Domain/Product/Customization/Command/DeleteCustomizationFieldCommand.php
  src/Core/Domain/Product/Customization/Command/UpdateCustomizationFieldCommand.php
Labels: Refactoring, develop, migration

#21993 Adjust behats localized fields assertion and add LocalizedArrayTransformContext
  tests/Integration/Behaviour/Features/Context/Domain/AbstractDomainFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/AttachmentFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CurrencyFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/AddProductFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/CommonProductFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateBasicInformationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateCustomizationFieldsFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateSeoFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateShippingFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateStockFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateTagsFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/SupplierFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Attachment/attachment_management.feature
  tests/Integration/Behaviour/Features/Scenario/Currency/currency_data.feature
  tests/Integration/Behaviour/Features/Scenario/Currency/currency_management.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_add_payment.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_currency.feature
  tests/Integration/Behaviour/Features/Scenario/Product/add_image.feature
  tests/Integration/Behaviour/Features/Scenario/Product/add_product.feature
  tests/Integration/Behaviour/Features/Scenario/Product/delete_product.feature
  tests/Integration/Behaviour/Features/Scenario/Product/duplicate_product.feature
  tests/Integration/Behaviour/Features/Scenario/Product/specific_price_priorities.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_attachments.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_basic_information.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_categories.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_customization_fields.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_options.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_pack.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_prices.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_related_products.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_seo.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_shipping.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_status.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_stock_advanced.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_stock_classic.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_suppliers.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_tags.feature
  tests/Integration/Behaviour/Features/Scenario/Supplier/supplier_management.feature
  tests/Integration/Behaviour/Features/Transform/LocalizedArrayTransformContext.php
  tests/Integration/Behaviour/behat.yml
Labels: Refactoring, develop, migration

#22087 Do not generate the data variable if it's not needed in PaymentModule
  classes/PaymentModule.php
Labels: Improvement, Wording ✔️, develop

#21582 Mark parameter deprecated for a future version
  classes/Product.php
Labels: Improvement, QA ✔️, develop

#22130 Fix dependency which is targeting the v1.3.0 instead of the 1.3 branch
  composer.json
  composer.lock
Labels: 1.7.7.x, Bug, QA ✔️

#22027 Remove duplicate id on product-list-bottom
  themes/classic/templates/catalog/listing/product-list.tpl
Labels: Bug, QA ✔️, develop

#22019 Add test 'Search bulk actions'
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/01_search/02_bulkActions.js
  tests/UI/pages/BO/shopParameters/search/index.js
Labels: QA ✔️, Refactoring, TE, develop

#22061 Add select2 to the import localization select
  src/PrestaShopBundle/Form/Admin/Improve/International/Localization/ImportLocalizationPackType.php
Labels: Bug, QA ✔️, develop

#22146 Remove --classmap-authoritative when building release
  tools/build/Library/ReleaseCreator.php
Labels: 1.7.7.x, Bug, waiting for QA
