Repository PrestaShop/PrestaShop, pull requests merged in 2020-04, with the labels that each got.

#18373 Avoid date time split in Grids
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/_grid.scss
Labels: 1.7.7.x, Bug, QA ✔️

#18363 Grid row delete confirmation modal - Advanced parameters > DB > Backups
  src/Core/Grid/Definition/Factory/BackupDefinitionFactory.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/backup.yml
Labels: Improvement, QA ✔️, develop, migration

#17467 Category admin jumps to home when deleting a category.
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Form/Admin/Sell/Category/DeleteCategoriesType.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/delete_categories_modal.html.twig
Labels: Bug, PM ✔️, QA ✔️, develop

#18380 Functional tests - Add 'Confirmation delete modal click' to tests Db backups
  tests/puppeteer/pages/BO/advancedParameters/database/dbBackup/index.js
Labels: Refactoring, TE, develop

#18408 Functional tests - Add 'Confirmation delete modal' to tests files
  tests/puppeteer/pages/BO/catalog/files/index.js
Labels: Refactoring, TE, develop

#18361 Grid row delete confirmation modal - Advanced parameters > Team > Profiles
  src/Core/Grid/Definition/Factory/ProfileGridDefinitionFactory.php
Labels: Improvement, QA ✔️, develop, migration

#18384 Functional tests - Add 'Confirmation delete modal' to tests profiles
  tests/puppeteer/pages/BO/advancedParameters/team/profiles/index.js
Labels: Refactoring, TE, develop

#18401 Functional tests - Filter delete and delete with bulk actions email
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/02_sendEmailAfterRegistration.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/04_email/01_filterDeleteAndBulkActionsEmails.js
  tests/puppeteer/pages/BO/advancedParameters/email/index.js
Labels: 1.7.7.x, Refactoring, TE

#18326 Fix messages block in order view page
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/OrderMessageType.php
Labels: 1.7.7.x, Bug, QA ✔️, migration

#18360 Grid row delete confirmation modal - Advanced parameters > Team > Employees
  src/Core/Grid/Definition/Factory/EmployeeGridDefinitionFactory.php
Labels: Improvement, QA ✔️, develop, migration

#18383 Functional tests - Fix delete modal for tests employees
  tests/puppeteer/pages/BO/advancedParameters/team/index.js
Labels: Refactoring, TE, develop

#18359 Grid row delete confirmation modal - Advanced parameters > Emails
  admin-dev/themes/new-theme/js/pages/email/index.js
  src/Core/Grid/Definition/Factory/EmailLogsDefinitionFactory.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/email.yml
Labels: Improvement, QA ✔️, develop, migration

#18234 Fix guest to customer transformation issue
  classes/Customer.php
  mails/themes/classic/core/guest_to_customer.html.twig
  mails/themes/modern/core/guest_to_customer.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️, migration

#18358 Grid row delete confirmation modal - Shop parameters > Traffic SEO > SEO URLs
  src/Core/Grid/Definition/Factory/DeleteActionTrait.php
  src/Core/Grid/Definition/Factory/MetaGridDefinitionFactory.php
Labels: Improvement, QA ✔️, develop, migration

#18386 Functional tests - Add 'Confirmation delete modal' to tests Seo and Url
  tests/puppeteer/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/index.js
Labels: Refactoring, TE, develop

#18357 Grid row delete confirmation modal - International > Localization > Currencies
  src/Core/Grid/Definition/Factory/CurrencyGridDefinitionFactory.php
Labels: Improvement, QA ✔️, develop, migration

#18389 Functional tests - Add 'Confirmation delete modal' to tests currencies
  tests/puppeteer/pages/BO/international/currencies/index.js
Labels: Refactoring, TE, develop

#18334 Add FancyBox in create order page details button
  admin-dev/themes/new-theme/js/pages/order/create/create-order-map.js
  admin-dev/themes/new-theme/js/pages/order/create/create-order-page.js
  admin-dev/themes/new-theme/js/pages/order/create/customer-manager.js
  admin-dev/themes/new-theme/js/pages/order/create/customer-renderer.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  classes/helper/HelperList.php
  src/Adapter/Cart/QueryHandler/GetCartForViewingHandler.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/carts.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/customer.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️

#17927 Wrong prices in edit order with secondary currency
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add-autocomplete.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  controllers/admin/AdminOrdersController.php
  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/AddProductRowType.php
Labels: 1.7.7.x, Bug, QA ✔️

#16710 Add webservice to OrderCartRule with endpoint order_cart_rules
  classes/webservice/WebserviceRequest.php
Labels: Improvement, QA ✔️, develop

#18419 Fix currency symbol in orders list
  src/Core/Grid/Data/Factory/OrderGridDataFactory.php
  src/Core/Grid/Query/OrderQueryBuilder.php
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_data_factory.yml
Labels: 1.7.7.x, Bug, QA ✔️

#18355 Grid row delete confirmation modal - Design > Pages
  src/Core/Grid/Definition/Factory/CmsPageCategoryDefinitionFactory.php
  src/Core/Grid/Definition/Factory/CmsPageDefinitionFactory.php
Labels: Improvement, QA ✔️, develop, migration

#18394 Functional tests - Add 'Confirmation delete modal' to tests design pages
  tests/puppeteer/pages/BO/design/pages/index.js
Labels: Refactoring, TE, develop

#18356 Grid row delete confirmation modal - International > Localization > Languages
  src/Core/Grid/Definition/Factory/LanguageGridDefinitionFactory.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/language.yml
Labels: Improvement, QA ✔️, develop, migration

#18392 Functional tests - Add 'Confirmation delete modal' to tests languages
  tests/puppeteer/pages/BO/international/languages/index.js
Labels: Refactoring, TE, develop

#18440 Added diff for php-cs-fixer in the GH Action
  .github/workflows/php.yml
Labels: 1.7.7.x, Improvement, PM

#18325 Grid row delete confirmation modal - Catalog > Brands > Brands
  src/Core/Grid/Definition/Factory/ManufacturerGridDefinitionFactory.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/manufacturer.yml
Labels: Improvement, QA ✔️, develop, migration

#18416 Fix overflow on main-menu and adjust workaround on last items in menu
  admin-dev/themes/default/public/theme.css
  admin-dev/themes/default/sass/partials/_nav.sass
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/layout/_nav_bar.scss
Labels: 1.7.7.x, Bug, QA ✔️

#18324 Grid row delete confirmation modal - Catalog > Brands > Addresses
  src/Core/Grid/Definition/Factory/ManufacturerAddressGridDefinitionFactory.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/manufacturer.yml
Labels: Improvement, QA ✔️, develop, migration

#18323 Grid row delete confirmation modal - Catalog > Suppliers
  src/Core/Grid/Definition/Factory/SupplierGridDefinitionFactory.php
Labels: Improvement, QA ✔️, develop, migration

#17850 Rework OrderRefundCalculator to use Number
  src/Adapter/Order/Refund/OrderRefundCalculator.php
Labels: 1.7.7.x, Bug, QA ✔️, migration

#17436 Update BO theme/default webpack to v4.41 and its dependencies
  admin-dev/themes/default/package-lock.json
  admin-dev/themes/default/package.json
Labels: Improvement, QA ✔️, develop

#18422 Functional tests - Product settings test label of in-stock products
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/03_labelOfInStockProducts.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
  tests/puppeteer/pages/FO/product.js
Labels: 1.7.7.x, Refactoring, TE

#18435 Functional tests - Localization test default language
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/02_defaultLanguage.js
  tests/puppeteer/pages/BO/international/localization/index.js
  tests/puppeteer/pages/FO/FObasePage.js
Labels: 1.7.7.x, Refactoring, TE

#18442 Functional tests - Add tests help card for pages Localization, Currencies and Languages
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/02_helpCard.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/currencies/03_helpCard.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/languages/05_helpCard.js
Labels: 1.7.7.x, Refactoring, TE

#18465 Functional tests - Add test 'Export languages' in translations page
  tests/puppeteer/campaigns/functional/BO/11_international/04_translations/03_exportLanguage.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/international/translations/index.js
Labels: 1.7.7.x, Refactoring, TE

#18457 Functional tests - Add filter customer to 'Filter orders' tests
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/02_filterOrders.js
Labels: 1.7.7.x, Refactoring, TE

#18452 Functional tests - Add tests Help card for pages employees, profiles, db backups, sql manager and webservice
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/employees/04_helpCard.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/profiles/04_helpCard.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/07_database/dbBackup/03_helpCard.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/02_helpCard.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/09_webservice/03_helpCard.js
Labels: 1.7.7.x, Refactoring, TE

#18476 Functional tests - Fix tests brands and suppliers
  tests/puppeteer/pages/BO/catalog/brands/index.js
  tests/puppeteer/pages/BO/catalog/suppliers/index.js
Labels: 1.7.7.x, Refactoring, TE

#18426 Functional tests - Add test for order setting gift options
  tests/puppeteer/campaigns/data/demo/tax.js
  tests/puppeteer/campaigns/functional/BO/11_international/03_taxes/01_filterAndQuickEditTaxes.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/giftOptions/01_giftOptions.js
  tests/puppeteer/pages/BO/shopParameters/orderSettings/index.js
  tests/puppeteer/pages/FO/FObasePage.js
  tests/puppeteer/pages/FO/checkout.js
Labels: 1.7.7.x, Refactoring, TE

#18485 Functional tests - Fix tests brands for nightly 07-04
  tests/puppeteer/pages/BO/catalog/brands/index.js
Labels: Refactoring, TE, develop

#18321 Do not stack free shipping vouchers on total: shipping fees applied once
  src/Core/Cart/Calculator.php
  src/Core/Cart/Fees.php
  tests/Integration/Behaviour/Features/Context/AbstractPrestaShopFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/free_shipping.feature
Labels: 1.7.7.x, Bug, QA ✔️, migration

#18486 Functional tests - Fix test filter stocks by category
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/05_filterStocksByCategory.js
  tests/puppeteer/pages/BO/catalog/stocks/index.js
Labels: 1.7.7.x, Refactoring, TE

#17736 Fix products search results order in SearchProductsHandler
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add-autocomplete.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  src/Adapter/Product/QueryHandler/SearchProductsHandler.php
  tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php
Labels: 1.7.7.x, Bug, QA ✔️, migration

#18451 Use scandir instead of readdir to get sorted entities
  src/PrestaShopBundle/Install/XmlLoader.php
Labels: 1.7.6.x, Bug, QA ✔️

#18504 Fix wording in classic guest mail template
  mails/themes/classic/core/guest_to_customer.html.twig
Labels: 1.7.7.x, Bug, Wording ✔️

#18437 fix sidebar not displayed in BO order page
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
Labels: 1.7.7.x, Bug, QA ✔️

#18438 Fix currency buttons on edit and add page not aligned by adding styles and changing markup
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/pages/_currency.scss
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Currency/Blocks/form.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️

#18459 Fix h1 on brandlist and supplierlist module that shouldn't be an h1
  themes/classic/modules/ps_brandlist/views/templates/hook/ps_brandlist.tpl
  themes/classic/modules/ps_supplierlist/views/templates/hook/ps_supplierlist.tpl
Labels: Bug, QA ✔️, develop

#18420 Change error message for invalid product quantity
  app/Resources/translations/default/AdminNotificationsError.xlf
  app/Resources/translations/default/AdminOrderscustomersNotification.xlf
  src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
Labels: 1.7.7.x, Improvement, QA ✔️, Wording ✔️

#18515 Fix some css to avoid max width on many languages
  admin-dev/themes/default/public/theme.css
  admin-dev/themes/default/sass/partials/_header.sass
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
Labels: 1.7.7.x, Bug, QA ✔️

#17296 Add displayProductPriceBlock hook
  themes/_core/js/cart.js
  themes/classic/templates/checkout/_partials/cart-detailed-product-line.tpl
Labels: Improvement, QA ✔️, develop

#18352 Fix language used in pdf attachement sent by mail
  classes/PaymentModule.php
  classes/order/OrderHistory.php
Labels: Bug, QA ✔️, develop

#18491 Installation under CLI doesn't take BASE_URI and Apache rewrite in consideration
  install-dev/classes/datas.php
  install-dev/controllers/console/process.php
  install-dev/index_cli.php
  install-dev/init.php
Labels: 1.7.6.x, Bug, QA ✔️

#18185 Add a few phpdoc
  classes/assets/CccReducer.php
  classes/assets/CssMinifier.php
  classes/assets/JavascriptManager.php
  classes/assets/JsMinifier.php
  classes/assets/PrestashopAssetsLibraries.php
  classes/assets/StylesheetManager.php
  classes/checkout/AbstractCheckoutStep.php
  classes/checkout/CheckoutProcess.php
  classes/checkout/CheckoutSession.php
Labels: Refactoring, develop

#18539 Fix minor code issue in BooleanColumn
  src/Core/Grid/Column/Type/BooleanColumn.php
Labels: Refactoring, develop

#18540 Improve nightly log reports
  tests/puppeteer/scripts/run-nightly-reports.sh
  tests/puppeteer/scripts/run-nightly-tests.sh
Labels: 1.7.7.x, Improvement, TE

#18548 Composer failed to be installed properly
  .github/release/create_release.sh
  .travis.yml
  tests/puppeteer/.docker/prestashop/Dockerfile
  tests/puppeteer/.docker/prestashop/Dockerfile-from-git
  tests/puppeteer/.docker/prestashop/docker_run.sh
Labels: 1.7.7.x, Bug

#17860 Fix display for RTL languages for Helper cards by changing animation
  .gitignore
  admin-dev/themes/default/public/theme.rtlfix
  admin-dev/themes/new-theme/public/theme.rtlfix
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Employee/Blocks/showcase_card.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/TrafficSeo/Meta/Blocks/meta_showcase_card.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/showcase_card.html.twig
Labels: Bug, QA ✔️, develop

#18327 Fix regex for category thumb delete route
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/categories.yml
Labels: Bug, QA ✔️, develop

#18493 Change product redirection rules to redirect to valid attribute url
  controllers/front/ProductController.php
Labels: 1.7.6.x, Bug, PM ✔️, QA ✔️

#18436 Functional tests - Add test 'Enable delivery time in stock products'
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/06_enableDeliveryTimeInStockProducts.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
  tests/puppeteer/pages/FO/product.js
  tests/puppeteer/pages/commonPage.js
Labels: 1.7.7.x, Refactoring, TE

#18490 Functional tests - Add test 'Send a test email'
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/04_email/03_sendTestEmail/01_sendTestEmail.js
  tests/puppeteer/pages/BO/advancedParameters/email/index.js
Labels: 1.7.7.x, Refactoring, TE

#18505 Functional tests - Payment > Preferences test group restrictions
  tests/puppeteer/campaigns/functional/BO/10_payment/02_preferences/02_groupRestrictions.js
  tests/puppeteer/pages/BO/customers/add.js
  tests/puppeteer/pages/BO/payment/preferences/index.js
  tests/puppeteer/pages/FO/checkout.js
Labels: 1.7.7.x, Refactoring, TE

#17852 Fix exception when adding negative amount/percentage discount in order view
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/pages/_orders_view.scss
  src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php
  src/Core/Domain/CartRule/Exception/InvalidCartRuleDiscountValueException.php
  src/Core/Domain/CartRule/Exception/InvalidCartRuleValueException.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/AddOrderCartRuleType.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/add_order_discount_modal.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️

#18125 Add missing entities in template inheritance.
  classes/Smarty/TemplateFinder.php
  controllers/front/listing/BestSalesController.php
  controllers/front/listing/NewProductsController.php
  controllers/front/listing/PricesDropController.php
Labels: Bug, QA ✔️, develop

#18207 Functional tests - Product settings enable/disable display discounted price
  tests/puppeteer/campaigns/data/faker/catalogPriceRule.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/06_displayDiscountedPrice.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/catalog/discounts/catalogPriceRules/add.js
  tests/puppeteer/pages/BO/catalog/discounts/catalogPriceRules/index.js
  tests/puppeteer/pages/BO/catalog/discounts/index.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
  tests/puppeteer/pages/FO/product.js
Labels: 1.7.7.x, Refactoring, TE

#18577 Functional tests - Update some tests titles
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/02_defaultLanguage.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/03_helpCard.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/01_enableFinalSummary.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/02_enableGuestCheckout.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/03_disableReorderingOption.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/04_minimumPurchaseTotalRequired.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/06_termsOfService.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/01_displayAvailableQuantities.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/02_displayRemainingQuantities.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/03_displayUnavailableProductAttributes.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/05_separatorOfAttributeAnchor.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/01_allowOrderingOutOfStock.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/02_enableStockManagement.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/03_labelOfInStockProducts.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/06_enableDeliveryTimeInStockProducts.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/01_redisplayCartAtLogin.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/02_sendEmailAfterRegistration.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/05_askForBirthDate.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/06_enablePartnerOffers.js
Labels: 1.7.7.x, Refactoring, TE

#18554 Fix init method not existing in module_card
  admin-dev/themes/new-theme/js/app/pages/module-card/index.js
Labels: Bug, QA ✔️, develop

#18220 Add phpdoc for PDF classes
  classes/pdf/HTMLTemplate.php
  classes/pdf/HTMLTemplateDeliverySlip.php
  classes/pdf/HTMLTemplateInvoice.php
  classes/pdf/HTMLTemplateOrderReturn.php
  classes/pdf/HTMLTemplateOrderSlip.php
  classes/pdf/HTMLTemplateSupplyOrderForm.php
  classes/pdf/PDF.php
  classes/pdf/PDFGenerator.php
Labels: QA ✔️, Refactoring, develop

#16349 Copy Croatian tax rates in EU localization packs
  localization/at.xml
  localization/be.xml
  localization/bg.xml
  localization/cy.xml
  localization/cz.xml
  localization/de.xml
  localization/dk.xml
  localization/ee.xml
  localization/es.xml
  localization/fi.xml
  localization/fr.xml
  localization/gb.xml
  localization/gr.xml
  localization/hr.xml
  localization/hu.xml
  localization/ie.xml
  localization/it.xml
  localization/lt.xml
  localization/lu.xml
  localization/lv.xml
  localization/mt.xml
  localization/nl.xml
  localization/pl.xml
  localization/pt.xml
  localization/ro.xml
  localization/se.xml
  localization/si.xml
  localization/sk.xml
Labels: Improvement, QA ✔️, develop

#18425 Fix minor code issues
  classes/pdf/HTMLTemplateDeliverySlip.php
  classes/pdf/HTMLTemplateOrderSlip.php
Labels: Refactoring, develop

#17979 Minor optimization when installing a language
  classes/Language.php
Labels: QA ✔️, Refactoring, develop

#18621 Functional tests - Add test 'Update default products order'
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/04_pagination/02_updateDefaultProductsOrder.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
  tests/puppeteer/pages/FO/category.js
Labels: 1.7.7.x, Refactoring, TE

#18564 Refactoring using OrderAmountUpdater
  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
  src/Adapter/Order/CommandHandler/DeleteProductFromOrderHandler.php
  src/Adapter/Order/OrderAmountUpdater.php
  src/PrestaShopBundle/Resources/config/services/adapter/order.yml
Labels: 1.7.7.x, Refactoring

#18607 Fix wrong number of "Last emails" in BO - Customer View page
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/sent_emails.html.twig
Labels: 1.7.6.x, Bug, PM ✔️, QA ✔️, Wording ✔️

#18628 Remove duplicate attributes
  classes/pdf/HTMLTemplateDeliverySlip.php
  classes/pdf/HTMLTemplateOrderSlip.php
Labels: Bug, develop

#18616 Functional tests - Add test download sample files for import
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/05_import/01_downloadSampleFiles.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/advancedParameters/import/index.js
Labels: 1.7.7.x, Refactoring, TE

#18632 Fix php-cs-fixer
  classes/Language.php
Labels: Improvement, develop

#18348 Cart products update
  admin-dev/themes/new-theme/js/pages/order/create/create-order-map.js
  admin-dev/themes/new-theme/js/pages/order/create/create-order-page.js
  admin-dev/themes/new-theme/js/pages/order/create/product-manager.js
  admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️

#18631 Functional tests - Refacto orders and invoices tests
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/04_checkInvoiceDownloadedFromList.js
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/05_checkDeliverySlipDownloadedFromList.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/01_enableDisableInvoices.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/02_enableDisableTaxBreakdown.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/03_enableDisableProductImage.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/06_otherOptions.js
Labels: 1.7.7.x, Refactoring, TE

#18637 Fix sidebar not displayed in BO Add employee page
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php
Labels: 1.7.6.x, Bug, QA ✔️

#18638 Update version to 1.7.6.5
  app/AppKernel.php
  install-dev/install_version.php
Labels: 1.7.6.x, Improvement

#18633 Convert cart rule value when order currency is different
  classes/PaymentModule.php
  controllers/admin/AdminOrdersController.php
Labels: 1.7.6.x, Bug, QA ✔️

#18651 Update dependencies for security reasons
  composer.lock
Labels: 1.7.6.x, Improvement

#18641 Show confirmation modal before deleting order messages
  admin-dev/themes/new-theme/js/pages/order_message/index.js
  admin-dev/themes/new-theme/public/order_message.bundle.js
  src/Core/Grid/Definition/Factory/OrderMessageGridDefinitionFactory.php
Labels: 1.7.7.x, Bug, QA ✔️

#18662 Functional tests - Fix customer creation in BO
  tests/puppeteer/pages/BO/customers/add.js
Labels: 1.7.7.x, Refactoring, TE

#18669 Functional tests - Add delete modal to test bulk delete order messages
  tests/puppeteer/pages/BO/customerService/orderMessages/index.js
Labels: 1.7.7.x, Refactoring, TE

#18639 Functional tests - Moving FO pages
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/06_bulkUpdateOrdersStatus.js
  tests/puppeteer/campaigns/functional/BO/02_orders/03_creditSlips/01_createFilterCreditSlips.js
  tests/puppeteer/campaigns/functional/BO/02_orders/03_creditSlips/02_generateCreditSlipsByDate.js
  tests/puppeteer/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/02_deliverySlipNumber.js
  tests/puppeteer/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/03_enableDisableProductImage.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/01_enableFinalSummary.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/03_disableReorderingOption.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/04_email/01_filterDeleteAndBulkActionsEmails.js
  tests/puppeteer/campaigns/sanity/01_installShop/01_installShop.js
  tests/puppeteer/campaigns/sanity/06_checkoutFO/01_orderProduct.js
  tests/puppeteer/pages/FO/cart/index.js
  tests/puppeteer/pages/FO/category/index.js
  tests/puppeteer/pages/FO/checkout/index.js
  tests/puppeteer/pages/FO/checkout/orderConfirmation.js
  tests/puppeteer/pages/FO/cms/index.js
  tests/puppeteer/pages/FO/home/index.js
  tests/puppeteer/pages/FO/login/index.js
  tests/puppeteer/pages/FO/myAccount/index.js
  tests/puppeteer/pages/FO/myAccount/orderHistory.js
  tests/puppeteer/pages/FO/product/index.js
  tests/puppeteer/pages/FO/searchResults/index.js
  tests/puppeteer/pages/FO/siteMap/index.js
  tests/puppeteer/pages/install/index.js
Labels: 1.7.7.x, Refactoring, TE

#18677 Functional tests - Fix call for module
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/04_checkInvoiceDownloadedFromList.js
Labels: 1.7.7.x, Refactoring, TE

#18680 Add array in @return of PaymentModule::getCurrency
  classes/PaymentModule.php
Labels: Bug, develop

#18652 Remove useless traduction wordings and exception codes
  app/Resources/translations/default/AdminActions.xlf
  app/Resources/translations/default/AdminInternationalFeature.xlf
  app/Resources/translations/default/AdminInternationalNotification.xlf
  src/Core/Domain/Currency/Exception/CurrencyConstraintException.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php
  tests/Integration/Behaviour/Features/Context/Domain/CurrencyFeatureContext.php
Labels: 1.7.7.x, Refactoring, Wording ✔️

#18670 Fix tests that are always green when the shop is broken
  tests/puppeteer/campaigns/functional/BO/10_payment/02_preferences/02_groupRestrictions.js
  tests/puppeteer/pages/BO/advancedParameters/team/index.js
  tests/puppeteer/pages/BO/advancedParameters/webservice/index.js
  tests/puppeteer/pages/BO/catalog/brands/index.js
  tests/puppeteer/pages/BO/catalog/categories/index.js
  tests/puppeteer/pages/BO/catalog/products/index.js
  tests/puppeteer/pages/BO/catalog/stocks/index.js
  tests/puppeteer/pages/BO/catalog/suppliers/index.js
  tests/puppeteer/pages/BO/customers/index.js
  tests/puppeteer/pages/BO/design/pages/index.js
  tests/puppeteer/pages/BO/international/currencies/index.js
  tests/puppeteer/pages/BO/international/taxes/index.js
Labels: 1.7.7.x, Refactoring, TE, waiting for QA

#18682 Functional tests - Fix wrong import for tests modules
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/05_checkDeliverySlipDownloadedFromList.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/01_enableDisableInvoices.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/02_enableDisableTaxBreakdown.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/03_enableDisableProductImage.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/06_otherOptions.js
Labels: 1.7.7.x, Refactoring, TE, waiting for QA

#18659 Changelog for 1.7.6.5
  docs/CHANGELOG.txt
Labels: 1.7.6.x, Improvement

#18095 Paste product combination tokens and highlight invalid tokens
  admin-dev/themes/default/js/bundle/product/form.js
  admin-dev/themes/new-theme/scss/components/_toggable_field.scss
Labels: Improvement, QA ✔️, develop

#18688 Update README files for tests directory
  tests/README.md
Labels: 1.7.7.x, Refactoring, TE

#18686 Rename CountryChoiceType options using camel case convention
  src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php
  src/PrestaShopBundle/Form/Admin/Sell/Address/ManufacturerAddressType.php
  src/PrestaShopBundle/Form/Admin/Sell/Supplier/SupplierType.php
  src/PrestaShopBundle/Form/Admin/Type/CountryChoiceType.php
Labels: 1.7.7.x, Bug, QA ✔️

#18720 Functional tests - change url for reporting
  tests/puppeteer/scripts/run-nightly-reports.sh
Labels: 1.7.7.x, Refactoring, TE

#18685 Fix outdated or bad license headers
  admin-dev/themes/new-theme/js/app/utils/email-idn.js
  src/PrestaShopBundle/Exception/InvalidLanguageException.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Address/modal_create_success.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/sent_emails.html.twig
  themes/_core/js/email-idn.js
  themes/classic/templates/checkout/_partials/steps/addresses.tpl
Labels: 1.7.7.x, Improvement, develop

#18005 Fix minor code issues
  classes/Language.php
  classes/ObjectModel.php
  classes/cache/Cache.php
  classes/db/Db.php
  install-dev/controllers/http/process.php
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Install/XmlLoader.php
Labels: QA ✔️, Refactoring, develop

#18196 Refresh documents tab when adding product in order view page
  admin-dev/themes/new-theme/js/fos_js_routes.json
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js
  admin-dev/themes/new-theme/js/pages/order/invoice-note-manager.js
  admin-dev/themes/new-theme/js/pages/order/view.js
  admin-dev/themes/new-theme/js/pages/order/view/order-documents-refresher.js
  admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js
  admin-dev/themes/new-theme/public/order.bundle.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/details.html.twig
Labels: 1.7.7.x, Bug, QA ✔️

#18716 Functional tests - Fix tests enable brands and suppliers pages
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/01_general/general/08_enableDisableSuppliers.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/01_general/general/09_enableDisableBrands.js
Labels: 1.7.7.x, Refactoring, TE

#18718 Functional tests - Refacto credit slips tests
  tests/puppeteer/campaigns/functional/BO/02_orders/03_creditSlips/01_createFilterCreditSlips.js
  tests/puppeteer/campaigns/functional/BO/02_orders/03_creditSlips/02_generateCreditSlipsByDate.js
Labels: 1.7.7.x, Refactoring, TE

#18704 Prevent Tabnabbing
  themes/classic/modules/ps_socialfollow/ps_socialfollow.tpl
Labels: Improvement, develop

#18329 View order page: Display correction - 2
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/_grid.scss
  admin-dev/themes/new-theme/scss/pages/_orders_view.scss
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/payments.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig
Labels: 1.7.7.x, Improvement, QA ✔️, Wording ✔️, migration

#18006 Check if $field['value'] is set before display it
  classes/webservice/WebserviceOutputXML.php
Labels: Bug, QA ✔️, develop

#16872 Allow everyone to track their order from guest tracking
  controllers/front/GuestTrackingController.php
  themes/classic/templates/customer/guest-tracking.tpl
Labels: Bug, PM ✔️, QA ✔️, Wording ✔️, develop

#18735 Fix "mixed content" message.
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/employee_name_with_avatar.html.twig
Labels: Bug, QA ✔️, develop

#18745 Functional tests - Improve test 'Filter stocks by categories'
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/01_simpleFilterStocks.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/02_updateQuantity.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/03_bulkEditQuantity.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/05_filterStocksByCategory.js
  tests/puppeteer/pages/BO/catalog/stocks/index.js
Labels: 1.7.7.x, Refactoring, TE

#18501 Add link to good first issue label
  README.md
Labels: Improvement, develop

#18756 Functional tests - Add test delivery time out of stocks
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/07_enableDeliveryTimeOutOfStockProducts.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
Labels: 1.7.7.x, Refactoring, TE, waiting for QA

#18696 Fix invoice number in multishop context
  classes/pdf/HTMLTemplateInvoice.php
Labels: Bug, QA ✔️, develop

#18743 Fix FO Exception after category add on multilang shop
  classes/Dispatcher.php
Labels: 1.7.7.x, Bug, QA ✔️

#18544 Show new invoice information when adding product with new invoice in BO Order
  admin-dev/themes/new-theme/js/pages/order/view/order-invoices-refresher.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
Labels: 1.7.7.x, Bug, QA ✔️, migration

#18754 Functional tests - View customer
  tests/puppeteer/campaigns/data/demo/products.js
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/02_CRUDCustomerInBO.js
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/08_viewCustomer.js
  tests/puppeteer/pages/BO/customers/view.js
  tests/puppeteer/pages/BO/orders/shoppingCarts/view.js
  tests/puppeteer/pages/FO/checkout/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#18477 Functional tests - Product settings label oos allowed/denied backorders
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/04_labelOutOfStock.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
Labels: 1.7.7.x, Refactoring, TE

#18753 Functional tests - Fix test name export languages
  tests/puppeteer/campaigns/functional/BO/11_international/04_translations/03_exportLanguage.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#18427 Fix issue when there is a quantity discount on combination products
  classes/Product.php
  tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Adding/Product/add_combination.feature
Labels: 1.7.7.x, Bug, QA ✔️

#18200 Fix "weird behaviour when filling the quantity field with letters of symbols"
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-edit.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/edit_product_row.html.twig
Labels: 1.7.7.x, Bug, QA ✔️

#18464 Add modal to customer address listing on bulk action
  src/Core/Grid/Definition/Factory/AddressGridDefinitionFactory.php
Labels: 1.7.7.x, Feature, QA ✔️, Wording ✔️

#18575 Functional tests - Fix delete with bulk actions address
  tests/puppeteer/pages/BO/customers/addresses/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#18774 Functional tests - Fix test filter email logs
  tests/puppeteer/pages/BO/advancedParameters/email/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#18778 Revert "Removed redundant code"
  classes/module/Module.php
Labels: Bug, develop

#18475 Enable controllers as a service through autowiring
  app/config/config.yml
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/PerformanceFormHandler.php
  src/PrestaShopBundle/Resources/config/services/bundle/controller.yml
Labels: 1.7.7.x, Feature

#18775 Functional tests - Renaming functions in files.js
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/03_exportOrders.js
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/04_checkInvoiceDownloadedFromList.js
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/05_checkDeliverySlipDownloadedFromList.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/01_generateInvoiceByDate.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/02_generateInvoiceByStatus.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/02_enableDisableTaxBreakdown.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/03_enableDisableProductImage.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/06_otherOptions.js
  tests/puppeteer/campaigns/functional/BO/02_orders/03_creditSlips/01_createFilterCreditSlips.js
  tests/puppeteer/campaigns/functional/BO/02_orders/03_creditSlips/02_generateCreditSlipsByDate.js
  tests/puppeteer/campaigns/functional/BO/02_orders/04_deliverySlips/01_generateDeliverySlipByDate.js
  tests/puppeteer/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/03_enableDisableProductImage.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/07_exportCategories.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/07_exportBrands.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/06_files/01_CRUDFile.js
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/06_exportCustomers.js
  tests/puppeteer/campaigns/functional/BO/11_international/04_translations/03_exportLanguage.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/05_import/01_downloadSampleFiles.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/07_database/dbBackup/01_CreateAndDeleteDbBackup.js
  tests/puppeteer/campaigns/utils/files.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#18635 Show confirm modal when adding product with new invoice
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️, migration

#18797 Functional tests - Refacto tests order settings
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/01_enableFinalSummary.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/02_enableGuestCheckout.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/03_disableReorderingOption.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/04_minimumPurchaseTotalRequired.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/06_termsOfService.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#18800 Functional tests - Fix number of element in table for emails logs page
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/04_email/01_filterDeleteAndBulkActionsEmails.js
  tests/puppeteer/pages/BO/advancedParameters/email/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#18524 Remove ability to apply discount on all invoices in order view page
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js
  admin-dev/themes/new-theme/js/pages/order/view.js
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/AddOrderCartRuleType.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/add_order_discount_modal.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, migration

#18804 Change selectors
  tests/puppeteer/pages/BO/payment/preferences/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#18617 Make computing precision matching currency's display precision
  config/config.inc.php
  src/Core/Cart/CartRow.php
  src/Core/Localization/CLDR/ComputingPrecision.php
  tests-legacy/Integration/classes/CartGetOrderTotalTest.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/amount_multiple.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/Currency/currency.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/RoundingType/round_item.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/RoundingType/round_line.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/RoundingType/round_total.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/CartToOrder/cart_to_order.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
  tests/Integration/Behaviour/Features/Scenario/Order/partial_refund.feature
  tests/Integration/Behaviour/Features/Scenario/Order/return_product.feature
  tests/Integration/Behaviour/Features/Scenario/Order/standard_refund.feature
  tests/Unit/Core/Localization/CLDR/ComputingPrecisionTest.php
Labels: 1.7.7.x, Improvement, QA ✔️

#18764 Fix exception when deleting address from customer view
  admin-dev/themes/new-theme/js/components/form-submit-button.js
  admin-dev/themes/new-theme/js/pages/customer/index.js
  admin-dev/themes/new-theme/public/customer.bundle.js
  src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig
  themes/core.js
  themes/core.js.map
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️

#18812 Fix invoices refresh when adding product in an order
  admin-dev/themes/new-theme/js/pages/order/view/order-invoices-refresher.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/pages/_orders.scss
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/edit_product_row.html.twig
Labels: 1.7.7.x, Bug, QA ✔️

#18757 [BO] Fix bug on type='color' in renderOption
  admin-dev/themes/default/template/helpers/options/options.tpl
Labels: Bug, QA ✔️, develop

#18832 Functional tests - Change selectors orders pages
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/01_enableFinalSummary.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/02_enableGuestCheckout.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/03_disableReorderingOption.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/04_minimumPurchaseTotalRequired.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/06_termsOfService.js
  tests/puppeteer/pages/BO/orders/creditSlips/index.js
  tests/puppeteer/pages/BO/orders/deliverySlips/index.js
  tests/puppeteer/pages/BO/orders/index.js
  tests/puppeteer/pages/BO/orders/invoices/index.js
  tests/puppeteer/pages/BO/orders/view.js
  tests/puppeteer/pages/BO/payment/preferences/index.js
Labels: 1.7.7.x, Refactoring, TE

#18836 Merge 1765 to 177
  docs/CHANGELOG.txt
Labels: 1.7.7.x, Improvement

#18840 Functional tests - Change selectors for advanced params pages
  tests/puppeteer/pages/BO/advancedParameters/database/dbBackup/index.js
  tests/puppeteer/pages/BO/advancedParameters/database/sqlManager/index.js
  tests/puppeteer/pages/BO/advancedParameters/database/sqlManager/view.js
  tests/puppeteer/pages/BO/advancedParameters/email/index.js
  tests/puppeteer/pages/BO/advancedParameters/import/index.js
  tests/puppeteer/pages/BO/advancedParameters/team/index.js
  tests/puppeteer/pages/BO/advancedParameters/team/profiles/index.js
  tests/puppeteer/pages/BO/advancedParameters/webservice/add.js
  tests/puppeteer/pages/BO/advancedParameters/webservice/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#18843 Functional tests - Create edit view voucher in customer information page
  tests/puppeteer/campaigns/data/faker/cartRule.js
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/09_viewEditVoucher.js
  tests/puppeteer/pages/BO/catalog/discounts/add.js
  tests/puppeteer/pages/BO/catalog/discounts/index.js
  tests/puppeteer/pages/BO/customers/view.js
Labels: 1.7.7.x, Refactoring, TE

#18851 Build assets for Beta
  admin-dev/themes/new-theme/public/address.bundle.js
  admin-dev/themes/new-theme/public/attachment.bundle.js
  admin-dev/themes/new-theme/public/attribute.bundle.js
  admin-dev/themes/new-theme/public/attribute_group.bundle.js
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/catalog_price_rule.bundle.js
  admin-dev/themes/new-theme/public/category.bundle.js
  admin-dev/themes/new-theme/public/cldr.bundle.js
  admin-dev/themes/new-theme/public/cms_page.bundle.js
  admin-dev/themes/new-theme/public/cms_page_form.bundle.js
  admin-dev/themes/new-theme/public/contacts.bundle.js
  admin-dev/themes/new-theme/public/currency_form.bundle.js
  admin-dev/themes/new-theme/public/customer.bundle.js
  admin-dev/themes/new-theme/public/customer_address_form.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/employee.bundle.js
  admin-dev/themes/new-theme/public/improve_design_positions.bundle.js
  admin-dev/themes/new-theme/public/language.bundle.js
  admin-dev/themes/new-theme/public/maintenance.bundle.js
  admin-dev/themes/new-theme/public/manufacturer.bundle.js
  admin-dev/themes/new-theme/public/manufacturer_address_form.bundle.js
  admin-dev/themes/new-theme/public/meta.bundle.js
  admin-dev/themes/new-theme/public/module.bundle.js
  admin-dev/themes/new-theme/public/module_card.bundle.js
  admin-dev/themes/new-theme/public/order.bundle.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  admin-dev/themes/new-theme/public/order_message.bundle.js
  admin-dev/themes/new-theme/public/product_page.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/profiles.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/supplier.bundle.js
  admin-dev/themes/new-theme/public/supplier_form.bundle.js
  admin-dev/themes/new-theme/public/tax.bundle.js
  admin-dev/themes/new-theme/public/tax_rules_group.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
Labels: 1.7.7.x, Bug

#18847 Update README chat badge gitter to slack
  README.md
Labels: Improvement, develop

#17179 Fix free gift product in Order create page
  admin-dev/themes/new-theme/js/pages/order/create/cart-rule-manager.js
  admin-dev/themes/new-theme/js/pages/order/create/create-order-map.js
  admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  classes/Cart.php
  classes/CartRule.php
  src/Adapter/Cart/CommandHandler/UpdateProductQuantityInCartHandler.php
  src/Adapter/Cart/QueryHandler/GetCartInformationHandler.php
  src/Core/Domain/Cart/QueryResult/CartInformation/CartProduct.php
  src/Core/Domain/Cart/QueryResult/CartInformation/CartRule.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php
  src/PrestaShopBundle/Resources/config/services/adapter/cart.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig
  tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Adding/CartRule/add_cartrule.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/Deleting/delete_cart_rule_from_cart.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/Deleting/delete_product_from_cart.feature
  tests/Integration/Behaviour/behat.yml
Labels: 1.7.7.x, Bug, PM ✔️, QA ✔️, Wording ✔️, migration

#18845 Add tag controller.service_arguments to PrestaShop controllers
  app/config/config.yml
Labels: 1.7.7.x, Bug

#18834 Remove newsletter registration during installation
  install-dev/classes/datas.php
  install-dev/controllers/console/process.php
  install-dev/controllers/http/configure.php
  install-dev/controllers/http/process.php
  tests-legacy/PrestaShopBundle/Utils/DatabaseCreator.php
Labels: 1.7.7.x, Bug, QA ✔️

#18697 Fix error when updating a used address with no DNI
  classes/Address.php
Labels: 1.7.7.x, Bug, QA ✔️, Regression

#18849 Functional tests - Change selectors for catalog pages
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/03_maxSizeShortDescription.js
  tests/puppeteer/pages/BO/catalog/brands/add.js
  tests/puppeteer/pages/BO/catalog/brands/index.js
  tests/puppeteer/pages/BO/catalog/brands/view.js
  tests/puppeteer/pages/BO/catalog/categories/add.js
  tests/puppeteer/pages/BO/catalog/categories/index.js
  tests/puppeteer/pages/BO/catalog/discounts/catalogPriceRules/index.js
  tests/puppeteer/pages/BO/catalog/files/add.js
  tests/puppeteer/pages/BO/catalog/files/index.js
  tests/puppeteer/pages/BO/catalog/monitoring/index.js
  tests/puppeteer/pages/BO/catalog/products/add.js
  tests/puppeteer/pages/BO/catalog/products/index.js
  tests/puppeteer/pages/BO/catalog/stocks/index.js
  tests/puppeteer/pages/BO/catalog/stocks/movements/index.js
  tests/puppeteer/pages/BO/catalog/suppliers/add.js
  tests/puppeteer/pages/BO/catalog/suppliers/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#18859 Defined Currency Context if needed in WebService Context
  webservice/dispatcher.php
Labels: 1.7.7.x, Bug, QA ✔️

#18580 In BO Product page, use ecotax excl. tax instead of tax incl.
  src/PrestaShopBundle/Model/Product/AdminModelAdapter.php
Labels: 1.7.7.x, Bug, QA ✔️

#18736 Address State field drop down is ordered by ID, instead of State Name
  classes/State.php
  classes/form/CustomerAddressFormatter.php
  src/Adapter/Form/ChoiceProvider/CountryStateByIdChoiceProvider.php
Labels: QA ✔️, Refactoring, develop

#18866 Functional tests - Fix adding customer to voucher
  tests/puppeteer/pages/BO/catalog/discounts/add.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE
