Repository PrestaShop/PrestaShop, pull requests merged in 2020-08, with the labels that each got.

#20407 Use sharedStorage for exceptions in behat domain contexts
  tests/Integration/Behaviour/Features/Context/Domain/AbstractDomainFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CurrencyFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/FeatureFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/MetaFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderPaymentFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderRefundFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/WebserviceKeyFeatureContext.php
Labels: Refactoring, develop

#20383 Clean a bit PaymentModule class
  classes/PaymentModule.php
Labels: Refactoring, develop

#20302 Functional tests - Add update a language
  tests/UI/campaigns/data/demo/languages.js
  tests/UI/campaigns/functional/BO/11_international/04_translations/02_addUpdateLanguage.js
  tests/UI/pages/BO/international/translations/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#20394 Functional tests - Add test 'Search customers in create order page'
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/01_searchCustomers.js
  tests/UI/pages/BO/orders/add.js
  tests/UI/pages/BO/orders/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#20418 Functional tests - Add tests for titles page
  tests/UI/campaigns/data/demo/titles.js
  tests/UI/campaigns/data/faker/customer.js
  tests/UI/campaigns/data/faker/title.js
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/03_titles/01_filterTitles.js
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/03_titles/02_CRUDTitles.js
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/03_titles/03_bulkDeleteTitles.js
  tests/UI/pages/BO/shopParameters/customerSettings/index.js
  tests/UI/pages/BO/shopParameters/customerSettings/titles/add.js
  tests/UI/pages/BO/shopParameters/customerSettings/titles/index.js
Labels: 1.7.7.x, Refactoring, TE

#20427 Refactor behats ProductFeatureContext to multiple smaller contexts
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/AbstractProductFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/AddProductFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/CommonProductFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateBasicInformationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateCategoriesFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateCustomizationFieldsFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateOptionsFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePackFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePricesFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateShippingFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateTagsFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/partial_refund.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_prices.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_shipping.feature
  tests/Integration/Behaviour/behat.yml
Labels: Refactoring, develop, migration

#20408 Fix bug on Invoices tax detail
  classes/order/Order.php
  classes/order/OrderInvoice.php
Labels: 1.7.7.x, Bug, QA ✔️

#20439 Functional tests - Avoid 'home' as new category to create
  tests/UI/campaigns/data/faker/category.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#20440 Functional tests - Enable using loginCommon with different user than default one
  tests/UI/campaigns/commonTests/loginBO.js
Labels: 1.7.7.x, Refactoring, TE

#20433 Dont show root category on category grid search results
  src/Core/Grid/Query/CategoryQueryBuilder.php
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
Labels: 1.7.7.x, Bug, QA ✔️

#20459 Functional tests - Add new test 'Select default Theme'
  tests/UI/campaigns/functional/BO/08_design/03_emailThemes/02_selectDefaultEmailTheme.js
  tests/UI/pages/BO/design/emailThemes/index.js
Labels: 1.7.7.x, Refactoring, TE

#20450 Functional tests - Update linkchecker urls
  tests/UI/campaigns/tools/linkchecker.js
  tests/UI/campaigns/tools/urls.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#20460 Functional tests - Update test filter categories
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/01_filterAndQuickEditCategories.js
Labels: 1.7.7.x, Refactoring, TE

#20410 Replace index.php?controller=404 by pagenotfound
  classes/form/CustomerAddressForm.php
  controllers/front/ProductController.php
  controllers/front/listing/BestSalesController.php
  controllers/front/listing/CategoryController.php
Labels: Improvement, QA ✔️, develop

#20366 Bug when delete address when use in shopping cart
  controllers/front/AddressController.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#20461 Fixed Modal "View pack content"
  admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js
  admin-dev/themes/new-theme/public/currency_form.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/order.bundle.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  admin-dev/themes/new-theme/public/theme.css
Labels: 1.7.7.x, Bug, QA ✔️

#20457 Include product name and employee name in out of stock email
  mails/themes/modern/core/productoutofstock.html.twig
  src/Core/Stock/StockManager.php
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️

#20468 Functional tests - Search hook in Positions page
  tests/UI/campaigns/functional/BO/08_design/05_positions/02_searchHook.js
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/design/positions/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#20472 Remove overwritten property: context
  js/admin/products.js
Labels: Improvement, develop

#20483 Typo error in AdminRequestSqlController.php
  controllers/admin/AdminRequestSqlController.php
Labels: Improvement, develop, typo fix

#20474 [FO] : Wrong base price in Invoice
  classes/order/Order.php
Labels: Bug, develop

#20475 Typo Error in AdminOutstandingController.php
  controllers/admin/AdminOutstandingController.php
Labels: Improvement, develop, typo fix

#17826 Add Kurdish language
  app/Resources/all_languages.json
  app/Resources/legacy-to-standard-locales.json
Labels: Improvement, International, Languages, QA ✔️, Wording ✔️, develop

#20488 Implement combinations generator which uses php Generator
  src/Core/Product/Generator/CombinationGenerator.php
  src/Core/Product/Generator/CombinationGeneratorInterface.php
  tests/Unit/Core/Product/Generator/CombinationGeneratorTest.php
Labels: Refactoring, develop, migration

#20511 Typo Error In CSV.php
  classes/CSV.php
Labels: Improvement, develop

#20515 Fix supplier service name to fit namespace convention
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
Labels: Refactoring, develop, migration

#20516 Functional tests - Fix selector changes for email themes form
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/MailTheme/Blocks/configuration_form.html.twig
  tests/UI/pages/BO/design/emailThemes/index.js
Labels: Refactoring, TE, develop

#20335 Remove discount from order (persist state)
  classes/Cart.php
  classes/CartRule.php
  classes/order/Order.php
  classes/order/OrderCartRule.php
  install-dev/data/db_structure.sql
  install-dev/upgrade/sql/1.7.7.0.sql
  src/Adapter/Order/CommandHandler/DeleteCartRuleFromOrderHandler.php
  src/Adapter/Order/OrderAmountUpdater.php
  src/Adapter/Order/Refund/OrderProductRemover.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_cart_rules.feature
Labels: 1.7.7.x, Bug, Key feature, QA ✔️, Wording ✔️

#20449 Add undeclared variables in AdminController
  classes/controller/AdminController.php
Labels: Improvement, develop

#20521 Functional tests - Add new test 'Configure module'
  tests/UI/campaigns/data/demo/modules.js
  tests/UI/campaigns/functional/BO/04_customers/01_customers/09_subscribeToNewsletter.js
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/03_configureModule.js
  tests/UI/pages/BO/modules/moduleConfiguration/index.js
  tests/UI/pages/BO/modules/moduleManager/index.js
  tests/UI/pages/BO/modules/psEmailSubscription/index.js
Labels: 1.7.7.x, Refactoring, TE

#20482 Set CartRule amount with tax in BO instead of without tax
  classes/Cart.php
  classes/PaymentModule.php
  src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php
  src/Adapter/Order/OrderAmountUpdater.php
  src/Core/Cart/Calculator.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/percent_multiple.feature
  tests/Integration/Behaviour/Features/Scenario/Order/add_cart_rule_to_order.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_cancel_product.feature
Labels: 1.7.7.x, BC break, Bug, waiting for QA

#20540 Functional tests - Add tests for seo pages
  tests/UI/campaigns/data/demo/CMSpage.js
  tests/UI/campaigns/data/faker/seoPage.js
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/seoAndUrls/06_sortAndPaginationSeoPages.js
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/seoAndUrls/07_bulkDeleteSeoPages.js
  tests/UI/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/add.js
  tests/UI/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/index.js
Labels: 1.7.7.x, Refactoring, TE

#20502 Functional tests - Add new test 'Create customer from create order page'
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/01_searchCustomers.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/02_createCustomer.js
  tests/UI/pages/BO/customers/add.js
  tests/UI/pages/BO/orders/add.js
  tests/UI/pages/commonPage.js
Labels: 1.7.7.x, Refactoring, TE

#20539 Functional tests - Update exchange rate
  tests/UI/campaigns/functional/BO/11_international/01_localization/currencies/04_updateExchangeRate.js
  tests/UI/pages/BO/international/currencies/add.js
  tests/UI/pages/BO/international/currencies/index.js
Labels: 1.7.7.x, Refactoring, TE

#20492 Remove call to updateOrderInvoice - not needed anymore
  src/Adapter/Order/OrderProductQuantityUpdater.php
Labels: 1.7.7.x, Bug, QA ✔️

#20491 Fix UpdateCustomizationFieldsHandler todo
  src/Adapter/Product/CommandHandler/UpdateProductCustomizationFieldsHandler.php
  src/Core/Domain/Product/Customization/Command/UpdateProductCustomizationFieldsCommand.php
  src/Core/Domain/Product/Customization/CommandHandler/UpdateProductCustomizationFieldsHandlerInterface.php
  src/Core/Domain/Product/Customization/CustomizationField.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateCustomizationFieldsFeatureContext.php
Labels: Refactoring, develop, migration

#20477 Fixed cast for primary key in PrestaShopCollection
  classes/ObjectModel.php
  classes/pdf/HTMLTemplateInvoice.php
  src/Adapter/Customer/QueryHandler/GetCustomerForEditingHandler.php
  tests/Integration/Behaviour/Features/Scenario/Customer/customer_management.feature
Labels: 1.7.7.x, Bug, QA ✔️

#20543 Functional tests - Add test 'Filter groups'
  tests/UI/campaigns/data/demo/groupAccess.js
  tests/UI/campaigns/data/faker/customer.js
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/02_groups/01_filterGroups.js
  tests/UI/pages/BO/shopParameters/customerSettings/groups/index.js
  tests/UI/pages/BO/shopParameters/customerSettings/index.js
Labels: 1.7.7.x, Refactoring, TE

#20524 Fix bad call in HTMLTemplateOrderSlip
  classes/pdf/HTMLTemplateOrderSlip.php
Labels: 1.7.7.x, Bug, QA ✔️

#20434 Fixed default value for the form Add Employee
  src/Core/Form/IdentifiableObject/DataHandler/EmployeeFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/EmployeeFormDataProvider.php
Labels: Bug, QA ✔️, develop

#20547 Update module productcommentsto v4.1.0
  composer.lock
Labels: 1.7.7.x, Improvement, QA ✔️

#20538 Fix order cart rule deletion
  src/Adapter/Order/CommandHandler/DeleteCartRuleFromOrderHandler.php
Labels: 1.7.7.x, Bug, QA ✔️, waiting for author

#12578 Fix wrong use of alias when registering new hook
  classes/Hook.php
  classes/cache/Cache.php
  classes/module/Module.php
  install-dev/data/xml/hook_alias.xml
  install-dev/upgrade/sql/1.7.7.0.sql
Labels: 1.7.7.x, Bug, QA ✔️

#17712 Prevent from loading old carts
  classes/Cart.php
Labels: Bug, QA ✔️, develop

#20384 Add classic stylelint
  themes/classic/_dev/.stylelintignore
  themes/classic/_dev/.stylelintrc
  themes/classic/_dev/css/components/alert.scss
  themes/classic/_dev/css/components/block-reassurance.scss
  themes/classic/_dev/css/components/brands.scss
  themes/classic/_dev/css/components/cart.scss
  themes/classic/_dev/css/components/categories.scss
  themes/classic/_dev/css/components/checkout.scss
  themes/classic/_dev/css/components/contact.scss
  themes/classic/_dev/css/components/custom-text.scss
  themes/classic/_dev/css/components/customer.scss
  themes/classic/_dev/css/components/customization-modal.scss
  themes/classic/_dev/css/components/drop-down.scss
  themes/classic/_dev/css/components/errors.scss
  themes/classic/_dev/css/components/featuredproducts.scss
  themes/classic/_dev/css/components/footer.scss
  themes/classic/_dev/css/components/forgotten-password.scss
  themes/classic/_dev/css/components/imageslider.scss
  themes/classic/_dev/css/components/mainmenu.scss
  themes/classic/_dev/css/components/newsletter.scss
  themes/classic/_dev/css/components/products.scss
  themes/classic/_dev/css/components/quickview.scss
  themes/classic/_dev/css/components/renew-password.scss
  themes/classic/_dev/css/components/search-widget.scss
  themes/classic/_dev/css/components/sitemap.scss
  themes/classic/_dev/css/components/stores.scss
  themes/classic/_dev/css/components/subcategories.scss
  themes/classic/_dev/css/partials/_commons.scss
  themes/classic/_dev/css/partials/_fonts.scss
  themes/classic/_dev/css/partials/_mixins.scss
  themes/classic/_dev/css/partials/_variables.scss
  themes/classic/_dev/css/theme.scss
  themes/classic/_dev/package-lock.json
  themes/classic/_dev/package.json
Labels: Improvement, QA ✔️, develop

#20529 Fix links in footer - https is better than http
  admin-dev/themes/default/template/footer.tpl
Labels: 1.7.7.x, Improvement

#20436 Extract translations of 177
  app/Resources/translations/default/AdminActions.xlf
  app/Resources/translations/default/AdminAdvparametersFeature.xlf
  app/Resources/translations/default/AdminAdvparametersHelp.xlf
  app/Resources/translations/default/AdminAdvparametersNotification.xlf
  app/Resources/translations/default/AdminCatalogFeature.xlf
  app/Resources/translations/default/AdminCatalogHelp.xlf
  app/Resources/translations/default/AdminCatalogNotification.xlf
  app/Resources/translations/default/AdminDesignHelp.xlf
  app/Resources/translations/default/AdminDesignNotification.xlf
  app/Resources/translations/default/AdminGlobal.xlf
  app/Resources/translations/default/AdminInternationalHelp.xlf
  app/Resources/translations/default/AdminInternationalNotification.xlf
  app/Resources/translations/default/AdminLoginNotification.xlf
  app/Resources/translations/default/AdminModulesFeature.xlf
  app/Resources/translations/default/AdminModulesNotification.xlf
  app/Resources/translations/default/AdminNavigationMenu.xlf
  app/Resources/translations/default/AdminNavigationNotification.xlf
  app/Resources/translations/default/AdminNotificationsError.xlf
  app/Resources/translations/default/AdminNotificationsInfo.xlf
  app/Resources/translations/default/AdminNotificationsSuccess.xlf
  app/Resources/translations/default/AdminNotificationsWarning.xlf
  app/Resources/translations/default/AdminOrderscustomersFeature.xlf
  app/Resources/translations/default/AdminOrderscustomersHelp.xlf
  app/Resources/translations/default/AdminOrderscustomersNotification.xlf
  app/Resources/translations/default/AdminShippingFeature.xlf
  app/Resources/translations/default/AdminShippingNotification.xlf
  app/Resources/translations/default/AdminShopparametersFeature.xlf
  app/Resources/translations/default/AdminShopparametersHelp.xlf
  app/Resources/translations/default/EmailsBody.xlf
  app/Resources/translations/default/EmailsSubject.xlf
  app/Resources/translations/default/Install.xlf
  app/Resources/translations/default/ModulesBlockwishlistAdmin.xlf
  app/Resources/translations/default/ModulesBlockwishlistShop.xlf
  app/Resources/translations/default/ModulesCheckpaymentShop.xlf
  app/Resources/translations/default/ModulesContactformAdmin.xlf
  app/Resources/translations/default/ModulesContactformShop.xlf
  app/Resources/translations/default/ModulesDashactivityAdmin.xlf
  app/Resources/translations/default/ModulesEmailsubscriptionAdmin.xlf
  app/Resources/translations/default/ModulesEmailsubscriptionShop.xlf
  app/Resources/translations/default/ModulesFaviconnotificationboAdmin.xlf
  app/Resources/translations/default/ModulesGsitemapAdmin.xlf
  app/Resources/translations/default/ModulesImagesliderAdmin.xlf
  app/Resources/translations/default/ModulesSharebuttonsAdmin.xlf
  app/Resources/translations/default/ModulesSharebuttonsShop.xlf
  app/Resources/translations/default/ModulesStatspersonalinfosAdmin.xlf
  app/Resources/translations/default/ModulesWirepaymentAdmin.xlf
  app/Resources/translations/default/ModulesWirepaymentShop.xlf
  app/Resources/translations/default/ShopNotificationsError.xlf
  app/Resources/translations/default/ShopThemeActions.xlf
  app/Resources/translations/default/ShopThemeCatalog.xlf
  app/Resources/translations/default/ShopThemeCheckout.xlf
  app/Resources/translations/default/messages.xlf
Labels: 1.7.7.x, Improvement

#20559 Functional tests - Add test 'Filter stores'
  tests/UI/campaigns/data/demo/stores.js
  tests/UI/campaigns/functional/BO/13_shopParameters/05_contact/stores/01_filterStores.js
  tests/UI/pages/BO/shopParameters/contact/index.js
  tests/UI/pages/BO/shopParameters/stores/index.js
Labels: 1.7.7.x, Refactoring, TE

#20569 Functional tests - Add new tests for stores page
  tests/UI/campaigns/data/faker/store.js
  tests/UI/campaigns/functional/BO/13_shopParameters/05_contact/stores/01_filterAndQuickEditStores.js
  tests/UI/campaigns/functional/BO/13_shopParameters/05_contact/stores/02_CRUDStores.js
  tests/UI/campaigns/functional/BO/13_shopParameters/05_contact/stores/03_bulkActionsStores.js
  tests/UI/pages/BO/shopParameters/stores/add.js
  tests/UI/pages/BO/shopParameters/stores/index.js
Labels: 1.7.7.x, Refactoring, TE

#20486 Functional tests - Enable/Disable display attributes in product meta title
  tests/UI/campaigns/data/demo/attributes.js
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/01_seoAndUrls/01_seoAndUrls/01_filterSeoPages.js
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/01_seoAndUrls/01_seoAndUrls/02_CRUDSeoPage.js
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/01_seoAndUrls/01_seoAndUrls/06_sortAndPaginationSeoPages.js
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/01_seoAndUrls/01_seoAndUrls/07_bulkDeleteSeoPages.js
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/01_seoAndUrls/02_setUpUrls/03_enableDisableFriendlyURL.js
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/01_seoAndUrls/02_setUpUrls/04_enableDisableAccentedURL.js
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/01_seoAndUrls/05_seoOptions/01_displayAttributesInProductMetaTitle.js
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/01_seoAndUrls/helperCard.js
  tests/UI/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/index.js
Labels: 1.7.7.x, Refactoring, TE

#20555 Fix images quickview also updating product page by changing product i…
  themes/_core/js/product.js
  themes/core.js
  themes/core.js.map
Labels: 1.7.7.x, Bug, QA ✔️

#20403 Remove useless assignment of logout_url in MyAccountController
  controllers/front/MyAccountController.php
  themes/classic/modules/ps_customersignin/ps_customersignin.tpl
  themes/classic/templates/customer/my-account.tpl
Labels: Improvement, QA ✔️, develop

#20451 Fix TinyMCE error on product page
  admin-dev/themes/default/js/bundle/product/form.js
Labels: 1.7.7.x, Bug, QA ✔️

#20570 Update _PS_JQUERY_VERSION_ to match the included jQuery version
  config/defines.inc.php
Labels: 1.7.7.x, Bug

#20581 Remove useless files
  README.md
  docs/docker/.gitignore
  docs/docker/README.md
  docs/docker/nginx_fpm/docker-compose.yml
  docs/docker/nginx_fpm/prestashop-fpm/Dockerfile
  docs/docker/nginx_fpm/prestashop-fpm/prestashop-php.ini
  docs/docker/nginx_fpm/prestashop-nginx/prestashop-nginx.conf
  docs/docker/nginx_fpm_supervisord/docker-compose.yml
  docs/docker/nginx_fpm_supervisord/prestashop-nginx-fpm/Dockerfile
  docs/docker/nginx_fpm_supervisord/prestashop-nginx-fpm/prestashop-nginx.conf
  docs/docker/nginx_fpm_supervisord/prestashop-nginx-fpm/prestashop-php.ini
  docs/docker/prestashopCli.sh
  docs/server_config/nginx.conf.dist
Labels: Improvement, develop

#20586 Functional tests - Add test 'Filter image types'
  tests/UI/campaigns/data/demo/imageTypes.js
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/01_filterImageTypes.js
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/design/imageSettings/index.js
Labels: 1.7.7.x, Refactoring, TE

#20571 Return an int instead of a float (in some cases) for Pack::getQuantity()
  classes/Pack.php
Labels: 1.7.7.x, Bug, QA ✔️

#20381 Order return states grid - Remove unnecessary filters merge
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/OrderStateController.php
  src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php
Labels: Bug, Bug fix, QA ✔️, develop

#20592 The delivery note's name is wrong after the download
  classes/pdf/HTMLTemplateDeliverySlip.php
Labels: Bug, QA ✔️, develop

#20593 Remove useless comments in HTMLTemplateInvoice.php
  classes/pdf/HTMLTemplateInvoice.php
Labels: Improvement, develop

#20305 Better form errors display for Address form
  admin-dev/themes/new-theme/scss/components/_form.scss
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: Improvement, QA ✔️, develop, waiting for UX, waiting for dev

#20387 Allow duplicates in log when an error is thrown in hooks
  src/Adapter/HookManager.php
Labels: Bug, QA ✔️, develop

#18733 Introduce Nightly status badge - thank you @SimonGrn
  README.md
Labels: Feature, develop

#20551 Functional tests - Add tests 'CRUD and bulk delete Groups'
  tests/UI/campaigns/data/faker/group.js
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/02_groups/02_CRUDGroups.js
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/02_groups/03_bulkDeleteGroups.js
  tests/UI/pages/BO/shopParameters/customerSettings/groups/add.js
  tests/UI/pages/BO/shopParameters/customerSettings/groups/index.js
  tests/UI/pages/BO/shopParameters/customerSettings/titles/index.js
Labels: 1.7.7.x, Refactoring, TE

#20599 Functional tests - Add CRUD and Bulk actions tests for image types
  tests/UI/campaigns/data/faker/imageType.js
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/02_CRUDImageType.js
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/03_bulkDeleteImageTypes.js
  tests/UI/pages/BO/design/imageSettings/add.js
  tests/UI/pages/BO/design/imageSettings/index.js
Labels: 1.7.7.x, Refactoring, TE

#20620 Fix license header for 1.7.7.x
  classes/Hook.php
Labels: 1.7.7.x, Improvement

#20618 Changelog v1.7.7.0-beta.2
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: 1.7.7.x, Feature

#20453 Search combination by ean
  classes/Combination.php
Labels: Improvement, QA ✔️, develop

#20375 Correct stylelint browsers on new-theme
  admin-dev/themes/new-theme/scss/components/_button.scss
  admin-dev/themes/new-theme/scss/components/_modulescards.scss
  admin-dev/themes/new-theme/scss/pages/partials/_theme_logo_configuration.scss
  admin-dev/themes/new-theme/scss/pages/partials/_theme_logo_theme_card.scss
Labels: Improvement, QA ✔️, develop

#20556 Fix images quickview also updating product page by changing product i…
  themes/_core/js/selectors.js
Labels: Bug, Minor, QA ✔️, develop

#20626 Fix duplicate ids in order page
  admin-dev/themes/new-theme/js/pages/order/view/order-product-edit.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig
  tests/UI/pages/BO/orders/view.js
Labels: 1.7.7.x, Bug, QA ✔️

#20211 Fix missing pagination for alternative lang url
  classes/controller/FrontController.php
Labels: Bug, QA ✔️, develop, waiting for dev

#20644 Check for address id before creating CartAddress
  src/Adapter/Cart/QueryHandler/GetCartInformationHandler.php
Labels: 1.7.7.x, Bug, QA ✔️

#20646 Bad static call to oneself in OrderDetail
  classes/order/OrderDetail.php
Labels: Bug, develop

#20647 Fix selectors for Seo options form after merge 1.7.7.x into develop
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/TrafficSeo/Meta/Blocks/seo_options_configuration.html.twig
  tests/UI/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/index.js
Labels: Refactoring, TE, develop

#20598 Do not reconvert discounts
  src/Adapter/Presenter/Cart/CartPresenter.php
Labels: 1.7.7.x, Bug, QA ✔️

#20683 Fix faker data - Title's name should take at most 20 characters
  tests/UI/campaigns/data/faker/title.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#20692 Add tests 'Filter attributes' and 'Filter attribute values'
  tests/UI/campaigns/data/demo/attributes.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/01_filterAttributes.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/02_filterAttributeValues.js
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/01_seoAndUrls/05_seoOptions/01_displayAttributesInProductMetaTitle.js
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/catalog/attributes/index.js
  tests/UI/pages/BO/catalog/attributes/view.js
Labels: 1.7.7.x, Refactoring, TE

#20717 Fix private final method
  src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php
Labels: Improvement, develop

#20711 Display more info when cli install fails
  install-dev/index_cli.php
Labels: Improvement, develop

#20742 Add $delta_quantity to hookActionUpdateQuantity()
  src/Core/Stock/StockManager.php
Labels: Improvement, develop

#20735 Add test 'CRUD attributes and values'
  tests/UI/campaigns/data/faker/attributeAndValue.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/03_CRUDAttributesAndValues.js
  tests/UI/pages/BO/catalog/attributes/addAttribute.js
  tests/UI/pages/BO/catalog/attributes/addValue.js
  tests/UI/pages/BO/catalog/attributes/index.js
  tests/UI/pages/BO/catalog/attributes/view.js
Labels: 1.7.7.x, Refactoring, TE

#20749 Add tests 'Filter features' and 'Filter feature values'
  tests/UI/campaigns/data/demo/features.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/02_filterAttributeValues.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/01_filterFeatures.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/02_filterFeatureValues.js
  tests/UI/pages/BO/catalog/features/index.js
  tests/UI/pages/BO/catalog/features/view.js
Labels: 1.7.7.x, Refactoring, TE

#20724 Add test 'Default pack stock management'
  tests/UI/campaigns/data/faker/product.js
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/08_defaultPackStockManagement.js
  tests/UI/pages/BO/catalog/products/add.js
  tests/UI/pages/BO/shopParameters/productSettings/index.js
Labels: 1.7.7.x, Refactoring, TE

#20106 Multistore: assign a color to a shop
  classes/shop/Shop.php
  controllers/admin/AdminShopController.php
  install-dev/upgrade/sql/1.7.8.0.sql
  src/PrestaShopBundle/Entity/Shop.php
Labels: Feature, develop, waiting for author, waiting for dev

#20758 fix cumulative percentage behat test
  tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/percent_multiple.feature
Labels: 1.7.7.x, Bug

#20759 Add test 'Bulk delete attributes'
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/04_bulkDeleteAttributes.js
  tests/UI/pages/BO/catalog/attributes/index.js
Labels: 1.7.7.x, Refactoring, TE

#20729 Fix price width is too small on some devices by setting a min-width
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/pages/_orders_view.scss
Labels: 1.7.7.x, Bug, QA ✔️, waiting for dev

#20721 Add property free_shipping to presented cart to ease FO usage
  src/Adapter/Presenter/Cart/CartPresenter.php
Labels: Improvement, develop

#20755 Fix free shipping cart rules not added/deleted in create order
  admin-dev/themes/new-theme/js/pages/order/create/create-order-page.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  src/Adapter/Cart/CommandHandler/SetFreeShippingToCartHandler.php
  src/Adapter/Cart/CommandHandler/UpdateCartCarrierHandler.php
  src/PrestaShopBundle/Resources/config/services/adapter/cart.yml
Labels: 1.7.7.x, Bug, QA ✔️

#18787 Add compatibility to PHP 7.4
  .travis.yml
  classes/Address.php
  classes/Connection.php
  classes/Currency.php
  classes/Employee.php
  classes/Language.php
  classes/ObjectModel.php
  classes/Page.php
  classes/Profile.php
  classes/QuickAccess.php
  classes/module/Module.php
  classes/order/OrderCarrier.php
  classes/stock/SupplyOrder.php
  classes/stock/SupplyOrderDetail.php
  composer.lock
  controllers/admin/AdminShopController.php
  controllers/front/CartController.php
  controllers/front/ProductController.php
  controllers/front/listing/SearchController.php
  install-dev/data/xml/profile.xml
  install-dev/fixtures/fashion/data/profile.xml
  install-dev/fixtures/fashion/langs/fr/data/profile.xml
  install-dev/install_version.php
  src/Adapter/EntityMapper.php
  src/Adapter/Module/ModuleDataProvider.php
  src/PrestaShopBundle/Command/UpdateLicensesCommand.php
  src/PrestaShopBundle/Install/XmlLoader.php
  tests-legacy/PrestaShopBundle/Utils/DatabaseCreator.php
  tests/Unit/Core/Webservice/ServerRequirementsCheckerTest.php
  themes/classic/modules/ps_shoppingcart/modal.tpl
  themes/classic/templates/catalog/_partials/category-header.tpl
  themes/classic/templates/catalog/_partials/miniatures/pack-product.tpl
  themes/classic/templates/catalog/_partials/product-images-modal.tpl
  themes/classic/templates/catalog/product.tpl
  themes/classic/templates/checkout/_partials/cart-summary-product-line.tpl
  tools/build/Library/InstallUnpacker/index_template.php
Labels: Improvement, Key feature, develop

#20145 Product management and specific prices new rules in Order
  admin-dev/themes/new-theme/js/fos_js_routes.json
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js
  admin-dev/themes/new-theme/js/pages/order/view/order-prices-refresher.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add-autocomplete.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-edit.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js
  admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  classes/Product.php
  classes/SpecificPrice.php
  src/Adapter/Order/AbstractOrderHandler.php
  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
  src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php
  src/Adapter/Order/OrderAmountUpdater.php
  src/Adapter/Order/OrderProductQuantityUpdater.php
  src/Adapter/Order/Refund/OrderProductRemover.php
  src/Adapter/Product/QueryHandler/SearchProductsHandler.php
  src/Core/Domain/Order/Exception/DuplicateProductInOrderException.php
  src/Core/Domain/Product/Query/SearchProducts.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/AddProductRowType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/edit_product_row.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig
  tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Delivery/delivery_options.feature
  tests/Integration/Behaviour/Features/Scenario/Order/duplicate_products.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_cancel_product.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_cart_rules.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_out_of_stock.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_specific_prices.feature
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️

#20684 Fix empty optional customization exception when creating BO order
  src/Adapter/Cart/CommandHandler/AddProductToCartHandler.php
Labels: 1.7.7.x, Bug, QA ✔️

#20738 Disable jquery migrate deprecation messages when prestashop debug mode is off
  classes/controller/AdminController.php
  classes/controller/FrontController.php
  js/jquery/bo-migrate-mute.js
  js/jquery/bo-migrate-mute.min.js
  themes/_core/js/migrate-mute.js
  themes/_core/js/theme.js
  themes/core.js
  themes/core.js.map
Labels: 1.7.7.x, Improvement, QA ✔️

#20714 Fix max attribute on qty input of an out of stock attribute available on create order
  admin-dev/themes/new-theme/js/pages/order/create/product-manager.js
  admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js
  admin-dev/themes/new-theme/public/address.bundle.js
  admin-dev/themes/new-theme/public/attachment.bundle.js
  admin-dev/themes/new-theme/public/attribute.bundle.js
  admin-dev/themes/new-theme/public/attribute_group.bundle.js
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/catalog_price_rule.bundle.js
  admin-dev/themes/new-theme/public/catalog_price_rule_form.bundle.js
  admin-dev/themes/new-theme/public/catalog_product.bundle.js
  admin-dev/themes/new-theme/public/category.bundle.js
  admin-dev/themes/new-theme/public/cms_page.bundle.js
  admin-dev/themes/new-theme/public/cms_page_form.bundle.js
  admin-dev/themes/new-theme/public/contacts.bundle.js
  admin-dev/themes/new-theme/public/credit_slip.bundle.js
  admin-dev/themes/new-theme/public/currency.bundle.js
  admin-dev/themes/new-theme/public/currency_form.bundle.js
  admin-dev/themes/new-theme/public/customer.bundle.js
  admin-dev/themes/new-theme/public/customer_address_form.bundle.js
  admin-dev/themes/new-theme/public/customer_thread_view.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/employee.bundle.js
  admin-dev/themes/new-theme/public/employee_form.bundle.js
  admin-dev/themes/new-theme/public/error.bundle.js
  admin-dev/themes/new-theme/public/feature_form.bundle.js
  admin-dev/themes/new-theme/public/form_popover_error.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/improve_design_positions.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/language.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/maintenance.bundle.js
  admin-dev/themes/new-theme/public/manufacturer.bundle.js
  admin-dev/themes/new-theme/public/manufacturer_address_form.bundle.js
  admin-dev/themes/new-theme/public/merchandise_return.bundle.js
  admin-dev/themes/new-theme/public/meta.bundle.js
  admin-dev/themes/new-theme/public/module.bundle.js
  admin-dev/themes/new-theme/public/module_card.bundle.js
  admin-dev/themes/new-theme/public/monitoring.bundle.js
  admin-dev/themes/new-theme/public/order.bundle.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_page.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/profiles.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/supplier_form.bundle.js
  admin-dev/themes/new-theme/public/tax.bundle.js
  admin-dev/themes/new-theme/public/themes.bundle.js
  admin-dev/themes/new-theme/public/translation_settings.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
Labels: 1.7.7.x, Bug, QA ✔️

#20693 Cancel/Refunds... adding missing hooks and cancel product refactor
  src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php
  src/Adapter/Order/CommandHandler/IssuePartialRefundHandler.php
  src/Adapter/Order/CommandHandler/IssueReturnProductHandler.php
  src/Adapter/Order/CommandHandler/IssueStandardRefundHandler.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_cancel_product.feature
Labels: 1.7.7.x, Bug, QA ✔️

#20603 Redirect to customer when canceling new customer address creation
  src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig
Labels: 1.7.7.x, Bug, QA ✔️

#20704 Expose missing route
  admin-dev/themes/new-theme/js/fos_js_routes.json
  admin-dev/themes/new-theme/public/currency_form.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/order.bundle.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
Labels: 1.7.7.x, Bug, QA ✔️
