Repository PrestaShop/PrestaShop, pull requests merged in 2020-05, with the labels that each got.

#18868 Functional tests - Change selectors for modules pages
  tests/puppeteer/campaigns/upgrade/upgradeShop.js
  tests/puppeteer/pages/BO/modules/moduleCatalog/index.js
  tests/puppeteer/pages/BO/modules/moduleManager/index.js
Labels: 1.7.7.x, Refactoring, TE

#18896 Functional tests - Change selectors for design pages
  tests/puppeteer/pages/BO/design/emailThemes/index.js
  tests/puppeteer/pages/BO/design/linkWidgets/add.js
  tests/puppeteer/pages/BO/design/linkWidgets/index.js
  tests/puppeteer/pages/BO/design/pages/add.js
  tests/puppeteer/pages/BO/design/pages/index.js
  tests/puppeteer/pages/BO/design/pages/pageCategory/add.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#18886 Functional tests - Fix test invoices and products settings
  tests/puppeteer/campaigns/data/demo/invoices.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/02_generateInvoiceByStatus.js
  tests/puppeteer/pages/BO/catalog/products/add.js
  tests/puppeteer/pages/BO/orders/invoices/index.js
Labels: 1.7.7.x, Refactoring, TE

#18963 Functional tests - Test page category pagination
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/08_categoryPagination.js
  tests/puppeteer/pages/BO/design/pages/index.js
Labels: 1.7.7.x, Refactoring, TE

#18962 Use progress format for Behat
  composer.json
Labels: Improvement, develop

#18871 Functional tests - Update default currency
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/04_defaultCurrency.js
  tests/puppeteer/pages/BO/international/localization/index.js
  tests/puppeteer/pages/FO/FObasePage.js
Labels: 1.7.7.x, Refactoring, TE

#18899 Functional tests - Country restrictions
  tests/puppeteer/campaigns/functional/BO/10_payment/02_preferences/03_countryRestrictions.js
  tests/puppeteer/pages/BO/payment/preferences/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#18877 Functional tests - Change selectors for FO pages
  tests/puppeteer/pages/FO/FObasePage.js
  tests/puppeteer/pages/FO/cart/index.js
  tests/puppeteer/pages/FO/checkout/index.js
  tests/puppeteer/pages/FO/home/index.js
  tests/puppeteer/pages/FO/login/index.js
  tests/puppeteer/pages/FO/myAccount/orderHistory.js
  tests/puppeteer/pages/FO/product/index.js
  tests/puppeteer/pages/FO/searchResults/index.js
  tests/puppeteer/pages/FO/siteMap/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#18977 Functional tests - Test pages pagination
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/09_pagesPagination.js
  tests/puppeteer/pages/BO/design/pages/index.js
Labels: 1.7.7.x, Refactoring, TE

#18990 Functional tests - Enable/Disable log emails
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/04_email/02_enableDisableLogEmails.js
  tests/puppeteer/pages/BO/advancedParameters/email/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#18986 Remove useless old call to addons
  admin-dev/ajax.php
Labels: Improvement, develop

#18988 Add phpdoc to class Curve
  classes/Curve.php
Labels: Improvement, develop

#18974 Remove Scrutinizer Config file as it seems to be disabled
  .scrutinizer.yml
Labels: Improvement, develop

#18979 Update Smarty 3.1.34 -> 3.1.36
  composer.lock
Labels: Improvement, develop

#18998 Merge 1.7.7.x into develop - 06/05/2020
  src/PrestaShopBundle/Model/Product/AdminModelAdapter.php
  tests/puppeteer/campaigns/data/demo/invoices.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/02_generateInvoiceByStatus.js
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/09_viewEditVoucher.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/08_categoryPagination.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/09_pagesPagination.js
  tests/puppeteer/campaigns/functional/BO/10_payment/02_preferences/03_countryRestrictions.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/04_defaultCurrency.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/04_email/02_enableDisableLogEmails.js
  tests/puppeteer/campaigns/upgrade/upgradeShop.js
  tests/puppeteer/pages/BO/advancedParameters/email/index.js
  tests/puppeteer/pages/BO/catalog/discounts/add.js
  tests/puppeteer/pages/BO/catalog/products/add.js
  tests/puppeteer/pages/BO/customerService/orderMessages/add.js
  tests/puppeteer/pages/BO/customerService/orderMessages/index.js
  tests/puppeteer/pages/BO/customers/add.js
  tests/puppeteer/pages/BO/customers/addresses/index.js
  tests/puppeteer/pages/BO/customers/index.js
  tests/puppeteer/pages/BO/customers/view.js
  tests/puppeteer/pages/BO/design/emailThemes/index.js
  tests/puppeteer/pages/BO/design/linkWidgets/add.js
  tests/puppeteer/pages/BO/design/linkWidgets/index.js
  tests/puppeteer/pages/BO/design/pages/add.js
  tests/puppeteer/pages/BO/design/pages/index.js
  tests/puppeteer/pages/BO/design/pages/pageCategory/add.js
  tests/puppeteer/pages/BO/international/currencies/add.js
  tests/puppeteer/pages/BO/international/currencies/index.js
  tests/puppeteer/pages/BO/international/languages/add.js
  tests/puppeteer/pages/BO/international/languages/index.js
  tests/puppeteer/pages/BO/international/localization/index.js
  tests/puppeteer/pages/BO/international/taxes/add.js
  tests/puppeteer/pages/BO/international/taxes/index.js
  tests/puppeteer/pages/BO/international/taxes/taxRules/add.js
  tests/puppeteer/pages/BO/modules/moduleCatalog/index.js
  tests/puppeteer/pages/BO/modules/moduleManager/index.js
  tests/puppeteer/pages/BO/orders/invoices/index.js
  tests/puppeteer/pages/BO/payment/preferences/index.js
  tests/puppeteer/pages/BO/shopParameters/contact/add.js
  tests/puppeteer/pages/BO/shopParameters/contact/index.js
  tests/puppeteer/pages/BO/shopParameters/customerSettings/index.js
  tests/puppeteer/pages/BO/shopParameters/general/index.js
  tests/puppeteer/pages/BO/shopParameters/general/maintenance/index.js
  tests/puppeteer/pages/BO/shopParameters/orderSettings/index.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
  tests/puppeteer/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/add.js
  tests/puppeteer/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/index.js
  tests/puppeteer/pages/FO/FObasePage.js
  tests/puppeteer/pages/FO/cart/index.js
  tests/puppeteer/pages/FO/checkout/index.js
  tests/puppeteer/pages/FO/home/index.js
  tests/puppeteer/pages/FO/login/index.js
  tests/puppeteer/pages/FO/myAccount/orderHistory.js
  tests/puppeteer/pages/FO/product/index.js
  tests/puppeteer/pages/FO/searchResults/index.js
  tests/puppeteer/pages/FO/siteMap/index.js
Labels: Improvement, develop

#19004 Functional tests - Sort suppliers table
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/suppliers/04_sortSuppliers.js
  tests/puppeteer/pages/BO/catalog/suppliers/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#19006 Functional tests - Fix change selectors
  tests/puppeteer/pages/BO/advancedParameters/database/dbBackup/index.js
  tests/puppeteer/pages/BO/advancedParameters/team/index.js
  tests/puppeteer/pages/BO/advancedParameters/team/profiles/index.js
  tests/puppeteer/pages/BO/advancedParameters/webservice/index.js
  tests/puppeteer/pages/BO/catalog/brands/index.js
  tests/puppeteer/pages/BO/catalog/files/index.js
  tests/puppeteer/pages/BO/catalog/monitoring/index.js
  tests/puppeteer/pages/BO/catalog/suppliers/index.js
Labels: QA ✔️, Refactoring, TE, develop

#19025 Functional tests - Increase timeout for docker puppeteer
  tests/puppeteer/docker-compose.tests.yml
  tests/puppeteer/pages/BO/international/taxes/index.js
  tests/puppeteer/scripts/run-nightly-tests.sh
Labels: Refactoring, TE, develop

#19065 Functional tests - Fix nightly 11/05/2020
  tests/puppeteer/pages/BO/advancedParameters/email/index.js
  tests/puppeteer/pages/BO/design/pages/index.js
Labels: QA ✔️, Refactoring, TE, develop

#19066 Functional test - Add test quick edit languages
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/languages/01_filterAndQuickEditLanguages.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/international/languages/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#19074 Functional tests - Add test pagination order message
  tests/puppeteer/campaigns/functional/BO/05_customerService/02_orderMessages/01_CRUDOrderMessage.js
  tests/puppeteer/campaigns/functional/BO/05_customerService/02_orderMessages/02_filterAndBulkDeleteOrderMessages.js
  tests/puppeteer/campaigns/functional/BO/05_customerService/02_orderMessages/03_pagination.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/08_categoryPagination.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/09_pagesPagination.js
  tests/puppeteer/pages/BO/customerService/orderMessages/add.js
  tests/puppeteer/pages/BO/customerService/orderMessages/index.js
Labels: 1.7.7.x, Refactoring, TE

#19092 Functional tests - Edit home category
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/08_editHomeCategory.js
  tests/puppeteer/pages/BO/catalog/categories/add.js
  tests/puppeteer/pages/BO/catalog/categories/index.js
Labels: 1.7.7.x, Refactoring, TE

#19071 Functional tests - Add test taxes pagination
  tests/puppeteer/campaigns/functional/BO/11_international/03_taxes/06_pagination.js
  tests/puppeteer/pages/BO/international/taxes/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#18854 Update Changelog and Contributors for beta 177
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: 1.7.7.x, Improvement, waiting for wording

#18884 FO: Display 'free' as shipping cost in the cart when a cart rule grants free shipping
  src/Adapter/Presenter/Cart/CartPresenter.php
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️

#19063 Fix simplfied url not properly set for multilang categories
  classes/Category.php
Labels: 1.7.7.x, Bug, QA ✔️

#19107 Merge 1.7.7.x into develop - 13/05/2020
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/08_editHomeCategory.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/suppliers/04_sortSuppliers.js
  tests/puppeteer/campaigns/functional/BO/05_customerService/02_orderMessages/01_CRUDOrderMessage.js
  tests/puppeteer/campaigns/functional/BO/05_customerService/02_orderMessages/02_filterAndBulkDeleteOrderMessages.js
  tests/puppeteer/campaigns/functional/BO/05_customerService/02_orderMessages/03_pagination.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/08_categoryPagination.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/09_pagesPagination.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/languages/01_filterAndQuickEditLanguages.js
  tests/puppeteer/campaigns/functional/BO/11_international/03_taxes/06_pagination.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/catalog/categories/add.js
  tests/puppeteer/pages/BO/catalog/categories/index.js
  tests/puppeteer/pages/BO/catalog/suppliers/index.js
  tests/puppeteer/pages/BO/customerService/orderMessages/add.js
  tests/puppeteer/pages/BO/customerService/orderMessages/index.js
  tests/puppeteer/pages/BO/international/languages/index.js
  tests/puppeteer/pages/BO/international/taxes/index.js
Labels: Improvement, develop

#19058 Refresh invoices total when product price is updated
  admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
Labels: 1.7.7.x, Bug, QA ✔️

#19109 Functional tests - Add test subscribe to newsletter from BO
  tests/puppeteer/campaigns/data/demo/modules.js
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/09_subscribeToNewsletter.js
  tests/puppeteer/pages/BO/modules/moduleManager/index.js
  tests/puppeteer/pages/BO/modules/psEmailSubscription/index.js
Labels: 1.7.7.x, Refactoring, TE

#19088 Functional tests - Filter and sort files
  tests/puppeteer/campaigns/functional/BO/03_catalog/06_files/03_filterAndSortFiles.js
  tests/puppeteer/pages/BO/catalog/files/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#18993 Fix discount display on multicurrency context
  src/Adapter/Presenter/Cart/CartPresenter.php
Labels: 1.7.7.x, Bug, QA ✔️

#19032 Update ps_themecusto to the latest version
  composer.lock
Labels: 1.7.7.x, Bug, QA ✔️

#19115 Functional tests - Fix order message grid modal
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/customerService/orderMessages/index.js
Labels: QA ✔️, Refactoring, TE, develop

#19069 Functional tests - Profiles pagination
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/profiles/06_profilesPagination.js
  tests/puppeteer/pages/BO/advancedParameters/team/profiles/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#19127 Functional tests - Delete bo base page from sanity tests
  tests/puppeteer/campaigns/commonTests/loginBO.js
  tests/puppeteer/campaigns/sanity/02_productsBO/01_filterProducts.js
  tests/puppeteer/campaigns/sanity/02_productsBO/02_CRUDStandardProductInBO.js
  tests/puppeteer/campaigns/sanity/02_productsBO/03_CRUDStandardProductWithCombinationsInBO.js
  tests/puppeteer/campaigns/sanity/02_productsBO/04_deleteProduct.js
  tests/puppeteer/campaigns/sanity/02_productsBO/05_deleteProductsWithBulkActions.js
  tests/puppeteer/campaigns/sanity/03_ordersBO/01_filterOrders.js
  tests/puppeteer/campaigns/sanity/03_ordersBO/02_editOrder.js
Labels: 1.7.7.x, Refactoring, TE

#19039 Fix product pagination in order with customization
  admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
Labels: 1.7.7.x, Bug, QA ✔️

#19086 BO - New Product - In MultiLang BO, the default name input wasn't in the employee language
  admin-dev/themes/default/js/bundle/product/form.js
Labels: 1.7.7.x, Bug, QA ✔️

#19067 Functional tests - Sort profiles
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/profiles/05_sortProfiles.js
  tests/puppeteer/pages/BO/advancedParameters/team/profiles/index.js
Labels: 1.7.7.x, Refactoring, TE

#15871 Avoid error when trying to translate an invalid module
  src/Adapter/Translations/TranslationRouteFinder.php
  src/PrestaShopBundle/Controller/Admin/TranslationsController.php
Labels: 1.7.7.x, Bug, Bug fix, QA ✔️, Wording ✔️, develop

#19089 Fix bug keeping user from accessing his profile page in BO
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php
Labels: 1.7.7.x, Bug, QA ✔️

#19133 Functional tests - Delete boBasePage for functional tests orders
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/01_helpCard.js
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/02_filterOrders.js
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/03_exportOrders.js
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/04_checkInvoiceDownloadedFromList.js
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/05_checkDeliverySlipDownloadedFromList.js
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/06_bulkUpdateOrdersStatus.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/01_generateInvoiceByDate.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/02_generateInvoiceByStatus.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/01_enableDisableInvoices.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/02_enableDisableTaxBreakdown.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/03_enableDisableProductImage.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/04_invoicePrefix.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/05_enableDisableCurrentYear.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/06_otherOptions.js
  tests/puppeteer/campaigns/functional/BO/02_orders/03_creditSlips/01_createFilterCreditSlips.js
  tests/puppeteer/campaigns/functional/BO/02_orders/03_creditSlips/02_generateCreditSlipsByDate.js
  tests/puppeteer/campaigns/functional/BO/02_orders/03_creditSlips/03_creditSlipOptions.js
  tests/puppeteer/campaigns/functional/BO/02_orders/04_deliverySlips/01_generateDeliverySlipByDate.js
  tests/puppeteer/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/01_deliverySlipPrefix.js
  tests/puppeteer/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/02_deliverySlipNumber.js
  tests/puppeteer/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/03_enableDisableProductImage.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#19103 Redirect to dashboard when employee default page is unauthorized
  classes/Dispatcher.php
  classes/Profile.php
Labels: 1.7.7.x, Bug, QA ✔️

#19155 PHP Codestyle fix
  src/Adapter/Translations/TranslationRouteFinder.php
  src/PrestaShopBundle/Controller/Admin/TranslationsController.php
Labels: 1.7.7.x, Bug

#19027 Functional tests - Export sql query
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/03_exportSqlQuery.js
  tests/puppeteer/campaigns/utils/files.js
  tests/puppeteer/pages/BO/advancedParameters/database/sqlManager/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#19137 Functional tests - Sort order messages table
  tests/puppeteer/campaigns/functional/BO/05_customerService/02_orderMessages/03_paginationAndSortOrderMessages.js
  tests/puppeteer/pages/BO/customerService/orderMessages/index.js
Labels: 1.7.7.x, Refactoring, TE

#19157 Functional tests - Delete bo base page from invoices tests
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/01_enableDisableInvoices.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/02_enableDisableTaxBreakdown.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/05_enableDisableCurrentYear.js
Labels: 1.7.7.x, Refactoring, TE

#19159 Functional tests - Delete bo base page from international tests
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/01_importLocalizationPack.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/02_defaultLanguage.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/03_helpCard.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/04_defaultCurrency.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/currencies/01_CreateOfficialCurrency.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/currencies/02_CreateUnofficialCurrency.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/currencies/03_helpCard.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/languages/01_filterAndQuickEditLanguages.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/languages/02_CRUDLanguage.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/languages/03_bulkActionsLanguages.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/languages/04_sortLanguages.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/languages/05_helpCard.js
  tests/puppeteer/campaigns/functional/BO/11_international/03_taxes/01_filterAndQuickEditTaxes.js
  tests/puppeteer/campaigns/functional/BO/11_international/03_taxes/02_CRUDTaxesInBO.js
  tests/puppeteer/campaigns/functional/BO/11_international/03_taxes/03_taxesBulkActionsInBO.js
  tests/puppeteer/campaigns/functional/BO/11_international/03_taxes/04_taxOptionsForm.js
  tests/puppeteer/campaigns/functional/BO/11_international/03_taxes/05_sortTaxes.js
  tests/puppeteer/campaigns/functional/BO/11_international/03_taxes/06_pagination.js
  tests/puppeteer/campaigns/functional/BO/11_international/04_translations/03_exportLanguage.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#19153 Functional tests - Delete BoBasePage from payment tests
  tests/puppeteer/campaigns/functional/BO/10_payment/02_preferences/01_currencyRestrictions.js
  tests/puppeteer/campaigns/functional/BO/10_payment/02_preferences/02_groupRestrictions.js
  tests/puppeteer/campaigns/functional/BO/10_payment/02_preferences/03_countryRestrictions.js
Labels: 1.7.7.x, Refactoring, TE

#19138 Functional tests - Delete boBasePage for tests modules
  tests/puppeteer/campaigns/functional/BO/07_modules/01_moduleManager/01_filterModulesByStatus.js
  tests/puppeteer/campaigns/functional/BO/07_modules/01_moduleManager/02_filterModulesByCategories.js
  tests/puppeteer/campaigns/sanity/02_productsBO/04_deleteProduct.js
  tests/puppeteer/campaigns/sanity/02_productsBO/05_deleteProductsWithBulkActions.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#19160 Functional tests - Test addresses pagination
  tests/puppeteer/campaigns/functional/BO/04_customers/02_addresses/04_paginationAndSortAddresses.js
  tests/puppeteer/campaigns/functional/BO/04_customers/02_addresses/04_sortAddresses.js
  tests/puppeteer/pages/BO/customers/addresses/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#19158 Functional tests - Test customers pagination
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/04_paginationAndSortCustomers.js
  tests/puppeteer/pages/BO/customers/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#19021 BO - Save button design change if an error message is displayed
  controllers/admin/AdminCartRulesController.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#19154 Remove _PS_MAGIC_QUOTES_GPC_ usage
  classes/Tools.php
  classes/db/Db.php
  controllers/admin/AdminTranslationsController.php
Labels: Refactoring, develop

#19108 Extend OrderController with FrameworkBundleAdminController instead of CommonController
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
Labels: 1.7.7.x, Bug, QA ✔️, migration

#19188 Docker-compose is failing due to missing build assets
  .docker/Dockerfile
  .docker/docker_run_git.sh
Labels: Bug, QA ✔️, develop

#18964 Functional tests - Update puppeteer to version 3.0.2
  .travis.yml
  tests/puppeteer/package-lock.json
  tests/puppeteer/package.json
  travis-scripts/setup-node-js.sh
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#18613 Cart rule order tests
  install-dev/fixtures/fashion/data/carrier_tax_rules_group_shop.xml
  src/Adapter/Order/AbstractOrderHandler.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Order/Refund/OrderRefundCalculator.php
  tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/add_cart_rule_to_order.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_add_payment.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
  tests/Integration/Behaviour/Features/Scenario/Order/partial_refund.feature
  tests/Integration/Behaviour/Features/Scenario/Order/return_product.feature
  tests/Integration/Behaviour/Features/Scenario/Order/standard_refund.feature
  tests/Integration/Behaviour/Features/Transform/StringToBooleanTransform.php
Labels: 1.7.7.x, Bug, QA ✔️

#19183 Functional tests - Delete bo base page for advanced params tests
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/04_email/01_filterDeleteAndBulkActionsEmails.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/04_email/02_enableDisableLogEmails.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/04_email/03_sendTestEmail/01_sendTestEmail.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/05_import/01_downloadSampleFiles.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/employees/01_filterAndQuickEditEmployees.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/employees/02_CRUDEmployee.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/employees/03_employeesBulkActions.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/employees/04_helpCard.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/profiles/01_filterProfiles.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/profiles/02_CRUDProfile.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/profiles/03_profileBulkActions.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/profiles/04_helpCard.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/profiles/05_sortProfiles.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/profiles/06_profilesPagination.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/07_database/dbBackup/01_CreateAndDeleteDbBackup.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/07_database/dbBackup/02_bulkDeleteDbBackups.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/07_database/dbBackup/03_helpCard.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/01_CRUDSqlQuery.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/02_helpCard.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/03_exportSqlQuery.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/09_webservice/01_CRUDWebservice.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/09_webservice/02_filterAndQuickEditWebservice.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/09_webservice/03_helpCard.js
Labels: 1.7.7.x, Refactoring, TE

#19185 Functional tests - Delete BoBasePage from order messages tests
  tests/puppeteer/campaigns/functional/BO/05_customerService/02_orderMessages/01_CRUDOrderMessage.js
  tests/puppeteer/campaigns/functional/BO/05_customerService/02_orderMessages/02_filterAndBulkDeleteOrderMessages.js
  tests/puppeteer/campaigns/functional/BO/05_customerService/02_orderMessages/03_paginationAndSortOrderMessages.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#19194 Functional tests - Delete bo base page customers tests
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/01_filterAndQuickEditCustomers.js
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/02_CRUDCustomerInBO.js
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/03_customersBulkActionsInBO.js
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/04_paginationAndSortCustomers.js
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/04_sortCustomers.js
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/05_setRequiredFields.js
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/06_exportCustomers.js
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/07_helpCard.js
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/08_viewCustomer.js
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/09_subscribeToNewsletter.js
  tests/puppeteer/campaigns/functional/BO/04_customers/02_addresses/01_filterAddresses.js
  tests/puppeteer/campaigns/functional/BO/04_customers/02_addresses/02_CRUDAddressInBO.js
  tests/puppeteer/campaigns/functional/BO/04_customers/02_addresses/03_addressesBulkActions.js
  tests/puppeteer/campaigns/functional/BO/04_customers/02_addresses/04_paginationAndSortAddresses.js
  tests/puppeteer/campaigns/functional/BO/04_customers/02_addresses/05_helpCard.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#19050 Delivery and billing address were displayed wrong.
  mails/themes/classic/core/order_conf.html.twig
Labels: Bug, QA ✔️, Wording ✔️, develop

#19020 BO - Catalog price rule - Currency sort and filter not working as expected #19014
  controllers/admin/AdminSpecificPriceRuleController.php
Labels: Bug, QA ✔️, develop

#19191 When the thread refers to a product, the generated link are wrong
  controllers/admin/AdminCustomerThreadsController.php
Labels: Bug, QA ✔️, develop

#19140 Fix partial refund display issues in order page (BO)
  admin-dev/themes/new-theme/scss/pages/_orders.scss
Labels: Bug, QA ✔️, develop

#19205 Backport bugfixes 19020 and 19021 for 1.7.7.x
  controllers/admin/AdminCartRulesController.php
  controllers/admin/AdminSpecificPriceRuleController.php
Labels: 1.7.7.x, Bug, QA ✔️

#18997 Add hook in module uninstall process - port of #8868 - thanks @Nermendis
  classes/module/Module.php
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.8.0.sql
Labels: Feature, QA ✔️, develop

#15614 Fix of new customer message
  classes/PaymentModule.php
Labels: Bug, PM ✔️, QA ✔️, develop

#18362 Grid row delete confirmation modal - Advanced parameters > DB > SQL Requests
  admin-dev/themes/new-theme/js/pages/sql-manager/index.js
  src/Core/Grid/Definition/Factory/DeleteActionTrait.php
  src/Core/Grid/Definition/Factory/RequestSqlGridDefinitionFactory.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/sql_request.yml
Labels: Improvement, QA ✔️, develop, migration

#18235 Improve prestashop:linter:security-annotation
  src/PrestaShopBundle/Command/SecurityAnnotationLinterCommand.php
  src/PrestaShopBundle/Routing/Linter/SecurityAnnotationLinter.php
Labels: Feature, develop

#18989 Add phpdoc for ChecksumInterface and CartChecksum
  classes/ChecksumInterface.php
  classes/checkout/CartChecksum.php
Labels: Improvement, develop

#18259 Update phpdoc Product class
  classes/Product.php
Labels: Refactoring, develop

#19186 Functional tests - Test pagination of categories table
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/05_paginationAndSortCategories.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/05_sortCategories.js
  tests/puppeteer/pages/BO/catalog/categories/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#19203 Functional tests - Pagination brands and addresses
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/06_paginationAndSortBrandsAndAddresses.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/06_sortBrandsAndAddresses.js
  tests/puppeteer/pages/BO/catalog/brands/index.js
Labels: 1.7.7.x, Refactoring, TE

#18876 Remove array to string conversion in bulk delete address faulty usecase
  src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php
Labels: Bug, QA ✔️, develop

#18519 Missing log datas in some controllers and classes
  src/Adapter/HookManager.php
  src/Adapter/Module/ModuleDataProvider.php
  src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Service/TranslationService.php
Labels: Bug, QA ✔️, develop

#19223 Functional tests - Delete test filter stocks by categories
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/05_filterStocksByCategory.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#19202 Functional tests - Delete bo base page from catalog tests
  tests/puppeteer/campaigns/functional/BO/03_catalog/01_products/01_filterAndQuickEditProducts.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/01_products/02_sortProducts.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/01_filterAndQuickEditCategories.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/02_CRUDCategoryInBO.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/03_categoriesBulkAction.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/04_changeCategoryPosition.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/05_sortCategories.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/06_helperCard.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/07_exportCategories.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/08_editHomeCategory.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/03_monitoring/01_deleteEmptyCategory.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/03_monitoring/02_monitoringProducts.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/03_monitoring/03_helpCard.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/03_monitoring/04_sortListOfEmptyCategories.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/03_monitoring/05_sortProductsNoQuantityWithCombination.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/03_monitoring/06_sortProductsNoQuantityWithoutCombination.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/03_monitoring/07_sortDisabledProducts.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/03_monitoring/08_sortProductsWithoutImage.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/03_monitoring/09_sortProductsWithoutDescription.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/03_monitoring/10_sortProductsWithoutPrice.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/01_filterAndQuickEditBrands.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/02_filterBrandAddresses.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/03_CRUDBrandAndAddress.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/04_BulkActionsBrands.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/05_BulkActionsBrandAddresses.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/06_sortBrandsAndAddresses.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/07_exportBrands.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/08_helperCard.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/suppliers/01_CRUDSupplier.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/suppliers/02_filterQuickEditAndBulkActionsSupplier.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/suppliers/03_helperCard.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/suppliers/04_sortSuppliers.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/06_files/01_CRUDFile.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/06_files/02_fileBulkActions.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/06_files/03_filterAndSortFiles.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/01_simpleFilterStocks.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/02_updateQuantity.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/03_bulkEditQuantity.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/04_filterStocksByStatus.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/06_helpCard.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#18984 Remove legacy files for Order page
  admin-dev/themes/default/template/controllers/orders/_customized_data.tpl
  admin-dev/themes/default/template/controllers/orders/_discount_form.tpl
  admin-dev/themes/default/template/controllers/orders/_documents.tpl
  admin-dev/themes/default/template/controllers/orders/_new_product.tpl
  admin-dev/themes/default/template/controllers/orders/_print_pdf_icon.tpl
  admin-dev/themes/default/template/controllers/orders/_product_line.tpl
  admin-dev/themes/default/template/controllers/orders/_select_payment.tpl
  admin-dev/themes/default/template/controllers/orders/_shipping.tpl
  admin-dev/themes/default/template/controllers/orders/form.tpl
  admin-dev/themes/default/template/controllers/orders/form_customization_feedback.tpl
  admin-dev/themes/default/template/controllers/orders/helpers/index.php
  admin-dev/themes/default/template/controllers/orders/helpers/list/index.php
  admin-dev/themes/default/template/controllers/orders/helpers/list/list_header.tpl
  admin-dev/themes/default/template/controllers/orders/helpers/view/index.php
  admin-dev/themes/default/template/controllers/orders/helpers/view/view.tpl
  admin-dev/themes/default/template/controllers/orders/index.php
  controllers/admin/AdminOrdersController.php
  js/admin/orders.js
  tests-legacy/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
  tests-legacy/PrestaShopBundle/Controller/ControllerTest.php
Labels: 1.7.7.x, QA ✔️, Refactoring, migration

#18811 Introduce CompilerPass to perform ControllerAwareTrait injection
  app/config/config.yml
  src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php
  src/PrestaShopBundle/DependencyInjection/Compiler/ContainerInjectionPass.php
  src/PrestaShopBundle/PrestaShopBundle.php
  src/PrestaShopBundle/Resources/config/services/bundle/controller.yml
Labels: 1.7.7.x, Bug, QA ✔️

#19206 Functional tests - Delete bo base page from design tests
  tests/puppeteer/campaigns/functional/BO/08_design/03_emailThemes/01_previewEmailThemes.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/01_filterAndQuickEditPages.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/02_CRUDPageCategory.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/03_categoriesBulkActions.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/04_filterAndQuickEditCategories.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/05_pagesBulkActions.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/06_helperCard.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/07_sortPages.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/08_categoryPagination.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/09_pagesPagination.js
  tests/puppeteer/campaigns/functional/BO/08_design/07_linkWidget/01_CreateAndCheckFooterLinkWidget.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#18923 Multistore: Fix error when viewing an order with custom product made on secondary shop
  classes/order/Order.php
Labels: 1.7.7.x, Bug, QA ✔️

#18456 Update cart currency when order currency changes
  classes/Product.php
  classes/SpecificPrice.php
  install-dev/fixtures/fashion/data/order_detail.xml
  install-dev/fixtures/fashion/data/orders.xml
  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
  src/Adapter/Order/CommandHandler/ChangeOrderCurrencyHandler.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
Labels: 1.7.7.x, Bug, QA ✔️, migration

#19195 Add breadcrumb to Stores & Sitemap front controllers
  controllers/front/SitemapController.php
  controllers/front/StoresController.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#19026 Enable drag-and-drop for Grid listings in both directions
  admin-dev/themes/new-theme/js/components/grid/extension/position-extension.js
  src/Core/Grid/Presenter/GridPresenter.php
  src/PrestaShopBundle/Twig/Extension/GridExtension.php
Labels: Bug, QA ✔️, develop, migration

#18895 Fix Maintenance Mode
  classes/controller/FrontController.php
Labels: Improvement, QA ✔️, develop

#19210 Functional tests - Test pagination of files table
  tests/puppeteer/campaigns/functional/BO/03_catalog/06_files/03_filterPaginationAndSortFiles.js
  tests/puppeteer/pages/BO/catalog/files/index.js
Labels: 1.7.7.x, Refactoring, TE

#18975 BO - Customer View page - Added Green alert when editing a voucher
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
Labels: 1.7.6.x, Bug, QA ✔️, Wording ✔️

#19080 Change product status in the BO search results
  controllers/admin/AdminSearchController.php
Labels: Bug, PM ✔️, QA ✔️, Wording ✔️, develop

#19279 Fix minor code issue in Language.php
  classes/Language.php
Labels: Refactoring, develop

#19257 Functional tests - Delete bo base page shop params tests
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/01_general/general/08_enableDisableSuppliers.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/01_general/general/09_enableDisableBrands.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/01_general/general/11_enableDisableMultistore.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/01_general/maintenance/01_enableDisableShop.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/01_enableFinalSummary.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/02_enableGuestCheckout.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/03_disableReorderingOption.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/04_minimumPurchaseTotalRequired.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/06_termsOfService.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/giftOptions/01_giftOptions.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/01_catalogMode.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/02_newDaysNumber.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/03_maxSizeShortDescription.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/04_quantityDiscountsBasedOn.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/05_forceUpdateFriendlyURL.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/06_defaultActivationStatus.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/01_displayAvailableQuantities.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/02_displayRemainingQuantities.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/03_displayUnavailableProductAttributes.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/05_separatorOfAttributeAnchor.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/06_displayDiscountedPrice.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/01_allowOrderingOutOfStock.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/02_enableStockManagement.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/03_labelOfInStockProducts.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/04_labelOutOfStock.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/06_enableDeliveryTimeInStockProducts.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/07_enableDeliveryTimeOutOfStockProducts.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/04_pagination/01_updateNumberOfProductsPerPage.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/04_pagination/02_updateDefaultProductsOrder.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/01_redisplayCartAtLogin.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/02_sendEmailAfterRegistration.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/04_enableB2BMode.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/05_askForBirthDate.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/06_enablePartnerOffers.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/05_contact/01_filterContacts.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/05_contact/02_CRUDContact.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/05_contact/03_contactBulkActions.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/05_contact/04_sortContacts.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/seoAndUrls/01_filterSeoPages.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/seoAndUrls/02_CRUDSeoPage.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/seoAndUrls/03_enableDisableFriendlyURL.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/seoAndUrls/04_enableDisableAccentedURL.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/seoAndUrls/05_helperCard.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#19268 Functional test - Fix Sql queries tests
  tests/puppeteer/pages/BO/advancedParameters/database/sqlManager/index.js
Labels: QA ✔️, Refactoring, TE, develop

#19208 Functional tests - Test pagination of suppliers table
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/suppliers/04_paginationAndSortSuppliers.js
  tests/puppeteer/pages/BO/catalog/suppliers/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#19235 Functional tests - Test pagination and sort of pages and categories
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/07_paginationAndSortPages.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/07_sortPages.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/08_paginationAndSortCategories.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#19275 Functional tests - Update linkchecker
  tests/puppeteer/campaigns/tools/linkchecker.js
  tests/puppeteer/campaigns/tools/urls.js
  tests/puppeteer/campaigns/utils/files.js
  tests/puppeteer/package.json
  tests/puppeteer/tools/linkchecker.js
Labels: QA ✔️, Refactoring, TE, develop

#19339 Functional tests - Update tests contexts
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/02_filterOrders.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/04_invoicePrefix.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/01_filterAndQuickEditCategories.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/03_monitoring/04_sortListOfEmptyCategories.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/03_CRUDBrandAndAddress.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/06_files/03_filterPaginationAndSortFiles.js
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/08_viewCustomer.js
  tests/puppeteer/campaigns/functional/BO/10_payment/02_preferences/02_groupRestrictions.js
  tests/puppeteer/campaigns/functional/BO/11_international/03_taxes/04_taxOptionsForm.js
  tests/puppeteer/campaigns/functional/BO/11_international/03_taxes/05_sortTaxes.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/01_general/maintenance/01_enableDisableShop.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/04_minimumPurchaseTotalRequired.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/01_allowOrderingOutOfStock.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/04_labelOutOfStock.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/05_contact/03_contactBulkActions.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/seoAndUrls/04_enableDisableAccentedURL.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/07_database/dbBackup/01_CreateAndDeleteDbBackup.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/07_database/dbBackup/02_bulkDeleteDbBackups.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/01_CRUDSqlQuery.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/03_exportSqlQuery.js
  tests/puppeteer/campaigns/sanity/02_productsBO/05_deleteProductsWithBulkActions.js
Labels: 1.7.7.x, Refactoring, TE

#19343 Fix minor code issue in BulkDeleteAttachmentsException
  src/Core/Domain/Attachment/Exception/BulkDeleteAttachmentsException.php
Labels: Refactoring, develop

#19347 Use Country from global namespace
  src/Adapter/Presenter/Cart/CartPresenter.php
Labels: 1.7.7.x, Bug, develop

#17502 Fix cart voucher values in cart summary and checkout summary
  classes/CartRule.php
  src/Adapter/Presenter/Cart/CartPresenter.php
Labels: 1.7.7.x, Bug, QA ✔️

#18739 Add a condition to avoid currency name repeat
  themes/classic/modules/ps_currencyselector/ps_currencyselector.tpl
Labels: Bug, QA ✔️, develop

#19390 Small improvements for WebserviceRequest class
  classes/webservice/WebserviceRequest.php
Labels: Improvement, develop

#19392 Remove useless variable and fix typo
  classes/controller/AdminController.php
Labels: Refactoring, develop

#19391 Remove useless variable from FromController::init()
  classes/controller/FrontController.php
Labels: Refactoring, develop

#19402 Rename and deprecate confusing method in classes/Configuration.php
  classes/Configuration.php
  classes/ConfigurationKPI.php
Labels: Refactoring, develop

#18875 BO - Create Order page - Defined the order status relative to payment
  src/Core/Domain/Order/Command/AddOrderFromBackOfficeCommand.php
  src/Core/Domain/Order/Exception/InvalidOrderStateException.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️

#19270 Functional tests - Fix display footer hook id
  tests/puppeteer/campaigns/data/demo/hooks.js
  tests/puppeteer/campaigns/data/demo/linkWidgets.js
  tests/puppeteer/campaigns/functional/BO/08_design/07_linkWidget/01_CreateAndCheckFooterLinkWidget.js
Labels: QA ✔️, Refactoring, TE, develop

#19298 Add missing breadcrumb links in order pages: confirmation/return/follow, cart and addresses pages
  controllers/front/AddressController.php
  controllers/front/OrderConfirmationController.php
  controllers/front/OrderFollowController.php
  controllers/front/OrderReturnController.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#19361 Fixed the SMTP Configuration Toggler
  admin-dev/themes/new-theme/js/pages/email/smtp-configuration-toggler.js
Labels: Bug, QA ✔️, develop

#19411 Functional tests - Using only symbol to select currency in FO
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/01_importLocalizationPack.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/currencies/01_CreateOfficialCurrency.js
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/currencies/02_CreateUnofficialCurrency.js
  tests/puppeteer/campaigns/tools/linkchecker.js
  tests/puppeteer/pages/FO/FObasePage.js
Labels: Refactoring, TE, develop

#19037 Fixed BackOffice Notification when Settings disable it
  src/Adapter/Notification/QueryHandler/GetNotificationLastElementsHandler.php
  src/PrestaShopBundle/Resources/config/services/adapter/notification.yml
Labels: Bug, QA ✔️, develop

#19409 Add missing index.php in upload directory
  .gitignore
  upload/index.php
Labels: 1.7.7.x, Bug

#19338 Fix options in CustomerAddressType
  src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php
Labels: Bug, QA ✔️, develop

#18399 Fix create order customers not being rendered
  admin-dev/themes/new-theme/js/pages/order/create/address-validator.js
  admin-dev/themes/new-theme/js/pages/order/create/customer-renderer.js
Labels: Bug, QA ✔️, develop

#19274 Add a missing comma in 1.7.7.0 upgrade file
  install-dev/upgrade/sql/1.7.7.0.sql
Labels: 1.7.7.x, Bug, QA ✔️

#17046 Make Mbstring extension required
  classes/ConfigurationTest.php
  composer.json
  composer.lock
Labels: Bug, QA ✔️, develop

#19216 Fix to show the Modules tab in the product editor
  src/PrestaShopBundle/Twig/HookExtension.php
Labels: Bug, PM ✔️, QA ✔️, develop

#19450 Add phpdoc for throws - Link
  classes/Link.php
Labels: Refactoring, develop

#19389 Extract SQL logic from WebserviceRequest to unit test it
  classes/webservice/SQLUtils.php
  classes/webservice/WebserviceRequest.php
  tests-legacy/Unit/Classes/WebserviceSQLUtilsTest.php
Labels: Improvement, develop

#18992 Improve prestashop.core.query_bus service to use parent
  src/PrestaShopBundle/Resources/config/services/core/command_bus.yml
Labels: Improvement, develop

#19452 Backport 19216 to 1.7.7.x
  src/PrestaShopBundle/Twig/HookExtension.php
Labels: 1.7.7.x, Bug

#19449 Validate lengths of fields submitted from addresse form
  classes/form/AbstractForm.php
Labels: QA ✔️, Refactoring, Wording ✔️, develop

#19434 Fix : "update address" page title is changed when an error is triggered
  controllers/front/AddressController.php
Labels: Bug, QA ✔️, develop
