Repository PrestaShop/PrestaShop, pull requests merged in 2020-03, with the labels that each got.

#17457 Disable add-to-cart button when product/attribute combination is not available
  themes/_core/js/product.js
  themes/core.js
  themes/core.js.map
Labels: 1.7.6.x, Bug, QA ✔️

#17910 Functional tests - Improving FO tests by adding wait for cart to disappear
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/04_quantityDiscountsBasedOn.js
  tests/puppeteer/pages/BO/catalog/products/add.js
  tests/puppeteer/pages/FO/product.js
Labels: 1.7.7.x, Refactoring, TE

#17915 Increase prestashop version
  app/AppKernel.php
  install-dev/install_version.php
Labels: 1.7.6.x, Improvement

#17889 Add displayAdditionalCustomerAddressFields hook during update
  install-dev/upgrade/sql/1.7.7.0.sql
Labels: 1.7.7.x, Improvement

#17925 Changelog 1.7.6.4
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: 1.7.6.x, Improvement

#17931 Missing extends in the new ValueObject\Email class
  src/Core/Domain/Customer/ValueObject/Email.php
Labels: 1.7.6.x, Bug

#17960 Functional tests - Accept GDPR if only exist
  tests/puppeteer/pages/FO/login.js
Labels: 1.7.7.x, Refactoring, TE

#17948 Functional tests - Fix problem of generate files by date for nightly 29-02
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/01_generateInvoiceByDate.js
  tests/puppeteer/campaigns/functional/BO/02_orders/03_creditSlips/02_generateCreditSlipsByDate.js
  tests/puppeteer/campaigns/functional/BO/02_orders/04_deliverySlips/01_generateDeliverySlipByDate.js
Labels: 1.7.7.x, Refactoring, TE

#16813 Add support for non-unity MySQL autoincrement
  .travis.yml
  classes/db/Db.php
  classes/db/DbMySQLi.php
  classes/db/DbPDO.php
  src/PrestaShopBundle/Install/Database.php
  src/PrestaShopBundle/Install/Install.php
  tests/Integration/Behaviour/Features/Context/Domain/CategoryFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Category/category_management.feature
  tests/Integration/Behaviour/Features/Scenario/Customer/customer_management.feature
Labels: Improvement, develop

#17777 Category update position test refactored to use generated position
  tests/Integration/Behaviour/Features/Context/Domain/CategoryFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Category/category_management.feature
Labels: Refactoring, develop

#17974 Functional tests - Refacto product settings display available quantities
  tests/puppeteer/.eslintrc.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/01_displayAvailableQuantities.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
  tests/puppeteer/pages/commonPage.js
Labels: 1.7.7.x, Refactoring, TE

#17989 Functional tests - Refacto product settings display remaining quantities
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/02_displayRemainingQuantities.js
Labels: 1.7.7.x, Refactoring, TE

#17996 Functional tests - Refacto product settings catalog mode
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/01_catalogMode.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/01_enableDisableCatalogMode.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
  tests/puppeteer/pages/FO/product.js
Labels: 1.7.7.x, Refactoring, TE

#17997 Functional tests- Refacto product settings new days number
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/02_newDaysNumber.js
Labels: 1.7.7.x, Refactoring, TE

#17998 Functional tests - Refacto product settings force update friendly URL
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/05_enableDisableForceUpdateFriendlyURL.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/05_forceUpdateFriendlyURL.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
Labels: 1.7.7.x, Refactoring, TE

#18001 Functional tests - Refacto product settings default activation status
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/06_defaultActivationStatus.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/06_enableDisableDefaultActivationStatus.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
Labels: 1.7.7.x, Refactoring, TE

#18022 Remove useless spaces for Ceuta and Melilla
  localization/es.xml
Labels: Improvement, develop

#18017 Update Customer-> passwd phpdoc
  classes/Customer.php
Labels: Improvement, develop

#18019 Merge 1.7.6.x into 1.7.7.x
  CONTRIBUTORS.md
  admin-dev/themes/new-theme/js/pages/cms-page/form/index.js
  admin-dev/themes/new-theme/public/theme.css
  classes/PaymentModule.php
  classes/form/CustomerAddressForm.php
  classes/form/CustomerAddressFormatter.php
  classes/form/CustomerForm.php
  classes/form/CustomerFormatter.php
  docs/CHANGELOG.txt
  src/Core/Domain/Customer/ValueObject/Email.php
  src/Core/Domain/ValueObject/Email.php
  src/PrestaShopBundle/Resources/views/Admin/Translations/overview.html.twig
  themes/_core/js/product.js
  themes/core.js
  themes/core.js.map
  themes/package.json
Labels: 1.7.7.x, Improvement

#18050 Use proper computing precision in payment module
  classes/PaymentModule.php
Labels: 1.7.7.x, Improvement

#18056 Functional tests - Back to default sort in test 'Sort Products'
  tests/puppeteer/campaigns/functional/BO/03_catalog/01_products/02_sortProducts.js
Labels: 1.7.7.x, Refactoring, TE

#18029 Remove prettyCI config file
  .prettyci.composer.json
Labels: Improvement, develop

#17120 Fix & remove unneeded reference operators
  classes/AddressFormat.php
  classes/CMSCategory.php
  classes/Carrier.php
  classes/CartRule.php
  classes/Category.php
  classes/Configuration.php
  classes/ObjectModel.php
  classes/Product.php
  classes/Tools.php
  classes/controller/AdminController.php
  classes/controller/FrontController.php
  classes/module/Module.php
  classes/order/OrderSlip.php
  classes/pdf/HTMLTemplateOrderSlip.php
  classes/pdf/HTMLTemplateSupplyOrderForm.php
  classes/tax/AverageTaxOfProductsTaxCalculator.php
  controllers/admin/AdminAccessController.php
  controllers/admin/AdminAttributeGeneratorController.php
  controllers/admin/AdminCustomerThreadsController.php
  controllers/admin/AdminOrdersController.php
  controllers/admin/AdminShopController.php
  controllers/admin/AdminShopUrlController.php
  controllers/front/ProductController.php
  install-dev/controllers/http/system.php
  src/Adapter/Cart/QueryHandler/GetCartForViewingHandler.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Presenter/Product/ProductLazyArray.php
  src/PrestaShopBundle/Form/Admin/Type/Material/MaterialChoiceTreeType.php
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Install/Upgrade.php
  tests-legacy/resources/modules/cronjobs/controllers/admin/AdminCronJobsController.php
Labels: Refactoring, develop

#17973 Fix pagination on migrated order listing
  src/Core/Grid/Query/OrderQueryBuilder.php
Labels: 1.7.7.x, Bug, QA ✔️

#17799 Order Page: Fix private note that cannot be emptied
  admin-dev/themes/new-theme/js/pages/order/view.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
Labels: 1.7.7.x, Bug, QA ✔️, migration

#17913 Remove useless TinyMCE scripts from brand form pages
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Suppliers/add.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Suppliers/edit.html.twig
Labels: 1.7.7.x, Bug, QA ✔️

#17804 Fix bug when changing addresses on virtual product command
  classes/order/Order.php
Labels: 1.7.7.x, Bug, QA ✔️

#17438 Fix submenu not displayed on mobile on classic theme
  themes/classic/_dev/css/components/mainmenu.scss
  themes/classic/assets/css/theme.css
Labels: 1.7.7.x, BC break, Bug, QA ✔️

#17877 Fix bug when adding a discount on order page
  src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php
Labels: 1.7.7.x, Bug, QA ✔️, migration

#17901 The button add to cart shouldn't be enabled when minimal quantity > quantity
  src/Adapter/Presenter/Product/ProductLazyArray.php
Labels: 1.7.7.x, Bug, QA ✔️

#17650 Fixed display for first cell (select all & input) in grid
  admin-dev/themes/new-theme/scss/components/_grid.scss
Labels: 1.7.7.x, Bug, QA ✔️

#17742 Fix country states input toggle on page load
  admin-dev/themes/new-theme/js/components/country-state-selection-toggler.js
  admin-dev/themes/new-theme/public/customer_address_form.bundle.js
  admin-dev/themes/new-theme/public/manufacturer_address_form.bundle.js
  admin-dev/themes/new-theme/public/supplier_form.bundle.js
  src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php
  src/PrestaShopBundle/Form/Admin/Sell/Address/ManufacturerAddressType.php
  src/PrestaShopBundle/Form/Admin/Sell/Supplier/SupplierType.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Address/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Manufacturer/Address/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Suppliers/Blocks/form.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️, migration

#18045 Fix selector for invoice note manager
  admin-dev/themes/new-theme/js/pages/order/invoice-note-manager.js
Labels: 1.7.7.x, Bug, QA ✔️, migration

#17985 Fix customer informations on order page when customer is a guest
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Core/Domain/Order/QueryResult/OrderCustomerForViewing.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️, migration

#17767 [Multishop - BO] Fix orders not appearing in order list for shared space shops
  src/PrestaShopBundle/Resources/config/services.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
Labels: 1.7.7.x, Bug, QA ✔️, migration

#17914 Add index on product table for fresh install
  install-dev/data/db_structure.sql
Labels: 1.7.7.x, Improvement, QA ✔️

#18054 In RTL I have to click 3 times on the checkbox to select the product
  admin-dev/themes/new-theme/js/pages/order/view/order-product-cancel.js
Labels: 1.7.7.x, Bug, QA ✔️, migration

#17734 Register new hook displayFooterCategory for 1770 and rename order hooks
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.7.0.sql
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig
Labels: 1.7.7.x, Improvement, QA ✔️

#17482 Allow token for TokenisedUrlsListener class and in form using the method=GET attribute
  src/Adapter/Translations/TranslationRouteFinder.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/DeliveryController.php
  src/PrestaShopBundle/Controller/Admin/TranslationsController.php
  src/PrestaShopBundle/EventListener/TokenizedUrlsListener.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Translations/TranslationsSettingsFormHandler.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_handler.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Translations/translations_settings.html.twig
  src/PrestaShopBundle/Service/Routing/Router.php
Labels: 1.7.7.x, Bug, QA ✔️

#18073 Checkout address edition is failing due to missing id_address in action
  classes/checkout/CheckoutAddressesStep.php
  themes/classic/templates/checkout/_partials/steps/addresses.tpl
Labels: 1.7.7.x, Bug, QA ✔️

#17839 Wrap OrderController::viewAction in try-catch
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️, migration

#17986 Fix "Module Manager" menu item not being translatable
  app/Resources/translations/default/AdminNavigationMenu.xlf
  classes/lang/KeysReference/TabLang.php
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️

#17843 Fix classic them subcategories in menu displayed hover menu by improving JS selector
  themes/classic/_dev/js/components/top-menu.js
  themes/classic/assets/js/theme.js
Labels: 1.7.7.x, Bug, QA ✔️

#18092 Merge 1.7.6.x into 1.7.7.x - 11/03/2020
  CONTRIBUTORS.md
  admin-dev/themes/new-theme/public/order_view.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  app/AppKernel.php
  install-dev/install_version.php
Labels: 1.7.7.x, Improvement

#17476 Don't allow comma in order payment amount field
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-edit.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
  src/Adapter/Order/CommandHandler/IssueReturnProductHandler.php
  src/Adapter/Order/CommandHandler/IssueStandardRefundHandler.php
  src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Order/Refund/OrderRefundCalculator.php
  src/Core/Domain/Order/Command/AbstractRefundCommand.php
  src/Core/Domain/Order/Command/IssuePartialRefundCommand.php
  src/Core/Domain/Order/Command/IssueReturnProductCommand.php
  src/Core/Domain/Order/Command/IssueStandardRefundCommand.php
  src/Core/Domain/Order/Exception/InvalidAmountException.php
  src/Core/Domain/Order/Payment/Command/AddPaymentCommand.php
  src/Core/Domain/Order/Product/Command/AddProductToOrderCommand.php
  src/Core/Domain/Order/Product/Command/UpdateProductInOrderCommand.php
  src/Core/Domain/Order/QueryResult/OrderDiscountForViewing.php
  src/Core/Domain/Order/QueryResult/OrderForViewing.php
  src/Core/Domain/Order/QueryResult/OrderPricesForViewing.php
  src/Core/Domain/Order/QueryResult/OrderProductForViewing.php
  src/Core/Domain/Order/ValueObject/OrderDetailRefund.php
  src/Core/Form/IdentifiableObject/DataHandler/PartialRefundFormDataHandler.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/CancelProductType.php
  src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
  src/PrestaShopBundle/Twig/Extension/NumberExtension.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderRefundFeatureContext.php
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️

#17982 Functional tests - Categories page test helper card
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/06_helperCard.js
  tests/puppeteer/pages/BO/BObasePage.js
Labels: 1.7.7.x, Refactoring, TE

#18002 Functional tests - Refacto customer settings redisplay cart at login
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/01_enableDisableRedisplayCartAtLogin.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/01_redisplayCartAtLogin.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/02_sendEmailAfterRegistration.js
  tests/puppeteer/pages/BO/shopParameters/customerSettings/index.js
Labels: 1.7.7.x, Refactoring, TE

#18071 Functional tests - Customers set required fields
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/05_setRequiredFields.js
  tests/puppeteer/pages/BO/customers/index.js
  tests/puppeteer/pages/FO/login.js
Labels: 1.7.7.x, Refactoring, TE

#17921 Functional tests - Enable disable webservice key
  tests/puppeteer/campaigns/data/faker/webservice.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/09_webservice/02_filterAndQuickEditWebservice.js
  tests/puppeteer/pages/BO/advancedParameters/webservice/add.js
  tests/puppeteer/pages/BO/advancedParameters/webservice/index.js
Labels: 1.7.7.x, Refactoring, TE

#18061 Order page: fix stock value update when editing a product
  admin-dev/themes/new-theme/js/pages/order/view/order-product-edit.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
Labels: 1.7.7.x, Bug, QA ✔️, migration

#18101 Fix typo in hook descriptions
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.7.0.sql
Labels: 1.7.7.x, Bug

#17917 Use appropriate hook name in contact right column
  themes/classic/templates/contact.tpl
Labels: 1.7.7.x, Bug, QA ✔️

#17292 Fixes undefined vars in some migrated controllers
  src/Adapter/File/Uploader/AttachmentFileUploader.php
  src/Core/Domain/Attachment/Exception/CannotUnlinkAttachmentException.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/AttachmentController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CatalogPriceRuleController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/SupplierController.php
  src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/OrderMessageController.php
Labels: 1.7.7.x, Bug, QA ✔️, migration

#18068 Improve img accessibility
  themes/classic/templates/catalog/_partials/miniatures/category.tpl
  themes/classic/templates/catalog/_partials/miniatures/pack-product.tpl
  themes/classic/templates/catalog/_partials/product-cover-thumbnails.tpl
  themes/classic/templates/catalog/_partials/product-images-modal.tpl
  themes/classic/templates/cms/stores.tpl
Labels: Bug, Improvement, QA ✔️, develop

#18035 Fix popover not hidden when changing product tab
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Panels/essentials.html.twig
Labels: Bug, QA ✔️, Wording ✔️, develop

#18040 Fix Brand dropdown empty value
  src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#18098 Add return to Tools::deleteFile() method
  classes/Tools.php
Labels: Improvement, develop

#18051 Fix Module Catalog page - The Menu "process-icon-dropdown" is not well displayed on mobile by adjusting sass
  admin-dev/themes/default/sass/partials/_toolbar.sass
Labels: Bug, QA ✔️, develop

#17907 Fix TinyMCEEditor that shouldn't handle language switching by adding a TranslatableField
  admin-dev/themes/new-theme/js/components/tinymce-editor.js
  admin-dev/themes/new-theme/js/pages/supplier/supplier-form.js
  admin-dev/themes/new-theme/public/attachment.bundle.js
  admin-dev/themes/new-theme/public/attribute.bundle.js
  admin-dev/themes/new-theme/public/attribute_group.bundle.js
  admin-dev/themes/new-theme/public/category.bundle.js
  admin-dev/themes/new-theme/public/cldr.bundle.js
  admin-dev/themes/new-theme/public/cms_page.bundle.js
  admin-dev/themes/new-theme/public/cms_page_form.bundle.js
  admin-dev/themes/new-theme/public/contacts.bundle.js
  admin-dev/themes/new-theme/public/credit_slip.bundle.js
  admin-dev/themes/new-theme/public/currency_form.bundle.js
  admin-dev/themes/new-theme/public/customer_address_form.bundle.js
  admin-dev/themes/new-theme/public/feature_form.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/maintenance.bundle.js
  admin-dev/themes/new-theme/public/manufacturer.bundle.js
  admin-dev/themes/new-theme/public/manufacturer_address_form.bundle.js
  admin-dev/themes/new-theme/public/merchandise_return.bundle.js
  admin-dev/themes/new-theme/public/meta.bundle.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_message_form.bundle.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  admin-dev/themes/new-theme/public/product_page.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/profiles.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/supplier_form.bundle.js
  admin-dev/themes/new-theme/public/tax.bundle.js
  admin-dev/themes/new-theme/public/tax_rules_group.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
Labels: 1.7.7.x, QA ✔️, Refactoring

#18041 Fix layout problem in BO Products category Filter
  admin-dev/themes/new-theme/scss/components/_category_tree.scss
Labels: Bug, QA ✔️, develop

#18093 Merge 177x into develop - 11/03/2020
  CONTRIBUTORS.md
  admin-dev/themes/new-theme/js/components/country-state-selection-toggler.js
  admin-dev/themes/new-theme/js/pages/order/invoice-note-manager.js
  admin-dev/themes/new-theme/js/pages/order/view.js
  admin-dev/themes/new-theme/scss/components/_grid.scss
  classes/form/CustomerAddressForm.php
  classes/form/CustomerAddressFormatter.php
  classes/form/CustomerForm.php
  classes/form/CustomerFormatter.php
  classes/order/Order.php
  docs/CHANGELOG.txt
  src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Presenter/Product/ProductLazyArray.php
  src/Core/Domain/Customer/ValueObject/Email.php
  src/Core/Domain/Order/QueryResult/OrderCustomerForViewing.php
  src/Core/Domain/ValueObject/Email.php
  src/Core/Grid/Query/OrderQueryBuilder.php
  src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php
  src/PrestaShopBundle/Form/Admin/Sell/Address/ManufacturerAddressType.php
  src/PrestaShopBundle/Form/Admin/Sell/Supplier/SupplierType.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Address/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Manufacturer/Address/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Suppliers/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Suppliers/add.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Suppliers/edit.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Translations/overview.html.twig
  tests/puppeteer/campaigns/functional/BO/03_catalog/01_products/02_sortProducts.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/01_catalogMode.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/01_enableDisableCatalogMode.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/02_newDaysNumber.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/05_enableDisableForceUpdateFriendlyURL.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/05_forceUpdateFriendlyURL.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/06_defaultActivationStatus.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/06_enableDisableDefaultActivationStatus.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/02_displayRemainingQuantities.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
  tests/puppeteer/pages/FO/product.js
  themes/_core/js/product.js
  themes/classic/_dev/css/components/mainmenu.scss
  themes/classic/assets/css/custom_rtl.css
  themes/classic/assets/css/error_rtl.css
  themes/classic/assets/css/theme_rtl.css
Labels: 1.7.7.x, Bug, Improvement

#18033 Remove tabs for summary and description fields in product page
  admin-dev/themes/default/js/bundle/product/form.js
  admin-dev/themes/new-theme/js/product-page/product-header.js
  admin-dev/themes/new-theme/scss/components/_tinymce.scss
  admin-dev/themes/new-theme/scss/pages/_product_page.scss
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Panels/essentials.html.twig
  tests/puppeteer/pages/BO/catalog/products/add.js
Labels: Bug, QA ✔️, Wording ✔️, develop

#18149 Functional tests - Add test Export Categories to csv
  tests/puppeteer/campaigns/data/faker/webservice.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/07_exportCategories.js
  tests/puppeteer/campaigns/utils/files.js
  tests/puppeteer/pages/BO/catalog/categories/index.js
Labels: 1.7.7.x, Refactoring, TE

#18156 Functional tests - Fix nightly 16-03
  tests/puppeteer/pages/BO/BObasePage.js
Labels: 1.7.7.x, Refactoring, TE

#18077 Add behat test for GetManufacturerForViewingHandler
  tests/Integration/Behaviour/Features/Context/Domain/ManufacturerFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Manufacturer/manufacturer_management.feature
  tests/Integration/Behaviour/behat.yml
Labels: Improvement, develop, migration

#17869 Add linkedin to classic theme with SVG icon
  themes/classic/_dev/css/components/footer.scss
  themes/classic/_dev/img/linkedin.svg
Labels: Improvement, QA ✔️, develop

#18135 Add some phpdoc to Tools
  classes/Tools.php
Labels: Refactoring, develop

#17672 Rework ChangeOrderCurrencyHandler to private methods
  src/Adapter/Order/AbstractOrderHandler.php
  src/Adapter/Order/CommandHandler/ChangeOrderCurrencyHandler.php
Labels: 1.7.7.x, Bug, QA ✔️, migration

#17849 Fix orders page dropdown going under header by removing the fixed property
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/pages/_orders.scss
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/choice.html.twig
Labels: 1.7.7.x, Bug, QA ✔️

#18143 Functional tests - Shop Parameters > Traffic & SEO test helper card
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/seoAndUrls/05_helperCard.js
Labels: 1.7.7.x, Refactoring, TE

#18145 Functional tests - Customer settings ask for birth date
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/05_askForBirthDate.js
  tests/puppeteer/pages/BO/shopParameters/customerSettings/index.js
  tests/puppeteer/pages/FO/login.js
Labels: 1.7.7.x, Refactoring, TE

#18081 Functional tests - Enable/Disable multistore
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/01_general/general/11_enableDisableMultistore.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/shopParameters/general/index.js
Labels: 1.7.7.x, Refactoring, TE

#17891 Functional tests - Product settings enable/disable display unavailable product attributes
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/03_displayUnavailableProductAttributes.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
  tests/puppeteer/pages/FO/product.js
Labels: 1.7.7.x, Refactoring, TE

#17805 Functional tests - Order settings enable/disable final summary
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/01_enableFinalSummary.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/shopParameters/orderSettings/index.js
  tests/puppeteer/pages/FO/orderConfirmation.js
Labels: 1.7.7.x, Refactoring, TE

#18146 After creating new voucher from orders/new, I get redirected to voucher list, not a new order
  admin-dev/themes/default/template/controllers/cart_rules/form.tpl
  admin-dev/themes/new-theme/js/pages/order/create.js
  admin-dev/themes/new-theme/js/pages/order/create/create-order-page.js
  controllers/admin/AdminCartRulesController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart_rules.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, migration

#18174 Functional tests - Product settings separator of attribute anchor on the product links
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/05_separatorOfAttributeAnchor.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
  tests/puppeteer/pages/FO/product.js
Labels: 1.7.7.x, Refactoring, TE

#18148 Functional tests - Customer settings enable/disable partner offer
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/06_enablePartnerOffers.js
  tests/puppeteer/pages/BO/shopParameters/customerSettings/index.js
  tests/puppeteer/pages/FO/login.js
Labels: 1.7.7.x, Refactoring, TE

#18158 Functional tests - Add test 'Export customers'
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/07_exportCategories.js
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/06_exportCustomers.js
  tests/puppeteer/pages/BO/customers/index.js
Labels: 1.7.7.x, Refactoring, TE

#17881 Fix Search by product name & category doesn't work in the second of the Stocks page
  admin-dev/themes/new-theme/js/app/pages/stock/components/app.vue
Labels: 1.7.7.x, Bug, PM ✔️, QA ✔️

#18191 Functional tests - Order settings enable/disable guest checkout
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/02_enableGuestCheckout.js
  tests/puppeteer/pages/BO/shopParameters/orderSettings/index.js
  tests/puppeteer/pages/FO/checkout.js
Labels: 1.7.7.x, Refactoring, TE

#18112 Functional tests - Refactoring products tests
  tests/puppeteer/campaigns/data/FO/cart.js
  tests/puppeteer/campaigns/data/FO/product.js
  tests/puppeteer/campaigns/data/faker/product.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/02_enableDisableTaxBreakdown.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/03_monitoring/02_monitoringProducts.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/04_filterStocksByStatus.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/03_maxSizeShortDescription.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/04_quantityDiscountsBasedOn.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/05_forceUpdateFriendlyURL.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/02_displayRemainingQuantities.js
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/seoAndUrls/04_enableDisableAccentedURL.js
  tests/puppeteer/campaigns/sanity/02_productsBO/02_CRUDStandardProductInBO.js
  tests/puppeteer/campaigns/sanity/02_productsBO/03_CRUDStandardProductWithCombinationsInBO.js
  tests/puppeteer/campaigns/sanity/02_productsBO/04_deleteProduct.js
  tests/puppeteer/campaigns/sanity/02_productsBO/05_deleteProductsWithBulkActions.js
  tests/puppeteer/campaigns/sanity/04_catalogFO/02_checkProduct.js
  tests/puppeteer/campaigns/sanity/05_cartFO/01_editCheckCart.js
  tests/puppeteer/campaigns/sanity/06_checkoutFO/01_orderProduct.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/catalog/products/add.js
  tests/puppeteer/pages/BO/catalog/products/index.js
  tests/puppeteer/pages/FO/cart.js
  tests/puppeteer/pages/FO/product.js
  tests/puppeteer/pages/commonPage.js
Labels: 1.7.7.x, Refactoring, TE

#18178 Functional tests - Add test 'Export brands'
  tests/puppeteer/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/07_exportBrands.js
  tests/puppeteer/campaigns/utils/files.js
  tests/puppeteer/pages/BO/catalog/brands/index.js
Labels: 1.7.7.x, Refactoring, TE

#18097 Remove unused result in for statement
  controllers/admin/AdminCartRulesController.php
Labels: Refactoring, develop

#18180 Functional tests - Add tests 'Help card' for customers and addresses
  tests/puppeteer/campaigns/functional/BO/04_customers/01_customers/07_helpCard.js
  tests/puppeteer/campaigns/functional/BO/04_customers/02_addresses/03_addressesBulkActions.js
  tests/puppeteer/campaigns/functional/BO/04_customers/02_addresses/04_sortAddresses.js
  tests/puppeteer/campaigns/functional/BO/04_customers/02_addresses/05_helpCard.js
Labels: 1.7.7.x, Refactoring, TE

#18198 Fix test 'display unavailable product attributes'
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/03_displayUnavailableProductAttributes.js
Labels: 1.7.7.x, Refactoring, TE

#18091 Display gift message into migrated Order page
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/shipping.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️, migration

#17959 Enable new Orders page
  classes/helper/HelperList.php
  controllers/admin/AdminCustomerThreadsController.php
  controllers/admin/AdminOutstandingController.php
  controllers/admin/AdminReturnController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
  tests/puppeteer/campaigns/sanity/03_ordersBO/01_filterOrders.js
  tests/puppeteer/campaigns/sanity/03_ordersBO/02_editOrder.js
Labels: 1.7.7.x, Improvement, Must-have, QA ✔️, migration

#17981 Functional tests - Fix invoices and credit slips tests
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/01_generateInvoiceByDate.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/02_generateInvoiceByStatus.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/01_enableDisableInvoices.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/02_enableDisableTaxBreakdown.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/03_enableDisableProductImage.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/04_invoicePrefix.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/05_enableDisableCurrentYear.js
  tests/puppeteer/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/06_otherOptions.js
  tests/puppeteer/campaigns/functional/BO/02_orders/03_creditSlips/01_createFilterCreditSlips.js
  tests/puppeteer/campaigns/functional/BO/02_orders/03_creditSlips/02_generateCreditSlipsByDate.js
  tests/puppeteer/campaigns/functional/BO/02_orders/03_creditSlips/03_creditSlipOptions.js
  tests/puppeteer/campaigns/functional/BO/02_orders/04_deliverySlips/01_generateDeliverySlipByDate.js
  tests/puppeteer/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/01_deliverySlipPrefix.js
  tests/puppeteer/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/02_deliverySlipNumber.js
  tests/puppeteer/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/03_enableDisableProductImage.js
  tests/puppeteer/campaigns/sanity/03_ordersBO/01_filterOrders.js
  tests/puppeteer/campaigns/sanity/03_ordersBO/02_editOrder.js
  tests/puppeteer/pages/BO/orders/index.js
  tests/puppeteer/pages/BO/orders/view.js
  tests/puppeteer/pages/commonPage.js
Labels: 1.7.7.x, Refactoring, TE

#18130 Use grid common search action where possible (1.7.7.x controllers only)
  src/Core/Grid/Definition/Factory/CmsPageCategoryDefinitionFactory.php
  src/Core/Grid/Definition/Factory/SupplierGridDefinitionFactory.php
  src/Core/Search/Filters/SupplierFilters.php
  src/PrestaShopBundle/Controller/Admin/CommonController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/AttributeController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/AttributeGroupController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/SupplierController.php
  src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/MerchandiseReturnController.php
  src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/OrderMessageController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/attribute.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/attribute_group.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/suppliers.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer/addresses.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer_service/merchandise_return.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer_service/order_message.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
Labels: 1.7.7.x, QA ✔️, Refactoring, migration

#17861 Add vertical scroll to customization fields in BO order create page
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/pages/_orders_create.scss
  admin-dev/themes/new-theme/scss/theme.scss
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, migration

#18214 Upgrade TravisCI OS
  .travis.yml
Labels: Improvement, develop

#18202 Do not display shipping address when order is virtual product only
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig
Labels: 1.7.7.x, Bug, QA ✔️

#18182 CO : Correct phpDoc
  classes/order/Order.php
Labels: Improvement, develop

#18217 Fix typo
  classes/Pack.php
Labels: Refactoring, develop, typo fix

#18160 Updating hook calls on WebserviceSpecificManagementImages
  classes/webservice/WebserviceSpecificManagementImages.php
Labels: Refactoring, develop

#18219 Fix wrong id_employee attribute description on PrestaShopLogger
  classes/PrestaShopLogger.php
Labels: Refactoring, develop

#18052 Replace a lot of http links by https
  admin-dev/themes/default/template/footer.tpl
  classes/Tools.php
  config/xml/themes/default.xml
  docs/CHANGELOG.txt
  install-dev/classes/controllerHttp.php
  install-dev/controllers/console/process.php
  install-dev/controllers/http/configure.php
  install-dev/data/xml/configuration.xml
  install-dev/fixtures/fashion/data/connections.xml
  install-dev/theme/views/footer.php
  install-dev/theme/views/welcome.php
  js/admin.js
  js/validate.js
  themes/classic/config/theme.yml
Labels: Improvement, QA ✔️, Wording ✔️, develop

#18227 Functional tests - Fix selector for tests categories
  tests/puppeteer/campaigns/functional/BO/03_catalog/02_categories/01_filterAndQuickEditCategories.js
  tests/puppeteer/pages/BO/catalog/categories/index.js
Labels: 1.7.7.x, Refactoring, TE

#18224 Functional tests - Product settings enable/disable allow ordering out of stock
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/01_allowOrderingOutOfStock.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
  tests/puppeteer/pages/FO/product.js
Labels: 1.7.7.x, Refactoring, TE

#18216 Functional tests - Retry to create Browser 3 times if first one fails
  tests/puppeteer/campaigns/utils/helpers.js
Labels: 1.7.7.x, Refactoring, TE

#18168 Prevent adding or editing an invalid product quantity on order
  classes/PrestaShopCollection.php
  src/Core/Domain/Order/Exception/InvalidProductQuantityException.php
  src/Core/Domain/Order/Product/Command/AddProductToOrderCommand.php
  src/Core/Domain/Order/Product/Command/UpdateProductInOrderCommand.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️

#18023 Modify test data generation to handle price with taxes
  classes/order/OrderSlip.php
  install-dev/fixtures/fashion/data/product.xml
  install-dev/fixtures/fashion/install.php
  src/Adapter/Order/Refund/OrderRefundCalculator.php
  src/Adapter/Order/Refund/OrderSlipCreator.php
  tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/TaxFeatureContext.php
  tests/Integration/Behaviour/Features/Context/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/partial_refund.feature
  tests/Integration/Behaviour/Features/Scenario/Order/return_product.feature
  tests/Integration/Behaviour/Features/Scenario/Order/standard_refund.feature
  tests/Integration/Behaviour/behat.yml
  tests/puppeteer/campaigns/sanity/02_productsBO/01_filterProducts.js
  tests/puppeteer/campaigns/sanity/02_productsBO/02_CRUDStandardProductInBO.js
  tests/puppeteer/pages/BO/catalog/products/index.js
Labels: 1.7.7.x, Bug, QA ✔️

#18239 Update tests data with taxes to fix behat tests
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
Labels: 1.7.7.x, Bug

#18243 Fix phpdoc for Currency class
  classes/Currency.php
Labels: Refactoring, develop

#18246 Add check when adding a product in an order that it is not out of stock
  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
Labels: 1.7.7.x, Bug

#18242 Functional tests - Add test 'Help card' for orders page
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/01_helpCard.js
Labels: 1.7.7.x, Refactoring, TE

#17562 Mailto - Spam Bot improvement - thanks @waschier-design
  themes/classic/modules/ps_contactinfo/ps_contactinfo-rich.tpl
  themes/classic/modules/ps_contactinfo/ps_contactinfo.tpl
Labels: Improvement, QA ✔️, develop

#17703 #17082 : Grid row delete confirmation modal - Catalog > Files
  admin-dev/themes/new-theme/js/components/grid/extension/action/row/submit-row-action-extension.js
  src/Core/Grid/Action/Row/Type/SubmitRowAction.php
  src/Core/Grid/Definition/Factory/AttachmentGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/DeleteActionTrait.php
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Actions/Row/submit.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop, migration

#18231 Functional tests - Fix default timeout for waiting for selector
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/advancedParameters/team/add.js
  tests/puppeteer/pages/BO/advancedParameters/team/index.js
  tests/puppeteer/pages/BO/advancedParameters/team/profiles/add.js
  tests/puppeteer/pages/BO/advancedParameters/team/profiles/index.js
  tests/puppeteer/pages/BO/advancedParameters/webservice/index.js
  tests/puppeteer/pages/BO/catalog/brands/add.js
  tests/puppeteer/pages/BO/catalog/brands/addresses/add.js
  tests/puppeteer/pages/BO/catalog/brands/index.js
  tests/puppeteer/pages/BO/catalog/categories/add.js
  tests/puppeteer/pages/BO/catalog/categories/index.js
  tests/puppeteer/pages/BO/catalog/files/add.js
  tests/puppeteer/pages/BO/catalog/files/index.js
  tests/puppeteer/pages/BO/catalog/monitoring/index.js
  tests/puppeteer/pages/BO/catalog/products/add.js
  tests/puppeteer/pages/BO/catalog/products/index.js
  tests/puppeteer/pages/BO/catalog/stocks/index.js
  tests/puppeteer/pages/BO/catalog/stocks/movements/index.js
  tests/puppeteer/pages/BO/catalog/suppliers/add.js
  tests/puppeteer/pages/BO/catalog/suppliers/index.js
  tests/puppeteer/pages/BO/customerService/orderMessages/add.js
  tests/puppeteer/pages/BO/customerService/orderMessages/index.js
  tests/puppeteer/pages/BO/customers/add.js
  tests/puppeteer/pages/BO/customers/addresses/add.js
  tests/puppeteer/pages/BO/customers/addresses/index.js
  tests/puppeteer/pages/BO/customers/index.js
  tests/puppeteer/pages/BO/design/linkWidgets/add.js
  tests/puppeteer/pages/BO/design/linkWidgets/index.js
  tests/puppeteer/pages/BO/design/pages/add.js
  tests/puppeteer/pages/BO/design/pages/index.js
  tests/puppeteer/pages/BO/design/pages/pageCategory/add.js
  tests/puppeteer/pages/BO/international/currencies/add.js
  tests/puppeteer/pages/BO/international/currencies/index.js
  tests/puppeteer/pages/BO/international/languages/index.js
  tests/puppeteer/pages/BO/international/taxes/add.js
  tests/puppeteer/pages/BO/international/taxes/index.js
  tests/puppeteer/pages/BO/modules/autoUpgrade/index.js
  tests/puppeteer/pages/BO/modules/moduleCatalog/index.js
  tests/puppeteer/pages/BO/modules/moduleManager/index.js
  tests/puppeteer/pages/BO/orders/view.js
  tests/puppeteer/pages/BO/payment/preferences/index.js
  tests/puppeteer/pages/BO/shopParameters/contact/add.js
  tests/puppeteer/pages/BO/shopParameters/contact/index.js
  tests/puppeteer/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/add.js
  tests/puppeteer/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/index.js
  tests/puppeteer/pages/FO/FObasePage.js
  tests/puppeteer/pages/FO/cart.js
  tests/puppeteer/pages/FO/checkout.js
  tests/puppeteer/pages/FO/home.js
  tests/puppeteer/pages/FO/login.js
  tests/puppeteer/pages/FO/product.js
  tests/puppeteer/pages/Install/install.js
  tests/puppeteer/pages/commonPage.js
Labels: 1.7.7.x, Refactoring, TE

#18197 Functional tests - Order settings enable/disable reordering option
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/03_disableReorderingOption.js
  tests/puppeteer/pages/BO/shopParameters/customerSettings/index.js
  tests/puppeteer/pages/BO/shopParameters/orderSettings/index.js
  tests/puppeteer/pages/FO/myAccount.js
  tests/puppeteer/pages/FO/orderHistory.js
Labels: 1.7.7.x, Refactoring, TE

#18267 Functional tests - Fix update successful message on addresses page
  tests/puppeteer/pages/BO/customers/addresses/index.js
Labels: 1.7.7.x, Refactoring, TE

#18063 Use localized dates for order page
  src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/documents.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/header.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/merchandise_returns.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/payments.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/shipping.html.twig
  src/PrestaShopBundle/Twig/Extension/LocalizationExtension.php
Labels: 1.7.7.x, Feature, QA ✔️, migration

#18245 Fix orders page dropdown going under header by adding a flip false property
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/choice.html.twig
Labels: 1.7.7.x, Bug, QA ✔️

#18102 Fix sidebar submenu opening by changing style and adding JS
  admin-dev/themes/default/js/admin-theme.js
  admin-dev/themes/default/js/theme.js
  admin-dev/themes/default/public/24aab533f87e7b434be5fa5b1684975c.svg
  admin-dev/themes/default/public/2a9a30e14574c9ec24add2901a80b81c.svg
  admin-dev/themes/default/public/a33a878f3861ca67e9bc423c58b2a357.svg
  admin-dev/themes/default/public/b46ff9f5c8bcba1ea3b4b320e22be5c7.svg
  admin-dev/themes/default/public/bf4dde0147bb02556500d922e2efc90b.svg
  admin-dev/themes/default/public/bundle.js
  admin-dev/themes/default/public/fedf49d31f55f4beaf2c891f3875554f.svg
  admin-dev/themes/default/public/theme.css
  admin-dev/themes/default/sass/partials/_nav.sass
  admin-dev/themes/default/template/nav.tpl
  admin-dev/themes/new-theme/js/nav_bar.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/components/layout/_nav_bar.scss
  admin-dev/themes/new-theme/template/components/layout/nav_bar.tpl
Labels: 1.7.7.x, Bug, QA ✔️

#18103 Duplicate address when submitting a form with errors
  classes/checkout/CheckoutAddressesStep.php
  controllers/front/AddressController.php
  themes/classic/templates/checkout/_partials/steps/addresses.tpl
Labels: 1.7.6.x, Bug, QA ✔️

#17975 Convert arabic/persian digits to latin digits in DatePickerType
  admin-dev/themes/default/js/bundle/product/form.js
  src/Adapter/Product/AdminProductWrapper.php
  src/Core/Util/ArabicToLatinDigitConverter.php
  src/PrestaShopBundle/Form/Admin/Type/DatePickerType.php
  src/PrestaShopBundle/Form/DataTransformer/ArabicToLatinDigitDataTransformer.php
  src/PrestaShopBundle/Model/Product/AdminModelAdapter.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/services.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_data_transformer.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/bundle/utils.yml
  src/PrestaShopBundle/Resources/config/services/core/util.yml
  src/PrestaShopBundle/Utils/FloatParser.php
  tests-legacy/PrestaShopBundle/Model/Product/AdminModelAdapterTest.php
  tests-legacy/Unit/PrestaShopBundle/Utils/FloatParserTest.php
  tests/Unit/PrestaShopBundle/Form/DataTransformer/ArabicToLatinDigitDataTransformerTest.php
Labels: 1.7.7.x, Bug, QA ✔️

#18208 Increase quantity when adding an already added product when creating order
  src/Adapter/Cart/CommandHandler/AddProductToCartHandler.php
Labels: 1.7.7.x, Bug, QA ✔️

#18272 Functional tests - Add test 'Export Orders'
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/03_exportOrders.js
  tests/puppeteer/pages/BO/orders/index.js
Labels: 1.7.7.x, Refactoring, TE

#18268 Functional tests - Add test 'Help card' for Monitoring page
  tests/puppeteer/campaigns/functional/BO/03_catalog/03_monitoring/03_helpCard.js
Labels: 1.7.7.x, TE

#18269 Functional tests - Add test 'Help card' for Stocks page
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/05_helpCard.js
Labels: 1.7.7.x, Refactoring, TE

#17923 Correct generatorRuntime on new-theme to fix an error on add currency page
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
Labels: Bug, QA ✔️, develop

#17385 Confirm modal on restoring currency settings
  admin-dev/themes/default/package.json
  admin-dev/themes/new-theme/js/pages/currency/form/components/CurrencyFormatter.vue
  admin-dev/themes/new-theme/js/pages/currency/form/currency-form.js
  admin-dev/themes/new-theme/public/cms_page_form.bundle.js
  admin-dev/themes/new-theme/public/currency_form.bundle.js
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Currency/Blocks/form.html.twig
Labels: 1.7.7.x, Improvement, QA ✔️, Wording ✔️

#18294 Return null when value is an empty string in ArabicToLatinDigitDataTransformer
  src/PrestaShopBundle/Form/DataTransformer/ArabicToLatinDigitDataTransformer.php
Labels: 1.7.7.x, Bug, QA ✔️

#18288 Fix wrong number of orders when filter 'New client' on
  src/Core/Grid/Query/OrderQueryBuilder.php
Labels: 1.7.7.x, Bug, QA ✔️

#18144 Fixed on CartRule : Discount on selected product excluding discounted products
  src/Adapter/Presenter/Cart/CartPresenter.php
  src/Core/Cart/CartRuleCalculator.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/exclude_discounted_product.feature
Labels: 1.7.7.x, BO, Bug, FO, QA ✔️

#18306 Functional tests - Add test 'Check invoice downloaded from orders list'
  tests/puppeteer/campaigns/data/demo/orderStatuses.js
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/04_checkInvoiceDownloadedFromList.js
  tests/puppeteer/pages/BO/orders/index.js
Labels: 1.7.7.x, Refactoring, TE

#17853 BO: Fix shipping price tax issue on order creation page
  admin-dev/themes/new-theme/js/pages/order/create/create-order-map.js
  admin-dev/themes/new-theme/js/pages/order/create/summary-renderer.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  src/Adapter/Cart/QueryHandler/GetCartInformationHandler.php
  src/Core/Domain/Cart/QueryResult/CartInformation/CartSummary.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/shipping.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, migration

#18221 Backport #16837 to 1.7.7.x : Add breadcrumbs to my account pages
  controllers/front/AddressesController.php
  controllers/front/AuthController.php
  controllers/front/DiscountController.php
  controllers/front/GuestTrackingController.php
  controllers/front/HistoryController.php
  controllers/front/IdentityController.php
  controllers/front/MyAccountController.php
  controllers/front/OrderDetailController.php
  controllers/front/OrderSlipController.php
  controllers/front/PasswordController.php
Labels: 1.7.7.x, Improvement, QA ✔️, Wording ✔️

#18064 Fix error when trying to translate Serbian using the BO interface
  src/PrestaShopBundle/Controller/Api/TranslationController.php
  src/PrestaShopBundle/Exception/InvalidLanguageException.php
  src/PrestaShopBundle/Service/TranslationService.php
  tests-legacy/Integration/PrestaShopBundle/Controller/Api/TranslationControllerTest.php
Labels: 1.7.6.x, Bug, QA ✔️

#18309 Change test fixtures that need to be in the future
  tests-legacy/Unit/Classes/ValidateCoreTest.php
Labels: 1.7.6.x, Bug, TE

#17426 Update new-theme webpack to v4.41 and its dependencies
  .gitignore
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/.webpack/prod.js
  admin-dev/themes/new-theme/js/theme.js
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
  admin-dev/themes/new-theme/postcss.config.js
  admin-dev/themes/new-theme/scss/theme.scss
  admin-dev/themes/new-theme/webpack.config.js
Labels: Improvement, QA ✔️, develop

#17526 Fix customer address form
  admin-dev/themes/new-theme/js/pages/address/form.js
  admin-dev/themes/new-theme/public/address.bundle.js
  admin-dev/themes/new-theme/public/attachment.bundle.js
  admin-dev/themes/new-theme/public/attribute.bundle.js
  admin-dev/themes/new-theme/public/attribute_group.bundle.js
  admin-dev/themes/new-theme/public/backup.bundle.js
  admin-dev/themes/new-theme/public/catalog_price_rule.bundle.js
  admin-dev/themes/new-theme/public/category.bundle.js
  admin-dev/themes/new-theme/public/cldr.bundle.js
  admin-dev/themes/new-theme/public/cms_page.bundle.js
  admin-dev/themes/new-theme/public/contacts.bundle.js
  admin-dev/themes/new-theme/public/customer.bundle.js
  admin-dev/themes/new-theme/public/customer_address_form.bundle.js
  admin-dev/themes/new-theme/public/email.bundle.js
  admin-dev/themes/new-theme/public/employee.bundle.js
  admin-dev/themes/new-theme/public/improve_design_positions.bundle.js
  admin-dev/themes/new-theme/public/language.bundle.js
  admin-dev/themes/new-theme/public/maintenance.bundle.js
  admin-dev/themes/new-theme/public/manufacturer.bundle.js
  admin-dev/themes/new-theme/public/manufacturer_address_form.bundle.js
  admin-dev/themes/new-theme/public/meta.bundle.js
  admin-dev/themes/new-theme/public/module.bundle.js
  admin-dev/themes/new-theme/public/module_card.bundle.js
  admin-dev/themes/new-theme/public/order.bundle.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  admin-dev/themes/new-theme/public/order_message.bundle.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  admin-dev/themes/new-theme/public/product_page.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/profiles.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/supplier.bundle.js
  admin-dev/themes/new-theme/public/supplier_form.bundle.js
  admin-dev/themes/new-theme/public/tax.bundle.js
  admin-dev/themes/new-theme/public/tax_rules_group.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
  src/Adapter/Address/CommandHandler/SetRequiredFieldsForAddressHandler.php
  src/Adapter/Form/ChoiceProvider/CountryStateByIdChoiceProvider.php
  src/Core/Domain/Address/Command/SetRequiredFieldsForAddressCommand.php
  src/Core/Form/IdentifiableObject/DataProvider/AddressFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Address/Blocks/form.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️, migration

#18266 Add target options to index grid of orders on customer column
  src/Core/Grid/Column/Type/Common/LinkColumn.php
  src/Core/Grid/Definition/Factory/OrderGridDefinitionFactory.php
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/link.html.twig
Labels: 1.7.7.x, Bug, QA ✔️

#18164 Use hasBeenPaid instead of hasInvoice to enable refund feature
  classes/order/Order.php
  src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php
  src/Adapter/Order/CommandHandler/IssuePartialRefundHandler.php
  src/Adapter/Order/CommandHandler/IssueReturnProductHandler.php
  src/Adapter/Order/CommandHandler/IssueStandardRefundHandler.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Order/Refund/OrderRefundUpdater.php
  src/Core/Domain/Order/Exception/InvalidOrderStateException.php
  src/Core/Domain/Order/QueryResult/OrderForViewing.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/order_actions.html.twig
  tests/Integration/Behaviour/Features/Context/Domain/OrderRefundFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_cancel_product.feature
  tests/Integration/Behaviour/Features/Scenario/Order/partial_refund.feature
  tests/Integration/Behaviour/Features/Scenario/Order/standard_refund.feature
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️, migration

#18314 Removed redundant code
  classes/module/Module.php
Labels: Refactoring, develop

#17920 Wrong redirection when using the quick search for a category
  classes/Tools.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/categories.yml
Labels: 1.7.6.x, Bug, QA ✔️

#17801 View and Create Order feedbacks corrections
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js
  admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js
  admin-dev/themes/new-theme/js/pages/order/view.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js
  admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/config/_settings.scss
  admin-dev/themes/new-theme/scss/pages/_orders.scss
  admin-dev/themes/new-theme/scss/pages/_orders_create.scss
  admin-dev/themes/new-theme/scss/pages/_orders_view.scss
  admin-dev/themes/new-theme/scss/pages/partials/_order-navigation.scss
  src/Core/Form/ChoiceProvider/OrderStateByIdChoiceProvider.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/AddOrderCartRuleType.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/UpdateOrderStatusType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/choice_provider.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/add_order_discount_modal.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/details.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/edit_product_row.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/history.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/messages.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/msg_list_item.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/order_actions.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/order_navigation.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️

#18176 Remove double border in TinyMCE translatable field
  admin-dev/themes/new-theme/scss/components/_tinymce.scss
Labels: Improvement, QA ✔️, develop

#18285 Fix case in path
  tests-legacy/Unit/Classes/CacheCoreTest.php
Labels: Bug, develop

#15100 Change the way to get the price without discounts
  controllers/front/ProductController.php
Labels: Bug, QA ✔️, develop

#18317 Functional tests - Add test 'Update number of products displayed per page'
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/04_pagination/01_updateNumberOfProductsPerPage.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
  tests/puppeteer/pages/FO/category.js
  tests/puppeteer/pages/FO/home.js
Labels: 1.7.7.x, Refactoring, TE

#17938 Fix conversion when adding payment to order
  classes/order/Order.php
  tests/Integration/Behaviour/Features/Context/Configuration/CommonConfigurationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderPaymentFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Customer/customer_management.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_add_payment.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
  tests/Integration/Behaviour/behat.yml
Labels: 1.7.7.x, Bug, Bug fix, QA ✔️

#18339 Fix behat tests that add payments
  tests/Integration/Behaviour/Features/Scenario/Order/partial_refund.feature
  tests/Integration/Behaviour/Features/Scenario/Order/standard_refund.feature
Labels: 1.7.7.x, Bug

#17965 Add HTML IDs and classes to View Customer BO page
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/bought_products.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/carts.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/discounts.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/groups.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/last_connections.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/messages.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/orders.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/personal_information.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/private_note.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/sent_emails.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/viewed_products.html.twig
Labels: 1.7.7.x, Improvement

#18290 Functional tests - Test minimum purchase total required in order to validate the order
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/03_minimumPurchaseTotalRequired.js
  tests/puppeteer/pages/BO/shopParameters/orderSettings/index.js
  tests/puppeteer/pages/FO/cart.js
Labels: 1.7.7.x, Refactoring, TE

#18342 Functional tests - Add test 'Filter stocks by category'
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/05_filterStocksByCategory.js
  tests/puppeteer/campaigns/functional/BO/03_catalog/08_stocks/06_helpCard.js
  tests/puppeteer/pages/BO/catalog/stocks/index.js
Labels: 1.7.7.x, Refactoring, TE

#18311 Functional tests - Add new client filter to order test
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/02_filterOrders.js
Labels: 1.7.7.x, Refactoring, TE

#18308 Functional tests - Add test 'Check delivery slip downloaded from list'
  tests/puppeteer/campaigns/functional/BO/02_orders/01_orders/05_checkDeliverySlipDownloadedFromList.js
  tests/puppeteer/pages/BO/orders/index.js
Labels: 1.7.7.x, Refactoring, TE

#18305 Fix count query with customer filter
  src/Core/Grid/Query/OrderQueryBuilder.php
Labels: 1.7.7.x, Bug, QA ✔️, migration

#17765 Fix shipping price in orders demo
  install-dev/fixtures/fashion/data/order_carrier.xml
  install-dev/fixtures/fashion/data/orders.xml
Labels: Bug, QA ✔️, develop
