Repository PrestaShop/PrestaShop, pull requests merged in 2020-01, with the labels that each got.

#17003 Functional tests - Fix date format (mm/dd/yyyy)
  tests/puppeteer/campaigns/functional/BO/orders/creditSlips/01_createFilterCreditSlips.js
  tests/puppeteer/campaigns/functional/BO/orders/creditSlips/02_generateCreditSlipsByDate.js
  tests/puppeteer/campaigns/functional/BO/orders/deliverySlips/01_generateDeliverySlipByDate.js
  tests/puppeteer/campaigns/functional/BO/orders/invoices/01_generateInvoiceByDate.js
Labels: Refactoring, develop

#17006 Functional tests - Fix supplier name and zip code
  tests/puppeteer/campaigns/data/faker/supplier.js
Labels: Refactoring, TE, develop

#16776 Cover CommandHandlers and QueryHandlers by behat tests
  src/Adapter/Contact/CommandHandler/AddContactHandler.php
  src/Adapter/Contact/QueryHandler/GetContactForEditingHandler.php
  src/Core/Domain/Contact/Command/AddContactCommand.php
  src/Core/Util/BoolParser.php
  tests/Integration/Behaviour/Features/Context/Domain/ContactFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Contact/contact.feature
  tests/Integration/Behaviour/behat.yml
  tests/Unit/Core/Util/BoolParserTest.php
Labels: Improvement, develop, migration

#16966 Cover Category CommandHandlers and QueryHandlers by behat tests
  src/Adapter/Category/CommandHandler/AddCategoryHandler.php
  src/Adapter/Category/CommandHandler/EditCategoryHandler.php
  src/Adapter/Category/QueryHandler/GetCategoryForEditingHandler.php
  tests/Integration/Behaviour/Features/Context/CategoryFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CategoryFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/EmployeeFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Util/CategoryTreeIterator.php
  tests/Integration/Behaviour/Features/Scenario/Category/category_management.feature
Labels: Improvement, develop, migration

#17002 Correcting price alignment on RTL language
  themes/classic/_dev/css/components/featuredproducts.scss
  themes/classic/assets/css/theme.css
  themes/classic/assets/css/theme_rtl.css
Labels: Bug, QA ✔️, develop

#16525 Behat tests for orders in the Back Office. Various Behat features created and scenarios added
  classes/order/Order.php
  src/Adapter/Address/CommandHandler/SetRequiredFieldsForAddressHandler.php
  src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php
  src/Core/Domain/Order/Command/AddOrderFromBackOfficeCommand.php
  src/Core/Domain/Order/QueryResult/OrderPaymentsForViewing.php
  src/Core/Domain/Order/QueryResult/OrderProductsForViewing.php
  src/Core/Domain/Order/QueryResult/OrderShippingForViewing.php
  src/Core/Domain/Product/Query/SearchProducts.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  tests/Integration/Behaviour/Features/Context/CarrierFeatureContext.php
  tests/Integration/Behaviour/Features/Context/CustomerFeatureContext.php
  tests/Integration/Behaviour/Features/Context/CustomerManagerFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/AbstractDomainFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderCartFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderPaymentFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderShippingFeatureContext.php
  tests/Integration/Behaviour/Features/Context/EmployeeFeatureContext.php
  tests/Integration/Behaviour/Features/Context/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/add_order_from_bo.feature
  tests/Integration/Behaviour/Features/Scenario/Order/add_product.feature
  tests/Integration/Behaviour/Features/Scenario/Order/generate_invoice.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
  tests/Integration/Behaviour/behat.yml
Labels: Improvement, develop, migration

#16856 Show list bullets on product page and align it
  themes/classic/_dev/css/components/products.scss
  themes/classic/assets/css/theme.css
Labels: Bug, QA ✔️, develop

#16941 Bad wording when installation check
  install-dev/theme/views/system.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#16946 Modified the string in success alert for attachements bulk deletion
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/AttachmentController.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#17017 Functional tests - Update file bulk action delete message
  tests/puppeteer/campaigns/functional/BO/catalog/files/02_fileBulkActions.js
Labels: Refactoring, TE, develop

#17013 Functional tests - Separate tests team employees and profiles
  tests/puppeteer/campaigns/functional/BO/advancedParameters/team/employees/01_filterAndQuickEditEmployees.js
  tests/puppeteer/campaigns/functional/BO/advancedParameters/team/employees/02_CRUDEmployee.js
  tests/puppeteer/campaigns/functional/BO/advancedParameters/team/employees/03_employeesBulkActions.js
  tests/puppeteer/campaigns/functional/BO/advancedParameters/team/profiles/01_filterProfiles.js
  tests/puppeteer/campaigns/functional/BO/advancedParameters/team/profiles/02_CRUDProfile.js
  tests/puppeteer/campaigns/functional/BO/advancedParameters/team/profiles/03_profileBulkActions.js
Labels: Refactoring, TE, develop

#16962 Functional tests - Crud contact
  tests/puppeteer/campaigns/data/faker/contact.js
  tests/puppeteer/campaigns/functional/BO/shopParameters/contact/02_CRUDContact.js
  tests/puppeteer/pages/BO/shopParameters/contact/add.js
  tests/puppeteer/pages/BO/shopParameters/contact/index.js
Labels: Refactoring, TE, develop

#16967 Functional Tests - Add number verification for delivery slip file
  tests/puppeteer/campaigns/data/faker/deliverySlipOptions.js
  tests/puppeteer/campaigns/functional/BO/orders/deliverySlips/02_deliverySlipOptions/02_deliverySlipNumber.js
  tests/puppeteer/pages/BO/orders/deliverySlips/index.js
Labels: Refactoring, TE, develop

#17009 Functional tests - add test 'Preview Email Themes'
  tests/puppeteer/campaigns/functional/BO/design/emailThemes/01_previewEmailThemes.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/design/emailThemes/index.js
  tests/puppeteer/pages/BO/design/emailThemes/preview.js
Labels: Refactoring, TE, develop

#17041 Functional tests - Fix tests brands and skip test Create unofficial currencies
  tests/puppeteer/campaigns/functional/BO/international/localization/currencies/02_CreateUnofficialCurrency.js
  tests/puppeteer/pages/BO/catalog/brands/add.js
Labels: Refactoring, TE, develop

#16963 Functional tests - add test 'filter languages'
  tests/puppeteer/campaigns/data/demo/languages.js
  tests/puppeteer/campaigns/data/faker/employee.js
  tests/puppeteer/campaigns/functional/BO/international/localization/languages/01_filterLanguages.js
  tests/puppeteer/pages/BO/international/currencies/index.js
  tests/puppeteer/pages/BO/international/languages/index.js
Labels: Refactoring, TE, develop

#17029 Functional Tests - Enable/Disable shop
  tests/puppeteer/campaigns/functional/BO/shopParameters/general/maintenance/01_enableDisableShop.js
  tests/puppeteer/pages/BO/shopParameters/general/maintenance/index.js
  tests/puppeteer/pages/FO/FObasePage.js
  tests/puppeteer/pages/commonPage.js
Labels: Refactoring, TE, develop

#17048 Update nginx configuration
  docs/server_config/nginx.conf.dist
Labels: Improvement, develop

#17005 Adding default "Select" when sort not up in FO is selected on category page
  themes/classic/templates/catalog/_partials/sort-orders.tpl
Labels: Bug, QA ✔️, develop

#16696 Fix email theme permission
  install-dev/data/xml/access.xml
  install-dev/data/xml/authorization_role.xml
  install-dev/data/xml/tab.xml
  install-dev/upgrade/php/copy_tab_rights.php
  install-dev/upgrade/php/ps_1763_update_tabs.php
  install-dev/upgrade/sql/1.7.6.3.sql
Labels: 1.7.6.x, Bug fix, QA ✔️

#17052 Functional tests - Add new test 'Crud language test'
  tests/puppeteer/campaigns/data/faker/language.js
  tests/puppeteer/campaigns/functional/BO/international/localization/languages/02_CRUDLanguage.js
  tests/puppeteer/pages/BO/international/languages/add.js
  tests/puppeteer/pages/BO/international/languages/index.js
  tests/puppeteer/pages/FO/FObasePage.js
Labels: Refactoring, TE, develop

#17049 Functional tests - Contact bulk actions
  tests/puppeteer/campaigns/functional/BO/shopParameters/contact/03_contactBulkActions.js
  tests/puppeteer/pages/BO/shopParameters/contact/add.js
  tests/puppeteer/pages/BO/shopParameters/contact/index.js
Labels: Refactoring, TE, develop

#17047 Functional tests - Enable disable image in delivery slip file
  tests/puppeteer/campaigns/functional/BO/orders/deliverySlips/02_deliverySlipOptions/03_enableDisableProductImage.js
  tests/puppeteer/pages/BO/orders/deliverySlips/index.js
  tests/puppeteer/pages/BO/orders/view.js
Labels: Refactoring, TE, develop

#16714 Update composer.json requirements
  composer.json
  composer.lock
Labels: Improvement, develop

#17060 Functional tests - Filter addresses table
  tests/puppeteer/campaigns/data/demo/address.js
  tests/puppeteer/campaigns/functional/BO/customers/addresses/01_filterAddresses.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/customers/addresses/index.js
Labels: Refactoring, TE, develop

#16998 Fix #16997 - assertion of first/classic theme from unsorted list
  src/Core/MailTemplate/FolderThemeCatalog.php
Labels: 1.7.6.x, Bug

#17030 Ignore rtl assets and remove _rtl.css files
  .gitignore
  themes/classic/assets/css/custom_rtl.css
  themes/classic/assets/css/error_rtl.css
  themes/classic/assets/css/theme_rtl.css
Labels: 1.7.6.x, Bug

#16724 Fix multiple cart rules calculation
  src/Core/Cart/Calculator.php
  src/Core/Cart/CartRow.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/amount_multiple.feature
Labels: 1.7.x, Bug, Bug fix, QA ✔️, develop

#16765 Fix recursive check of updated files
  src/Adapter/Requirement/CheckMissingOrUpdatedFiles.php
Labels: Bug, QA ✔️, develop

#16742 Can't export data more than filters limits
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/SupplierController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
Labels: 1.7.6.x, Bug, QA ✔️

#17067 fix phpdoc on Category constructor
  classes/Category.php
Labels: Improvement, develop

#17066 Functional tests - Update confirm delete files method
  tests/puppeteer/pages/BO/catalog/files/index.js
Labels: Refactoring, TE, develop

#17061 Functional tests - Add base page for localization
  tests/puppeteer/pages/BO/international/currencies/index.js
  tests/puppeteer/pages/BO/international/languages/index.js
  tests/puppeteer/pages/BO/international/localization/index.js
  tests/puppeteer/pages/BO/international/localization/localizationBasePage.js
Labels: Refactoring, TE, develop

#17027 Functional tests - add test 'Filter modules by status'
  tests/puppeteer/campaigns/functional/BO/modules/moduleManager/01_filterModulesByStatus.js
  tests/puppeteer/pages/BO/modules/moduleManager/index.js
Labels: Refactoring, TE, develop

#16809 Fix date parsing in tests when TZ is changed to non-UTC during tests
  tests-legacy/Unit/Classes/ValidateCoreTest.php
Labels: Bug, develop

#17076 Tests - Fix dockerfile for puppeteer
  tests/puppeteer/.docker/Dockerfile
Labels: Refactoring, TE, develop

#16632 Replace deprecated "create_function"
  tests-legacy/resources/modules/gamification/classes/GamificationTools.php
Labels: Refactoring, develop

#17084 Functional tests - Fix error in the test Enable/Disable invoices
  tests/puppeteer/campaigns/functional/BO/orders/invoices/03_invoiceOptions/01_enableDisableInvoices.js
Labels: Refactoring, TE, develop

#17091 Functional tests - Fix Crud language test
  tests/puppeteer/pages/BO/international/languages/index.js
Labels: Refactoring, TE, develop

#17092 Functional tests - Fix other options test
  tests/puppeteer/campaigns/data/faker/invoice.js
Labels: Refactoring, TE, develop

#17079 Improve modal object without using this
  admin-dev/themes/new-theme/js/components/modal.js
  admin-dev/themes/new-theme/public/attachment.bundle.js
Labels: Improvement, QA ✔️, develop

#17069 Fix Currency i18n fields issue in webservice
  classes/Currency.php
Labels: 1.7.6.x, Bug, QA ✔️

#17094 Add twig lint check and move bash script from tests-legacy to tests
  .travis.yml
  tests/check_file_syntax.sh
Labels: Bug, develop

#8770 CO: remove file 'fileType' when deleting images
  classes/Image.php
Labels: Improvement, QA ✔️, develop

#15284 Color and texture consistent when both are set
  classes/Product.php
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combinations.html.twig
  themes/classic/templates/catalog/_partials/facets.tpl
  themes/classic/templates/catalog/_partials/product-variants.tpl
  themes/classic/templates/catalog/_partials/variant-links.tpl
Labels: QA ✔️, Refactoring, develop

#16860 Fix United Kingdom VAT issue for all EU countries
  localization/at.xml
  localization/be.xml
  localization/bg.xml
  localization/cy.xml
  localization/cz.xml
  localization/de.xml
  localization/dk.xml
  localization/ee.xml
  localization/es.xml
  localization/fi.xml
  localization/fr.xml
  localization/gr.xml
  localization/hu.xml
  localization/ie.xml
  localization/it.xml
  localization/lt.xml
  localization/lu.xml
  localization/lv.xml
  localization/mt.xml
  localization/nl.xml
  localization/pl.xml
  localization/pt.xml
  localization/ro.xml
  localization/si.xml
  localization/sk.xml
Labels: Bug, QA ✔️, develop

#16883 Fixed filtering for date in Back Office / Logs
  src/PrestaShopBundle/Entity/Repository/LogRepository.php
Labels: Bug, QA ✔️, develop

#17036 Protect modules vendor folder on install/upgrade/enable
  app/Resources/security/.htaccess.dist
  src/Core/Exception/IOException.php
  src/Core/Security/FolderGuardInterface.php
  src/Core/Security/HtaccessFolderGuard.php
  src/PrestaShopBundle/EventListener/ModuleGuardListener.php
  src/PrestaShopBundle/Resources/config/services/bundle/event_listener.yml
  src/PrestaShopBundle/Resources/config/services/core/security.yml
  tests/Unit/Core/Security/HtaccessFolderGuardTest.php
  tests/Unit/Resources/security/htaccess
Labels: 1.7.6.x, Improvement, QA ✔️

#17071 Fix recursive check of updated files - backport of #16765
  src/Adapter/Requirement/CheckMissingOrUpdatedFiles.php
Labels: 1.7.6.x, Bug, QA ✔️

#17065 Fixed encoding on product name in viewed product
  src/Adapter/Customer/QueryHandler/GetCustomerForViewingHandler.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/viewed_products.html.twig
Labels: 1.7.6.x, Bug, QA ✔️

#16574 Fix product cannot be deleted from cart IF another customization is made and not added to cart yet
  controllers/front/CartController.php
Labels: Bug, QA ✔️, develop

#16520 Fixing contact layout not working at all
  themes/classic/templates/contact.tpl
Labels: Bug, FO, QA ✔️, develop

#15277 Combine two equal adjacent selectors
  themes/classic/_dev/css/components/checkout.scss
Labels: Refactoring, develop

#17050 Quick access error when having a wrong url
  admin-dev/themes/default/template/header.tpl
  admin-dev/themes/new-theme/js/header.js
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/public/catalog.bundle.js
  admin-dev/themes/new-theme/public/catalog_product.bundle.js
  admin-dev/themes/new-theme/public/cldr.bundle.js
  admin-dev/themes/new-theme/public/cms_page_form.bundle.js
  admin-dev/themes/new-theme/public/employee_form.bundle.js
  admin-dev/themes/new-theme/public/form_popover_error.bundle.js
  admin-dev/themes/new-theme/public/geolocation.bundle.js
  admin-dev/themes/new-theme/public/imports.bundle.js
  admin-dev/themes/new-theme/public/improve_design_positions.bundle.js
  admin-dev/themes/new-theme/public/invoices.bundle.js
  admin-dev/themes/new-theme/public/localization.bundle.js
  admin-dev/themes/new-theme/public/logs.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/maintenance.bundle.js
  admin-dev/themes/new-theme/public/module.bundle.js
  admin-dev/themes/new-theme/public/module_card.bundle.js
  admin-dev/themes/new-theme/public/order_delivery.bundle.js
  admin-dev/themes/new-theme/public/order_preferences.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_page.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/themes.bundle.js
  admin-dev/themes/new-theme/public/translation_settings.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  controllers/admin/AdminQuickAccessesController.php
  install-dev/data/xml/quick_access.xml
Labels: 1.7.6.x, Bug, QA ✔️

#17087 Define alert message when error are found in Category Form
  src/Adapter/Category/CommandHandler/AddCategoryHandler.php
  src/Adapter/Category/CommandHandler/EditCategoryHandler.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
Labels: 1.7.6.x, Bug, QA ✔️, Wording ✔️

#16852 Fix a bug where changing quantity on product quickview adds products tags on ever products
  themes/_core/js/product.js
  themes/core.js
  themes/core.js.map
Labels: 1.7.6.x, Bug, QA ✔️

#17129 Functional tests - Set FR text value for custom maintenance text
  tests/puppeteer/pages/BO/shopParameters/general/maintenance/index.js
Labels: Refactoring, TE, develop

#17132 Javascript errors in BO's webservice and login page
  admin-dev/themes/new-theme/js/components/generatable-input.js
  controllers/admin/AdminLoginController.php
Labels: Bug, develop, waiting for QA

#17028 Behat tests for Customer, Address features handlers
  src/Core/Domain/Address/Command/AddCustomerAddressCommand.php
  src/Core/Domain/Address/QueryResult/EditableManufacturerAddress.php
  tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php
  tests/Integration/Behaviour/Features/Context/CustomerManagerFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/AddressFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CustomerFeatureContext.php
  tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Address/address.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
  tests/Integration/Behaviour/behat.yml
Labels: Improvement, develop, migration

#16961 Remove useless customer query filter statements
  src/Core/Grid/Query/CustomerQueryBuilder.php
Labels: Bug, QA ✔️, develop

#17100 Update the number of PrestaShop stores
  install-dev/theme/views/welcome.php
Labels: Improvement, QA ✔️, Wording ✔️, develop

#17130 Make $localizedSymbols variable to be compatible with develop
  classes/Currency.php
Labels: 1.7.6.x, QA ✔️, Refactoring

#16964 Refactor UI kit form theme and apply it to the Performance page
  admin-dev/themes/default/js/bundle/admin_parameters/performancePageUI.js
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/PerformanceController.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/CachingType.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/CombineCompressCacheType.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/DebugModeType.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/MediaServersType.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/MemcacheServerType.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/OptionalFeaturesType.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/SmartyType.php
  src/PrestaShopBundle/Form/Admin/Extension/RowAttributesExtension.php
  src/PrestaShopBundle/Form/Admin/Type/TranslatorAwareType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_extension.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/memcache_servers.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/performance.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: Improvement, QA ✔️, develop

#16956 Changing classic theme filters alignments and spaces
  themes/classic/_dev/css/components/categories.scss
  themes/classic/assets/css/theme.css
Labels: Bug, QA ✔️, develop

#17150 Functional tests - Fix disable shop function
  tests/puppeteer/pages/BO/shopParameters/general/maintenance/index.js
Labels: Refactoring, TE, develop

#17152 Revert "Functional tests - Fix disable shop function"
  tests/puppeteer/pages/BO/shopParameters/general/maintenance/index.js
Labels: TE

#17154 Functional tests - Fix test employee and maintenance
  tests/puppeteer/campaigns/functional/BO/advancedParameters/team/employees/02_CRUDEmployee.js
  tests/puppeteer/pages/BO/login/index.js
  tests/puppeteer/pages/BO/shopParameters/general/maintenance/index.js
Labels: Refactoring, TE, develop

#17155 Refacto refund
  classes/order/Order.php
  classes/order/OrderHistory.php
  src/Adapter/Order/AbstractOrderHandler.php
  src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php
  src/Adapter/Order/CommandHandler/IssuePartialRefundHandler.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Core/Domain/Order/Command/IssuePartialRefundCommand.php
  src/Core/Domain/Order/OrderDocumentType.php
  src/Core/Domain/Order/QueryResult/OrderProductForViewing.php
  src/Core/Domain/Order/ValueObject/OrderDetailRefund.php
  src/Core/Domain/Order/VoucherRefundType.php
  src/Core/Form/IdentifiableObject/DataHandler/PartialRefundFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/PartialRefundFormDataProvider.php
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
  tests/Integration/Behaviour/Features/Context/CustomerFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderRefundFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_refund.feature
  tests/Integration/Behaviour/behat.yml
Labels: 1.7.7.x, Refactoring

#17167 Functional Tests - Fix Enable Disable shop automated test
  tests/puppeteer/pages/BO/shopParameters/general/maintenance/index.js
Labels: 1.7.7.x, Refactoring, TE

#17168 Functional tests - Fix test customer bulk action
  tests/puppeteer/campaigns/functional/BO/customers/customers/03_customersBulkActionsInBO.js
Labels: 1.7.7.x, Refactoring, TE

#17175 Replace partialRefund form/builder/dataProvider with CancelProduct
  src/Core/Form/IdentifiableObject/DataProvider/CancelProductFormDataProvider.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/CancelProductType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_provider.yml
Labels: 1.7.7.x, Refactoring

#17169 Refacto partial refund handler
  src/Adapter/Order/CommandHandler/IssuePartialRefundHandler.php
  src/Adapter/Order/Refund/OrderRefundCalculator.php
  src/Adapter/Order/Refund/OrderRefundSummary.php
  src/Adapter/Order/Refund/OrderSlipCreator.php
  src/Adapter/Order/Refund/VoucherGenerator.php
  src/Core/Domain/Order/ValueObject/OrderDetailRefund.php
  src/PrestaShopBundle/Resources/config/services/adapter/order.yml
Labels: 1.7.7.x, Refactoring, waiting for wording

#17086 Functional tests - Crud customer address
  tests/puppeteer/campaigns/data/faker/address.js
  tests/puppeteer/campaigns/functional/BO/customers/addresses/02_CRUDAddressInBO.js
  tests/puppeteer/pages/BO/customers/addresses/add.js
  tests/puppeteer/pages/BO/customers/addresses/index.js
Labels: Refactoring, TE, develop

#17184 Merge 1.7.7.x into develop - 15/01/2020
  classes/order/Order.php
  classes/order/OrderHistory.php
  src/Adapter/Order/AbstractOrderHandler.php
  src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php
  src/Adapter/Order/CommandHandler/IssuePartialRefundHandler.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Order/Refund/OrderRefundCalculator.php
  src/Adapter/Order/Refund/OrderRefundSummary.php
  src/Adapter/Order/Refund/OrderSlipCreator.php
  src/Adapter/Order/Refund/VoucherGenerator.php
  src/Core/Domain/Order/Command/IssuePartialRefundCommand.php
  src/Core/Domain/Order/OrderDocumentType.php
  src/Core/Domain/Order/QueryResult/OrderProductForViewing.php
  src/Core/Domain/Order/ValueObject/OrderDetailRefund.php
  src/Core/Domain/Order/VoucherRefundType.php
  src/Core/Form/IdentifiableObject/DataHandler/PartialRefundFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/CancelProductFormDataProvider.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/CancelProductType.php
  src/PrestaShopBundle/Resources/config/services/adapter/order.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
  tests/Integration/Behaviour/Features/Context/CustomerFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderRefundFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_refund.feature
  tests/Integration/Behaviour/behat.yml
  tests/puppeteer/campaigns/functional/BO/advancedParameters/team/employees/02_CRUDEmployee.js
  tests/puppeteer/campaigns/functional/BO/customers/customers/03_customersBulkActionsInBO.js
  tests/puppeteer/pages/BO/login/index.js
  tests/puppeteer/pages/BO/shopParameters/general/maintenance/index.js
Labels: Improvement, develop, waiting for wording

#17183 Sanity tests - Fix CRUD standard product with combinations test
  tests/puppeteer/campaigns/functional/BO/catalog/categories/01_filterAndQuickEditCategories.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/catalog/products/add.js
  tests/puppeteer/pages/BO/modules/moduleCatalog/index.js
Labels: Refactoring, TE, develop

#17201 Functional Tests - Fix "emailThemes/01_previewEmailThemes" test
  tests/puppeteer/pages/BO/BObasePage.js
Labels: 1.7.7.x, Refactoring, TE

#17204 Add missing deprecation on previous PerformanceFormHandler
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/PerformanceFormHandler.php
Labels: Improvement, develop

#17214 Revert "Functional tests - Crud customer address"
  tests/puppeteer/campaigns/data/faker/address.js
  tests/puppeteer/campaigns/functional/BO/customers/addresses/02_CRUDAddressInBO.js
  tests/puppeteer/pages/BO/customers/addresses/add.js
  tests/puppeteer/pages/BO/customers/addresses/index.js
Labels: TE

#17229 Recompute FOSJSRouting JSON file
  admin-dev/themes/new-theme/js/fos_js_routes.json
Labels: 1.7.7.x, Bug, waiting for QA

#17232 Rebuild Create an Order page assets
  admin-dev/themes/new-theme/public/order_create.bundle.js
Labels: 1.7.7.x, Bug

#17248 Added RTL Style for Classic Theme
  themes/classic/assets/css/custom_rtl.css
  themes/classic/assets/css/error_rtl.css
  themes/classic/assets/css/theme_rtl.css
Labels: 1.7.6.x, Bug, QA ✔️

#17251 Changelog 1.7.6.3
  docs/CHANGELOG.txt
Labels: 1.7.6.x

#17255 Clean a bit files in install folder
  install-dev/controllers/http/process.php
  install-dev/theme/js/install.js
  install-dev/theme/js/process.js
  install-dev/theme/views/configure.php
  install-dev/theme/views/database.php
  install-dev/theme/views/license.php
Labels: Improvement, develop

#17267 Merge 1.7.6.x into 1.7.7.x - 21/01/2020
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
  themes/classic/assets/css/custom_rtl.css
  themes/classic/assets/css/error_rtl.css
  themes/classic/assets/css/theme_rtl.css
Labels: 1.7.7.x, Improvement

#17180 Fix suppliers form description to be optional
  src/PrestaShopBundle/Form/Admin/Sell/Supplier/SupplierType.php
Labels: 1.7.7.x, Bug, QA ✔️, migration

#16965 Adjusting quantity on product page if empty or under min qty
  themes/classic/_dev/js/product.js
  themes/classic/assets/js/theme.js
Labels: Bug, QA ✔️, develop

#16927 Add BA, BD, CM, MG and SN localization packs
  localization/ba.xml
  localization/bd.xml
  localization/cm.xml
  localization/mg.xml
  localization/sn.xml
Labels: Feature, International, Localization, QA ✔️, develop

#17257 Fix some links with http and no https
  admin-dev/themes/default/template/controllers/login/content.tpl
  admin-dev/themes/default/template/controllers/search/helpers/view/view.tpl
  admin-dev/themes/default/template/footer.tpl
Labels: Improvement, develop

#17272 Functional tests - Limit the legal free text length to 50
  tests/puppeteer/campaigns/data/faker/invoice.js
Labels: 1.7.7.x, Refactoring, TE

#17216 Functional tests - CRUD customer address
  tests/puppeteer/campaigns/data/faker/address.js
  tests/puppeteer/campaigns/functional/BO/04_customers/02_addresses/02_CRUDAddressInBO.js
  tests/puppeteer/pages/BO/customers/addresses/add.js
  tests/puppeteer/pages/BO/customers/addresses/index.js
Labels: 1.7.7.x, Refactoring, TE

#17281 Functional tests - Addresses bulk actions
  tests/puppeteer/campaigns/functional/BO/04_customers/02_addresses/03_addressesBulkActions.js
  tests/puppeteer/pages/BO/customers/addresses/index.js
Labels: 1.7.7.x, Refactoring, TE

#17043 Display symbols in form in case of error, remove DefaultLanguage constraint
  src/PrestaShopBundle/Form/Admin/Improve/International/Currencies/CurrencyType.php
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Currency/Blocks/form.html.twig
Labels: Bug, QA ✔️, develop

#17284 Add new badges to README
  README.md
Labels: Improvement, develop

#16934 Fixing submenu not showing on classic theme
  themes/classic/_dev/css/components/mainmenu.scss
  themes/classic/assets/css/theme.css
Labels: Bug, QA ✔️, develop

#17254 Fix deleted products not being displayed in orders
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Presenter/Order/OrderLazyArray.php
  themes/classic/templates/checkout/_partials/order-confirmation-table.tpl
Labels: 1.7.7.x, Bug, QA ✔️

#17291 Display symbols in form in case of error, remove DefaultLanguage constraint
  src/PrestaShopBundle/Form/Admin/Improve/International/Currencies/CurrencyType.php
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Currency/Blocks/form.html.twig
Labels: 1.7.7.x, Bug

#17286 Enable bulk delete modal for Suppliers, Brands, Brand adresses
  src/Core/Grid/Definition/Factory/ManufacturerAddressGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/ManufacturerGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/SupplierGridDefinitionFactory.php
Labels: 1.7.7.x, Improvement, QA ✔️

#17301 Functional tests - Enable/Disable friendly url
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/seoAndUrls/03_enableDisableFriendlyURL.js
  tests/puppeteer/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/index.js
  tests/puppeteer/pages/commonPage.js
Labels: 1.7.7.x, Refactoring, TE

#17319 Build assets for nightly
  tests/puppeteer/.docker/prestashop/Dockerfile
  tests/puppeteer/.docker/prestashop/docker_run.sh
Labels: Bug, develop, waiting for QA

#17018 Cover Category CommandHandlers and QueryHandlers by behat tests - Part 2
  app/config/config_test.yml
  src/Adapter/Category/CommandHandler/AddRootCategoryHandler.php
  src/Adapter/Image/Uploader/CategoryCoverImageUploader.php
  tests/Integration/Behaviour/Features/Context/Domain/AbstractDomainFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CategoryFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Category/category_management.feature
Labels: Improvement, develop, migration

#17328 Remove PHP GitHub Actions and use PrettyCI only
  .github/workflows/main.yml
  .github/workflows/php.yml
  .prettyci.composer.json
  composer.json
Labels: Improvement, develop

#17329 Functional tests - Fix delete with bulk actions (brand, brand address, supplier) tests
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/seoAndUrls/03_enableDisableFriendlyURL.js
  tests/puppeteer/pages/BO/catalog/brands/index.js
  tests/puppeteer/pages/BO/catalog/suppliers/index.js
  tests/puppeteer/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/index.js
Labels: 1.7.7.x, Refactoring, TE

#17306 Do not force memory_limit in index_cli.php
  install-dev/index_cli.php
  install-dev/init.php
Labels: 1.7.6.x, Bug

#16697 Fix setWsPositionInCategory and setWsCategories, the product position in the categories changes
  classes/Product.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#16620 Prevent order controller from validating all guest addresses
  controllers/front/OrderController.php
Labels: Bug, QA ✔️, develop

#17330 Add make assets while creating release
  tools/build/Library/ReleaseCreator.php
Labels: Improvement, QA ✔️, develop

#17334 Merge 1.7.7.x into develop - 23/01/2020
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/seoAndUrls/03_enableDisableFriendlyURL.js
  tests/puppeteer/pages/BO/catalog/brands/index.js
  tests/puppeteer/pages/BO/catalog/suppliers/index.js
  tests/puppeteer/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/index.js
  tests/puppeteer/pages/commonPage.js
Labels: Improvement, develop

#17340 Remove share buttons after install
  install-dev/theme/js/install.js
  install-dev/theme/view.css
  install-dev/theme/views/process.php
Labels: Improvement, QA ✔️, develop

#17331 ProfileId accepts int and string as input type although int value is required
  src/Adapter/Profile/CommandHandler/AddProfileHandler.php
  src/Core/Domain/Profile/Command/BulkDeleteProfileCommand.php
  src/Core/Domain/Profile/Command/DeleteProfileCommand.php
  src/Core/Domain/Profile/Command/EditProfileCommand.php
  src/Core/Domain/Profile/Query/GetProfileForEditing.php
  src/Core/Domain/Profile/ValueObject/ProfileId.php
  tests/Unit/Core/Domain/Profile/ValueObject/ProfileIdTest.php
Labels: 1.7.7.x, Bug, QA ✔️

#17213 Functional tests - Enable disable catalog mode from product settings page
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_enableDisableCatalogMode.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
  tests/puppeteer/pages/FO/home.js
Labels: 1.7.7.x, Refactoring, TE

#17307 Do not force memory_limit in index_cli.php
  install-dev/index_cli.php
  install-dev/init.php
Labels: 1.7.7.x, Bug

#17372 Functional tests - Activate tests Profiles
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/profiles/02_CRUDProfile.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/profiles/03_profileBulkActions.js
  tests/puppeteer/pages/BO/catalog/brands/index.js
Labels: 1.7.7.x, Refactoring, TE

#17369 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improvement, develop

#17279 Fix monitoring page sorting
  admin-dev/themes/new-theme/js/pages/monitoring/index.js
  admin-dev/themes/new-theme/public/monitoring.bundle.js
Labels: 1.7.7.x, Bug, QA ✔️

#16722 "Orders > Products" : Display content of a pack
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js
  admin-dev/themes/new-theme/js/pages/order/view.js
  admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js
  admin-dev/themes/new-theme/scss/pages/_orders.scss
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Core/Domain/Order/QueryResult/OrderProductForViewing.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/view_product_pack_modal.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig
Labels: 1.7.7.x, Improvement, QA ✔️

#17349 Classic Theme : enable some hooks for BlockReassurance
  themes/classic/config/theme.yml
Labels: 1.7.7.x, Bug, Must-have, QA ✔️

#16553 Avoids webservice to create duplicated customers with same email
  classes/Customer.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#17191 Translate exception message when customer not found on address creation form
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️, migration

#16431 Webservice: Updating category position is changed
  classes/Category.php
Labels: Bug, QA ✔️, WS, develop

#17342 Make rewrite pattern non greedy
  classes/Dispatcher.php
Labels: 1.7.7.x, Bug, QA ✔️

#16863 Fix a bug where product images were not scrollable after product refresh
  themes/classic/_dev/js/product.js
  themes/classic/assets/js/theme.js
Labels: 1.7.7.x, Bug, QA ✔️

#17375 Functional tests - Enable disable accented url
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/seoAndUrls/04_enableDisableAccentedURL.js
  tests/puppeteer/pages/BO/catalog/products/add.js
  tests/puppeteer/pages/BO/catalog/products/index.js
  tests/puppeteer/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/index.js
  tests/puppeteer/pages/commonPage.js
Labels: 1.7.7.x, Refactoring, TE

#17387 Merge 1.7.7.x into develop - 28/01/2020
  admin-dev/themes/new-theme/js/pages/monitoring/index.js
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js
  admin-dev/themes/new-theme/js/pages/order/view.js
  admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js
  admin-dev/themes/new-theme/scss/pages/_orders.scss
  classes/Dispatcher.php
  install-dev/index_cli.php
  install-dev/init.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Profile/CommandHandler/AddProfileHandler.php
  src/Core/Domain/Order/QueryResult/OrderProductForViewing.php
  src/Core/Domain/Profile/Command/BulkDeleteProfileCommand.php
  src/Core/Domain/Profile/Command/DeleteProfileCommand.php
  src/Core/Domain/Profile/Command/EditProfileCommand.php
  src/Core/Domain/Profile/Query/GetProfileForEditing.php
  src/Core/Domain/Profile/ValueObject/ProfileId.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/view_product_pack_modal.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig
  tests/Unit/Core/Domain/Profile/ValueObject/ProfileIdTest.php
  tests/puppeteer/campaigns/functional/BO/13_shopParameters/03_productSettings/01_enableDisableCatalogMode.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/profiles/02_CRUDProfile.js
  tests/puppeteer/campaigns/functional/BO/14_advancedParameters/06_team/profiles/03_profileBulkActions.js
  tests/puppeteer/pages/BO/BObasePage.js
  tests/puppeteer/pages/BO/catalog/brands/index.js
  tests/puppeteer/pages/BO/shopParameters/productSettings/index.js
  tests/puppeteer/pages/FO/home.js
  themes/classic/config/theme.yml
Labels: Improvement, develop

#17386 Functional tests - Enable unofficial currency
  tests/puppeteer/campaigns/functional/BO/11_international/01_localization/currencies/02_CreateUnofficialCurrency.js
  tests/puppeteer/pages/BO/international/currencies/add.js
Labels: 1.7.7.x, Refactoring, TE

#17288 Upgrade Symfony 3.4
  composer.json
  composer.lock
Labels: 1.7.7.x, Bug, QA ✔️

#17389 Do not force the npm to be updated in the build.sh file
  tools/assets/build.sh
Labels: Bug, develop

#17391 Fix develop according to linter
  admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js
Labels: Refactoring, develop

#17233 Fixed error when generating link_rewrite with API
  classes/Product.php
Labels: Bug, QA ✔️, develop

#17405 Functional tests - Improve test enableDisableAccentedURL
  tests/puppeteer/pages/BO/catalog/products/index.js
Labels: 1.7.7.x, Refactoring

#17410 Add FO hook displayFooterCategory
  themes/classic/templates/catalog/listing/product-list.tpl
Labels: 1.7.7.x, Feature

#17211 Reintegrate partial refund in the order view page
  admin-dev/themes/new-theme/js/fos_js_routes.json
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js
  admin-dev/themes/new-theme/js/pages/order/view.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-cancel.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js
  admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/scss/pages/_orders.scss
  classes/order/OrderDetail.php
  classes/order/OrderSlip.php
  install-dev/data/db_structure.sql
  install-dev/fixtures/fashion/data/order_detail.xml
  install-dev/upgrade/sql/1.7.7.0.sql
  src/Adapter/Order/CommandHandler/AbstractOrderCommandHandler.php
  src/Adapter/Order/CommandHandler/IssuePartialRefundHandler.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Order/Refund/OrderRefundCalculator.php
  src/Adapter/Order/Refund/OrderRefundSummary.php
  src/Adapter/Order/Refund/OrderSlipCreator.php
  src/Core/Domain/Order/Command/IssuePartialRefundCommand.php
  src/Core/Domain/Order/Exception/CancelProductFromOrderException.php
  src/Core/Domain/Order/Exception/EmptyRefundAmountException.php
  src/Core/Domain/Order/Exception/InvalidRefundException.php
  src/Core/Domain/Order/QueryResult/OrderForViewing.php
  src/Core/Domain/Order/QueryResult/OrderProductForViewing.php
  src/Core/Domain/Order/ValueObject/OrderDetailRefund.php
  src/Core/Form/IdentifiableObject/DataHandler/PartialRefundFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/CancelProductFormDataProvider.php
  src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/CancelProductType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/order_actions.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
  tests/Integration/Behaviour/Features/Context/CustomerFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/AbstractDomainFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderRefundFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_refund.feature
Labels: 1.7.7.x, Improvement, QA ✔️, Wording ✔️, migration

#17402 Fix reversed product sorting
  src/Core/Product/Search/SortOrdersCollection.php
Labels: Bug, QA ✔️, develop

#17135 Orders > Product : Display "Stock Location" column only if it is not empty
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js
  src/Adapter/Product/QueryHandler/SearchProductsHandler.php
  src/Core/Domain/Product/QueryResult/ProductCombination.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
Labels: 1.7.7.x, Improvement, QA ✔️

#17404 Fix order creation bug due to wrong computing precision
  classes/PaymentModule.php
Labels: 1.7.7.x, Bug, QA ✔️

#17377 Merge pull request #17377 from atomiix/fix-currency-modal
  admin-dev/themes/new-theme/js/pages/currency/form/currency-form.js
  admin-dev/themes/new-theme/public/currency_form.bundle.js
Labels: 1.7.7.x, Bug, QA ✔️

#17413 Merge pull request #17413 from Progi1984/issue17174
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Geolocation/index.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️

#17373 Fix currency localization
  classes/Language.php
Labels: 1.7.7.x, Bug, QA ✔️

#17381 Show product customizations in the order BO page
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js
  admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js
  src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Core/Domain/Order/QueryResult/OrderProductCustomizationForViewing.php
  src/Core/Domain/Order/QueryResult/OrderProductCustomizationsForViewing.php
  src/Core/Domain/Order/QueryResult/OrderProductForViewing.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️

#17446 Fix PHP CS FIXER - again
  classes/Product.php
Labels: Bug, develop

#17325 Fix cart re-rendering after customer not found in Order creation
  admin-dev/themes/new-theme/js/pages/order/create/create-order-map.js
  admin-dev/themes/new-theme/js/pages/order/create/create-order-page.js
  admin-dev/themes/new-theme/js/pages/order/create/customer-manager.js
  admin-dev/themes/new-theme/js/pages/order/create/customer-renderer.js
  admin-dev/themes/new-theme/js/pages/order/create/event-map.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  src/Adapter/Customer/QueryHandler/GetCustomerOrdersHandler.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/create.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, migration

#17418 Functional tests - adding additional information to tests
  tests/puppeteer/campaigns/commonTests/loginBO.js
  tests/puppeteer/campaigns/sanity/01_installShop/01_installShop.js
  tests/puppeteer/campaigns/sanity/02_productsBO/01_filterProducts.js
  tests/puppeteer/campaigns/sanity/02_productsBO/02_CRUDStandardProductInBO.js
  tests/puppeteer/campaigns/sanity/02_productsBO/03_CRUDStandardProductWithCombinationsInBO.js
  tests/puppeteer/campaigns/sanity/02_productsBO/04_deleteProduct.js
  tests/puppeteer/campaigns/sanity/02_productsBO/05_deleteProductsWithBulkActions.js
  tests/puppeteer/campaigns/sanity/03_ordersBO/01_filterOrders.js
  tests/puppeteer/campaigns/sanity/03_ordersBO/02_editOrder.js
  tests/puppeteer/campaigns/sanity/04_catalogFO/01_filterProducts.js
  tests/puppeteer/campaigns/sanity/04_catalogFO/02_checkProduct.js
  tests/puppeteer/campaigns/sanity/05_cartFO/01_editCheckCart.js
  tests/puppeteer/campaigns/sanity/06_checkoutFO/01_orderProduct.js
  tests/puppeteer/campaigns/utils/testContext.js
Labels: 1.7.7.x, Refactoring, TE

#17077 Remove unused legacy Customer Adresses files
  admin-dev/themes/default/template/controllers/addresses/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/addresses/helpers/form/index.php
  admin-dev/themes/default/template/controllers/addresses/helpers/index.php
  admin-dev/themes/default/template/controllers/addresses/helpers/list/index.php
  admin-dev/themes/default/template/controllers/addresses/helpers/list/list_header.tpl
  admin-dev/themes/default/template/controllers/addresses/index.php
  controllers/admin/AdminAddressesController.php
Labels: 1.7.7.x, Refactoring, migration

#17287 Enable bulk delete modal for Languages, Taxes, CMS Pages, CMS Cats
  src/Core/Grid/Definition/Factory/CmsPageCategoryDefinitionFactory.php
  src/Core/Grid/Definition/Factory/CmsPageDefinitionFactory.php
  src/Core/Grid/Definition/Factory/LanguageGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/TaxGridDefinitionFactory.php
Labels: 1.7.7.x, Improvement, QA ✔️, migration

#17443 Functional tests - Add delete modal for tests (taxes and cms pages)
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/03_categoriesBulkActions.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/04_filterAndQuickEditCategories.js
  tests/puppeteer/campaigns/functional/BO/08_design/04_pages/05_pagesBulkActions.js
  tests/puppeteer/pages/BO/catalog/files/index.js
  tests/puppeteer/pages/BO/design/pages/index.js
  tests/puppeteer/pages/BO/international/taxes/index.js
Labels: 1.7.7.x, Refactoring, TE

#17434 Update eslint config to check for hidden directories and files
  admin-dev/themes/new-theme/.eslintignore
  admin-dev/themes/new-theme/.eslintrc.js
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/.webpack/dev.js
  admin-dev/themes/new-theme/.webpack/prod.js
  admin-dev/themes/new-theme/webpack.config.js
Labels: Improvement, develop

#17203 Add override hooks into Presenters
  src/Adapter/Presenter/Cart/CartPresenter.php
  src/Adapter/Presenter/Module/ModulePresenter.php
  src/Adapter/Presenter/Order/OrderPresenter.php
  src/Adapter/Presenter/Order/OrderReturnPresenter.php
  src/Adapter/Presenter/Product/ProductPresenter.php
Labels: Improvement, develop

#17187 Delete migrated AdminRequestSqlController again - part 2
  admin-dev/themes/default/template/controllers/request_sql/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/request_sql/helpers/view/view.tpl
  admin-dev/themes/default/template/controllers/request_sql/list_action_export.tpl
Labels: 1.7.7.x, QA ✔️, Refactoring, migration
