Repository PrestaShop/PrestaShop, pull requests merged in 2020-10, with the labels that each got.

#21225 Add test 'Filter shopping carts'
  tests/UI/campaigns/data/demo/shoppingCarts.js
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/01_filterShoppingCarts.js
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/orders/shoppingCarts/index.js
Labels: 1.7.7.x, Refactoring, TE

#21188 Refactoring create cart rule and faker in tests
  tests/UI/campaigns/data/faker/cartRule.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/02_filterQuickEditAndBulkActionsCartRules.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/03_sortAndPaginationCartRule.js
  tests/UI/pages/BO/catalog/discounts/add.js
  tests/UI/pages/commonPage.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#21211 "/build/" was defined twice in .gitignore root file
  .gitignore
Labels: Improvement, develop, waiting for rebase

#21256 Fix test 'Filter shopping carts'
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/01_filterShoppingCarts.js
Labels: 1.7.7.x, Refactoring, TE

#21246 Update licenses headers
  admin-dev/themes/new-theme/js/pages/improve/design_positions/hook-status-handler.js
  src/Adapter/Hook/CommandHandler/UpdateHookStatusCommandHandler.php
  src/Adapter/Hook/QueryHandler/GetHookStatusHandler.php
  src/Core/Domain/Hook/Command/UpdateHookStatusCommand.php
  src/Core/Domain/Hook/CommandHandler/UpdateHookStatusCommandHandlerInterface.php
  src/Core/Domain/Hook/Exception/CannotUpdateHookException.php
  src/Core/Domain/Hook/Exception/HookConstraintException.php
  src/Core/Domain/Hook/Exception/HookException.php
  src/Core/Domain/Hook/Exception/HookNotFoundException.php
  src/Core/Domain/Hook/Exception/HookUpdateHookException.php
  src/Core/Domain/Hook/Query/GetHookStatus.php
  src/Core/Domain/Hook/QueryHandler/GetHookStatusHandlerInterface.php
  src/Core/Domain/Hook/ValueObject/HookId.php
  src/PrestaShopBundle/Exception/ServiceContainerException.php
  tools/profiling/Hook.php
  tools/profiling/Module.php
  tools/profiling/Profiler.php
  tools/profiling/templates/configuration.tpl
  tools/profiling/templates/doubles.tpl
  tools/profiling/templates/files.tpl
  tools/profiling/templates/functions.tpl
  tools/profiling/templates/functions/load-time.tpl
  tools/profiling/templates/functions/memory.tpl
  tools/profiling/templates/functions/mysql-version.tpl
  tools/profiling/templates/functions/objectmodel.tpl
  tools/profiling/templates/functions/peak-memory.tpl
  tools/profiling/templates/functions/php-version.tpl
  tools/profiling/templates/functions/rows-browsed.tpl
  tools/profiling/templates/functions/sql-queries.tpl
  tools/profiling/templates/functions/table.tpl
  tools/profiling/templates/functions/time.tpl
  tools/profiling/templates/functions/total-queries.tpl
  tools/profiling/templates/functions/total-querying-time.tpl
  tools/profiling/templates/hooks.tpl
  tools/profiling/templates/links.tpl
  tools/profiling/templates/modules.tpl
  tools/profiling/templates/objectmodel.tpl
  tools/profiling/templates/profiling.tpl
  tools/profiling/templates/redirect.tpl
  tools/profiling/templates/run.tpl
  tools/profiling/templates/stopwatch.tpl
  tools/profiling/templates/styles.tpl
  tools/profiling/templates/summary.tpl
  tools/profiling/templates/table-stress.tpl
Labels: Bug, develop

#21250 Fix left sidebar while onboarding is on
  admin-dev/themes/default/sass/partials/_nav.sass
  admin-dev/themes/new-theme/scss/components/layout/_nav_bar.scss
Labels: Bug, Hacktoberfest, QA ✔️, develop

#21265 Fix tests errors in nightly 02/10/2020
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/01_filterShoppingCarts.js
  tests/UI/pages/BO/orders/shoppingCarts/index.js
Labels: 1.7.7.x, Refactoring, TE

#21209 Lower permissions for attachment dummy file
  tests/Integration/Behaviour/Features/Context/Domain/AttachmentFeatureContext.php
Labels: Refactoring, develop

#21277 Fixed call for Windows PrestaShop Components
  admin-dev/themes/new-theme/js/pages/category/index.js
Labels: Bug, QA ✔️, develop

#21264 Clean a bit class AdminController
  classes/controller/AdminController.php
Labels: Improvement, develop

#21226 Modify partial update in AbstractObjectModelRepository to simplify argument & implement it in UpdateProductBasicInformationHandler
  classes/ObjectModel.php
  src/Adapter/AbstractObjectModelRepository.php
  src/Adapter/Product/CommandHandler/UpdateProductBasicInformationHandler.php
  src/Adapter/Product/Update/ProductCustomizationFieldUpdater.php
  src/Adapter/Product/Update/ProductSupplierUpdater.php
  src/Adapter/Product/Validate/ProductValidator.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
Labels: Refactoring, develop, migration

#21255 Add test 'Sort and pagination shopping carts'
  tests/UI/campaigns/data/demo/shoppingCarts.js
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/01_filterShoppingCarts.js
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/02_sortAndPagination.js
  tests/UI/pages/BO/orders/shoppingCarts/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE, waiting for rebase

#21311 Merge 177x into develop 05/10/2020
  tests/UI/campaigns/data/demo/shoppingCarts.js
  tests/UI/campaigns/data/faker/cartRule.js
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/01_filterShoppingCarts.js
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/02_sortAndPagination.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/02_filterQuickEditAndBulkActionsCartRules.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/03_sortAndPaginationCartRule.js
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/catalog/discounts/add.js
  tests/UI/pages/BO/orders/shoppingCarts/index.js
  tests/UI/pages/commonPage.js
Labels: Improvement, develop

#21302 Change UI tests workflow name
  .github/workflows/ui-tests-code-checks.yml
Labels: 1.7.7.x, Refactoring, TE

#21295 Deprecated AddSpecificPriceCommand getter/setter & clarified misnamed property
  src/Adapter/SpecificPrice/CommandHandler/AddSpecificPriceHandler.php
  src/Core/Domain/SpecificPrice/Command/AddSpecificPriceCommand.php
Labels: Deprecations, Refactoring, develop, migration

#21307 Refacto UpdateProductOptionsHandler to use Product repository
  src/Adapter/Manufacturer/Repository/ManufacturerRepository.php
  src/Adapter/Product/CommandHandler/RemoveAllAssociatedProductSuppliersHandler.php
  src/Adapter/Product/CommandHandler/UpdateProductOptionsHandler.php
  src/Adapter/Product/Validate/ProductValidator.php
  src/PrestaShopBundle/Resources/config/services/adapter/manufacturer.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
Labels: Refactoring, develop, migration

#21278 Add test for ArabicToLatinDigitConverter
  tests/Unit/Core/Util/ArabicToLatinDigitConverterTest.php
Labels: Improvement, develop

#21308 Fix tests errors in nightly 04/10/2020
  tests/UI/campaigns/data/faker/group.js
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/02_groups/02_CRUDGroups.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#21266 Fix wrong combination image shown when clicking to zoom
  themes/classic/templates/catalog/_partials/product-images-modal.tpl
Labels: 1.7.7.x, Bug, QA ✔️

#21279 Carrier: improve documentation of shipping properties
  classes/Carrier.php
Labels: Documentation, Improvement, QA ✔️, develop

#21324 Add new test 'Change position for attributes and values'
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/01_filterAttributes.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/02_filterAttributeValues.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/03_CRUDAttributesAndValues.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/04_bulkDeleteAttributes.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/05_sortAndPagination.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/06_changeAttributePosition.js
  tests/UI/pages/BO/catalog/attributes/index.js
  tests/UI/pages/BO/catalog/attributes/view.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#21310 Fix delete order state confirmation
  controllers/admin/AdminStatusesController.php
Labels: 1.7.7.x, Bug, QA ✔️

#21314 Tools::getDefaultIndexContent() generates obsolete headers
  classes/Tools.php
Labels: Bug, develop

#21217 Make FO product delivery time bold
  themes/classic/_dev/css/components/products.scss
Labels: Improvement, QA ✔️, develop

#21057 Reduce conditions complexity
  classes/Cart.php
Labels: Improvement, QA ✔️, develop

#21327 Create first test 'Computing precision set to 3' for UI tests new campaign 'Regression'
  tests/UI/campaigns/data/FO/cart.js
  tests/UI/campaigns/data/demo/products.js
  tests/UI/campaigns/data/faker/cartRule.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule.js
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/04_quantityDiscountsBasedOn.js
  tests/UI/campaigns/regression/currencies/computingPrecision_FO.js
  tests/UI/campaigns/sanity/05_cartFO/01_editCheckCart.js
  tests/UI/package.json
  tests/UI/pages/BO/advancedParameters/database/sqlManager/view.js
  tests/UI/pages/BO/catalog/discounts/add.js
  tests/UI/pages/BO/international/currencies/add.js
  tests/UI/pages/BO/orders/index.js
  tests/UI/pages/FO/cart/index.js
  tests/UI/pages/FO/product/index.js
Labels: 1.7.7.x, Refactoring, TE

#21330 Return a real 404 when product doesn't exist instead of a 302 redirection
  controllers/front/ProductController.php
  themes/classic/templates/errors/404.tpl
Labels: Hacktoberfest, Improvement, QA ✔️, develop

#21218 Fix tab entity tabLangs variable mapping
  src/PrestaShopBundle/Entity/Tab.php
Labels: Bug, QA ✔️, develop

#21260 Remove Add/Update/Delete CustomizationField handlers (Redundant & Untested)
  src/Adapter/Product/CommandHandler/AddCustomizationFieldHandler.php
  src/Adapter/Product/CommandHandler/DeleteCustomizationFieldHandler.php
  src/Adapter/Product/CommandHandler/UpdateCustomizationFieldHandler.php
  src/Core/Domain/Product/Customization/CommandHandler/AddCustomizationFieldHandlerInterface.php
  src/Core/Domain/Product/Customization/CommandHandler/DeleteCustomizationFieldHandlerInterface.php
  src/Core/Domain/Product/Customization/CommandHandler/UpdateCustomizationFieldHandlerInterface.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
Labels: Improvement, develop, migration

#21215 Improvement/emphasize irreversibly of thumbs regeneration
  admin-dev/themes/default/template/controllers/images/content.tpl
Labels: Improvement, QA ✔️, Wording ✔️, develop

#21339 Delete all references to ttc in UI folder
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule.js
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/04_quantityDiscountsBasedOn.js
  tests/UI/campaigns/regression/currencies/computingPrecision_FO.js
  tests/UI/campaigns/sanity/02_productsBO/01_filterProducts.js
  tests/UI/campaigns/sanity/02_productsBO/02_CRUDStandardProductInBO.js
  tests/UI/campaigns/sanity/05_cartFO/01_editCheckCart.js
  tests/UI/pages/BO/catalog/products/add.js
  tests/UI/pages/BO/catalog/products/index.js
  tests/UI/pages/BO/orders/index.js
Labels: 1.7.7.x, Refactoring, TE

#21341 Fix test 'CRUD carrier' in nightly 07/10/2020
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/01_CRUDCarrier.js
Labels: 1.7.7.x, Hacktoberfest, Refactoring, TE

#21239 Fix deletion message in edit product page
  admin-dev/themes/default/js/bundle/product/form.js
  admin-dev/themes/default/js/bundle/product/product-combinations.js
  admin-dev/themes/default/js/bundle/product/product-manufacturer.js
  admin-dev/themes/default/js/bundle/product/product-related.js
  admin-dev/themes/new-theme/js/pages/catalog/product/specific-price-form-handler.js
  admin-dev/themes/new-theme/js/product-page/product-bulk-combinations.js
  admin-dev/themes/new-theme/js/product-page/product-search-autocomplete.js
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/product.html.twig
Labels: Bug, Hacktoberfest, QA ✔️, develop

#20882 Recompute specific price tax excluded when mismatch with price tax included
  src/Adapter/Number/RoundModeConverter.php
  src/Adapter/Order/AbstractOrderHandler.php
  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
  src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php
  src/Adapter/Order/OrderAmountUpdater.php
  src/Adapter/Order/OrderProductQuantityUpdater.php
  src/Adapter/Order/QueryHandler/GetOrderProductsForViewingHandler.php
  tests/Integration/Behaviour/Features/Context/CarrierFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/TaxFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_french_tax.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
  tests/Integration/Behaviour/Features/Scenario/Order/partial_refund.feature
Labels: 1.7.7.x, Bug, QA ✔️

#21334 Create state with only iso code that does not exist
  tests/UI/campaigns/data/faker/state.js
Labels: 1.7.7.x, Refactoring, TE

#21297 Fix variable name in order_customer_comment.html.twig
  mails/themes/modern/core/order_customer_comment.html.twig
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️

#21328 Improve SQL requests on specific prices
  classes/SpecificPrice.php
Labels: Improvement, develop

#20653 HelperForm field label not work in switch type
  admin-dev/themes/default/template/helpers/form/form.tpl
  classes/helper/HelperForm.php
  controllers/admin/AdminCarrierWizardController.php
  controllers/admin/AdminCarriersController.php
  controllers/admin/AdminCountriesController.php
  controllers/admin/AdminGroupsController.php
  controllers/admin/AdminImagesController.php
  controllers/admin/AdminQuickAccessesController.php
  controllers/admin/AdminStatesController.php
  controllers/admin/AdminStoresController.php
  controllers/admin/AdminSuppliersController.php
  controllers/admin/AdminTabsController.php
  controllers/admin/AdminTaxRulesGroupController.php
  controllers/admin/AdminZonesController.php
Labels: Bug, PM ✔️, QA ✔️, Wording ✔️, develop

#21344 Move product search controller that was not in the right place
  admin-dev/themes/new-theme/js/fos_js_routes.json
  admin-dev/themes/new-theme/js/pages/order/create/product-manager.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add-autocomplete.js
  admin-dev/themes/new-theme/public/order.bundle.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products/product.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/_orders.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
Labels: 1.7.7.x, Bug, QA ✔️

#21168 Fix FrontController names in modules hook-exceptions
  classes/Dispatcher.php
  controllers/admin/AdminModulesPositionsController.php
Labels: Bug, QA ✔️, develop

#20927 Avoid possible notice due to breaking change
  themes/classic/templates/catalog/_partials/miniatures/product.tpl
Labels: 1.7.7.x, Bug, QA ✔️

#21317 Notifications bell icon read fix (Backport)
  src/Adapter/Notification/CommandHandler/UpdateEmployeeNotificationLastElementHandler.php
Labels: 1.7.7.x, Bug, QA ✔️

#21367 Add test 'CRUD catalog price rule'
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/02_catalogPriceRules/01_CRUDCatalogPriceRule.js
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/06_displayDiscountedPrice.js
  tests/UI/pages/BO/catalog/discounts/catalogPriceRules/add.js
  tests/UI/pages/BO/catalog/discounts/catalogPriceRules/index.js
  tests/UI/pages/FO/product/index.js
Labels: 1.7.7.x, Hacktoberfest, Refactoring, TE

#21343 Fix status dropdown of order listing page not being well displayed using rtl language
  admin-dev/themes/new-theme/public/theme.rtlfix
Labels: 1.7.7.x, Bug, Hacktoberfest, QA ✔️

#21232 Fix tab modules list
  classes/Tab.php
  classes/Tools.php
  classes/controller/AdminController.php
  controllers/admin/AdminCarriersController.php
  controllers/admin/AdminModulesController.php
  controllers/admin/AdminStatsTabController.php
  controllers/admin/AdminSuppliersController.php
Labels: 1.7.7.x, Bug fix, QA ✔️

#20201 Fix throw InstallControllerHttpSystem::trans during installation process
  install-dev/theme/views/system.php
Labels: 1.7.7.x, Bug, QA ✔️, Wording ✔️, develop

#21365 Fixed Currency Numeric Iso Code (Nullable & Default Value)
  .github/workflows/phpstan.yml
  classes/Currency.php
  install-dev/upgrade/sql/1.7.8.0.sql
Labels: Bug, QA ✔️, develop

#21335 Fixed "Add new alias" button which was disappearing after adding a new alias. [BO][Shop param][search]
  controllers/admin/AdminSearchConfController.php
Labels: Bug, QA ✔️, develop

#21372 Update decimal number to version 1.4 And update all use statements
  classes/Product.php
  composer.json
  composer.lock
  src/Adapter/Cart/QueryHandler/GetCartInformationHandler.php
  src/Adapter/CatalogPriceRule/QueryHandler/GetCatalogPriceRuleForEditingHandler.php
  src/Adapter/CombinationDataProvider.php
  src/Adapter/Order/AbstractOrderHandler.php
  src/Adapter/Order/CommandHandler/IssueReturnProductHandler.php
  src/Adapter/Order/CommandHandler/IssueStandardRefundHandler.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Order/QueryHandler/GetOrderPreviewHandler.php
  src/Adapter/Order/QueryHandler/GetOrderProductsForViewingHandler.php
  src/Adapter/Order/Refund/OrderRefundCalculator.php
  src/Adapter/Presenter/Product/ProductLazyArray.php
  src/Adapter/Product/CommandHandler/UpdateProductPricesHandler.php
  src/Adapter/Tools.php
  src/Core/Currency/ExchangeRateProvider.php
  src/Core/Domain/CartRule/Command/AddCartRuleCommand.php
  src/Core/Domain/CatalogPriceRule/Command/AddCatalogPriceRuleCommand.php
  src/Core/Domain/CatalogPriceRule/QueryResult/EditableCatalogPriceRule.php
  src/Core/Domain/Currency/QueryResult/ExchangeRate.php
  src/Core/Domain/Currency/ValueObject/ExchangeRate.php
  src/Core/Domain/Order/Command/AbstractRefundCommand.php
  src/Core/Domain/Order/Command/AddCartRuleToOrderCommand.php
  src/Core/Domain/Order/Command/IssuePartialRefundCommand.php
  src/Core/Domain/Order/Payment/Command/AddPaymentCommand.php
  src/Core/Domain/Order/Product/Command/AddProductToOrderCommand.php
  src/Core/Domain/Order/Product/Command/UpdateProductInOrderCommand.php
  src/Core/Domain/Order/QueryResult/OrderDiscountForViewing.php
  src/Core/Domain/Order/QueryResult/OrderPricesForViewing.php
  src/Core/Domain/Order/ValueObject/OrderDetailRefund.php
  src/Core/Domain/Product/Command/UpdateProductPricesCommand.php
  src/Core/Domain/Product/Command/UpdateProductShippingCommand.php
  src/Core/Domain/Product/QueryResult/ProductPricesInformation.php
  src/Core/Domain/Product/QueryResult/ProductShippingInformation.php
  src/Core/Domain/SpecificPrice/Command/AddSpecificPriceCommand.php
  src/Core/Domain/ValueObject/Money.php
  src/Core/Domain/ValueObject/Reduction.php
  src/Core/Localization/Number/Formatter.php
  src/Core/Util/Number/NumberExtractor.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/CancelProductType.php
  src/PrestaShopBundle/Twig/Extension/NumberExtension.php
  tests/Integration/Behaviour/Features/Context/Domain/CartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePricesFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateProductSuppliersFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateShippingFeatureContext.php
  tests/Unit/Core/Domain/CartRule/ValueObject/CartRuleAction/CartRuleActionBuilderTest.php
  tests/Unit/Core/Domain/ValueObject/MoneyTest.php
  tests/Unit/Core/Util/Number/NumberExtractorTest.php
Labels: Developer Feature, Improvement, develop

#21325 Introduce ProductShippingUpdater & use it in UpdateShippingHandler
  src/Adapter/Product/CommandHandler/UpdateProductShippingHandler.php
  src/Adapter/Product/Validate/ProductValidator.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
Labels: Refactoring, develop, migration

#21396 Add navigation when selecting pagination limit
  tests/UI/pages/BO/catalog/categories/index.js
Labels: 1.7.7.x, Refactoring, TE

#21394 Correct product meta-title after changing variant
  controllers/front/ProductController.php
Labels: Bug, QA ✔️, develop

#21355 Simplifies geolocation form
  admin-dev/themes/new-theme/js/app/utils/init-components.js
  admin-dev/themes/new-theme/js/pages/geolocation/index.js
  src/PrestaShopBundle/Form/Admin/Improve/International/Geolocation/GeolocationByIpAddressType.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Geolocation/GeolocationIpAddressWhitelistType.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Geolocation/GeolocationOptionsType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Geolocation/Blocks/geolocation_by_ip_address.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Geolocation/Blocks/geolocation_ip_address_whitelist.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Geolocation/Blocks/geolocation_options.html.twig
Labels: QA ✔️, Refactoring, develop, migration

#21237 Fix the french exotax percentage displayed as an example
  src/PrestaShopBundle/Form/Admin/Improve/International/Tax/TaxOptionsType.php
Labels: Bug, Hacktoberfest, QA ✔️, Wording ✔️, develop

#21346 Removed order of languages in TranslatableType field for migrated pages
  src/Adapter/LegacyContext.php
Labels: Bug, QA ✔️, develop

#21313 Sanitize product sort order
  src/Core/Product/Search/SortOrder.php
Labels: Bug, Hacktoberfest, PM ✔️, QA ✔️, develop

#21401 Fix address item different height in checkout
  themes/classic/_dev/css/components/checkout.scss
Labels: Bug, Hacktoberfest, QA ✔️, develop

#21385 Add test 'Filter and bulk actions catalog price rules'
  tests/UI/campaigns/data/faker/catalogPriceRule.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/02_catalogPriceRules/02_filterAndBulkActions.js
  tests/UI/pages/BO/catalog/discounts/catalogPriceRules/add.js
  tests/UI/pages/BO/catalog/discounts/catalogPriceRules/index.js
Labels: 1.7.7.x, Hacktoberfest, QA ✔️, Refactoring, TE

#21332 Replace spread by condition and assign, add an event to init components
  admin-dev/themes/new-theme/js/app/utils/init-components.js
Labels: Improvement, QA ✔️, develop

#20942 Use SF cache pool prune after module action
  src/Adapter/Cache/Clearer/SymfonyCacheClearer.php
  src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php
Labels: Bug, QA ✔️, develop

#21362 Possibility to check if we're in product quick view mode
  controllers/front/ProductController.php
  themes/_core/js/product.js
Labels: 1.7.7.x, Bug, QA ✔️

#21377 New hooks for ProductListingFrontController
  classes/controller/ProductListingFrontController.php
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.8.0.sql
Labels: Feature, QA ✔️, develop

#21402 Add test 'Sort and pagination zones table'
  tests/UI/campaigns/functional/BO/11_international/02_locations/01_zones/04_sortAndPagination.js
  tests/UI/pages/BO/international/locations/index.js
Labels: 1.7.7.x, Hacktoberfest, QA ✔️, Refactoring, TE

#21093 Fix function typo when changing address on create order
  admin-dev/themes/new-theme/js/pages/order/create/create-order-page.js
Labels: Bug, QA ✔️, develop

#20980 Use assembler to present products in cart
  src/Adapter/Presenter/Cart/CartPresenter.php
Labels: Bug, QA ✔️, develop

#20140 Add hooks to cart modal - crosseling and promotion
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.8.0.sql
  themes/classic/modules/ps_shoppingcart/modal.tpl
Labels: Improvement, QA ✔️, develop

#21360 Change typo function name initOrderStatutsList
  controllers/admin/AdminStatusesController.php
Labels: Refactoring, develop

#21326 Set order currency to added cart rule
  app/AppKernel.php
  src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php
  src/Adapter/Order/CommandHandler/DeleteCartRuleFromOrderHandler.php
  src/Adapter/Order/OrderAmountUpdater.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/PrestaShopBundle/Resources/config/services/adapter/order.yml
  tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_currency.feature
Labels: 1.7.7.x, Bug, Must-have, QA ✔️

#21432 Fixed Configuration when Disabling/Enabling Shop
  src/Adapter/Shop/MaintenanceConfiguration.php
Labels: 1.7.7.x, Bug, QA ✔️

#21407 Fixed typo in wording in modal.tpl
  themes/classic/modules/ps_shoppingcart/modal.tpl
Labels: Bug, develop

#21338 Feature/simplifiy localization form
  src/PrestaShopBundle/Form/Admin/Improve/International/Localization/AdvancedConfigurationType.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Localization/ImportLocalizationPackType.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Localization/LocalUnitsType.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Localization/LocalizationConfigurationType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Localization/Blocks/advanced_configuration.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Localization/Blocks/configuration.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Localization/Blocks/import_localization_pack_block.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Localization/Blocks/local_units.html.twig
Labels: BC break, QA ✔️, Refactoring, develop, migration

#21433 Fix a small error in nightly 14-10-2020
  tests/UI/campaigns/utils/globals.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#21429 Fix symfony cache clear
  src/Adapter/Cache/Clearer/SymfonyCacheClearer.php
Labels: Bug, QA ✔️, develop

#21390 Fix getting proper cover for image
  classes/Product.php
Labels: 1.7.7.x, Bug, QA ✔️

#21435 Add hooks for the AdminLoginController, AdminController, FrontController and Controller
  classes/controller/AdminController.php
  classes/controller/Controller.php
  classes/controller/FrontController.php
  controllers/admin/AdminLoginController.php
  install-dev/data/xml/hook.xml
  install-dev/data/xml/hook_alias.xml
  install-dev/upgrade/sql/1.7.7.0.sql
Labels: 1.7.7.x, Improvement, QA ✔️

#21458 Two Time actionAdminLoginControllerResetBefore
  install-dev/data/xml/hook.xml
Labels: 1.7.7.x, Bug

#21415 Add test 'Filter, sort and pagination tax rules group'
  tests/UI/campaigns/functional/BO/11_international/03_taxes/taxRules/01_CRUDTaxRules.js
  tests/UI/campaigns/functional/BO/11_international/03_taxes/taxRules/02_filterSortAndPagination.js
  tests/UI/pages/BO/international/taxes/taxRules/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#21411 Add test 'Sort and pagination states table'
  tests/UI/campaigns/functional/BO/11_international/02_locations/03_states/04_sortAndPagination.js
  tests/UI/pages/BO/international/locations/states/index.js
Labels: 1.7.7.x, Hacktoberfest, QA ✔️, Refactoring, TE

#21403 Add test 'Sort and pagination countries table'
  tests/UI/campaigns/functional/BO/11_international/02_locations/02_countries/04_sortAndPagination.js
  tests/UI/pages/BO/international/locations/countries/index.js
Labels: 1.7.7.x, Hacktoberfest, QA ✔️, Refactoring, TE

#21405 Add test 'Filter, sort and pagination search engines'
  tests/UI/campaigns/data/demo/searchEngines.js
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/02_searchEngines/01_filterSortAndPagination.js
  tests/UI/pages/BO/shopParameters/trafficAndSeo/searchEngines/index.js
  tests/UI/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#21399 Add test 'Help card on attributes page'
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/07_helperCard.js
  tests/UI/pages/BO/catalog/attributes/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#21452 Fix page name in orders tests
  tests/UI/campaigns/functional/BO/02_orders/01_orders/08_viewCustomer.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/09_viewGuest.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#21453 Update INSTALL.txt
  INSTALL.txt
Labels: Refactoring, develop

#21459 Add test 'CRUD order status'
  tests/UI/campaigns/data/faker/orderStatus.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/01_CRUDOrderStatus.js
  tests/UI/pages/BO/orders/view.js
  tests/UI/pages/BO/shopParameters/orderSettings/index.js
  tests/UI/pages/BO/shopParameters/orderSettings/statuses/add.js
  tests/UI/pages/BO/shopParameters/orderSettings/statuses/index.js
Labels: 1.7.7.x, Refactoring, TE

#21467 Fix help link in Create order
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
Labels: 1.7.7.x, Bug, QA ✔️

#21114 Fixed CSS issues when using DisplayProductPriceBlock
  themes/classic/_dev/css/components/featuredproducts.scss
Labels: Improvement, QA ✔️, develop

#21462 Add var for visible selectors in methods
  tests/UI/pages/BO/catalog/attributes/index.js
  tests/UI/pages/BO/design/imageSettings/index.js
Labels: 1.7.7.x, Refactoring, TE

#21258 Added 404 page without redirections on category page if category doesn't exists
  controllers/front/listing/CategoryController.php
Labels: Improvement, QA ✔️, Wording ✔️, develop

#21351 BO - Import CSV - sample for manufacturer not OK
  docs/csv_import/brands_import.csv
  docs/csv_import/manufacturers_import.csv
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Blocks/import_sample_files.html.twig
Labels: Bug, QA ✔️, develop

#21473 Add test 'Filter sort and pagination order status'
  tests/UI/campaigns/data/demo/orderStatuses.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/01_CRUDOrderStatus.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/02_filterSortAndPaginationOrderStatus.js
  tests/UI/pages/BO/shopParameters/orderSettings/statuses/index.js
Labels: 1.7.7.x, Refactoring, TE

#21481 Add test 'Sort and pagination price rule'
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/02_catalogPriceRules/02_filterAndBulkActions.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/02_catalogPriceRules/02_filterSortAndPagination.js
  tests/UI/pages/BO/catalog/discounts/catalogPriceRules/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#21400 Introduce ProductPackUpdater & add behats for packing combinations
  src/Adapter/Product/CommandHandler/RemoveAllProductsFromPackHandler.php
  src/Adapter/Product/CommandHandler/SetPackProductsHandler.php
  src/Adapter/Product/Repository/ProductPackRepository.php
  src/Adapter/Product/Update/ProductPackUpdater.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePackFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/update_pack.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_related_products.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_suppliers.feature
Labels: Refactoring, develop, migration

#21497 Improve behat config which did not use appropriate format for paths
  tests/Integration/Behaviour/behat.yml
Labels: 1.7.7.x, Improvement, waiting for dev

#21253 Rename product price fields labels
  src/PrestaShopBundle/Form/Admin/Product/ProductPrice.php
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_supplier_combination.html.twig
Labels: Hacktoberfest, Improvement, QA ✔️, Wording ✔️, develop

#21447 Synchronize OrderDetail with Cart when removing a voucher
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js
  admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js
  admin-dev/themes/new-theme/public/currency_form.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  src/Adapter/Cart/CommandHandler/UpdateProductQuantityInCartHandler.php
  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
  src/Adapter/Order/CommandHandler/DeleteCartRuleFromOrderHandler.php
  src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php
  src/Adapter/Order/OrderAmountUpdater.php
  src/Adapter/Order/OrderProductQuantityUpdater.php
  src/Adapter/Order/Refund/OrderProductRemover.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/config/services/adapter/cart.yml
  src/PrestaShopBundle/Resources/config/services/adapter/order.yml
  tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature
  themes/classic/templates/checkout/_partials/order-confirmation-table.tpl
Labels: 1.7.7.x, Bug, QA ✔️

#21490 Title tag required to make html 5 valid
  error500.html
Labels: Improvement, develop

#21499 Fixed PHPDoc
  src/Adapter/Currency/CommandHandler/AddUnofficialCurrencyHandler.php
  src/Adapter/Product/Repository/ProductRepository.php
Labels: Bug, develop

#21505 Add test pagination stores
  tests/UI/campaigns/functional/BO/13_shopParameters/05_contact/stores/04_sortAndPagination.js
  tests/UI/pages/BO/shopParameters/stores/index.js
Labels: 1.7.7.x, Refactoring, TE

#21449 Update modules (blockreassurance/dashtrends/ps_checkpayment/welcome)
  composer.json
  composer.lock
Labels: 1.7.7.x, Improvement, QA ✔️

#21508 Add test 'CRUD search engines'
  tests/UI/campaigns/data/faker/searchEngine.js
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/02_searchEngines/02_CRUDSearchEngines.js
  tests/UI/pages/BO/shopParameters/trafficAndSeo/searchEngines/add.js
  tests/UI/pages/BO/shopParameters/trafficAndSeo/searchEngines/index.js
Labels: 1.7.7.x, Refactoring, TE

#21509 Update catalog with latest wordings
  app/Resources/translations/default/AdminActions.xlf
  app/Resources/translations/default/AdminAdvparametersFeature.xlf
  app/Resources/translations/default/AdminCatalogHelp.xlf
  app/Resources/translations/default/AdminCatalogNotification.xlf
  app/Resources/translations/default/AdminDesignNotification.xlf
  app/Resources/translations/default/AdminGlobal.xlf
  app/Resources/translations/default/AdminLoginNotification.xlf
  app/Resources/translations/default/AdminNavigationNotification.xlf
  app/Resources/translations/default/AdminNotificationsError.xlf
  app/Resources/translations/default/AdminNotificationsSuccess.xlf
  app/Resources/translations/default/AdminOrderscustomersFeature.xlf
  app/Resources/translations/default/AdminOrderscustomersNotification.xlf
  app/Resources/translations/default/AdminShopparametersNotification.xlf
  app/Resources/translations/default/AdminStatsFeature.xlf
  app/Resources/translations/default/AdminStatsNotification.xlf
  app/Resources/translations/default/ShopNotificationsError.xlf
  app/Resources/translations/default/ShopNotificationsWarning.xlf
  app/Resources/translations/default/ShopThemeCatalog.xlf
  app/Resources/translations/default/ShopThemeGlobal.xlf
  app/Resources/translations/default/messages.xlf
Labels: 1.7.7.x, Improvement, waiting for wording

#21512 Add tests 'Helper card' for catalog pages
  tests/UI/campaigns/functional/BO/03_catalog/01_products/03_helperCard.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/03_helperCard.js
  tests/UI/campaigns/functional/BO/03_catalog/06_files/04_helperCard.js
  tests/UI/pages/BO/catalog/features/index.js
Labels: 1.7.7.x, Refactoring, TE

#21498 Fix test 'Download sample file'
  tests/UI/campaigns/functional/BO/14_advancedParameters/05_import/01_downloadSampleFiles.js
Labels: Refactoring, TE, develop

#21523 Several fixes found via PHPStan while mergin to develop
  src/Adapter/Cart/CommandHandler/UpdateCartDeliverySettingsHandler.php
  src/Adapter/Configuration.php
  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
Labels: 1.7.7.x, Bug

#21485 Prevent page freeze because off multiple add to cart clicks
  themes/_core/js/cart.js
Labels: Bug, QA ✔️, develop

#21513 Change classic readme in order to avoid missunderstanding
  themes/classic/README.md
Labels: Improvement, develop

#21511 Remove unused webpack and npm files in admin-dev
  admin-dev/package-lock.json
  admin-dev/package.json
  admin-dev/webpack.config.js
Labels: Hacktoberfest, Improvement, develop

#21532 Update behat and gerkhin to allow debugging in PHPStorm
  composer.lock
Labels: 1.7.7.x, Bug, waiting for dev

#21544 Fix image name for CRUD title test
  tests/UI/campaigns/data/faker/title.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#21464 index.html does not exist in INSTALL.txt
  INSTALL.txt
Labels: Improvement, develop

#21537 Fix typo in Product Object code
  classes/Product.php
Labels: Documentation, Improvement, develop

#21517 Add test 'Tax rules bulk actions'
  tests/UI/campaigns/functional/BO/11_international/03_taxes/taxRules/03_bulkActions.js
  tests/UI/pages/BO/international/taxes/taxRules/index.js
Labels: Refactoring, TE, develop

#21570 Upgrade playwright to v1.5.1
  tests/UI/package-lock.json
  tests/UI/package.json
  tests/UI/pages/BO/catalog/products/add.js
  tests/UI/pages/BO/shipping/carriers/add.js
Labels: Refactoring, TE, develop

#21569 Use ubuntu Latest for PHPStan GA
  .github/workflows/phpstan.yml
Labels: Bug, develop

#21580 Update view customer selectors
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/carts.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/orders.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/personal_information.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/private_note.html.twig
  tests/UI/pages/BO/customers/view.js
Labels: QA ✔️, Refactoring, TE, develop

#21589 Fix fail on sanity tests on travis
  tests/UI/pages/FO/home/index.js
Labels: QA ✔️, Refactoring, TE, develop

#21574 Allow ContextStateManager to stash contexts
  classes/Cart.php
  src/Adapter/Cart/CommandHandler/AddCartRuleToCartHandler.php
  src/Adapter/Cart/CommandHandler/UpdateCartCarrierHandler.php
  src/Adapter/Cart/CommandHandler/UpdateProductQuantityInCartHandler.php
  src/Adapter/Cart/QueryHandler/GetCartInformationHandler.php
  src/Adapter/ContextStateManager.php
  src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php
  src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php
  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
  src/Adapter/Order/CommandHandler/DeleteCartRuleFromOrderHandler.php
  src/Adapter/Order/CommandHandler/DeleteProductFromOrderHandler.php
  src/Adapter/Order/CommandHandler/DuplicateOrderCartHandler.php
  src/Adapter/Order/OrderAmountUpdater.php
  src/Adapter/Order/OrderProductQuantityUpdater.php
  src/Adapter/Product/QueryHandler/SearchProductsHandler.php
  tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_currency.feature
  tests/Unit/Adapter/ContextStateManagerTest.php
Labels: 1.7.7.x, Bug, QA ✔️

#21609 Make PrestaShop compatible with composer 2.0
  classes/AddressFormat.php
  classes/Attribute.php
  classes/AttributeGroup.php
  classes/Cart.php
  classes/Combination.php
  classes/ConfigurationTest.php
  classes/Connection.php
  classes/Context.php
  classes/Customer.php
  classes/CustomerMessage.php
  classes/CustomizationField.php
  classes/DateRange.php
  classes/Employee.php
  classes/Feature.php
  classes/Product.php
  classes/Search.php
  classes/controller/AdminController.php
  classes/controller/FrontController.php
  classes/helper/HelperForm.php
  classes/helper/HelperList.php
  classes/order/OrderDetail.php
  composer.lock
  src/Adapter/Contact/CommandHandler/EditContactHandler.php
  src/Adapter/Order/Refund/OrderSlipCreator.php
  src/Adapter/Presenter/Module/ModulePresenter.php
  src/Core/Domain/Address/QueryResult/EditableManufacturerAddress.php
  src/Core/Hook/Generator/HookDescriptionGenerator.php
  src/Core/Shop/LogoUploader.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php
  tests/Integration/Behaviour/Features/Context/Util/CategoryTreeIterator.php
Labels: 1.7.7.x, Bug, Improvement

#21607 Update translation catalogs
  app/Resources/translations/default/AdminNotificationsError.xlf
  app/Resources/translations/default/AdminOrderscustomersFeature.xlf
  app/Resources/translations/default/AdminOrderscustomersNotification.xlf
  app/Resources/translations/default/ModulesBlockreassuranceAdmin.xlf
  app/Resources/translations/default/ModulesCheckpaymentAdmin.xlf
  app/Resources/translations/default/ModulesCheckpaymentShop.xlf
  app/Resources/translations/default/ModulesDashtrendsAdmin.xlf
  app/Resources/translations/default/ModulesWelcomeAdmin.xlf
Labels: 1.7.7.x, Improvement

#21622 Merge 177x into develop 26/10/2020
  classes/Cart.php
  composer.lock
  src/Adapter/Cart/CommandHandler/AddCartRuleToCartHandler.php
  src/Adapter/Cart/CommandHandler/UpdateCartCarrierHandler.php
  src/Adapter/Cart/CommandHandler/UpdateProductQuantityInCartHandler.php
  src/Adapter/Cart/QueryHandler/GetCartInformationHandler.php
  src/Adapter/ContextStateManager.php
  src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php
  src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php
  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
  src/Adapter/Order/CommandHandler/DeleteCartRuleFromOrderHandler.php
  src/Adapter/Order/CommandHandler/DeleteProductFromOrderHandler.php
  src/Adapter/Order/CommandHandler/DuplicateOrderCartHandler.php
  src/Adapter/Order/OrderAmountUpdater.php
  src/Adapter/Order/OrderProductQuantityUpdater.php
  src/Adapter/Product/QueryHandler/SearchProductsHandler.php
  src/Core/Shop/LogoUploader.php
  tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_currency.feature
  tests/UI/campaigns/data/faker/title.js
  tests/Unit/Adapter/ContextStateManagerTest.php
Labels: Improvement, develop

#21631 Using setValue on login to test multiple login attempts
  tests/UI/pages/BO/login/index.js
Labels: QA ✔️, Refactoring, TE, develop

#21534 Add test 'Bulk delete search engine'
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/02_searchEngines/03_bulkActions.js
  tests/UI/pages/BO/shopParameters/trafficAndSeo/searchEngines/index.js
Labels: QA ✔️, Refactoring, TE, develop

#21573 Add test 'Quick edit and bulk actions carriers'
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/02_filterSortAndPagination.js
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/03_QuickEditAndBulkActions.js
  tests/UI/pages/BO/shipping/carriers/index.js
Labels: QA ✔️, Refactoring, TE, develop

#21637 Add test 'Sort and pagination employees'
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/employees/05_sortAndPagination.js
  tests/UI/pages/BO/advancedParameters/team/index.js
Labels: Refactoring, TE, develop

#21641 Fix nightly (18-10-2020) comment not working tests
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/02_filterSortAndPagination.js
Labels: Refactoring, TE, develop

#21665 Fix PHPDoc AdminController::$explicitSelect
  classes/controller/AdminController.php
Labels: Documentation, Improvement, develop

#21654 Select first payment method if only one is available
  themes/classic/templates/checkout/_partials/steps/payment.tpl
Labels: Improvement, QA ✔️, develop

#21656 Detect click but not drag and drop on grid
  admin-dev/themes/new-theme/js/components/grid/extension/link-row-action-extension.js
Labels: Improvement, QA ✔️, develop

#21554 Fix layout breaking on order when discount name is way too long
  admin-dev/themes/new-theme/scss/pages/orders/_orders_view.scss
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/discount_list.html.twig
Labels: Bug, QA ✔️, develop
