Repository PrestaShop/PrestaShop, pull requests merged in 2020-07, with the labels that each got.

#20018 Remove COLLATION placeholder from 1.7.6.6.sql
  install-dev/upgrade/sql/1.7.6.6.sql
Labels: 1.7.6.x, Bug, High, QA ✔️

#20032 Add changelog for v1.7.6.6
  docs/CHANGELOG.txt
Labels: 1.7.6.x, Improvement

#17399 Expand Categories search capabilities for categories listing home page and avoid going from subcategory to root category when using grid filters
  src/Core/Grid/Factory/CategoryGridFactoryDecorator.php
  src/Core/Grid/Filter/CategoryFilterFormFactory.php
  src/Core/Grid/Filter/FilterCollection.php
  src/Core/Grid/Query/CategoryQueryBuilder.php
  src/Core/Search/Filters.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_factory.yml
Labels: 1.7.7.x, Bug, QA ✔️

#20046 Functional tests - Do not skip steps in CRUD category and subcategory scenario
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/02_CRUDCategoryInBO.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#20052 Fix product page event theme sided not getting fired
  themes/_core/js/product.js
  themes/core.js
  themes/core.js.map
Labels: 1.7.6.x, Bug, High, QA ✔️

#20017 Improve dynamic hooks comment
  classes/ObjectModel.php
Labels: Improvement, develop

#20066 Release 1.7.6.7
  app/AppKernel.php
  docs/CHANGELOG.txt
  install-dev/install_version.php
Labels: 1.7.6.x, Improvement

#19981 Refactor cancel product and bug fix
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/public/order_view.bundle.js
  src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php
  src/Adapter/Order/OrderProductQuantityUpdater.php
  src/Adapter/Order/Refund/OrderProductRemover.php
  src/PrestaShopBundle/Resources/config/services/adapter/order.yml
  tests/Integration/Behaviour/Features/Scenario/Order/order_cancel_product.feature
Labels: 1.7.7.x, QA ✔️, Refactoring, Wording ✔️

#20074 Ignore swo temporary files in gitignore
  .gitignore
Labels: Improvement, QA ✔️, develop

#20028 BO - Customers / Wrong redirection after creating a new address from the customer detail page
  src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php
Labels: Bug, QA ✔️, develop

#20070 Fix incorrect redirect URL parameter when editing translations
  controllers/admin/AdminTranslationsController.php
Labels: Bug, QA ✔️, develop

#19961 Install classic theme when possible
  install-dev/init.php
Labels: Improvement, QA ✔️, develop

#19951 Truncate category description in BO list view
  src/Core/Grid/Data/Factory/CategoryDataFactory.php
Labels: Improvement, QA ✔️, UX ✔️, develop

#19948 Check maximum PHP Version Support at installation
  install-dev/index.php
  install-dev/index_cli.php
  install-dev/install_version.php
  install-dev/missing_requirement.php
  tools/build/Library/InstallUnpacker/index_template.php
Labels: Improvement, QA ✔️, develop

#19937 Fixed position action button in Order Page
  admin-dev/themes/new-theme/scss/pages/_orders_view.scss
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
Labels: 1.7.7.x, Bug, QA ✔️

#20089 Merge 1.7.6.x into 1.7.7.x - 07/07/2020
  admin-dev/themes/default/js/bundle/product/form.js
  admin-dev/themes/default/template/helpers/list/list_action_delete.tpl
  admin-dev/themes/new-theme/js/components/module-card.js
  admin-dev/themes/new-theme/public/currency_form.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/module.bundle.js
  admin-dev/themes/new-theme/public/module_card.bundle.js
  app/AppKernel.php
  classes/Context.php
  classes/Cookie.php
  classes/Currency.php
  classes/Customer.php
  classes/CustomerSession.php
  classes/Employee.php
  classes/EmployeeSession.php
  classes/Tools.php
  classes/controller/AdminController.php
  classes/form/CustomerPersister.php
  classes/module/Module.php
  composer.lock
  controllers/admin/AdminCarriersController.php
  controllers/admin/AdminDashboardController.php
  controllers/admin/AdminLoginController.php
  docs/CHANGELOG.txt
  install-dev/data/db_structure.sql
  install-dev/upgrade/sql/1.7.6.6.sql
  install-dev/upgrade/upgrade.php
  src/Adapter/Module/Module.php
  src/Core/Session/SessionInterface.php
  src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
  src/PrestaShopBundle/Controller/Api/Improve/Design/PositionsController.php
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/modal_confirm_bulk_action.html.twig
  themes/_core/js/product.js
  themes/classic/templates/catalog/product.tpl
  themes/core.js
  themes/core.js.map
  tools/build/Library/ReleaseCreator.php
Labels: Improvement, develop

#19947 Fixed preview in Order Page
  admin-dev/themes/new-theme/js/components/grid/extension/preview-extension.js
Labels: Bug, QA ✔️, develop

#20006 Allow the + sign in the url path
  classes/Cookie.php
  src/Adapter/Assets/AssetUrlGeneratorTrait.php
Labels: Bug, QA ✔️, develop

#20086 Functional tests - Test pagination of products table
  tests/UI/campaigns/functional/BO/03_catalog/01_products/02_paginationAndSortProducts.js
  tests/UI/campaigns/functional/BO/03_catalog/01_products/02_sortProducts.js
  tests/UI/pages/BO/catalog/products/add.js
  tests/UI/pages/BO/catalog/products/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#19871 UpdateProductCategoriesCommand
  classes/Category.php
  src/Adapter/Product/AbstractProductHandler.php
  src/Adapter/Product/CommandHandler/AddProductHandler.php
  src/Adapter/Product/CommandHandler/UpdateProductBasicInformationHandler.php
  src/Adapter/Product/CommandHandler/UpdateProductCategoriesHandler.php
  src/Adapter/Product/CommandHandler/UpdateProductOptionsHandler.php
  src/Adapter/Product/CommandHandler/UpdateProductPackHandler.php
  src/Adapter/Product/CommandHandler/UpdateProductPricesHandler.php
  src/Adapter/Product/CommandHandler/UpdateProductStatusCommandHandler.php
  src/Adapter/Product/CommandHandler/UpdateProductTagsHandler.php
  src/Adapter/Product/QueryHandler/GetProductIsEnabledHandler.php
  src/Core/Domain/Product/Command/UpdateProductCategoriesCommand.php
  src/Core/Domain/Product/CommandHandler/UpdateProductCategoriesHandlerInterface.php
  src/Core/Domain/Product/Exception/CannotUpdateProductException.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CategoryFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/add_product.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_categories.feature
  tests/Integration/Behaviour/behat.yml
Labels: Refactoring, WIP, develop, migration

#19239 Always display "Related product" title
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_related_products.html.twig
Labels: Bug, PM ✔️, QA ✔️, UX ✔️, develop

#19970 Create specific price when product price is updated in order
  classes/CartRule.php
  src/Adapter/Order/AbstractOrderHandler.php
  src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php
  src/Adapter/Order/CommandHandler/AddPaymentHandler.php
  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
  src/Adapter/Order/CommandHandler/ChangeOrderCurrencyHandler.php
  src/Adapter/Order/CommandHandler/ChangeOrderDeliveryAddressHandler.php
  src/Adapter/Order/CommandHandler/ChangeOrderInvoiceAddressHandler.php
  src/Adapter/Order/CommandHandler/DeleteCartRuleFromOrderHandler.php
  src/Adapter/Order/CommandHandler/GenerateInvoiceHandler.php
  src/Adapter/Order/CommandHandler/IssuePartialRefundHandler.php
  src/Adapter/Order/CommandHandler/IssueReturnProductHandler.php
  src/Adapter/Order/CommandHandler/IssueStandardRefundHandler.php
  src/Adapter/Order/CommandHandler/ResendOrderEmailHandler.php
  src/Adapter/Order/CommandHandler/UpdateOrderShippingDetailsHandler.php
  src/Adapter/Order/CommandHandler/UpdateOrderStatusHandler.php
  src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Order/QueryHandler/GetOrderProductsForViewingHandler.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_cart_rules.feature
Labels: 1.7.7.x, Bug, QA ✔️

#20122 Fix session tables charset
  install-dev/data/db_structure.sql
  install-dev/upgrade/sql/1.7.7.0.sql
Labels: 1.7.7.x, Bug

#20092 Fix some phpdoc
  src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php
  src/PrestaShopBundle/Controller/Api/ApiController.php
Labels: Improvement, develop

#19704 Migrate linked orders
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Core/Domain/Order/QueryResult/LinkedOrderForViewing.php
  src/Core/Domain/Order/QueryResult/LinkedOrdersForViewing.php
  src/Core/Domain/Order/QueryResult/OrderDiscountsForViewing.php
  src/Core/Domain/Order/QueryResult/OrderForViewing.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/linked_orders.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/payments.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig
Labels: 1.7.7.x, Feature, Wording ✔️, migration, waiting for QA

#20039 Make customization image downloadable in BO order page
  src/Adapter/LegacyContext.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig
Labels: 1.7.7.x, Improvement, PM ✔️, QA ✔️, Wording ✔️

#16439 Frontend Translation mixed up when switching languages
  classes/Context.php
Labels: Bug, QA ✔️, develop

#20123 Fix license headers
  classes/CustomerSession.php
  classes/EmployeeSession.php
  src/Adapter/Order/OrderProductQuantityUpdater.php
  src/Core/Domain/Order/QueryResult/OrderSourceForViewing.php
  src/Core/Domain/Order/QueryResult/OrderSourcesForViewing.php
  src/Core/Session/SessionInterface.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/sources.html.twig
Labels: 1.7.7.x, Improvement, QA ✔️

#20096 Show last visible order state in customer order history page
  src/Adapter/Presenter/Order/OrderLazyArray.php
Labels: Improvement, QA ✔️, develop

#19455 Add hook displayAfterTitleTag
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.7.0.sql
  themes/classic/templates/_partials/head.tpl
Labels: Hook, Improvement, QA ✔️

#20136 Mention good first issues in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Improvement, develop

#19866 Simplify Taxes and Tax options forms
  src/Core/ConstraintValidator/TypedRegexValidator.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/TaxController.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Tax/TaxOptionsType.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Tax/TaxType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Tax/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Tax/Blocks/tax_options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: BC break, QA ✔️, Refactoring, Wording ✔️, develop, migration, waiting for wording

#20142 Fix a few things in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Improvement, QA ✔️, develop

#20141 Property display_footer is a boolean
  classes/controller/Controller.php
Labels: Bug, QA ✔️, develop

#20148 [BO] Color picker doesn't recognize html color name on page load
  js/jquery/plugins/jquery.colorpicker.js
Labels: Bug, QA ✔️, develop

#20126 Correctly uncheck previous default combination
  admin-dev/themes/default/js/bundle/product/product-combinations.js
Labels: 1.7.7.x, Bug, QA ✔️

#20157 Functional tests - Fix the ID of display footer hook
  tests/UI/campaigns/data/demo/hooks.js
Labels: QA ✔️, Refactoring, TE, develop

#20132 Enable hook 'displayAfterProductThumbs' to access product - thanks @elburgl69
  themes/classic/templates/catalog/_partials/product-cover-thumbnails.tpl
Labels: Improvement, QA ✔️, develop

#20149 [BO Addresses page] - Error after saving new address
  src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php
Labels: QA ✔️, Type: Critical Bug Fix, bugfix, develop

#20167 Add PHPStan badge to README
  README.md
Labels: Improvement, develop

#18690 Remove unwanted replace and raw calls in twig and fix js error
  admin-dev/themes/new-theme/js/pages/currency/form/currency-form.js
  admin-dev/themes/new-theme/js/vue/plugins/vue-i18n/replace-formatter.js
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Currency/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
Labels: Improvement, QA ✔️, develop

#20166 Return Response to provide a good error message when import directory doesnt exist
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ImportController.php
Labels: 1.7.7.x, Bug, QA ✔️

#20114 Allow employee to choose their own avatar
  .gitignore
  classes/Employee.php
  config/defines_uri.inc.php
  img/e/index.php
  src/Adapter/Image/Uploader/EmployeeImageUploader.php
  src/Adapter/Profile/Employee/QueryHandler/GetEmployeeForEditingHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/EmployeeFormDataHandler.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Employee/EmployeeType.php
  src/PrestaShopBundle/Resources/config/services/adapter/employee.yml
  src/PrestaShopBundle/Resources/config/services/adapter/image.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Employee/Blocks/form.html.twig
Labels: Feature, QA ✔️, Wording ✔️, develop

#19968 Fixed specific price list in the product editor
  classes/SpecificPrice.php
  classes/SpecificPriceRule.php
  src/Adapter/Product/AdminProductWrapper.php
Labels: Bug, QA ✔️, develop

#20182 Revert change from #18220, it breaks modules
  classes/pdf/PDF.php
Labels: Bug, develop

#20124 Use /usr/sbin/sendmail instead of mail() in config wording
  src/Core/Form/ChoiceProvider/MailMethodChoiceProvider.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/system_information.html.twig
Labels: 1.7.7.x, Improvement, QA ✔️, Wording ✔️

#19873 Code issues : Avoid code duplicate in EmployeeGridDefinitionFactory
  src/Core/Grid/Definition/Factory/EmployeeGridDefinitionFactory.php
Labels: QA ✔️, Refactoring, develop

#19560 Implement Native Lazy Loading on theme classic
  themes/classic/modules/blockreassurance/views/templates/hook/blockreassurance.tpl
  themes/classic/modules/ps_advertising/ps_advertising.tpl
  themes/classic/modules/ps_banner/ps_banner.tpl
  themes/classic/modules/ps_imageslider/views/templates/hook/slider.tpl
  themes/classic/modules/ps_shoppingcart/modal.tpl
  themes/classic/modules/ps_shoppingcart/ps_shoppingcart-product-line.tpl
  themes/classic/templates/_partials/header.tpl
  themes/classic/templates/catalog/_partials/category-header.tpl
  themes/classic/templates/catalog/_partials/miniatures/brand.tpl
  themes/classic/templates/catalog/_partials/miniatures/category.tpl
  themes/classic/templates/catalog/_partials/miniatures/pack-product.tpl
  themes/classic/templates/catalog/_partials/miniatures/product.tpl
  themes/classic/templates/catalog/_partials/product-cover-thumbnails.tpl
  themes/classic/templates/catalog/_partials/product-customization.tpl
  themes/classic/templates/catalog/_partials/product-details.tpl
  themes/classic/templates/catalog/_partials/subcategories.tpl
  themes/classic/templates/checkout/_partials/cart-detailed-product-line.tpl
  themes/classic/templates/checkout/_partials/cart-summary-product-line.tpl
  themes/classic/templates/checkout/_partials/header.tpl
  themes/classic/templates/checkout/_partials/order-confirmation-table.tpl
  themes/classic/templates/checkout/_partials/order-final-summary.tpl
  themes/classic/templates/checkout/_partials/steps/payment.tpl
  themes/classic/templates/checkout/_partials/steps/shipping.tpl
  themes/classic/templates/customer/_partials/order-detail-no-return.tpl
  themes/classic/templates/customer/_partials/order-detail-return.tpl
  themes/classic/templates/customer/order-return.tpl
  themes/classic/templates/errors/maintenance.tpl
  themes/classic/templates/errors/restricted-country.tpl
Labels: Improvement, Key feature, QA ✔️, develop

#20192 Remove tables upgrade lines related to gamification module
  install-dev/upgrade/sql/1.7.7.0.sql
Labels: 1.7.7.x, Bug, QA ✔️

#20153 Product duplication in table ps_product_supplier
  classes/Product.php
Labels: Bug, QA ✔️, develop

#20078 BO > CUSTOMERS > GENERAL SETTINGS : Wrong helper description
  app/Resources/translations/default/AdminShopparametersHelp.xlf
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/customer_preferences_general.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop

#20213 Update Prestashop module versions
  composer.lock
Labels: Improvement, develop

#20210 Functional tests - Add 'Sort orders' tests
  tests/UI/campaigns/functional/BO/02_orders/01_orders/07_sortOrders.js
  tests/UI/pages/BO/orders/index.js
Labels: 1.7.7.x, Refactoring, TE

#20215 Functional tests - Add checking order status in FO after update status in BO
  tests/UI/campaigns/functional/BO/02_orders/01_orders/04_checkInvoiceDownloadedFromList.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/05_checkDeliverySlipDownloadedFromList.js
  tests/UI/pages/FO/myAccount/orderHistory.js
Labels: 1.7.7.x, Refactoring, TE

#20212 Fix some license headers
  src/Core/Domain/Order/QueryResult/LinkedOrderForViewing.php
  src/Core/Domain/Order/QueryResult/LinkedOrdersForViewing.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/linked_orders.html.twig
Labels: 1.7.7.x, Improvement

#19838 Add modal actions to attribute and attribute actions
  src/Core/Grid/Definition/Factory/AttributeGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/AttributeGroupGridDefinitionFactory.php
  src/Core/Search/Filters/AttributeFilters.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/attribute.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/attribute_group.yml
Labels: QA ✔️, Refactoring, Wording ✔️, develop, migration

#20139 Module widget display fix
  classes/Hook.php
  classes/module/Module.php
Labels: Bug, QA ✔️, develop

#20237 Fixed PHPStan CI
  phpstan.neon.dist
Labels: Bug, QA ✔️, develop

#20241 Functional tests - Modify translation
  tests/UI/campaigns/functional/BO/11_international/04_translations/01_modifyTranslation.js
  tests/UI/pages/BO/international/translations/index.js
  tests/UI/pages/FO/home/index.js
Labels: 1.7.7.x, Refactoring, TE

#20083 Refacto order updater
  classes/CartRule.php
  src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php
  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
  src/Adapter/Order/CommandHandler/DeleteCartRuleFromOrderHandler.php
  src/Adapter/Order/OrderAmountUpdater.php
  src/Adapter/Order/OrderProductQuantityUpdater.php
  src/Core/Domain/CartRule/Exception/InvalidCartRuleDiscountValueException.php
  src/Core/Domain/Order/Command/AddCartRuleToOrderCommand.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/config/services/adapter/order.yml
  tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/add_cart_rule_to_order.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_cancel_product.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_cart_rules.feature
Labels: 1.7.7.x, Bug, Wording ✔️, waiting for author, waiting for dev

#20204 Simplified credit slip options
  src/PrestaShopBundle/Controller/Admin/Sell/Order/CreditSlipController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/CreditSlip/CreditSlipOptionsType.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/CreditSlip/GeneratePdfByDateType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/CreditSlip/Blocks/credit_slip_options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/CreditSlip/Blocks/pdf_by_date.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: BC break, QA ✔️, Refactoring, develop, migration, waiting for wording

#20242 Add deprecated message on js files in order to inform about next major possible deletions
  js/admin-categories-tree.js
  js/admin/attachments.js
  js/admin/email.js
  js/date.js
  js/fileuploader.js
  js/validate.js
Labels: Improvement, develop

#20253 Grid row delete confirmation modal - Customers > Addresses
  src/Core/Grid/Definition/Factory/AddressGridDefinitionFactory.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer/addresses.yml
Labels: Improvement, QA ✔️, develop, migration

#20262 Functional tests - Fix click on delete confirmation modal - Customers > Addresses
  tests/UI/pages/BO/customers/addresses/index.js
Labels: QA ✔️, Refactoring, TE, develop

#20258 Add const MAIL_DIR for phpstan bootstrap
  .github/workflows/phpstan/autoload.php
Labels: Improvement, develop

#20235 Remove useless ini_set for Windows
  classes/Windows.php
  config/config.inc.php
Labels: Bug, develop

#20260 Fix color of cursor using arrow keyboard on product page
  admin-dev/themes/new-theme/scss/pages/_product_page.scss
Labels: Bug, QA ✔️, develop

#20273 Functional tests - Fix confirm delete modal selector for addresses page
  tests/UI/pages/BO/customers/addresses/index.js
Labels: QA ✔️, Refactoring, TE, develop

#20111 Fix order max quantity
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-edit.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  install-dev/fixtures/fashion/data/order_detail.xml
  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
  src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php
  src/Adapter/Order/OrderProductQuantityUpdater.php
  src/Adapter/Order/QueryHandler/GetOrderProductsForViewingHandler.php
  src/Adapter/Product/QueryHandler/SearchProductsHandler.php
  src/Core/Domain/Order/Product/Command/AddProductToOrderCommand.php
  src/Core/Domain/Product/QueryResult/ProductCombination.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_out_of_stock.feature
Labels: 1.7.7.x, Bug, QA ✔️

#20002 Add selectors mapping so themes can override it
  themes/_core/js/cart.js
  themes/_core/js/checkout-address.js
  themes/_core/js/checkout-delivery.js
  themes/_core/js/checkout-payment.js
  themes/_core/js/checkout-steps.js
  themes/_core/js/checkout.js
  themes/_core/js/listing.js
  themes/_core/js/product.js
  themes/_core/js/selectors.js
  themes/_core/js/theme.js
  themes/classic/_dev/js/cart.js
  themes/classic/_dev/js/checkout.js
  themes/classic/_dev/js/customer.js
  themes/classic/_dev/js/listing.js
  themes/classic/_dev/js/product.js
  themes/classic/_dev/js/selectors.js
  themes/classic/_dev/js/theme.js
  themes/classic/_dev/package-lock.json
Labels: Improvement, QA ✔️, develop

#20263 Fix bad redirection after error in address controller
  src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php
Labels: 1.7.7.x, Bug, QA ✔️

#20016 Simplify Address form
  src/Core/ConstraintValidator/TypedRegexValidator.php
  src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Address/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit.html.twig
Labels: BC break, Refactoring, Wording ✔️, develop, migration, waiting for QA, waiting for UX

#20280 Functional tests - Create new test 'View customer from orders page'
  tests/UI/campaigns/functional/BO/02_orders/01_orders/08_viewCustomer.js
  tests/UI/pages/BO/orders/index.js
Labels: 1.7.7.x, Refactoring, TE

#20291 Add the Bug Bounty Program in SECURITY.md
  .github/SECURITY.md
Labels: Improvement, develop

#20293 Functional tests - Add new test 'Carrier restrictions'
  tests/UI/campaigns/functional/BO/10_payment/02_preferences/04_carrierRestrictions.js
  tests/UI/pages/BO/payment/preferences/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#19830 Allow override of checkout process
  classes/checkout/CheckoutProcess.php
  controllers/front/OrderController.php
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.8.0.sql
Labels: Bug, QA ✔️, develop

#20143 Add actionGetProductPropertiesAfterUnitPrice hook
  classes/Hook.php
  classes/Product.php
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.8.0.sql
Labels: Developer Feature, Feature, Hook, QA ✔️, develop

#20195 Log when webservice key is deleted
  classes/webservice/WebserviceKey.php
Labels: Improvement, QA ✔️, Wording ✔️, develop

#20297 Simplify is_gift checking in checkout tpl
  themes/classic/templates/checkout/_partials/cart-detailed-product-line.tpl
Labels: Improvement, develop

#20224 [BO][PRODUCT][SPECIFIC PRICE TAB] Add id_specific_price in list
  admin-dev/themes/new-theme/js/pages/catalog/product/specific-price-form-handler.js
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Panels/pricing.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop

#20289 Fix wrongly placed block end tag in carts/helpers/view/view.tpl
  admin-dev/themes/default/template/controllers/carts/helpers/view/view.tpl
Labels: Bug, QA ✔️, develop

#20312 Improve combination tests, use IDs instead of names to check quantities
  src/Adapter/Order/QueryHandler/GetOrderProductsForViewingHandler.php
  src/Core/Domain/Order/QueryResult/OrderProductForViewing.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_cart_rules.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_out_of_stock.feature
Labels: 1.7.7.x, Improvement, TE

#20356 Fix phpstan ignore lines
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/OrderStateController.php
Labels: Bug, develop

#20318 Functional tests - Add new test 'View guest from orders page'
  tests/UI/campaigns/data/faker/customer.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/08_viewCustomer.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/09_viewGuest.js
  tests/UI/campaigns/sanity/06_checkoutFO/01_orderProduct.js
  tests/UI/pages/FO/checkout/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#15049 Fix wrong hook names
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.7.0.sql
Labels: 1.7.7.x, Bug, Documentation, QA ✔️

#20324 Set editorconfig to indent yml files using 4 spaces instead of two
  .editorconfig
Labels: 1.7.7.x, Improvement

#20358 Improve UI tests readme
  tests/UI/README.md
Labels: Improvement, develop

#20360 Functional tests - Reset orders before going to order view page
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/01_generateInvoiceByDate.js
  tests/UI/campaigns/sanity/06_checkoutFO/01_orderProduct.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#20362 Functional tests - Fix nightly fails after merging 1.7.7.x into develop
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/01_generateInvoiceByDate.js
  tests/UI/campaigns/functional/BO/11_international/01_localization/currencies/01_CreateOfficialCurrency.js
  tests/UI/pages/BO/advancedParameters/database/sqlManager/index.js
Labels: QA ✔️, Refactoring, TE, develop

#20303 Fix bad redirection after error in address controller - edit usecase
  src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php
Labels: 1.7.7.x, Bug, QA ✔️

#20364 Fix typo
  controllers/admin/AdminProductsController.php
Labels: Improvement, develop

#20328 Fixed the title 'List of products without description'
  src/Core/Grid/Definition/Factory/Monitoring/ProductWithoutDescriptionGridDefinitionFactory.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#20361 Add Apple Touch Icon
  .gitignore
  img/app_icon.png
Labels: Bug, QA ✔️, develop

#20368 Functional tests - Add browser listeners to tests
  tests/UI/campaigns/utils/globals.js
  tests/UI/campaigns/utils/helpers.js
  tests/UI/campaigns/utils/setup.js
Labels: 1.7.7.x, Refactoring, TE

#20107 Add UpdateProductShipping command
  classes/Product.php
  src/Adapter/Product/CommandHandler/UpdateProductShippingHandler.php
  src/Adapter/Product/QueryHandler/GetProductForEditingHandler.php
  src/Core/Domain/Product/Command/UpdateProductShippingCommand.php
  src/Core/Domain/Product/CommandHandler/UpdateProductShippingHandlerInterface.php
  src/Core/Domain/Product/Exception/CannotUpdateProductException.php
  src/Core/Domain/Product/Exception/ProductConstraintException.php
  src/Core/Domain/Product/QueryResult/ProductForEditing.php
  src/Core/Domain/Product/QueryResult/ProductShippingInformation.php
  src/Core/Domain/Product/ValueObject/DeliveryTimeNotesType.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  tests/Integration/Behaviour/Features/Context/Domain/CarrierFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Util/PrimitiveUtils.php
  tests/Integration/Behaviour/Features/Scenario/CLDR/cldr.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_shipping.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_tags.feature
  tests/Integration/Behaviour/behat.yml
Labels: Refactoring, develop, migration

#19856 Check Select Privilege in the Install Process
  classes/db/Db.php
  classes/db/DbMySQLi.php
  classes/db/DbPDO.php
  src/PrestaShopBundle/Install/Database.php
Labels: Improvement, QA ✔️, Wording ✔️, develop

#20363 Fixed duplication of Currencies after install/remove
  classes/LocalizationPack.php
Labels: Bug, QA ✔️, develop

#20137 Computing precision: set minimum computing precision value to zero
  classes/PaymentModule.php
  src/Core/Localization/CLDR/ComputingPrecision.php
  tests/Unit/Core/Localization/CLDR/ComputingPrecisionTest.php
Labels: 1.7.7.x, Improvement, QA ✔️

#20319 Cannot remove attributes if token is disabled
  admin-dev/themes/default/js/bundle/product/product-combinations.js
Labels: 1.7.7.x, Bug, QA ✔️

#20198 Product supplier_reference is not updated when saving a product in the BO
  classes/Product.php
  controllers/admin/AdminProductsController.php
  src/Adapter/Product/AdminProductWrapper.php
Labels: 1.7.7.x, Bug, QA ✔️

#19965 Add High DPI support to ImageRetriever
  src/Adapter/Image/ImageRetriever.php
Labels: Bug, QA ✔️, develop

#20398 Fixed Cache Problem in Language & Currency
  classes/Currency.php
  classes/Language.php
  tests-legacy/Integration/classes/CurrencyTest.php
  tests-legacy/Integration/classes/LanguageTest.php
Labels: 1.7.7.x, Bug

#20386 Add tests for Tools rounding functions
  classes/Tools.php
  tests-legacy/Unit/Classes/ToolsCoreTest.php
Labels: Improvement, develop

#20282 Reduce conditions complexity
  themes/classic/templates/checkout/_partials/steps/addresses.tpl
Labels: Improvement, develop

#20329 Format add webservice key log like deletion log
  classes/webservice/WebserviceKey.php
Labels: Improvement, QA ✔️, develop

#20311 Mark deprecated order hooks for 1.7.7 as such
  classes/Hook.php
  install-dev/data/xml/hook_alias.xml
Labels: 1.7.7.x, Improvement, QA ✔️

#20207 Added hook & gravatar management for avatar employee
  classes/Employee.php
  install-dev/data/db_structure.sql
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.8.0.sql
  src/Adapter/Profile/Employee/CommandHandler/AddEmployeeHandler.php
  src/Adapter/Profile/Employee/CommandHandler/EditEmployeeHandler.php
  src/Adapter/Profile/Employee/QueryHandler/GetEmployeeForEditingHandler.php
  src/Core/Domain/Employee/Command/AddEmployeeCommand.php
  src/Core/Domain/Employee/Command/EditEmployeeCommand.php
  src/Core/Domain/Employee/QueryResult/EditableEmployee.php
  src/Core/Form/IdentifiableObject/DataHandler/EmployeeFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/EmployeeFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Employee/EmployeeType.php
  src/PrestaShopBundle/Resources/config/services/adapter/image.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Employee/Blocks/form.html.twig
Labels: Feature, Hook, Key feature, QA ✔️, Wording ✔️, develop
