Repository PrestaShop/PrestaShop, pull requests merged in 2021-07, with the labels that each got.

#24985 In dev mode, hooks must not swallow exceptions.
  classes/Hook.php
  src/Adapter/Environment.php
  src/Adapter/HookManager.php
Labels: Improvement, QA ✔️, develop

#25152 Fix selectors map not being set in experimental product combinations page
  admin-dev/themes/new-theme/js/components/pagination/dynamic-paginator.ts
Labels: Bug fix, QA ✔️, develop, migration

#25153 Make color picker global in back office
  admin-dev/themes/new-theme/js/app/utils/init-components.js
Labels: Documentation, Improvement, QA ✔️, develop

#25187 Replace getmanufacturerLink with getManufacturerLink
  controllers/front/listing/ManufacturerController.php
Labels: Refactoring, develop

#25196 Removed phpunit-controllers tests
  .github/workflows/php.yml
  composer.json
  tests-legacy/bootstrap-controllers.php
  tests-legacy/old-controllers.xml
Labels: Refactoring, develop

#25146 Separate functional tests to BO and FO and Add regression campaign to the actual run
  tests/UI/scripts/run-nightly-tests.sh
Labels: E2E Tests, Refactoring, TE, develop

#24932 Fix unexpected condition in country-state-selection-toggler
  admin-dev/themes/new-theme/js/components/country-state-selection-toggler.ts
Labels: Improvement, QA ✔️, develop

#25266 Fix develop tests
  tests/Integration/Behaviour/Features/Scenario/Product/duplicate_product.feature
  tests/Integration/Core/Localization/Locale/RepositoryTest.php
Labels: Bug fix, develop

#25281 Rise Apache Travis timeout
  tests/travis-ci-apache-vhost
Labels: 1.7.7.x, Bug fix

#24868 Fixed cart rule on selected product with product with ecotax
  classes/CartRule.php
  tests/Integration/Behaviour/Features/Context/CarrierFeatureContext.php
  tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Context/TaxFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/ecotax.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/Taxes/tax.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/CartToOrder/cart_to_order.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/Delivery/delivery_options.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_cartrule.feature
  tests/Integration/Behaviour/behat.yml
Labels: 1.7.7.x, Bug fix, QA ✔️

#25059 Fixed translated order messages in Order View
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/OrderMessage/OrderMessageProvider.php
  src/Core/Domain/Order/QueryResult/OrderCustomerForViewing.php
  src/Core/Form/ChoiceProvider/CustomerServiceOrderMessagesChoiceProvider.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/OrderMessageType.php
  src/PrestaShopBundle/Resources/config/services/core/form/choice_provider.yml
  tests/Unit/Core/Domain/Order/QueryResult/OrderCustomerForViewingTest.php
Labels: 1.7.7.x, BC break, Bug fix, QA ✔️

#25106 Fixed management of INNER JOIN & GROUP BY in SqlQueryValidator
  classes/RequestSql.php
  tests/Integration/Adapter/SqlManager/SqlQueryValidatorTest.php
Labels: 1.7.7.x, Bug fix, QA ✔️

#24324 Orders View : Display right price depending configuration
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-edit.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js
  admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig
  tests/Integration/Behaviour/Features/Scenario/Order/add_cart_rule_to_order.feature
Labels: 1.7.7.x, Bug fix, QA ✔️

#25200 In Invoice PDF, escape customization name
  pdf/invoice.product-tab.tpl
Labels: 1.7.7.x, Bug fix, QA ✔️

#25107 Fixed meta title in BO - Order View
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
Labels: 1.7.7.x, Bug fix, QA ✔️, Wording ✔️, migration

#25216 Fix brands links not clickable inside description
  themes/classic/_dev/css/components/brands.scss
  themes/classic/assets/css/theme.css
  themes/classic/assets/js/theme.js
Labels: 1.7.7.x, Bug fix, QA ✔️

#25287 Removed code related to Gamification module
  admin-dev/themes/default/scss/partials/_header.scss
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
  classes/Language.php
Labels: Improvement, develop

#25292 Fix 1.7.8.x test for product duplicate
  tests/Integration/Behaviour/Features/Scenario/Product/duplicate_product.feature
Labels: 1.7.8.x, Bug fix

#25267 Replace getsupplierlink with getSupplierLink
  controllers/front/listing/SupplierController.php
Labels: Refactoring, develop

#25067 Added clickable phone number on navbar and footer
  themes/classic/modules/ps_contactinfo/nav.tpl
  themes/classic/modules/ps_contactinfo/ps_contactinfo.tpl
Labels: Improvement, QA ✔️, Wording ✔️, develop

#25285 Add search for newsletter module before going to module configuration on tests
  tests/UI/campaigns/functional/FO/04_newsletter/01_subscribeNewsletter.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#24997 Cancel previous build when it's possible
  .github/workflows/integration.yml
  .github/workflows/php.yml
  .github/workflows/pr.yml
  .github/workflows/sanity-72.yml
  .github/workflows/sanity-73.yml
  .github/workflows/sanity-74.yml
  .github/workflows/ui-tests-code-checks.yml
Labels: Bug fix, CI/CD, Developer Feature, develop

#25333 Caching playwright browsers on github workflows
  .github/workflows/sanity-72.yml
  .github/workflows/sanity-73.yml
  .github/workflows/sanity-74.yml
  .github/workflows/sanity.yml
  .github/workflows/ui-tests-code-checks.yml
Labels: 1.7.8.x, E2E Tests, Refactoring, TE

#25268 Fix isCatalogMode condition + Remove the price-drop link from the the best seller display condition
  controllers/front/SitemapController.php
Labels: QA ✔️, Refactoring, develop

#25344 Disable failing Behat test about product duplicate translation
  tests/Integration/Behaviour/Features/Scenario/Product/duplicate_product.feature
Labels: 1.7.8.x, Bug fix

#25286 Fix cart rule that can be used more than once per user when it shouldn't
  classes/CartRule.php
  tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Adding/CartRule/usage_limit_per_user.feature
  tests/Integration/Behaviour/behat.yml
Labels: 1.7.7.x, Bug fix, QA ✔️

#23698 Can't show module on the Left Column
  themes/classic/templates/layouts/layout-both-columns.tpl
Labels: Bug fix, QA ✔️, develop

#24080 Improve complexity of CategoryController::getCanonicalURL & Add doc to the parent function
  classes/controller/FrontController.php
  controllers/front/ProductController.php
  controllers/front/listing/CategoryController.php
Labels: QA ✔️, Refactoring, develop

#25242 Minor code refacto `Order.php`
  classes/order/Order.php
Labels: Refactoring, develop

#25210 Add download link when an order have 2 product type virtual and normal
  themes/classic/templates/customer/_partials/order-detail-no-return.tpl
  themes/classic/templates/customer/_partials/order-detail-return.tpl
Labels: Bug fix, QA ✔️, develop

#23798 Replace ProductInterface (wich is deprecated) occurences by RedirectType
  classes/Product.php
  controllers/front/ProductController.php
  src/PrestaShopBundle/Form/Admin/Product/ProductSeo.php
  src/PrestaShopBundle/Model/Product/AdminModelAdapter.php
Labels: QA ✔️, Refactoring, develop

#25365 Re-enable Behat test about product duplicate translation
  tests/Integration/Behaviour/Features/Scenario/Product/duplicate_product.feature
Labels: 1.7.8.x, Improvement

#25038 Fix tinymce max length computing in BO
  admin-dev/themes/new-theme/js/components/tinymce-editor.js
  classes/Product.php
  controllers/admin/AdminProductsController.php
  js/admin/tinymce_loader.js
  src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php
  src/PrestaShopBundle/Form/Validator/Constraints/TinyMceMaxLengthValidator.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_validator.yml
  tests/Unit/PrestaShopBundle/Form/Validator/Constraints/TinyMceMaxLengthValidatorTest.php
Labels: 1.7.8.x, BC break, Improvement, QA ✔️

#24620 No email check in BO > Advanced Parameters > Logs page
  src/Adapter/Configuration/LogsConfiguration.php
  src/Adapter/Validate.php
  src/PrestaShopBundle/Resources/config/services/adapter/data_configuration.yml
  tests/Unit/Adapter/ValidateTest.php
Labels: 1.7.8.x, BC break, Bug fix, QA ✔️, Wording ✔️

#25219 Functional tests - Refacto products tests
  tests/UI/campaigns/functional/BO/03_catalog/01_products/01_filterAndQuickEditProducts.js
  tests/UI/campaigns/functional/BO/03_catalog/01_products/02_paginationAndSortProducts.js
  tests/UI/campaigns/functional/BO/03_catalog/01_products/03_helpCard.js
  tests/UI/campaigns/functional/BO/03_catalog/01_products/04_previewProductFromList.js
  tests/UI/campaigns/functional/BO/03_catalog/01_products/05_duplicateProductFromList.js
  tests/UI/campaigns/functional/BO/03_catalog/01_products/06_bulkActions.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#25250 Functional tests - Refacto monitoring tests
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/01_deleteEmptyCategory.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/02_monitoringProducts.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/03_helpCard.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortAndPagination/01_emptyCategories.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortAndPagination/02_withCombinationsWithoutQuantities.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortAndPagination/03_withoutCombinationsWithoutQuantities.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortAndPagination/04_disabledProducts.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortAndPagination/05_productsWithoutImage.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortAndPagination/06_productsWithoutDescription.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortAndPagination/07_productsWithoutPrice.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#25171 Functional tests - Refacto login tests
  tests/UI/campaigns/functional/BO/00_login/01_passwordReminder.js
  tests/UI/campaigns/functional/BO/00_login/02_login.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#25150 Fix pagination condition on shopping cart test
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/01_filterShoppingCarts.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#25249 Create more order statuses to allow pagination
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/statuses/02_filterSortAndPagination.js
Labels: 1.7.8.x, E2E Tests, Refactoring, TE

#25325 Allow GitHub UI tests to run on branch push
  .github/workflows/sanity-72.yml
  .github/workflows/sanity-73.yml
  .github/workflows/sanity-74.yml
Labels: Improvement, QA ✔️, develop

#25341 Functional tests - Refacto modules and design tests
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/01_filterModulesByStatus.js
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/02_filterModulesByCategories.js
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/03_configureModule.js
  tests/UI/campaigns/functional/BO/08_design/03_emailTheme/01_previewEmailThemes.js
  tests/UI/campaigns/functional/BO/08_design/03_emailTheme/02_selectDefaultEmailTheme.js
  tests/UI/campaigns/functional/BO/08_design/03_emailTheme/03_viewRawHtmlAndText.js
  tests/UI/campaigns/functional/BO/08_design/04_pages/01_CRUDPageCategory.js
  tests/UI/campaigns/functional/BO/08_design/04_pages/02_helpCard.js
  tests/UI/campaigns/functional/BO/08_design/04_pages/04_filterAndQuickEditCategories.js
  tests/UI/campaigns/functional/BO/08_design/04_pages/categories/01_filterAndQuickEditCategories.js
  tests/UI/campaigns/functional/BO/08_design/04_pages/categories/02_categoriesBulkActions.js
  tests/UI/campaigns/functional/BO/08_design/04_pages/categories/03_paginationAndSortCategories.js
  tests/UI/campaigns/functional/BO/08_design/04_pages/pages/01_filterAndQuickEditPages.js
  tests/UI/campaigns/functional/BO/08_design/04_pages/pages/02_pagesBulkActions.js
  tests/UI/campaigns/functional/BO/08_design/04_pages/pages/03_paginationAndSortPages.js
  tests/UI/campaigns/functional/BO/08_design/05_positions/02_searchHook.js
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/01_filterImageTypes.js
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/02_CRUDImageType.js
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/03_bulkDeleteImageTypes.js
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/04_sortAndPagination.js
  tests/UI/campaigns/functional/BO/08_design/07_linkWidget/01_createAndCheckFooterLinkWidget.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#25259 Functional tests - Refacto attributes and features tests
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/01_CRUDAttributesAndValues.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/attributes/01_filterAttributes.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/attributes/02_sortPaginationAndBulkDelete.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/attributes/03_changePosition.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/attributes/04_helpCard.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/values/01_filterValues.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/values/02_sortPaginationAndBulkDelete.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/values/03_changePosition.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/features/01_filterFeatures.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/features/02_sortPaginationAndBulkDelete.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/features/03_changePosition.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/features/04_helpCard.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/values/01_filterFeatureValues.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/values/02_sortPaginationAndBulkDelete.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#25167 Functional tests - CRUD cart rule with/without code
  tests/UI/campaigns/data/faker/cartRule.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/01_withAndWithoutCode.js
  tests/UI/pages/BO/catalog/discounts/add.js
  tests/UI/pages/FO/FObasePage.js
  tests/UI/pages/FO/cart/index.js
  tests/UI/pages/commonPage.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#25201 Functional tests - (Refacto) Delete 'uppercaseFirstCharacter()' method
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/01_enableFinalSummary.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/02_enableGuestCheckout.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/03_disableReorderingOption.js
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/01_catalogMode.js
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/05_forceUpdateFriendlyURL.js
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/06_defaultActivationStatus.js
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/01_displayAvailableQuantities.js
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/03_displayUnavailableProductAttributes.js
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/06_displayDiscountedPrice.js
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/04_enableB2BMode.js
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/05_askForBirthDate.js
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/06_enablePartnerOffers.js
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/02_filterAndQuickEditWebservice.js
  tests/UI/pages/commonPage.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#25326 Create empty Customer when the customer or the guest has been deleted
  src/Adapter/Customer/CustomerDataProvider.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewing.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/private_note.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/update_customer_address_modal.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/view_all_messages_modal.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/header.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig
  tests/Integration/Behaviour/Features/Context/Domain/OrderCustomerFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_customer.feature
Labels: 1.7.7.x, Bug fix, QA ✔️

#25375 In Order view, set the lang of the order for order messages
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
Labels: 1.7.7.x, Bug fix, QA ✔️

#25378 Order Product Search: Limit only if the search phrase length is greater than 2 characters and HTTP Code Error become a 400
  admin-dev/themes/new-theme/js/pages/order/create/product-manager.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add-autocomplete.js
  src/Core/Domain/Product/Exception/ProductSearchEmptyPhraseException.php
  src/Core/Domain/Product/Query/SearchProducts.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  tests/Integration/PrestaShopBundle/Controller/Admin/Sell/Order/OrderControllerTest.php
  tests/Unit/Core/Domain/Product/Query/SearchProductsTest.php
Labels: 1.7.7.x, Bug fix, QA ✔️

#25364 Fix inputs prefilling bug when a combination is added to an order
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/discount_list.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
Labels: 1.7.8.x, Bug fix, QA ✔️

#25316 Fix blocking add to cart button
  themes/_core/js/cart.js
Labels: 1.7.8.x, Bug fix, QA ✔️

#25306 Fix 1.7.7.2 upgrade
  install-dev/upgrade/sql/1.7.7.2.sql
Labels: 1.7.7.x, Bug fix, QA ✔️

#25320 Fix languages test install
  .github/workflows/integration.yml
  .github/workflows/phpunit/parameters.php
  src/PrestaShopBundle/Install/DatabaseDump.php
  tests-legacy/PrestaShopBundle/Utils/DatabaseCreator.php
Labels: 1.7.8.x, Bug fix

#25169 Cart rule category selection : display categories in a hierarchical way
  controllers/admin/AdminCartRulesController.php
Labels: Improvement, PM ✔️, QA ✔️, develop

#25295 Allow enable/disable selection for customers in Customer Groups
  controllers/admin/AdminGroupsController.php
Labels: Bug fix, QA ✔️, Wording ✔️, develop

#25391 Fixed PHPDoc
  classes/controller/Controller.php
Labels: Documentation, develop

#25403 Fixed Unit Tests
  tests/Unit/Core/Grid/Query/Filter/DoctrineFilterApplicatorTest.php
Labels: Bug fix, develop

#25212 Fixed typo `Country.php`
  classes/Country.php
Labels: Bug fix, Refactoring, develop

#25288 Github Actions: Migrated base to ubuntu-latest & Grouped Sanity Tests
  .github/workflows/integration.yml
  .github/workflows/php.yml
  .github/workflows/sanity-73.yml
  .github/workflows/sanity-74.yml
  .github/workflows/sanity.yml
Labels: Improvement, develop

#25410 Make sure order variable exists and also return the order_list variable in actionValidateOrderAfter hook
  classes/PaymentModule.php
Labels: Bug fix, develop

#25411 Use only one file for sanity, remove sanity-80.yml
  .github/workflows/sanity-80.yml
  .github/workflows/sanity.yml
Labels: Improvement, develop

#25413 Fix performance issue on Smarty template caching
  classes/module/Module.php
Labels: Bug fix, QA ✔️, develop

#25301 Display validation when Enable/Disable webservice keys by bulk actions
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceController.php
  tests/Integration/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceControllerTest.php
Labels: Bug fix, QA ✔️, Wording ✔️, develop

#24786 Remove unused backoffice footer
  admin-dev/index.php
  admin-dev/themes/default/scss/admin-theme.scss
  admin-dev/themes/default/scss/partials/_footer.scss
  admin-dev/themes/default/template/footer.tpl
  classes/controller/AdminController.php
  js/admin.js
Labels: BC break, QA ✔️, Refactoring, develop

#25139 Fix the path of the "form_warehouse_combination"
  templates/bundles/PrestaShopBundle/Admin/Product/ProductPage/Forms/form_shipping.html.twig
Labels: Bug fix, QA ✔️, develop

#24991 Fix combination ecotax display and edition
  admin-dev/themes/default/js/bundle/product/form.js
  admin-dev/themes/default/js/bundle/product/product-combinations.js
  admin-dev/themes/new-theme/js/product-page/product-bulk-combinations.js
  classes/Product.php
  classes/order/OrderDetail.php
  classes/order/OrderInvoice.php
  controllers/front/ProductController.php
  pdf/invoice.tax-tab.tpl
  src/Adapter/CombinationDataProvider.php
  src/Adapter/Product/AdminProductWrapper.php
  src/PrestaShopBundle/Form/Admin/Product/ProductCombination.php
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combination.html.twig
  tests-legacy/PrestaShopBundle/Model/Product/AdminModelAdapterTest.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_currency.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_combination.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_french_tax.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_multi_shop.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_odd_tax.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_shipping.feature
Labels: 1.7.7.x, Bug fix, QA ✔️, Wording ✔️

#25447 Update prestashop modules on 1.7.7.x
  composer.lock
Labels: 1.7.7.x, Improvement

#25445 Fix wrong service for TranslationExtension
  src/PrestaShopBundle/Twig/TranslationsExtension.php
Labels: Bug fix, develop

#25428 Don't recalculate total when PS_ORDER_RECALCULATE_SHIPPING is 0 and editing a carrier
  src/Adapter/Order/OrderAmountUpdater.php
  src/Core/Cart/Calculator.php
  src/Core/Cart/Fees.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature
Labels: 1.7.7.x, Bug fix, QA ✔️

#25449 Build assets on 1.7.7.x
  admin-dev/themes/new-theme/public/currency_form.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  admin-dev/themes/new-theme/public/product_page.bundle.js
  themes/classic/assets/js/theme.js
Labels: 1.7.7.x, Improvement

#25435 Update twig to v3
  composer.json
  composer.lock
  src/Adapter/Twig/LocaleExtension.php
  src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
  src/PrestaShopBundle/Twig/AdminExtension.php
  src/PrestaShopBundle/Twig/ContextIsoCodeProviderExtension.php
  src/PrestaShopBundle/Twig/DataFormatterExtension.php
  src/PrestaShopBundle/Twig/Extension/ColorBrightnessCalculatorExtension.php
  src/PrestaShopBundle/Twig/Extension/DocumentationLinkExtension.php
  src/PrestaShopBundle/Twig/Extension/GridExtension.php
  src/PrestaShopBundle/Twig/Extension/JsRouterMetadataExtension.php
  src/PrestaShopBundle/Twig/Extension/LocalizationExtension.php
  src/PrestaShopBundle/Twig/Extension/MultistoreUrlExtension.php
  src/PrestaShopBundle/Twig/HookExtension.php
  src/PrestaShopBundle/Twig/LayoutExtension.php
  src/PrestaShopBundle/Twig/TranslationsExtension.php
  templates/bundles/PrestaShopBundle/Admin/Common/Grid/Columns/Content/action.html.twig
  templates/bundles/PrestaShopBundle/Admin/Common/Grid/Columns/Content/choice.html.twig
  templates/bundles/PrestaShopBundle/Admin/Improve/Design/positions.html.twig
  templates/bundles/PrestaShopBundle/Admin/Multistore/header.html.twig
  templates/bundles/PrestaShopBundle/Admin/Product/ProductPage/Panels/essentials.html.twig
  templates/bundles/PrestaShopBundle/Admin/Product/ProductPage/Panels/options.html.twig
  templates/bundles/PrestaShopBundle/Admin/Sell/Address/Blocks/form.html.twig
  templates/bundles/PrestaShopBundle/Admin/Sell/Catalog/Manufacturer/index.html.twig
  templates/bundles/PrestaShopBundle/Admin/Sell/Catalog/Suppliers/index.html.twig
  templates/bundles/PrestaShopBundle/Admin/Sell/Order/Order/Blocks/Create/summary.html.twig
  templates/bundles/PrestaShopBundle/Admin/TwigTemplateForm/bootstrap_4_horizontal_layout.html.twig
  templates/bundles/PrestaShopBundle/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
  templates/bundles/PrestaShopBundle/Admin/TwigTemplateForm/prestashop_ui_kit.html.twig
  templates/bundles/PrestaShopBundle/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
  templates/bundles/PrestaShopBundle/Admin/TwigTemplateForm/typeahead.html.twig
  templates/bundles/PrestaShopBundle/Admin/layout.html.twig
Labels: BC break, Improvement, QA ✔️, develop

#25433 ObjectModel::add() : force_id is working now with lang table
  classes/ObjectModel.php
Labels: Bug fix, QA ✔️, develop

#24684 Option to override CMS category template
  classes/Smarty/TemplateFinder.php
  controllers/front/CmsController.php
Labels: Developer Feature, Improvement, QA ✔️, develop

#25305 States : Added add button only on listing pages
  controllers/admin/AdminStatesController.php
Labels: Bug fix, QA ✔️, Wording ✔️, develop

#25439 BO - Customer View page - Added alert when removing a voucher
  controllers/admin/AdminCartRulesController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
Labels: Bug fix, QA ✔️, Wording ✔️, develop

#25186 Refacto stock page using TypeScript
  admin-dev/themes/new-theme/.eslintrc.js
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/js/app/pages/stock/components/app.vue
  admin-dev/themes/new-theme/js/app/pages/stock/components/header/breadcrumb.vue
  admin-dev/themes/new-theme/js/app/pages/stock/components/header/filters.vue
  admin-dev/themes/new-theme/js/app/pages/stock/components/header/filters/filter-component.vue
  admin-dev/themes/new-theme/js/app/pages/stock/components/header/filters/low-filter.vue
  admin-dev/themes/new-theme/js/app/pages/stock/components/header/search.vue
  admin-dev/themes/new-theme/js/app/pages/stock/components/header/stock-header.vue
  admin-dev/themes/new-theme/js/app/pages/stock/components/header/tabs.vue
  admin-dev/themes/new-theme/js/app/pages/stock/components/movements/index.vue
  admin-dev/themes/new-theme/js/app/pages/stock/components/movements/movement-line.vue
  admin-dev/themes/new-theme/js/app/pages/stock/components/overview/index.vue
  admin-dev/themes/new-theme/js/app/pages/stock/components/overview/movement-type.vue
  admin-dev/themes/new-theme/js/app/pages/stock/components/overview/product-line.vue
  admin-dev/themes/new-theme/js/app/pages/stock/components/overview/products-actions.vue
  admin-dev/themes/new-theme/js/app/pages/stock/components/overview/products-table.vue
  admin-dev/themes/new-theme/js/app/pages/stock/components/overview/spinner.vue
  admin-dev/themes/new-theme/js/app/pages/stock/index.ts
  admin-dev/themes/new-theme/js/app/widgets/ps-alert.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-button.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-checkbox.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-datepicker.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-loader.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-media.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-modal.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-number.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-pagination.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-radio.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-select.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-table/ps-sort.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-table/ps-table.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-tags.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-tree/ps-tree-item.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-tree/ps-tree.vue
  admin-dev/themes/new-theme/js/theme.ts
  admin-dev/themes/new-theme/js/types/global.d.ts
  admin-dev/themes/new-theme/js/types/vue/resource.d.ts
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
  admin-dev/themes/new-theme/tsconfig.json
Labels: Bug fix, Improvement, QA ✔️, develop

#25157 Improve admin product list header
  admin-dev/themes/new-theme/scss/pages/product/products_catalog.scss
  templates/bundles/PrestaShopBundle/Admin/Product/CatalogPage/Blocks/filters.html.twig
  templates/bundles/PrestaShopBundle/Admin/Product/CatalogPage/Blocks/tools.html.twig
  templates/bundles/PrestaShopBundle/Admin/Product/CatalogPage/Forms/form_products.html.twig
  templates/bundles/PrestaShopBundle/Admin/Product/CatalogPage/Lists/products_table.html.twig
  templates/bundles/PrestaShopBundle/Admin/Product/CatalogPage/catalog.html.twig
  tests/UI/pages/BO/catalog/products/index.js
Labels: Bug fix, QA ✔️, develop

#25056 Fix BO order create responsivity
  templates/bundles/PrestaShopBundle/Admin/Sell/Order/Order/Blocks/Create/addresses.html.twig
  templates/bundles/PrestaShopBundle/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig
  templates/bundles/PrestaShopBundle/Admin/Sell/Order/Order/Blocks/Create/cart_rules.html.twig
  templates/bundles/PrestaShopBundle/Admin/Sell/Order/Order/Blocks/Create/customer.html.twig
  templates/bundles/PrestaShopBundle/Admin/Sell/Order/Order/Blocks/Create/shipping.html.twig
  templates/bundles/PrestaShopBundle/Admin/Sell/Order/Order/Blocks/Create/summary.html.twig
  templates/bundles/PrestaShopBundle/Admin/Sell/Order/Order/create.html.twig
Labels: Bug fix, QA ✔️, develop
