Repository PrestaShop/PrestaShop, pull requests merged in 2021-04, with the labels that each got.

#23528 Fix, hide desactivated categories in breadcrumbs
  controllers/front/ProductController.php
  controllers/front/listing/CategoryController.php
Labels: Bug fix, QA ✔️, develop

#23852 Fix 'Add to cart' test
  tests/UI/campaigns/functional/FO/08_productPage/02_addToCart.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#23855 Fix Close onboarding on sanity tests
  tests/UI/campaigns/sanity/02_productsBO/01_filterProducts.js
  tests/UI/pages/BO/BObasePage.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#23599 Fix module page responsive bug on modal nav, close icon and icon height
  admin-dev/themes/new-theme/scss/pages/_modules.scss
Labels: Bug fix, QA ✔️, develop

#23841 Fix autocomplete UI going under the header on classic theme
  themes/classic/_dev/css/partials/_commons.scss
Labels: Bug fix, QA ✔️, develop

#23840 Disable shop context switching from the multistore header if the shop has no URL
  admin-dev/themes/new-theme/scss/components/_multishop-modal.scss
  src/Adapter/Shop/QueryHandler/SearchShopsHandler.php
  src/PrestaShopBundle/Resources/views/Admin/Multistore/header.html.twig
  tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Shop/search_shops.feature
Labels: Improvement, QA ✔️, develop

#23828 Update state.xml - Distrito Federal changed to Ciudad de México
  install-dev/data/xml/state.xml
Labels: Improvement, PM ✔️, QA ✔️, develop

#23844 Fix BOEvent not being on window object anymore
  admin-dev/themes/default/js/bundle/default.js
Labels: Bug fix, QA ✔️, develop

#23834 Remove code related to CACHE_FILE_MODULES_LIST
  classes/module/Module.php
  controllers/admin/AdminModulesController.php
Labels: BC break, Bug fix, QA ✔️, develop

#23877 Refacto product command builder
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/BasicInformationCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/CustomizationFieldsCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/FeatureValuesCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/OptionsCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandBuilderInterface.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandsBuilderInterface.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductSuppliersCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/SEOCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/ShippingCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/StockCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/TypeCommandsBuilder.php
  src/PrestaShopBundle/Resources/config/services/core/form/command_builder.yml
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/BasicInformationCommandBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/CustomizationFieldsCommandBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/FeatureValuesCommandBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductOptionsCommandBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductSuppliersCommandBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/SEOCommandBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/ShippingCommandBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/StockCommandBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/TypeCommandBuilderTest.php
Labels: Improvement, develop, migration

#23856 Fix for issue where log controller would crash in dev mode.
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/severity_level.html.twig
Labels: Bug fix, QA ✔️, develop

#23742 Fixed the quantity calculation of packs when containing product variations
  classes/Pack.php
Labels: Bug fix, QA ✔️, develop

#23794 List attribute groups CQRS query using Doctrine EntityRepository
  src/Adapter/Attribute/Repository/AttributeRepository.php
  src/Adapter/Product/AttributeGroup/QueryHandler/AbstractAttributeGroupQueryHandler.php
  src/Adapter/Product/AttributeGroup/QueryHandler/GetAttributeGroupListHandler.php
  src/Adapter/Product/AttributeGroup/QueryHandler/GetProductAttributeGroupsHandler.php
  src/Adapter/Product/Combination/QueryHandler/GetEditableCombinationsListHandler.php
  src/Adapter/Product/Combination/Repository/CombinationRepository.php
  src/Core/Domain/Product/AttributeGroup/Attribute/QueryResult/Attribute.php
  src/Core/Domain/Product/AttributeGroup/Query/GetAttributeGroupList.php
  src/Core/Domain/Product/AttributeGroup/Query/GetProductAttributeGroups.php
  src/Core/Domain/Product/AttributeGroup/QueryHandler/GetAttributeGroupListHandlerInterface.php
  src/Core/Domain/Product/AttributeGroup/QueryHandler/GetProductAttributeGroupsHandlerInterface.php
  src/Core/Domain/Product/AttributeGroup/QueryResult/AttributeGroup.php
  src/PrestaShopBundle/Entity/AttributeGroup.php
  src/PrestaShopBundle/Entity/Repository/AttributeGroupRepository.php
  src/PrestaShopBundle/Resources/config/services/adapter/attribute_group.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_combination.yml
  src/PrestaShopBundle/Resources/config/services/bundle/repository.yml
  tests/Integration/Behaviour/Features/Context/Domain/AttributeGroupFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Attribute/list_attribute_groups.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/forbidden_actions.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/generate_combinations.feature
  tests/Integration/Behaviour/behat.yml
Labels: Improvement, develop, migration

#23760 Fix uses of #fff instead of $white in the classic and new-theme scss
  admin-dev/themes/new-theme/scss/components/_button.scss
  admin-dev/themes/new-theme/scss/components/_grid.scss
  admin-dev/themes/new-theme/scss/components/_modulescards.scss
  admin-dev/themes/new-theme/scss/components/_multishop-modal.scss
  admin-dev/themes/new-theme/scss/components/_notifications.scss
  admin-dev/themes/new-theme/scss/components/_ps_alert.scss
  admin-dev/themes/new-theme/scss/components/_ps_dropdown.scss
  admin-dev/themes/new-theme/scss/components/_ps_number.scss
  admin-dev/themes/new-theme/scss/components/_ps_radio.scss
  admin-dev/themes/new-theme/scss/components/_ps_spinner.scss
  admin-dev/themes/new-theme/scss/components/_showcase-card.scss
  admin-dev/themes/new-theme/scss/components/_submittable_input.scss
  admin-dev/themes/new-theme/scss/components/_timeline.scss
  admin-dev/themes/new-theme/scss/components/_tinymce.scss
  admin-dev/themes/new-theme/scss/components/_toggable_field.scss
  admin-dev/themes/new-theme/scss/components/layout/_header-multistore.scss
  admin-dev/themes/new-theme/scss/components/layout/_header_toolbar.scss
  admin-dev/themes/new-theme/scss/components/layout/_kpi.scss
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
  admin-dev/themes/new-theme/scss/components/layout/_nav_bar.scss
  admin-dev/themes/new-theme/scss/components/layout/_non_responsive.scss
  admin-dev/themes/new-theme/scss/components/layout/_right-sidebar.scss
  admin-dev/themes/new-theme/scss/config/_settings.scss
  admin-dev/themes/new-theme/scss/mixins/_cards.scss
  admin-dev/themes/new-theme/scss/mixins/_notification_counter.scss
  admin-dev/themes/new-theme/scss/pages/_compromised.scss
  admin-dev/themes/new-theme/scss/pages/_modules.scss
  admin-dev/themes/new-theme/scss/pages/_themes_logo.scss
  admin-dev/themes/new-theme/scss/pages/_translation_page.scss
  admin-dev/themes/new-theme/scss/pages/orders/_orders_main.scss
  admin-dev/themes/new-theme/scss/pages/orders/_orders_view.scss
  admin-dev/themes/new-theme/scss/pages/partials/_theme_logo_theme_card.scss
  admin-dev/themes/new-theme/scss/pages/product/product_page.scss
  admin-dev/themes/new-theme/scss/pages/product/products_catalog.scss
  admin-dev/themes/new-theme/scss/pages/stock/stock_page.scss
  admin-dev/themes/new-theme/scss/theme.scss
  themes/classic/_dev/css/components/block-reassurance.scss
  themes/classic/_dev/css/components/brands.scss
  themes/classic/_dev/css/components/cart.scss
  themes/classic/_dev/css/components/categories.scss
  themes/classic/_dev/css/components/checkout.scss
  themes/classic/_dev/css/components/contact.scss
  themes/classic/_dev/css/components/custom-text.scss
  themes/classic/_dev/css/components/customer.scss
  themes/classic/_dev/css/components/drop-down.scss
  themes/classic/_dev/css/components/errors.scss
  themes/classic/_dev/css/components/featuredproducts.scss
  themes/classic/_dev/css/components/footer.scss
  themes/classic/_dev/css/components/header.scss
  themes/classic/_dev/css/components/imageslider.scss
  themes/classic/_dev/css/components/mainmenu.scss
  themes/classic/_dev/css/components/newsletter.scss
  themes/classic/_dev/css/components/products.scss
  themes/classic/_dev/css/components/quickview.scss
  themes/classic/_dev/css/components/search-widget.scss
  themes/classic/_dev/css/partials/_commons.scss
  themes/classic/_dev/css/partials/_mixins.scss
  themes/classic/_dev/css/partials/_variables.scss
Labels: Improvement, QA ✔️, develop

#23894 Multistore dropdown in configuration forms
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/js/components/components-map.js
  admin-dev/themes/new-theme/js/components/multistore-dropdown.js
  admin-dev/themes/new-theme/scss/components/_multistore-dropdown.scss
  admin-dev/themes/new-theme/scss/theme.scss
  classes/controller/AdminController.php
  src/PrestaShopBundle/Controller/Admin/MultistoreController.php
  src/PrestaShopBundle/Entity/Shop.php
  src/PrestaShopBundle/Form/Admin/Extension/MultistoreConfigurationTypeExtension.php
  src/PrestaShopBundle/Form/Admin/Extension/MultistoreDropdownExtension.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_extension.yml
  src/PrestaShopBundle/Resources/views/Admin/Multistore/dropdown.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Multistore/header.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit.html.twig
  src/PrestaShopBundle/Service/Form/MultistoreCheckboxEnabler.php
  tests/Unit/PrestaShopBundle/Service/Form/MultistoreCheckboxEnablerTest.php
Labels: Feature, Must-have, QA ✔️, develop

#23907 Enable header toolbar buttons to be disabled and use it for Add an Order
  admin-dev/themes/new-theme/scss/components/_button.scss
  admin-dev/themes/new-theme/template/page_header_toolbar.tpl
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
Labels: Feature, Must-have, QA ✔️, Wording ✔️, develop

#23672 Add photoswipe to zoom on images on product page v2
  admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue
  admin-dev/themes/new-theme/js/pages/product/components/dropzone/DropzonePhotoSwipe.vue
  admin-dev/themes/new-theme/js/pages/product/components/dropzone/DropzoneWindow.vue
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
  admin-dev/themes/new-theme/scss/pages/product/product_page.scss
  src/PrestaShopBundle/Form/Admin/Sell/Product/Image/ImageDropzoneType.php
Labels: Feature, PM ✔️, QA ✔️, Waiting for PM, Wording ✔️, develop

#23938 Add some missing scenarios on customer block test
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/01_customerBlock.js
  tests/UI/pages/BO/customers/addresses/add.js
  tests/UI/pages/BO/orders/view.js
  tests/UI/pages/FO/myAccount/addresses.js
  tests/UI/pages/FO/myAccount/index.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#23913 Get categories tree query and endpoint
  src/Adapter/Category/QueryHandler/GetCategoriesTreeHandler.php
  src/Core/Domain/Category/Query/GetCategoriesTree.php
  src/Core/Domain/Category/QueryHandler/GetCategoriesTreeHandlerInterface.php
  src/Core/Domain/Category/QueryResult/CategoryForTree.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/categories.yml
  src/PrestaShopBundle/Resources/config/services/adapter/category.yml
  tests/Integration/Behaviour/Features/Context/Domain/CategoryFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/category_tree.feature
Labels: Refactoring, develop

#21751 Show out of stock label on listing pages : Configuration & Display in FrontOffice
  classes/ProductPresenterFactory.php
  install-dev/data/xml/configuration.xml
  install-dev/upgrade/sql/1.7.8.0.sql
  src/Adapter/Presenter/Cart/CartPresenter.php
  src/Adapter/Presenter/Product/ProductLazyArray.php
  src/Adapter/Presenter/Product/ProductPresenter.php
  src/Adapter/Product/StockConfiguration.php
  src/Core/Product/ProductPresentationSettings.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/StockType.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_stock.html.twig
  tests/Integration/Adapter/Presenter/Product/ProductLazyArrayTest.php
Labels: Feature, QA ✔️, Wording ✔️, develop

#23903 No image available in German: fix typo.
  install-dev/langs/de/img/de-default-category.jpg
  install-dev/langs/de/img/de-default-home.jpg
  install-dev/langs/de/img/de-default-large.jpg
  install-dev/langs/de/img/de-default-large_scene.jpg
  install-dev/langs/de/img/de-default-medium.jpg
  install-dev/langs/de/img/de-default-small.jpg
  install-dev/langs/de/img/de-default-thickbox.jpg
  install-dev/langs/de/img/de-default-thumb_scene.jpg
  install-dev/langs/de/img/de.jpg
Labels: Bug fix, QA ✔️, develop

#23846 Fix options is undefined on right-sidebar of default theme
  admin-dev/themes/default/js/bundle/right-sidebar.js
Labels: Bug fix, QA ✔️, develop

#23921 Attributes list api for combinations filtering
  admin-dev/themes/new-theme/js/fos_js_routes.json
  src/Adapter/Product/AttributeGroup/QueryHandler/AbstractAttributeGroupQueryHandler.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/product_v2/combination.yml
Labels: Refactoring, Waiting for QA, develop

#23925 Set locale to null when empty
  src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php
Labels: 1.7.7.x, Bug fix, QA ✔️

#23950 Update outdated composer.lock
  composer.lock
Labels: Bug fix, develop

#23943 Improve compatibility in legacy code for new product_type field
  classes/Pack.php
  classes/Product.php
  install-dev/data/db_structure.sql
  src/Core/Domain/Product/ValueObject/ProductType.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/CommonProductFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/legacy_product_type.feature
  tests/Integration/Behaviour/behat.yml
Labels: Improvement, develop, migration

#23946 Separate error messages on Installation test
  tests/UI/campaigns/sanity/01_installShop/01_installShop.js
  tests/UI/pages/install/index.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#23931 Add composer validate check to CI
  .github/workflows/php.yml
  composer.json
  composer.lock
Labels: Improvement, develop

#23967 Fix role in combination list
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php
Labels: Bug fix, develop, migration

#23819 Open tracking url in a new tab and add the link to the order preview
  src/Adapter/Order/QueryHandler/GetOrderPreviewHandler.php
  src/Core/Domain/Order/QueryResult/OrderPreviewShippingDetails.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/shipping.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/preview.html.twig
  tests/Integration/Behaviour/Features/Context/CarrierFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_address.feature
  tests/Unit/Core/Domain/Order/QueryResult/OrderPreviewShippingDetailsTest.php
Labels: 1.7.7.x, Bug fix, QA ✔️

#23965 Fix nightly tests 09-04-2021
  tests/UI/campaigns/functional/FO/03_userAccount/01_orderHistory/01_orderDetails/01_sendMessage.js
  tests/UI/campaigns/functional/FO/08_productPage/01_quickView.js
  tests/UI/campaigns/functional/FO/08_productPage/02_addToCart.js
  tests/UI/package.json
  tests/UI/pages/BO/customers/addresses/add.js
  tests/UI/pages/BO/shopParameters/search/index.js
  tests/UI/pages/FO/category/index.js
  tests/UI/pages/FO/home/index.js
  tests/UI/pages/FO/product/index.js
  themes/classic/templates/catalog/_partials/product-prices.tpl
  themes/classic/templates/catalog/_partials/product-variants.tpl
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#23703 New BO page Experimental Feature
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/js/pages/feature-flag/index.js
  install-dev/data/xml/access.xml
  install-dev/data/xml/authorization_role.xml
  install-dev/data/xml/tab.xml
  install-dev/langs/en/data/tab.xml
  install-dev/upgrade/php/ps_1780_add_feature_flag_tab.php
  install-dev/upgrade/sql/1.7.8.0.sql
  src/Core/FeatureFlag/FeatureFlagsModifier.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/FeatureFlagController.php
  src/PrestaShopBundle/Entity/FeatureFlag.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/FeatureFlag/FeatureFlagsFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/FeatureFlag/FeatureFlagsType.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/_advanced_parameters.yml
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/feature_flags.yml
  src/PrestaShopBundle/Resources/config/services/adapter/data_configuration.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_handler.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/FeatureFlag/index.html.twig
  tests/Integration/Behaviour/Features/Context/FeatureFlagFeatureContext.php
  tests/Unit/Core/FeatureFlag/FeatureFlagsModifierTest.php
  tests/Unit/PrestaShopBundle/Entity/FeatureFlagTest.php
Labels: Feature, Must-have, PM ✔️, QA ✔️, UX ✔️, develop

#23994 Fix step 'Go back to BO' on maintenance test
  tests/UI/campaigns/functional/BO/13_shopParameters/01_general/maintenance/01_enableDisableShop.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#23995 Rename currency column into name
  src/Core/Grid/Definition/Factory/CurrencyGridDefinitionFactory.php
Labels: Bug fix, QA ✔️, develop

#23960 Add webservice/ dir to phpstan
  phpstan.neon.dist
Labels: Improvement, develop

#23940 Disable add new customer button in all shops or in a group context
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/index.html.twig
Labels: Feature, Must-have, QA ✔️, develop

#24005 Fix order details product pagination not showing
  admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js
Labels: Bug fix, QA ✔️, develop

#23857 Change signature of TranslationFinder::getTranslationFilesFromPath to accept null pattern
  src/PrestaShopBundle/Translation/Provider/TranslationFinder.php
  tests/Integration/PrestaShopBundle/Translation/Provider/TranslationFinderTest.php
Labels: Bug fix, QA ✔️, develop

#23776 Enable to back to shop in admin login page
  admin-dev/themes/default/template/controllers/login/content.tpl
  controllers/admin/AdminLoginController.php
Labels: Improvement, PM ✔️, QA ✔️, Wording ✔️, develop

#22712 Migrated Nightly Cron from Travis CI to Github Actions
  .github/workflows/cron_nightly.yml
  .travis.yml
  tests/UI/scripts/run-nightly-reports.sh
  tests/UI/scripts/run-nightly-tests.sh
Labels: Improvement, develop

#18082 Make BO menu translatable
  classes/Language.php
  classes/Tab.php
  classes/lang/DataLang.php
  classes/lang/TabLang.php
  classes/shop/Shop.php
  install-dev/data/xml/tab.xml
  install-dev/langs/en/data/tab.xml
  install-dev/upgrade/sql/1.7.8.0.sql
  src/Adapter/EntityTranslation/DataLangFactory.php
  src/Adapter/EntityTranslation/EntityTranslator.php
  src/Adapter/EntityTranslation/EntityTranslatorFactory.php
  src/Adapter/EntityTranslation/Exception/DataLangClassNameNotFoundException.php
  src/Adapter/EntityTranslation/TabTranslator.php
  src/Adapter/Module/Tab/ModuleTabRegister.php
  src/Core/Translation/EntityTranslatorInterface.php
  src/PrestaShopBundle/Controller/Api/TranslationController.php
  src/PrestaShopBundle/Entity/Tab.php
  src/PrestaShopBundle/Install/EntityLoader/FileLoader.php
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Install/XmlLoader.php
  src/PrestaShopBundle/Service/TranslationService.php
  src/PrestaShopBundle/Translation/DataCollectorTranslator.php
  src/PrestaShopBundle/Translation/Translator.php
  src/PrestaShopBundle/Translation/TranslatorComponent.php
  src/PrestaShopBundle/Translation/TranslatorInterface.php
  tests/Unit/Adapter/Translations/DataLangFactoryTest.php
Labels: Bug, Bug fix, Key feature, QA ✔️, Wording ✔️, develop

#24004 Functional tests - Add missing test to sort orders by date
  tests/UI/campaigns/functional/BO/02_orders/01_orders/07_sortOrders.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#24006 Functional tests - Add missing test to filter orders by date
  tests/UI/campaigns/functional/BO/02_orders/01_orders/02_filterOrders.js
  tests/UI/pages/BO/orders/index.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#21737 Added support for Addons API stability channel
  controllers/admin/AdminModulesController.php
  install-dev/data/xml/configuration.xml
  install-dev/upgrade/sql/1.7.8.0.sql
  src/Adapter/Addons/AddonsDataProvider.php
  src/Adapter/GeneralConfiguration.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AdministrationController.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Administration/GeneralType.php
  src/PrestaShopBundle/Resources/config/services/adapter/data_configuration.yml
  src/PrestaShopBundle/Resources/config/services/adapter/data_provider.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Service/DataProvider/Marketplace/ApiClient.php
  tests/Unit/Adapter/Addons/AddonsDataProviderTest.php
  tests/Unit/PrestaShopBundle/Service/DataProvider/Admin/Marketplace/ApiClientTest.php
  tests/Unit/bootstrap.php
Labels: Improvement, QA ✔️, Wording ✔️, develop

#24014 Update "node-sass" dep from 4.13.1 to 4.14.1
  .github/workflows/lint.yml
  admin-dev/themes/default/package-lock.json
  admin-dev/themes/default/package.json
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
  themes/classic/_dev/package.json
  themes/package.json
Labels: Improvement, develop

#24030 Fix nightly - Separate enable and disable demo mode iteration
  tests/UI/campaigns/functional/BO/01_dashboard/01_enableDisableDemoMode.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#24016 Functional tests - Add test to verify login BO
  tests/UI/campaigns/functional/BO/00_login/02_login.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#24028 Fixed wording domains in multistore dropdown template
  src/PrestaShopBundle/Resources/views/Admin/Multistore/dropdown.html.twig
Labels: Improvement, Must-have, QA ✔️, Wording ✔️, develop

#23956 Combination form part 2 in new Product Page
  src/Adapter/Product/Combination/QueryHandler/GetCombinationForEditingHandler.php
  src/Adapter/Product/QueryHandler/GetProductForEditingHandler.php
  src/Adapter/Tax/TaxComputer.php
  src/Core/Domain/Product/Combination/QueryResult/CombinationPrices.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationDetailsCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationPriceCommandsBuilder.php
  src/Core/Form/IdentifiableObject/DataProvider/CombinationFormDataProvider.php
  src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationDetailsType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationFormType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationPriceImpactType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationStockType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/StockType.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_combination.yml
  src/PrestaShopBundle/Resources/config/services/adapter/tax.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/command_builder.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/UpdateCombinationPricesFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/update_combination_prices.feature
  tests/Unit/Adapter/Tax/TaxComputerTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationDetailsCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationPriceCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/CombinationFormDataProviderTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProviderTest.php
Labels: Feature, develop

#24032 Add multistore info messages
  controllers/admin/AdminStatesController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/BackupController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/PerformanceController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ProfileController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SqlManagerController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/MetaController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/LanguageController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/TaxController.php
  src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/OrderMessageController.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Backup/index.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Profiles/create.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Profiles/index.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/RequestSql/create.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/performance.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/TrafficSeo/Meta/create.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Language/index.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Tax/create.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/CustomerService/OrderMessage/create.html.twig
Labels: 1.7.8.0, Improvement, Must-have, QA ✔️, Wording ✔️, develop

#24034 Nightly: Remove unused environment variable
  .github/workflows/cron_nightly.yml
Labels: Refactoring, develop

#23617 Added blockwishlist module & Removed archived modules
  composer.json
  composer.lock
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Install/Upgrade.php
Labels: Improvement, Key feature, QA ✔️, develop

#24017 Update SHOP_LOGO_* configuration when changing shop logo
  src/Core/Shop/LogoUploader.php
  tests/Integration/Behaviour/Features/Context/Domain/ShopFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Shop/shop.feature
  tests/Integration/Behaviour/behat.yml
  tests/Resources/assets/new_logo.jpg
Labels: 1.7.7.x, Bug fix, QA ✔️

#23947 Upgrade playwright to v1.8.1
  tests/UI/package-lock.json
  tests/UI/package.json
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/catalog/products/add.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#23927 Display multishop header for translations page and lock it to all shops context
  admin-dev/themes/new-theme/js/app/pages/translations/components/app.vue
  admin-dev/themes/new-theme/js/app/pages/translations/components/header/breadcrumb.vue
  admin-dev/themes/new-theme/js/app/pages/translations/components/header/translations-header.vue
  controllers/admin/AdminLegacyLayoutController.php
Labels: Bug fix, PM ✔️, QA ✔️, develop

#24037 Load Product Page V2 Feature flag at install
  install-dev/data/db_data.sql
  install-dev/upgrade/sql/1.7.8.0.sql
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/FeatureFlagController.php
Labels: Improvement, Must-have, QA ✔️, Wording ✔️, develop

#24045 Register translation wordings for Feature Flag
  app/Resources/translations/default/AdminAdvparametersFeature.xlf
  app/Resources/translations/default/AdminAdvparametersHelp.xlf
  classes/lang/KeysReference/FeatureFlagLang.php
Labels: Must-have, QA ✔️, develop

#24040 Update prestakit to v1.2.3
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
Labels: Improvement, QA ✔️, develop

#24009 Use object mapping in multistore-header js
  admin-dev/themes/new-theme/js/components/components-map.js
  admin-dev/themes/new-theme/js/components/multistore-header.js
Labels: Improvement, QA ✔️, develop

#24012 Remove touchstart even on TouchSpin on FO
  themes/classic/_dev/js/cart.js
  themes/classic/_dev/js/listing.js
  themes/classic/_dev/js/product.js
  themes/classic/_dev/js/selectors.js
Labels: Bug fix, QA ✔️, develop

#24058 Fixed Initialization of GCloud Service Key
  .github/workflows/cron_nightly.yml
Labels: Bug fix, develop

#24061 Nightly : Add manual trigger
  .github/workflows/cron_nightly.yml
Labels: Bug fix, develop

#24062 Nightly : Fix manual trigger
  .github/workflows/cron_nightly.yml
Labels: Bug fix, develop

#24053 Fix file license headers
  classes/webservice/WebserviceSpecificManagementAttachments.php
  src/Adapter/EntityTranslation/DataLangFactory.php
  src/Adapter/EntityTranslation/EntityTranslator.php
  src/Adapter/EntityTranslation/EntityTranslatorFactory.php
  src/Adapter/EntityTranslation/Exception/DataLangClassNameNotFoundException.php
  src/Adapter/EntityTranslation/TabTranslator.php
  src/Core/File/FileUploader.php
  src/Core/File/FileUploaderInterface.php
  src/Core/Translation/EntityTranslatorInterface.php
  src/PrestaShopBundle/Install/EntityLoader/FileLoader.php
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/currency_name.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/data.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Multistore/dropdown.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Multistore/header.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/features.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/suppliers.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Form/features_form_theme.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Form/suppliers_form_theme.html.twig
  src/PrestaShopBundle/Translation/TranslatorInterface.php
  tests/Integration/Core/Form/IdentifiableObject/Handler/FormHandlerFactory.php
  tests/Unit/Adapter/Translations/DataLangFactoryTest.php
Labels: Bug fix, develop

#24067 Nightly : fixed use environment variables
  .github/workflows/cron_nightly.yml
Labels: Bug fix, develop

#24046 Functional tests - Add test change customer service message status
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/02_changeStatus.js
  tests/UI/pages/BO/customerService/customerService/index.js
  tests/UI/pages/BO/customerService/customerService/view.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#24074 Nightly : fixed set env deprecation
  .github/workflows/cron_nightly.yml
Labels: Bug fix, develop

#23968 Display module's multistore compatibility in description
  admin-dev/themes/new-theme/scss/pages/_modules.scss
  classes/module/Module.php
  src/Adapter/Presenter/Module/ModulePresenter.php
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/modal_read_more_content.html.twig
  tests-legacy/Unit/Classes/Module/ModuleCoreTest.php
Labels: Improvement, Must-have, QA ✔️, Wording ✔️, develop

#24024 Add new test "subscribe newsletter"
  tests/UI/campaigns/functional/FO/04_newsletter/01_subscribeNewsletter.js
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/FO/home/index.js
  tests/UI/pages/FO/myAccount/identity.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#24069 Merge 1.7.7.x to develop 15/04/21 [merge]
  src/Adapter/Order/QueryHandler/GetOrderPreviewHandler.php
  src/Core/Domain/Order/QueryResult/OrderPreviewShippingDetails.php
  src/Core/Shop/LogoUploader.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/shipping.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/preview.html.twig
  src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php
  tests/Integration/Behaviour/Features/Context/CarrierFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/ShopFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_address.feature
  tests/Integration/Behaviour/Features/Scenario/Shop/shop.feature
  tests/Integration/Behaviour/behat.yml
  tests/Resources/assets/new_logo.jpg
  tests/UI/campaigns/functional/BO/01_dashboard/01_enableDisableDemoMode.js
  tests/Unit/Core/Domain/Order/QueryResult/OrderPreviewShippingDetailsTest.php
Labels: Improvement, develop

#24013 Add images to combinations list
  admin-dev/themes/new-theme/js/pages/product/edit/combinations-grid-renderer.js
  admin-dev/themes/new-theme/js/pages/product/product-map.js
  src/Adapter/Image/ImageValidator.php
  src/Adapter/Product/Combination/CommandHandler/RemoveAllCombinationImagesHandler.php
  src/Adapter/Product/Combination/CommandHandler/SetCombinationImagesHandler.php
  src/Adapter/Product/Combination/QueryHandler/GetCombinationForEditingHandler.php
  src/Adapter/Product/Combination/QueryHandler/GetEditableCombinationsListHandler.php
  src/Adapter/Product/Combination/Update/CombinationImagesUpdater.php
  src/Adapter/Product/Image/ProductImagePathFactory.php
  src/Adapter/Product/Image/Repository/ProductImageRepository.php
  src/Adapter/Product/Image/Uploader/ProductImageUploader.php
  src/Adapter/Shop/Url/ProductImageFolderProvider.php
  src/Core/Domain/Product/Combination/Command/RemoveAllCombinationImagesCommand.php
  src/Core/Domain/Product/Combination/Command/SetCombinationImagesCommand.php
  src/Core/Domain/Product/Combination/CommandHandler/RemoveAllCombinationImagesHandlerInterface.php
  src/Core/Domain/Product/Combination/CommandHandler/SetCombinationImagesHandlerInterface.php
  src/Core/Domain/Product/Combination/QueryResult/CombinationForEditing.php
  src/Core/Domain/Product/Combination/QueryResult/EditableCombinationForListing.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php
  src/PrestaShopBundle/Resources/config/services/adapter/image.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_combination.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_image.yml
  src/PrestaShopBundle/Resources/config/services/adapter/shop.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Form/combinations_form_theme.html.twig
  tests/Integration/Adapter/Shop/Url/TestProductImageFolderProvider.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/CombinationListingFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/UpdateCombinationImagesFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/update_combination_images.feature
  tests/Integration/Behaviour/behat.yml
  tests/Resources/config/services.yml
  tests/Unit/Adapter/Image/ImageValidatorTest.php
  tests/Unit/Adapter/Product/Image/ProductImagePathFactoryTest.php
  tests/Unit/Adapter/Shop/Url/ProductImageFolderProviderTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/CombinationFormDataProviderTest.php
Labels: Bug fix, Refactoring, develop, migration

#24083 Nightly: disabled manual trigger, added env for nightly & changed cron hour
  .github/workflows/cron_nightly.yml
Labels: Improvement, develop

#24075 Update js documentation for base pages
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/FO/FObasePage.js
  tests/UI/pages/commonPage.js
  tests/UI/pages/install/index.js
Labels: E2E Tests, QA ✔️, Refactoring, develop

#24087 Added unit test on Validate and Behat test on WSKey Management
  classes/Validate.php
  src/Adapter/Validate.php
  tests/Integration/Behaviour/Features/Context/Domain/WebserviceKeyFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Webservice/webservice_key_management.feature
  tests/Unit/Adapter/ValidateTest.php
Labels: Improvement, develop

#24042 Improve multistore dropdown behavior
  src/PrestaShopBundle/Controller/Admin/MultistoreController.php
  src/PrestaShopBundle/Entity/Shop.php
  src/PrestaShopBundle/Resources/config/services/bundle/services.yml
  src/PrestaShopBundle/Resources/views/Admin/Multistore/dropdown.html.twig
  src/PrestaShopBundle/Service/Multistore/CustomizedConfigurationChecker.php
  tests/Unit/PrestaShopBundle/Service/Multistore/CustomizedConfigurationCheckerTest.php
Labels: 1.7.8.0, Improvement, Must-have, QA ✔️, develop

#24049 Export translation catalogues
  admin-dev/themes/new-theme/js/pages/translation-settings/ExportFormFieldToggle.js
  admin-dev/themes/new-theme/js/pages/translation-settings/TranslationSettingsMap.js
  admin-dev/themes/new-theme/js/pages/translation-settings/TranslationSettingsPage.js
  admin-dev/themes/new-theme/scss/pages/_translation_page.scss
  admin-dev/themes/new-theme/scss/theme.scss
  src/Core/Form/ChoiceProvider/TranslationTypeChoiceProvider.php
  src/Core/Translation/Builder/Map/Message.php
  src/Core/Translation/Export/TranslationCatalogueExporter.php
  src/Core/Translation/Storage/Provider/Definition/ProviderDefinitionInterface.php
  src/PrestaShopBundle/Controller/Admin/TranslationsController.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Translations/ExportCataloguesType.php
  src/PrestaShopBundle/Form/Admin/Type/RadioWithChoiceChildrenType.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/translations.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_handler.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/bundle/services.yml
  src/PrestaShopBundle/Resources/config/services/bundle/translation.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Translations/Blocks/export_language.html.twig
  tests/UI/campaigns/functional/BO/11_international/04_translations/03_exportLanguage.js
  tests/UI/pages/BO/international/translations/index.js
  tests/Unit/Core/Translation/Builder/Map/CatalogueTest.php
  tests/Unit/Core/Translation/Builder/Map/DomainTest.php
  tests/Unit/Core/Translation/Builder/Map/MessageTest.php
  tests/Unit/Core/Translation/Builder/TranslationCatalogueBuilderTest.php
  tests/Unit/Core/Translation/Builder/TranslationTreeBuilderTest.php
Labels: BC break, Improvement, QA ✔️, TE, Waiting for wording, develop

#24091 Fix nightly tests 16-06-2021
  tests/UI/pages/BO/catalog/products/add.js
  tests/UI/pages/BO/design/emailThemes/preview.js
  tests/UI/pages/BO/orders/index.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#24086 Delete dashboad UI test
  tests/UI/campaigns/functional/BO/01_dashboard/01_enableDisableDemoMode.js
  tests/UI/pages/BO/dashboard/index.js
Labels: 1.7.7.x, E2E Tests, Refactoring, TE

#24094 Fix OrderState deletion when not in default language context
  controllers/admin/AdminStatusesController.php
Labels: 1.7.7.x, Bug fix, QA ✔️

#24072 Fix category filter not checked
  src/PrestaShopBundle/Controller/Admin/ProductController.php
Labels: 1.7.7.x, Bug fix, QA ✔️

#24110 Fix brand address and supplier tests
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/05_BulkActionsBrandAddresses.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/suppliers/01_CRUDSupplier.js
Labels: E2E Tests, Refactoring, TE, develop

#23858 Fix breadcrumb and h1 on prices drop page
  controllers/front/listing/PricesDropController.php
Labels: Improvement, QA ✔️, Wording ✔️, develop

#24109 Replace "on sale" flag by "price drop"
  src/Adapter/Presenter/Product/ProductLazyArray.php
  src/PrestaShopBundle/Form/Admin/Product/ProductPrice.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/PriceType.php
  tests/Integration/Adapter/Presenter/Product/ProductLazyArrayTest.php
Labels: Improvement, QA ✔️, Wording ✔️, develop

#24114 Fixed PHPDoc
  classes/PaymentModule.php
Labels: Improvement, develop

#24112 Update Ukraine localization pack
  localization/ua.xml
Labels: Improvement, QA ✔️, develop

#22908 Set different 404 strings for different behaviors on classic theme
  themes/classic/templates/catalog/listing/product-list.tpl
  themes/classic/templates/catalog/listing/search.tpl
  themes/classic/templates/errors/404.tpl
  themes/classic/templates/errors/not-found.tpl
Labels: Improvement, QA ✔️, Wording ✔️, develop

#24015 Fix gift not added when changing carrier in Create order page
  admin-dev/themes/new-theme/js/pages/order/create/create-order-page.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  classes/CartRule.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_cart_rules.feature
  tests/Integration/Behaviour/behat.yml
Labels: 1.7.7.x, Bug fix, QA ✔️

#24115 Backport fix on growl messages
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/catalog/products/add.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#23063 Fix typos in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Bug, Improvement, Wording ✔️, develop

#23975 Fix ThemeExporterTest test path
  tests-legacy/PrestaShopBundle/Translation/Exporter/ThemeExporterTest.php
  tests/Unit/PrestaShopBundle/Entity/FeatureFlagTest.php
Labels: Bug fix, develop

#24118 Remove unused table ps_order_slip_detail_tax from install
  install-dev/data/db_structure.sql
Labels: Improvement, QA ✔️, develop

#24132 Update doc for login and payment preferences pages
  tests/UI/pages/BO/login/index.js
  tests/UI/pages/BO/payment/preferences/index.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#24085 Load modules built in translation catalogues
  app/AppKernel.php
  app/config/config.yml
  classes/Context.php
  classes/Language.php
  classes/lang/DataLang.php
  classes/module/Module.php
  config/services/front/services_prod.yml
  src/Adapter/Container/ContainerParametersExtension.php
  src/Adapter/Module/Repository/ModuleRepository.php
  src/Core/Domain/Module/Exception/ModuleException.php
  src/Core/Domain/Module/Exception/ModuleNotFoundException.php
  src/Core/Domain/Module/ValueObject/ModuleId.php
  src/Core/Translation/Storage/Provider/ModuleCatalogueLayersProvider.php
  src/PrestaShopBundle/Kernel/ModuleRepository.php
  src/PrestaShopBundle/Kernel/ModuleRepositoryFactory.php
  src/PrestaShopBundle/Resources/config/services/adapter/module.yml
  src/PrestaShopBundle/Resources/config/services/bundle/routing.yml
  src/PrestaShopBundle/Resources/config/services/bundle/translation.yml
  src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
  src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php
  tests/Integration/Core/Translation/Storage/Provider/ModuleCatalogueLayersProviderTest.php
  tests/Integration/PrestaShopBundle/Translation/Provider/TranslationFinderTest.php
  tests/Resources/modules/xlftranslatedmodule/README.md
  tests/Resources/modules/xlftranslatedmodule/composer.json
  tests/Resources/modules/xlftranslatedmodule/config/routes.yml
  tests/Resources/modules/xlftranslatedmodule/controllers/admin/AdminXlftranslatedmoduleFooController.php
  tests/Resources/modules/xlftranslatedmodule/controllers/front/bar.php
  tests/Resources/modules/xlftranslatedmodule/src/Controller/Admin/ExempleController.php
  tests/Resources/modules/xlftranslatedmodule/translations/fr-FR/ModulesXlftranslatedmoduleAdmin.fr-FR.xlf
  tests/Resources/modules/xlftranslatedmodule/vendor/autoload.php
  tests/Resources/modules/xlftranslatedmodule/vendor/composer/ClassLoader.php
  tests/Resources/modules/xlftranslatedmodule/vendor/composer/autoload_classmap.php
  tests/Resources/modules/xlftranslatedmodule/vendor/composer/autoload_namespaces.php
  tests/Resources/modules/xlftranslatedmodule/vendor/composer/autoload_psr4.php
  tests/Resources/modules/xlftranslatedmodule/vendor/composer/autoload_real.php
  tests/Resources/modules/xlftranslatedmodule/vendor/composer/autoload_static.php
  tests/Resources/modules/xlftranslatedmodule/vendor/composer/installed.json
  tests/Resources/modules/xlftranslatedmodule/views/templates/admin/index.html.twig
  tests/Resources/modules/xlftranslatedmodule/views/templates/admin/someFile.with-things.tpl
  tests/Resources/modules/xlftranslatedmodule/views/templates/front/some_template.tpl
  tests/Resources/modules/xlftranslatedmodule/xlftranslatedmodule.php
  tests/Resources/translations/default/ModulesXlftranslatedmoduleAdmin.xlf
  tests/Resources/translations/fr-FR/ModulesXlftranslatedmoduleAdmin.fr-FR.xlf
Labels: Deprecations, Improvement, Key feature, QA ✔️, Translations, develop

#24126 Add click and wait for download function
  tests/UI/pages/BO/advancedParameters/database/dbBackup/index.js
  tests/UI/pages/BO/advancedParameters/database/sqlManager/index.js
  tests/UI/pages/BO/advancedParameters/import/index.js
  tests/UI/pages/BO/catalog/brands/index.js
  tests/UI/pages/BO/catalog/categories/index.js
  tests/UI/pages/BO/catalog/files/index.js
  tests/UI/pages/BO/catalog/products/add.js
  tests/UI/pages/BO/customers/index.js
  tests/UI/pages/BO/international/translations/index.js
  tests/UI/pages/BO/orders/creditSlips/index.js
  tests/UI/pages/BO/orders/deliverySlips/index.js
  tests/UI/pages/BO/orders/index.js
  tests/UI/pages/BO/orders/invoices/index.js
  tests/UI/pages/BO/orders/view.js
  tests/UI/pages/commonPage.js
Labels: E2E Tests, Refactoring, TE, develop

#24139 Merge 177x to develop 11/04/21 [merge]
  admin-dev/themes/new-theme/js/pages/order/create/create-order-page.js
  classes/CartRule.php
  controllers/admin/AdminStatusesController.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_cart_rules.feature
  tests/Integration/Behaviour/behat.yml
  tests/UI/campaigns/functional/BO/01_dashboard/01_enableDisableDemoMode.js
  tests/UI/pages/BO/dashboard/index.js
Labels: Improvement, develop

#24144 Use different instance name for 1.7.7.x branch
  .travis.yml
Labels: 1.7.7.x, Improvement

#24019 Improve complexity of assignCase var in CMS Controller
  controllers/front/CmsController.php
Labels: QA ✔️, Refactoring, develop

#24125 Some fixes of English mispells
  classes/Search.php
  classes/module/Module.php
Labels: Refactoring, develop

#24113 Improve `OrderSlip::create` code readability
  classes/order/OrderSlip.php
Labels: Improvement, develop

#24127 Add missing param phpdoc in LayoutExtension::getLegacyLayout
  src/PrestaShopBundle/Twig/LayoutExtension.php
Labels: Improvement, develop

#24148 Use base:7.4-apache image for UI tests
  tests/UI/.docker/prestashop/Dockerfile
  tests/UI/.docker/prestashop/Dockerfile-from-git
  tests/UI/docker-compose.ps-git.yml
Labels: 1.7.8.x, E2E Tests, Refactoring

#24146 Nightly : Added branch 1.7.8.x
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/cron_nightly.yml
Labels: Improvement, develop

#21174 Fix color picker template
  admin-dev/themes/default/template/helpers/options/options.tpl
Labels: Bug, QA ✔️, develop

#24027 Improve `Tools::passwdGen` method
  classes/Tools.php
  tests/Unit/Classes/ToolsTest.php
Labels: Refactoring, develop

#24161 Allow all characters when using combination, not only \w
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
Labels: 1.7.7.x, Bug fix, QA ✔️

#23758 Wording corrections
  src/PrestaShopBundle/Form/Admin/Sell/Product/BasicInformationType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Image/ImageDropzoneType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/ShortcutsType.php
Labels: Bug fix, QA ✔️, Wording ✔️, develop, migration

#24151 Replace price drop flag by on sale
  src/Adapter/Presenter/Product/ProductLazyArray.php
  src/PrestaShopBundle/Form/Admin/Product/ProductPrice.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/PriceType.php
  tests/Integration/Adapter/Presenter/Product/ProductLazyArrayTest.php
Labels: 1.7.8.x, Improvement, QA ✔️, Wording ✔️

#24176 Upgrade playwright to 1.8.1
  tests/UI/package-lock.json
  tests/UI/package.json
Labels: 1.7.7.x, E2E Tests, Refactoring, TE

#24196 Update badges in the README following Travis drop
  README.md
Labels: Improvement, develop

#24088 Fix Gift + discount cartRule calculation in cart summary
  classes/Cart.php
  classes/CartRule.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/gift.feature
Labels: 1.7.7.x, Bug fix, QA ✔️

#24163 Refacto / update FO tests pages for the js-doc
  tests/UI/pages/FO/cart/index.js
  tests/UI/pages/FO/category/index.js
  tests/UI/pages/FO/checkout/index.js
  tests/UI/pages/FO/checkout/orderConfirmation.js
  tests/UI/pages/FO/contactUs/index.js
  tests/UI/pages/FO/home/index.js
  tests/UI/pages/FO/login/index.js
  tests/UI/pages/FO/myAccount/add.js
  tests/UI/pages/FO/myAccount/addAddress.js
  tests/UI/pages/FO/myAccount/addresses.js
  tests/UI/pages/FO/myAccount/identity.js
  tests/UI/pages/FO/myAccount/index.js
  tests/UI/pages/FO/myAccount/orderDetails.js
  tests/UI/pages/FO/myAccount/orderHistory.js
  tests/UI/pages/FO/myAccount/vouchers.js
  tests/UI/pages/FO/passwordReminder/index.js
  tests/UI/pages/FO/product/index.js
  tests/UI/pages/FO/searchResults/index.js
  tests/UI/pages/FO/siteMap/index.js
  tests/UI/pages/install/index.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#24129 Fix bug on cover when you select only one image on dropzone of product page v2
  admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue
  admin-dev/themes/new-theme/js/pages/product/components/dropzone/DropzoneWindow.vue
Labels: 1.7.8.x, Bug fix, QA ✔️, migration

#24222 Fix comment
  classes/Category.php
Labels: Documentation, Refactoring, develop

#24225 Fix nightly 177x for 27-04-2021
  tests/UI/pages/BO/orders/index.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#24228 Update version number to 1.7.7.4
  app/AppKernel.php
  install-dev/install_version.php
Labels: 1.7.7.x, Improvement

#24128 Force All shops context for Experimental Features BO page
  controllers/admin/AdminLegacyLayoutController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/FeatureFlagController.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/FeatureFlag/index.html.twig
Labels: 1.7.8.x, Bug fix, QA ✔️, Wording ✔️

#24237 Update smarty from 3.1.34 to 3.1.39
  composer.lock
Labels: 1.7.7.x, Improvement

#23625 Collapse option not working for the the BO category tree
  admin-dev/themes/default/js/tree.js
Labels: 1.7.7.x, Bug fix, QA ✔️

#24187 Add hardcoded translation entry for Experimental Features Navbar link
  app/Resources/translations/default/AdminNavigationMenu.xlf
  classes/lang/KeysReference/TabLang.php
Labels: 1.7.8.x, Bug fix, QA ✔️, Wording ✔️

#24184 Make color required for order state forms
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/OrderReturnStates/OrderReturnStateType.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/OrderStates/OrderStateType.php
Labels: Bug fix, QA ✔️, develop

#24183 Handle info flash messages in Twig layout
  src/PrestaShopBundle/Resources/views/Admin/layout.html.twig
Labels: Bug fix, QA ✔️, develop

#24124 Allow .webp image format in /img/.htaccess.
  img/.htaccess
Labels: Bug fix, Feature, QA ✔️, develop

#24246 Fix nightly tests for 1.7.8.x on 28-04-2021
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/02_sortAndPagination.js
  tests/UI/pages/FO/searchResults/index.js
Labels: 1.7.8.x, E2E Tests, Refactoring, TE

#24160 Add new test contact us from the order confirmation page
  tests/UI/campaigns/functional/FO/05_contactUs/01_checkMailtoLink.js
  tests/UI/campaigns/functional/FO/05_contactUs/02_sendMessageWithCustomer.js
  tests/UI/campaigns/functional/FO/07_search/01_consultAutocompleteList.js
  tests/UI/campaigns/functional/FO/07_search/01_searchProduct.js
  tests/UI/campaigns/functional/FO/08_menuAndNavigation/01_consultCategoriesInHeader.js
  tests/UI/campaigns/functional/FO/09_productPage/01_quickView.js
  tests/UI/campaigns/functional/FO/09_productPage/02_addToCart.js
  tests/UI/campaigns/functional/FO/12_orderConfirmation/05_contactUs.js
  tests/UI/pages/BO/customerService/customerService/index.js
  tests/UI/pages/FO/checkout/orderConfirmation.js
  tests/UI/pages/FO/contactUs/index.js
  tests/UI/pages/FO/myAccount/identity.js
  themes/classic/templates/checkout/order-confirmation.tpl
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#24212 Add an unit test for refreshCaCertFile
  tests/Unit/Adapter/ToolsTest.php
Labels: Improvement, develop

#24262 Add settings for sentiment bot
  .github/config.yml
Labels: Feature, develop

#24252 Add more scripts on package.json
  tests/UI/package.json
Labels: 1.7.8.x, E2E Tests, Refactoring, TE

#24247 Add missing window assignments in javascript default theme
  admin-dev/themes/default/js/bundle/product/default-category.js
  admin-dev/themes/default/js/bundle/product/product-category-tags.js
Labels: 1.7.8.x, Bug fix, QA ✔️

#24272 Fix `dashtrends` module position during install
  src/PrestaShopBundle/Install/Install.php
Labels: 1.7.8.x, Improvement, QA ✔️

#24240 Update js documentation for Credit slips - Delivery slips - Invoices - Shopping carts pages
  tests/UI/pages/BO/orders/creditSlips/index.js
  tests/UI/pages/BO/orders/deliverySlips/index.js
  tests/UI/pages/BO/orders/invoices/index.js
  tests/UI/pages/BO/orders/shoppingCarts/index.js
  tests/UI/pages/BO/orders/shoppingCarts/view.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#24236 Update js documentation for order pages (index - add - view)
  tests/UI/pages/BO/orders/add.js
  tests/UI/pages/BO/orders/index.js
  tests/UI/pages/BO/orders/view.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#24215 Add pagination tests for monitoring page
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/05_sortProductsNoQuantityWithCombination.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/06_sortProductsNoQuantityWithoutCombination.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/07_sortDisabledProducts.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/08_sortProductsWithoutImage.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/09_sortProductsWithoutDescription.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/10_sortProductsWithoutPrice.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortAndPagination/01_emptyCategories.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortAndPagination/02_withCombinationsWithoutQuantities.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortAndPagination/03_withoutCombinationsWithoutQuantities.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortAndPagination/04_disabledProducts.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortAndPagination/05_productsWithoutImage.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortAndPagination/06_productsWithoutDescription.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortAndPagination/07_productsWithoutPrice.js
  tests/UI/pages/BO/catalog/monitoring/index.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#24248 Use combination image instead of the cover image in cart
  themes/classic/templates/checkout/_partials/cart-detailed-product-line.tpl
Labels: 1.7.8.x, Bug fix, QA ✔️

#24155 Making the inline tag working for js and css
  classes/assets/JavascriptManager.php
  classes/assets/StylesheetManager.php
Labels: Bug fix, Key feature, QA ✔️, develop
