Repository PrestaShop/PrestaShop, pull requests merged in 2021-03, with the labels that each got.

#23425 Additional checks for var existence in Admin Features controller
  controllers/admin/AdminFeaturesController.php
Labels: Bug fix, QA ✔️, develop

#23452 Add test - Check product block in order page BO
  tests/UI/campaigns/data/faker/product.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/02_productBlock.js
  tests/UI/pages/BO/catalog/products/add.js
  tests/UI/pages/BO/orders/view.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#23407 Helperlist optimization
  classes/helper/HelperList.php
Labels: Bug fix, QA ✔️, develop

#23386 Introduce UpdateVirtualProductFileCommand
  src/Adapter/File/Uploader/VirtualProductFileUploader.php
  src/Adapter/Product/VirtualProduct/CommandHandler/UpdateVirtualProductFileHandler.php
  src/Adapter/Product/VirtualProduct/Repository/VirtualProductFileRepository.php
  src/Adapter/Product/VirtualProduct/Update/VirtualProductUpdater.php
  src/Core/Domain/Product/VirtualProductFile/Command/UpdateVirtualProductFileCommand.php
  src/Core/Domain/Product/VirtualProductFile/CommandHandler/UpdateVirtualProductFileHandlerInterface.php
  src/Core/Domain/Product/VirtualProductFile/Exception/CannotUpdateVirtualProductFileException.php
  src/PrestaShopBundle/Resources/config/services/adapter/product/_virtual_product.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/VirtualProductFileFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/VirtualProductFile/add_virtual_product_file.feature
  tests/Integration/Behaviour/Features/Scenario/Product/VirtualProductFile/delete_virtual_product_file.feature
  tests/Integration/Behaviour/Features/Scenario/Product/VirtualProductFile/update_virtual_product_file.feature
Labels: Refactoring, develop, migration

#23463 Rename PHPStan exclude class list
  .github/workflows/phpstan/strict-types-for-new-classes-rule-exclusion-list.php
  phpstan.neon.dist
Labels: Improvement, develop

#23146 Adjust default BO theme styles to new-theme styles
  admin-dev/themes/default/package-lock.json
  admin-dev/themes/default/package.json
  admin-dev/themes/default/scss/admin-theme.scss
  admin-dev/themes/default/scss/controllers/_dashboard.scss
  admin-dev/themes/default/scss/modules/_variables.scss
  admin-dev/themes/default/scss/partials/_buttons.scss
  admin-dev/themes/default/scss/partials/_content.scss
  admin-dev/themes/default/scss/partials/_forms.scss
  admin-dev/themes/default/scss/partials/_header.scss
  admin-dev/themes/default/scss/partials/_nav.scss
  admin-dev/themes/default/scss/partials/_switch-btn.scss
  admin-dev/themes/default/scss/partials/_switch.scss
  admin-dev/themes/default/scss/partials/_tables.scss
  admin-dev/themes/default/scss/partials/_toolbar.scss
  admin-dev/themes/default/scss/vendor/bootstrap-sass/_forms.scss
  admin-dev/themes/default/template/controllers/carrier_wizard/helpers/form/form.tpl
  admin-dev/themes/default/template/helpers/form/form.tpl
  admin-dev/themes/default/template/helpers/list/list_content.tpl
Labels: Improvement, QA ✔️, develop

#23467 Little improvements in the README: update FAQ link and add Slack channel
  README.md
Labels: Improvement, develop

#23471 Backport test 'Check footer links'
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/02_CRUDCategoryInBO.js
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/01_viewCustomerService.js
  tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/01_activateMerchandiseReturn.js
  tests/UI/campaigns/functional/BO/08_design/04_pages/02_CRUDPageCategory.js
  tests/UI/campaigns/functional/BO/13_shopParameters/01_general/general/08_enableDisableSuppliers.js
  tests/UI/campaigns/functional/BO/13_shopParameters/01_general/general/09_enableDisableBrands.js
  tests/UI/campaigns/functional/FO/02_headerAndFooter/02_checkLinksInFooter.js
  tests/UI/pages/FO/FObasePage.js
  tests/UI/pages/FO/aboutUs/index.js
  tests/UI/pages/FO/bestSales/index.js
  tests/UI/pages/FO/delivery/index.js
  tests/UI/pages/FO/legalNotice/index.js
  tests/UI/pages/FO/myAccount/creditSlips.js
  tests/UI/pages/FO/newProducts/index.js
  tests/UI/pages/FO/pricesDrop/index.js
  tests/UI/pages/FO/securePayment/index.js
  tests/UI/pages/FO/stores/index.js
  tests/UI/pages/FO/termsAndConditionsOfUse/index.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#23473 Make sure key exists before using it
  classes/tax/TaxCalculator.php
Labels: Bug fix, develop

#23464 Add test 'Filter, sort and pagination shop urls'
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/05_filterSortAndPaginationShopUrls.js
  tests/UI/pages/BO/advancedParameters/multistore/index.js
  tests/UI/pages/BO/advancedParameters/multistore/shop/index.js
  tests/UI/pages/BO/advancedParameters/multistore/url/index.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#23388 Fix product list width on home and search page
  themes/classic/_dev/css/components/featuredproducts.scss
  themes/classic/templates/catalog/_partials/miniatures/product.tpl
Labels: 1.7.7.x, Bug fix, QA ✔️

#23406 Check if id_country exists before using the result of the array
  classes/Product.php
Labels: Bug fix, QA ✔️, develop

#23234 Translations - ThemeExporter : Use array of directories when getting catalog
  src/PrestaShopBundle/Translation/Exporter/ThemeExporter.php
  src/PrestaShopBundle/Translation/Provider/ThemeProvider.php
Labels: Bug fix, QA ✔️, develop

#23409 Allow module exception to be displayed to make debugging easier
  src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php
Labels: Improvement, QA ✔️, develop

#21125 Introduce ContextLoadHelper to load legacy context in Commands
  controllers/admin/DummyAdminController.php
  src/Adapter/LegacyContextLoader.php
  src/PrestaShopBundle/Resources/config/services/adapter/context.yml
  tests/Integration/PrestaShopBundle/Command/LoadLegacyClassesinCommandTest.php
Labels: Feature, QA ✔️, develop

#23490 Use GA ubuntu 18.04 for sanity and integration tests
  .github/workflows/integration.yml
  .github/workflows/php.yml
  .github/workflows/sanity.yml
Labels: Bug fix, Improvement, develop

#23494 Fix click on toggles on nightly develop
  tests/UI/pages/BO/advancedParameters/multistore/add.js
  tests/UI/pages/BO/catalog/attributes/addAttribute.js
  tests/UI/pages/BO/catalog/discounts/add.js
  tests/UI/pages/BO/customerService/merchandiseReturns/index.js
  tests/UI/pages/BO/design/imageSettings/add.js
  tests/UI/pages/BO/international/locations/add.js
  tests/UI/pages/BO/international/locations/countries/add.js
  tests/UI/pages/BO/international/locations/countries/index.js
  tests/UI/pages/BO/international/locations/states/add.js
  tests/UI/pages/BO/international/taxes/taxRules/add.js
  tests/UI/pages/BO/shipping/carriers/add.js
  tests/UI/pages/BO/shopParameters/customerSettings/groups/add.js
  tests/UI/pages/BO/shopParameters/stores/add.js
Labels: E2E Tests, Refactoring, TE, develop

#23020 Add consistency to page blocks in the BO
  admin-dev/themes/new-theme/scss/pages/product/products_catalog.scss
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/ImportPage/import.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/administration.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/performance.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/customer_preferences_general.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_general.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_page.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_pagination.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_stock.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/OrderPreferences/Blocks/order_preferences_general.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/OrderPreferences/Blocks/order_preferences_gift_options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/OrderPreferences/order_preferences.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/customer_preferences.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/maintenance.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/preferences.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/product_preferences.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/MailTheme/Blocks/configuration_form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/MailTheme/Blocks/generate_mails_form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/MailTheme/Blocks/list_mail_theme_layouts.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/MailTheme/Blocks/list_mail_themes.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/MailTheme/Blocks/translate_mails_body_form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Geolocation/index.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Localization/index.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Translations/translations_settings.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Shipping/Preferences/Blocks/shipping_preferences_carrier_options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Shipping/Preferences/Blocks/shipping_preferences_handling.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Shipping/Preferences/preferences.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Delivery/slip.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Invoices/Blocks/generate_by_date.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Invoices/Blocks/generate_by_status.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Invoices/Blocks/invoice_options.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop

#12728 Added the ability to manage and download Attachments via Webservice
  classes/Attachment.php
  classes/Product.php
  classes/webservice/WebserviceRequest.php
  classes/webservice/WebserviceSpecificManagementAttachments.php
  classes/webservice/WebserviceSpecificManagementImages.php
  controllers/front/AttachmentController.php
  src/Core/File/Exception/MaximumSizeExceededException.php
  src/Core/File/FileUploader.php
  src/Core/File/FileUploaderInterface.php
  tests/Unit/Core/File/FileUploaderTest.php
  tests/Unit/phpunit.xml
Labels: Feature, Key feature, QA ✔️, Wording ✔️, develop

#23510 Fix visibility of const OutstandingGridDefinitionFactory::GRID_ID
  src/Core/Grid/Definition/Factory/OutstandingGridDefinitionFactory.php
Labels: Improvement, develop

#23507 Fix search icon height
  admin-dev/themes/default/scss/partials/_header.scss
Labels: Bug fix, QA ✔️, develop

#23519 Fix local sort for shop url on multistore
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/05_filterSortAndPaginationShopUrls.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#23443 Fixed save of translation message
  src/PrestaShopBundle/Service/TranslationService.php
Labels: Bug fix, QA ✔️, develop

#23405 Make sure array are correctly filled in Customer class
  classes/Customer.php
Labels: Bug fix, QA ✔️, develop

#23489 Improve integration.yml GA file name
  .github/workflows/integration.yml
Labels: Improvement, develop

#23503 Add test 'Check links in header page FO'
  tests/UI/campaigns/data/demo/categories.js
  tests/UI/campaigns/functional/FO/02_headerAndFooter/01_checkLinksInHeader.js
  tests/UI/campaigns/functional/FO/06_search/01_searchProduct.js
  tests/UI/campaigns/functional/FO/07_menuAndNavigation/01_consultCategoriesInHeader.js
  tests/UI/pages/FO/FObasePage.js
  tests/UI/pages/FO/home/index.js
  tests/UI/pages/FO/searchResults/index.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#23522 Introduce phpstan for prestashop v1.1 with 3 new Rules: ClassConstantsMustHaveVisibilityRule, UseTypeHintForNewMethodsRule, UseTypedReturnForNewMethodsRule
  .github/workflows/phpstan/return-types-for-new-class-methods-rule-exclusion-list.php
  .github/workflows/phpstan/type-hint-for-new-class-methods-rule-exclusion-list.php
  composer.lock
  phpstan.neon.dist
Labels: CI/CD, Feature, develop

#23539 Disable temporarily phpstan extension
  phpstan.neon.dist
Labels: Bug fix, develop

#18396 Import source files of the UIKit instead of dist files to use prestakit variables
  admin-dev/themes/new-theme/scss/components/_notifications.scss
  admin-dev/themes/new-theme/scss/config/_settings.scss
  admin-dev/themes/new-theme/scss/pages/_translation_page.scss
  admin-dev/themes/new-theme/scss/pages/orders/_orders_main.scss
  admin-dev/themes/new-theme/scss/pages/orders/_orders_view.scss
  admin-dev/themes/new-theme/scss/theme.scss
Labels: Improvement, QA ✔️, develop

#23554 Click on logo link on checkout page to go to home page
  tests/UI/pages/FO/FObasePage.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#23137 Trigger change() on attribute_priceTE when clicking save button to handle broken localization packs.
  admin-dev/themes/default/js/bundle/product/form.js
  admin-dev/themes/default/js/bundle/product/product-combinations.js
  classes/Combination.php
  src/PrestaShopBundle/Form/Admin/Product/ProductCombination.php
Labels: Bug, QA ✔️, develop

#23541 BO / Cart rule / neutralize titles
  admin-dev/themes/default/template/controllers/cart_rules/product_rule_itemlist.tpl
Labels: Bug fix, QA ✔️, develop

#23566 Use correct protocol in install.txt
  INSTALL.txt
Labels: Improvement, develop

#23564 Merge 1.7.7.x into develop
  classes/order/OrderState.php
  controllers/admin/AdminStatusesController.php
  tests/UI/campaigns/data/demo/categories.js
  tests/UI/campaigns/data/faker/product.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/02_productBlock.js
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/04_quantityDiscountsBasedOn.js
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/08_defaultPackStockManagement.js
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/01_seoAndUrls/02_setUpUrls/04_enableDisableAccentedURL.js
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/05_filterSortAndPaginationShopUrls.js
  tests/UI/campaigns/functional/FO/02_headerAndFooter/01_checkLinksInHeader.js
  tests/UI/campaigns/functional/FO/06_search/01_searchProduct.js
  tests/UI/campaigns/functional/FO/07_menuAndNavigation/01_consultCategoriesInHeader.js
  tests/UI/campaigns/functional/FO/08_productPage/01_quickView.js
  tests/UI/pages/BO/advancedParameters/multistore/index.js
  tests/UI/pages/BO/advancedParameters/multistore/shop/index.js
  tests/UI/pages/BO/advancedParameters/multistore/url/index.js
  tests/UI/pages/BO/catalog/products/add.js
  tests/UI/pages/BO/orders/view.js
  tests/UI/pages/FO/FObasePage.js
  tests/UI/pages/FO/home/index.js
  tests/UI/pages/FO/searchResults/index.js
  themes/classic/_dev/css/components/featuredproducts.scss
  themes/classic/templates/catalog/_partials/miniatures/product.tpl
Labels: Improvement, develop

#23525 Problem with PHP7.4 with Customer::getCurrentCountry and Tab management
  classes/Customer.php
  classes/Tab.php
  classes/controller/AdminController.php
Labels: Bug fix, QA ✔️, develop

#23127 Simplify 'Add a theme' form
  src/Core/Translation/Finder/TranslationFinder.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php
  src/PrestaShopBundle/Form/Admin/Improve/Design/Theme/ImportThemeType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Theme/import.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: BC break, QA ✔️, Refactoring, Wording ✔️, develop, migration

#23590 Update phpstan-prestashop to 1.1.1, restore the usage of the extension
  composer.lock
  phpstan.neon.dist
Labels: CI/CD, Feature, develop

#23585 Fix nightly 09/03/2021
  tests/UI/campaigns/data/demo/stores.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#23527 BO / Cart rule / Improve product selection
  admin-dev/themes/default/scss/partials/_commons.scss
  admin-dev/themes/default/template/controllers/cart_rules/product_rule.tpl
  admin-dev/themes/default/template/controllers/cart_rules/product_rule_itemlist.tpl
Labels: Improvement, QA ✔️, develop

#22438 Make root category of a shop non editable
  classes/Category.php
  src/Adapter/Category/CommandHandler/EditCategoryHandler.php
  src/Adapter/Category/CommandHandler/EditRootCategoryHandler.php
  src/Adapter/Category/QueryHandler/GetCategoryForEditingHandler.php
  src/Core/Domain/Category/Exception/CannotEditRootCategoryException.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/breadcrumb.html.twig
  tests/Integration/Adapter/Category/QueryHandler/EditRootCategoryHandlerTest.php
  tests/Integration/Adapter/Category/QueryHandler/GetCategoryForEditingHandlerTest.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#23542 Add test 'Check product details in product page FO'
  tests/UI/campaigns/data/demo/products.js
  tests/UI/campaigns/functional/BO/03_catalog/01_products/04_previewProductFromList.js
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/04_quantityDiscountsBasedOn.js
  tests/UI/campaigns/functional/FO/08_productPage/01_quickView.js
  tests/UI/campaigns/functional/FO/08_productPage/02_addToCart.js
  tests/UI/campaigns/sanity/02_productsBO/02_CRUDStandardProductInBO.js
  tests/UI/campaigns/sanity/02_productsBO/03_CRUDStandardProductWithCombinationsInBO.js
  tests/UI/campaigns/sanity/04_catalogFO/02_checkProduct.js
  tests/UI/pages/FO/cart/index.js
  tests/UI/pages/FO/product/index.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#23594 Add missing functions on develop to fix the nightly
  tests/UI/pages/FO/FObasePage.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#23568 Fix logout and hover colors on profile pan responsive
  admin-dev/themes/default/scss/partials/_header.scss
  admin-dev/themes/default/template/header.tpl
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
  admin-dev/themes/new-theme/template/components/layout/employee_dropdown.tpl
Labels: Bug fix, QA ✔️, UX ✔️, develop

#23611 Fix nightly 11-03-2020
  tests/UI/pages/BO/catalog/products/add.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#23613 Bump version to 1.7.7.3
  app/AppKernel.php
  install-dev/install_version.php
Labels: 1.7.7.x, Improvement

#23502 Harmonize wordings of notifications pan
  admin-dev/themes/default/template/header.tpl
  classes/controller/AdminController.php
Labels: Bug fix, QA ✔️, develop

#23615 Fix typo in LayoutExtension
  src/PrestaShopBundle/Twig/LayoutExtension.php
Labels: Improvement, develop

#23614 Add test 'Quick edit and bulk actions shop URLs'
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/06_quickEditAndbulkActionsShopUrls.js
  tests/UI/pages/BO/advancedParameters/multistore/url/index.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#23608 Fix shadow of right sidebar on responsive
  admin-dev/themes/new-theme/scss/components/layout/_right-sidebar.scss
Labels: Bug fix, QA ✔️, develop

#23475 Introduce javascript pagination component for combinations
  admin-dev/themes/new-theme/js/components/pagination/dynamic-paginator.js
  admin-dev/themes/new-theme/js/fos_js_routes.json
  admin-dev/themes/new-theme/js/pages/product/edit/combinations-grid-renderer.js
  admin-dev/themes/new-theme/js/pages/product/edit/combinations-manager.js
  admin-dev/themes/new-theme/js/pages/product/edit/index.js
  admin-dev/themes/new-theme/js/pages/product/edit/product-partial-updater.js
  admin-dev/themes/new-theme/js/pages/product/product-map.js
  admin-dev/themes/new-theme/js/pages/product/services/combinations-service.js
  admin-dev/themes/new-theme/scss/pages/product/product_page.scss
  src/Adapter/Product/Combination/QueryHandler/GetEditableCombinationsListHandler.php
  src/Core/Domain/Product/Combination/Query/GetEditableCombinationsList.php
  src/Core/Domain/Product/Supplier/Command/SetProductSuppliersCommand.php
  src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationItemType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationListType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/RedirectOptionType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/product_v2/combination.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/product_v2/product.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Common/javascript_pagination.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/combinations.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/tabs.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Form/combinations_form_theme.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Tabs/combinations.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/edit.html.twig
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/CombinationListingFeatureContext.php
Labels: Refactoring, develop, migration

#23622 Fix click on behavior input on Add product page
  tests/UI/pages/BO/catalog/products/add.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#23624 Fix wait after choosing combination
  tests/UI/pages/FO/product/index.js
Labels: 1.7.7.x, E2E Tests, Refactoring, TE

#23627 Add test - Search product and check autocomplete list on FO
  tests/UI/campaigns/functional/FO/06_search/01_consultAutocompleteList.js
  tests/UI/campaigns/functional/FO/06_search/01_searchProduct.js
  tests/UI/pages/BO/shopParameters/search/index.js
  tests/UI/pages/FO/FObasePage.js
  tests/UI/pages/FO/searchResults/index.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#23584 Handle searchProduct method when in another shop context
  controllers/admin/AdminCartRulesController.php
Labels: 1.7.7.x, Bug fix, QA ✔️

#8738 FO Don't display shipping method for virtual cart
  themes/classic/templates/checkout/_partials/order-final-summary.tpl
Labels: Bug fix, QA ✔️, develop

#23601 Take customization into account when updating quantity
  admin-dev/themes/new-theme/js/pages/order/view/order-prices-refresher.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  src/Adapter/Order/OrderProductQuantityUpdater.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
Labels: 1.7.7.x, Bug fix, QA ✔️

#20737 Migrate carriers listing
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/js/pages/carrier/index.js
  admin-dev/themes/new-theme/scss/components/_showcase-card.scss
  admin-dev/themes/new-theme/static/helper-card/carrier@3x.png
  src/Adapter/Carrier/AbstractCarrierHandler.php
  src/Adapter/Carrier/CarrierModuleAdviceAlertChecker.php
  src/Adapter/Carrier/CarrierThumbnailLogoProvider.php
  src/Adapter/Carrier/CommandHandler/BulkDeleteCarrierHandler.php
  src/Adapter/Carrier/CommandHandler/BulkToggleCarrierStatusHandler.php
  src/Adapter/Carrier/CommandHandler/DeleteCarrierHandler.php
  src/Adapter/Carrier/CommandHandler/ToggleCarrierIsFreeHandler.php
  src/Adapter/Carrier/CommandHandler/ToggleCarrierStatusHandler.php
  src/Core/Domain/Carrier/Command/BulkDeleteCarrierCommand.php
  src/Core/Domain/Carrier/Command/BulkToggleCarrierStatusCommand.php
  src/Core/Domain/Carrier/Command/DeleteCarrierCommand.php
  src/Core/Domain/Carrier/Command/ToggleCarrierIsFreeCommand.php
  src/Core/Domain/Carrier/Command/ToggleCarrierStatusCommand.php
  src/Core/Domain/Carrier/CommandHandler/BulkDeleteCarrierHandlerInterface.php
  src/Core/Domain/Carrier/CommandHandler/BulkToggleCarrierStatusHandlerInterface.php
  src/Core/Domain/Carrier/CommandHandler/DeleteCarrierHandlerInterface.php
  src/Core/Domain/Carrier/CommandHandler/ToggleCarrierIsFreeHandlerInterface.php
  src/Core/Domain/Carrier/CommandHandler/ToggleCarrierStatusHandlerInterface.php
  src/Core/Domain/Carrier/Exception/CannotDeleteCarrierException.php
  src/Core/Domain/Carrier/Exception/CannotToggleCarrierIsFreeStatusException.php
  src/Core/Domain/Carrier/Exception/CannotToggleCarrierStatusException.php
  src/Core/Domain/Carrier/Exception/CarrierConstraintException.php
  src/Core/Domain/Carrier/Exception/CarrierException.php
  src/Core/Domain/Carrier/Exception/CarrierNotFoundException.php
  src/Core/Domain/Carrier/ValueObject/CarrierId.php
  src/Core/Domain/ShowcaseCard/ConfigurationMap.php
  src/Core/Domain/ShowcaseCard/ValueObject/ShowcaseCard.php
  src/Core/Grid/Data/Factory/CarrierGridDataFactory.php
  src/Core/Grid/Definition/Factory/CarrierGridDefinitionFactory.php
  src/Core/Grid/Query/CarrierQueryBuilder.php
  src/Core/Search/Filters/CarrierFilters.php
  src/PrestaShopBundle/Controller/Admin/Improve/Shipping/CarriersController.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/_improve.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/shipping/_shipping.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/shipping/carriers.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/shipping/preferences.yml
  src/PrestaShopBundle/Resources/config/services/adapter/carrier.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_data_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_position_definition_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/util/helper_card.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/Shipping/Carriers/Blocks/information_block.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Shipping/Carriers/Blocks/showcase_card.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Shipping/Carriers/index.html.twig
  tests-legacy/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
  tests/Integration/PrestaShopBundle/Routing/Converter/LegacyUrlConverterTest.php
Labels: QA ✔️, Refactoring, Wording ✔️, develop, migration

#23668 Product form adaptation
  admin-dev/themes/new-theme/js/pages/product/edit/index.js
  src/PrestaShopBundle/Form/Admin/Sell/Product/BasicInformationType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/FeatureValueListener.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/ProductTypeListener.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/ProductFormType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_builder.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/tabs.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Tabs/options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/edit.html.twig
  tests/Integration/PrestaShopBundle/Form/EventListener/FeatureValueListenerTest.php
  tests/Integration/PrestaShopBundle/Form/EventListener/FormListenerTestCase.php
  tests/Integration/PrestaShopBundle/Form/EventListener/ProductTypeListenerTest.php
Labels: Feature, Wording ✔️, develop, migration

#23630 Fix "Trying to access array offset on value of type ..." error for legacy creation forms
  admin-dev/themes/default/template/helpers/form/form.tpl
Labels: Bug fix, QA ✔️, develop

#23679 Add test 'Check mailto link on contact us page'
  tests/UI/campaigns/functional/FO/04_contactUs/01_checkMailtoLink.js
  tests/UI/pages/FO/contactUs/index.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#23650 Introduce Experimental Feature data model
  src/PrestaShopBundle/Entity/FeatureFlag.php
  tests/Integration/Behaviour/Features/Context/FeatureFlagFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/FeatureFlag/feature_flag.feature
  tests/Integration/Behaviour/behat.yml
  tests/Unit/PrestaShopBundle/Entity/FeatureFlagTest.php
Labels: Feature, develop

#23674 Change functions and add more comments on install page
  tests/UI/campaigns/sanity/01_installShop/01_installShop.js
  tests/UI/pages/install/index.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#23678 Update the version of the UIKit to 1.2.2
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
Labels: Bug fix, QA ✔️, develop

#22942 Add html validation to radio buttons on category tree
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/material.html.twig
Labels: Bug fix, QA ✔️, Waiting for author, develop

#22677 Use context langId if order langId not available
  classes/Cart.php
  classes/ObjectModel.php
  classes/PaymentModule.php
  classes/order/OrderCarrier.php
  src/Adapter/Cart/CommandHandler/AddCartRuleToCartHandler.php
  src/Adapter/Cart/CommandHandler/RemoveProductFromCartHandler.php
  src/Adapter/Cart/CommandHandler/SendCartToCustomerHandler.php
  src/Adapter/Cart/CommandHandler/UpdateCartCarrierHandler.php
  src/Adapter/Cart/QueryHandler/GetCartForOrderCreationHandler.php
  src/Adapter/CustomerService/CommandHandler/AddOrderCustomerMessageHandler.php
  src/Adapter/Order/CommandHandler/AbstractOrderCommandHandler.php
  src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php
  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
  src/Adapter/Order/CommandHandler/BulkChangeOrderStatusHandler.php
  src/Adapter/Order/CommandHandler/DuplicateOrderCartHandler.php
  src/Adapter/Order/CommandHandler/ResendOrderEmailHandler.php
  src/Adapter/Order/CommandHandler/SendProcessOrderEmailHandler.php
  src/Adapter/Order/CommandHandler/UpdateOrderShippingDetailsHandler.php
  src/Adapter/Order/CommandHandler/UpdateOrderStatusHandler.php
  src/Adapter/Order/OrderAmountUpdater.php
  src/Adapter/Order/OrderDetailUpdater.php
  src/Adapter/Order/OrderProductQuantityUpdater.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Order/QueryHandler/GetOrderPreviewHandler.php
  src/Adapter/Order/QueryHandler/GetOrderProductsForViewingHandler.php
  src/Adapter/Order/Refund/OrderSlipCreator.php
  src/Adapter/Order/Refund/VoucherGenerator.php
  src/Adapter/Presenter/Order/OrderLazyArray.php
  tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderCartFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Context/LanguageFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
Labels: 1.7.7.x, Bug, QA ✔️

#23693 Add test 'Send message from contact us page with customer logged in'
  tests/UI/campaigns/data/faker/contactUs.js
  tests/UI/campaigns/functional/FO/04_contactUs/02_sendMessageWithCustomer.js
  tests/UI/pages/FO/contactUs/index.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#23694 Do not allow empty payment_method
  src/PrestaShopBundle/Form/Admin/Sell/Order/OrderPaymentType.php
Labels: 1.7.7.x, Bug fix, QA ✔️

#23688 Fix color style of add to cart modal on FO
  themes/classic/_dev/css/partials/_commons.scss
  themes/classic/assets/css/theme.css
Labels: 1.7.7.x, Bug fix, QA ✔️

#23667 Product brand integration
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/OptionsCommandBuilder.php
  src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/ManufacturerType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/OptionsType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/ProductFormType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/tabs.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Tabs/basic.html.twig
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductOptionsCommandBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProviderTest.php
Labels: Feature, Waiting for wording, develop, migration

#23689 Change install demo datas string on install
  install-dev/theme/views/configure.php
Labels: Improvement, QA ✔️, Waiting for wording, develop

#23725 Build assets for 1.7.7.3
  admin-dev/themes/default/package-lock.json
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/public/category.bundle.js
  admin-dev/themes/new-theme/public/cldr.bundle.js
  admin-dev/themes/new-theme/public/cms_page.bundle.js
  admin-dev/themes/new-theme/public/cms_page_form.bundle.js
  admin-dev/themes/new-theme/public/currency_form.bundle.js
  admin-dev/themes/new-theme/public/improve_design_positions.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/manufacturer.bundle.js
  admin-dev/themes/new-theme/public/meta.bundle.js
  admin-dev/themes/new-theme/public/module.bundle.js
  admin-dev/themes/new-theme/public/module_card.bundle.js
  admin-dev/themes/new-theme/public/order.bundle.js
  admin-dev/themes/new-theme/public/order_create.bundle.js
  admin-dev/themes/new-theme/public/order_message.bundle.js
  admin-dev/themes/new-theme/public/order_message_form.bundle.js
  admin-dev/themes/new-theme/public/payment_preferences.bundle.js
  admin-dev/themes/new-theme/public/product_page.bundle.js
  admin-dev/themes/new-theme/public/product_preferences.bundle.js
  admin-dev/themes/new-theme/public/profiles.bundle.js
  admin-dev/themes/new-theme/public/sql_manager.bundle.js
  admin-dev/themes/new-theme/public/stock.bundle.js
  admin-dev/themes/new-theme/public/supplier.bundle.js
  admin-dev/themes/new-theme/public/supplier_form.bundle.js
  admin-dev/themes/new-theme/public/tax.bundle.js
  admin-dev/themes/new-theme/public/tax_rules_group.bundle.js
  admin-dev/themes/new-theme/public/theme.css
  admin-dev/themes/new-theme/public/themes.bundle.js
  admin-dev/themes/new-theme/public/translation_settings.bundle.js
  admin-dev/themes/new-theme/public/translations.bundle.js
  admin-dev/themes/new-theme/public/webservice.bundle.js
  themes/classic/_dev/package-lock.json
  themes/package-lock.json
Labels: 1.7.7.x, Bug fix

#23722 Add missing license headers
  tests/Unit/Core/Domain/Order/Payment/Command/AddPaymentCommandTest.php
  tests/Unit/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewingTest.php
  tests/Unit/Core/Domain/Order/QueryResult/OrderPreviewInvoiceDetailsTest.php
  tests/Unit/Core/Domain/Order/QueryResult/OrderPreviewShippingDetailsTest.php
  tests/Unit/Core/Domain/Order/QueryResult/OrderShippingAddressForViewingTest.php
Labels: 1.7.7.x, Bug fix

#23543 BO password reset with maildev
  admin-dev/themes/default/template/controllers/login/content.tpl
  tests/UI/campaigns/functional/BO/00_login/01_passwordReminder.js
  tests/UI/campaigns/functional/FO/01_login/01_passwordReminder.js
  tests/UI/package-lock.json
  tests/UI/pages/BO/login/index.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#23740 Create message with only 35 characters for contact us test
  tests/UI/campaigns/data/faker/contactUs.js
  tests/UI/campaigns/functional/FO/04_contactUs/02_sendMessageWithCustomer.js
Labels: 1.7.7.x, E2E Tests, Refactoring, TE

#23684 Add sortable feature to product page v2 images dropzone
  admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue
  admin-dev/themes/new-theme/js/pages/product/services/images.js
  src/Adapter/Product/Image/CommandHandler/UpdateProductImageHandler.php
  src/Adapter/Product/Image/Update/ProductImageUpdater.php
  src/Core/Domain/Product/Image/Command/UpdateProductImageCommand.php
  src/Core/Domain/Product/Image/Exception/CannotUpdateProductImageException.php
  src/Core/Form/IdentifiableObject/DataHandler/ProductImageFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/ProductImageFormDataProvider.php
  src/Core/Grid/Position/PositionDefinition.php
  src/Core/Grid/Position/PositionDefinitionInterface.php
  src/Core/Grid/Position/UpdateHandler/DoctrinePositionUpdateHandler.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ImageController.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Image/ProductImageType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/product_v2/image.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_image.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_position_definition_factory.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Image/update_image.feature
Labels: BC break, Feature, Waiting for QA, develop

#23752 Fixes issue with credit slip not downloading
  classes/pdf/HTMLTemplateOrderSlip.php
Labels: Bug fix, QA ✔️, develop, migration

#23789 Fix `Validate::isArrayWithIds` method issue
  classes/Validate.php
  tests-legacy/Unit/Classes/ValidateCoreTest.php
Labels: Bug fix, QA ✔️, develop

#23675 Add remove feature on product page v2
  admin-dev/themes/new-theme/js/fos_js_routes.json
  admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue
  admin-dev/themes/new-theme/js/pages/product/components/dropzone/DropzoneWindow.vue
  admin-dev/themes/new-theme/js/pages/product/services/images.js
  admin-dev/themes/new-theme/js/vue/plugins/vue-i18n/replace-formatter.js
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ImageController.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Image/ImageDropzoneType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/product_v2/image.yml
Labels: Refactoring, Wording ✔️, develop

#23811 Remove instock
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig
Labels: Bug fix, QA ✔️, develop

#23802 Fix jquery selector warning with ps_currencyselector
  themes/classic/modules/ps_currencyselector/ps_currencyselector.tpl
Labels: 1.7.7.x, Bug fix, QA ✔️, Waiting for author

#23780 Delete unused functions on common page
  tests/UI/pages/BO/international/localization/index.js
  tests/UI/pages/commonPage.js
  tests/UI/pages/install/index.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#23778 Wrap playwright function waitForSelector
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/advancedParameters/database/dbBackup/index.js
  tests/UI/pages/BO/advancedParameters/multistore/url/index.js
  tests/UI/pages/BO/catalog/attributes/index.js
  tests/UI/pages/BO/catalog/categories/index.js
  tests/UI/pages/BO/catalog/discounts/catalogPriceRules/index.js
  tests/UI/pages/BO/catalog/discounts/index.js
  tests/UI/pages/BO/catalog/stocks/index.js
  tests/UI/pages/BO/catalog/stocks/movements/index.js
  tests/UI/pages/BO/customers/index.js
  tests/UI/pages/BO/design/imageSettings/index.js
  tests/UI/pages/BO/international/locations/countries/index.js
  tests/UI/pages/BO/international/locations/index.js
  tests/UI/pages/BO/international/locations/states/index.js
  tests/UI/pages/BO/international/taxes/taxRules/index.js
  tests/UI/pages/BO/international/translations/index.js
  tests/UI/pages/BO/orders/add.js
  tests/UI/pages/BO/orders/index.js
  tests/UI/pages/BO/orders/shoppingCarts/index.js
  tests/UI/pages/BO/payment/preferences/index.js
  tests/UI/pages/BO/shipping/carriers/index.js
  tests/UI/pages/BO/shopParameters/customerSettings/groups/add.js
  tests/UI/pages/BO/shopParameters/customerSettings/groups/index.js
  tests/UI/pages/BO/shopParameters/customerSettings/titles/add.js
  tests/UI/pages/BO/shopParameters/customerSettings/titles/index.js
  tests/UI/pages/BO/shopParameters/orderSettings/statuses/index.js
  tests/UI/pages/BO/shopParameters/search/index.js
  tests/UI/pages/BO/shopParameters/search/tags/index.js
  tests/UI/pages/BO/shopParameters/stores/index.js
  tests/UI/pages/BO/shopParameters/trafficAndSeo/searchEngines/index.js
  tests/UI/pages/FO/product/index.js
  tests/UI/pages/FO/searchResults/index.js
  tests/UI/pages/commonPage.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#22228 Fixed Update Quantity in an order in multishop context
  classes/module/Module.php
  src/Adapter/Cart/AbstractCartHandler.php
  src/Adapter/Cart/CommandHandler/UpdateCartCarrierHandler.php
  src/Adapter/ContextStateManager.php
  src/Adapter/LegacyContext.php
  src/Adapter/Order/CommandHandler/AbstractOrderCommandHandler.php
  src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php
  src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php
  src/Adapter/Product/QueryHandler/SearchProductsHandler.php
  src/PrestaShopBundle/Resources/config/services/adapter/common.yml
  src/PrestaShopBundle/Resources/config/services/adapter/order.yml
  tests-legacy/Unit/ContextMocker.php
  tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php
  tests/Integration/Behaviour/Features/Context/CustomerFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/AbstractDomainFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CommonDomainFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CurrencyFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Currency/currency_data.feature
  tests/Integration/Behaviour/Features/Scenario/Currency/currency_management.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_multi_shop.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_shipping.feature
  tests/Integration/Behaviour/behat.yml
  tests/Unit/Adapter/ContextStateManagerTest.php
Labels: 1.7.7.x, BC break, Bug fix, QA ✔️, Waiting for author

#23691 Fix notification refresh on migrated pages
  admin-dev/themes/new-theme/js/notifications.js
  admin-dev/themes/new-theme/public/main.bundle.js
Labels: 1.7.7.x, Bug fix, QA ✔️

#20929 Avoid loading all combinations in memory when only one is needed
  classes/Product.php
  controllers/front/ProductController.php
Labels: Improvement, QA ✔️, develop

#22290 Simplify product isNew() query
  classes/Product.php
Labels: Improvement, QA ✔️, develop

#21652 Simplify database settings, DB Backup and add new database query forms
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Backup/BackupOptionsType.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/RequestSql/SqlRequestSettingsType.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/RequestSql/SqlRequestType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Backup/Blocks/options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/RequestSql/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/RequestSql/Blocks/settings_panel.html.twig
Labels: QA ✔️, Refactoring, Wording ✔️, develop

#22152 No unit of value for the txt files attached to a product
  classes/Tools.php
Labels: Improvement, PM ✔️, QA ✔️, Wording ✔️, develop

#22999 Add eslint on the default BO theme
  .github/workflows/lint.yml
  admin-dev/themes/default/.eslintignore
  admin-dev/themes/default/.eslintrc.js
  admin-dev/themes/default/js/admin-theme.js
  admin-dev/themes/default/js/bundle/admin_parameters/performancePage.js
  admin-dev/themes/default/js/bundle/admin_parameters/performancePageUI.js
  admin-dev/themes/default/js/bundle/category-tree.js
  admin-dev/themes/default/js/bundle/components/navbar-transition-handler.js
  admin-dev/themes/default/js/bundle/default.js
  admin-dev/themes/default/js/bundle/modal-confirmation.js
  admin-dev/themes/default/js/bundle/module/loader.js
  admin-dev/themes/default/js/bundle/module/module.js
  admin-dev/themes/default/js/bundle/module/module_card.js
  admin-dev/themes/default/js/bundle/pagination.js
  admin-dev/themes/default/js/bundle/plugins/jquery.pstagger.js
  admin-dev/themes/default/js/bundle/product/catalog.js
  admin-dev/themes/default/js/bundle/product/default-category.js
  admin-dev/themes/default/js/bundle/product/form.js
  admin-dev/themes/default/js/bundle/product/product-category-tags.js
  admin-dev/themes/default/js/bundle/product/product-combinations.js
  admin-dev/themes/default/js/bundle/product/product-manufacturer.js
  admin-dev/themes/default/js/bundle/product/product-related.js
  admin-dev/themes/default/js/bundle/right-sidebar.js
  admin-dev/themes/default/js/bundle/utils/animations.js
  admin-dev/themes/default/js/calendar.js
  admin-dev/themes/default/js/date-range-picker.js
  admin-dev/themes/default/js/help.js
  admin-dev/themes/default/js/jquery.fileupload-image.js
  admin-dev/themes/default/js/jquery.fileupload-process.js
  admin-dev/themes/default/js/jquery.fileupload-validate.js
  admin-dev/themes/default/js/jquery.fileupload.js
  admin-dev/themes/default/js/jquery.iframe-transport.js
  admin-dev/themes/default/js/modernizr-loads.js
  admin-dev/themes/default/js/theme.js
  admin-dev/themes/default/js/tree.js
  admin-dev/themes/default/package-lock.json
  admin-dev/themes/default/package.json
  admin-dev/themes/default/postcss.config.js
  admin-dev/themes/default/template/controllers/cart_rules/form.js
  admin-dev/themes/default/webpack.config.js
Labels: Improvement, QA ✔️, develop

#23298 Add TinyMCE mobile theme in the BO
  admin-dev/themes/new-theme/js/components/tinymce-editor.js
  js/admin/tinymce.inc.js
  js/tiny_mce/skins/lightgray/content.mobile.min.css
  js/tiny_mce/skins/lightgray/fonts/tinymce-mobile.woff
  js/tiny_mce/skins/lightgray/img/anchor.gif
  js/tiny_mce/skins/lightgray/img/loader.gif
  js/tiny_mce/skins/lightgray/img/object.gif
  js/tiny_mce/skins/lightgray/img/trans.gif
  js/tiny_mce/skins/lightgray/skin.mobile.min.css
  js/tiny_mce/themes/mobile/theme.js
  js/tiny_mce/themes/mobile/theme.min.js
Labels: Improvement, Key feature, QA ✔️, develop

#23818 Fixed legacy "view my shop" link when multistore is not used
  admin-dev/themes/new-theme/template/layout.tpl
  controllers/admin/AdminLegacyLayoutController.php
  tests-legacy/PrestaShopBundle/Controller/ControllerTest.php
Labels: Bug fix, QA ✔️, develop

#22309 Fixed unclear error message during api/products/image requests with improper input data
  classes/webservice/WebserviceSpecificManagementImages.php
Labels: Improvement, QA ✔️, develop

#23232 Add custom tinymce configuration on migrated pages
  admin-dev/themes/new-theme/js/components/tinymce-editor.js
Labels: Bug fix, QA ✔️, develop

#23579 Remove useless code since migration to BO new-theme
  js/admin.js
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
Labels: QA ✔️, Refactoring, develop

#23583 Remove unused bootstrap classes causing side effects on nav
  admin-dev/themes/default/template/nav.tpl
Labels: Bug fix, QA ✔️, develop
