Repository PrestaShop/PrestaShop, pull requests merged in 2021-06, with the labels that each got.

#24717 Update native modules
  composer.lock
Labels: 1.7.7.x, Improvement

#24712 1780 - Changelog
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: 1.7.8.x, Improvement

#24718 The addProductNewInvoiceInfo is not displayed when creating new invoice
  admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js
Labels: 1.7.8.x, Bug fix, QA ✔️

#24594 Fix order create page on product qty update
  admin-dev/themes/new-theme/js/pages/order/create/product-manager.js
Labels: 1.7.8.x, Bug fix, QA ✔️

#24696 Fix delete modal translation
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/typeahead.html.twig
Labels: 1.7.8.x, Bug fix, QA ✔️, Wording ✔️

#24720 Add selectors for view customer service page and fix autocomplete test
  admin-dev/themes/default/template/controllers/customer_threads/helpers/view/view.tpl
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/01_viewCustomerService.js
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/03_contactOptions.js
  tests/UI/campaigns/functional/FO/07_search/01_consultAutocompleteList.js
  tests/UI/pages/BO/customerService/customerService/view.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring

#24660 Update Js documentation for customers pages
  tests/UI/pages/BO/customers/add.js
  tests/UI/pages/BO/customers/addresses/add.js
  tests/UI/pages/BO/customers/addresses/index.js
  tests/UI/pages/BO/customers/index.js
  tests/UI/pages/BO/customers/view.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#24729 Update linklist to v4
  app/AppKernel.php
  composer.json
  composer.lock
  src/Adapter/Module/Tab/ModuleTabRegister.php
  src/PrestaShopBundle/Install/Upgrade.php
  src/PrestaShopBundle/Kernel/ModuleRepository.php
  tests-legacy/Endpoints/AbstractEndpointAdminTest.php
  tests-legacy/Endpoints/AbstractEndpointTest.php
  tests-legacy/PrestaShopBundle/Utils/DatabaseCreator.php
  tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php
Labels: 1.7.7.x, Improvement

#24737 Add ids for link to download sample file on import page
  src/PrestaShopBundle/Resources/views/Admin/macros.html.twig
  tests/UI/pages/BO/advancedParameters/import/index.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring

#24701 Deprecate Tools::safePostVars method
  classes/Tools.php
Labels: BC break, Improvement, develop

#24771 Build assets
  admin-dev/themes/new-theme/public/currency_form.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
Labels: 1.7.7.x, Bug fix

#24680 Fix unclosed div in product-list.tpl
  themes/classic/templates/catalog/listing/product-list.tpl
Labels: 1.7.8.x, Bug fix, QA ✔️

#24775 Add class for columns on legacy tables to be able to target them on tests
  admin-dev/themes/default/template/helpers/list/list_content.tpl
  tests/UI/pages/BO/design/imageSettings/index.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring

#24330 Disable Menus tab and deny access
  install-dev/data/xml/access.xml
  install-dev/data/xml/authorization_role.xml
  install-dev/data/xml/tab.xml
  install-dev/langs/en/data/tab.xml
  install-dev/upgrade/sql/1.7.8.0.sql
Labels: 1.7.8.x, Bug fix, QA ✔️

#24757 Make getValue more strict to avoid false negative
  classes/db/Db.php
Labels: Bug fix, develop

#24745 Form builder modifier
  src/PrestaShopBundle/Form/FormBuilderModifier.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form.yml
  tests/Integration/PrestaShopBundle/Form/AbstractFormTester.php
  tests/Integration/PrestaShopBundle/Form/AdvancedFormType.php
  tests/Integration/PrestaShopBundle/Form/FormBuilderModifierTest.php
  tests/Integration/PrestaShopBundle/Form/FormClonerTest.php
Labels: 1.7.8.x, Developer Feature, Feature, migration

#24782 Check that $session is set before using it
  classes/Cookie.php
Labels: Bug fix, develop

#24785 Fix mispelled word in AdminController
  classes/controller/AdminController.php
Labels: Improvement, develop

#24789 Add jsdoc for classes: imageType, invoice, language, orderMessage, orderReturnStatus, orderStatus, product, profile
  tests/UI/campaigns/data/faker/imageType.js
  tests/UI/campaigns/data/faker/invoice.js
  tests/UI/campaigns/data/faker/language.js
  tests/UI/campaigns/data/faker/orderMessage.js
  tests/UI/campaigns/data/faker/orderReturnStatus.js
  tests/UI/campaigns/data/faker/orderStatus.js
  tests/UI/campaigns/data/faker/product.js
  tests/UI/campaigns/data/faker/profile.js
Labels: 1.7.8.x, E2E Tests, Refactoring

#24688 Correctly displayed precise product weight
  src/PrestaShopBundle/Form/Admin/Product/ProductCombination.php
  src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php
  src/PrestaShopBundle/Form/Admin/Type/CommonAbstractType.php
Labels: Bug fix, QA ✔️, develop

#24787 Add regression test 'Access to Menu tab on Bo should be denied'
  tests/UI/campaigns/regression/menu/deniedAccessToMenuTab.js
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/advancedParameters/menuTab/index.js
Labels: 1.7.8.x, E2E Tests, Refactoring, TE

#24760 Drop leftover code, /tools/http_build_url/ was removed
  controllers/admin/AdminImportController.php
  src/Adapter/Import/ImageCopier.php
Labels: Bug fix, QA ✔️, develop

#24805 Fix customer delete regression and tests
  admin-dev/themes/new-theme/js/components/grid/extension/action/row/customer/delete-customer-row-action-extension.ts
Labels: Bug fix, QA ✔️, develop

#24829 Show formatted Load time in Profiler
  tools/profiling/templates/summary.tpl
Labels: 1.7.8.x, Bug fix

#24835 Fix customers delete bulk selector map
  admin-dev/themes/new-theme/js/components/grid/grid-map.ts
Labels: Bug fix, QA ✔️, develop

#24836 Merge 177x into 178x
  src/Adapter/Order/OrderAmountUpdater.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_shipping.feature
Labels: 1.7.8.x, Improvement

#24282 Remove unwanted margins on order page cards
  admin-dev/themes/new-theme/scss/pages/orders/_orders_view.scss
Labels: 1.7.8.x, Bug fix, PM ✔️, QA ✔️, UX ✔️

#24854 Fix typo in comments of class Mail
  classes/Mail.php
Labels: Improvement, develop

#24730 Add product page link and move download in order details
  themes/classic/templates/customer/_partials/order-detail-no-return.tpl
Labels: Improvement, QA ✔️, Wording ✔️, develop

#24665 Fix dropzone component design on product page v2
  admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue
Labels: 1.7.8.x, Bug fix, QA ✔️, migration

#24834 Check if regeneration is wanted before checking filesystem
  classes/ImageManager.php
Labels: Refactoring, develop

#24813 Fix header toolbar getting over content on mobile and table
  admin-dev/themes/default/scss/partials/_toolbar.scss
Labels: 1.7.8.x, Bug fix, QA ✔️

#24861 Merge 178x into develop
  admin-dev/themes/default/scss/partials/_toolbar.scss
  admin-dev/themes/default/template/controllers/customer_threads/helpers/view/view.tpl
  admin-dev/themes/default/template/helpers/list/list_content.tpl
  admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue
  admin-dev/themes/new-theme/scss/pages/orders/_orders_view.scss
  install-dev/data/xml/access.xml
  install-dev/data/xml/authorization_role.xml
  install-dev/data/xml/tab.xml
  install-dev/langs/en/data/tab.xml
  install-dev/upgrade/sql/1.7.8.0.sql
  src/Adapter/Order/OrderAmountUpdater.php
  src/PrestaShopBundle/Form/FormBuilderModifier.php
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form.yml
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/typeahead.html.twig
  src/PrestaShopBundle/Resources/views/Admin/macros.html.twig
  tests-legacy/PrestaShopBundle/Utils/DatabaseCreator.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_shipping.feature
  tests/Integration/PrestaShopBundle/Form/AbstractFormTester.php
  tests/Integration/PrestaShopBundle/Form/AdvancedFormType.php
  tests/Integration/PrestaShopBundle/Form/FormBuilderModifierTest.php
  tests/Integration/PrestaShopBundle/Form/FormClonerTest.php
  tests/UI/campaigns/data/faker/imageType.js
  tests/UI/campaigns/data/faker/invoice.js
  tests/UI/campaigns/data/faker/language.js
  tests/UI/campaigns/data/faker/orderMessage.js
  tests/UI/campaigns/data/faker/orderReturnStatus.js
  tests/UI/campaigns/data/faker/orderStatus.js
  tests/UI/campaigns/data/faker/product.js
  tests/UI/campaigns/data/faker/profile.js
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/01_viewCustomerService.js
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/03_contactOptions.js
  tests/UI/campaigns/functional/FO/07_search/01_consultAutocompleteList.js
  tests/UI/campaigns/regression/menu/deniedAccessToMenuTab.js
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/advancedParameters/import/index.js
  tests/UI/pages/BO/advancedParameters/menuTab/index.js
  tests/UI/pages/BO/customerService/customerService/view.js
  tests/UI/pages/BO/customers/add.js
  tests/UI/pages/BO/customers/addresses/add.js
  tests/UI/pages/BO/customers/addresses/index.js
  tests/UI/pages/BO/customers/index.js
  tests/UI/pages/BO/customers/view.js
  tests/UI/pages/BO/design/imageSettings/index.js
  themes/classic/templates/catalog/listing/product-list.tpl
  tools/profiling/templates/summary.tpl
Labels: Improvement, develop

#24865 Country GB is non-EU country
  admin-dev/themes/default/scss/partials/_toolbar.scss
  admin-dev/themes/default/template/controllers/customer_threads/helpers/view/view.tpl
  admin-dev/themes/default/template/helpers/list/list_content.tpl
  admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue
  admin-dev/themes/new-theme/scss/pages/orders/_orders_view.scss
  install-dev/data/xml/access.xml
  install-dev/data/xml/authorization_role.xml
  install-dev/data/xml/tab.xml
  install-dev/langs/en/data/tab.xml
  install-dev/upgrade/sql/1.7.8.0.sql
  src/Adapter/Order/OrderAmountUpdater.php
  src/PrestaShopBundle/Form/FormBuilderModifier.php
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form.yml
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/typeahead.html.twig
  src/PrestaShopBundle/Resources/views/Admin/macros.html.twig
  tests-legacy/PrestaShopBundle/Utils/DatabaseCreator.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_shipping.feature
  tests/Integration/PrestaShopBundle/Form/AbstractFormTester.php
  tests/Integration/PrestaShopBundle/Form/AdvancedFormType.php
  tests/Integration/PrestaShopBundle/Form/FormBuilderModifierTest.php
  tests/Integration/PrestaShopBundle/Form/FormClonerTest.php
  tests/UI/campaigns/data/faker/imageType.js
  tests/UI/campaigns/data/faker/invoice.js
  tests/UI/campaigns/data/faker/language.js
  tests/UI/campaigns/data/faker/orderMessage.js
  tests/UI/campaigns/data/faker/orderReturnStatus.js
  tests/UI/campaigns/data/faker/orderStatus.js
  tests/UI/campaigns/data/faker/product.js
  tests/UI/campaigns/data/faker/profile.js
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/01_viewCustomerService.js
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/03_contactOptions.js
  tests/UI/campaigns/functional/FO/07_search/01_consultAutocompleteList.js
  tests/UI/campaigns/regression/menu/deniedAccessToMenuTab.js
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/advancedParameters/import/index.js
  tests/UI/pages/BO/advancedParameters/menuTab/index.js
  tests/UI/pages/BO/customerService/customerService/view.js
  tests/UI/pages/BO/customers/add.js
  tests/UI/pages/BO/customers/addresses/add.js
  tests/UI/pages/BO/customers/addresses/index.js
  tests/UI/pages/BO/customers/index.js
  tests/UI/pages/BO/customers/view.js
  tests/UI/pages/BO/design/imageSettings/index.js
  themes/classic/templates/catalog/listing/product-list.tpl
  tools/profiling/templates/summary.tpl
Labels: Bug fix

#24849 Fix wrong tab selected after changing a product combination on the FO
  themes/classic/_dev/js/product.js
  themes/classic/_dev/js/selectors.js
Labels: 1.7.8.x, Bug fix, QA ✔️

#24846 Remove extracted comments from webpack config of core js
  themes/webpack.config.js
Labels: Bug fix, develop

#24847 Fix hook wording
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.8.0.sql
Labels: 1.7.8.x, Bug fix

#24595 Wrong mimetype for svg file
  admin-dev/filemanager/config/config.php
Labels: Bug fix, QA ✔️, develop

#24867 Fix order notes not being saved
  classes/order/Order.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#24728 Remove unwanted bundle.js call
  admin-dev/themes/new-theme/.webpack/common.js
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Theme/import.html.twig
Labels: 1.7.8.x, Bug fix, QA ✔️

#24738 Add a hook 'actionValidateOrderAfter', This hook is called after the complete creation of an order
  classes/PaymentModule.php
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.9.0.sql
Labels: Feature, QA ✔️, develop

#24795 Fix checkout page details removed and wrong price when adding/removing voucher
  themes/_core/js/selectors.js
  themes/classic/templates/checkout/_partials/cart-summary-totals.tpl
Labels: 1.7.8.x, Bug fix, QA ✔️

#24794 Fix js error when adding voucher in create order
  admin-dev/themes/default/template/controllers/cart_rules/form.js
  admin-dev/themes/default/template/form_submit_ajax.tpl
  classes/controller/AdminController.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#24876 Add classes for sort links on legacy pages
  admin-dev/themes/default/template/helpers/list/list_header.tpl
Labels: 1.7.8.x, Improvement

#24398 Partially restore feature search in Back Office
  admin-dev/themes/default/template/controllers/search/helpers/view/view.tpl
  controllers/admin/AdminSearchController.php
Labels: Feature, QA ✔️, develop

#24661 Display tab for extra modules in product page
  admin-dev/themes/new-theme/js/pages/product/edit/index.js
  admin-dev/themes/new-theme/js/pages/product/edit/product-modules-manager.js
  admin-dev/themes/new-theme/js/pages/product/product-map.js
  admin-dev/themes/new-theme/scss/pages/product/product_page.scss
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/modules-content.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/modules-preview.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/tabs.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Tabs/modules.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/edit.html.twig
Labels: 1.7.8.x, Improvement, QA ✔️, Wording ✔️

#24870 Improve selectors and functions on statuses page
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/returnStatuses/01_CRUDOrderReturnStatus.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/returnStatuses/02_filterSortAndPagination.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/statuses/01_CRUDOrderStatus.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/statuses/02_filterSortAndPagination.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/statuses/03_quickEdit.js
  tests/UI/pages/BO/shopParameters/orderSettings/statuses/index.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#24885 Register new hooks for 1.7.8.0
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.8.0.sql
Labels: 1.7.8.x, Improvement

#24796 Checking for url existence in possible new default shop
  controllers/admin/AdminShopGroupController.php
Labels: Bug fix, QA ✔️, Wording ✔️, develop

#24837 Fix zoom on theme email grid and legacy dropdowns
  admin-dev/themes/default/scss/partials/_tables.scss
  admin-dev/themes/new-theme/scss/components/_grid.scss
Labels: 1.7.8.x, Bug fix, QA ✔️

#24821 Handle CustomerAddressGridDefinitionFactory in CLI context
  src/Core/Grid/Definition/Factory/CustomerAddressGridDefinitionFactory.php
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
Labels: 1.7.8.x, Bug fix, QA ✔️

#24852 Fix 404 layout for wrong category
  controllers/front/listing/CategoryController.php
  themes/classic/_dev/css/components/errors.scss
Labels: 1.7.8.x, Bug fix, QA ✔️, Wording ✔️

#24904 Wait for navigation after click on FO menu
  tests/UI/pages/FO/FObasePage.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#24699 Functional test - Add quick access test
  admin-dev/themes/default/template/header.tpl
  admin-dev/themes/new-theme/template/components/layout/quick_access.tpl
  tests/UI/campaigns/functional/BO/15_header/02_quickAccess.js
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/customers/add.js
  tests/UI/pages/BO/quickAccess/add.js
  tests/UI/pages/BO/quickAccess/index.js
  tests/UI/pages/BO/stats/index.js
  tests/UI/pages/commonPage.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#24894 Update Js doc for design pages
  tests/UI/pages/BO/design/emailThemes/index.js
  tests/UI/pages/BO/design/emailThemes/preview.js
  tests/UI/pages/BO/design/imageSettings/add.js
  tests/UI/pages/BO/design/imageSettings/index.js
  tests/UI/pages/BO/design/linkWidgets/add.js
  tests/UI/pages/BO/design/linkWidgets/index.js
  tests/UI/pages/BO/design/pages/add.js
  tests/UI/pages/BO/design/pages/index.js
  tests/UI/pages/BO/design/pages/pageCategory/add.js
  tests/UI/pages/BO/design/positions/index.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#24848 Avoid setting height to 0 if height isn't defined on product dropzone
  admin-dev/themes/default/js/bundle/product/form.js
  admin-dev/themes/new-theme/scss/pages/product/product_page.scss
Labels: 1.7.8.x, Bug fix, QA ✔️

#24634 Remove _PS_SMARTY_DIR_ pointing to no longer existing directory
  .github/workflows/phpstan/autoload.php
  config/smarty.config.inc.php
Labels: BC break, Bug fix, develop

#24682 Add missing Grid and Router JS components
  admin-dev/themes/new-theme/js/app/utils/init-components.js
Labels: 1.7.8.x, Bug fix, Developer Feature, Documentation, QA ✔️

#24905 Add forgotten contributor in CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: 1.7.8.x

#24469 Multistore header on product pages
  src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/disabled_form_alert.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/product.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/edit.html.twig
  src/PrestaShopBundle/Twig/Extension/MultistoreHeaderExtension.php
Labels: 1.7.8.x, Improvement, QA ✔️

#24892 Fix productv2 creation link
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Blocks/footer.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/product.html.twig
Labels: 1.7.8.x, Bug fix, QA ✔️, Wording ✔️, migration

#24600 FO - Validate field values when creating customer account
  classes/form/CustomerAddressForm.php
  classes/form/CustomerForm.php
Labels: 1.7.8.x, Bug fix, QA ✔️, Wording ✔️

#24879 Update JS documentation for international pages
  tests/UI/pages/BO/international/currencies/add.js
  tests/UI/pages/BO/international/currencies/index.js
  tests/UI/pages/BO/international/languages/add.js
  tests/UI/pages/BO/international/languages/index.js
  tests/UI/pages/BO/international/localization/index.js
  tests/UI/pages/BO/international/localization/localizationBasePage.js
  tests/UI/pages/BO/international/locations/add.js
  tests/UI/pages/BO/international/locations/countries/add.js
  tests/UI/pages/BO/international/locations/countries/index.js
  tests/UI/pages/BO/international/locations/index.js
  tests/UI/pages/BO/international/locations/states/add.js
  tests/UI/pages/BO/international/locations/states/index.js
  tests/UI/pages/BO/international/taxes/add.js
  tests/UI/pages/BO/international/taxes/index.js
  tests/UI/pages/BO/international/taxes/taxRules/add.js
  tests/UI/pages/BO/international/taxes/taxRules/index.js
  tests/UI/pages/BO/international/translations/index.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#23515 Add category products number in BO list
  src/Core/Grid/Definition/Factory/CategoryGridDefinitionFactory.php
  src/Core/Grid/Query/CategoryQueryBuilder.php
Labels: Improvement, PM ✔️, QA ✔️, Wording ✔️, develop

#24950 Changelog 1.7.7.5
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: 1.7.7.x, Improvement

#24811 Fix invalid html attribute on multistore fields
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/General/MaintenanceType.php
  src/PrestaShopBundle/Form/Admin/Extension/MultistoreExtension.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_extension.yml
  src/PrestaShopBundle/Service/Form/MultistoreCheckboxEnabler.php
  tests/Unit/PrestaShopBundle/Service/Form/MultistoreCheckboxEnablerTest.php
Labels: 1.7.8.x, Bug fix, Improvement, QA ✔️

#24783 Fix pages name for link list module
  tests/UI/pages/BO/design/linkWidgets/add.js
  tests/UI/pages/BO/design/linkWidgets/index.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring

#24773 BO - Order Preview : Added email
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/preview.html.twig
Labels: 1.7.7.x, Bug fix, QA ✔️, Wording ✔️

#24770 Added currency BYN TO CLDR dataset
  localization/CLDR/core/common/supplemental/supplementalData.xml
Labels: 1.7.7.x, Bug fix, QA ✔️

#24765 Fix edit price modal showed when adding same product in multi-invoices
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
Labels: 1.7.7.x, Bug fix, QA ✔️

#24762 Fixed adding a free shipping cart rule on a 0.00 order
  src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_cart_rules.feature
Labels: 1.7.7.x, Bug fix, QA ✔️

#24899 Avoid errors display when Emails translations lang.php does not exist
  controllers/admin/AdminTranslationsController.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#24951 Change attribute name to something more specific to fix filter
  tests/UI/campaigns/data/faker/attributeAndValue.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#24920 Fixed duplicate address in checkout
  themes/classic/templates/checkout/_partials/steps/addresses.tpl
Labels: Bug fix, QA ✔️, develop

#24910 CO allow merchant and customer to add < } in a message
  classes/CustomerMessage.php
  controllers/front/OrderDetailController.php
  themes/classic/templates/customer/_partials/order-messages.tpl
Labels: Bug fix, QA ✔️, develop

#24927 Add unit tests for javascript
  .github/workflows/js.yml
Labels: Improvement, develop

#24953 Bump version to 1.7.7.6
  app/AppKernel.php
  install-dev/install_version.php
Labels: 1.7.7.x, Bug fix

#24936 In PDF, Use "freeserif" for Armenian language (hy)
  classes/pdf/PDFGenerator.php
Labels: Improvement, QA ✔️, develop

#24957 Bump modules Welcome to 6.0.5 & ProductComments to 4.2.2
  composer.lock
Labels: 1.7.7.x, Improvement

#24918 Fix table responsive of multistore page
  admin-dev/themes/default/scss/partials/_multistore.scss
Labels: 1.7.8.x, Bug fix, QA ✔️

#24897 Fix translations escaping for BO header
  admin-dev/themes/default/template/header.tpl
  admin-dev/themes/new-theme/template/layout.tpl
Labels: Bug fix, QA ✔️, develop

#24866 Country GB is non-EU country (2)
  install-dev/data/xml/country.xml
Labels: 1.7.8.x, Bug fix, CO, QA ✔️, Wording ✔️

#24808 Remove white-space : nowrap to the category tree.
  admin-dev/themes/new-theme/scss/pages/product/product_page.scss
Labels: Improvement, QA ✔️, UX ✔️, develop

#24960 Merge 177x into 178x
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js
  composer.lock
  docs/CHANGELOG.txt
  localization/CLDR/core/common/supplemental/supplementalData.xml
  src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/preview.html.twig
  tests/Integration/Behaviour/Features/Scenario/Order/order_cart_rules.feature
Labels: 1.7.8.x, Improvement

#23441 Migrate "Shop parameters > Traffic & SEO > Search Engines" and create/edit of search engines
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/js/pages/search-engine/index.js
  controllers/admin/AdminSearchEnginesController.php
  src/Adapter/SearchEngine/AbstractSearchEngineHandler.php
  src/Adapter/SearchEngine/CommandHandler/AddSearchEngineHandler.php
  src/Adapter/SearchEngine/CommandHandler/BulkDeleteSearchEngineHandler.php
  src/Adapter/SearchEngine/CommandHandler/DeleteSearchEngineHandler.php
  src/Adapter/SearchEngine/CommandHandler/EditSearchEngineHandler.php
  src/Adapter/SearchEngine/QueryHandler/GetSearchEngineForEditingHandler.php
  src/Core/ConstraintValidator/Constraints/TypedRegex.php
  src/Core/ConstraintValidator/TypedRegexValidator.php
  src/Core/Domain/SearchEngine/Command/AddSearchEngineCommand.php
  src/Core/Domain/SearchEngine/Command/BulkDeleteSearchEngineCommand.php
  src/Core/Domain/SearchEngine/Command/DeleteSearchEngineCommand.php
  src/Core/Domain/SearchEngine/Command/EditSearchEngineCommand.php
  src/Core/Domain/SearchEngine/CommandHandler/AddSearchEngineHandlerInterface.php
  src/Core/Domain/SearchEngine/CommandHandler/BulkDeleteSearchEngineHandlerInterface.php
  src/Core/Domain/SearchEngine/CommandHandler/DeleteSearchEngineHandlerInterface.php
  src/Core/Domain/SearchEngine/CommandHandler/EditSearchEngineHandlerInterface.php
  src/Core/Domain/SearchEngine/Exception/DeleteSearchEngineException.php
  src/Core/Domain/SearchEngine/Exception/SearchEngineException.php
  src/Core/Domain/SearchEngine/Exception/SearchEngineNotFoundException.php
  src/Core/Domain/SearchEngine/Query/GetSearchEngineForEditing.php
  src/Core/Domain/SearchEngine/QueryHandler/GetSearchEngineForEditingHandlerInterface.php
  src/Core/Domain/SearchEngine/QueryResult/SearchEngineForEditing.php
  src/Core/Domain/SearchEngine/ValueObject/SearchEngineId.php
  src/Core/Form/IdentifiableObject/DataHandler/SearchEngineFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/SearchEngineFormDataProvider.php
  src/Core/Grid/Definition/Factory/SearchEngineGridDefinitionFactory.php
  src/Core/Grid/Query/SearchEngineQueryBuilder.php
  src/Core/Search/Filters/SearchEngineFilters.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/SearchEnginesController.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/SearchEngines/SearchEngineType.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/shop_parameters/_shop_parameters.yml
  src/PrestaShopBundle/Resources/config/routing/admin/configure/shop_parameters/search_engines.yml
  src/PrestaShopBundle/Resources/config/services/adapter/search_engine.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_handler.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_data_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_factory.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/TrafficSeo/SearchEngines/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/TrafficSeo/SearchEngines/create.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/TrafficSeo/SearchEngines/edit.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/TrafficSeo/SearchEngines/index.html.twig
  tests-legacy/Integration/PrestaShopBundle/Controller/Admin/SurvivalTest.php
  tests-legacy/PrestaShopBundle/Controller/ControllerTest.php
  tests/Integration/Behaviour/Features/Context/Domain/SearchEngineFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/SearchEngine/search_engine_management.feature
  tests/Integration/Behaviour/behat.yml
  tests/UI/campaigns/data/demo/searchEngines.js
  tests/UI/campaigns/data/faker/searchEngine.js
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/02_searchEngines/01_filterSortAndPagination.js
  tests/UI/pages/BO/shopParameters/trafficAndSeo/searchEngines/add.js
  tests/UI/pages/BO/shopParameters/trafficAndSeo/searchEngines/index.js
  tests/Unit/Core/ConstraintValidator/TypedRegexValidatorTest.php
Labels: BO, QA ✔️, Refactoring, TE, develop, migration

#24676 Remove addons modules on install and add postinstall execution
  classes/module/Module.php
  composer.lock
  install-dev/classes/datas.php
  install-dev/controllers/console/process.php
  install-dev/controllers/http/process.php
  src/Adapter/Module/Module.php
  src/Core/Addon/Module/ModuleInterface.php
  src/Core/Addon/Module/ModuleManager.php
  src/PrestaShopBundle/Event/ModuleManagementEvent.php
  src/PrestaShopBundle/Install/Install.php
  tests/UI/campaigns/sanity/01_installShop/01_installShop.js
  tests/UI/pages/install/index.js
  tests/Unit/Core/Addon/Module/ModuleManagerTest.php
Labels: BC break, Improvement, QA ✔️, Wording ✔️, develop

#24924 Add missing supplier for product pack in fixtures
  install-dev/fixtures/fashion/data/product_supplier.xml
Labels: 1.7.8.x, Bug fix, QA ✔️

#24823 Validate image if needed first when adding new brand
  src/Adapter/Image/Uploader/AbstractImageUploader.php
  src/Core/Form/IdentifiableObject/DataHandler/ManufacturerFormDataHandler.php
Labels: BC break, Bug fix, QA ✔️, develop

#24970 Remove uselss static cache and make sure CI exit in status 1 when installation failed
  .github/workflows/integration.yml
  .github/workflows/lint.yml
  classes/Tab.php
  install-dev/classes/controllerConsole.php
  install-dev/controllers/console/process.php
  src/PrestaShopBundle/Install/Install.php
Labels: Bug fix, Waiting for QA, develop

#24919 Update node sass
  admin-dev/themes/default/package-lock.json
  admin-dev/themes/default/package.json
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
Labels: Bug fix, QA ✔️, develop

#24713 Fix missing scrollbar on multistore dropdowns
  admin-dev/themes/new-theme/scss/components/_multishop-modal.scss
  admin-dev/themes/new-theme/scss/components/_multistore-dropdown.scss
  src/PrestaShopBundle/Resources/views/Admin/Multistore/dropdown.html.twig
Labels: Improvement, QA ✔️, develop

#24981 Fix order status test after deleting status added by addons modules
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/statuses/02_filterSortAndPagination.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#24851 Twig extension for multistore shop context URLs
  admin-dev/themes/new-theme/js/components/components-map.js
  admin-dev/themes/new-theme/js/components/multistore-dropdown.js
  src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
  src/PrestaShopBundle/Resources/views/Admin/Multistore/dropdown.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Multistore/header.html.twig
  src/PrestaShopBundle/Twig/Extension/MultistoreUrlExtension.php
  tests/Unit/PrestaShopBundle/Twig/Extension/MultistoreUrlExtensionTest.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#24909 Fix steps height on carrier page on mobile
  admin-dev/themes/default/template/controllers/carrier_wizard/summary.tpl
  js/jquery/plugins/smartWizard/jquery.smartWizard.js
Labels: Bug fix, QA ✔️, develop

#24908 Fixed default value for Currency after upgrade
  install-dev/upgrade/sql/1.7.7.6.sql
Labels: 1.7.7.x, Bug fix, QA ✔️

#24323 Update classic webpack and fix watch issue by adding webpack-cli locally
  themes/classic/_dev/package-lock.json
  themes/classic/_dev/package.json
  themes/classic/_dev/webpack.config.js
Labels: 1.7.8.x, Bug fix, QA ✔️, Waiting for dev

#24320 Bug fix for number of decimals in product price
  classes/Product.php
  src/Core/Localization/Number/Formatter.php
  src/Core/Localization/Specification/Factory.php
  tests-legacy/Unit/Core/Localization/Specification/FactoryTest.php
Labels: 1.7.7.x, Bug fix, QA ✔️

#24657 BO - New Order - Warn when product's stock of a pack are empty
  src/Adapter/Cart/CommandHandler/UpdateProductQuantityInCartHandler.php
  src/Core/Domain/Product/Exception/PackOutOfStockException.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php
  tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Updating/Product/update_pack.feature
  tests/Integration/Behaviour/behat.yml
Labels: 1.7.7.x, Bug fix, QA ✔️

#24996 Fix nightly 17-06-2021
  tests/UI/campaigns/functional/BO/02_orders/01_orders/08_viewCustomer.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#24509 Remove old selected_filters route
  classes/Dispatcher.php
  classes/Link.php
Labels: Bug fix, QA ✔️, develop

#24958 Allow HOOK_DISPLAY_PDF to fill the whole page area
  pdf/delivery-slip.tpl
  pdf/invoice-b2b.tpl
  pdf/invoice.tpl
  pdf/order-return.tpl
  pdf/order-slip.tpl
Labels: Bug fix, QA ✔️, develop

#23480 Improve accessibility of classic theme forms by adding for and ids
  themes/classic/modules/contactform/views/templates/widget/contactform.tpl
  themes/classic/modules/ps_shoppingcart/ps_shoppingcart.tpl
  themes/classic/templates/_partials/form-fields.tpl
  themes/classic/templates/catalog/_partials/product-customization.tpl
  themes/classic/templates/catalog/_partials/sort-orders.tpl
  themes/classic/templates/checkout/_partials/cart-detailed-product-line.tpl
  themes/classic/templates/customer/_partials/customer-form.tpl
  themes/classic/templates/customer/_partials/login-form.tpl
  themes/classic/templates/page.tpl
Labels: 1.7.8.x, Improvement, QA ✔️, Wording ✔️

#24952 Limit id min-max width on product list
  admin-dev/themes/new-theme/scss/components/_grid.scss
  admin-dev/themes/new-theme/scss/pages/product/products_catalog.scss
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/Table/filters_row.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/Table/headers_row.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/table.html.twig
Labels: Bug fix, QA ✔️, develop

#24774 Fix missing product indexation after creation on product page V2
  src/Adapter/Product/CommandHandler/UpdateProductOptionsHandler.php
  src/Adapter/Product/Update/ProductIndexationUpdater.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  tests/Integration/Behaviour/Features/Context/Configuration/CommonConfigurationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/CommonProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/update_options.feature
Labels: 1.7.8.x, Bug fix, QA ✔️

#25021 Fix license headers
  tests/Unit/Resources/module-self-config-files/php/MyComplexModuleConfiguration.php
  themes/classic/templates/checkout/_partials/cart-detailed-product-line.tpl
Labels: 1.7.8.x, Improvement

#24799 Improved performance for watermarking on import
  controllers/admin/AdminImportController.php
  src/Adapter/Import/ImageCopier.php
Labels: Improvement, QA ✔️, develop

#24890 Fix top buttons on order view on mobile
  admin-dev/themes/new-theme/scss/pages/orders/_orders_view.scss
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/documents.html.twig
Labels: 1.7.8.x, Bug fix, QA ✔️

#25004 Fix help sidebar on Experimental Features BO Page
  controllers/admin/AdminLegacyLayoutController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/FeatureFlagController.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#24940 Refactor cartPresenter to reflect the real business need
  src/Adapter/Presenter/Cart/CartPresenter.php
Labels: Refactoring, develop

#24895 Fix empty data by < in invoice note
  classes/order/OrderInvoice.php
  pdf/invoice.note-tab.tpl
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
Labels: Bug fix, QA ✔️, Wording ✔️, develop

#24025 Add SubmittableInput successfull and error states
  admin-dev/themes/new-theme/js/components/form/submittable-input.js
  admin-dev/themes/new-theme/js/pages/product/edit/combinations-manager.js
  admin-dev/themes/new-theme/js/pages/product/services/combinations-service.js
  admin-dev/themes/new-theme/scss/components/_submittable_input.scss
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php
Labels: 1.7.8.x, Bug fix, QA ✔️, Wording ✔️, migration

#24921 Reset Germany tax rates
  localization/de.xml
Labels: Improvement, QA ✔️, Wording ✔️, develop

#25057 Fix menu check on regression test
  tests/UI/campaigns/regression/menu/deniedAccessToMenuTab.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#25047 Fix nightly tests for 21-06-2021
  tests/UI/pages/FO/checkout/index.js
  tests/UI/pages/FO/contactUs/index.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#25039 Disable product V2 page when multistore is used
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/disabled.html.twig
Labels: 1.7.8.x, Improvement, QA ✔️

#24869 Fix no active payment module displayed in Payment Methods
  src/Adapter/Module/Presenter/PaymentModulesPresenter.php
  src/Adapter/Module/TabModuleListProvider.php
  src/Adapter/Presenter/Module/PaymentModulesPresenter.php
  src/PrestaShopBundle/Controller/Admin/Improve/Payment/PaymentMethodsController.php
  src/PrestaShopBundle/Resources/config/services/adapter/module.yml
Labels: 1.7.8.x, Bug fix, QA ✔️

#25037 Be able to use subquery when using DbQuery class
  classes/db/DbQuery.php
  tests/Unit/Classes/Db/DbQueryTest.php
Labels: Improvement, QA ✔️, develop

#24933 Old products.js fixes
  js/admin/products.js
Labels: Bug fix, QA ✔️, develop

#25082 Fix category create in old product page
  src/Core/Domain/Product/Command/AssignProductToCategoryCommand.php
  src/PrestaShopBundle/Controller/Admin/CategoryController.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#24052 Open confirm modal only when eligible for feature flag form
  admin-dev/themes/new-theme/js/pages/feature-flag/index.js
Labels: 1.7.8.x, Bug fix, PM ✔️, QA ✔️

#25035 Fix product footer direction using RTL language
  admin-dev/themes/new-theme/public/theme.rtlfix
Labels: 1.7.8.x, Bug fix, QA ✔️

#25088 Functional tests - Add some refacto to Orders>Invoices tests
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/01_generateInvoiceByDate.js
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/02_generateInvoiceByStatus.js
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/01_enableDisableInvoices.js
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/02_enableDisableTaxBreakdown.js
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/03_enableDisableProductImage.js
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/04_invoicePrefix.js
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/05_enableDisableCurrentYear.js
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/06_otherOptions.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#24902 Wording corrections before RC
  admin-dev/themes/default/template/header.tpl
  app/Resources/translations/default/AdminActions.xlf
  app/Resources/translations/default/AdminAdvparametersFeature.xlf
  app/Resources/translations/default/AdminAdvparametersHelp.xlf
  app/Resources/translations/default/AdminCatalogFeature.xlf
  app/Resources/translations/default/AdminCatalogHelp.xlf
  app/Resources/translations/default/AdminCatalogNotification.xlf
  app/Resources/translations/default/AdminGlobal.xlf
  app/Resources/translations/default/AdminModulesFeature.xlf
  app/Resources/translations/default/AdminNavigationHeader.xlf
  app/Resources/translations/default/AdminNotificationsError.xlf
  app/Resources/translations/default/AdminNotificationsInfo.xlf
  app/Resources/translations/default/AdminNotificationsSuccess.xlf
  app/Resources/translations/default/AdminNotificationsWarning.xlf
  app/Resources/translations/default/AdminOrderscustomersFeature.xlf
  app/Resources/translations/default/AdminPaymentNotification.xlf
  app/Resources/translations/default/AdminShopparametersFeature.xlf
  app/Resources/translations/default/AdminShopparametersHelp.xlf
  app/Resources/translations/default/Install.xlf
  app/Resources/translations/default/ModulesLinklistAdmin.xlf
  app/Resources/translations/default/ModulesLinklistShop.xlf
  app/Resources/translations/default/ModulesProductcommentsAdmin.xlf
  app/Resources/translations/default/ModulesWelcomeAdmin.xlf
  app/Resources/translations/default/ShopFormsErrors.xlf
  app/Resources/translations/default/ShopFormsHelp.xlf
  app/Resources/translations/default/ShopFormsLabels.xlf
  app/Resources/translations/default/ShopNotificationsError.xlf
  app/Resources/translations/default/ShopThemeActions.xlf
  app/Resources/translations/default/ShopThemeCatalog.xlf
  app/Resources/translations/default/ShopThemeCheckout.xlf
  app/Resources/translations/default/ShopThemeGlobal.xlf
  app/Resources/translations/default/messages.xlf
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/CustomerPreferences/GeneralType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/SEO/SEOType.php
  src/PrestaShopBundle/Resources/views/Admin/Common/pagination.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Payment/Preferences/payment_preferences.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/modal_read_more_content.html.twig
Labels: 1.7.8.x, Bug fix, Wording ✔️

#25048 Fix mobile boostrap column spacing and forgotten class
  admin-dev/themes/new-theme/scss/components/layout/_content_div.scss
Labels: Bug fix, QA ✔️, develop

#25012 Fix color picker bug
  js/jquery/plugins/jquery.colorpicker.js
Labels: Bug fix, QA ✔️, develop

#25034 Fix checkbox direction on RTL
  admin-dev/themes/new-theme/public/theme.rtlfix
Labels: 1.7.8.x, Bug fix, QA ✔️

#25102 Update ps_linklist module to v5.0.1
  composer.json
  composer.lock
Labels: 1.7.8.x, Improvement

#25098 Remove precision type for currency
  src/Core/Localization/Currency.php
  src/Core/Localization/Currency/CurrencyData.php
  src/Core/Localization/Specification/Factory.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#25111 Fix compiled legacy container
  classes/container/LegacyCompilerPass.php
  src/Adapter/ContainerBuilder.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#25096 Merge 177x into 178x
  classes/Product.php
  install-dev/upgrade/sql/1.7.7.6.sql
  src/Core/Localization/Number/Formatter.php
  tests/Unit/Core/Localization/Specification/FactoryTest.php
Labels: 1.7.8.x, Improvement

#25120 Update Welcome module to 6.0.6
  composer.lock
Labels: 1.7.8.x, Improvement

#25121 Update translations catalogue with Welcome module wordings
  app/Resources/translations/default/ModulesWelcomeAdmin.xlf
Labels: 1.7.8.x, Improvement

#24754 Removed free shipping from cumulative reduction
  classes/CartRule.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/percent_multiple.feature
Labels: 1.7.7.x, Bug fix, QA ✔️

#25126 Fix currency precision regression test
  tests/UI/campaigns/regression/currencies/computingPrecision_FO.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring

#25131 Update ps_linklist version
  composer.lock
Labels: 1.7.8.x, Improvement

#25072 BO: Product Form V2 : Show inactive categories in the category tree
  admin-dev/themes/new-theme/js/pages/product/components/categories/index.js
  src/Adapter/Category/QueryHandler/GetCategoriesTreeHandler.php
  src/Core/Domain/Category/QueryResult/CategoryForTree.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
Labels: Bug fix, QA ✔️, develop

#22969 Fixed API inconsistent return format of JSON
  classes/webservice/WebserviceOutputBuilder.php
  classes/webservice/WebserviceOutputJSON.php
Labels: Bug, QA ✔️, develop

#25085 Kick border radius of the middle button of search bar
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
Labels: Bug fix, QA ✔️, develop

#25141 Upgrade ps_linklist to 5.0.3
  composer.lock
Labels: 1.7.8.x, Improvement, QA ✔️

#25108 Functional tests - Refacto 'Orders > Shopping carts' tests
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/01_filterShoppingCarts.js
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/02_sortAndPagination.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#25128 Functional tests - Add js doc for 'Advanced parameters' pages
  tests/UI/pages/BO/advancedParameters/database/dbBackup/index.js
  tests/UI/pages/BO/advancedParameters/database/sqlManager/add.js
  tests/UI/pages/BO/advancedParameters/database/sqlManager/index.js
  tests/UI/pages/BO/advancedParameters/database/sqlManager/view.js
  tests/UI/pages/BO/advancedParameters/email/index.js
  tests/UI/pages/BO/advancedParameters/import/index.js
  tests/UI/pages/BO/advancedParameters/logs/index.js
  tests/UI/pages/BO/advancedParameters/multistore/add.js
  tests/UI/pages/BO/advancedParameters/multistore/index.js
  tests/UI/pages/BO/advancedParameters/multistore/shop/add.js
  tests/UI/pages/BO/advancedParameters/multistore/shop/index.js
  tests/UI/pages/BO/advancedParameters/multistore/url/addURL.js
  tests/UI/pages/BO/advancedParameters/multistore/url/index.js
  tests/UI/pages/BO/advancedParameters/team/add.js
  tests/UI/pages/BO/advancedParameters/team/index.js
  tests/UI/pages/BO/advancedParameters/team/profiles/add.js
  tests/UI/pages/BO/advancedParameters/team/profiles/index.js
  tests/UI/pages/BO/advancedParameters/webservice/add.js
  tests/UI/pages/BO/advancedParameters/webservice/index.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#25104 Functional tests - Refacto 'Orders > Delivery slips' tests
  tests/UI/campaigns/functional/BO/02_orders/04_deliverySlips/01_generateDeliverySlipByDate.js
  tests/UI/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/01_deliverySlipPrefix.js
  tests/UI/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/02_deliverySlipNumber.js
  tests/UI/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/03_enableDisableProductImage.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE, Waiting for author

#25101 Fix RTL issues on material icons on FO
  themes/classic/_dev/css/components/featuredproducts.scss
  themes/classic/_dev/css/components/imageslider.scss
Labels: 1.7.8.x, Bug fix, QA ✔️, Waiting for author

#24995 Functional tests - Add Js doc for catalog pages
  tests/UI/pages/BO/catalog/attributes/addAttribute.js
  tests/UI/pages/BO/catalog/attributes/addValue.js
  tests/UI/pages/BO/catalog/attributes/index.js
  tests/UI/pages/BO/catalog/attributes/view.js
  tests/UI/pages/BO/catalog/brands/add.js
  tests/UI/pages/BO/catalog/brands/addAddress.js
  tests/UI/pages/BO/catalog/brands/index.js
  tests/UI/pages/BO/catalog/categories/add.js
  tests/UI/pages/BO/catalog/categories/index.js
  tests/UI/pages/BO/catalog/discounts/add.js
  tests/UI/pages/BO/catalog/discounts/catalogPriceRules/add.js
  tests/UI/pages/BO/catalog/discounts/catalogPriceRules/index.js
  tests/UI/pages/BO/catalog/discounts/index.js
  tests/UI/pages/BO/catalog/files/add.js
  tests/UI/pages/BO/catalog/files/index.js
  tests/UI/pages/BO/catalog/monitoring/index.js
  tests/UI/pages/BO/catalog/products/add.js
  tests/UI/pages/BO/catalog/products/index.js
  tests/UI/pages/BO/catalog/stocks/index.js
  tests/UI/pages/BO/catalog/stocks/movements/index.js
  tests/UI/pages/BO/catalog/suppliers/add.js
  tests/UI/pages/BO/catalog/suppliers/index.js
  tests/UI/pages/BO/catalog/suppliers/view.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE, Waiting for author

#25123 Changelog for 1.7.8.0-RC-1
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: 1.7.8.x, Improvement

#25089 Fixed replaced image in product page
  admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue
Labels: Improvement, QA ✔️, develop

#25147 Do not strict type for compatibility reason
  classes/module/Module.php
Labels: Bug fix, develop

#25087 Fix form label alignment, switch precision and alignment
  admin-dev/themes/default/scss/partials/_switch-btn.scss
  admin-dev/themes/new-theme/scss/components/_form.scss
Labels: Bug fix, QA ✔️, develop

#24982 Fix getting products count on category list
  src/Core/Grid/Query/CategoryQueryBuilder.php
Labels: Bug fix, QA ✔️, develop

#25151 Remove useless 50x.html pages in classic
  themes/classic/templates/errors/static/500.html
  themes/classic/templates/errors/static/503.html
Labels: Bug fix, QA ✔️, develop
