Repository PrestaShop/PrestaShop, pull requests merged in 2021-05, with the labels that each got.

#24266 Increase minimum size of the Quantity field in Partial Refund
  admin-dev/themes/new-theme/scss/pages/orders/_orders_view.scss
Labels: 1.7.8.x, Bug fix, QA ✔️

#24134 Remove combination from list
  admin-dev/themes/new-theme/js/fos_js_routes.json
  admin-dev/themes/new-theme/js/pages/product/edit/combinations-manager.js
  admin-dev/themes/new-theme/js/pages/product/edit/feature-values-manager.js
  admin-dev/themes/new-theme/js/pages/product/product-map.js
  admin-dev/themes/new-theme/js/pages/product/services/combinations-service.js
  src/Adapter/Product/Combination/CommandHandler/RemoveCombinationCommandHandler.php
  src/Adapter/Product/Combination/Update/CombinationRemover.php
  src/Adapter/Product/Combination/Update/DefaultCombinationUpdater.php
  src/Core/Domain/Product/Combination/Command/RemoveCombinationCommand.php
  src/Core/Domain/Product/Combination/CommandHandler/RemoveCombinationCommandHandlerInterface.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationItemType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/FeatureValueType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/product_v2/combination.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_combination.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/GenerateCombinationFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/remove_combination.feature
Labels: 1.7.8.x, Feature, QA ✔️, Wording ✔️, migration

#24289 Fix visibility of constants
  src/Core/Domain/Carrier/Exception/CannotDeleteCarrierException.php
  src/Core/Domain/Carrier/Exception/CannotToggleCarrierStatusException.php
  src/Core/Domain/Carrier/Exception/CarrierConstraintException.php
  src/Core/Domain/ShowcaseCard/ValueObject/ShowcaseCard.php
  src/Core/Grid/Definition/Factory/CarrierGridDefinitionFactory.php
  src/PrestaShopBundle/Install/EntityLoader/FileLoader.php
Labels: Refactoring, develop

#24280 Add Js doc for Dashboad and modules pages
  tests/UI/pages/BO/dashboard/index.js
  tests/UI/pages/BO/modules/moduleCatalog/index.js
  tests/UI/pages/BO/modules/moduleConfiguration/index.js
  tests/UI/pages/BO/modules/moduleManager/index.js
  tests/UI/pages/BO/modules/psEmailSubscription/index.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring

#24168 Fix obvious bugs in product page
  admin-dev/themes/new-theme/js/pages/product/edit/index.js
  admin-dev/themes/new-theme/js/pages/product/edit/product-type-manager.js
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/VirtualProductFileCommandsBuilder.php
  src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Extension/DefaultEmptyDataExtension.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationStockType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/OptionsType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/ProductFormType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/ProductSupplierType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/ShortcutsType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/StockType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_extension.yml
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/VirtualProductFileCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProviderTest.php
Labels: 1.7.8.x, Bug fix, QA ✔️, migration

#24288 Refactoring addImagesToProduct function
  tests/UI/pages/BO/catalog/products/add.js
  tests/UI/pages/commonPage.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#23902 Take customizations into account when performing operations on orders
  admin-dev/themes/new-theme/js/pages/order/view/order-product-edit.js
  admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  src/Adapter/Cart/Comparator/CartProductUpdate.php
  src/Adapter/Cart/Comparator/CartProductsComparator.php
  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
  src/Adapter/Order/OrderProductQuantityUpdater.php
  src/Adapter/Order/Refund/OrderProductRemover.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/edit_product_row.html.twig
  tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature
  tests/Unit/Adapter/Cart/Comparator/CartProductsComparatorTest.php
Labels: 1.7.7.x, BC break, Bug fix, QA ✔️, Wording ✔️

#24286 Clear Module::getModuleIdByName_ when installing a module
  classes/module/Module.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#24305 Remove some modules when building docker for tests
  tests/UI/.docker/prestashop/docker_run.sh
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#24329 Bump version to 1.7.7.5
  app/AppKernel.php
  install-dev/install_version.php
Labels: 1.7.7.x, Improvement

#24310 Merge 1.7.7.x into 1.7.8.x [merge]
  admin-dev/themes/default/js/tree.js
  classes/Cart.php
  classes/CartRule.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/gift.feature
Labels: 1.7.8.x, Improvement

#24211 Make multistore dropdown appear in group shop context
  src/PrestaShopBundle/Controller/Admin/MultistoreController.php
  src/PrestaShopBundle/Resources/views/Admin/Multistore/dropdown.html.twig
  src/PrestaShopBundle/Service/Form/MultistoreCheckboxEnabler.php
  src/PrestaShopBundle/Service/Multistore/CustomizedConfigurationChecker.php
  tests/Unit/PrestaShopBundle/Service/Form/MultistoreCheckboxEnablerTest.php
  tests/Unit/PrestaShopBundle/Service/Multistore/CustomizedConfigurationCheckerTest.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#24213 Add missing product form hooks
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.8.0.sql
Labels: 1.7.8.x, Bug fix, QA ✔️, migration

#24274 Fix getting CLDR data when creating a new currency
  src/Core/Localization/CLDR/Currency.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#24325 Move notifications inside content wrapper to fix a regression
  themes/classic/templates/layouts/layout-both-columns.tpl
Labels: 1.7.8.x, Bug fix, QA ✔️

#24315 Fix quickview image size on FO
  themes/classic/_dev/css/components/quickview.scss
Labels: 1.7.8.x, Bug fix, QA ✔️

#24268 Enable translation export button only when export choices are made
  admin-dev/themes/new-theme/js/pages/translation-settings/ExportFormFieldToggle.js
  admin-dev/themes/new-theme/js/pages/translation-settings/TranslationSettingsMap.js
  src/PrestaShopBundle/Form/Admin/Improve/International/Translations/ExportCataloguesType.php
  src/PrestaShopBundle/Form/Admin/Type/RadioWithChoiceChildrenType.php
Labels: 1.7.8.x, Bug fix, QA ✔️, Wording ✔️

#24022 Register feature flag page hooks
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.8.0.sql
Labels: Improvement, QA ✔️, develop

#24269 Fix already selected condition group on safari inside catalog price rules
  admin-dev/themes/default/template/controllers/specific_price_rule/helpers/form/form.tpl
Labels: 1.7.7.x, Bug fix, QA ✔️

#24345 No alert displayed when we click on "Save then add another value" button
  controllers/admin/AdminFeaturesController.php
Labels: Improvement, QA ✔️, develop

#24270 Fix exception thrown in FO when category not active or doesn't exists
  controllers/front/listing/CategoryController.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#24328 Fwd: Customer message link is incorrect
  controllers/admin/AdminCustomerThreadsController.php
Labels: Bug fix, QA ✔️, develop

#24119 When saving an image as a square png, add always a transparent border
  classes/ImageManager.php
Labels: Bug fix, QA ✔️, develop

#24348 Use right link and add redirect
  themes/classic/modules/ps_customersignin/ps_customersignin.tpl
Labels: Improvement, QA ✔️, develop

#24366 Fix hooks tests (Nightly error)
  tests/UI/campaigns/functional/BO/08_design/05_positions/02_searchHook.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#24359 eMail Preview - wrong value in {total_products}
  src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php
Labels: Bug fix, QA ✔️, develop

#23492 Fixed Ecotax when editing an Order ((Add/Update)ProductToOrder)
  classes/Product.php
  classes/order/Order.php
  classes/order/OrderDetail.php
  src/Adapter/Order/OrderDetailUpdater.php
  tests/Integration/Behaviour/Features/Context/Configuration/CommonConfigurationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_combination.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_odd_tax.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_with_tax.feature
Labels: 1.7.7.x, Bug fix, QA ✔️

#24352 Search Conf Incorrect successful alert message
  controllers/admin/AdminSearchConfController.php
Labels: Bug fix, PM ✔️, QA ✔️, Wording ✔️, develop

#24377 Fix sanity workflow - Add repo to download libapache2
  .github/workflows/sanity/setup-apache.sh
Labels: 1.7.8.x, E2E Tests, Refactoring, TE

#24387 Merge 1.7.8.x into develop [merge]
  .github/workflows/sanity/setup-apache.sh
  admin-dev/themes/new-theme/js/components/auto-complete-search.js
  admin-dev/themes/new-theme/js/fos_js_routes.json
  admin-dev/themes/new-theme/js/pages/product/components/filters/Filters.vue
  admin-dev/themes/new-theme/js/pages/product/components/filters/index.js
  admin-dev/themes/new-theme/js/pages/product/components/generator/AttributesSelector.vue
  admin-dev/themes/new-theme/js/pages/product/components/generator/CombinationGenerator.vue
  admin-dev/themes/new-theme/js/pages/product/components/generator/index.js
  admin-dev/themes/new-theme/js/pages/product/edit/combinations-manager.js
  admin-dev/themes/new-theme/js/pages/product/edit/index.js
  admin-dev/themes/new-theme/js/pages/product/mixins/is-attribute-selected.js
  admin-dev/themes/new-theme/js/pages/product/product-map.js
  admin-dev/themes/new-theme/js/pages/product/services/attribute-groups.js
  admin-dev/themes/new-theme/js/pages/product/services/combinations-service.js
  admin-dev/themes/new-theme/js/pages/translation-settings/ExportFormFieldToggle.js
  admin-dev/themes/new-theme/js/vue/directives/click-outside.js
  controllers/front/listing/CategoryController.php
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.8.0.sql
  src/Adapter/Product/Combination/Create/CombinationCreator.php
  src/Adapter/Product/Combination/Repository/CombinationRepository.php
  src/Adapter/Product/Repository/ProductRepository.php
  src/Core/Localization/CLDR/Currency.php
  src/PrestaShopBundle/Controller/Admin/MultistoreController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Translations/ExportCataloguesType.php
  src/PrestaShopBundle/Form/Admin/Type/RadioWithChoiceChildrenType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/product_v2/combination.yml
  src/PrestaShopBundle/Resources/views/Admin/Multistore/dropdown.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/paginated_list.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Tabs/combinations.html.twig
  src/PrestaShopBundle/Service/Form/MultistoreCheckboxEnabler.php
  src/PrestaShopBundle/Service/Multistore/CustomizedConfigurationChecker.php
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/generate_combinations.feature
  tests/UI/campaigns/data/demo/attributes.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/01_CRUDAttributesAndValues.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/01_filterAttributes.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/04_bulkDeleteAttributes.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/attributes/01_filterAttributes.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/attributes/02_sortPaginationAndBulkDelete.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/attributes/03_changePosition.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/attributes/04_helperCard.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/values/01_filterValues.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/values/02_sortPaginationAndBulkDelete.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/values/03_changePosition.js
  tests/UI/pages/BO/catalog/attributes/index.js
  tests/UI/pages/BO/catalog/attributes/view.js
  tests/Unit/PrestaShopBundle/Service/Form/MultistoreCheckboxEnablerTest.php
  tests/Unit/PrestaShopBundle/Service/Multistore/CustomizedConfigurationCheckerTest.php
  themes/classic/_dev/css/components/quickview.scss
  themes/classic/templates/layouts/layout-both-columns.tpl
Labels: Improvement, develop

#23886 Add composer.json CS normalizer to CI
  .github/workflows/php.yml
  composer.json
  composer.lock
Labels: Feature, develop

#24285 Refacto shipping test pages for js-doc
  tests/UI/pages/BO/shipping/carriers/add.js
  tests/UI/pages/BO/shipping/carriers/index.js
  tests/UI/pages/BO/shipping/preferences/index.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#24273 Implement Address Format in the View Order Page
  src/Adapter/Address/AddressFormatter.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Order/QueryHandler/GetOrderPreviewHandler.php
  src/Core/Address/AddressFormatterInterface.php
  src/Core/Domain/Order/QueryResult/OrderForViewing.php
  src/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewing.php
  src/Core/Domain/Order/QueryResult/OrderPreview.php
  src/Core/Domain/Order/QueryResult/OrderPreviewInvoiceDetails.php
  src/Core/Domain/Order/QueryResult/OrderPreviewShippingDetails.php
  src/Core/Domain/Order/QueryResult/OrderShippingAddressForViewing.php
  src/PrestaShopBundle/Resources/config/services/adapter/address.yml
  src/PrestaShopBundle/Resources/config/services/adapter/order.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/preview.html.twig
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_address.feature
  tests/Unit/Core/Domain/Order/QueryResult/OrderForViewingTest.php
  tests/Unit/Core/Domain/Order/QueryResult/OrderPreviewTest.php
Labels: 1.7.7.x, Bug fix, Deprecations, QA ✔️

#23546 CategoryDataFactory : Avoid code duplicate
  src/Core/Grid/Data/Factory/AbstractCategoryDataFactory.php
  src/Core/Grid/Data/Factory/CategoryDataFactory.php
  src/Core/Grid/Data/Factory/EmptyCategoryGridDataFactory.php
Labels: QA ✔️, Refactoring, develop

#24116 Fix thumbnail regeneration for files other than jpg
  src/Adapter/Image/ImageRetriever.php
Labels: Bug fix, QA ✔️, develop

#24353 Fix module activation checkbox in module configuration pages
  admin-dev/themes/default/template/controllers/modules/configuration_bar.tpl
Labels: 1.7.7.x, Bug fix, QA ✔️

#24396 Fix nightly tests on develop for 07-05-2021
  tests/UI/campaigns/functional/BO/02_orders/01_orders/04_checkInvoiceDownloadedFromList.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/05_checkDeliverySlipDownloadedFromList.js
  tests/UI/campaigns/functional/BO/04_customers/02_addresses/06_setRequiredFields.js
  tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/01_activateMerchandiseReturn.js
  tests/UI/campaigns/functional/BO/11_international/02_locations/02_countries/02_CRUDCountry.js
  tests/UI/campaigns/functional/BO/11_international/02_locations/02_countries/05_countriesRestrictions.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/03_disableReorderingOption.js
  tests/UI/campaigns/functional/FO/03_userAccount/01_orderHistory/01_orderDetails/01_sendMessage.js
  tests/UI/campaigns/functional/FO/03_userAccount/02_CRUDAddress.js
  tests/UI/campaigns/functional/FO/03_userAccount/03_userDiscounts.js
  tests/UI/campaigns/functional/FO/03_userAccount/04_orderList.js
  tests/UI/campaigns/functional/FO/04_newsletter/01_subscribeNewsletter.js
  tests/UI/pages/BO/shopParameters/search/index.js
Labels: E2E Tests, Refactoring, TE, develop

#23138 Fix gift added/removed when editing order (product quantity/shipping address)
  admin-dev/themes/new-theme/js/pages/order/order-shipping-manager.js
  admin-dev/themes/new-theme/js/pages/order/view/order-discounts-refresher.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-edit.js
  admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js
  admin-dev/themes/new-theme/public/order_view.bundle.js
  classes/Cart.php
  classes/CartRule.php
  src/Adapter/Cart/Comparator/CartProductsComparator.php
  src/Adapter/Cart/QueryHandler/GetCartForOrderCreationHandler.php
  src/Adapter/Order/CommandHandler/ChangeOrderDeliveryAddressHandler.php
  src/Adapter/Order/OrderAmountUpdater.php
  src/Adapter/Order/OrderProductQuantityUpdater.php
  src/Adapter/Order/Refund/OrderProductRemover.php
  src/PrestaShopBundle/Resources/config/services/adapter/order.yml
  tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature
  tests/Unit/Adapter/Cart/Comparator/CartProductsComparatorTest.php
Labels: 1.7.7.x, BC break, Bug, Bug fix, QA ✔️

#24379 Fix smarty product lazy load exception
  classes/Product.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#24429 Do not remove modules pushed by API for UI tests
  tests/UI/.docker/prestashop/docker_run.sh
Labels: 1.7.8.x, Bug fix

#24356 Fix javascript error in console in multistore `create shop` page
  admin-dev/themes/default/js/tree.js
Labels: 1.7.8.x, Bug fix, QA ✔️

#24434 Remove order_view asset on 1.7.8.x
  admin-dev/themes/new-theme/public/order_view.bundle.js
Labels: 1.7.8.x, Bug fix

#24435 Fix click on toggle for seo and url page
  tests/UI/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/index.js
Labels: 1.7.8.x, E2E Tests, Refactoring, TE

#24430 Improve CartPresenter performance, and allow Order to retrieve default_image
  src/Adapter/Presenter/Cart/CartPresenter.php
  src/Adapter/Presenter/Order/OrderLazyArray.php
  themes/classic/templates/checkout/_partials/cart-summary-product-line.tpl
  themes/classic/templates/checkout/_partials/order-confirmation-table.tpl
Labels: 1.7.8.x, Bug fix, QA ✔️

#24457 Fix final summary exception
  themes/classic/templates/checkout/_partials/order-confirmation-table.tpl
Labels: 1.7.8.x, Bug fix, QA ✔️

#24455 Remove forgotten function description
  tests/UI/pages/FO/product/index.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#24239 Typo in head-jsonld.tpl, shop logo link: correction for #23151
  themes/classic/templates/_partials/microdata/head-jsonld.tpl
Labels: 1.7.8.x, Bug fix, QA ✔️, develop

#24426 Fix error on favicon when maintenance mode is enabled
  themes/classic/templates/layouts/layout-error.tpl
Labels: Bug fix, QA ✔️, develop

#24445 Fix click on a hidden checkbox on localization and translation page
  tests/UI/campaigns/functional/BO/11_international/04_translations/03_exportLanguage.js
  tests/UI/pages/BO/international/localization/index.js
  tests/UI/pages/BO/international/translations/index.js
  tests/UI/pages/commonPage.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring

#24462 Update js doc for customer service pages
  tests/UI/campaigns/data/faker/orderMessage.js
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/02_changeStatus.js
  tests/UI/pages/BO/customerService/customerService/index.js
  tests/UI/pages/BO/customerService/customerService/view.js
  tests/UI/pages/BO/customerService/merchandiseReturns/index.js
  tests/UI/pages/BO/customerService/orderMessages/add.js
  tests/UI/pages/BO/customerService/orderMessages/index.js
  tests/UI/pages/commonPage.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#24459 Wait For price to be updated on view order page
  tests/UI/pages/BO/orders/view.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#24461 Fix missing _this replacement with that
  admin-dev/themes/default/js/bundle/module/module_card.js
Labels: 1.7.8.x, Bug fix, QA ✔️

#24454 Functional tests - Fix and add tests for Features and Values
  tests/UI/campaigns/data/faker/featureAndValue.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/features/01_filterFeatures.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/features/02_sortPaginationAndBulkDelete.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/features/03_changePosition.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/features/04_helperCard.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/values/01_filterFeatureValues.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/values/02_sortPaginationAndBulkDelete.js
  tests/UI/pages/BO/catalog/features/addFeature.js
  tests/UI/pages/BO/catalog/features/addValue.js
  tests/UI/pages/BO/catalog/features/index.js
  tests/UI/pages/BO/catalog/features/view.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#24479 Fix php7.4 incompability warning
  controllers/admin/AdminStoresController.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#24500 Fix change customer message status
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/02_changeStatus.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring

#24506 Upgrade Symfony to 3.4.48
  composer.lock
Labels: 1.7.8.x, Bug fix

#24466 Added override/ & tools/ to PHPStan Check
  .github/workflows/phpstan/autoload.php
  phpstan.neon.dist
  src/Adapter/Product/AdminProductDataUpdater.php
  tools/build/CreateRelease.php
  tools/build/Library/InstallUnpacker/classes/Download.php
  tools/build/Library/InstallUnpacker/classes/InstallManager.php
  tools/build/Library/InstallUnpacker/classes/Unzip.php
  tools/build/Library/ReleaseCreator.php
  tools/build/Library/Version.php
  tools/foreignkeyGenerator/changes.php
  tools/foreignkeyGenerator/foreign.php
  tools/profiling/Controller.php
  tools/profiling/ObjectModel.php
  tools/profiling/Profiler.php
  tools/profiling/Tools.php
Labels: Improvement, develop

#24428 Correct logo size of classic theme
  themes/classic/_dev/css/components/header.scss
Labels: 1.7.8.x, Bug fix, QA ✔️

#24478 Functional tests - Fix and add tests for Brands and Addresses pages
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/01_CRUDBrandAndAddress.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/02_helperCard.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/04_BulkActionsBrands.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/05_BulkActionsBrandAddresses.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/06_paginationAndSortBrandsAndAddresses.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/addresses/01_filterAddresses.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/addresses/02_sortPaginationAndBulkActions.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/brands/01_filterAndQuickEditBrands.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/brands/02_sortPaginationAndBulkActions.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/brands/03_exportBrands.js
  tests/UI/pages/BO/catalog/brands/add.js
  tests/UI/pages/BO/catalog/brands/addAddress.js
  tests/UI/pages/BO/catalog/brands/index.js
  tests/UI/pages/BO/catalog/brands/view.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#24456 Fix js error in console in multistore mode
  admin-dev/themes/new-theme/js/components/multistore-dropdown.js
Labels: 1.7.8.x, Bug fix, QA ✔️

#24089 Improve Product getAttributesResume function for MySQL 8
  classes/Product.php
Labels: 1.7.8.x, Bug fix, Improvement, QA ✔️

#24375 Add new test 'Guest checkout: Use different invoice address'
  tests/UI/campaigns/functional/FO/11_checkout/02_addresses/02_useDifferentAddressForInvoice.js
  tests/UI/pages/FO/checkout/index.js
Labels: 1.7.8.x, E2E Tests, Refactoring, TE

#23863 Enable to extends module `card_list.html.twig` and use custom actions
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/card_list.html.twig
Labels: Improvement, QA ✔️, develop

#24427 Fixed wrong price of the delivery slip of the document list
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_documents.feature
Labels: 1.7.7.x, Bug fix, QA ✔️

#24525 Wrong usage of shopId property during installation process
  src/Adapter/EntityTranslation/EntityTranslator.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#24566 Add js-doc to faker data classes: Address, brand, brandAddress, carrier, attribute and value
  tests/UI/campaigns/data/faker/address.js
  tests/UI/campaigns/data/faker/attributeAndValue.js
  tests/UI/campaigns/data/faker/brand.js
  tests/UI/campaigns/data/faker/brandAddress.js
  tests/UI/campaigns/data/faker/carrier.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/01_CRUDAttributesAndValues.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/attributes/02_sortPaginationAndBulkDelete.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/values/02_sortPaginationAndBulkDelete.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring

#24527 Restricted to all shop context for Order Status controller
  controllers/admin/AdminLegacyLayoutController.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#24569 Add js-doc to faker data classes: tag, tax, taxRule, taxRuleGroup, title, webservice, zone
  tests/UI/campaigns/data/faker/tag.js
  tests/UI/campaigns/data/faker/tax.js
  tests/UI/campaigns/data/faker/taxRule.js
  tests/UI/campaigns/data/faker/taxRuleGroup.js
  tests/UI/campaigns/data/faker/title.js
  tests/UI/campaigns/data/faker/webservice.js
  tests/UI/campaigns/data/faker/zone.js
Labels: 1.7.8.x, E2E Tests, Refactoring, TE

#24540 Update license headers
  tests/Resources/assets_manager/core.js
  tests/Resources/assets_manager/css/custom.css
  tests/Resources/assets_manager/css/theme.css
  tests/Resources/assets_manager/custom.css
  tests/Resources/assets_manager/js/core.js
  tests/Resources/assets_manager/js/theme.js
  tests/Resources/assets_manager/theme.css
  tests/Resources/assets_manager/theme.js
  tests/Unit/Resources/module-self-config-files/php/MyComplexModuleConfiguration.php
  themes/classic/templates/checkout/_partials/cart-detailed-product-line.tpl
Labels: Improvement, develop

#24578 Fix test Handling charges and backport fixes for product quick view test
  tests/UI/campaigns/functional/BO/09_shipping/02_preferences/01_handling/01_handlingCharges.js
  tests/UI/pages/BO/catalog/products/add.js
  tests/UI/pages/FO/searchResults/index.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring

#24551 Update js documentation for shop parameters pages
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/returnStatuses/01_CRUDOrderReturnStatus.js
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/statuses/01_CRUDOrderStatus.js
  tests/UI/pages/BO/shopParameters/contact/add.js
  tests/UI/pages/BO/shopParameters/contact/index.js
  tests/UI/pages/BO/shopParameters/customerSettings/groups/add.js
  tests/UI/pages/BO/shopParameters/customerSettings/groups/index.js
  tests/UI/pages/BO/shopParameters/customerSettings/index.js
  tests/UI/pages/BO/shopParameters/customerSettings/titles/add.js
  tests/UI/pages/BO/shopParameters/customerSettings/titles/index.js
  tests/UI/pages/BO/shopParameters/general/index.js
  tests/UI/pages/BO/shopParameters/general/maintenance/index.js
  tests/UI/pages/BO/shopParameters/orderSettings/index.js
  tests/UI/pages/BO/shopParameters/orderSettings/statuses/add.js
  tests/UI/pages/BO/shopParameters/orderSettings/statuses/index.js
  tests/UI/pages/BO/shopParameters/orderSettings/statuses/returnStatus/add.js
  tests/UI/pages/BO/shopParameters/productSettings/index.js
  tests/UI/pages/BO/shopParameters/search/add.js
  tests/UI/pages/BO/shopParameters/search/index.js
  tests/UI/pages/BO/shopParameters/search/tags/add.js
  tests/UI/pages/BO/shopParameters/search/tags/index.js
  tests/UI/pages/BO/shopParameters/stores/add.js
  tests/UI/pages/BO/shopParameters/stores/index.js
  tests/UI/pages/BO/shopParameters/trafficAndSeo/searchEngines/add.js
  tests/UI/pages/BO/shopParameters/trafficAndSeo/searchEngines/index.js
  tests/UI/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/add.js
  tests/UI/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/index.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring

#24568 BO - Order Preview - Use the tracking number in tracking url
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Order/QueryHandler/GetOrderPreviewHandler.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_address.feature
Labels: 1.7.7.x, Bug fix, QA ✔️

#24586 Fix addons modules not being installed in CI
  app/config/config.yml
Labels: 1.7.8.x, Bug fix, Waiting for QA

#24592 Add `DbQueryCore` phpunit test
  classes/db/DbQuery.php
  tests/Unit/Classes/Db/DbQueryTest.php
Labels: Refactoring, TE, develop

#24579 BO - Order Messages - Avoid message with duplicate name
  src/Adapter/OrderMessage/CommandHandler/AddOrderMessageHandler.php
  src/Adapter/OrderMessage/CommandHandler/EditOrderMessageHandler.php
  src/Core/Domain/OrderMessage/Exception/OrderMessageNameAlreadyUsedException.php
  src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/OrderMessageController.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderMessageContext.php
  tests/Integration/Behaviour/Features/Scenario/OrderMessage/order_message_management.feature
  tests/Integration/Behaviour/behat.yml
Labels: 1.7.7.x, Bug fix, QA ✔️, Wording ✔️

#24601 Merge 177x into 178x
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Order/QueryHandler/GetOrderPreviewHandler.php
  src/Adapter/OrderMessage/CommandHandler/AddOrderMessageHandler.php
  src/Adapter/OrderMessage/CommandHandler/EditOrderMessageHandler.php
  src/Core/Domain/OrderMessage/Exception/OrderMessageNameAlreadyUsedException.php
  src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/OrderMessageController.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderMessageContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_address.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_documents.feature
  tests/Integration/Behaviour/Features/Scenario/OrderMessage/order_message_management.feature
  tests/Integration/Behaviour/behat.yml
  tests/UI/campaigns/functional/BO/09_shipping/02_preferences/01_handling/01_handlingCharges.js
Labels: 1.7.8.x, Improvement

#24618 Improve `Tools` protocol check
  classes/Tools.php
  tests/Unit/Classes/ToolsTest.php
Labels: Refactoring, develop

#24603 Add js-doc to faker data classes: search, searchEngine, seoPage, shop, shopGroup, sqlQuery, state, store, supplier
  tests/UI/campaigns/data/faker/search.js
  tests/UI/campaigns/data/faker/searchEngine.js
  tests/UI/campaigns/data/faker/seoPage.js
  tests/UI/campaigns/data/faker/shop.js
  tests/UI/campaigns/data/faker/shopGroup.js
  tests/UI/campaigns/data/faker/sqlQuery.js
  tests/UI/campaigns/data/faker/state.js
  tests/UI/campaigns/data/faker/store.js
  tests/UI/campaigns/data/faker/supplier.js
Labels: 1.7.8.x, E2E Tests, Refactoring

#24625 Fix PHP 7.4 - Cannot use "parent" when current class scope has no parent
  classes/module/Module.php
Labels: Bug fix, develop

#24565 Order View - Discount Modal - Disable submit until name is filled
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js
  admin-dev/themes/new-theme/js/pages/order/view.js
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/add_order_discount_modal.html.twig
Labels: 1.7.7.x, Bug fix, QA ✔️

#24628 Add router to defined javascript components
  admin-dev/themes/new-theme/js/app/utils/init-components.js
Labels: Refactoring, develop

#24642 Merge 177x into 178x
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js
  admin-dev/themes/new-theme/js/pages/order/view.js
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/add_order_discount_modal.html.twig
Labels: 1.7.8.x, Improvement

#24614 Fixed error message for avoiding duplicate order message name
  src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/OrderMessageController.php
Labels: 1.7.8.x, Improvement, QA ✔️, Wording ✔️

#24485 Fixed an error displayed in the console when changing the order status - Orders list page
  admin-dev/themes/new-theme/js/components/grid/extension/choice-extension.js
Labels: 1.7.8.x, Bug fix, QA ✔️

#24539 Added style for maintenance page
  themes/classic/_dev/css/error.scss
  themes/classic/_dev/webpack.config.js
Labels: 1.7.8.x, Bug fix, QA ✔️

#24611 Make sure array keys exist before using it for PHP7.4 compatibility
  classes/DateRange.php
  classes/ProductSupplier.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#24610 Fixed check on array in template Smarty
  themes/classic/templates/catalog/_partials/subcategories.tpl
Labels: 1.7.8.x, Bug fix, QA ✔️

#24541 Remove inline-style from form_row of the UIKit and adapt js
  admin-dev/themes/new-theme/js/components/country-state-selection-toggler.js
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit.html.twig
Labels: 1.7.8.x, Improvement, QA ✔️

#24627 Functional tests - Add test 'Contact options'
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/03_contactOptions.js
  tests/UI/pages/BO/customerService/customerService/index.js
  tests/UI/pages/FO/contactUs/index.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#24573 Fix title layout on order view page
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/header.html.twig
Labels: 1.7.8.x, Bug fix, QA ✔️

#24242 Fix upgrade from 1.6.1.24 to 1.7.8.x
  classes/Language.php
  install-dev/upgrade/php/migrate_tabs_17.php
  install-dev/upgrade/sql/1.7.8.0.sql
  src/Adapter/EntityTranslation/EntityTranslator.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#24648 Fix nightly tests on 1.7.8.x for 25/05/2021
  tests/UI/campaigns/data/faker/attributeAndValue.js
Labels: 1.7.8.x, E2E Tests, Refactoring

#24632 Wrong get and set data for employee options configuration
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Employee/EmployeeOptionsFormDataProvider.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#24355 Fix Multistore dropdown in current group context
  src/PrestaShopBundle/Controller/Admin/MultistoreController.php
Labels: 1.7.8.x, Bug fix, QA ✔️

#24649 Remove irrelevant "todo" reminder
  src/Core/Domain/Product/ValueObject/ProductType.php
Labels: Refactoring, develop

#24576 BO - New Order - Empty gift message is not a null value
  src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php
Labels: 1.7.7.x, Bug fix, QA ✔️

#24596 Fix primary buttons not being inline on Theme & Logo > Pages configurations
  admin-dev/themes/default/scss/controllers/_themes.scss
  admin-dev/themes/default/scss/partials/_buttons.scss
Labels: 1.7.8.x, Bug fix, QA ✔️

#24382 `GridColumn` add alignment `option`
  src/Core/Grid/Column/AbstractColumn.php
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/table.html.twig
Labels: Improvement, QA ✔️, develop

#24629 Test adapter `Validate::isUnsignedInt`
  tests/Unit/Adapter/ValidateTest.php
Labels: Improvement, develop

#24555 Fix for product combination quantity change in RTL panel
  src/PrestaShopBundle/Model/Product/AdminModelAdapter.php
Labels: Bug fix, QA ✔️, develop

#24580 Fix the alignment columns Features and Attributes
  admin-dev/themes/default/template/controllers/attributes/helpers/form/form.tpl
Labels: 1.7.8.x, Bug fix, QA ✔️

#24652 Functional tests - Add test merchandise return options
  tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/01_merchandiseReturnOptions.js
  tests/UI/pages/BO/customerService/merchandiseReturns/index.js
  tests/UI/pages/FO/myAccount/merchandiseReturns.js
  tests/UI/pages/FO/myAccount/orderDetails.js
Labels: 1.7.8.x, E2E Tests, QA ✔️, Refactoring, TE

#24253 Backport #23902 with new modal content
  admin-dev/themes/new-theme/js/pages/order/view/order-prices-refresher.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js
  admin-dev/themes/new-theme/js/pages/order/view/order-product-edit.js
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/edit_product_row.html.twig
Labels: 1.7.8.x, Bug fix, QA ✔️, Wording ✔️

#24677 Update vue-style-loader to fix scoped css bug
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
Labels: 1.7.8.x, Bug fix, QA ✔️

#24653 Remove abstract product handler
  src/Adapter/Product/AbstractProductHandler.php
  src/Adapter/Product/Combination/CommandHandler/GenerateProductCombinationsHandler.php
  src/Adapter/Product/Combination/QueryHandler/GetEditableCombinationsListHandler.php
  src/Adapter/Product/CommandHandler/AssociateProductAttachmentHandler.php
  src/Adapter/Product/CommandHandler/DeleteProductHandler.php
  src/Adapter/Product/CommandHandler/SetAssociatedProductAttachmentsHandler.php
  src/Adapter/Product/CommandHandler/UpdateProductSeoHandler.php
  src/Adapter/Product/CommandHandler/UpdateProductShippingHandler.php
  src/Adapter/Product/Pack/CommandHandler/RemoveAllProductsFromPackHandler.php
  src/Adapter/Product/Pack/CommandHandler/SetPackProductsHandler.php
  src/Adapter/Product/QueryHandler/GetProductForEditingHandler.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
Labels: 1.7.8.x, QA ✔️, Refactoring, migration

#24659 Improved profiler
  tools/profiling/Hook.php
  tools/profiling/Profiler.php
  tools/profiling/templates/hooks.tpl
  tools/profiling/templates/links.tpl
  tools/profiling/templates/modules.tpl
  tools/profiling/templates/styles.tpl
Labels: 1.7.8.x, Improvement, QA ✔️

#24678 Added admin-dev/ & some directories to PHPStan Check
  .github/workflows/phpstan/autoload.php
  admin-dev/ajax.php
  admin-dev/footer.inc.php
  admin-dev/functions.php
  admin-dev/index.php
  admin-dev/init.php
  app/config/set_parameters.php
  classes/Tools.php
  classes/controller/AdminController.php
  controllers/admin/AdminImportController.php
  phpstan.neon.dist
Labels: Improvement, develop

#16138 Fixed the bad discount amount for specific prices
  classes/product/SpecificPriceFormatter.php
  tests-legacy/Unit/Classes/Product/SpecificPriceFormatterTest.php
Labels: Bug, QA ✔️, develop

#24577 Customer Service page - A title section is not well displayed
  admin-dev/themes/default/template/controllers/customer_threads/helpers/view/view.tpl
Labels: 1.7.8.x, Bug fix, QA ✔️

#24283 Add info block background to order page
  admin-dev/themes/new-theme/scss/config/_settings.scss
  admin-dev/themes/new-theme/scss/pages/orders/_orders_main.scss
Labels: 1.7.8.x, BC break, Bug fix, QA ✔️

#23692 A lot of HTML errors are breaking DOM parsing
  admin-dev/themes/default/template/controllers/cart_rules/actions.tpl
  admin-dev/themes/default/template/controllers/cart_rules/conditions.tpl
  admin-dev/themes/default/template/controllers/cart_rules/informations.tpl
  admin-dev/themes/default/template/controllers/countries/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/customer_threads/message.tpl
  admin-dev/themes/default/template/controllers/modules/list.tpl
  admin-dev/themes/default/template/header.tpl
  admin-dev/themes/new-theme/template/components/layout/employee_dropdown.tpl
  admin-dev/themes/new-theme/template/layout.tpl
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combinations.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/Themes/categories_theme.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/shipping.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/typeahead.html.twig
  src/PrestaShopBundle/Resources/views/Admin/macros.html.twig
Labels: Bug fix, QA ✔️, Wording ✔️, develop

#24681 Update prestashop modules in composer.lock
  composer.lock
Labels: 1.7.8.x, Improvement, QA ✔️

#24690 Update Symfony to latest patch
  composer.lock
Labels: 1.7.8.x, Improvement, QA ✔️

#24447 Fix order view layout of right column
  admin-dev/themes/new-theme/scss/pages/orders/_orders_view.scss
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
Labels: 1.7.8.x, Bug fix, QA ✔️

#24697 Fix product stats alignment on order view page
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig
Labels: 1.7.8.x, Bug fix, QA ✔️

#24623 Refacto `TinyMceMaxLengthValidator`
  src/PrestaShopBundle/Form/Validator/Constraints/TinyMceMaxLength.php
  src/PrestaShopBundle/Form/Validator/Constraints/TinyMceMaxLengthValidator.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_validator.yml
  tests/Unit/PrestaShopBundle/Form/Validator/TinyMceMaxLengthValidatorTest.php
Labels: Refactoring, Wording ✔️, develop

#24679 Fix free shipping cart rule should not be recalculate when PS_ORDER_RECALCULATE_SHIPPING is false
  src/Adapter/Order/OrderAmountUpdater.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_shipping.feature
Labels: 1.7.7.x, Bug fix, QA ✔️

#24704 Merge 177x into 178x
  src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php
Labels: 1.7.8.x, Improvement

#24723 Fix domain wordings
  app/Resources/translations/default/AdminOrderscustomersNotification.xlf
  app/Resources/translations/default/ShopThemeCatalog.xlf
  src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/OrderMessageController.php
  themes/classic/modules/ps_brandlist/views/templates/hook/ps_brandlist.tpl
Labels: 1.7.8.x, Bug fix
