Repository PrestaShop/PrestaShop, pull requests merged in 2021-10, with the labels that each got.

#26026 BO: Fix the search button wrap
  admin-dev/themes/new-theme/scss/components/_grid.scss
Labels: QA ✔️, Bug fix, 1.7.8.x

#25988 Removed phake/phake as dev dependency
  composer.json
  composer.lock
  tests-legacy/Unit/ContextMocker.php
Labels: develop, Refactoring

#26047 Fix bugs that occur in CI because of non-resilient code
  classes/module/Module.php
  src/Adapter/Presenter/Module/ModulePresenter.php
Labels: develop, Bug fix

#26049 Update Symfony v4.4.32
  composer.lock
Labels: Improvement, develop

#25923 Update Readme
  README.md
Labels: Improvement, develop

#26043 Remove bad deprecated comment
  classes/Tools.php
Labels: develop, Bug fix

#25834 Fix the StoreController and add missing data
  controllers/front/StoresController.php
Labels: QA ✔️, develop, Bug fix

#25066 Removed links in employee menu & Added hook for adding links
  admin-dev/themes/default/template/header.tpl
  admin-dev/themes/new-theme/template/components/layout/employee_dropdown.tpl
  classes/controller/AdminController.php
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.9.0.sql
  src/PrestaShopBundle/Component/ActionBar/ActionsBarButton.php
  src/PrestaShopBundle/Component/ActionBar/ActionsBarButtonInterface.php
  src/PrestaShopBundle/Component/ActionBar/ActionsBarButtonsCollection.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
Labels: Improvement, QA ✔️, develop

#26057 Update 1.8 into 8.0 version
  src/PrestaShopBundle/Resources/config/services/adapter/admin.yml
Labels: Improvement, develop

#26078 Merge 178x into develop [merge]
  admin-dev/themes/new-theme/scss/components/_grid.scss
  classes/Cart.php
  themes/classic/templates/_partials/microdata/product-jsonld.tpl
Labels: develop, Bug fix

#25857 Fetch and set logo image size inside template
  classes/controller/FrontController.php
  themes/classic/templates/_partials/header.tpl
  themes/classic/templates/_partials/microdata/head-jsonld.tpl
  themes/classic/templates/checkout/_partials/header.tpl
Labels: QA ✔️, develop, Bug fix, BC break

#26079 Fixing titles, steps and comments on FO tests
  tests/UI/campaigns/functional/FO/01_login/01_passwordReminder.js
  tests/UI/campaigns/functional/FO/02_headerAndFooter/01_checkLinksInHeader.js
  tests/UI/campaigns/functional/FO/02_headerAndFooter/02_checkLinksInFooter.js
  tests/UI/campaigns/functional/FO/03_userAccount/01_editInformation.js
  tests/UI/campaigns/functional/FO/03_userAccount/02_CRUDAddress.js
  tests/UI/campaigns/functional/FO/03_userAccount/03_userDiscounts.js
  tests/UI/campaigns/functional/FO/03_userAccount/04_orderList.js
  tests/UI/campaigns/functional/FO/03_userAccount/08_orderHistory/01_reorderFromOrderList.js
  tests/UI/campaigns/functional/FO/03_userAccount/08_orderHistory/04_orderDetails/01_sendMessage.js
  tests/UI/campaigns/functional/FO/03_userAccount/08_orderHistory/04_orderDetails/02_reorderFromOrderDetail.js
  tests/UI/campaigns/functional/FO/04_newsletter/01_subscribeNewsletter.js
  tests/UI/campaigns/functional/FO/05_contactUs/01_checkMailtoLink.js
  tests/UI/campaigns/functional/FO/05_contactUs/02_sendMessageWithCustomer.js
  tests/UI/campaigns/functional/FO/07_search/01_consultAutocompleteList.js
  tests/UI/campaigns/functional/FO/07_search/01_searchProduct.js
  tests/UI/campaigns/functional/FO/08_menuAndNavigation/01_consultCategoriesInHeader.js
  tests/UI/campaigns/functional/FO/09_productPage/01_quickView.js
  tests/UI/campaigns/functional/FO/09_productPage/02_addToCart.js
  tests/UI/campaigns/functional/FO/11_checkout/02_addresses/02_useDifferentAddressForInvoice.js
  tests/UI/campaigns/functional/FO/12_orderConfirmation/05_contactUs.js
  tests/UI/campaigns/utils/globals.js
  tests/UI/campaigns/utils/helpers.js
  tests/UI/pages/FO/product/index.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#26110 Fix selectors for db backup page
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Backup/Blocks/download_file.html.twig
  tests/UI/pages/BO/advancedParameters/database/dbBackup/index.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#26085 Update changelog for 1780 RC1 Build6
  docs/CHANGELOG.txt
Labels: Improvement, 1.7.8.x

#26112 Functional tests - Refacto shop parameters general
  tests/UI/campaigns/functional/BO/13_shopParameters/01_general/general/08_enableDisableSuppliers.js
  tests/UI/campaigns/functional/BO/13_shopParameters/01_general/general/09_enableDisableBrands.js
  tests/UI/campaigns/functional/BO/13_shopParameters/01_general/general/11_enableDisableMultistore.js
  tests/UI/campaigns/functional/BO/13_shopParameters/01_general/maintenance/01_enableDisableShop.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#26115 Merge 1.7.8.0-build into 1.7.8.x
  CONTRIBUTORS.md
  classes/shop/Shop.php
  docs/CHANGELOG.txt
  install-dev/controllers/console/process.php
Labels: Bug fix, 1.7.8.x

#26118 Change material-icons library causing a too long install
  admin-dev/themes/default/package-lock.json
  admin-dev/themes/default/package.json
  admin-dev/themes/default/scss/font.scss
Labels: QA ✔️, develop, Bug fix, Hacktoberfest

#25903 Fixed preview of product in frontoffice
  controllers/front/ProductController.php
Labels: QA ✔️, Bug fix, 1.7.8.x

#26042 Allow # ° ... for credit slip prefix
  src/PrestaShopBundle/Form/Admin/Sell/Order/CreditSlip/CreditSlipOptionsType.php
Labels: QA ✔️, develop, Bug fix
