Repository PrestaShop/PrestaShop, pull requests merged in 2021-01, with the labels that each got.

#22641 Behat github actions names swapped
  .github/workflows/behat.yml
Labels: Improvement, develop

#22548 Update phpstan to 0.12.64
  composer.lock
  phpstan.neon.dist
  src/Adapter/CustomerService/QueryHandler/GetCustomerThreadForViewingHandler.php
  src/Adapter/Import/Handler/ProductImportHandler.php
  src/Adapter/Presenter/Order/OrderDetailLazyArray.php
  src/Core/Addon/Module/ModuleManager.php
  src/Core/Grid/Collection/AbstractCollection.php
  src/PrestaShopBundle/Controller/Admin/CombinationController.php
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Install/SimplexmlElement.php
  src/PrestaShopBundle/Install/Upgrade.php
Labels: Improvement, develop

#21065 Add '-' to checkout's summary subtotal if it is discount type
  themes/classic/templates/checkout/_partials/cart-summary-subtotals.tpl
Labels: Bug, QA ✔️, develop

#22579 Prevent HookDataCollector unserialize() to throw an exception
  src/PrestaShopBundle/DataCollector/HookDataCollector.php
Labels: 1.7.7.x, Bug, QA ✔️

#22462 Improve multiple choice table : Add option to keep table heads fixed
  admin-dev/themes/new-theme/scss/components/_choice_table.scss
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Webservice/WebserviceKeyType.php
  src/PrestaShopBundle/Form/Admin/Improve/Payment/Preferences/PaymentModulePreferencesType.php
  src/PrestaShopBundle/Form/Admin/Type/Material/MaterialMultipleChoiceTableType.php
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: Improvement, PM ✔️, QA ✔️, develop

#22519 Adjust notifications pan on mobile
  admin-dev/themes/new-theme/scss/components/_notifications.scss
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
Labels: Bug, QA ✔️, develop

#22670 Set leading zero to always and remove cache
  admin-dev/themes/new-theme/.stylelintrc
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
  admin-dev/themes/new-theme/scss/components/_cards.scss
  admin-dev/themes/new-theme/scss/components/_category_tree.scss
  admin-dev/themes/new-theme/scss/components/_form_popover_error.scss
  admin-dev/themes/new-theme/scss/components/_hint_box.scss
  admin-dev/themes/new-theme/scss/components/_material_choice_tree.scss
  admin-dev/themes/new-theme/scss/components/_ps_alert.scss
  admin-dev/themes/new-theme/scss/components/_ps_radio.scss
  admin-dev/themes/new-theme/scss/components/_ps_tree.scss
  admin-dev/themes/new-theme/scss/components/_showcase-card.scss
  admin-dev/themes/new-theme/scss/components/_tinymce.scss
  admin-dev/themes/new-theme/scss/components/_toggable_field.scss
  admin-dev/themes/new-theme/scss/components/_translatable_input.scss
  admin-dev/themes/new-theme/scss/components/layout/_non_responsive.scss
  admin-dev/themes/new-theme/scss/mixins/_cards.scss
  admin-dev/themes/new-theme/scss/mixins/_notification_counter.scss
  admin-dev/themes/new-theme/scss/mixins/_stars.scss
  admin-dev/themes/new-theme/scss/pages/_invoices.scss
  admin-dev/themes/new-theme/scss/pages/_themes_logo.scss
  admin-dev/themes/new-theme/scss/pages/orders/_orders_create.scss
  admin-dev/themes/new-theme/scss/pages/partials/_order-navigation.scss
  themes/classic/_dev/.stylelintrc
  themes/classic/_dev/css/components/featuredproducts.scss
  themes/classic/_dev/package-lock.json
  themes/classic/_dev/package.json
Labels: Improvement, develop

#21623 Fix help text not displayed in form_row
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_horizontal_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/macros.html.twig
Labels: Bug, QA ✔️, develop

#22479 Adjust BO menu on responsive (font-sizes, margins, closing cross, signout)
  admin-dev/themes/default/sass/partials/_nav.sass
  admin-dev/themes/new-theme/scss/components/layout/_nav_bar.scss
Labels: Improvement, QA ✔️, develop

#22539 Show help message for PageNotFound for ajax calls
  controllers/front/PageNotFoundController.php
Labels: Improvement, QA ✔️, Wording ✔️, develop

#21923 Simplified currency form
  admin-dev/themes/new-theme/js/pages/currency/form/index.js
  src/Core/Form/IdentifiableObject/DataProvider/CurrencyFormDataProvider.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Currencies/CurrencyExchangeRateType.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Currencies/CurrencyType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Currency/Blocks/exchange_rates.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Currency/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: QA ✔️, Refactoring, Wording ✔️, develop, migration

#22696 IN: Fix inheritdoc annotation
  install-dev/fixtures/fashion/install.php
Labels: Improvement, develop

#22570 Migrate sanity tests to github actions
  .github/workflows/sanity.yml
  .github/workflows/sanity/apache-vhost
  .github/workflows/sanity/setup-apache.sh
  .travis.yml
  tests/UI/README.md
  tests/UI/campaigns/utils/globals.js
  tests/UI/campaigns/utils/helpers.js
  tests/UI/campaigns/utils/setup.js
  tests/UI/package.json
  tests/check_e2e.sh
  tests/check_sanity.sh
  tests/travis-ci-apache-vhost
  travis-scripts/.composer-auth.json
  travis-scripts/install-prestashop
  travis-scripts/run-functional-tests
  travis-scripts/run-sanity-tests
  travis-scripts/setup-apache.sh
  travis-scripts/setup-node-js.sh
  travis-scripts/setup-php-fpm.sh
  travis-scripts/start-xvfb
Labels: Refactoring, TE, develop

#22585 AdminStats Controller use the good column for total
  controllers/admin/AdminStatsController.php
Labels: Bug, QA ✔️, develop

#22663 Integrate product shipping form and related command
  admin-dev/themes/new-theme/js/pages/product/edit/product-partial-updater.js
  src/Adapter/Product/CommandHandler/UpdateProductShippingHandler.php
  src/Core/ConstraintValidator/Constraints/PositiveOrZero.php
  src/Core/ConstraintValidator/PositiveOrZeroValidator.php
  src/Core/Domain/Product/Command/UpdateProductShippingCommand.php
  src/Core/Domain/Product/QueryResult/ProductShippingInformation.php
  src/Core/Domain/Product/ValueObject/DeliveryTimeNoteType.php
  src/Core/Form/ChoiceProvider/DeliveryTimeNoteTypesProvider.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/ShippingCommandBuilder.php
  src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/ProductType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/ShippingType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/choice_provider.yml
  src/PrestaShopBundle/Resources/config/services/core/form/command_builder.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/tabs.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/edit.html.twig
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateShippingFeatureContext.php
  tests/Unit/Core/ConstraintValidator/PositiveOrZeroValidatorTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/ShippingCommandBuilderTest.php
Labels: Refactoring, develop, migration

#22659 Add test 'Sort carriers by' in FO
  tests/UI/campaigns/functional/BO/09_shipping/02_preferences/02_carrierOptions/02_updateCarriersSortOption.js
  tests/UI/pages/BO/shipping/preferences/index.js
  tests/UI/pages/FO/checkout/index.js
Labels: QA ✔️, Refactoring, TE, develop

#22684 Add test 'Countries restrictions'
  tests/UI/campaigns/data/demo/countries.js
  tests/UI/campaigns/functional/BO/11_international/02_locations/02_countries/05_countriesRestrictions.js
  tests/UI/pages/BO/international/locations/countries/index.js
Labels: QA ✔️, Refactoring, TE, develop

#22477 Added form theme to the address required fields
  src/PrestaShopBundle/Resources/views/Admin/Sell/Address/Blocks/required_fields.html.twig
Labels: QA ✔️, Refactoring, develop, migration

#22714 Remove file diff-hooks.php
  diff-hooks.php
Labels: Improvement, develop

#22708 Fix http link in composer.json
  composer.json
Labels: Improvement, develop

#22526 Change color of view website and add icon color on hover
  admin-dev/themes/default/sass/partials/_header.sass
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
Labels: Bug, QA ✔️, develop

#22723 Fix scss for linter
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
Labels: Bug, CI/CD, develop

#22727 Disable GitHub Actions fail fast
  .github/workflows/behat.yml
  .github/workflows/php.yml
  .github/workflows/sanity.yml
Labels: CI/CD, Improvement, develop

#22734 Fix nightly develop - 08/01/2021 (successful update message in countries page)
  tests/UI/campaigns/functional/BO/11_international/02_locations/02_countries/05_countriesRestrictions.js
  tests/UI/pages/BO/international/locations/countries/index.js
Labels: Refactoring, TE, develop

#22702 Add /var/lib/php/sessions folder to github actions
  .github/workflows/sanity.yml
Labels: Refactoring, TE, develop

#22722 Move attribute group services into proper namespace
  src/Adapter/Product/AttributeGroup/AbstractAttributeGroupHandler.php
  src/Adapter/Product/AttributeGroup/AttributeGroupViewDataProvider.php
  src/Adapter/Product/AttributeGroup/CommandHandler/BulkDeleteAttributeGroupHandler.php
  src/Adapter/Product/AttributeGroup/CommandHandler/DeleteAttributeGroupHandler.php
  src/PrestaShopBundle/Resources/config/services/adapter/attribute_group.yml
  src/PrestaShopBundle/Resources/config/services/core/attribute_group.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
Labels: Refactoring, develop, migration

#22726 Move virtual product file namespace into product sub namespace
  src/Adapter/Product/QueryHandler/GetProductForEditingHandler.php
  src/Adapter/Product/Validate/ProductDownloadValidator.php
  src/Adapter/Product/VirtualProductFile/CommandHandler/AddVirtualProductFileHandler.php
  src/Adapter/Product/VirtualProductFile/Repository/VirtualProductFileRepository.php
  src/Adapter/Product/VirtualProductFile/Update/VirtualProductUpdater.php
  src/Adapter/Product/VirtualProductFile/Uploader/VirtualProductFileUploader.php
  src/Adapter/Product/VirtualProductFile/Validate/VirtualProductFileValidator.php
  src/Adapter/Product/VirtualProductFile/Validator/VirtualProductFileValidator.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_virtual_product_file.yml
  tests/Unit/Adapter/File/Validator/VirtualProductFileValidatorTest.php
Labels: Refactoring, develop, migration

#22725 Move image namespace into product sub namespace
  src/Adapter/Product/Image/CommandHandler/AddProductImageHandler.php
  src/Adapter/Product/Image/ProductImagePathFactory.php
  src/Adapter/Product/Image/QueryHandler/GetProductImagesHandler.php
  src/Adapter/Product/Image/Repository/ProductImageRepository.php
  src/Adapter/Product/Image/Uploader/ProductImageUploader.php
  src/Core/Domain/Product/Image/Command/AddProductImageCommand.php
  src/Core/Domain/Product/Image/CommandHandler/AddProductImageHandlerInterface.php
  src/Core/Domain/Product/Image/Query/GetProductImages.php
  src/Core/Domain/Product/Image/QueryHandler/GetProductImagesHandlerInterface.php
  src/Core/Domain/Product/Image/QueryResult/ProductImage.php
  src/PrestaShopBundle/Resources/config/services/adapter/image.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_image.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php
Labels: Refactoring, develop, migration

#22474 Simplify brand and brand address forms
  admin-dev/themes/new-theme/js/pages/manufacturer/index.js
  src/PrestaShopBundle/Form/Admin/Sell/Address/ManufacturerAddressType.php
  src/PrestaShopBundle/Form/Admin/Sell/Manufacturer/ManufacturerType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Manufacturer/Address/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Manufacturer/Blocks/form.html.twig
Labels: QA ✔️, Refactoring, Wording ✔️, develop, migration

#22718 Move combination namespace into product sub namespace
  src/Adapter/Product/Combination/CommandHandler/GenerateProductCombinationsHandler.php
  src/Adapter/Product/Combination/CommandHandler/UpdateCombinationDetailsHandler.php
  src/Adapter/Product/Combination/CommandHandler/UpdateCombinationPricesHandler.php
  src/Adapter/Product/Combination/CommandHandler/UpdateCombinationStockHandler.php
  src/Adapter/Product/Combination/Create/CombinationCreator.php
  src/Adapter/Product/Combination/QueryHandler/GetCombinationForEditingHandler.php
  src/Adapter/Product/Combination/QueryHandler/GetEditableCombinationsListHandler.php
  src/Adapter/Product/Combination/Repository/CombinationRepository.php
  src/Adapter/Product/Combination/Update/CombinationStockUpdater.php
  src/Adapter/Product/Combination/Validate/CombinationValidator.php
  src/Core/Product/Combination/Generator/CombinationGenerator.php
  src/Core/Product/Combination/Generator/CombinationGeneratorInterface.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_combination.yml
  src/PrestaShopBundle/Resources/config/services/bundle/services.yml
  src/PrestaShopBundle/Resources/config/services/core/product.yml
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/generate_combinations.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/update_combination_details.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/update_combination_prices.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/update_combination_stock.feature
  tests/Unit/Core/Product/Combination/Generator/CombinationGeneratorTest.php
Labels: Refactoring, develop, migration

#22745 Move stock services into proper namespace
  src/Adapter/Product/Combination/QueryHandler/GetCombinationForEditingHandler.php
  src/Adapter/Product/Combination/QueryHandler/GetEditableCombinationsListHandler.php
  src/Adapter/Product/Combination/Update/CombinationStockUpdater.php
  src/Adapter/Product/QueryHandler/GetProductForEditingHandler.php
  src/Adapter/Product/Stock/Repository/StockAvailableRepository.php
  src/Adapter/Product/Stock/Validate/StockAvailableValidator.php
  src/Adapter/Product/Update/ProductStockUpdater.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_combination.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_stock.yml
Labels: Refactoring, develop, migration

#22717 Change import file test to import attributes instead of customers
  tests/UI/campaigns/data/demo/customer.js
  tests/UI/campaigns/data/demo/sampleFiles.js
  tests/UI/campaigns/functional/BO/14_advancedParameters/05_import/02_importFile.js
Labels: QA ✔️, Refactoring, TE, develop

#22738 Add new FO test 'CRUD Address in FO'
  tests/UI/campaigns/functional/FO/03_userAccount/02_CRUDAddress.js
  tests/UI/pages/FO/FObasePage.js
  tests/UI/pages/FO/myAccount/addAddress.js
  tests/UI/pages/FO/myAccount/addresses.js
  tests/UI/pages/FO/myAccount/identity.js
Labels: QA ✔️, Refactoring, TE, develop

#22686 Add more data to actionProductCancel hook
  src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php
  src/Adapter/Order/CommandHandler/IssuePartialRefundHandler.php
  src/Adapter/Order/CommandHandler/IssueReturnProductHandler.php
  src/Adapter/Order/CommandHandler/IssueStandardRefundHandler.php
Labels: Improvement, QA ✔️, develop

#21249 Make sure the force ssl is used in Cookie class when we are in admin context
  config/config.inc.php
  src/Adapter/Preferences/PreferencesConfiguration.php
  tests/Unit/Adapter/Preferences/PreferencesConfigurationTest.php
Labels: Bug, QA ✔️, Wording ✔️, develop

#22349 Hide recommended modules and help on mobile view in the BO
  admin-dev/themes/new-theme/scss/components/layout/_header_toolbar.scss
  admin-dev/themes/new-theme/scss/pages/product/products_catalog.scss
  admin-dev/themes/new-theme/template/page_header_toolbar.tpl
  controllers/admin/AdminLegacyLayoutController.php
Labels: Improvement, QA ✔️, develop

#22742 Fix some width and spacing of kpis pan
  admin-dev/themes/new-theme/scss/components/layout/_kpi.scss
Labels: Bug, QA ✔️, develop

#22550 Changelog 1.7.7.1
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: 1.7.7.x, Improvement

#22764 Introduce phpstan extension
  .github/workflows/phpstan/list.php
  composer.json
  composer.lock
  phpstan.neon.dist
  src/Adapter/Product/AttributeGroup/AbstractAttributeGroupHandler.php
  src/Adapter/Product/AttributeGroup/AttributeGroupViewDataProvider.php
  src/Adapter/Product/AttributeGroup/CommandHandler/BulkDeleteAttributeGroupHandler.php
  src/Adapter/Product/AttributeGroup/CommandHandler/DeleteAttributeGroupHandler.php
  src/Adapter/Product/SpecificPrice/CommandHandler/AddProductSpecificPriceHandler.php
  src/Core/Domain/Product/Exception/ProductCustomizationNotFoundException.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/OptionsType.php
Labels: CI/CD, Feature, develop

#22518 Define when a voucher should be displayed in 'Your vouchers'
  admin-dev/themes/default/template/controllers/cart_rules/informations.tpl
  classes/CartRule.php
  js/admin.js
Labels: 1.7.7.x, Bug, QA ✔️

#22749 Remove useless redirection on shop logo in multilingual context
  themes/classic/templates/_partials/header.tpl
  themes/classic/templates/checkout/_partials/header.tpl
Labels: Improvement, QA ✔️, develop

#22542 Handle case where product location is a boolean
  classes/Product.php
Labels: 1.7.7.x, Bug, QA ✔️

#22691 Fix stock page responsive
  admin-dev/themes/new-theme/js/app/pages/stock/components/header/filters/low-filter.vue
  admin-dev/themes/new-theme/scss/pages/stock/stock_page.scss
Labels: Bug, QA ✔️, develop

#22735 Fix installation carrier delay Error for Persian Language
  install-dev/fixtures/fashion/langs/fa/data/carrier.xml
Labels: 1.7.7.x, Bug, QA ✔️

#19996 Simplify Suppliers form
  admin-dev/themes/new-theme/js/app/utils/init-components.js
  admin-dev/themes/new-theme/js/pages/supplier/supplier-form.js
  src/PrestaShopBundle/Form/Admin/Sell/Supplier/SupplierType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Suppliers/Blocks/form.html.twig
Labels: QA ✔️, Refactoring, Wording ✔️, develop

#22656 Delete UI upgrade test
  tests/UI/DOCKER.md
  tests/UI/README.md
  tests/UI/campaigns/upgrade/upgradeShop.js
  tests/UI/pages/BO/modules/autoUpgrade/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#22673 PerfectScrollBar needs available element
  admin-dev/themes/default/js/theme.js
  admin-dev/themes/default/public/bundle.js
  admin-dev/themes/new-theme/js/nav_bar.js
  admin-dev/themes/new-theme/public/currency_form.bundle.js
  admin-dev/themes/new-theme/public/main.bundle.js
Labels: 1.7.7.x, Bug, QA ✔️

#22685 Create Order - Cart details modal - Fix refresh for cart total
  classes/Cart.php
  controllers/admin/AdminStatsController.php
  src/Adapter/Kpi/ShoppingCartTotalKpi.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php
Labels: 1.7.7.x, Bug, QA ✔️

#22378 Get rid of empty string of redirect type from database structure
  install-dev/data/db_structure.sql
  install-dev/upgrade/sql/1.7.8.0.sql
Labels: BC break, QA ✔️, Refactoring, develop, migration

#22436 Update legacy pages style in order to collapse a bit more to the UIKit
  admin-dev/themes/default/sass/admin-theme.sass
  admin-dev/themes/default/sass/modules/_variables.sass
  admin-dev/themes/default/sass/partials/_buttons.sass
  admin-dev/themes/default/sass/partials/_commons.sass
  admin-dev/themes/default/sass/partials/_content.sass
  admin-dev/themes/default/sass/partials/_forms.sass
  admin-dev/themes/default/sass/vendor/bootstrap-sass/_buttons.scss
Labels: Improvement, QA ✔️, develop

#22678 Fix nightly 1.7.7.x - 05/01/2021
  tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/01_activateMerchandiseReturn.js
  tests/UI/pages/BO/orders/view.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#22688 Prevent HookDataCollector unserialize() to throw an exception
  src/PrestaShopBundle/DataCollector/HookDataCollector.php
Labels: 1.7.7.x, Bug, QA ✔️

#22316 Add confirm modal on module update
  admin-dev/themes/new-theme/js/components/modal.js
  admin-dev/themes/new-theme/js/components/module-card.js
  admin-dev/themes/new-theme/js/pages/module/controller.js
  src/PrestaShopBundle/Resources/views/Admin/Module/common.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop

#22619 Fix invisible input in SEO Options
  src/Adapter/Meta/SEOOptionsDataConfiguration.php
Labels: Bug, QA ✔️, develop

#22223 Be able to don't add anchor in the URL for getProductLink method
  classes/Link.php
Labels: Improvement, QA ✔️, develop

#22556 Fix nightly 1.7.7.x - 23/12/2020
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/01_viewCustomerService.js
  tests/UI/pages/BO/customerService/customerService/index.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#22698 Module manager page needs some adjusts on mobile
  admin-dev/themes/new-theme/scss/pages/_modules.scss
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/modal_read_more_content.html.twig
Labels: Bug, QA ✔️, develop

#22795 Fix phpstan CI on develop
  src/Core/Grid/Column/Type/Currency/NameColumn.php
Labels: Bug, develop

#22780 Improve Category::getProducts : Avoid short variable names
  classes/Category.php
Labels: Improvement, develop

#21491 Add id_product_attribute to order conf mails
  classes/PaymentModule.php
  src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php
Labels: Improvement, PM ✔️, QA ✔️, develop

#22792 Backport UI tests for 1.7.7.2
  tests/UI/campaigns/data/demo/countries.js
  tests/UI/campaigns/data/demo/customer.js
  tests/UI/campaigns/data/demo/sampleFiles.js
  tests/UI/campaigns/functional/BO/09_shipping/02_preferences/02_carrierOptions/02_updateCarriersSortOption.js
  tests/UI/campaigns/functional/BO/11_international/02_locations/02_countries/05_countriesRestrictions.js
  tests/UI/campaigns/functional/BO/14_advancedParameters/05_import/02_importFile.js
  tests/UI/campaigns/functional/FO/03_userAccount/02_CRUDAddress.js
  tests/UI/pages/BO/international/locations/countries/index.js
  tests/UI/pages/BO/shipping/preferences/index.js
  tests/UI/pages/FO/FObasePage.js
  tests/UI/pages/FO/checkout/index.js
  tests/UI/pages/FO/myAccount/addAddress.js
  tests/UI/pages/FO/myAccount/addresses.js
  tests/UI/pages/FO/myAccount/identity.js
Labels: 1.7.7.x, Refactoring, TE

#22766 Improve ProductCommandBuilderInterface for multi return
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/BasicInformationCommandBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/OptionsCommandBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandBuilderInterface.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandCollection.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/ShippingCommandBuilder.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/BasicInformationCommandBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductOptionsCommandBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/ShippingCommandBuilderTest.php
Labels: Improvement, develop, migration

#22707 Add test 'Filter, sort and pagination currencies'
  tests/UI/campaigns/data/demo/currencies.js
  tests/UI/campaigns/functional/BO/11_international/01_localization/currencies/05_filterSortAndPagination.js
  tests/UI/pages/BO/international/currencies/index.js
Labels: QA ✔️, Refactoring, TE, develop

#22793 Upgrade playwright to 1.6.2
  tests/UI/package-lock.json
  tests/UI/package.json
Labels: QA ✔️, Refactoring, TE, develop

#22777 Allow extra fields in product combinations
  src/PrestaShopBundle/Controller/Admin/ProductController.php
Labels: Bug, QA ✔️, develop

#22761 Fix mobile dropdown of multishop context on default theme of the BO
  admin-dev/themes/default/sass/partials/_header.sass
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
Labels: Bug, QA ✔️, develop

#22807 Adjust payment page responsive
  admin-dev/themes/new-theme/scss/pages/_payment.scss
  admin-dev/themes/new-theme/scss/theme.scss
Labels: Bug, QA ✔️, develop

#22588 Added cron for dumping JS Routing
  .github/workflows/cron_js_routing.yml
Labels: Improvement, develop

#22845 Fixed body in Cron Update JS Routing
  .github/workflows/cron_js_routing.yml
Labels: Bug, develop

#22820 Update Setup PHP Actions to v2
  .github/workflows/lint.yml
  .github/workflows/php.yml
Labels: Improvement, develop

#22808 Do not log addons requests urls, we don't want it in logs
  src/Adapter/Module/AdminModuleDataProvider.php
Labels: Improvement, QA ✔️, develop

#22736 Update the UIKit to the latest release
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
Labels: Bug, Key feature, QA ✔️, develop

#22849 Move customization into product subdomain namespace
  src/Adapter/Product/Customization/CommandHandler/RemoveAllCustomizationFieldsFromProductHandler.php
  src/Adapter/Product/Customization/CommandHandler/SetProductCustomizationFieldsHandler.php
  src/Adapter/Product/Customization/QueryHandler/GetProductCustomizationFieldsHandler.php
  src/Adapter/Product/Customization/Repository/CustomizationFieldRepository.php
  src/Adapter/Product/Customization/Update/CustomizationFieldDeleter.php
  src/Adapter/Product/Customization/Update/ProductCustomizationFieldUpdater.php
  src/Adapter/Product/Customization/Validate/CustomizationFieldValidator.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_customization.yml
Labels: Refactoring, develop

#22555 Move Product pack classes in Pack subdomain in adapter
  src/Adapter/Product/Pack/CommandHandler/RemoveAllProductsFromPackHandler.php
  src/Adapter/Product/Pack/CommandHandler/SetPackProductsHandler.php
  src/Adapter/Product/Pack/QueryHandler/GetPackedProductsHandler.php
  src/Adapter/Product/Pack/Repository/ProductPackRepository.php
  src/Adapter/Product/Pack/Update/ProductPackUpdater.php
  src/Core/Domain/Product/Pack/Command/RemoveAllProductsFromPackCommand.php
  src/Core/Domain/Product/Pack/Command/SetPackProductsCommand.php
  src/Core/Domain/Product/Pack/CommandHandler/RemoveAllProductsFromPackHandlerInterface.php
  src/Core/Domain/Product/Pack/CommandHandler/SetPackProductsHandlerInterface.php
  src/Core/Domain/Product/Pack/Query/GetPackedProducts.php
  src/Core/Domain/Product/Pack/QueryHandler/GetPackedProductsHandlerInterface.php
  src/Core/Domain/Product/Pack/QueryResult/PackedProduct.php
  src/Core/Domain/Product/Pack/ValueObject/PackId.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_pack.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePackFeatureContext.php
Labels: Refactoring, Waiting for rebase, develop, migration

#22842 Block PR if it has merge commits
  .github/workflows/pr.yml
Labels: Improvement, develop

#22876 Add test 'Filter,sort and pagination logs'
  tests/UI/campaigns/functional/BO/14_advancedParameters/08_logs/01_filterSortAndPagination.js
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/advancedParameters/logs/index.js
Labels: 1.7.7.x, E2E Tests, Refactoring, TE

#22879 Add test 'CRUD shop group'
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/03_CRUDShops.js
  tests/UI/pages/BO/advancedParameters/multistore/shop/add.js
  tests/UI/pages/BO/advancedParameters/multistore/shop/index.js
Labels: 1.7.7.x, E2E Tests, Refactoring, TE

#22762 Add test 'Filter sort pagination shop groups'
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/02_filterSortAndPaginationShopGroups.js
  tests/UI/pages/BO/advancedParameters/multistore/index.js
Labels: 1.7.7.x, Refactoring, TE

#19818 Added Countries Translations (Installation & LocalizationPack)
  classes/Language.php
  install-dev/data/xml/address_format.xml
  install-dev/data/xml/country.xml
  install-dev/langs/en/data/country.xml
  src/PrestaShopBundle/Install/Language.php
  src/PrestaShopBundle/Install/LanguageList.php
  src/PrestaShopBundle/Install/XmlLoader.php
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
Labels: Improvement, QA ✔️, develop

#18136 Use grid common search action where possible (1.7.8 target)
  src/Core/Grid/Definition/Factory/LogGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/MetaGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/RequestSqlGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/TaxGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/WebserviceKeyDefinitionFactory.php
  src/Core/Search/Filters/CmsPageCategoryFilters.php
  src/Core/Search/Filters/CmsPageFilters.php
  src/Core/Search/Filters/LogsFilters.php
  src/Core/Search/Filters/MetaFilters.php
  src/Core/Search/Filters/RequestSqlFilters.php
  src/Core/Search/Filters/TaxFilters.php
  src/Core/Search/Filters/WebserviceKeyFilters.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/LogsController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SqlManagerController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/MetaController.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/CmsPageController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/LanguageController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/TaxController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
  src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/MerchandiseReturnController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/CreditSlipController.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/sql_request.yml
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/webservice.yml
  src/PrestaShopBundle/Resources/config/routing/admin/configure/shop_parameters/meta.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/currencies.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/language.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/tax.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/categories.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer/customers.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/credit_slips.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_filter_form_factory.yml
Labels: BC break, QA ✔️, Refactoring, develop, migration

#22890 Fix shopping cart tests for the nightly
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/01_filterShoppingCarts.js
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/02_sortAndPagination.js
Labels: E2E Tests, Refactoring, TE, develop

#22874 Add test 'Check number of orders in order history page'
  tests/UI/campaigns/functional/FO/03_userAccount/04_orderList.js
  tests/UI/pages/FO/myAccount/orderHistory.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#22855 Add test 'View vouchers on FO account Page'
  tests/UI/campaigns/functional/FO/03_userAccount/03_userDiscounts.js
  tests/UI/pages/FO/myAccount/index.js
  tests/UI/pages/FO/myAccount/vouchers.js
Labels: 1.7.7.x, E2E Tests, Refactoring, TE

#22856 Add test 'Check customer block' in order page
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/03_createSimpleOrderInBO.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/01_customerBlock.js
  tests/UI/pages/BO/customers/view.js
  tests/UI/pages/BO/orders/view.js
Labels: 1.7.7.x, QA ✔️, Refactoring, TE

#22805 BO - Orders page - Cannot delete a product restricted by a cart rule
  src/Adapter/Order/Refund/OrderProductRemover.php
  tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature
Labels: 1.7.7.x, Bug, QA ✔️

#22863 Fix reference in Shopping carts view
  src/Adapter/Cart/QueryHandler/GetCartForViewingHandler.php
Labels: 1.7.7.x, Bug, QA ✔️

#22900 Add test 'Test handling charges for carriers in FO'
  src/PrestaShopBundle/Resources/views/Admin/Improve/Shipping/Preferences/Blocks/shipping_preferences_carrier_options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Shipping/Preferences/Blocks/shipping_preferences_handling.html.twig
  tests/UI/campaigns/data/faker/carrier.js
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/01_CRUDCarrier.js
  tests/UI/campaigns/functional/BO/09_shipping/02_preferences/01_handling/01_handlingCharges.js
  tests/UI/pages/BO/shipping/carriers/add.js
  tests/UI/pages/BO/shipping/preferences/index.js
  tests/UI/pages/BO/shopParameters/customerSettings/groups/add.js
  tests/UI/pages/FO/checkout/index.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#22895 Adjust items alignment of order view header
  admin-dev/themes/new-theme/scss/pages/orders/_orders_view.scss
Labels: Bug, QA ✔️, develop

#22912 Fix nightly tests failing on 20-01-2021
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/01_customerBlock.js
  tests/UI/campaigns/functional/FO/03_userAccount/03_userDiscounts.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#22909 BO - Create Order - Updated product list when adresses changed
  admin-dev/themes/new-theme/js/pages/order/create/create-order-page.js
Labels: 1.7.7.x, Bug, QA ✔️

#22884 Fix carrier depth, height and width limits
  classes/Carrier.php
Labels: Bug, QA ✔️, develop

#20446 Fix cache class
  classes/cache/Cache.php
Labels: Bug, QA ✔️, develop

#22922 New hooks on grid component table
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.8.0.sql
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/table.html.twig
Labels: Feature, QA ✔️, develop

#22927 Fix nightly 21-01-2021 on 1.7.7.x
  tests/UI/campaigns/functional/FO/03_userAccount/03_userDiscounts.js
  tests/UI/package-lock.json
  tests/UI/pages/BO/catalog/discounts/add.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#19231 Add caching on Theme Yaml parsing
  src/Core/Addon/Theme/Theme.php
Labels: Improvement, QA ✔️, develop

#22887 Improve TypedRegexValidator->getPattern()
  src/Core/ConstraintValidator/TypedRegexValidator.php
Labels: Improvement, develop

#22935 Update GitHub Action actions/checkout to v2
  .github/workflows/cron_js_routing.yml
  .github/workflows/lint.yml
  .github/workflows/php.yml
Labels: Improvement, develop

#22841 Bring back vat number to address on order view
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewing.php
  src/Core/Domain/Order/QueryResult/OrderShippingAddressForViewing.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig
Labels: 1.7.7.x, Bug, QA ✔️

#22944 Fix undefined index when iso doesn't exists in language list
  src/PrestaShopBundle/Install/LanguageList.php
Labels: Bug, QA ✔️, develop

#22768 Exclude gifts from getOrderTotal when selected ONLY_PRODUCTS
  classes/Cart.php
  controllers/front/OrderController.php
Labels: 1.7.7.x, Bug, QA ✔️

#22967 Delete parameters.yml.travis
  .github/workflows/php.yml
  tests-legacy/parameters.yml.travis
Labels: Improvement, develop

#22925 Add test 'Add and delete shop URL'
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/03_CRUDShops.js
  tests/UI/pages/BO/advancedParameters/multistore/shop/index.js
  tests/UI/pages/BO/advancedParameters/multistore/url/addURL.js
  tests/UI/pages/BO/advancedParameters/multistore/url/index.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#22954 Add test 'Sort shop groups'
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/02_filterSortAndPaginationShopGroups.js
  tests/UI/pages/BO/advancedParameters/multistore/index.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#22662 Fix buttons height on mobile on order view page
  admin-dev/themes/new-theme/scss/pages/orders/_orders_view.scss
  admin-dev/themes/new-theme/scss/pages/partials/_order-navigation.scss
Labels: Bug, QA ✔️, develop

#22955 Fix product image form display in mobile view
  admin-dev/themes/default/js/bundle/product/form.js
  admin-dev/themes/new-theme/scss/pages/product/product_page.scss
Labels: Improvement, QA ✔️, develop

#21878 Simplified add language form
  src/Adapter/Language/CommandHandler/AbstractLanguageHandler.php
  src/Adapter/Language/CommandHandler/AddLanguageHandler.php
  src/Adapter/Language/CommandHandler/BulkDeleteLanguagesHandler.php
  src/Adapter/Language/CommandHandler/DeleteLanguageHandler.php
  src/Adapter/Language/CommandHandler/EditLanguageHandler.php
  src/Core/Domain/Language/Exception/DefaultLanguageException.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/LanguageController.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Language/LanguageType.php
  src/PrestaShopBundle/Resources/config/services/adapter/language.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Language/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: QA ✔️, Refactoring, Waiting for wording, develop, migration

#22947 Fix Shopping Cart page in BO throwing an exception
  classes/Cart.php
Labels: 1.7.7.x, Bug, QA ✔️

#22966 Faster checkout - depth of 0 means unlimited
  .github/workflows/behat.yml
  .github/workflows/cron_js_routing.yml
  .github/workflows/lint.yml
  .github/workflows/php.yml
  .github/workflows/sanity.yml
Labels: Improvement, develop

#22985 Add test 'Set required fields for address page'
  tests/UI/campaigns/functional/BO/04_customers/02_addresses/06_setRequiredFields.js
  tests/UI/pages/BO/customers/addresses/index.js
  tests/UI/pages/FO/myAccount/addAddress.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#22417 Add breadcrumb rich data on the frontpage
  themes/classic/templates/_partials/breadcrumb.tpl
Labels: Improvement, QA ✔️, develop

#22945 Fix product list hover and overflow on catalog mode
  themes/classic/_dev/css/components/featuredproducts.scss
Labels: Bug, QA ✔️, develop

#22982 Bump version to 1.7.7.2
  app/AppKernel.php
  install-dev/install_version.php
Labels: 1.7.7.x, Improvement

#22986 Integrate product quantities form and related command
  admin-dev/themes/new-theme/js/pages/product/edit/product-partial-updater.js
  src/Core/Form/ChoiceProvider/OutOfStockTypeChoiceProvider.php
  src/Core/Form/ChoiceProvider/PackStockTypeChoiceProvider.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/StockCommandBuilder.php
  src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/ProductType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/StockType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/choice_provider.yml
  src/PrestaShopBundle/Resources/config/services/core/form/command_builder.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/tabs.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/edit.html.twig
  tests/Unit/Core/Form/ChoiceProvider/ChoiceProviderTestCase.php
  tests/Unit/Core/Form/ChoiceProvider/OutOfStockTypeChoiceProviderTest.php
  tests/Unit/Core/Form/ChoiceProvider/PackStockTypeChoiceProviderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/ShippingCommandBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/StockCommandBuilderTest.php
Labels: Refactoring, Waiting for wording, develop, migration

#22988 Hide shop name on mobile
  admin-dev/themes/default/sass/partials/_header.sass
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
Labels: Bug, QA ✔️, develop

#22997 Fix compare function of dashboard's calendar
  admin-dev/themes/default/js/calendar.js
Labels: 1.7.7.x, Bug, QA ✔️

#22996 Align labels to right and space on red star
  admin-dev/themes/new-theme/scss/components/_form.scss
Labels: Bug, QA ✔️, develop

#23003 Update Symfony debug toolbar link to developer documentation
  src/PrestaShopBundle/Resources/views/Admin/WebProfiler/config.html.twig
Labels: Improvement, QA ✔️, develop

#22984 Remove header button on mobile and push these into new floating btn
  admin-dev/themes/new-theme/scss/components/layout/_header_toolbar.scss
  admin-dev/themes/new-theme/template/page_header_toolbar.tpl
Labels: Improvement, QA ✔️, UX ✔️, develop

#22953 Add test 'Filter, sort and paginaion shops'
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/04_filterSortAndPaginationShops.js
  tests/UI/pages/BO/advancedParameters/multistore/shop/index.js
Labels: 1.7.7.x, E2E Tests, QA ✔️, Refactoring, TE

#22813 Remove box-shadows from classic theme
  themes/classic/_dev/css/components/block-reassurance.scss
  themes/classic/_dev/css/components/categories.scss
  themes/classic/_dev/css/components/checkout.scss
  themes/classic/_dev/css/components/customer.scss
  themes/classic/_dev/css/components/errors.scss
  themes/classic/_dev/css/components/featuredproducts.scss
  themes/classic/_dev/css/components/footer.scss
  themes/classic/_dev/css/components/header.scss
  themes/classic/_dev/css/components/imageslider.scss
  themes/classic/_dev/css/components/newsletter.scss
  themes/classic/_dev/css/components/products.scss
  themes/classic/_dev/css/components/wrapper.scss
  themes/classic/_dev/css/partials/_commons.scss
Labels: Improvement, QA ✔️, develop

#22888 Change create order buttons position and wording
  install-dev/data/xml/hook.xml
  install-dev/upgrade/sql/1.7.8.0.sql
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/summary.html.twig
Labels: Improvement, QA ✔️, Wording ✔️, develop

#23037 Fix nightly 28/01/2021
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/RequestSql/Blocks/form.html.twig
  tests/UI/pages/BO/advancedParameters/database/sqlManager/add.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#23030 Fix duplicate id on floating button
  admin-dev/themes/new-theme/template/page_header_toolbar.tpl
Labels: Bug, QA ✔️, develop

#23031 Merge 177x to develop 2021/01/28
  admin-dev/themes/default/js/calendar.js
  admin-dev/themes/default/js/theme.js
  admin-dev/themes/new-theme/js/nav_bar.js
  admin-dev/themes/new-theme/js/pages/order/create/create-order-page.js
  classes/Cart.php
  controllers/admin/AdminStatsController.php
  controllers/front/OrderController.php
  src/Adapter/Cart/QueryHandler/GetCartForViewingHandler.php
  src/Adapter/Kpi/ShoppingCartTotalKpi.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Order/Refund/OrderProductRemover.php
  src/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewing.php
  src/Core/Domain/Order/QueryResult/OrderShippingAddressForViewing.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php
  src/PrestaShopBundle/DataCollector/HookDataCollector.php
  src/PrestaShopBundle/Resources/views/Admin/Improve/Shipping/Preferences/Blocks/shipping_preferences_carrier_options.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Shipping/Preferences/Blocks/shipping_preferences_handling.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig
  tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature
  tests/UI/DOCKER.md
  tests/UI/campaigns/data/faker/carrier.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/01_customerBlock.js
  tests/UI/campaigns/functional/BO/04_customers/02_addresses/06_setRequiredFields.js
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/01_viewCustomerService.js
  tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/01_activateMerchandiseReturn.js
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/01_CRUDCarrier.js
  tests/UI/campaigns/functional/BO/09_shipping/02_preferences/01_handling/01_handlingCharges.js
  tests/UI/campaigns/functional/BO/14_advancedParameters/08_logs/01_filterSortAndPagination.js
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/02_filterSortAndPaginationShopGroups.js
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/03_CRUDShops.js
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/04_filterSortAndPaginationShops.js
  tests/UI/campaigns/functional/FO/03_userAccount/03_userDiscounts.js
  tests/UI/campaigns/functional/FO/03_userAccount/04_orderList.js
  tests/UI/campaigns/upgrade/upgradeShop.js
  tests/UI/package-lock.json
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/advancedParameters/logs/index.js
  tests/UI/pages/BO/advancedParameters/multistore/index.js
  tests/UI/pages/BO/advancedParameters/multistore/shop/add.js
  tests/UI/pages/BO/advancedParameters/multistore/shop/index.js
  tests/UI/pages/BO/advancedParameters/multistore/url/addURL.js
  tests/UI/pages/BO/advancedParameters/multistore/url/index.js
  tests/UI/pages/BO/catalog/discounts/add.js
  tests/UI/pages/BO/customerService/customerService/index.js
  tests/UI/pages/BO/customers/addresses/index.js
  tests/UI/pages/BO/customers/view.js
  tests/UI/pages/BO/international/locations/countries/index.js
  tests/UI/pages/BO/modules/autoUpgrade/index.js
  tests/UI/pages/BO/orders/view.js
  tests/UI/pages/BO/shipping/carriers/add.js
  tests/UI/pages/BO/shipping/preferences/index.js
  tests/UI/pages/BO/shopParameters/customerSettings/groups/add.js
  tests/UI/pages/FO/checkout/index.js
  tests/UI/pages/FO/myAccount/addAddress.js
  tests/UI/pages/FO/myAccount/index.js
  tests/UI/pages/FO/myAccount/orderHistory.js
  tests/UI/pages/FO/myAccount/vouchers.js
Labels: Improvement, develop

#23006 Fix product search by ISBN
  classes/Search.php
Labels: Bug, QA ✔️, develop

#23049 Fix nightly 29/01/2021
  tests/UI/campaigns/functional/BO/14_advancedParameters/08_logs/01_filterSortAndPagination.js
  tests/UI/pages/BO/shipping/preferences/index.js
Labels: E2E Tests, QA ✔️, Refactoring, TE, develop

#23024 Fixed BreadcrumbList Rich Result on FrontOffice
  themes/classic/templates/_partials/breadcrumb.tpl
Labels: 1.7.7.x, Bug, QA ✔️

#22746 PHP sessions are not correctly configured
  classes/Context.php
  config/config.inc.php
  src/Core/Session/SessionHandler.php
  src/Core/Session/SessionHandlerInterface.php
Labels: Bug, Key feature, QA ✔️, develop
