Repository PrestaShop/PrestaShop, pull requests merged in 2021-09, with the labels that each got.

#25714 Remove unused parameters from Tools::addonsRequest()
  classes/Tools.php
Labels: develop, Feature, BC break

#25302 Fixed sort for naming in Admin > Carriers list
  controllers/admin/AdminCarriersController.php
Labels: QA ✔️, develop, Bug fix

#25757 Define version to 1778
  app/AppKernel.php
  install-dev/install_version.php
Labels: Improvement, 1.7.7.x

#22389 Fixed case where the "Place Order" button is disabled when the order is free and "Terms of service" is disabled
  controllers/front/OrderConfirmationController.php
  tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js
  tests/UI/pages/FO/checkout/index.js
  themes/_core/js/checkout-payment.js
  themes/classic/templates/checkout/_partials/steps/payment.tpl
Labels: Bug, QA ✔️, TE, develop

#25749 Product combination price edit : Use blur instead of onkeyup to avoid price flip
  admin-dev/themes/default/js/bundle/product/form.js
Labels: QA ✔️, Bug fix, 1.7.7.x

#25387 Product flags: Fixed spacing with multiples flags on frontoffice
  themes/classic/_dev/css/components/products.scss
Labels: QA ✔️, UX ✔️, Bug fix, 1.7.8.x

#25767 Fix date to filter with on cutomers and logs tests
  tests/UI/campaigns/functional/BO/04_customers/01_customers/01_filterAndQuickEditCustomers.js
  tests/UI/campaigns/functional/BO/14_advancedParameters/08_logs/01_filterSortAndPagination.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#25745 Do not use Math.random for cart rule code generation
  js/admin.js
Labels: Improvement, QA ✔️, develop

#25769 Delete step identifiers for common tests to fix the generated report
  tests/UI/campaigns/functional/FO/09_productPage/03_writeReview.js
Labels: QA ✔️, TE, Refactoring, E2E Tests, 1.7.8.x

#25803 Merge 177x into 178x
  admin-dev/themes/default/js/bundle/product/form.js
Labels: Bug fix, 1.7.7.x

#25784 Use null coalescing operator to fix possible notice
  classes/Product.php
Labels: QA ✔️, PM ✔️, Bug fix, 1.7.7.x

#25781 Upgrade to Symfony 4.4.30
  composer.lock
Labels: Improvement, develop

#25777 Fix supplier error when trying to see products linked to the supplier
  install-dev/fixtures/fashion/data/product_supplier.xml
Labels: QA ✔️, Bug fix, 1.7.8.x

#25828 Fix module's filter and product's quick view tests
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/01_filterModulesByStatus.js
  tests/UI/pages/BO/modules/moduleManager/index.js
  tests/UI/pages/FO/home/index.js
Labels: TE, Refactoring, E2E Tests, 1.7.8.x

#25725 Fix the save "meta_keywords" field on suppliers
  src/Core/Form/IdentifiableObject/DataHandler/SupplierFormDataHandler.php
Labels: QA ✔️, Bug fix, 1.7.8.x

#25839 Removed mcrypt dependencies
  .github/workflows/phpstan/strict-types-for-new-classes-rule-exclusion-list.php
  classes/PhpEncryption.php
  classes/PhpEncryptionEngine.php
  classes/PhpEncryptionLegacyEngine.php
  composer.json
  composer.lock
  src/PrestaShopBundle/Install/Upgrade.php
  tests/Unit/Classes/PhpEncryptionLegacyEngineTest.php
Labels: Improvement, develop, BC break

#25833 Fix exception when switching shop context after pushing a form on some configuration pages
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/MetaController.php
  src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/MerchandiseReturnController.php
Labels: QA ✔️, Bug fix, 1.7.8.x

#25842 Update egulias/email-validator to latest version
  composer.json
  composer.lock
  src/Core/Email/SwiftMailerValidation.php
  src/Core/Exception/NonASCIIInLocalPartException.php
Labels: Improvement, develop, BC break

#25846 Add unit test for SwiftMailerValidation
  tests/Unit/Core/Email/SwiftMailerValidationTest.php
Labels: Improvement, develop

#25830 Install "Products comments" module when its not to fix test
  tests/UI/campaigns/functional/FO/09_productPage/03_writeReview.js
  tests/UI/pages/BO/modules/moduleCatalog/index.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#25704 Fixed error on View Order when contains a customized product which has been deleted
  src/Adapter/Order/QueryHandler/GetOrderProductsForViewingHandler.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_product.feature
  tests/Integration/Behaviour/behat.yml
Labels: QA ✔️, Bug fix, 1.7.8.x

#25844 Deprecate fields.php usage
  admin-dev/init.php
  classes/ObjectModel.php
Labels: Improvement, develop

#25523 Fixed empty translation for OrderReturn
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
Labels: QA ✔️, Bug fix, 1.7.8.x

#25835 Add missing brands/manufacturer URL to the $urls
  classes/controller/FrontController.php
Labels: QA ✔️, develop, Bug fix

#25497 Removed ecotax in invoice/orderslip PDF if ecotax is disabled
  classes/pdf/HTMLTemplateInvoice.php
  classes/pdf/HTMLTemplateOrderSlip.php
  pdf/invoice.tax-tab.tpl
Labels: QA ✔️, PM ✔️, Bug fix, 1.7.8.x

#25868 Merge 178x into develop
  install-dev/fixtures/fashion/data/product_supplier.xml
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Order/QueryHandler/GetOrderProductsForViewingHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/SupplierFormDataHandler.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/MetaController.php
  src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/MerchandiseReturnController.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_product.feature
  tests/Integration/Behaviour/behat.yml
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/01_filterModulesByStatus.js
  tests/UI/pages/BO/modules/moduleManager/index.js
  tests/UI/pages/FO/home/index.js
Labels: develop, Bug fix

#25847 Update cssjanus 1.2 to 2.1, stop relying on PrestaShop fork
  composer.json
  composer.lock
  tests/Unit/Core/Localization/RTL/StylesheetGeneratorTest.php
  tests/Unit/Resources/assets/css/rtl_input.css
  tests/Unit/Resources/assets/css/rtl_output.css
Labels: Improvement, develop, BC break

#25778 Changelog for 1.7.7.8
  docs/CHANGELOG.txt
Labels: Improvement, 1.7.7.x

#25874 Apply PR #25833 into 1.7.8.0-build
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/MetaController.php
  src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/MerchandiseReturnController.php
Labels: Bug fix, 1.7.8.x

#25692 In BO > Orders: Fix disabled add voucher button
  admin-dev/themes/new-theme/js/pages/order/view.ts
Labels: QA ✔️, develop, Bug fix

#25876 Merge 177x into 1780-build
  admin-dev/themes/default/js/bundle/product/form.js
  classes/Product.php
  docs/CHANGELOG.txt
Labels: Bug fix, 1.7.8.x

#25741 Some buttons should not be allowed to wrap
  admin-dev/themes/default/scss/vendor/bootstrap-sass/_input-groups.scss
  admin-dev/themes/new-theme/scss/pages/orders/_orders_main.scss
Labels: QA ✔️, Bug fix, 1.7.8.x

#25611 Introduce new Symfony ArrayFinder to replace Shudrum ArrayFinder
  composer.json
  composer.lock
  src/Core/Util/ArrayFinder.php
  tests/Unit/Core/Util/ArrayFinderTest.php
Labels: develop, Feature

#25533 PHPStan (Level 0) on classes/
  .github/workflows/php.yml
  .github/workflows/phpstan/autoload.php
  classes/Carrier.php
  classes/Chart.php
  classes/Cookie.php
  classes/Manufacturer.php
  classes/Media.php
  classes/ObjectModel.php
  classes/PaymentModule.php
  classes/ProductAttribute.php
  classes/Smarty/SmartyResourceModule.php
  classes/Smarty/SmartyResourceParent.php
  classes/State.php
  classes/Uploader.php
  classes/assets/CccReducer.php
  classes/cache/Cache.php
  classes/checkout/CheckoutPaymentStep.php
  classes/checkout/CheckoutPersonalInformationStep.php
  classes/controller/AdminController.php
  classes/controller/Controller.php
  classes/controller/FrontController.php
  classes/helper/HelperList.php
  classes/helper/HelperOptions.php
  classes/helper/HelperUploader.php
  classes/module/Module.php
  classes/module/ModuleGraph.php
  classes/module/ModuleGrid.php
  classes/order/Order.php
  classes/order/OrderState.php
  classes/pdf/HTMLTemplateSupplyOrderForm.php
  classes/shop/Shop.php
  classes/stock/StockAvailable.php
  classes/tree/Tree.php
  classes/webservice/WebserviceRequest.php
  classes/webservice/WebserviceSpecificManagementAttachments.php
  classes/webservice/WebserviceSpecificManagementImages.php
  classes/webservice/WebserviceSpecificManagementSearch.php
  phpstan.neon.dist
  src/Adapter/Presenter/Object/ObjectPresenter.php
Labels: Improvement, QA ✔️, develop

#25388 FrontOffice : Use formatted ecotax price
  themes/classic/templates/catalog/_partials/product-prices.tpl
Labels: QA ✔️, Bug fix, 1.7.8.x

#25898 Fixed selector in computePriceTaxIncluded
  admin-dev/themes/default/js/bundle/product/form.js
Labels: QA ✔️, Bug fix, 1.7.8.x

#25556 Fix product list layout on responsive on classic theme
  themes/classic/_dev/css/components/featuredproducts.scss
  themes/classic/modules/ps_categoryproducts/views/templates/hook/ps_categoryproducts.tpl
  themes/classic/modules/ps_featuredproducts/views/templates/hook/ps_featuredproducts.tpl
  themes/classic/modules/ps_newproducts/views/templates/hook/ps_newproducts.tpl
  themes/classic/templates/catalog/_partials/miniatures/product.tpl
  themes/classic/templates/catalog/_partials/productlist.tpl
  themes/classic/templates/catalog/listing/product-list.tpl
Labels: QA ✔️, Bug fix, 1.7.8.x

#25858 Fix warning on the Customer Threads page
  controllers/admin/AdminCustomerThreadsController.php
Labels: develop, Bug fix

#25899 Correct some typescript ignore and external libraries
  admin-dev/themes/new-theme/js/components/entity-search-input.ts
  admin-dev/themes/new-theme/js/components/router.ts
  admin-dev/themes/new-theme/js/pages/order/create/create-order-page.ts
  admin-dev/themes/new-theme/js/pages/product/components/categories/category-tree-selector.ts
  admin-dev/themes/new-theme/js/pages/search-engine/index.ts
  admin-dev/themes/new-theme/js/translation-page/messages-edition.ts
  admin-dev/themes/new-theme/js/translation-page/messages-search.ts
  admin-dev/themes/new-theme/js/types/external-modules.d.ts
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
  admin-dev/themes/new-theme/tsconfig.json
Labels: Improvement, develop

#25931 Merge 1780build into 178x
  admin-dev/themes/default/js/bundle/product/form.js
  classes/Product.php
  docs/CHANGELOG.txt
  themes/classic/templates/catalog/_partials/product-prices.tpl
Labels: Bug fix, 1.7.8.x

#25940 Update to node 14 and correctly use mounted directories in docker-compose
  .docker/Dockerfile
  docker-compose.yml
Labels: QA ✔️, develop, Bug fix

#25900 Fix broken multistore config forms's javascript
  admin-dev/themes/new-theme/js/components/form/multistore-config-field.ts
Labels: QA ✔️, develop, Bug fix

#25476 Add contributions and contributors for 1.7.8 RC 1 build 3
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: Waiting for author, 1.7.8.x

#25115 Use AsyncToggleColumnExtension for Customers list
  admin-dev/themes/new-theme/js/pages/customer/index.ts
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
Labels: QA ✔️, develop, Bug fix, migration, BC break

#25958 Bump version to 1.7.8.1
  app/AppKernel.php
  install-dev/install_version.php
Labels: Improvement, 1.7.8.x

#25954 Update modules list in composer.json
  classes/Language.php
  composer.json
  composer.lock
  src/Core/Localization/RTL/StyleSheetProcessorFactory.php
Labels: Improvement, develop

#25965 Update test to get growl message after quick editing customer
  tests/UI/campaigns/functional/BO/04_customers/01_customers/01_filterAndQuickEditCustomers.js
  tests/UI/pages/BO/customers/index.js
Labels: TE, develop, Refactoring, E2E Tests

#25311 In upgrade, fixed configuration update on multi store
  install-dev/upgrade/upgrade.php
Labels: QA ✔️, Bug fix, 1.7.8.x

#25904 Fixed modal content when bulk delete combinations
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/product.html.twig
Labels: QA ✔️, Bug fix, Wording ✔️, 1.7.8.x

#25964 Make admin directory folder name longer
  controllers/admin/AdminLoginController.php
Labels: Improvement, QA ✔️, develop

#25776 Removed use of service parameter in controller
  src/Core/Form/ChoiceProvider/ThemeByNameWithEmailsChoiceProvider.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php
  tests/Integration/Behaviour/Features/Context/Domain/ThemeMailTemplatesFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Misc/theme_mail_templates.feature
  tests/Unit/Core/Form/ChoiceProvider/ThemeByNameWithEmailsChoiceProviderTest.php
Labels: QA ✔️, develop, Bug fix

#25936 Update webpack, babel and others webpack dependencies of new-theme
  admin-dev/themes/new-theme/.babelrc
  admin-dev/themes/new-theme/.eslintrc.js
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
Labels: Improvement, develop

#25760 Fixed error in SqlQueryValidator with multiple conditions in ON clause
  classes/RequestSql.php
  src/Adapter/SqlManager/SqlQueryValidator.php
  tests/Integration/Adapter/SqlManager/SqlQueryValidatorTest.php
Labels: QA ✔️, Bug fix, 1.7.8.x

#25993 Add jsDoc on tests helpers
  tests/UI/campaigns/utils/files.js
  tests/UI/campaigns/utils/globals.js
  tests/UI/campaigns/utils/helpers.js
  tests/UI/campaigns/utils/mailHelper.js
  tests/UI/campaigns/utils/setup.js
  tests/UI/campaigns/utils/testContext.js
Labels: QA ✔️, develop, Refactoring, E2E Tests

#26010 Replaced Github Action for block merge commits
  .github/workflows/pr.yml
Labels: 1.7.8.x

#26005 Merge 178x into develop [merge]
  .github/workflows/pr.yml
  app/AppKernel.php
  classes/RequestSql.php
  install-dev/install_version.php
  install-dev/upgrade/upgrade.php
  src/Adapter/SqlManager/SqlQueryValidator.php
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/product.html.twig
  tests/Integration/Adapter/SqlManager/SqlQueryValidatorTest.php
Labels: develop, Bug fix

#25953 Use playwright@1.13.1 for UI tests
  tests/UI/campaigns/functional/BO/11_international/01_localization/03_currencies/01_CreateOfficialCurrency.js
  tests/UI/campaigns/functional/BO/11_international/01_localization/03_currencies/02_CreateUnofficialCurrency.js
  tests/UI/campaigns/functional/BO/14_advancedParameters/08_logs/01_filterSortAndPagination.js
  tests/UI/campaigns/utils/globals.js
  tests/UI/package-lock.json
  tests/UI/package.json
  tests/UI/pages/BO/catalog/products/add.js
  tests/UI/pages/FO/FObasePage.js
  tests/UI/pages/commonPage.js
  tests/UI/pages/install/index.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#25987 Fixed URL encoding when Friendly URL is disabled
  themes/classic/modules/ps_customersignin/ps_customersignin.tpl
Labels: QA ✔️, develop, Bug fix

#25995 Remove duplicate actionCategoryUpdate call on toggling category display status
  classes/Category.php
Labels: QA ✔️, develop, Bug fix

#26015 Fix wording of prestashop:update:sql-upgrade-file-hooks-listing
  src/PrestaShopBundle/Command/AppendHooksListForSqlUpgradeFileCommand.php
Labels: Improvement, develop

#25982 Fix CLI install
  classes/shop/Shop.php
  install-dev/controllers/console/process.php
Labels: Bug fix, 1.7.8.x

#25961 Fixed display of attributes in cart on Frontoffice
  classes/Cart.php
Labels: QA ✔️, Bug fix, 1.7.8.x

#25726 Added API status block in WebService page
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceController.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Webservice/index.html.twig
Labels: QA ✔️, develop, Feature, Wording ✔️

#25551 Fixed JSON-LD with productcomments module data
  themes/classic/templates/_partials/microdata/product-jsonld.tpl
Labels: QA ✔️, Bug fix, 1.7.8.x

#25976 Update webpack dependencies of classic theme
  themes/classic/_dev/.eslintrc.js
  themes/classic/_dev/js/theme.js
  themes/classic/_dev/package-lock.json
  themes/classic/_dev/package.json
Labels: Improvement, QA ✔️, develop

#25913 Fix object model partial update
  classes/ObjectModel.php
  src/Adapter/Product/Combination/CommandHandler/UpdateCombinationDetailsHandler.php
  tests/Integration/Classes/ObjectModelTest.php
  tests/Resources/classes/TestableObjectModel.php
  tests/Resources/sql/install_testable_object.sql
Labels: develop, Bug fix

#25949 Easily override default value for primary user on docker
  .docker/Dockerfile
  docker-compose.yml
Labels: Improvement, develop
