Repository PrestaShop/PrestaShop, pull requests merged in 2022-12, with the labels that each got.

#30460 Fix use statement for ProductResetter
  tests/Integration/PrestaShopBundle/Controller/Sell/Catalog/CombinationControllerTest.php
Labels: develop, Bug fix

#30449 Optimize getting meta title of the product
  controllers/front/ProductController.php
Labels: Improvement, QA ✔️, develop

#28582 Stronger https detection in Tools::getShopProtocol()
  classes/Tools.php
Labels: Improvement, QA ✔️, develop

#30454 Update composer dependencies
  composer.lock
Labels: Improvement, QA ✔️, 1.7.8.x

#30458 Functional Tests : Migration TS (FO > 11)
  tests/UI/campaigns/functional/FO/11_checkout/02_addresses/02_useDifferentAddressForInvoice.ts
  tests/UI/pages/FO/FObasePage.ts
  tests/UI/pages/FO/aboutUs/index.js
  tests/UI/pages/FO/bestSales/index.js
  tests/UI/pages/FO/cart/index.js
  tests/UI/pages/FO/category/index.js
  tests/UI/pages/FO/checkout/index.js
  tests/UI/pages/FO/checkout/orderConfirmation.js
  tests/UI/pages/FO/cms/index.js
  tests/UI/pages/FO/contactUs/index.js
  tests/UI/pages/FO/delivery/index.js
  tests/UI/pages/FO/home/index.js
  tests/UI/pages/FO/legalNotice/index.js
  tests/UI/pages/FO/login/index.js
  tests/UI/pages/FO/myAccount/add.js
  tests/UI/pages/FO/myAccount/addAddress.js
  tests/UI/pages/FO/myAccount/addresses.js
  tests/UI/pages/FO/myAccount/creditSlips.js
  tests/UI/pages/FO/myAccount/gdprPersonalData.js
  tests/UI/pages/FO/myAccount/identity.js
  tests/UI/pages/FO/myAccount/index.js
  tests/UI/pages/FO/myAccount/merchandiseReturns.js
  tests/UI/pages/FO/myAccount/myWishlists.js
  tests/UI/pages/FO/myAccount/orderDetails.js
  tests/UI/pages/FO/myAccount/orderHistory.js
  tests/UI/pages/FO/myAccount/returnDetails.js
  tests/UI/pages/FO/myAccount/vouchers.js
  tests/UI/pages/FO/newProducts/index.js
  tests/UI/pages/FO/orderTracking/guestOrderTracking.js
  tests/UI/pages/FO/passwordReminder/index.js
  tests/UI/pages/FO/pricesDrop/index.js
  tests/UI/pages/FO/product/index.js
  tests/UI/pages/FO/searchResults/index.js
  tests/UI/pages/FO/securePayment/index.js
  tests/UI/pages/FO/siteMap/index.js
  tests/UI/pages/FO/stores/index.js
  tests/UI/pages/FO/termsAndConditionsOfUse/index.js
  tests/UI/pages/commonPage.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#30231 Update product.id_category_default after deleting categories
  classes/Category.php
  classes/ObjectModel.php
  src/Adapter/Category/CommandHandler/AbstractDeleteCategoryHandler.php
  src/Adapter/Category/CommandHandler/BulkDeleteCategoriesHandler.php
  src/Adapter/Category/CommandHandler/DeleteCategoryHandler.php
  src/Adapter/Product/Repository/ProductRepository.php
  src/Core/Domain/Category/Command/EditRootCategoryCommand.php
  src/PrestaShopBundle/Resources/config/services/adapter/category.yml
  tests/Integration/Behaviour/Features/Context/Domain/AbstractDomainFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CategoryFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateCategoriesFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Category/category_management.feature
  tests/Integration/Behaviour/Features/Scenario/Product/category_tree.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_position.feature
  tests/Integration/Behaviour/behat.yml
Labels: QA ✔️, develop, Bug fix

#30465 fix(Cart): fix notice saving customization when customer field is empty and not required
  classes/Cart.php
Labels: QA ✔️, 8.0.x, Bug fix

#30505 Add phpstan disallowed calls extension
  composer.json
  composer.lock
Labels: Improvement, develop, Waiting for dev

#30519 // Changelog 1.7.8.8
  CONTRIBUTORS.md
  classes/Dispatcher.php
  docs/CHANGELOG.txt
Labels: Improvement, 1.7.8.x

#30504 Remove combination handlers in favour of unified UpdateCombinationCommand
  src/Adapter/Product/Combination/CommandHandler/SetDefaultCombinationHandler.php
  src/Adapter/Product/Combination/CommandHandler/UpdateCombinationDetailsHandler.php
  src/Adapter/Product/Combination/CommandHandler/UpdateCombinationHandler.php
  src/Adapter/Product/Combination/CommandHandler/UpdateCombinationPricesHandler.php
  src/Adapter/Product/Combination/CommandHandler/UpdateCombinationStockHandler.php
  src/Core/Domain/Product/Combination/Command/SetDefaultCombinationCommand.php
  src/Core/Domain/Product/Combination/Command/UpdateCombinationCommand.php
  src/Core/Domain/Product/Combination/Command/UpdateCombinationDetailsCommand.php
  src/Core/Domain/Product/Combination/Command/UpdateCombinationPricesCommand.php
  src/Core/Domain/Product/Combination/Command/UpdateCombinationStockCommand.php
  src/Core/Domain/Product/Combination/CommandHandler/SetDefaultCombinationHandlerInterface.php
  src/Core/Domain/Product/Combination/CommandHandler/UpdateCombinationDetailsHandlerInterface.php
  src/Core/Domain/Product/Combination/CommandHandler/UpdateCombinationHandlerInterface.php
  src/Core/Domain/Product/Combination/CommandHandler/UpdateCombinationPricesHandlerInterface.php
  src/Core/Domain/Product/Combination/CommandHandler/UpdateCommandHandlerInterface.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationDetailsCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationPriceCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationStockCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/DefaultCombinationCommandsBuilder.php
  src/PrestaShopBundle/Resources/config/services/adapter/product/_combination.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/SetDefaultCombinationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/UpdateCombinationDetailsFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/UpdateCombinationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/UpdateCombinationPricesFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/UpdateCombinationStockFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/combinations_listing.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/generate_combinations.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/search_combinations_for_association.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/update_combination_details.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/update_combination_prices.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/update_combination_stock.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/update_combination_suppliers.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_multishop_pack.feature
  tests/Integration/Behaviour/Features/Scenario/Product/StockMovement/combination_stock_movement_history.feature
  tests/Integration/Behaviour/Features/Scenario/Product/search_products_for_association.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_pack.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_product_type.feature
  tests/Integration/Behaviour/behat.yml
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationDetailsCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationPriceCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationStockCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/DefaultCombinationCommandsBuilderTest.php
Labels: develop, Refactoring

#30507 Merge 1.7.8.x into 8.0.x
  classes/form/AbstractForm.php
Labels: Improvement, QA ✔️, 8.0.x

#30512 Allow negative number for attribute quantity
  src/PrestaShopBundle/Model/Product/AdminModelAdapter.php
Labels: QA ✔️, 8.0.x, Bug fix

#30357 Migrate Tools::str2url to new code
  classes/Tools.php
  src/Core/Util/String/StringModifier.php
  src/Core/Util/String/StringModifierInterface.php
  tests/Unit/Core/Util/String/StringModifierTest.php
Labels: Improvement, QA ✔️, develop

#30513 Add PHPStan rule to disallow calling of deprecated Symfony Translation
  phpstan.neon.dist
Labels: Improvement, develop

#30526 CI - Github Actions : Move from `styfle/cancel-workflow-action` to native concurrency
  .github/workflows/behaviour.yml
  .github/workflows/integration.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .github/workflows/php.yml
  .github/workflows/pr.yml
  .github/workflows/sanity-productV2.yml
  .github/workflows/sanity.yml
  .github/workflows/ui_tests_code_checks.yml
Labels: QA ✔️, develop, Refactoring

#30518 Define `_PS_DO_NOT_LOAD_CONFIGURATION_` default state
  classes/Configuration.php
  config/defines.inc.php
Labels: QA ✔️, develop, Refactoring

#29927 Add visibility checkbox description
  admin-dev/themes/new-theme/js/pages/product/edit/product-options-manager.ts
  admin-dev/themes/new-theme/js/pages/product/product-map.ts
  src/Core/Form/ChoiceProvider/ProductVisibilityChoiceProvider.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Options/VisibilityType.php
Labels: QA ✔️, develop, Feature, BC break

#30521 Fix translations
  classes/controller/FrontController.php
  classes/lang/KeysReference/FeatureValueLang.php
  controllers/admin/AdminLoginController.php
  install-dev/controllers/http/configure.php
  install-dev/theme/views/content.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Security/index.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/TrafficSeo/Meta/Blocks/url_schema_configuration.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Helpers/password_feedback.html.twig
Labels: Improvement, QA ✔️, 8.0.x, Wording ✔️

#30466 Functional Tests : Migration TS (BO > Advanced Parameters 04 => 07)
  tests/UI/campaigns/functional/BO/14_advancedParameters/04_email/01_filterDeleteAndBulkActionsEmails.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/04_email/02_enableDisableLogEmails.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/04_email/03_sendTestEmail/01_sendTestEmail.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/04_email/03_sortAndPagination.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/05_import/01_downloadSampleFiles.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/05_import/02_importFile.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/employees/01_filterAndQuickEditEmployees.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/employees/02_CRUDEmployee.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/employees/03_employeesBulkActions.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/employees/04_helpCard.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/employees/05_sortAndPagination.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/profiles/01_filterProfiles.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/profiles/02_CRUDProfile.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/profiles/03_helpCard.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/profiles/04_sortProfiles.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/profiles/05_paginationAndBulkActions.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/07_database/dbBackup/01_createAndDeleteDbBackup.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/07_database/dbBackup/02_paginationAndBulkDelete.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/07_database/dbBackup/03_helpCard.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/01_CRUDSqlQuery.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/02_helpCard.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/03_exportSqlQuery.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/04_filterSortAndPagination.ts
  tests/UI/campaigns/functional/FO/12_orderConfirmation/05_contactUs.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/commonPage.ts
Labels: Improvement, TE, develop, E2E Tests

#30455 Fetching every image details for a product in every shop
  src/Adapter/Product/Image/QueryHandler/GetShopProductImagesHandler.php
  src/Adapter/Product/Image/Repository/ProductImageMultiShopRepository.php
  src/Core/Data/ImmutableCollection.php
  src/Core/Domain/Product/Image/Query/GetShopProductImages.php
  src/Core/Domain/Product/Image/QueryHandler/GetShopProductImagesHandlerInterface.php
  src/Core/Domain/Product/Image/QueryResult/Shop/ShopImageAssociation.php
  src/Core/Domain/Product/Image/QueryResult/Shop/ShopImageAssociationCollection.php
  src/Core/Domain/Product/Image/QueryResult/Shop/ShopProductImages.php
  src/Core/Domain/Product/Image/QueryResult/Shop/ShopProductImagesCollection.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_image.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/get_shop_product_images.feature
Labels: develop, Feature

#29922 InkExtension added to Twig
  composer.json
  composer.lock
  src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
Labels: QA ✔️, develop, Feature, Email, Email theme, Needs documentation

#30549 Fix typo
  src/Core/Shop/LogoUploader.php
Labels: QA ✔️, develop, Bug fix

#30558 Removal of unnecessary comparison
  classes/Validate.php
Labels: QA ✔️, develop, Refactoring

#29931 Introduce OAuth2 Authorization server
  .github/workflows/phpunit/parameters.php
  app/AppKernel.php
  app/config/config.yml
  app/config/config_dev.yml
  app/config/config_prod.yml
  app/config/security_dev.yml
  app/config/security_prod.yml
  composer.json
  composer.lock
  src/Adapter/Security/Admin.php
  src/Core/Security/OAuth2/ResourceServerInterface.php
  src/Core/Security/TokenAuthenticator.php
  src/PrestaShopBundle/Controller/Api/OAuth2/AccessTokenController.php
  src/PrestaShopBundle/Entity/FeatureFlag.php
  src/PrestaShopBundle/EventListener/ActionDispatcherLegacyHooksSubscriber.php
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Resources/config/routing.yml
  src/PrestaShopBundle/Resources/config/routing/api.yml
  src/PrestaShopBundle/Resources/config/routing/api/oauth2.yml
  src/PrestaShopBundle/Resources/config/services/adapter/context.yml
  src/PrestaShopBundle/Resources/config/services/bundle/new_api.yml
  src/PrestaShopBundle/Resources/config/services/bundle/security.yml
  src/PrestaShopBundle/Security/OAuth2/Entity/AccessToken.php
  src/PrestaShopBundle/Security/OAuth2/Entity/Client.php
  src/PrestaShopBundle/Security/OAuth2/Repository/AccessTokenRepository.php
  src/PrestaShopBundle/Security/OAuth2/Repository/ClientRepository.php
  src/PrestaShopBundle/Security/OAuth2/Repository/NullScopeRepository.php
  src/PrestaShopBundle/Security/OAuth2/ResourceServer.php
  tests/Unit/Core/Security/TokenAuthenticatorTest.php
  tests/Unit/PrestaShopBundle/Security/OAuth2/OAuth2ClientTest.php
  tests/Unit/PrestaShopBundle/Security/OAuth2/Repository/AccessTokenRepositoryTest.php
  tests/Unit/PrestaShopBundle/Security/OAuth2/Repository/ClientRepositoryTest.php
Labels: QA ✔️, develop, Feature, BC break, Key feature

#30571 Revert inky extension
  composer.json
  composer.lock
  src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
Labels: QA ✔️, develop, Bug fix

#30419 Add better logging in the create-test-db script
  classes/log/AbstractLogger.php
  classes/log/NullLogger.php
  classes/log/PSRLoggerAdapter.php
  classes/log/PrestaShopLoggerInterface.php
  classes/log/SymfonyConsoleLogger.php
  src/Core/Addon/Theme/ThemeManager.php
  src/Core/Addon/Theme/ThemeManagerBuilder.php
  src/PrestaShopBundle/Install/AbstractInstall.php
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Resources/config/services/core/addon.yml
  tests/bin/create-test-db.php
Labels: Improvement, QA ✔️, develop

#30557 Only show current and all shops for specific price type
  src/Adapter/Form/ChoiceProvider/ShopNameByIdChoiceProvider.php
  src/Adapter/Product/SpecificPrice/Repository/SpecificPriceRepository.php
  src/Core/Form/IdentifiableObject/DataProvider/SpecificPriceFormDataProvider.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/SpecificPriceController.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/ApplicableGroupsType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_provider.yml
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/SpecificPriceFormDataProviderTest.php
Labels: QA ✔️, develop, Refactoring

#30503 Add class to password field
  admin-dev/themes/default/template/helpers/options/options.tpl
Labels: QA ✔️, develop, Bug fix

#30472 Bump dependencies for 8.1
  classes/controller/FrontController.php
  classes/webservice/SQLUtils.php
  composer.json
  composer.lock
  controllers/admin/AdminImportController.php
  controllers/admin/AdminProductsController.php
  src/Adapter/Product/Update/Filler/ProductFillerInterface.php
  tests/Integration/Adapter/ContextStateManagerTest.php
  tests/Unit/Adapter/ContextStateManagerTest.php
  tests/Unit/Core/Domain/Order/QueryResult/OrderForViewingTest.php
  tests/Unit/Core/Localization/CLDR/DataLayer/CurrencyCacheTest.php
  tests/Unit/Core/Localization/CLDR/DataLayer/LocaleCacheTest.php
  tests/Unit/Core/Localization/CLDR/DataLayer/LocaleReferenceTest.php
  tests/Unit/Core/Localization/DataLayer/CurrencyCacheTest.php
  tests/Unit/Core/Localization/LocaleCacheDataLayerTest.php
Labels: Improvement, QA ✔️, develop

#30559 Add a checkbox to generate combinations for all shops
  admin-dev/themes/new-theme/js/pages/product/components/generator/CombinationGenerator.vue
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/FormTheme/combination.html.twig
Labels: Waiting for wording, develop, Refactoring

#30567 Fix stock availability labels update when product is combination type
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/UpdateProductCommandsBuilder.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/UpdateProductCommandsBuilderTest.php
Labels: QA ✔️, develop, Bug fix

#30564 Implement delete combinations for all shops button
  admin-dev/themes/new-theme/js/pages/product/components/combination-list/bulk-delete-handler.ts
  admin-dev/themes/new-theme/js/pages/product/product-map.ts
  admin-dev/themes/new-theme/js/pages/product/services/combinations-service.ts
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/paginated_list.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/paginated_list_header.html.twig
Labels: Waiting for wording, develop, Refactoring

#28542 Add catalog price rule list to product form
  admin-dev/themes/new-theme/js/fos_js_routes.json
  admin-dev/themes/new-theme/js/pages/product/components/catalog-price-rule/catalog-price-rule-renderer.ts
  admin-dev/themes/new-theme/js/pages/product/components/catalog-price-rule/type/index.d.ts
  admin-dev/themes/new-theme/js/pages/product/edit/specific-prices-manager.ts
  admin-dev/themes/new-theme/js/pages/product/product-map.ts
  admin-dev/themes/new-theme/js/pages/product/services/paginated-catalog-price-rules-service.ts
  src/Adapter/CatalogPriceRule/QueryHandler/GetCatalogPriceRuleListForProductHandler.php
  src/Adapter/CatalogPriceRule/Repository/CatalogPriceRuleRepository.php
  src/Core/Domain/CatalogPriceRule/Query/GetCatalogPriceRuleListForProduct.php
  src/Core/Domain/CatalogPriceRule/QueryHandler/GetCatalogPriceRuleListForProductHandlerInterface.php
  src/Core/Domain/CatalogPriceRule/QueryResult/CatalogPriceRuleForListing.php
  src/Core/Domain/CatalogPriceRule/QueryResult/CatalogPriceRuleList.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CatalogPriceRuleController.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/CatalogPriceRulesType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/PricingType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/catalog_price_rule.yml
  src/PrestaShopBundle/Resources/config/services/adapter/catalog_price_rule.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/FormTheme/catalog_price_rules.html.twig
  tests/Integration/Behaviour/Features/Context/Domain/CatalogPriceRuleContext.php
  tests/Integration/Behaviour/Features/Scenario/CatalogPriceRule/catalog_price_rules_listing.feature
  tests/Integration/Behaviour/behat.yml
Labels: QA ✔️, Waiting for wording, develop, Refactoring, migration

#30510 Added the deletion of images linked to the image settings
  admin-dev/themes/default/scss/partials/_forms.scss
  admin-dev/themes/default/template/controllers/images/content.tpl
  admin-dev/themes/default/template/controllers/images/helpers/list/list_action_delete.tpl
  admin-dev/themes/default/template/controllers/images/modal_confirm_delete_type.tpl
  classes/ImageType.php
  controllers/admin/AdminImagesController.php
Labels: Improvement, QA ✔️, Waiting for wording, develop

#30524 Functional Tests : Migration TS (tools/stepIdentifiersChecker)
  tests/UI/package.json
  tests/UI/tools/stepIdentifiersChecker.js
  tests/UI/tools/stepIdentifiersChecker.ts
Labels: TE, develop, Refactoring, E2E Tests

#30605 GA : Fixed CI Concurrency for Sanity Product v2
  .github/workflows/sanity-productV2.yml
Labels: develop, Bug fix

#30540 improve Product::getAttributesResume
  classes/Product.php
Labels: Improvement, QA ✔️, develop

#30594 Fix total total_price_tax_excl
  install-dev/fixtures/fashion/data/order_detail.xml
Labels: QA ✔️, develop, Bug fix

#30616 Functional Tests : Fixed the selector in deletion modal
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/02_CRUDImageType.js
  tests/UI/pages/BO/design/imageSettings/index.js
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#30432 Functional tests - Add new test 'BO > Catalog > Filter products table v2'
  tests/UI/campaigns/productV2/functional/01_filterProducts.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/catalog/productsV2/index.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#30602 Get stores ordered by names
  classes/Store.php
Labels: Improvement, QA ✔️, develop

#30611 Functional Tests : Migration TS (FO - 04/05/06)
  tests/UI/campaigns/functional/BO/02_orders/01_orders/04_updateStatus.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/04_selectPreviousCarts.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/08_chooseAddress.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/06_merchandiseReturnsTab.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/07_messagesBlock.js
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/03_enableDisableProductImage.js
  tests/UI/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/03_enableDisableProductImage.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/12_groupCustomerRestriction.js
  tests/UI/campaigns/functional/BO/04_customers/01_customers/02_CRUDCustomer.js
  tests/UI/campaigns/functional/BO/04_customers/01_customers/05_setRequiredFields.js
  tests/UI/campaigns/functional/BO/04_customers/02_addresses/06_setRequiredFields.js
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/02_changeStatus.js
  tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/01_merchandiseReturnOptions.js
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/01_CRUDCarrier.js
  tests/UI/campaigns/functional/BO/09_shipping/02_preferences/01_handling/01_handlingCharges.js
  tests/UI/campaigns/functional/BO/10_payment/02_preferences/04_carrierRestrictions.js
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/04_quantityDiscountsBasedOn.ts
  tests/UI/campaigns/functional/FO/01_login/01_passwordReminder.js
  tests/UI/campaigns/functional/FO/01_login/02_login.js
  tests/UI/campaigns/functional/FO/01_login/03_logout.js
  tests/UI/campaigns/functional/FO/01_login/04_createAccount.js
  tests/UI/campaigns/functional/FO/02_headerAndFooter/01_checkLinksInHeader.js
  tests/UI/campaigns/functional/FO/02_headerAndFooter/02_checkLinksInFooter.js
  tests/UI/campaigns/functional/FO/03_userAccount/01_creditSlips/01_consultCreditSlip.js
  tests/UI/campaigns/functional/FO/03_userAccount/01_editInformation.js
  tests/UI/campaigns/functional/FO/03_userAccount/02_CRUDAddress.js
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/01_reorderFromOrderDetail.js
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/04_sendMessage.js
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderList.js
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/02_reorderFromOrderList.js
  tests/UI/campaigns/functional/FO/03_userAccount/03_viewVouchers.js
  tests/UI/campaigns/functional/FO/03_userAccount/04_getGDPRDataInPDF.js
  tests/UI/campaigns/functional/FO/03_userAccount/05_getGDPRDataInCSV.js
  tests/UI/campaigns/functional/FO/03_userAccount/06_contactUsOnGDPRPage.js
  tests/UI/campaigns/functional/FO/03_userAccount/07_logOut.js
  tests/UI/campaigns/functional/FO/03_userAccount/merchandiseReturns/01_consultReturnDetails.js
  tests/UI/campaigns/functional/FO/03_userAccount/merchandiseReturns/02_checkOrderReturnPDF.js
  tests/UI/campaigns/functional/FO/04_newsletter/01_subscribeNewsletter.ts
  tests/UI/campaigns/functional/FO/05_contactUs/01_checkMailtoLink.ts
  tests/UI/campaigns/functional/FO/05_contactUs/02_sendMessageWithCustomer.ts
  tests/UI/campaigns/functional/FO/05_contactUs/03_sendMessageAsAnonymous.ts
  tests/UI/campaigns/functional/FO/05_contactUs/04_addAttachment.ts
  tests/UI/campaigns/functional/FO/06_homePage/01_checkSlider.ts
  tests/UI/campaigns/functional/FO/06_homePage/03_allProducts.ts
  tests/UI/campaigns/functional/FO/06_homePage/04_productQuickView.ts
  tests/UI/campaigns/functional/FO/09_productPage/01_quickView.ts
  tests/UI/campaigns/functional/FO/09_productPage/02_addToCart.ts
  tests/UI/campaigns/regression/currencies/computingPrecision_FO.js
  tests/UI/campaigns/sanity/06_checkoutFO/01_orderProduct.js
  tests/UI/commonTests/FO/createAccount.js
  tests/UI/commonTests/FO/createOrder.js
  tests/UI/commonTests/FO/createShoppingCart.js
  tests/UI/commonTests/FO/loginFO.js
  tests/UI/data/types/customer.d.ts
  tests/UI/data/types/module.d.ts
  tests/UI/data/types/product.d.ts
  tests/UI/pages/FO/home/index.ts
  tests/UI/pages/FO/login/index.ts
  tests/UI/pages/FO/product/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#30587 Functional tests - Add new test 'CRUD pack of products' in product page V2
  tests/UI/campaigns/productV2/functional/04_CRUDPackOfProducts.ts
  tests/UI/data/demo/products.js
  tests/UI/pages/BO/catalog/productsV2/add/index.js
  tests/UI/pages/BO/catalog/productsV2/add/packTab.ts
  tests/UI/pages/BO/catalog/productsV2/index.js
  tests/UI/pages/FO/product/index.ts
Labels: TE, develop, Refactoring, E2E Tests

#30607 Improve comment wording in src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
Labels: Improvement, QA ✔️, develop

#30613 Handle multishop builders interfaces in bulk form data handler
  src/Core/Form/IdentifiableObject/DataHandler/BulkCombinationFormDataHandler.php
  src/PrestaShopBundle/Resources/config/services/core/form/command_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
Labels: QA ✔️, develop, Bug fix

#30608 Merge 1.7.8.x into 8.0.x
  CONTRIBUTORS.md
  admin-dev/themes/default/template/controllers/customer_threads/helpers/view/message.tpl
  classes/Dispatcher.php
  classes/Tools.php
  composer.lock
  controllers/admin/AdminCustomerThreadsController.php
  controllers/front/GetFileController.php
  controllers/front/UploadController.php
  src/Adapter/Image/ImageRetriever.php
  src/Adapter/Presenter/Order/OrderLazyArray.php
  upload/.htaccess
Labels: Improvement, QA ✔️, 8.0.x, 1.7.8.x

#30618 Merge 8.0.x into develop
  CONTRIBUTORS.md
  admin-dev/themes/default/template/controllers/customer_threads/helpers/view/message.tpl
  classes/Cart.php
  classes/Dispatcher.php
  classes/Tools.php
  classes/controller/FrontController.php
  classes/form/AbstractForm.php
  classes/lang/KeysReference/FeatureValueLang.php
  composer.lock
  controllers/admin/AdminCustomerThreadsController.php
  controllers/admin/AdminLoginController.php
  controllers/front/GetFileController.php
  controllers/front/UploadController.php
  install-dev/controllers/http/configure.php
  install-dev/theme/views/content.php
  src/Adapter/Image/ImageRetriever.php
  src/Adapter/Meta/SetUpUrlsDataConfiguration.php
  src/Adapter/Presenter/Order/OrderLazyArray.php
  src/PrestaShopBundle/Model/Product/AdminModelAdapter.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Security/index.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/TrafficSeo/Meta/Blocks/url_schema_configuration.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Helpers/password_feedback.html.twig
  upload/.htaccess
Labels: Improvement, QA ✔️, develop, Wording ✔️

#30615 Functional tests : Migration TS (Migrate `@utils/files`)
  tests/UI/campaigns/functional/BO/02_orders/01_orders/03_exportOrders.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/04_updateStatus.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/04_documentsTab.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/08_paymentBlock.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/10_changeStatus.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/11_checkInvoice.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/12_checkMultiInvoice.js
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/01_generateInvoiceByDate.js
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/02_generateInvoiceByStatus.js
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/02_enableDisableTaxBreakdown.js
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/03_enableDisableProductImage.js
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/06_otherOptions.js
  tests/UI/campaigns/functional/BO/02_orders/03_creditSlips/01_createFilterCreditSlips.js
  tests/UI/campaigns/functional/BO/02_orders/03_creditSlips/03_generateCreditSlipsByDate.js
  tests/UI/campaigns/functional/BO/02_orders/04_deliverySlips/01_generateDeliverySlipByDate.js
  tests/UI/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/03_enableDisableProductImage.js
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/02_CRUDCategoryInBO.js
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/03_categoriesBulkAction.js
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/05_paginationAndSortCategories.js
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/07_exportCategories.js
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/08_editHomeCategory.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/01_deleteEmptyCategory.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/01_emptyCategories.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/02_withCombinationsWithoutQuantities.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/03_withoutCombinationsWithoutQuantities.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/04_disabledProducts.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/05_productsWithoutImage.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/06_productsWithoutDescription.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/07_productsWithoutPrice.js
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/01_CRUDAttributesAndValues.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/01_CRUDBrandAndAddress.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/brands/02_sortPaginationAndBulkActions.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/brands/03_exportBrands.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/suppliers/01_CRUDSupplier.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/suppliers/04_paginationSortAndBulkActions.js
  tests/UI/campaigns/functional/BO/03_catalog/06_files/01_CRUDFile.js
  tests/UI/campaigns/functional/BO/03_catalog/06_files/03_filterSortPaginationAndBulkActions.js
  tests/UI/campaigns/functional/BO/04_customers/01_customers/04_paginationAndSortCustomers.js
  tests/UI/campaigns/functional/BO/04_customers/01_customers/06_exportCustomers.js
  tests/UI/campaigns/functional/BO/04_customers/02_addresses/04_paginationAndSortAddresses.js
  tests/UI/campaigns/functional/BO/04_customers/03_outstanding/03_viewInvoice.js
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/01_viewCustomerService.js
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/02_changeStatus.js
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/03_contactOptions.js
  tests/UI/campaigns/functional/BO/08_design/01_themeAndLogo/03_advancedCustomization/01_advancedCustomization.js
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/01_CRUDCarrier.js
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/02_filterSortAndPagination.js
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/03_quickEditAndBulkActions.js
  tests/UI/campaigns/functional/BO/09_shipping/02_preferences/01_handling/01_handlingCharges.js
  tests/UI/campaigns/functional/FO/02_headerAndFooter/03_changeCurrency.js
  tests/UI/campaigns/functional/FO/03_userAccount/01_creditSlips/01_consultCreditSlip.js
  tests/UI/campaigns/functional/FO/03_userAccount/04_getGDPRDataInPDF.js
  tests/UI/campaigns/functional/FO/03_userAccount/05_getGDPRDataInCSV.js
  tests/UI/campaigns/functional/FO/03_userAccount/06_contactUsOnGDPRPage.js
  tests/UI/campaigns/functional/FO/03_userAccount/merchandiseReturns/02_checkOrderReturnPDF.js
  tests/UI/utils/files.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#30621 Functional Tests : Migration TS (BO - 10)
  tests/UI/campaigns/functional/BO/10_payment/02_preferences/01_currencyRestrictions.ts
  tests/UI/campaigns/functional/BO/10_payment/02_preferences/02_groupRestrictions.ts
  tests/UI/campaigns/functional/BO/10_payment/02_preferences/03_countryRestrictions.ts
  tests/UI/campaigns/functional/BO/10_payment/02_preferences/04_carrierRestrictions.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/payment/preferences/index.ts
  tests/UI/pages/FO/home/index.ts
  tests/UI/pages/commonPage.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#30627 Functional Tests : Migration TS (FO - 03)
  tests/UI/campaigns/functional/BO/02_orders/01_orders/11_previewOrder.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/04_selectPreviousCarts.js
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/02_enableDisableTaxBreakdown.js
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/03_enableDisableProductImage.js
  tests/UI/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/03_enableDisableProductImage.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/01_withAndWithoutCode.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/09_checkTotalAvailable.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/10_countryRestriction.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/11_carrierRestriction.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/12_groupCustomerRestriction.js
  tests/UI/campaigns/functional/BO/04_customers/01_customers/08_viewCustomer.js
  tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/01_merchandiseReturnOptions.js
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/01_CRUDCarrier.js
  tests/UI/campaigns/functional/BO/09_shipping/02_preferences/01_handling/01_handlingCharges.js
  tests/UI/campaigns/functional/BO/09_shipping/02_preferences/02_carrierOptions/01_defaultCarrier.js
  tests/UI/campaigns/functional/BO/09_shipping/02_preferences/02_carrierOptions/02_updateCarriersSortOption.js
  tests/UI/campaigns/functional/BO/10_payment/02_preferences/03_countryRestrictions.ts
  tests/UI/campaigns/functional/BO/10_payment/02_preferences/04_carrierRestrictions.ts
  tests/UI/campaigns/functional/FO/02_headerAndFooter/01_checkLinksInHeader.js
  tests/UI/campaigns/functional/FO/03_userAccount/01_creditSlips/01_consultCreditSlip.ts
  tests/UI/campaigns/functional/FO/03_userAccount/01_editInformation.ts
  tests/UI/campaigns/functional/FO/03_userAccount/02_CRUDAddress.ts
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/01_reorderFromOrderDetail.ts
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/04_sendMessage.ts
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderList.ts
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/02_reorderFromOrderList.ts
  tests/UI/campaigns/functional/FO/03_userAccount/03_viewVouchers.ts
  tests/UI/campaigns/functional/FO/03_userAccount/04_getGDPRDataInPDF.ts
  tests/UI/campaigns/functional/FO/03_userAccount/05_getGDPRDataInCSV.ts
  tests/UI/campaigns/functional/FO/03_userAccount/06_contactUsOnGDPRPage.ts
  tests/UI/campaigns/functional/FO/03_userAccount/07_logOut.ts
  tests/UI/campaigns/functional/FO/03_userAccount/merchandiseReturns/01_consultReturnDetails.ts
  tests/UI/campaigns/functional/FO/03_userAccount/merchandiseReturns/02_checkOrderReturnPDF.ts
  tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js
  tests/UI/campaigns/regression/currencies/computingPrecision_FO.js
  tests/UI/campaigns/sanity/05_cartFO/01_editCheckCart.js
  tests/UI/campaigns/sanity/06_checkoutFO/01_orderProduct.js
  tests/UI/commonTests/FO/createOrder.js
  tests/UI/commonTests/FO/createShoppingCart.js
  tests/UI/data/types/order.d.ts
  tests/UI/pages/FO/cart/index.ts
  tests/UI/pages/FO/login/index.ts
Labels: Improvement, TE, develop, E2E Tests

#30603 Allow controlling profiler from backoffice
  src/Adapter/Debug/DebugModeConfiguration.php
  src/Adapter/Debug/DebugProfiling.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/DebugModeType.php
  src/PrestaShopBundle/Resources/config/services/adapter/data_configuration.yml
  src/PrestaShopBundle/Resources/config/services/adapter/services.yml
Labels: QA ✔️, develop, Feature, Wording ✔️

#30639 Functional Tests : Migration TS (BO - 09)
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/01_CRUDCarrier.ts
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/02_filterSortAndPagination.ts
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/03_quickEditAndBulkActions.ts
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/04_changePosition.ts
  tests/UI/campaigns/functional/BO/09_shipping/02_preferences/01_handling/01_handlingCharges.ts
  tests/UI/campaigns/functional/BO/09_shipping/02_preferences/02_carrierOptions/01_defaultCarrier.ts
  tests/UI/campaigns/functional/BO/09_shipping/02_preferences/02_carrierOptions/02_updateCarriersSortOption.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/shipping/carriers/add.ts
  tests/UI/pages/BO/shipping/carriers/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#30638 Functional Tests : Migration TS (FO - 02)
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/01_viewCustomerService.js
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/02_changeStatus.js
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/03_contactOptions.js
  tests/UI/campaigns/functional/FO/02_headerAndFooter/01_checkLinksInHeader.ts
  tests/UI/campaigns/functional/FO/02_headerAndFooter/02_checkLinksInFooter.ts
  tests/UI/campaigns/functional/FO/02_headerAndFooter/03_changeCurrency.ts
  tests/UI/campaigns/functional/FO/02_headerAndFooter/04_changeLanguage.ts
  tests/UI/pages/FO/aboutUs/index.ts
  tests/UI/pages/FO/bestSales/index.ts
  tests/UI/pages/FO/cart/index.ts
  tests/UI/pages/FO/contactUs/index.ts
Labels: Improvement, TE, develop, E2E Tests

#30640 Functional Tests : Migration TS (Install)
  tests/UI/campaigns/sanity/01_installShop/01_installShop.ts
  tests/UI/pages/install/index.ts
Labels: Improvement, TE, develop, E2E Tests

#30673 // Changelog 8.0.1
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: Improvement, 8.0.x

#30672 Updated headers without license block
  tests/Integration/PrestaShopBundle/TranslationIntegrationTest.php
Labels: Improvement, 8.0.x

#30671 Update version number to 8.0.1
  app/AppKernel.php
  install-dev/install_version.php
Labels: Improvement, 8.0.x

#30676 Upgraded classic theme and ps_contactinfo module
  composer.lock
Labels: Improvement, 8.0.x, Bug fix

#30636 Functional test - Add new test 'CRUD virtual product' in product page V2
  tests/UI/campaigns/productV2/functional/05_CRUDVirtualProduct.ts
  tests/UI/data/faker/product.js
  tests/UI/pages/BO/catalog/productsV2/add/index.js
  tests/UI/pages/BO/catalog/productsV2/add/virtualProductTab.js
  tests/UI/pages/BO/catalog/productsV2/add/virtualProductTab.ts
  tests/UI/pages/BO/catalog/productsV2/index.js
  tests/UI/pages/FO/myAccount/orderDetails.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#30675 // Changelog 8.0.1
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: Improvement, 8.0.x

#30667 add a display hook in the address step just like other checkout step
  install-dev/data/xml/hook.xml
Labels: QA ✔️, PM ✔️, develop, Feature, Needs documentation, Needs autoupgrade PR

#30598 Improve syntax of information page
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/LogsPage/Blocks/severity_levels.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/system_information.html.twig
Labels: QA ✔️, UX ✔️, develop, Refactoring, Wording ✔️
