Repository PrestaShop/PrestaShop, pull requests merged in 2022-07, with the labels that each got.

#28918 Functional tests - Refactoring of 'Check header links on FO' test
  tests/UI/campaigns/functional/FO/02_headerAndFooter/01_checkLinksInHeader.js
  tests/UI/pages/FO/home/index.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#28843 Remove Addons reference in the Improve > Theme page
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Theme/Blocks/logo_configuration.html.twig
Labels: QA ✔️, develop, Bug fix

#28827 Fix default theme compatibility with npm 8
  admin-dev/themes/default/.eslintrc.js
  admin-dev/themes/default/js/bundle/product/form.js
  admin-dev/themes/default/js/theme.js
  admin-dev/themes/default/package-lock.json
  admin-dev/themes/default/package.json
  admin-dev/themes/default/scss/font.scss
  admin-dev/themes/default/webpack.config.js
Labels: QA ✔️, develop, Bug fix

#28962 Fix nightly 8.0.x - Fix 'CRUD customer' test
  tests/UI/pages/BO/customers/add.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#28829 Fix performances links spaces and URLs
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/CachingType.php
Labels: QA ✔️, Bug fix, 1.7.8.x

#28926 Set permissions for GitHub actions
  .github/workflows/cron_nightly_build.yml
  .github/workflows/cron_nightly_gcp.yml
  .github/workflows/cron_nightly_tests.yml
  .github/workflows/cron_php_update_modules.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .github/workflows/php.yml
  .github/workflows/ui-tests-code-checks.yml
Labels: Improvement, develop

#28524 Fix select2 style in order view
  admin-dev/themes/new-theme/scss/pages/orders/_orders_view.scss
Labels: QA ✔️, develop, Bug fix

#28246 Fix DisabledProductGridDefinitionFactory
  src/Core/Grid/Definition/Factory/Monitoring/DisabledProductGridDefinitionFactory.php
Labels: QA ✔️, develop, Refactoring, migration

#28949 Change PrestaShop URL in footer of emails
  mails/themes/classic/components/footer.html.twig
  mails/themes/modern/components/footer.html.twig
Labels: Improvement, QA ✔️, develop, Wording ✔️

#28984 Fix customer edit/add select all group access
  admin-dev/themes/new-theme/js/pages/customer/form.ts
  admin-dev/themes/new-theme/js/pages/customer/index.ts
Labels: QA ✔️, 8.0.x, Bug fix

#28904 Fix responsive for product quick view.
  themes/classic/_dev/css/components/featuredproducts.scss
  themes/classic/modules/ps_bestsellers/views/templates/hook/ps_bestsellers.tpl
  themes/classic/modules/ps_categoryproducts/views/templates/hook/ps_categoryproducts.tpl
  themes/classic/modules/ps_crossselling/views/templates/hook/ps_crossselling.tpl
  themes/classic/modules/ps_featuredproducts/views/templates/hook/ps_featuredproducts.tpl
  themes/classic/modules/ps_newproducts/views/templates/hook/ps_newproducts.tpl
  themes/classic/modules/ps_specials/views/templates/hook/ps_specials.tpl
  themes/classic/modules/ps_viewedproduct/views/templates/hook/ps_viewedproduct.tpl
  themes/classic/templates/catalog/_partials/productlist.tpl
  themes/classic/templates/catalog/listing/manufacturer.tpl
  themes/classic/templates/catalog/listing/product-list.tpl
  themes/classic/templates/catalog/listing/search.tpl
  themes/classic/templates/catalog/listing/supplier.tpl
  themes/classic/templates/catalog/product.tpl
Labels: QA ✔️, Bug fix, 1.7.8.x

#28992 Fix material icons for legacy BO search form
  admin-dev/themes/default/js/admin-theme.js
  admin-dev/themes/default/scss/partials/_header.scss
  admin-dev/themes/default/template/search_form.tpl
Labels: QA ✔️, develop, BO, Bug fix, Front-end

#29032 Fix nightly 11-07-2022 - Fix some random errors
  tests/UI/campaigns/functional/FO/09_productPage/01_quickView.js
  tests/UI/pages/BO/orders/index.js
  tests/UI/pages/BO/orders/view/productsBlock.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#29010 Fix number of groups to check on customer view page
  tests/UI/campaigns/functional/BO/04_customers/01_customers/08_viewCustomer.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#28987 Fix associated categories in product page v1
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
Labels: QA ✔️, 8.0.x, Bug fix

#28608 Set $registeredHookName as renderWidget when no hook given
  tools/profiling/Hook.php
Labels: QA ✔️, Bug fix, 1.7.8.x

#29036 Deprecate URL generation on category with id 0 and remove preview in category creation
  classes/Link.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/form.html.twig
Labels: QA ✔️, develop, Bug fix

#28706 Fix orders export limit
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
Labels: QA ✔️, Bug fix, 1.7.8.x

#29064 Move email alerts module default translations
  translations/default/ModulesEmailalertsAdmin.xlf
  translations/default/ModulesEmailalertsShop.xlf
Labels: 8.0.x, Bug fix

#29055 Fix anchor links in product list
  themes/classic/_dev/js/listing.js
Labels: QA ✔️, Bug fix, 1.7.8.x

#29020 Use LegacyModule instance instead of ModuleAdaptater
  src/Adapter/Translations/TranslationRouteFinder.php
Labels: QA ✔️, 8.0.x, Bug fix

#28865 PrestashopCollection needs a shop restriction
  classes/PrestaShopCollection.php
Labels: QA ✔️, develop, Bug fix

#29019 BO - Brands & Suppliers - the red alert "Image format not recognized" is missing the webp
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/SupplierController.php
Labels: QA ✔️, 8.0.x, Bug fix

#28947 Fix missing translations on meta pages
  classes/lang/KeysReference/MetaLang.php
  install-dev/langs/en/data/meta.xml
Labels: QA ✔️, develop, Bug fix, Wording ✔️

#28814 Call initContent of the parent at the beginning
  controllers/front/OrderDetailController.php
Labels: Improvement, QA ✔️, develop

#29067 Fix permissions for read-only user
  src/PrestaShopBundle/Controller/Admin/Improve/Design/PositionsController.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/DeliveryController.php
Labels: QA ✔️, 8.0.x, Bug fix

#29025 Fix module link in adminsearch
  admin-dev/themes/new-theme/js/pages/module/controller.js
  controllers/admin/AdminSearchController.php
Labels: QA ✔️, 8.0.x, Bug fix

#29069 Fix install theme without hooks
  src/Core/Addon/Theme/ThemeManager.php
Labels: QA ✔️, 8.0.x, Bug fix

#29022 Display an error while the file format does not match the allowed formats
  src/PrestaShopBundle/Controller/Admin/ProductImageController.php
Labels: Improvement, QA ✔️, 8.0.x, Wording ✔️

#28784 Allow to translate placeholder
  classes/Tools.php
Labels: Improvement, QA ✔️, develop, Wording ✔️

#29086 Fix filtering by date in Movements page (stock section)
  admin-dev/themes/new-theme/js/app/pages/stock/components/header/filters.vue
Labels: QA ✔️, 8.0.x, Bug fix

#29094 Add Smarty blocks to variables and styles definition
  pdf/delivery-slip.style-tab.tpl
  pdf/invoice.style-tab.tpl
Labels: Improvement, QA ✔️, develop

#28943 Throw exception when ImageType doesn't return anything on FO
  src/Adapter/Image/ImageRetriever.php
Labels: Improvement, QA ✔️, develop

#29141 Fix typo inside Reference's comment
  src/Core/Domain/Product/ValueObject/Reference.php
Labels: QA ✔️, develop, Bug fix

#29153 Merge 1.7.8.7 into 1.7.8.x [merge]
  app/AppKernel.php
  classes/Smarty/SmartyCacheResourceMysql.php
  docs/CHANGELOG.txt
  install-dev/install_version.php
Labels: Bug fix, 1.7.8.x

#28416 Do not throw an exception if a module is invalid
  src/Core/Module/ModuleRepository.php
Labels: QA ✔️, develop, Bug fix

#29054 Fix BO Units on inputs
  src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php
  src/PrestaShopBundle/Form/Admin/Product/ProductSpecificPrice.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_shipping.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_specific_price.html.twig
Labels: QA ✔️, 8.0.x, Bug fix, BC break, Needs documentation

#29068 Regenerate modern mail theme
  mails/themes/modern/components/footer.html.twig
  mails/themes/modern/components/header.html.twig
  mails/themes/modern/components/layout.html.twig
  mails/themes/modern/components/order_layout.html.twig
  mails/themes/modern/core/account.html.twig
  mails/themes/modern/core/backoffice_order.html.twig
  mails/themes/modern/core/bankwire.html.twig
  mails/themes/modern/core/cheque.html.twig
  mails/themes/modern/core/contact.html.twig
  mails/themes/modern/core/contact_form.html.twig
  mails/themes/modern/core/credit_slip.html.twig
  mails/themes/modern/core/download_product.html.twig
  mails/themes/modern/core/employee_password.html.twig
  mails/themes/modern/core/forward_msg.html.twig
  mails/themes/modern/core/guest_to_customer.html.twig
  mails/themes/modern/core/import.html.twig
  mails/themes/modern/core/in_transit.html.twig
  mails/themes/modern/core/log_alert.html.twig
  mails/themes/modern/core/newsletter.html.twig
  mails/themes/modern/core/order_canceled.html.twig
  mails/themes/modern/core/order_changed.html.twig
  mails/themes/modern/core/order_conf.html.twig
  mails/themes/modern/core/order_customer_comment.html.twig
  mails/themes/modern/core/order_merchant_comment.html.twig
  mails/themes/modern/core/order_return_state.html.twig
  mails/themes/modern/core/outofstock.html.twig
  mails/themes/modern/core/password.html.twig
  mails/themes/modern/core/password_query.html.twig
  mails/themes/modern/core/payment.html.twig
  mails/themes/modern/core/payment_error.html.twig
  mails/themes/modern/core/preparation.html.twig
  mails/themes/modern/core/productoutofstock.html.twig
  mails/themes/modern/core/refund.html.twig
  mails/themes/modern/core/reply_msg.html.twig
  mails/themes/modern/core/shipped.html.twig
  mails/themes/modern/core/test.html.twig
  mails/themes/modern/core/voucher.html.twig
  mails/themes/modern/core/voucher_new.html.twig
  mails/themes/modern/modules/followup/followup_1.html.twig
  mails/themes/modern/modules/followup/followup_2.html.twig
  mails/themes/modern/modules/followup/followup_3.html.twig
  mails/themes/modern/modules/followup/followup_4.html.twig
  mails/themes/modern/modules/ps_emailalerts/customer_qty.html.twig
  mails/themes/modern/modules/ps_emailalerts/new_order.html.twig
  mails/themes/modern/modules/ps_emailalerts/order_changed.html.twig
  mails/themes/modern/modules/ps_emailalerts/productcoverage.html.twig
  mails/themes/modern/modules/ps_emailalerts/productoutofstock.html.twig
  mails/themes/modern/modules/ps_emailalerts/return_slip.html.twig
  mails/themes/modern/modules/ps_emailsubscription/newsletter_conf.html.twig
  mails/themes/modern/modules/ps_emailsubscription/newsletter_verif.html.twig
  mails/themes/modern/modules/ps_emailsubscription/newsletter_voucher.html.twig
  mails/themes/modern/modules/referralprogram/referralprogram-congratulations.html.twig
  mails/themes/modern/modules/referralprogram/referralprogram-invitation.html.twig
  mails/themes/modern/modules/referralprogram/referralprogram-voucher.html.twig
Labels: QA ✔️, 8.0.x, Bug fix

#29162 Remove smarty caching_type
  classes/Smarty/SmartyCacheResourceMysql.php
  config/smarty.config.inc.php
  install-dev/data/xml/configuration.xml
  src/Adapter/Smarty/SmartyCacheConfiguration.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/SmartyType.php
Labels: QA ✔️, 8.0.x, Bug fix, BC break

#28940 Merge `1.7.8.x` into `8.0.x`
  classes/Cart.php
  classes/ProductAssembler.php
  composer.lock
  config/config.inc.php
  src/Adapter/AddressFactory.php
  src/Core/Form/ChoiceProvider/CurrencyNameByIsoCodeChoiceProvider.php
  src/Core/Localization/CLDR/Currency.php
  src/Core/Product/Search/ProductSearchContext.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/CachingType.php
  tests/Unit/Core/Localization/CLDR/CurrencyTest.php
Labels: QA ✔️, 8.0.x, Bug fix

#29099 Add docker-compose.override.yml to ignored files
  .gitignore
Labels: Improvement, 8.0.x

#29096 BO - Bad display on Your Profile button on all of pages when hover and click on it
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
Labels: QA ✔️, Bug fix, 1.7.8.x

#29073 Remove select2 for categories in product v1
  src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php
Labels: QA ✔️, 8.0.x, Bug fix

#29186 Fix supplier / product v1 association
  controllers/admin/AdminProductsController.php
Labels: QA ✔️, 8.0.x, Bug fix

#29190 Fix menu display for legacy pages
  admin-dev/themes/default/scss/partials/_nav.scss
Labels: QA ✔️, 8.0.x, Bug fix

#29158 Fix product type error when enabling experimental product page
  src/Adapter/Product/Repository/ProductRepository.php
Labels: QA ✔️, 8.0.x, Bug fix

#28825 Order invoices configuration form: add multistore compatibility and some refactoring
  admin-dev/themes/new-theme/js/pages/invoices/index.ts
  src/Adapter/Invoice/InvoiceOptionsConfiguration.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/InvoicesController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/Invoices/InvoiceOptionsType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/invoices.yml
  src/PrestaShopBundle/Resources/config/services/adapter/data_configuration.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Invoices/Blocks/invoice_options.html.twig
  tests/Unit/Adapter/Invoice/InvoicesConfigurationTest.php
Labels: QA ✔️, develop, Refactoring, Wording ✔️

#28948 Functional tests - Add new test 'Change language in FO'
  tests/UI/campaigns/functional/BO/11_international/01_localization/01_localization/01_importLocalizationPack.js
  tests/UI/campaigns/functional/BO/11_international/01_localization/01_localization/02_defaultLanguage.js
  tests/UI/campaigns/functional/FO/02_headerAndFooter/04_changeLanguage.js
  tests/UI/pages/FO/FObasePage.js
  tests/UI/pages/commonPage.js
Labels: TE, 8.0.x, Refactoring, E2E Tests

#28991 Update faker dependency for UI tests
  tests/UI/campaigns/functional/FO/03_userAccount/08_orderHistory/04_orderDetails/01_sendMessage.js
  tests/UI/data/faker/CMScategory.js
  tests/UI/data/faker/CMSpage.js
  tests/UI/data/faker/address.js
  tests/UI/data/faker/attributeAndValue.js
  tests/UI/data/faker/brand.js
  tests/UI/data/faker/brandAddress.js
  tests/UI/data/faker/carrier.js
  tests/UI/data/faker/cartRule.js
  tests/UI/data/faker/catalogPriceRule.js
  tests/UI/data/faker/category.js
  tests/UI/data/faker/contact.js
  tests/UI/data/faker/contactUs.js
  tests/UI/data/faker/country.js
  tests/UI/data/faker/customer.js
  tests/UI/data/faker/deliverySlipOptions.js
  tests/UI/data/faker/employee.js
  tests/UI/data/faker/featureAndValue.js
  tests/UI/data/faker/file.js
  tests/UI/data/faker/group.js
  tests/UI/data/faker/imageType.js
  tests/UI/data/faker/invoice.js
  tests/UI/data/faker/language.js
  tests/UI/data/faker/orderMessage.js
  tests/UI/data/faker/orderReturnStatus.js
  tests/UI/data/faker/orderStatus.js
  tests/UI/data/faker/product.js
  tests/UI/data/faker/productReview.js
  tests/UI/data/faker/profile.js
  tests/UI/data/faker/search.js
  tests/UI/data/faker/searchEngine.js
  tests/UI/data/faker/seoPage.js
  tests/UI/data/faker/shop.js
  tests/UI/data/faker/shopGroup.js
  tests/UI/data/faker/sqlQuery.js
  tests/UI/data/faker/state.js
  tests/UI/data/faker/store.js
  tests/UI/data/faker/supplier.js
  tests/UI/data/faker/tag.js
  tests/UI/data/faker/tax.js
  tests/UI/data/faker/taxRule.js
  tests/UI/data/faker/taxRuleGroup.js
  tests/UI/data/faker/title.js
  tests/UI/data/faker/webservice.js
  tests/UI/data/faker/zone.js
  tests/UI/data/import/addresses.js
  tests/UI/data/import/brands.js
  tests/UI/data/import/customers.js
  tests/UI/package-lock.json
  tests/UI/package.json
Labels: TE, 8.0.x, Refactoring, E2E Tests

#28922 Functional tests - Refactoring of 'Check footer links on FO' test
  tests/UI/campaigns/functional/FO/02_headerAndFooter/02_checkLinksInFooter.js
  tests/UI/pages/FO/FObasePage.js
Labels: TE, 8.0.x, Refactoring, E2E Tests
