Repository PrestaShop/PrestaShop, pull requests merged in 2022-05, with the labels that each got.

#28362 Request prestashop/blockreassurance 5.1.0 for 1.7.8.6
  composer.lock
Labels: Improvement, 1.7.8.x

#28103 Fixed profiler in PHP8.0 in migrated page
  tools/profiling/Profiler.php
Labels: QA ✔️, develop, Bug fix

#28226 Fix notifications color contrast on module manager page
  admin-dev/themes/default/scss/partials/_header.scss
  admin-dev/themes/new-theme/scss/mixins/_notification_counter.scss
Labels: QA ✔️, UX ✔️, develop, Bug fix

#28340 Functional tests - Add new test 'Bulk open in new tab'
  tests/UI/campaigns/functional/BO/02_orders/01_orders/07_bulkOpenInNewTab.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/08_sortOrders.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/09_viewCustomer.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/10_viewGuest.js
  tests/UI/commonTests/BO/customers/createDeleteCustomer.js
  tests/UI/pages/BO/orders/index.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#28066 add select2 in large select options
  admin-dev/themes/new-theme/scss/pages/orders/_orders_view.scss
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/General/PreferencesType.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/OrderPreferences/GeneralType.php
  src/PrestaShopBundle/Form/Admin/Improve/Shipping/Preferences/CarrierOptionsType.php
  src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php
  src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php
  src/PrestaShopBundle/Form/Admin/Sell/Address/ManufacturerAddressType.php
  src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/UpdateOrderShippingType.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/UpdateOrderStatusType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Category/CategoriesType.php
  src/PrestaShopBundle/Form/Admin/Sell/Supplier/SupplierType.php
Labels: Improvement, QA ✔️, develop

#28318 Extra message to display for an empty modules category
  install-dev/data/xml/hook.xml
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/grid_manage_empty.html.twig
Labels: Improvement, QA ✔️, PM ✔️, develop

#28153 Fix cart rule shop association
  admin-dev/themes/default/template/controllers/cart_rules/conditions.tpl
  admin-dev/themes/default/template/controllers/cart_rules/form.js
  controllers/admin/AdminCartRulesController.php
Labels: QA ✔️, develop, Bug fix, Wording ✔️

#28399 Fix Nightly 03/05/2022 - Fix export customer test
  tests/UI/pages/BO/customers/index.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#28412 Remove useless PrestaShop install
  .github/workflows/php.yml
Labels: Improvement, develop

#27803 No more auto created carts on login.
  classes/Context.php
  classes/controller/FrontController.php
Labels: QA ✔️, develop, Bug fix

#28380 Add module ps_distributionapiclient
  composer.json
  composer.lock
Labels: QA ✔️, develop, Feature

#28359 Bulk delete combinations
  admin-dev/themes/new-theme/js/fos_js_routes.json
  admin-dev/themes/new-theme/js/pages/product/combination/bulk-choices-selector.ts
  admin-dev/themes/new-theme/js/pages/product/combination/bulk-delete-handler.ts
  admin-dev/themes/new-theme/js/pages/product/combination/bulk-form-handler.ts
  admin-dev/themes/new-theme/js/pages/product/edit/combinations-manager.ts
  admin-dev/themes/new-theme/js/pages/product/product-map.ts
  admin-dev/themes/new-theme/js/pages/product/services/combinations-service.ts
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/product_v2/combination.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/paginated_list_header.html.twig
Labels: Waiting for wording, develop, Refactoring

#28370 Functional tests - Add test 'Pagination of orders table'
  tests/UI/campaigns/functional/BO/02_orders/01_orders/02_filterOrders.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/10_pagination.js
  tests/UI/campaigns/sanity/02_ordersBO/01_filterOrders.js
  tests/UI/pages/BO/orders/index.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#28414 Fix nightly 04/05/2022
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/05_carriersTab.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/09_addDiscount.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/11_checkInvoice.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/12_checkMultiInvoice.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/02_catalogPriceRules/02_filterSortAndPagination.js
  tests/UI/pages/BO/catalog/discounts/catalogPriceRules/index.js
  tests/UI/pages/BO/catalog/suppliers/add.js
  tests/UI/pages/BO/orders/view/tabListBlock.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#28068 Specific Price Form : Changing currency change the symbol
  admin-dev/themes/new-theme/js/components/form/currency-symbol-updater.ts
  admin-dev/themes/new-theme/js/components/form/reduction-tax-field-toggle.ts
  admin-dev/themes/new-theme/js/pages/catalog-price-rule/form/catalog-price-rule-form-map.ts
  admin-dev/themes/new-theme/js/pages/catalog-price-rule/form/index.ts
  admin-dev/themes/new-theme/js/pages/specific-price/form/index.ts
  admin-dev/themes/new-theme/js/pages/specific-price/specific-price-map.ts
  src/Adapter/Product/SpecificPrice/QueryHandler/GetSpecificPriceListHandler.php
  src/Adapter/Product/SpecificPrice/Repository/SpecificPriceRepository.php
  src/Core/Domain/Product/SpecificPrice/QueryResult/SpecificPriceForListing.php
  src/Core/Form/ChoiceProvider/CurrencyByIdChoiceProvider.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/SpecificPriceController.php
  src/PrestaShopBundle/Form/Admin/Sell/CatalogPriceRule/CatalogPriceRuleType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/SpecificPriceType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/CatalogPriceRule/Blocks/form.html.twig
  tests/Integration/Behaviour/Features/Context/Domain/Product/SpecificPriceContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/SpecificPrice/specific_prices_listing.feature
Labels: QA ✔️, develop, Bug fix, BC break, Needs documentation

#27683 Add a warning log when a module registers to a hook but implements no hook listener
  classes/Hook.php
  tests/Integration/Classes/module/ModuleTest.php
  tests/Resources/modules/bankwire/bankwire.php
Labels: QA ✔️, develop, Feature

#28290 Add product property `manufacturer_name`
  classes/Product.php
  src/Adapter/Presenter/Product/ProductLazyArray.php
Labels: Improvement, QA ✔️, develop

#27227 Don't reassign global vars in front controller
  controllers/front/CartController.php
  controllers/front/OrderController.php
Labels: QA ✔️, develop, Refactoring

#28310 Validate by github action if phpunit tests don't change repos state
  .github/workflows/behaviour.yml
  .github/workflows/integration.yml
  .github/workflows/php.yml
  tests/Unit/Core/Module/SourceHandler/ZipSourceHandlerTest.php
Labels: develop, Bug fix

#28358 Avoid ` ConnectException` check Webservice Endpoint
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceController.php
Labels: QA ✔️, develop, Bug fix

#28423 Functional tests - Add test to create and import csv file of addresses
  tests/UI/campaigns/functional/BO/04_customers/02_addresses/04_paginationAndSortAddresses.js
  tests/UI/commonTests/BO/customers/createDeleteAddress.js
  tests/UI/data/import/addresses.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#28332 Module manager : Restore modules actions order
  src/Adapter/Module/AdminModuleDataProvider.php
Labels: QA ✔️, develop, Bug fix

#28437 Functional tests - Delete close onboarding method
  tests/UI/campaigns/functional/FO/04_newsletter/01_subscribeNewsletter.js
  tests/UI/campaigns/sanity/03_productsBO/01_filterProducts.js
  tests/UI/commonTests/BO/loginBO.js
  tests/UI/pages/BO/BObasePage.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#28375 Add reset button to reset category filter in products list
  src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Blocks/filters.html.twig
Labels: Improvement, QA ✔️, develop, Wording ✔️

#27485 Add hook to allow adding buttons to modules catalogue toolbar
  classes/controller/AdminController.php
  install-dev/data/xml/hook.xml
  src/Core/Action/ActionsBarButton.php
  src/Core/Action/ActionsBarButtonInterface.php
  src/Core/Action/ActionsBarButtonsCollection.php
  src/PrestaShopBundle/Controller/Admin/Improve/Modules/ModuleAbstractController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/ActionsBarButton.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/ActionsBarButtonInterface.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/ActionsBarButtonsCollection.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
Labels: QA ✔️, develop, Feature

#28447 Use toolbar buttons array index as class when missing
  classes/controller/AdminController.php
Labels: QA ✔️, develop, Bug fix

#28451 New product price display and product summary
  admin-dev/themes/new-theme/js/components/form/form-object-mapper.ts
  admin-dev/themes/new-theme/js/pages/product/edit/index.ts
  admin-dev/themes/new-theme/js/pages/product/edit/price-summary.ts
  admin-dev/themes/new-theme/js/pages/product/edit/product-form-mapping.ts
  admin-dev/themes/new-theme/js/pages/product/edit/product-form-model.ts
  admin-dev/themes/new-theme/js/pages/product/product-map.ts
  admin-dev/themes/new-theme/scss/pages/product/product_page.scss
  src/Adapter/Session/Repository/CustomerSessionRepository.php
  src/Adapter/Session/Repository/EmployeeSessionRepository.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilder.php
  src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/PriceSummaryType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/PricingType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/header-details.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/FormTheme/product.html.twig
  tests/Integration/Behaviour/Features/Scenario/Security/security_configuration.feature
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProviderTest.php
Labels: Waiting for wording, develop, Feature, migration

#28277 Fix bugs for RTL languages by SCSS in BO
  admin-dev/themes/default/public/theme.rtlfix
  admin-dev/themes/default/scss/rtl.scss
  admin-dev/themes/default/template/controllers/login/header.tpl
  admin-dev/themes/new-theme/public/theme.rtlfix
  admin-dev/themes/new-theme/scss/rtl.scss
  classes/controller/AdminController.php
  src/Core/Localization/RTL/StylesheetGenerator.php
Labels: Improvement, QA ✔️, develop, BC break, Key feature

#27308 Restore needed removed row in customer view
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/view.html.twig
Labels: QA ✔️, develop, Bug fix

#27738 FO : Fix offset for "NEW" products listing
  classes/Product.php
Labels: QA ✔️, develop, Bug fix

#28309 Functional tests - Refacto 'Update order status'
  tests/UI/campaigns/functional/BO/02_orders/01_orders/04_checkInvoiceDownloadedFromList.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/04_updateStatus.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/05_bulkUpdateOrdersStatus.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/05_checkDeliverySlipDownloadedFromList.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/06_bulkOpenInNewTab.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/07_sortOrders.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/08_viewCustomer.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/09_viewGuest.js
  tests/UI/campaigns/sanity/02_ordersBO/01_filterOrders.js
  tests/UI/data/demo/orderStatuses.js
  tests/UI/pages/FO/FObasePage.js
  tests/UI/pages/FO/myAccount/orderHistory.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#28456 Functional tests - Add 'data-role' attribute to 'header-desc' selectors
  admin-dev/themes/default/template/page_header_toolbar.tpl
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule.js
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/03_titles/03_bulkDeleteTitles.js
  tests/UI/campaigns/functional/BO/15_header/02_quickAccess.js
  tests/UI/pages/BO/catalog/attributes/index.js
  tests/UI/pages/BO/catalog/discounts/catalogPriceRules/index.js
  tests/UI/pages/BO/catalog/discounts/index.js
  tests/UI/pages/BO/catalog/features/index.js
  tests/UI/pages/BO/design/imageSettings/index.js
  tests/UI/pages/BO/international/locations/countries/index.js
  tests/UI/pages/BO/international/locations/states/index.js
  tests/UI/pages/BO/international/taxes/taxRules/add.js
  tests/UI/pages/BO/international/taxes/taxRules/index.js
  tests/UI/pages/BO/quickAccess/index.js
  tests/UI/pages/BO/shipping/carriers/index.js
  tests/UI/pages/BO/shopParameters/customerSettings/groups/index.js
  tests/UI/pages/BO/shopParameters/customerSettings/titles/index.js
  tests/UI/pages/BO/shopParameters/search/index.js
  tests/UI/pages/BO/shopParameters/search/tags/index.js
  tests/UI/pages/BO/shopParameters/stores/index.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#28493 Fix nightly 13/05/2022 - Fix failed Orders tests
  tests/UI/campaigns/functional/BO/02_orders/01_orders/04_updateStatus.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/04_selectPreviousCarts.js
  tests/UI/pages/FO/myAccount/orderHistory.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#28506 Empty state for combinations list
  admin-dev/themes/new-theme/js/components/pagination/dynamic-paginator.ts
  admin-dev/themes/new-theme/js/pages/product/components/combination-list/combinations-list-renderer.ts
  admin-dev/themes/new-theme/js/pages/product/components/combination-list/index.ts
  admin-dev/themes/new-theme/js/pages/product/product-map.ts
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/empty_filters_state.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/paginated_list.html.twig
Labels: Waiting for wording, develop, Refactoring, migration

#28198 Remove deprecated method inside AbstractProvider
  src/PrestaShopBundle/Translation/Provider/AbstractProvider.php
Labels: Improvement, QA ✔️, develop, BC break, Needs documentation

#28461 Bump guzzle version to 7.4 (PHP 8.1 compatibility)
  composer.json
  composer.lock
Labels: Improvement, QA ✔️, develop

#28458 HelperList: remove notice if specificConfirmDelete is set to false #27718
  classes/helper/HelperList.php
Labels: QA ✔️, develop, Bug fix

#28460 Use config vars in `GetOrderForViewingHandler`
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
Labels: QA ✔️, develop, Refactoring

#28426 Fix product images size consistency
  themes/classic/templates/catalog/_partials/product-cover-thumbnails.tpl
Labels: QA ✔️, Bug fix, 1.7.8.x

#28231 Fix totals excluding tax in confirmation email
  classes/PaymentModule.php
Labels: QA ✔️, develop, Bug fix

#28266 Add regex constraint to the webservice key
  src/Core/ConstraintValidator/Constraints/TypedRegex.php
  src/Core/ConstraintValidator/TypedRegexValidator.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Webservice/WebserviceKeyType.php
  tests/Unit/Core/ConstraintValidator/TypedRegexValidatorTest.php
Labels: QA ✔️, develop, Bug fix

#28315 Fix delivery information for the product
  src/Adapter/Presenter/Product/ProductLazyArray.php
  tests/Integration/Adapter/Presenter/Product/ProductLazyArrayTest.php
Labels: QA ✔️, develop, Bug fix

#28072 Be able to skip CSV Header in CSV export
  src/PrestaShopBundle/Component/CsvResponse.php
Labels: Improvement, QA ✔️, develop, BC break

#28526 Fix wording
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Webservice/WebserviceKeyType.php
Labels: QA ✔️, develop, Refactoring, Wording ✔️

#28528 Merge 1.7.8.x into develop
  CONTRIBUTORS.md
  classes/Product.php
  docs/CHANGELOG.txt
Labels: Improvement, develop

#28544 Removed deprecated in Carrier class
  classes/Carrier.php
Labels: Improvement, QA ✔️, develop, BC break

#27187 Set country from browser language if option is set in customer address
  classes/Tools.php
  classes/controller/FrontController.php
  classes/form/CustomerAddressForm.php
Labels: QA ✔️, develop, Bug fix

#28545 Remove deprecated in Cart model
  classes/Cart.php
  classes/order/Order.php
  src/Adapter/Presenter/Cart/CartPresenter.php
Labels: Improvement, QA ✔️, develop, BC break, Needs documentation

#28575 Fix UI tests by selecting country on FO
  tests/UI/campaigns/functional/BO/02_orders/01_orders/06_bulkOpenInNewTab.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/09_viewGuest.js
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/02_sortAndPagination.js
  tests/UI/campaigns/functional/FO/11_checkout/02_addresses/02_useDifferentAddressForInvoice.js
  tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js
  tests/UI/pages/FO/checkout/index.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#27755 Move registration logic to new controller
  classes/Tools.php
  classes/controller/FrontController.php
  classes/lang/KeysReference/MetaLang.php
  config/xml/themes/default.xml
  controllers/front/AuthController.php
  controllers/front/RegistrationController.php
  controllers/front/SitemapController.php
  tests/UI/campaigns/functional/BO/04_customers/01_customers/05_setRequiredFields.js
  tests/UI/campaigns/functional/FO/02_headerAndFooter/02_checkLinksInFooter.js
Labels: QA ✔️, develop, Bug fix, Wording ✔️

#28558 Add fixed quantity update to bulk combination edition
  admin-dev/themes/new-theme/js/components/form/form-field-disabler.ts
  admin-dev/themes/new-theme/js/pages/product/combination/QuantityModeSwitcher.ts
  admin-dev/themes/new-theme/js/pages/product/combination/bulk.ts
  admin-dev/themes/new-theme/js/pages/product/product-event-map.ts
  admin-dev/themes/new-theme/js/pages/product/product-map.ts
  src/Adapter/Product/Combination/CommandHandler/UpdateCombinationStockHandler.php
  src/Core/Domain/Product/Combination/Command/UpdateCombinationStockCommand.php
  src/Core/Domain/Product/Stock/Exception/ProductStockConstraintException.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationStockCommandsBuilder.php
  src/Core/Form/IdentifiableObject/DataFormatter/BulkCombinationFormDataFormatter.php
  src/Core/Form/IdentifiableObject/DataProvider/BulkCombinationFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/BulkCombinationStockType.php
  src/PrestaShopBundle/Resources/config/services/adapter/product/_combination.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/UpdateCombinationStockFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/update_combination_stock.feature
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationStockCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataFormatter/BulkCombinationFormDataFormatterTest.php
Labels: Waiting for wording, develop, Refactoring

#28533 Introduce SetDefaultCombinationCommand
  src/Adapter/Product/Combination/CommandHandler/SetDefaultCombinationHandler.php
  src/Adapter/Product/Combination/CommandHandler/UpdateCombinationFromListingHandler.php
  src/Adapter/Product/Combination/QueryHandler/GetCombinationForEditingHandler.php
  src/Core/Domain/Product/Combination/Command/SetDefaultCombinationCommand.php
  src/Core/Domain/Product/Combination/Command/UpdateCombinationFromListingCommand.php
  src/Core/Domain/Product/Combination/CommandHandler/SetDefaultCombinationHandlerInterface.php
  src/Core/Domain/Product/Combination/QueryResult/CombinationForEditing.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/DefaultCombinationCommandsBuilder.php
  src/Core/Form/IdentifiableObject/DataProvider/CombinationFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationFormType.php
  src/PrestaShopBundle/Resources/config/services/adapter/product/_combination.yml
  src/PrestaShopBundle/Resources/config/services/core/form/command_builder.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/CombinationListingFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/GenerateCombinationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/SetDefaultCombinationFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/combinations_listing.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/set_default_combination.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/update_combination_from_listing.feature
  tests/Integration/Behaviour/behat.yml
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/DefaultCombinationCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/CombinationFormDataProviderTest.php
Labels: develop, Refactoring, Wording ✔️

#28559 Micro performance optimizations in Order class
  classes/order/Order.php
Labels: Improvement, QA ✔️, develop

#28584 Product list bulk delete and duplicate actions
  admin-dev/themes/new-theme/js/fos_js_routes.json
  src/Core/Grid/Definition/Factory/ProductGridDefinitionFactory.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/product_v2/product.yml
Labels: Waiting for QA, Waiting for wording, develop, Refactoring, migration

#28527 Functional Tests - Add test 'Choose address' in create order page
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/header.html.twig
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/03_createSimpleOrderInBO.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/08_chooseAddress.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/11_checkInvoice.js
  tests/UI/campaigns/functional/BO/04_customers/02_addresses/01_filterAddresses.js
  tests/UI/data/demo/address.js
  tests/UI/data/faker/address.js
  tests/UI/pages/BO/customers/addresses/add.js
  tests/UI/pages/BO/orders/add.js
  tests/UI/pages/BO/orders/index.js
  tests/UI/pages/BO/orders/view/viewOrderBasePage.js
  tests/UI/pages/FO/myAccount/orderDetails.js
  tests/UI/pages/FO/myAccount/orderHistory.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#28615 Add Db::ON_DUPLICATE_KEY into available possibilities
  classes/db/Db.php
Labels: Improvement, QA ✔️, develop

#28535 Removes old images and their hight DPI
  classes/Image.php
  controllers/admin/AdminImagesController.php
Labels: QA ✔️, develop, Bug fix

#28536 Functional tests - Add new test 'Check summary' on create order page
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/10_checkSummary.js
  tests/UI/pages/BO/orders/add.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#28623 Remove system-specific entries from gitignore
  .gitignore
Labels: develop, Refactoring, BC break

#28330 Extra message on module description
  src/Core/Module/ModuleRepository.php
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/card_list.html.twig
Labels: Improvement, QA ✔️, develop
