Repository PrestaShop/PrestaShop, pull requests merged in 2022-03, with the labels that each got.

#27416 Remove unused variables in Cart::applyProductCalculations()
  classes/Cart.php
Labels: develop, Refactoring

#27767 Add autocomplete="off" to date picker inputs in helpers
  admin-dev/themes/default/template/helpers/form/form.tpl
  admin-dev/themes/default/template/helpers/list/list_header.tpl
Labels: QA ✔️, develop, Bug fix

#27641 Added CQRS Commands & Queries for State domain
  src/Adapter/State/CommandHandler/BulkDeleteStateHandler.php
  src/Adapter/State/CommandHandler/BulkToggleStateStatusHandler.php
  src/Adapter/State/CommandHandler/DeleteStateHandler.php
  src/Adapter/State/CommandHandler/ToggleStateStatusHandler.php
  src/Adapter/State/QueryHandler/GetStateForEditingHandler.php
  src/Core/Domain/State/Command/BulkDeleteStateCommand.php
  src/Core/Domain/State/Command/BulkToggleStateStatusCommand.php
  src/Core/Domain/State/Command/DeleteStateCommand.php
  src/Core/Domain/State/Command/ToggleStateStatusCommand.php
  src/Core/Domain/State/CommandHandler/BulkDeleteStateHandlerInterface.php
  src/Core/Domain/State/CommandHandler/BulkToggleStateStatusHandlerInterface.php
  src/Core/Domain/State/CommandHandler/DeleteStateHandlerInterface.php
  src/Core/Domain/State/CommandHandler/ToggleStateStatusHandlerInterface.php
  src/Core/Domain/State/Exception/CannotToggleStateStatusException.php
  src/Core/Domain/State/Exception/DeleteStateException.php
  src/Core/Domain/State/Exception/StateNotFoundException.php
  src/Core/Domain/State/Query/GetStateForEditing.php
  src/Core/Domain/State/QueryHandler/GetStateForEditingHandlerInterface.php
  src/Core/Domain/State/QueryResult/EditableState.php
  src/PrestaShopBundle/Resources/config/services/adapter/state.yml
  tests/Integration/Behaviour/Features/Context/Domain/StateFeatureContext.php
  tests/Integration/Behaviour/Features/Context/StateFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/State/state_management.feature
  tests/Integration/Behaviour/behat.yml
Labels: Improvement, develop

#24584 Database update command - Wrong SQL Query generated
  src/PrestaShopBundle/Command/UpdateSchemaCommand.php
  tests/Unit/PrestaShopBundle/Command/UpdateSchemaCommandTest.php
Labels: QA ✔️, develop, Bug fix

#27347 Added contextual information messages in multistore context
  admin-dev/themes/default/template/content.tpl
  admin-dev/themes/new-theme/js/components/components-map.ts
  admin-dev/themes/new-theme/js/components/contextual-notification.ts
  admin-dev/themes/new-theme/js/components/form/multistore-config-field.ts
  admin-dev/themes/new-theme/js/components/multistore-header.ts
  admin-dev/themes/new-theme/scss/components/_alert.scss
  admin-dev/themes/new-theme/scss/theme.scss
  admin-dev/themes/new-theme/template/content.tpl
  src/PrestaShopBundle/Controller/Admin/MultistoreController.php
  src/PrestaShopBundle/Resources/views/Admin/Multistore/header.html.twig
Labels: QA ✔️, develop, Feature, Wording ✔️

#27763 Add help field when integer type is used to a form
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: QA ✔️, Bug fix, 1.7.8.x

#27827 Release 1.7.8.4
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: Improvement, 1.7.8.x

#27510 Improve wording tooltip Traffic & SEO > Schema of URLs
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/TrafficSeo/Meta/Blocks/url_schema_configuration.html.twig
Labels: Improvement, QA ✔️, develop, Wording ✔️

#27762 Add help field when integer type is used to a form
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: QA ✔️, develop, Bug fix

#27808 Fixes Security controller help frame opening CORS Problem
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SecurityController.php
Labels: QA ✔️, develop, Bug fix

#27831 Fix Github Action: Use absolute paths for hashFiles
  .github/workflows/sanity.yml
Labels: develop, Bug fix

#27663 Fixed wording on Security page
  src/Core/Grid/Definition/Factory/BulkDeleteActionTrait.php
  src/Core/Grid/Definition/Factory/DeleteActionTrait.php
  src/Core/Grid/Definition/Factory/Security/Session/CustomerGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/Security/Session/EmployeeGridDefinitionFactory.php
Labels: QA ✔️, develop, Feature, Wording ✔️

#27815 Display Ecotax select when ecotax is enabled, without saving
  admin-dev/themes/new-theme/js/pages/tax/index.ts
  admin-dev/themes/new-theme/js/pages/tax/tax-map.ts
  src/PrestaShopBundle/Form/Admin/Improve/International/Tax/TaxOptionsType.php
Labels: QA ✔️, develop, Bug fix

#27620 Multistore - Catalog > Stocks > Stocks & Movements - Update message in all shops or in a group context
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Stock/overview.html.twig
Labels: QA ✔️, develop, Bug fix, Wording ✔️

#27837 Fix Github Action: Use absolute paths for hashFiles (cherry pick of #27831)
  .github/workflows/sanity-72.yml
  .github/workflows/sanity-73.yml
  .github/workflows/sanity-74.yml
  .github/workflows/sanity.yml
Labels: Bug fix, 1.7.8.x

#27720 MultiStore - Sell > Customer Service > Merchandise Return - Add Checkbox & Simplify Form
  admin-dev/themes/new-theme/js/pages/merchandise-return/index.ts
  src/Core/MerchandiseReturn/Configuration/MerchandiseReturnOptionsConfiguration.php
  src/PrestaShopBundle/Form/Admin/Sell/CustomerService/MerchandiseReturn/MerchandiseReturnOptionsType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer_service/merchandise_return.yml
  src/PrestaShopBundle/Resources/config/services/adapter/data_configuration.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/CustomerService/MerchandiseReturn/Blocks/options.html.twig
  tests/Unit/Core/MerchandiseReturn/Configuration/MerchandiseReturnOptionsConfigurationTest.php
Labels: QA ✔️, develop, Bug fix, Wording ✔️

#27820 Functional tests - Add new test 'Select previous order'
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/04_selectPreviousOrders.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/03_statusTab.js
  tests/UI/commonTests/BO/customers/createDeleteAddress.js
  tests/UI/pages/BO/orders/add.js
  tests/UI/pages/BO/orders/view/messagesBlock.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#27394 Improve Cart Rule Form Responsive footer
  admin-dev/themes/default/scss/admin-theme.scss
  admin-dev/themes/default/scss/controllers/_cartrules.scss
  admin-dev/themes/default/template/footer_toolbar.tpl
Labels: QA ✔️, UX ✔️, develop, Bug fix

#27373 BO Migration Contact > Stores - Add command, command handler and behat tests for status toggle
  src/Adapter/Store/CommandHandler/ToggleStoreStatusHandler.php
  src/Adapter/Store/QueryHandler/GetStoreForEditingHandler.php
  src/Core/Domain/Store/Command/ToggleStoreStatusCommand.php
  src/Core/Domain/Store/CommandHandler/ToggleStoreStatusHandlerInterface.php
  src/Core/Domain/Store/Exception/CannotToggleStoreStatusException.php
  src/Core/Domain/Store/Exception/CannotUpdateStoreException.php
  src/Core/Domain/Store/Query/GetStoreForEditing.php
  src/Core/Domain/Store/QueryHandler/GetStoreForEditingHandlerInterface.php
  src/Core/Domain/Store/QueryResult/StoreForEditing.php
  src/Core/Domain/Store/Repository/StoreRepository.php
  src/PrestaShopBundle/Resources/config/services/adapter/store.yml
  tests/Integration/Behaviour/Features/Context/Domain/StoreFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Store/store.feature
  tests/Integration/Behaviour/behat.yml
Labels: Improvement, develop, migration

#27673 Remove ecotax field when the product is virtual
  src/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/ProductTypeListener.php
  tests/Integration/PrestaShopBundle/Form/EventListener/ProductTypeListenerTest.php
  tests/Integration/PrestaShopBundle/Form/TestProductFormType.php
  themes/classic/templates/catalog/_partials/product-prices.tpl
Labels: QA ✔️, develop, Feature

#27275 Move condition field from options to specifications tab
  admin-dev/themes/new-theme/scss/components/_form.scss
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/OptionsCommandsBuilder.php
  src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationFormType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationPriceImpactType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Description/DescriptionType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Description/ManufacturerType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Options/OptionsType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Options/ProductAttachmentsType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Options/SuppliersType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Options/VisibilityType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/PricingType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/UnitPriceType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/SEO/RedirectOptionType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/SEO/SEOType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Shipping/DimensionsType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Shipping/ShippingType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Specification/CustomizationsType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Specification/ReferencesType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Specification/SpecificationsType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/AvailabilityType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/QuantityType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/StockOptionsType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/StockType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/VirtualProductFileType.php
  src/PrestaShopBundle/Form/Admin/Type/SwitchType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductOptionsCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProviderTest.php
Labels: Improvement, QA ✔️, develop, migration, BC break, Wording ✔️

#27859 Update decimal to make it work without bcmath
  composer.lock
Labels: Improvement, develop

#27527 Remove deprecated enable_mobile|disable_mobile
  admin-dev/themes/default/js/bundle/module/module.js
  admin-dev/themes/default/js/bundle/module/module_card.js
  admin-dev/themes/new-theme/js/components/module-card.ts
  admin-dev/themes/new-theme/js/pages/module/controller.js
  src/Adapter/Module/AdminModuleDataProvider.php
  src/Adapter/Module/Module.php
  src/Core/Addon/Module/ModuleManager.php
  src/PrestaShopBundle/Command/ModuleCommand.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/modules/_modules.yml
  tests/Unit/Core/Addon/Module/ModuleManagerTest.php
Labels: Improvement, QA ✔️, develop, BC break

#27646 Added module productcomments (now compatible with PS 8.0)
  composer.json
  composer.lock
  themes/classic/config/theme.yml
Labels: QA ✔️, develop, Bug fix

#27813 Fix css specificity issue in mobile menu
  admin-dev/themes/default/scss/partials/_nav.scss
  admin-dev/themes/new-theme/scss/components/layout/_nav_bar.scss
Labels: QA ✔️, Bug fix

#27776 Stock field must be empty and still be considered as zero
  admin-dev/themes/new-theme/js/app/pages/stock/components/overview/spinner.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-number.vue
Labels: QA ✔️, Bug fix, 1.7.8.x

#27822 Don't allow emails without TLD in the Email Validator
  classes/Validate.php
  tests/Unit/Adapter/ValidateTest.php
  tests/Unit/Classes/ValidateCoreTest.php
Labels: QA ✔️, develop, Bug fix

#26048 Check quantities at any point of checkout process
  classes/checkout/CheckoutPaymentStep.php
  controllers/front/OrderController.php
  themes/_core/js/checkout-payment.js
  themes/package-lock.json
Labels: QA ✔️, develop, Bug fix, Documentation

#27848 Check href exists before replacing it in multistore header
  admin-dev/themes/new-theme/js/components/multistore-header.ts
Labels: QA ✔️, develop, Bug fix

#27843 Fix: login page float buggy on latest chrome version and long shop name problem
  admin-dev/themes/default/scss/controllers/_login.scss
  admin-dev/themes/default/template/controllers/login/content.tpl
Labels: QA ✔️, Bug fix, 1.7.8.x

#27793 BO - Customer Page - Allow only positive number for Maximum number of payment days
  classes/Validate.php
  src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php
Labels: QA ✔️, develop, Bug fix, Wording ✔️

#27851 Simply Delivery Slip Form
  src/PrestaShopBundle/Form/Admin/Sell/Order/Delivery/SlipOptionsType.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/Delivery/SlipPdfType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Delivery/slip.html.twig
Labels: Improvement, QA ✔️, develop, BC break, Wording ✔️

#27860 Added hooks for blockwishlist in classic theme
  themes/classic/config/theme.yml
Labels: QA ✔️, develop, Bug fix

#27814 Fixed Microdata ItemList position : index starts to 1 and not 0
  themes/classic/templates/_partials/microdata/product-list-jsonld.tpl
Labels: QA ✔️, Bug fix, 1.7.8.x

#27850 Move notifications divs to the vuejs app
  admin-dev/themes/new-theme/js/app/pages/stock/components/header/stock-header.vue
  admin-dev/themes/new-theme/js/components/components-map.ts
  admin-dev/themes/new-theme/scss/pages/stock/stock_page.scss
Labels: QA ✔️, develop, Bug fix

#24797 Force disabled discounts (CartRules) to show if needed
  classes/CartRule.php
  src/Adapter/Customer/QueryHandler/GetCustomerForViewingHandler.php
  src/Core/Grid/Data/Factory/CustomerDiscountGridDataFactory.php
  src/Core/Search/Filters/CustomerDiscountFilters.php
  tests/Integration/Classes/CartRuleTest.php
Labels: QA ✔️, develop, Bug fix

#27868 The delivery slip date in the template must be the delivery date and not the invoice creation date
  classes/pdf/HTMLTemplateDeliverySlip.php
Labels: QA ✔️, develop, Bug fix

#27644 Remove unused FrontController properties
  classes/controller/FrontController.php
  controllers/front/listing/ManufacturerController.php
Labels: develop, Refactoring

#27919 Changelog 1.7.8.5
  docs/CHANGELOG.txt
Labels: Improvement, 1.7.8.x

#27923 Added module ps_emailalerts
  composer.json
  composer.lock
Labels: QA ✔️, develop, Bug fix

#27895 Handle seo data for multishop
  admin-dev/themes/new-theme/js/pages/product/edit/product-form-mapping.ts
  src/Adapter/Product/CommandHandler/UpdateProductSeoHandler.php
  src/Core/Domain/Product/Command/UpdateProductSeoCommand.php
  src/Core/Form/IdentifiableObject/CommandBuilder/CommandBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/CommandBuilderConfig.php
  src/Core/Form/IdentifiableObject/CommandBuilder/CommandField.php
  src/Core/Form/IdentifiableObject/CommandBuilder/DataField.php
  src/Core/Form/IdentifiableObject/CommandBuilder/DataFieldException.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/BasicInformationCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/SEOCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/StockCommandsBuilder.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/SEO/RedirectOptionType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/SEO/SEOType.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/core/form/command_builder.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateSeoFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_multishop_seo.feature
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/CommandBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/CommandBuilderTestCommand.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/CommandFieldTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/DataFieldTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/SEOCommandsBuilderTest.php
Labels: Improvement, Waiting for QA, develop, migration

#27974 Pin setup-gcloud to v0 instead of master
  .github/workflows/cron_nightly_build.yml
  .github/workflows/cron_nightly_gcp.yml
  .github/workflows/cron_nightly_tests.yml
Labels: Improvement, develop, Developer Feature, CI/CD

#26824 Avoid using _PS_PRICE_COMPUTE_PRECISION_
  classes/PaymentModule.php
Labels: QA ✔️, Bug fix, 1.7.8.x

#27626 Fix stock movement creation from new order
  classes/order/OrderDetail.php
  src/PrestaShopBundle/Entity/Repository/StockManagementRepository.php
  src/PrestaShopBundle/Entity/Repository/StockMovementRepository.php
  src/PrestaShopBundle/Entity/Repository/StockRepository.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_stock.feature
Labels: QA ✔️, develop, Bug fix, BC break, Needs documentation

#27756 FO: Remove Front controller deprecated properties
  classes/controller/FrontController.php
Labels: Improvement, QA ✔️, develop

#27914 Remove deprecated include "images.inc.php"
  admin-dev/functions.php
  images.inc.php
Labels: Improvement, develop, BC break

#27961 Remove Adapter\Tools::bcadd
  src/Adapter/Tools.php
  tests/Unit/Adapter/ToolsTest.php
Labels: develop, Bug fix

#27956 Remove useless parameters in displayDate method
  classes/PaymentModule.php
  classes/Tools.php
  controllers/admin/AdminCustomerThreadsController.php
  controllers/front/DiscountController.php
  controllers/front/OrderSlipController.php
  src/Adapter/Customer/QueryHandler/GetCustomerForViewingHandler.php
  src/Adapter/CustomerService/CommandHandler/ForwardCustomerThreadHandler.php
  src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php
  src/Adapter/Presenter/Order/OrderDetailLazyArray.php
  src/Adapter/Presenter/Order/OrderLazyArray.php
  src/Adapter/Presenter/Order/OrderReturnLazyArray.php
  src/Adapter/Tools.php
Labels: Improvement, develop

#28009 Remove OrderHistory getLastOrderState deprecated function
  classes/order/OrderHistory.php
Labels: Improvement, develop

#27364 Deprecate Tools::redirectLink
  classes/Tools.php
  classes/controller/FrontController.php
  tools/profiling/Tools.php
Labels: QA ✔️, develop, Bug fix

#28007 Use category ME instead of [merge] in PR title to allow merge commit
  .github/workflows/pr.yml
Labels: Improvement, develop

#27959 Remove AdminController deprecated
  classes/controller/AdminController.php
Labels: Improvement, develop

#27958 Remove Tools::display404Error
  classes/Tools.php
Labels: Improvement, develop

#27925 Remove all deprecated templates in /admin-dev/themes/default/template/controllers/modules_positions/
  admin-dev/themes/default/template/controllers/modules_positions/form.tpl
  admin-dev/themes/default/template/controllers/modules_positions/index.php
  admin-dev/themes/default/template/controllers/modules_positions/list_modules.tpl
Labels: Improvement, develop, BC break

#28022 Fixed the exception when we disable the tax in the BO > International > Taxes page
  src/Core/Tax/TaxOptionsConfiguration.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Tax/TaxOptionsType.php
Labels: QA ✔️, develop, Bug fix

#28003 Fixed wording and color button on exit button for the bulk delete
  src/PrestaShopBundle/Resources/views/Admin/Helpers/bootstrap_popup.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/catalog.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/delete_categories_modal.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/delete_modal.html.twig
Labels: QA ✔️, develop, Bug fix, Wording ✔️

#27669 Multistore - Design > Position - Do not display content and update message in all shops or in a group context
  src/PrestaShopBundle/Controller/Admin/Improve/Design/PositionsController.php
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/positions.html.twig
Labels: QA ✔️, develop, Bug fix, migration, Wording ✔️

#27667 Multistore - Payment > Payment methods - Do not display content and update message in all shops or in a group context
  src/PrestaShopBundle/Resources/views/Admin/Improve/Payment/PaymentMethods/payment_methods.html.twig
Labels: QA ✔️, develop, Bug fix, migration, Wording ✔️

#27781 Fixes error which occurred when you try to modify any customer information after the import
  controllers/admin/AdminImportController.php
Labels: QA ✔️, develop, Bug fix

#28001 In Stock Movement page, localize date & time
  admin-dev/themes/new-theme/js/app/pages/stock/components/movements/movement-line.vue
  src/PrestaShopBundle/Entity/Repository/StockMovementRepository.php
  src/PrestaShopBundle/Resources/config/services/bundle/repository.yml
Labels: Improvement, QA ✔️, develop

#28015 Added module ps_googleanalytics
  composer.json
  composer.lock
Labels: QA ✔️, develop, Bug fix

#28044 Pin setup-gcloud to v0 instead of master (backport of #27974)
  .github/workflows/cron_nightly.yml
Labels: Improvement, Developer Feature, CI/CD, 1.7.8.x

#28010 Remove OrderSlip createOrderSlip deprecated function
  classes/order/OrderSlip.php
Labels: Improvement, develop, BC break, Needs documentation

#28021 Remove HookExtension::hookCount method
  src/PrestaShopBundle/Twig/HookExtension.php
Labels: Improvement, develop, BC break, Needs documentation

#27922 Avoid Notice: Trying to access array offset on value of type bool
  classes/Product.php
Labels: QA ✔️, FO, Bug fix, 1.7.8.x

#26938 SpecificPrice priority form
  admin-dev/themes/new-theme/js/components/form/disabling-toggler.ts
  admin-dev/themes/new-theme/js/pages/product/components/specific-price/specific-price-list.ts
  admin-dev/themes/new-theme/js/pages/product/edit/index.ts
  admin-dev/themes/new-theme/js/pages/product/edit/specific-prices-manager.ts
  admin-dev/themes/new-theme/js/pages/product/product-map.ts
  admin-dev/themes/new-theme/scss/pages/_product_preferences.scss
  admin-dev/themes/new-theme/scss/pages/product/product_page.scss
  admin-dev/themes/new-theme/scss/theme.scss
  classes/SpecificPrice.php
  install-dev/data/xml/configuration.xml
  src/Adapter/Product/GeneralConfiguration.php
  src/Adapter/Product/QueryHandler/GetProductForEditingHandler.php
  src/Adapter/Product/SpecificPrice/CommandHandler/RemoveSpecificPricePriorityForProductHandler.php
  src/Adapter/Product/SpecificPrice/Repository/SpecificPriceRepository.php
  src/Adapter/Product/SpecificPrice/Update/SpecificPricePriorityUpdater.php
  src/Core/Domain/Product/QueryResult/ProductPricesInformation.php
  src/Core/Domain/Product/SpecificPrice/Command/RemoveSpecificPricePriorityForProductCommand.php
  src/Core/Domain/Product/SpecificPrice/CommandHandler/RemoveSpecificPricePriorityForProductHandler.php
  src/Core/Domain/Product/SpecificPrice/CommandHandler/RemoveSpecificPricePriorityForProductHandlerInterface.php
  src/Core/Domain/Product/SpecificPrice/ValueObject/PriorityList.php
  src/Core/Form/ChoiceProvider/SpecificPricePriorityChoiceProvider.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/SpecificPricePriorityCommandsBuilder.php
  src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php
  src/Core/Form/IdentifiableObject/DataProvider/SpecificPriceFormDataProvider.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/GeneralType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/PricingType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/ProductSpecificPricePriorityType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/SpecificPricePriorityType.php
  src/PrestaShopBundle/Form/Admin/Type/EventListener/ReductionListener.php
  src/PrestaShopBundle/Resources/config/services/adapter/data_configuration.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_specific_prices.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/choice_provider.yml
  src/PrestaShopBundle/Resources/config/services/core/form/command_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_general.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/SpecificPrice/Blocks/list.html.twig
  tests/Integration/Behaviour/Features/Context/Domain/Product/SpecificPricePrioritiesFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/SpecificPrice/specific_price_priorities.feature
  tests/Integration/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminControllerTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/SpecificPricePriorityCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProviderTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/SpecificPriceFormDataProviderTest.php
Labels: QA ✔️, develop, Refactoring, migration, Wording ✔️

#26774 Fix missing canonicals
  classes/controller/ProductListingFrontController.php
  controllers/front/listing/BestSalesController.php
  controllers/front/listing/CategoryController.php
  controllers/front/listing/ManufacturerController.php
  controllers/front/listing/NewProductsController.php
  controllers/front/listing/PricesDropController.php
  controllers/front/listing/SearchController.php
  controllers/front/listing/SupplierController.php
Labels: QA ✔️, develop, Bug fix

#28060 Removed phpstan-ignore with use of `dynamicConstantNames`
  admin-dev/index.php
  classes/Media.php
  classes/PaymentModule.php
  classes/Smarty/SmartyResourceModule.php
  classes/Smarty/SmartyResourceParent.php
  classes/Tools.php
  classes/cache/CacheMemcached.php
  classes/controller/Controller.php
  classes/controller/FrontController.php
  classes/db/Db.php
  classes/exception/PrestaShopException.php
  classes/module/Module.php
  config/config.inc.php
  config/defines.inc.php
  config/smarty.config.inc.php
  config/smartyadmin.config.inc.php
  config/smartyfront.config.inc.php
  controllers/admin/AdminAccessController.php
  controllers/admin/AdminImportController.php
  controllers/admin/AdminLoginController.php
  controllers/admin/AdminModulesController.php
  controllers/admin/AdminModulesPositionsController.php
  controllers/admin/AdminRequestSqlController.php
  controllers/admin/AdminTabsController.php
  controllers/admin/AdminTranslationsController.php
  install-dev/controllers/http/process.php
  install-dev/controllers/http/welcome.php
  install-dev/index.php
  install-dev/index_cli.php
  install-dev/missing_requirement.php
  js/retro-compat.js.php
  phpstan.neon.dist
  src/PrestaShopBundle/Install/Install.php
Labels: Improvement, develop

#28076 Remove unwanted char
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Localization/Blocks/configuration.html.twig
Labels: Bug fix, 1.7.8.x

#27983 Fix PHPDoc on Address class
  classes/Address.php
Labels: Improvement, develop

#28078 Fix check merge commit Github action
  .github/workflows/pr.yml
Labels: develop, Bug fix

#27969 Add the possibility to load PHP / XML files for modules services
  src/PrestaShopBundle/DependencyInjection/Compiler/LoadServicesFromModulesPass.php
Labels: Improvement, QA ✔️, develop

#28031 Handle empty outstanding_allow_amount field
  src/Core/Grid/Data/Factory/OutstandingGridDataFactory.php
Labels: QA ✔️, Bug fix, 1.7.8.x

#28083 Remove useless sensio/distribution-bundle composer scripts
  composer.json
Labels: Bug fix, 1.7.8.x

#27662 Allow X at the end of ISBN
  classes/Validate.php
  src/Core/Domain/Product/ValueObject/Isbn.php
  src/PrestaShopBundle/Form/Admin/Product/ProductOptions.php
  tests/Unit/Core/ConstraintValidator/TypedRegexValidatorTest.php
  tests/Unit/Core/Domain/Product/ValueObject/IsbnTest.php
  tests/Unit/Core/Domain/Product/ValueObject/RedirectTypeTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationDetailsCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/DetailsCommandsBuilderTest.php
Labels: QA ✔️, develop, Feature

#28052 Fixed incompatibility of private property in PS 1.7.8.0
  classes/pdf/PDF.php
Labels: Bug fix, 1.7.8.x

#27555 Fix update attachment webservice
  classes/webservice/WebserviceSpecificManagementAttachments.php
Labels: QA ✔️, Bug fix, 1.7.8.x

#27404 Simplify multistore service call in controllers
  classes/controller/AdminController.php
  classes/controller/Controller.php
  controllers/admin/AdminLegacyLayoutController.php
  controllers/admin/AdminStatesController.php
Labels: Improvement, QA ✔️, develop

#27941 [FO] : displayOverrideTemplate hook not executing on checkout page due to naming issue.
  classes/controller/FrontController.php
Labels: Improvement, QA ✔️, develop, BC break, Needs documentation

#26743 Provide modules information about old order status
  classes/order/OrderHistory.php
Labels: Improvement, QA ✔️, develop, Topwatchers, Needs documentation
