Repository PrestaShop/PrestaShop, pull requests merged in 2022-08, with the labels that each got.

#28799 Sort product table (in email, invoices and order view) by reference id
  classes/pdf/HTMLTemplateDeliverySlip.php
  classes/pdf/HTMLTemplateInvoice.php
  classes/pdf/HTMLTemplateOrderSlip.php
  src/Adapter/Cart/QueryHandler/GetCartForViewingHandler.php
  src/Adapter/Order/QueryHandler/GetOrderPreviewHandler.php
  src/Adapter/Order/QueryHandler/GetOrderProductsForViewingHandler.php
  src/Core/Util/Sorter.php
  tests/Unit/Core/Util/SorterTest.php
Labels: Improvement, QA ✔️, develop

#29199 Fix 29165 BO input unit display
  src/PrestaShopBundle/Form/Admin/Extension/UnitTypeExtension.php
  src/PrestaShopBundle/Form/Admin/Product/ProductCombination.php
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combination.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_horizontal_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: QA ✔️, 8.0.x, Bug fix

#29174 Toggle condition availability based on show_condition
  admin-dev/themes/new-theme/js/pages/product/edit/index.ts
  admin-dev/themes/new-theme/js/pages/product/edit/product-specifications-manager.ts
  admin-dev/themes/new-theme/js/pages/product/product-map.ts
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/OptionsCommandsBuilder.php
  src/PrestaShopBundle/Form/Admin/Extension/DisablingSwitchTrait.php
  src/PrestaShopBundle/Form/Admin/Type/DisablingSwitchType.php
Labels: QA ✔️, 8.0.x, Bug fix

#27422 Use core translations sources for themes in addition to the translations of the theme itself
  config/smartyfront.config.inc.php
  src/Core/Translation/Builder/TranslationCatalogueBuilder.php
  src/Core/Translation/Storage/Provider/CatalogueProviderFactory.php
  src/Core/Translation/Storage/Provider/Definition/ModulesProviderDefinition.php
  src/Core/Translation/Storage/Provider/ModuleCatalogueProviderFactory.php
  src/Core/Translation/Storage/Provider/ThemeCatalogueLayersProvider.php
  src/PrestaShopBundle/Resources/config/services/bundle/translation.yml
  src/PrestaShopBundle/Service/TranslationService.php
  src/PrestaShopBundle/Translation/Loader/DatabaseTranslationLoader.php
  src/PrestaShopBundle/Translation/Loader/SqlTranslationLoader.php
  src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php
  tests/Integration/Core/Translation/Storage/Provider/ThemeCatalogueLayersProviderTest.php
  tests/Unit/Core/Translation/Builder/TranslationTreeBuilderTest.php
Labels: QA ✔️, Bug fix, BC break, 1.7.8.x

#29024 Fixes BO Dashdoard Button wrong display
  js/admin/dashboard.js
Labels: QA ✔️, 8.0.x, Bug fix

#28820 Add employee info on the Payments tab when payment is registered
  classes/order/Order.php
  classes/order/OrderPayment.php
  install-dev/data/db_structure.sql
  src/Adapter/Order/CommandHandler/AddPaymentHandler.php
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Core/Domain/Order/Payment/Command/AddPaymentCommand.php
  src/Core/Domain/Order/QueryResult/OrderPaymentForViewing.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/payments.html.twig
  tests/Integration/Behaviour/Features/Context/Domain/OrderPaymentFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Order/order_add_payment.feature
  tests/Unit/Core/Domain/Order/Payment/Command/AddPaymentCommandTest.php
Labels: QA ✔️, develop, Feature, Wording ✔️

#29239 Update composer deps and lock classic to beta-2.0.0
  composer.json
  composer.lock
Labels: Improvement, QA ✔️, 8.0.x

#29261 Bump distribution API module to 1.0.1
  composer.lock
Labels: Improvement, QA ✔️, 8.0.x

#29230 Add help.prestashop-project.org documentation links & fix popup opening
  admin-dev/themes/default/js/help.js
  classes/controller/AdminController.php
  src/Core/Help/Documentation.php
  src/PrestaShopBundle/Bridge/Smarty/ToolbarFlagsConfigurator.php
  src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php
  src/PrestaShopBundle/Resources/config/services/bundle/bridge.yml
  src/PrestaShopBundle/Resources/config/services/core/help.yml
Labels: Improvement, QA ✔️, 8.0.x, BC break

#29276 Changelog for 8.0 beta 1
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: Improvement, 8.0.x

#28441 IP white list should not be preconfigured
  install-dev/data/xml/configuration.xml
Labels: Improvement, QA ✔️, develop

#29256 When there no module upgrade script to run, make module upgrade succeed
  src/Core/Module/ModuleManager.php
Labels: QA ✔️, 8.0.x, Bug fix

#29113 More data available for the productoutofstock email
  src/Core/Stock/StockManager.php
Labels: Improvement, QA ✔️, develop

#28846 Functional tests - Add new test 'Change Currency' in FO
  tests/UI/campaigns/functional/FO/02_headerAndFooter/03_changeCurrency.js
  tests/UI/data/demo/currencies.js
  tests/UI/pages/BO/international/currencies/index.js
  tests/UI/pages/FO/FObasePage.js
  tests/UI/pages/FO/searchResults/index.js
Labels: TE, 8.0.x, Refactoring, E2E Tests

#29227 Bump wishlist to 2.1.2
  composer.lock
Labels: Improvement, QA ✔️, 1.7.8.x

#29278 Fix undefined quantity index in light product list
  src/Adapter/Product/Grid/Data/Factory/ProductLightGridDataFactoryDecorator.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
Labels: QA ✔️, 8.0.x, Bug fix

#29272 Making PHP8.1 implicit conversion explicit
  admin-dev/filemanager/include/php_image_magician.php
Labels: QA ✔️, 8.0.x, Bug fix

#29180 Fix order payment currency unit
  src/PrestaShopBundle/Form/Admin/Sell/Order/OrderPaymentType.php
  src/PrestaShopBundle/Form/Admin/Type/AmountCurrencyType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/payments.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_horizontal_layout.html.twig
Labels: QA ✔️, 8.0.x, Bug fix

#29161 [29152] Fix update order status settings with readonly user
  controllers/admin/AdminStatusesController.php
Labels: QA ✔️, develop, Bug fix, Wording ✔️

#29114 BO > Customers > Addresses - Required fields are not used in back office
  src/Core/Form/IdentifiableObject/OptionProvider/CustomerAddressFormOptionsProvider.php
  src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php
  src/PrestaShopBundle/Resources/config/services/core/form/form_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_options_provider.yml
  tests/Unit/Core/Form/IdentifiableObject/OptionsProvider/CustomerAddressFormOptionsProviderTest.php
Labels: QA ✔️, develop, Bug fix

#29214 Fix logo on pdf for RTL
  composer.json
  composer.lock
Labels: QA ✔️, Bug fix, 1.7.8.x

#28762 Target the table on the reload of the page after a sort
  admin-dev/themes/new-theme/js/app/utils/table-sorting.ts
  admin-dev/themes/new-theme/js/pages/customer/index.ts
Labels: QA ✔️, develop, Bug fix

#29290 Fix nightly 8.0.x - 09/08/2022 - 'Enable/Disable guest checkout' and 'Check links in footer page'
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/02_enableGuestCheckout.js
  tests/UI/pages/FO/FObasePage.js
  tests/UI/pages/FO/checkout/index.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#26788 Cart: replace this->getAssociatedLanguage()->getId() by equivalent th…
  classes/ObjectModel.php
Labels: QA ✔️, develop, Bug fix

#29311 Functional tests - Skip some steps on 'FO > Edit information' test after the new behavior
  tests/UI/campaigns/functional/FO/03_userAccount/01_editInformation.js
  tests/UI/pages/FO/myAccount/identity.js
Labels: TE, 8.0.x, Refactoring, E2E Tests

#29306 Fix specific price creation for dedicated customer
  src/PrestaShopBundle/Form/Admin/Sell/Customer/SearchedCustomerType.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/SpecificPrice/FormTheme/specific_price.html.twig
Labels: QA ✔️, 8.0.x, Bug fix

#29319 Upgrade symfony version
  composer.lock
Labels: Improvement, 8.0.x

#29307 Remove module_card.js from the product page v1
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/product.html.twig
Labels: QA ✔️, Bug fix, 1.7.8.x

#29325 Fix exception message while removing configuration
  src/Adapter/Configuration.php
Labels: Improvement, develop

#28872 [BO] : Class name must be allowed from controller in select render list column
  admin-dev/themes/default/template/helpers/list/list_header.tpl
Labels: Improvement, QA ✔️, develop

#29288 Restructurize horizontal migration Bridge directories
  src/PrestaShopBundle/Bridge/AdminController/Action/AbstractAction.php
  src/PrestaShopBundle/Bridge/AdminController/ControllerConfiguration.php
  src/PrestaShopBundle/Bridge/AdminController/FrameworkBridgeControllerListTrait.php
  src/PrestaShopBundle/Bridge/Helper/ListCustomizer/FeatureHelperListBridge.php
  src/PrestaShopBundle/Bridge/Helper/Listing/Action/ListBulkAction.php
  src/PrestaShopBundle/Bridge/Helper/Listing/Action/ListHeaderToolbarAction.php
  src/PrestaShopBundle/Bridge/Helper/Listing/Action/ListRowAction.php
  src/PrestaShopBundle/Bridge/Helper/Listing/Field/Field.php
  src/PrestaShopBundle/Bridge/Helper/Listing/Field/FieldInterface.php
  src/PrestaShopBundle/Bridge/Helper/Listing/FilterPrefix.php
  src/PrestaShopBundle/Bridge/Helper/Listing/FiltersProcessor.php
  src/PrestaShopBundle/Bridge/Helper/Listing/HelperBridge/FeatureHelperListBridge.php
  src/PrestaShopBundle/Bridge/Helper/Listing/HelperBridge/HelperListBridge.php
  src/PrestaShopBundle/Bridge/Helper/Listing/HelperListConfiguration.php
  src/PrestaShopBundle/Bridge/Helper/Listing/HelperListConfigurationFactory.php
  src/PrestaShopBundle/Bridge/Helper/Listing/HelperListConfigurator.php
  src/PrestaShopBundle/Bridge/Helper/ResetFiltersHelper.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureController.php
  src/PrestaShopBundle/Resources/config/services/bundle/bridge.yml
  src/PrestaShopBundle/Resources/config/services/bundle/bridge/_admin_controller.yml
  src/PrestaShopBundle/Resources/config/services/bundle/bridge/_helper.yml
  src/PrestaShopBundle/Resources/config/services/bundle/bridge/_list.yml
  src/PrestaShopBundle/Resources/config/services/bundle/bridge/helper/_list_customizer.yml
Labels: 8.0.x, Refactoring

#29367 Update the theme argument description
  src/PrestaShopBundle/Command/ThemeEnablerCommand.php
Labels: Improvement, develop

#28906 Functional tests - Fix CRUD address test on FO
  tests/UI/campaigns/functional/FO/03_userAccount/02_CRUDAddress.js
  tests/UI/pages/FO/FObasePage.js
  tests/UI/pages/FO/checkout/index.js
  tests/UI/pages/FO/myAccount/addresses.js
  tests/UI/pages/FO/myAccount/index.js
Labels: TE, 8.0.x, Refactoring, E2E Tests

#29274 Update guzzle and smarty dependencies
  composer.lock
Labels: Improvement, QA ✔️, 8.0.x, Needs documentation

#29403 Add index.php into directory
  classes/product/index.php
Labels: Improvement, develop

#29387 Sanity tests - Add new test 'Filter products table' V2
  tests/UI/campaigns/productV2/sanity/01_filterProducts.js
  tests/UI/commonTests/BO/advancedParameters/newFeatures.js
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/advancedParameters/featureFlag/index.js
  tests/UI/pages/BO/catalog/productsV2/index.js
Labels: TE, 8.0.x, Refactoring, E2E Tests

#29363 Fix typo in module controller messages
  src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php
Labels: develop, Bug fix

#29356 Fix nightly develop 16/08/2022 after a new behaviour on view order page
  tests/UI/campaigns/functional/BO/02_orders/01_orders/11_previewOrder.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/02_productBlock.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/12_checkMultiInvoice.js
  tests/UI/campaigns/functional/BO/11_international/01_localization/03_currencies/01_createOfficialCurrency.js
  tests/UI/campaigns/functional/BO/11_international/01_localization/03_currencies/02_createUnofficialCurrency.js
  tests/UI/pages/FO/FObasePage.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#29419 Ignore `.htpasswd` file
  .gitignore
Labels: Improvement, develop

#29430 Sanity tests - Add new test 'CRUD standard product' V2
  tests/UI/campaigns/productV2/sanity/02_CRUDStandardProduct.js
  tests/UI/data/faker/product.js
  tests/UI/pages/BO/catalog/productsV2/add.js
  tests/UI/pages/BO/catalog/productsV2/index.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#29373 Fix checkout when one module and no cgv validation
  themes/_core/js/checkout-payment.js
Labels: QA ✔️, Bug fix, 1.7.8.x

#29388 Fix customer voucher "active" column in customer view page
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/status.html.twig
Labels: QA ✔️, 8.0.x, Bug fix

#29416 Fix customer form validation from module
  classes/form/CustomerForm.php
Labels: QA ✔️, 8.0.x, Bug fix

#28794 Deprecate AdminPdf calls and use Sf routes
  controllers/admin/AdminPdfController.php
  controllers/admin/AdminSearchController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/documents.html.twig
Labels: QA ✔️, develop, Refactoring, Deprecations

#29452 Functional tests - Fix 'FO > User account> Edit information' test
  tests/UI/campaigns/functional/FO/03_userAccount/01_editInformation.js
  tests/UI/pages/FO/myAccount/identity.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#29443 Functional tests - Fix errors on nightly 8.0.x
  tests/UI/campaigns/functional/FO/03_userAccount/02_CRUDAddress.js
  tests/UI/pages/BO/orders/add.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#29442 Merge 1.7.8.x into 8.0.x
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
  config/smartyfront.config.inc.php
  src/Core/Translation/Builder/TranslationCatalogueBuilder.php
  src/Core/Translation/Storage/Provider/CatalogueProviderFactory.php
  src/Core/Translation/Storage/Provider/Definition/ModulesProviderDefinition.php
  src/Core/Translation/Storage/Provider/ModuleCatalogueProviderFactory.php
  src/Core/Translation/Storage/Provider/ThemeCatalogueLayersProvider.php
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/product.html.twig
  src/PrestaShopBundle/Service/TranslationService.php
  src/PrestaShopBundle/Translation/Loader/DatabaseTranslationLoader.php
  src/PrestaShopBundle/Translation/Loader/SqlTranslationLoader.php
  src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php
  tests/Integration/Core/Translation/Storage/Provider/ThemeCatalogueLayersProviderTest.php
  tests/Unit/Core/Translation/Builder/TranslationTreeBuilderTest.php
Labels: Improvement, QA ✔️, develop, 8.0.x, Bug fix
