Repository PrestaShop/PrestaShop, pull requests merged in 2022-10, with the labels that each got.

#29841 Add info about fixing multiple issues into template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improvement, develop

#29844 Functional Tests : Fixed errors from the script `check:step-identifiers`
  tests/UI/commonTests/BO/advancedParameters/setPermissions.js
  tests/UI/tools/stepIdentifiersChecker.js
Labels: QA ✔️, TE, 8.0.x, Bug fix, E2E Tests

#29835 Functional tests - Add new test 'FO > Check slider'
  tests/UI/campaigns/functional/FO/06_homePage/01_checkSlider.js
  tests/UI/pages/FO/home/index.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#29864 Fix nightly 04/10/2022 - Fix 'BO > Header > My profile' test
  tests/UI/campaigns/functional/BO/15_header/07_myProfile.js
  tests/UI/pages/BO/advancedParameters/team/myProfile.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#29831 Convert 1.7.9 to 8.0.0 in deprecation message
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
Labels: Improvement, 8.0.x

#29896 Functional tests - Add new test 'FO > Marchandise returns > check order return PDF'
  tests/UI/campaigns/functional/FO/03_userAccount/merchandiseReturns/02_checkOrderReturnPDF.js
  tests/UI/pages/FO/myAccount/merchandiseReturns.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#29899 Functional tests - Fix 'FO > Contact US > Add attachment' test
  tests/UI/campaigns/functional/FO/05_contactUs/04_addAttachment.js
  tests/UI/pages/BO/customerService/customerService/view.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#29731 Fix a problem with invalid filtering on the Modules -> Positions page
  admin-dev/themes/new-theme/js/pages/improve/design_positions/positions-list-handler.ts
  src/PrestaShopBundle/Controller/Admin/Improve/Design/PositionsController.php
Labels: QA ✔️, develop, Bug fix

#29861 Fix subtitle default position on module configure page
  admin-dev/themes/default/scss/partials/_toolbar.scss
Labels: QA ✔️, develop, Bug fix

#29912 Delete run on label 'TE' for UI code checks
  .github/workflows/ui_tests_code_checks.yml
Labels: QA ✔️, TE, 8.0.x, Bug fix, E2E Tests

#29898 Functional Tests : BO - Orders - Shopping carts - View carts
  admin-dev/themes/default/template/controllers/carts/helpers/view/view.tpl
  controllers/admin/AdminCartsController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Cart/Blocks/View/order_information.html.twig
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/03_createSimpleOrderInBO.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/04_selectPreviousCarts.js
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/03_viewCarts.js
  tests/UI/commonTests/FO/createShoppingCart.js
  tests/UI/data/demo/paymentMethods.js
  tests/UI/pages/BO/orders/shoppingCarts/index.js
  tests/UI/pages/BO/orders/shoppingCarts/view.js
  tests/UI/pages/FO/checkout/index.js
Labels: Improvement, QA ✔️, TE, 8.0.x, E2E Tests

#29847 Fix product page v1 footer responsive
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Blocks/footer.html.twig
Labels: QA ✔️, 8.0.x, Bug fix

#29791 Fix form layout in Advanced Parameters > Security > Password policy
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Security/index.html.twig
Labels: QA ✔️, 8.0.x, Bug fix

#29926 Remove permissions from workflow
  .github/workflows/ui_tests_code_checks.yml
Labels: develop, Refactoring

#29740 Remove not needed help text when you add new tax rule
  controllers/admin/AdminTaxRulesGroupController.php
Labels: QA ✔️, develop, Bug fix, Wording ✔️

#29490 Notice in Back Office where you edit image settings
  controllers/admin/AdminImagesController.php
Labels: Improvement, QA ✔️, develop, Wording ✔️

#29047 Fix ordering by product name + add ordering by product id (movements page)
  admin-dev/themes/new-theme/js/app/pages/stock/components/movements/index.vue
  admin-dev/themes/new-theme/js/app/pages/stock/components/movements/movement-line.vue
  src/PrestaShopBundle/Api/QueryStockMovementParamsCollection.php
Labels: QA ✔️, 8.0.x, Bug fix

#29910 Fix image size when zooming on tablet
  themes/classic/_dev/css/components/products.scss
  themes/classic/templates/catalog/_partials/product-images-modal.tpl
Labels: QA ✔️, Bug fix, 1.7.8.x

#29235 Update prestashop 1.7.8.x composer dependencies
  composer.lock
Labels: Improvement, QA ✔️, 1.7.8.x

#29954 Functional Tests : BO - View my shop
  tests/UI/campaigns/functional/BO/15_header/05_viewMyShop.js
  tests/UI/utils/helpers.js
Labels: Improvement, QA ✔️, TE, 8.0.x, E2E Tests

#29805 Functional tests - Add new test 'BO > Catalog > Cart rules carrier restriction'
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/11_carrierRestriction.js
  tests/UI/data/faker/cartRule.js
  tests/UI/pages/BO/catalog/discounts/add.js
  tests/UI/pages/FO/cart/index.js
  tests/UI/pages/FO/checkout/index.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#29928 Refacto tests - Delete 'Data>FO' & fix nightly
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/01_withAndWithoutCode.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/09_checkTotalAvailable.js
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/01_catalogMode.js
  tests/UI/campaigns/functional/FO/03_userAccount/08_orderHistory/02_reorderFromOrderList.js
  tests/UI/campaigns/functional/FO/03_userAccount/08_orderHistory/04_orderDetails/02_reorderFromOrderDetail.js
  tests/UI/campaigns/functional/FO/03_userAccount/merchandiseReturns/01_consultReturnDetails.js
  tests/UI/campaigns/functional/FO/03_userAccount/merchandiseReturns/02_checkOrderReturnPDF.js
  tests/UI/campaigns/functional/FO/09_productPage/01_quickView.js
  tests/UI/campaigns/functional/FO/12_orderConfirmation/05_contactUs.js
  tests/UI/campaigns/sanity/04_catalogFO/02_checkProduct.js
  tests/UI/campaigns/sanity/05_cartFO/01_editCheckCart.js
  tests/UI/campaigns/sanity/06_checkoutFO/01_orderProduct.js
  tests/UI/data/FO/cart.js
  tests/UI/data/FO/product.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#29956 Functional tests - Fix nightly 10/10/2022
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/03_createSimpleOrderInBO.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/04_selectPreviousCarts.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/05_selectPreviousOrders.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/08_chooseAddress.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/09_chooseShipping.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/10_checkSummary.js
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/03_viewCarts.js
  tests/UI/pages/BO/catalog/stocks/movements/index.js
  tests/UI/pages/BO/orders/add.js
  tests/UI/pages/BO/orders/shoppingCarts/view.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#29781 Add possibility for modules to return custom order number
  classes/order/Order.php
  install-dev/data/xml/hook.xml
Labels: Improvement, QA ✔️, develop

#29953 Deprecate Customer::validateController
  classes/Customer.php
Labels: Improvement, develop, Deprecations, Needs documentation

#29934 Center icon into sidebar
  admin-dev/themes/new-theme/scss/components/layout/_nav_bar.scss
Labels: Improvement, QA ✔️, develop

#29907 Functional Tests : Add dependabot for UI Tests
  .github/dependabot.yml
Labels: Improvement, QA ✔️, develop, E2E Tests

#29645 Fix typo into phpDoc
  src/Adapter/Meta/UrlSchemaDataConfiguration.php
Labels: Improvement, develop

#28465 Simplify Employee Form
  src/Core/Domain/Employee/ValueObject/Password.php
  src/Core/Form/IdentifiableObject/DataProvider/EmployeeFormDataProvider.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Employee/EmployeeType.php
  src/PrestaShopBundle/Form/Admin/Type/ChangePasswordType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Employee/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Employee/create.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Employee/edit.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/material.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: QA ✔️, develop, Refactoring, migration, Wording ✔️

#29801 Fix group when converting customer through front office form
  classes/form/CustomerPersister.php
Labels: QA ✔️, develop, Bug fix

#29958 Add comments to hook class
  classes/Hook.php
Labels: develop, Refactoring

#29942 Fix alert spacing inside modal content of product page v2
  admin-dev/themes/new-theme/scss/components/layout/_light_display.scss
Labels: QA ✔️, 8.0.x, Bug fix

#29976 Functional Tests : Fixes Dependabot (Remove assignees team / Fixes reviewers team)
  .github/dependabot.yml
  .github/workflows/behaviour.yml
  .github/workflows/integration.yml
  .github/workflows/php.yml
  .github/workflows/sanity-productV2.yml
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#29860 Functional tests - Add new test 'FO > Quick view product'
  tests/UI/campaigns/functional/FO/06_homePage/04_productQuickView.js
  tests/UI/campaigns/functional/FO/09_productPage/01_quickView.js
  tests/UI/data/demo/products.js
  tests/UI/pages/FO/category/index.js
  tests/UI/pages/FO/home/index.js
  tests/UI/pages/FO/searchResults/index.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#29909 Fix join on product lang to retrieve correctly the product's name
  src/PrestaShopBundle/Entity/Repository/StockRepository.php
Labels: QA ✔️, develop, Bug fix

#29515 Fix tag relation with product in Tag form
  classes/Tag.php
  src/Adapter/Product/Update/ProductTagUpdater.php
Labels: QA ✔️, develop, Bug fix

#29960 Functional Tests : BO - Search bar
  admin-dev/themes/default/template/controllers/search/helpers/view/view.tpl
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/11_carrierRestriction.js
  tests/UI/campaigns/functional/BO/15_header/03_searchBar.js
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/searchResults/index.js
Labels: Improvement, QA ✔️, TE, 8.0.x, E2E Tests

#29822 Fix accessing disabled product, further refacto of controller
  controllers/front/ProductController.php
Labels: QA ✔️, develop, Bug fix, Refactoring, Wording ✔️

#29803 Changelog for 8.0 RC 1
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: Improvement, 8.0.x

#29554 Replace exception message by custom message on invalid avatar on employee page
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php
Labels: QA ✔️, Bug fix, Wording ✔️, 1.7.8.x

#29587 Replace exception message by custom error message when uploading avatar with invalid extension
  classes/ImageManager.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ProfileController.php
Labels: QA ✔️, Bug fix, 1.7.8.x

#29619 Remove inifinite loop on actionObjectUpdateAfter hook
  classes/Cookie.php
Labels: QA ✔️, 8.0.x, Bug fix

#30039 Removed `faker.company.companyName()` deprecated since faker v7.4
  tests/UI/data/faker/address.js
  tests/UI/data/faker/brand.js
  tests/UI/data/faker/carrier.js
  tests/UI/data/faker/customer.js
  tests/UI/data/faker/store.js
  tests/UI/data/faker/supplier.js
  tests/UI/data/import/addresses.js
  tests/UI/data/import/brands.js
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#30037 Functional tests - Fix 'BO > Orders > Preview order' test
  tests/UI/campaigns/functional/BO/02_orders/01_orders/11_previewOrder.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#29785 Functional Tests : FO - Consult credit slip list & View PDF Credit slip & View order
  composer.lock
  tests/UI/campaigns/functional/FO/03_userAccount/01_creditSlips/01_consultCreditSlip.js
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/01_reorderFromOrderDetail.js
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/04_sendMessage.js
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderList.js
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/02_reorderFromOrderList.js
  tests/UI/pages/BO/orders/view/tabListBlock.js
  tests/UI/pages/FO/myAccount/creditSlips.js
  tests/UI/pages/FO/myAccount/index.js
Labels: Improvement, QA ✔️, TE, 8.0.x, E2E Tests

#30033 Fix cron modules update Github action
  .github/workflows/cron_php_update_modules.yml
Labels: develop, Bug fix

#29957 Add comments to customer class
  classes/Customer.php
Labels: develop, Refactoring

#29938 Fix issue 29937 - Array to string conversion in information of cli installation command
  install-dev/classes/controllerConsole.php
Labels: QA ✔️, develop, Bug fix

#29821 Fix category access when group feature is disabled
  classes/Category.php
  classes/Product.php
Labels: QA ✔️, develop, Bug fix

#30048 Fix linkchecker script for UI tests
  tests/UI/.gitignore
  tests/UI/tools/linkchecker.js
  tests/UI/tools/urls.js
Labels: QA ✔️, TE, 8.0.x, Bug fix, E2E Tests

#29574 Remove product image dropzone flex that was adding space
  admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue
Labels: Improvement, QA ✔️, 8.0.x, migration

#29615 Fixed installation screen when some config keys were missing
  src/Core/Theme/ConfigReader.php
  tests/Unit/Core/Theme/ConfigReaderTest.php
  themes/preview-fallback.png
Labels: QA ✔️, 8.0.x, Bug fix

#29707 Add template country global vars
  classes/controller/FrontController.php
Labels: Improvement, QA ✔️, develop

#29846 Fix 29341 - Rate impact calculation
  admin-dev/themes/new-theme/js/pages/product/combination/bulk.ts
  admin-dev/themes/new-theme/js/pages/product/combination/form/combination-form-mapping.ts
  src/Adapter/LegacyContext.php
  src/Adapter/Product/Repository/ProductRepository.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/BulkCombinationPriceType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/BulkCombinationType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
Labels: QA ✔️, 8.0.x, BO, Bug fix

#28537 Fix bug with all shops context in WebService
  classes/shop/Shop.php
  webservice/dispatcher.php
Labels: QA ✔️, develop, Bug fix

#30069 Fix phpstan error "Right side of && is always true"
  phpstan.neon.dist
Labels: QA ✔️, develop, Refactoring

#29859 Fix update status button responsive on order page
  admin-dev/themes/new-theme/scss/pages/orders/_orders_view.scss
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/history.html.twig
Labels: QA ✔️, 8.0.x, Bug fix, Wording ✔️

#30005 Update Classic to v2.0.5
  composer.lock
Labels: Improvement, QA ✔️, 8.0.x

#30049 Functional Tests : BO - Cart rules - Case 10 - Country Restriction
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/10_countryRestriction.js
  tests/UI/commonTests/BO/international/removeCountryQuickAccess.js
  tests/UI/data/demo/countries.js
  tests/UI/pages/BO/catalog/discounts/add.js
  tests/UI/pages/FO/cart/index.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#30064 Cherry pick fix from #29619
  classes/Cookie.php
Labels: 8.0.x, Bug fix

#28917 Display an error message if editing by zero on quantity field
  admin-dev/themes/new-theme/js/app/pages/stock/components/overview/products-actions.vue
  admin-dev/themes/new-theme/js/app/pages/stock/components/overview/spinner.vue
  admin-dev/themes/new-theme/js/app/pages/stock/store/actions.ts
  admin-dev/themes/new-theme/js/app/pages/stock/store/mutations.ts
  src/PrestaShopBundle/Controller/Api/StockController.php
  tests/Integration/PrestaShopBundle/Controller/Api/StockManagementControllerTest.php
Labels: QA ✔️, develop, Bug fix, Wording ✔️

#29996 Fix saving status code 410 on the product page v1
  src/PrestaShopBundle/Model/Product/AdminModelAdapter.php
Labels: QA ✔️, 8.0.x, Bug fix

#30080 Do not force new translation system when no domain is provided
  config/smartyfront.config.inc.php
Labels: QA ✔️, 8.0.x, Bug fix

#29079 Change default assignation of Product::pack_stock_type
  classes/Product.php
Labels: QA ✔️, 8.0.x, Bug fix

#29304 Add support for other file extensions in rewrite rules
  classes/Tools.php
  tests/Unit/Classes/ToolsTest.php
Labels: Improvement, QA ✔️, develop

#29470 Don't register `module` on `hook` if already registered
  classes/Hook.php
Labels: Improvement, QA ✔️, develop

#30068 Functional tests - Fix nightly 19/10 (Fix FO > send message test)
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/04_sendMessage.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#29992 Better escape PR description for the Pull Request Validator Github action
  .github/workflows/pr.yml
Labels: QA ✔️, 8.0.x, Bug fix

#30104 Dynamic import for zxcvbn library
  .gitignore
  classes/controller/FrontController.php
  themes/_core/js/common.js
  themes/_core/js/theme.js
  themes/webpack.config.js
Labels: Improvement, QA ✔️

#29104 Fix missing id_guest in cookie
  classes/Context.php
  classes/controller/FrontController.php
Labels: QA ✔️, develop, 8.0.x, Bug fix

#30047 Remove unused "override" property in class index
  classes/PrestaShopAutoload.php
  tests/Integration/Classes/PrestaShopAutoloadTest.php
Labels: Improvement, QA ✔️, develop

#29783 Migrate node-sass to sass-embedded on default theme
  admin-dev/themes/default/package-lock.json
  admin-dev/themes/default/package.json
Labels: Improvement, QA ✔️, 8.0.x, 1.7.8.x

#30116 Update twig dependency
  composer.lock
Labels: QA ✔️, 8.0.x, Bug fix, Needs documentation

#30107 Add missing trans method instead of hard-coded wording
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/SpecificPriceImpactType.php
  translations/default/AdminActions.xlf
  translations/default/AdminCatalogFeature.xlf
  translations/default/AdminCatalogNotification.xlf
  translations/default/AdminModulesNotification.xlf
  translations/default/ShopThemeCatalog.xlf
Labels: QA ✔️, 8.0.x, Bug fix, Wording ✔️

#29372 Hide suppliers if there are no suppliers on product v2
  src/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/ProductTypeListener.php
  tests/Integration/PrestaShopBundle/Form/EventListener/ProductTypeListenerTest.php
  tests/Integration/PrestaShopBundle/Form/TestProductFormType.php
Labels: QA ✔️, 8.0.x, Bug fix

#30110 Merge 8.0.0-rc branch into 8.0.x
  CONTRIBUTORS.md
  composer.lock
  docs/CHANGELOG.txt
  src/PrestaShopBundle/Model/Product/AdminModelAdapter.php
Labels: Improvement, 8.0.x

#29765 Changed message when PHP version is not correct
  install-dev/index_cli.php
  install-dev/missing_requirement.php
Labels: QA ✔️, develop, Feature

#29891 [Merge] Merge 1.7.8.x to 8.0.x
  admin-dev/themes/new-theme/scss/components/_alert.scss
  controllers/admin/AdminShopController.php
  controllers/front/OrderController.php
  src/PrestaShopBundle/Utils/Tree.php
  tests/Unit/PrestaShopBundle/Utils/TreeTest.php
Labels: Improvement, QA ✔️, develop

#29888 [Merge] Merge 8.0.x to develop
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  tests/UI/campaigns/functional/BO/00_login/02_login.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/03_statusTab.js
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/employees/02_CRUDEmployee.js
  tests/UI/campaigns/functional/BO/15_header/07_myProfile.js
  tests/UI/campaigns/functional/FO/06_homePage/01_checkSlider.js
  tests/UI/commonTests/BO/loginBO.js
  tests/UI/pages/BO/advancedParameters/team/myProfile.js
  tests/UI/pages/BO/login/index.js
  tests/UI/pages/FO/home/index.js
Labels: Improvement, QA ✔️, develop

#29636 Upgrade Smarty to 3.1.47
  composer.lock
Labels: Improvement, QA ✔️, 1.7.8.x

#30115 Changelog v8.0.0
  docs/CHANGELOG.txt
Labels: Improvement, 8.0.x

#30127 Functional tests - Fix errors in nightly develop
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/11_checkInvoice.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/12_checkMultiInvoice.js
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/01_viewCustomerService.js
  tests/UI/pages/BO/customerService/customerService/view.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#29382 Do not authorize PHP direct call on themes directory
  themes/.htaccess
Labels: Improvement, QA ✔️, develop

#28500 Add a lock file during the install (and it's removed only if the install is well finished)
  .github/workflows/phpstan/autoload.php
  controllers/admin/AdminLoginController.php
  install-dev/controllers/console/process.php
  install-dev/controllers/http/process.php
  install-dev/init.php
  src/PrestaShopBundle/Install/Install.php
Labels: Improvement, QA ✔️, develop

#30133 Use array short tag in translations files
  controllers/admin/AdminTranslationsController.php
Labels: Improvement, QA ✔️, develop

#29750 Replace AppKernel version constants by prestashop versions
  app/AppKernel.php
  app/config/config.yml
  config/autoload.php
  src/Adapter/Admin/PagePreference.php
  src/Adapter/Hook/HookDispatcher.php
  src/Adapter/Product/AdminProductDataProvider.php
  src/Adapter/Requirement/CheckMissingOrUpdatedFiles.php
  src/Adapter/Shop/ShopInformation.php
  src/Core/Version.php
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Resources/config/services/core/foundation.yml
  tests/Resources/DatabaseDump.php
  tests/Unit/PrestaShopBundle/AppKernelTest.php
Labels: Improvement, QA ✔️, develop, Needs documentation

#29664 Removed `US/Pacific New` from timezone list
  install-dev/data/xml/timezone.xml
Labels: QA ✔️, develop, Bug fix

#29423 Prevent *.twig, config.xml & config_{lang}.xml files from direct access in modules folder
  modules/.htaccess
Labels: Improvement, QA ✔️, develop

#29756 Fix error on patch method because of php 8.0 throw a fatal error
  classes/Currency.php
  classes/webservice/WebserviceRequest.php
Labels: QA ✔️, 8.0.x, Bug fix

#30129 Final merge 8.0.0-rc branch into 8.0.x
  .gitignore
  classes/controller/FrontController.php
  composer.lock
  config/smartyfront.config.inc.php
  docs/CHANGELOG.txt
  themes/_core/js/common.js
  themes/_core/js/theme.js
  themes/webpack.config.js
Labels: Improvement, QA ✔️, 8.0.x

#30052 Added required attribute on text input for admin controller
  admin-dev/themes/default/template/helpers/options/options.tpl
Labels: QA ✔️

#29084 27054: fixed taxes for wrong countries
  admin-dev/themes/new-theme/js/pages/product/edit/product-form-model.ts
  admin-dev/themes/new-theme/js/pages/product/product-map.ts
  classes/tax/TaxCalculator.php
  src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php
  src/Adapter/Tax/TaxComputer.php
  src/Adapter/TaxRulesGroup/Repository/TaxRulesGroupRepository.php
  src/Core/Form/IdentifiableObject/OptionProvider/ProductFormOptionsProvider.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/EditProductFormType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/PricingType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php
  src/PrestaShopBundle/Resources/config/services/core/form/choice_provider.yml
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
  tests/Integration/Adapter/Tax/TaxComputerTest.php
  tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Configuration/CommonConfigurationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/TaxFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_multishop_prices.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_prices.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_prices_ecotax.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_prices_without_states.feature
  tests/Integration/Behaviour/behat.yml
  tests/Integration/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminControllerTest.php
  tests/Unit/Adapter/Tax/TaxComputerTest.php
Labels: QA ✔️, 8.0.x, Bug fix

#29715 Fix discount detail in cart when a product has en ecotax with applied tax
  classes/CartRule.php
  classes/Product.php
  tests/Integration/Behaviour/Features/Context/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Context/TaxFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/ecotax.feature
Labels: QA ✔️, Bug fix, 1.7.8.x

#29135 Webservice: honor maximum image upload size
  classes/webservice/WebserviceSpecificManagementImages.php
Labels: QA ✔️, develop, Bug fix, BC break

#29977 Updating default combination is now take into account when submitting the form
  src/Core/Form/IdentifiableObject/DataFormatter/CombinationListFormDataFormatter.php
  tests/Unit/Core/Form/IdentifiableObject/DataFormatter/CombinationListFormDataFormatterTest.php
Labels: QA ✔️, develop, Bug fix, Wording ✔️

#30099 Fix issue on fresh installation with docker in branch 1.7.8.x
  .docker/Dockerfile
  docker-compose.yml
Labels: QA ✔️, Bug fix, 1.7.8.x

#29767 GitHub Workflows security hardening
  .github/workflows/behaviour.yml
  .github/workflows/cron_js_routing.yml
  .github/workflows/integration.yml
  .github/workflows/sanity.yml
Labels: Improvement, develop

#29993 Allow to use own value to submit button
  admin-dev/themes/default/template/helpers/form/form.tpl
Labels: Improvement, QA ✔️, develop

#30132 Upgrade AddProductImageCommand and GetProductImageCommand to fit with multishop
  src/Adapter/Product/Image/CommandHandler/AddProductImageHandler.php
  src/Adapter/Product/Image/QueryHandler/GetProductImageHandler.php
  src/Adapter/Product/Image/QueryHandler/GetProductImagesHandler.php
  src/Adapter/Product/Image/Repository/ProductImageRepository.php
  src/Adapter/Product/Repository/ProductMultiShopRepository.php
  src/Core/Domain/Product/Image/Command/AddProductImageCommand.php
  src/Core/Domain/Product/Image/QueryResult/ProductImage.php
  src/Core/Form/IdentifiableObject/DataHandler/ProductImageFormDataHandler.php
  src/PrestaShopBundle/Resources/config/services/adapter/product/_image.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/add_multishop_image.feature
  tests/Unit/Core/Form/ChoiceProvider/ProductImagesChoiceProviderTest.php
Labels: develop, Feature, BC break

#30082 Functional tests - Refacto (Rename combinations by attributes in all project)
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/02_productBlock.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/02_monitoringProducts.js
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/04_quantityDiscountsBasedOn.js
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/03_displayUnavailableProductAttributes.js
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/04_sendMessage.js
  tests/UI/campaigns/functional/FO/06_homePage/04_productQuickView.js
  tests/UI/campaigns/functional/FO/09_productPage/01_quickView.js
  tests/UI/campaigns/functional/FO/09_productPage/02_addToCart.js
  tests/UI/campaigns/productV2/sanity/03_CRUDProductWithCombinations.js
  tests/UI/campaigns/sanity/03_productsBO/03_CRUDStandardProductWithCombinationsInBO.js
  tests/UI/data/demo/products.js
  tests/UI/data/faker/product.js
  tests/UI/pages/BO/catalog/products/add.js
  tests/UI/pages/FO/home/index.js
  tests/UI/pages/FO/product/index.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#29872 Functional tests - Add new test 'BO > Catalog > Cart rules customer group restriction
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/12_groupCustomerRestriction.js
  tests/UI/data/faker/cartRule.js
  tests/UI/pages/BO/catalog/discounts/add.js
  tests/UI/pages/FO/cart/index.js
  tests/UI/pages/FO/checkout/index.js
Labels: QA ✔️, 8.0.x, Refactoring, E2E Tests

#30057 Remove Aria-label attribute to improve BO pagination selectors
  src/PrestaShopBundle/Resources/views/Admin/Common/pagination.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Common/pagination_quicknav.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Backup/Blocks/backup_form.html.twig
  tests/UI/pages/BO/advancedParameters/database/dbBackup/index.js
  tests/UI/pages/BO/advancedParameters/database/sqlManager/index.js
  tests/UI/pages/BO/advancedParameters/email/index.js
  tests/UI/pages/BO/advancedParameters/logs/index.js
  tests/UI/pages/BO/advancedParameters/team/index.js
  tests/UI/pages/BO/advancedParameters/team/profiles/index.js
  tests/UI/pages/BO/advancedParameters/webservice/index.js
  tests/UI/pages/BO/catalog/brands/index.js
  tests/UI/pages/BO/catalog/categories/index.js
  tests/UI/pages/BO/catalog/files/index.js
  tests/UI/pages/BO/catalog/monitoring/index.js
  tests/UI/pages/BO/catalog/products/index.js
  tests/UI/pages/BO/catalog/productsV2/index.js
  tests/UI/pages/BO/catalog/suppliers/index.js
  tests/UI/pages/BO/customerService/orderMessages/index.js
  tests/UI/pages/BO/customers/addresses/index.js
  tests/UI/pages/BO/customers/index.js
  tests/UI/pages/BO/customers/outstanding/index.js
  tests/UI/pages/BO/design/pages/index.js
  tests/UI/pages/BO/international/currencies/index.js
  tests/UI/pages/BO/international/languages/index.js
  tests/UI/pages/BO/international/locations/index.js
  tests/UI/pages/BO/international/taxes/index.js
  tests/UI/pages/BO/orders/index.js
  tests/UI/pages/BO/shopParameters/trafficAndSeo/searchEngines/index.js
  tests/UI/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/index.js
Labels: Improvement, QA ✔️, TE, 8.0.x, E2E Tests

#30066 Functional tests - Refacto BO - Catalog - crud category
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/02_CRUDCategoryInBO.js
  tests/UI/pages/FO/category/index.js
  tests/UI/pages/FO/siteMap/index.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#30166 Functional tests - Fix 'Orders>View and edit order> Check invoice' test
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/11_checkInvoice.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#30135 Fix child theme download
  themes/.htaccess
Labels: QA ✔️, develop, Bug fix
