Repository PrestaShop/PrestaShop, pull requests merged in 2022-06, with the labels that each got.

#28554 UI tests - Fix step double identifer and remove doubles
  tests/UI/campaigns/functional/BO/02_orders/01_orders/05_bulkUpdateOrdersStatus.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/06_bulkOpenInNewTab.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/10_pagination.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/01_searchViewCustomer.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/05_selectPreviousOrders.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/06_addProductToTheCart.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/07_searchAddRemoveVoucher.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/08_chooseAddress.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/09_chooseShipping.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/10_checkSummary.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/01_customerBlock.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/02_productBlock.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/03_statusTab.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/04_documentsTab.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/05_carriersTab.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/06_merchandiseReturnsTab.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/07_messagesBlock.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/08_paymentBlock.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/09_addDiscount.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/10_changeStatus.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/11_checkInvoice.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/12_checkMultiInvoice.js
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/02_sortAndPagination.js
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/05_paginationAndSortCategories.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/02_withCombinationsWithoutQuantities.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/03_withoutCombinationsWithoutQuantities.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/04_disabledProducts.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/05_productsWithoutImage.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/06_productsWithoutDescription.js
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/07_productsWithoutPrice.js
  tests/UI/campaigns/functional/BO/04_customers/01_customers/04_paginationAndSortCustomers.js
  tests/UI/campaigns/functional/BO/04_customers/02_addresses/04_paginationAndSortAddresses.js
  tests/UI/campaigns/functional/BO/14_advancedParameters/04_email/01_filterDeleteAndBulkActionsEmails.js
  tests/UI/campaigns/functional/BO/14_advancedParameters/05_import/02_importFile.js
  tests/UI/tools/stepIdentifiersChecker.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#28619 Replace unit type with a form type extension
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Administration/GeneralType.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Administration/UploadQuotaType.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Employee/EmployeeOptionsType.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/CustomerPreferences/GeneralType.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/GeneralType.php
  src/PrestaShopBundle/Form/Admin/Extension/UnitTypeExtension.php
  src/PrestaShopBundle/Form/Admin/Improve/Shipping/Preferences/HandlingType.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/AddProductRowType.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/EditProductRowType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/BulkCombinationPriceType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationPriceImpactType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Shipping/DimensionsType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_extension.yml
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_horizontal_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: QA ✔️, develop, Refactoring, BC break

#28445 Allow clearing modules cache for all shops
  src/Core/Module/EventSubscriber.php
  src/Core/Module/ModuleRepository.php
Labels: QA ✔️, develop, Bug fix, BC break, Needs documentation

#28665 Fix nightly 02/06/2022 - Fix random error on 'Choose address' test
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/08_chooseAddress.js
  tests/UI/pages/BO/orders/add.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#28578 Remove deprecated in Core namespace
  src/Core/Domain/SpecificPrice/Exception/CannotAddSpecificPriceException.php
  src/Core/Email/SmtpDataConfigurator.php
  src/Core/Foundation/Version.php
  src/Core/Kpi/Row/HookableKpiRowFactory.php
  src/Core/Kpi/Row/KpiRowFactory.php
  src/PrestaShopBundle/Resources/config/services/adapter/data_configuration.yml
  tests/Unit/Core/Kpi/KpiRowFactoryTest.php
Labels: QA ✔️, develop, Refactoring, BC break, Needs documentation

#28356 Functional tests - Add new test "Design > Theme & Logo > Advanced customization page"
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Theme/Blocks/Partials/theme_card.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Theme/index.html.twig
  tests/UI/campaigns/functional/BO/08_design/01_themeAndLogo/03_advancedCustomization/01_advancedCustomization.js
  tests/UI/data/demo/modules.js
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/design/themeAndLogo/advancedCustomization/index.js
  tests/UI/pages/BO/design/themeAndLogo/themeAndLogo/index.js
  tests/UI/pages/BO/design/themeAndLogo/themeAndLogo/themeAndLogoBasePage.js
  tests/UI/utils/files.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#28682 Functional tests - Fix some random errors on nightly 178x
  tests/UI/pages/BO/advancedParameters/import/index.js
  tests/UI/pages/BO/shopParameters/general/maintenance/index.js
  tests/UI/pages/FO/myAccount/index.js
Labels: QA ✔️, TE, Refactoring, E2E Tests, 1.7.8.x

#28647 Update min & max php version of the installer
  tools/build/Library/InstallUnpacker/index_template.php
Labels: QA ✔️, develop, Bug fix

#28691 Functional tests - Add test to Import csv file to Brand pagination test
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/brands/02_sortPaginationAndBulkActions.js
  tests/UI/data/import/brands.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#28694 Functional tests - Fix customer faker password
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/employees/02_CRUDEmployee.js
  tests/UI/data/faker/customer.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#28624 Bump phpstan/phpstan from 1.5.4 to 1.7.4
  classes/Hook.php
  classes/Language.php
  classes/Pack.php
  classes/Product.php
  classes/order/OrderInvoice.php
  classes/order/OrderReturn.php
  classes/pdf/HTMLTemplateSupplyOrderForm.php
  composer.lock
  controllers/admin/AdminImportController.php
  controllers/admin/AdminProductsController.php
  controllers/admin/AdminTranslationsController.php
  phpstan.neon.dist
  src/Adapter/ContainerBuilder.php
  src/Adapter/Import/Handler/ProductImportHandler.php
  src/Adapter/Module/ModuleDataProvider.php
  src/Adapter/Presenter/AbstractLazyArray.php
  src/Adapter/Presenter/Cart/CartPresenter.php
  src/Adapter/Product/AdminProductDataProvider.php
  src/Core/Order/InvoiceInterface.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
Labels: Improvement, develop

#28641 Functional tests - Add new test 'Preview order'
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/preview.html.twig
  tests/UI/campaigns/functional/BO/02_orders/01_orders/11_previewOrder.js
  tests/UI/data/demo/products.js
  tests/UI/pages/BO/orders/index.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#28690 Fix YAML lint on GH workflow files
  .github/workflows/integration.yml
  .github/workflows/php.yml
Labels: develop, Bug fix

#28710 Update github template and CI configuration for the new 8.0.x branch
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/cron_js_routing.yml
  .github/workflows/cron_nightly_build.yml
  .github/workflows/cron_nightly_tests.yml
  .github/workflows/cron_php_update_modules.yml
  .github/workflows/cron_update_modules/script.php
  .github/workflows/js.yml
Labels: develop, Feature

#28724 Add new default password for docker image
  .docker/docker_run_git.sh
  .github/workflows/cron_nightly_tests.yml
  docker-compose.yml
Labels: QA ✔️, develop, Bug fix, CI/CD

#28725 Add new default password for docker image for 8.0.x
  .docker/docker_run_git.sh
  .github/workflows/cron_nightly_tests.yml
  .github/workflows/js.yml
  docker-compose.yml
Labels: QA ✔️, 8.0.x, Bug fix, CI/CD

#28592 Remove id from entity search input templates
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/FormTheme/product.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/SpecificPrice/FormTheme/specific_price.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/entity_search_input.html.twig
Labels: QA ✔️, develop, Bug fix, Refactoring, migration

#28232 Optimizing queries for checking address existence
  classes/Address.php
  classes/Cart.php
Labels: Improvement, QA ✔️, 1.7.8.x

#28481 Handle no themes issue at install
  install-dev/init.php
Labels: QA ✔️, develop, Bug fix, Wording ✔️

#27890 Add check if the gift wrapping is disabled
  mails/themes/classic/core/order_conf.html.twig
  mails/themes/modern/core/order_conf.html.twig
  src/Adapter/MailTemplate/MailTemplateTwigRenderer.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/OrderPreferences/GiftOptionsType.php
  src/PrestaShopBundle/Resources/config/services/adapter/mail_template.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  tests/Unit/Adapter/MailTemplate/MailTemplateTwigRendererTest.php
Labels: QA ✔️, develop, Bug fix, BC break, Wording ✔️, Needs documentation

#28482 Handle product ecotax in product v2 (for both standard and combination form)
  admin-dev/themes/new-theme/js/components/form/form-object-mapper.ts
  admin-dev/themes/new-theme/js/pages/product/combination/form/combination-event-map.ts
  admin-dev/themes/new-theme/js/pages/product/combination/form/combination-form-mapping.ts
  admin-dev/themes/new-theme/js/pages/product/combination/form/combination-form-model.ts
  admin-dev/themes/new-theme/js/pages/product/components/combination-list/combinations-list-renderer.ts
  admin-dev/themes/new-theme/js/pages/product/components/combination-modal/CombinationModal.vue
  admin-dev/themes/new-theme/js/pages/product/edit/price-summary.ts
  admin-dev/themes/new-theme/js/pages/product/edit/product-form-mapping.ts
  admin-dev/themes/new-theme/js/pages/product/edit/product-form-model.ts
  admin-dev/themes/new-theme/js/pages/product/edit/product-type-switcher.ts
  admin-dev/themes/new-theme/js/pages/product/product-event-map.ts
  admin-dev/themes/new-theme/scss/pages/product/product_page.scss
  classes/Product.php
  src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php
  src/Adapter/Product/Combination/QueryHandler/GetCombinationForEditingHandler.php
  src/Adapter/Product/CommandHandler/UpdateProductPricesHandler.php
  src/Adapter/Product/Grid/Data/Factory/ProductGridDataFactoryDecorator.php
  src/Adapter/Product/QueryHandler/GetProductForEditingHandler.php
  src/Adapter/Product/Update/ProductPricePropertiesFiller.php
  src/Adapter/Product/Update/ProductTypeUpdater.php
  src/Adapter/Tax/TaxComputer.php
  src/Core/Domain/Product/Combination/QueryResult/CombinationPrices.php
  src/Core/Domain/Product/QueryResult/ProductPricesInformation.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationPriceCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilder.php
  src/Core/Form/IdentifiableObject/DataProvider/CombinationFormDataProvider.php
  src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php
  src/Core/Grid/Definition/Factory/ProductGridDefinitionFactory.php
  src/Core/Grid/Presenter/GridPresenter.php
  src/Core/Grid/Query/ProductQueryBuilder.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationItemType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationPriceImpactType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/ProductTypeListener.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/HeaderType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_combination.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/header-details.html.twig
  tests/Integration/Behaviour/Features/Context/Configuration/AbstractConfigurationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Configuration/CommonConfigurationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Configuration/PackConfigurationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Configuration/RoundingModeConfigurationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Configuration/RoundingTypeConfigurationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/UpdateCombinationPricesFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePricesFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/TaxRulesGroupFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/update_combination_prices.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/update_combination_suppliers.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_multishop_prices.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_prices.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_prices_ecotax.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_product_type.feature
  tests/Integration/PrestaShopBundle/Controller/Sell/Catalog/ProductControllerTest.php
  tests/Integration/PrestaShopBundle/Form/EventListener/ProductTypeListenerTest.php
  tests/Integration/PrestaShopBundle/Form/TestProductFormType.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationPriceCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/CombinationFormDataProviderTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProviderTest.php
Labels: QA ✔️, Waiting for wording, develop, Feature, migration

#28743 Remove dependency to the missing news.yml
  config/services/admin/services_prod.yml
Labels: QA ✔️, develop, Bug fix

#28722 Cart with wrong id_shop_group when order is made in BO
  classes/Cart.php
Labels: QA ✔️, develop, Bug fix

#28741 Add node and npm versions for UI tests
  .github/workflows/ui-tests-code-checks.yml
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#28613 Fix inability to delete csv-converted files from import
  src/Core/Import/File/FileRemoval.php
Labels: QA ✔️, develop, Bug fix

#28756 Fix nightly 15-06-2022 : Fix check help side bar test of features page
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/features/04_helpCard.js
  tests/UI/pages/BO/catalog/features/index.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#28763 Fixed redirect after canceling the edition of an address from the customer detail page
  src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php
Labels: QA ✔️, develop, Bug fix

#28769 Functional test - Add new test to check login in FO
  tests/UI/campaigns/functional/FO/01_login/02_login.js
  tests/UI/pages/FO/login/index.js
Labels: TE, 8.0.x, Refactoring, E2E Tests

#28768 Functional tests - Fix 'Gift option' test
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/giftOptions/01_giftOptions.js
  tests/UI/pages/BO/orders/view/productsBlock.js
  tests/UI/pages/FO/checkout/index.js
  tests/UI/pages/FO/checkout/orderConfirmation.js
Labels: TE, 8.0.x, Refactoring, E2E Tests

#28683 Improve datepicker design in dashboard
  admin-dev/themes/default/scss/partials/_date-range-picker.scss
  admin-dev/themes/default/template/helpers/calendar/calendar.tpl
Labels: QA ✔️, develop, Bug fix

#28639 [FO]: Blank message from customer end must not be allow from order detail page
  controllers/front/OrderDetailController.php
Labels: QA ✔️, develop, Bug fix

#28718 Fix carriers with same names don't show in Shipping > Preferences
  controllers/admin/AdminCartRulesController.php
  src/Adapter/Carrier/CarrierDataProvider.php
  src/Core/Form/ChoiceProvider/CarrierByReferenceChoiceProvider.php
  src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php
Labels: QA ✔️, develop, Bug fix

#28788 Fix carrier Exeption with free shipping
  classes/Carrier.php
Labels: QA ✔️, Bug fix

#28699 Tax Rules Groups > Grid : Confirm Modal & Common Search
  src/Core/Grid/Definition/Factory/TaxRulesGroupGridDefinitionFactory.php
  src/Core/Grid/Query/AbstractDoctrineQueryBuilder.php
  src/Core/Grid/Query/TaxRulesGroupQueryBuilder.php
  src/Core/Search/Filters/TaxRulesGroupFilters.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/TaxRulesGroupController.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/tax_rules_groups.yml
  tests/Unit/Core/Grid/Query/TaxRulesGroupQueryBuilderTest.php
Labels: QA ✔️, develop, Refactoring

#28800 Functional tests - Add some fixes to 'FO > Password reminder' test
  tests/UI/campaigns/functional/FO/01_login/01_passwordReminder.js
  tests/UI/pages/FO/myAccount/index.js
  tests/UI/pages/FO/passwordReminder/index.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#28469 `Shop::getBaseURL` use secure mode by default
  classes/controller/AdminController.php
  classes/shop/Shop.php
Labels: Improvement, QA ✔️, develop, BC break, Needs documentation

#28817 Fix notices in email translation
  controllers/admin/AdminTranslationsController.php
Labels: QA ✔️, 8.0.x, Bug fix

#27841 [Multistore] - Product on category page display out of stock flag instead of availlable on order
  classes/ProductAssembler.php
  src/Core/Product/Search/ProductSearchContext.php
Labels: QA ✔️, Bug fix, 1.7.8.x

#28815 Functional tests - Add new test 'Create account on FO'
  tests/UI/campaigns/functional/FO/01_login/04_createAccount.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#28828 Functional tests - Add new test 'Edit personal information' in FO
  tests/UI/campaigns/functional/FO/03_userAccount/01_editInformation.js
  tests/UI/pages/FO/FObasePage.js
  tests/UI/pages/FO/myAccount/identity.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#28717 Functional tests - Add new test "Customers > Outstanding page" Help card - View order - View Invoice
  tests/UI/campaigns/functional/BO/04_customers/03_outstanding/01_helpCard.js
  tests/UI/campaigns/functional/BO/04_customers/03_outstanding/02_viewOrder.js
  tests/UI/campaigns/functional/BO/04_customers/03_outstanding/03_viewInvoice.js
  tests/UI/commonTests/BO/shopParameters/enableDisableB2B.js
  tests/UI/pages/BO/BObasePage.js
  tests/UI/pages/BO/customers/outstanding/index.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#28809 Functional tests - Add new test 'Logout from FO'
  tests/UI/campaigns/functional/FO/01_login/01_passwordReminder.js
  tests/UI/campaigns/functional/FO/01_login/03_logout.js
  tests/UI/pages/FO/myAccount/index.js
  tests/UI/pages/FO/passwordReminder/index.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#28884 Fix errors on nightly 8.0.x
  tests/UI/pages/FO/myAccount/index.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#28842 Remove Addons reference in the Carriers Listing
  admin-dev/themes/default/template/controllers/carriers/helpers/list/list_header.tpl
Labels: QA ✔️, develop, Bug fix

#28821 Handle fallback when currency has empty display names
  src/Core/Form/ChoiceProvider/CurrencyNameByIsoCodeChoiceProvider.php
  src/Core/Localization/CLDR/Currency.php
  tests/Unit/Core/Localization/CLDR/CurrencyTest.php
Labels: QA ✔️, Bug fix, 1.7.8.x

#28392 Fix back-office translations when multishop and multiple languages
  config/config.inc.php
Labels: QA ✔️, Bug fix, 1.7.8.x

#28902 Fix nightly develop 21-06-2022 - Update default carrier and check it in FO
  tests/UI/campaigns/functional/BO/09_shipping/02_preferences/02_carrierOptions/01_defaultCarrier.js
  tests/UI/pages/BO/shipping/preferences/index.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#28477 Adjust footer on V2 product page
  admin-dev/themes/new-theme/js/pages/product/edit/index.ts
  admin-dev/themes/new-theme/js/pages/product/edit/product-footer-manager.ts
  admin-dev/themes/new-theme/js/pages/product/edit/product-partial-updater.ts
  admin-dev/themes/new-theme/js/pages/product/product-map.ts
  admin-dev/themes/new-theme/scss/pages/product/product_page.scss
  src/Adapter/Shop/Url/ProductPreviewProvider.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductStatusCommandsBuilder.php
  src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php
  src/Core/Form/IdentifiableObject/OptionProvider/ProductFormOptionsProvider.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Category/CategoriesType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/BulkCombinationType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationFormType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationImagesChoiceType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationManagerType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationsType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Description/DescriptionType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/EditProductFormType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/FooterType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/HeaderType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Image/ImageDropzoneType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/SEO/RedirectOptionType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/SEO/SEOType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/QuantityType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/StockType.php
  src/PrestaShopBundle/Resources/config/services/adapter/shop.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/footer.html.twig
  tests/Integration/Adapter/Shop/Url/ProductPreviewProviderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductStatusCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProviderTest.php
  tests/Unit/Core/Form/IdentifiableObject/OptionsProvider/ProductFormOptionsProviderTest.php
Labels: QA ✔️, develop, Bug fix, migration, Wording ✔️

#28811 Add random to Validate Class and Test
  classes/Validate.php
  tests/Unit/Adapter/ValidateTest.php
Labels: QA ✔️, develop, Bug fix
