Repository PrestaShop/PrestaShop, pull requests merged in 2023-02, with the labels that each got.

#30891 Functional tests - Refacto 'Sort, pagination and bulk delete features test'
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/features/02_sortPaginationAndBulkDelete.ts
  tests/UI/commonTests/BO/catalog/features.ts
Labels: TE, develop, Refactoring, E2E Tests

#31063 Functional tests - Delete commented tests & fix failed tests
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/11_checkInvoice.ts
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/03_quickEditAndBulkActions.ts
  tests/UI/campaigns/functional/BO/11_international/03_taxes/02_taxRules/03_quickEditAndBulkActions.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/returnStatuses/01_CRUDOrderReturnStatus.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/returnStatuses/02_filterSortAndPagination.ts
  tests/UI/campaigns/functional/FO/03_userAccount/04_getGDPRDataInPDF.ts
  tests/UI/campaigns/functional/FO/03_userAccount/05_getGDPRDataInCSV.ts
  tests/UI/campaigns/productV2/functional/01_filterProducts.ts
  tests/UI/campaigns/productV2/functional/02_CRUDStandardProduct.ts
  tests/UI/campaigns/productV2/functional/03_CRUDProductWithCombinations.ts
  tests/UI/campaigns/productV2/functional/04_CRUDPackOfProducts.ts
  tests/UI/campaigns/productV2/functional/06_productBulkActions.ts
  tests/UI/campaigns/productV2/functional/07_duplicateProduct.ts
  tests/UI/pages/BO/catalog/productsV2/add/combinationsTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/packTab.ts
  tests/UI/pages/BO/catalog/productsV2/index.ts
  tests/UI/pages/BO/international/taxes/taxRules/index.ts
  tests/UI/pages/BO/shipping/carriers/index.ts
  tests/UI/pages/BO/shopParameters/orderSettings/statuses/index.ts
  tests/UI/utils/basicHelper.ts
  tests/UI/utils/files.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#31108 Functional Tests : Migration TS (`@pages\BO` : Part 5)
  tests/UI/campaigns/functional/BO/04_customers/01_customers/06_exportCustomers.ts
  tests/UI/campaigns/functional/FO/03_userAccount/05_getGDPRDataInCSV.ts
  tests/UI/campaigns/functional/FO/03_userAccount/merchandiseReturns/01_consultReturnDetails.ts
  tests/UI/campaigns/functional/FO/03_userAccount/merchandiseReturns/02_checkOrderReturnPDF.ts
  tests/UI/campaigns/functional/FO/05_contactUs/03_sendMessageAsAnonymous.ts
  tests/UI/commonTests/BO/customerService/merchandiseReturns.ts
  tests/UI/commonTests/BO/customers/address.ts
  tests/UI/commonTests/BO/customers/customer.ts
  tests/UI/pages/BO/catalog/suppliers/add.ts
  tests/UI/pages/BO/catalog/suppliers/index.ts
  tests/UI/pages/BO/catalog/suppliers/view.ts
  tests/UI/pages/BO/customerService/customerService/index.ts
  tests/UI/pages/BO/customerService/customerService/view.ts
  tests/UI/pages/BO/customerService/merchandiseReturns/edit.ts
  tests/UI/pages/BO/customerService/merchandiseReturns/index.ts
  tests/UI/pages/BO/customerService/orderMessages/add.ts
  tests/UI/pages/BO/customerService/orderMessages/index.ts
  tests/UI/pages/BO/customers/add.ts
  tests/UI/pages/BO/customers/addresses/add.ts
  tests/UI/pages/BO/customers/addresses/index.ts
  tests/UI/pages/BO/customers/index.ts
  tests/UI/pages/BO/customers/outstanding/index.ts
  tests/UI/pages/BO/customers/view.ts
  tests/UI/pages/FO/login/index.ts
Labels: Improvement, TE, develop, E2E Tests

#31096 Functional tests - Fix random error on 'BO> Orders > Create order > Choose shipping' test
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/09_chooseShipping.ts
  tests/UI/pages/BO/orders/add.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#31104 Improve customer view totals
  src/Adapter/Customer/QueryHandler/GetCustomerForViewingHandler.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/carts.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/orders.html.twig
Labels: Improvement, QA ✔️, develop

#31136 Handle route not found in new api
  admin-dev/index.php
  app/config/config.yml
  app/config/security_dev.yml
  src/PrestaShopBundle/Api/Api.php
  src/PrestaShopBundle/Resources/config/routing.yml
Labels: Improvement, QA ✔️, develop

#28550 Removed deprecated methods in Order class
  classes/order/Order.php
Labels: Improvement, develop, BC break, Needs documentation

#28532 Removed deprecated Form Types
  src/PrestaShopBundle/Form/Admin/Type/TextEmptyType.php
  src/PrestaShopBundle/Form/Admin/Type/TextareaEmptyType.php
Labels: Improvement, develop, BC break, Needs documentation

#28564 Remove deprecated in Adapter namespace
  src/Adapter/Address/AbstractManufacturerAddressHandler.php
  src/Adapter/ClassLang.php
  src/Adapter/CombinationDataProvider.php
  src/Adapter/Module/ModulePresenter.php
  src/Adapter/Module/TabModuleListProvider.php
  src/Adapter/Order/OrderPresenter.php
  src/Adapter/Order/OrderReturnPresenter.php
  src/Adapter/Shop/Context.php
  src/Adapter/SqlManager/SqlRequestFormDataValidator.php
  src/PrestaShopBundle/Controller/Admin/AttributeController.php
  src/PrestaShopBundle/Resources/config/services/adapter/module.yml
  src/PrestaShopBundle/Resources/config/services/adapter/sql_manager.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  tests/Integration/PrestaShopBundle/EventListener/MultishopCommandListenerTest.php
Labels: develop, Refactoring, BC break, Needs documentation

#28548 Removed deprecated methods & properties in Product class
  classes/Product.php
Labels: develop, Refactoring, BC break, Needs documentation

#31109 Change limit of filed value on ps_customized_data so that it can accepts more than 255 characters
  install-dev/data/db_structure.sql
Labels: QA ✔️, develop, Feature, Needs autoupgrade PR

#31167 Added 8.1.x in PULL_REQUEST template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improvement

#31142 Add feature flags for rest of migrated pages
  classes/lang/KeysReference/FeatureFlagLang.php
  install-dev/data/xml/feature_flag.xml
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/permission.yml
  src/PrestaShopBundle/Resources/config/routing/admin/configure/shop_parameters/order_states.yml
  src/PrestaShopBundle/Resources/config/routing/admin/configure/shop_parameters/title.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/country.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/state.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/tax_rules_groups.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/shipping/carriers.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/cart_rule.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/catalog_price_rule.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/features.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer_service/customer_threads.yml
Labels: Improvement, QA ✔️, 8.1.x

#31148 Change domain to fix translation issue
  src/PrestaShopBundle/Form/Admin/Product/ProductOptions.php
Labels: QA ✔️, 8.0.x, Bug fix

#31114 Fix translation page responsivity
  admin-dev/themes/new-theme/js/app/pages/translations/components/app.vue
  admin-dev/themes/new-theme/js/app/pages/translations/components/header/search.vue
  admin-dev/themes/new-theme/js/app/pages/translations/components/principal/index.vue
  admin-dev/themes/new-theme/js/app/pages/translations/components/principal/translation-input.vue
  admin-dev/themes/new-theme/js/app/pages/translations/components/sidebar/index.vue
Labels: QA ✔️, develop, Refactoring

#31174 Functional tests - Fix nightly 01-02-2023
  tests/UI/campaigns/functional/FO/03_userAccount/merchandiseReturns/01_consultReturnDetails.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/catalog/products/index.js
Labels: TE, Refactoring, E2E Tests, 8.1.x

#31178 Functional Tests : Fixed Import Tests
  js/admin/import.js
Labels: QA ✔️, TE, Bug fix, E2E Tests, 8.1.x

#31162 Merge 8.0.x into 8.1.x
  classes/Hook.php
  classes/Tools.php
  classes/controller/FrontController.php
  src/Core/Util/ColorBrightnessCalculator.php
  tests/Unit/Core/Util/ColorBrightnessCalculatorTest.php
Labels: Bug fix

#31165 Running nightly on branch 8.1.x
  .github/workflows/cron_nightly_build.yml
  .github/workflows/cron_nightly_tests.yml
Labels: Improvement, QA ✔️, develop, CI/CD

#31179 Functional Tests : Migration TS (`@pages\BO` : Part 6)
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/06_addProductToTheCart.ts
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/02_enableDisableTaxBreakdown.ts
  tests/UI/campaigns/functional/BO/03_catalog/01_products/01_filterAndQuickEditProducts.ts
  tests/UI/campaigns/functional/BO/03_catalog/01_products/02_paginationAndSortProducts.ts
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/02_CRUDCategoryInBO.ts
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/04_changeCategoryPosition.ts
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/02_changePosition.ts
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/features/03_changePosition.ts
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/01_CRUDBrandAndAddress.ts
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/addresses/02_sortPaginationAndBulkActions.ts
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/brands/02_sortPaginationAndBulkActions.ts
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/02_catalogPriceRules/01_CRUDCatalogPriceRule.ts
  tests/UI/campaigns/functional/BO/03_catalog/08_stocks/02_updateQuantity.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/employees/02_CRUDEmployee.ts
  tests/UI/campaigns/functional/BO/15_header/02_quickAccess.ts
  tests/UI/campaigns/functional/BO/15_header/07_myProfile.ts
  tests/UI/campaigns/productV2/functional/03_CRUDProductWithCombinations.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/catalog/attributes/addAttribute.ts
  tests/UI/pages/BO/catalog/attributes/addValue.ts
  tests/UI/pages/BO/catalog/attributes/index.ts
  tests/UI/pages/BO/catalog/attributes/view.ts
  tests/UI/pages/BO/catalog/brands/add.ts
  tests/UI/pages/BO/catalog/brands/addAddress.ts
  tests/UI/pages/BO/catalog/brands/index.ts
  tests/UI/pages/BO/catalog/brands/view.ts
  tests/UI/pages/BO/catalog/categories/add.ts
  tests/UI/pages/BO/catalog/categories/index.ts
  tests/UI/pages/BO/catalog/discounts/add.ts
  tests/UI/pages/BO/catalog/discounts/catalogPriceRules/add.ts
  tests/UI/pages/BO/catalog/discounts/catalogPriceRules/index.ts
  tests/UI/pages/BO/catalog/discounts/index.ts
  tests/UI/pages/BO/catalog/features/addFeature.ts
  tests/UI/pages/BO/catalog/features/addValue.ts
  tests/UI/pages/BO/catalog/features/index.ts
  tests/UI/pages/BO/catalog/features/view.ts
  tests/UI/pages/BO/catalog/files/add.ts
  tests/UI/pages/BO/catalog/files/index.ts
  tests/UI/pages/BO/catalog/monitoring/index.ts
  tests/UI/pages/BO/catalog/products/add.ts
  tests/UI/pages/BO/catalog/products/index.ts
  tests/UI/pages/BO/catalog/stocks/index.ts
  tests/UI/pages/BO/catalog/stocks/movements/index.ts
Labels: Improvement, TE, develop, E2E Tests

#31112 Functional tests - Add new test 'Enable/disable demo mode'
  tests/UI/campaigns/functional/BO/01_dashboard/01_enableDisableDemoMode.ts
  tests/UI/package.json
  tests/UI/pages/BO/dashboard/index.ts
Labels: TE, Refactoring, E2E Tests, 8.1.x

#31118 Remove controller deprecations
  src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php
Labels: Improvement, QA ✔️, develop, BC break, Needs documentation

#31217 Functional Tests : Migration TS (`@data/import/*`)
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/05_paginationAndSortCategories.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/01_emptyCategories.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/02_withCombinationsWithoutQuantities.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/03_withoutCombinationsWithoutQuantities.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/04_disabledProducts.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/05_productsWithoutImage.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/06_productsWithoutDescription.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/07_productsWithoutPrice.ts
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/brands/02_sortPaginationAndBulkActions.ts
  tests/UI/campaigns/functional/BO/04_customers/01_customers/04_paginationAndSortCustomers.ts
  tests/UI/campaigns/functional/BO/04_customers/02_addresses/04_paginationAndSortAddresses.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/05_import/02_importFile.ts
  tests/UI/data/faker/import.ts
  tests/UI/data/import/addresses.js
  tests/UI/data/import/addresses.ts
  tests/UI/data/import/brands.js
  tests/UI/data/import/brands.ts
  tests/UI/data/import/categories.js
  tests/UI/data/import/categories.ts
  tests/UI/data/import/combinations.js
  tests/UI/data/import/combinations.ts
  tests/UI/data/import/customers.js
  tests/UI/data/import/customers.ts
  tests/UI/data/import/disabledProducts.js
  tests/UI/data/import/disabledProducts.ts
  tests/UI/data/import/productsWithoutQuantities.js
  tests/UI/data/import/productsWithoutQuantities.ts
  tests/UI/data/types/import.d.ts
  tests/UI/utils/files.ts
Labels: Improvement, QA ✔️, TE, E2E Tests

#31241 Improved session availability test
  classes/ConfigurationTest.php
Labels: QA ✔️, 8.0.x, Bug fix

#31237 Update hook list
  install-dev/data/xml/hook.xml
Labels: Improvement, QA ✔️

#31199 prestashop:linter:security-annotation find-missing failed because of non existant methods
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AuthorizationServer/ApiAccessController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AuthorizationServer/ApplicationController.php
Labels: QA ✔️, BO, Bug fix

#31236 Bump patch symfony
  composer.json
  composer.lock
Labels: Improvement, QA ✔️

#29524 Disable product type button when new changes are not saved
  admin-dev/themes/new-theme/js/pages/product/edit/product-partial-updater.ts
  admin-dev/themes/new-theme/scss/pages/product/product_page.scss
Labels: Improvement, QA ✔️, 8.1.x

#31029 Remove autoload
  classes/PrestaShopAutoload.php
  classes/Tools.php
  controllers/admin/AdminTranslationsController.php
  tests/Integration/Classes/PrestaShopAutoloadTest.php
Labels: Improvement, QA ✔️, develop, BC break

#31249 Update licenses
  src/Adapter/Product/Image/CommandHandler/SetProductImagesForAllShopHandler.php
  src/Core/Domain/Product/Image/Command/ProductImageSetting.php
  src/Core/Domain/Product/Image/Command/SetProductImagesForAllShopCommand.php
  src/Core/Domain/Product/Image/CommandHandler/SetProductImagesForAllShopHandlerInterface.php
  src/Core/Domain/Product/Image/Exception/CannotRemoveCoverException.php
  src/Core/Search/Filters/CustomerThreadFilter.php
  src/Core/Security/Hashing.php
  src/Core/Security/OpenSsl/OpenSSL.php
  src/Core/Security/OpenSsl/OpenSSLInterface.php
  src/Core/Security/PasswordGenerator.php
  src/Core/Version.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/FeatureFlag/EventListener/FeatureFlagTypeListener.php
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/private.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/not_found.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/FormTheme/catalog_price_rules.html.twig
  src/PrestaShopBundle/Routing/Converter/LegacyRouteFactory.php
  tests/Unit/Core/Security/HashingTest.php
  tests/Unit/Core/Security/PasswordGeneratorTest.php
  tests/Unit/PrestaShopBundle/AppKernelTest.php
  tests/Unit/PrestaShopBundle/Routing/Converter/LegacyRouteFactoryTest.php
  var/class_stub.php
Labels: Improvement, QA ✔️

#31171 Fallback to first found combination when fetching combination by all shops constraint
  src/Adapter/Product/Combination/Repository/CombinationRepository.php
  src/Adapter/Product/Repository/ProductSupplierRepository.php
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/Shop/update_combination_suppliers_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/update_combination_suppliers.feature
Labels: QA ✔️, Bug fix, 8.1.x

#31023 backport #30309 : Fix broken result in webservices for 8.0.x
  classes/webservice/WebserviceOutputBuilder.php
Labels: QA ✔️, 8.0.x, Bug fix

#31247 Feature flag multistore
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/FeatureFlag/FeatureFlagsFormDataProvider.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/views/Admin/Common/multistore-infotip.html.twig
Labels: QA ✔️, Bug fix

#31243 Functional tests - Add new tests 'FO > CRUD address in checkout page'
  tests/UI/campaigns/functional/FO/11_checkout/02_addresses/01_CRUDAddress.ts
  tests/UI/pages/FO/checkout/index.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#31283 Functional tests - Add new test 'FO > Checkout page > Add order message'
  tests/UI/campaigns/functional/FO/11_checkout/03_shippingMethods/01_addOrderMessage.ts
  tests/UI/pages/FO/checkout/index.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#31255 PPV2 catch ProductNotFound exception and flash error
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
Labels: QA ✔️, Bug fix

#31220 Rename behats multishop features for easier to follow convention
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/Shop/combinations_listing_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/Shop/copy_combinations_to_shop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/Shop/delete_combination_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/Shop/generate_combination_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/Shop/set_default_combination_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/Shop/update_combination_details_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/Shop/update_combination_prices_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/Shop/update_combination_stock_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/add_image_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/bulk_delete_product_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/bulk_update_product_status_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/delete_image_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/duplicate_product_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_basic_information_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_categories_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_customization_fields_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_image_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_options_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_pack_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_prices_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_seo_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_shipping_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_status_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_stock_multishop.feature
Labels: Refactoring

#31076 Send proper welcome emails to customers
  classes/Customer.php
  classes/form/CustomerPersister.php
Labels: QA ✔️, develop, Refactoring

#12422 Remove legacy customization system
  admin-dev/themes/default/template/controllers/carts/helpers/view/view.tpl
  classes/Cart.php
  classes/Customization.php
  classes/Product.php
  classes/order/Order.php
  classes/order/OrderDetail.php
  classes/order/OrderInvoice.php
  classes/order/OrderReturn.php
  classes/pdf/HTMLTemplateOrderSlip.php
  controllers/admin/AdminCartsController.php
  controllers/front/OrderFollowController.php
  pdf/invoice.product-tab.tpl
  src/Adapter/Cart/QueryHandler/GetCartForViewingHandler.php
  src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php
  src/Adapter/Order/OrderProductQuantityUpdater.php
  src/Adapter/Order/QueryHandler/GetOrderProductsForViewingHandler.php
  src/Adapter/Order/Refund/OrderRefundCalculator.php
  src/Adapter/Presenter/Order/OrderLazyArray.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Cart/Blocks/View/cart_summary.html.twig
Labels: QA ✔️, develop, Refactoring, Topwatchers, Deprecations, BC break, Wording ✔️, Needs documentation

#31260 Update PrestaShop module version
  composer.lock
Labels: Improvement, QA ✔️, CO

#31155 Allow custom redirect after login
  controllers/admin/AdminLoginController.php
Labels: Improvement, QA ✔️, develop

#31292 Functional Tests : Fixed Warning `Warning: fetchStandardFontData: failed to fetch file "FoxitSans.pfb" with "UnknownErrorException: The standard font "baseUrl" parameter must be specified, ensure that the "standardFontDataUrl" API parameter is provided.".`
  tests/UI/utils/files.ts
Labels: Improvement, QA ✔️, TE, E2E Tests

#31262 Adjust stock movement label when product is virtual
  src/Core/Domain/Product/Stock/Query/GetProductStockMovements.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationStockType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/QuantityType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/StockMovementType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/StockType.php
Labels: QA ✔️, Bug fix

#31257 Functional Tests : Migration TS (Remove public attributes targeting a selector)
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/01_CRUDBrandAndAddress.ts
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule.ts
  tests/UI/campaigns/functional/BO/15_header/07_myProfile.ts
  tests/UI/campaigns/functional/FO/07_search/01_consultAutocompleteList.ts
  tests/UI/campaigns/functional/FO/07_search/02_searchProduct.ts
  tests/UI/campaigns/functional/FO/07_search/03_searchNoResult.ts
  tests/UI/campaigns/sanity/04_catalogFO/01_filterProducts.ts
  tests/UI/campaigns/sanity/05_cartFO/01_editCheckCart.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/advancedParameters/team/employeeBasePage.ts
  tests/UI/pages/BO/advancedParameters/team/myProfile.ts
  tests/UI/pages/BO/catalog/brands/view.ts
  tests/UI/pages/BO/customers/add.ts
  tests/UI/pages/BO/customers/addresses/add.ts
  tests/UI/pages/BO/design/themeAndLogo/advancedCustomization/index.ts
  tests/UI/pages/BO/orders/add.ts
  tests/UI/pages/BO/orders/view/customerBlock.ts
  tests/UI/pages/FO/FObasePage.ts
  tests/UI/pages/FO/cart/index.ts
  tests/UI/pages/FO/home/index.ts
  tests/UI/pages/FO/myAccount/addresses.ts
Labels: Improvement, QA ✔️, TE, E2E Tests

#29510 Migrate "Internation > Locations > States" page
  controllers/admin/AdminStatesController.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/state.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Locations/State/Blocks/form.html.twig
  tests/Integration/Classes/controller/AdminControllerTest.php
  tests/Integration/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminControllerTest.php
  tests/UI/campaigns/functional/BO/11_international/02_locations/03_states/01_filterAndQuickEditStates.ts
  tests/UI/campaigns/functional/BO/11_international/02_locations/03_states/02_CRUDState.ts
  tests/UI/campaigns/functional/BO/11_international/02_locations/03_states/03_bulkActionsStates.ts
  tests/UI/campaigns/functional/BO/11_international/02_locations/03_states/04_sortAndPagination.ts
  tests/UI/data/demo/countries.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/international/locations/states/add.ts
  tests/UI/pages/BO/international/locations/states/index.ts
Labels: QA ✔️, develop, Refactoring, BC break

#30929 Customer Groups migration
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/js/pages/customer-groups/index.ts
  src/Core/Grid/Definition/Factory/CustomerGroupsGridDefinitionFactory.php
  src/Core/Grid/Query/CustomerGroupsQueryBuilder.php
  src/Core/Search/Filters/CustomerGroupsFilters.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/CustomerGroupsController.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/shop_parameters/_shop_parameters.yml
  src/PrestaShopBundle/Resources/config/routing/admin/configure/shop_parameters/customer_groups.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_data_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_factory.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/CustomerSettings/Groups/index.html.twig
Labels: develop, Refactoring, migration

#31223 Don't catch exception that implements ModuleErrorInterface
  classes/Hook.php
Labels: QA ✔️, develop, Bug fix

#31339 Add @experimental to new API-related classes
  src/Core/Grid/Column/Type/AuthorizationServer/ApiAccessesStatesColumn.php
  src/Core/Grid/Definition/Factory/AuthorizedApplicationGridDefinitionFactory.php
  src/Core/Grid/Query/AuthorizedApplicationQueryBuilder.php
  src/Core/Search/Filters/AuthorizedApplicationsFilters.php
  src/Core/Security/OAuth2/ResourceServerInterface.php
  src/Core/Security/TokenAuthenticator.php
  src/PrestaShopBundle/Api/Api.php
  src/PrestaShopBundle/Api/Resource/HookStatus.php
  src/PrestaShopBundle/Api/StateProvider/HookStatusProvider.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AuthorizationServer/ApiAccessController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AuthorizationServer/ApplicationController.php
  src/PrestaShopBundle/Controller/Api/OAuth2/AccessTokenController.php
  src/PrestaShopBundle/Entity/ApiAccess.php
  src/PrestaShopBundle/Entity/AuthorizedApplication.php
  src/PrestaShopBundle/Entity/Repository/ApiAccessRepository.php
  src/PrestaShopBundle/Entity/Repository/AuthorizedApplicationRepository.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/FeatureFlag/EventListener/FeatureFlagTypeListener.php
  src/PrestaShopBundle/Security/OAuth2/Entity/AccessToken.php
  src/PrestaShopBundle/Security/OAuth2/Entity/Client.php
  src/PrestaShopBundle/Security/OAuth2/Repository/AccessTokenRepository.php
  src/PrestaShopBundle/Security/OAuth2/Repository/ClientRepository.php
  src/PrestaShopBundle/Security/OAuth2/Repository/NullScopeRepository.php
  src/PrestaShopBundle/Security/OAuth2/ResourceServer.php
Labels: Improvement

#31138 Migrate form types to FQCN / autowire
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/OrderPreferences/GeneralType.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/OrderStates/OrderStateType.php
  src/PrestaShopBundle/Form/Admin/Improve/Shipping/Preferences/HandlingType.php
  src/PrestaShopBundle/Form/Admin/Product/ProductCombinationBulk.php
  src/PrestaShopBundle/Form/Admin/Product/ProductCustomField.php
  src/PrestaShopBundle/Form/Admin/Product/ProductQuantity.php
  src/PrestaShopBundle/Form/Admin/Product/ProductSeo.php
  src/PrestaShopBundle/Form/Admin/Product/ProductWarehouseCombination.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/PricingType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/UnitPriceType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_extension.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type/webservice.yml
Labels: Improvement, QA ✔️, develop, Bug fix, BC break

#31363 Add customer edit tests
  tests/Integration/Behaviour/Features/Context/CustomerManagerFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Customer/customer_management.feature
Labels: TE, develop, Feature

#31111 Improve customer basic info section
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/personal_information.html.twig
Labels: Improvement, QA ✔️, develop, Wording ✔️

#31364 Update phpstan configuration file
  phpstan-baseline.neon
  phpstan-disallowed-calls.neon
  phpstan.neon.dist
Labels: Improvement, develop

#31357 Functional tests - Add new test 'FO > checkout page > Select carrier'
  tests/UI/campaigns/functional/FO/11_checkout/03_shippingMethods/02_selectCarrier.ts
  tests/UI/pages/FO/checkout/index.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#31307 8.1.0 build
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
  src/Core/Domain/Product/Stock/StockSettings.php
Labels: Improvement

#31395 Changed selfupdate composer command
  .github/workflows/cron_php_update_modules.yml
Labels: Improvement, develop

#25353 Allow ordering as a guest, even after a you made an account
  classes/Customer.php
  classes/form/CustomerForm.php
  classes/form/CustomerFormatter.php
  classes/form/CustomerPersister.php
  controllers/front/GuestTrackingController.php
  controllers/front/OrderConfirmationController.php
  src/Adapter/Customer/CommandHandler/EditCustomerHandler.php
  src/Adapter/Customer/CommandHandler/TransformGuestToCustomerHandler.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
Labels: QA ✔️, PM ✔️, develop, Bug fix, Wording ✔️

#31405 Add back 8.0.1 changelog
  docs/CHANGELOG.txt
Labels: Bug fix

#26764 Avoid including negative stock quantity values in attribute selector total quantity sum
  controllers/front/ProductController.php
Labels: QA ✔️, develop, Bug fix

#31355 Fix invisible label on checkbox
  admin-dev/themes/new-theme/js/app/pages/stock/components/header/filters/low-filter.vue
Labels: QA ✔️, Bug fix

#31323 Improve customer group selector
  admin-dev/themes/new-theme/js/pages/customer/CustomerForm.ts
  admin-dev/themes/new-theme/js/pages/customer/customer-form-map.ts
Labels: Improvement, QA ✔️, develop

#31386 Add test for mismatching groups, fix the check in handler
  src/Adapter/Customer/CommandHandler/EditCustomerHandler.php
  tests/Integration/Behaviour/Features/Scenario/Customer/customer_management.feature
Labels: Waiting for author, develop, Refactoring

#31367 Fix a typo in xml hook list
  install-dev/data/xml/hook.xml
Labels: QA ✔️, Bug fix

#31099 Adjust multishop images behavior in dropzone
  admin-dev/themes/new-theme/js/fos_js_routes.json
  admin-dev/themes/new-theme/js/pages/product/edit/index.ts
  admin-dev/themes/new-theme/js/pages/product/image/dropzone/Dropzone.vue
  admin-dev/themes/new-theme/js/pages/product/image/dropzone/DropzoneWindow.vue
  admin-dev/themes/new-theme/js/pages/product/image/dropzone/index.ts
  admin-dev/themes/new-theme/js/pages/product/image/images-shop-association/ImageShopAssociationModal.vue
  admin-dev/themes/new-theme/js/pages/product/image/images-shop-association/index.ts
  admin-dev/themes/new-theme/js/pages/product/service/image.ts
  src/Adapter/Product/Image/CommandHandler/SetProductImagesForAllShopHandler.php
  src/Adapter/Product/Image/CommandHandler/UpdateProductImageHandler.php
  src/Adapter/Product/Image/QueryHandler/GetProductImagesHandler.php
  src/Adapter/Product/Image/Repository/ProductImageMultiShopRepository.php
  src/Adapter/Product/Image/Update/ProductImageUpdater.php
  src/Adapter/Product/QueryHandler/GetProductForEditingHandler.php
  src/Adapter/Product/Repository/ProductMultiShopRepository.php
  src/Adapter/Product/Shop/CommandHandler/BulkDeleteProductFromShopsHandler.php
  src/Adapter/Product/Shop/CommandHandler/DeleteProductFromShopsHandler.php
  src/Adapter/Product/Update/ProductShopUpdater.php
  src/Core/Form/IdentifiableObject/DataHandler/ProductImageFormDataHandler.php
  src/Core/Repository/AbstractMultiShopObjectModelRepository.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ImageController.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Description/DescriptionType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/EditProductFormType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Image/ImageDropzoneType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Image/ProductImageType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/product_v2/image.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_image.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/FormTheme/product.html.twig
  tests/Integration/Behaviour/Features/Context/Domain/AbstractDomainFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/ShopFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/search_combinations_for_association.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Image/add_image.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/add_image_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/bulk_delete_product_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/delete_image_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/get_shop_product_images.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/set_product_images_for_all_shops.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_image_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/search_products_for_association.feature
Labels: QA ✔️, Bug fix, Wording ✔️, 8.1.x

#31389 Functional tests - Add scripts to run each test less than 30 minutes
  tests/UI/package.json
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#31456 Fixed indentation in yaml file
  .github/workflows/php.yml
Labels: develop, Bug fix

#31375 Add guest functionality to add customer command
  src/Adapter/Customer/CommandHandler/AddCustomerHandler.php
  src/Core/Domain/Customer/Command/AddCustomerCommand.php
  tests/Integration/Behaviour/Features/Context/CustomerManagerFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CustomerFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Customer/customer_management.feature
Labels: QA ✔️, develop, Refactoring

#31294 New hook for performing actions when address change on cart
  classes/Cart.php
  install-dev/data/xml/hook.xml
Labels: QA ✔️, develop, Feature, Needs documentation, Needs autoupgrade PR

#31440 Fix sales value in customer grid list
  src/Core/Grid/Query/CustomerQueryBuilder.php
Labels: Improvement, QA ✔️, develop

#29000 Add actionCartGetPackageShippingCost hook
  classes/Cart.php
  install-dev/data/xml/hook.xml
Labels: Improvement, QA ✔️, develop, Needs autoupgrade PR

#31028 Remove deprecated features on v9
  classes/Currency.php
  classes/Tools.php
  classes/Translate.php
  config/services/common.yml
  src/Adapter/Tools.php
  src/Core/Hook/HookDispatcherAwareTrait.php
  src/Core/String/CharacterCleaner.php
  src/PrestaShopBundle/Form/Admin/Type/CommonAbstractType.php
  src/PrestaShopBundle/Resources/config/services/core/string.yml
Labels: Improvement, QA ✔️, develop, BC break, Needs documentation

#31455 Fix missing closing div in linked orders
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/linked_orders.html.twig
Labels: develop, Bug fix

#31310 Fix thumbnail links for categories and stores, add manufacturer and supplier support
  classes/Link.php
  src/Adapter/Image/ImageRetriever.php
Labels: QA ✔️, Bug fix, Waiting for dev

#29464 Remove forgotten deprecations
  classes/Link.php
  controllers/front/ProductController.php
  install-dev/init.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Form/Admin/Type/TranslateTextType.php
Labels: QA ✔️, develop, Refactoring, BC break

#31439 Add information about customer default group
  src/Adapter/Customer/QueryHandler/GetCustomerForViewingHandler.php
  src/Core/Domain/Customer/QueryResult/GroupInformation.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/groups.html.twig
Labels: QA ✔️, PM ✔️, develop, Feature

#31461 Add guest customer edit test
  tests/Integration/Behaviour/Features/Context/CustomerManagerFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CustomerFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Customer/customer_management.feature
Labels: develop, Refactoring

#31374 Cleanup StockAvailable repositories
  src/Adapter/Product/Combination/Create/CombinationCreator.php
  src/Adapter/Product/Combination/QueryHandler/GetCombinationForEditingHandler.php
  src/Adapter/Product/Combination/Update/CombinationStockUpdater.php
  src/Adapter/Product/QueryHandler/GetProductForEditingHandler.php
  src/Adapter/Product/Stock/QueryHandler/AbstractGetStockMovementsHandler.php
  src/Adapter/Product/Stock/Repository/StockAvailableMultiShopRepository.php
  src/Adapter/Product/Stock/Repository/StockAvailableRepository.php
  src/Adapter/Product/Stock/Update/ProductStockUpdater.php
  src/Adapter/Product/Update/ProductShopUpdater.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_combination.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_stock.yml
Labels: Refactoring, 8.1.x

#31479 Functional tests - Fix typo error in addOrder page
  tests/UI/pages/BO/orders/add.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#31471 Functional tests : BO - Design - Image Settings - Delete actions
  classes/ImageType.php
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/05_sortAndPagination.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/06_deleteActions.ts
  tests/UI/pages/BO/design/imageSettings/index.ts
Labels: Improvement, TE, E2E Tests

#31492 Functional tests - Fix random errors
  tests/UI/pages/BO/catalog/stocks/index.ts
  tests/UI/pages/BO/orders/add.ts
Labels: TE, Refactoring, E2E Tests

#31426 Functional tests - Add new test 'Add to cart by quick view modal'
  tests/UI/campaigns/functional/FO/09_productPage/01_quickView/01_addToCart.ts
  tests/UI/pages/FO/home/index.ts
Labels: TE, Refactoring, E2E Tests

#31407 Functional tests - Add new test 'Sign in in checkout page'
  tests/UI/campaigns/functional/FO/11_checkout/01_personalInformation/02_signIn.ts
  tests/UI/pages/FO/cart/index.ts
  tests/UI/pages/FO/checkout/index.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#31467 PPV2 Fix virtual file validation
  admin-dev/themes/new-theme/js/pages/product/edit/manager/virtual-product-manager.ts
  admin-dev/themes/new-theme/js/pages/product/product-map.ts
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/VirtualProductFileType.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/FormTheme/virtual_product_file.html.twig
Labels: QA ✔️, Bug fix, 8.1.x

#31513 Merge 8.0.x into 8.1.x
  .github/workflows/php.yml
  tests/Resources/TestCase/ExtendedTestCaseMethodsTrait.php
  tests/Unit/Classes/Tax/TaxCalculatorCoreTest.php
  tests/Unit/Classes/ToolsTest.php
  tests/Unit/Core/Cart/AmountImmutableTest.php
Labels: Improvement

#31483 Functional Tests : Refactored Feature Flag
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/06_addProductToTheCart.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/09_imageGenerationOptions.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/11_newAndExperimentalFeatures/01_enableDisableExperimentalProductV2.ts
  tests/UI/campaigns/sanity/03_productsBO/01_filterProducts.ts
  tests/UI/commonTests/BO/advancedParameters/newFeatures.ts
  tests/UI/pages/BO/advancedParameters/featureFlag/index.ts
Labels: TE, Refactoring, E2E Tests

#31474 Remove FrameworkExtraBundle `@Template` annotation.
  phpstan-disallowed-calls.neon
  src/PrestaShopBundle/Controller/Admin/CommonController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SystemInformationController.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/PositionsController.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Controller/Admin/ProductImageController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/DeliveryController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/InvoicesController.php
  src/PrestaShopBundle/Controller/Admin/SpecificPriceController.php
Labels: QA ✔️, develop, Refactoring, BC break

#31525 Bump modules (ps_linklist in v6 & blockwishlist in v3)
  composer.json
  composer.lock
Labels: Improvement, Waiting for QA, develop

#31495 Add whitelist to legacy link linter mechanism
  src/PrestaShopBundle/Command/LegacyLinkLinterCommand.php
Labels: Improvement, QA ✔️, develop

#31523 multistore table dropdown correction
  admin-dev/themes/default/scss/partials/_multistore.scss
Labels: QA ✔️, Bug fix

#31509 Functional tests - Add new test 'FO > Checkout > Password reminder'
  tests/UI/campaigns/functional/FO/11_checkout/01_personalInformation/05_passwordReminder.ts
  tests/UI/pages/FO/checkout/index.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#31337 Fix open new tab when target _blank exist for new product page link
  admin-dev/themes/new-theme/js/pages/product/create/create-product-modal.ts
Labels: QA ✔️, develop, Bug fix

#31550 CI : Nightly : Split by version & Fail on error (for tests)
  .github/workflows/cron_nightly_tests_8.0.x.yml
  .github/workflows/cron_nightly_tests_8.1.x.yml
  .github/workflows/cron_nightly_tests_develop.yml
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#31416 Fix the bypass of censorship of sensitive data in sql queries
  src/Adapter/SqlManager/QueryHandler/GetSqlRequestExecutionResultHandler.php
  tests/Integration/Adapter/SqlManager/QueryHandler/GetSqlRequestExecutionResultHandlerTest.php
Labels: QA ✔️, develop, Bug fix

#31485 Fix base image format generation, enable it for new image system, simplify
  classes/ImageManager.php
  controllers/admin/AdminImagesController.php
  controllers/admin/AdminProductsController.php
  controllers/admin/AdminStoresController.php
  controllers/admin/AdminSuppliersController.php
  src/Adapter/Image/ImageGenerator.php
  src/Adapter/Image/ImageRetriever.php
  src/Adapter/Image/Uploader/AbstractImageUploader.php
  src/Core/Shop/LogoUploader.php
Labels: QA ✔️, Bug fix, Refactoring, Wording ✔️

#31503 Filter empty values for modulesFromHooks
  src/Core/Module/ModuleRepository.php
Labels: QA ✔️, 8.0.x, Bug fix

#31524 CI : Added support to branch 8.1.x (and removed support to branch 1.7.8.x)
  .github/workflows/cron_js_routing.yml
  .github/workflows/cron_nightly_build.yml
  .github/workflows/cron_php_update_modules.yml
Labels: Improvement, QA ✔️, develop

#31558 Bump classic theme to 2.1.0
  composer.lock
Labels: Improvement, QA ✔️, 8.1.x

#31496 Handle shop constraint when searching customer for specific price
  admin-dev/themes/new-theme/js/components/entity-search-input.ts
  admin-dev/themes/new-theme/js/pages/product/specific-price/form/customer-selector.ts
  admin-dev/themes/new-theme/js/pages/product/specific-price/form/index.ts
  classes/Customer.php
  src/Adapter/Customer/QueryHandler/SearchCustomersHandler.php
  src/Core/Domain/Customer/Query/SearchCustomers.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
Labels: QA ✔️, Bug fix, 8.1.x

#31552 Functional tests - Add new test 'FO > Checkout > Show details'
  tests/UI/campaigns/functional/FO/11_checkout/01_showDetails.ts
  tests/UI/data/types/product.d.ts
  tests/UI/pages/FO/checkout/index.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#31555 Functional tests - Refacto 'BO >International > CRUD country'
  tests/UI/campaigns/functional/BO/11_international/02_locations/02_countries/02_CRUDCountry.ts
  tests/UI/pages/BO/international/locations/countries/add.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#31462 Improve duplicate customer exceptions
  src/Adapter/Customer/CommandHandler/AddCustomerHandler.php
  src/Adapter/Customer/CommandHandler/EditCustomerHandler.php
  src/Core/Domain/Customer/Exception/DuplicateCustomerEmailException.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
  tests/Integration/Behaviour/Features/Scenario/Customer/customer_management.feature
Labels: QA ✔️, develop, Refactoring, Wording ✔️

#31499 Simplify module manager, remove see more/less
  admin-dev/themes/new-theme/js/components/module-card.ts
  admin-dev/themes/new-theme/js/pages/module/controller.js
  admin-dev/themes/new-theme/scss/components/_modulescards.scss
  admin-dev/themes/new-theme/scss/pages/_modules.scss
  src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/card_grid.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/card_list_addons.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/categories_card.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/categories_grid.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/grid_loader.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/see_more.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/sorting.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/manage.html.twig
Labels: Improvement, QA ✔️, develop, BC break, Needs documentation

#31566 CI : Nightly (Move secrets outside the composite and continue even if there are errors in job)
  .github/workflows/cron_nightly_tests_8.0.x.yml
  .github/workflows/cron_nightly_tests_8.1.x.yml
  .github/workflows/cron_nightly_tests_develop.yml
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#31330 Fix access error when accessing product creation modal
  classes/QuickAccess.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
Labels: QA ✔️, Bug fix, 8.1.x

#31575 Add missing licence
  tests/Resources/TestCase/ExtendedTestCaseMethodsTrait.php
Labels: Improvement, 8.0.x
