Repository PrestaShop/PrestaShop, pull requests merged in 2023-11, with the labels that each got.

#34444 Fix php warning webservice
  webservice/dispatcher.php
Labels: QA ✔️, Refactoring, 8.1.x

#34443 Remove useless htaccess rule for not existing file retro-compat.css.php
  js/.htaccess
Labels: Refactoring, 8.1.x

#34439 Update retro-compat.js.php - prevent PHP Warning
  js/retro-compat.js.php
Labels: Waiting for QA, Refactoring, 8.1.x

#34441 Fixed SQL apostrophe (') incompatibility
  src/Adapter/Product/Update/ProductDuplicator.php
Labels: QA ✔️, Bug fix, 8.1.x

#34435 Protect js folder from dangerous files
  js/.htaccess
Labels: Improvement, Waiting for dev, 8.1.x

#34158 Explicit error messages
  classes/Country.php
Labels: Improvement, QA ✔️, 8.1.x

#33700 Add an instruction in htaccess to prevent directory listings
  classes/Tools.php
Labels: QA ✔️, develop, Bug fix

#34422 Functional Tests : `functional/BO/14*/12*/02*` : Changes for Client Secret
  tests/UI/campaigns/functional/BO/14_advancedParameters/12_authorizationServer/02_addAPIAccess.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/12_authorizationServer/03_editAPIAccess.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/advancedParameters/APIAccess/add.ts
  tests/UI/pages/commonPage.ts
  tests/UI/utils/helpers.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#34420 Make old style errors verbose.
  admin-dev/filemanager/config/config.php
  classes/CMSCategory.php
  classes/Carrier.php
  classes/Cart.php
  classes/Category.php
  classes/Cookie.php
  classes/Country.php
  classes/Customer.php
  classes/Employee.php
  classes/Feature.php
  classes/Image.php
  classes/ImageType.php
  classes/Language.php
  classes/Manufacturer.php
  classes/Message.php
  classes/Meta.php
  classes/PaymentModule.php
  classes/PrestaShopBackup.php
  classes/Product.php
  classes/State.php
  classes/Supplier.php
  classes/controller/AdminController.php
  classes/module/ModuleGraph.php
  classes/module/ModuleGrid.php
  classes/order/OrderReturn.php
  classes/tax/TaxRule.php
  controllers/admin/AdminCustomerThreadsController.php
  controllers/admin/AdminFeaturesController.php
  controllers/admin/AdminRequestSqlController.php
  controllers/admin/AdminReturnController.php
  controllers/admin/AdminStatsController.php
  controllers/admin/AdminStatusesController.php
  controllers/front/GetFileController.php
  controllers/front/OrderFollowController.php
Labels: QA ✔️, Refactoring, 8.1.x

#34461 Nightly : Fixed `campaigns/functional/BO/05*/01*/06*`
  tests/UI/pages/BO/customerService/customerService/view.ts
  tests/UI/pages/BO/shopParameters/orderSettings/statuses/add.ts
  tests/UI/pages/BO/shopParameters/orderSettings/statuses/returnStatus/add.ts
  tests/UI/pages/commonPage.ts
Labels: TE, develop, Bug fix, E2E Tests

#34449 Functional tests - Add new test 'FO> Menu and navigation > Clear one filter'
  tests/UI/campaigns/functional/FO/classic/08_menuAndNavigation/02_sortAndFilter/03_clearOneFilter.ts
  tests/UI/pages/FO/category/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34456 Functional tests - Add new test 'FO > Personal information > Order as a guest'
  tests/UI/campaigns/functional/FO/classic/11_checkout/01_personalInformation/01_orderAsAGuest.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34459 Functional Tests : `functional/BO/14*/12*/03*` : Changes for Token Lifetime
  tests/UI/campaigns/functional/BO/14_advancedParameters/12_authorizationServer/03_editAPIAccess.ts
  tests/UI/data/faker/APIAccess.ts
  tests/UI/data/types/APIAccess.ts
  tests/UI/pages/BO/advancedParameters/APIAccess/add.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#34463 Functional tests - Add new test 'FO > Cart > Display of modal when adding a product to cart'
  tests/UI/campaigns/functional/FO/classic/10_cart/01_modal/01_displayModal.ts
Labels: TE, develop, Refactoring, E2E Tests

#34465 Functional Tests : FO - Checkout - Payment - Choose a payment method
  tests/UI/campaigns/functional/FO/classic/11_checkout/04_payment/01_choosePaymentMethod.ts
  tests/UI/data/demo/paymentMethods.ts
  tests/UI/pages/FO/checkout/orderConfirmation.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#34466 Functional tests - Add new test 'FO > Menu and navigation > Check breadcrumb links'
  tests/UI/campaigns/functional/FO/classic/08_menuAndNavigation/01_navigateInCategories/02_breadcrumb.ts
  tests/UI/pages/FO/FObasePage.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34467 Functional Tests : FO - Menu and Navigation : Side block categories
  tests/UI/campaigns/functional/FO/classic/08_menuAndNavigation/01_navigateInCategories/03_sideBlockCategories.ts
  tests/UI/data/demo/categories.ts
  tests/UI/data/faker/category.ts
  tests/UI/data/types/category.d.ts
  tests/UI/pages/FO/category/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#34478 Nightly : Fixed `functional/BO/04*/02*/02*`
  tests/UI/pages/BO/customers/addresses/add.ts
  tests/UI/pages/commonPage.ts
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#34462 Improve front office date validation
  controllers/front/ProductController.php
  src/Adapter/Presenter/Product/ProductLazyArray.php
Labels: QA ✔️, Bug fix, 8.1.x

#34452 Prevent Internal Server Error 500 - opcache_invalidate with restrict_api
  src/Adapter/Configuration/PhpParameters.php
  src/Adapter/Debug/DebugMode.php
  src/Adapter/Debug/DebugProfiling.php
  src/Adapter/Smarty/SmartyCacheConfiguration.php
  src/Core/SqlManager/Configuration/SqlRequestConfiguration.php
Labels: Improvement, 8.1.x

#34438 Fix BO CSV import - broken functionality
  controllers/admin/AdminImportController.php
  js/admin/import.js
Labels: QA ✔️, Bug fix, 8.1.x

#34394 Fix on asset links for the symfony layout
  admin-dev/themes/new-theme/.webpack/common.js
  app/config/config.yml
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/head_tag.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/core_javascript.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/stylesheets.html.twig
Labels: QA ✔️, develop, Bug fix

#34376 Fix potential TypeError in ProductLazyArray.php
  src/Adapter/Presenter/Product/ProductLazyArray.php
Labels: QA ✔️, Bug fix, 8.1.x

#34446 Functional tests - Fix product v2 multistore test after the fix of #34197
  tests/UI/campaigns/functional/BO/03_catalog/01_products/20_multistore.ts
  tests/UI/pages/BO/catalog/products/add/index.ts
  tests/UI/pages/commonPage.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34484 Merge 8.1.x into develop
  admin-dev/filemanager/config/config.php
  classes/CMSCategory.php
  classes/Carrier.php
  classes/Cart.php
  classes/Category.php
  classes/Cookie.php
  classes/Country.php
  classes/Customer.php
  classes/Employee.php
  classes/Feature.php
  classes/Image.php
  classes/ImageType.php
  classes/Language.php
  classes/Manufacturer.php
  classes/Message.php
  classes/Meta.php
  classes/PaymentModule.php
  classes/PrestaShopBackup.php
  classes/Product.php
  classes/State.php
  classes/Supplier.php
  classes/controller/AdminController.php
  classes/module/ModuleGraph.php
  classes/module/ModuleGrid.php
  classes/order/OrderReturn.php
  classes/tax/TaxRule.php
  controllers/admin/AdminCustomerThreadsController.php
  controllers/admin/AdminImportController.php
  controllers/admin/AdminReturnController.php
  controllers/admin/AdminStatsController.php
  controllers/front/GetFileController.php
  controllers/front/OrderFollowController.php
  controllers/front/ProductController.php
  js/admin/import.js
  src/Adapter/Configuration/PhpParameters.php
  src/Adapter/Debug/DebugMode.php
  src/Adapter/Debug/DebugProfiling.php
  src/Adapter/Presenter/Product/ProductLazyArray.php
  src/Adapter/Product/Update/ProductDuplicator.php
  src/Adapter/Smarty/SmartyCacheConfiguration.php
  src/Core/SqlManager/Configuration/SqlRequestConfiguration.php
  webservice/dispatcher.php
Labels: QA ✔️, develop

#34494 Functional Tests : `functional/BO/14*/12*/*` : Changes for Scopes
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/AuthorizationServer/SwitchScopeType.php
  tests/UI/campaigns/functional/BO/14_advancedParameters/12_authorizationServer/02_addAPIAccess.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/12_authorizationServer/03_editAPIAccess.ts
  tests/UI/campaigns/modules/ps_apiresources/01_installation/01_uninstallAndInstallModule.ts
  tests/UI/campaigns/modules/ps_apiresources/01_installation/02_disableEnableModule.ts
  tests/UI/data/demo/modules.ts
  tests/UI/data/faker/APIAccess.ts
  tests/UI/data/types/APIAccess.ts
  tests/UI/pages/BO/advancedParameters/APIAccess/add.ts
Labels: Improvement, TE, develop, E2E Tests

#34501 Nightly : Fixed `campaigns/modules/blockwishlist/02*/02*` & `campaigns/functional/BO/14*/12*/02*`
  tests/UI/pages/BO/advancedParameters/APIAccess/add.ts
  tests/UI/pages/FO/category/index.ts
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#34450 Fix TaxRulesGroup try to update removed column
  classes/tax/TaxRulesGroup.php
Labels: QA ✔️, Bug fix

#34491 Improve error message on login page
  controllers/admin/AdminLoginController.php
  js/admin/login.js
  tests/UI/pages/BO/login/index.ts
Labels: QA ✔️, Refactoring, 8.1.x

#34487 Fix manufacturer name overwriting
  classes/Product.php
Labels: QA ✔️, Bug fix, 8.1.x

#33931 Inform customer about quantity in cart
  classes/Cart.php
  controllers/front/ProductController.php
  install-dev/data/xml/configuration.xml
  src/Adapter/Product/PageConfiguration.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/PageType.php
Labels: QA ✔️, develop, Feature, Bug fix, Wording ✔️, 8.1.x

#34502 Functional tests - Refacto 'BO > International > Translations' tests
  tests/UI/campaigns/functional/BO/11_international/04_translations/01_modifyTranslation.ts
  tests/UI/campaigns/functional/BO/11_international/04_translations/02_addUpdateLanguage.ts
  tests/UI/campaigns/functional/BO/11_international/04_translations/03_exportLanguage.ts
  tests/UI/pages/BO/catalog/discounts/add.ts
  tests/UI/pages/BO/international/translations/index.ts
  tests/UI/pages/BO/modules/moduleManager/index.ts
  tests/UI/pages/FO/home/index.ts
  tests/UI/pages/FO/hummingbird/home/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34511 Functional tests - Refacto tests in 'BO > Shop parameters > Customer settings'
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/01_redisplayCartAtLogin.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/02_sendEmailAfterRegistration.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/04_enableB2BMode.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/05_askForBirthDate.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/06_enablePartnerOffers.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/02_groups/01_filterGroups.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/02_groups/01_filterSortAndPaginationGroups.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/02_groups/03_bulkDeleteGroups.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/02_groups/03_defaultGroupsOptions.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/03_titles/01_filterSortAndPaginationTitles.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/03_titles/01_filterTitles.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/03_titles/03_bulkActions.ts
  tests/UI/pages/BO/shopParameters/customerSettings/groups/index.ts
  tests/UI/pages/BO/shopParameters/customerSettings/titles/index.ts
Labels: TE, develop, Refactoring, E2E Tests

#34514 Functional Tests : API : GET `/api/hook-status/{id}`
  admin-dev/themes/new-theme/js/pages/improve/design_positions/positions-list-handler.ts
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/positions.html.twig
  tests/UI/campaigns/functional/API/02_endpoints/04_hook/01_getAPIHookStatusId.ts
  tests/UI/pages/BO/design/positions/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#34531 Update Address.php - small phpdoc edit (@return value)
  classes/Address.php
Labels: QA ✔️, Refactoring, 8.1.x

#34548 Bump version to 8.1.3
  install-dev/install_version.php
  src/Core/Version.php
Labels: Improvement, 8.1.x

#34524 Upgrade symfony http-kernel to 5.4.31
  composer.lock
Labels: QA ✔️, develop, Refactoring

#34550 Use NumberFormatter's round constant instead of NumberToLocalizedStringTransformer's constant
  src/PrestaShopBundle/Form/Admin/Sell/Product/DataTransformer/SpecificPriceFixedPriceTransformer.php
Labels: Improvement, develop

#34520 Functional tests - Add new test and refacto "BO > Shop parameters > Product settings"
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/01_catalogMode.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/02_newDaysNumber.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/03_maxSizeShortDescription.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/04_quantityDiscountsBasedOn.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/01_displayAvailableQuantities.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/02_displayAddToCartButton.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/04_displayDiscountedPrice.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/02_defaultPackStockManagement.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/03_displayUnavailableProductAttributes.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/06_labelOfInStockProducts.ts
  tests/UI/pages/BO/shopParameters/productSettings/index.ts
  tests/UI/pages/FO/hummingbird/home/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34448 Validate smarty render calls (prevent errors from outdated themes)
  config/smartyfront.config.inc.php
Labels: Improvement, QA ✔️, 8.1.x

#34547 Merge 8.1.x into develop
  classes/Address.php
  classes/Product.php
  classes/tax/TaxRulesGroup.php
  controllers/admin/AdminLoginController.php
  js/admin/login.js
  tests/UI/pages/BO/login/index.ts
Labels: QA ✔️, develop

#34565 Functional tests - Add new test 'Shop Parameters > Enable/disable display best sellers page'
  tests/UI/campaigns/functional/BO/13_shopParameters/01_general/general/10_enableDisableBestSellers.ts
  tests/UI/pages/BO/shopParameters/general/index.ts
  tests/UI/pages/FO/siteMap/index.ts
Labels: TE, develop, Refactoring, E2E Tests

#34546 Functional Tests : API : GET `/api/api-access/{apiAccessId}`
  tests/UI/campaigns/functional/API/02_endpoints/01_apiAccess/01_getAPIApiAccessId.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/12_authorizationServer/03_editAPIAccess.ts
  tests/UI/commonTests/BO/advancedParameters/authServer.ts
  tests/UI/data/faker/APIAccess.ts
  tests/UI/data/types/APIAccess.ts
  tests/UI/pages/BO/advancedParameters/APIAccess/add.ts
  tests/UI/pages/BO/advancedParameters/APIAccess/index.ts
Labels: Improvement, TE, develop, E2E Tests

#34184 Forbidden sensitive files extentions on modules directory
  modules/.htaccess
Labels: QA ✔️, develop, Bug fix, Topwatchers, BC break

#34529 New 12% VAT Czech Republic from 2024-01-01
  localization/cz.xml
Labels: Improvement, QA ✔️, 8.1.x

#34537 Minimal quantity should be 1 at least, not 0!
  classes/Combination.php
  classes/Product.php
  classes/Validate.php
  src/PrestaShopBundle/Form/Admin/Product/ProductCombination.php
  src/PrestaShopBundle/Form/Admin/Product/ProductQuantity.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/QuantityType.php
Labels: QA ✔️, Bug fix, 8.1.x

#34556 Migrate deprecated DoctrineProvider to new one
  src/Adapter/Cache/Clearer/DoctrineCacheClearer.php
  src/Adapter/ContainerBuilder.php
  src/Core/Addon/Module/ModuleManagerBuilder.php
  src/PrestaShopBundle/Resources/config/services/bundle/cache.yml
  src/PrestaShopBundle/Resources/config/services/core/circuit_breaker.yml
  tests/Integration/Core/Module/ModuleRepositoryTest.php
Labels: Improvement, QA ✔️, develop

#34584 Functional tests - Add new test 'Shop parameters > Round mode'
  tests/UI/campaigns/functional/BO/13_shopParameters/01_general/general/05_roundMode.ts
  tests/UI/pages/BO/shopParameters/general/index.ts
Labels: TE, develop, Refactoring, E2E Tests

#34561 Functional tests - Add new test 'Shop parameters > Filter, sort, pagination and bulk actions search'
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/01_search/02_bulkActions.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/01_search/02_filterSortPaginationAndBulkActions.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/01_search/editSearchSettings/03_fuzzySearch.ts
  tests/UI/pages/BO/shopParameters/search/index.ts
Labels: TE, develop, Refactoring, E2E Tests

#34573 Functional tests - Add new test 'Shop parameters > Enable/Disable iframes'
  tests/UI/campaigns/functional/BO/13_shopParameters/01_general/general/03_allowIframes.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/01_general/general/08_enableDisableSuppliers.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/01_general/general/09_enableDisableBrands.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/01_general/general/10_enableDisableBestSellers.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/01_general/general/11_enableDisableMultistore.ts
  tests/UI/pages/BO/catalog/products/add/descriptionTab.ts
  tests/UI/pages/BO/shopParameters/general/index.ts
  tests/UI/pages/FO/product/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34571 Remove unused things in Media class
  classes/Media.php
  config/defines.inc.php
  tests/Integration/Classes/MediaTest.php
Labels: QA ✔️, develop, Refactoring, BC break

#34590 Functional tests - Fix random error in 'Nightly tests (develop, functional:BO:catalog:01-02)'
  tests/UI/pages/BO/catalog/products/add/combinationsTab.ts
  tests/UI/pages/commonPage.ts
Labels: TE, develop, Refactoring, E2E Tests

#34563 Update wording of add to cart from list setting
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/PageType.php
Labels: Improvement, Waiting for QA, QA ✔️, Wording ✔️, 8.1.x

#34600 Remove unnecessary Jquery selector in SerpApp.
  admin-dev/themes/new-theme/js/app/utils/serp/index.js
Labels: Waiting for QA, QA ✔️, Bug fix, 8.1.x

#34608 Functional tests - Add new test 'Multistore > Multistore options'
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/08_multistoreOptions.ts
  tests/UI/pages/BO/advancedParameters/multistore/index.ts
  tests/UI/pages/BO/advancedParameters/multistore/shop/add.ts
Labels: TE, develop, Refactoring, E2E Tests

#34609 Better validate cookie length
  classes/Cookie.php
Labels: QA ✔️, Refactoring, 8.1.x

#34614 Revise docblock for getToken()
  classes/Tools.php
Labels: Improvement, Waiting for QA, develop

#34515 Documentation to help run UI tests locally (Linux distribution)
  tests/UI/README.md
Labels: Improvement, develop

#34598 Fix sorting by Relevance in search results (develop branch version)
  src/Adapter/Search/SearchProductSearchProvider.php
Labels: QA ✔️, develop, Bug fix

#34317 Fix sorting by Relevance in search results
  src/Adapter/Search/SearchProductSearchProvider.php
Labels: QA ✔️, Bug fix, 8.1.x

#34633 Update ps_shoppingcart
  composer.json
  composer.lock
Labels: Waiting for QA, Refactoring, 8.1.x

#34635 Nightly : Fixed `campaigns/functional/WS/02*`
  tests/UI/campaigns/functional/WS/02_ordersCRUD.ts
  tests/UI/pages/BO/orders/view/tabListBlock.ts
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#34523 Fix combination unit price math
  classes/Product.php
  controllers/front/ProductController.php
Labels: QA ✔️, Bug fix, 8.1.x

#34626 Functional tests - Add new test 'Administration > Notifications'
  tests/UI/campaigns/functional/BO/14_advancedParameters/03_administration/03_notifications.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/advancedParameters/administration/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34528 Update 2 old links to PrestaShop site and github on BO login page
  admin-dev/themes/default/template/controllers/login/content.tpl
Labels: Waiting for QA, develop, Refactoring

#34464 Fix gift display in cart
  classes/Cart.php
  classes/CartRule.php
  classes/controller/FrontController.php
  controllers/front/CartController.php
  src/Core/Cart/CartRuleCalculator.php
Labels: QA ✔️, develop, Bug fix

#34647 Add empty string check for price in Catalog price rules
  controllers/admin/AdminSpecificPriceRuleController.php
Labels: QA ✔️, Bug fix, 8.1.x

#34650 Functional Tests : Cash on delivery (COD) module - Place an order with it
  tests/UI/campaigns/modules/ps_cashondelivery/02_configuration/01_placeOrderWithIt.ts
  tests/UI/data/demo/orderStatuses.ts
  tests/UI/data/faker/orderStatus.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#34560 Handle backward compatibility for smarty context
  src/Core/Context/CountryContextBuilder.php
  src/Core/Context/LanguageContextBuilder.php
  src/Core/Context/LegacyControllerContext.php
  src/Core/Context/ShopContext.php
  src/Core/Context/ShopContextBuilder.php
  src/PrestaShopBundle/EventListener/Context/Admin/LanguageContextListener.php
  src/PrestaShopBundle/EventListener/Context/Admin/ShopContextListener.php
  src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
  src/PrestaShopBundle/Resources/config/services/core/context.yml
  src/PrestaShopBundle/Resources/views/Admin/Layout/default_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/light_layout.html.twig
  src/PrestaShopBundle/Twig/Component/HeadTag.php
  src/PrestaShopBundle/Twig/Layout/PrestaShopLayoutGlobalVariables.php
  src/PrestaShopBundle/Twig/Layout/SmartyVariablesFiller.php
  src/PrestaShopBundle/Twig/Layout/TemplateVariables.php
  src/PrestaShopBundle/Twig/Layout/TemplateVariablesBuilder.php
  tests/Unit/PrestaShopBundle/EventListener/Context/Admin/ShopContextListenerTest.php
Labels: Improvement, develop, BC break

#34641 Merge 8.1.x into develop
  admin-dev/themes/new-theme/js/app/utils/serp/index.js
  classes/Combination.php
  classes/Cookie.php
  classes/Product.php
  classes/Tools.php
  classes/Validate.php
  composer.json
  composer.lock
  config/smartyfront.config.inc.php
  controllers/admin/AdminCartRulesController.php
  localization/cz.xml
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/PageType.php
  src/PrestaShopBundle/Form/Admin/Product/ProductCombination.php
  src/PrestaShopBundle/Form/Admin/Product/ProductQuantity.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/QuantityType.php
Labels: Waiting for QA, develop

#34648 Early return from rule check
  classes/CartRule.php
Labels: Improvement, QA ✔️, 8.1.x

#34625 Add hook "actionUpdateQuantity" in product v2
  src/Adapter/Product/Combination/Update/CombinationStockUpdater.php
  src/PrestaShopBundle/Resources/config/services/adapter/product/_combination.yml
Labels: QA ✔️, Bug fix, 8.1.x

#34645 Improve FeatureFlagManager ServiceLocator
  src/Core/FeatureFlag/FeatureFlagManager.php
  src/Core/FeatureFlag/Layer/DbLayer.php
  src/Core/FeatureFlag/Layer/DotEnvLayer.php
  src/Core/FeatureFlag/Layer/EnvLayer.php
  src/Core/FeatureFlag/Layer/QueryLayer.php
  src/Core/FeatureFlag/TypeLayerInterface.php
  src/PrestaShopBundle/Resources/config/services/core/feature_flag.yml
Labels: Improvement, develop

#34661 Functional Tests : Theme Customization module - Advanced Customization tab
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/13_checkProductImageFormat.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/14_checkCategoryImageFormat.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/15_checkStoreImageFormat.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/16_checkBaseImageFormat.ts
  tests/UI/campaigns/modules/ps_themecusto/02_configuration/02_advancedCustomizationTab.ts
  tests/UI/pages/BO/design/themeAndLogo/advancedCustomization/index.ts
  tests/UI/utils/files.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#34663 Functional Tests : Theme Customization module - Reset module
  tests/UI/campaigns/modules/ps_themecusto/01_installation/04_resetModule.ts
  tests/UI/data/demo/modules.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#34662 Functional tests - Add new test 'Administration > Check quota'
  tests/UI/campaigns/functional/BO/14_advancedParameters/03_administration/02_uploadQuota.ts
  tests/UI/data/faker/file.ts
  tests/UI/pages/BO/advancedParameters/administration/index.ts
  tests/UI/pages/BO/catalog/files/add.ts
  tests/UI/pages/BO/catalog/products/add/descriptionTab.ts
  tests/UI/pages/BO/catalog/products/add/virtualProductTab.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34690 Functional tests - Fix nightly 'BO > Advanced parameters > Administration> Update quota'
  tests/UI/pages/BO/catalog/products/add/virtualProductTab.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34653 Type protected and private methods of legacy admin controllers
  controllers/admin/AdminAccessController.php
  controllers/admin/AdminCarrierWizardController.php
  controllers/admin/AdminCarriersController.php
  controllers/admin/AdminCartRulesController.php
  controllers/admin/AdminCustomerThreadsController.php
  controllers/admin/AdminGroupsController.php
  controllers/admin/AdminImagesController.php
  controllers/admin/AdminModulesController.php
  controllers/admin/AdminProductsController.php
  controllers/admin/AdminSearchController.php
  controllers/admin/AdminStoresController.php
  controllers/admin/AdminTaxRulesGroupController.php
  controllers/admin/AdminTranslationsController.php
Labels: QA ✔️, develop, Refactoring, BC break, Needs documentation

#34521 Remove extra checks
  classes/Attachment.php
  classes/AttributeGroup.php
  classes/CMSCategory.php
  classes/Carrier.php
  classes/Category.php
  classes/Currency.php
  classes/Feature.php
  classes/Language.php
  classes/Manufacturer.php
  classes/Message.php
  classes/Meta.php
  classes/ObjectModel.php
  classes/PrestaShopBackup.php
  classes/Product.php
  classes/Search.php
  classes/Tools.php
  classes/webservice/WebserviceRequest.php
  tests/UI/data/demo/modules.ts
Labels: QA ✔️, develop, Refactoring, BC break

#34498 Remove calls to get products properties
  classes/Category.php
  classes/Manufacturer.php
  classes/Pack.php
  classes/Product.php
  classes/ProductAssembler.php
  classes/ProductSale.php
  classes/Search.php
  classes/Supplier.php
  classes/controller/ProductListingFrontController.php
  classes/order/OrderDetail.php
  controllers/front/ProductController.php
Labels: Waiting for QA, develop, Refactoring, BC break, Needs documentation

#34716 Merge 8.1.x into develop
  classes/Cart.php
  classes/CartRule.php
  classes/Product.php
  classes/order/Order.php
  controllers/admin/AdminSpecificPriceRuleController.php
  controllers/front/ProductController.php
  src/Adapter/Product/Combination/Update/CombinationStockUpdater.php
  src/PrestaShopBundle/Resources/config/services/adapter/product/_combination.yml
Labels: QA ✔️, develop

#34695 Better validate availability date
  src/Adapter/Presenter/Product/ProductLazyArray.php
Labels: QA ✔️, Bug fix, 8.1.x
