Repository PrestaShop/PrestaShop, pull requests merged in 2023-03, with the labels that each got.

#31472 Fix "generate for all shops" button visibility when multiShop is off
  admin-dev/themes/new-theme/js/pages/product/combination/generator/CombinationGenerator.vue
  admin-dev/themes/new-theme/js/pages/product/combination/generator/index.ts
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationManagerType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/FormTheme/combination.html.twig
Labels: QA ✔️, Bug fix, 8.1.x

#31580 CI : Nightly : Fixed uses of secrets in composite action
  .github/workflows/cron_nightly_tests_8.0.x.yml
  .github/workflows/cron_nightly_tests_8.1.x.yml
  .github/workflows/cron_nightly_tests_develop.yml
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#31591 Functional Tests : Splits Tests in small packages
  tests/UI/package.json
Labels: Improvement, QA ✔️, TE, E2E Tests

#31592 Functional Tests : Splits Tests in small packages
  tests/UI/package.json
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#31573 Functional tests - Add new test 'BO > CRUD features and values'
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/01_CRUDFeaturesAndValues.ts
  tests/UI/pages/BO/catalog/features/addValue.ts
  tests/UI/pages/BO/catalog/features/editFeature.ts
  tests/UI/pages/BO/catalog/features/index.ts
  tests/UI/pages/BO/catalog/features/view.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#31598 CI : Nightly : Added type for each input
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#31590 Functional tests - Add new test 'BO > Orders > Shopping carts > Export shopping carts'
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/04_exportCarts.ts
  tests/UI/data/types/shoppingCart.d.ts
  tests/UI/pages/BO/orders/shoppingCarts/index.ts
  tests/UI/utils/date.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#31628 Fix Sanity Product V2 tests blocking CI
  .github/workflows/sanity-productV2.yml
  .github/workflows/skip-sanity-productV2.yml
Labels: develop, Bug fix

#31629 CI : Nightly : Force the push of reports even if there are jobs in error
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: TE, develop, Bug fix, E2E Tests

#31632 Functional Tests : Add the script `test:functional:productV2`
  tests/UI/package.json
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#31635 CI : UI Tests (Ignore Sanity PPV2 in some paths)
  .github/workflows/sanity-productV2-skip.yml
Labels: Improvement, QA ✔️, TE, E2E Tests

#31631 Functional Tests : Add the script `test:functional:productV2`
  tests/UI/package.json
Labels: QA ✔️, TE, Bug fix, E2E Tests, 8.1.x

#31608 Functional tests - Refacto 'BO > Catalog > CRUD cart rule with & without code'
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/01_withAndWithoutCode.ts
  tests/UI/pages/FO/cart/index.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#31634 CI : UI Tests (Ignore Sanity PPV2 in some paths)
  .github/workflows/sanity-productV2-skip.yml
  .github/workflows/sanity-productV2.yml
Labels: Improvement, QA ✔️, TE, 8.0.x, E2E Tests

#31655 CI : UI Tests (Fixed typo)
  .github/workflows/sanity-productV2-skip.yml
  .github/workflows/sanity-productV2.yml
Labels: Improvement, TE, 8.0.x, E2E Tests

#31296 Update summary quantity on combination list refresh
  admin-dev/themes/new-theme/js/fos_js_routes.json
  admin-dev/themes/new-theme/js/pages/product/edit/index.ts
  admin-dev/themes/new-theme/js/pages/product/edit/summary-quantity-updater.ts
  admin-dev/themes/new-theme/js/pages/product/product-map.ts
  admin-dev/themes/new-theme/js/pages/product/service/product.ts
  src/Adapter/Product/Combination/Create/CombinationCreator.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/product_v2/product.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/header-details.html.twig
Labels: QA ✔️, Bug fix, 8.1.x

#31102 Functional Tests : API - Basic Test
  tests/UI/campaigns/functional/API/01_basicTest.ts
  tests/UI/package.json
Labels: Improvement, QA ✔️, TE, E2E Tests, 8.1.x

#31654 Fix addslashes not working
  config/smartyadmin.config.inc.php
Labels: QA ✔️, 8.0.x, Bug fix

#31661 CI : Nightly : Added `BO:dashboard` & `API`
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: Improvement, QA ✔️, TE, develop, Bug fix, E2E Tests

#31568 Fix virtual product file constraints
  src/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/VirtualProductFileListener.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/VirtualProductFileType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_extension.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  tests/Integration/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/CombinationListenerTest.php
  tests/Integration/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/FeatureValueListenerTest.php
  tests/Integration/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/ProductTypeListenerTest.php
  tests/Integration/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/RedirectOptionListenerTest.php
  tests/Integration/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/VirtualProductFileListenerTest.php
  tests/Integration/PrestaShopBundle/Form/FormListenerTestCase.php
Labels: QA ✔️, Bug fix, 8.1.x

#31671 Functional tests - Delete the test of best sellers block in home page
  tests/UI/campaigns/functional/FO/06_homePage/02_displaySomeProducts.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#31667 Catch PrestaShopException to validate sql-requests properly in PHP 8.X
  src/Adapter/SqlManager/SqlQueryValidator.php
Labels: QA ✔️, 8.0.x, Bug fix

#31563 Limit the size of changelog for module updates
  admin-dev/themes/new-theme/scss/theme.scss
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/card_list.html.twig
Labels: Improvement, QA ✔️, develop

#30957 Redirect to product list with warning message instead of raising an exception when we try to access a product which doesn't exist
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/preview.html.twig
Labels: QA ✔️, 8.0.x, Bug fix, Wording ✔️

#31418 Remove ModuleRepository and ModuleRepositoryFactory
  src/PrestaShopBundle/Kernel/ModuleRepository.php
  src/PrestaShopBundle/Kernel/ModuleRepositoryFactory.php
  src/PrestaShopBundle/Resources/config/services/bundle/repository.yml
Labels: Improvement, QA ✔️, develop, BC break

#31682 Cast `featureId` into int to fix `InvalidFeatureIdException`
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureController.php
Labels: QA ✔️, Bug fix

#31571 Fix error Uncaught TypeError: abs() in CartController
  controllers/front/CartController.php
Labels: QA ✔️, develop, Bug fix

#31688 Add avif to htaccess allowed formats
  img/.htaccess
Labels: Waiting for QA, Bug fix, Refactoring, Waiting for dev

#27912 Refactor AdminModulesControllers and remove obsolete features
  admin-dev/themes/default/js/admin-theme.js
  admin-dev/themes/default/template/controllers/modules/configuration_bar.tpl
  admin-dev/themes/default/template/controllers/modules/configure.tpl
  admin-dev/themes/default/template/controllers/modules/content-legacy.tpl
  admin-dev/themes/default/template/controllers/modules/favorites.tpl
  admin-dev/themes/default/template/controllers/modules/filters.tpl
  admin-dev/themes/default/template/controllers/modules/js.tpl
  admin-dev/themes/default/template/controllers/modules/list.tpl
  admin-dev/themes/default/template/controllers/modules/page.tpl
  admin-dev/themes/default/template/controllers/modules/page_header_toolbar-legacy.tpl
  admin-dev/themes/default/template/controllers/modules/quickview.tpl
  admin-dev/themes/default/template/controllers/modules/readmore-body.tpl
  admin-dev/themes/default/template/controllers/modules/readmore-header.tpl
  admin-dev/themes/default/template/controllers/modules/tab_module_line.tpl
  admin-dev/themes/default/template/controllers/modules/tab_modules_list.tpl
  admin-dev/themes/default/template/controllers/modules/warning_module.tpl
  admin-dev/themes/default/template/header.tpl
  admin-dev/themes/default/template/page_header_toolbar.tpl
  admin-dev/themes/default/template/toolbar.tpl
  admin-dev/themes/new-theme/template/header.tpl
  classes/Tab.php
  classes/controller/AdminController.php
  classes/module/Module.php
  config/defines_uri.inc.php
  controllers/admin/AdminCarriersController.php
  controllers/admin/AdminModulesController.php
  controllers/admin/AdminSearchController.php
  js/admin.js
  js/admin/addons.js
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/tab-module-line.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/tab-modules-list.html.twig
Labels: Improvement, QA ✔️, develop, BC break, Needs documentation

#31353 Add QS to some of the back office assets to force cache clearance
  classes/controller/AdminController.php
  src/PrestaShopBundle/Bridge/AdminController/LegacyControllerBridge.php
Labels: Improvement, QA ✔️, develop

#31702 (ui-test) Fix AfterEach to not fail trying to take a screenshot
  tests/UI/utils/helpers.ts
  tests/UI/utils/setup.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#31692 Corrects some CORE wordings
  admin-dev/themes/default/template/controllers/images/modal_confirm_delete_type.tpl
  admin-dev/themes/default/template/controllers/images/modal_regenerate_thumbnails.tpl
  admin-dev/themes/default/template/controllers/login/content.tpl
  admin-dev/themes/new-theme/template/layout.tpl
  classes/controller/AdminController.php
  classes/lang/KeysReference/FeatureFlagLang.php
  controllers/admin/AdminAttributesGroupsController.php
  controllers/admin/AdminCarrierWizardController.php
  controllers/admin/AdminCarriersController.php
  controllers/admin/AdminCountriesController.php
  controllers/admin/AdminFeaturesController.php
  controllers/admin/AdminGroupsController.php
  controllers/admin/AdminLoginController.php
  controllers/admin/AdminStoresController.php
  controllers/admin/AdminSuppliersController.php
  controllers/admin/AdminTaxRulesGroupController.php
  controllers/front/PasswordController.php
  install-dev/data/xml/feature_flag.xml
  src/Adapter/Presenter/Product/ProductLazyArray.php
  src/Core/Domain/CustomerService/CommandHandler/ReplyToCustomerThreadHandler.php
  src/Core/Domain/CustomerService/CommandHandler/UpdateCustomerThreadStatusHandler.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AuthorizationServer/ApplicationController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/ContactsController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/StateController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ImageController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/SupplierController.php
  src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/CustomerThreadController.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Email/EmailConfigurationType.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Employee/EmployeeType.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/RequestSql/SqlRequestSettingsType.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Webservice/WebserviceKeyType.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/Contact/ContactType.php
  src/PrestaShopBundle/Form/Admin/Improve/Design/Pages/CmsPageCategoryType.php
  src/PrestaShopBundle/Form/Admin/Improve/Design/Pages/CmsPageType.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Currencies/CurrencyType.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Language/LanguageType.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Locations/CountryType.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Locations/ZoneType.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Tax/TaxRulesGroupType.php
  src/PrestaShopBundle/Form/Admin/Sell/Manufacturer/ManufacturerType.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/Invoices/InvoiceOptionsType.php
  src/PrestaShopBundle/Form/Admin/Sell/Supplier/SupplierType.php
  src/PrestaShopBundle/Resources/views/Admin/Multistore/dropdown.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Multistore/header.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Multistore/product_header.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Features/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/multishop.html.twig
  tests/Integration/Adapter/Presenter/Product/ProductLazyArrayTest.php
Labels: Improvement

#31707 Update composer.lock for modules contactform and ps_contactinfo
  composer.lock
Labels: Improvement, 8.0.x

#31508 Fix errors when submitting empty feature or feature values ppv2
  admin-dev/themes/new-theme/js/pages/product/edit/manager/feature-values-manager.ts
  src/PrestaShopBundle/Form/Admin/Sell/Product/Details/FeatureValueType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/FeatureValueListener.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  tests/Integration/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/FeatureValueListenerTest.php
Labels: QA ✔️, Bug fix, Wording ✔️, 8.1.x

#31695 Do not enable add to cart button if catalog mode is enabled
  src/Adapter/Presenter/Product/ProductLazyArray.php
Labels: QA ✔️, Bug fix

#31710 Fix nightly 10-03 - 'BO > Orders > View invoice'
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/11_checkInvoice.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests, 8.1.x

#31718 Fix nightly 8.0.x - 'BO > Orders > Check invoice'
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/11_checkInvoice.js
Labels: QA ✔️, TE, 8.0.x, Refactoring, E2E Tests

#31703 Add validation rule to avoid special characters in virtual urls
  controllers/admin/AdminShopUrlController.php
Labels: QA ✔️, develop, Bug fix

#31716 Update disallowed calls
  phpstan-disallowed-calls.neon
Labels: Improvement, develop

#31723 Fix nightly Develop - 'BO > Customers > View customer'
  tests/UI/campaigns/functional/BO/04_customers/01_customers/08_viewCustomer.ts
  tests/UI/pages/BO/customers/view.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#31279 Fix errors en customer email field for registration form in FO and BO
  classes/Validate.php
  src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php
Labels: QA ✔️, Waiting for wording, 8.0.x, Bug fix

#31736 Improve LinkColumn phpdoc
  src/Core/Grid/Column/Type/Common/LinkColumn.php
Labels: Improvement, develop

#31701 Functional tests - Add new test 'BO > CRUD cart rules > Enable/disable partial use'
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/02_enableDisablePartialUse.ts
  tests/UI/pages/BO/catalog/discounts/add.ts
  tests/UI/pages/FO/checkout/index.ts
  tests/UI/pages/FO/myAccount/vouchers.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests, 8.1.x

#31687 Functional Tests : CLDR - Enable/Disable a currency
  tests/UI/campaigns/cldr/09_enableDisableCurrency.ts
  tests/UI/package.json
  tests/UI/pages/BO/international/currencies/index.ts
  tests/UI/pages/BO/international/localization/localizationBasePage.ts
Labels: Improvement, QA ✔️, TE, E2E Tests, 8.1.x

#31714 Functional Tests : Workaround until #29813
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#31753 Merge 8.0.x 8.1.x 13/03/23
  classes/Validate.php
  classes/controller/AdminController.php
  classes/helper/Helper.php
  composer.lock
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/preview.html.twig
Labels: Bug fix

#31754 Correct translation domain names to standardize
  src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/MerchandiseReturnController.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Image/ImageDropzoneType.php
Labels: Improvement, Waiting for QA

#27769 Proper guest management in backoffice
  admin-dev/themes/new-theme/js/pages/customer/CustomerForm.ts
  admin-dev/themes/new-theme/js/pages/customer/customer-form-map.ts
  src/Core/Form/IdentifiableObject/DataHandler/CustomerFormDataHandler.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
  src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/create.html.twig
Labels: QA ✔️, develop, Feature, Bug fix, Wording ✔️

#31757 Changelog 8.0.2
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: Improvement, 8.0.x

#31560 Duplicate product for multishop final part
  src/Adapter/Product/Image/Repository/ProductImageMultiShopRepository.php
  src/Adapter/Product/Update/ProductDuplicator.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_image.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/CombinationAssertionFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/CombinationListingFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/GenerateCombinationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/UpdateCombinationStockFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/DuplicateProductFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/ShippingAssertionFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/SpecificPricePrioritiesFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/StockAssertionFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateCustomizationFieldsFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateProductFeatureValuesFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/VirtualProductFileFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/duplicate_product_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/VirtualProductFile/add_virtual_product_file.feature
  tests/Integration/Behaviour/Features/Scenario/Product/VirtualProductFile/update_virtual_product_file.feature
  tests/Integration/Behaviour/Features/Scenario/Product/bulk_duplicate_product.feature
  tests/Integration/Behaviour/Features/Scenario/Product/duplicate_product.feature
  tests/Resources/DummyFileUploader.php
  tests/Resources/Resetter/ProductResetter.php
Labels: Improvement, QA ✔️

#31511 Fix exception 'Template ::base.html.twig is not defined'
  src/PrestaShopBundle/Resources/views/Admin/Exception/error.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Exception/not_found.html.twig
Labels: QA ✔️, develop, Bug fix

#31722 Add `force_hide_bulk_actions_btn` in HelperList for AdminCartsController.php
  admin-dev/themes/default/template/helpers/list/list_footer.tpl
  classes/helper/HelperList.php
  controllers/admin/AdminCartsController.php
Labels: QA ✔️, Bug fix

#31647 Prevent email enumeration
  classes/Employee.php
Labels: Improvement, QA ✔️, 8.0.x

#31783 Functional Tests : ps_linklist : Fixed selector for the language selector
  tests/UI/pages/BO/design/linkWidgets/add.ts
Labels: TE, develop, Bug fix, E2E Tests

#31772 Fix wordings in BO for keys WS
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceController.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Webservice/WebserviceKeyType.php
Labels: QA ✔️, 8.0.x, Bug fix

#31739 Delete jquery-passy.LICENSE
  admin-dev/themes/default/js/vendor/jquery-passy.LICENSE
Labels: Improvement, QA ✔️, Waiting for dev

#31787 Installer : Fixed link to docs in Installer
  tools/build/doc/Install_PrestaShop.html
Labels: 8.0.x, Bug fix

#31762 Functional tests - Add 2 tests 'BO > Cart rule > Check priority and disabled status'
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule.ts
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/01_information/01_withAndWithoutCode.ts
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/01_information/02_enableDisablePartialUse.ts
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/01_information/03_priority.ts
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/01_information/04_disableStatus.ts
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/02_condition/09_checkTotalAvailable.ts
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/02_condition/10_countryRestriction.ts
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/02_condition/11_carrierRestriction.ts
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/02_condition/12_groupCustomerRestriction.ts
  tests/UI/pages/FO/cart/index.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#31657 Clean product & combination command builders
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/CarriersCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationCommandsBuilderInterface.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationImagesCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationSuppliersCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/MultiShopCombinationCommandsBuilderInterface.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/UpdateCombinationCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/UpdateCombinationStockAvailableCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/CustomizationFieldsCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/FeatureValuesCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/MultiShopProductCommandsBuilderInterface.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/PackedProductsCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductAttachmentsCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCategoriesCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandsBuilderInterface.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductStockAvailableCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductSuppliersCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/RelatedProductsCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/SpecificPricePriorityCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/TagsCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/TypeCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/UpdateProductCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/VirtualProductFileCommandsBuilder.php
  src/Core/Form/IdentifiableObject/DataHandler/BulkCombinationFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/CombinationFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/CombinationListFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/ProductFormDataHandler.php
  src/PrestaShopBundle/Resources/config/services/core/form/command_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_handler.yml
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationImagesCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/CombinationSuppliersCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/FeatureValuesCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/PackedProductsCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductAttachmentsCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductSuppliersCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/RelatedProductsCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/SpecificPricePriorityCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/TagsCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/TypeCommandBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/VirtualProductFileCommandsBuilderTest.php
Labels: QA ✔️, Refactoring, 8.1.x

#31786 Merge 8.1.x to develop 14/03/23
  admin-dev/themes/default/template/helpers/list/list_footer.tpl
  classes/helper/HelperList.php
  controllers/admin/AdminCartsController.php
  controllers/front/SitemapController.php
  src/Adapter/Product/Image/Repository/ProductImageMultiShopRepository.php
  src/Adapter/Product/Update/ProductDuplicator.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_image.yml
  src/PrestaShopBundle/Resources/views/Admin/Exception/error.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Exception/not_found.html.twig
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/CombinationAssertionFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/CombinationListingFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/GenerateCombinationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/UpdateCombinationStockFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/DuplicateProductFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/ShippingAssertionFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/SpecificPricePrioritiesFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/StockAssertionFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateCustomizationFieldsFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateProductFeatureValuesFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/VirtualProductFileFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/duplicate_product_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/VirtualProductFile/add_virtual_product_file.feature
  tests/Integration/Behaviour/Features/Scenario/Product/VirtualProductFile/update_virtual_product_file.feature
  tests/Integration/Behaviour/Features/Scenario/Product/bulk_duplicate_product.feature
  tests/Integration/Behaviour/Features/Scenario/Product/duplicate_product.feature
  tests/Resources/DummyFileUploader.php
  tests/Resources/Resetter/ProductResetter.php
  tests/UI/README.md
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/01_internalAuthServer/02_resourceEndpoint.ts
  tests/UI/types/global.d.ts
  tests/UI/utils/api.ts
  tests/UI/utils/globals.ts
Labels: Improvement, develop

#31800 Replace non existent steps with their replacement
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/duplicate_product_multishop.feature
Labels: Bug fix, 8.1.x

#31770 Removed deprecated method `Translate::getAdminTranslation`
  admin-dev/functions.php
  classes/Translate.php
  classes/helper/HelperShop.php
  controllers/admin/AdminCountriesController.php
  controllers/admin/AdminTranslationsController.php
Labels: QA ✔️, develop, Refactoring, BC break

#31776 Remove command handler definition that was removed
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
Labels: Bug fix

#31808 Functional Tests : API : Authorization Endpoint
  tests/UI/campaigns/functional/API/01_basicTest.ts
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/01_internalAuthServer/01_authorizationEndpoint.ts
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/01_internalAuthServer/02_resourceEndpoint.ts
Labels: Improvement, QA ✔️, TE, E2E Tests

#31676 Functional Tests : BO - Design - Image Settings - Image Generation options
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/09_imageGenerationOptions.ts
  tests/UI/pages/BO/advancedParameters/featureFlag/index.ts
  tests/UI/pages/BO/design/imageSettings/index.ts
  tests/UI/pages/commonPage.ts
Labels: Improvement, QA ✔️, TE, E2E Tests

#31804 Nightly : Added CLDR
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#31824 No need to check error_get_last exist it exists since PHP 5.2
  config/alias.php
Labels: Improvement, develop

#31829 Remove broken crowdin badge
  README.md
Labels: Improvement, develop

#31818 Functional Tests : CLDR - Edit symbol / format currency
  tests/UI/campaigns/cldr/07_editSymbolFormatCurrency.ts
  tests/UI/data/faker/currency.ts
  tests/UI/data/types/currency.d.ts
  tests/UI/pages/BO/international/currencies/add.ts
Labels: Improvement, QA ✔️, TE, E2E Tests

#31674 Add `_legacy_feature_flag` for customer threads routes
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer_service/customer_threads.yml
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/01_viewCustomerService.ts
  tests/UI/campaigns/functional/BO/15_header/08_checkNotifications.ts
  tests/UI/campaigns/functional/FO/05_contactUs/04_addAttachment.ts
  tests/UI/campaigns/productV2/sanity/03_CRUDProductWithCombinations.ts
  tests/UI/pages/BO/customerService/customerService/view.ts
Labels: QA ✔️, Bug fix

#31855 Refactor product stock update
  src/Adapter/Product/Combination/CommandHandler/UpdateCombinationStockAvailableHandler.php
  src/Adapter/Product/Combination/Update/CombinationStockProperties.php
  src/Adapter/Product/Combination/Update/CombinationStockUpdater.php
  src/Adapter/Product/Stock/CommandHandler/UpdateProductStockAvailableHandler.php
  src/Adapter/Product/Stock/Update/ProductStockProperties.php
  src/Adapter/Product/Stock/Update/ProductStockUpdater.php
  src/Adapter/Product/Update/ProductDuplicator.php
  src/Adapter/Product/Update/ProductShopUpdater.php
Labels: Refactoring

#31858 Add Sponsor company into issue template
  .github/ISSUE_TEMPLATE/1_bug_report.yml
Labels: Improvement, develop

#31823 Disable legacy_feature_flag for migrated feature page
  classes/lang/KeysReference/FeatureFlagLang.php
  install-dev/data/xml/feature_flag.xml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/features.yml
Labels: QA ✔️, Bug fix

#31584 Footer UX improvements
  admin-dev/themes/default/template/header.tpl
  admin-dev/themes/new-theme/js/app/utils/watch-symfony-debug-bar.ts
  admin-dev/themes/new-theme/js/pages/product/edit/product-partial-updater.ts
  admin-dev/themes/new-theme/js/theme.ts
  admin-dev/themes/new-theme/scss/pages/product/product_page.scss
  admin-dev/themes/new-theme/template/layout.tpl
  admin-dev/themes/new-theme/template/light_display_layout.tpl
  src/PrestaShopBundle/Form/Admin/Sell/Product/FooterType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/HeaderType.php
  src/PrestaShopBundle/Form/Admin/Type/ButtonCollectionType.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/footer.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
  tests/UI/pages/BO/catalog/productsV2/add/index.ts
Labels: Improvement, QA ✔️

#31885 Final multishop fields that needed to be renamed
  src/Adapter/Product/Combination/Update/CombinationDeleter.php
  src/Adapter/Product/ProductDeleter.php
Labels: Refactoring

#31825 Improve smartyClassname()
  config/smarty.config.inc.php
Labels: Improvement, Waiting for QA, develop, Waiting for dev

#31811 Deprecate PS1.6 product list colors + formatting
  classes/Product.php
  classes/Tools.php
  classes/controller/FrontController.php
Labels: Improvement

#31845 Functional tests - Add some new tests on 'FO > Navigation and display'
  tests/UI/campaigns/functional/FO/08_menuAndNavigation/01_navigateInCategories/01_consultCategoriesInHeader.ts
  tests/UI/campaigns/functional/FO/08_menuAndNavigation/02_sortAndFilter/01_sortProducts.ts
  tests/UI/campaigns/functional/FO/08_menuAndNavigation/03_navigationAndDisplay/01_displayTags.ts
  tests/UI/campaigns/functional/FO/08_menuAndNavigation/03_navigationAndDisplay/02_pagination.ts
  tests/UI/campaigns/functional/FO/08_menuAndNavigation/03_navigationAndDisplay/03_quickViewProducts.ts
  tests/UI/campaigns/functional/FO/08_menuAndNavigation/03_navigationAndDisplay/04_displayOnSaleFlag.ts
  tests/UI/commonTests/BO/catalog/product.ts
  tests/UI/data/demo/products.ts
  tests/UI/data/faker/product.ts
  tests/UI/data/types/product.d.ts
  tests/UI/pages/BO/catalog/products/add.ts
  tests/UI/pages/BO/catalog/products/index.ts
  tests/UI/pages/FO/category/index.ts
  tests/UI/pages/FO/product/index.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#31764 Removed deprecated file `admin-dev/get-file-admin.php`
  admin-dev/get-file-admin.php
  classes/ProductDownload.php
  classes/order/OrderHistory.php
  src/Adapter/Presenter/Order/OrderLazyArray.php
Labels: Waiting for QA, develop, Refactoring, BC break, Waiting for dev

#31766 Removed deprecated class linked to FileUpload
  classes/FileUploader.php
  classes/QqUploadedFileForm.php
  classes/QqUploadedFileXhr.php
Labels: Waiting for QA, develop, Refactoring, BC break, Waiting for dev

#31769 Removed deprecated method Tools::isBright
  admin-dev/themes/default/template/helpers/list/list_content.tpl
  classes/Tools.php
  config/smartyadmin.config.inc.php
Labels: Waiting for QA, develop, Refactoring, BC break, Waiting for dev

#31865 Merge 80x 81x 2103
  CONTRIBUTORS.md
  classes/Employee.php
  controllers/admin/AdminLoginController.php
  docs/CHANGELOG.txt
  install-dev/theme/views/license.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceController.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Webservice/WebserviceKeyType.php
  src/PrestaShopBundle/Resources/config/services/bundle/services.yml
  src/PrestaShopBundle/Security/Admin/SessionRenewer.php
  tests/Integration/PrestaShopBundle/Admin/Security/SessionRenewerTest.php
  tools/build/doc/Install_PrestaShop.html
Labels: Bug fix

#31820 Handle custom lock file during the cache clear and force module actions one by one
  admin-dev/themes/new-theme/js/components/module-card.ts
  admin-dev/themes/new-theme/js/pages/module/controller.js
  app/AppKernel.php
  classes/Tools.php
  src/Adapter/Cache/Clearer/SymfonyCacheClearer.php
  src/Core/Module/EventSubscriber.php
  src/Core/Module/ModuleManager.php
  src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php
  src/PrestaShopBundle/Event/ModuleManagementEvent.php
  src/PrestaShopBundle/Resources/views/Admin/Module/common.html.twig
Labels: QA ✔️, Waiting for wording, 8.0.x, Bug fix

#31902 Remove cache clear lock file after it is not needed
  app/AppKernel.php
Labels: Improvement, QA ✔️, 8.0.x

#31909 Bump prestashop to 8.0.3 patch version
  app/AppKernel.php
  install-dev/install_version.php
Labels: Improvement, 8.0.x

#31074 Fix and unify sort orders in default search providers
  src/Adapter/BestSales/BestSalesProductSearchProvider.php
  src/Adapter/Category/CategoryProductSearchProvider.php
  src/Adapter/Manufacturer/ManufacturerProductSearchProvider.php
  src/Adapter/NewProducts/NewProductsProductSearchProvider.php
  src/Adapter/PricesDrop/PricesDropProductSearchProvider.php
  src/Adapter/Search/SearchProductSearchProvider.php
  src/Adapter/Supplier/SupplierProductSearchProvider.php
  src/Core/Product/Search/SortOrdersCollection.php
Labels: QA ✔️, develop, Refactoring

#31907 Bump module ps_distributionapiclient
  composer.lock
Labels: Improvement, 8.0.x

#31913 Bump symfony version
  composer.lock
Labels: Improvement, 8.0.x

#28988 Remove deprecated in Core namespace
  composer.lock
  src/Core/Domain/Customer/ValueObject/Email.php
  src/Core/Product/ProductListingPresenter.php
  src/Core/Product/ProductPresenter.php
  src/Core/Product/Search/SortOrderFactory.php
  src/Core/Product/Search/URLFragmentSerializer.php
  tests/Unit/Core/Product/Search/URLFragmentSerializerTest.php
Labels: Waiting for QA, develop, Refactoring, BC break, Needs documentation

#31889 Removed deprecated method `addJquery` in `Controller` class
  classes/Media.php
  classes/controller/Controller.php
Labels: Improvement, QA ✔️, develop, BC break

#31923 Use assertSame instead of assertEquals when type must match in ThemeTest
  tests/Unit/Core/Addon/Theme/ThemeTest.php
Labels: Improvement, develop

#31916 Add language warning to issue template
  .github/ISSUE_TEMPLATE/1_bug_report.yml
Labels: develop, Refactoring

#31893 Removed deprecated controller `AdminRequestSqlController`
  controllers/admin/AdminRequestSqlController.php
Labels: Improvement, develop, BC break

#31892 Removed deprecated methods `generateDeliverySlipPDFByIdOrder` & `generateInvoicePDFByIdOrder` in class `AdminPdfController`
  controllers/admin/AdminPdfController.php
Labels: Improvement, QA ✔️, develop, BC break

#31891 Removed deprecated methods `stripslashes` & `safePostVars` in class `Tools`
  classes/Tools.php
  src/PrestaShopBundle/Bridge/Smarty/HeaderConfigurator.php
Labels: Improvement, QA ✔️, develop, BC break

#31576 Ignore non existing product while importing by reference
  controllers/admin/AdminImportController.php
Labels: Improvement, QA ✔️, develop, Wording ✔️

#31946 Nightly : Remove `service_account_key has been deprecated`
  .github/workflows/cron_nightly_build.yml
  .github/workflows/cron_nightly_gcp.yml
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: Improvement, QA ✔️, develop

#31531 Standardize `filterManufacturerContent` hook
  controllers/front/listing/ManufacturerController.php
Labels: Improvement, QA ✔️, develop, BC break, Needs documentation

#31960 Nightly : Fixed `FO/08*/02*/01*` & `productV2/functional/03*`
  tests/UI/pages/BO/catalog/productsV2/add/combinationsTab.ts
  tests/UI/pages/FO/category/index.ts
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#31729 Use index for connections.date_add
  controllers/admin/AdminCartsController.php
Labels: QA ✔️, develop, Bug fix, Refactoring

#31956 Nightly : Fixed Auth Cloud SDK use of secrets
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: TE, develop, Bug fix, E2E Tests

#31959 Merge 8.0.x into 8.1.x
  admin-dev/themes/new-theme/js/components/module-card.ts
  admin-dev/themes/new-theme/js/pages/module/controller.js
  app/AppKernel.php
  classes/Tools.php
  composer.lock
  src/Adapter/Cache/Clearer/SymfonyCacheClearer.php
  src/Core/Module/EventSubscriber.php
  src/Core/Module/ModuleManager.php
  src/PrestaShopBundle/Event/ModuleManagementEvent.php
  src/PrestaShopBundle/Resources/views/Admin/Module/common.html.twig
  tests/UI/campaigns/functional/FO/06_homePage/01_checkSlider.ts
  tests/UI/data/demo/moduleCategories.ts
Labels: Improvement

#31300 Mitigate multiple function call CartPresenter::present
  src/Adapter/Presenter/Cart/CartPresenter.php
Labels: QA ✔️, develop, Bug fix

#31752 Fix ProductCore::getDefaultCategory to return an int consistently
  classes/Product.php
Labels: Waiting for QA, develop, Bug fix, BC break, Waiting for dev

#31487 FO: Fix cart rule detail amount
  classes/CartRule.php
Labels: QA ✔️, develop, Bug fix

#28854 Improve StockManager queries performances
  src/Adapter/StockManager.php
Labels: Improvement, develop

#31986 Update Code of Conduct to follow #173
  CODE_OF_CONDUCT.md
Labels: Improvement, develop

#31990 Remove deprecated hook in Behat Tests
  tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php
Labels: Improvement, develop
