Repository PrestaShop/PrestaShop, pull requests merged in 2023-10, with the labels that each got.

#34115 Fix wrong license in modules/index.php
  modules/index.php
Labels: Improvement, Waiting for QA, develop, Hacktoberfest

#34123 Nightly : Move `skip` to method in UI Tests
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/02_externalAuthServer/01_authorizationEndpoint.ts
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/02_externalAuthServer/02_resourceEndpoint.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/11_checkInvoice.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/11_imageGenerationOnCreation.ts
  tests/UI/campaigns/functional/FO/classic/03_userAccount/04_getGDPRDataInPDF.ts
  tests/UI/campaigns/functional/WS/02_productsCRUD.ts
  tests/UI/campaigns/modules/blockwishlist/02_configuration/02_statisticsTabSettings.ts
  tests/UI/campaigns/productV2/functional/11_combinationTab.ts
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#34121 Change prestashop.com to prestashop-project.org in .htaccess
  classes/Tools.php
Labels: Improvement, QA ✔️, develop

#34153 Fix feature values export
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureValueController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/features.yml
Labels: QA ✔️, develop, Bug fix

#34135 Functional tests - Add new test to check 'BO > Product V2 > Options tab'
  tests/UI/campaigns/productV2/functional/20_optionsTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/optionsTab.ts
Labels: TE, develop, Refactoring, E2E Tests

#34144 Functional Tests : BO - Catalog - Products : Stocks tab
  tests/UI/campaigns/productV2/functional/15_stocksTab.ts
  tests/UI/data/xml/product.ts
  tests/UI/pages/BO/catalog/productsV2/add/stocksTab.ts
  tests/UI/pages/BO/catalog/stocks/movements/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#34179 Functional tests - Fix the max length of the faker value for alias address
  tests/UI/data/faker/address.ts
  tests/UI/data/import/addresses.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34171 Integrate external PrestaShop module for API resources
  .gitignore
  admin-dev/bundles/apiplatform
  app/AppKernel.php
  app/config/config.yml
  app/config/security_test.yml
  composer.json
  composer.lock
  src/Adapter/Cache/Clearer/SymfonyCacheClearer.php
  src/Adapter/Container/ContainerParametersExtension.php
  src/Adapter/ContainerBuilder.php
  src/Adapter/Module/Repository/ModuleRepository.php
  src/Adapter/Product/QueryHandler/SearchProductsHandler.php
  src/Core/Module/EventSubscriber.php
  src/PrestaShopBundle/DependencyInjection/Compiler/LoadServicesFromModulesPass.php
  src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php
  src/PrestaShopBundle/DependencyInjection/PrestaShopExtension.php
  src/PrestaShopBundle/Entity/FeatureFlag.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/AuthorizationServer/ApiAccess/index.html.twig
Labels: develop, Feature

#34159 Functional Tests : BO - Catalog - Products list : Filter & Sort, Pagination, Filter by category, Position
  tests/UI/campaigns/productV2/functional/08_header.ts
  tests/UI/campaigns/productV2/functional/10_descriptionTab.ts
  tests/UI/campaigns/productV2/functional/21_filterSortPagination.ts
  tests/UI/pages/BO/catalog/discounts/index.ts
  tests/UI/pages/BO/catalog/productsV2/index.ts
  tests/UI/pages/BO/orders/index.ts
Labels: Improvement, TE, develop, E2E Tests

#34105 Functional tests - Add new test 'BO > Product V2 > Check seo tab'
  tests/UI/campaigns/productV2/functional/18_seoTab.ts
  tests/UI/data/faker/product.ts
  tests/UI/data/types/product.d.ts
  tests/UI/pages/BO/catalog/productsV2/add/index.ts
  tests/UI/pages/BO/catalog/productsV2/add/seoTab.ts
Labels: TE, develop, Refactoring, E2E Tests

#34194 Functional Tests : BO - Products list - Bulk actions, Enable/Disable, 3-dot button
  tests/UI/campaigns/productV2/functional/22_bulkActionsEnableDisable3DotsButton.ts
  tests/UI/pages/BO/catalog/productsV2/index.ts
  tests/UI/pages/FO/product/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#34187 Use chrome beta to avoid crash on playwright
  .github/workflows/cron_nightly_tests_reusable.yml
  .github/workflows/sanity.yml
  .github/workflows/ui_tests_code_checks.yml
  tests/UI/types/global.d.ts
  tests/UI/utils/globals.ts
Labels: TE, develop, Refactoring, E2E Tests

#34182 Fix sorting by "time" in profiler's stopwatch SQL
  tools/profiling/templates/stopwatch.tpl
Labels: QA ✔️, develop, Bug fix

#34223 Functional tests - Add new test 'BO > Customers > View/edit voucher'
  tests/UI/campaigns/functional/BO/04_customers/01_customers/10_viewEditVoucher.ts
  tests/UI/pages/BO/catalog/discounts/add.ts
  tests/UI/pages/BO/customers/view.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34195 Add `tinyMCE` hr plugin & toolbar
  admin-dev/themes/new-theme/js/components/tinymce-editor.js
Labels: Improvement, QA ✔️, develop

#34240 Nightly : Fixed `campaigns/productV2/functional/22_*`
  tests/UI/pages/BO/catalog/productsV2/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#34162 Fix edit bulk quantity for stock page
  admin-dev/themes/new-theme/js/app/pages/stock/components/overview/products-actions.vue
  admin-dev/themes/new-theme/js/app/pages/stock/components/overview/spinner.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-number.vue
Labels: QA ✔️, Bug fix, 8.1.x

#33229 Add Warning check in updateSchema command output
  src/PrestaShopBundle/Install/Install.php
Labels: Improvement, QA ✔️, develop

#34232 Functional tests - Add new test 'BO > Customers > Transform a Guest to a Customer'
  tests/UI/campaigns/functional/BO/04_customers/01_customers/11_transformGuestToCustomer.ts
  tests/UI/pages/BO/customers/index.ts
  tests/UI/pages/BO/customers/view.ts
Labels: TE, develop, Refactoring, E2E Tests

#34249 Functional tests - Refacto 'BO > Order settings > Order status & return status'
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/returnStatuses/01_CRUDOrderReturnStatus.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/returnStatuses/02_filterSortAndPagination.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/statuses/01_CRUDOrderStatus.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/statuses/02_filterSortAndPagination.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/statuses/04_bulkActions.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34241 Improve installation language fallback system
  install-dev/classes/controllerHttp.php
  src/PrestaShopBundle/Install/LanguageList.php
Labels: QA ✔️, develop, Bug fix

#34235 Allow html tags in BO module footer
  admin-dev/themes/default/template/controllers/modules/configuration_bar.tpl
Labels: QA ✔️, develop, Bug fix

#34255 Nightly : Fixed `campaigns/productV2/functional/01*`
  tests/UI/campaigns/productV2/functional/01_filterProducts.ts
  tests/UI/pages/BO/catalog/productsV2/index.ts
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#34251 Functional tests - Add new test 'BO > Shop parameters > Recalculate shipping costs after editing the order '
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/01_enableFinalSummary.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/02_enableGuestCheckout.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/03_disableReorderingOption.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/04_minimumPurchaseTotalRequired.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/05_recalculateShippingCosts.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/general/06_termsOfService.ts
  tests/UI/pages/BO/shopParameters/orderSettings/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34291 Merge `8.1.x` into `develop`
  admin-dev/themes/new-theme/js/app/pages/stock/components/overview/products-actions.vue
  admin-dev/themes/new-theme/js/app/pages/stock/components/overview/spinner.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-number.vue
Labels: Waiting for QA, develop

#34290 Remove historic tabs system
  .github/workflows/phpstan/autoload.php
  admin-dev/functions.php
  classes/Dispatcher.php
  controllers/admin/AdminSearchController.php
  tools/profiling/Tools.php
Labels: Waiting for QA, develop, Refactoring, BC break

#34207 Don't check all product availability in cart on add to cart action
  controllers/front/CartController.php
Labels: QA ✔️, Bug fix, 8.1.x

#34307 Functional tests - Fix some random errors
  tests/UI/pages/BO/design/themeAndLogo/themeAndLogo/import.ts
  tests/UI/pages/BO/orders/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34267 Functional tests - Add new test 'BO > Customer service > Forward message'
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/06_forwardMessage.ts
  tests/UI/pages/BO/customerService/customerService/view.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34258 Functional tests - Add new test 'BO > Orders > Return order'
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/13_returnOrder.ts
  tests/UI/pages/BO/orders/view/productsBlock.ts
  tests/UI/pages/BO/orders/view/tabListBlock.ts
  tests/UI/pages/BO/orders/view/viewOrderBasePage.ts
Labels: TE, develop, Refactoring, E2E Tests

#34329 Functional Tests : BO - Advanced Parameter - Authorization Server - Add API Access
  tests/UI/campaigns/functional/BO/14_advancedParameters/12_authorizationServer/02_addAPIAccess.ts
Labels: Improvement, TE, develop, E2E Tests

#34330 Functional Tests : BO - Advanced Parameter - Authorization Server : Edit API Access
  tests/UI/campaigns/functional/BO/14_advancedParameters/12_authorizationServer/03_editAPIAccess.ts
  tests/UI/commonTests/BO/advancedParameters/authServer.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#34268 Functional tests - Add new test 'BO > Customer service > Check customer service options'
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/05_customerServiceOptions.ts
  tests/UI/data/faker/customerServiceOptions.ts
  tests/UI/data/types/CustomerServiceOptions.d.ts
  tests/UI/pages/BO/customerService/customerService/index.ts
Labels: develop, Refactoring, E2E Tests

#34338 Functional Tests : Refacto `setLabelWhenOutOfStock` for StocksTab
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/01_internalAuthServer/01_authorizationEndpoint.ts
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/01_internalAuthServer/02_resourceEndpoint.ts
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/02_externalAuthServer/01_authorizationEndpoint.ts
  tests/UI/campaigns/functional/BO/01_dashboard/02_activityOverview.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/12_authorizationServer/02_addAPIAccess.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/12_authorizationServer/03_editAPIAccess.ts
  tests/UI/pages/BO/catalog/products/add/stocksTab.ts
Labels: TE, develop, Refactoring, E2E Tests

#34305 Fix ButtonCollectionType groups splitting
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: QA ✔️, develop, Bug fix

#34328 Functional Tests: Mail alerts module - Uninstall/Install module
  tests/UI/campaigns/modules/ps_emailalerts/01_installation/01_uninstallAndInstallModule.ts
  tests/UI/data/demo/modules.ts
  tests/UI/pages/FO/category/index.ts
  tests/UI/pages/FO/product/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#34344 Functional Tests : Hummingbird : FO - User account - Edit informations
  tests/UI/campaigns/functional/FO/hummingbird/03_userAccount/01_editInformation.ts
  tests/UI/pages/FO/myAccount/identity.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#34333 Functional tests - Add new test 'BO Dashboard > Products and sales & help card'
  tests/UI/campaigns/functional/BO/01_dashboard/03_productsAndSales.ts
  tests/UI/campaigns/functional/BO/01_dashboard/04_helpCard.ts
  tests/UI/pages/BO/dashboard/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#33864 [Twig component] Create global layout
  admin-dev/themes/new-theme/template/layout.tpl
  app/AppKernel.php
  app/config/config.yml
  composer.lock
  config/smarty.config.inc.php
  install-dev/controllers/console/process.php
  phpstan-tmp-legacy-layout-baseline.neon
  src/Adapter/Cache/Clearer/SymfonyCacheClearer.php
  src/Adapter/ContainerBuilder.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php
  src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/employee_dropdown.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/head_tag.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/nav_bar.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/notifications_center.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/quick_access.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/toolbar.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/core_javascript.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/default_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/employee_dropdown.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/footer.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/head.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/light_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/mobile_quick_access.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/nav_bar.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/notifications_center.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/quick_access.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/stylesheets.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/toolbar.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig
  src/PrestaShopBundle/Resources/views/Admin/layout.html.twig
  src/PrestaShopBundle/Twig/Component/HeadTag.php
  src/PrestaShopBundle/Twig/Component/MultistoreHeader.php
  src/PrestaShopBundle/Twig/Component/NavBar.php
  src/PrestaShopBundle/Twig/Component/Toolbar.php
  src/PrestaShopBundle/Twig/Layout/MenuBuilder.php
  src/PrestaShopBundle/Twig/Layout/PrestaShopLayoutGlobalVariables.php
  tests/Integration/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminControllerTest.php
Labels: QA ✔️, develop, Bug fix, Refactoring, BC break

#33787 Functional Tests : BO - Stocks - Movements - Filter by category, movement type, employee and period
  admin-dev/themes/new-theme/js/app/widgets/ps-select.vue
  admin-dev/themes/new-theme/js/app/widgets/ps-tree/ps-tree.vue
  docker-compose.yml
  tests/UI/campaigns/functional/BO/01_dashboard/02_activityOverview.ts
  tests/UI/campaigns/functional/BO/03_catalog/01_products/20_multistore.ts
  tests/UI/campaigns/functional/BO/03_catalog/08_stocks/01_movements/01_filterMovements.ts
  tests/UI/campaigns/functional/BO/03_catalog/08_stocks/01_movements/02_sortAndPagination.ts
  tests/UI/commonTests/BO/catalog/stock.ts
  tests/UI/data/faker/employee.ts
  tests/UI/data/types/product.d.ts
  tests/UI/package-lock.json
  tests/UI/package.json
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/catalog/products/add/combinationsTab.ts
  tests/UI/pages/BO/catalog/products/add/index.ts
  tests/UI/pages/BO/catalog/stocks/index.ts
  tests/UI/pages/BO/catalog/stocks/movements/index.ts
  tests/UI/utils/date.ts
Labels: Improvement, TE, develop, E2E Tests

#34029 Get a list of unique module's name
  src/Core/Translation/Storage/Provider/ThemeCatalogueLayersProvider.php
Labels: Improvement, PM ✔️, develop

#34309 Remove archived modules from email themes
  mails/themes/classic/modules/ps_reminder/followup_1.html.twig
  mails/themes/classic/modules/ps_reminder/followup_2.html.twig
  mails/themes/classic/modules/ps_reminder/followup_3.html.twig
  mails/themes/classic/modules/ps_reminder/followup_4.html.twig
  mails/themes/classic/modules/referralprogram/referralprogram-congratulations.html.twig
  mails/themes/classic/modules/referralprogram/referralprogram-invitation.html.twig
  mails/themes/classic/modules/referralprogram/referralprogram-voucher.html.twig
  mails/themes/modern/modules/followup/followup_1.html.twig
  mails/themes/modern/modules/followup/followup_2.html.twig
  mails/themes/modern/modules/followup/followup_3.html.twig
  mails/themes/modern/modules/followup/followup_4.html.twig
  mails/themes/modern/modules/ps_reminder/followup_1.html.twig
  mails/themes/modern/modules/ps_reminder/followup_2.html.twig
  mails/themes/modern/modules/ps_reminder/followup_3.html.twig
  mails/themes/modern/modules/ps_reminder/followup_4.html.twig
  mails/themes/modern/modules/referralprogram/referralprogram-congratulations.html.twig
  mails/themes/modern/modules/referralprogram/referralprogram-invitation.html.twig
  mails/themes/modern/modules/referralprogram/referralprogram-voucher.html.twig
  tests/UI/campaigns/functional/BO/08_design/03_emailTheme/01_previewEmailThemes.ts
Labels: Improvement, QA ✔️, develop

#34375 Merge 8.1.x into develop
  controllers/admin/AdminProductsController.php
  controllers/front/CartController.php
Labels: develop

#34345 Fix typo squared
  install-dev/fixtures/fashion/data/attribute.xml
  install-dev/fixtures/fashion/data/product_attribute_combination.xml
  install-dev/fixtures/fashion/langs/en/data/attribute.xml
  install-dev/fixtures/fashion/langs/fa/data/attribute.xml
  install-dev/fixtures/fashion/langs/fr/data/attribute.xml
  tests/Integration/Behaviour/Features/Scenario/Supplier/supplier_management.feature
  tests/UI/data/demo/attributes.ts
  tests/UI/data/demo/products.ts
Labels: QA ✔️, develop, Bug fix

#34352 Fix placeholder filter in BO > Employee and Customer Sessions
  src/Core/Grid/Definition/Factory/Security/Session/CustomerGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/Security/Session/EmployeeGridDefinitionFactory.php
Labels: QA ✔️, develop, Bug fix

#34350 Update link for user doc in Import page to v8
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Blocks/import_panel.html.twig
  translations/default/AdminAdvparametersHelp.xlf
Labels: QA ✔️, develop, Bug fix

#34242 Change the APE field validation to match all formats
  classes/Validate.php
  install-dev/data/db_structure.sql
  src/Core/Domain/Customer/ValueObject/ApeCode.php
  src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php
  src/PrestaShopBundle/Form/Admin/Type/ApeType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
Labels: Improvement, QA ✔️, Needs autoupgrade PR, 8.1.x

#34379 Functional tests - Fix random errors in nightly
  tests/UI/campaigns/functional/BO/03_catalog/01_products/11_combinationTab.ts
  tests/UI/campaigns/functional/BO/03_catalog/01_products/19_optionsTab.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34381 Update module versions in composer.lock (develop)
  composer.lock
Labels: Improvement, QA ✔️, develop

#34380 Update module versions in composer.lock (PS 8.1.x)
  composer.lock
Labels: Improvement, QA ✔️, 8.1.x

#34343 Fix combination modal changes detection
  admin-dev/themes/new-theme/js/pages/product/combination/combination-modal/CombinationModal.vue
  tests/UI/campaigns/productV2/functional/03_CRUDProductWithCombinations.ts
  tests/UI/pages/BO/catalog/productsV2/add/combinationsTab.ts
Labels: QA ✔️, Bug fix, 8.1.x

#34396 Remove the � from the invalid character
  src/Core/ConstraintValidator/TypedRegexValidator.php
Labels: Improvement, QA ✔️, develop

#34406 Functional tests - Fix create API access tests
  tests/UI/campaigns/functional/BO/14_advancedParameters/12_authorizationServer/01_CRUD.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/12_authorizationServer/02_addAPIAccess.ts
  tests/UI/commonTests/BO/advancedParameters/authServer.ts
  tests/UI/pages/BO/advancedParameters/APIAccess/add.ts
Labels: TE, Refactoring, E2E Tests

#34397 API access - add/edit lifetime
  src/Adapter/ApiAccess/CommandHandler/AddApiAccessHandler.php
  src/Adapter/ApiAccess/CommandHandler/EditApiAccessHandler.php
  src/Adapter/ApiAccess/QueryHandler/GetApiAccessForEditingHandler.php
  src/Core/Domain/ApiAccess/Command/AddApiAccessCommand.php
  src/Core/Domain/ApiAccess/Command/EditApiAccessCommand.php
  src/Core/Domain/ApiAccess/Exception/ApiAccessConstraintException.php
  src/Core/Domain/ApiAccess/QueryResult/EditableApiAccess.php
  src/Core/Form/IdentifiableObject/DataHandler/ApiAccessFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/ApiAccessFormDataProvider.php
  src/PrestaShopBundle/Entity/ApiAccess.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/AuthorizationServer/ApiAccessType.php
  tests/Integration/Behaviour/Features/Context/Domain/ApiAccessManagementFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/ApiAccess/api_access_management.feature
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/ApiAccessFormDataProviderTest.php
Labels: Improvement, develop

#34354 Functional tests - Refacto BO > Webservice'
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/02_filterAndQuickEditWebservice.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/02_quickEditWebservice.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/04_filterSortPagination.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/05_bulkActions.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34400 Functional tests - Add new test 'FO > Menu and navigation > Filter products'
  tests/UI/campaigns/functional/FO/classic/08_menuAndNavigation/02_sortAndFilter/02_filterProducts.ts
  tests/UI/pages/FO/category/index.ts
Labels: QA ✔️, develop, Refactoring, E2E Tests

#34395 Fix html encoded urls in symfony layout
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/employee_dropdown.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/mobile_quick_access.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/nav_bar.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/quick_access.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/shop_list.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/default_layout.html.twig
Labels: QA ✔️, develop, Bug fix

#34419 Allow unit price to be zero even when displayed
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/UnitPriceType.php
Labels: QA ✔️, Bug fix, 8.1.x

#34122 Protect .git folder with htaccess
  classes/Tools.php
Labels: Improvement, Waiting for QA, develop, Waiting for dev

#34426 Merge 8.1.x into develop
  admin-dev/themes/new-theme/js/pages/product/combination/combination-modal/CombinationModal.vue
  classes/Validate.php
  install-dev/data/db_structure.sql
  src/Core/ConstraintValidator/CleanHtmlValidator.php
  src/Core/Domain/Customer/ValueObject/ApeCode.php
  src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/UnitPriceType.php
  src/PrestaShopBundle/Form/Admin/Type/ApeType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  tests/UI/campaigns/functional/BO/03_catalog/01_products/03_CRUDProductWithCombinations.ts
  tests/UI/campaigns/functional/BO/03_catalog/01_products/11_combinationTab.ts
  tests/UI/pages/BO/catalog/products/add/combinationsTab.ts
Labels: develop

#34427 Nightly: Fixed `campaigns/functional/BO/15*/01*/06*`
  tests/UI/pages/BO/customerService/customerService/view.ts
Labels: TE, develop, Bug fix, E2E Tests

#34407 Theme with the right width in multistore creation
  admin-dev/themes/default/scss/controllers/_themes.scss
Labels: develop, Bug fix
