Repository PrestaShop/PrestaShop, pull requests merged in 2023-01, with the labels that each got.

#30657 Functional Tests : FO - 01
  tests/UI/campaigns/functional/BO/04_customers/01_customers/05_setRequiredFields.js
  tests/UI/campaigns/functional/FO/01_login/01_passwordReminder.ts
  tests/UI/campaigns/functional/FO/01_login/02_login.ts
  tests/UI/campaigns/functional/FO/01_login/03_logout.ts
  tests/UI/campaigns/functional/FO/01_login/04_createAccount.ts
  tests/UI/commonTests/FO/createAccount.js
  tests/UI/data/types/maildev.d.ts
  tests/UI/pages/FO/login/index.ts
  tests/UI/pages/FO/myAccount/add.ts
  tests/UI/pages/FO/passwordReminder/index.ts
  tests/UI/utils/mailHelper.ts
Labels: Improvement, TE, develop, E2E Tests

#30693 Functional Tests : Migration TS (`@data/faker/title` / `@data/faker/webservice` / `@data/faker/zone`)
  tests/UI/campaigns/functional/BO/11_international/02_locations/01_zones/01_filterAndQuickEditZones.ts
  tests/UI/campaigns/functional/BO/11_international/02_locations/01_zones/02_CRUDZone.ts
  tests/UI/campaigns/functional/BO/11_international/02_locations/01_zones/03_bulkActionsZones.ts
  tests/UI/campaigns/functional/BO/11_international/02_locations/01_zones/04_sortAndPagination.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/03_titles/01_filterTitles.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/03_titles/02_CRUDTitles.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/03_titles/03_bulkDeleteTitles.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/01_CRUDWebservice.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/02_filterAndQuickEditWebservice.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/04_sortPaginationAndBulkActions.ts
  tests/UI/data/demo/titles.js
  tests/UI/data/demo/titles.ts
  tests/UI/data/demo/zones.js
  tests/UI/data/demo/zones.ts
  tests/UI/data/faker/carrier.js
  tests/UI/data/faker/country.js
  tests/UI/data/faker/customer.js
  tests/UI/data/faker/state.js
  tests/UI/data/faker/title.ts
  tests/UI/data/faker/webservice.ts
  tests/UI/data/faker/zone.ts
  tests/UI/data/types/title.d.ts
  tests/UI/data/types/webservice.d.ts
  tests/UI/data/types/zone.d.ts
Labels: Improvement, TE, develop, E2E Tests

#30718 Functional-Sanity tests - Migration TS all tests of products v2 page
  tests/UI/campaigns/productV2/functional/01_filterProducts.ts
  tests/UI/campaigns/productV2/functional/02_CRUDStandardProduct.ts
  tests/UI/campaigns/productV2/functional/03_CRUDProductWithCombinations.ts
  tests/UI/campaigns/productV2/functional/04_CRUDPackOfProducts.ts
  tests/UI/campaigns/productV2/functional/05_CRUDVirtualProduct.ts
  tests/UI/campaigns/productV2/sanity/01_filterProducts.ts
  tests/UI/campaigns/productV2/sanity/02_CRUDStandardProduct.ts
  tests/UI/campaigns/productV2/sanity/03_CRUDProductWithCombinations.ts
  tests/UI/campaigns/productV2/sanity/04_CRUDVirtualProduct.ts
  tests/UI/campaigns/productV2/sanity/05_deleteProduct.ts
  tests/UI/campaigns/productV2/sanity/06_deleteProductsWithBulkActions.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/catalog/productsV2/add/combinationsTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/descriptionTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/detailsTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/index.ts
  tests/UI/pages/BO/catalog/productsV2/add/packTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/pricingTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/stocksTab.ts
  tests/UI/pages/BO/catalog/productsV2/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#30660 Functional Tests : Migration TS (BO - 08)
  tests/UI/campaigns/functional/BO/04_customers/01_customers/09_subscribeToNewsletter.js
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/01_filterModulesByStatus.js
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/02_filterModulesByCategories.js
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/03_configureModule.js
  tests/UI/campaigns/functional/BO/08_design/01_themeAndLogo/03_advancedCustomization/01_advancedCustomization.ts
  tests/UI/campaigns/functional/BO/08_design/03_emailTheme/01_previewEmailThemes.ts
  tests/UI/campaigns/functional/BO/08_design/03_emailTheme/02_selectDefaultEmailTheme.ts
  tests/UI/campaigns/functional/BO/08_design/03_emailTheme/03_viewRawHtmlAndText.ts
  tests/UI/campaigns/functional/BO/08_design/04_pages/01_CRUDPageCategory.ts
  tests/UI/campaigns/functional/BO/08_design/04_pages/02_helpCard.ts
  tests/UI/campaigns/functional/BO/08_design/04_pages/categories/01_filterAndQuickEditCategories.ts
  tests/UI/campaigns/functional/BO/08_design/04_pages/categories/02_categoriesBulkActions.ts
  tests/UI/campaigns/functional/BO/08_design/04_pages/categories/03_paginationAndSortCategories.ts
  tests/UI/campaigns/functional/BO/08_design/04_pages/pages/01_filterAndQuickEditPages.ts
  tests/UI/campaigns/functional/BO/08_design/04_pages/pages/02_pagesBulkActions.ts
  tests/UI/campaigns/functional/BO/08_design/04_pages/pages/03_paginationAndSortPages.ts
  tests/UI/campaigns/functional/BO/08_design/05_positions/02_searchHook.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/01_filterImageTypes.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/02_CRUDImageType.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/03_bulkDeleteImageTypes.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/04_sortAndPagination.ts
  tests/UI/campaigns/functional/BO/08_design/07_linkWidget/01_createAndCheckFooterLinkWidget.ts
  tests/UI/pages/BO/design/imageSettings/index.js
  tests/UI/pages/BO/design/pages/index.js
  tests/UI/pages/BO/modules/moduleManager/index.ts
  tests/UI/pages/BO/orders/add.js
Labels: Improvement, TE, develop, E2E Tests

#30682 Functional Tests : Migration TS (Sanity)
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/01_productsGeneral/01_catalogMode.ts
  tests/UI/campaigns/sanity/01_installShop/01_installShop.ts
  tests/UI/campaigns/sanity/02_ordersBO/01_filterOrders.ts
  tests/UI/campaigns/sanity/02_ordersBO/02_editOrder.ts
  tests/UI/campaigns/sanity/03_productsBO/01_filterProducts.ts
  tests/UI/campaigns/sanity/03_productsBO/02_CRUDStandardProductInBO.ts
  tests/UI/campaigns/sanity/03_productsBO/03_CRUDStandardProductWithCombinationsInBO.ts
  tests/UI/campaigns/sanity/03_productsBO/04_deleteProduct.ts
  tests/UI/campaigns/sanity/03_productsBO/05_deleteProductsWithBulkActions.ts
  tests/UI/campaigns/sanity/04_catalogFO/01_filterProducts.ts
  tests/UI/campaigns/sanity/04_catalogFO/02_checkProduct.ts
  tests/UI/campaigns/sanity/05_cartFO/01_editCheckCart.ts
  tests/UI/campaigns/sanity/06_checkoutFO/01_orderProduct.ts
  tests/UI/data/types/product.d.ts
  tests/UI/pages/FO/FObasePage.ts
  tests/UI/pages/FO/cart/index.ts
  tests/UI/pages/FO/home/index.ts
  tests/UI/pages/FO/product/index.ts
Labels: Improvement, TE, develop, E2E Tests

#30717 Merge 8.0.x into develop
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
  tests/Integration/PrestaShopBundle/TranslationIntegrationTest.php
Labels: Improvement, QA ✔️, develop

#30695 Functional Tests : Migration TS (`@data/faker/tax` / `@data/faker/taxRule` / `@data/faker/taxRulesGroup`)
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/02_enableDisableTaxBreakdown.js
  tests/UI/campaigns/functional/BO/11_international/03_taxes/01_taxes/01_filterAndQuickEditTaxes.ts
  tests/UI/campaigns/functional/BO/11_international/03_taxes/01_taxes/02_CRUDTaxesInBO.ts
  tests/UI/campaigns/functional/BO/11_international/03_taxes/01_taxes/03_taxesBulkActionsInBO.ts
  tests/UI/campaigns/functional/BO/11_international/03_taxes/02_taxRules/01_CRUDTaxRules.ts
  tests/UI/campaigns/functional/BO/11_international/03_taxes/02_taxRules/02_filterSortAndPagination.ts
  tests/UI/campaigns/functional/BO/11_international/03_taxes/02_taxRules/03_quickEditAndBulkActions.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/01_orderSettings/giftOptions/01_giftOptions.ts
  tests/UI/campaigns/sanity/03_productsBO/01_filterProducts.ts
  tests/UI/campaigns/sanity/03_productsBO/02_CRUDStandardProductInBO.ts
  tests/UI/data/demo/tax.js
  tests/UI/data/demo/tax.ts
  tests/UI/data/demo/taxRule.js
  tests/UI/data/demo/taxRule.ts
  tests/UI/data/demo/taxRuleBehaviour.ts
  tests/UI/data/faker/carrier.js
  tests/UI/data/faker/tax.js
  tests/UI/data/faker/tax.ts
  tests/UI/data/faker/taxRule.js
  tests/UI/data/faker/taxRule.ts
  tests/UI/data/faker/taxRulesGroup.ts
  tests/UI/data/types/tax.d.ts
  tests/UI/data/types/taxRule.d.ts
  tests/UI/data/types/taxRulesGroup.d.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/international/taxes/taxRules/add.js
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#30681 Functional Tests : Migration TS (BO - 05/07)
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/01_viewCustomerService.ts
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/02_changeStatus.ts
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/03_contactOptions.ts
  tests/UI/campaigns/functional/BO/05_customerService/02_orderMessages/01_CRUDOrderMessage.ts
  tests/UI/campaigns/functional/BO/05_customerService/02_orderMessages/02_filterAndBulkDeleteOrderMessages.ts
  tests/UI/campaigns/functional/BO/05_customerService/02_orderMessages/03_paginationAndSortOrderMessages.ts
  tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/01_merchandiseReturnOptions.ts
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/01_filterModulesByStatus.ts
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/02_filterModulesByCategories.ts
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/03_configureModule.ts
  tests/UI/pages/BO/searchResults/index.ts
  tests/UI/pages/BO/stats/index.ts
  tests/UI/pages/FO/contactUs/index.ts
Labels: Improvement, TE, develop, E2E Tests

#30683 Combination multishop fix
  classes/stock/StockAvailable.php
  src/Adapter/Product/Combination/Repository/CombinationMultiShopRepository.php
  src/Adapter/Product/Combination/Update/CombinationStockUpdater.php
  src/Adapter/Product/Stock/Repository/StockAvailableMultiShopRepository.php
  src/Adapter/Product/Stock/Update/ProductStockUpdater.php
  src/Adapter/Product/Update/ProductShopUpdater.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_stock.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/CombinationAssertionFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/StockAssertionFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/Shop/copy_combinations_to_shop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/Shop/delete_multishop_combination.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/Shop/update_multishop_combination_stock.feature
Labels: develop, Bug fix

#30724 Functional Tests : Migration TS (BO - 04)
  tests/UI/campaigns/functional/BO/04_customers/01_customers/01_filterAndQuickEditCustomers.ts
  tests/UI/campaigns/functional/BO/04_customers/01_customers/02_CRUDCustomer.ts
  tests/UI/campaigns/functional/BO/04_customers/01_customers/03_customersBulkActions.ts
  tests/UI/campaigns/functional/BO/04_customers/01_customers/04_paginationAndSortCustomers.ts
  tests/UI/campaigns/functional/BO/04_customers/01_customers/05_setRequiredFields.ts
  tests/UI/campaigns/functional/BO/04_customers/01_customers/06_exportCustomers.ts
  tests/UI/campaigns/functional/BO/04_customers/01_customers/07_helpCard.ts
  tests/UI/campaigns/functional/BO/04_customers/01_customers/08_viewCustomer.ts
  tests/UI/campaigns/functional/BO/04_customers/01_customers/09_subscribeToNewsletter.ts
  tests/UI/campaigns/functional/BO/04_customers/02_addresses/01_filterAddresses.ts
  tests/UI/campaigns/functional/BO/04_customers/02_addresses/02_CRUDAddressInBO.ts
  tests/UI/campaigns/functional/BO/04_customers/02_addresses/03_addressesBulkActions.ts
  tests/UI/campaigns/functional/BO/04_customers/02_addresses/04_paginationAndSortAddresses.ts
  tests/UI/campaigns/functional/BO/04_customers/02_addresses/05_helpCard.ts
  tests/UI/campaigns/functional/BO/04_customers/02_addresses/06_setRequiredFields.ts
  tests/UI/campaigns/functional/BO/04_customers/03_outstanding/01_helpCard.ts
  tests/UI/campaigns/functional/BO/04_customers/03_outstanding/02_viewOrder.ts
  tests/UI/campaigns/functional/BO/04_customers/03_outstanding/03_viewInvoice.ts
  tests/UI/campaigns/functional/BO/04_customers/03_outstanding/04_pagination.ts
  tests/UI/campaigns/functional/BO/04_customers/03_outstanding/05_sortFilterOutstanding.ts
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/02_filterModulesByCategories.ts
  tests/UI/campaigns/functional/BO/08_design/04_pages/02_helpCard.ts
  tests/UI/campaigns/functional/BO/11_international/01_localization/01_localization/05_defaultCountry.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/02_defaultPackStockManagement.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/04_enableB2BMode.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/05_contact/01_filterContacts.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/01_seoAndUrls/02_setUpUrls/04_enableDisableAccentedURL.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/01_seoAndUrls/helpCard.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/02_searchEngines/01_filterSortAndPagination.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/08_logs/01_filterSortAndPagination.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/01_CRUDWebservice.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/02_filterAndQuickEditWebservice.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/03_helpCard.ts
  tests/UI/campaigns/functional/BO/15_header/01_leftMenu.ts
  tests/UI/campaigns/functional/BO/15_header/02_quickAccess.ts
  tests/UI/campaigns/functional/BO/15_header/03_searchBar.ts
  tests/UI/campaigns/functional/BO/15_header/05_viewMyShop.ts
  tests/UI/campaigns/functional/BO/15_header/07_myProfile.ts
  tests/UI/campaigns/functional/FO/01_login/02_login.ts
  tests/UI/campaigns/functional/FO/02_headerAndFooter/02_checkLinksInFooter.ts
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderList.ts
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/02_reorderFromOrderList.ts
  tests/UI/campaigns/functional/FO/03_userAccount/05_getGDPRDataInCSV.ts
  tests/UI/campaigns/functional/FO/03_userAccount/merchandiseReturns/01_consultReturnDetails.ts
  tests/UI/campaigns/regression/currencies/computingPrecision_FO.ts
  tests/UI/campaigns/regression/menu/deniedAccessToMenuTab.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/customers/index.js
  tests/UI/pages/BO/orders/index.js
  tests/UI/pages/BO/shopParameters/trafficAndSeo/searchEngines/add.ts
  tests/UI/pages/BO/shopParameters/trafficAndSeo/searchEngines/index.ts
Labels: Improvement, TE, develop, E2E Tests

#30726 Functional Tests : Migration TS (`@data/faker/tag`, `@data/faker/supplier`, `@data/faker/store`)
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/suppliers/01_CRUDSupplier.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/suppliers/02_filterAndQuickEdit.js
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/suppliers/04_paginationSortAndBulkActions.js
  tests/UI/campaigns/functional/BO/03_catalog/08_stocks/01_simpleFilterStocks.js
  tests/UI/campaigns/functional/BO/13_shopParameters/05_contact/stores/01_filterAndQuickEditStores.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/05_contact/stores/03_bulkActionsStores.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/05_contact/stores/04_sortAndPagination.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/05_contact/stores/05_contactDetails.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/02_tags/01_CRUDTag.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/02_tags/02_filterSortAndPagination.ts
  tests/UI/data/demo/stores.js
  tests/UI/data/demo/stores.ts
  tests/UI/data/demo/suppliers.js
  tests/UI/data/demo/suppliers.ts
  tests/UI/data/faker/store.ts
  tests/UI/data/faker/supplier.ts
  tests/UI/data/faker/tag.js
  tests/UI/data/faker/tag.ts
  tests/UI/data/types/store.d.ts
  tests/UI/data/types/supplier.d.ts
  tests/UI/data/types/tag.d.ts
  tests/UI/pages/BO/BObasePage.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#30736 Add GITHUB_TOKEN to the github action env
  .github/actions/setup-prestashop-env/action.yml
  .github/workflows/behaviour.yml
  .github/workflows/cron_js_routing.yml
  .github/workflows/cron_nightly_build.yml
  .github/workflows/cron_php_update_modules.yml
  .github/workflows/integration.yml
  .github/workflows/lint.yml
  .github/workflows/php.yml
  .github/workflows/sanity-productV2.yml
  .github/workflows/sanity.yml
Labels: develop, Bug fix

#30737 Fix error message when enabling product without name in monitoring page
  src/PrestaShopBundle/Controller/Admin/ProductController.php
Labels: QA ✔️, develop, Bug fix

#30728 Bump `phpstan/phpstan` from 1.9.3 to 1.9.6
  composer.lock
Labels: Improvement, QA ✔️, develop

#30739 Functional Tests : Migration TS (BO - 00)
  tests/UI/campaigns/functional/BO/00_login/01_passwordReminder.ts
  tests/UI/campaigns/functional/BO/00_login/02_login.ts
  tests/UI/campaigns/functional/BO/00_login/03_logout.ts
Labels: Improvement, TE, develop, E2E Tests

#30725 Optimize `Product::hasCombinations`
  classes/Product.php
Labels: QA ✔️, develop, Refactoring

#30624 Manage multi shop images association
  admin-dev/themes/new-theme/js/fos_js_routes.json
  admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue
  admin-dev/themes/new-theme/js/pages/product/components/images-shop-association/ImageShopAssociationModal.vue
  admin-dev/themes/new-theme/js/pages/product/components/images-shop-association/ImageShopGrid.vue
  admin-dev/themes/new-theme/js/pages/product/components/images-shop-association/index.ts
  admin-dev/themes/new-theme/js/pages/product/components/images-shop-association/types.d.ts
  admin-dev/themes/new-theme/js/pages/product/edit/index.ts
  admin-dev/themes/new-theme/js/pages/product/product-event-map.ts
  admin-dev/themes/new-theme/js/pages/product/product-map.ts
  admin-dev/themes/new-theme/js/pages/product/services/images.ts
  admin-dev/themes/new-theme/scss/config/_settings.scss
  admin-dev/themes/new-theme/scss/pages/product/product_page.scss
  src/Adapter/Product/Image/Repository/ProductImageMultiShopRepository.php
  src/Adapter/Shop/Repository/ShopRepository.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ImageController.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Description/DescriptionType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Image/ImageDropzoneType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/product_v2/image.yml
  src/PrestaShopBundle/Resources/config/services/adapter/shop.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/FormTheme/product.html.twig
Labels: develop, Feature, Wording ✔️

#30456 Unify brightness checks
  classes/Tools.php
  classes/controller/AdminController.php
  src/Adapter/Presenter/Order/OrderLazyArray.php
Labels: QA ✔️, develop, Bug fix, Deprecations

#29842 Update UIKit, switch to sass-embedded and make new-theme compatible with node 16, 18 and 19
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/js/app/pages/translations/store/index.ts
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
  admin-dev/themes/new-theme/scss/rtl.scss
  admin-dev/themes/new-theme/scss/theme.scss
Labels: Improvement, QA ✔️, develop, 8.0.x, Hacktoberfest

#30743 Migrate all FO pages to TS
  tests/UI/campaigns/functional/BO/02_orders/01_orders/04_updateStatus.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/11_previewOrder.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/04_selectPreviousCarts.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/08_chooseAddress.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/10_checkSummary.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/06_merchandiseReturnsTab.js
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/07_messagesBlock.js
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/02_enableDisableTaxBreakdown.js
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/03_enableDisableProductImage.js
  tests/UI/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/03_enableDisableProductImage.js
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/10_countryRestriction.ts
  tests/UI/commonTests/FO/createAccount.js
  tests/UI/commonTests/FO/createOrder.js
  tests/UI/pages/FO/FObasePage.ts
  tests/UI/pages/FO/cart/index.ts
  tests/UI/pages/FO/category/index.ts
  tests/UI/pages/FO/checkout/index.ts
  tests/UI/pages/FO/checkout/orderConfirmation.ts
  tests/UI/pages/FO/cms/index.ts
  tests/UI/pages/FO/delivery/index.ts
  tests/UI/pages/FO/legalNotice/index.ts
  tests/UI/pages/FO/myAccount/addAddress.ts
  tests/UI/pages/FO/myAccount/addresses.ts
  tests/UI/pages/FO/myAccount/creditSlips.ts
  tests/UI/pages/FO/myAccount/gdprPersonalData.ts
  tests/UI/pages/FO/myAccount/identity.ts
  tests/UI/pages/FO/myAccount/index.ts
  tests/UI/pages/FO/myAccount/merchandiseReturns.ts
  tests/UI/pages/FO/myAccount/myWishlists.ts
  tests/UI/pages/FO/myAccount/orderDetails.ts
  tests/UI/pages/FO/myAccount/orderHistory.ts
  tests/UI/pages/FO/myAccount/returnDetails.ts
  tests/UI/pages/FO/myAccount/vouchers.js
  tests/UI/pages/FO/myAccount/vouchers.ts
  tests/UI/pages/FO/newProducts/index.ts
  tests/UI/pages/FO/orderTracking/guestOrderTracking.ts
  tests/UI/pages/FO/passwordReminder/index.ts
  tests/UI/pages/FO/pricesDrop/index.ts
  tests/UI/pages/FO/product/index.ts
  tests/UI/pages/FO/searchResults/index.ts
  tests/UI/pages/FO/securePayment/index.ts
  tests/UI/pages/FO/siteMap/index.ts
  tests/UI/pages/FO/stores/index.ts
  tests/UI/pages/FO/termsAndConditionsOfUse/index.ts
Labels: TE, develop, Refactoring, E2E Tests

#30584 Manage cover in multishop context
  classes/Image.php
  src/Adapter/Product/Image/CommandHandler/UpdateProductImageHandler.php
  src/Adapter/Product/Image/QueryHandler/GetProductImagesHandler.php
  src/Adapter/Product/Image/Repository/ProductImageMultiShopRepository.php
  src/Adapter/Product/Image/Update/ProductImageUpdater.php
  src/Adapter/Product/QueryHandler/GetProductForEditingHandler.php
  src/Adapter/Product/Update/ProductShopUpdater.php
  src/Core/Domain/Product/Image/Command/UpdateProductImageCommand.php
  src/Core/Domain/Product/Image/Query/GetProductImages.php
  src/Core/Form/ChoiceProvider/ProductImagesChoiceProvider.php
  src/Core/Form/IdentifiableObject/DataHandler/ProductImageFormDataHandler.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ImageController.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_image.yml
  src/PrestaShopBundle/Resources/config/services/core/form/choice_provider.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/add_multishop_image.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/delete_multishop_image.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/get_shop_product_images.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_multishop_image.feature
  tests/Unit/Core/Form/ChoiceProvider/ProductImagesChoiceProviderTest.php
Labels: develop, Feature

#30585 Implement shopConstraint in getCombinationIds()
  admin-dev/themes/new-theme/js/pages/product/services/paginated-combinations-service.ts
  src/Adapter/Product/Combination/QueryHandler/GetEditableCombinationsListHandler.php
  src/Adapter/Product/Combination/Repository/CombinationMultiShopRepository.php
  src/Adapter/Product/Combination/Repository/CombinationRepository.php
  src/Adapter/Product/Update/ProductShopUpdater.php
  src/Core/Domain/Product/Combination/Query/GetCombinationIds.php
  src/Core/Domain/Product/Combination/QueryHandler/GetCombinationIdsHandler.php
  src/Core/Domain/Product/Combination/QueryHandler/GetCombinationIdsHandlerInterface.php
  src/Core/Grid/Query/ProductCombinationQueryBuilder.php
  src/Core/Search/Builder/TypedBuilder/ProductCombinationFiltersBuilder.php
  src/Core/Search/Filters/ProductCombinationFilters.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php
  src/PrestaShopBundle/Resources/config/services/adapter/product/_combination.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/AbstractCombinationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/CombinationListingFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/GetCombinationIdsFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/Shop/combinations_multishop_listing.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/combinations_listing.feature
  tests/Integration/Behaviour/behat.yml
  tests/Unit/Core/Search/Builder/TypedBuilder/ProductCombinationFiltersBuilderTest.php
  tests/Unit/Core/Search/Filters/ProductCombinationFiltersTest.php
Labels: develop, Refactoring

#30590 All shops checkboxes for combination edit/bulk-edit forms
  admin-dev/themes/new-theme/js/pages/product/combination/bulk.ts
  admin-dev/themes/new-theme/js/pages/product/combination/form/index.ts
  src/Core/Form/IdentifiableObject/DataFormatter/AbstractFormDataFormatter.php
  src/Core/Form/IdentifiableObject/DataFormatter/BulkCombinationFormDataFormatter.php
  src/Core/Form/IdentifiableObject/DataHandler/BulkCombinationFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/BulkCombinationFormDataProvider.php
  src/Core/Form/IdentifiableObject/DataProvider/CombinationFormDataProvider.php
  src/Core/Util/String/ModifyAllShopsUtil.php
  src/PrestaShopBundle/Form/Admin/Extension/DisablingSwitchExtension.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/BulkCombinationPriceType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/BulkCombinationStockType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationHeaderType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationPriceImpactType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationStockType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/QuantityType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/StockOptionsType.php
  src/PrestaShopBundle/Form/Admin/Type/DeltaQuantityType.php
  src/PrestaShopBundle/Resources/config/services/core/form/data_formatter.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
  tests/Unit/Core/Form/IdentifiableObject/DataFormatter/BulkCombinationFormDataFormatterTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataFormatter/CombinationListFormDataFormatterTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/CombinationFormDataProviderTest.php
  tests/Unit/Core/Util/String/ModifyAllShopsUtilTest.php
  tests/Unit/Core/Util/String/StringModifierTest.php
Labels: develop, Refactoring

#30742 Remove wholesale price suppliers synchronicity
  admin-dev/themes/new-theme/js/pages/product/combination/form/index.ts
  admin-dev/themes/new-theme/js/pages/product/components/suppliers/product-suppliers-collection.ts
  admin-dev/themes/new-theme/js/pages/product/edit/product-options-manager.ts
  classes/Combination.php
  src/Adapter/Product/Combination/CommandHandler/UpdateCombinationHandler.php
  src/Adapter/Product/CommandHandler/UpdateProductHandler.php
  src/Adapter/Product/Update/ProductSupplierUpdater.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/update_combination_suppliers.feature
  tests/Integration/Behaviour/Features/Scenario/Product/bulk_duplicate_product.feature
  tests/Integration/Behaviour/Features/Scenario/Product/duplicate_product.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_suppliers.feature
Labels: develop, Bug fix, Needs documentation

#30752 Functional Tests : Migration TS (`@data/faker/{state,sqlQuery,shopGroup,shop,seoPage, searchEngine,search,profile}`)
  tests/UI/campaigns/functional/BO/11_international/02_locations/03_states/01_filterAndQuickEditStates.ts
  tests/UI/campaigns/functional/BO/11_international/02_locations/03_states/02_CRUDState.ts
  tests/UI/campaigns/functional/BO/11_international/02_locations/03_states/03_bulkActionsStates.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/01_seoAndUrls/01_seoAndUrls/01_filterSeoPages.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/01_seoAndUrls/01_seoAndUrls/02_CRUDSeoPage.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/01_seoAndUrls/01_seoAndUrls/07_bulkDeleteSeoPages.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/02_searchEngines/01_filterSortAndPagination.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/02_searchEngines/02_CRUDSearchEngines.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/06_trafficAndSeo/02_searchEngines/03_bulkActions.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/01_search/01_CRUDSearch.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/01_search/02_bulkActions.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/01_search/03_quickEditStatus.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/profiles/02_CRUDProfile.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/profiles/05_paginationAndBulkActions.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/01_CRUDSqlQuery.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/03_exportSqlQuery.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/04_filterSortAndPagination.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/01_CRUDShopGroups.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/02_filterSortAndPaginationShopGroups.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/03_CRUDShops.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/04_filterSortAndPaginationShops.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/05_filterSortAndPaginationShopUrls.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/06_quickEditAndbulkActionsShopUrls.ts
  tests/UI/data/demo/profiles.js
  tests/UI/data/demo/profiles.ts
  tests/UI/data/demo/search.js
  tests/UI/data/demo/search.ts
  tests/UI/data/demo/searchEngines.js
  tests/UI/data/demo/searchEngines.ts
  tests/UI/data/demo/seoPages.ts
  tests/UI/data/demo/sqlTables.js
  tests/UI/data/demo/sqlTables.ts
  tests/UI/data/demo/states.js
  tests/UI/data/demo/states.ts
  tests/UI/data/faker/address.js
  tests/UI/data/faker/employee.js
  tests/UI/data/faker/profile.ts
  tests/UI/data/faker/search.ts
  tests/UI/data/faker/searchEngine.js
  tests/UI/data/faker/searchEngine.ts
  tests/UI/data/faker/seoPage.ts
  tests/UI/data/faker/shop.ts
  tests/UI/data/faker/shopGroup.ts
  tests/UI/data/faker/sqlQuery.js
  tests/UI/data/faker/sqlQuery.ts
  tests/UI/data/faker/sqlTable.ts
  tests/UI/data/faker/state.js
  tests/UI/data/faker/state.ts
  tests/UI/data/types/profile.d.ts
  tests/UI/data/types/search.d.ts
  tests/UI/data/types/searchEngine.d.ts
  tests/UI/data/types/seoPage.d.ts
  tests/UI/data/types/shop.d.ts
  tests/UI/data/types/shopGroup.d.ts
  tests/UI/data/types/sqlQuery.d.ts
  tests/UI/data/types/sqlTable.d.ts
  tests/UI/data/types/state.d.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#30727 Delete all combinations when removing product from shop
  src/Adapter/Product/Shop/CommandHandler/DeleteProductFromShopsHandler.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature
Labels: QA ✔️, develop, Bug fix

#30293 Aaa/apis01 implement cqrs based api endpoint
  app/config/api_platform/resources.yml
  app/config/config.yml
  composer.lock
  src/PrestaShopBundle/Api/Resource/HookStatus.php
  src/PrestaShopBundle/Api/StateProvider/HookStatusProvider.php
  src/PrestaShopBundle/Resources/config/services/bundle/services.yml
  tests/Integration/Api/GetHookStatusTest.php
  tests/Unit/PrestaShopBundle/Api/StateProvider/HookStatusProviderTest.php
Labels: QA ✔️, develop, Feature

#30776 Allow searching brands in choices list of product v2
  src/PrestaShopBundle/Form/Admin/Sell/Product/Description/ManufacturerType.php
Labels: QA ✔️, develop, Bug fix

#30789 Add `new-products` page in global urls smarty
  classes/controller/FrontController.php
Labels: Improvement, QA ✔️, develop

#29923 Refactor PrestashopAutoload system
  autoload.php
  classes/PrestaShopAutoload.php
  classes/Tools.php
  classes/module/Module.php
  composer.json
  composer.lock
  config/autoload.php
  controllers/admin/AdminTranslationsController.php
  install-dev/classes/controllerHttp.php
  src/Adapter/Cache/Clearer/ClassIndexCacheClearer.php
Labels: Improvement, QA ✔️, develop, Deprecations

#30774 Functional tests - Refacto 'FO > User account > Order history > Consult order list' test
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_consultOrderList.ts
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderList.ts
  tests/UI/data/types/order.d.ts
  tests/UI/pages/FO/myAccount/orderHistory.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#30791 Functional test - Add new test 'FO > User account > Order history > Download invoice'
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/02_reorderFromOrderList.ts
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/03_downloadInvoice.ts
  tests/UI/pages/FO/myAccount/orderHistory.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#30795 Functional tests - Add new test 'FO > User account > Order history > Order details > Download invoice'
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/01_reorderFromOrderDetail.ts
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/02_downloadInvoice.ts
  tests/UI/pages/FO/myAccount/orderDetails.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#30801 Use packagist to download prestashop/autoload
  composer.json
  composer.lock
Labels: Improvement, develop

#28642 Feature/migrate merchandise return view 1
  admin-dev/themes/new-theme/scss/components/_form.scss
  src/Adapter/Form/ChoiceProvider/OrderReturnStateChoiceProvider.php
  src/Adapter/Order/Repository/OrderRepository.php
  src/Adapter/OrderReturn/CommandHandler/UpdateOrderReturnStateHandler.php
  src/Adapter/OrderReturn/QueryHandler/GetOrderReturnForEditingHandler.php
  src/Adapter/OrderReturn/Repository/OrderReturnRepository.php
  src/Adapter/OrderReturn/Validator/OrderReturnValidator.php
  src/Adapter/OrderReturnState/Repository/OrderReturnStateRepository.php
  src/Core/Domain/OrderReturn/Command/UpdateOrderReturnStateCommand.php
  src/Core/Domain/OrderReturn/CommandHandler/UpdateOrderReturnStateHandlerInterface.php
  src/Core/Domain/OrderReturn/Exception/OrderReturnConstraintException.php
  src/Core/Domain/OrderReturn/Exception/OrderReturnException.php
  src/Core/Domain/OrderReturn/Exception/OrderReturnNotFoundException.php
  src/Core/Domain/OrderReturn/Exception/OrderReturnOrderStateConstraintException.php
  src/Core/Domain/OrderReturn/Exception/UpdateOrderReturnException.php
  src/Core/Domain/OrderReturn/Query/GetOrderReturnForEditing.php
  src/Core/Domain/OrderReturn/QueryHandler/GetOrderReturnForEditingHandlerInterface.php
  src/Core/Domain/OrderReturn/QueryResult/OrderReturnForEditing.php
  src/Core/Domain/OrderReturn/ValueObject/OrderReturnId.php
  src/Core/Exception/NotImplementedException.php
  src/Core/Form/IdentifiableObject/DataHandler/OrderReturnFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/OrderReturnFormDataProvider.php
  src/Core/Grid/Definition/Factory/MerchandiseReturnGridDefinitionFactory.php
  src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/MerchandiseReturnController.php
  src/PrestaShopBundle/Form/Admin/Sell/CustomerService/MerchandiseReturn/OrderReturnType.php
  src/PrestaShopBundle/Form/Admin/Type/LinkPreviewType.php
  src/PrestaShopBundle/Form/Admin/Type/TextPreviewType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer_service/merchandise_return.yml
  src/PrestaShopBundle/Resources/config/services/adapter/form.yml
  src/PrestaShopBundle/Resources/config/services/adapter/order.yml
  src/PrestaShopBundle/Resources/config/services/adapter/order_return.yml
  src/PrestaShopBundle/Resources/config/services/adapter/order_return_state.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_handler.yml
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
  templates/bundles/PrestaShopBundle/Admin/Sell/CustomerService/OrderReturn/Blocks/form.html.twig
  templates/bundles/PrestaShopBundle/Admin/Sell/CustomerService/OrderReturn/edit.html.twig
  tests/Integration/Adapter/Customer/Repository/CustomerRepositoryTest.php
  tests/Integration/Adapter/Order/Repository/OrderRepositoryTest.php
  tests/Integration/Adapter/OrderReturn/Repository/OrderReturnRepositoryTest.php
  tests/Integration/Adapter/OrderReturnState/Repository/OrderReturnStateRepositoryTest.php
  tests/Integration/Behaviour/Features/Context/Domain/OrderReturnFeatureContext.php
  tests/Integration/Behaviour/Features/Context/OrderReturnFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/OrderReturn/order_return_management.feature
  tests/Integration/Behaviour/behat.yml
  tests/Unit/Core/Domain/OrderReturn/QueryResult/OrderReturnForEditingReturnTest.php
  tests/Unit/Core/Domain/OrderReturn/ValueObject/OrderReturnIdTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/OrderReturnFormDataProviderTest.php
Labels: Waiting for wording, develop, Refactoring, migration

#29421 Remove empty category blocks in module manager
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/grid_manage_empty.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Module/manage.html.twig
Labels: Improvement, QA ✔️, develop

#30810 Adapt automated tests to the fix of #29421
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/02_filterModulesByCategories.ts
  tests/UI/pages/BO/modules/moduleManager/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#30832 Fix nightly 12 - 01 - Fix error in FO > Download invoice test
  tests/UI/campaigns/functional/FO/03_userAccount/01_creditSlips/01_consultCreditSlip.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#30689 Use Symfony HttpClient inside WebserviceController instead of Guzzle
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceController.php
Labels: QA ✔️, develop, Refactoring

#30799 Fix GetResponseEvent deprecations
  src/Adapter/Security/Admin.php
  src/Adapter/Security/SslMiddleware.php
  src/PrestaShopBundle/EventListener/LegacyParametersListener.php
  src/PrestaShopBundle/EventListener/LegacyUrlListener.php
  src/PrestaShopBundle/EventListener/TokenizedUrlsListener.php
  src/PrestaShopBundle/EventListener/UserLocaleListener.php
  tests/Integration/Utility/AdapterSecurityAdmin.php
Labels: Improvement, QA ✔️, develop

#30225 add modern and active Sortable library
  js/vendor/Sortable.min.js
Labels: QA ✔️, develop, Refactoring, Developer Feature, Needs documentation

#28521 Remove final class from attachment uploader
  src/Adapter/File/Uploader/AttachmentFileUploader.php
Labels: Improvement, develop

#30746 Add sponsor company to PR description
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improvement, 8.0.x

#30809 Functional Tests : Migration TS (`@pages\BO` : Part 1)
  tests/UI/campaigns/functional/BO/02_orders/01_orders/01_helpCard.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/02_filterOrders.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/03_exportOrders.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/04_updateStatus.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/05_bulkUpdateOrdersStatus.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/06_bulkOpenInNewTab.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/07_sortOrders.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/04_selectPreviousCarts.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/05_carriersTab.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/06_merchandiseReturnsTab.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/10_changeStatus.ts
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/01_generateInvoiceByDate.ts
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/02_generateInvoiceByStatus.ts
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/01_enableDisableInvoices.ts
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/02_enableDisableTaxBreakdown.ts
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/03_enableDisableProductImage.ts
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/04_invoicePrefix.ts
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/05_enableDisableCurrentYear.ts
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/06_otherOptions.ts
  tests/UI/campaigns/functional/BO/02_orders/03_creditSlips/01_createFilterCreditSlips.ts
  tests/UI/campaigns/functional/BO/02_orders/03_creditSlips/02_sortAndPaginationCreditSlips.ts
  tests/UI/campaigns/functional/BO/02_orders/03_creditSlips/03_generateCreditSlipsByDate.ts
  tests/UI/campaigns/functional/BO/02_orders/03_creditSlips/04_creditSlipOptions.ts
  tests/UI/campaigns/functional/BO/02_orders/04_deliverySlips/01_generateDeliverySlipByDate.ts
  tests/UI/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/02_deliverySlipNumber.ts
  tests/UI/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/03_enableDisableProductImage.ts
  tests/UI/campaigns/functional/BO/04_customers/03_outstanding/02_viewOrder.ts
  tests/UI/campaigns/functional/BO/04_customers/03_outstanding/03_viewInvoice.ts
  tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/01_merchandiseReturnOptions.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/statuses/01_CRUDOrderStatus.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/employees/02_CRUDEmployee.ts
  tests/UI/campaigns/functional/FO/03_userAccount/01_creditSlips/01_consultCreditSlip.ts
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/04_sendMessage.ts
  tests/UI/campaigns/functional/FO/03_userAccount/merchandiseReturns/01_consultReturnDetails.ts
  tests/UI/campaigns/functional/FO/03_userAccount/merchandiseReturns/02_checkOrderReturnPDF.ts
  tests/UI/campaigns/productV2/functional/05_CRUDVirtualProduct.ts
  tests/UI/campaigns/sanity/02_ordersBO/01_filterOrders.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/orders/add.ts
  tests/UI/pages/BO/orders/index.ts
  tests/UI/pages/BO/orders/view/customerBlock.ts
  tests/UI/pages/BO/orders/view/messagesBlock.ts
  tests/UI/pages/BO/orders/view/paymentBlock.ts
  tests/UI/pages/BO/orders/view/productsBlock.ts
  tests/UI/pages/BO/orders/view/tabListBlock.ts
  tests/UI/pages/BO/orders/view/viewOrderBasePage.ts
  tests/UI/pages/BO/quickAccess/add.ts
  tests/UI/pages/BO/quickAccess/index.ts
  tests/UI/pages/BO/shipping/carriers/index.ts
  tests/UI/pages/BO/shipping/preferences/index.ts
  tests/UI/pages/commonPage.ts
Labels: Improvement, TE, develop, E2E Tests

#30588 Load module autoloaders and service configurations before the core Symfony compiler passes are executed
  src/Adapter/ContainerBuilder.php
  src/PrestaShopBundle/PrestaShopBundle.php
Labels: Improvement, QA ✔️, develop

#30118 Fix potential warning on getPosition method of Module class
  classes/module/Module.php
Labels: QA ✔️, develop, Bug fix

#30826 Functional Tests : Migration TS (`@commonTests/FO/*`)
  tests/UI/campaigns/functional/BO/02_orders/01_orders/04_updateStatus.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/05_bulkUpdateOrdersStatus.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/06_bulkOpenInNewTab.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/09_viewGuest.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/10_pagination.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/05_selectPreviousOrders.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/01_customerBlock.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/02_productBlock.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/03_statusTab.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/04_documentsTab.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/05_carriersTab.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/06_merchandiseReturnsTab.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/07_messagesBlock.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/08_paymentBlock.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/09_addDiscount.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/10_changeStatus.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/11_checkInvoice.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/12_checkMultiInvoice.ts
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/01_enableDisableInvoices.ts
  tests/UI/campaigns/functional/BO/02_orders/02_invoices/03_invoiceOptions/06_otherOptions.ts
  tests/UI/campaigns/functional/BO/02_orders/03_creditSlips/01_createFilterCreditSlips.ts
  tests/UI/campaigns/functional/BO/02_orders/03_creditSlips/02_sortAndPaginationCreditSlips.ts
  tests/UI/campaigns/functional/BO/02_orders/03_creditSlips/03_generateCreditSlipsByDate.ts
  tests/UI/campaigns/functional/BO/02_orders/03_creditSlips/04_creditSlipOptions.ts
  tests/UI/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/02_deliverySlipNumber.ts
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/02_sortAndPagination.ts
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/03_viewCarts.ts
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/05_deleteAbandonedCarts.ts
  tests/UI/campaigns/functional/BO/04_customers/03_outstanding/02_viewOrder.ts
  tests/UI/campaigns/functional/BO/04_customers/03_outstanding/03_viewInvoice.ts
  tests/UI/campaigns/functional/BO/04_customers/03_outstanding/04_pagination.ts
  tests/UI/campaigns/functional/BO/04_customers/03_outstanding/05_sortFilterOutstanding.ts
  tests/UI/campaigns/functional/FO/01_login/01_passwordReminder.ts
  tests/UI/campaigns/functional/FO/02_headerAndFooter/02_checkLinksInFooter.ts
  tests/UI/campaigns/functional/FO/03_userAccount/01_creditSlips/01_consultCreditSlip.ts
  tests/UI/campaigns/functional/FO/03_userAccount/01_editInformation.ts
  tests/UI/campaigns/functional/FO/03_userAccount/02_CRUDAddress.ts
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_consultOrderList.ts
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/01_reorderFromOrderDetail.ts
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/02_downloadInvoice.ts
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/02_reorderFromOrderList.ts
  tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/03_downloadInvoice.ts
  tests/UI/campaigns/functional/FO/03_userAccount/03_viewVouchers.ts
  tests/UI/campaigns/functional/FO/03_userAccount/merchandiseReturns/01_consultReturnDetails.ts
  tests/UI/campaigns/functional/FO/03_userAccount/merchandiseReturns/02_checkOrderReturnPDF.ts
  tests/UI/commonTests/FO/account.ts
  tests/UI/commonTests/FO/order.ts
  tests/UI/commonTests/FO/shoppingCart.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#29381 Allow blank value for mobile phone
  src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php
Labels: QA ✔️, develop, Bug fix

#28502 Fix showing price of customized products in Order Confirmation page
  src/Adapter/Presenter/Order/OrderLazyArray.php
Labels: QA ✔️, develop, Bug fix

#29837 Avoid possibility to create product with combinations when combinations feature is disabled
  src/Core/Form/ChoiceProvider/ProductTypeChoiceProvider.php
  src/PrestaShopBundle/Resources/config/services/core/form/choice_provider.yml
Labels: QA ✔️, 8.0.x, Bug fix

#29488 Module translations no longer take translations from another lang if its default one.
  controllers/admin/AdminTranslationsController.php
Labels: QA ✔️, 8.0.x, Bug fix

#30755 Functional tests - Add new test 'Duplicate product V2'
  tests/UI/campaigns/productV2/functional/07_duplicateProduct.ts
  tests/UI/campaigns/productV2/sanity/05_deleteProduct.ts
  tests/UI/pages/BO/catalog/productsV2/add/index.ts
  tests/UI/pages/BO/catalog/productsV2/index.ts
Labels: TE, develop, Refactoring, E2E Tests

#30857 Transform feature request template from GitHub issues into "Idea" on Discussions
  .github/DISCUSSION_TEMPLATE/ideas.yml
  .github/ISSUE_TEMPLATE/2_feature_request.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: Improvement, develop

#28946 Show errors when installing a module fails
  install-dev/theme/js/process.js
Labels: QA ✔️, develop, Bug fix

#30860 Merge 8.0.X into develop
  src/PrestaShopBundle/EventListener/UserLocaleListener.php
  src/PrestaShopBundle/Resources/config/services/bundle/event_listener.yml
Labels: develop, Bug fix

#30415 Fix applying special char on translations
  classes/ObjectModel.php
  classes/controller/AdminController.php
  classes/controller/Controller.php
  classes/module/Module.php
  controllers/admin/AdminAttributesGroupsController.php
  controllers/admin/AdminFeaturesController.php
  controllers/admin/AdminGroupsController.php
  controllers/admin/AdminLoginController.php
  controllers/admin/AdminShopController.php
  src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php
  tests/Integration/Classes/ObjectModelTest.php
  tests/Integration/Classes/controller/AdminControllerTest.php
  tests/Integration/Classes/module/ModuleTest.php
  tests/Integration/PrestaShopBundle/TranslationIntegrationTest.php
Labels: QA ✔️, develop, 8.0.x, Bug fix, Topwatchers, Wording ✔️

#30652 GA : YAML Lint (YamlLint Check) : Node.js 12 actions are deprecated
  .github/workflows/lint.yml
Labels: Improvement, develop

#30158 Disable access to the customer groups page when this feature is disabled
  controllers/admin/AdminGroupsController.php
Labels: QA ✔️, Waiting for wording, develop, Bug fix, Hacktoberfest

#30831 Fix text-preview widget to show combination names in list
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: QA ✔️, develop, Bug fix

#29647 BO - Import files - Do not show generated csv files from import/csvfromexcel folder in history of uploaded files
  src/Core/Import/File/FileFinder.php
  tests/Integration/Core/Import/File/FileFinderTest.php
Labels: QA ✔️, 8.0.x, Bug fix

#29358 Fix price formatting in MoneyType
  src/Adapter/Currency/CommandHandler/AbstractCurrencyHandler.php
  src/Adapter/Currency/CommandHandler/AddOfficialCurrencyHandler.php
  src/Adapter/Currency/CommandHandler/AddUnofficialCurrencyHandler.php
  src/Adapter/Currency/QueryHandler/GetCurrencyForEditingHandler.php
  src/Adapter/Currency/Repository/CurrencyRepository.php
  src/Core/Localization/Specification/Price.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php
  src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php
  src/PrestaShopBundle/Resources/config/services/adapter/currency.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_extension.yml
  src/PrestaShopBundle/Resources/config/services/core/currency.yml
  tests/Unit/Core/Localization/Currency/PatternTransformerTest.php
  tests/Unit/PrestaShopBundle/Form/Admin/Extension/CustomMoneyTypeTest.php
Labels: QA ✔️, 8.0.x, Bug fix

#29016 Improve quantity check for Product and Cart
  controllers/front/CartController.php
  themes/_core/js/cart.js
Labels: Improvement, QA ✔️, develop, Bug fix, Front-end, Shopping carts FO, Back-end

#30885 Fix package updater
  .github/workflows/cron_php_update_modules.yml
Labels: develop, Bug fix

#29944 Use relative urls for Quick Access menu
  classes/QuickAccess.php
Labels: QA ✔️, develop, Bug fix

#30772 Allow unselecting default category in category tree
  admin-dev/themes/new-theme/js/pages/product/components/categories/categories-manager.ts
  admin-dev/themes/new-theme/js/pages/product/components/categories/category-tree-selector.ts
  admin-dev/themes/new-theme/js/pages/product/components/categories/tags-renderer.ts
Labels: Improvement, QA ✔️, develop

#30906 Fix a typo in the profiler
  tools/profiling/templates/run.tpl
Labels: develop, Bug fix

#30907 Package updater fixes
  .github/workflows/cron_php_update_modules.yml
  .github/workflows/cron_update_modules/script.php
Labels: develop, Bug fix

#30665 Allow override.css to be used in the new back office theme
  classes/controller/AdminController.php
Labels: Improvement, QA ✔️, develop

#30886 Functional tests - Fix CRUDCarrier test
  tests/UI/pages/BO/shipping/carriers/add.ts
Labels: TE, develop, Refactoring, E2E Tests

#28720 Avoid clear ranges when click on "Free shipping"
  js/admin/carrier_wizard.js
Labels: QA ✔️, PM ✔️, develop, Bug fix

#30541 improvement(product): speedup product delete
  classes/Product.php
Labels: Improvement, QA ✔️, develop

#30915 Fix the PR table in the package updater script
  .github/workflows/cron_update_modules/script.php
Labels: develop, Bug fix

#30900 Adding feature flag for catalog price rules and cart rules
  classes/lang/KeysReference/FeatureFlagLang.php
  install-dev/data/xml/feature_flag.xml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/cart_rule.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/catalog_price_rule.yml
Labels: Improvement, QA ✔️, develop

#30926 Adapt automated tests to the fix of #30846
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/02_filterModulesByCategories.ts
  tests/UI/data/demo/moduleCategories.js
  tests/UI/pages/BO/modules/moduleManager/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#30846 Refactor module manager
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/dropdown_categories.html.twig
  src/PrestaShopBundle/Service/DataProvider/Admin/CategoriesProvider.php
  tests/Unit/PrestaShopBundle/Service/DataProvider/Admin/CategoriesProviderTest.php
Labels: Improvement, QA ✔️, develop, Refactoring, Module manager

#30522 Fix : Allow front product controller breadcrumb function override
  controllers/front/ProductController.php
Labels: QA ✔️, develop, Refactoring

#30075 Improve cart recovery and show proper errors.
  classes/controller/FrontController.php
Labels: Improvement, QA ✔️, PM ✔️, develop, Wording ✔️

#29340 Duplicated join in query.
  classes/Hook.php
Labels: QA ✔️, develop, Bug fix

#30918 Change icon of module with missing logo
  .gitignore
  classes/controller/AdminController.php
  img/module/default.png
  img/module/index.php
  src/Adapter/Module/Module.php
Labels: Improvement, QA ✔️, develop

#30806 Rename SpecificationType to Details type and whole namespace
  admin-dev/themes/new-theme/js/pages/product/edit/index.ts
  admin-dev/themes/new-theme/js/pages/product/edit/product-details-manager.ts
  admin-dev/themes/new-theme/js/pages/product/product-map.ts
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/CustomizationFieldsCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/FeatureValuesCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductAttachmentsCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/UpdateProductCommandsBuilder.php
  src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php
  src/Core/Grid/Definition/Factory/ProductGridDefinitionFactory.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationFormType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Details/CustomizationsType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Details/DetailsType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Details/FeatureValueType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Details/FeaturesType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Details/ReferencesType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/EditProductFormType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/header-details.html.twig
  tests/Integration/PrestaShopBundle/Controller/Sell/Catalog/ProductControllerTest.php
  tests/UI/pages/BO/catalog/productsV2/add/detailsTab.ts
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/CustomizationFieldsCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/FeatureValuesCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductAttachmentsCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/UpdateProductCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProviderTest.php
  tests/Unit/PrestaShopBundle/Form/Admin/Sell/Product/Details/DetailsTypeTest.php
  tests/Unit/PrestaShopBundle/Form/Admin/Sell/Product/Details/FeaturesTypeTest.php
Labels: develop, Refactoring

#29570 Fix availability structured data
  src/Adapter/Presenter/Product/ProductLazyArray.php
Labels: Improvement, QA ✔️, develop

#30408 Add getters for controller objects
  controllers/front/CmsController.php
  controllers/front/OrderConfirmationController.php
  controllers/front/ProductController.php
  controllers/front/listing/CategoryController.php
  controllers/front/listing/ManufacturerController.php
  controllers/front/listing/SupplierController.php
Labels: develop, Refactoring

#30948 Restore original module action order
  src/Adapter/Module/AdminModuleDataProvider.php
Labels: QA ✔️, PM ✔️, develop, Bug fix

#30946 Delete old module manager JS files
  admin-dev/themes/default/js/bundle/module/loader.js
  admin-dev/themes/default/js/bundle/module/module.js
  admin-dev/themes/default/js/bundle/module/module_card.js
Labels: QA ✔️, develop, Refactoring

#30954 Simplify text in CONTRIBUTING file
  CONTRIBUTING.md
Labels: Improvement, develop

#30730 Changing wording and adding text helper for product name error input
  src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/HeaderType.php
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
Labels: QA ✔️, develop, Bug fix, Wording ✔️

#28070 Add new order - Cart rule description is not correct
  classes/Cart.php
  tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php
Labels: QA ✔️, develop, Bug fix

#30961 Adapt automated tests to the fix of #28070
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/07_searchAddRemoveVoucher.ts
  tests/UI/pages/BO/catalog/discounts/index.js
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#30962 Module from theme with tab using SF routing fails after enabling the theme
  classes/controller/AdminController.php
  src/Core/Module/ModuleManager.php
Labels: QA ✔️, 8.0.x, Bug fix

#30966 Avoid potencial fatal error in `Link::getCategoryLink`
  classes/Link.php
Labels: develop, Refactoring

#30959 Fix typo in getCombinationIdsAction annotation and simplify js selector
  admin-dev/themes/new-theme/js/pages/product/components/combination-list/bulk-choices-selector.ts
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php
Labels: QA ✔️, develop, Bug fix

#30808 Remove images from shop when deleting product from shop
  src/Adapter/Product/Image/CommandHandler/SetProductImagesForAllShopHandler.php
  src/Adapter/Product/Image/Repository/ProductImageMultiShopRepository.php
  src/Adapter/Product/Shop/CommandHandler/DeleteProductFromShopsHandler.php
  src/Adapter/Product/Update/ProductShopUpdater.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/add_multishop_image.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/delete_multishop_image.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature
Labels: QA ✔️, develop, Bug fix

#30947 Fix doubled message on module upload
  admin-dev/themes/new-theme/js/pages/module/controller.js
  controllers/front/listing/BestSalesController.php
Labels: QA ✔️, develop, Bug fix, Refactoring

#30986 Merge 8.0.x into develop 20/01/23
  classes/Customer.php
  classes/ObjectModel.php
  classes/controller/AdminController.php
  classes/controller/Controller.php
  classes/module/Module.php
  controllers/admin/AdminAttributesGroupsController.php
  controllers/admin/AdminFeaturesController.php
  controllers/admin/AdminGroupsController.php
  controllers/admin/AdminLoginController.php
  controllers/admin/AdminShopController.php
  src/Adapter/Currency/CommandHandler/AbstractCurrencyHandler.php
  src/Adapter/Currency/CommandHandler/AddOfficialCurrencyHandler.php
  src/Adapter/Currency/CommandHandler/AddUnofficialCurrencyHandler.php
  src/Adapter/Currency/QueryHandler/GetCurrencyForEditingHandler.php
  src/Adapter/Currency/Repository/CurrencyRepository.php
  src/Core/Import/File/FileFinder.php
  src/Core/Localization/Specification/Price.php
  src/Core/Module/ModuleManager.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php
  src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php
  src/PrestaShopBundle/Resources/config/services/adapter/currency.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_extension.yml
  src/PrestaShopBundle/Resources/config/services/core/currency.yml
  src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php
  tests/Integration/Classes/ObjectModelTest.php
  tests/Integration/Classes/controller/AdminControllerTest.php
  tests/Integration/Classes/module/ModuleTest.php
  tests/Integration/Core/Import/File/FileFinderTest.php
  tests/Integration/PrestaShopBundle/TranslationIntegrationTest.php
  tests/Unit/Core/Localization/Currency/PatternTransformerTest.php
  tests/Unit/PrestaShopBundle/Form/Admin/Extension/CustomMoneyTypeTest.php
Labels: develop, Bug fix

#30996 Fix sql request when fetching all products of a shop group
  src/Core/Grid/Query/ProductQueryBuilder.php
Labels: develop, Bug fix

#30971 Use PrestaShop's jwt repository
  composer.json
  composer.lock
Labels: Improvement, develop

#30936 Simplify stock_threshold_alert field in UpdateProductCommand and UpdateCombinationCommand
  admin-dev/themes/new-theme/js/pages/product/combination/bulk.ts
  src/Adapter/Product/Combination/Update/Filler/StockInformationFiller.php
  src/Adapter/Product/Update/Filler/StockInformationFiller.php
  src/Core/Domain/Product/Combination/Command/UpdateCombinationCommand.php
  src/Core/Domain/Product/Command/UpdateProductCommand.php
  src/Core/Domain/Product/Stock/ValueObject/LowStockThreshold.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/UpdateCombinationCommandsBuilder.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/UpdateProductCommandsBuilder.php
  src/Core/Form/IdentifiableObject/DataFormatter/BulkCombinationFormDataFormatter.php
  src/Core/Form/IdentifiableObject/DataProvider/BulkCombinationFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/BulkCombinationStockType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/LowStockThresholdType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/UpdateCombinationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_multishop_stock.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_stock.feature
  tests/Unit/Adapter/Product/Combination/Update/Filler/StockInformationFillerTest.php
  tests/Unit/Adapter/Product/Update/Filler/StockInformationFillerTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/UpdateCombinationCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/UpdateProductCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataFormatter/BulkCombinationFormDataFormatterTest.php
Labels: QA ✔️, develop, Refactoring

#30169 Skip admin IP check when maintenance mode is enabled
  admin-dev/themes/default/template/header.tpl
  admin-dev/themes/new-theme/template/layout.tpl
  classes/controller/AdminController.php
  classes/controller/FrontController.php
  controllers/admin/AdminLegacyLayoutController.php
  install-dev/data/xml/configuration.xml
  src/Adapter/Shop/MaintenanceConfiguration.php
  src/PrestaShopBundle/Bridge/Smarty/ToolbarFlagsConfigurator.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/General/MaintenanceType.php
  tests/Unit/Adapter/Shop/MaintenanceConfigurationTest.php
Labels: QA ✔️, develop, Feature, Wording ✔️, Key feature

#31014 Functional Tests : Fixed UI Test 'Enable/Disable Shop'
  tests/UI/campaigns/functional/BO/13_shopParameters/01_general/maintenance/01_enableDisableShop.ts
  tests/UI/pages/BO/shopParameters/general/maintenance/index.ts
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#30889 Functional tests - Add new test 'enable/disable new product page'
  tests/UI/campaigns/functional/BO/14_advancedParameters/11_newAndExperimentalFeatures/01_enableDisableExperimentalProductV2.ts
Labels: TE, develop, Refactoring, E2E Tests

#30933 Functional tests - Refacto 'Change position of attributes & values'
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/02_changePosition.ts
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/attributes/03_changePosition.ts
Labels: TE, develop, Refactoring, E2E Tests

#30993 Fix issue #26568 about customer blank schema
  classes/webservice/WebserviceOutputBuilder.php
Labels: QA ✔️, 8.0.x, Bug fix

#30881 Load combination choices depending on shop selection in SpecificPrice form
  admin-dev/themes/new-theme/js/fos_js_routes.json
  admin-dev/themes/new-theme/js/pages/specific-price/form/combination-selector.ts
  admin-dev/themes/new-theme/js/pages/specific-price/form/index.ts
  admin-dev/themes/new-theme/js/pages/specific-price/specific-price-map.ts
  src/Adapter/Product/Combination/Repository/CombinationRepository.php
  src/Core/Domain/Product/Combination/Query/SearchProductCombinations.php
  src/Core/Domain/Product/Combination/QueryHandler/SearchProductCombinationsHandler.php
  src/Core/Domain/Product/Combination/QueryHandler/SearchProductCombinationsHandlerInterface.php
  src/Core/Domain/Product/Combination/QueryResult/ProductCombination.php
  src/Core/Domain/Product/Combination/QueryResult/ProductCombinationsCollection.php
  src/Core/Form/IdentifiableObject/DataProvider/SpecificPriceFormDataProvider.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/SpecificPriceCombinationListener.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/SpecificPriceType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/product_v2/product.yml
  src/PrestaShopBundle/Resources/config/services/adapter/product/_combination.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/product.yml
  tests/Integration/Behaviour/Features/Context/AttributeFeatureContext.php
  tests/Integration/Behaviour/Features/Context/AttributeGroupFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/AttributeGroupFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/SearchProductCombinationFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/search_product_combinations.feature
  tests/Integration/Behaviour/behat.yml
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/SpecificPriceFormDataProviderTest.php
Labels: QA ✔️, develop, Bug fix

#30945 Update workflows events to ignore tests PRs on pull requests
  .github/workflows/behaviour.yml
  .github/workflows/integration.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .github/workflows/php.yml
Labels: Improvement, develop, CI/CD

#31011 Functional tests - Add new test 'Check notifications in BO'
  tests/UI/campaigns/functional/BO/15_header/08_checkNotifications.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/customerService/orderMessages/add.js
  tests/UI/pages/commonPage.ts
Labels: QA ✔️, TE, develop, E2E Tests

#31037 Merge 8.0.x into develop 26 01 2023
  classes/webservice/WebserviceOutputBuilder.php
Labels: develop, Bug fix

#31031 Deprecate renderForm methods
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/MetaController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/PreferencesController.php
  src/PrestaShopBundle/Controller/Admin/Improve/Shipping/PreferencesController.php
Labels: Improvement, develop

#31004 Migrate security function hash / hashIV / generatePassword
  classes/Tools.php
  src/Core/Security/Hashing.php
  src/Core/Security/OpenSsl/OpenSSL.php
  src/Core/Security/OpenSsl/OpenSSLInterface.php
  src/Core/Security/PasswordGenerator.php
  tests/Unit/Core/Security/HashingTest.php
  tests/Unit/Core/Security/PasswordGeneratorTest.php
Labels: QA ✔️, develop, Refactoring

#31040 Add required jobs as skipped for UI tests
  .github/workflows/behaviour-skip.yml
  .github/workflows/behaviour.yml
  .github/workflows/integration-skip.yml
  .github/workflows/js-skip.yml
  .github/workflows/lint-skip.yml
  .github/workflows/php-skip.yml
Labels: Improvement, QA ✔️, develop, CI/CD

#31051 GA Workflows : Make the same name and Matrix for skipped required workflows
  .github/workflows/behaviour-skip.yml
  .github/workflows/integration-skip.yml
  .github/workflows/js-skip.yml
  .github/workflows/lint-skip.yml
  .github/workflows/php-skip.yml
Labels: develop, Bug fix, CI/CD

#31054 Fix behat tests
  tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/AbstractDomainFeatureContext.php
  tests/Integration/Behaviour/Features/Context/LastExceptionTrait.php
  tests/Integration/Behaviour/Features/Context/SharedStorageTrait.php
  tests/Integration/Behaviour/Features/Scenario/Product/update_stock.feature
Labels: develop, Refactoring

#31043 Fix deprecated function usage
  config/smartyadmin.config.inc.php
  config/smartyfront.config.inc.php
Labels: Improvement, develop

#30845 Functional tests - Add new test 'FO > Home page > Display some products'
  tests/UI/campaigns/functional/BO/11_international/04_translations/01_modifyTranslation.ts
  tests/UI/campaigns/functional/FO/06_homePage/02_displaySomeProducts.ts
  tests/UI/pages/FO/home/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#31030 Functional Tests : Migration TS (`@pages\BO` : Part 3)
  tests/UI/campaigns/functional/BO/08_design/04_pages/01_CRUDPageCategory.ts
  tests/UI/campaigns/functional/BO/08_design/04_pages/02_helpCard.ts
  tests/UI/campaigns/functional/BO/08_design/04_pages/categories/01_filterAndQuickEditCategories.ts
  tests/UI/campaigns/functional/BO/08_design/04_pages/categories/02_categoriesBulkActions.ts
  tests/UI/campaigns/functional/BO/08_design/04_pages/categories/03_paginationAndSortCategories.ts
  tests/UI/campaigns/functional/BO/08_design/04_pages/pages/01_filterAndQuickEditPages.ts
  tests/UI/campaigns/functional/BO/08_design/04_pages/pages/02_pagesBulkActions.ts
  tests/UI/campaigns/functional/BO/08_design/04_pages/pages/03_paginationAndSortPages.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/05_import/01_downloadSampleFiles.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/employees/01_filterAndQuickEditEmployees.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/employees/02_CRUDEmployee.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/employees/05_sortAndPagination.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/profiles/01_filterProfiles.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/profiles/02_CRUDProfile.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/08_logs/01_filterSortAndPagination.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/01_CRUDWebservice.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/02_filterAndQuickEditWebservice.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/04_sortPaginationAndBulkActions.ts
  tests/UI/campaigns/functional/FO/03_userAccount/02_CRUDAddress.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/dashboard/index.ts
  tests/UI/pages/BO/design/emailThemes/index.ts
  tests/UI/pages/BO/design/emailThemes/preview.ts
  tests/UI/pages/BO/design/imageSettings/add.ts
  tests/UI/pages/BO/design/imageSettings/index.ts
  tests/UI/pages/BO/design/linkWidgets/add.ts
  tests/UI/pages/BO/design/linkWidgets/index.js
  tests/UI/pages/BO/design/linkWidgets/index.ts
  tests/UI/pages/BO/design/pages/add.ts
  tests/UI/pages/BO/design/pages/index.ts
  tests/UI/pages/BO/design/pages/pageCategory/add.ts
  tests/UI/pages/BO/design/positions/index.ts
  tests/UI/pages/BO/design/themeAndLogo/advancedCustomization/index.ts
  tests/UI/pages/BO/design/themeAndLogo/themeAndLogo/index.ts
  tests/UI/pages/BO/design/themeAndLogo/themeAndLogo/themeAndLogoBasePage.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#31044 Deprecate some useless classes related to legacy upload system
  classes/FileUploader.php
  classes/QqUploadedFileForm.php
  classes/QqUploadedFileXhr.php
Labels: Improvement, QA ✔️, develop, Refactoring, Deprecations

#31006 Fix conversion of hex color codes
  classes/Tools.php
  src/Core/Util/ColorBrightnessCalculator.php
  tests/Unit/Core/Util/ColorBrightnessCalculatorTest.php
Labels: QA ✔️, 8.0.x, Bug fix

#31049 Functional Tests : Migration TS (`@pages\BO` : Part 4)
  tests/UI/campaigns/functional/BO/00_login/01_passwordReminder.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/04_email/03_sortAndPagination.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/05_import/02_importFile.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/employees/01_filterAndQuickEditEmployees.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/employees/02_CRUDEmployee.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/employees/03_employeesBulkActions.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/employees/04_helpCard.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/employees/05_sortAndPagination.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/profiles/01_filterProfiles.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/profiles/02_CRUDProfile.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/profiles/03_helpCard.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/profiles/04_sortProfiles.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/06_team/profiles/05_paginationAndBulkActions.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/07_database/dbBackup/02_paginationAndBulkDelete.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/01_CRUDSqlQuery.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/02_helpCard.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/03_exportSqlQuery.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/07_database/sqlManager/04_filterSortAndPagination.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/08_logs/01_filterSortAndPagination.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/01_CRUDWebservice.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/02_filterAndQuickEditWebservice.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/03_helpCard.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/09_webservice/04_sortPaginationAndBulkActions.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/01_CRUDShopGroups.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/02_filterSortAndPaginationShopGroups.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/03_CRUDShops.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/04_filterSortAndPaginationShops.ts
  tests/UI/campaigns/functional/BO/15_header/07_myProfile.ts
  tests/UI/commonTests/BO/advancedParameters/employee.ts
  tests/UI/commonTests/BO/advancedParameters/setPermissions.ts
  tests/UI/commonTests/BO/advancedParameters/smtp.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/advancedParameters/database/dbBackup/index.ts
  tests/UI/pages/BO/advancedParameters/database/sqlManager/add.ts
  tests/UI/pages/BO/advancedParameters/database/sqlManager/index.ts
  tests/UI/pages/BO/advancedParameters/database/sqlManager/view.ts
  tests/UI/pages/BO/advancedParameters/email/index.ts
  tests/UI/pages/BO/advancedParameters/featureFlag/index.ts
  tests/UI/pages/BO/advancedParameters/import/index.ts
  tests/UI/pages/BO/advancedParameters/logs/index.ts
  tests/UI/pages/BO/advancedParameters/menuTab/index.ts
  tests/UI/pages/BO/advancedParameters/multistore/add.ts
  tests/UI/pages/BO/advancedParameters/multistore/index.ts
  tests/UI/pages/BO/advancedParameters/multistore/shop/add.ts
  tests/UI/pages/BO/advancedParameters/multistore/shop/index.ts
  tests/UI/pages/BO/advancedParameters/multistore/url/addURL.ts
  tests/UI/pages/BO/advancedParameters/multistore/url/index.ts
  tests/UI/pages/BO/advancedParameters/performance/index.ts
  tests/UI/pages/BO/advancedParameters/team/add.ts
  tests/UI/pages/BO/advancedParameters/team/employeeBasePage.ts
  tests/UI/pages/BO/advancedParameters/team/index.ts
  tests/UI/pages/BO/advancedParameters/team/myProfile.ts
  tests/UI/pages/BO/advancedParameters/team/permissions/index.ts
  tests/UI/pages/BO/advancedParameters/team/profiles/add.ts
  tests/UI/pages/BO/advancedParameters/team/profiles/index.ts
  tests/UI/pages/BO/advancedParameters/webservice/add.ts
  tests/UI/pages/BO/advancedParameters/webservice/index.ts
  tests/UI/pages/commonPage.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#31045 Fix deprecated function usage in test function
  tests/Resources/modules/cronjobs/cronjobs.php
Labels: Improvement, develop, Bug fix, BC break

#31046 Minor improvements for Readme.md
  README.md
Labels: Improvement, develop

#31048 Duplicate product multishop (part 1)
  src/Adapter/Product/CommandHandler/BulkDuplicateProductHandler.php
  src/Adapter/Product/ProductDuplicator.php
  src/Adapter/Product/Repository/ProductRepository.php
  src/Adapter/Product/SpecificPrice/Repository/SpecificPriceRepository.php
  src/Adapter/Product/Update/ProductDuplicator.php
  src/Core/Domain/Product/Command/BulkDuplicateProductCommand.php
  src/Core/Domain/Product/Command/DuplicateProductCommand.php
  src/Core/Domain/Product/Exception/CannotDuplicateProductException.php
  src/Core/Domain/Product/Exception/CannotUpdateProductException.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/DetailsAssertionFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/DuplicateProductFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/SpecificPriceContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/VirtualProductFileFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/TaxFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/duplicate_multishop_product.feature
  tests/Integration/Behaviour/Features/Scenario/Product/SpecificPrice/specific_prices_listing.feature
  tests/Integration/Behaviour/Features/Scenario/Product/duplicate_product.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_prices.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_prices_without_states.feature
  tests/Resources/Resetter/TaxesResetter.php
Labels: Improvement, develop, Bug fix, BC break

#31047 Add shop constraint on SetAssociatedProductCategoriesCommand and RemoveAllAssociatedProductCategoriesCommand
  classes/shop/Shop.php
  src/Adapter/Category/Repository/CategoryRepository.php
  src/Adapter/Product/CommandHandler/RemoveAllAssociatedProductCategoriesHandler.php
  src/Adapter/Product/CommandHandler/SetAssociatedProductCategoriesHandler.php
  src/Adapter/Product/QueryHandler/GetProductForEditingHandler.php
  src/Adapter/Product/Repository/ProductMultiShopRepository.php
  src/Adapter/Product/Update/ProductCategoryUpdater.php
  src/Adapter/Product/Update/ProductShopUpdater.php
  src/Core/Domain/Product/Command/RemoveAllAssociatedProductCategoriesCommand.php
  src/Core/Domain/Product/Command/SetAssociatedProductCategoriesCommand.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCategoriesCommandsBuilder.php
  src/PrestaShopBundle/Resources/config/services/adapter/product.yml
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateCategoriesFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePositionFeatureContext.php
  tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_multishop_categories.feature
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCategoriesCommandsBuilderTest.php
Labels: Improvement, develop, Bug fix, BC break

#31060 Deprecate `Tools::getDescriptionClean()`
  classes/Category.php
  classes/Tools.php
Labels: Improvement, develop

#31078 Deprecate Tools::getBytes()
  classes/Tools.php
Labels: Improvement, develop, Deprecations

#30992 Fix customer isLogged property in FO
  classes/Hook.php
  classes/controller/FrontController.php
Labels: QA ✔️, 8.0.x, Bug fix

#28999 Add actionLoggerLogMessage hook
  classes/log/AbstractLogger.php
  install-dev/data/xml/hook.xml
Labels: QA ✔️, develop, Feature, Needs documentation, Needs autoupgrade PR

#31073 Deprecate FrameworkBundleAdminController::configuration
  src/Core/Domain/Configuration/ShopConfigurationInterface.php
  src/PrestaShopBundle/Controller/Admin/CategoryController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/BackupController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmailController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/MetaController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/OrderPreferencesController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/PreferencesController.php
  src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Controller/Admin/ProductImageController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/SupplierController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Controller/Admin/VirtualProductController.php
  src/PrestaShopBundle/Resources/config/services/adapter/shop.yml
  src/PrestaShopBundle/Resources/config/services/bundle/bridge/_smarty.yml
  src/PrestaShopBundle/Resources/config/services/core/help.yml
Labels: Improvement, develop, Bug fix

#31032 Fix LOGO_MAIL in multistore
  classes/Mail.php
Labels: QA ✔️, develop, Bug fix

#30863 Add delete action to module manager
  admin-dev/themes/new-theme/js/components/module-card.ts
  admin-dev/themes/new-theme/js/pages/module/controller.js
  src/Adapter/Module/AdminModuleDataProvider.php
  src/Adapter/Module/Module.php
  src/Core/Module/ModuleManager.php
  src/Core/Module/ModuleManagerInterface.php
  src/PrestaShopBundle/Command/ModuleCommand.php
  src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php
  src/PrestaShopBundle/Event/ModuleManagementEvent.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/modules/_modules.yml
Labels: Improvement, QA ✔️, PM ✔️, develop

#31131 DI improvements 2/2 (follow up f56456cf902c0cbe19b4df3c234354c284bc52de)
  src/Adapter/Twig/LocaleExtension.php
  src/PrestaShopBundle/Resources/config/services/core/domain/country.yml
Labels: Improvement, develop

#31027 Multiple format generation at product creation
  classes/Image.php
  controllers/admin/AdminImagesController.php
  controllers/admin/AdminProductsController.php
  src/Adapter/Image/ImageGenerator.php
  src/Core/Shop/LogoUploader.php
  src/PrestaShopBundle/Resources/config/services/adapter/image.yml
  src/PrestaShopBundle/Resources/config/services/core/shop.yml
Labels: QA ✔️, develop, Feature

#31135 Forced jpg format for images generation
  controllers/admin/AdminImagesController.php
  js/admin/image.js
Labels: Improvement, QA ✔️, develop
