Repository PrestaShop/PrestaShop, pull requests merged in 2023-08, with the labels that each got.

#33061 Webservices tests : CRUD Stores
  tests/UI/campaigns/functional/WS/01_storesCRUD.ts
  tests/UI/data/xml/store.ts
  tests/UI/pages/BO/shopParameters/stores/add.ts
  tests/UI/webservices/baseWs.ts
  tests/UI/webservices/store/storeWS.ts
  tests/UI/webservices/store/storeXml.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#33143 Replace shop list smarty template by twig component
  admin-dev/themes/new-theme/template/layout.tpl
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/shop_list.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/shop_list.html.twig
  src/PrestaShopBundle/Twig/Component/ShopList.php
Labels: QA ✔️, develop, Refactoring, Symfony layout

#32584 Improved the CQRS listing command to track the progress of the development of the CQRS endpoints
  src/PrestaShopBundle/Command/ListCommandsAndQueriesCommand.php
  src/PrestaShopBundle/Exception/DomainClassNameMalformedException.php
  src/PrestaShopBundle/Resources/config/services_dev/bundle/command.yml
  tests/Unit/PrestaShopBundle/Command/ListCommandsAndQueriesCommandTest.php
Labels: Improvement, QA ✔️, develop

#33476 Add image helptext
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationImagesChoiceType.php
Labels: Improvement, QA ✔️, PM ✔️, 8.1.x

#33512 Functional tests - Add new test 'Advanced parameters > Import file'
  tests/UI/campaigns/functional/BO/14_advancedParameters/05_import/02_importFile.ts
  tests/UI/pages/BO/advancedParameters/import/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#33468 Update Keycloak module URL in tests
  tests/UI/data/demo/modules.ts
  tests/UI/package-lock.json
  tests/UI/package.json
  tests/UI/utils/api.ts
  tests/UI/utils/keycloakHelper.ts
Labels: Improvement, develop

#33491 Add low_stock_threshold to fixtures
  install-dev/fixtures/fashion/data/product.xml
  install-dev/fixtures/fashion/data/product_attribute.xml
Labels: QA ✔️, Bug fix, 8.1.x

#33292 Add a check for key generation
  classes/ConfigurationTest.php
  install-dev/controllers/http/system.php
  src/Adapter/Requirement/CheckRequirements.php
Labels: Improvement, QA ✔️, 8.1.x

#33502 Merge `8.1.x` into `develop`
  admin-dev/themes/new-theme/js/pages/product/specific-price/form/combination-selector.ts
  admin-dev/themes/new-theme/js/pages/product/specific-price/form/customer-selector.ts
  classes/Product.php
  classes/Tools.php
  src/Core/Grid/Definition/Factory/ProductGridDefinitionFactory.php
  src/PrestaShopBundle/Form/Admin/Improve/Design/Pages/CmsPageType.php
  src/PrestaShopBundle/Form/Admin/Type/FormattedTextareaType.php
  upload/.htaccess
Labels: Improvement, Waiting for author, develop

#32873 Upgrade cssjanus to 2.1.1
  composer.lock
Labels: Improvement, QA ✔️, develop

#33526 Functional tests - Add new test in 'Advanced parameters > Administration page > General'
  tests/UI/campaigns/functional/BO/14_advancedParameters/03_administration/01_general.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/advancedParameters/administration/index.ts
Labels: TE, develop, Refactoring, E2E Tests

#33336 Replace twig component header
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/template/layout.tpl
  app/config/config.yml
  classes/controller/Controller.php
  phpstan-tmp-legacy-layout-baseline.neon
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/header.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/header.html.twig
  src/PrestaShopBundle/Twig/Component/Header.php
Labels: Improvement, QA ✔️, develop

#33466 Remove remains of AdminCartsController view
  admin-dev/themes/default/template/controllers/carts/helpers/index.php
  admin-dev/themes/default/template/controllers/carts/helpers/view/index.php
  admin-dev/themes/default/template/controllers/carts/helpers/view/view.tpl
  admin-dev/themes/default/template/controllers/carts/index.php
  controllers/admin/AdminCartsController.php
Labels: Waiting for QA, QA ✔️, develop, Refactoring, BC break

#33515 Retry downloading language packs
  classes/Language.php
Labels: Improvement, QA ✔️, 8.1.x

#33533 Improve Makefile usage
  Makefile
Labels: Improvement, QA ✔️, develop

#33532 Nightly : Fixed functional/BO/14*/03*/01*
  tests/UI/campaigns/functional/BO/14_advancedParameters/03_administration/01_general.ts
Labels: TE, develop, Bug fix, E2E Tests

#33379 Make navbar component independent
  admin-dev/themes/new-theme/template/layout.tpl
  phpstan-tmp-legacy-layout-baseline.neon
  src/PrestaShopBundle/Resources/config/services/adapter/nav_bar.yml
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/nav_bar.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/nav_bar.html.twig
  src/PrestaShopBundle/Twig/Component/NavBar.php
Labels: Improvement, Waiting for QA, develop, Waiting for dev

#33531 Functional Tests : BO - Catalog - Products : CRUD virtual product (Add check for email)
  tests/UI/campaigns/productV2/functional/05_CRUDVirtualProduct.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#33537 Functional Tests : Hummingbird - FO - Header and Footer : Change language
  tests/UI/campaigns/functional/FO/hummingbird/02_headerAndFooter/04_changeLanguage.ts
  tests/UI/pages/FO/FObasePage.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#33056 Enable migrated Title page and Remove AdminGendersController
  controllers/admin/AdminGendersController.php
  install-dev/data/xml/feature_flag.xml
  src/PrestaShopBundle/Resources/config/routing/admin/configure/shop_parameters/titles.yml
  tests/Integration/Classes/controller/AdminControllerTest.php
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/03_titles/01_filterTitles.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/03_titles/02_CRUDTitles.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/03_titles/03_bulkDeleteTitles.ts
  tests/UI/pages/BO/shopParameters/customerSettings/titles/add.ts
  tests/UI/pages/BO/shopParameters/customerSettings/titles/index.ts
Labels: QA ✔️, develop, Feature, migration

#33555 Remove duplicates from smarty.config.inc.php
  config/smarty.config.inc.php
Labels: QA ✔️, Refactoring, 8.1.x

#33572 Merge `8.0.x` to `8.1.x`
  docs/CHANGELOG.txt
Labels: Improvement, Waiting for author, 8.1.x

#32992 Symfony 6 - Fix user deprecations
  src/Adapter/Security/Admin.php
  src/PrestaShopBundle/Resources/config/services/bundle/new_api.yml
  src/PrestaShopBundle/Security/Admin/Employee.php
  src/PrestaShopBundle/Security/Admin/EmployeeProvider.php
  src/PrestaShopBundle/Security/OAuth2/Repository/ClientRepository.php
  src/PrestaShopBundle/Security/OAuth2/ResourceServer.php
  src/PrestaShopBundle/Service/DataProvider/UserProvider.php
  tests/UI/data/demo/modules.ts
  tests/UI/pages/BO/shopParameters/customerSettings/titles/index.ts
  tests/Unit/Adapter/Invoice/InvoiceOptionsConfigurationTest.php
  tests/Unit/Adapter/Security/CommandHandler/BulkDeleteCustomersSessionHandlerTest.php
  tests/Unit/Core/Domain/Security/ValueObject/CustomerSessionIdTest.php
  tests/Unit/Core/Domain/Security/ValueObject/EmployeeSessionIdTest.php
  tests/Unit/PrestaShopBundle/Security/OAuth2/Repository/ClientRepositoryTest.php
Labels: QA ✔️, develop, Refactoring

#33463 make search_form twig component independant
  admin-dev/themes/new-theme/template/layout.tpl
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/search_form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/search_form.html.twig
  src/PrestaShopBundle/Twig/Component/SearchForm.php
Labels: QA ✔️, develop, Refactoring

#33024 Add complex query with optional parameters
  app/config/config.yml
  src/PrestaShopBundle/ApiPlatform/Converters/ConverterInterface.php
  src/PrestaShopBundle/ApiPlatform/Converters/StringToIntConverter.php
  src/PrestaShopBundle/ApiPlatform/Provider/QueryProvider.php
  src/PrestaShopBundle/ApiPlatform/Resources/FoundProduct.php
  src/PrestaShopBundle/Resources/config/services/bundle/new_api.yml
  src/PrestaShopBundle/Resources/config/services/bundle/services.yml
  tests/Integration/ApiPlatform/ApiTestCase.php
  tests/Integration/ApiPlatform/GetHookStatusTest.php
  tests/Integration/ApiPlatform/GetHookTest.php
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/01_internalAuthServer/02_resourceEndpoint.ts
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/02_externalAuthServer/02_resourceEndpoint.ts
  tests/Unit/PrestaShopBundle/ApiPlatform/StateProvider/QueryProviderTest.php
Labels: QA ✔️, develop, Feature

#33581 Fix modules from distribution api
  src/Core/Module/ModuleRepository.php
Labels: Waiting for QA, Bug fix, Waiting for dev, 8.1.x

#33593 Fix navbar twig component error
  src/PrestaShopBundle/Resources/config/services/adapter/nav_bar.yml
  src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/nav_bar.html.twig
Labels: develop, Bug fix, Symfony layout

#33563 Fix load JqueryUI on FrontController : load only requested components
  classes/controller/FrontController.php
Labels: QA ✔️, develop, Bug fix, BC break

#33570 Replacing MultistoreHeaderController by a twig component and using it in ToolBar twig component instead
  admin-dev/themes/new-theme/template/layout.tpl
  controllers/admin/AdminLegacyLayoutController.php
  phpstan-tmp-legacy-layout-baseline.neon
  src/Adapter/LegacyContext.php
  src/PrestaShopBundle/Resources/config/services/adapter/services.yml
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/multistore_header.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/toolbar.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/toolbar.html.twig
  src/PrestaShopBundle/Twig/Component/MultistoreHeader.php
  src/PrestaShopBundle/Twig/Component/Toolbar.php
Labels: Improvement, QA ✔️, develop, Symfony layout

#33573 Fix dropExistingForeignKeys method when updating doctrine schema
  src/PrestaShopBundle/Command/UpdateSchemaCommand.php
Labels: QA ✔️, Bug fix, 8.1.x

#32720 Update TranslationToolsBundle to version 6
  composer.json
  composer.lock
  src/Core/Translation/Storage/Extractor/ThemeExtractor.php
Labels: Improvement, QA ✔️, develop

#33324 Remove non responsive component
  admin-dev/themes/default/js/admin-theme.js
  admin-dev/themes/new-theme/js/nav_bar.ts
  admin-dev/themes/new-theme/scss/components/layout/_non_responsive.scss
  admin-dev/themes/new-theme/scss/theme.scss
  admin-dev/themes/new-theme/template/components/layout/non-responsive.tpl
  admin-dev/themes/new-theme/template/layout.tpl
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/non_responsive.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/non_responsive.html.twig
  src/PrestaShopBundle/Twig/Component/NonResponsive.php
Labels: QA ✔️, develop, Refactoring, BC break, Needs documentation

#33232 Remove purpose (activity) of store during install and in config
  install-dev/classes/datas.php
  install-dev/classes/session.php
  install-dev/controllers/console/process.php
  install-dev/controllers/http/configure.php
  install-dev/controllers/http/process.php
  install-dev/data/xml/configuration.xml
  install-dev/theme/views/configure.php
  src/Adapter/Preferences/PreferencesConfiguration.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/General/PreferencesType.php
  src/PrestaShopBundle/Install/Install.php
  tests/Unit/Adapter/Preferences/PreferencesConfigurationTest.php
Labels: QA ✔️, develop, Refactoring, BC break, Needs documentation, Needs autoupgrade PR

#33608 Fix tax detail in invoice
  classes/order/Order.php
Labels: QA ✔️, develop, Bug fix

#33623 Merge 8.1.x to develop
  src/Core/Module/ModuleRepository.php
Labels: Improvement, develop

#33631 Modules tests - Fix 'Modules > Faceted search > Uninstall and delete module''
  tests/UI/campaigns/modules/ps_facetedsearch/01_installation/04_uninstallAndDeleteModule.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests, 8.1.x

#33632 Add useful email variables
  classes/PaymentModule.php
Labels: QA ✔️, Feature, 8.1.x

#32941 getShopLogo remove hasKey usage
  classes/controller/FrontController.php
Labels: QA ✔️, develop, Bug fix

#33643 Do not attempt to rebuild modules list if missing data
  admin-dev/themes/new-theme/js/pages/module/controller.js
Labels: QA ✔️, Bug fix, 8.1.x

#33464 Functional Tests : WS - Products - CRUD
  tests/UI/campaigns/functional/WS/02_productsCRUD.ts
  tests/UI/campaigns/functional/WS/03_storesCRUD.ts
  tests/UI/data/xml/product.ts
  tests/UI/pages/BO/catalog/productsV2/add/descriptionTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/detailsTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/index.ts
  tests/UI/pages/BO/catalog/productsV2/add/optionsTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/pricingTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/seoTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/shippingTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/stocksTab.ts
  tests/UI/pages/BO/catalog/productsV2/index.ts
  tests/UI/utils/xml.ts
  tests/UI/webservices/product/productWs.ts
  tests/UI/webservices/product/productXml.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#33649 Merge `8.1.x` into `develop`
  admin-dev/themes/new-theme/js/pages/module/controller.js
  classes/PaymentModule.php
  classes/order/Order.php
  composer.lock
  src/PrestaShopBundle/Command/UpdateSchemaCommand.php
Labels: Improvement, QA ✔️, develop

#33660 Fix error in the module translation page (old translation system)
  controllers/admin/AdminTranslationsController.php
Labels: QA ✔️, Bug fix, 8.1.x

#33664 Fix(webservice): allow preflight requests
  webservice/dispatcher.php
Labels: develop, Bug fix

#33673 Add discussion in the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improvement, Waiting for QA, develop

#32063 Problems with actionValidateCustomerAddressForm hook
  classes/Hook.php
  classes/form/CustomerAddressForm.php
Labels: QA ✔️, develop, Bug fix

#33633 Fixing Employee Object Creation: Ensuring Correct Data Types for id and id_profile Properties
  classes/Employee.php
Labels: develop, Bug fix

#33675 Add webservice order returns - issue #17753
  classes/webservice/WebserviceRequest.php
Labels: QA ✔️, develop, Feature

#33682 [Twig component] Makes breadcrumbs management independent
  admin-dev/themes/new-theme/template/layout.tpl
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/toolbar.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/toolbar.html.twig
  src/PrestaShopBundle/Twig/Component/Toolbar.php
  src/PrestaShopBundle/Twig/Layout/MenuBuilder.php
  src/PrestaShopBundle/Twig/Layout/MenuLink.php
Labels: Improvement, QA ✔️, develop

#33567 Fix visual issues new product page
  admin-dev/themes/new-theme/js/components/translatable-input.ts
  admin-dev/themes/new-theme/js/pages/product/edit/manager/product-seo-manager.ts
  admin-dev/themes/new-theme/js/pages/product/supplier/product-suppliers-collection.ts
  admin-dev/themes/new-theme/js/pages/product/supplier/product-suppliers-map.ts
  admin-dev/themes/new-theme/scss/components/_delta_quantity.scss
  admin-dev/themes/new-theme/scss/components/_modal.scss
  src/PrestaShopBundle/Form/Admin/Sell/Product/Options/CustomizationFieldType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Options/ProductSupplierType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/SpecificPriceImpactType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/SEO/RedirectOptionType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/StockOptionsType.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/FormTheme/categories.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/FormTheme/product_seo.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: QA ✔️, Bug fix, 8.1.x

#33380 Improve reorder positions on grids
  admin-dev/themes/new-theme/js/components/grid/extension/position-extension.ts
  src/Core/Grid/Definition/Factory/AttributeGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/AttributeGroupGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/CarrierGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/CmsPageCategoryDefinitionFactory.php
  src/Core/Grid/Definition/Factory/CmsPageDefinitionFactory.php
  src/Core/Grid/Definition/Factory/ProductGridDefinitionFactory.php
  src/PrestaShopBundle/Form/Admin/Type/ReorderPositionsButtonType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
Labels: QA ✔️, Bug fix, 8.1.x

#33708 UI Test: delete filter by position on pages and categories
  tests/UI/campaigns/functional/BO/08_design/04_pages/categories/01_filterAndQuickEditCategories.ts
  tests/UI/campaigns/functional/BO/08_design/04_pages/pages/01_filterAndQuickEditPages.ts
Labels: TE, Refactoring, E2E Tests, 8.1.x

#33658 fix: issue when clearing cache with opcache with enable_file_override
  src/Core/Cache/Clearer/CacheClearerChain.php
Labels: QA ✔️, Bug fix, 8.1.x

#33339 Fix symfony legacy route configuration, PART 2
  src/PrestaShopBundle/Command/LegacyLinkLinterCommand.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/attribute.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/cart_rule.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/features.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/monitoring.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products_v2/product.yml
Labels: Improvement, QA ✔️, develop

#33518 Functional Tests : BO - Catalog - Products : Header
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/header-details.html.twig
  tests/UI/campaigns/functional/WS/02_productsCRUD.ts
  tests/UI/campaigns/productV2/functional/01_filterProducts.ts
  tests/UI/campaigns/productV2/functional/02_CRUDStandardProduct.ts
  tests/UI/campaigns/productV2/functional/03_CRUDProductWithCombinations.ts
  tests/UI/campaigns/productV2/functional/04_CRUDPackOfProducts.ts
  tests/UI/campaigns/productV2/functional/05_CRUDVirtualProduct.ts
  tests/UI/campaigns/productV2/functional/06_duplicateProduct.ts
  tests/UI/campaigns/productV2/functional/07_productBulkActions.ts
  tests/UI/campaigns/productV2/functional/08_header.ts
  tests/UI/campaigns/sanity/03_productsBO/02_CRUDStandardProduct.ts
  tests/UI/data/demo/products.ts
  tests/UI/data/types/product.d.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/catalog/productsV2/add/descriptionTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/detailsTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/index.ts
  tests/UI/pages/BO/catalog/productsV2/add/pricingTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/stocksTab.ts
  tests/UI/pages/commonPage.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#32719 Load symfony container in front
  .env
  .env.dist
  .gitignore
  admin-dev/index.php
  app/AdminKernel.php
  app/AppKernel.php
  app/FrontKernel.php
  bin/console
  classes/controller/AdminController.php
  classes/controller/Controller.php
  classes/controller/FrontController.php
  classes/lang/KeysReference/FeatureFlagLang.php
  composer.json
  controllers/admin/DummyAdminController.php
  index.php
  install-dev/controllers/console/process.php
  install-dev/data/xml/feature_flag.xml
  install-dev/init.php
  src/Adapter/ContainerBuilder.php
  src/Core/FeatureFlag/FeatureFlagSettings.php
  src/PrestaShopBundle/PrestaShopBundle.php
  src/PrestaShopBundle/Resources/config/services.yml
  src/PrestaShopBundle/Resources/config/services/front_legacy.yml
  src/PrestaShopBundle/Service/Command/AbstractCommand.php
  tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php
  tests/Integration/Behaviour/Features/Context/OrderFeatureContext.php
  tests/Integration/phpunit-isolated.xml
  tests/Integration/phpunit.xml
  tests/Unit/phpunit.xml
Labels: QA ✔️, develop, Feature, BC break

#33753 Nightly : Fixed `campaigns/modules/ps_facetedsearch/02*/*`
  tests/UI/campaigns/modules/ps_facetedsearch/02_configuration/14_editTemplateProductStockFilter.ts
  tests/UI/campaigns/modules/ps_facetedsearch/02_configuration/15_editTemplateProductBrandFilter.ts
  tests/UI/data/demo/modules.ts
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#33748 Functional Tests : BO - Catalog - Products : Footer
  tests/UI/campaigns/productV2/functional/09_footer.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#33764 Nightly : Fixed URL in @todo
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/01_internalAuthServer/01_authorizationEndpoint.ts
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/01_internalAuthServer/02_resourceEndpoint.ts
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/02_externalAuthServer/01_authorizationEndpoint.ts
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#33746 Fix nightly which was broken due to legacy route configuration
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/attribute.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/attribute_group.yml
Labels: Waiting for author, develop, Bug fix

#33366 Feat(api): add endpoint with complex custom type
  src/PrestaShopBundle/ApiPlatform/DomainSerializer.php
  src/PrestaShopBundle/ApiPlatform/Normalizer/DecimalNumberDenormalizer.php
  src/PrestaShopBundle/ApiPlatform/Normalizer/ObjectDenormalizer.php
  src/PrestaShopBundle/ApiPlatform/Processor/CommandProcessor.php
  src/PrestaShopBundle/ApiPlatform/Provider/QueryProvider.php
  src/PrestaShopBundle/ApiPlatform/Resources/CustomerGroup.php
  src/PrestaShopBundle/Resources/config/services/bundle/new_api.yml
  src/PrestaShopBundle/Resources/config/services/bundle/services.yml
  tests/Integration/ApiPlatform/PostCustomerTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/DomainSerializerTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/StateProvider/QueryProviderTest.php
Labels: QA ✔️, develop, Feature

#33760 Introduce `css component` for `TypeaheadProductCollectionType`
  admin-dev/themes/new-theme/scss/components/_typeahead_product_collection_type.scss
  admin-dev/themes/new-theme/scss/pages/product/product_page.scss
  admin-dev/themes/new-theme/scss/theme.scss
  src/PrestaShopBundle/Form/Admin/Sell/Product/SEO/RedirectOptionType.php
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_seo.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Panels/essentials.html.twig
Labels: Improvement, QA ✔️, develop
