Repository PrestaShop/PrestaShop, pull requests merged in 2023-06, with the labels that each got.

#32781 Update phpunit-speedtrap to 4.0.1
  composer.json
  composer.lock
Labels: Improvement, develop

#32777 fix(ci) backport fixes to github action template from develop
  .github/workflows/cron_update_modules/script.php
Labels: Improvement, 8.0.x

#32756 Functional Tests : Faceted search module - Uninstall and delete module
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/01_modules/08_uploadModule.ts
  tests/UI/campaigns/modules/ps_facetedsearch/01_installation/04_uninstallAndDeleteModule.ts
  tests/UI/data/demo/modules.ts
  tests/UI/data/faker/module.ts
  tests/UI/data/types/module.d.ts
  tests/UI/pages/BO/modules/moduleManager/index.ts
  tests/UI/pages/FO/category/index.ts
Labels: Improvement, QA ✔️, TE, E2E Tests

#32771 Update lcobucci/jwt to 5.0.0
  composer.json
  composer.lock
Labels: Improvement, develop

#32785 Nightly : Add WS & Modules campaigns
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: Improvement, TE, develop, E2E Tests

#32486 Fix license headers
  admin-dev/filemanager/ajax_calls.php
  admin-dev/filemanager/config/config.php
  admin-dev/filemanager/config/index.php
  admin-dev/filemanager/css/index.php
  admin-dev/filemanager/dialog.php
  admin-dev/filemanager/execute.php
  admin-dev/filemanager/force_download.php
  admin-dev/filemanager/img/ico/index.php
  admin-dev/filemanager/img/ico_dark/index.php
  admin-dev/filemanager/img/index.php
  admin-dev/filemanager/include/index.php
  admin-dev/filemanager/include/utils.php
  admin-dev/filemanager/index.php
  admin-dev/filemanager/jPlayer/add-on/index.php
  admin-dev/filemanager/jPlayer/index.php
  admin-dev/filemanager/jPlayer/popcorn/index.php
  admin-dev/filemanager/jPlayer/skin/blue.monday/index.php
  admin-dev/filemanager/jPlayer/skin/index.php
  admin-dev/filemanager/js/index.php
  admin-dev/filemanager/lang/index.php
  admin-dev/filemanager/upload.php
  admin-dev/filemanager/uploader/index.php
  admin-dev/themes/default/css/vendor/index.php
  admin-dev/themes/default/js/vendor/bootstrap/index.php
  admin-dev/themes/default/js/vendor/index.php
  admin-dev/themes/default/scss/vendor/bi-app/index.php
  admin-dev/themes/default/scss/vendor/bootstrap-rtl-sass/index.php
  admin-dev/themes/default/scss/vendor/bootstrap-sass/index.php
  admin-dev/themes/default/scss/vendor/bootstrap-sass/mixins/index.php
  admin-dev/themes/default/scss/vendor/font-awesome/index.php
  admin-dev/themes/default/scss/vendor/index.php
  admin-dev/themes/new-theme/scss/components/_form.scss
  admin-dev/themes/new-theme/scss/components/_modal.scss
  admin-dev/themes/new-theme/webpack.config.js
Labels: Improvement, develop

#32742 Update composer installers
  composer.json
  composer.lock
Labels: Improvement, develop, Bug fix

#32782 Functional tests - Add new tests 'Stock > Sort and pagination movements table'
  admin-dev/themes/new-theme/js/app/widgets/ps-table/ps-sort.vue
  tests/UI/campaigns/functional/BO/03_catalog/08_stocks/02_updateQuantity.ts
  tests/UI/campaigns/functional/BO/03_catalog/08_stocks/movements/02_sortAndPagination.ts
  tests/UI/pages/BO/catalog/stocks/movements/index.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#32780 Update pelago/emogrifier to 7.0.0
  composer.json
  composer.lock
Labels: Improvement, develop

#32347 Use service discovery for form types
  src/PrestaShopBundle/Resources/config/services/bundle/form.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
Labels: Improvement, QA ✔️, develop

#32769 Functional Tests : API : External Auth Server - Resource Endpoint
  tests/UI/README.md
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/02_externalAuthServer/01_authorizationEndpoint.ts
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/02_externalAuthServer/02_resourceEndpoint.ts
  tests/UI/commonTests/BO/modules/moduleManager.ts
  tests/UI/pages/BO/modules/keycloakConnectorDemo/index.ts
  tests/UI/pages/BO/modules/moduleConfiguration/index.ts
  tests/UI/types/global.d.ts
  tests/UI/utils/globals.ts
  tests/UI/utils/keycloakHelper.ts
Labels: Improvement, QA ✔️, TE, E2E Tests

#31151 Remove obsolete enable/disable module on mobile feature, remove mobile_theme feature remains
  admin-dev/themes/new-theme/js/components/module-card.ts
  admin-dev/themes/new-theme/js/pages/module/controller.js
  classes/Cart.php
  classes/Context.php
  classes/Guest.php
  classes/Hook.php
  classes/PaymentModule.php
  classes/controller/FrontController.php
  classes/module/Module.php
  classes/order/Order.php
  controllers/front/CartController.php
  install-dev/data/xml/configuration.xml
  install-dev/data/xml/hook.xml
  src/Adapter/Module/AdminModuleDataProvider.php
  src/Adapter/Module/Module.php
  src/Adapter/Module/ModuleDataProvider.php
  src/Core/Addon/Module/AddonListFilterDeviceStatus.php
  src/Core/Module/EventSubscriber.php
  src/Core/Module/ModuleInterface.php
  src/Core/Module/ModuleManager.php
  src/Core/Module/ModuleManagerInterface.php
  src/PrestaShopBundle/Command/ModuleCommand.php
  src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php
  src/PrestaShopBundle/Event/ModuleManagementEvent.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/modules/_modules.yml
  tests/Resources/modules/ps_banner/ps_banner.php
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/01_modules/04_enableDisableModule.ts
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/01_modules/07_bulkActions.ts
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/02_alerts/01_enableDisableMobile.ts
  tests/UI/campaigns/functional/BO/08_design/01_themeAndLogo/02_pagesConfiguration/01_enableDisableModule.ts
  tests/UI/pages/BO/modules/moduleManager/index.ts
  tests/Unit/Adapter/Module/Configuration/ModuleSelfConfiguratorTest.php
  tests/Unit/Core/Module/ModuleManagerTest.php
Labels: QA ✔️, PM ✔️, develop, Refactoring, Topwatchers, BC break, Needs documentation, Needs autoupgrade PR

#32790 Fix PDF translations in backoffice
  config/smartyadmin.config.inc.php
Labels: QA ✔️, 8.0.x, Bug fix

#32802 Nightly - Split commands for optimizing time
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#32627 Add CTAs for edit pages
  src/PrestaShopBundle/Controller/Admin/Improve/Design/CmsPageController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/SupplierController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Cms/index.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Manufacturer/index.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Suppliers/index.html.twig
Labels: Improvement, QA ✔️, PM ✔️, develop

#32834 Nightly : 8.0.x : Fixed error in package.json
  tests/UI/package.json
Labels: TE, 8.0.x, Bug fix, E2E Tests

#32835 Nightly : 8.1.x : Fixed error in package.json
  tests/UI/package.json
Labels: QA ✔️, TE, Bug fix, E2E Tests, 8.1.x

#32836 Nightly : Develop : Fixed error in package.json
  .github/workflows/cron_nightly_tests_reusable.yml
  tests/UI/package.json
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#30565 Allow only tlsv1.2+ for api calls
  admin-dev/.htaccess
  config/defines.inc.php
  src/Adapter/Security/SslMiddleware.php
  src/PrestaShopBundle/Resources/config/services/adapter/services.yml
  src/PrestaShopBundle/Resources/config/services/bundle/security.yml
  src/PrestaShopBundle/Resources/config/services/core/security.yml
  src/PrestaShopBundle/Security/SslMiddleware.php
  tests/Integration/bootstrap.php
Labels: QA ✔️, develop, Feature, BC break

#32849 Nightly : Fixed functional/BO/04*/01*/08*
  tests/UI/pages/FO/checkout/index.ts
Labels: QA ✔️, TE, Bug fix, E2E Tests

#32736 Replace swift mailer by symfony mailer
  app/AppKernel.php
  app/config/config.yml
  app/config/config_dev.yml
  app/config/config_test.yml
  classes/Mail.php
  classes/PrestaShopLogger.php
  classes/Validate.php
  composer.json
  composer.lock
  src/Core/Email/CyrillicCharactersInEmailValidation.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Email/SmtpConfigurationType.php
  tests/Unit/Adapter/ValidateTest.php
  tests/Unit/Classes/ValidateCoreTest.php
  tests/Unit/Core/Email/CyrillicCharactersInEmailValidationTest.php
Labels: Improvement, QA ✔️, develop, BC break, Key feature, Needs documentation, Needs autoupgrade PR

#32840 Error in cache id naming
  classes/Hook.php
Labels: Waiting for QA, develop, Bug fix, Waiting for dev

#32811 Improve Product::getAnchor()
  classes/Product.php
Labels: Improvement, QA ✔️, develop

#32863 Nightly : Fixed call to campaign Order
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#32446 Remove high DPI images functionality
  classes/Image.php
  controllers/admin/AdminImagesController.php
  controllers/admin/AdminProductsController.php
  controllers/admin/AdminStoresController.php
  controllers/admin/AdminSuppliersController.php
  src/Adapter/Image/ImageGenerator.php
  src/Adapter/Image/ImageRetriever.php
  src/Adapter/Image/Uploader/AbstractImageUploader.php
  src/Adapter/Image/Uploader/ManufacturerImageUploader.php
Labels: QA ✔️, PM ✔️, develop, Refactoring, BC break

#32845 Merge `8.0.x` into `8.1.x`
  config/smarty.config.inc.php
  config/smartyadmin.config.inc.php
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/11_checkInvoice.ts
Labels: Improvement, QA ✔️

#32776 Update soundasleep/html2text to 2.1.0
  composer.json
  composer.lock
  src/Core/MailTemplate/Transformation/HTMLToTextTransformation.php
Labels: Improvement, develop

#32842 Changed error code when access token is invalid
  app/config/config.yml
Labels: QA ✔️, Bug fix

#32861 Fix invalid token in redirection after editing himself
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php
  src/PrestaShopBundle/Service/Routing/Router.php
  tests/Integration/PrestaShopBundle/Controller/Admin/Sell/Order/OrderControllerTest.php
Labels: QA ✔️, develop, Bug fix

#32701 Deleting an attached file from the webservice API does not work
  classes/webservice/WebserviceSpecificManagementAttachments.php
Labels: QA ✔️, develop, Bug fix

#32872 Use laminas/laminas-code 4.11.0 instead of fork of 4.5
  composer.json
  composer.lock
Labels: Improvement, develop

#32884 Error Webservice combinations or categories on a blank schema
  classes/webservice/WebserviceOutputBuilder.php
Labels: QA ✔️, develop, 8.0.x, Bug fix

#32888 Fix link to blog in install
  install-dev/theme/config.php
Labels: QA ✔️, develop, Bug fix

#29391 Fix issue where field updates by api when they are not supposed to
  classes/Customer.php
  classes/Employee.php
Labels: QA ✔️, develop, Bug fix

#32615 Update ImageGenerator resize destination path
  src/Adapter/Image/ImageGenerator.php
  src/Adapter/Product/Image/Uploader/ProductImageUploader.php
Labels: QA ✔️, Bug fix

#29116 Support for PHP 8.2
  .github/workflows/behaviour.yml
  .github/workflows/integration.yml
  .github/workflows/php.yml
  .github/workflows/sanity-productV2.yml
  .github/workflows/sanity.yml
  classes/Address.php
  classes/Cart.php
  classes/PrestaShopLogger.php
  classes/Product.php
  classes/Store.php
  classes/controller/AdminController.php
  classes/controller/Controller.php
  classes/form/FormField.php
  classes/helper/HelperList.php
  classes/module/CarrierModule.php
  classes/module/Module.php
  classes/order/Order.php
  classes/order/OrderInvoice.php
  classes/pdf/HTMLTemplate.php
  classes/tree/Tree.php
  composer.json
  composer.lock
  config/smarty.config.inc.php
  controllers/admin/AdminProductsController.php
  install-dev/index_cli.php
  install-dev/install_version.php
  src/Adapter/Hook/HookDispatcher.php
  src/Adapter/Product/AdminProductDataProvider.php
  src/Core/Util/DateTime/NullDateTime.php
  src/PrestaShopBundle/Bridge/Helper/Listing/FiltersProcessor.php
  src/PrestaShopBundle/Bridge/Smarty/ToolbarFlagsConfigurator.php
  src/PrestaShopBundle/Controller/Admin/WarehouseController.php
  src/PrestaShopBundle/Install/Language.php
  src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
  src/PrestaShopBundle/Security/Admin/EmployeeProvider.php
  tests/Resources/modules/bankwire/bankwire.php
  tests/Resources/modules/cronjobs/cronjobs.php
  tests/Resources/modules/ps_emailsubscription/ps_emailsubscription.php
  tests/Unit/bootstrap.php
  tools/profiling/Controller.php
Labels: QA ✔️, develop, Feature

#32891 Nightly : Move 1.7.8.x to Github Actions
  .github/workflows/cron_nightly_gcp.yml
  .github/workflows/cron_nightly_tests_1.7.8.x.yml
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: Improvement, Waiting for QA, TE, develop, E2E Tests

#32926 Fix updateQuantity PHPDOC
  classes/stock/StockAvailable.php
  src/Adapter/StockManager.php
  src/Core/Stock/StockManager.php
Labels: QA ✔️, develop, Refactoring

#32935 Nightly : 1.7.8.x : Fixed Admin password & Removed sanity:productV2 campaign
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#32916 Remove deprecated functions for Faker V8 and use new functions
  tests/UI/data/faker/CMSpage.ts
  tests/UI/data/faker/address.ts
  tests/UI/data/faker/brandAddress.ts
  tests/UI/data/faker/carrier.ts
  tests/UI/data/faker/cartRule.ts
  tests/UI/data/faker/catalogPriceRule.ts
  tests/UI/data/faker/contact.ts
  tests/UI/data/faker/country.ts
  tests/UI/data/faker/customer.ts
  tests/UI/data/faker/deliverySlipOptions.ts
  tests/UI/data/faker/employee.ts
  tests/UI/data/faker/group.ts
  tests/UI/data/faker/imageType.ts
  tests/UI/data/faker/invoice.ts
  tests/UI/data/faker/message.ts
  tests/UI/data/faker/order.ts
  tests/UI/data/faker/orderStatus.ts
  tests/UI/data/faker/product.ts
  tests/UI/data/faker/productReview.ts
  tests/UI/data/faker/role.ts
  tests/UI/data/faker/sqlQuery.ts
  tests/UI/data/faker/state.ts
  tests/UI/data/faker/store.ts
  tests/UI/data/faker/supplier.ts
  tests/UI/data/faker/tax.ts
  tests/UI/data/faker/taxRule.ts
  tests/UI/data/faker/taxRulesGroup.ts
  tests/UI/data/faker/title.ts
  tests/UI/data/faker/webservice.ts
  tests/UI/data/import/addresses.ts
  tests/UI/data/import/brands.ts
  tests/UI/data/import/customers.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#32927 Remove deprecated actions buttons
  src/PrestaShopBundle/Controller/Admin/Sell/Order/ActionsBarButton.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/ActionsBarButtonInterface.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/ActionsBarButtonsCollection.php
Labels: QA ✔️, develop, Refactoring, BC break

#32163 Remove deprecated method `setPriorities` in class `SpecificPrice`
  classes/SpecificPrice.php
  controllers/admin/AdminProductsController.php
  tests/Resources/modules_tests/override/AdminProductsController.php
  tests/Resources/modules_tests/pscsx32412/override/controllers/admin/AdminProductsController.php
Labels: Improvement, QA ✔️, develop, BC break

#32943 Remove unused symfony librairies
  composer.json
  composer.lock
Labels: Improvement, develop, BC break

#32896 Fix github action runs on 1.7.8.x
  .github/workflows/cron_js_routing.yml
  .github/workflows/integration.yml
  .github/workflows/lint.yml
  .github/workflows/php.yml
  .github/workflows/sanity-72.yml
  .github/workflows/sanity-73.yml
  .github/workflows/sanity-74.yml
  .github/workflows/sanity.yml
  .github/workflows/sanity/setup-apache.sh
  .github/workflows/ui-tests-code-checks.yml
Labels: TE, Bug fix, E2E Tests, 1.7.8.x

#32789 Warning on Modules List page when Distribution API cannot be contacted
  src/Core/Module/ModuleCollection.php
  src/Core/Module/ModuleRepository.php
  src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php
Labels: Improvement, QA ✔️

#32859 Refacto WS tests countries
  tests/UI/campaigns/functional/WS/01_countriesCRUD.ts
  tests/UI/data/xml/country.ts
  tests/UI/package.json
  tests/UI/tsconfig.json
  tests/UI/utils/helpers.ts
  tests/UI/utils/xml.ts
  tests/UI/webservices/baseWs.ts
  tests/UI/webservices/baseXml.ts
  tests/UI/webservices/country/countryWs.ts
  tests/UI/webservices/country/countryXml.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests, 8.1.x

#32596 Fix availability display logic
  src/Adapter/Presenter/Product/ProductLazyArray.php
  tests/Integration/Adapter/Presenter/Product/ProductLazyArrayTest.php
Labels: QA ✔️, 8.0.x, Bug fix

#32956 Override service discovery
  src/PrestaShopBundle/Resources/config/services/bundle/event_listener.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form.yml
Labels: QA ✔️, develop, Bug fix

#32960 Removing guzzle library
  composer.json
  composer.lock
Labels: Improvement, QA ✔️, develop, BC break

#32860 feat(api-platform): api platform documentation spike
  .gitignore
  app/config/security_dev.yml
  src/PrestaShopBundle/ApiPlatform/Resources/Hook.php
Labels: QA ✔️, develop, Feature

#32809 Add debug cookie option
  admin-dev/themes/default/js/bundle/admin_parameters/performancePageUI.js
  admin-dev/themes/new-theme/js/components/generatable-input.ts
  admin-dev/themes/new-theme/js/pages/performance-preferences/index.ts
  src/Adapter/Debug/DebugMode.php
  src/Adapter/Debug/DebugModeConfiguration.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/DebugModeType.php
Labels: QA ✔️, develop, Feature, Needs autoupgrade PR

#32946 FrontController should not drop existing notifications
  classes/controller/FrontController.php
Labels: QA ✔️, develop, Bug fix

#32957 Update changelog and upgrade modules
  composer.json
  composer.lock
  docs/CHANGELOG.txt
Labels: Improvement

#32995 Functional tests - Fix random errors in the nightly 1.7.8.x
  tests/UI/campaigns/functional/FO/09_productPage/01_quickView.js
  tests/UI/pages/FO/home/index.js
  tests/UI/pages/FO/product/index.js
  tests/UI/pages/commonPage.js
Labels: QA ✔️, TE, Refactoring, E2E Tests, 1.7.8.x

#32983 Replace legacy cart rule creation methods in behats with new CQRS steps
  src/Adapter/CartRule/CommandHandler/AddCartRuleHandler.php
  tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CartRule/AbstractCartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CartRule/CommonCartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Cart/CartRule/BackOffice/gift_cartrule.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/CartRule/BackOffice/usage_limit_per_user.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/CartRule/FrontOffice/Restrictions/cart_rule_country_restriction.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/CartRule/FrontOffice/ecotax.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/cart_to_order.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/delivery_options.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_cancel_product.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_cart_rules.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_currency.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_cartrule.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_multi_invoices.feature
  tests/Integration/Behaviour/behat.yml
Labels: QA ✔️, develop, Refactoring

#33016 Improve controller depreciation documentation
  src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php
Labels: Improvement, develop

#32164 Removed deprecated methods `displayNumber` & `displayPrice` in class `Tools`
  classes/Tools.php
  composer.lock
  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
  src/Adapter/Presenter/Cart/CartPresenter.php
  src/Adapter/Presenter/Product/ProductLazyArray.php
  src/Adapter/Product/PriceFormatter.php
  src/Core/Domain/CustomerService/QueryHandler/GetCustomerThreadForViewingHandler.php
  src/PrestaShopBundle/Resources/config/services/core/domain/customer_service.yml
  tests/Resources/modules_tests/override/AdminProductsController.php
  tests/Resources/modules_tests/pscsx32412/override/controllers/admin/AdminProductsController.php
Labels: Improvement, QA ✔️, develop, BC break

#33017 Merge `8.0.x` into `8.1.x`
  classes/module/Module.php
  src/Adapter/Module/ModuleDataProvider.php
Labels: Improvement, Waiting for QA

#33012 Nightly : Fixed mocha loader (8.0.x)
  tests/UI/package.json
Labels: QA ✔️, TE, 8.0.x, Bug fix, E2E Tests

#31116 Aaa/apis08d view authorized application
  admin-dev/themes/new-theme/scss/pages/_authorization_server.scss
  admin-dev/themes/new-theme/scss/theme.scss
  src/Core/Domain/AuthorizationServer/Query/GetApplicationForViewing.php
  src/Core/Domain/AuthorizationServer/QueryHandler/GetApplicationForViewingHandler.php
  src/Core/Domain/AuthorizationServer/QueryHandler/GetApplicationForViewingHandlerInterface.php
  src/Core/Domain/AuthorizationServer/QueryResult/ViewableApplication.php
  src/Core/Grid/Definition/Factory/ApiAccessGridDefinitionFactory.php
  src/Core/Grid/Query/ApiAccessQueryBuilder.php
  src/Core/Search/Builder/TypedBuilder/ApiAccessFiltersBuilder.php
  src/Core/Search/Filters/ApiAccessesFilters.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AuthorizationServer/ApplicationController.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/authorization_server.yml
  src/PrestaShopBundle/Resources/config/services/core/domain/authorization_server.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_data_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_factory.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/AuthorizationServer/Application/view.html.twig
Labels: Waiting for QA, develop, Feature

#32631 Cache backup fix with no products
  src/Adapter/Presenter/Cart/CartPresenter.php
Labels: QA ✔️, develop, Bug fix

#32993 Change translation key when duplicate product
  src/Core/Grid/Definition/Factory/ProductGridDefinitionFactory.php
Labels: Improvement, QA ✔️, develop, Wording ✔️

#32994 Feature value form integration
  admin-dev/themes/new-theme/.webpack/common.js
  admin-dev/themes/new-theme/js/pages/feature/feature-value/form.ts
  classes/FeatureValue.php
  src/Core/Domain/Feature/FeatureValueSettings.php
  src/Core/Form/IdentifiableObject/DataHandler/FeatureValueFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/FeatureFormDataProvider.php
  src/Core/Form/IdentifiableObject/DataProvider/FeatureValueFormDataProvider.php
  src/Core/Grid/Definition/Factory/FeatureGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/FeatureValueGridDefinitionFactory.php
  src/Core/Grid/Query/FeatureValueQueryBuilder.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureValueController.php
  src/PrestaShopBundle/Form/Admin/Sell/Catalog/FeatureValueType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/features.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_handler.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Features/FeatureValue/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Features/FeatureValue/create.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Features/FeatureValue/edit.html.twig
Labels: Waiting for QA, develop, Refactoring, migration

#33011 Nightly : Fixed mocha loader (8.1.x)
  tests/UI/package.json
Labels: TE, Bug fix, E2E Tests, 8.1.x

#32662 Remove module list item when force deletion
  admin-dev/themes/new-theme/js/components/module-card.ts
  admin-dev/themes/new-theme/js/pages/module/controller.js
  src/Adapter/Module/AdminModuleDataProvider.php
  src/Adapter/Module/Module.php
  src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php
Labels: QA ✔️, develop, Bug fix

#31621 Enable Order Creation in BO with a virtual product and a customer add…
  admin-dev/themes/new-theme/js/pages/order/create/create-order-page.ts
  src/Adapter/Cart/QueryHandler/GetCartForOrderCreationHandler.php
  src/Core/Domain/Cart/QueryResult/CartForOrderCreation/CartShipping.php
Labels: QA ✔️, develop, Bug fix, BC break

#32894 Admin search - Transmit the search query param
  controllers/admin/AdminSearchController.php
  tests/Integration/Controllers/AdminSearchControllerCoreTest.php
Labels: Improvement

#32556 SetCartRuleProductRestrictions CQRS handling
  src/Adapter/CartRule/CommandHandler/SetCartRuleRestrictionsHandler.php
  src/Adapter/CartRule/QueryHandler/GetCartRuleForEditingHandler.php
  src/Adapter/CartRule/Repository/CartRuleRepository.php
  src/Core/Domain/CartRule/Command/SetCartRuleRestrictionsCommand.php
  src/Core/Domain/CartRule/Exception/CartRuleConstraintException.php
  src/Core/Domain/CartRule/QueryResult/CartRuleRestrictionsForEditing.php
  src/Core/Domain/CartRule/ValueObject/Restriction/RestrictionRule.php
  src/Core/Domain/CartRule/ValueObject/Restriction/RestrictionRuleGroup.php
  tests/Integration/Behaviour/Features/Context/Domain/CartRule/AbstractCartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CartRule/AddCartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CartRule/CartRuleAssertionFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CartRule/EditCartRuleFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CartRule/SetCartRuleRestrictionsFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/SupplierFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/CartRule/set_cart_rule_combination_restrictions.feature
  tests/Integration/Behaviour/Features/Scenario/CartRule/set_mixed_cart_rule_restrictions.feature
  tests/Integration/Behaviour/Features/Scenario/CartRule/set_product_restrictions.feature
  tests/Integration/Behaviour/behat.yml
Labels: develop, Refactoring, migration

#33023 Nightly : Fixed install Node 14
  .docker/Dockerfile
  docker-compose.yml
Labels: QA ✔️, Bug fix

#33033 Nightly : Fixed install Node 14
  .docker/Dockerfile
  docker-compose.yml
Labels: QA ✔️, TE, 8.0.x, Bug fix, E2E Tests

#33032 Nightly : Fixed install Node 16
  .docker/Dockerfile
  docker-compose.yml
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#33015 Feature value delete and export actions
  admin-dev/themes/new-theme/js/pages/feature/feature-value/index.ts
  src/Adapter/Feature/CommandHandler/BulkDeleteFeatureValueHandler.php
  src/Adapter/Feature/CommandHandler/DeleteFeatureValueHandler.php
  src/Adapter/Feature/Repository/FeatureValueRepository.php
  src/Core/Domain/Feature/Command/BulkDeleteFeatureValueCommand.php
  src/Core/Domain/Feature/Command/DeleteFeatureValueCommand.php
  src/Core/Domain/Feature/CommandHandler/BulkDeleteFeatureValueHandlerInterface.php
  src/Core/Domain/Feature/CommandHandler/DeleteFeatureValueHandlerInterface.php
  src/Core/Domain/Feature/Exception/BulkFeatureValueException.php
  src/Core/Domain/Feature/Exception/CannotDeleteFeatureValueException.php
  src/Core/Grid/Definition/Factory/FeatureValueGridDefinitionFactory.php
  src/Core/Grid/Factory/FeatureValueGridFactory.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureValueController.php
  src/PrestaShopBundle/Form/Admin/Sell/Catalog/FeatureValueType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/features.yml
  src/PrestaShopBundle/Resources/config/services/adapter/feature.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  tests/Integration/Behaviour/Features/Context/Domain/FeatureValueFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Feature/feature_value_management.feature
Labels: develop, Refactoring, migration

#33037 Merge build PR into 8.1.x
  composer.json
  composer.lock
  docs/CHANGELOG.txt
  tests/UI/pages/BO/design/linkWidgets/add.ts
Labels: Improvement, QA ✔️
