Repository PrestaShop/PrestaShop, pull requests merged in 2023-09, with the labels that each got.

#33784 Add missing wording and domains
  install-dev/data/xml/tab.xml
Labels: QA ✔️, Bug fix, 8.1.x

#33702 [twig component] Make navigation bar management independent
  admin-dev/themes/new-theme/template/layout.tpl
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/toolbar.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/toolbar.html.twig
  src/PrestaShopBundle/Twig/Component/Toolbar.php
  src/PrestaShopBundle/Twig/Layout/MenuBuilder.php
Labels: Improvement, QA ✔️, develop

#33723 Protect templates directory
  templates/.htaccess
Labels: QA ✔️, develop, Bug fix

#33788 Add htaccess to fix 33722
  templates/.htaccess
Labels: QA ✔️, Bug fix, 8.1.x

#33781 Functional Tests : Moved tests from `campaigns/functional/BO/13_shopParameters/05_contact/*`
  tests/UI/campaigns/functional/BO/13_shopParameters/05_contact/01_contacts/01_filterContacts.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/05_contact/01_contacts/02_CRUDContact.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/05_contact/01_contacts/03_contactBulkActions.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/05_contact/01_contacts/04_sortAndPagination.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/05_contact/02_stores/01_filterAndQuickEditStores.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/05_contact/02_stores/02_CRUDStores.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/05_contact/02_stores/03_bulkActionsStores.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/05_contact/02_stores/04_contactDetails.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/05_contact/02_stores/05_sortAndPagination.ts
Labels: Improvement, TE, develop, E2E Tests

#33789 Nightly `8.1.x` : Fixed `campaigns/productV2/functional/01_filterProducts.ts`
  tests/UI/campaigns/productV2/functional/01_filterProducts.ts
Labels: QA ✔️, TE, Bug fix, E2E Tests, 8.1.x

#33795 CI : TypeScript Check (Fixed NPM Install)
  .github/workflows/ui_tests_code_checks.yml
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#33791 Nightly `develop` : Fixed `campaigns/productV2/functional/*`
  tests/UI/campaigns/productV2/functional/01_filterProducts.ts
  tests/UI/campaigns/productV2/functional/09_footer.ts
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#33745 Introduce alternative search panels same page links
  admin-dev/themes/default/scss/partials/_content.scss
  admin-dev/themes/default/template/controllers/search/helpers/view/view.tpl
  controllers/admin/AdminSearchController.php
  src/Core/Search/SearchPanel.php
  src/Core/Search/SearchPanelInterface.php
  tests/Integration/Controllers/AdminSearchControllerCoreTest.php
Labels: Improvement, Waiting for QA, QA ✔️, UX ✔️, 8.1.x

#33830 Merge `8.1.x` into `develop`
  composer.lock
  install-dev/data/xml/tab.xml
Labels: Improvement, QA ✔️, develop

#33802 Fix uninstalling modules with deleted hooks.
  classes/Hook.php
  classes/module/Module.php
Labels: QA ✔️, Bug fix, 8.1.x

#33778 Handle friendly url automatic update and automatic offline shop configurations
  admin-dev/themes/new-theme/js/pages/product/create/create-product-modal.ts
  admin-dev/themes/new-theme/js/pages/product/edit/manager/product-seo-manager.ts
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/GeneralType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/EditProductFormType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/HeaderType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/SEO/SEOType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/FormTheme/product_seo.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/edit.html.twig
Labels: QA ✔️, develop, Bug fix, 8.1.x

#33758 fix PDO prepare for CVE-2023-39524
  src/Adapter/Product/Repository/ProductRepository.php
Labels: Waiting for QA, develop, Refactoring, Waiting for dev

#33869 Nightly: Fixed `campaigns/productV2/functional/03_CRUDProductWithCombinations.ts`
  tests/UI/pages/BO/catalog/productsV2/add/index.ts
Labels: QA ✔️, TE, Bug fix, E2E Tests, 8.1.x

#33860 Add order by for attribute by position
  src/Adapter/Attribute/Repository/AttributeRepository.php
  tests/Integration/Behaviour/Features/Context/AttributeFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Attribute/list_attribute_groups.feature
Labels: QA ✔️, Bug fix, 8.1.x

#33771 Update classname regex to allow FQDN
  classes/Validate.php
Labels: QA ✔️, Bug fix, 8.1.x

#33801 Add line in PR template to not forget UI tests
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improvement, QA ✔️, 8.1.x

#33264 Remove usage of multiaddress delivery
  classes/Address.php
  classes/Cart.php
  classes/Context.php
  classes/Customization.php
  classes/Product.php
  classes/order/OrderReturn.php
  controllers/front/CartController.php
  src/Adapter/Cart/CommandHandler/CreateEmptyCustomerCartHandler.php
  src/Adapter/Order/GeneralConfiguration.php
  src/Core/Cart/CartRow.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/OrderPreferencesController.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/OrderPreferences/GeneralType.php
  tests/Integration/Utility/CartOld.php
  tests/Resources/modules_tests/override/Cart.php
  tests/Resources/modules_tests/pscsx32412/override/classes/Cart.php
  tests/Unit/Adapter/Order/GeneralConfigurationTest.php
Labels: QA ✔️, develop, Refactoring, BC break, Needs documentation

#33844 Allow adding multilanguage routes, add comments
  classes/Dispatcher.php
Labels: Improvement, QA ✔️, Bug fix, BC break, 8.1.x

#33775 [Twig component] Make Header independent
  admin-dev/themes/new-theme/template/layout.tpl
  phpstan-tmp-legacy-layout-baseline.neon
  src/PrestaShopBundle/Entity/Repository/TabRepository.php
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/employee_dropdown.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/head.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/header.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/mobile_quick_access.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/nav_bar.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/quick_access.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/search_form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/toolbar.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/head.html.twig
  src/PrestaShopBundle/Twig/Component/Head.php
  src/PrestaShopBundle/Twig/Component/Header.php
  src/PrestaShopBundle/Twig/Extension/PathExtension.php
  src/PrestaShopBundle/Twig/Layout/MenuBuilder.php
Labels: Improvement, Waiting for QA, develop, BC break

#27590 Migrate "Shop parameters > Order settings > Statuses" page
  admin-dev/themes/default/template/controllers/statuses/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/statuses/helpers/index.php
  admin-dev/themes/new-theme/js/app/utils/colorpicker.js
  admin-dev/themes/new-theme/js/components/grid/extension/bulk-action-checkbox-extension.ts
  admin-dev/themes/new-theme/js/pages/order-states/index.ts
  admin-dev/themes/new-theme/scss/components/_colorpicker.scss
  admin-dev/themes/new-theme/scss/components/_grid.scss
  admin-dev/themes/new-theme/scss/pages/_order_states.scss
  classes/order/OrderReturnState.php
  classes/order/OrderState.php
  controllers/admin/AdminStatusesController.php
  install-dev/data/xml/feature_flag.xml
  src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php
  src/Adapter/OrderState/CommandHandler/AddOrderStateHandler.php
  src/Adapter/OrderState/CommandHandler/EditOrderStateHandler.php
  src/Core/Domain/OrderReturnState/Command/BulkDeleteOrderReturnStateCommand.php
  src/Core/Domain/OrderReturnState/OrderReturnStateSettings.php
  src/Core/Domain/OrderState/Command/BulkDeleteOrderStateCommand.php
  src/Core/Domain/OrderState/OrderStateSettings.php
  src/Core/Grid/Definition/Factory/OrderReturnStatesGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/OrderStatesGridDefinitionFactory.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/OrderReturnStates/OrderReturnStateType.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/OrderStates/OrderStateType.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/shop_parameters/order_states.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/OrderReturnStates/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/OrderStates/Blocks/form.html.twig
  tests/Integration/Behaviour/Features/Context/Domain/OrderStateFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/OrderState/order_state.feature
  tests/Integration/Classes/controller/AdminControllerTest.php
  tests/Integration/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminControllerTest.php
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/returnStatuses/01_CRUDOrderReturnStatus.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/returnStatuses/02_filterSortAndPagination.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/statuses/01_CRUDOrderStatus.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/statuses/02_filterSortAndPagination.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/02_orderSettings/02_statuses/statuses/03_quickEdit.ts
  tests/UI/data/faker/orderReturnStatus.ts
  tests/UI/data/faker/orderStatus.ts
  tests/UI/pages/BO/shopParameters/orderSettings/statuses/add.ts
  tests/UI/pages/BO/shopParameters/orderSettings/statuses/index.ts
  tests/UI/pages/BO/shopParameters/orderSettings/statuses/returnStatus/add.ts
  tests/UI/pages/commonPage.ts
Labels: QA ✔️, develop, Refactoring, migration, BC break, Needs documentation

#32458 Remove menu thumbnails
  src/Adapter/Category/CommandHandler/AddCategoryHandler.php
  src/Adapter/Category/CommandHandler/AddRootCategoryHandler.php
  src/Adapter/Category/CommandHandler/DeleteCategoryMenuThumbnailImageHandler.php
  src/Adapter/Category/CommandHandler/EditCategoryHandler.php
  src/Adapter/Category/CommandHandler/EditRootCategoryHandler.php
  src/Adapter/Category/QueryHandler/GetCategoryForEditingHandler.php
  src/Adapter/Image/Uploader/CategoryImageUploader.php
  src/Adapter/Image/Uploader/CategoryMenuThumbnailUploader.php
  src/Core/Category/Provider/CategoryImageFinder.php
  src/Core/Category/Provider/MenuThumbnailAvailableKeyProvider.php
  src/Core/Domain/Category/Command/AddCategoryCommand.php
  src/Core/Domain/Category/Command/AddRootCategoryCommand.php
  src/Core/Domain/Category/Command/DeleteCategoryMenuThumbnailImageCommand.php
  src/Core/Domain/Category/Command/EditCategoryCommand.php
  src/Core/Domain/Category/Command/EditRootCategoryCommand.php
  src/Core/Domain/Category/CommandHandler/DeleteCategoryMenuThumbnailImageHandlerInterface.php
  src/Core/Domain/Category/Exception/CannotDeleteImageException.php
  src/Core/Domain/Category/Exception/CategoryConstraintException.php
  src/Core/Domain/Category/Exception/MenuThumbnailsLimitException.php
  src/Core/Domain/Category/QueryResult/EditableCategory.php
  src/Core/Domain/Category/ValueObject/MenuThumbnailId.php
  src/Core/Form/IdentifiableObject/DataHandler/CategoryFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/RootCategoryFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/CategoryFormDataProvider.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Form/Admin/Catalog/Category/AbstractCategoryType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/categories.yml
  src/PrestaShopBundle/Resources/config/services/adapter/category.yml
  src/PrestaShopBundle/Resources/config/services/adapter/image.yml
  src/PrestaShopBundle/Resources/config/services/core/category.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/edit_root.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
  tests/Integration/Behaviour/Features/Context/Domain/CategoryFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Category/category_management.feature
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/11_imageGenerationOnCreation.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/14_checkCategoryImageFormat.ts
  tests/UI/data/faker/category.ts
  tests/UI/data/types/category.d.ts
  tests/UI/pages/BO/catalog/categories/add.ts
  tests/Unit/Core/Category/Provider/CategoryImageFinderTest.php
  tests/Unit/Core/Category/Provider/MenuThumbnailAvailableKeyProviderTest.php
Labels: QA ✔️, PM ✔️, develop, Refactoring, BC break, Needs documentation

#33706 Handle advanced setters in command processor
  src/PrestaShopBundle/ApiPlatform/DomainSerializer.php
  src/PrestaShopBundle/ApiPlatform/Normalizer/DateTimeImmutableDenormalizer.php
  src/PrestaShopBundle/ApiPlatform/Resources/CartRule.php
  tests/Unit/PrestaShopBundle/ApiPlatform/DomainSerializerTest.php
Labels: QA ✔️, develop, Feature

#33905 Merge 8.1.x into develop
  .github/PULL_REQUEST_TEMPLATE.md
  admin-dev/themes/default/scss/partials/_content.scss
  admin-dev/themes/default/template/controllers/search/helpers/view/view.tpl
  admin-dev/themes/new-theme/js/pages/product/create/create-product-modal.ts
  admin-dev/themes/new-theme/js/pages/product/edit/manager/product-seo-manager.ts
  classes/Dispatcher.php
  classes/Hook.php
  classes/Validate.php
  classes/module/Module.php
  controllers/admin/AdminSearchController.php
  src/Adapter/Attribute/Repository/AttributeRepository.php
  src/Core/Search/SearchPanel.php
  src/Core/Search/SearchPanelInterface.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/GeneralType.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/Delivery/SlipOptionsType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/EditProductFormType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/HeaderType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/SEO/SEOType.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/FormTheme/product_seo.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/edit.html.twig
  tests/Integration/Behaviour/Features/Context/AttributeFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Attribute/list_attribute_groups.feature
  tests/Integration/Controllers/AdminSearchControllerCoreTest.php
  tests/UI/pages/BO/catalog/productsV2/add/index.ts
Labels: Improvement, QA ✔️, develop

#33909 Cannot add feature or cusotmization fields to virtual product
  admin-dev/themes/new-theme/js/pages/product/edit/index.ts
Labels: QA ✔️, Bug fix, 8.1.x

#33873 Allow modules to provide language link params in correct languages
  classes/Link.php
  install-dev/data/xml/hook.xml
Labels: QA ✔️, Feature, Bug fix, BC break, 8.1.x

#33907 Use softDelete method
  classes/Address.php
  classes/Currency.php
  classes/tax/Tax.php
  classes/tax/TaxRulesGroup.php
Labels: Refactoring, 8.1.x

#33885 Fix URL sanitization and duplicate language ID
  classes/Dispatcher.php
  classes/controller/FrontController.php
Labels: QA ✔️, Bug fix, 8.1.x

#33937 Bump 8.1.2 version
  install-dev/install_version.php
  src/Core/Version.php
Labels: Improvement, Waiting for QA, QA ✔️, 8.1.x

#33894 Fix adding and deleting language entries from tables
  classes/Language.php
Labels: QA ✔️, Bug fix, 8.1.x

#33741 Introduce employee menu same page links
  admin-dev/themes/default/scss/partials/_header.scss
  admin-dev/themes/default/template/controllers/search/helpers/view/view.tpl
  admin-dev/themes/default/template/header.tpl
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
  admin-dev/themes/new-theme/template/components/layout/employee_dropdown.tpl
  controllers/admin/AdminSearchController.php
  src/Core/Search/SearchPanel.php
  src/Core/Search/SearchPanelInterface.php
  tests/Integration/Controllers/AdminSearchControllerCoreTest.php
Labels: Improvement, QA ✔️, UX ✔️, 8.1.x

#33929 Functional Tests : BO - Customers - Filter and Quick Edit
  tests/UI/campaigns/functional/BO/04_customers/01_customers/01_filterAndQuickEditCustomers.ts
  tests/UI/data/demo/customers.ts
  tests/UI/data/demo/socialTitles.ts
Labels: Improvement, TE, develop, E2E Tests

#33933 Functional Tests : Added email check to `BO - Advanced Parameters - Import : Import file`
  tests/UI/campaigns/functional/BO/14_advancedParameters/05_import/02_importFile.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#33934 Functional Tests : Hummingbird : FO - Header and Footer : Change currency
  tests/UI/campaigns/functional/BO/02_orders/01_orders/11_previewOrder.ts
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/02_conditions/10_productSelection.ts
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/03_actions/07_applyToSpecificProduct.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/02_productPage/03_separatorOfAttributeAnchor.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/02_defaultPackStockManagement.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/03_displayUnavailableProductAttributes.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/04_displayRemainingQuantities.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/05_allowOrderingOutOfStock.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/07_labelOutOfStock.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/09_enableDeliveryTimeOfOutOfStockProducts.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/01_search/01_editSearchSettings/03_fuzzySearch.ts
  tests/UI/campaigns/functional/FO/classic/02_headerAndFooter/03_changeCurrency.ts
  tests/UI/campaigns/functional/FO/classic/07_search/02_searchProduct.ts
  tests/UI/campaigns/functional/FO/classic/07_search/03_searchNoResult.ts
  tests/UI/campaigns/functional/FO/classic/08_menuAndNavigation/03_navigationAndDisplay/01_displayTags.ts
  tests/UI/campaigns/functional/FO/classic/08_menuAndNavigation/03_navigationAndDisplay/03_quickViewProducts.ts
  tests/UI/campaigns/functional/FO/classic/09_productPage/01_quickView.ts
  tests/UI/campaigns/functional/FO/classic/09_productPage/01_quickView/01_addToCart.ts
  tests/UI/campaigns/functional/FO/classic/09_productPage/02_addToCart.ts
  tests/UI/campaigns/functional/FO/hummingbird/02_headerAndFooter/03_changeCurrency.ts
  tests/UI/campaigns/regression/currencies/computingPrecision_FO.ts
  tests/UI/commonTests/FO/order.ts
  tests/UI/commonTests/FO/shoppingCart.ts
  tests/UI/pages/FO/FObasePage.ts
  tests/UI/pages/FO/hummingbird/searchResults/index.ts
  tests/UI/pages/FO/searchResults/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#33935 Functional tests - Add new test 'BO > Product v2 > Description tab'
  tests/UI/campaigns/productV2/functional/08_header.ts
  tests/UI/campaigns/productV2/functional/10_descriptionTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/descriptionTab.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#33407 Do not check for multiple image formats feature, add fallback
  classes/Image.php
  classes/ObjectModel.php
  controllers/admin/AdminImagesController.php
  controllers/admin/AdminProductsController.php
  controllers/admin/AdminStoresController.php
  src/Adapter/Image/ImageGenerator.php
  src/Adapter/Image/ImageRetriever.php
  src/Adapter/Image/Uploader/ManufacturerImageUploader.php
  src/Adapter/Manufacturer/CommandHandler/DeleteManufacturerLogoImageHandler.php
  src/Core/ContainerBuilder.php
  src/Core/Image/ImageFormatConfiguration.php
  src/Core/Shop/LogoUploader.php
  tests/Unit/Core/Image/ImageFormatConfigurationTest.php
Labels: Improvement, QA ✔️, Bug fix, 8.1.x

#33930 Cannot set specific price with currency filter
  classes/Product.php
Labels: QA ✔️, Bug fix, 8.1.x

#33968 Remove 8.0.x branch from Update PHP Modules cron
  .github/workflows/cron_php_update_modules.yml
Labels: Improvement, QA ✔️, develop

#33807 Fixed $legacyKey in buildTranslationCatalogueFromLegacyFiles()
  src/PrestaShopBundle/Translation/Provider/ExternalModuleLegacySystemProvider.php
Labels: QA ✔️, Bug fix, 8.1.x

#33756 feat(api-platform): handle scope on endpoints
  app/config/security_test.yml
  src/PrestaShopBundle/ApiPlatform/Decorator/AttributesResourceMetadataCollectionFactoryDecorator.php
  src/PrestaShopBundle/ApiPlatform/Resources/Hook.php
  src/PrestaShopBundle/Resources/config/services/adapter/hook.yml
  src/PrestaShopBundle/Security/OAuth2/Repository/AccessTokenRepository.php
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/02_externalAuthServer/01_authorizationEndpoint.ts
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/02_externalAuthServer/02_resourceEndpoint.ts
Labels: Improvement, QA ✔️, develop

#33961 Do not construct presenters that we already have from the parent
  classes/controller/FrontController.php
  controllers/front/CartController.php
  controllers/front/OrderConfirmationController.php
Labels: QA ✔️, Refactoring, 8.1.x

#33928 Provide rendered category footer
  controllers/front/listing/CategoryController.php
Labels: QA ✔️, Bug fix, 8.1.x

#33964 Fix rounding of no pack price
  classes/Pack.php
Labels: QA ✔️, Bug fix, 8.1.x

#34018 Wording fixed for final export for 8.1.2
  src/Core/Form/ChoiceProvider/DeliveryTimeNoteTypesProvider.php
  src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php
Labels: Bug fix, Wording ✔️, 8.1.x

#33976 Update czech localization pack
  localization/cz.xml
Labels: Improvement, QA ✔️, 8.1.x

#34007 Update default catalog 8.1.x
  translations/default/AdminActions.xlf
  translations/default/AdminAdvparametersFeature.xlf
  translations/default/AdminAdvparametersHelp.xlf
  translations/default/AdminAdvparametersNotification.xlf
  translations/default/AdminCatalogFeature.xlf
  translations/default/AdminCatalogHelp.xlf
  translations/default/AdminCatalogNotification.xlf
  translations/default/AdminDesignFeature.xlf
  translations/default/AdminDesignHelp.xlf
  translations/default/AdminDesignNotification.xlf
  translations/default/AdminGlobal.xlf
  translations/default/AdminInternationalFeature.xlf
  translations/default/AdminInternationalHelp.xlf
  translations/default/AdminInternationalNotification.xlf
  translations/default/AdminLoginNotification.xlf
  translations/default/AdminModulesFeature.xlf
  translations/default/AdminModulesNotification.xlf
  translations/default/AdminNavigationHeader.xlf
  translations/default/AdminNavigationMenu.xlf
  translations/default/AdminNavigationNotification.xlf
  translations/default/AdminNavigationSearch.xlf
  translations/default/AdminNotificationsError.xlf
  translations/default/AdminNotificationsInfo.xlf
  translations/default/AdminNotificationsSuccess.xlf
  translations/default/AdminNotificationsWarning.xlf
  translations/default/AdminOrderscustomersFeature.xlf
  translations/default/AdminOrderscustomersNotification.xlf
  translations/default/AdminShippingFeature.xlf
  translations/default/AdminShippingHelp.xlf
  translations/default/AdminShopparametersFeature.xlf
  translations/default/AdminShopparametersHelp.xlf
  translations/default/AdminShopparametersNotification.xlf
  translations/default/AdminStatsNotification.xlf
  translations/default/EmailsBody.xlf
  translations/default/EmailsSubject.xlf
  translations/default/Install.xlf
  translations/default/ModulesBlockwishlistShop.xlf
  translations/default/ModulesDashgoalsAdmin.xlf
  translations/default/ModulesEmailalertsAdmin.xlf
  translations/default/ModulesEmailalertsShop.xlf
  translations/default/ModulesFacetedsearchAdmin.xlf
  translations/default/ModulesFacetedsearchShop.xlf
  translations/default/ModulesImagesliderAdmin.xlf
  translations/default/ModulesLinklistAdmin.xlf
  translations/default/ModulesLinklistShop.xlf
  translations/default/ModulesWirepaymentShop.xlf
  translations/default/ShopFormsHelp.xlf
  translations/default/ShopFormsLabels.xlf
  translations/default/ShopNotificationsError.xlf
  translations/default/ShopNotificationsSuccess.xlf
  translations/default/ShopNotificationsWarning.xlf
  translations/default/ShopPdf.xlf
  translations/default/ShopThemeActions.xlf
  translations/default/ShopThemeCatalog.xlf
  translations/default/ShopThemeCheckout.xlf
  translations/default/ShopThemeCustomeraccount.xlf
  translations/default/ShopThemeGlobal.xlf
  translations/default/messages.xlf
Labels: Improvement, QA ✔️, Wording ✔️, 8.1.x

#33969 Functional tests - Add new test to check 'BO > Product V2 > Combination tab'
  tests/UI/campaigns/productV2/functional/03_CRUDProductWithCombinations.ts
  tests/UI/campaigns/productV2/functional/11_combinationTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/combinationsTab.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34026 Update product comments in composer.lock
  composer.json
  composer.lock
Labels: Improvement, 8.1.x

#34030 Nightly : Fixed Playwright in 1.7.8.x version
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#34025 Add actionAfterLoadRoutes in hook.xml
  install-dev/data/xml/hook.xml
Labels: Bug fix, 8.1.x

#34034 Update INSTALL.txt for 8.x
  INSTALL.txt
Labels: Improvement, QA ✔️, 8.1.x

#33988 Functional tests - Fix random error in 'FO > Quick view product'
  tests/UI/campaigns/functional/FO/09_productPage/01_quickView.js
  tests/UI/pages/FO/home/index.js
Labels: TE, E2E Tests

#34037 Functional tests - Add new test 'BO > Product V2 > Shipping tab'
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/05_carriersTab.ts
  tests/UI/campaigns/productV2/functional/16_shippingTab.ts
  tests/UI/data/demo/products.ts
  tests/UI/data/faker/product.ts
  tests/UI/data/types/product.d.ts
  tests/UI/pages/BO/catalog/productsV2/add/shippingTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/stocksTab.ts
  tests/UI/pages/FO/product/index.ts
Labels: TE, develop, Refactoring, E2E Tests

#34054 Nightly : Disable PS_INSTALL_AUTO on campaign sanity
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: TE, develop, Bug fix, E2E Tests

#33690 Composer and npm not installed in Docker when assets are not built
  .docker/Dockerfile
  .docker/docker_run_git.sh
  docker-compose.yml
  tests/UI/package.json
Labels: Improvement, develop

#34014 Backport of 32884 / Fix Error Webservice combinations or categories on a blank schema
  classes/webservice/WebserviceOutputBuilder.php
Labels: QA ✔️, Bug fix, 8.1.x

#34056 Add missing params doc for get method in Configuration.php
  classes/Configuration.php
Labels: Improvement, QA ✔️, develop

#34068 Nightly : Fixed the URL to ping
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: TE, develop, Bug fix, E2E Tests

#33990 Fix WebProfiler when dev mode is active
  phpstan-baseline.neon
  src/PrestaShopBundle/DataCollector/ConfigDataCollector.php
  src/PrestaShopBundle/Resources/config/services/bundle/data_collector.yml
Labels: QA ✔️, develop, Bug fix

#34060 Fix image configuration
  controllers/admin/AdminImagesController.php
Labels: QA ✔️, Bug fix, 8.1.x

#33459 Update egulias/email-validator to 4.0.1 and bump multiple doctrine deps
  composer.lock
  install-dev/init.php
  src/Adapter/Alias/Repository/AliasRepository.php
  src/Adapter/Attachment/AttachmentRepository.php
  src/Adapter/Attribute/Repository/AttributeRepository.php
  src/Adapter/AttributeGroup/Repository/AttributeGroupRepository.php
  src/Adapter/Cache/MemcacheServerManager.php
  src/Adapter/CartRule/Repository/CartRuleRepository.php
  src/Adapter/CatalogPriceRule/Repository/CatalogPriceRuleRepository.php
  src/Adapter/Category/Repository/CategoryRepository.php
  src/Adapter/Feature/Repository/FeatureRepository.php
  src/Adapter/Feature/Repository/FeatureValueRepository.php
  src/Adapter/Import/ImportEntityDeleter.php
  src/Adapter/PDF/CreditSlipPdfGenerator.php
  src/Adapter/Product/Combination/QueryHandler/GetEditableCombinationsListHandler.php
  src/Adapter/Product/Combination/Repository/CombinationRepository.php
  src/Adapter/Product/Combination/Update/CombinationImagesUpdater.php
  src/Adapter/Product/Customization/Repository/CustomizationFieldRepository.php
  src/Adapter/Product/FeatureValue/Update/ProductFeatureValueUpdater.php
  src/Adapter/Product/Image/Repository/ProductImageRepository.php
  src/Adapter/Product/Pack/Repository/ProductPackRepository.php
  src/Adapter/Product/Repository/ProductRepository.php
  src/Adapter/Product/Repository/ProductSupplierRepository.php
  src/Adapter/Product/Repository/TagRepository.php
  src/Adapter/Product/SpecificPrice/Repository/SpecificPriceRepository.php
  src/Adapter/Product/Stock/Repository/StockAvailableRepository.php
  src/Adapter/Product/Stock/Repository/StockMovementRepository.php
  src/Adapter/Product/Update/ProductDuplicator.php
  src/Adapter/Session/Repository/CustomerSessionRepository.php
  src/Adapter/Session/Repository/EmployeeSessionRepository.php
  src/Adapter/Shop/Repository/ShopGroupRepository.php
  src/Adapter/Shop/Repository/ShopRepository.php
  src/Adapter/TaxRulesGroup/Repository/TaxRulesGroupRepository.php
  src/Core/Domain/CustomerService/CommandHandler/UpdateCustomerThreadStatusHandler.php
  src/Core/Domain/Product/Combination/QueryHandler/GetCombinationIdsHandler.php
  src/Core/Domain/Store/Repository/StoreRepository.php
  src/Core/Grid/Data/Factory/AttachmentGridDataFactoryDecorator.php
  src/Core/Grid/Data/Factory/DoctrineGridDataFactory.php
  src/Core/Grid/Position/UpdateHandler/DoctrinePositionUpdateHandler.php
  src/Core/Grid/Query/ProductCombinationQueryBuilder.php
  src/Core/Grid/Query/RequestSqlQueryBuilder.php
  src/PrestaShopBundle/Command/UpdateSchemaCommand.php
  src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php
  src/PrestaShopBundle/Entity/Repository/CategoryRepository.php
  src/PrestaShopBundle/Entity/Repository/FeatureAttributeRepository.php
  src/PrestaShopBundle/Entity/Repository/ImportMatchRepository.php
  src/PrestaShopBundle/Entity/Repository/LogRepository.php
  src/PrestaShopBundle/Entity/Repository/ManufacturerRepository.php
  src/PrestaShopBundle/Entity/Repository/ModuleRepository.php
  src/PrestaShopBundle/Entity/Repository/OrderInvoiceRepository.php
  src/PrestaShopBundle/Entity/Repository/StockManagementRepository.php
  src/PrestaShopBundle/Entity/Repository/StockMovementRepository.php
  src/PrestaShopBundle/Entity/Repository/StockRepository.php
  src/PrestaShopBundle/Entity/Repository/SupplierRepository.php
  tests/Unit/Adapter/Module/Configuration/ModuleSelfConfiguratorTest.php
  tests/Unit/Core/Grid/Data/Factory/DoctrineGridDataFactoryTest.php
  tests/Unit/PrestaShopBundle/Command/UpdateSchemaCommandTest.php
Labels: Improvement, Waiting for QA, develop, Bug fix, BC break, Needs documentation

#34084 Update Changelog for 8.1.2
  CONTRIBUTORS.md
  controllers/admin/AdminDashboardController.php
  docs/CHANGELOG.txt
Labels: Improvement, 8.1.x

#34023 Handle via javascript that the two fields for impact are synced, mean…
  admin-dev/themes/new-theme/js/pages/product/combination/bulk.ts
  admin-dev/themes/new-theme/js/pages/product/combination/bulk/combination-bulk-map.ts
  admin-dev/themes/new-theme/js/pages/product/combination/bulk/index.ts
  admin-dev/themes/new-theme/js/pages/product/combination/form/combination-form-mapping.ts
Labels: QA ✔️, Bug fix, 8.1.x

#33779 Move `FrontController::updateQueryString` to `Tools` to make reusable
  classes/Tools.php
  classes/controller/FrontController.php
  classes/controller/ProductListingFrontController.php
Labels: QA ✔️, develop, Refactoring

#33954 Fix undefined currency if cart is updated before currency is assigned to the context
  classes/Tools.php
  classes/controller/FrontController.php
Labels: QA ✔️, Bug fix, 8.1.x

#34078 Fix URL with accented chars
  classes/Tools.php
  src/Core/Util/String/StringModifier.php
  tests/Unit/Core/Util/String/StringModifierTest.php
Labels: QA ✔️, Bug fix, 8.1.x

#34069 Functional tests - Add new test 'BO > Product V2 > Pricing tab'
  tests/UI/campaigns/productV2/functional/17_pricingTab.ts
  tests/UI/pages/BO/catalog/productsV2/add/pricingTab.ts
  tests/UI/pages/FO/product/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34111 Fix `wording` in `AbstractColumn`
  src/Core/Grid/Column/AbstractColumn.php
Labels: Improvement, Waiting for QA, develop
