Repository PrestaShop/PrestaShop, pull requests merged in 2023-05, with the labels that each got.

#32314 Functional tests - Add some tests in module manager page
  tests/UI/campaigns/functional/BO/04_customers/01_customers/09_subscribeToNewsletter.ts
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/01_filterModulesByStatus.ts
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/03_searchModule.ts
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/04_enableDisableModule.ts
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/05_resetModule.ts
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/06_installUninstallModule.ts
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/07_bulkActions.ts
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/09_configureModule.ts
  tests/UI/campaigns/functional/BO/08_design/01_themeAndLogo/03_advancedCustomization/01_advancedCustomization.ts
  tests/UI/campaigns/functional/FO/classic/04_newsletter/01_subscribeNewsletter.ts
  tests/UI/data/demo/modules.ts
  tests/UI/pages/BO/modules/moduleManager/index.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#32402 Functional tests - Fix random error in 'FO > User account > Get GDPR data in PDF'
  tests/UI/campaigns/functional/FO/classic/03_userAccount/04_getGDPRDataInPDF.ts
  tests/UI/utils/files.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#32403 Update sidebar transform value
  admin-dev/themes/new-theme/scss/rtl.scss
Labels: QA ✔️, develop, Bug fix

#32345 fix(discounts): hide vouchers with no available quantities
  controllers/front/DiscountController.php
Labels: QA ✔️, 8.0.x, Bug fix

#32406 add .php-cs-fixer.dist.php to remove file list of the ZIP creator tool
  tools/build/Library/ReleaseCreator.php
Labels: develop, Bug fix

#32433 Remove unused var
  install-dev/controllers/http/process.php
Labels: Improvement, QA ✔️, develop

#32340 Add missing y to service name
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_data_factory.yml
Labels: Improvement, Waiting for QA, develop, BC break, Waiting for dev

#32366 Use `CurrencyChoiceType` on all form types
  src/Core/Form/ChoiceProvider/CurrencyByIdChoiceProvider.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Localization/LocalizationConfigurationType.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Locations/CountryType.php
  src/PrestaShopBundle/Form/Admin/Improve/Payment/Preferences/PaymentModulePreferencesType.php
  src/PrestaShopBundle/Form/Admin/Sell/CatalogPriceRule/CatalogPriceRuleType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Options/ProductSupplierType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/ApplicableGroupsType.php
  src/PrestaShopBundle/Form/Admin/Type/CurrencyChoiceType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/choice_provider.yml
Labels: QA ✔️, develop, Refactoring

#32290 Fix: Setting DNI mandatory after address creation launches an exception during checkout
  classes/AddressChecksumCore.php
Labels: QA ✔️, Bug fix

#32394 Add `autocomplete` option to every ChoiceType
  src/PrestaShopBundle/Form/Admin/Category/SimpleCategory.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Employee/EmployeeType.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/General/PreferencesType.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/OrderPreferences/GeneralType.php
  src/PrestaShopBundle/Form/Admin/Feature/ProductFeature.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Currencies/CurrencyType.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Localization/ImportLocalizationPackType.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Localization/LocalizationConfigurationType.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Translations/AddUpdateLanguageType.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Translations/ModifyTranslationsType.php
  src/PrestaShopBundle/Form/Admin/Improve/Shipping/Preferences/CarrierOptionsType.php
  src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php
  src/PrestaShopBundle/Form/Admin/Product/ProductPrice.php
  src/PrestaShopBundle/Form/Admin/Product/ProductSpecificPrice.php
  src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php
  src/PrestaShopBundle/Form/Admin/Sell/Address/ManufacturerAddressType.php
  src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/UpdateOrderShippingType.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/UpdateOrderStatusType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Category/CategoriesType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Description/ManufacturerType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php
  src/PrestaShopBundle/Form/Admin/Sell/Supplier/SupplierType.php
  src/PrestaShopBundle/Form/Extension/AutoCompleteExtension.php
Labels: QA ✔️, develop, Feature

#32055 Implement Add Alias Command
  src/Adapter/Alias/CommandHandler/AddAliasHandler.php
  src/Adapter/Alias/QueryHandler/GetAliasForEditingHandler.php
  src/Adapter/Alias/Repository/AliasRepository.php
  src/Adapter/Alias/Validate/AliasValidator.php
  src/Core/Domain/Alias/Command/AddAliasCommand.php
  src/Core/Domain/Alias/CommandHandler/AddAliasHandlerInterface.php
  src/Core/Domain/Alias/Exception/AliasConstraintException.php
  src/Core/Domain/Alias/Exception/AliasException.php
  src/Core/Domain/Alias/Exception/AliasNotFoundException.php
  src/Core/Domain/Alias/Exception/CannotAddAliasException.php
  src/Core/Domain/Alias/Query/GetAliasForEditing.php
  src/Core/Domain/Alias/QueryHandler/GetAliasForEditingHandlerInterface.php
  src/Core/Domain/Alias/QueryResult/AliasForEditing.php
  src/Core/Domain/Alias/ValueObject/AliasId.php
  src/PrestaShopBundle/Resources/config/services/adapter/alias.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
  tests/Integration/Behaviour/Features/Context/Domain/AliasFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Search/add_alias.feature
  tests/Integration/Behaviour/behat.yml
  tests/Unit/Core/Domain/Alias/ValueObject/AliasIdTest.php
Labels: develop, Refactoring

#32155 Don't attach logo to emails if text only mails is configured 8.1.x
  classes/Mail.php
Labels: QA ✔️, PM ✔️, Bug fix, 8.1.x

#32465 Fix: Useless redirection in the Customer Service page
  controllers/admin/AdminCustomerThreadsController.php
Labels: QA ✔️, Bug fix

#32438 Fix minimum quantity label
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/QuantityType.php
Labels: QA ✔️, Refactoring

#32395 Introduce `FormHelper` and deprecate `CommonAbstractType`
  src/Adapter/CombinationDataProvider.php
  src/Adapter/Product/AdminProductWrapper.php
  src/PrestaShopBundle/Form/Admin/Feature/ProductFeature.php
  src/PrestaShopBundle/Form/Admin/Product/ProductCombination.php
  src/PrestaShopBundle/Form/Admin/Product/ProductCombinationBulk.php
  src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php
  src/PrestaShopBundle/Form/Admin/Product/ProductOptions.php
  src/PrestaShopBundle/Form/Admin/Product/ProductPrice.php
  src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php
  src/PrestaShopBundle/Form/Admin/Product/ProductSpecificPrice.php
  src/PrestaShopBundle/Form/Admin/Product/ProductSupplierCombination.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/BulkCombinationPriceType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationPriceImpactType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Options/ProductSupplierType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/PricingType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/SpecificPriceImpactType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/UnitPriceType.php
  src/PrestaShopBundle/Form/Admin/Type/CommonAbstractType.php
  src/PrestaShopBundle/Form/Extension/CustomMoneyTypeExtension.php
  src/PrestaShopBundle/Form/FormHelper.php
Labels: QA ✔️, develop, Feature, Deprecations

#32505 Merge 8.0.x into 8.1.x
  controllers/front/DiscountController.php
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/01_information/02_enableDisablePartialUse.ts
Labels: Improvement

#32536 Update default catalog 8.1.x
  translations/default/AdminInternationalHelp.xlf
Labels: Improvement

#32539 Bump ps_themecusto to v1.2.3
  composer.lock
Labels: Improvement, develop

#32506 Removes the placeholder for the import form on advanced parameters
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Import/ImportType.php
Labels: QA ✔️, develop, Bug fix

#32492 Fix: Can't use LIMIT clause in Sql request manager
  classes/RequestSql.php
Labels: QA ✔️, Bug fix

#32515 fix(trans): removed old htmlspecialchar parameters in smarty config
  config/smartyadmin.config.inc.php
Labels: QA ✔️, develop, Bug fix

#32551 Bump ps_linklist to v6.0.1
  composer.lock
Labels: Improvement, develop

#32312 Fix quantity check when there a customization in cart
  classes/Cart.php
  classes/Pack.php
  classes/Product.php
  controllers/front/CartController.php
Labels: QA ✔️, develop, Bug fix

#31921 Verify file exists before parsing it in ThemeValidatorTest
  tests/Unit/Core/Addon/Theme/ThemeValidatorTest.php
Labels: Improvement, develop

#30922 500 Error fix for Admin Categories If description null
  src/Core/Grid/Data/Factory/AbstractCategoryDataFactory.php
Labels: develop, Bug fix

#32514 Remove compatibility for php versions inferior to PHP 8.1
  .github/workflows/behaviour-skip.yml
  .github/workflows/behaviour.yml
  .github/workflows/cron_docker_build.yml
  .github/workflows/integration-skip.yml
  .github/workflows/integration.yml
  .github/workflows/php-skip.yml
  .github/workflows/php.yml
  .github/workflows/sanity-productV2-skip.yml
  .github/workflows/sanity-productV2.yml
  .github/workflows/sanity.yml
  .github/workflows/skip-sanity-productV2.yml
  INSTALL.txt
  README.md
  composer.json
  composer.lock
  install-dev/install_version.php
  phpstan.neon.dist
  tools/build/Library/InstallUnpacker/index_template.php
Labels: Improvement, develop, BC break

#32160 Re-Removed deprecated method Tools::isBright & Tools::getBrightness
  classes/Tools.php
Labels: QA ✔️, develop, Refactoring, BC break

#32474 Add phpmyadmin service as optional
  README.md
  docker-compose.override.yml.dist
  docker-composer.override.yml
Labels: Improvement, QA ✔️, develop

#32562 Update Composer dependencies
  composer.lock
Labels: Improvement

#32370 Add customer `GenderType` and `GroupType`
  src/Adapter/Form/ChoiceProvider/GroupByIdChoiceProvider.php
  src/Core/Grid/Definition/Factory/CustomerGridDefinitionFactory.php
  src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php
  src/PrestaShopBundle/Form/Admin/Sell/Customer/GenderType.php
  src/PrestaShopBundle/Form/Admin/Sell/Customer/GroupType.php
  src/PrestaShopBundle/Resources/config/services/adapter/form.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_definition_factory.yml
Labels: QA ✔️, develop, Feature, Bug fix

#32410 Functional Tests : BO - Design - Image Settings - Check category image format
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/13_checkProductImageFormat.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/14_checkCategoryImageFormat.ts
  tests/UI/commonTests/BO/catalog/category.ts
  tests/UI/pages/FO/category/index.ts
Labels: Improvement, QA ✔️, TE, E2E Tests

#32417 Functional Tests : CLDR - Search a currency by ISO code
  tests/UI/campaigns/cldr/04_searchCurrencyByISOCode.ts
  tests/UI/data/demo/currencies.ts
Labels: Improvement, TE, E2E Tests

#32511 Functional Tests : BO - Shop Parameters - Search : Fuzzy search
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/01_search/01_editSearchSettings/03_fuzzySearch.ts
  tests/UI/pages/BO/shopParameters/search/index.ts
Labels: Improvement, TE, E2E Tests

#32529 Functional Tests : BO - Design - Image Settings - Check stores image format
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/15_checkStoreImageFormat.ts
  tests/UI/data/faker/store.ts
  tests/UI/data/types/store.d.ts
  tests/UI/pages/BO/shopParameters/stores/add.ts
  tests/UI/pages/FO/stores/index.ts
Labels: Improvement, QA ✔️, TE, E2E Tests

#32545 Functional tests - Fix 'BO > Redisplay cart at login' test
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/01_redisplayCartAtLogin.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#32431 Functional Tests : WS - Countries : CRUD
  tests/UI/campaigns/functional/API/01_basicTest.ts
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/01_internalAuthServer/01_authorizationEndpoint.ts
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/01_internalAuthServer/02_resourceEndpoint.ts
  tests/UI/campaigns/functional/WS/01_countriesCRUD.ts
  tests/UI/commonTests/BO/advancedParameters/ws.ts
  tests/UI/data/faker/webservice.ts
  tests/UI/data/types/webservice.d.ts
  tests/UI/package-lock.json
  tests/UI/package.json
  tests/UI/pages/BO/advancedParameters/webservice/add.ts
  tests/UI/pages/BO/advancedParameters/webservice/index.ts
  tests/UI/pages/BO/international/locations/countries/add.ts
  tests/UI/utils/helpers.ts
  tests/UI/utils/ws.ts
Labels: Improvement, QA ✔️, TE, E2E Tests

#32159 Removed deprecated parameters in `OrderReturn`
  classes/order/OrderReturn.php
  tests/Integration/Behaviour/Features/Context/OrderReturnFeatureContext.php
Labels: Improvement, develop, BC break

#32535 Fix: Empty tracking URL for "in transit" email
  classes/order/OrderCarrier.php
Labels: QA ✔️, Bug fix

#32318 Translation app URL, refresh and selection issues
  admin-dev/themes/new-theme/js/app/pages/translations/router/index.ts
  admin-dev/themes/new-theme/js/pages/translation-settings/FormFieldToggle.ts
Labels: QA ✔️, Bug fix

#32424 Update BO stock router
  admin-dev/themes/new-theme/js/app/pages/stock/router/index.ts
Labels: QA ✔️, develop, Bug fix

#32509 Fix css for search dropdown in combination generator (81x)
  admin-dev/themes/new-theme/js/pages/product/combination/generator/CombinationGenerator.vue
  admin-dev/themes/new-theme/js/vue/components/Modal.vue
  admin-dev/themes/new-theme/scss/components/_entity_search.scss
  admin-dev/themes/new-theme/scss/components/_twitter_typeahead.scss
  admin-dev/themes/new-theme/scss/pages/product/product_page.scss
Labels: QA ✔️, develop, Bug fix

#32555 Functional tests - Add some tests in 'BO > Merchandise return' page
  tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/01_merchandiseReturnOptions.ts
  tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/02_deleteProduct.ts
  tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/03_updateStatus.ts
  tests/UI/pages/BO/customerService/merchandiseReturns/edit.ts
  tests/UI/pages/BO/customerService/merchandiseReturns/index.ts
  tests/UI/pages/BO/dashboard/index.ts
  tests/UI/pages/FO/myAccount/orderDetails.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#32595 Functional Tests : Remove JS support
  tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/03_updateStatus.ts
  tests/UI/data/types/order.d.ts
  tests/UI/package.json
  tests/UI/pages/FO/myAccount/orderDetails.ts
Labels: Improvement, QA ✔️, TE, E2E Tests

#32589 Remove default value for Customer Group form
  src/PrestaShopBundle/Form/Admin/Sell/Customer/GroupType.php
Labels: QA ✔️, develop, Bug fix

#32554 Fix states selector in back office stores form
  admin-dev/themes/default/template/helpers/form/form.tpl
  controllers/admin/AdminStoresController.php
  js/admin.js
Labels: QA ✔️, develop, Bug fix

#29520 Fix shipping cost on order details page
  src/Adapter/Presenter/Order/OrderDetailLazyArray.php
Labels: QA ✔️, develop, Bug fix

#32607 Functional Tests : Fixed Mocha typescript loader
  tests/UI/.mocharc.json
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/01_internalAuthServer/01_authorizationEndpoint.ts
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/01_internalAuthServer/02_resourceEndpoint.ts
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/02_externalAuthServer/01_authorizationEndpoint.ts
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/features/02_sortPaginationAndBulkDelete.ts
  tests/UI/campaigns/functional/BO/07_modules/01_moduleManager/10_seeMore.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/09_imageGenerationOptions.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/14_checkCategoryImageFormat.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/15_checkStoreImageFormat.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/01_general/maintenance/01_enableDisableShop.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/02_performance/02_debugMode.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/06_quickEditAndBulkActionsShopUrls.ts
  tests/UI/campaigns/functional/WS/01_countriesCRUD.ts
  tests/UI/package.json
  tests/UI/tools/stepIdentifiersChecker.ts
Labels: QA ✔️, TE, Bug fix, E2E Tests

#32411 Add missing MPN column into products CSV example
  docs/csv_import/products_import.csv
  tests/UI/campaigns/functional/BO/14_advancedParameters/05_import/01_downloadSampleFiles.ts
Labels: Improvement, QA ✔️, develop

#32609 Fix missing AdminSecurity for 8.1.x
  src/PrestaShopBundle/Command/SecurityAnnotationLinterCommand.php
  src/PrestaShopBundle/Controller/Admin/AttachementProductController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AuthorizationServer/ApiAccessController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AuthorizationServer/ApplicationController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/TranslationsController.php
  src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php
  src/PrestaShopBundle/Controller/Admin/Improve/Shipping/CarriersController.php
  src/PrestaShopBundle/Controller/Admin/ProductController.php
  src/PrestaShopBundle/Controller/Admin/ProductImageController.php
  src/PrestaShopBundle/Controller/Admin/SupplierController.php
  src/PrestaShopBundle/Controller/Admin/VirtualProductController.php
  src/PrestaShopBundle/Controller/Admin/WarehouseController.php
  src/PrestaShopBundle/Resources/config/routing/admin/_common.yml
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/authorization_server.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/shipping/carriers.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products/product.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products/products.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products/suppliers.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products/warehouses.yml
Labels: Improvement, QA ✔️

#32563 Update EmailConfigurationTester.php
  src/Adapter/Email/EmailConfigurationTester.php
Labels: QA ✔️, develop, Bug fix

#32664 Fix modules page bulk action
  admin-dev/themes/new-theme/js/pages/module/controller.js
Labels: QA ✔️, develop, Bug fix

#32657 Remove empty value for default customer group
  src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php
Labels: QA ✔️, develop, Bug fix

#32671 Fix confirm text for bulk actions in module manager
  admin-dev/themes/new-theme/js/pages/module/controller.js
Labels: QA ✔️, develop, Bug fix

#32656 Fix: Warning on the Cart Rules creation/editing page
  controllers/admin/AdminCartRulesController.php
Labels: QA ✔️, Bug fix

#32673 Add some comments to controllers
  classes/controller/FrontController.php
  classes/controller/ModuleFrontController.php
  controllers/admin/AdminCustomerThreadsController.php
  controllers/admin/AdminImagesController.php
  controllers/admin/AdminImportController.php
  controllers/admin/AdminLegacyLayoutController.php
  controllers/admin/AdminLoginController.php
  controllers/admin/AdminModulesPositionsController.php
  controllers/admin/AdminNotFoundController.php
  controllers/admin/AdminShopController.php
  controllers/admin/AdminShopGroupController.php
  controllers/admin/AdminShopUrlController.php
  controllers/admin/AdminStatsTabController.php
  controllers/front/AuthController.php
  controllers/front/CartController.php
  controllers/front/CmsController.php
  controllers/front/GetFileController.php
  controllers/front/OrderController.php
  controllers/front/PageNotFoundController.php
  controllers/front/ProductController.php
  controllers/front/RegistrationController.php
  controllers/front/UploadController.php
  controllers/front/listing/BestSalesController.php
  controllers/front/listing/CategoryController.php
  controllers/front/listing/ManufacturerController.php
  controllers/front/listing/NewProductsController.php
  controllers/front/listing/PricesDropController.php
  controllers/front/listing/SearchController.php
  controllers/front/listing/SupplierController.php
Labels: develop, Refactoring

#32669 Change hook status command logic
  src/Adapter/Hook/CommandHandler/UpdateHookStatusCommandHandler.php
  src/Core/Domain/Hook/Command/UpdateHookStatusCommand.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/PositionsController.php
Labels: Improvement, QA ✔️, develop, BC break

#32682 Remove workflow skipping that ignored some tests in some cases
  .github/workflows/behaviour-skip.yml
  .github/workflows/behaviour.yml
  .github/workflows/integration-skip.yml
  .github/workflows/integration.yml
  .github/workflows/js-skip.yml
  .github/workflows/js.yml
  .github/workflows/lint-skip.yml
  .github/workflows/lint.yml
  .github/workflows/php-skip.yml
  .github/workflows/php.yml
  .github/workflows/sanity-productV2-skip.yml
  .github/workflows/sanity-productV2.yml
  .github/workflows/skip-sanity-productV2.yml
Labels: Improvement, develop

#32660 Use service discovery for Twig extensions
  src/PrestaShopBundle/EventListener/TokenizedUrlsListener.php
  src/PrestaShopBundle/Resources/config/services/bundle/bridge/_admin_controller.yml
  src/PrestaShopBundle/Resources/config/services/bundle/bridge/_list.yml
  src/PrestaShopBundle/Resources/config/services/bundle/event_listener.yml
  src/PrestaShopBundle/Resources/config/services/bundle/services.yml
  src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
  src/PrestaShopBundle/Service/DataProvider/UserProvider.php
  src/PrestaShopBundle/Twig/Extension/JsRouterMetadataExtension.php
  src/PrestaShopBundle/Twig/Extension/PathWithBackUrlExtension.php
  src/PrestaShopBundle/Twig/LayoutExtension.php
  tests/Unit/PrestaShopBundle/Twig/Extension/PathWithBackUrlExtensionTest.php
Labels: QA ✔️, develop, Refactoring

#32679 Remove deprecated code
  classes/Combination.php
  classes/Product.php
  classes/Tools.php
  classes/Validate.php
  classes/controller/FrontController.php
  classes/stock/StockAvailable.php
  controllers/admin/AdminAttributesGroupsController.php
  controllers/admin/AdminLoginController.php
  controllers/admin/AdminProductsController.php
  controllers/front/CmsController.php
  controllers/front/PasswordController.php
  src/Adapter/Attribute/AdminAttributeGeneratorControllerWrapper.php
  tests/Resources/modules_tests/override/AdminProductsController.php
  tests/Resources/modules_tests/pscsx32412/override/controllers/admin/AdminProductsController.php
Labels: QA ✔️, develop, Refactoring, BC break

#32704 Nightly : Fixed fill of Adress Form
  tests/UI/pages/FO/checkout/index.ts
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#32659 Add changelog for 8.1.0 Release Candidate 1
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: Improvement

#32674 Functional Tests : Hummingbird : FO - Login : Login in FO
  tests/UI/campaigns/functional/FO/hummingbird/01_login/02_login.ts
  tests/UI/pages/FO/hummingbird/login/index.ts
  tests/UI/pages/FO/login/index.ts
Labels: Improvement, QA ✔️, TE, E2E Tests

#32668 Functional Tests : Cash on delivery (COD) module - Reset module
  tests/UI/campaigns/modules/ps_cashondelivery/01_installation/04_resetModule.ts
  tests/UI/data/demo/modules.ts
  tests/UI/package.json
  tests/UI/pages/BO/modules/moduleManager/index.ts
  tests/UI/pages/FO/checkout/index.ts
Labels: Improvement, QA ✔️, TE, E2E Tests

#32666 Functional Tests : BO - Design - Image Settings - Check base image format
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/15_checkStoreImageFormat.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/16_checkBaseImageFormat.ts
  tests/UI/pages/BO/design/imageSettings/index.ts
Labels: Improvement, QA ✔️, TE, E2E Tests

#32695 Url cleaner integration
  admin-dev/init.php
  classes/controller/AdminController.php
  src/Core/Util/Url/UrlCleaner.php
  tests/Unit/Core/Util/Url/UrlCleanerTest.php
Labels: QA ✔️, develop, Refactoring

#32693 Remove deprecated inside `AdminController`
  classes/controller/AdminController.php
Labels: QA ✔️, develop, Refactoring, BC break

#32691 Remove search parameters
  src/Core/Search/SearchParameters.php
  src/Core/Search/SearchParametersInterface.php
  src/PrestaShopBundle/Controller/ArgumentResolver/SearchParametersResolver.php
  src/PrestaShopBundle/Resources/config/services/core/search.yml
  tests/Unit/Core/Search/SearchParametersTest.php
  tests/Unit/PrestaShopBundle/Controller/ArgumentResolver/SearchParametersResolverTest.php
Labels: QA ✔️, develop, Refactoring, BC break

#29760 Invalid characters are being saved as Social titles
  classes/Gender.php
  controllers/admin/AdminGendersController.php
Labels: QA ✔️, Bug fix, BC break, Wording ✔️, Needs documentation, 9.0.x

#31666 Take locale into account when deciding whether module translation should fall back to the legacy system
  src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php
Labels: QA ✔️, develop, Bug fix

#32715 Fix: [BO] : Error notification displayed in Multistore page
  config/smarty.config.inc.php
Labels: QA ✔️, 8.0.x, Bug fix

#32524 Migrate choice providers to autowiring 1/X
  src/Core/Form/ChoiceProvider/DeliveryTimeNoteTypesProvider.php
  src/Core/Form/ChoiceProvider/OrderStateByIdChoiceProvider.php
  src/Core/Form/ChoiceProvider/OutOfStockTypeChoiceProvider.php
  src/Core/Form/ChoiceProvider/PackStockTypeChoiceProvider.php
  src/Core/Form/ChoiceProvider/ProductTypeChoiceProvider.php
  src/PrestaShopBundle/Resources/config/services/adapter/data_configuration.yml
  src/PrestaShopBundle/Resources/config/services/adapter/data_provider_common.yml
  src/PrestaShopBundle/Resources/config/services/adapter/shop_feature.yml
  src/PrestaShopBundle/Resources/config/services/core/domain/theme.yml
  src/PrestaShopBundle/Resources/config/services/core/form/choice_provider.yml
  src/PrestaShopBundle/Resources/config/services/core/form/choice_provider_deprecated.yml
  src/PrestaShopBundle/Resources/config/services/core/foundation.yml
  src/PrestaShopBundle/Resources/config/services/core/help.yml
  src/PrestaShopBundle/Resources/config/services/core/language.yml
  src/PrestaShopBundle/Resources/config/services/core/localization.yml
  tests/Unit/Core/Form/ChoiceProvider/OutOfStockTypeChoiceProviderTest.php
  tests/Unit/Core/Form/ChoiceProvider/PackStockTypeChoiceProviderTest.php
Labels: QA ✔️, develop, Refactoring

#32500 Fix PDF invoice generator footer which only shows a %s
  classes/Translate.php
  pdf/footer.tpl
Labels: QA ✔️, develop, Bug fix

#32752 Update default catalog 8.1.x
  translations/default/AdminActions.xlf
  translations/default/AdminCatalogFeature.xlf
  translations/default/AdminCatalogNotification.xlf
  translations/default/AdminInternationalNotification.xlf
  translations/default/AdminModulesNotification.xlf
  translations/default/AdminNavigationMenu.xlf
  translations/default/AdminNotificationsError.xlf
  translations/default/AdminShippingNotification.xlf
  translations/default/EmailsSubject.xlf
Labels: Improvement

#32599 Country choice improvements
  src/PrestaShopBundle/Form/Admin/Improve/International/Localization/LocalizationConfigurationType.php
  src/PrestaShopBundle/Form/Admin/Sell/CatalogPriceRule/CatalogPriceRuleType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/ApplicableGroupsType.php
  src/PrestaShopBundle/Form/Admin/Type/CountryChoiceType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
Labels: Improvement, QA ✔️, develop

#32758 fix(ci): template update package fix table 8.0.x
  .github/workflows/cron_update_modules/script.php
Labels: Improvement, 8.0.x

#32707 Split symfony components in composer.json
  composer.json
  composer.lock
Labels: Improvement, develop

#31146 Change version to 9.0.0
  install-dev/install_version.php
  src/Core/Version.php
Labels: Improvement, develop

#32718 Functional tests - Add some tests in 'FO > Carts' page
  tests/UI/campaigns/functional/FO/classic/10_cart/02_cart/01_changeQuantity.ts
  tests/UI/campaigns/functional/FO/classic/10_cart/02_cart/02_deleteProduct.ts
  tests/UI/campaigns/functional/FO/classic/10_cart/02_cart/03_addPromoCode.ts
  tests/UI/pages/FO/cart/index.ts
Labels: QA ✔️, TE, Refactoring, E2E Tests

#32652 Introduce store presenter
  controllers/front/StoresController.php
  install-dev/data/xml/hook.xml
  src/Adapter/Presenter/Store/StoreLazyArray.php
  src/Adapter/Presenter/Store/StorePresenter.php
Labels: QA ✔️, develop, Feature, Needs autoupgrade PR

#32759 Update jsrouting to 3.2.1
  composer.json
  composer.lock
Labels: Improvement, develop
