Repository PrestaShop/PrestaShop, pull requests merged in 2023-12, with the labels that each got.

#33945 Fix specific price datetime range
  admin-dev/themes/new-theme/js/pages/catalog/product/specific-price-form-handler.ts
  src/PrestaShopBundle/Controller/Admin/SpecificPriceController.php
  src/PrestaShopBundle/Form/Admin/Product/ProductSpecificPrice.php
  src/PrestaShopBundle/Form/Admin/Sell/CatalogPriceRule/CatalogPriceRuleType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/SpecificPriceType.php
  src/PrestaShopBundle/Form/Admin/Type/DateRangeType.php
Labels: QA ✔️, Bug fix, BC break, 8.1.x

#34499 Migrate more properties to lazy array
  classes/Pack.php
  classes/Product.php
  controllers/front/ProductController.php
  src/Adapter/Presenter/Product/ProductLazyArray.php
  src/Adapter/Presenter/Product/ProductListingLazyArray.php
Labels: QA ✔️, develop, Refactoring, BC break

#34715 Fix combination search in PPV2 specific price
  src/Adapter/Product/Combination/Repository/CombinationRepository.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/SearchProductCombinationFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/Combination/search_product_combinations.feature
Labels: QA ✔️, Bug fix, 8.1.x

#34699 Fix customer search in specific price PPV2
  admin-dev/themes/new-theme/js/pages/product/specific-price/form/customer-selector.ts
Labels: QA ✔️, Bug fix, 8.1.x

#34606 Optimize product page
  src/Adapter/Feature/Repository/FeatureRepository.php
  src/Adapter/Feature/Repository/FeatureValueRepository.php
  src/Adapter/Form/ChoiceProvider/FeatureValuesChoiceProvider.php
  src/Adapter/Form/ChoiceProvider/FeaturesChoiceProvider.php
  src/Adapter/Product/FeatureValue/QueryHandler/GetProductFeatureValuesHandler.php
  src/PrestaShopBundle/Resources/config/services/adapter/form.yml
Labels: Improvement, QA ✔️, 8.1.x

#34721 Fix use of front_legacy_context constant in FrontController
  classes/controller/FrontController.php
Labels: QA ✔️, develop, Bug fix

#34370 Load theme css on maintenance page
  classes/controller/FrontController.php
Labels: QA ✔️, develop, Bug fix

#34773 Modify sanity tests workflow to use docker
  .github/workflows/sanity-productV2-skip.yml
  .github/workflows/sanity-productV2.yml
  .github/workflows/sanity.yml
Labels: Improvement, Waiting for QA, 8.1.x

#34741 Backport v9 SymfonyCacheClearer
  app/AppKernel.php
  install-dev/controllers/console/process.php
  src/Adapter/Cache/Clearer/SymfonyCacheClearer.php
  src/Adapter/ContainerBuilder.php
Labels: Improvement, QA ✔️, 8.1.x

#34731 Fix module upgrades, cleanup a bit
  classes/module/Module.php
  src/Adapter/Module/ModuleDataUpdater.php
  src/Core/Addon/Module/ModuleManagerBuilder.php
  src/Core/Module/ModuleManager.php
  src/PrestaShopBundle/Resources/views/Admin/Module/Includes/modal_read_more_content.html.twig
Labels: QA ✔️, develop, Bug fix, BC break

#34749 Functional tests - Fix nightly : BO:Catalog:07-08
  tests/UI/pages/BO/catalog/stocks/movements/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34764 SF6 - Remove deprecated code from TwigBundle
  config/smarty.config.inc.php
  src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php
  src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
  src/PrestaShopBundle/Twig/TranslationsExtension.php
Labels: Improvement, develop

#34778 SF6 - Remove deprecated code from HttpKernel
  index.php
  src/PrestaShopBundle/Controller/Api/Readme.md
  src/PrestaShopBundle/Resources/config/routing/api/attributes.yml
  src/PrestaShopBundle/Resources/config/routing/api/categories.yml
  src/PrestaShopBundle/Resources/config/routing/api/features.yml
  src/PrestaShopBundle/Resources/config/routing/api/i18n.yml
  src/PrestaShopBundle/Resources/config/routing/api/improve/design/positions.yml
  src/PrestaShopBundle/Resources/config/routing/api/manufacturers.yml
  src/PrestaShopBundle/Resources/config/routing/api/stock_movements.yml
  src/PrestaShopBundle/Resources/config/routing/api/stocks.yml
  src/PrestaShopBundle/Resources/config/routing/api/suppliers.yml
  src/PrestaShopBundle/Resources/config/routing/api/translations.yml
  src/PrestaShopBundle/Resources/config/services/bundle/controller.yml
Labels: Improvement, develop, BC break

#34780 SF6 - Remove deprecated code from HttpFoundation
  admin-dev/index.php
  src/PrestaShopBundle/Controller/Admin/CommonController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmailController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceController.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/CmsPageController.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/PositionsController.php
  src/PrestaShopBundle/Controller/Admin/Improve/Shipping/CarriersController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/AttributeController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/AttributeGroupController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/SupplierController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
  src/PrestaShopBundle/EventListener/TokenizedUrlsListener.php
Labels: Improvement, develop

#34732 Refacto(api): change the uri to respect the adr
  src/PrestaShopBundle/ApiPlatform/Resources/CartRule.php
Labels: QA ✔️, develop, Refactoring

#34790 CACHEDIR.TAG - saving resources and disk space
  img/tmp/CACHEDIR.TAG
  var/cache/CACHEDIR.TAG
Labels: Improvement, QA ✔️, develop

#34746 Workflow: fix error on GCP auth for nightly
  .github/workflows/cron_nightly_build.yml
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34810 Bump to 1.7.8.11
  app/AppKernel.php
  install-dev/install_version.php
Labels: Improvement, 1.7.7.x, 1.7.8.x

#34666 Handle return in CommandProcessor to return resource content after modification
  composer.lock
  phpstan.neon.dist
  src/Core/Domain/Customer/Group/Command/DeleteCustomerGroupCommand.php
  src/PrestaShopBundle/ApiPlatform/DomainSerializer.php
  src/PrestaShopBundle/ApiPlatform/Exception/CQRSCommandNotFoundException.php
  src/PrestaShopBundle/ApiPlatform/Exception/CQRSQueryNotFoundException.php
  src/PrestaShopBundle/ApiPlatform/Metadata/AbstractCQRSOperation.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSCommand.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSCreate.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSDelete.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSGet.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSUpdate.php
  src/PrestaShopBundle/ApiPlatform/Normalizer/CQRSApiNormalizer.php
  src/PrestaShopBundle/ApiPlatform/Normalizer/DateTimeImmutableNormalizer.php
  src/PrestaShopBundle/ApiPlatform/Normalizer/DecimalNumberNormalizer.php
  src/PrestaShopBundle/ApiPlatform/Processor/CommandProcessor.php
  src/PrestaShopBundle/ApiPlatform/Provider/QueryProvider.php
  src/PrestaShopBundle/ApiPlatform/QueryResultSerializerTrait.php
  src/PrestaShopBundle/ApiPlatform/Resources/CartRule.php
  src/PrestaShopBundle/ApiPlatform/Resources/CustomerGroup.php
  src/PrestaShopBundle/ApiPlatform/Resources/FoundProduct.php
  src/PrestaShopBundle/ApiPlatform/Resources/Hook.php
  src/PrestaShopBundle/Resources/config/services/bundle/oauth.yml
  src/PrestaShopBundle/Resources/config/services/bundle/services.yml
  src/PrestaShopBundle/Security/OAuth2/Repository/ScopeRepository.php
  tests/Integration/ApiPlatform/DomainSerializerTest.php
  tests/Integration/ApiPlatform/EndPoint/ApiAccessTokenEndpointTest.php
  tests/Integration/ApiPlatform/EndPoint/ApiTestCase.php
  tests/Integration/ApiPlatform/EndPoint/CustomerGroupApiTest.php
  tests/Integration/ApiPlatform/EndPoint/GetHookApiTest.php
  tests/Integration/ApiPlatform/EndPoint/GetHookStatusApiTest.php
  tests/Integration/ApiPlatform/PostCustomerTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/DomainSerializerTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSCommandTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSCreateTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSDeleteTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSGetTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSUpdateTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/StateProvider/QueryProviderTest.php
Labels: QA ✔️, develop, Feature

#34812 Bump classic-theme to 2.1.2
  composer.lock
Labels: Improvement, Waiting for QA, 8.1.x

#34811 Exclude new routes for Security Annotation linter command
  src/PrestaShopBundle/Command/SecurityAnnotationLinterCommand.php
Labels: Improvement, 8.1.x

#34772 Functional tests - Add check received mail from contact us page
  tests/UI/campaigns/functional/FO/classic/05_contactUs/02_sendMessageWithCustomer.ts
  tests/UI/campaigns/functional/FO/classic/05_contactUs/03_sendMessageAsAnonymous.ts
  tests/UI/pages/BO/modules/contactForm/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34818 Deal with security deprecations
  src/PrestaShopBundle/Security/Admin/Employee.php
  src/PrestaShopBundle/Security/Admin/EmployeeProvider.php
Labels: develop, Refactoring, BC break

#34668 Functional Tests : Mail alerts module - Customer notifications - Enable/Disable product availability
  tests/UI/campaigns/modules/ps_emailalerts/02_configuration/01_configurationForCustomer/01_enableDisableProductAvailability.ts
  tests/UI/pages/BO/modules/psEmailAlerts/index.ts
  tests/UI/pages/FO/product/index.ts
  tests/UI/pages/commonPage.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#34817 Functional Tests : Mail alerts module - Merchant notifications - Enable/Disable new order
  tests/UI/campaigns/modules/ps_emailalerts/02_configuration/01_customerNotifications/01_enableDisableProductAvailability.ts
  tests/UI/campaigns/modules/ps_emailalerts/02_configuration/02_merchantNotifications/01_enableDisableNewOrder.ts
  tests/UI/campaigns/modules/ps_emailalerts/02_configuration/02_merchantNotifications/04_enableDisableReturn.ts
  tests/UI/pages/BO/modules/psEmailAlerts/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34820 Update prestashop modules for 1.7.8.11
  composer.json
  composer.lock
Labels: Improvement, Waiting for QA

#34834 Unreleased version of Classic is required for v9
  composer.json
  composer.lock
Labels: Waiting for QA

#34829 Functional Tests : Mail alerts module - Merchant notifications - Enable/Disable out of stock
  tests/UI/campaigns/modules/ps_emailalerts/02_configuration/02_merchantNotifications/02_enableDisableOutOfStock.ts
  tests/UI/pages/BO/modules/psEmailAlerts/index.ts
Labels: TE, develop, Refactoring, E2E Tests

#34824 Functional Tests : Mail alerts module - Customer notifications - Enable/Disable order edit
  tests/UI/campaigns/modules/ps_emailalerts/02_configuration/01_customerNotifications/02_enableDisableOrderEdit.ts
  tests/UI/pages/BO/modules/psEmailAlerts/index.ts
  tests/UI/pages/BO/orders/view/productsBlock.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34827 Test: use locator for textContent, hover, fill and getAttribute
  admin-dev/themes/new-theme/js/app/components/checkboxes-dropdown/CheckboxesDropdown.vue
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/advancedParameters/APIAccess/add.ts
  tests/UI/pages/BO/advancedParameters/email/index.ts
  tests/UI/pages/BO/advancedParameters/featureFlag/index.ts
  tests/UI/pages/BO/advancedParameters/import/index.ts
  tests/UI/pages/BO/advancedParameters/logs/index.ts
  tests/UI/pages/BO/advancedParameters/team/myProfile.ts
  tests/UI/pages/BO/catalog/categories/add.ts
  tests/UI/pages/BO/catalog/categories/index.ts
  tests/UI/pages/BO/catalog/discounts/add.ts
  tests/UI/pages/BO/catalog/products/add/combinationsTab.ts
  tests/UI/pages/BO/catalog/products/add/descriptionTab.ts
  tests/UI/pages/BO/catalog/products/add/index.ts
  tests/UI/pages/BO/catalog/products/add/packTab.ts
  tests/UI/pages/BO/customerService/customerService/index.ts
  tests/UI/pages/BO/design/imageSettings/index.ts
  tests/UI/pages/BO/design/linkWidgets/add.ts
  tests/UI/pages/BO/design/themeAndLogo/themeAndLogo/themeAndLogoBasePage.ts
  tests/UI/pages/BO/international/currencies/add.ts
  tests/UI/pages/BO/international/currencies/index.ts
  tests/UI/pages/BO/international/locations/countries/add.ts
  tests/UI/pages/BO/modules/keycloakConnectorDemo/index.ts
  tests/UI/pages/BO/orders/index.ts
  tests/UI/pages/BO/orders/invoices/index.ts
  tests/UI/pages/BO/orders/view/productsBlock.ts
  tests/UI/pages/BO/shopParameters/trafficAndSeo/seoAndUrls/add.ts
  tests/UI/pages/FO/FObasePage.ts
  tests/UI/pages/FO/category/index.ts
  tests/UI/pages/FO/checkout/index.ts
  tests/UI/pages/FO/home/index.ts
  tests/UI/pages/FO/searchResults/index.ts
  tests/UI/pages/commonPage.ts
  tests/UI/pages/install/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34833 Add an address alias to the list of available addresses
  src/Core/Form/ChoiceProvider/CustomerAddressesChoiceProvider.php
Labels: QA ✔️

#34792 SF6: Use AbstractAuthenticator for TokenAuthenticator
  app/config/security.yml
  src/Core/Security/OAuth2/TokenAuthenticator.php
  tests/Integration/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminControllerTest.php
  tests/Integration/Utility/AdapterSecurityAdmin.php
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/01_internalAuthServer/02_resourceEndpoint.ts
  tests/Unit/Core/Security/TokenAuthenticatorTest.php
Labels: Improvement, QA ✔️, develop, Bug fix, BC break

#34857 Fix product csv import wiping category assignments, fixes #34601
  controllers/admin/AdminImportController.php
Labels: QA ✔️

#34883 Nightly : Fixed error after #34833
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/01_customerBlock.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/11_checkInvoice.ts
Labels: QA ✔️, TE, E2E Tests

#34890 UI Tests: Add .env.local for nightly use on 1.7.8.x (backport of 34759)
  .github/actions/setup-env/action.yml
  .github/actions/ui-test/action.yml
  .github/workflows/sanity-72.yml
  .github/workflows/sanity-73.yml
  .github/workflows/sanity-74.yml
  .github/workflows/sanity.yml
  .github/workflows/sanity/apache-vhost
  .github/workflows/sanity/setup-apache.sh
  tests/UI/.env.ci
  tests/UI/campaigns/utils/globals.js
  tests/UI/package-lock.json
  tests/UI/package.json
Labels: TE, Refactoring, E2E Tests, 1.7.8.x

#34893 Sanity: Fix sanity command to stop after first fail
  .github/workflows/sanity.yml
Labels: TE, Refactoring, E2E Tests, 8.1.x

#34894 Move returns templates to proper location
  src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/MerchandiseReturnController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/CustomerService/MerchandiseReturn/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/CustomerService/MerchandiseReturn/edit.html.twig
Labels: QA ✔️

#34882 Functional Tests : BO - Advanced Parameter - Authorization Server : Edit API Access (Enabled/Disabled)
  tests/UI/campaigns/functional/BO/14_advancedParameters/12_authorizationServer/03_editAPIAccess.ts
  tests/UI/pages/BO/advancedParameters/APIAccess/add.ts
  tests/UI/pages/BO/advancedParameters/APIAccess/index.ts
  tests/UI/pages/BO/advancedParameters/database/sqlManager/view.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#34919 Sanity Tests : Execute on Firefox & Chrome & Webkit
  .github/actions/ui-test/action.yml
  .github/workflows/sanity.yml
  tests/UI/campaigns/sanity/04_catalogFO/01_filterProducts.ts
  tests/UI/pages/BO/catalog/products/index.ts
  tests/UI/utils/helpers.ts
Labels: TE, E2E Tests

#34929 Add debug cookie configuration values to installation data
  install-dev/data/xml/configuration.xml
Labels: Waiting for QA
