Repository PrestaShop/PrestaShop, pull requests merged in 2024-01, with the labels that each got.

#34951 Fix CI for `8.1.x` branch after 8.1.3 release
  src/Core/ConstraintValidator/CleanHtmlValidator.php
  tests/Unit/Adapter/ValidateTest.php
  tests/Unit/Core/ConstraintValidator/CleanHtmlValidatorTest.php
Labels: Waiting for QA

#34903 Nightly: Add nightly.zip for prestashop/flashLight use
  .github/workflows/cron_nightly_build.yml
Labels: Improvement, QA ✔️, develop, CI/CD

#34946 Added id_shop param to actionAfterLoadRoutes Hook
  classes/Dispatcher.php
Labels: Waiting for QA

#34957 Remove old Czech lower VAT 10% and 15%
  localization/cz.xml
Labels: Waiting for QA

#34836 SF6- Remove deprecated code from FrameworkBundle
  app/config/config_test.yml
  classes/Context.php
  classes/Language.php
  classes/controller/AdminController.php
  classes/lang/DataLang.php
  controllers/admin/AdminImportController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php
  src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php
  src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Controller/Api/StockController.php
  src/PrestaShopBundle/Controller/Api/TranslationController.php
  src/PrestaShopBundle/EventListener/AccessDeniedListener.php
  src/PrestaShopBundle/EventListener/DemoModeEnabledListener.php
  src/PrestaShopBundle/EventListener/ModuleActivatedListener.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Import/ImportFormDataProvider.php
  src/PrestaShopBundle/Form/Extension/AlertsTrackingExtension.php
  src/PrestaShopBundle/Resources/config/services/adapter/admin.yml
  src/PrestaShopBundle/Resources/config/services/alias.yml
  src/PrestaShopBundle/Resources/config/services/bundle/controller.yml
  src/PrestaShopBundle/Resources/config/services/bundle/event_listener.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/config/services/bundle/grid.yml
  src/PrestaShopBundle/Security/Admin/SessionRenewer.php
  src/PrestaShopBundle/Service/Grid/ResponseBuilder.php
  tests/Integration/Adapter/SqlManager/QueryHandler/GetSqlRequestExecutionResultHandlerTest.php
  tests/Integration/Classes/controller/AdminControllerTest.php
  tests/Integration/PrestaShopBundle/Admin/Security/SessionRenewerTest.php
  tests/Integration/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceControllerTest.php
  tests/Integration/PrestaShopBundle/Controller/Admin/Improve/Design/PositionsControllerTest.php
  tests/Integration/PrestaShopBundle/Controller/Admin/Sell/Order/DeliveryControllerTest.php
  tests/Integration/PrestaShopBundle/Controller/Api/ApiTestCase.php
  tests/Integration/PrestaShopBundle/Controller/Api/StockManagementControllerTest.php
  tests/Unit/PrestaShopBundle/Service/Grid/ResponseBuilderTest.php
Labels: QA ✔️, BC break, Needs documentation

#34525 Remove some old deprecations
  .github/workflows/phpstan/autoload.php
  admin-dev/footer.inc.php
  admin-dev/header.inc.php
  admin-dev/index.php
  admin-dev/init.php
  admin-dev/themes/default/js/admin-theme.js
  admin-dev/themes/default/template/controllers/customer_threads/message.tpl
  admin-dev/themes/default/template/controllers/stores/helpers/options/options.tpl
  admin-dev/themes/default/template/controllers/tax_rules/helpers/form/form.tpl
  classes/Cart.php
  classes/PaymentModule.php
  classes/Product.php
  classes/Tab.php
  classes/helper/HelperList.php
  classes/order/OrderDetail.php
  config/config.inc.php
  config/defines.inc.php
  controllers/admin/AdminGroupsController.php
  controllers/admin/AdminModulesController.php
  controllers/admin/AdminSearchController.php
  controllers/front/MyAccountController.php
  js/admin.js
  js/admin/import.js
  src/Adapter/Cart/CartPresenter.php
  src/Adapter/Image/ImageRetriever.php
  src/Adapter/ObjectPresenter.php
  src/Adapter/Product/Pack/Repository/ProductPackRepository.php
  src/Adapter/Product/Pack/Update/ProductPackUpdater.php
  src/Core/Domain/Product/Combination/ValueObject/CombinationId.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmailController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SqlManagerController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/ContactsController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/MetaController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/LanguageController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/TaxController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/CreditSlipController.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/OrderPreferences/OrderPreferencesFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/ProductPreferencesFormDataProvider.php
  src/PrestaShopBundle/Routing/Converter/LegacyUrlConverter.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePackFeatureContext.php
  tests/Integration/PrestaShopBundle/Routing/Converter/LegacyUrlConverterTest.php
  tests/Integration/Utility/CartOld.php
  tests/Unit/PrestaShopBundle/Routing/Converter/LegacyUrlConverterTest.php
Labels: develop, Refactoring, BC break, Needs documentation

#34953 feat: Backport and add node and dev mode for composite on 1.7.8.x
  .docker/Dockerfile
  .github/actions/setup-env/action.yml
  docker-compose.yml
Labels: TE, Refactoring, E2E Tests, 1.7.8.x

#34945 feat: Backport and add node and dev mode for composite on 8.0.x
  .github/actions/setup-env/action.yml
Labels: TE, E2E Tests

#34931 feat: Backport and add node and dev mode for composite on 8.1.x
  .github/actions/setup-env/action.yml
Labels: TE, Refactoring, E2E Tests, 8.1.x

#34902 Nightly: use composite actions
  .github/actions/setup-env/action.yml
  .github/workflows/cron_nightly_tests_1.7.8.x.yml
  .github/workflows/cron_nightly_tests_8.0.x.yml
  .github/workflows/cron_nightly_tests_8.1.x.yml
  .github/workflows/cron_nightly_tests_develop.yml
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: Improvement, TE, develop, E2E Tests

#34969 Fix Nightly build workflow for 8.0.x and Develop
  .github/workflows/cron_nightly_build.yml
Labels: develop, Bug fix, CI/CD

#34948 Correct warning with substr if $component is an array
  classes/controller/FrontController.php
Labels: Waiting for author, Waiting for QA, develop, Bug fix

#34973 Merge `8.1.x` into `develop`
  .github/workflows/sanity.yml
  CONTRIBUTORS.md
  classes/CustomerMessage.php
  classes/Dispatcher.php
  classes/Validate.php
  controllers/admin/AdminImportController.php
  docs/CHANGELOG.txt
  js/admin.js
  js/tools.js
  localization/cz.xml
  src/Core/ConstraintValidator/CleanHtmlValidator.php
  tests/Unit/Adapter/ValidateTest.php
  tests/Unit/Core/ConstraintValidator/CleanHtmlValidatorTest.php
Labels: Improvement, QA ✔️, 8.1.x

#34907 Remove generation of unused file "fileType" in every image folder
  classes/ImageManager.php
  src/Adapter/Product/Update/ProductDuplicator.php
Labels: Waiting for QA, develop, Refactoring

#34940 Remove smarty precompilation and fix notices
  classes/Configuration.php
  config/defines.inc.php
  install-dev/classes/controllerHttp.php
  install-dev/controllers/http/smarty_compile.php
  install-dev/theme/js/install.js
  phpstan.neon.dist
Labels: Waiting for QA

#34982 Always set HelperKpi source and use conditional refresh
  controllers/admin/AdminCartsController.php
Labels: QA ✔️, Bug fix, 8.1.x

#35008 Improving Clarity: Refactor Image Link Handling in Link.php
  classes/Link.php
Labels: QA ✔️, develop, Bug fix, Refactoring

#34959 Functional tests - Add steps to check email when transform a guest to customer
  tests/UI/campaigns/functional/BO/04_customers/01_customers/11_transformGuestToCustomer.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34983 Functional Tests : Mail subscription - check verification and confirmation email after subscribe to newsletter
  tests/UI/campaigns/modules/ps_emailsubscription/02_configuration/01_checkVerificationEmail.ts
  tests/UI/campaigns/modules/ps_emailsubscription/02_configuration/02_checkConfirmatonEmail.ts
  tests/UI/pages/BO/modules/psEmailSubscription/index.ts
  tests/UI/pages/FO/home/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35018 Functional tests - Add steps to check emails in 'Enable/Disable product availability' test
  tests/UI/campaigns/modules/ps_emailalerts/02_configuration/01_customerNotifications/01_enableDisableProductAvailability.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34172 Remove image feature flag and fix original images
  classes/ImageManager.php
  classes/lang/KeysReference/FeatureFlagLang.php
  controllers/admin/AdminImagesController.php
  controllers/admin/AdminStoresController.php
  controllers/admin/AdminSuppliersController.php
  install-dev/data/xml/feature_flag.xml
  src/Adapter/Image/ImageGenerator.php
  src/Adapter/Image/ImageRetriever.php
  src/Adapter/Image/Uploader/CategoryCoverImageUploader.php
  src/Adapter/Image/Uploader/ManufacturerImageUploader.php
  src/Core/FeatureFlag/FeatureFlagSettings.php
  src/Core/Image/ImageFormatConfiguration.php
  src/Core/Shop/LogoUploader.php
  tests/Integration/Classes/controller/AdminControllerTest.php
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/09_imageGenerationOptions.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/10_regenerateThumbnails.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/11_imageGenerationOnCreation.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/13_checkProductImageFormat.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/14_checkCategoryImageFormat.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/15_checkStoreImageFormat.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/16_checkBaseImageFormat.ts
  tests/UI/commonTests/BO/advancedParameters/newFeatures.ts
  tests/UI/pages/BO/advancedParameters/featureFlag/index.ts
  tests/Unit/Core/Image/ImageFormatConfigurationTest.php
Labels: Waiting for author, Waiting for PM, develop, Refactoring, BC break, Needs documentation, Needs autoupgrade PR

#35036 Functional tests : Email subscription - Fix check confirmation email
  tests/UI/pages/BO/modules/psEmailSubscription/index.ts
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#35032 Functional tests : Mail subscription - Add new test to check 'Welcome voucher' email
  tests/UI/campaigns/modules/ps_emailsubscription/02_configuration/03_checkWelcomeVoucher.ts
  tests/UI/pages/BO/modules/psEmailSubscription/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35030 Add cachedir tag during release
  tools/build/Library/ReleaseCreator.php
Labels: QA ✔️, Feature, 8.1.x

#35027 Merge 8.1.x into develop
  src/Core/Cache/Clearer/CacheClearerChain.php
Labels: Improvement, develop

#35034 Bump ps emailalerts to v3
  composer.json
  composer.lock
Labels: Waiting for QA, 8.1.x

#34698 Allow Front controller called in cli if ssl is on or maintenance mode is on in 8.1
  classes/controller/FrontController.php
Labels: QA ✔️, Bug fix, 8.1.x

#35048 Functional tests - Add test to check received email in customer service page
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/03_respondToMessage.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35031 Functional tests - Add test to check email when the merchant change the order status
  tests/UI/campaigns/functional/BO/02_orders/01_orders/04_updateStatus.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34763 Features UX improvement
  admin-dev/themes/new-theme/js/pages/product/edit/manager/feature-values-manager.ts
  admin-dev/themes/new-theme/js/pages/product/product-map.ts
  admin-dev/themes/new-theme/scss/pages/product/product_page.scss
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/FeatureValuesCommandsBuilder.php
  src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Details/FeatureCollectionItemType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Details/FeatureCollectionType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Details/FeatureValueType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Details/FeaturesType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/FeatureValueListener.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/FormTheme/features.html.twig
  tests/Integration/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/FeatureValueListenerTest.php
  tests/UI/campaigns/functional/BO/03_catalog/01_products/14_detailsTab.ts
  tests/UI/data/types/product.d.ts
  tests/UI/pages/BO/catalog/products/add/detailsTab.ts
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/FeatureValuesCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProviderTest.php
  tests/Unit/PrestaShopBundle/Form/Admin/Sell/Product/Details/FeaturesTypeTest.php
Labels: Improvement, QA ✔️, develop, BC break

#35049 Nightly : Externalize Push Reports & Define the maximum number of concurrent jobs
  .github/workflows/cron_nightly_tests_1.7.8.x.yml
  .github/workflows/cron_nightly_tests_8.0.x.yml
  .github/workflows/cron_nightly_tests_8.1.x.yml
  .github/workflows/cron_nightly_tests_develop.yml
  .github/workflows/cron_nightly_tests_reports.yml
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35050 Fix(dbdump): add complete insert in databasedump
  tests/Resources/DatabaseDump.php
Labels: develop, Bug fix

#35051 Functional tests - Add steps to check emails when change the order status to on backorder
  tests/UI/campaigns/functional/BO/02_orders/01_orders/04_updateStatus.ts
  tests/UI/data/demo/orderStatuses.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35055 Functional tests - Add steps to check received email log
  tests/UI/campaigns/functional/BO/14_advancedParameters/08_logs/02_logsByEmail.ts
  tests/UI/pages/BO/advancedParameters/logs/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35068 Functional tests - Add some steps to check welcome and payment emails
  tests/UI/campaigns/functional/FO/classic/01_login/04_createAccount.ts
  tests/UI/campaigns/functional/FO/classic/11_checkout/01_personalInformation/03_createAccount.ts
  tests/UI/campaigns/functional/FO/classic/11_checkout/04_payment/01_choosePaymentMethod.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34873 Prevent uncheck cast
  src/Adapter/EntityMapper.php
Labels: QA ✔️, Bug fix, 8.1.x

#35077 Functional tests - Fix Nightly 18-01 : Fix slider URL
  tests/UI/campaigns/functional/FO/classic/06_homePage/01_checkSlider.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35011 CLI improvement before and during install
  .github/workflows/lint.yml
  .github/workflows/symfony-console.yml
  app/config/doctrine.yml
  app/config/set_parameters.php
  bin/console
  classes/Tools.php
  classes/db/Db.php
  classes/exception/PrestaShopException.php
  classes/shop/Shop.php
  classes/shop/ShopUrl.php
  config/config.inc.php
  install-dev/controllers/console/process.php
  src/PrestaShopBundle/Doctrine/DatabaseConnection.php
  src/PrestaShopBundle/Install/AbstractInstall.php
  src/PrestaShopBundle/Install/Database.php
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Resources/config/services/adapter/module.yml
  src/PrestaShopBundle/Resources/config/services/bundle/controller.yml
  src/PrestaShopBundle/Resources/config/services/bundle/repository.yml
  src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
  src/PrestaShopBundle/Resources/config/services_dev/bundle/command.yml
  src/PrestaShopBundle/Translation/Loader/SqlTranslationLoader.php
  src/PrestaShopBundle/Twig/Extension/LocalizationExtension.php
  src/PrestaShopBundle/Twig/LocaleExtension.php
  tests/bin/create-test-db.php
Labels: Improvement, QA ✔️, develop

#35079 Functional tests - Fix nightly 8.1.x : Fix slider URL
  tests/UI/campaigns/functional/FO/classic/06_homePage/01_checkSlider.ts
Labels: QA ✔️, Refactoring, E2E Tests, 8.1.x

#35070 Fix default Finnish date_format
  app/Resources/all_languages.json
Labels: Improvement, Waiting for PM, QA ✔️, develop

#35058 Disable autofill of password for SMTP
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Email/SmtpConfigurationType.php
Labels: Improvement, QA ✔️, 8.1.x

#35075 Add avif support to theme files
  themes/.htaccess
Labels: Improvement, Waiting for QA, develop

#35039 Functional tests : Email subscription - Add some steps to check validation email
  tests/UI/campaigns/modules/ps_emailsubscription/02_configuration/02_checkConfirmationEmail.ts
  tests/UI/pages/FO/emailSubscription/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35056 Functional tests - Add steps to check voucher email when return a product
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/13_returnOrder.ts
  tests/UI/pages/BO/orders/view/productsBlock.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35059 Functional tests - Add new steps to check received emails when change merchandise returns status
  tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/03_updateStatus.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35060 Functional tests - Add test to check received email when send a message from FO > order details page
  tests/UI/campaigns/functional/FO/classic/03_userAccount/02_orderHistory/01_orderDetails/04_sendMessage.ts
Labels: TE, develop, Refactoring, E2E Tests

#35057 Functional tests - Add test to check the email when change the order status to refunded
  tests/UI/campaigns/functional/BO/02_orders/01_orders/04_updateStatus.ts
  tests/UI/data/demo/orderStatuses.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35104 Update PS version available in README.md
  README.md
Labels: Improvement, develop, Refactoring

#35109 Merge 8.1.x into develop
  classes/controller/FrontController.php
  composer.json
  composer.lock
  src/Adapter/EntityMapper.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Email/SmtpConfigurationType.php
  tools/build/Library/ReleaseCreator.php
Labels: Improvement, develop

#35017 Fix and comment address deletion process
  classes/Address.php
  classes/Cart.php
  classes/form/CustomerAddressPersister.php
Labels: QA ✔️, Bug fix, 8.1.x

#35123 Merge 81x into develop 22/01/24
  classes/Address.php
  classes/Cart.php
  classes/form/CustomerAddressPersister.php
  img/tmp/CACHEDIR.TAG
  var/cache/CACHEDIR.TAG
Labels: Improvement, QA ✔️, develop

#35131 Fix broken features link in README
  README.md
Labels: Waiting for QA, develop, Bug fix

#35137 Add more consistency about branches
  README.md
Labels: Improvement, develop

#35129 Update symfony to 6.3
  composer.json
  composer.lock
  phpstan-baseline.neon
  src/PrestaShopBundle/Command/ExportThemeCommand.php
  src/PrestaShopBundle/Command/ModuleCommand.php
  src/PrestaShopBundle/Command/UpdateEUTaxruleGroupsCommand.php
  src/PrestaShopBundle/DataCollector/ConfigDataCollector.php
  src/PrestaShopBundle/Entity/ApiAccess.php
  src/PrestaShopBundle/Form/Extension/ModifyAllShopsExtension.php
  tests/Integration/ApiPlatform/DomainSerializerTest.php
  tests/Integration/PrestaShopBundle/Form/FormClonerTest.php
Labels: Improvement, develop

#35132 Functional tests - Add/Refacto tests in 'BO > Stocks ' page
  tests/UI/campaigns/functional/BO/03_catalog/08_stocks/01_simpleFilterStocks.ts
  tests/UI/campaigns/functional/BO/03_catalog/08_stocks/02_sortAndPagination.ts
  tests/UI/campaigns/functional/BO/03_catalog/08_stocks/02_updateQuantity.ts
  tests/UI/campaigns/functional/BO/03_catalog/08_stocks/03_updateQuantity.ts
  tests/UI/campaigns/functional/BO/03_catalog/08_stocks/04_bulkEditQuantity.ts
  tests/UI/campaigns/functional/BO/03_catalog/08_stocks/05_filterStocksByStatus.ts
  tests/UI/campaigns/functional/BO/03_catalog/08_stocks/06_displayProductsBelowLowStock.ts
  tests/UI/campaigns/functional/BO/03_catalog/08_stocks/07_filterStocksByCategories.ts
  tests/UI/campaigns/functional/BO/03_catalog/08_stocks/08_helpCard.ts
  tests/UI/data/demo/categories.ts
  tests/UI/data/faker/category.ts
  tests/UI/data/types/category.d.ts
  tests/UI/pages/BO/catalog/stocks/index.ts
Labels: TE, develop, Refactoring, E2E Tests

#35145 Functional tests - Add new test 'BO > Design > Export current theme'
  tests/UI/campaigns/functional/BO/08_design/01_themeAndLogo/01_themeAndLogo/02_exportCurrentTheme.ts
  tests/UI/pages/BO/design/themeAndLogo/themeAndLogo/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34927 Add comments, remove unused constants
  config/config.inc.php
  config/defines.inc.php
  config/smarty.config.inc.php
  config/smartyfront.config.inc.php
  src/Adapter/Smarty/SmartyCacheConfiguration.php
Labels: QA ✔️, develop, Refactoring, BC break

#32208 Add maildev for docker dev environments
  .docker/Dockerfile
  .docker/docker_run_git.sh
  .github/actions/setup-env/action.yml
  docker-compose.yml
  tests/UI/.env.ci
  tests/UI/README.md
  tests/UI/utils/globals.ts
  tests/UI/utils/mailHelper.ts
Labels: Improvement, QA ✔️, develop

#35139 Fix smarty foreach loop on boolean variable $quick_access in BO
  admin-dev/themes/new-theme/template/components/layout/mobile_quickaccess.tpl
  admin-dev/themes/new-theme/template/components/layout/quick_access.tpl
Labels: QA ✔️, Bug fix

#35134 Implement canonical urls and remove not needed parameters
  classes/Customer.php
  classes/Link.php
  classes/Mail.php
  classes/checkout/CheckoutAddressesStep.php
  classes/checkout/ConditionsToApproveFinder.php
  classes/controller/FrontController.php
  controllers/admin/AdminCartsController.php
  controllers/admin/AdminCustomerThreadsController.php
  controllers/front/AuthController.php
  controllers/front/CmsController.php
  controllers/front/ContactController.php
  controllers/front/GuestTrackingController.php
  controllers/front/HistoryController.php
  controllers/front/IndexController.php
  controllers/front/MyAccountController.php
  controllers/front/OrderConfirmationController.php
  controllers/front/OrderController.php
  controllers/front/OrderSlipController.php
  controllers/front/PasswordController.php
  controllers/front/RegistrationController.php
  controllers/front/SitemapController.php
  controllers/front/StoresController.php
  controllers/front/listing/BestSalesController.php
  controllers/front/listing/ManufacturerController.php
  controllers/front/listing/NewProductsController.php
  controllers/front/listing/PricesDropController.php
  controllers/front/listing/SupplierController.php
  src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php
  src/Adapter/Presenter/Cart/CartPresenter.php
  src/Adapter/Presenter/Order/OrderDetailLazyArray.php
  src/Adapter/Presenter/Order/OrderReturnLazyArray.php
  src/Core/Domain/CustomerService/CommandHandler/ReplyToCustomerThreadHandler.php
Labels: QA ✔️, Bug fix, 8.1.x

#35142 Update symfony to 6.4
  app/config/config.yml
  composer.json
  composer.lock
  src/PrestaShopBundle/Resources/config/services/bundle/routing.yml
  src/PrestaShopBundle/Translation/Translator.php
  tests/Integration/Behaviour/Features/Context/CustomerManagerFeatureContext.php
  tests/Integration/PrestaShopBundle/Admin/Security/SessionRenewerTest.php
  tests/Integration/PrestaShopBundle/Controller/Admin/Sell/Order/DeliveryControllerTest.php
  tests/Integration/PrestaShopBundle/Controller/Admin/Sell/Order/OrderControllerTest.php
  tests/Integration/PrestaShopBundle/Form/AbstractFormTester.php
  tests/Integration/PrestaShopBundle/Form/FormListenerTestCase.php
  tests/Resources/config/services.yml
Labels: Improvement, develop

#34431 Add a hook 'actionValidateOrderBefore' called before actionValidateOrder
  classes/PaymentModule.php
  install-dev/data/xml/hook.xml
Labels: QA ✔️, develop, Feature, Needs autoupgrade PR

#35064 Update MetaType.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/TrafficSeo/Meta/MetaType.php
Labels: QA ✔️

#35180 Enable symfony layout feature flag by default
  .github/workflows/integration.yml
  install-dev/data/xml/feature_flag.xml
  src/PrestaShopBundle/EventListener/Context/Admin/EmployeeContextListener.php
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/head_tag.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/LegacyLayout/head_tag.html.twig
  tests/Unit/PrestaShopBundle/EventListener/Context/Admin/EmployeeContextListenerTest.php
Labels: develop, Feature

#35191 Clean horizontal migration code
  classes/Context.php
  controllers/admin/AdminLegacyLayoutController.php
  phpstan-baseline.neon
  src/PrestaShopBundle/Bridge/AdminController/ControllerConfiguration.php
  src/PrestaShopBundle/Bridge/AdminController/ControllerConfigurationFactory.php
  src/PrestaShopBundle/Bridge/AdminController/FrameworkBridgeControllerInterface.php
  src/PrestaShopBundle/Bridge/AdminController/FrameworkBridgeControllerListTrait.php
  src/PrestaShopBundle/Bridge/AdminController/FrameworkBridgeControllerTrait.php
  src/PrestaShopBundle/Bridge/AdminController/LegacyControllerBridge.php
  src/PrestaShopBundle/Bridge/AdminController/LegacyControllerBridgeFactory.php
  src/PrestaShopBundle/Bridge/AdminController/LegacyControllerBridgeInterface.php
  src/PrestaShopBundle/Bridge/AdminController/Listener/InitFrameworkBridgeControllerListener.php
  src/PrestaShopBundle/Bridge/Exception/BridgeException.php
  src/PrestaShopBundle/Bridge/Exception/FailedToFetchListRecordsException.php
  src/PrestaShopBundle/Bridge/Helper/AddFlashMessage.php
  src/PrestaShopBundle/Bridge/Helper/Listing/FilterPrefix.php
  src/PrestaShopBundle/Bridge/Helper/Listing/FiltersProcessor.php
  src/PrestaShopBundle/Bridge/Helper/Listing/HelperBridge/FeatureHelperListBridge.php
  src/PrestaShopBundle/Bridge/Helper/Listing/HelperBridge/HelperListBridge.php
  src/PrestaShopBundle/Bridge/Helper/Listing/HelperListConfiguration.php
  src/PrestaShopBundle/Bridge/Helper/Listing/HelperListConfigurationFactory.php
  src/PrestaShopBundle/Bridge/Smarty/BreadcrumbsAndTitleConfigurator.php
  src/PrestaShopBundle/Bridge/Smarty/ConfiguratorInterface.php
  src/PrestaShopBundle/Bridge/Smarty/FooterConfigurator.php
  src/PrestaShopBundle/Bridge/Smarty/FrameworkControllerSmartyTrait.php
  src/PrestaShopBundle/Bridge/Smarty/HeaderConfigurator.php
  src/PrestaShopBundle/Bridge/Smarty/ModalConfigurator.php
  src/PrestaShopBundle/Bridge/Smarty/NotificationsConfigurator.php
  src/PrestaShopBundle/Bridge/Smarty/SmartyBridge.php
  src/PrestaShopBundle/Bridge/Smarty/ToolbarFlagsConfigurator.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/HorizontalFeatureController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/features.yml
  src/PrestaShopBundle/Resources/config/services/bundle/bridge.yml
  src/PrestaShopBundle/Resources/config/services/bundle/bridge/_admin_controller.yml
  src/PrestaShopBundle/Resources/config/services/bundle/bridge/_list.yml
  src/PrestaShopBundle/Resources/config/services/bundle/bridge/_smarty.yml
  tests/Unit/PrestaShopBundle/Bridge/AdminController/LegacyControllerBridgeTest.php
Labels: Waiting for QA, develop, Refactoring, BC break

#35203 Functional tests - Fix nightly 29-01
  tests/UI/pages/BO/catalog/products/index.ts
Labels: TE, develop, Refactoring, E2E Tests

#35021 Fix Address form not work properly in customer account area
  classes/form/CustomerAddressForm.php
Labels: Waiting for author, QA ✔️, Bug fix, 8.1.x

#35217 Bump version to 8.1.4
  install-dev/install_version.php
  src/Core/Version.php
Labels: QA ✔️, Refactoring, 8.1.x

#35215 Fix alias hooks and add the missing ones
  install-dev/data/xml/hook.xml
  install-dev/data/xml/hook_alias.xml
Labels: QA ✔️, Refactoring, 8.1.x

#35006 Backport newer method in filemanager
  admin-dev/filemanager/include/utils.php
Labels: Waiting for QA, QA ✔️, Bug fix, 8.1.x

#35222 Functional tests - Add new test 'BO > Sort link list table'
  tests/UI/campaigns/functional/BO/08_design/07_linkWidget/04_sortLinkList.ts
  tests/UI/pages/BO/design/linkWidgets/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests
