Repository PrestaShop/PrestaShop, pull requests merged in 2024-04, with the labels that each got.

#35779 Functional tests - Add some tests in 'FO > Classic > Quick view modal'
  tests/UI/campaigns/functional/FO/classic/09_productPage/01_quickView/02_changeQuantity.ts
  tests/UI/campaigns/functional/FO/classic/09_productPage/01_quickView/03_shareLinks.ts
  tests/UI/campaigns/functional/FO/classic/09_productPage/01_quickView/04_displayOfTheProduct.ts
  tests/UI/pages/FO/classic/modal/quickView.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35761 Introduce PS_TRUSTED_PROXIES env, and delete the obsolete PS_SSL_ENABLED_EVERYWHERE config
  .env
  .env.dist
  admin-dev/filemanager/config/config.php
  app/config/config.yml
  classes/Link.php
  classes/controller/FrontController.php
  config/config.inc.php
  src/Adapter/GeneralConfiguration.php
  src/Adapter/Preferences/PreferencesConfiguration.php
  src/PrestaShopBundle/EventListener/Admin/SSLMiddlewareListener.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Administration/GeneralDataProvider.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/General/PreferencesType.php
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_data_provider.yml
  tests/Unit/Adapter/Preferences/PreferencesConfigurationTest.php
Labels: Improvement, QA ✔️, develop, BC break, Needs documentation, Needs autoupgrade PR

#35697 Create gtin and replace ean13 usages
  classes/Combination.php
  classes/Product.php
  classes/Validate.php
  controllers/admin/AdminImportController.php
  install-dev/data/db_structure.sql
  src/Adapter/Product/Combination/Update/Filler/DetailsFiller.php
  src/Adapter/Product/Update/Filler/DetailsFiller.php
  src/Adapter/Product/Validate/ProductValidator.php
  src/Core/ConstraintValidator/Constraints/TypedRegex.php
  src/Core/ConstraintValidator/TypedRegexValidator.php
  src/Core/Domain/Product/Combination/Command/UpdateCombinationCommand.php
  src/Core/Domain/Product/Combination/QueryResult/CombinationDetails.php
  src/Core/Domain/Product/Command/UpdateProductCommand.php
  src/Core/Domain/Product/Exception/ProductConstraintException.php
  src/Core/Domain/Product/QueryResult/ProductDetails.php
  src/Core/Domain/Product/ValueObject/Gtin.php
  src/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/UpdateCombinationCommandsBuilder.php
  src/Core/Form/IdentifiableObject/DataProvider/CombinationFormDataProvider.php
  src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/BulkCombinationReferencesType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Details/ReferencesType.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/UpdateCombinationFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateProductFeatureContext.php
  tests/Unit/Adapter/Product/Combination/Update/Filler/DetailsFillerTest.php
  tests/Unit/Adapter/Product/Update/Filler/DetailsFillerTest.php
  tests/Unit/Core/Domain/Product/ValueObject/GtinTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/Combination/UpdateCombinationCommandsBuilderTest.php
  tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/UpdateProductCommandsBuilderTest.php
Labels: Improvement, QA ✔️, develop, BC break

#35804 Functional tests - Add new test 'FO > Classic > Add product to cart in product page'
  tests/UI/campaigns/functional/FO/classic/09_productPage/01_quickView.ts
  tests/UI/campaigns/functional/FO/classic/09_productPage/02_addToCart.ts
  tests/UI/campaigns/functional/FO/classic/09_productPage/02_productPage/01_addToCart.ts
  tests/UI/pages/FO/classic/modal/blockCart.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35793 Functional Tests : BO - Design - Positions - Unhook module in list by Bulk actions
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/positions.html.twig
  tests/UI/campaigns/functional/BO/08_design/05_positions/02_filterModule.ts
  tests/UI/campaigns/functional/BO/08_design/05_positions/03_searchHook.ts
  tests/UI/campaigns/functional/BO/08_design/05_positions/05_unhookModuleInListByBulkActions.ts
  tests/UI/pages/BO/design/positions/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35705 Fix strstr modifier
  config/smarty.config.inc.php
Labels: Improvement, QA ✔️, 8.1.x

#35817 Functional Tests : Migration from Docker Compose v1 to v2 (8.0.x)
  .github/actions/setup-env/action.yml
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35818 Functional Tests : Migration from Docker Compose v1 to v2 (8.1.x)
  .github/actions/setup-env/action.yml
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35771 Updated query to remove subquery
  src/Core/Grid/Query/AttributeGroupQueryBuilder.php
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
Labels: QA ✔️, develop, Bug fix

#35821 Functional tests - Add new tests to check share links in product page FO in Hummingbird and classic theme
  tests/UI/campaigns/functional/FO/classic/09_productPage/02_productPage/05_shareLinks.ts
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/02_productPage/05_shareLinks.ts
  tests/UI/pages/FO/classic/product/index.ts
  tests/UI/pages/commonPage.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35819 Functional tests - Add new test in 'FO > Hummingbird > Check highlighted promo code'
  tests/UI/campaigns/functional/FO/hummingbird/11_checkout/03_displayOfHighlightedCartRules.ts
  tests/UI/pages/FO/classic/cart/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35840 Functional tests - Add new test to add customization in FO > Product page (classic and hummingbird theme)
  tests/UI/campaigns/functional/FO/classic/09_productPage/02_productPage/06_addCustomization.ts
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/02_productPage/06_addCustomization.ts
  tests/UI/pages/BO/catalog/products/add/detailsTab.ts
  tests/UI/pages/FO/classic/product/index.ts
  tests/UI/pages/FO/hummingbird/product/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35827 Fix uasort in dead code
  controllers/admin/AdminModulesController.php
Labels: QA ✔️, Refactoring, 8.1.x

#35434 Improve wording of pack quantities
  src/Core/Form/ChoiceProvider/PackStockTypeChoiceProvider.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/StockType.php
  src/PrestaShopBundle/Form/Admin/Product/ProductQuantity.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/StockType.php
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/02_defaultPackStockManagement.ts
  tests/UI/campaigns/productV2/functional/04_CRUDPackOfProducts.ts
  tests/UI/pages/BO/catalog/productsV2/add/packTab.ts
  tests/Unit/Core/Form/ChoiceProvider/PackStockTypeChoiceProviderTest.php
Labels: Improvement, PM ✔️, Wording ✔️, 8.1.x

#35812 Fix unit price everywhere
  classes/Cart.php
  controllers/front/ProductController.php
  src/Adapter/Presenter/Product/ProductLazyArray.php
Labels: Bug fix, 8.1.x

#35749 Unify text field database limits
  classes/Address.php
  classes/Attachment.php
  classes/CMS.php
  classes/CMSCategory.php
  classes/Cart.php
  classes/CartRule.php
  classes/Category.php
  classes/Configuration.php
  classes/Contact.php
  classes/Customer.php
  classes/CustomerMessage.php
  classes/Hook.php
  classes/Manufacturer.php
  classes/Message.php
  classes/PrestaShopLogger.php
  classes/Product.php
  classes/RequestSql.php
  classes/Store.php
  classes/Supplier.php
  classes/order/Order.php
  classes/order/OrderDetail.php
  classes/order/OrderInvoice.php
  classes/order/OrderMessage.php
  classes/order/OrderReturn.php
  classes/webservice/WebserviceKey.php
  install-dev/data/db_structure.sql
  src/PrestaShopBundle/Form/Admin/Type/FormattedTextareaType.php
Labels: Bug fix, Refactoring, 8.1.x

#35773 chore(api) allow customer group endpoint to be created without shopid…
  composer.json
  composer.lock
  src/PrestaShopBundle/ApiPlatform/ContextParametersTrait.php
Labels: Improvement, QA ✔️, develop, Bug fix

#35822 Fix strpos modifier
  config/smarty.config.inc.php
Labels: QA ✔️, Refactoring, 8.1.x

#35830 Fix notice on nulls
  src/PrestaShopBundle/Form/Validator/Constraints/TinyMceMaxLengthValidator.php
Labels: QA ✔️, Refactoring, 8.1.x

#35887 Update fos_js_routes file
  admin-dev/themes/new-theme/js/fos_js_routes.json
Labels: Improvement, develop

#35826 Better inform about faulty hooks
  classes/Hook.php
Labels: QA ✔️, Refactoring, 8.1.x

#35861 Update HTMLTemplateOrderSlip.php to fix #35802
  classes/pdf/HTMLTemplateOrderSlip.php
Labels: QA ✔️, Bug fix, 8.1.x

#35832 Chore(api): make api based on grid instead of query builder
  composer.json
  composer.lock
  src/PrestaShopBundle/ApiPlatform/Exception/GridDataFactoryNotFoundException.php
  src/PrestaShopBundle/ApiPlatform/Metadata/PaginatedList.php
  src/PrestaShopBundle/ApiPlatform/Provider/QueryListProvider.php
  src/PrestaShopBundle/ApiPlatform/Resources/Language.php
  src/PrestaShopBundle/Resources/config/services/core/grid/grid_data_factory.yml
  tests/Integration/ApiPlatform/EndPoint/LanguageEndpointTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/PaginatedListTest.php
Labels: Improvement, Waiting for author, Waiting for QA, develop

#35848 Introduce AllShopContext Attribute for Symfony layout
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/FeatureFlagController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/PermissionController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ProfileController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SecurityController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/OrderStateController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/LanguageController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/TranslationsController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CatalogPriceRuleController.php
  src/PrestaShopBundle/Controller/Attribute/AllShopContext.php
  src/PrestaShopBundle/EventListener/Admin/Context/ShopContextListener.php
  tests/Unit/PrestaShopBundle/EventListener/Admin/Context/ShopContextListenerTest.php
Labels: Improvement, QA ✔️, develop

#35863 Fixed title in attribute value form
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/AttributeController.php
Labels: QA ✔️, develop, Bug fix

#35864 Update outdated licence headers / Add missing licence headers
  classes/order/OrderReturnState.php
  classes/order/OrderState.php
  controllers/admin/AdminPdfController.php
  rector.php
  src/Adapter/Country/QueryHandler/GetCountryForEditingHandler.php
  src/Adapter/Customer/Group/CommandHandler/AddCustomerGroupHandler.php
  src/Adapter/Customer/Group/Repository/GroupRepository.php
  src/Adapter/Customer/Group/Validate/CustomerGroupValidator.php
  src/Core/Domain/Country/Query/GetCountryForEditing.php
  src/Core/Domain/Country/QueryHandler/GetCountryForEditingHandlerInterface.php
  src/Core/Domain/Country/QueryResult/CountryForEditing.php
  src/Core/Domain/Customer/Group/Command/AddCustomerGroupCommand.php
  src/Core/Http/CookieOptions.php
  src/PrestaShopBundle/Form/Admin/Type/LocaleChoiceType.php
  src/PrestaShopBundle/Form/FormHelper.php
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/head_tag.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/notifications_center.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/LegacyLayout/notifications_center.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Country/edit.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/core_javascript.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/default_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/legacy_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/light_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/stylesheets.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Features/FeatureValue/create.html.twig
  src/PrestaShopBundle/Resources/views/Admin/layout.html.twig
  tests/Integration/Behaviour/Features/Context/Domain/CustomerGroupFeatureContext.php
  tests/Unit/Core/Domain/Customer/Group/Command/AddCustomerGroupCommandTest.php
Labels: Improvement, develop

#35898 Changelog v9.0.0-alpha.1
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: Improvement, QA ✔️, develop

#34875 Add cart rule module validation
  classes/CartRule.php
  install-dev/data/xml/hook.xml
Labels: QA ✔️, develop, Bug fix, Needs autoupgrade PR

#35905 Nightly : Fixed error install libnss3-tools
  .github/actions/setup-env/action.yml
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35891 Functional Tests: Mail alerts module - BO Header Buttons
  tests/UI/campaigns/modules/ps_emailalerts/02_configuration/01_boHeaderButtons.ts
  tests/UI/pages/BO/design/positions/index.ts
  tests/UI/pages/BO/modules/moduleConfiguration/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35859 Functional Tests : `GET /api/modules`
  src/Adapter/Presenter/Module/ModulePresenter.php
  tests/UI/campaigns/functional/API/02_endpoints/06_module/02_getAPIModules.ts
  tests/UI/commonTests/BO/modules/moduleManager.ts
  tests/UI/data/types/module.d.ts
  tests/UI/pages/BO/modules/moduleManager/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35847 Functional Tests: `GET /api/languages`
  tests/UI/campaigns/functional/API/02_endpoints/05_language/01_getAPILanguages.ts
  tests/UI/campaigns/functional/API/02_endpoints/08_product/01_postAPIProduct.ts
  tests/UI/campaigns/functional/API/02_endpoints/08_product/02_deleteAPIProductId.ts
  tests/UI/campaigns/functional/API/02_endpoints/08_product/03_getAPIProductId.ts
  tests/UI/campaigns/functional/API/02_endpoints/08_product/04_patchAPIProductId.ts
  tests/UI/campaigns/functional/API/02_endpoints/09_productList/01_getAPIProducts.ts
  tests/UI/pages/BO/international/languages/add.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35845 Functional Tests: FO - Order confirmation : Order details and totals - Recap of payment method (Classic & Hummingbird)
  tests/UI/campaigns/functional/FO/classic/12_orderConfirmation/03_recapPaymentMethod.ts
  tests/UI/campaigns/functional/FO/hummingbird/12_orderConfirmation/03_recapPaymentMethod.ts
  tests/UI/pages/FO/classic/checkout/orderConfirmation.ts
  tests/UI/pages/FO/hummingbird/checkout/orderConfirmation.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35834 Stabilize search indexation and check referrer
  controllers/admin/AdminSearchController.php
Labels: QA ✔️, Refactoring, 8.1.x

#35940 Nightly : Need Keycloak for execution
  .github/actions/setup-keycloak/action.yml
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#35941 Nightly : Fixed API : GET /languages
  tests/UI/campaigns/functional/API/02_endpoints/05_language/01_getAPILanguages.ts
  tests/UI/pages/BO/international/languages/index.ts
  tests/UI/pages/BO/modules/moduleManager/index.ts
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#35944 Nightly : Fixed cron_nightly_tests_reusable.yml
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#35270 Enable attribute migrated page
  admin-dev/themes/default/template/controllers/attributes/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/attributes/helpers/form/index.php
  admin-dev/themes/default/template/controllers/attributes/helpers/index.php
  admin-dev/themes/default/template/controllers/attributes/index.php
  admin-dev/themes/default/template/controllers/attributes_groups/helpers/form/form.tpl
  admin-dev/themes/default/template/controllers/attributes_groups/helpers/form/index.php
  admin-dev/themes/default/template/controllers/attributes_groups/helpers/index.php
  admin-dev/themes/default/template/controllers/attributes_groups/helpers/list/index.php
  admin-dev/themes/default/template/controllers/attributes_groups/helpers/list/list_header.tpl
  admin-dev/themes/default/template/controllers/attributes_groups/helpers/view/index.php
  admin-dev/themes/default/template/controllers/attributes_groups/index.php
  admin-dev/themes/new-theme/scss/components/_form.scss
  classes/lang/KeysReference/FeatureFlagLang.php
  controllers/admin/AdminAttributesGroupsController.php
  phpstan-baseline.neon
  src/Core/Grid/Definition/Factory/AttributeGroupGridDefinitionFactory.php
  src/Core/Grid/Query/AttributeGroupQueryBuilder.php
  src/Core/Search/Filters/AttributeFilters.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/AttributeController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/AttributeGroupController.php
  src/PrestaShopBundle/Form/Admin/Sell/Catalog/AttributeGroupType.php
  src/PrestaShopBundle/Form/Admin/Sell/Catalog/AttributeType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/attribute.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/attribute_group.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Attribute/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/empty_state.html.twig
  tests/Integration/Classes/controller/AdminControllerTest.php
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/04_changeCategoryPosition.ts
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/01_CRUDAttributesAndValues.ts
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/02_changePosition.ts
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/attributes/01_filterAttributes.ts
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/attributes/02_sortPaginationAndBulkDelete.ts
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/values/01_filterValues.ts
  tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/01_attributes/values/02_sortPaginationAndBulkDelete.ts
  tests/UI/data/faker/attributeValue.ts
  tests/UI/data/types/attribute.d.ts
  tests/UI/pages/BO/catalog/attributes/addAttribute.ts
  tests/UI/pages/BO/catalog/attributes/addValue.ts
  tests/UI/pages/BO/catalog/attributes/index.ts
  tests/UI/pages/BO/catalog/attributes/view.ts
  tests/UI/pages/BO/catalog/categories/index.ts
  tests/UI/pages/commonPage.ts
Labels: Waiting for QA, develop, Feature, BC break

#35893 Merge `8.1.x` into `develop`
  admin-dev/index.php
  admin-dev/themes/new-theme/js/pages/product/service/image.ts
  classes/Address.php
  classes/Attachment.php
  classes/CMS.php
  classes/CMSCategory.php
  classes/Cart.php
  classes/CartRule.php
  classes/Configuration.php
  classes/Contact.php
  classes/Customer.php
  classes/CustomerMessage.php
  classes/Hook.php
  classes/Manufacturer.php
  classes/Message.php
  classes/PrestaShopLogger.php
  classes/Product.php
  classes/RequestSql.php
  classes/Store.php
  classes/Supplier.php
  classes/order/Order.php
  classes/order/OrderDetail.php
  classes/order/OrderInvoice.php
  classes/order/OrderMessage.php
  classes/order/OrderReturn.php
  classes/webservice/WebserviceKey.php
  composer.lock
  config/smarty.config.inc.php
  controllers/front/ProductController.php
  install-dev/data/db_structure.sql
  src/Adapter/Order/CommandHandler/UpdateOrderStatusHandler.php
  src/Adapter/Presenter/Product/ProductLazyArray.php
  src/Core/Form/ChoiceProvider/PackStockTypeChoiceProvider.php
  src/Core/Form/IdentifiableObject/DataHandler/AddressFormDataHandler.php
  src/Core/Module/ModuleRepository.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/StockType.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/StockType.php
  src/PrestaShopBundle/Form/Admin/Type/FormattedTextareaType.php
  src/PrestaShopBundle/Form/Validator/Constraints/TinyMceMaxLengthValidator.php
  tests/UI/campaigns/functional/BO/01_dashboard/02_activityOverview.ts
  tests/UI/campaigns/functional/BO/03_catalog/01_products/04_CRUDPackOfProducts.ts
  tests/UI/campaigns/functional/BO/03_catalog/01_products/12_packTab.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/02_defaultPackStockManagement.ts
  tests/UI/pages/BO/catalog/products/add/packTab.ts
  tests/Unit/Core/Form/ChoiceProvider/PackStockTypeChoiceProviderTest.php
  themes/_core/js/checkout-steps.js
Labels: Improvement, develop

#35907 Handle API upload file
  app/config/admin-api/config.yml
  app/config/admin-api/services.yml
  composer.json
  composer.lock
  src/PrestaShopBundle/ApiPlatform/Encoder/MultipartDecoder.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSCommand.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSGetCollection.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSPartialUpdate.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSUpdate.php
  src/PrestaShopBundle/ApiPlatform/Normalizer/UploadedFileNormalizer.php
  src/PrestaShopBundle/ApiPlatform/Processor/CommandProcessor.php
  src/PrestaShopBundle/ApiPlatform/Provider/QueryListProvider.php
  src/PrestaShopBundle/ApiPlatform/Provider/QueryProvider.php
  src/PrestaShopBundle/ApiPlatform/QueryResultSerializerTrait.php
  src/PrestaShopBundle/ApiPlatform/Serializer/DomainSerializer.php
  src/PrestaShopBundle/Resources/config/services/bundle/api_platform.yml
  tests/Integration/ApiPlatform/Serializer/DomainSerializerTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSCommandTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSCreateTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSGetCollectionTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSPartialUpdateTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSUpdateTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/StateProvider/QueryProviderTest.php
Labels: develop, Feature

#35957 Functional Tests : API : GET /api-clients
  tests/UI/campaigns/functional/API/02_endpoints/02_apiClients/01_getAPIApiClients.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35950 Functional tests - Add new tests in 'FO > Classic > Search result page > Consult search results - Sort search results - Consult quick view'
  tests/UI/campaigns/functional/FO/classic/07_search/04_consultResultsList.ts
  tests/UI/campaigns/functional/FO/classic/07_search/05_sortResultsList.ts
  tests/UI/campaigns/functional/FO/classic/07_search/06_consultProductQuickView.ts
  tests/UI/pages/FO/classic/searchResults/index.ts
  tests/UI/pages/FO/hummingbird/searchResults/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35960 Functional Tests : API : GET /module/{moduleId}
  tests/UI/campaigns/functional/API/02_endpoints/06_module/01_getAPIModuleId.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35934 Functional Tests : GDPR : Consent checkbox customization
  tests/UI/campaigns/modules/psgdpr/02_configuration/03_consentCheckboxCustomization.ts
  tests/UI/commonTests/BO/modules/moduleManager.ts
  tests/UI/data/demo/modules.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/design/positions/hookModule.ts
  tests/UI/pages/BO/design/positions/index.ts
  tests/UI/pages/BO/modules/moduleConfiguration/index.ts
  tests/UI/pages/BO/modules/psGdpr/index.ts
  tests/UI/pages/BO/modules/psGdpr/tabDataConsent.ts
  tests/UI/pages/FO/classic/contactUs/index.ts
  tests/UI/pages/FO/classic/home/index.ts
  tests/UI/pages/FO/classic/myAccount/add.ts
  tests/UI/pages/FO/classic/myAccount/identity.ts
  tests/UI/pages/FO/classic/product/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35974 Functional Tests : API : PUT /modules/toggle-status
  tests/UI/campaigns/functional/API/02_endpoints/09_modules/03_putModulesToggleStatus.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35988 Merge `8.1.x` into `develop`
  composer.lock
  controllers/admin/AdminSearchController.php
Labels: Improvement, Waiting for QA, develop

#35990 Functional Tests : API : POST /product/{productId}/image
  tests/UI/campaigns/functional/API/02_endpoints/10_product/05_postProductIdImage.ts
  tests/UI/data/types/product.d.ts
  tests/UI/pages/BO/catalog/products/add/descriptionTab.ts
  tests/UI/utils/files.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35959 Functional tests - Add new test to edit quantity in product page (Classic & Hummingbird)
  tests/UI/campaigns/functional/FO/classic/09_productPage/02_productPage/02_changeQuantity.ts
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/02_productPage/01_addToCart.ts
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/02_productPage/02_changeQuantity.ts
  tests/UI/pages/FO/classic/product/index.ts
  tests/UI/pages/FO/hummingbird/product/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#36000 Functional Tests : API : GET /product/image/{imageId}
  tests/UI/campaigns/functional/API/02_endpoints/10_product/07_getProductImageId.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35989 Add xdebug install into the dockerfile
  .docker/Dockerfile
  docker-compose.yml
Labels: Improvement, Waiting for QA, develop

#35994 Fix typo
  controllers/admin/AdminTranslationsController.php
Labels: Improvement, develop

#36021 Integrate phpstan extension for Doctrine
  composer.json
  composer.lock
  phpstan-baseline.neon
  phpstan.neon.dist
  src/Adapter/Shop/QueryHandler/SearchShopsHandler.php
  src/PrestaShopBundle/Entity/AdminFilter.php
  src/PrestaShopBundle/Entity/ApiClient.php
  src/PrestaShopBundle/Entity/Attribute.php
  src/PrestaShopBundle/Entity/AttributeGroup.php
  src/PrestaShopBundle/Entity/AttributeGroupLang.php
  src/PrestaShopBundle/Entity/AttributeLang.php
  src/PrestaShopBundle/Entity/FeatureFlag.php
  src/PrestaShopBundle/Entity/ImageType.php
  src/PrestaShopBundle/Entity/Lang.php
  src/PrestaShopBundle/Entity/ModuleHistory.php
  src/PrestaShopBundle/Entity/Mutation.php
  src/PrestaShopBundle/Entity/ProductDownload.php
  src/PrestaShopBundle/Entity/ProductIdentity.php
  src/PrestaShopBundle/Entity/Shop.php
  src/PrestaShopBundle/Entity/ShopGroup.php
  src/PrestaShopBundle/Entity/ShopUrl.php
  src/PrestaShopBundle/Entity/StockMvt.php
  src/PrestaShopBundle/Entity/Tab.php
  src/PrestaShopBundle/Entity/TabLang.php
  src/PrestaShopBundle/Entity/Translation.php
  tests/Unit/PrestaShopBundle/PassVsprintfContraintTest.php
Labels: Improvement, develop, BC break

#35996 Update redirect_type enum values
  install-dev/data/db_structure.sql
Labels: Improvement, QA ✔️, develop, Bug fix, BC break, Needs autoupgrade PR

#34823 Sets the current date on the duplicate product
  src/Adapter/Product/Update/ProductDuplicator.php
Labels: QA ✔️, develop, Bug fix, 8.1.x

#34917 Groups list : display new group buttons even after saving options
  controllers/admin/AdminGroupsController.php
Labels: QA ✔️, develop, Bug fix

#35953 Fix cart calculator tax rounding issues
  src/Core/Cart/CartRuleCalculator.php
Labels: QA ✔️, Refactoring, 8.1.x

#36018 Docker-compose.override.yml.dist : add prestashop-network
  docker-compose.override.yml.dist
Labels: QA ✔️, develop, Bug fix

#35998 Moves the random admin folder name generation at the end of the install process
  controllers/admin/AdminLoginController.php
  install-dev/classes/session.php
  install-dev/controllers/console/process.php
  install-dev/controllers/http/configure.php
  install-dev/controllers/http/process.php
  install-dev/theme/views/process.php
  src/PrestaShopBundle/Install/Install.php
Labels: QA ✔️, develop, Refactoring

#36009 Functional Tests : API : POST /product/image/{imageId}
  tests/UI/campaigns/functional/API/02_endpoints/10_product/08_postProductImageId.ts
  tests/UI/pages/BO/catalog/products/add/descriptionTab.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#36052 Removed useless aliases which cause issue with MariaDB
  src/Adapter/CartRule/Repository/CartRuleRepository.php
Labels: QA ✔️, develop, Bug fix, WIP, 9.0.x

#36059 Merge `8.1.x` into `develop`
  src/Adapter/Product/Update/ProductDuplicator.php
  src/Core/Cart/CartRuleCalculator.php
Labels: Improvement, develop

#36029 Remove deprecated object model validation and other dead code
  classes/Address.php
  classes/AddressFormat.php
  classes/Alias.php
  classes/Customer.php
  classes/ObjectModel.php
  classes/Tag.php
  classes/controller/AdminController.php
  classes/helper/Helper.php
  classes/stock/SupplyOrderDetail.php
  controllers/admin/AdminSuppliersController.php
  controllers/admin/AdminTranslationsController.php
  tests/Integration/Classes/controller/AdminControllerTest.php
Labels: QA ✔️, develop, Bug fix, Refactoring, BC break

#34908 Don't create useless file "index.php" in every image folder
  classes/Image.php
Labels: Improvement, QA ✔️, develop, Topwatchers
