Repository PrestaShop/PrestaShop, pull requests merged in 2024-03, with the labels that each got.

#35513 update modules on composer for PS 8.1.5 (patch release)
  classes/Tools.php
  composer.json
  composer.lock
Labels: Improvement, Waiting for QA, 8.1.x

#35502 Functional tests - Add new tests in 'FO > Hummingbird > Quick view modal'
  tests/UI/campaigns/functional/FO/classic/06_homePage/04_productQuickView.ts
  tests/UI/campaigns/functional/FO/hummingbird/06_homePage/04_productQuickView.ts
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/01_quickView/04_displayOfTheProduct.ts
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/01_quickView/05_closeModal.ts
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/01_quickView/06_changeCombination.ts
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/01_quickView/07_changeImage.ts
  tests/UI/pages/FO/classic/modal/quickView.ts
  tests/UI/pages/FO/hummingbird/modal/quickView.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35023 Fix: BO - Import/Export - Can't import Store contact
  controllers/admin/AdminImportController.php
Labels: QA ✔️, Bug fix, 8.1.x

#35530 Fix invoice download for non logged in customer
  controllers/front/PdfInvoiceController.php
Labels: QA ✔️, Bug fix, 8.1.x

#35550 Nightly : Fixed `campaigns/functional/FO/hummingbird/09*/01*/*`
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/01_quickView/04_displayOfTheProduct.ts
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/01_quickView/05_closeModal.ts
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/01_quickView/06_changeCombination.ts
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/01_quickView/07_changeImage.ts
Labels: TE, develop, Bug fix, E2E Tests

#35556 Functional Tests : API : DELETE /api/customers/group/{customerGroupId}
  tests/UI/campaigns/functional/API/02_endpoints/03_customerGroup/01_deleteAPICustomerGroupsId.ts
  tests/UI/campaigns/functional/API/02_endpoints/05_hook/01_getAPIHookStatusId.ts
  tests/UI/campaigns/functional/API/02_endpoints/05_hook/02_getAPIHooksId.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35558 Functional Tests : Remove FF Authorization Server
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/01_internalAuthServer/01_authorizationEndpoint.ts
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/01_internalAuthServer/02_resourceEndpoint.ts
  tests/UI/campaigns/functional/API/02_endpoints/01_apiClient/01_getAPIApiClientInfos.ts
  tests/UI/campaigns/functional/API/02_endpoints/01_apiClient/02_getAPIApiClientId.ts
  tests/UI/campaigns/functional/API/02_endpoints/03_customerGroup/01_deleteAPICustomerGroupsId.ts
  tests/UI/campaigns/functional/API/02_endpoints/05_hook/01_getAPIHookStatusId.ts
  tests/UI/campaigns/functional/API/02_endpoints/05_hook/02_getAPIHooksId.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/12_authorizationServer/01_CRUD.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/12_authorizationServer/02_addAPIClient.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/12_authorizationServer/03_editAPIClient.ts
  tests/UI/campaigns/modules/ps_apiresources/01_installation/01_uninstallAndInstallModule.ts
  tests/UI/campaigns/modules/ps_apiresources/01_installation/02_disableEnableModule.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35529 Functional tests - Add new test 'FO > Hummingbird > Consult auto complete list'
  tests/UI/campaigns/functional/FO/hummingbird/07_search/01_consultAutoCompleteList.ts
  tests/UI/pages/FO/FObasePage.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35554 Update ps_googleanalytics
  composer.json
  composer.lock
Labels: Improvement, Waiting for QA, 8.1.x

#35561 Functional Tests : API : DELETE /api/api-client/{apiClientId}
  tests/UI/campaigns/functional/API/02_endpoints/01_apiClient/02_deleteAPIApiClientId.ts
  tests/UI/campaigns/functional/API/02_endpoints/01_apiClient/03_getAPIApiClientId.ts
  tests/UI/campaigns/functional/API/02_endpoints/01_apiClient/05_getAPIApiClientInfos.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35562 Functional Tests : API : DELETE /api/product/{productId}
  tests/UI/campaigns/functional/API/02_endpoints/06_product/02_deleteAPIProductId.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35559 Functional Tests : Improve check of GET endpoints
  tests/UI/campaigns/functional/API/02_endpoints/01_apiClient/02_deleteAPIApiClientId.ts
  tests/UI/campaigns/functional/API/02_endpoints/01_apiClient/03_getAPIApiClientId.ts
  tests/UI/campaigns/functional/API/02_endpoints/01_apiClient/05_getAPIApiClientInfos.ts
  tests/UI/campaigns/functional/API/02_endpoints/03_customerGroup/01_deleteAPICustomerGroupsId.ts
  tests/UI/campaigns/functional/API/02_endpoints/05_hook/01_getAPIHookStatusId.ts
  tests/UI/campaigns/functional/API/02_endpoints/05_hook/02_getAPIHooksId.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35544 Update hook.xml
  install-dev/data/xml/hook.xml
Labels: QA ✔️, develop, Bug fix

#35384 Fix: Catalog - Stocks - multiple filters not working
  src/PrestaShopBundle/Controller/Api/StockController.php
Labels: QA ✔️, Bug fix, 8.1.x

#35579 Update default catalog 8.1.x
  translations/default/AdminActions.xlf
  translations/default/AdminAdvparametersFeature.xlf
  translations/default/AdminAdvparametersHelp.xlf
  translations/default/AdminAdvparametersNotification.xlf
  translations/default/AdminCatalogFeature.xlf
  translations/default/AdminCatalogHelp.xlf
  translations/default/AdminCatalogNotification.xlf
  translations/default/AdminDesignFeature.xlf
  translations/default/AdminDesignHelp.xlf
  translations/default/AdminGlobal.xlf
  translations/default/AdminInternationalFeature.xlf
  translations/default/AdminInternationalHelp.xlf
  translations/default/AdminInternationalNotification.xlf
  translations/default/AdminModulesFeature.xlf
  translations/default/AdminModulesNotification.xlf
  translations/default/AdminNavigationHeader.xlf
  translations/default/AdminNavigationMenu.xlf
  translations/default/AdminNavigationNotification.xlf
  translations/default/AdminNotificationsError.xlf
  translations/default/AdminNotificationsInfo.xlf
  translations/default/AdminNotificationsSuccess.xlf
  translations/default/AdminNotificationsWarning.xlf
  translations/default/AdminOrderscustomersFeature.xlf
  translations/default/AdminOrderscustomersNotification.xlf
  translations/default/AdminPaymentNotification.xlf
  translations/default/AdminShippingFeature.xlf
  translations/default/AdminShippingHelp.xlf
  translations/default/AdminShopparametersFeature.xlf
  translations/default/AdminShopparametersHelp.xlf
  translations/default/EmailsBody.xlf
  translations/default/EmailsSubject.xlf
  translations/default/Install.xlf
  translations/default/ModulesBlockreassuranceAdmin.xlf
  translations/default/ModulesBlockwishlistShop.xlf
  translations/default/ModulesContactinfoShop.xlf
  translations/default/ModulesDashgoalsAdmin.xlf
  translations/default/ModulesEmailalertsShop.xlf
  translations/default/ModulesFacetedsearchAdmin.xlf
  translations/default/ModulesFacetedsearchShop.xlf
  translations/default/ModulesGoogleanalyticsAdmin.xlf
  translations/default/ModulesLinklistAdmin.xlf
  translations/default/ModulesProductcommentsAdmin.xlf
  translations/default/ModulesProductcommentsShop.xlf
  translations/default/ShopFormsLabels.xlf
  translations/default/ShopNotificationsError.xlf
  translations/default/ShopNotificationsSuccess.xlf
  translations/default/ShopPdf.xlf
  translations/default/ShopThemeActions.xlf
  translations/default/ShopThemeCatalog.xlf
  translations/default/ShopThemeCheckout.xlf
  translations/default/ShopThemeCustomeraccount.xlf
  translations/default/ShopThemeGlobal.xlf
  translations/default/messages.xlf
Labels: Improvement, 8.1.x

#35569 Functional Tests : API : PUT /api/customers/group/{customerGroupId}
  tests/UI/campaigns/functional/API/02_endpoints/03_customerGroup/02_deleteAPICustomerGroupsId.ts
  tests/UI/campaigns/functional/API/02_endpoints/03_customerGroup/04_putAPICustomerGroupsId.ts
  tests/UI/campaigns/functional/API/02_endpoints/06_product/02_deleteAPIProductId.ts
  tests/UI/pages/BO/catalog/products/add/combinationsTab.ts
  tests/UI/pages/BO/shopParameters/customerSettings/groups/add.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35552 `MaterialChoiceTableType` introduce `display_total_items` form `option`
  src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php
  src/PrestaShopBundle/Form/Admin/Type/Material/MaterialChoiceTableType.php
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
  tests/Unit/PrestaShopBundle/Form/Admin/Type/Material/MaterialChoiceTableTypeTest.php
Labels: Improvement, QA ✔️

#35568 Make products and specific combination products searchable by all kind of references in stock management page
  src/PrestaShopBundle/Api/QueryParamsCollection.php
  src/PrestaShopBundle/Entity/Repository/StockManagementRepository.php
  src/PrestaShopBundle/Entity/Repository/StockRepository.php
  tests/Unit/PrestaShopBundle/Api/QueryParamsCollectionTest.php
Labels: Improvement, QA ✔️, develop

#35618 Functional tests - Add new tests 'FO > Hummingbird > Search page'
  tests/UI/campaigns/functional/FO/classic/07_search/02_searchProduct.ts
  tests/UI/campaigns/functional/FO/hummingbird/07_search/02_searchProductAndValidate.ts
  tests/UI/campaigns/functional/FO/hummingbird/07_search/03_searchNoResult.ts
  tests/UI/campaigns/functional/FO/hummingbird/07_search/04_consultResultsList.ts
  tests/UI/campaigns/functional/FO/hummingbird/07_search/05_sortResultsList.ts
  tests/UI/campaigns/functional/FO/hummingbird/07_search/06_consultProductQuickView.ts
  tests/UI/data/demo/products.ts
  tests/UI/pages/FO/FObasePage.ts
  tests/UI/pages/FO/classic/searchResults/index.ts
  tests/UI/pages/FO/hummingbird/searchResults/index.ts
  tests/UI/utils/basicHelper.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35496 Fix docker config
  .docker/docker_run_git.sh
  docker-compose.yml
Labels: Improvement, Waiting for QA, develop, Waiting for dev

#35571 Stop requesting core.js source map in production
  themes/webpack.config.js
Labels: Improvement, Waiting for dev, 8.1.x

#35620 Functional Tests : API : POST /api/product
  tests/UI/campaigns/functional/API/02_endpoints/06_product/01_postAPIProduct.ts
  tests/UI/data/faker/product.ts
  tests/UI/data/types/product.d.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35587 Fix $action variable in postProcess method
  classes/controller/AdminController.php
Labels: Bug fix, 8.1.x

#35462 Functional Tests : Hummingbird > FO - Product page - Product page : Add to cart
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/02_productPage/01_addToCart.ts
  tests/UI/pages/FO/classic/cart/index.ts
  tests/UI/pages/FO/classic/product/index.ts
  tests/UI/pages/FO/hummingbird/cart/index.ts
  tests/UI/pages/FO/hummingbird/home/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35639 Functional tests - Add new test 'FO > Hummingbird > Download invoice from orders list'
  tests/UI/campaigns/functional/FO/hummingbird/03_userAccount/02_orderHistory/01_orderDetails/02_downloadInvoice.ts
  tests/UI/campaigns/functional/FO/hummingbird/03_userAccount/02_orderHistory/03_downloadInvoice.ts
  tests/UI/pages/FO/classic/myAccount/orderDetails.ts
  tests/UI/pages/FO/hummingbird/myAccount/orderDetails.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35646 UI Tests : Allow to enable/disable make
  .github/actions/setup-env/action.yml
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35630 Product multilang listing
  composer.json
  composer.lock
  src/Adapter/Language/Repository/LanguageRepository.php
  src/Core/Context/LanguageContextBuilder.php
  src/PrestaShopBundle/ApiPlatform/Metadata/DQBPaginatedList.php
  src/PrestaShopBundle/ApiPlatform/Provider/QueryListProvider.php
  src/PrestaShopBundle/EventListener/Context/API/ApiLegacyContextListener.php
  src/PrestaShopBundle/Resources/config/services/adapter/language.yml
  src/PrestaShopBundle/Resources/config/services/bundle/context.yml
  src/PrestaShopBundle/Resources/config/services/bundle/services.yml
  src/PrestaShopBundle/Resources/config/services/core/search.yml
  tests/Unit/Core/Context/LanguageContextBuilderTest.php
  tests/Unit/PrestaShopBundle/EventListener/Context/API/ApiLegacyContextListenerTest.php
  tests/Unit/PrestaShopBundle/EventListener/Context/API/LanguageContextListenerTest.php
  tests/Unit/PrestaShopBundle/EventListener/Context/Admin/LanguageContextListenerTest.php
Labels: Waiting for author, Waiting for QA, develop, Feature, BC break

#35518 BO login screen - don't show PrestaShop version before Employee successful login
  admin-dev/themes/default/template/controllers/login/content.tpl
Labels: Improvement, QA ✔️, 8.1.x

#35651 Functional tests - Add new test 'FO > Hummingbird > Check modal'
  tests/UI/campaigns/functional/FO/hummingbird/10_cart/01_modal/01_displayModal.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35650 Functional tests - Add new test 'FO > Hummingbird > Select color in home page'
  tests/UI/campaigns/functional/FO/hummingbird/06_homePage/05_selectColor.ts
  tests/UI/pages/FO/hummingbird/home/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35564 Update product SEO metadata length
  src/Core/Domain/Product/ProductSettings.php
  src/PrestaShopBundle/Form/Admin/Sell/Product/SEO/SEOType.php
  translations/default/AdminCatalogHelp.xlf
Labels: Improvement, QA ✔️, develop, Topwatchers

#35662 Update ps_linklist module
  composer.lock
Labels: Improvement, develop

#35657 Functional Tests: Hummingbird > FO - User account - Order history - Order details - Request a merchandise return from order details
  tests/UI/campaigns/functional/FO/classic/03_userAccount/03_merchandiseReturns/01_consultReturnDetails.ts
  tests/UI/campaigns/functional/FO/classic/03_userAccount/03_merchandiseReturns/02_checkOrderReturnPDF.ts
  tests/UI/campaigns/functional/FO/hummingbird/03_userAccount/02_orderHistory/01_orderDetails/03_requestMerchandiseReturn.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35660 Functional tests - Add new test 'FO > Hummingbird > Show details in checkout page'
  tests/UI/campaigns/functional/FO/hummingbird/11_checkout/01_showDetails.ts
  tests/UI/pages/FO/classic/checkout/index.ts
  tests/UI/pages/FO/classic/product/index.ts
  tests/UI/pages/FO/hummingbird/checkout/index.ts
  tests/UI/pages/FO/hummingbird/product/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35661 Functional Tests : API : GET /api/products
  tests/UI/campaigns/functional/API/02_endpoints/04_hook/01_getAPIHookStatusId.ts
  tests/UI/campaigns/functional/API/02_endpoints/04_hook/02_getAPIHooksId.ts
  tests/UI/campaigns/functional/API/02_endpoints/05_product/01_postAPIProduct.ts
  tests/UI/campaigns/functional/API/02_endpoints/05_product/02_deleteAPIProductId.ts
  tests/UI/campaigns/functional/API/02_endpoints/05_product/03_getAPIProductId.ts
  tests/UI/campaigns/functional/API/02_endpoints/05_product/04_patchAPIProductId.ts
  tests/UI/campaigns/functional/API/02_endpoints/06_productList/01_getAPIProducts.ts
  tests/UI/pages/BO/catalog/products/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35658 Functional Tests: Category products module - Disable/Enable module
  tests/UI/campaigns/modules/ps_categoryproducts/01_installation/01_disableEnableModule.ts
  tests/UI/data/demo/modules.ts
  tests/UI/pages/FO/classic/product/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35656 Functional Tests: Faceted search module - Disable/Enable module
  tests/UI/campaigns/modules/ps_facetedsearch/01_installation/03_disableEnableModule.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35652 Functional Tests : Hummingbird > FO - Order confirmation : Contact us
  tests/UI/campaigns/functional/FO/hummingbird/12_orderConfirmation/05_contactUs.ts
  tests/UI/pages/FO/classic/checkout/orderConfirmation.ts
  tests/UI/pages/FO/hummingbird/checkout/orderConfirmation.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35669 Merge 8.1.5 build branch into 8.1.x
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: Improvement, Waiting for QA, 8.1.x

#35673 Fix changelog 8.1.5
  docs/CHANGELOG.txt
Labels: Improvement, QA ✔️, 8.1.x

#35689 Functional tests - Add new tests 'FO > Hummingbird > Menu and navigation''
  tests/UI/campaigns/functional/FO/hummingbird/06_homePage/02_displaySomeProducts.ts
  tests/UI/campaigns/functional/FO/hummingbird/06_homePage/03_allProducts.ts
  tests/UI/campaigns/functional/FO/hummingbird/06_homePage/04_productQuickView.ts
  tests/UI/campaigns/functional/FO/hummingbird/08_menuAndNavigation/01_navigateInCategories/02_breadcrumb.ts
  tests/UI/campaigns/functional/FO/hummingbird/08_menuAndNavigation/01_navigateInCategories/03_sideBlockCategories.ts
  tests/UI/campaigns/functional/FO/hummingbird/08_menuAndNavigation/02_sortAndFilter/01_sortProducts.ts
  tests/UI/campaigns/functional/FO/hummingbird/08_menuAndNavigation/02_sortAndFilter/02_filterProducts.ts
  tests/UI/campaigns/functional/FO/hummingbird/08_menuAndNavigation/02_sortAndFilter/03_clearFilters.ts
  tests/UI/pages/FO/FObasePage.ts
  tests/UI/pages/FO/classic/category/index.ts
  tests/UI/pages/FO/hummingbird/category/index.ts
  tests/UI/pages/FO/hummingbird/home/index.ts
  tests/UI/pages/commonPage.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35653 Take account of active and deleted fields when fetching a tax rules group id by name
  classes/tax/TaxRulesGroup.php
Labels: Improvement, QA ✔️

#35380 feat(infos): added hostname in system information
  src/Adapter/Hosting/HostingInformation.php
  src/Adapter/System/SystemInformation.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/system_information.html.twig
Labels: QA ✔️, develop, Feature

#35699 Correction of patch requests in PPV2
  admin-dev/index.php
  admin-dev/themes/new-theme/js/pages/product/service/image.ts
Labels: Improvement, QA ✔️, 8.1.x

#35621 Fix: Clear cache module multishop
  src/Core/Module/ModuleRepository.php
Labels: QA ✔️, Bug fix, 8.1.x

#35725 Add languages list API as a core endpoint that is available without specific scope
  composer.json
  composer.lock
  src/PrestaShopBundle/ApiPlatform/Metadata/DQBPaginatedList.php
  src/PrestaShopBundle/ApiPlatform/Provider/QueryListProvider.php
  src/PrestaShopBundle/ApiPlatform/Resources/Language.php
  tests/Integration/ApiPlatform/EndPoint/LanguageEndpointTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/DQBPaginatedListTest.php
Labels: develop, Feature

#35715 Functional tests - Add new test 'FO > Hummingbird > Check tags'
  tests/UI/campaigns/functional/FO/hummingbird/08_menuAndNavigation/03_navigationAndDisplay/01_displayTags.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35735 Fix array_slice modifier
  config/smarty.config.inc.php
Labels: Improvement, 8.1.x

#35729 Remove deprecated jquery method
  themes/_core/js/checkout-steps.js
Labels: QA ✔️, Bug fix, 8.1.x

#35698 Make changing order status more resilient to failed data
  src/Adapter/Order/CommandHandler/UpdateOrderStatusHandler.php
Labels: QA ✔️, Refactoring, 8.1.x

#35750 Filter experimental apis
  .github/workflows/symfony-console.yml
  composer.json
  composer.lock
  install-dev/data/xml/configuration.xml
  src/Adapter/AuthorizationServer/AuthorizationServerConfiguration.php
  src/PrestaShopBundle/ApiPlatform/Metadata/AbstractCQRSOperation.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSCommand.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSCreate.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSDelete.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSGet.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSPartialUpdate.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSQueryCollection.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSUpdate.php
  src/PrestaShopBundle/ApiPlatform/Metadata/DQBPaginatedList.php
  src/PrestaShopBundle/ApiPlatform/Metadata/Resource/Factory/ExperimentalOperationsMetadataCollectionFactoryDecorator.php
  src/PrestaShopBundle/ApiPlatform/Scopes/ApiResourceScopesExtractor.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AuthorizationServer/ApiClientController.php
  src/PrestaShopBundle/EventListener/API/SSLMiddlewareListener.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/AuthorizationServer/ConfigurationType.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/AuthorizationServer/FormDataProvider.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/authorization_server.yml
  src/PrestaShopBundle/Resources/config/services/adapter/data_configuration.yml
  src/PrestaShopBundle/Resources/config/services/bundle/api_platform.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_data_provider.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_handler.yml
  src/PrestaShopBundle/Resources/config/services/bundle/oauth.yml
  src/PrestaShopBundle/Resources/config/services/bundle/services.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/AuthorizationServer/ApiClient/index.html.twig
  tests/Integration/ApiPlatform/DisabledEndpointsTest.php
  tests/Integration/ApiPlatform/EndPoint/ApiTestCase.php
  tests/Resources/ApiPlatform/Resources/ApiTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSCommandTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSCreateTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSDeleteTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSGetTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSPartialUpdateTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSQueryCollectionTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSUpdateTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/DQBPaginatedListTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Scopes/ApiResourceScopesExtractorTest.php
Labels: develop, Feature

#35757 Functional Tests : Hummingbird : FO - Menu and Navigation : Check categories and subcategories links in header
  tests/UI/campaigns/functional/FO/hummingbird/08_menuAndNavigation/01_navigateInCategories/01_consultCategoriesInHeader.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35769 Functional Tests: Hummingbird - FO - Checkout - Addresses - Use another address for invoice as a guest
  tests/UI/campaigns/functional/FO/hummingbird/11_checkout/02_addresses/02_useDifferentAddressForInvoice.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35718 Functional tests - Add new test 'FO > Hummingbird > Checkout > Display totals'
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/01_information/01_withAndWithoutCode.ts
  tests/UI/campaigns/functional/FO/classic/11_checkout/02_displayOfTotals.ts
  tests/UI/campaigns/functional/FO/hummingbird/11_checkout/02_displayOfTotals.ts
  tests/UI/pages/FO/classic/cart/index.ts
  tests/UI/pages/FO/classic/checkout/index.ts
  tests/UI/pages/FO/hummingbird/cart/index.ts
  tests/UI/pages/FO/hummingbird/checkout/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests
