Repository PrestaShop/PrestaShop, pull requests merged in 2024-02, with the labels that each got.

#35025 Fix module updates
  classes/module/Module.php
Labels: QA ✔️, develop, Bug fix

#35234 Fix route name
  src/Core/Grid/Definition/Factory/CustomerViewedProductGridDefinitionFactory.php
Labels: QA ✔️, develop, Bug fix

#35241 Update Symfony components after 6.4.3 release
  composer.lock
Labels: Improvement, develop

#35259 Remove dataviz related
  admin-dev/themes/default/template/helpers/dataviz/graph.tpl
  admin-dev/themes/default/template/helpers/dataviz/index.php
  controllers/admin/AdminTranslationsController.php
  tests/Integration/Core/Translation/Storage/Provider/OthersCatalogueLayersProviderTest.php
  tests/Resources/translations/default/messages.xlf
  tests/Resources/translations/fr-FR/messages.fr-FR.xlf
  translations/default/messages.xlf
Labels: QA ✔️, develop, Refactoring

#35249 Change runners to be based on macos environment
  .github/workflows/php.yml
Labels: Improvement, develop, Bug fix, BC break

#35271 Update GitHub actions using deprecated version of node
  .github/actions/ui-test/action.yml
  .github/workflows/behaviour.yml
  .github/workflows/cron_docker_build.yml
  .github/workflows/cron_js_routing.yml
  .github/workflows/cron_nightly_build.yml
  .github/workflows/cron_nightly_tests_reusable.yml
  .github/workflows/cron_php_update_modules.yml
  .github/workflows/integration.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .github/workflows/php.yml
  .github/workflows/sanity.yml
  .github/workflows/symfony-console.yml
  .github/workflows/ui_tests_code_checks.yml
Labels: Improvement, develop

#35274 Move debug and web profiler bundle into prod dependencies
  composer.json
  composer.lock
Labels: develop, Bug fix

#35167 Change old links to newer method
  classes/PaymentModule.php
  classes/controller/FrontController.php
  classes/controller/ModuleFrontController.php
  classes/form/CustomerAddressForm.php
  controllers/front/AddressController.php
  controllers/front/OrderConfirmationController.php
  controllers/front/OrderController.php
  controllers/front/OrderDetailController.php
  controllers/front/OrderFollowController.php
  controllers/front/PasswordController.php
  controllers/front/PdfInvoiceController.php
  controllers/front/PdfOrderReturnController.php
  controllers/front/PdfOrderSlipController.php
Labels: QA ✔️, develop, Refactoring

#35281 Fix diacritics pdf invoice support for ro-RO
  classes/pdf/PDFGenerator.php
Labels: Waiting for QA, QA ✔️, develop, Bug fix

#35244 Functional tests - Fix random error in 'BO > Catalog:07-08'
  tests/UI/pages/BO/catalog/stocks/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35290 Functional Tests : Fixed glob for package.json
  tests/UI/package.json
Labels: TE, develop, Bug fix, E2E Tests

#35294 Nightly : Fixed `tests/UI/campaigns/functional/FO/classic/01*/04*`
  tests/UI/campaigns/functional/FO/classic/01_login/04_createAccount.ts
Labels: develop, Bug fix

#35231 Fix index.php links in admin zone
  admin-dev/filemanager/config/config.php
  admin-dev/init.php
  admin-dev/themes/default/template/controllers/carrier_wizard/logo.tpl
  admin-dev/themes/default/template/controllers/customer_threads/message.tpl
  admin-dev/themes/default/template/controllers/modules/configure.tpl
  admin-dev/themes/default/template/search_form.tpl
  admin-dev/themes/new-theme/template/components/layout/search_form.tpl
  classes/helper/HelperList.php
  controllers/admin/AdminDashboardController.php
  controllers/admin/AdminLegacyLayoutController.php
  controllers/admin/AdminModulesController.php
  controllers/admin/AdminSearchController.php
  controllers/admin/AdminTranslationsController.php
Labels: QA ✔️, develop, Refactoring

#35300 Nightly : Fixed `campaigns/functional/BO/02*/05*/*`
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/01_filterShoppingCarts.ts
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/04_exportCarts.ts
Labels: develop, Bug fix

#35310 Functional tests - Add new test 'FO > Hummingbird > Check mailto link'
  tests/UI/campaigns/functional/FO/hummingbird/05_contactUs/01_checkMailtoLink.ts
Labels: TE, develop, Refactoring, E2E Tests

#35266 Update API-platform to v3
  app/config/config.yml
  composer.json
  composer.lock
  src/PrestaShopBundle/ApiPlatform/Provider/QueryProvider.php
  src/PrestaShopBundle/ApiPlatform/Resources/CustomerGroup.php
  src/PrestaShopBundle/ApiPlatform/Resources/FoundProduct.php
  src/PrestaShopBundle/ApiPlatform/Resources/Hook.php
  src/PrestaShopBundle/ApiPlatform/Resources/Product.php
  src/PrestaShopBundle/EventListener/AccessDeniedListener.php
  tests/Integration/ApiPlatform/EndPoint/ApiAccessTokenEndpointTest.php
  tests/Integration/ApiPlatform/EndPoint/ApiTestCase.php
  tests/Integration/ApiPlatform/EndPoint/ProductEndpointTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSDeleteTest.php
  tests/Unit/Resources/api_platform/fake_core_resources/src/PrestaShopBundle/ApiPlatform/Resources/Hook.php
  tests/Unit/Resources/api_platform/fake_module_resources/fake_module/src/ApiPlatform/Resources/ApiAccess.php
Labels: Improvement, develop

#35309 Nightly : Add campaign Hummingbird 04 & 11
  .github/workflows/cron_nightly_tests_reusable.yml
  tests/UI/package.json
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35282 Functional Tests : Theme Customization module - Uninstall and delete module
  tests/UI/campaigns/modules/ps_themecusto/01_installation/03_uninstallAndDeleteModule.ts
  tests/UI/data/demo/modules.ts
  tests/UI/pages/BO/BObasePage.ts
  tests/UI/pages/BO/design/themeAndLogo/themeAndLogo/themeAndLogoBasePage.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35315 Functional Tests : Hummingbird : FO - Checkout - Shipping method - Select a carrier
  tests/UI/campaigns/functional/FO/hummingbird/11_checkout/03_shippingMethods/02_selectCarrier.ts
  tests/UI/pages/FO/classic/checkout/index.ts
  tests/UI/pages/FO/hummingbird/checkout/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35308 Functional tests - Add new test 'FO > Hummingbird > Subscribe to newsletter'
  tests/UI/campaigns/functional/FO/hummingbird/04_newsletter/01_subscribeNewsletter.ts
  tests/UI/pages/FO/classic/home/index.ts
  tests/UI/pages/FO/hummingbird/home/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35302 Functional tests - Add new test in 'FO > Hummingbird > logout from user account page'
  tests/UI/campaigns/functional/FO/hummingbird/03_userAccount/04_logOut.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35172 Delete endpoints that have been moved to the module
  admin-dev/themes/new-theme/scss/pages/_authorization_server.scss
  composer.lock
  src/PrestaShopBundle/ApiPlatform/Resources/CustomerGroup.php
  src/PrestaShopBundle/ApiPlatform/Resources/FoundProduct.php
  src/PrestaShopBundle/ApiPlatform/Resources/Hook.php
  src/PrestaShopBundle/ApiPlatform/Resources/Product.php
  src/PrestaShopBundle/ApiPlatform/Resources/readme.md
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/AuthorizationServer/ApiAccessType.php
  src/PrestaShopBundle/Form/Admin/AdvancedParameters/AuthorizationServer/ResourceScopesType.php
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/AuthorizationServer/ApiAccess/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/AuthorizationServer/ApiAccess/form_theme.html.twig
  tests/Integration/ApiPlatform/DomainSerializerTest.php
  tests/Integration/ApiPlatform/EndPoint/CustomerGroupApiTest.php
  tests/Integration/ApiPlatform/EndPoint/GetHookApiTest.php
  tests/Integration/ApiPlatform/EndPoint/GetHookStatusApiTest.php
  tests/Integration/ApiPlatform/EndPoint/ProductEndpointTest.php
  tests/Integration/ApiPlatform/EndPoint/ProductMultiShopEndpointTest.php
  tests/UI/campaigns/modules/ps_apiresources/01_installation/01_uninstallAndInstallModule.ts
  tests/UI/campaigns/modules/ps_apiresources/01_installation/02_disableEnableModule.ts
  tests/UI/pages/BO/advancedParameters/APIAccess/add.ts
  tests/Unit/PrestaShopBundle/ApiPlatform/StateProvider/QueryProviderTest.php
Labels: Waiting for QA, develop, Refactoring

#35335 Functional tests - Add tests in 'FO > Hummingbird > Order as a guest - Sign in - Create account'
  tests/UI/campaigns/functional/FO/hummingbird/11_checkout/01_personalInformation/01_orderAsAGuest.ts
  tests/UI/campaigns/functional/FO/hummingbird/11_checkout/01_personalInformation/02_signIn.ts
  tests/UI/campaigns/functional/FO/hummingbird/11_checkout/01_personalInformation/03_createAccount.ts
  tests/UI/pages/FO/classic/cart/index.ts
  tests/UI/pages/FO/classic/checkout/index.ts
  tests/UI/pages/FO/hummingbird/cart/index.ts
  tests/UI/pages/FO/hummingbird/checkout/index.ts
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#35307 Fix non scalar value in translation
  src/Adapter/Translations/TranslationRouteFinder.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/TranslationsController.php
  src/PrestaShopBundle/Controller/Api/TranslationController.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/translations.yml
  src/PrestaShopBundle/Resources/views/Admin/Improve/International/Translations/Blocks/modify_translations.html.twig
  tests/UI/pages/BO/international/translations/index.ts
Labels: QA ✔️, develop, Bug fix

#35166 Validate cart rule actions on load
  classes/controller/FrontController.php
Labels: QA ✔️, Bug fix, 8.1.x

#35313 RouteNotFoundException when I configure a disabled module
  src/Adapter/Module/Repository/ModuleRepository.php
  src/PrestaShopBundle/DependencyInjection/Compiler/LoadServicesFromModulesPass.php
  src/PrestaShopBundle/DependencyInjection/Compiler/ModuleControllerRegisterPass.php
  src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php
  src/PrestaShopBundle/Resources/config/services/bundle/routing.yml
  src/PrestaShopBundle/Routing/YamlModuleLoader.php
Labels: QA ✔️, develop, Bug fix

#35343 Clean empty old API files
  src/PrestaShopBundle/ApiPlatform/Resources/CustomerGroup.php
  src/PrestaShopBundle/ApiPlatform/Resources/FoundProduct.php
  src/PrestaShopBundle/ApiPlatform/Resources/Hook.php
  src/PrestaShopBundle/ApiPlatform/Resources/Product.php
  src/PrestaShopBundle/ApiPlatform/Resources/README.md
  tests/Integration/ApiPlatform/EndPoint/ProductEndpointTest.php
Labels: develop, Bug fix

#35332 Run the API module tests in the core CI
  composer.json
  composer.lock
Labels: Improvement, develop

#35352 Functional Tests : Hummingbird - FO - Checkout - Shipping methods : Add order message
  tests/UI/campaigns/functional/BO/01_dashboard/02_activityOverview.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/08_chooseAddress.ts
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/06_merchandiseReturnsTab.ts
  tests/UI/campaigns/functional/BO/03_catalog/01_products/05_CRUDVirtualProduct.ts
  tests/UI/campaigns/functional/BO/03_catalog/01_products/13_virtualTab.ts
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/06_forwardMessage.ts
  tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/01_merchandiseReturnOptions.ts
  tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/02_deleteProduct.ts
  tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/03_updateStatus.ts
  tests/UI/campaigns/functional/BO/14_advancedParameters/03_administration/03_notifications.ts
  tests/UI/campaigns/functional/BO/15_header/08_checkNotifications.ts
  tests/UI/campaigns/functional/FO/classic/03_userAccount/01_creditSlips/01_consultCreditSlip.ts
  tests/UI/campaigns/functional/FO/classic/03_userAccount/02_orderHistory/01_orderDetails/01_reorderFromOrderDetail.ts
  tests/UI/campaigns/functional/FO/classic/03_userAccount/02_orderHistory/01_orderDetails/02_downloadInvoice.ts
  tests/UI/campaigns/functional/FO/classic/03_userAccount/02_orderHistory/01_orderDetails/03_requestMerchandiseReturn.ts
  tests/UI/campaigns/functional/FO/classic/03_userAccount/02_orderHistory/01_orderDetails/04_sendMessage.ts
  tests/UI/campaigns/functional/FO/classic/03_userAccount/02_orderHistory/02_reorderFromOrderList.ts
  tests/UI/campaigns/functional/FO/classic/03_userAccount/merchandiseReturns/01_consultReturnDetails.ts
  tests/UI/campaigns/functional/FO/classic/03_userAccount/merchandiseReturns/02_checkOrderReturnPDF.ts
  tests/UI/campaigns/functional/FO/classic/11_checkout/03_shippingMethods/01_addOrderMessage.ts
  tests/UI/campaigns/functional/FO/hummingbird/11_checkout/03_shippingMethods/01_addOrderMessage.ts
  tests/UI/campaigns/modules/ps_emailalerts/02_configuration/02_merchantNotifications/04_enableDisableReturn.ts
  tests/UI/pages/FO/classic/checkout/index.ts
  tests/UI/pages/FO/classic/myAccount/orderDetails.ts
  tests/UI/pages/FO/classic/myAccount/orderHistory.ts
  tests/UI/pages/FO/hummingbird/checkout/index.ts
  tests/UI/pages/FO/hummingbird/myAccount/orderDetails.ts
  tests/UI/pages/FO/hummingbird/myAccount/orderHistory.ts
Labels: Improvement, QA ✔️, TE, develop, BC break, E2E Tests

#35360 List operation and pagination
  src/Core/Grid/Query/Api/HookQueryBuilder.php
  src/PrestaShopBundle/ApiPlatform/DomainSerializer.php
  src/PrestaShopBundle/ApiPlatform/Exception/QueryBuilderNotFoudException.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSQueryCollection.php
  src/PrestaShopBundle/ApiPlatform/Metadata/DQBPaginatedList.php
  src/PrestaShopBundle/ApiPlatform/Pagination/PaginationElements.php
  src/PrestaShopBundle/ApiPlatform/Provider/QueryListProvider.php
  src/PrestaShopBundle/Resources/config/services/bundle/services.yml
  src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
  tests/Integration/ApiPlatform/DomainSerializerTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSQueryCollectionTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/DQBPaginatedListTest.php
Labels: Waiting for QA, develop, Feature

#35357 Functional Tests : New products block module - Reset module
  composer.lock
  tests/UI/campaigns/functional/BO/11_international/04_translations/01_modifyTranslation.ts
  tests/UI/campaigns/functional/FO/classic/06_homePage/02_displaySomeProducts.ts
  tests/UI/campaigns/modules/ps_newproducts/01_installation/04_resetModule.ts
  tests/UI/data/demo/modules.ts
  tests/UI/pages/BO/modules/psNewProducts/index.ts
  tests/UI/pages/FO/classic/home/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35386 Functional Tests : Hummingbird > FO - Checkout - Addresses : CRUD address
  tests/UI/campaigns/functional/FO/hummingbird/11_checkout/02_addresses/01_CRUDAddress.ts
  tests/UI/pages/FO/classic/checkout/index.ts
  tests/UI/pages/FO/hummingbird/checkout/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35388 Functional Tests : New products block module - Disable/Enable module
  tests/UI/campaigns/modules/ps_newproducts/01_installation/05_disableEnableModule.ts
  tests/UI/pages/FO/classic/home/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35392 Functional Tests : Hummingbird > FO - Checkout - Personal information : Password reminder
  tests/UI/campaigns/functional/FO/hummingbird/11_checkout/01_personalInformation/05_passwordReminder.ts
  tests/UI/pages/FO/classic/checkout/index.ts
  tests/UI/pages/FO/hummingbird/checkout/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35415 Functional tests - Add new test 'FO > Hummingbird > Add to cart'
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/01_quickView/01_addToCart.ts
  tests/UI/pages/FO/classic/cart/index.ts
  tests/UI/pages/FO/classic/home/index.ts
  tests/UI/pages/FO/classic/searchResults/index.ts
  tests/UI/pages/FO/hummingbird/cart/index.ts
  tests/UI/pages/FO/hummingbird/home/index.ts
  tests/UI/pages/FO/hummingbird/searchResults/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35414 Rebind composer on the API module dev branch and update composer.lock
  composer.json
  composer.lock
Labels: develop, Refactoring

#35364 Functional tests - Fix 'FO:classic:01-03 get GDPR data in PDF'
  tests/UI/campaigns/functional/FO/classic/03_userAccount/04_getGDPRDataInPDF.ts
  tests/UI/utils/files.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#34485 Add support for PHP 8.3
  .github/workflows/api-module.yml
  .github/workflows/behaviour.yml
  .github/workflows/integration.yml
  .github/workflows/php.yml
  .github/workflows/sanity.yml
  install-dev/install_version.php
  tools/build/Library/InstallUnpacker/index_template.php
Labels: Improvement, develop

#35424 Allow JSON format for OpenApi doc
  app/config/config.yml
Labels: Waiting for QA, develop, Bug fix

#35417 AppKernel is now able to detect the admin folder
  app/AppKernel.php
  app/config/config.yml
Labels: Improvement, QA ✔️, develop

#35329 Remove migrated shopping carts pages feature flag
  classes/controller/AdminController.php
  classes/lang/KeysReference/FeatureFlagLang.php
  controllers/admin/AdminCartsController.php
  install-dev/data/xml/feature_flag.xml
  src/Adapter/Kpi/AbandonedCartKpi.php
  src/Core/FeatureFlag/FeatureFlagSettings.php
  src/Core/Grid/Definition/Factory/CartGridDefinitionFactory.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/carts.yml
  src/PrestaShopBundle/Twig/Component/NotificationsCenter.php
  tests/Integration/Classes/controller/AdminControllerTest.php
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/04_selectPreviousCarts.ts
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/01_filterShoppingCarts.ts
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/02_sortAndPagination.ts
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/03_viewCarts.ts
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/05_deleteAbandonedCarts.ts
  tests/UI/campaigns/functional/FO/classic/03_userAccount/04_getGDPRDataInPDF.ts
  tests/UI/campaigns/functional/FO/classic/03_userAccount/05_getGDPRDataInCSV.ts
  tests/UI/campaigns/functional/WS/02_ordersCRUD.ts
  tests/UI/commonTests/BO/orders/shoppingCarts.ts
  tests/UI/data/types/shoppingCart.d.ts
  tests/UI/pages/BO/advancedParameters/database/dbBackup/index.ts
  tests/UI/pages/BO/dashboard/index.ts
  tests/UI/pages/BO/orders/shoppingCarts/index.ts
Labels: Improvement, QA ✔️, develop, BC break, Needs autoupgrade PR

#35431 Functional Tests : Added some tests for some mocha tests
  tests/UI/package.json
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#35350 Add params to actionValidateOrderBefore
  classes/PaymentModule.php
Labels: Improvement, QA ✔️, develop, Needs documentation

#35430 Functional tests - Add new test 'FO > Hummingbird > Change quantity in quick view modal'
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/01_quickView/02_changeQuantity.ts
  tests/UI/pages/FO/classic/home/index.ts
  tests/UI/pages/FO/hummingbird/home/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35437 Nighly : Fixed `campaigns/functional/BO/02*/05*/01*`
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/01_filterShoppingCarts.ts
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#35373 Remove migrated image settings pages feature flag
  admin-dev/themes/new-theme/js/pages/image-settings/index.ts
  classes/lang/KeysReference/FeatureFlagLang.php
  controllers/admin/AdminImagesController.php
  install-dev/data/xml/feature_flag.xml
  src/Core/Domain/ImageSettings/CommandHandler/RegenerateThumbnailsHandler.php
  src/Core/FeatureFlag/FeatureFlagSettings.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/design/image_settings.yml
  tests/Integration/Classes/controller/AdminControllerTest.php
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/01_filterImageTypes.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/02_CRUDImageType.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/05_sortAndPagination.ts
  tests/UI/pages/BO/catalog/categories/index.ts
  tests/UI/pages/BO/design/imageSettings/add.ts
  tests/UI/pages/BO/design/imageSettings/index.ts
Labels: Improvement, QA ✔️, develop, BC break

#35321 Fix display of categories from other shops
  controllers/front/listing/CategoryController.php
Labels: QA ✔️, Bug fix, 8.1.x

#35440 Functioanl tests - Add new test 'FO > Hummingbird > Change quantity in cart page'
  tests/UI/campaigns/functional/FO/hummingbird/10_cart/02_cart/01_changeQuantity.ts
  tests/UI/package.json
  tests/UI/pages/FO/classic/cart/index.ts
  tests/UI/pages/FO/hummingbird/cart/index.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35450 Merge 8.1.x into develop 22/02/24
  classes/controller/FrontController.php
  controllers/front/listing/CategoryController.php
  docs/CHANGELOG.txt
  src/Adapter/Cart/QueryHandler/GetCartForViewingHandler.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Cart/Blocks/View/customer_information.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Cart/Blocks/View/order_information.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Cart/view.html.twig
  tests/UI/campaigns/functional/BO/02_orders/01_orders/createOrders/04_selectPreviousCarts.ts
  tests/UI/campaigns/functional/BO/02_orders/05_shoppingCarts/03_viewCarts.ts
  tests/UI/pages/BO/orders/shoppingCarts/view.ts
Labels: Improvement, develop

#35368 Improve TokenAuthenticator
  app/config/config.yml
  app/config/config_test.yml
  app/config/security.yml
  composer.json
  composer.lock
  src/Core/Security/OAuth2/TokenAuthenticator.php
  src/PrestaShopBundle/ApiPlatform/Metadata/AbstractCQRSOperation.php
  src/PrestaShopBundle/ApiPlatform/Metadata/ScopesToSecurityMetadataCollectionFactoryDecorator.php
  src/PrestaShopBundle/EventListener/AccessDeniedListener.php
  src/PrestaShopBundle/EventListener/ScopeCheckerListener.php
  src/PrestaShopBundle/Resources/config/services/bundle/event_listener.yml
  src/PrestaShopBundle/Resources/config/services/bundle/services.yml
  src/PrestaShopBundle/Resources/config/services/core/security.yml
  src/PrestaShopBundle/Security/OAuth2/Provider/ApiClientProvider.php
  tests/Integration/ApiPlatform/ApiSecurityTest.php
  tests/Integration/ApiPlatform/EndPoint/ApiAccessTokenEndpointTest.php
  tests/Integration/ApiPlatform/EndPoint/ApiTestCase.php
  tests/Resources/ApiPlatform/Resources/ApiTest.php
  tests/Unit/Core/Security/TokenAuthenticatorTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSCommandTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSCreateTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSDeleteTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSGetTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSPartialUpdateTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSQueryCollectionTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSUpdateTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/DQBPaginatedListTest.php
Labels: develop, Bug fix

#35455 Nightly : Fixed `campaigns/functional/BO/02*/05*/03*`
  tests/UI/pages/BO/orders/shoppingCarts/view.ts
Labels: QA ✔️, TE, develop, Bug fix, E2E Tests

#35456 Comment cart and quantity methods
  classes/Cart.php
  classes/Pack.php
  classes/Product.php
  controllers/front/CartController.php
Labels: Waiting for QA, Refactoring, 8.1.x

#35439 Fixed sort error after generation of credit slip just for delivery fees; refs #33890
  classes/pdf/HTMLTemplateOrderSlip.php
Labels: QA ✔️, develop, Bug fix

#35422 Bump version to 8.1.5
  install-dev/install_version.php
  src/Core/Version.php
Labels: 8.1.x

#34954 Fix Link->getModuleLink() function for other shop contexts
  classes/Dispatcher.php
  classes/Link.php
Labels: QA ✔️, Bug fix, 8.1.x

#35451 Functional tests - Add some refacto to 'FO > Quick edit - Block cart modal'
  tests/UI/campaigns/functional/BO/03_catalog/01_products/19_optionsTab.ts
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/02_conditions/01_limitToSingleCustomer.ts
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/02_conditions/02_invalidDateTime.ts
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/02_conditions/03_minimumAmount.ts
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/02_conditions/10_productSelection.ts
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/03_actions/07_applyToSpecificProduct.ts
  tests/UI/campaigns/functional/BO/05_customerService/01_customerService/06_forwardMessage.ts
  tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/02_deleteProduct.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/13_checkProductImageFormat.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/04_customerSettings/01_customers/01_redisplayCartAtLogin.ts
  tests/UI/campaigns/functional/FO/classic/02_headerAndFooter/01_checkLinksInHeader.ts
  tests/UI/campaigns/functional/FO/classic/06_homePage/04_productQuickView.ts
  tests/UI/campaigns/functional/FO/classic/08_menuAndNavigation/03_navigationAndDisplay/03_quickViewProducts.ts
  tests/UI/campaigns/functional/FO/classic/09_productPage/01_quickView.ts
  tests/UI/campaigns/functional/FO/classic/09_productPage/01_quickView/01_addToCart.ts
  tests/UI/campaigns/functional/FO/classic/10_cart/01_modal/01_displayModal.ts
  tests/UI/campaigns/functional/FO/classic/10_cart/02_cart/01_changeQuantity.ts
  tests/UI/campaigns/functional/FO/classic/10_cart/02_cart/02_deleteProduct.ts
  tests/UI/campaigns/functional/FO/classic/10_cart/02_cart/03_addPromoCode.ts
  tests/UI/campaigns/functional/FO/classic/11_checkout/01_showDetails.ts
  tests/UI/campaigns/functional/FO/classic/11_checkout/04_payment/01_choosePaymentMethod.ts
  tests/UI/campaigns/functional/FO/classic/12_orderConfirmation/05_contactUs.ts
  tests/UI/campaigns/functional/FO/hummingbird/02_headerAndFooter/01_checkLinksInHeader.ts
  tests/UI/campaigns/functional/FO/hummingbird/06_homePage/04_productQuickView.ts
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/01_quickView/01_addToCart.ts
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/01_quickView/02_changeQuantity.ts
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/01_quickView/03_shareLinks.ts
  tests/UI/campaigns/functional/FO/hummingbird/10_cart/02_cart/01_changeQuantity.ts
  tests/UI/campaigns/functional/FO/hummingbird/11_checkout/04_payment/01_choosePaymentMethod.ts
  tests/UI/campaigns/modules/ps_cashondelivery/01_installation/04_resetModule.ts
  tests/UI/campaigns/modules/ps_cashondelivery/02_configuration/01_placeOrderWithIt.ts
  tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.ts
  tests/UI/campaigns/sanity/04_catalogFO/01_filterProducts.ts
  tests/UI/campaigns/sanity/06_checkoutFO/01_orderProduct.ts
  tests/UI/pages/FO/classic/category/index.ts
  tests/UI/pages/FO/classic/home/index.ts
  tests/UI/pages/FO/classic/modal/blockCart.ts
  tests/UI/pages/FO/classic/modal/quickView.ts
  tests/UI/pages/FO/classic/searchResults/index.ts
  tests/UI/pages/FO/hummingbird/home/index.ts
  tests/UI/pages/FO/hummingbird/modal/blockCart.ts
  tests/UI/pages/FO/hummingbird/modal/quickView.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35418 Fix: The new password policy is not present in the reset password page #35410
  controllers/front/PasswordController.php
Labels: QA ✔️, Bug fix, 8.1.x

#35322 Fix shipping cost on order details page - backport from v9
  src/Adapter/Presenter/Order/OrderDetailLazyArray.php
Labels: QA ✔️, Bug fix, 8.1.x

#35372 Fix A pack set to Decrement products in pack only. cannot be added to cart
  classes/Cart.php
  controllers/front/CartController.php
Labels: QA ✔️, PM ✔️, Bug fix, 8.1.x

#34891 Fix issues on some catalog pages
  admin-dev/themes/new-theme/js/pages/feature/feature-value/index.ts
  src/Core/Grid/Definition/Factory/FeatureGridDefinitionFactory.php
  src/Core/Grid/Definition/Factory/FeatureValueGridDefinitionFactory.php
  src/PrestaShopBundle/Command/LegacyLinkLinterCommand.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureValueController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/SupplierController.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Features/FeatureValue/Blocks/form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Features/index.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Manufacturer/Blocks/View/products.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Manufacturer/index.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Suppliers/index.html.twig
  tests/UI/campaigns/functional/BO/13_shopParameters/01_general/general/08_enableDisableSuppliers.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/01_general/general/09_enableDisableBrands.ts
Labels: QA ✔️, PM ✔️, develop, Bug fix

#35482 Revert MacOs runner because of its instability
  .github/workflows/php.yml
Labels: develop, Bug fix

#35483 Bump classic to 2.1.3
  composer.lock
Labels: Improvement, Waiting for QA, 8.1.x

#35476 Github Actions (UI Tests) : Check that all suites are executed
  .github/workflows/ui_tests_code_checks.yml
  tests/UI/campaigns/modules/ps_apiresources/01_installation/01_uninstallAndInstallModule.ts
  tests/UI/campaigns/modules/ps_emailalerts/01_installation/01_uninstallAndInstallModule.ts
  tests/UI/campaigns/modules/ps_emailalerts/02_configuration/02_merchantNotifications/01_enableDisableNewOrder.ts
  tests/UI/campaigns/modules/ps_newproducts/01_installation/04_resetModule.ts
  tests/UI/package.json
  tests/UI/tools/linkchecker.ts
  tests/UI/tools/suites.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35464 Do not show vouchers that should be hidden
  admin-dev/themes/default/template/controllers/cart_rules/informations.tpl
  classes/CartRule.php
  js/admin.js
  tests/Integration/Classes/CartRuleTest.php
Labels: QA ✔️, PM ✔️, Bug fix, 8.1.x

#35495 Add most used rule group to new products
  src/Adapter/Product/Repository/ProductRepository.php
  src/Adapter/TaxRulesGroup/Repository/TaxRulesGroupRepository.php
  tests/Integration/Behaviour/Features/Scenario/Product/update_prices.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_prices_ecotax.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_prices_without_states.feature
Labels: QA ✔️, Bug fix, 8.1.x

#35452 Functional Tests : Hummingbird > FO - Account : Send a message with an ordered product
  tests/UI/campaigns/functional/FO/hummingbird/03_userAccount/02_orderHistory/01_orderDetails/04_sendMessage.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35453 Functional Tests : Faceted search module - Add new template
  tests/UI/campaigns/modules/ps_facetedsearch/02_configuration/14_editTemplateProductStockFilter.ts
  tests/UI/campaigns/modules/ps_facetedsearch/02_configuration/15_editTemplateProductBrandFilter.ts
  tests/UI/campaigns/modules/ps_facetedsearch/02_configuration/21_addNewTemplate.ts
  tests/UI/pages/BO/modules/psFacetedSearch/filterTemplate.ts
  tests/UI/pages/BO/modules/psFacetedSearch/index.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35459 Functional Tests : Mail alerts module - Uninstall and delete module
  tests/UI/campaigns/modules/ps_emailalerts/01_installation/03_uninstallAndDeleteModule.ts
  tests/UI/commonTests/BO/modules/moduleManager.ts
Labels: Improvement, QA ✔️, TE, develop, E2E Tests

#35498 Functional Tests : Refactoring Install Hummingbird with remove zip
  tests/UI/campaigns/functional/BO/08_design/01_themeAndLogo/01_themeAndLogo/01_addNewTheme.ts
  tests/UI/campaigns/functional/FO/hummingbird/01_login/01_passwordReminder.ts
  tests/UI/campaigns/functional/FO/hummingbird/01_login/02_login.ts
  tests/UI/campaigns/functional/FO/hummingbird/01_login/03_logout.ts
  tests/UI/campaigns/functional/FO/hummingbird/01_login/04_createAccount.ts
  tests/UI/campaigns/functional/FO/hummingbird/02_headerAndFooter/01_checkLinksInHeader.ts
  tests/UI/campaigns/functional/FO/hummingbird/02_headerAndFooter/02_checkLinksInFooter.ts
  tests/UI/campaigns/functional/FO/hummingbird/02_headerAndFooter/03_changeCurrency.ts
  tests/UI/campaigns/functional/FO/hummingbird/02_headerAndFooter/04_changeLanguage.ts
  tests/UI/campaigns/functional/FO/hummingbird/03_userAccount/01_editInformation.ts
  tests/UI/campaigns/functional/FO/hummingbird/03_userAccount/02_CRUDAddress.ts
  tests/UI/campaigns/functional/FO/hummingbird/03_userAccount/03_viewVoucher.ts
  tests/UI/campaigns/functional/FO/hummingbird/03_userAccount/04_logOut.ts
  tests/UI/campaigns/functional/FO/hummingbird/04_newsletter/01_subscribeNewsletter.ts
  tests/UI/campaigns/functional/FO/hummingbird/05_contactUs/01_checkMailtoLink.ts
  tests/UI/campaigns/functional/FO/hummingbird/05_contactUs/02_sendMessageWithCustomer.ts
  tests/UI/campaigns/functional/FO/hummingbird/05_contactUs/03_sendMessageAsAnonymous.ts
  tests/UI/campaigns/functional/FO/hummingbird/05_contactUs/04_addAttachment.ts
  tests/UI/campaigns/functional/FO/hummingbird/06_homePage/01_checkSlider.ts
  tests/UI/campaigns/functional/FO/hummingbird/06_homePage/02_displaySomeProducts.ts
  tests/UI/campaigns/functional/FO/hummingbird/06_homePage/03_allProducts.ts
  tests/UI/campaigns/functional/FO/hummingbird/06_homePage/04_productQuickView.ts
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/01_quickView/01_addToCart.ts
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/01_quickView/02_changeQuantity.ts
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/01_quickView/03_shareLinks.ts
  tests/UI/campaigns/functional/FO/hummingbird/10_cart/02_cart/01_changeQuantity.ts
  tests/UI/campaigns/functional/FO/hummingbird/11_checkout/01_personalInformation/01_orderAsAGuest.ts
  tests/UI/campaigns/functional/FO/hummingbird/11_checkout/01_personalInformation/02_signIn.ts
  tests/UI/campaigns/functional/FO/hummingbird/11_checkout/01_personalInformation/03_createAccount.ts
  tests/UI/commonTests/FO/hummingbird.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35514 Fix nightly 28-02 : 'FO > Cart > Display modal'
  tests/UI/campaigns/functional/FO/classic/10_cart/01_modal/01_displayModal.ts
Labels: QA ✔️, TE, develop, Refactoring, E2E Tests

#35505 Add ean13 field to api stock management search engine for product and combinations
  src/PrestaShopBundle/Api/QueryParamsCollection.php
  src/PrestaShopBundle/Entity/Repository/StockManagementRepository.php
  src/PrestaShopBundle/Entity/Repository/StockRepository.php
  tests/Unit/PrestaShopBundle/Api/QueryParamsCollectionTest.php
Labels: Improvement, QA ✔️, develop
