Repository PrestaShop/PrestaShop, pull requests merged in 2024-06, with the labels that each got.

#36250 Stabilise CI and docker initialisation
  .docker/docker_run_git.sh
  .docker/wait-for-it.sh
  .github/workflows/create_diff_for_autoupgrade_pr_label.yml
  .github/workflows/cron_js_routing.yml
  .github/workflows/cron_php_update_modules.yml
  config/config.inc.php
  install-dev/init.php
  tools/assets/wait-build.sh
Labels: develop, Bug fix

#36303 Make explicit which PHP and Node.js versions needed to CreateRelease
  tools/build/README.md
Labels: Improvement, QA ✔️, develop

#36264 Check Employee IP address in BO
  src/PrestaShopBundle/EventListener/Admin/Context/ShopContextListener.php
  src/PrestaShopBundle/EventListener/Admin/EmployeeSessionSubscriber.php
  src/PrestaShopBundle/Security/Admin/TokenAttributes.php
  tests/Integration/Utility/LoginTrait.php
  tests/Unit/PrestaShopBundle/EventListener/Admin/Context/ShopContextListenerTest.php
Labels: Improvement, QA ✔️, Waiting for wording, develop

#36301 Reset password page - updating cancel btn selector (css…
  admin-dev/themes/new-theme/js/pages/login/login-map.ts
Labels: Waiting for QA, develop, Bug fix

#35488 Add Export button missing on new Product Page V2
  src/Core/Grid/Definition/Factory/ProductGridDefinitionFactory.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products_v2/product.yml
Labels: Improvement, QA ✔️

#36310 Merge 8.1.x into develop 04/06/2024
  admin-dev/themes/new-theme/js/pages/product/combination/generator/AttributesSelector.vue
  admin-dev/themes/new-theme/js/pages/product/combination/types.d.ts
  admin-dev/themes/new-theme/js/pages/product/edit/manager/feature-values-manager.ts
  admin-dev/themes/new-theme/scss/pages/product/product_page.scss
  admin-dev/themes/new-theme/scss/pages/product/products_catalog.scss
  classes/Cart.php
  classes/CartRule.php
  classes/assets/JavascriptManager.php
  classes/assets/StylesheetManager.php
  composer.json
  composer.lock
  controllers/front/PdfInvoiceController.php
  docs/CHANGELOG.txt
  phpstan-baseline.neon
  phpstan.neon.dist
  src/Adapter/AttributeGroup/QueryHandler/AbstractAttributeGroupQueryHandler.php
  src/Core/Domain/AttributeGroup/Attribute/QueryResult/Attribute.php
  src/Core/Domain/CustomerService/QueryHandler/GetCustomerThreadForViewingHandler.php
  src/PrestaShopBundle/Controller/Admin/SecuredFileReaderController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php
  src/PrestaShopBundle/Resources/config/routing/admin/_common.yml
  src/PrestaShopBundle/Resources/config/services/bundle/controller.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/FormTheme/categories.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/FormTheme/customizations.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/CustomerService/CustomerThread/Block/thread_messages.html.twig
  tests/Integration/Behaviour/Features/Context/Domain/AttributeGroupFeatureContext.php
  upload/.htaccess
Labels: develop, Bug fix

#36309 Integrate social icons on login page with symfony ux-icons
  admin-dev/themes/new-theme/icons/bi/facebook.svg
  admin-dev/themes/new-theme/icons/bi/github.svg
  admin-dev/themes/new-theme/icons/bi/twitter-x.svg
  admin-dev/themes/new-theme/scss/pages/login/login.scss
  app/AppKernel.php
  app/config/admin/config.yml
  composer.json
  composer.lock
  src/PrestaShopBundle/Resources/views/Admin/Layout/login_layout.html.twig
Labels: Waiting for QA, develop, Bug fix

#36316 Update auto generated hooks
  install-dev/data/xml/hook.xml
Labels: Needs autoupgrade PR

#36314 Update missing security attributes
  src/PrestaShopBundle/Command/SecurityAttributeLinterCommand.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/AttributeController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/permission.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/manufacturer.yml
Labels: Improvement, develop

#36293 Update Symfony components after 6.4.8 release
  composer.json
  composer.lock
Labels: Improvement, develop

#36312 Add optional blackfire installation in docker
  .docker/docker_run_git.sh
  README.md
  docker-compose.override.yml.dist
  docker-compose.yml
Labels: Improvement, QA ✔️, develop

#36298 Increase composer timeout globally in docker init script
  .docker/docker_run_git.sh
  .github/actions/setup-env-export-logs/action.yml
  .github/actions/setup-env/action.yml
Labels: Improvement, develop

#36318 Update Changelog for 9.0.0 Alpha 1
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: Improvement, Waiting for QA, develop

#36092 Explain branching strategy
  CONTRIBUTING.md
Labels: Improvement, Waiting for QA, develop

#36329 The most useful PR in the world
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improvement, develop

#36326 Add condition for "Needs autoupgrade pr" label workflow
  .github/workflows/create_diff_for_autoupgrade_pr_label.yml
Labels: Improvement, develop

#36270 Update doc about ReleaseCreator
  tools/build/README.md
Labels: Improvement, develop

#36338 Bump version to 8.1.7
  install-dev/install_version.php
  src/Core/Version.php
Labels: Improvement, Waiting for QA, 8.1.x

#36322 Symfony clean after migration
  src/Core/Context/LegacyControllerContext.php
  src/Core/Security/OAuth2/JwtTokenUser.php
  src/PrestaShopBundle/Entity/ApiClient.php
  src/PrestaShopBundle/Security/OAuth2/Provider/ApiClientProvider.php
  src/PrestaShopBundle/Service/DataProvider/UserProvider.php
Labels: QA ✔️

#36341 Preliminary tasks for 8.1.7 release
  composer.lock
  src/PrestaShopBundle/Command/SecurityAnnotationLinterCommand.php
Labels: Improvement, 8.1.x

#36342 Fix quantity check when there a customization in cart (Backport from #32312)
  classes/Cart.php
  classes/Pack.php
  classes/Product.php
  controllers/front/CartController.php
Labels: QA ✔️, Bug fix, 8.1.x

#36343 Downgrade blockreassurance
  composer.json
  composer.lock
Labels: develop, Bug fix

#36306 Open EntitySearchInput to public components in backoffice
  admin-dev/themes/new-theme/js/app/utils/init-components.ts
  admin-dev/themes/new-theme/js/pages/product/edit/manager/related-products-manager.ts
Labels: Improvement, QA ✔️, 8.1.x

#36340 Update default catalog 8.1.x
  translations/default/AdminActions.xlf
  translations/default/AdminAdvparametersFeature.xlf
  translations/default/AdminAdvparametersHelp.xlf
  translations/default/AdminAdvparametersNotification.xlf
  translations/default/AdminCatalogFeature.xlf
  translations/default/AdminCatalogHelp.xlf
  translations/default/AdminCatalogNotification.xlf
  translations/default/AdminDesignFeature.xlf
  translations/default/AdminDesignHelp.xlf
  translations/default/AdminDesignNotification.xlf
  translations/default/AdminGlobal.xlf
  translations/default/AdminInternationalFeature.xlf
  translations/default/AdminInternationalHelp.xlf
  translations/default/AdminInternationalNotification.xlf
  translations/default/AdminLoginFeature.xlf
  translations/default/AdminLoginNotification.xlf
  translations/default/AdminModulesFeature.xlf
  translations/default/AdminModulesNotification.xlf
  translations/default/AdminNavigationHeader.xlf
  translations/default/AdminNavigationMenu.xlf
  translations/default/AdminNavigationNotification.xlf
  translations/default/AdminNotificationsError.xlf
  translations/default/AdminNotificationsInfo.xlf
  translations/default/AdminNotificationsSuccess.xlf
  translations/default/AdminNotificationsWarning.xlf
  translations/default/AdminOrderscustomersFeature.xlf
  translations/default/AdminOrderscustomersNotification.xlf
  translations/default/AdminShippingFeature.xlf
  translations/default/AdminShopparametersFeature.xlf
  translations/default/AdminShopparametersHelp.xlf
  translations/default/AdminShopparametersNotification.xlf
  translations/default/EmailsBody.xlf
  translations/default/EmailsSubject.xlf
  translations/default/ModulesBlockreassuranceAdmin.xlf
  translations/default/ModulesBlockwishlistShop.xlf
  translations/default/ModulesContactinfoShop.xlf
  translations/default/ModulesDashactivityAdmin.xlf
  translations/default/ModulesDashgoalsAdmin.xlf
  translations/default/ModulesEmailalertsShop.xlf
  translations/default/ModulesFacetedsearchAdmin.xlf
  translations/default/ModulesLinklistShop.xlf
  translations/default/ModulesProductcommentsAdmin.xlf
  translations/default/ModulesProductcommentsShop.xlf
  translations/default/ModulesWirepaymentAdmin.xlf
  translations/default/ModulesWirepaymentShop.xlf
  translations/default/ShopFormsLabels.xlf
  translations/default/ShopNotificationsError.xlf
  translations/default/ShopPdf.xlf
  translations/default/ShopThemeActions.xlf
  translations/default/ShopThemeCatalog.xlf
  translations/default/ShopThemeCheckout.xlf
  translations/default/ShopThemeCustomeraccount.xlf
  translations/default/ShopThemeGlobal.xlf
  translations/default/messages.xlf
Labels: Improvement, Wording ✔️, 8.1.x

#36345 Update default catalog 8.1.x
  translations/default/AdminCatalogNotification.xlf
Labels: Improvement, 8.1.x

#36272 Fix compatibility error on ARM processors when installing via docker
  docker-compose.yml
Labels: QA ✔️

#36026 Attribute group list is sorted by position
  admin-dev/themes/new-theme/js/components/grid/extension/position-extension.ts
  admin-dev/themes/new-theme/scss/components/_grid.scss
  admin-dev/themes/new-theme/scss/config/_keyframes.scss
  src/Core/Search/Filters/AttributeGroupFilters.php
Labels: QA ✔️, develop, Bug fix

#36160 Follow symlinks for traductions - Deployer best practice
  src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php
Labels: QA ✔️, develop, Bug fix

#36381 [UI] Size, weight, group access for Carrier form
  classes/Carrier.php
  src/Adapter/Carrier/CommandHandler/EditCarrierHandler.php
  src/Adapter/Carrier/Repository/CarrierRepository.php
  src/Core/Domain/Carrier/Command/AddCarrierCommand.php
  src/Core/Domain/Carrier/Command/EditCarrierCommand.php
  src/Core/Domain/Carrier/QueryResult/EditableCarrier.php
  src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/CarrierFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Improve/Shipping/Carrier/CarrierType.php
  src/PrestaShopBundle/Form/Admin/Improve/Shipping/Carrier/GeneralSettings.php
  src/PrestaShopBundle/Form/Admin/Improve/Shipping/Carrier/SizeWeightSettings.php
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/CarrierFormDataProviderTest.php
Labels: Waiting for wording

#36383 Functional Tests : New products block module - BO header buttons
  tests/UI/campaigns/modules/ps_newproducts/01_installation/04_resetModule.ts
  tests/UI/campaigns/modules/ps_newproducts/01_installation/05_disableEnableModule.ts
  tests/UI/campaigns/modules/ps_newproducts/02_configuration/02_boHeaderButtons.ts
  tests/UI/campaigns/modules/ps_newproducts/02_configuration/03_configureSettingsNumberOfDays.ts
  tests/UI/package-lock.json
  tests/UI/pages/BO/modules/psNewProducts/index.ts
Labels: QA ✔️, TE, E2E Tests

#36389 Improve Carrier management behat tests
  tests/Integration/Behaviour/Features/Scenario/Carrier/carrier_management.feature
  tests/Integration/Behaviour/behat.yml
Labels: Improvement, Waiting for QA, develop

#36393 Functional Tests : BO - Shop Parameters - Search : Blacklisted words
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/01_search/01_CRUDSearch.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/01_search/01_editSearchSettings/03_fuzzySearch.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/01_search/01_editSearchSettings/06_blacklistedWords.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/01_search/02_filterSortPaginationAndBulkActions.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/01_search/03_quickEditStatus.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/02_tags/01_CRUDTag.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/02_tags/02_filterSortAndPagination.ts
  tests/UI/package-lock.json
  tests/UI/pages/BO/shopParameters/search/index.ts
Labels: QA ✔️, TE, develop, E2E Tests

#36394 Merge `8.1.x` into `develop`
  admin-dev/themes/new-theme/js/app/utils/init-components.ts
  admin-dev/themes/new-theme/js/pages/product/edit/manager/related-products-manager.ts
  controllers/front/ProductController.php
  src/Core/Grid/Definition/Factory/ProductGridDefinitionFactory.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products/product.yml
Labels: Improvement, Waiting for QA, develop

#36363 Update Changelog for 8.1.7 release
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: Improvement, 8.1.x

#36171 View templatesRemove email "Preview" from BO section "Statutes" (because it's not working)
  admin-dev/themes/default/template/controllers/statuses/helpers/form/form.tpl
  js/admin.js
Labels: Improvement, QA ✔️, PM ✔️, 8.1.x

#36416 Functional Tests : Wishlist module - Help header buttons
  tests/UI/campaigns/modules/blockwishlist/02_configuration/04_helpHeaderButtons.ts
  tests/UI/package-lock.json
Labels: QA ✔️, TE, E2E Tests

#36320 Use v8 documentation in CMS Page (HelperCard)
  src/PrestaShopBundle/Resources/config/services/core/util/helper_card.yml
Labels: Improvement, QA ✔️, develop

#36353 Update API Platform to version 3.3
  composer.json
  composer.lock
  tests/Integration/ApiPlatform/EndPoint/ApiClientEndpointTest.php
  tests/Integration/ApiPlatform/EndPoint/ApiTestCase.php
  tests/Integration/ApiPlatform/EndPoint/LanguageEndpointTest.php
Labels: Improvement, Waiting for QA, develop

#36357 Load parent assets in shop selector iframe page
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/shops.html.twig
Labels: QA ✔️, develop, Bug fix

#36233 Remove doctrine command from install process
  install-dev/data/db_structure.sql
  src/PrestaShopBundle/Command/UpdateSchemaCommand.php
  src/PrestaShopBundle/Entity/ImageType.php
  src/PrestaShopBundle/Entity/Mutation.php
  src/PrestaShopBundle/Entity/ProductDownload.php
  src/PrestaShopBundle/Entity/ShopUrl.php
  src/PrestaShopBundle/Entity/Translation.php
  src/PrestaShopBundle/Install/Install.php
  src/PrestaShopBundle/Resources/config/services/bundle/cache.yml
  src/PrestaShopBundle/Service/Cache/Refresh.php
  src/PrestaShopBundle/Service/Database/Upgrade.php
  tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php
Labels: Improvement, QA ✔️, develop, BC break, Needs documentation, Needs autoupgrade PR

#36348 Finalize login page migration
  admin-dev/themes/default/template/controllers/login/content.tpl
  admin-dev/themes/default/template/controllers/login/header.tpl
  admin-dev/themes/default/template/controllers/login/index.php
  admin-dev/themes/new-theme/js/app/utils/init-components.ts
  admin-dev/themes/new-theme/js/components/components-map.ts
  admin-dev/themes/new-theme/js/components/email-input.ts
  admin-dev/themes/new-theme/js/pages/login/index.ts
  admin-dev/themes/new-theme/js/pages/login/login-map.ts
  admin-dev/themes/new-theme/package-lock.json
  admin-dev/themes/new-theme/package.json
  admin-dev/themes/new-theme/scss/pages/login/login.scss
  classes/ConfigurationTest.php
  classes/controller/AdminController.php
  classes/shop/Shop.php
  controllers/admin/AdminLoginController.php
  install-dev/data/xml/hook.xml
  js/admin/login.js
  src/Adapter/Configuration.php
  src/Adapter/Profile/Employee/CommandHandler/AbstractEmployeeHandler.php
  src/Adapter/Profile/Employee/CommandHandler/AddEmployeeHandler.php
  src/Adapter/Profile/Employee/CommandHandler/EditEmployeeHandler.php
  src/Core/Context/LegacyControllerContextBuilder.php
  src/Core/Domain/Employee/Exception/EmployeeConstraintException.php
  src/Core/QuickAccess/QuickAccessGenerator.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php
  src/PrestaShopBundle/Controller/Admin/LoginController.php
  src/PrestaShopBundle/EventListener/Admin/Context/CountryContextListener.php
  src/PrestaShopBundle/EventListener/Admin/Context/CurrencyContextListener.php
  src/PrestaShopBundle/EventListener/Admin/Context/EmployeeContextListener.php
  src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Employee/EmployeeType.php
  src/PrestaShopBundle/Form/Admin/Login/LoginType.php
  src/PrestaShopBundle/Form/Admin/Login/RequestPasswordResetType.php
  src/PrestaShopBundle/Form/Admin/Type/EmailType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/quick_access.yml
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/employee_dropdown.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Component/LegacyLayout/employee_dropdown.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Error/error403.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Error/error404.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Layout/login_layout.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Login/required_actions.html.twig
  src/PrestaShopBundle/Routing/LegacyRouterChecker.php
  src/PrestaShopBundle/Security/Admin/EmployeePasswordResetter.php
  src/PrestaShopBundle/Security/Admin/Exception/PasswordResetTemporarilyBlockedException.php
  src/PrestaShopBundle/Security/Admin/Exception/PendingPasswordResetExistingException.php
  src/PrestaShopBundle/Twig/Component/HeadTag.php
  src/PrestaShopBundle/Twig/Component/Legacy/LegacyHeadTag.php
  src/PrestaShopBundle/Twig/Layout/PrestaShopLayoutGlobalVariables.php
  src/PrestaShopBundle/Twig/Layout/SmartyVariablesFiller.php
  tests/Integration/Behaviour/Features/Context/Domain/EmployeeFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Employee/employee_management.feature
  tests/Integration/Classes/controller/AdminControllerTest.php
  tests/UI/tools/urls.ts
  tests/Unit/Core/Context/LegacyControllerContextBuilderTest.php
  tests/Unit/PrestaShopBundle/EventListener/Admin/Context/EmployeeContextListenerTest.php
Labels: QA ✔️, develop, Feature, BC break, Needs autoupgrade PR

#36431 Functional Tests : Faceted search module - Uninstall and install module
  tests/UI/campaigns/functional/BO/03_catalog/01_products/18_seoTab.ts
  tests/UI/campaigns/functional/BO/03_catalog/01_products/19_optionsTab.ts
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/02_CRUDCategoryInBO.ts
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/08_editHomeCategory.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/13_checkProductImageFormat.ts
  tests/UI/campaigns/functional/BO/08_design/06_imageSettings/14_checkCategoryImageFormat.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/04_pagination/01_updateNumberOfProductsPerPage.ts
  tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/04_pagination/02_updateDefaultProductsOrder.ts
  tests/UI/campaigns/functional/FO/classic/06_homePage/02_displaySomeProducts.ts
  tests/UI/campaigns/functional/FO/classic/06_homePage/03_allProducts.ts
  tests/UI/campaigns/functional/FO/classic/06_homePage/04_productQuickView.ts
  tests/UI/campaigns/functional/FO/classic/08_menuAndNavigation/01_navigateInCategories/02_breadcrumb.ts
  tests/UI/campaigns/functional/FO/classic/08_menuAndNavigation/01_navigateInCategories/03_sideBlockCategories.ts
  tests/UI/campaigns/functional/FO/classic/08_menuAndNavigation/02_sortAndFilter/01_sortProducts.ts
  tests/UI/campaigns/functional/FO/classic/08_menuAndNavigation/02_sortAndFilter/02_filterProducts.ts
  tests/UI/campaigns/functional/FO/classic/08_menuAndNavigation/02_sortAndFilter/03_clearOneFilter.ts
  tests/UI/campaigns/functional/FO/classic/08_menuAndNavigation/03_navigationAndDisplay/02_pagination.ts
  tests/UI/campaigns/functional/FO/classic/09_productPage/02_productPage/01_addToCart.ts
  tests/UI/campaigns/functional/FO/classic/09_productPage/02_productPage/10_displayDiscount.ts
  tests/UI/campaigns/functional/FO/classic/09_productPage/02_productPage/12_displayTag.ts
  tests/UI/campaigns/functional/FO/classic/09_productPage/02_productPage/13_displayOnSaleLabel.ts
  tests/UI/campaigns/functional/FO/classic/12_orderConfirmation/04_popularProduct.ts
  tests/UI/campaigns/functional/FO/hummingbird/06_homePage/02_displaySomeProducts.ts
  tests/UI/campaigns/functional/FO/hummingbird/06_homePage/03_allProducts.ts
  tests/UI/campaigns/functional/FO/hummingbird/06_homePage/04_productQuickView.ts
  tests/UI/campaigns/functional/FO/hummingbird/08_menuAndNavigation/01_navigateInCategories/02_breadcrumb.ts
  tests/UI/campaigns/functional/FO/hummingbird/08_menuAndNavigation/01_navigateInCategories/03_sideBlockCategories.ts
  tests/UI/campaigns/functional/FO/hummingbird/08_menuAndNavigation/02_sortAndFilter/01_sortProducts.ts
  tests/UI/campaigns/functional/FO/hummingbird/08_menuAndNavigation/02_sortAndFilter/02_filterProducts.ts
  tests/UI/campaigns/functional/FO/hummingbird/08_menuAndNavigation/02_sortAndFilter/03_clearFilters.ts
  tests/UI/campaigns/functional/FO/hummingbird/08_menuAndNavigation/03_navigationAndDisplay/02_pagination.ts
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/02_productPage/11_displayTag.ts
  tests/UI/campaigns/functional/FO/hummingbird/09_productPage/02_productPage/12_displayOnSaleLabel.ts
  tests/UI/campaigns/functional/FO/hummingbird/12_orderConfirmation/04_popularProduct.ts
  tests/UI/campaigns/modules/ps_emailalerts/01_installation/01_uninstallAndInstallModule.ts
  tests/UI/campaigns/modules/ps_emailalerts/01_installation/03_uninstallAndDeleteModule.ts
  tests/UI/campaigns/modules/ps_facetedsearch/01_installation/02_uninstallAndInstallModule.ts
  tests/UI/campaigns/modules/ps_facetedsearch/01_installation/03_disableEnableModule.ts
  tests/UI/campaigns/modules/ps_facetedsearch/01_installation/04_uninstallAndDeleteModule.ts
  tests/UI/campaigns/modules/ps_facetedsearch/02_configuration/14_editTemplateProductStockFilter.ts
  tests/UI/campaigns/modules/ps_facetedsearch/02_configuration/15_editTemplateProductBrandFilter.ts
  tests/UI/campaigns/modules/ps_facetedsearch/02_configuration/18_editTemplatePaperTypeFilter.ts
  tests/UI/campaigns/sanity/04_catalogFO/01_filterProducts.ts
  tests/UI/package-lock.json
  tests/UI/pages/FO/classic/category/index.ts
  tests/UI/pages/FO/hummingbird/category/index.ts
Labels: QA ✔️, TE, E2E Tests

#36359 Match URLs with a trailing slash
  classes/Dispatcher.php
Labels: Improvement, QA ✔️, 8.1.x

#36437 Update Pull Request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improvement, QA ✔️, develop

#35465 Order accessories by name
  classes/Product.php
Labels: Improvement, QA ✔️, PM ✔️

#36433 Fix addJs/addCss on migrated pages with Symfony layout
  src/Core/Context/LegacyControllerContextBuilder.php
  src/Core/Context/LegacyControllerContextInjector.php
  src/PrestaShopBundle/Resources/config/services/core/context.yml
  tests/Unit/Core/Context/LegacyControllerContextBuilderTest.php
  tests/Unit/PrestaShopBundle/EventListener/Admin/Context/LegacyControllerContextListenerTest.php
Labels: QA ✔️, develop, Bug fix

#36408 Decouple cart presenter into lazy array
  controllers/front/CartController.php
  src/Adapter/Presenter/AbstractLazyArray.php
  src/Adapter/Presenter/Cart/CartLazyArray.php
  src/Adapter/Presenter/Cart/CartPresenter.php
Labels: Improvement, develop
