Repository PrestaShop/PrestaShop, pull requests merged in 2024-08, with the labels that each got.

#36172 input type "number" is not styled properly
  admin-dev/themes/default/scss/partials/_content.scss
  admin-dev/themes/default/scss/partials/_forms.scss
  admin-dev/themes/default/scss/vendor/bootstrap-sass/_forms.scss
Labels: Improvement, QA ✔️, 8.1.x

#36659 Functional tests - Add new test to edit official and unofficial currency
  tests/UI/campaigns/cldr/03_deleteCurrency.ts
  tests/UI/campaigns/cldr/04_searchCurrencyByISOCode.ts
  tests/UI/campaigns/cldr/05_searchCurrencyByEnableDisable.ts
  tests/UI/campaigns/cldr/07_editSymbolFormatCurrency.ts
  tests/UI/campaigns/cldr/08_resetSymbolFormatSettings.ts
  tests/UI/campaigns/cldr/09_enableDisableCurrency.ts
  tests/UI/campaigns/functional/BO/11_international/01_localization/01_localization/01_importLocalizationPack.ts
  tests/UI/campaigns/functional/BO/11_international/01_localization/01_localization/07_defaultCurrency.ts
  tests/UI/campaigns/functional/BO/11_international/01_localization/03_currencies/01_createOfficialCurrency.ts
  tests/UI/campaigns/functional/BO/11_international/01_localization/03_currencies/02_createUnofficialCurrency.ts
  tests/UI/campaigns/functional/BO/11_international/01_localization/03_currencies/03_helpButton.ts
  tests/UI/campaigns/functional/BO/11_international/01_localization/03_currencies/04_updateExchangeRate.ts
  tests/UI/campaigns/functional/BO/11_international/01_localization/03_currencies/05_filterSortAndPagination.ts
  tests/UI/campaigns/functional/BO/11_international/01_localization/03_currencies/06_editOfficialAndUnofficialCurrency.ts
  tests/UI/campaigns/functional/FO/classic/02_headerAndFooter/03_changeCurrency.ts
  tests/UI/campaigns/functional/FO/hummingbird/02_headerAndFooter/03_changeCurrency.ts
  tests/UI/campaigns/regression/currencies/computingPrecision_FO.ts
  tests/UI/commonTests/BO/international/currency.ts
  tests/UI/package-lock.json
  tests/UI/pages/BO/international/currencies/add.ts
  tests/UI/pages/BO/international/currencies/index.ts
Labels: QA ✔️, TE, E2E Tests

#36676 Update UI testing library to work on Mac OS
  tests/UI/package-lock.json
Labels: QA ✔️, develop, Bug fix

#36681 Update UI testing library to be compatible with reskin
  tests/UI/package-lock.json
Labels: Improvement, develop

#36683 Merge 81x to develop 06/08/24
  admin-dev/themes/default/scss/partials/_content.scss
  admin-dev/themes/default/scss/partials/_forms.scss
  admin-dev/themes/default/scss/vendor/bootstrap-sass/_forms.scss
Labels: Improvement, develop

#36585 Renew PrestaShop installer branding
  install-dev/theme/fonts/IBMPlexSans-Bold.ttf
  install-dev/theme/fonts/IBMPlexSans-Regular.ttf
  install-dev/theme/fonts/Prestafont-Regular.woff
  install-dev/theme/img/check_circle.svg
  install-dev/theme/img/empty.svg
  install-dev/theme/img/error.svg
  install-dev/theme/img/info.svg
  install-dev/theme/img/nok.svg
  install-dev/theme/img/ok.svg
  install-dev/theme/img/prestashop_logo.svg
  install-dev/theme/img/success.svg
  install-dev/theme/img/sync.svg
  install-dev/theme/img/unfold_more_24px.svg
  install-dev/theme/img/warning.svg
  install-dev/theme/js/configure.js
  install-dev/theme/rtl.css
  install-dev/theme/view.css
  install-dev/theme/views/configure.php
  install-dev/theme/views/content.php
  install-dev/theme/views/database.php
  install-dev/theme/views/header.php
  install-dev/theme/views/layout.php
  install-dev/theme/views/license.php
  install-dev/theme/views/process.php
  install-dev/theme/views/system.php
  tools/build/Library/InstallUnpacker/content/IBMPlexSans-Regular.ttf
  tools/build/Library/InstallUnpacker/content/OpenSans-Regular.ttf
  tools/build/Library/InstallUnpacker/content/installer-static.png
  tools/build/Library/InstallUnpacker/content/installer.gif
  tools/build/Library/InstallUnpacker/content/style.css
  tools/build/Library/InstallUnpacker/index_template.php
Labels: QA ✔️, develop, Feature

#36664 Use attribute public name instead of private name in URL anchors -- r…
  classes/Product.php
Labels: QA ✔️, Bug fix, 8.1.x

#36653 Fix missing id_address_delivery to fix #35190
  src/Adapter/Cart/QueryHandler/GetCartForViewingHandler.php
Labels: QA ✔️, develop, Bug fix

#36706 Clean legacy links part 5
  classes/lang/KeysReference/FeatureFlagLang.php
  install-dev/data/xml/feature_flag.xml
  src/PrestaShopBundle/Command/LegacyLinkLinterCommand.php
  src/PrestaShopBundle/Command/SecurityAttributeLinterCommand.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/shop_parameters/customer_groups.yml
  src/PrestaShopBundle/Resources/config/routing/admin/configure/shop_parameters/search_preferences.yml
  src/PrestaShopBundle/Resources/config/routing/admin/configure/shop_parameters/stores.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/design/_mail_theme_deprecated.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/design/mail_theme.yml
  src/PrestaShopBundle/Resources/config/routing/admin/improve/shipping/carriers.yml
Labels: Improvement, Waiting for wording, develop, BC break, Needs autoupgrade PR

#36718 Clean all missing legacy links
  .github/workflows/lint.yml
  classes/lang/KeysReference/FeatureFlagLang.php
  install-dev/data/xml/feature_flag.xml
  install-dev/data/xml/tab.xml
  src/PrestaShopBundle/Command/LegacyLinkLinterCommand.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/admin_api.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/cart_rule.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/features.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/customer_service/merchandise_return.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/carts.yml
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
  src/PrestaShopBundle/Routing/Linter/LegacyLinkLinter.php
Labels: Improvement, Waiting for wording, develop, Needs autoupgrade PR

#36725 Compressed unzip wizard GIF animation
  tools/build/Library/InstallUnpacker/content/installer.gif
Labels: Improvement, develop

#36576 Mail - Reply-To can be the same as the To address (spam indicator - negative points)
  classes/Mail.php
Labels: Improvement, 8.1.x

#36287 Fix for issue 2 of Problems with Product Customizations
  classes/Cart.php
  classes/Product.php
  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
  src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php
  src/Adapter/Order/OrderAmountUpdater.php
  src/Adapter/Order/OrderDetailUpdater.php
  src/Adapter/Product/PriceCalculator.php
  src/Core/Cart/CartRow.php
Labels: QA ✔️, Bug fix, 8.1.x

#36726 Add possiblity to customize the installer based on template from a module
  install-dev/classes/controllerHttp.php
Labels: Improvement, QA ✔️, develop

#36746 fix: remove required tax rule when freeshipping is enabled
  admin-dev/themes/new-theme/js/pages/carrier/form/carrier-form-manager.ts
Labels: develop, Bug fix

#36750 fix: add missing import for checkbox selection
  admin-dev/themes/new-theme/js/pages/carrier/form/index.ts
Labels: QA ✔️, develop, Bug fix

#36656 Clean behat scenarios with new carrier steps
  src/Adapter/Carrier/CommandHandler/AddCarrierHandler.php
  src/Adapter/Carrier/QueryHandler/GetCarrierForEditingHandler.php
  src/Adapter/Carrier/Repository/CarrierRangeRepository.php
  src/Adapter/Carrier/Repository/CarrierRepository.php
  src/Adapter/Cart/CommandHandler/UpdateCartCarrierHandler.php
  src/Core/Domain/Carrier/Command/AddCarrierCommand.php
  src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php
  tests/Integration/Behaviour/Features/Context/CarrierFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Carrier/CarrierFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Carrier/CarrierRangesFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Carrier/CarrierTaxRuleGroupFeatureContext.php
  tests/Integration/Behaviour/Features/Context/TaxFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Carrier/Ranges/carrier_ranges.feature
  tests/Integration/Behaviour/Features/Scenario/Carrier/carrier_management.feature
  tests/Integration/Behaviour/Features/Scenario/Carrier/carrier_tax_rule_group_management.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/CartRule/FrontOffice/Restrictions/cart_rule_carrier_restriction.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/CartRule/FrontOffice/Restrictions/cart_rule_country_restriction.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/CartRule/FrontOffice/carrier.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/CartRule/FrontOffice/cart_rule_validation.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/CartRule/FrontOffice/ecotax.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/carrier.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/cart_to_order.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/delivery_options.feature
  tests/Integration/Behaviour/Features/Scenario/Cart/tax.feature
  tests/Integration/Behaviour/Features/Scenario/CartRule/set_carrier_restrictions.feature
  tests/Integration/Behaviour/Features/Scenario/CartRule/set_mixed_cart_rule_restrictions.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_address.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_cart_rules.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_currency.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_cartrule.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_combination.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_odd_tax.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_with_tax.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_fixed_product_prices.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_french_tax.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_odd_tax.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_rounding_type.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_shipping.feature
  tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/duplicate_product_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/Shop/update_shipping_multishop.feature
  tests/Integration/Behaviour/Features/Scenario/Product/bulk_duplicate_product.feature
  tests/Integration/Behaviour/Features/Scenario/Product/duplicate_product.feature
  tests/Integration/Behaviour/Features/Scenario/Product/update_shipping.feature
  tests/Integration/Behaviour/behat.yml
Labels: develop, Refactoring

#36749 Fix `Image::getCover` & `Image::getGlobalCover` PHPDoc
  classes/Image.php
Labels: Waiting for QA, develop, Refactoring

#36762 Functional Tests : Added nightly for 8.2.x
  .github/workflows/cron_nightly_build.yml
  .github/workflows/cron_nightly_tests_8.2.x.yml
Labels: QA ✔️, TE, E2E Tests

#36761 Update PULL_REQUEST_TEMPLATE.md to acknowledge 8.2.x
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improvement, develop

#36763 Nightly : Fixed 8.2.x
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: QA ✔️, TE, E2E Tests

#36662 Cast OrderProductForViewing - location to string for Memcached
  classes/order/Order.php
Labels: QA ✔️, Bug fix

#36764 Version number 8.2.0
  install-dev/install_version.php
  src/Core/Version.php
Labels: Improvement

#36733 Replace Puffing logo in Symfony debug bar
  admin-dev/themes/new-theme/img/glyph.png
Labels: QA ✔️, develop, Bug fix

#36236 Update iframe-modal.ts DOM text reinterpreted as HTML
  admin-dev/themes/new-theme/js/components/modal/iframe-modal.ts
Labels: Improvement, QA ✔️, develop

#36772 Fix button style issue inside alerts for default theme
  admin-dev/themes/default/scss/partials/_alerts.scss
Labels: QA ✔️, develop, Bug fix

#36673 Screenshot on each steps in UI tests
  .github/actions/ui-test/action.yml
  tests/UI/.env.ci
  tests/UI/.env.local
  tests/UI/package-lock.json
  tests/UI/pages/FO/classic/checkout/index.ts
  tests/UI/types/global.d.ts
  tests/UI/utils/globals.ts
  tests/UI/utils/setup.ts
Labels: develop, Bug fix

#36714 Order modules on translation page alphabetically
  src/Core/Form/ChoiceProvider/ModuleByNameChoiceProvider.php
Labels: Improvement, QA ✔️, 8.2.x

#36730 Automatically generate no image thumbnails
  img/noimageavailable.jpg
  src/Adapter/Image/ImageRetriever.php
  src/Adapter/ImageThumbnailsRegenerator.php
Labels: QA ✔️, develop, Bug fix

#36777 Nightly : Push report for 8.2.x
  .github/workflows/cron_nightly_tests_reports.yml
Labels: QA ✔️, TE, E2E Tests

#36782 Remove unused lines
  classes/order/OrderHistory.php
Labels: QA ✔️, develop, Refactoring
