Repository PrestaShop/PrestaShop, pull requests merged in 2025-03, with the labels that each got.

#38046 Feat: add entities for multi-shipment
  install-dev/data/db_structure.sql
  src/PrestaShopBundle/Entity/Shipment.php
  src/PrestaShopBundle/Entity/ShipmentProduct.php
  tests/Unit/PrestaShopBundle/Entity/ShipmentTest.php
Labels: Waiting for author, Waiting for QA, develop, Feature, PR Autoupgrade opened ✔️

#36374 PR - Fix order detail price re-calculation
  src/Adapter/Order/OrderDetailUpdater.php
Labels: QA ✔️, develop, Bug fix

#38156 Fix legacy context initialisation inconsistencies
  app/config/admin/services.yml
  phpstan-baseline.neon
  src/Core/Context/CountryContextBuilder.php
  src/Core/Context/CurrencyContextBuilder.php
  src/Core/Context/EmployeeContextBuilder.php
  src/Core/Context/LanguageContextBuilder.php
  src/Core/Context/LegacyObjectCheckerTrait.php
  src/Core/Context/ShopContextBuilder.php
  src/PrestaShopBundle/EventListener/Admin/Context/LegacyContextSubscriber.php
  src/PrestaShopBundle/Service/DataProvider/UserProvider.php
  tests/Unit/Core/Context/LanguageContextBuilderTest.php
Labels: QA ✔️, Bug fix, 9.0.x

#37961 Search Tab with case sensitive matching
  app/config/doctrine.yml
  src/PrestaShopBundle/Entity/Repository/TabRepository.php
Labels: QA ✔️, Bug fix, 9.0.x

#38202 Detail development possibilities for trusted proxies
  .env
Labels: Improvement, Waiting for QA, 9.0.x

#38168 Category::getParentsCategories fix with multiple root categories
  classes/Category.php
Labels: QA ✔️, Bug fix, 8.2.x

#38157 Fix: Issue with multilingual translations
  src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php
Labels: QA ✔️, Bug fix, 8.2.x

#38136 Fix: Issue with JS and CSS cache clearing in multishop context
  classes/Media.php
Labels: QA ✔️, Bug fix, 8.2.x

#38112 Fix: header positioning
  admin-dev/themes/default/scss/partials/_header.scss
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
Labels: QA ✔️, Bug fix, 9.0.x

#38198 Functional Tests : Enable after #22581
  tests/UI/campaigns/modules/07_ps_apiresources/01_installation/02_disableEnableModule.ts
Labels: QA ✔️, TE, E2E Tests

#38205 Functional Tests : Stabilisation "functional:BO:catalog:07-08"
  tests/UI/campaigns/functional/BO/03_catalog/08_stocks/07_filterStocksByCategories.ts
  tests/UI/package-lock.json
Labels: QA ✔️, develop, Refactoring

#38100 Fix: Cookie mechanism is broken after refactoring for 9.0.0
  src/PrestaShopBundle/EventListener/Admin/EmployeeSessionSubscriber.php
Labels: QA ✔️, Bug fix, 9.0.x

#38210 Functional Tests : Stabilisation "functional:FO:hummingbird:08-12"
  tests/UI/package-lock.json
Labels: TE, E2E Tests

#38226 Functional Tests : Stabilisation "functional:BO:shop-parameters:05-07"
  tests/UI/campaigns/functional/BO/13_shopParameters/07_search/01_search/02_filterSortPaginationAndBulkActions.ts
Labels: TE, E2E Tests

#38228 Merge `8.2.x` into `9.0.x`
  classes/Category.php
  classes/Media.php
  classes/Product.php
  controllers/admin/AdminTranslationsController.php
  localization/at.xml
  localization/be.xml
  localization/bg.xml
  localization/cy.xml
  localization/cz.xml
  localization/de.xml
  localization/dk.xml
  localization/ee.xml
  localization/es.xml
  localization/fi.xml
  localization/fr.xml
  localization/gb.xml
  localization/gr.xml
  localization/hr.xml
  localization/hu.xml
  localization/ie.xml
  localization/it.xml
  localization/lt.xml
  localization/lu.xml
  localization/lv.xml
  localization/mc.xml
  localization/mt.xml
  localization/nl.xml
  localization/pl.xml
  localization/pt.xml
  localization/ro.xml
  localization/se.xml
  localization/si.xml
  localization/sk.xml
Labels: Improvement, Waiting for QA, 9.0.x

#38230 Functional Tests : Stabilisation "functional:BO:shipping"
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/05_changePosition.ts
  tests/UI/package-lock.json
Labels: TE, E2E Tests

#38236 Functional Tests : Stabilisation "functional:FO:hummingbird:04-07"
  tests/UI/campaigns/functional/FO/hummingbird/06_homePage/04_productQuickView.ts
  tests/UI/package-lock.json
Labels: TE, E2E Tests

#38153 Load module translation catalogues for all present modules
  app/AppKernel.php
  phpstan-baseline.neon
  src/Adapter/Module/Repository/ModuleRepository.php
  src/Core/Addon/Module/ModuleManagerBuilder.php
  src/Core/Module/ModuleManager.php
  src/PrestaShopBundle/Resources/config/services/core/module.yml
  tests/Unit/Core/Module/ModuleManagerTest.php
Labels: QA ✔️, Bug fix, 9.0.x

#38243 Fixed FI taxes in localization files
  localization/at.xml
  localization/be.xml
  localization/bg.xml
  localization/cy.xml
  localization/cz.xml
  localization/de.xml
  localization/dk.xml
  localization/ee.xml
  localization/es.xml
  localization/fi.xml
  localization/fr.xml
  localization/gb.xml
  localization/gr.xml
  localization/hr.xml
  localization/hu.xml
  localization/ie.xml
  localization/it.xml
  localization/lt.xml
  localization/lu.xml
  localization/lv.xml
  localization/mc.xml
  localization/mt.xml
  localization/nl.xml
  localization/pl.xml
  localization/pt.xml
  localization/ro.xml
  localization/se.xml
  localization/si.xml
  localization/sk.xml
Labels: Bug fix, 8.2.x

#38234 Update product indexation after each update when it is needed
  src/Adapter/Product/CommandHandler/BulkUpdateProductStatusHandler.php
  src/Adapter/Product/CommandHandler/UpdateProductHandler.php
  src/Adapter/Product/Update/ProductIndexationUpdater.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/product_indexation.feature
Labels: QA ✔️, Bug fix, 8.2.x

#38191 Feat: add CQRS command for add & list shipment
  classes/PaymentModule.php
  src/Adapter/Shipment/OrderShipmentCreator.php
  src/Adapter/Shipment/QueryHandler/GetOrderShipmentsHandler.php
  src/Adapter/Shipment/QueryHandler/GetShipmentProductsHandler.php
  src/Core/Domain/Shipment/Exception/CannotAddShipmentException.php
  src/Core/Domain/Shipment/Exception/ShipmentException.php
  src/Core/Domain/Shipment/Exception/ShipmentNotFoundException.php
  src/Core/Domain/Shipment/Query/GetOrderShipments.php
  src/Core/Domain/Shipment/Query/GetShipmentProducts.php
  src/Core/Domain/Shipment/QueryHandler/GetOrderShipmentsHandlerInterface.php
  src/Core/Domain/Shipment/QueryHandler/GetShipmentProductsHandlerInterface.php
  src/Core/Domain/Shipment/QueryResult/OrderShipment.php
  src/Core/Domain/Shipment/QueryResult/OrderShipmentProduct.php
  src/Core/Domain/Shipment/ValueObject/ShipmentId.php
  src/PrestaShopBundle/Entity/Repository/ShipmentRepository.php
  src/PrestaShopBundle/Entity/Shipment.php
  src/PrestaShopBundle/Resources/config/services/adapter/common.yml
  src/PrestaShopBundle/Resources/config/services/adapter/shipment.yml
  src/PrestaShopBundle/Resources/config/services/bundle/common.yml
  src/PrestaShopBundle/Resources/config/services/bundle/repository.yml
  tests/Integration/Behaviour/Features/Context/Domain/ShipmentFeatureContext.php
  tests/Integration/Behaviour/Features/Context/FeatureFlagFeatureContext.php
  tests/Integration/Behaviour/Features/Context/OrderFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Shipment/shipment.feature
  tests/Integration/Behaviour/behat.yml
  tests/Unit/PrestaShopBundle/Entity/ShipmentTest.php
Labels: develop, Feature, Hook Contribution

#38263 Fix profiler working with arrays
  tools/profiling/Profiler.php
Labels: QA ✔️, Bug fix, 9.0.x

#38300 Functional Tests : Stabilisation "functional:BO:shop-parameters:05-07"
  tests/UI/package-lock.json
Labels: TE, E2E Tests

#38232 Improve hook generation for fixtures and documentation
  install-dev/data/xml/hook.xml
  src/Core/Hook/Extractor/HookExtractor.php
  src/PrestaShopBundle/Command/AppendConfigurationFileHooksListCommand.php
  src/PrestaShopBundle/Command/GenerateHooksDocumentationCommand.php
Labels: Improvement, 9.0.x, Needs autoupgrade PR, Hook Contribution

#38056 Added smartyRegisterFunction for file_exists and strpos.
  config/smarty.config.inc.php
Labels: QA ✔️, Bug fix, 9.0.x

#38306 Functional Tests : Bump `@prestashop-core/ui-testing`
  tests/UI/package-lock.json
Labels: TE, E2E Tests

#38303 Add missing function strpos for smarty templates
  composer.json
  composer.lock
  config/smarty.config.inc.php
Labels: QA ✔️, Bug fix, 9.0.x

#38309 Merge `8.2.x` into `9.0.x`
  localization/at.xml
  localization/be.xml
  localization/bg.xml
  localization/cy.xml
  localization/cz.xml
  localization/de.xml
  localization/dk.xml
  localization/ee.xml
  localization/es.xml
  localization/fi.xml
  localization/fr.xml
  localization/gb.xml
  localization/gr.xml
  localization/hr.xml
  localization/hu.xml
  localization/ie.xml
  localization/it.xml
  localization/lt.xml
  localization/lu.xml
  localization/lv.xml
  localization/mc.xml
  localization/mt.xml
  localization/nl.xml
  localization/pl.xml
  localization/pt.xml
  localization/ro.xml
  localization/se.xml
  localization/si.xml
  localization/sk.xml
  src/Adapter/Product/CommandHandler/UpdateProductHandler.php
  src/Adapter/Product/Update/ProductIndexationUpdater.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateProductFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Product/product_indexation.feature
Labels: Improvement, 9.0.x

#38257 Fix: Address Fields Disappear After Changing Country on Checkout Page
  themes/_core/js/address.js
Labels: QA ✔️, Bug fix, 8.2.x

#38246 Tax rule group country edition
  controllers/admin/AdminTaxRulesGroupController.php
  src/PrestaShopBundle/Command/SecurityAttributeLinterCommand.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/StateController.php
  src/PrestaShopBundle/Resources/config/routing/admin/improve/international/state.yml
Labels: QA ✔️, Bug fix, 9.0.x

#38152 Hide spinner if no ajax in progress
  js/admin.js
Labels: QA ✔️, Bug fix, 9.0.x

#38203 Remove link in help message for product stock option
  src/PrestaShopBundle/Form/Admin/Sell/Product/Stock/StockOptionsType.php
Labels: QA ✔️, Bug fix, 9.0.x

#38304 Fix mail theme scanner when used on a module folder
  src/Core/MailTemplate/FolderThemeScanner.php
  src/PrestaShopBundle/Resources/config/services/core/mail_template.yml
Labels: QA ✔️, Bug fix, 9.0.x

#38346 Functional Tests : Bump `@prestashop-core/ui-testing`
  tests/UI/package-lock.json
Labels: TE, E2E Tests

#38327 Fix actionFilterDeliveryOptionList hook Cart Param
  classes/Cart.php
Labels: Bug fix, Needs documentation, 8.2.x

#38341 Fix: product carrier delete
  classes/Carrier.php
Labels: QA ✔️, Bug fix, 8.2.x

#38262 Cast icon to string if null
  src/PrestaShopBundle/Twig/Layout/MenuBuilder.php
Labels: QA ✔️, Bug fix, 9.0.x

#38355 Fix: It is not possible to view a cart in the admin if it contains customized items
  classes/Product.php
Labels: QA ✔️

#38265 Fix and refactor category controller for non existent categories
  controllers/front/ProductController.php
  controllers/front/listing/CategoryController.php
Labels: QA ✔️, Bug fix, 9.0.x

#38349 Discount feedbacks
  classes/CartRule.php
  src/Core/FeatureFlag/FeatureFlagSettings.php
  src/Core/Form/IdentifiableObject/DataHandler/DiscountFormDataHandler.php
  src/Core/Grid/Definition/Factory/DiscountGridDefinitionFactory.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/DiscountController.php
  src/PrestaShopBundle/Form/Admin/Sell/Discount/CreateDiscountType.php
  tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Discount/DiscountFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Discount/FO/full_user_experience_test_with_two_discounts.feature
  tests/Integration/Behaviour/behat.yml
Labels: Waiting for QA, Waiting for wording, develop, Bug fix

#38235 Display the error reported by the module when the installation of PrestaShop fails because of it
  src/PrestaShopBundle/Install/Install.php
Labels: Improvement, QA ✔️, 9.0.x

#38376 Update Symfony components after 6.4.20 release
  composer.lock
Labels: Improvement, Waiting for QA, develop
