Repository PrestaShop/PrestaShop, pull requests merged in 2025-01, with the labels that each got.

#37745 Improve ShopCollection list of shop IDs in API, and test API validation
  composer.json
  composer.lock
  src/Adapter/ApiClient/CommandHandler/ForceApiClientSecretHandler.php
  src/Adapter/Product/QueryHandler/GetProductForEditingHandler.php
  src/Core/Domain/ApiClient/Command/ForceApiClientSecretCommand.php
  src/Core/Domain/ApiClient/CommandHandler/ForceApiClientSecretHandlerInterface.php
  src/Core/Domain/ApiClient/ValueObject/ApiClientSecret.php
  src/Core/Domain/Product/QueryResult/ProductForEditing.php
  src/PrestaShopBundle/ApiPlatform/ContextParametersTrait.php
  src/PrestaShopBundle/ApiPlatform/Normalizer/ShopConstraintNormalizer.php
  src/PrestaShopBundle/Command/APIClientCommand.php
  src/PrestaShopBundle/Resources/config/services/adapter/api_client.yml
  tests/Integration/ApiPlatform/Serializer/DomainSerializerTest.php
  tests/Integration/Behaviour/Features/Context/Domain/ApiClientManagementFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/ProductShopFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/ApiClient/api_client_management.feature
  tests/UI/campaigns/functional/API/02_endpoints/09_product/01_postProduct.ts
  tests/UI/campaigns/functional/API/02_endpoints/09_product/03_getProductId.ts
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProviderTest.php
Labels: Improvement, 9.0.x

#37744 [FIX] Notify autoupgrade workflow
  .github/workflows/notify_for_autoupgrade_pr_label.yml
Labels: Bug fix, 9.0.x

#37332 getCustomerOrders - in specific case incorrect sorting by date_add DESC
  classes/order/Order.php
Labels: Waiting for QA, Bug fix, Waiting for dev, 8.2.x

#37763 SymfonyCacheClearer tries multiple manual cache clear
  src/Adapter/Cache/Clearer/SymfonyCacheClearer.php
Labels: Improvement, QA ✔️, 9.0.x

#37826 Merge 8.2.x to 9.0. 15/01/25
  classes/order/Order.php
  localization/sk.xml
Labels: Improvement, 9.0.x

#37747 Add sales to manufacturer sort
  classes/Manufacturer.php
Labels: QA ✔️, Bug fix, 9.0.x

#37834 Merge 9.0.x to develop 15/01/25
  .github/workflows/notify_for_autoupgrade_pr_label.yml
  classes/Manufacturer.php
  classes/order/Order.php
  composer.json
  composer.lock
  localization/sk.xml
  src/Adapter/ApiClient/CommandHandler/ForceApiClientSecretHandler.php
  src/Adapter/Cache/Clearer/SymfonyCacheClearer.php
  src/Adapter/Product/QueryHandler/GetProductForEditingHandler.php
  src/Core/Domain/ApiClient/Command/ForceApiClientSecretCommand.php
  src/Core/Domain/ApiClient/CommandHandler/ForceApiClientSecretHandlerInterface.php
  src/Core/Domain/ApiClient/ValueObject/ApiClientSecret.php
  src/Core/Domain/Product/QueryResult/ProductForEditing.php
  src/PrestaShopBundle/ApiPlatform/ContextParametersTrait.php
  src/PrestaShopBundle/ApiPlatform/Normalizer/ShopConstraintNormalizer.php
  src/PrestaShopBundle/Command/APIClientCommand.php
  src/PrestaShopBundle/Resources/config/services/adapter/api_client.yml
  tests/Integration/ApiPlatform/Serializer/DomainSerializerTest.php
  tests/Integration/Behaviour/Features/Context/Domain/ApiClientManagementFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Product/ProductShopFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/ApiClient/api_client_management.feature
  tests/UI/campaigns/audit/BO/12_shopParameters.ts
  tests/UI/campaigns/functional/API/02_endpoints/04_customerGroup/01_postCustomersGroup.ts
  tests/UI/campaigns/functional/API/02_endpoints/06_language/01_getLanguages.ts
  tests/UI/campaigns/functional/API/02_endpoints/09_product/01_postProduct.ts
  tests/UI/campaigns/functional/API/02_endpoints/09_product/03_getProductId.ts
  tests/UI/campaigns/functional/BO/11_international/01_localization/02_languages/01_filterAndQuickEditLanguages.ts
  tests/UI/campaigns/functional/BO/11_international/01_localization/02_languages/04_sortAndPagination.ts
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProviderTest.php
Labels: Improvement, develop

#37845 Nightly : Fixed `functional/BO/00*/04*`
  .github/workflows/cron_nightly_tests_reusable.yml
  tests/UI/campaigns/functional/BO/00_login/04_checkLinks.ts
Labels: QA ✔️, TE, E2E Tests

#37819 Fix: BO > Carriers - Exception thrown Carrier cannot be both shipping handling and free
  src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php
Labels: QA ✔️, Bug fix, 9.0.x

#37717 Fix: Problem with shop association component
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
Labels: QA ✔️

#37818 Fix: BO > Carriers - Exception thrown Invalid Carrier url. Got "@"
  src/PrestaShopBundle/Form/Admin/Improve/Shipping/Carrier/GeneralSettings.php
Labels: QA ✔️, Waiting for wording, Bug fix, 9.0.x

#37860 Functional Tests : `actions/upload-artifact@v4` doesn't support colon
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: QA ✔️, TE, E2E Tests

#37862 `8.2.x` : Use Ubuntu 22.04
  .github/workflows/sanity-productV2.yml
  .github/workflows/sanity.yml
  .github/workflows/ui_tests_code_checks.yml
Labels: QA ✔️, TE, E2E Tests

#37867 Nightly : Define Ubuntu Version for 8.1.x & 8.2.x
  .github/workflows/cron_nightly_tests_8.1.x.yml
  .github/workflows/cron_nightly_tests_8.2.x.yml
  .github/workflows/cron_nightly_tests_reusable.yml
Labels: QA ✔️, TE, E2E Tests

#37866 `8.1.x` : Use Ubuntu 22.04
  .github/workflows/sanity-productV2.yml
  .github/workflows/sanity.yml
  .github/workflows/ui_tests_code_checks.yml
Labels: TE, E2E Tests, 8.1.x

#37870 Nightly : Improved `functionals/BO/00*/04*`
  tests/UI/campaigns/functional/BO/00_login/04_checkLinks.ts
Labels: TE, E2E Tests

#37771 Improve constraint on Product description
  src/PrestaShopBundle/Form/Admin/Sell/Product/Description/DescriptionType.php
Labels: QA ✔️, Bug fix, 8.2.x

#37876 Downgrade lockfileVersion of themes package-lock.json files
  admin-dev/themes/default/package-lock.json
  admin-dev/themes/new-theme/package-lock.json
  themes/package-lock.json
  themes/package.json
Labels: Bug fix, 8.2.x

#37803 Fix multistore disabling
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/General/PreferencesType.php
Labels: QA ✔️, Bug fix, 8.2.x

#36086 Improve Admin API doc generation
  app/config/admin/config.yml
  composer.json
  composer.lock
  src/PrestaShopBundle/ApiPlatform/ContextParametersProvider.php
  src/PrestaShopBundle/ApiPlatform/LocalizedValueUpdater.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSCommand.php
  src/PrestaShopBundle/ApiPlatform/Metadata/LocalizedValue.php
  src/PrestaShopBundle/ApiPlatform/Metadata/Property/Factory/CQRSConstructorPropertyMetadataFactory.php
  src/PrestaShopBundle/ApiPlatform/NormalizationMapper.php
  src/PrestaShopBundle/ApiPlatform/Normalizer/CQRSApiNormalizer.php
  src/PrestaShopBundle/ApiPlatform/Normalizer/DateTimeImmutableNormalizer.php
  src/PrestaShopBundle/ApiPlatform/Normalizer/DecimalNumberNormalizer.php
  src/PrestaShopBundle/ApiPlatform/Normalizer/ShopConstraintNormalizer.php
  src/PrestaShopBundle/ApiPlatform/Normalizer/UploadedFileNormalizer.php
  src/PrestaShopBundle/ApiPlatform/Normalizer/ValueObjectNormalizer.php
  src/PrestaShopBundle/ApiPlatform/OpenApi/Factory/CQRSOpenApiFactory.php
  src/PrestaShopBundle/ApiPlatform/Processor/CommandProcessor.php
  src/PrestaShopBundle/ApiPlatform/Provider/QueryListProvider.php
  src/PrestaShopBundle/ApiPlatform/Provider/QueryProvider.php
  src/PrestaShopBundle/ApiPlatform/QueryResultSerializerTrait.php
  src/PrestaShopBundle/ApiPlatform/Serializer/CQRSApiSerializer.php
  src/PrestaShopBundle/ApiPlatform/Validator/CQRSApiValidator.php
  src/PrestaShopBundle/DependencyInjection/Compiler/CommandAndQueryCollectorPass.php
  src/PrestaShopBundle/Resources/config/services/bundle/api_platform.yml
  src/PrestaShopBundle/Resources/config/services/bundle/open_api.yml
  src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/AdminAPI/index.html.twig
  tests/Integration/ApiPlatform/Serializer/CQRSApiSerializerTest.php
  tests/Integration/PrestaShopBundle/ApiPlatform/CQRSOpenApiFactoryTest.php
  tests/Resources/config/services.yml
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSCommandTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSCreateTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSPartialUpdateTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSUpdateTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/StateProvider/QueryProviderTest.php
Labels: Improvement, Waiting for wording, 9.0.x

#37828 Add URL Validation when installing theme from URL
  classes/Tools.php
Labels: Improvement, QA ✔️, 8.2.x

#37887 fix: #37886 - [docker-compose] - upgrade node 14 to 16
  .github/workflows/cron_nightly_tests.yml
  .github/workflows/sanity-productV2.yml
  .github/workflows/sanity.yml
  admin-dev/themes/default/package-lock.json
  admin-dev/themes/new-theme/package-lock.json
  docker-compose.yml
  themes/package-lock.json
Labels: Waiting for QA, Bug fix, 8.2.x

#37849 Fix issue with count on string
  src/Adapter/Presenter/Product/ProductListingLazyArray.php
Labels: QA ✔️, Bug fix, 8.2.x

#37888 Fix: BO > Order details page - When changing pagination, Refunded column displays automatically
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig
Labels: QA ✔️, Bug fix, 8.2.x

#37882 Fix: BO - Product Page - Display all features in feature choice, even if two features have the same name
  src/Adapter/Form/ChoiceProvider/FeaturesChoiceProvider.php
Labels: QA ✔️, develop, Bug fix, Topwatchers

#37907 chore: [release-8.2.1] - update version number to 8.2.1
  install-dev/install_version.php
  src/Core/Version.php
Labels: Improvement, Waiting for author, 8.2.x

#37908 Clean JS errors between each steps in UI tests
  tests/UI/campaigns/audit/BO/01_dashboard.ts
  tests/UI/campaigns/audit/BO/02_orders.ts
  tests/UI/campaigns/audit/BO/03_catalog.ts
  tests/UI/campaigns/audit/BO/04_customers.ts
  tests/UI/campaigns/audit/BO/05_customerService.ts
  tests/UI/campaigns/audit/BO/06_statistics.ts
  tests/UI/campaigns/audit/BO/07_modules.ts
  tests/UI/campaigns/audit/BO/08_design.ts
  tests/UI/campaigns/audit/BO/09_shipping.ts
  tests/UI/campaigns/audit/BO/10_payment.ts
  tests/UI/campaigns/audit/BO/11_international.ts
  tests/UI/campaigns/audit/BO/12_shopParameters.ts
  tests/UI/campaigns/audit/FO/classic/01_guest.ts
  tests/UI/campaigns/audit/FO/classic/02_connected.ts
  tests/UI/campaigns/audit/FO/classic/03_cart.ts
  tests/UI/campaigns/audit/FO/hummingbird/01_guest.ts
  tests/UI/campaigns/audit/FO/hummingbird/02_connected.ts
  tests/UI/campaigns/audit/FO/hummingbird/03_cart.ts
Labels: Bug fix, 9.0.x

#37838 Fix: bug: Legacy form sends GET request instead of POST as it should
  src/PrestaShopBundle/Routing/Converter/LegacyUrlConverter.php
  tests/Integration/PrestaShopBundle/Routing/Converter/LegacyUrlConverterTest.php
Labels: QA ✔️, Bug fix, 9.0.x

#37912 Fix performance issue linked to HookModuleFilter PR
  classes/Hook.php
  src/PrestaShopBundle/Resources/config/services/core/common.yml
Labels: QA ✔️, Bug fix, 8.2.x

#37919 Merge 8.2.x to 9.0.x 28/01/25
  classes/Tools.php
  src/Adapter/Presenter/Product/ProductListingLazyArray.php
  src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/General/PreferencesType.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig
  tests/UI/campaigns/functional/BO/03_catalog/01_products/20_multistore.ts
Labels: Improvement, 9.0.x

#37861 Fix Customer threads messages for multiple products
  classes/CustomerMessage.php
  controllers/front/OrderDetailController.php
  install-dev/data/db_structure.sql
Labels: QA ✔️, Bug fix, BC break, 9.0.x, Needs autoupgrade PR

#37889 Fix [verify autoupdate label] workflow
  .github/workflows/notify_for_autoupgrade_pr_label.yml
  .github/workflows/verify_autoupgrade_label_and_approvals.yml
Labels: Bug fix, 9.0.x

#37890 Fix preview mode for combination products
  controllers/front/ProductController.php
  themes/_core/js/product.js
Labels: QA ✔️, Bug fix, 8.2.x

#37931 Update dependencies
  composer.json
  composer.lock
  tests/UI/campaigns/functional/BO/03_catalog/01_products/20_multistore.ts
  tests/UI/campaigns/functional/FO/classic/08_menuAndNavigation/01_navigateInCategories/03_sideBlockCategories.ts
  tests/UI/campaigns/functional/FO/hummingbird/08_menuAndNavigation/01_navigateInCategories/03_sideBlockCategories.ts
Labels: Improvement, 9.0.x

#37945 Functional Tests: Bump `@prestashop-core/ui-testing`
  tests/UI/package-lock.json
Labels: Improvement, QA ✔️, 9.0.x

#37941 Improve category helptext
  src/PrestaShopBundle/Form/Admin/Catalog/Category/AbstractCategoryType.php
Labels: Improvement, QA ✔️, Waiting for wording, 9.0.x

#37943 chore: [release-8.2.1] - composer : update classic-theme package to 2…
  composer.json
  composer.lock
Labels: Improvement, 8.2.x

#37942 Generate category thumbnail for demo data on install
  src/PrestaShopBundle/Install/XmlLoader.php
Labels: QA ✔️, Bug fix, 9.0.x

#37944 Fix: MaterialChoiceTableType does not render help text
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig
Labels: QA ✔️, Bug fix, 9.0.x
