Repository PrestaShop/PrestaShop, pull requests merged in 2025-08, with the labels that each got.

#39257 Add missing attribute tag on constraints
  src/Core/ConstraintValidator/Constraints/AddressDniRequired.php
  src/Core/ConstraintValidator/Constraints/AddressStateRequired.php
  src/Core/ConstraintValidator/Constraints/AddressZipCode.php
  src/Core/ConstraintValidator/Constraints/CartRule.php
  src/Core/ConstraintValidator/Constraints/CleanHtml.php
  src/Core/ConstraintValidator/Constraints/CustomerName.php
  src/Core/ConstraintValidator/Constraints/DateRange.php
  src/Core/ConstraintValidator/Constraints/DefaultLanguage.php
  src/Core/ConstraintValidator/Constraints/ExistingCustomerEmail.php
  src/Core/ConstraintValidator/Constraints/IsUrlRewrite.php
  src/Core/ConstraintValidator/Constraints/NoTags.php
  src/Core/ConstraintValidator/Constraints/NotBlankWhenRequired.php
  src/Core/ConstraintValidator/Constraints/PositiveOrZero.php
  src/Core/ConstraintValidator/Constraints/Reduction.php
  src/Core/ConstraintValidator/Constraints/TypedRegex.php
  src/Core/ConstraintValidator/Constraints/UniqueStateIsoCode.php
  src/Core/ConstraintValidator/DefaultLanguageValidator.php
  src/Core/Context/ContextBuilderPreparer.php
  src/PrestaShopBundle/Resources/config/services/core/constraint_validator.yml
  tests/Unit/Core/ConstraintValidator/DefaultLanguageValidatorTest.php
Labels: Bug fix, 9.0.x

#39191 Fix: recoverCart link does not log the user. Stuck to process checkout step 1
  classes/controller/FrontController.php
Labels: QA ✔️, Bug fix, 8.2.x

#39160 Fix OrderStateType form to show all languages, including disabled ones
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
Labels: QA ✔️, Bug fix, 9.0.x

#39291 Functional Tests : Bump @prestashop-core/ui-testing
  tests/UI/campaigns/functional/BO/02_orders/01_orders/11_previewOrder.ts
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/02_conditions/10_productSelection.ts
  tests/UI/campaigns/regression/currencies/computingPrecision_FO.ts
  tests/UI/package-lock.json
Labels: TE, E2E Tests

#39137 Create merge shipment form
  admin-dev/themes/new-theme/js/fos_js_routes.json
  admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.ts
  admin-dev/themes/new-theme/js/pages/order/merge-shipment-manager.ts
  admin-dev/themes/new-theme/js/pages/order/view.ts
  admin-dev/themes/new-theme/scss/components/_skeleton.scss
  admin-dev/themes/new-theme/scss/pages/orders/_orders_shipment.scss
  admin-dev/themes/new-theme/scss/pages/orders/orders.scss
  admin-dev/themes/new-theme/scss/theme.scss
  src/Adapter/Shipment/QueryHandler/GetOrderShipmentsHandler.php
  src/Adapter/Shipment/QueryHandler/GetShipmentProductsHandler.php
  src/Core/Domain/Shipment/QueryResult/OrderShipment.php
  src/Core/Domain/Shipment/QueryResult/OrderShipmentProduct.php
  src/Core/Grid/Action/Row/Type/Shipment/AdditionalShipmentRowAction.php
  src/Core/Grid/Data/Factory/ShipmentGridDataFactory.php
  src/Core/Grid/Definition/Factory/ShipmentGridDefinitionFactory.php
  src/Core/Grid/Query/ShipmentQueryBuilder.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/Shipment/MergeShipmentType.php
  src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Actions/Row/additional_shipment_row_action.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/merge_shipment_modal.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/merge_shipment_form.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig
  tests/Integration/Behaviour/Features/Context/Domain/ShipmentFeatureContext.php
Labels: QA ✔️, develop, Feature

#39203 BO : Invoices : Harmonize Helper Text
  src/PrestaShopBundle/Form/Admin/Sell/Order/Invoices/GenerateByDateType.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/Invoices/GenerateByStatusType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Invoices/Blocks/generate_by_date.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Invoices/Blocks/generate_by_status.html.twig
Labels: QA ✔️, Bug fix, 9.0.x

#39209 BO : Fixed HTML in informations & warnings block
  src/PrestaShopBundle/Resources/views/Admin/Component/LegacyLayout/session_alert.html.twig
Labels: QA ✔️, Bug fix, 9.0.x

#39010 fix(checkout-address-step): save address choice on click
  themes/_core/js/checkout-address.js
Labels: QA ✔️, Bug fix, 9.0.x

#39295 Admin API CQRSDelete can use CQRSCommand and empty bodies can be used
  composer.json
  composer.lock
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSCommand.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSCreate.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSDelete.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSPartialUpdate.php
  src/PrestaShopBundle/ApiPlatform/Metadata/CQRSUpdate.php
  src/PrestaShopBundle/ApiPlatform/Provider/EmptyBodyDeserializerProvider.php
  src/PrestaShopBundle/ApiPlatform/Serializer/CQRSApiSerializer.php
  src/PrestaShopBundle/Resources/config/services/bundle/api_platform.yml
  tests/Integration/ApiPlatform/Serializer/CQRSApiSerializerTest.php
  tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/01_internalAuthServer/02_resourceEndpoint.ts
  tests/UI/campaigns/functional/API/02_checkEndpoints.ts
  tests/UI/campaigns/functional/API/02_endpoints/03_hook/03_getHooksId.ts
  tests/UI/campaigns/functional/API/02_endpoints/05_module/03_putModuleTechnicalNameInstall.ts
  tests/UI/campaigns/functional/API/02_endpoints/05_module/04_patchModuleTechnicalNameReset.ts
  tests/UI/campaigns/functional/API/02_endpoints/05_module/07_putModuleTechnicalNameUpgrade.ts
  tests/UI/campaigns/functional/API/02_endpoints/06_product/03_postProductIdImage.ts
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSCommandTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSCreateTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSDeleteTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSPartialUpdateTest.php
  tests/Unit/PrestaShopBundle/ApiPlatform/Metadata/CQRSUpdateTest.php
Labels: Bug fix, BC break, 9.0.x

#39140 Condition based on categories
  admin-dev/themes/new-theme/js/pages/discount/form/index.ts
  src/Core/ConstraintValidator/Constraints/DiscountProductSegment.php
  src/Core/ConstraintValidator/DiscountProductSegmentValidator.php
  src/Core/Form/IdentifiableObject/DataHandler/DiscountFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/DiscountFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Sell/Discount/CartConditionsType.php
  src/PrestaShopBundle/Form/Admin/Sell/Discount/DiscountProductSegmentType.php
  src/PrestaShopBundle/Resources/config/services/core/constraint_validator.yml
  tests/Integration/Behaviour/Features/Scenario/Discount/BO/add_discount_with_category_trigger.feature
  tests/Integration/Behaviour/Features/Scenario/Discount/FO/discount_with_category_trigger.feature
  tests/Integration/Behaviour/behat.yml
Labels: QA ✔️, Waiting for wording, develop, Feature

#39260 Adding taxes for shipping cost if needed
  classes/Cart.php
Labels: QA ✔️, Bug fix, 9.0.x

#39302 Fix shipments tab
  src/Core/Grid/Data/Factory/ShipmentGridDataFactory.php
  src/Core/Grid/Definition/Factory/ShipmentGridDefinitionFactory.php
  src/Core/Grid/Query/ShipmentQueryBuilder.php
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/details.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/merge_shipment_form.html.twig
Labels: Waiting for QA, QA ✔️, develop, Bug fix

#39312 Fix ALT shop name.
  src/PrestaShopBundle/Resources/views/Admin/Layout/login_layout.html.twig
Labels: Waiting for QA, Bug fix, 9.0.x

#39284 Command `prestashop:list:commands-and-queries` : Filter CQRS with (1) or without (0) an endpoint
  src/PrestaShopBundle/Command/ListCommandsAndQueriesCommand.php
Labels: Improvement, QA ✔️, 9.0.x

#39232 Fix some informations in README
  README.md
Labels: Improvement, 9.0.x

#39292 BO : Fixed redirection when permission is not allowed
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmailController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/PerformanceController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SecurityController.php
  src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceController.php
  src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/MetaController.php
  src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/LanguageController.php
  src/PrestaShopBundle/Controller/Admin/Improve/International/LocalizationController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Order/InvoicesController.php
Labels: QA ✔️, Bug fix, 9.0.x

#39321 Update Distribution API Client to include the new wall of fame
  composer.json
  composer.lock
Labels: Improvement, Waiting for QA, 8.2.x

#39322 Update Distribution API Client to include the new wall of fame
  composer.json
  composer.lock
Labels: Improvement, 9.0.x

#39272 BO : Fixed the memorization of the language used in Admin in the cookie (if option is enabled)
  phpstan-baseline.neon
  src/Core/Form/IdentifiableObject/DataHandler/EmployeeFormDataHandler.php
  src/PrestaShopBundle/Resources/config/services/core/form/form_data_handler.yml
Labels: QA ✔️, Bug fix, 9.0.x

#39331 Fix: using dev version of ps_apiresources
  composer.json
  composer.lock
  tests/UI/campaigns/functional/API/02_checkEndpoints.ts
Labels: Bug fix, 9.0.x

#39299 BO : Products - Bulk Actions : Fixed error when no permissions
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/EventListener/Admin/AccessDeniedListener.php
  src/PrestaShopBundle/Security/Attribute/AdminSecurity.php
Labels: QA ✔️, Bug fix, 9.0.x

#39337 Fix: Cannot use newline in textarea on product page
  admin-dev/themes/new-theme/js/pages/product/edit/product-partial-updater.ts
Labels: QA ✔️, Bug fix, 8.2.x

#39245 Fix: Back Office becomes inaccessible if the employee's assigned language is deleted
  src/Adapter/Employee/EmployeeLanguageUpdater.php
  src/Adapter/Language/CommandHandler/DeleteLanguageHandler.php
  src/PrestaShopBundle/Resources/config/services/adapter/common.yml
  src/PrestaShopBundle/Resources/config/services/adapter/language.yml
Labels: QA ✔️, Bug fix, 9.0.x

#39314 BO : Orders : Modal Discount reset when it's hidden
  admin-dev/themes/new-theme/js/pages/order/view.ts
Labels: QA ✔️, Bug fix, 9.0.x

#39246 Discount condition based on supplier
  src/Core/ConstraintValidator/DiscountProductSegmentValidator.php
  src/Core/Domain/Discount/ProductRuleType.php
  src/Core/Form/IdentifiableObject/DataHandler/DiscountFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/DiscountFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Sell/Discount/DiscountProductSegmentType.php
  src/PrestaShopBundle/Form/Admin/Sell/Discount/DiscountSupplierType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  tests/Integration/Behaviour/Features/Scenario/Discount/BO/add_discount_with_supplier_trigger.feature
  tests/Integration/Behaviour/Features/Scenario/Discount/FO/discount_with_supplier_trigger.feature
  tests/Integration/Behaviour/behat.yml
Labels: QA ✔️, Waiting for wording, develop, Feature

#39341 Fix shipments "items"
  src/Core/Grid/Query/ShipmentQueryBuilder.php
Labels: QA ✔️, develop, Bug fix

#39333 Fix product access in BO when seo redirection related entity is deleted
  classes/Product.php
Labels: QA ✔️, Bug fix, Topwatchers, 9.0.x

#39373 Small Refacto Store.php for semantic (backticks unification)
  classes/Store.php
Labels: Refactoring, 9.0.x

#39197 Added PrestaShop version in bin/console
  phpstan-baseline.neon
  src/PrestaShopBundle/Command/AboutCommand.php
  src/PrestaShopBundle/Console/PrestaShopApplication.php
  src/PrestaShopBundle/Resources/config/services/bundle/command.yml
Labels: Improvement, QA ✔️, develop

#39406 Display full history time
  src/Adapter/Presenter/Order/OrderLazyArray.php
Labels: Improvement, QA ✔️, 9.0.x

#39404 Allow filtering module list for translation export
  src/PrestaShopBundle/Form/Admin/Improve/International/Translations/ExportCataloguesType.php
  src/PrestaShopBundle/Form/Admin/Type/RadioWithChoiceChildrenType.php
Labels: Improvement, QA ✔️, 9.0.x

#37590 Patch tinymce fullscreen
  admin-dev/themes/new-theme/scss/components/_tinymce.scss
Labels: QA ✔️, Bug fix, 9.0.x

#39358 Create ModuleParser to parse module information
  .php-cs-fixer.dist.php
  classes/module/Module.php
  phpstan-baseline.neon
  src/Core/Module/ModuleRepository.php
  src/Core/Module/Parser/ModuleParser.php
  src/Core/Module/Parser/ModuleParserException.php
  tests/Unit/Core/Module/Parser/ModuleParserTest.php
  tests/Unit/Resources/parsed-modules/all-hard-coded.php
  tests/Unit/Resources/parsed-modules/cannot-parse.php.txt
  tests/Unit/Resources/parsed-modules/cs-fixed-fqcn-const.php
  tests/Unit/Resources/parsed-modules/defined-const.php
  tests/Unit/Resources/parsed-modules/empty.php
  tests/Unit/Resources/parsed-modules/fqcn-const.php
  tests/Unit/Resources/parsed-modules/module-const-array.php
  tests/Unit/Resources/parsed-modules/module-self-const.php
  tests/Unit/Resources/parsed-modules/module-static-const.php
  tests/Unit/Resources/parsed-modules/no-constructor.php
  tests/Unit/Resources/parsed-modules/translated-values.php
  tests/Unit/Resources/parsed-modules/use-statement-const.php
Labels: QA ✔️, Waiting for wording, Bug fix, 9.0.x

#39363 Condition based on countries
  admin-dev/themes/new-theme/js/components/form/toggle-children-choice.ts
  admin-dev/themes/new-theme/js/pages/discount/discount-map.ts
  admin-dev/themes/new-theme/js/pages/discount/form/index.ts
  bin/console
  install-dev/init.php
  src/Adapter/Cart/CommandHandler/UpdateCartCarrierHandler.php
  src/Adapter/Discount/CommandHandler/UpdateDiscountConditionsHandler.php
  src/Adapter/Discount/QueryHandler/GetDiscountForEditingHandler.php
  src/Adapter/Discount/Repository/DiscountRepository.php
  src/Adapter/Discount/Update/DiscountConditionsUpdater.php
  src/Core/Domain/Discount/Command/UpdateDiscountConditionsCommand.php
  src/Core/Domain/Discount/QueryResult/DiscountForEditing.php
  src/Core/Form/ChoiceProvider/CountryByIdChoiceProvider.php
  src/Core/Form/IdentifiableObject/DataHandler/DiscountFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/DiscountFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Sell/Discount/DeliveryConditionsType.php
  src/PrestaShopBundle/Form/Admin/Type/CarrierChoiceType.php
  src/PrestaShopBundle/Form/Admin/Type/CountryChoiceType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  src/PrestaShopBundle/Resources/config/services/core/form/choice_provider.yml
  tests/Integration/Behaviour/Features/Context/Domain/Discount/DiscountConditionsFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/Discount/DiscountFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Discount/BO/add_discount_with_country_trigger.feature
  tests/Integration/Behaviour/Features/Scenario/Discount/FO/discount_with_country_trigger.feature
  tests/Integration/Behaviour/behat.yml
Labels: QA ✔️, Waiting for wording, develop, Feature

#39424 Update CSSJanus to wikimedia/cssjanus
  composer.json
  composer.lock
Labels: Improvement, QA ✔️, develop

#39430 Fix quantity in delivery slip if we have a refunded product
  pdf/delivery-slip.product-tab.tpl
Labels: QA ✔️, Bug fix, 8.2.x

#39461 Merge 9.0.x to develop 29/08/25
  .docker/docker_run_git.sh
  .docker/wait-for-it.sh
  .github/actions/setup-env/action.yml
  .github/workflows/cron_nightly_tests_reusable.yml
  .php-cs-fixer.dist.php
  admin-dev/themes/new-theme/scss/components/_tinymce.scss
  classes/ConnectionsSource.php
  classes/Tools.php
  classes/module/Module.php
  composer.lock
  docker-compose.yml
  phpstan-baseline.neon
  src/Adapter/Presenter/Order/OrderLazyArray.php
  src/Core/Module/ModuleRepository.php
  src/Core/Module/Parser/ModuleParser.php
  src/Core/Module/Parser/ModuleParserException.php
  src/PrestaShopBundle/Form/Admin/Improve/International/Translations/ExportCataloguesType.php
  src/PrestaShopBundle/Form/Admin/Sell/Order/CancelProductType.php
  src/PrestaShopBundle/Form/Admin/Type/RadioWithChoiceChildrenType.php
  src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_horizontal_layout.html.twig
  tests/Unit/Core/Module/Parser/ModuleParserTest.php
  tests/Unit/Resources/parsed-modules/all-hard-coded.php
  tests/Unit/Resources/parsed-modules/cannot-parse.php.txt
  tests/Unit/Resources/parsed-modules/cs-fixed-fqcn-const.php
  tests/Unit/Resources/parsed-modules/defined-const.php
  tests/Unit/Resources/parsed-modules/empty.php
  tests/Unit/Resources/parsed-modules/fqcn-const.php
  tests/Unit/Resources/parsed-modules/module-const-array.php
  tests/Unit/Resources/parsed-modules/module-self-const.php
  tests/Unit/Resources/parsed-modules/module-static-const.php
  tests/Unit/Resources/parsed-modules/no-constructor.php
  tests/Unit/Resources/parsed-modules/translated-values.php
  tests/Unit/Resources/parsed-modules/use-statement-const.php
Labels: Improvement, develop
