Repository PrestaShop/PrestaShop, pull requests merged in 2025-02, with the labels that each got.

#37956 Update Changelog for 9.0.0 Beta 1 Build 4
  docs/CHANGELOG.txt
Labels: Improvement, 9.0.x

#37969 Functional Tests : Fixed `functional/API/02*/09*/01*`
  tests/UI/campaigns/functional/API/02_endpoints/09_product/01_postProduct.ts
Labels: QA ✔️, TE, E2E Tests

#37973 Stabilize test view order multi invoices
  tests/UI/campaigns/functional/BO/02_orders/01_orders/viewAndEditOrder/12_checkMultiInvoice.ts
  tests/UI/package-lock.json
Labels: Improvement, QA ✔️, 9.0.x

#37911 Cart rule refacto command free shipping
  classes/CartRule.php
  install-dev/data/db_structure.sql
  src/Adapter/CartRule/CartRuleBuilder.php
  src/Adapter/Discount/CommandHandler/AddFreeShippingDiscountHandler.php
  src/Adapter/Discount/QueryHandler/GetDiscountForEditingHandler.php
  src/Core/Domain/Discount/Command/AddDiscountCommand.php
  src/Core/Domain/Discount/Command/AddFreeShippingDiscountCommand.php
  src/Core/Domain/Discount/CommandHandler/AddFreeShippingDiscountHandlerInterface.php
  src/Core/Domain/Discount/Exception/DiscountConstraintException.php
  src/Core/Domain/Discount/Exception/DiscountException.php
  src/Core/Domain/Discount/Exception/DiscountNotFoundException.php
  src/Core/Domain/Discount/Query/GetDiscountForEditing.php
  src/Core/Domain/Discount/QueryHandler/GetDiscountForEditingHandlerInterface.php
  src/Core/Domain/Discount/QueryResult/DiscountForEditing.php
  src/Core/Domain/Discount/ValueObject/DiscountId.php
  src/Core/Domain/Discount/ValueObject/DiscountType.php
  src/Core/Domain/Discount/ValueObject/GiftedProduct.php
  src/PrestaShopBundle/Resources/config/services/adapter/cart_rule.yml
  src/PrestaShopBundle/Resources/config/services/adapter/discount.yml
  tests/Integration/Behaviour/Features/Context/Domain/Discount/DiscountFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Discount/add_discount.feature
  tests/Integration/Behaviour/behat.yml
Labels: Waiting for PM, Waiting for QA, Feature, 9.0.x, Needs autoupgrade PR

#37980 Tests UI stabilization: order creation
  tests/UI/package-lock.json
Labels: Improvement, QA ✔️, 9.0.x

#37975 Merge branch `8.2.x` into `9.0.x`
  composer.lock
  controllers/front/ProductController.php
  themes/_core/js/product.js
Labels: Improvement, 9.0.x

#37638 Switch carrier feature flag to stable and enabled by default
  admin-dev/themes/new-theme/js/pages/carrier/form/carrier-form-manager.ts
  install-dev/data/xml/feature_flag.xml
  src/Adapter/Carrier/CommandHandler/SetCarrierTaxRuleGroupHandler.php
  src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php
  src/Core/Form/IdentifiableObject/DataProvider/CarrierFormDataProvider.php
  src/PrestaShopBundle/Form/Admin/Improve/Shipping/Carrier/ShippingLocationsAndCostsType.php
  src/PrestaShopBundle/Resources/config/services/adapter/data_provider.yml
  src/PrestaShopBundle/Resources/config/services/adapter/group.yml
  tests/Integration/Behaviour/Features/Context/Domain/Carrier/CarrierTaxRuleGroupFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Carrier/carrier_tax_rule_group_management.feature
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/01_CRUDCarrier.ts
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/02_filterSortAndPagination.ts
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/03_quickEditAndBulkActions.ts
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/04_quickEditStatusAndFreeShipping.ts
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/05_changePosition.ts
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/06_generalSettings.ts
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/07_shippingLocationsAndCosts.ts
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/08_sizeAndWeight.ts
  tests/UI/campaigns/functional/BO/09_shipping/02_preferences/01_handling/01_handlingCharges.ts
  tests/UI/campaigns/functional/BO/09_shipping/02_preferences/02_carrierOptions/02_updateCarriersSortOption.ts
  tests/UI/package-lock.json
  tests/Unit/Core/Form/IdentifiableObject/DataProvider/CarrierFormDataProviderTest.php
Labels: QA ✔️, Waiting for wording, Feature, 9.0.x, Needs autoupgrade PR, Backlog SUE

#38014 Rename `emailField` to `field` for aligning the variable name with its actual purpose
  classes/form/CustomerForm.php
Labels: Waiting for QA, develop, Refactoring

#38022 Changelog 8.2.1
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: Improvement, Waiting for QA, 8.2.x

#37982 Empty the labels "totalPriceText" and "availableText".
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add.ts
Labels: QA ✔️, 8.2.x

#38000 Add new integration test for discount CQRS
  tests/Integration/Behaviour/Features/Context/Domain/Discount/DiscountFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Discount/BO/add_discount.feature
  tests/Integration/Behaviour/Features/Scenario/Discount/FO/full_user_experience_test_with_discount.feature
  tests/Integration/Behaviour/behat.yml
Labels: Waiting for QA

#38020 Functional Tests : Fixed `functional/API/02*/05_hooks/02*`
  admin-dev/themes/new-theme/scss/pages/_modules.scss
  src/PrestaShopBundle/Resources/views/Admin/Improve/Design/positions.html.twig
  tests/UI/campaigns/functional/API/02_endpoints/05_hooks/02_getHooksId.ts
  tests/UI/package-lock.json
Labels: QA ✔️, TE, E2E Tests

#37958 Fix product filters for csv export
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
Labels: QA ✔️, Bug fix, 8.2.x

#37985 Fix: display... hooks duplicated on module transplant list
  classes/module/Module.php
Labels: QA ✔️, Bug fix, 8.2.x

#38030 Functional Tests : FO - Menu and Navigation - Navigate in Categories - Side block categories
  tests/UI/campaigns/functional/FO/classic/08_menuAndNavigation/01_navigateInCategories/03_sideBlockCategories.ts
  tests/UI/campaigns/functional/FO/hummingbird/08_menuAndNavigation/01_navigateInCategories/03_sideBlockCategories.ts
  tests/UI/package-lock.json
Labels: QA ✔️, TE, E2E Tests, 9.0.x

#38050 Functional Tests : BO - Catalog - Discounts : CRUD catalog price rules
  tests/UI/campaigns/functional/BO/03_catalog/07_discounts/02_catalogPriceRules/01_CRUDCatalogPriceRule.ts
  tests/UI/package-lock.json
Labels: QA ✔️, TE, E2E Tests

#37970 Fix: [Bug] Missing attributes autoplay, loop, muted, and playsinline in the video tag within Tools::purifyHTML()
  classes/Tools.php
Labels: QA ✔️, Bug fix, 8.2.x

#38052 Merge `8.2.x` into `9.0.x`
  CONTRIBUTORS.md
  admin-dev/themes/new-theme/js/pages/order/view/order-product-add.ts
  classes/module/Module.php
  docs/CHANGELOG.txt
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  tests/Resources/modules_tests/override_for_unit_test/classes/Cart.php
Labels: Improvement, QA ✔️, 9.0.x

#37947 Add new hook in object presenter
  install-dev/data/xml/hook.xml
  src/Adapter/Presenter/Object/ObjectPresenter.php
Labels: QA ✔️, develop, Feature, Needs autoupgrade PR, Hook Contribution

#37877 Fix: BO - Product Page - Redirection type - Category without image generate 404 call
  src/Adapter/Category/CategoryDataProvider.php
  src/Adapter/Category/Repository/CategoryPreviewRepository.php
  src/Adapter/Image/ImagePathFactory.php
Labels: QA ✔️, Bug fix, Topwatchers, 8.2.x

#38054 Change version to 9.1.0
  install-dev/install_version.php
  src/Core/Version.php
Labels: Improvement, QA ✔️, develop

#38086 Revert #38054, UI tests are not ready yet
  install-dev/install_version.php
  src/Core/Version.php
Labels: develop, Bug fix

#37955 Fix: prestashop don't display Title of product, category meta title, meta description
  classes/Meta.php
  classes/Tools.php
  classes/controller/FrontController.php
Labels: QA ✔️, Bug fix, 8.2.x

#38137 Add missing token for gh workflow
  .github/workflows/notify_for_autoupgrade_pr_label.yml
Labels: Waiting for QA, Bug fix, 9.0.x

#38040 Feature: add feature flag for upcoming new shipment system
  install-dev/data/xml/feature_flag.xml
  src/Core/FeatureFlag/FeatureFlagSettings.php
Labels: develop, Feature, Needs autoupgrade PR, PR Autoupgrade opened ✔️

#38140 Merge `8.2.x` into `9.0.x`
  .docker/docker_run_git.sh
  classes/Meta.php
  classes/Tools.php
  classes/controller/FrontController.php
  src/Adapter/Category/CategoryDataProvider.php
  src/Adapter/Category/Repository/CategoryPreviewRepository.php
  src/Adapter/Image/ImagePathFactory.php
Labels: Improvement, Waiting for author, Waiting for QA, 9.0.x

#38104 Fixed SK tax in all localization files
  localization/at.xml
  localization/be.xml
  localization/bg.xml
  localization/cy.xml
  localization/cz.xml
  localization/de.xml
  localization/dk.xml
  localization/ee.xml
  localization/es.xml
  localization/fi.xml
  localization/fr.xml
  localization/gb.xml
  localization/gr.xml
  localization/hr.xml
  localization/hu.xml
  localization/ie.xml
  localization/it.xml
  localization/lt.xml
  localization/lu.xml
  localization/lv.xml
  localization/mc.xml
  localization/mt.xml
  localization/nl.xml
  localization/pl.xml
  localization/pt.xml
  localization/ro.xml
  localization/se.xml
  localization/si.xml
  localization/sk.xml
Labels: QA ✔️, Bug fix, 9.0.x

#38163 Update Symfony components after 6.4.19 release
  composer.lock
Labels: Improvement, 9.0.x

#38142 fix: improve link styling for better identification – issue #38122
  admin-dev/themes/default/scss/partials/_content.scss
  admin-dev/themes/default/scss/partials/_toolbar.scss
  admin-dev/themes/new-theme/scss/components/layout/_content_div.scss
Labels: Improvement, QA ✔️, 9.0.x

#38073 Check mail template directory before reading
  controllers/admin/AdminTranslationsController.php
Labels: Improvement, QA ✔️, 8.2.x

#38037 Fix: Use 'active' from 'product_shop' instead of 'product' in Product::searchByName()
  classes/Product.php
Labels: QA ✔️, Bug fix, 8.2.x

#38093 Improve message on exception
  src/PrestaShopBundle/Routing/LegacyRouterChecker.php
Labels: QA ✔️, Refactoring, 9.0.x

#38169 Add setup log export action
  .github/actions/setup-env-export-logs/action.yml
Labels: QA ✔️
