Repository PrestaShop/PrestaShop, pull requests merged in 2025-05, with the labels that each got.

#38552 Use id_customization for matching cart and order products
  src/Adapter/Presenter/Order/OrderLazyArray.php
Labels: QA ✔️, Bug fix, 8.2.x

#38569 Stabilize UI tests for new product module
  tests/UI/package-lock.json
Labels: Improvement, 9.0.x

#38557 Improve OpenApi configuration to include OAuth scopes dynamically
  app/config/admin-api/config.yml
  app/config/admin/config.yml
  app/config/config.yml
  app/config/config_dev.yml
  app/config/config_prod.yml
  app/config/config_test.yml
  src/PrestaShopBundle/ApiPlatform/OpenApi/Factory/CQRSOpenApiFactory.php
  src/PrestaShopBundle/ApiPlatform/Scopes/ApiResourceScopesExtractorFactory.php
  src/PrestaShopBundle/DependencyInjection/Compiler/ApiPlatformCompilerPass.php
  src/PrestaShopBundle/PrestaShopBundle.php
  src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/admin_api.yml
  tests/Integration/PrestaShopBundle/ApiPlatform/CQRSOpenApiFactoryTest.php
Labels: Improvement, 9.0.x

#38575 Update dependencies
  composer.json
  composer.lock
Labels: Bug fix, 9.0.x

#38583 Update changelog 9.0.0 RC 1
  CONTRIBUTORS.md
  docs/CHANGELOG.txt
Labels: Improvement, 9.0.x

#38436 Functional Tests : Stabilisation "functional:FO:hummingbird:08-12"
  tests/UI/campaigns/functional/BO/09_shipping/01_carriers/05_changePosition.ts
  tests/UI/campaigns/functional/FO/hummingbird/11_checkout/01_showDetails.ts
  tests/UI/package-lock.json
Labels: Improvement, 9.0.x

#38595 Functional Tests : Bump `@prestashop-core/ui-testing`
  tests/UI/package-lock.json
Labels: Improvement, QA ✔️, develop

#38572 Fix spinner on mobile resolution
  admin-dev/themes/new-theme/scss/components/layout/_main_header.scss
Labels: QA ✔️, Bug fix, 9.0.x

#38576 Update Symfony components after 6.4.21 release
  composer.lock
Labels: Improvement, develop

#38633 Fix for 900rc1
  classes/Language.php
  composer.json
  composer.lock
  src/PrestaShopBundle/Security/OAuth2/GrantType/CustomClientCredentialsGrant.php
  src/PrestaShopBundle/Security/OAuth2/Repository/ScopeRepository.php
  tests/Integration/ApiPlatform/EndPoint/ApiAccessTokenEndpointTest.php
Labels: Waiting for QA, Bug fix, 9.0.x

#38689 Functional Tests : Bump @prestashop-core/ui-testing
  tests/UI/package-lock.json
Labels: QA ✔️, TE, E2E Tests

#38698 Block execution while cache clear is running in install endpoints
  install-dev/index.php
  install-dev/index_cli.php
Labels: Improvement, 9.0.x

#38703 Revert modification in OrderLazyArray that breaks the UI tests
  src/Adapter/Presenter/Order/OrderLazyArray.php
Labels: Bug fix, 8.2.x

#38691 Add hook displayCartExtraProductInfo to display cart extra product information
  install-dev/data/xml/hook.xml
Labels: Waiting for QA, Feature, Needs autoupgrade PR, 8.2.x

#38714 Functional Tests : Migrate to `@prestashop-core/ui-testing` (Part 8)
  tests/UI/campaigns/functional/API/02_endpoints/08_modules/01_getModules.ts
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/05_paginationAndSortCategories.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/01_emptyCategories.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/02_withCombinationsWithoutQuantities.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/03_withoutCombinationsWithoutQuantities.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/04_disabledProducts.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/05_productsWithoutImage.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/06_productsWithoutDescription.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/07_productsWithoutPrice.ts
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/brands/02_sortPaginationAndBulkActions.ts
  tests/UI/campaigns/functional/BO/04_customers/01_customers/04_paginationAndSortCustomers.ts
  tests/UI/campaigns/functional/BO/04_customers/02_addresses/04_paginationAndSortAddresses.ts
  tests/UI/data/import/addresses.ts
  tests/UI/data/import/brands.ts
  tests/UI/data/import/categories.ts
  tests/UI/data/import/combinations.ts
  tests/UI/data/import/customers.ts
  tests/UI/data/import/disabledProducts.ts
  tests/UI/data/import/productsWithoutQuantities.ts
  tests/UI/data/types/module.ts
  tests/UI/package-lock.json
  tests/UI/types/global.d.ts
Labels: TE, E2E Tests

#38712 Prevent data from hooks from overriding local translated module data
  src/Core/Module/ModuleRepository.php
Labels: Improvement, QA ✔️, 9.0.x

#38251 Fix: Query to select most used tax rule is simply ridicoulous
  classes/Product.php
  install-dev/data/db_structure.sql
Labels: QA ✔️, Bug fix, Topwatchers, 8.2.x, PR Autoupgrade opened ✔️

#38718 Merge 8.2.x 9.0.x 16/05/25
  classes/Product.php
  install-dev/data/db_structure.sql
  install-dev/data/xml/hook.xml
Labels: Improvement, 9.0.x

#38484 Modify the shipment creation & remove order duplication for different carrier
  classes/PaymentModule.php
  src/Adapter/Shipment/OrderShipmentCreator.php
  tests/Integration/Behaviour/Features/Context/Domain/ShipmentFeatureContext.php
  tests/Integration/Behaviour/Features/Context/Domain/ZoneFeatureContext.php
  tests/Integration/Behaviour/Features/Scenario/Shipment/products_with_different_carriers.feature
  tests/Integration/Behaviour/Features/Scenario/Shipment/shipment.feature
  tests/Integration/Behaviour/behat.yml
Labels: develop, Feature

#38733 Functional Tests : Migrate `@utils/globals` into `ui-testing-library`
  tests/UI/package-lock.json
  tests/UI/package.json
  tests/UI/utils/globals.ts
Labels: QA ✔️, TE, E2E Tests

#38731 Fix showcase-card image for attribute page
  admin-dev/themes/new-theme/static/helper-card/attributes@3x.svg
  admin-dev/themes/new-theme/static/helper-card/features@3x.svg
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/AttributeGroup/Blocks/showcase_card.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Features/Blocks/showcase_card.html.twig
Labels: QA ✔️, Bug fix, 9.0.x

#38581 Allow refund on an order of a deleted customer
  classes/Customer.php
  src/Adapter/Order/Refund/OrderSlipCreator.php
  src/Adapter/Order/Refund/VoucherGenerator.php
Labels: QA ✔️, Bug fix, Topwatchers, 8.2.x

#38747 Functional Tests : Bump `@prestashop-core/ui-testing`
  tests/UI/package-lock.json
Labels: QA ✔️, TE, E2E Tests

#38048 Fix: Unable to configure a module that utilizes a modern controller
  classes/Tools.php
  tests/Integration/Classes/ToolsTest.php
Labels: QA ✔️, Bug fix, 9.0.x

#38736 Improve multi shop permissions
  classes/Employee.php
  phpstan-baseline.neon
  src/Adapter/Shop/Repository/ShopRepository.php
  src/Core/Context/EmployeeContext.php
  src/Core/Context/EmployeeContextBuilder.php
  src/Core/Exception/MultiShopAccessDeniedException.php
  src/PrestaShopBundle/Controller/Admin/PrestaShopAdminController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/EventListener/Admin/Context/ShopContextSubscriber.php
  src/PrestaShopBundle/EventListener/Admin/EmployeeSessionSubscriber.php
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/multistore_header.html.twig
  src/PrestaShopBundle/Twig/Component/AbstractMultistoreHeader.php
  src/PrestaShopBundle/Twig/Component/MultistoreHeader.php
  src/PrestaShopBundle/Twig/Component/MultistoreProductHeader.php
  src/PrestaShopBundle/Twig/Layout/MenuBuilder.php
  tests/Resources/Context/EmployeeContextDecorator.php
  tests/Unit/Core/Context/EmployeeContextBuilderTest.php
  tests/Unit/Core/Context/EmployeeContextTest.php
  tests/Unit/PrestaShopBundle/EventListener/Admin/Context/EmployeeContextSubscriberTest.php
  tests/Unit/PrestaShopBundle/EventListener/Admin/Context/ShopContextSubscriberTest.php
Labels: Improvement, QA ✔️, 9.0.x

#38762 Merge 9.0.x to develop 23/05/25
  admin-dev/themes/new-theme/static/helper-card/attributes@3x.svg
  admin-dev/themes/new-theme/static/helper-card/features@3x.svg
  classes/Employee.php
  classes/Product.php
  classes/Tools.php
  install-dev/data/db_structure.sql
  install-dev/data/xml/hook.xml
  phpstan-baseline.neon
  src/Adapter/Shop/Repository/ShopRepository.php
  src/Core/Context/EmployeeContext.php
  src/Core/Context/EmployeeContextBuilder.php
  src/Core/Exception/MultiShopAccessDeniedException.php
  src/Core/Form/ChoiceProvider/OrderStateByIdChoiceProvider.php
  src/Core/Module/ModuleRepository.php
  src/PrestaShopBundle/Controller/Admin/PrestaShopAdminController.php
  src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php
  src/PrestaShopBundle/EventListener/Admin/Context/ShopContextSubscriber.php
  src/PrestaShopBundle/EventListener/Admin/EmployeeSessionSubscriber.php
  src/PrestaShopBundle/Resources/views/Admin/Component/Layout/multistore_header.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/AttributeGroup/Blocks/showcase_card.html.twig
  src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Features/Blocks/showcase_card.html.twig
  src/PrestaShopBundle/Twig/Component/AbstractMultistoreHeader.php
  src/PrestaShopBundle/Twig/Component/MultistoreHeader.php
  src/PrestaShopBundle/Twig/Component/MultistoreProductHeader.php
  src/PrestaShopBundle/Twig/Layout/MenuBuilder.php
  tests/Integration/Classes/ToolsTest.php
  tests/Resources/Context/EmployeeContextDecorator.php
  tests/UI/campaigns/functional/API/02_endpoints/08_modules/01_getModules.ts
  tests/UI/campaigns/functional/BO/03_catalog/02_categories/05_paginationAndSortCategories.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/01_emptyCategories.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/02_withCombinationsWithoutQuantities.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/03_withoutCombinationsWithoutQuantities.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/04_disabledProducts.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/05_productsWithoutImage.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/06_productsWithoutDescription.ts
  tests/UI/campaigns/functional/BO/03_catalog/03_monitoring/sortPaginationAndBulkDelete/07_productsWithoutPrice.ts
  tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/brands/02_sortPaginationAndBulkActions.ts
  tests/UI/campaigns/functional/BO/04_customers/01_customers/04_paginationAndSortCustomers.ts
  tests/UI/campaigns/functional/BO/04_customers/02_addresses/04_paginationAndSortAddresses.ts
  tests/UI/data/import/addresses.ts
  tests/UI/data/import/brands.ts
  tests/UI/data/import/categories.ts
  tests/UI/data/import/combinations.ts
  tests/UI/data/import/customers.ts
  tests/UI/data/import/disabledProducts.ts
  tests/UI/data/import/productsWithoutQuantities.ts
  tests/UI/data/types/module.ts
  tests/UI/package-lock.json
  tests/UI/package.json
  tests/UI/types/global.d.ts
  tests/UI/utils/globals.ts
  tests/Unit/Core/Context/EmployeeContextBuilderTest.php
  tests/Unit/Core/Context/EmployeeContextTest.php
  tests/Unit/PrestaShopBundle/EventListener/Admin/Context/EmployeeContextSubscriberTest.php
  tests/Unit/PrestaShopBundle/EventListener/Admin/Context/ShopContextSubscriberTest.php
Labels: Improvement, develop

#38745 Enabling theme of add/update shop in a multistore context
  classes/ImageType.php
  controllers/admin/AdminShopController.php
  install-dev/data/db_structure.sql
  phpstan-baseline.neon
  src/Adapter/Image/ImageRetriever.php
  src/Core/Addon/Theme/ThemeManager.php
  src/Core/Domain/ImageSettings/QueryHandler/GetImageTypeForEditingHandler.php
  src/Core/Domain/ImageSettings/QueryResult/EditableImageType.php
  src/Core/Form/IdentifiableObject/DataProvider/ImageTypeFormDataProvider.php
  src/Core/Grid/Definition/Factory/ImageTypeGridDefinitionFactory.php
  src/Core/Grid/Query/ImageTypeQueryBuilder.php
  src/Core/Image/ImageTypeRepository.php
  src/PrestaShopBundle/Entity/ImageType.php
  src/PrestaShopBundle/Form/Admin/Type/ThemeChoiceType.php
  src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
  tests/Unit/Core/Domain/ImageSettings/QueryResult/EditableImageTypeTest.php
Labels: QA ✔️, Bug fix, 9.0.x, Needs autoupgrade PR

#38763 Fix for setAmountDiscount constructor type
  src/Core/Domain/Discount/Command/AddDiscountCommand.php
  src/Core/Form/IdentifiableObject/DataHandler/DiscountFormDataHandler.php
  tests/Integration/Behaviour/Features/Context/Domain/Discount/DiscountFeatureContext.php
Labels: develop, Bug fix

#38764 Update default catalog 9.0.x
  translations/default/AdminActions.xlf
  translations/default/AdminAdvparametersFeature.xlf
  translations/default/AdminAdvparametersHelp.xlf
  translations/default/AdminAdvparametersNotification.xlf
  translations/default/AdminCatalogFeature.xlf
  translations/default/AdminCatalogNotification.xlf
  translations/default/AdminDesignFeature.xlf
  translations/default/AdminGlobal.xlf
  translations/default/AdminLoginFeature.xlf
  translations/default/AdminNavigationMenu.xlf
  translations/default/AdminNotificationsError.xlf
  translations/default/AdminNotificationsInfo.xlf
  translations/default/AdminNotificationsSuccess.xlf
  translations/default/AdminShopparametersFeature.xlf
  translations/default/AdminShopparametersHelp.xlf
  translations/default/AdminShopparametersNotification.xlf
  translations/default/Install.xlf
  translations/default/ShopFormsHelp.xlf
Labels: Improvement, 9.0.x

#38765 Preliminary steps for RC
  composer.lock
  install-dev/data/xml/hook.xml
  src/PrestaShopBundle/Command/UpdateLicensesCommand.php
  src/PrestaShopBundle/EventListener/API/Context/CurrencyContextListener.php
Labels: Improvement, 9.0.x

#38767 Fix image type entity
  install-dev/data/db_structure.sql
  src/PrestaShopBundle/Entity/ImageType.php
Labels: Improvement, QA ✔️, 9.0.x

#38783 Update API module and improve CQRS not found filtering in API
  .github/workflows/api-module.yml
  .github/workflows/integration.yml
  .github/workflows/php.yml
  composer.lock
  src/PrestaShopBundle/ApiPlatform/Metadata/Resource/Factory/CQRSNotFoundMetadataCollectionFactoryDecorator.php
  src/PrestaShopBundle/ApiPlatform/Scopes/ApiResourceScopesExtractor.php
  tests/Integration/ApiPlatform/DisabledEndpointsTest.php
  tests/Resources/ApiPlatform/Resources/ApiTest.php
Labels: Improvement, 9.0.x

#38789 Functional Tests : API : `PATCH /product/{productId}`
  tests/UI/campaigns/functional/API/02_endpoints/09_product/04_patchProductId.ts
Labels: QA ✔️, TE, E2E Tests

#38761 Refactor Warehouse::getProductLocation()
  classes/stock/Warehouse.php
Labels: QA ✔️, Refactoring, 8.2.x
